### ISSUE TITLE
CoreDNS 011 release tracking bug

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1012]
/cc @johnbelamaric @nwoods3 @chrisohaver 

CoreDNS 1.0.0 tracking bug. All 1.0.0 milestone issues have been a) solved b) pushed to post 1.0.0.

IOW: we are ready to move to semver and release a 1.0.0

**Comment by miekg** [comment]
work-in-progress release notes: https://github.com/coredns/coredns/wiki/CoreDNS-1.0.0-Release

**Comment by miekg** [comment]
Note: we introduce backwards incompatible changes with this release. Further release follow semver for new/deprecated things.

**Comment by fturib** [comment]
@miekg : are we confident enough on the test after the refactoring. I am thinking of the 2 new middleware "autopath" and "federation" ?

**Comment by miekg** [comment]
Bluntly: no. These only have a bit of unit tests and I haven't done any
integration tests from within a cluster, nor have we a setup for this.

Otoh: 1.0.0 is just a number. But, better testing would be welcome even if
it is just manual atm.

**Comment by strigazi** [comment]
Can you add that #823 is fixed in the release notes? Kubernetes users are hit by it, would be helpful for them.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS 1.0.0..." ]
>Can you add that #823 is fixed in the release notes? Kubernetes users are hit by it, would be helpful for them.

Feel free to update the draft release notes at
https://github.com/coredns/coredns/wiki/CoreDNS-1.0.0-Release


/Miek

--
Miek Gieben

**Comment by yongtang** [comment]
HA of kubernetes api endpoints might be added to the release note as well.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS 1.0.0..." ]
>HA of kubernetes api endpoints might be added to the release note as well.

please add!

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
We (CoreDNS maintainers) feel it's better to do a 011 release, before going to 1.0.0. So we'll release a 011 soon and go for the full 1.0.0.

**Comment by miekg** [comment]
011 released: https://coredns.io/2017/09/10/coredns-011-release/
