### ISSUE TITLE
[Question]: Grafana Dashboard

### ISSUE THREAD

**Issue by prologic** [coredns/coredns#1021]
Does anyone have a working Grafana Dashbaord for CoreDNS metrics using Prometheus as a data source?

**Comment by miekg** [comment]
Yes, I have one, could give you the json. It's not very good - mainly just sum(rate) of stuff, but might provide a good starting point.

**Comment by prologic** [comment]
Please :D


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by miekg** [comment]
[CoreDNS-1504553895435.json.txt](https://github.com/coredns/coredns/files/1275415/CoreDNS-1504553895435.json.txt)

**Comment by prologic** [comment]
Thank you! I [improved it slightly](https://gist.github.com/prologic/f28ab2d5f9567646e9fdfcdcf19d8e97) to make the `$Instance` selection dynamic (*I run 3 coredns instances locally on my network*).

Amazingly I do about ~500-600 kpps wut?! Is this normal for a home network with some dozen devices, cputers and a few servers? :)

**Comment by prologic** [comment]
I also proxy everything else out via google's public dns servers; so I'll add in respective Response and Response duration graphs for all proxy metrics and post an updated version.

**Comment by miekg** [comment]
500-600 Kqps? For your home network - no way!

**Comment by prologic** [comment]
Published to https://grafana.com/dashboards/5926

**Comment by miekg** [comment]
Spotted small typo: A Dashbaord for the CoreDNS dns 

Dashboard and prolly: dns -> DNS.

**Comment by prologic** [comment]
Fixed! Not sure what else to document really; because besides you and me I'm not sure who else uses/wants this dashboard :)

**Comment by pawelprazak** [comment]
FYI @prologic there was a metric rename:
- `coredns_dns_request_duration_milliseconds_bucket` -> `coredns_dns_request_duration_seconds_bucket`

**Comment by Sherlock-Holo** [comment]
After enable prometheus in corefile, I add prometheus data source into grafana and then import json file, but it report

```
{
    "err": {
        "data": null,
        "status": -1,
        "config": {
            "method": "GET",
            "transformRequest": [
                null
            ],
            "transformResponse": [
                null
            ],
            "jsonpCallbackParam": "callback",
            "silent": true,
            "url": "http://10.20.30.15:9253/metrics/api/v1/series?match[]=up%7Bjob%3D%22coredns%22%7D&start=1557808201&end=1557819001",
            "retry": 0,
            "headers": {
                "Accept": "application/json, text/plain, */*"
            }
        },
        "statusText": "",
        "xhrStatus": "error"
    },
    "cancelled": true
}
```

What can I do to fix it

**Comment by Dentrax** [comment]
> besides you and me I'm not sure who else uses/wants this dashboard :)

`Downloads: 337,965` :)

Just curious if the dashboard is up-to-date since `Last update: 2018-05-05T19:15:28` quite old.
