### ISSUE TITLE
mw/kubernetes: stubdomains?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1028]
See https://github.com/kubernetes/dns/issues/83#issuecomment-327601788

See stubzones option in *etcd* middleware. Don't think we have this in the kubernetes middleware?

**Comment by chrisohaver** [comment]
If I understand correctly, this can be done with proxy middleware.

**Comment by miekg** [comment]
That's a good call. Think you're right.

**Comment by miekg** [comment]
Means this could potentially also removed from the etcd middleware at some point.

Yeah for middleware!

**Comment by miekg** [comment]
ah, the only different is that the config *lives* in etcd, meaning it is easy to update. Which is an option we don't have in the *proxy* middleware - asking the proxy middleware to ask *etcd* won't fly in this case as the etcd middleware already used the proxy middleware leading to a circular dep.

**Comment by miekg** [comment]
OTOH configuring this in the config means it is pretty static in the k8s case, which makes `stubzones` in etcd slightly different...

**Comment by chrisohaver** [comment]
I meant to say that the kube-dns stubdomains functionality can be replicated using proxy middleware.

**Comment by johnbelamaric** [comment]
Yes, kube-dns stub domains are managed via a ConfigMap - the same way we manage the Corefile.
