### ISSUE TITLE
Middleware/Federation: Question section mismatch

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1031]
After PR #1029, getting a "Question section mismatch" error when making a query of a federated service.

```
dnstools# host -v -t a svc-1-a.test-1.prod.svc.cluster.local.
Trying "svc-1-a.test-1.prod.svc.cluster.local"
;; Question section mismatch: got svc-1-a.test-1.svc.cluster.local/A/IN
```

Configuration:

```
    .:53 {
      health
      errors
      log
      kubernetes cluster.local {
        pods verified
      }
      federation cluster.local {
        prod prod.feddomain.com
      }
    }
```

**Comment by miekg** [comment]
what's the rcode of the response?

**Comment by chrisohaver** [comment]
`host -v` and `dig` do not show the response when the name mismatch is detected. I could not find an option in `dig` to show the response in this type of case.

**Comment by chrisohaver** [comment]
Fixed by #1033

**Comment by tmm1** [comment]
> `host -v` and `dig` do not show the response when the name mismatch is detected. I could not find an option in `dig` to show the response in this type of case.

This is rather frustrating. Did you find any dns clients that will let you see the actual response?

**Comment by chrisohaver** [comment]
No i did not.  You should be able to use a packet sniffer (tcpdump/wireshark).
