### ISSUE TITLE
middleware/federation: kube-dns/coredns difference

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1034]
According to:
https://kubernetes.io/docs/tasks/federation/federation-service-discovery/

For queries of services in the local cluster, the response contains two records, a CNAME and an A record.  e.g. 

```
svc-1-a.test-1.prod.svc.cluster.local. 5 IN CNAME	svc-1-a.test-1.svc.cluster.local.
svc-1-a.test-1.svc.cluster.local. 5 IN A	10.0.0.100

```

Whereas coredns returns a single record. e.g. ...

```
svc-1-a.test-1.prod.svc.cluster.local. 5 IN A	10.0.0.100
```

I don't think this difference would confuse any clients.  But it technically there is a difference. coredns treats all federated names of local services as `A` records, giving two `A` records to each service local to the cluster. The kube-dns behavior is more consistent, treating all federated names as `CNAME`s (either pointing to a local `A` record as in the example above, or to a `CNAME` chain upstream for non-local services)

Should the kube-dns behavior be replicated?  Or is this difference innocuous.

**Comment by miekg** [comment]
Should be relative simple to mimic kube-dns here?
