### ISSUE TITLE
rename "middleware" to "plugins" and naming things

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1040]
The caddy nomenclature for "middleware" is plugins, i.e. `coredns -plugins` lists all the middleware. This is a bit confusing. I think we should rename middleware to plugins (and make changes to source as well to reflect this).

Speaking of naming things, I myself, don't consistently name thing in a corefile. I.e. stanza, directive and zone-stanza.

This is a blog https://coredns.io/2017/06/08/how-queries-are-processed-in-coredns/ that also defines a bunch of things.

**Comment by miekg** [comment]
Anyone against this?

**Comment by stp-ip** [comment]
Sounds good.

**Comment by miekg** [comment]
Website has been updated to *not* use the name middleware anymore. There might still be some dead links, but I'll wrap those up when I encounter them.

**Comment by miekg** [comment]
Closed via https://github.com/coredns/coredns/commit/d8714e64e400ef873c2adc4d929a07d7890727b9
coredns.io has already been updated.
