### ISSUE TITLE
middleware/bind: rename

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1044]
Filing bugs from: https://gist.github.com/jpmens/c3f593c81e630b4a616c6205a97fd7a4 because it is good feedback.

Should we rename `bind` to `listen`? BIND is the most famous nameserver, so it has a diff. connotation in this setting. However I think it is more important to keep in sync w/ caddy where this is also called `bind`

It also is a backwards incompatible change.

cc @jpmens

**Comment by jpmens** [comment]
Instead of renaming: add "listen" as an alias and use that in the docs?  #justsayin

**Comment by miekg** [comment]
But isn't the system call also actually called `bind`?

What did you actually expected this to do? Or couldn't you find how to bind to an address? (i.e. looking for listen?)

**Comment by jpmens** [comment]
I wrote:

> bind middleware reminded me of Bind9. Maybe rename to listen? (I'd normally not mention this b/c "bind" is a perfectly normal term for the operation, but in a DNS context BIND wins I think :-)
