### ISSUE TITLE
mw/host: separate reverse config?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1048]
https://gist.github.com/jpmens/c3f593c81e630b4a616c6205a97fd7a4

> hosts middleware needs separate config for PTR; this could be improved upon by automating forward/reverse

/cc @pmoroney

**Comment by pmoroney** [comment]
I am not sure what this issue actually is, what would the PTR config do? The plugin automatically creates PTR answers based on what is in the hosts file. Do we need to filter those responses, or modify them in some way?
