### ISSUE TITLE
mw/alias: non-standard behavior?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1051]
from: https://gist.github.com/jpmens/c3f593c81e630b4a616c6205a97fd7a4

> alias middleware should behave like Habbie's ALIAS and be included

/cc @serverwentdown

**Comment by serverwentdown** [comment]
to resolve this we should implement ANAME in accordance with the [draft RFC](https://tools.ietf.org/html/draft-ietf-dnsop-aname-00) but i'm not sure if your DNS library supports custom record types?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] mw/alias: non..." ]
>to resolve this we should implement ANAME in accordance with the [draft RFC](https://tools.ietf.org/html/draft-ietf-dnsop-aname-00) but i'm not sure if your DNS library supports custom record types?

Generic records are supported. But we can also just add ANAME?

**Comment by miekg** [comment]
Closing here, as this a an external plugin. Patches for miekg/dns and coredns welcome though.
