### ISSUE TITLE
Recommended changes from CII badge

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1063]
While filling out https://bestpractices.coreinfrastructure.org/projects/1250 to get the CII badge, there were several suggestions we should implement:

* Switch to SemVer
* ~~Document a separate process for vulnerabilities reporting that allows private reporting~~ #1136
* Increase coverage of unit tests and/or figure out away to get a coverage number from the integration tests.
* ~~Document the policy on creation of new tests with new code.~~ already in CONTRIBUTING.md
* ~~Integrate the warnings/lint/vet analysis into the CI.~~
* ~~Integrate dynamic analysis tools (e.g., `gofuzz`) into the build and/or release process.~~ See #1118

**Comment by johnbelamaric** [comment]
I added https://sideci.com which does go vet and lint in the CI (separate from Travis). Let's see if we like it.

**Comment by johnbelamaric** [comment]
I disabled SideCI because it was pointed out to me that it requests far more privileges than seem necessary for the function it provides.

**Comment by miekg** [comment]
* [soon to be done] Switch to SemVer, will be done with our 1.0.0 release
* [needs owner] Document a separate process for vulnerabilities reporting that allows private reporting
* [yeah] Increase coverage of unit tests and/or figure out away to get a coverage number from the integration tests.
* [need owner, and where do we document this] Document the policy on creation of new tests with new code.

**Comment by miekg** [comment]
apart from semver and getting tests coverage higher (which is already high but because of the layout we use the tests in tests/ don't get counted).

I think this can be closed?
