### ISSUE TITLE
mw/auto support for include not available from mw/file

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#1066]
Am I right to assume that $INCLUDE is only available with the file mw and not with the auto one?

**Comment by miekg** [comment]
no. It's actually implemented in go-dns, https://github.com/miekg/dns/blob/master/scan.go#L139

**Comment by stp-ip** [comment]
Thanks for the code pointer. Will try to debug, why it didn't like my usage of it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] mw/auto suppo..." ]
>Thanks for the code pointer. Will try to debug, why it didn't like my usage of it.

Code had a bug, see latest commit to that part of the library

**Comment by stp-ip** [comment]
Thanks. Looking into the code already. Still having some issues with relative vs absolute paths and syntax errors and open file errors in general. Will see, if that's all me.
