### ISSUE TITLE
mw/file|path $INCLUDE is not relative to mw/root set directory

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#1068]
It seems like the working/excution directory from coredns is used and not something set in the root mw.

Corefile:
```
  .:5053 {
    root /zones/
    auto {
      directory . (.*)
      transfer *
    }
    errors stdout
    log stdout
  }
```

Main zone (example.com):
```
@                   3600 IN SOA     ns.example.com. domains.example.com. (
                                      2017091317   ; serial
                                      15m          ; refresh
                                      5m           ; retry
                                      1w           ; expire
                                      12h    )     ; minimum

@                  86400 IN NS     ns.example.com

test IN A 127.0.0.1

; works
$INCLUDE /zones/test.example.com test

; doesn't work
$INCLUDE test.example.com test
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] mw/file|path $INC..." ]
>It seems like the working/excution directory from coredns is used and not something set in the root mw.
>
>Corefile:
>```
>  .:5053 {
>    root /zones/
>    auto {
>      directory . (.*)
>      transfer *
>    }
>    errors stdout
>    log stdout
>  }
>```
>
>Main zone (example.com):
>```
>@                   3600 IN SOA     ns.example.com. domains.example.com. (
>                                      2017091317   ; serial
>                                      15m          ; refresh
>                                      5m           ; retry
>                                      1w           ; expire
>                                      12h    )     ; minimum
>
>@                  86400 IN NS     ns.example.com
>
>test IN A 127.0.0.1
>
>; works
>$INCLUDE /zones/test.example.com test
>
>; doesn't work
>$INCLUDE test.example.com test
>```

That is perfecly possible. Note sure if coredns bug or go-dns bug (or feature 
request there).

**Comment by miekg** [comment]
so $INCLUDE should be local to where to zonefile resides, this does not seem the case here? (Haven't repro-ed myself, yet)

**Comment by stp-ip** [comment]
It does not seem to be the case and yes I assumed with using root it should be local to where the root was set. Actually I first assumed it's relative to the actual read zonefile, but that's not the case either.

So seems like: relative to execution dir, not zonefile or root dir
Assumption one using root: relative to root dir
First assumption in general: relative to the read zonefile (maybe even with the prevention of going up the directory tree)

**Comment by miekg** [comment]
local to the CWD is wrong, I'll check for a test in go-dns (should be fixed there)

**Comment by miekg** [comment]
Confirmed.

~~~
package main

import (
	"fmt"
	"os"

	"github.com/miekg/dns"
)

func main() {
	zone := "/tmp/db.miek.nl"
	f, _ := os.Open(zone)
	tok := dns.ParseZone(f, "", "")
	for x := range tok {
		fmt.Printf("%s\n", x.RR)
	}
}
~~~
With this zone:
~~~
@       IN      SOA     linode.atoom.net. miek.miek.nl. (
			     1282630059 ; Serial
                             4H         ; Refresh
                             1H         ; Retry
                             7D         ; Expire
                             4H )       ; Negative Cache TTL

a		IN 	A       176.58.119.54
$INCLUDE ../home/miek/include-miek.nl
~~~
running dir where the zone is placed:
~~~
% go run scan.go
.	3600	IN	SOA	linode.atoom.net. miek.miek.nl. 1282630059 14400 3600 604800 14400
a.	3600	IN	A	176.58.119.54
miek.nl.	3600	IN	A	127.0.0.53
~~~
Running one dir deeper
~~~
% cd a
% go run ../scan.go
.	3600	IN	SOA	linode.atoom.net. miek.miek.nl. 1282630059 14400 3600 604800 14400
a.	3600	IN	A	176.58.119.54
%!s(<nil>)
~~~

**Comment by miekg** [comment]
This proofs somewhat tricky to fix though

**Comment by miekg** [comment]
opened: https://github.com/miekg/dns/issues/537
