### ISSUE TITLE
mw/file|path allowing $INCLUDE might be seen as security issue

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#1069]
Having $INCLUDE be available and not be restricted to the root mw defined directory might lead to users reading information they shouldn't read and also serve these records.
Not huge similar to allowing AXFR without whitelisting, but still something to consider.

Either we could contain the $INCLUDE possibility to the directory defined with the root mw or we should add a method to disable I would say.

**Comment by miekg** [comment]
$INCLUDEs can never be in an AXFR, so this can't be an issue there.

**Comment by stp-ip** [comment]
But it does replace it's content.

Corefile:
```
  com.:5053 {
    root /src/com/
    auto {
      directory . (.*)
      transfer to *
    }
  }
  net.:5053 {
    root /src/net/
    auto {
      directory . (.*)
      transfer to *
    }
  }
```
example.com zone:
```
@                   3600 IN SOA     ns.example.com. domains.example.com. (
                                      2017091321   ; serial
                                      15m          ; refresh
                                      5m           ; retry
                                      1w           ; expire
                                      12h    )     ; minimum

@                  86400 IN NS      raw.example.com.

$INCLUDE /src/com/private.example.net rogue-include
```

Now doing a AXFR to rogue-include.example.com will show the whole zone data. 
Sure not that DNS is private anyway, but thought I mention it to at least have it on the radar.

**Comment by miekg** [comment]
Yes :-) It will do what you ask it to do. This is how $INCLUDE is defined, so this is not a DNS, or CoreDNS issue.

**Comment by stp-ip** [comment]
Yes this is what I expected, I was just saying that for multi-tenancy it might be a good feature to either have it relative to the zone-file and disallow access to the parent directories or that it might make sense to disable that feature.

Isn't a huge issue, but better have it on the radar, while there seems to be something going on with this code section anyway ;)

Thanks for taking the time to dig through my issues.

**Comment by stp-ip** [comment]
Can I assume this is closed as won't fix or might that actually be something folded into #1068 aka disallowing parent directory INCLUDEs.

**Comment by miekg** [comment]
there is no security issue, nor something to fix.

**Comment by stp-ip** [comment]
I disagree with that notion concerning multi tenant systems.

**Comment by miekg** [comment]
sorry to be sparse - not enough time, RFC 1035 has the $INCLUDE definition; that is the standard we need to adhere to.

**Comment by stp-ip** [comment]
Open for a PR disabling INCLUDE for file/auto, if that's easily possible?
Or open for a PR to disallow the INCLUDE for parent directories?
Wasn't suggesting you should be doing it, just that it might be a good addition.

**Comment by miekg** [comment]
> Open for a PR disabling INCLUDE for file/auto, if that's easily possible?

that would have to be a PR against go-dns, which could be done, but I'm not sure if we can pull that off in a backwards compat matter - it also goes against the standard, so YMMV :-)

But remind again, how do you get zone with $INCLUDE - you let user upload those? Or from git?

**Comment by stp-ip** [comment]
Yeah git is one possibility. So probably needs to be done by an intermediate layer to prevent any INCLUDE being pushed to coredns then.

**Comment by miekg** [comment]
yeah, not a perfect solution, but the check is pretty trivial

**Comment by miekg** [comment]
So we were thinking about this a time back: https://github.com/coredns/coredns/issues/236, but didn't implement it. Even if we have this would not have supported it, unless we add it to Go DNS as well
