### ISSUE TITLE
Classless reverse DNS handling

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1074]
Currently, you can specify a reverse zone in the Corefile with the CIDR notation (e.g., 10.0.0.0/8). However, if the network is not on a classful boundary, it is silently ignored.

In the K8s use cases in particular, we would like to be able to serve PTR records for the address space that K8s manages, but proxy other PTR requests upstream. This is how the `cidrs` feature worked in the past, before we added the CIDR notation for zones.

I think that if there is a classless zone defined, we could automatically round it to the containing classful boundary. We could retain the original CIDR though, and in the middleware we can test if the request falls outside that original CIDR. If so, we `fallthrough`. This could be automatic or it could be an option we set on a given middleware (e.g., `ptr_fallthrough` or something).

If multiple reverse zone CIDRs are listed in the ZONES, then we should find the minimal set of containing classful zones and adjust to those, storing away all the specific CIDRs.

The end logic of doing the PTR fall through would need to be implemented in each middleware, but most of this should be able to be done in a pkg to make it easy to implement per middleware.

**Comment by miekg** [comment]
We could extend to allow non /8*n multiples and then teach plugin.Matches to check for the correct cidr range? All middl^W plugins already call this, so this would then magically work...?

**Comment by miekg** [comment]
hmmm, but then the query routing won't work, because it still needs to have an octet boundary.

**Comment by miekg** [comment]
I think your plan can work (on second thought)

**Comment by miekg** [comment]
wouldn't this work with fallthrough btw? IOW: a test that fails would be nice.

**Comment by johnbelamaric** [comment]
Yeah, I suppose regular fall through would work for it. But you might not want to fallthrough on all stuff.  The scheme described would help limit the scope of issues like https://github.com/kubernetes/dns/issues/124 (although we need a better solution to that).

**Comment by johnbelamaric** [comment]
@chrisohaver @rajansandeep ordinary `fallthrough` should work with PTR. Maybe we should configure that in our default K8s manifest?

It could have unintended consequences though, like cluster.local requests for non-existent things getting proxied out. Which I am guessing would mean an NXDOMAIN from the recursive resolver we hit without it even doing much work.

**Comment by chrisohaver** [comment]
Probably not best to fallthrough on everything, just to handle the PTR case.
Consider when autopath is not enabled... many queries would fallthrough to proxy.

fallthrough should probably either be implcit for PTRs (sane default) ...
or as @johnbelamaric said, a special `ptr_fallthrough` added.

**Comment by miekg** [comment]
I don't see why forward fallthrough is different than reverse fallthrough

**Comment by johnbelamaric** [comment]
The only real difference in my mind is that do to the classful limitation, a plugin may have to declare itself as authoritative on a wider address space than it actually is. For k8s at least that will be very common. So it would seem more likely to need to fall through for reverse.

**Comment by chrisohaver** [comment]
The mechanism of fall through is the same, however the condition of when we want to fall through is different. We want to be able to fall through on PTR requests, without falling through on other requests.  So `fallthrough` would still mean "fall through for all query types", but `ptr_fallthrough` would mean "fall through for PTR queries only"

**Comment by chrisohaver** [comment]
`ptr_fallthrough` would actually mean "only fall through for PTR queries that are _not_ in the classless cidr"  
We don't want to fall though on `NXDOMAIN` results that fall _within_ the classless cidr.

**Comment by miekg** [comment]
Think the best way to handle this is in core and generalize the /N handling there, i.e. if a name fall under in-addr.arpa or ip6.arpa check if the plugin is willing to handle the request.

This needs to be pretty performant code cause we will have to do those checks on every query.

**Comment by miekg** [comment]
Who's picking this up?

**Comment by chrisohaver** [comment]
> Think the best way to handle this is in core and generalize the /N handling there, i.e. if a name fall under in-addr.arpa or ip6.arpa check if the plugin is willing to handle the request.
> This needs to be pretty performant code cause we will have to do those checks on every query.

@miekg, Can you describe this in more detail so someone can pick it up and do it the way you prefer?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Classless rev..." ]
>> Think the best way to handle this is in core and generalize the /N handling there, i.e. if a name fall under in-addr.arpa or ip6.arpa check if the plugin is willing to handle the request.
>> This needs to be pretty performant code cause we will have to do those checks on every query.
>
>@miekg, Can you describe this in more detail so someone can pick it up and do it the way you prefer?

I don't have a design for this. Requirement: don't be slow; meaning no (or very 
little allocations). So you find the handler for the current name, check if it's 
a reverse and want this name as well, if not continue.

**Comment by chrisohaver** [comment]
I can take this when i'm finished with the integration test refactoring, unless someone else wants to take it.

**Comment by miekg** [comment]
Ack.

Might be worth having a benchmark function.

**Comment by chrisohaver** [comment]
The integration stuff is taking longer than expected. Someone else should take this if we want it fixed soon.

**Comment by miekg** [comment]
I can probably take a look

**Comment by miekg** [comment]
Some thoughts:
* this is only needed for v4
* most zones don't care and will serve the full /{8,16,24}

We can detect this while loading the config and just setting a boolean for that zone. In core's `ServeDNS` we *only* check if this boolean is set (thus fast in the normal path) and then do whatever slower code we had for this in *kubernetes*.

**Comment by miekg** [comment]
`plugin/normalize.go`'s `SplitHostPort(s string) (host, port string, err error)` prolly needs extending and return the cidr as an int, so we can pick that up while we parse the config

**Comment by miekg** [comment]
Just thinking aloud here. If you have a /25 I make you serve a /24 and check if you fall in the range... 
So:
* 24+ --> /24
* 16+ --> /16 
* 8+ --> /8

**Comment by miekg** [comment]
#1159 is nearing completion. "Just" tests and enabling it fully.
