### ISSUE TITLE
Versioning scheme caused funny bug

### ISSUE THREAD

**Issue by jhrv** [coredns/coredns#1082]
We are using Ansible to setup our kubernetes environment, including CoreDNS. 
During setup we are generating the Deployment-yaml for CoreDNS, and here we inject the version from a separate inventory file.

This is where we encountered a funny bug. Since Ansible is based on Python, and it in some version has the convention that numbers prefixed with zero means that the following numbers are to be interpreted as octadecimal, the version 010 resolves to 8. 011 resolves to 9 and so forth.
This is solved by simply adding quotes, but can cause quite a bit of confusion when first encountered. 

Just letting you know.

Cheers!

**Comment by johnbelamaric** [comment]
Thanks! We will be moving to [SemVer](http://semver.org) in the next release (1.0.0).

**Comment by jhrv** [comment]
That should do it! 👍
