### ISSUE TITLE
plugin/kubernetes: Update to use protobuf K8s client

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1094]
Per https://github.com/kubernetes/community/pull/1100#issuecomment-330860057

**Comment by miekg** [comment]
added for 1.0.0

**Comment by chrisohaver** [comment]
I'll look into this one.

**Comment by aledbf** [comment]
@johnbelamaric @chrisohaver  this can help https://github.com/kubernetes/ingress/blob/master/core/pkg/ingress/controller/launch.go#L281

**Comment by chrisohaver** [comment]
merged #1114
