### ISSUE TITLE
Subscription plugin

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1100]
In some cases, a client may want to subscribe to updates for a particular name, in a manner similar to a _watch_ in etcd or consul.

We can implement a subscription plugin that uses the gRPC server and extends the API to allow clients to subscribe to a query. Upon receiving the request, it will call down into the chain and get the response, returning it to the client but also keeping track of the records for that query. It will provide a channel (or function call) that *other* plugins will call whenever their state changes. For example, if `auto` reloads a file, and the `subscription` (or `push`?) plugin is enabled,  it will call a function to indicate that "something in this zone may have change". The subscription plugin will then re-query the records for any subscriptions to records in that zone, compare to the current state, and push down the changes to the subscribers.

It's not the most efficient way, but in this simple implementation we have the bulk of the logic in the new middleware, and avoid other plugins having to do much work.

**Comment by miekg** [comment]
At least in etcd this is called a Watch; but that doesn't do the diff. It send you "some changed" and an index. For simplicity this could be a first iteration; don't send anything back, just something has changed and let the client requery.

**Comment by zhujinghui** [comment]
Actually, etcd will send client  not only index, but also the current and previous data, see doc here https://coreos.com/etcd/docs/latest/v2/api.html#waiting-for-a-change

etcd2 implement watch by long polling (etcd 2 using HTTP/1.1). And etcd3 implement watch by gRPC stream (which may leverage on HTTP/2 server push, I am not sure), see https://coreos.com/etcd/docs/latest/learning/api.html#watch-streams

In either case, server side will send client side updated data, client does not need requery.

**Comment by johnbelamaric** [comment]
Yeah. I have a very crude not-working-yet start on this plugin on my laptop that I haven't pushed yet. It's basically etcd-like functionality using a grpc stream. Users connect and create that watch, then the watch plugin informs each supported plugin that there is a watch on some particular name and gives them a channel to tickle if they have a relevant change.

If we implement this, then etcd plugin would be notified when a user creates a watch, so it could in fact employ its own watch on the same name. Right now I am just doing a k8s implementation, which will basically notify the watch plugin if anything changes in k8s. First cut won't be selective but eventually it will get better.

**Comment by zhujinghui** [comment]
Another challenge to implement watch in coredns is: coredns is a dns server, and data may is fetching from backend (like database, etc). If client want to watch a records which is stored in other backends (say mySQL, which not support watch), then coredns need to frequently poll mySQL server to see if the data was updated. When we have a large number of wach client, poll is a terrible idea. If the backend itself support watch(eg. Etcd), then implementation becomes simple: client watch coredns, coredns then watch etcd; etcd inform coredns, and coredns then inform client.

**Comment by johnbelamaric** [comment]
Yep. It's a bit sketchy in some plugins. The mitigation is that the "watch" doesn't need to be super-accurate. You don't *have* to poll for each watch client. For example, with K8s, there will be just the same watches there always have been (services, endpoints, pods if so configured).
