### ISSUE TITLE
incubation for new plugins?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1102]
Each new plugin increases the maintainers load. We should be relative conservative when adding new ones in the coredns/coredns repository.

I propose we (reuse) the incubator (or make up a diff. name) for new plugins and that it lives out of tree, like for instance the *import* plugin: https://coredns.io/explugins/import/
(out of tree, but enabled by default). For coredns maintainers  I see no problem of making new repos in the coredns github org.

This also gives it a clear owner in the early stages.

**Comment by johnbelamaric** [comment]
This sounds like a good idea.

**Comment by miekg** [comment]
Then this is now the new law :)
