### ISSUE TITLE
plugin/etcd: drop upstream

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1103]
*etcd* and *file* have an `upsteam` directive that allows them to resolve external CNAMEs. At the time we couldn't not call into the proxy middleware to make this work, hence the extra directive.

I would be more natural that when you have a proxy statement, the other plugins would just use that, and "call into" the proxy plugin (see *federation* and *autopath* for an example*). This gives other benefits as you would use whatever proxy uses: `https_google`, the `except`s, etc.

Also makes the config simpler and removes this (in essence) special case.

**Comment by johnbelamaric** [comment]
This doesn't though work if the CNAME should come from another plugin. For example:

* `file` handles example.com
* `kubernetes` handles cluster.local
* example.com has CNAME `k8s.example.com` to `kubernetes.default.svc.cluster.local`

In this case, we need to resolved the CNAME with another middleware, not the upstream proxy.

**Comment by miekg** [comment]
noted. Good point.

**Comment by johnbelamaric** [comment]
We could re-enter the query routing either automatically or if you specify something like "@self" for the upstream. If we do that maybe we can detect loops.
