### ISSUE TITLE
plugin/proxy: can we be faster

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1117]
From recent Slack discussion.
See https://github.com/felipejfc/udpx/blob/master/proxy/proxy.go#L124 for super fast udp proxy. Open udp/tcp socket, use channel to forward request on that channel

Implement the same in CoreDNS?

**Comment by miekg** [comment]
OK so the gist of that thing is 1 udp socket to upstream and then a map index by sourceIP/port that returns the original incoming udp sock. You then wait for a reply, lookup the sock and write to the correct client. This can probably work for the other proxy transports as well (tcp, udp, grpc).

Problem might be the EDNS0 bufsize setting although that could be done some easily (I think).

**Comment by miekg** [comment]
If this is really faster, it will be (another?) killer feature for k8s.

**Comment by miekg** [comment]
the model is quite different from the current *proxy* plugin. Think best way to test this is to create a new one. *fastproxy* or something. Also interesting to see if this model can be extended to our other protocol as well and TCP.

**Comment by johnbelamaric** [comment]
We are finding that gRPC unary RPC doesn't perform very well (at least not by DNS QPS standards). 8 packets exchanged for each query. We are looking at implementing gRPC streaming with some batching. Should help with that.

**Comment by johnbelamaric** [comment]
We are finding that gRPC unary RPC doesn't perform very well (at least not by DNS QPS standards). 8 packets exchanged for each query. We are looking at implementing gRPC streaming with some batching. Should help with that.

**Comment by johnbelamaric** [comment]
Too easy too hit the wrong buttons doing this on my phone...

**Comment by miekg** [comment]
8?! Wow.

Also not sure if we really need to whole policy complexity in the healthchecking - feel we can get away with something simpler.

**Comment by miekg** [comment]
Or if we care about encryption, just encrypt the payload over UDP. Shared secret between two coredns endpoints.

**Comment by miekg** [comment]
We should also not to afraid to rip stuff out (i.e. gRPC) if it is just too slow.

Coming back to this specific issue, the code in question is MIT and can just be copied into a new proxy plugin (can even be external :) ).  Plan for this; bare bones udp/tcp proxy with some healthchecking (also simplified)

Some things I don't understand, this line should be a Dial: https://github.com/felipejfc/udpx/blob/master/proxy/proxy.go#L146 

If this WIP works, we can open a discussion on what to do with both proxy implementations.

**Comment by miekg** [comment]
Ok, i've cleaned up my branch and I'm doing some `@localhost` testing. Because we do *more* than just proxying we pay a performance hit, but still still looks to be faster.

I'm using this Corefile and flip between the two proxies (this proxy runs on port 1052):
~~~
. {
    #proxy . 127.0.0.1:1053
    forward . 127.0.0.1:1053
}
~~~
Then I have a CoreDNS running on port 1053 that serves `miek.nl`. Using the query-perf stuff from perf-tests repo.
Getting qps from CoreDNS running on port 1053:
~~~
$ make TIME=2 PORT=1052 queryperf
Queries per second:   25332.289759 qps
~~~
Roughly 25K qps (small VPS with minute CPUs).

Using the proxy: `Queries per second:   6714.696676 qps`
Using the forwarder: `Queries per second:   10346.844998 qps`

Note these qps have quite some variance (took the highest values) here, so this is 50% faster (roughly). I think this worth following up, as this could potentially safe 40 to 50% of your kube-dns instances.

**Comment by miekg** [comment]
There is an issue in going to the next upstream if a query fails:

Current handler looks like this:
~~~
func (f Forward) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) (int, error) {

	f.proxies[0].clientChan <- request.Request{W: w, Req: r}

	return 0, nil
}
~~~
This delves then into the async stuff the deals with upstream and writes the packet. But I have no way of knowing if it succeeds. I can write back from a channel in `proxies[0]` with an error, but there is no guarantee that that has any relation to the request I just send down the channel.

We could check if an upstream is down and then select a good upstream, but this does mean there is no retry when forwarding (not sure if people expect that).

Unless someone has a bright idea on how to signal back.

**Comment by miekg** [comment]
Added as an external middleware: https://coredns.io/explugins/forward/ (for now)
