### ISSUE TITLE
plugins: fix generating code for disabled plugins

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [coredns/coredns#1119]
The issue: for example if we want disable kubernetes plugin for standalone CoreDNS binary kubernetes code is included to the binary anyway.

ATM coredns/core/ contains two files: coredns.go and zplugin.go where last one is generating with 'go generate' in accordance to plugin.cfg data. But coredns.go contains own imports and this caused generate code for disabled in plugin.cfg plugins.

Would be useful to use one file instead two (zplugin.go) and improve directives_generate.go to add import 'github.com/coredns/coredns/core/dnsserver' to zplugin.go so if we don't use 'go generate' CoreDNS is built with 'default' plugin list otherwise with list defined in plugin.cfg.

Alternate way - use two files but leave in coredns.go only 'github.com/coredns/coredns/core/dnsserver' import.

**Comment by miekg** [comment]
make sense to generate coredns.go as well.

**Comment by miekg** [comment]
@UladzimirTrehubenka think this PR fixes this?
