### ISSUE TITLE
plugin/secondary: test suddenly fail

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1124]
For unknown reason this test suddenly fails

~~~
=== RUN   TestTransferIn
--- FAIL: TestTransferIn (0.00s)
	secondary_test.go:138: unable to run TransferIn: read udp 127.0.0.1:43671->127.0.0.1:43682: read: connection refused
=== RUN   TestIsNotify
~~~

**Comment by johnbelamaric** [comment]
This test passes if I rollback to https://github.com/miekg/dns/commit/032fbabc82455d0649e332bdf83767f134fc9431

**Comment by miekg** [comment]
ah nice find! (of course!) @fastest963

**Comment by miekg** [comment]
Inclined to rollback, but I can wait for a bit :)

**Comment by miekg** [comment]
Fixed with https://github.com/miekg/dns/pull/526 (hopefully)
