### ISSUE TITLE
/etc/hosts not being honored by CoreDNS backend

### ISSUE THREAD

**Issue by itsmaverick** [coredns/coredns#1125]
Here is the issue. I have a new image with top of the branch changes. Added an entry to /etc/hosts (registry.local to /etc/hosts). Tested nslookup or dig on the entry and it did not get resolved. It looks like /etc/hosts is not being honored or I am doing something wrong.
 
Thanks
Sada
 
[root@ip-172-16-8-240 ec2-user]# more /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost6 localhost6.localdomain6
10.2.192.1  etcd1
10.2.128.1  etcd2
10.2.64.1   etcd3
172.16.8.14 registry.local

[root@ip-172-16-8-240 ec2-user]# ping registry.local
PING registry.local (172.16.8.14) 56(84) bytes of data.

[root@ip-172-16-8-240 ec2-user]# more /etc/resolv.conf 
nameserver 10.2.192.1
nameserver 8.8.8.8

[root@ip-172-16-8-240 ec2-user]# more /etc/Corefile 
.:53 {
  proxy . 172.16.0.2
  hosts . {
    fallthrough
  }
  errors stdout
  log stdout
}
 

[root@ip-172-16-8-240 ec2-user]# docker ps | grep core
f7287049091c        405093580753.dkr.ecr.us-east-1.amazonaws.com/coredns:012-dev                                "/coredns"               6 seconds ago       Up 5 seconds                            coredns

[root@ip-172-16-8-240 ec2-user]# nslookup registry.local
Server:
10.2.192.1
Address:
10.2.192.1#53
 
** server can't find registry.local: NXDOMAIN
 
[root@ip-172-16-8-240 ec2-user]# docker logs -f coredns
2017/09/28 16:48:41 [INFO] CoreDNS-011
2017/09/28 16:48:41 [INFO] linux/amd64, go1.8.3, daf8ef0-dirty
.:53
CoreDNS-011
linux/amd64, go1.8.3, daf8ef0-dirty
10.2.192.1 - [28/Sep/2017:16:49:11 +0000] "A IN registry.local. udp 32 false 512" NXDOMAIN qr,rd,ra 108 29.525307ms
10.2.192.1 - [28/Sep/2017:16:49:11 +0000] "A IN registry.local. udp 32 false 512" NXDOMAIN qr,rd,ra 108 318.02µs
^C
[

**Comment by johnbelamaric** [comment]
This is a configuration issue. The `hosts` middleware config is:

```
hosts [ FILE [ ZONES ]]
```

So you should change your Corefile to:

```
.:53 {
  proxy . 172.16.0.2
  hosts {
    fallthrough
  }
  errors stdout
  log stdout
}
```

That is, without the `.`, which makes it read the current directory as a hosts file. That should probably be an error...
