### ISSUE TITLE
NSEC-records are missing in some cases

### ISSUE THREAD

**Issue by Isolus** [coredns/coredns#1127]
I'm experiencing issues with the DNSSEC-plugin. If I query a non-existent domain, the server responds with correct NSEC-records. But if I query the A-record for a domain where only an AAAA-record exists, there is no NSEC-record which causes DNSSEC validating resolvers to issue a SERVFAIL.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] NSEC-records are ..." ]
>I'm experiencing issues with the DNSSEC-plugin. If I query a non-existent domain, the server responds with correct NSEC-records. But if I query the A-record for a domain where only an AAAA-record exists, there is no NSEC-record which causes DNSSEC validating resolvers to issue a SERVFAIL.

Please add some more details, Corefile used, and some dig output.

**Comment by Isolus** [comment]
I'm using the file-plugin together with the DNSSEC-plugin.
I have an entry
`mysubdomain                  IN              AAAA            [...]`
in my zone file (and no other entries for `mysubdomain`).
If I query `dig -t A mysubdomain.example.org +dnssec @coredns-instance`, there are no NSEC-records in the response.
I think this is because in `plugin/file/lookup.go` the `found && shot` case is executed even though there is no A-record (and no `NameError` is returned).
In `plugin/dnssec/dnssec.go`we add NSEC-records only if there is a `NameError`.

**Comment by miekg** [comment]
Able to do Go? Welcome a PR for this (please also with test case). Thanks!

**Comment by miekg** [comment]
Closed via #1138
