### ISSUE TITLE
plugin/etcd: Fallthrough when no records are generated

### ISSUE THREAD

**Issue by boyander** [coredns/coredns#1130]
I'm using the following `Corefile` config:
```
.:53 {
    etcd {
        path /faable
        endpoint http://localhost:2379
        fallthrough
    }
    proxy . 127.0.0.1:5400
}

.:5400 {
    auto {
      directory <zones_dir> (.*).hosts {1} 30
    }
    debug
    log stdout
    errors stdout
}
```
**Description:** Config is uses etcd to solve letsencrypt dns challenges, in an ideal case a TXT record is written in etcd, the challenge is resolved and the key is erased. 

**Issue:** While the key exists, etcd plugin captures all other non TXT dns queries that should be proxied to the server on port 5400 and answers `NOERROR`.  

**Proposal:** Can we have an option that also does a fallthrough when no records are generated?  Maybe add a `norecords` option, can do PR if needed.

**Comment by miekg** [comment]
We already provide `fallthrough` in etcd: https://coredns.io/plugins/etcd/
doesn't that do what you want or is this slightly different?

**Comment by johnbelamaric** [comment]
We fall through in NXDOMAIN, this is fall through on NODATA.

On Oct 7, 2017, at 10:27 AM, Miek Gieben <notifications@github.com<mailto:notifications@github.com>> wrote:


We already provide fallthrough in etcd: https://coredns.io/plugins/etcd/
doesn't that do what you want or is this slightly different?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/etcd: ..." ]
>We fall through in NXDOMAIN, this is fall through on NODATA.

*eeeuw*....

**Comment by miekg** [comment]
*iff* we would allow this we could amend `fallthough` to have an optional argument, say `no_data` that alllows for this; this should however be implemented in *all* plugins using fallthrough.

Is there a way for let's encrrypt to ask a different domain, so normal fallthrough works?

**Comment by boyander** [comment]
letsencrypt DNS verification should find a TXT record on `_acme-challenge.example.com` in order to verify `example.com`. https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.8.5

I'm not sure on how to do it with another domain. Any ideas?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/etcd: ..." ]
>letsencrypt DNS verification should find a TXT record on `_acme-challenge.example.com` in order to verify `example.com`. https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.8.5
>
>I'm not sure on how to do it with another domain. Any ideas?

No, I'm just wondering if extending `fallthrough` for this is worth it.
You have other data under `_acme-challenge`? I.e removing everything from etcd 
should result in NXDOMAIN and make the current fallthrough stuff "just work"

**Comment by boyander** [comment]
If i remove the key for /skydns/com/example/_acme-challenge it answers NODATA. I can try to remove also the /skydns/com/example dir and test it. But removing everything from etcd will not work due to potentially multiple challenges running at the same time.

**Comment by miekg** [comment]
Hmmm. That might be a bug in etcd. Should be nxdomain at that point.

**Comment by miekg** [comment]
[test-patch.diff.txt](https://github.com/coredns/coredns/files/1366778/test-patch.diff.txt)
A quickly written does not confirm your theory.

**Comment by miekg** [comment]
@boyander have you got any further here?
