### ISSUE TITLE
packaging: add deb and rpm

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1148]
We push to Docker when we release.

Personally I just want to have deb that I can use for my server (amd64) and PI (arm).

We https://github.com/coredns/deployment for some of this stuff lives, but (for instance) not the Dockerfile, so it probably(?) makes sense to push this into the main repo.

**Comment by johnbelamaric** [comment]
We could move the Dockerfile there. Then "release" in the main repo would just do the build and upload the binaries to GitHub. We'd have to do the Docker and Deb packaging in the deployment repo. Otherwise we could just move it all into the main repo.

**Comment by miekg** [comment]
Yes, I like where you're going with this. Just tick everything off a new build and upload of the binaries (to github). rpm/deb's only extra requirement is a systemd service file, no idea about mac though.

But this also touching on the point of having some release automation.

**Comment by miekg** [comment]
See https://github.com/coredns/deployment/tree/master/debian
