### ISSUE TITLE
plugin/metrics: have PROMETHEUS_PORT env?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1150]
Doing a describe on kube-dns I saw this env var, might be worth putting in CoreDNS as well.

**Comment by miekg** [comment]
Hmmm, obviously coming from SkyDNS which has a whole slew of these; wondering if we should support most/some. 
Also while thinking. I think we already do because of how the Corefile support environment variables

**Comment by johnbelamaric** [comment]
I didn't know about this. It's awesome.
