### ISSUE TITLE
plugin/kubernetes - improve performance in findService() 

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1156]
1- compute wildcard status for a service is costly and we call it twice. => save info in boolean.
2- building endPoint list of the Service is also costly and useful only when we met an endPoint query or an headless service. => change into a lazy initialization.

**Comment by miekg** [comment]
As I said on other issues/PRs, having a little benchmark functions helps in guiding you.

**Comment by miekg** [comment]
I actually don't believe we save much by caching the wildcard bit, unless we go to string.EqualFold every time (and then still).
The lazy building of endPoint list is good to have.
