### ISSUE TITLE
Cache discussion

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1157]
So, I was thinking about how `cache` really [doesn't perform as well as some of the backends](https://docs.google.com/document/d/183DsEDkRn8ceM_QWNSrDotTmJVl1qoJrila0H0ol44U/edit?usp=sharing). I realized that this means that `cache` is really only useful for caching data returned by upstreams from `proxy` or `forward`.  So, it probably should appear *right before* `proxy` in the plugin ordering.

Not only that, but I also realized that because we use `upstream` in `file` and `kubernetes` and others for resolving external CNAMEs, we are not getting any benefit of caching of those queries. We probably should instead be able to target a plugin - i.e., something  like `upstream @cache` which would initiate the query for the external CNAME at that point in the plugin chain (which would have to be *after* the current plugin). Or we should be able to push the external CNAME resolution through the entire query routing (i.e., an internal equivalent of making `127.0.0.1` and upstream).

Thoughts?

**Comment by miekg** [comment]
We should probably try make the cache faster - note that doc does not say what queries are sent, but identical queries are [bucketed](https://github.com/coredns/coredns/blob/master/plugin/pkg/cache/cache.go#L25) (seeing `interface{}` there as well, might kill that) to the same shard, sharing a lock. Is that what you're seeing.

If *cache* sits before another plugin the whole answer is put in the cache, but yes, a new, uncached query would resolve that name again.

Quantifying how much of a problem this is would help.

**Comment by miekg** [comment]
After some localhost queryperfing with *whoami* and *caching* enabled, I'm not seeing any difference, both fluctuate around 120/130K qps on my laptop.

**Comment by johnbelamaric** [comment]
@miekg it was the same query over and over (just one).

**Comment by miekg** [comment]
Ack. Pretty sure you hit that mutex

**Comment by miekg** [comment]
Still `Len()` might be expensive in plugin/pkg/cache

**Comment by johnbelamaric** [comment]
Sweet. With 1000 unique queries:

```
33.4 FINAL cached tx 250942.0 rx 250944.6 to 0
```

**Comment by johnbelamaric** [comment]
250k qps

**Comment by johnbelamaric** [comment]
That's with our in-house tool. `dnsperf` gives:

```
  Queries per second:   303810.876817
```

**Comment by johnbelamaric** [comment]
If I increase the timeout on our in-house tool to 10s instead of 5s, then I get 312k QPS.

**Comment by miekg** [comment]
There are 256 shards in the cache. Upping that might get you even more.
