### ISSUE TITLE
CNAME and other data: cannot serve MX entry for domain

### ISSUE THREAD

**Issue by Waffeldrache** [coredns/coredns#1162]
I recently faced the issue that I am unable to set the MX record for the domain xyz.ab, but was able to do it for a subdomain sub.xyz.ab

I tried to set the MX record in many different ways:

~~~
@ IN  SOA ns1.example.org example.example.org. (
      2017091601	    ; Serial
      28800           ; Refresh
      7200            ; Retry
      864000          ; Expire
      86400   )       ; Min TTl

; Nameserver Information

             IN NS       ns1.example.org.
             IN NS       ns2.example.org.

; MX

             IN MX 10    mail.example.org.
~~~

I also tried to set it like this:

`example.org.          IN  MX    10 mail.example.org.`
`@         IN  MX    10 mail.example.org.`

I think this *may* be caused by this check (I'm not sure, I just checked a few issues related to MX on here)
#531

I'm using the 'file' plugin

**Comment by miekg** [comment]
The markup of you bug report is off. Is that the full zone you pasted?
I don't see the IP for `mail.example.org.` btw?
Also what are you seeing from the client side? I.e. some `dig` output would be handy.

**Comment by Waffeldrache** [comment]
It's a bit cluttered I know.

The mail.example.org was defined as 10.0.0.1 for testing purpose 

`mail    IN    A    10.0.0.1`

Which is resolved correctly when doing a dig on the server.

I'm setting up a small debug instance on my machine and then send you the dig output

**Comment by miekg** [comment]
With this zonefile, and config:
~~~
@ IN  SOA ns1.example.org example.example.org. (
      2017091601	    ; Serial
      28800           ; Refresh
      7200            ; Retry
      864000          ; Expire
      86400   )       ; Min TTl

; Nameserver Information

             IN NS       ns1.example.org.
             IN NS       ns2.example.org.

; MX

             IN MX 10    mail.example.org.
~~~
Config:
~~~
. {
    file db.example.org example.org
}
~~~
I get:
`dig @localhost -p 1053 mx example.org`:
~~~
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;example.org.			IN	MX

;; ANSWER SECTION:
example.org.		0	IN	MX	10 mail.example.org.

;; AUTHORITY SECTION:
example.org.		0	IN	NS	ns1.example.org.
example.org.		0	IN	NS	ns2.example.org.
~~~

**Comment by Waffeldrache** [comment]
Yes, when only specifying the MX entry it works for me too!

But defining a CNAME for that domain results in failure

```
$TTL 86400

@     IN      SOA     ns1.example.org.      admin.example.org. (
                        2017091601	; serial number YYMMDDNN
                        28800           ; Refresh
                        7200            ; Retry
                        864000          ; Expire
                        86400           ; Min TTL
			)

                NS      ns1.example.org.
                NS      ns2.example.org.


$ORIGIN example.org.

example.org.           IN  MX    10 mail.example.org.
                       IN  CNAME http.example.org.
```

```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 9e99a9a2a3173eca (echoed)
;; QUESTION SECTION:
;example.org.			IN	MX

;; AUTHORITY SECTION:
example.org.		86400	IN	NS	ns1.example.org.
example.org.		86400	IN	NS	ns2.example.org.
```

```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 2eb8c5e3511e902a (echoed)
;; QUESTION SECTION:
;example.org.			IN	A

;; ANSWER SECTION:
example.org.		30	IN	A	xxx.xxx.xxx.xxx

;; AUTHORITY SECTION:
example.org.		86400	IN	NS	ns1.example.org.
example.org.		86400	IN	NS	ns2.example.org.
```

**Comment by miekg** [comment]
you can't have both data and a cname for the same name.

**Comment by Waffeldrache** [comment]
Why not, I do it on cloudflare and it works... 

I mean alias does the CNAME flattening like cloudflare... so why can't we do that here too

**Comment by miekg** [comment]
https://serverfault.com/questions/694895/cname-record-with-any-other-resource-record-in-bind

If named-checkzone says OK, it should load otherwise not.

Trying to find the canonical source of this no-data thing.

This is a good read as well: https://blog.dnsimple.com/2014/01/why-alias-record/
Cloudflare is prolly doing something like that.

**Comment by Waffeldrache** [comment]
Is this ALIAS entry already a thing ? Can we use that with CoreDNS i

**Comment by miekg** [comment]
https://coredns.io/explugins/alias/

But afaict that implements something different. Actual ALIAS support prolly needs to be hacked in miekg/dns (and it is not a standard yet)

**Comment by Waffeldrache** [comment]
This does CNAME Flattening on the root domain AFAIK.

This is how cloudflare does the MX-CNAME thing

https://support.cloudflare.com/hc/en-us/articles/200169056-CNAME-Flattening-RFC-compliant-support-for-CNAME-at-the-root

Maybe a new option for the file plugin like 'flatten' or something ?

**Comment by miekg** [comment]
I believe the world is moving to ANAME or ALIAS. 

But maybe it is relatively easy to add such an option to the *file* middleware. The lookup code is already tricky, I hate to add complexity there for an (as of yet) non standard DNS feature. But YMMV.

**Comment by Waffeldrache** [comment]
Well it would be nice if we could serve MX and flattened CNAME's of the same domain. 
I think cloudflare did a good job on "extending" the DNS RFC (I mean.. it works just fine)

I'd add it myself but I am not proficient in the GO language :/

Edit:

I'm trying to hack in support for MX records on a custom build.

**Comment by miekg** [comment]
Ack. ALIAS support (or something would be nice), but don't think anyone can work on it.
Note that you should never leak the CNAME (in your hack), because that will confuse resolvers (i.e. there can't be any other data, so they might not look for it)

**Comment by miekg** [comment]
wtf is "stale bot" doing?

**Comment by Waffeldrache** [comment]
First I have to get coredns to output the MX anyway. Then I have to flatten the CNAME...

This is kinda hard if you don't know go. But well, there is not really a choice.

IDK what your bot is doing ^^ But it for sure likes to mess with your labels :)

Can you tell me where you drop the MX entry from the response ? (It would speed this up a bit)

**Comment by miekg** [comment]
There is no actual dropping, it's keeping track of seeing the CNAME, plugin/file/lookup.go#L155  looks like a good starting place.

**Comment by Waffeldrache** [comment]
Ok thank you! So I actually managed to return a static valid MX response without leaking the CNAME!
It actually only required 5 lines of code to catch it.

You did good code! Easy to read

**Comment by Waffeldrache** [comment]
So uhm... basically I ended up doing this below if found && shot:
```
if qtype == dns.TypeMX {
	rrs := elem.Types(dns.TypeMX)
	return rrs, z.ns(do), nil, Success
}
```
Hope I didn't mess up too bad (I'll see in the future)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CNAME and oth..." ]
>So uhm... basically I ended up doing this below if found && shot:
>```
>if qtype == dns.TypeMX {
>	rrs := elem.Types(dns.TypeMX)
>	return rrs, z.ns(do), nil, Success
>}
>```
>Hope I didn't mess up too bad (I'll see in the future)

Code wise this looks Ok. But doing this properly with ALIAS/ANAME would be 
better :)

**Comment by Waffeldrache** [comment]
Yes absolutely! But I'm afraid that I am unable to implement a entire new type :( ... I'd love to though!

But until then my problem is solved with 4 lines of code :) I could try to create that option for the file plugin though (If you'd like)

Thanks a lot for your support

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CNAME and oth..." ]
>Yes absolutely! But I'm afraid that I am unable to implement a entire new type :( ... I'd love to though!
>
>But until then my problem is solved with 4 lines of code :) I could try to create that option for the file plugin though (If you'd like)
>
>Thanks a lot for your support

np and thanks for using CoreDNS.

This hack is not something we should carry forward into coredns though :)

**Comment by Waffeldrache** [comment]
Alright! Thanks for creating it in the first place :)
