### ISSUE TITLE
core: migration from kube-dns

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1167]
See: https://github.com/kubernetes/community/pull/1100#issuecomment-338765725

How should we support this? One-time converter of the kube-dns config?

**Comment by johnbelamaric** [comment]
Yes, that's what I think.

**Comment by miekg** [comment]
How will this work?
* Parse the config map
* Write Corefile
* Let CoreDNS start up?

or eat a manifest and write a new one?

**Comment by chrisohaver** [comment]
https://github.com/kubernetes/kubernetes/pull/48899

**Comment by miekg** [comment]
Ack, but not everyone will use kubeadm. I wonder if we should add a little helper *inside* coredns (but icky) and @johnbelamaric mentioned that at some point both configs (kube-dns config map + Corefile) must potentially be merged.

**Comment by chrisohaver** [comment]
The Corefile would need to be constructed based on kube-dns ConfigMap (which is currently blank in a default deployment) and Deployment command line args for kube-dns, and dnsmasq-nanny, (and possibly sidecar).

Seems to make most sense to do this at deployment time - i.e. extending the existing deployment scripts in coredns/deployment. Whatever is done would ideally be gracefully reused by `kubeadm upgrade` without too much duplication or refactoring. 

A possible flow would be to ...

- Create yaml manifest of the existing kube-dns ConfigMap and Deployment.
- Parse kube-dns manifest and create CoreDNS manifest

@johnbelamaric: What is the "merge kube-dns config map + Corefile" case?

**Comment by johnbelamaric** [comment]
> @johnbelamaric: What is the "merge kube-dns config map + Corefile" case?

Something we never want to do! My point is that since a Corefile could be arbitrarily complex with all sorts of stuff in it, we can't deterministically merge the "kube-dns config" into an arbitrary Corefile. Instead, I think we take our default K8s Corefile, and we have a way to write that out using data from the kube-dns configuration. This would create a functionally equivalent deployment of CoreDNS for a given kube-dns deployment.

**Comment by johnbelamaric** [comment]
I don't think something inside makes sense. I think in the deployment repo and hopefully re-usable in kubeadmin is what we want.
