### ISSUE TITLE
fork to background?

### ISSUE THREAD

**Issue by branzo** [coredns/coredns#1170]
Hello all,

i was decided to use CoreDNS (maybe wrongly but i feel comfortable in using it) to replace dnsmasq as a DNS responder for a small project but I have not found a convenient way to run it background. At the moment i'm using this small kludge to 

`coredns > /dev/null 2>&1 & ; disown`

but i do not like it so much; shoud a 'go-to-background' feature be implemented?

**Comment by miekg** [comment]
Thanks for using CoreDNS.

Go binaries don't provide a way to daemonize because of reasons, so this can't be implemented in CoreDNS. We mostly depend on systemd (as the current Linux standard) to do this for us. Or you run it as a docker container.

**Comment by branzo** [comment]
Howdy @miekg,

thanks for your clarifications; I mainly asked because i'm running the binary itself inside a docker container so do not have systemd running, not problems btw, i should rethink a few bits here.

Keep up the amazing work! 

Cheers,
Brando
