### ISSUE TITLE
Implement a way to use root DNS servers

### ISSUE THREAD

**Issue by jpds** [coredns/coredns#1171]
I'd like to have two coredns instances that are not forwarders to other explicitly set DNS servers, but rather have them talk straight to the DNS root servers for their queries.

I'm using Debian which has a `dns-root-data` package which includes a file called `/usr/share/dns/root.hints` which has for example:

```
.                        3600000      NS    A.ROOT-SERVERS.NET.
A.ROOT-SERVERS.NET.      3600000      A     198.41.0.4
A.ROOT-SERVERS.NET.      3600000      AAAA  2001:503:ba3e::2:30
```

I tried using this with the `file` plugin, however it complains that this file has no SOA record.

Is there another way of configuring coredns to use the root servers?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Implement a way t..." ]
>I'd like to have two coredns instances that are not forwarders to other explicitly set DNS servers, but rather have them talk straight to the DNS root servers for their queries.
>
>I'm using Debian which has a `dns-root-data` package which includes a file called `/usr/share/dns/root.hints` which has for example:
>
>```
>.                        3600000      NS    A.ROOT-SERVERS.NET.
>A.ROOT-SERVERS.NET.      3600000      A     198.41.0.4
>A.ROOT-SERVERS.NET.      3600000      AAAA  2001:503:ba3e::2:30
>```
>
>I tried using this with the `file` plugin, however it complains that this file has no SOA record.

Yes, the root hints file isn't a zone file, it just lists the records for the 
root-servers.

>Is there another way of configuring coredns to use the root servers?

If you want to host the root zone, just axfr it:

dig AXFR . @b.root-servers.net

save to disk and voila. You can even configure it using the *secondary* plugin, 
and act like a secondary.

Using a root zone in CoreDNS might uncover some subtle bugs I think, so trying 
it out is encouraged :)

**Comment by jpds** [comment]
Done with https://github.com/coredns/unbound
