### ISSUE TITLE
Docker image should be a manifest

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1177]
In order to fully implement https://github.com/kubernetes/community/pull/1100 we need our Docker image to be a manifest list with various platforms built. From @luxas:

> k8s requires the image to be built for amd64,  arm, arm64, ppc64le and s390x

We may want to consider moving the Docker packaging step from the main repo to the https://github.com/coredns/deployment repo at the same time.

Examples for this are here: https://github.com/luxas/kubeadm-workshop

**Comment by luxas** [comment]
Thanks! LMK if you have any questions

**Comment by miekg** [comment]
If we are going to curl these from the official coredns releases we might want to build them there as well, means adding Linux/{arm64,ppc64le,s390x}

But really s390??

**Comment by luxas** [comment]
> But really s390??

@miekg Yeah, people do care about that for k8s ;)

**Comment by yongtang** [comment]
I have some free cycles. I can work on this issue.

**Comment by johnbelamaric** [comment]
@rajansandeep is about to push this already

**Comment by yongtang** [comment]
Ok. Reassign to @rajansandeep.

**Comment by yongtang** [comment]
Let's re-open this issue.

**Comment by miekg** [comment]
Closing because:
https://github.com/coredns/coredns/pull/1195#issuecomment-341722649
