### ISSUE TITLE
Add a homebrew repo for coredns?

### ISSUE THREAD

**Issue by lugoues** [coredns/coredns#1183]
I created a homebrew recipe for coredns. Unfortunately it looks like they won't accept it due to the non-vendorized dependencies within the project. I was wondering if it would be possible to create a new repo in coredns' org named `homebrew-coredns`. I can then submit a pull request setting up the repo.

This would allow users to tap it with `brew tap coredns/coredns`and install with `brew install coredns` while keeping homebrew recipes from polluting coredns' repository.

**Comment by miekg** [comment]
What would the new repo solve?
(aside: I rather not create something under coredns that deals with a specific packager)

FWIW: we have a repo that we use for deployment scripts: https://github.com/coredns/deployment
(docker will prolly move there and maybe deb and rpm packages)

**Comment by lugoues** [comment]
Deployment works too I guess :) I'll add it there.
