### ISSUE TITLE
NAPTR support

### ISSUE THREAD

**Issue by isaldarriaga** [coredns/coredns#1185]
I couldn't find a reference to the NAPTR RR ([RFC3403](https://tools.ietf.org/html/rfc3403)) in the [source code](https://github.com/coredns/coredns/blob/d8714e64e400ef873c2adc4d929a07d7890727b9/plugin/kubernetes/handler.go).

**Motivation**: Correct selection of a transport protocol on **SIP** calls when no transport protocol or port is specified ([RFC3263](https://www.ietf.org/rfc/rfc3263.txt))

From the spec:
"
4.1 Selecting a Transport Protocol
. . .
if no transport protocol or port is specified, and the target is not a numeric IP address, the client SHOULD perform a **NAPTR** query for the domain in the URI.  The services relevant for the task of transport  protocol selection are those with NAPTR service fields with values "SIP+D2X" and "SIPS+D2X", where X is a letter that corresponds to a transport protocol supported by the domain.  This specification defines D2U for UDP, D2T for TCP, and D2S for SCTP.  We also establish an IANA registry for NAPTR service name to transport protocol mappings.

These NAPTR records provide a mapping from a domain to the **SRV** record for contacting a server with the specific transport protocol in the NAPTR services field.

. . .

As an example, consider a client that wishes to resolve sip:user@example.com.  The client performs a NAPTR query for that domain, and the following NAPTR records are returned:

   ;          order pref flags service      regexp  replacement
      IN NAPTR 50   50  "s"  "SIPS+D2T"     ""  _sips._tcp.example.com.
      IN NAPTR 90   50  "s"  "SIP+D2T"      ""  _sip._tcp.example.com
      IN NAPTR 100  50  "s"  "SIP+D2U"      ""  _sip._udp.example.com.

   This indicates that the server supports TLS over TCP, TCP, and UDP, in that order of preference.  Since the client supports TCP and UDP, TCP will be used, targeted to a host determined by an SRV lookup of
   _sip._tcp.example.com.  That lookup would return:

   ;;          Priority Weight Port   Target
       IN SRV  0        1      5060   server1.example.com
       IN SRV  0        2      5060   server2.example.com
"

closing quotes..

BIND already support NAPTR and is the recommended DNS on this type of solution.

You cannot test SIP easily in the cloud without an IP Multimedia System (IMS) already developed. So if NAPTR is going to be implemented, I propose a testing platform for this: [Project ClearWater](www.projectclearwater.org) running on [kubernetes](https://github.com/Metaswitch/clearwater-docker). 

Clearweater is an open source IMS capable of making SIP calls, in its simplest form between users in the same system. This should be something that works out of the box after registering them in Ellis, a website running in the same deployment. I can say clearwater deploys without error in GKE, but it's mostly production ready right now in AWS + Route 53.

Reference: Clearwater's [DNS Setup on BIND](http://clearwater.readthedocs.io/en/stable/Clearwater_DNS_Usage.html#bind).

But take a look into the following limitation in Kubernetes, which is actually a secondary problem to the unavailability to perform the service discovery with NAPTR, and becomes more like a number of questions:

From the github page..
"
Scaling the deployment:
Most Clearwater services can be dynamically scaled up and down by running e.g. kubectl scale deployment sprout --replicas=3 
Exceptions are:
-- You can only have a single Bono if Bono pods do not have **externally routable IP addresses**.
"
Bono is the P-CSCF (Proxy-Control Session Control Function) on clearwater, i.e. the SIP Proxy server that receives all the requests to the IMS in the form of SIP calls. 

Bono cannot be scaled with the default LB service in K8s, because each of these SIP servers alter the  messages coming through the proxy by setting their public IPs (i guess into the "via" header), in order the SIP transaction (a collection of related messages) to be completely processed by the same proxy until the end. i.e. a single SIP transaction doesn't jump from proxy to proxy during the round-trips to he client like in a load balancer in K8s, because clients uses the IP in the "via" header to communicate back to the same proxy. 

So i think there should exists something in kubernetes like a "Headless Load balancer", that could be implemented maybe at the DNS level in CoreDNS. With this i mean a service that is able to expose the public IPs of the nodes of an internally balanced cluster, so the caller can reach the IPs written in the protocol's messages.

There is an additional requirement for the P-CSCFs. They must alter the SIP messages in order to set the public IP of the **cluster** where they are running on, in order the SIP dialog (long-lived collection of  transactions) to be processed by any P-CSCF in the same cluster. This part is easily covered by having a K8s LB Service, but since we only want a single object managing this, the headless LB that i'm referring to, should also expose the public IP of the cluster. not only the ones of its nodes.

As a side note: Clearwater IMS use ephemeral storage to keep transaction state (hostPath), and persistent storage to keep dialog state (cassandra / memcached). it's irrelevant to the topic, but enforces the separation of this 2 concepts that happen at the networking level too.

So the question is:

Is there something/plugin in CoreDNS allowing the first scenario (headless load balancer)? somebody could say "A" records are enough for this, plus an auto-reload mechanism (that i think is already in place in CoreDNS), but how about the mechanism that fire this update on the DNS? can CoreDNS listen to the "scale event" coming from K8s for a particular LB service and reconfigure its A records upon scale?

I've thought about running multiple "LB k8s services" each one pointing to one node in the P-CSCF cluster (Bono), in order to have multiple public IPs. but this is rather an ugly solution, and does not let scale easily neither at P-CSCF cluster itself nor the DNS, involving a number of manual steps.

**Comment by miekg** [comment]
This should be done upstream in the DNS spec: https://github.com/kubernetes/dns/blob/master/docs/specification.md

**Comment by johnbelamaric** [comment]
I think there are multiple questions here:

1. NAPTR - do we support that in the `file` middleware at least?
2. NAPTR support for k8s - that would be part of the spec.
3. Exposing the external IPs of a service (i.e., the node IPs or explicitly configured externalIPs) along with the ports - see #839 - this should also be addressed in the spec.

**Comment by miekg** [comment]
>  1. NAPTR - do we support that in the file middleware at least?

yes, everything supported by miekg/dns works there, there is no arbitrary limiting of supported records.

**Comment by miekg** [comment]
Btw: I'm not against a PR doing this in kubernetes and the etcd plugin, but someone needs to provide code.

**Comment by miekg** [comment]
Closing here, as noone seemed care enought.
