### ISSUE TITLE
Cannot define same zones on different listen addresses

### ISSUE THREAD

**Issue by yunzheng** [coredns/coredns#1208]
I cannot seem to define the same zones for different listen addresses, e.g.:

```
. {
  bind 10.0.0.1
  proxy . 8.8.8.8
}

. {
  bind 10.0.0.2
  proxy local.network 10.0.0.10
  proxy other.network 192.168.1.1
}
```

It will error with `cannot serve dns://.:53 - zone already defined for dns://.:53`. I would expect I could define a ServeDNS instance separately per listen address/port combination. Is there maybe another way?

**Comment by miekg** [comment]
ah with `bind`, nice twist. Interesting. I agree with you that this should work.

**Comment by miekg** [comment]
The `bind` plugin code runs after the server starts up and does this duplication check. A "fix" is unwieldy. Why can't you just start 2 instances of coredns?

**Comment by yunzheng** [comment]
I currently do, I have like 5 instances now... and each instance takes up like 3% of memory. It kinda pollutes the process list imho, so I was wondering if this was possible at all.

Maybe do it outside the `bind` plugin and make it part of main coredns logic?

**Comment by miekg** [comment]
I don't think "pollutes the process list" is good reason to push for this though.
@mholt is this something that works in Caddy (i.e. did I miss some updates)

**Comment by yunzheng** [comment]
Fair enough, but the memory usage point still stands though. It's currently using 30mb total now for 5 instances. Each `coredns` instance takes up 6mb.

**Comment by miekg** [comment]
How much of that memory is shared?

Anyway I don't believe this can be fixed in a good way - which means you're stuck with running multiple processes. Sorry.

**Comment by stp-ip** [comment]
Not "fixed" in caddy yet. It's more a go limitation.
Issue for caddy: mholt/caddy#864
Issue for go: golang/go#9334

**Comment by miekg** [comment]
Note that *this* issue is different a not related to ipv6

**Comment by stp-ip** [comment]
Yes it just came up during that IPv6 discussion and was discussed within this issue the most. It basically formed into IPv6 not being the issue, but the issue not binding to multiple IPs. ;)

**Comment by yunzheng** [comment]
ok, then i'm closing the issue.

**Comment by fturib** [comment]
It is now implemented : BIND directive accept several addresses.
