### ISSUE TITLE
DS records for delegations with dnssec plugin

### ISSUE THREAD

**Issue by schors** [coredns/coredns#1211]
I see github.com/coredns/coredns/plugin/dnssec/dnssec.go:

>  For delegations it will insert DS records and sign those.

and 
```Go
                for i := range d.keys {
                        ds = append(ds, d.keys[i].D)
                }

```

But why? This prevents to using CoreDNS for real world zones with delegations. Maybe I did not understand these lines?

**Comment by miekg** [comment]
It *should* only happen for delegation from unsigned zones served from CoreDNS. There is nothing to prevent you from applying this to proxied content though.

What are you seeing, what's your config, etc?

**Comment by schors** [comment]
I want to use CoreDNS as an authoritative nameserver for your domains.
Corefile:

```
example.com:1053 {
        file example.com {
                transfer to *
        }
        dnssec example.com {
                key file Kexample.com.+013+57179
        }
}

schors.ru:1053 {
        proxy schors.ru 185.35.220.5:53
        dnssec schors.ru {
                key file Kschors.ru.+013+22401
        }
}

```
(schors.ru - real not signed domain with controlled NS 185.35.220.5)

example.com file:
```
example.com.  3600 IN  SOA   ns.example.com. username.example.com. ( 2007120710 1d 2h 4w 1h )
example.com.  3600 IN  NS    ns.example.com.
example.com.  3600 IN  A     10.0.0.1
dstest.example.com. 3600 IN NS ns.somewhere.example.org.
```

```
dig -p 1053 +dnssec -t A dstest.example.com

; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> -p 1053 +dnssec -t A dstest.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11270
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 3, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;dstest.example.com.		IN	A

;; AUTHORITY SECTION:
dstest.example.com.	3600	IN	NS	ns.somewhere.example.org.
example.com.		3600	IN	DS	57179 13 2 EECAAAF1E3406A04FF2DB058097111C1E2301220C51B54E355B8F4F5 A5158564
example.com.		3600	IN	RRSIG	DS 13 2 3600 20171118181143 20171110151143 57179 example.com. Ma0cAt90gTIcXVkq2YQEYjvXSPFTvx6VEKfgcOIU5FmT+yWHuh/6bRzB o1MiDUjdbUXig8T/6j8Etzn8ZLR8jQ==

;; Query time: 0 msec
;; SERVER: 127.0.1.1#1053(127.0.1.1)
;; WHEN: Fri Nov 10 21:11:43 MSK 2017
;; MSG SIZE  rcvd: 240

```
```
dig -p 1053 +dnssec -t A dstest.schors.ru

; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> -p 1053 +dnssec -t A dstest.schors.ru
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58993
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;dstest.schors.ru.		IN	A

;; AUTHORITY SECTION:
dstest.schors.ru.	300	IN	NS	ns1.example.com.
dstest.schors.ru.	300	IN	NS	ns2.example.com.
schors.ru.		3600	IN	DS	22401 13 2 491A01FC43EA5A1E6E49276E095502D52BF86CAE5CE0E6531B6070AB 73383456
schors.ru.		300	IN	RRSIG	DS 13 2 3600 20171118181519 20171110151519 22401 schors.ru. 3KULQ+gWb2tGyykzKfAIHZDrAwhmsRldcxAgflhEHsKT4j+Hrv1em41j Cg4NrDb6AAIUIOv9nkr7lyfNrcBwmw==

;; Query time: 28 msec
;; SERVER: 127.0.1.1#1053(127.0.1.1)
;; WHEN: Fri Nov 10 21:15:20 MSK 2017
;; MSG SIZE  rcvd: 245


```

It's not true. I want to keep DSTEST delegation unsigned. If I add DS record to my zone manually, CoreDNS add it to generated record. It's all fail.

**Comment by schors** [comment]
I basically do not understand why you need a generated DS

**Comment by miekg** [comment]
Hmm, current code might indeed be wrong: coming back to the reason. I was thinking:
Non signed zone - but 1 (or more delegation), how can we support this case with on the fly signing?

If possible at all now that I think about it again...

**Comment by schors** [comment]
## Statements: 

1. We assume that we have an unsigned zone.
2. In any case, we sign it on the fly.

## Logic

1. Referral to a signed zone.  The DS RR contains the data which the resolver will need to validate the corresponding DNSKEY RR in the child zone's apex. DS RR from source!
2. Referral to an unsigned zone.  The NSEC RR proves that no DS RR for this delegation exists in the parent zone. 

All in AUTHORITY section

https://tools.ietf.org/html/rfc4035

**Comment by johnbelamaric** [comment]
Do we need this for 1.0.0? We need to close out on that release this week.

**Comment by miekg** [comment]
We might want to push this to post 1.0.0

**Comment by miekg** [comment]
Or revert the initial commit that added this and rethink. I'll think that is best in this case.

**Comment by miekg** [comment]
This code was reverted. I'll open another bug with what we should need (if any) here.
