### ISSUE TITLE
Development of protocol for backend comms

### ISSUE THREAD

**Issue by alialshamali** [coredns/coredns#1226]
To use CoreDNS authoritative DNS to service publicly zone files. Discussion started on issue #1223 , and wanted to open dedicated issue for this. 

The use case Core-DNS will serve zone file from a backend(maybe DB or resource records backend).
The basic requirements for implementing the backend (As suggested @schors):

1. Speed :-)
2. Low latency
3. Online adding, changing and deleting zones
4. Online zone refreshing
5. Selecting for signing or unsigning zones (for secondary zones)

**Comment by miekg** [comment]
Do note that the *file* plugin already implements this. The request here is to develop an protocol/API to talk to any back (DB, etcd, whatever) *and* implement the "full" DNS spec, meaning DNS + the NSEC.

From that issue:
> I'm thinking about this for a while. It may be better to implement the resource records backend, not zones, as is done by CloudFlare

@schors: What do you mean by this (on a technical level)

**Comment by alialshamali** [comment]
@miekg I have question regard something you said from the other issue:

> The etcd plugin doesn't provide all resource type - I'll clarify that in the docs. 

I was checking the [skydns documnetation](https://github.com/skynetservices/skydns), its appears that its supports most resource types including MX. So I am guessing the  coredns etcd plugin doesn't ? 

I think @schors meant a backend support such DB or etcd or etc... to store the DNS resource records in, not zones files. The DNS will interact with that value storage and take those values and serve them.
I personally support this backend to be implemented in etcd, I think is the best choice for a backend.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Development o..." ]
>@miekg I have question regard something you said from the other issue:
>
>> The etcd plugin doesn't provide all resource type - I'll clarify that in the docs.
>
>I was checking the [skydns documnetation](https://github.com/skynetservices/skydns), its appears that its supports most resource types including MX. So I am guessing the  coredns etcd plugin doesn't ?

it does, everything from skydns is supported in the etcd plugin.

>I think @schors meant a backend support such DB or etcd or etc... to store the DNS resource records in, not zones files. The DNS will interact with that value storage and take those values and serve them.
>I personally support this backend to be implemented in etcd, I think is the best choice for a backend.

Ok, I would be good a sketch out some design/api before we create code (I think)

**Comment by schors** [comment]
I'm very busy right now. I will describe my thoughts in more detail later. And even probably I will make PR for DNSSEC
Everything is not clear there. The best performance will be obtained if the entire database is kept in memory (NSD-like). And backend to use only for persistent storage. 
Some problems:
* Both zone and subzone serve (it's unusually, but...).
* Dynamic zonelist.
* Key change without server reload (for CSK rotation).
* Dynamic updates. Update at first backend and then memory base from it, or contra?

**Comment by mcdee** [comment]
Jumping in to this: I stumbled upon coredns whilst looking for a modern DNS server with which to serve DNS (read-only, but authoritative). The thing that strikes me is that although the basic infrastructure for handling requests is present it appears that coredns is missing the piece that handles the higher-level understanding of DNS.  Probably best to give an example for this:

Say that someone requests the A record for www.example.com.  At current my backend receives a single request for this record, but in reality there are multiple steps that should be taken:

- Going down the labels to see which (if any) of the domains are served by the plugin
- Checking www.example.com for CNAME/DNAME records, and recursively resolving them if so
- Appending DNSSEC records if present
- Appending authority information

etc. At current I'm faced with building out all of this logic myself, and given that I'm no DNS expert it's probable that I'll get it wrong.

It seems to me that a saner approach would be to have the above logic centralised as a standard authoritative resolver piece, and the relevant plugin could be a small set of focused functions, e.g.

- Is this plugin authoritative for domain x?
- Return the records of qtype Y for key Z in domain x

There might be other functions, but hopefully this gives the idea.

This would result in more standardised handling of DNS requests independent of the plugin (file, DB, whatever) and significantly reduce the load of the plugin writer.

Is this the issue that is being addressed here, and if so is there a plugin that already does a lot of this work that could be used as the base for a suitable abstraction?

**Comment by miekg** [comment]
So, the file plugin does all that. This discussion here is precisely what you're asking: there is (will be, at some point) a *db* plugin that has all the logic and calls out to a backend(s) to get the pieces it needs. 

Nailing down what that API should look like is a piece of this work.

**Comment by mcdee** [comment]
Thanks for that.  As I need it anyway I'll see if I can put together a preliminary attempt at breaking out the what-to-lookup logic from the file plugin and see what falls out in terms of a required API.  Hopefully that will serve as a base for those who are far more knowledgeable in DNS than I to point out the flaws and fixes required.

**Comment by miekg** [comment]
My gut feeling is that the API should be fairly simplistic; the *file* plugin uses an "API" to talk to the tree holding the data.
The I'm I authoritative bit is handled by CoreDNS already (see top of plugin/file/file.go's ServeDNS).

So once figured out the only thing we pull out of the tree is following the labels right to left and asking `<name>` to the tree object (see plugin/file/tree/tree.go Search). That responds with an `*tree.Elem` which is defined as:
~~~
type Elem struct {
	m    map[uint16][]dns.RR
	name string // owner name
}
~~~

Secondary questions are how dns.RR's should this be stored in a backend? Txt, gob-encoded, binary? And it this efficient enough as there will be quite some back and forth to get all the data.

**Comment by mcdee** [comment]
After looking at the existing `lookup` function in the `file` plugin the interface to the backend could be something as simple as the following:

    type Server interface {
        // Query returns records for a specific domain, key and resource type
        Query(qdomain string, qkey string, qtype uint16, do bool) ([]dns.RR, error)

        // IsAuthoritative returns true if this server is authoritative for the
        // supplied domain
        IsAuthoritative(qname string) bool
    }

`Query` tries to make no assumptions about the backend; the plugin might have the data in a per-zone format, be a simple key/value lookup, cache or not cache, whatever.  It leaves the plugin with a lot of freedom but seems to fit the bill of being able to handle all of the queries that are thrown at it.  `qdomain` is the equivalent of the origin of the zone being queried, and `qkey` is the key of the record being queried.  `qtype` and `do` are the query type and DNSSEC flag, respectively.

If this makes sense, the next step would be to write a `lookup`-like function to work with this style of server.  There is a lot in there that I don't fully understand; I'm happy to take a look at it over the next few days and see what I can come up with but if someone with more knowledge of coredns and DNS thinks they can throw something together easily please yell.

**Comment by miekg** [comment]
Query can be shortened to `Query(qname string, qtype uint16, do bool) ([]dns.RR, error)` I think.
For NSEC you may also need to the know the types that exist at a name, returning a map with that info works better for that use case, i.e. let Query return a `map[uint16][]dns.RR` (also for getting RRSIG etc)

Why is IsAuthoratitative needed? Think this should come from the Corefile.

**Comment by mcdee** [comment]
`IsAuthoritative()` allows for both static and dynamic information about the zones for which a server is authoritative.  A plugin might read it from the Corefile, pull it dynamically when requested, or whatever, but the idea is to abstract that with the function call.

The thought behind splitting the key from the domain is to make the backend's job easier.  Perhaps a simple example of fetching an A record for `www.example.com` when the server is authoritative for `example.com.` might help.  I'm going to skip over a lot of the wrinkles (DNAME/CNAME, DNSSEC etc) but in general:

  - coredns queries the server to find out the lowest-level domain for which it is authoritative (starting with `.` and moving through `com.`, `example.com.` and `www.example.com.`); the server will return `example.com.`
  - coredns uses this information to break the name in to key `www` and domain `example.com.`
  - coredns queries the server for the A record of `www` in the `example.com.` domain

The benefit here is that coredns contains the logic for handling what is required and the server just needs to pull the record(s).  The `file` plugin would fetch the relevant Zone, a `db` plugin might hit a table that breaks out the domain and the key, a key-value store plugin might create its own composite key from the key, domain and RR type, etc. Again, the idea is that coredns handles the logic of what should be fetched and the plugin does the fetching with minimal knowledge of DNS.

As I said, I'm no DNS expert so I might have made a mistake in how resolution works. I'm also very vague on the DNSSEC piece; is there a decent intro that you could point me to that explains how it works under the hood?  Alternatively, is this something else the can be handled outside of each plugin (i.e. coredns works out which DNSSEC records are required and asks for them through further queries)?

**Comment by miekg** [comment]
I see. Still think you can get away with just Query and asking for data. Getting nothing back indicates not authoritative.

But it looks to be instructive to add the interface and use it in the file and auto plugin. If that works I see no reason why we can't implement a DB (better names welcome) plugin that generalizes this and write some sql backend.

**Comment by glerchundi** [comment]
I would like to sketch something on top of this and I think creating a gRPC based integration point would open up CoreDNS to a wide range of possibilities. CoreDNS being the client which queries for data on a gRPC Server. WDYT?

**Comment by miekg** [comment]
Yes I think this makes sense. Not 100% sure we should say it must gRPC, but
it will be good to see what kind of API we like.

**Comment by glerchundi** [comment]
Something like this? I'm just a mere materializer of @mcdee's proposal.

```
service DNSService {
    // Query returns records for a specific domain, key and resource type.
    rpc Query(QueryRequest) returns (QueryResponse);
}

message Record {
	string name = 1;
	uint16 rr_type = 2;
	uint16 class = 3;
	uint32 ttl = 4;
	bytes data = 5;
}

message QueryRequest {
    // The equivalent of the origin of the zone being queried.
    string domain = 1;
    
    // The key of the record being queried
    string key = 2;
    
    // The query type.
    uint16 type = 3;

    // DNSSEC flag.
    bool do = 4;
}

message QueryResponse {
    message ListOfRecords {
        repeated Record records = 1;
    }
    map<uint16, ListOfRecords> results = 1;
}
```

Take into account that proto3 doesn't have `uint16` data types so we should put a uint32 on those.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Development o..." ]
>Something like this? I'm just a mere materializer of @mcdee's proposal.

Yes, this might work. But before we commit to this I would like to see an 
implementation using this. 

>
>```
>service DNSService {
>    // Query returns records for a specific domain, key and resource type.
>    rpc Query(QueryRequest) returns (QueryResponse);
>}
>
>message Record {
>	string name = 1;
>	uint16 rr_type = 2;
>	uint16 class = 3;
>	uint32 ttl = 4;
>	bytes data = 5;
>}
>
>message QueryRequest {
>    // The equivalent of the origin of the zone being queried.
>    string domain = 1;
>
>    // The key of the record being queried
>    string key = 2;
>
>    // The query type.
>    uint16 type = 3;
>
>    // DNSSEC flag.
>    bool do = 4;
>}
>
>message QueryResponse {
>    message ListOfRecords {
>        repeated Record records = 1;
>    }
>    map<uint16, ListOfRecords> results = 1;
>}
>```
>
>Take into account that proto3 doesn't have `uint16` data types so we should put a uint32 on those.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/coredns/coredns/issues/1226#issuecomment-378858325
/Miek

--
Miek Gieben

**Comment by glerchundi** [comment]
Ok @miekg, before doing anything else, what would be the difference between this and a forward plugin implementing `grpc` as an upstream protocol, as proposed here: #1476? I'm not sure which one would be the best way to approach this.

Which one would you choose?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Development o..." ]
>Ok @miekg, before doing anything else, what would be the difference between this and a forward plugin implementing `grpc` as an upstream protocol, as proposed here: #1476? I'm not sure which one would be the best way to approach this.
>
>Which one would you choose?

I believe the context for this would be backend comms, i.e. a database at least 
that's what comes to my mind. So we should do the following (just saw the bug 
you filed);

Rework *file* to use a database using this protocol and create a *db* plugin
(prolly the gist of your issue as well). If this works, we should back port the 
protocol to *file* **or** make *db* be able to use a file - not sure how this 
ends up.

If we do implement this as gRPC that can work as well, but then (in the case of 
the db) you need to translate from and to gRPC which adds latency as opposed to 
just using sql and the Go DB driver.

**Comment by johnbelamaric** [comment]
I see the importance of a set of Go interfaces to define this API. But not sure the value of creating gRPC services with the actual message semantics built in. That is, we already have gRPC that just wraps a dns.Msg (https://github.com/coredns/coredns/blob/master/pb/dns.proto)). By doing that, we automatically get all the DNS fields and functionality. Why do we need to actually represent the fields in protobuf? What does it gain? The receiving side can unpack a dns.Msg, it is wire format (at least I think so?) so it will work in any language as is.

Also take a look at the `watch` function in #1527 which extends the current gRPC interface.
