### ISSUE TITLE
plugin/k8s: Don't include unexposed namespaces in cache

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1232]
Currently k8s plugin keeps a cache of all k8s items (services, endpoints, pods).  It does this regardless of wether or not those items are in exposed namespaces.  For every query that comes in, k8s plugin filters out unexposed namespaces from answers. By default, all namespaces are exposed, however the user can configure the k8s plugin to only expose items in a give list of namespaces. 

We should consider changing namespace exposure checks from query time, to be k8s cache time (i.e. in `controller.go`).  In other words, the k8s plugin only cache items in exposed namespaces.  With the cache "pre-filtered", name lookups don't need to check namespace exposure per query.

This would simplify code a bit and be more efficient, removing need to screen for exposed namespaces for each query. 

For pods, this is problematic. To support `autopath`, we need a pod cache for all pods making dns queries - some of which could be in unexposed namespaces.

So, pods may be an issue, but for services and endpoints, moving namespace exposure check to k8s cache time is probably a good idea.

**Comment by miekg** [comment]
How common is not exposing namespaces?

**Comment by johnbelamaric** [comment]
Rare now. There has been talk of running separate DNS servers for multi-tenancy. In that case it would become common. But today the way kubelet configures DNS pods that's not feasible anyway.

**Comment by miekg** [comment]
Ok. thanks

This sounds like a good optimization - anything we can pull out of the serving path is good.

**Comment by miekg** [comment]
Are we still going to do this?

**Comment by chrisohaver** [comment]
Perhaps eventually.

**Comment by chrisohaver** [comment]
Now that we control the cache/store more manually (memory reduction efforts), this is easier to implement.
