### ISSUE TITLE
loadbalancing and failover

### ISSUE THREAD

**Issue by tweakmy** [coredns/coredns#1238]
I would like to say the coredns is awesome and simplistic to use to some certain extend. 

I would like to know if the loadbalancing plugin is supporting failover(health check on the services) or there is other coredns plugin that is doing the same feature. 
AWS have this feature:[]( http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-configuring.html)

**Comment by miekg** [comment]
the loadbalancer plugin does not do that; it just shuffles the records

**Comment by miekg** [comment]
the idea is not new though; there is benefit in having something doing slightly smart loadbalancing - maybe in the new plugin, maybe in loadbalance?
