### ISSUE TITLE
reverse for endpoints?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1241]
I'm not sure if this handled in the dns spec (https://github.com/kubernetes/dns/blob/master/docs/specification.md#243---ptr-records). But I have a headless service with endpoints. I.e.
~~~
kubectl get ep
~~~
Shows a whole bunch of them. The headless service stuff from the spec all works, but a reverse for these pods seems lacking, i.e. `ep` prints 10.40.0.3:8080 as an endpoint, but dig -x 10.40.0.3 gives nothing.

This is in `pod verified` mode.

I'll update this with some actual data from the setup I have at work, once I'm back on that network.

**Comment by johnbelamaric** [comment]
You need both the service CIDR and the pod CIDR in the Corefile. What zones are in your Corefile?

**Comment by johnbelamaric** [comment]
We need to document that better. Generally the pod CIDRs aren't known up front during kubeadm install for example. The are determined when you set up the networking.

**Comment by miekg** [comment]
I'm just using https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed with `pods verified` added.

**Comment by johnbelamaric** [comment]
Yeah. That's you need to add in your pod CIDRs.

**Comment by johnbelamaric** [comment]
This is a bit of an issue compared to kube-dns, which basically will handle all PTRs.

**Comment by miekg** [comment]
Ah, got it.

**Comment by johnbelamaric** [comment]
Endpoints are distinct from pods. We don't do reverse lookups for pod IPs to pod FQDNs (i.e., `a-b-c-d.namespace.pod.cluster.local.`). If a pod IP is also an endpoint IP, we will do reverse for that IP and it will point the endpoint FQDN `ep.servicename.namespace.svc.cluster.local`.

We don't need `pods verified` to do the endpoint PTRs. We have not implemented PTR that returns the `pod` zone names at all, even with `pods verified`.

**Comment by miekg** [comment]
Would could/would be a good way to do this on-the-fly and fit the CoreDNS model? (sidecar that updates the config?)

**Comment by johnbelamaric** [comment]
I don't want a sidecar. Also last I checked this information was not available from the Kube API...
