### ISSUE TITLE
failed health_check in coredns proxy module does not have an effect on round robin loadbalancing

### ISSUE THREAD

**Issue by imewes** [coredns/coredns#1247]
the following config adapted straight from the proxy module readme does not work as expected with coredns v0.9.10

```
. {
    proxy . 10.0.3.20:5300 10.0.3.21:5300 {
        policy round_robin
        health_check /index.html:4444
    }
}
```
Both systems get an amount of equally distributed requests (as seen in tcpdump),  if one server has failed the health_check (can be seen in the log). Experimenting with max_fail and fail_timeout did not change anything on this behaviour.

Healthcheck on 10.0.3.20 returns a 200/OK, healthcheck on 10.0.3.21 returns a 404

```
 curl -v http://10.0.3.20:4444/index.html
*   Trying 10.0.3.20...
* Connected to 10.0.3.20 (10.0.3.20) port 4444 (#0)
> GET /index.html HTTP/1.1
> Host: 10.0.3.20:4444
> User-Agent: curl/7.47.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: SimpleHTTP/0.6 Python/2.7.5
< Date: Wed, 22 Nov 2017 09:17:02 GMT
< Content-type: text/html
< Content-Length: 3
< Last-Modified: Wed, 22 Nov 2017 09:15:23 GMT
< 
OK
```
```
curl -v http://10.0.3.21:4444/index.html
*   Trying 10.0.3.21...
* Connected to 10.0.3.21 (10.0.3.21) port 4444 (#0)
> GET /index.html HTTP/1.1
> Host: 10.0.3.21:4444
> User-Agent: curl/7.47.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 404 File not found
< Server: SimpleHTTP/0.6 Python/2.7.5
< Date: Wed, 22 Nov 2017 09:18:30 GMT
< Content-Type: text/html
< Connection: close
< 
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 404.
<p>Message: File not found.
<p>Error code explanation: 404 = Nothing matches the given URI.
</body>
* Closing connection 0
```

Log from coredns:
2017/11/22 09:58:12 [WARNING] Host 10.0.3.21:5300 health check returned HTTP code 404
2017/11/22 09:58:16 [WARNING] Host 10.0.3.21:5300 health check returned HTTP code 404
2017/11/22 09:58:20 [WARNING] Host 10.0.3.21:5300 health check returned HTTP code 404
2017/11/22 09:58:24 [WARNING] Host 10.0.3.21:5300 health check returned HTTP code 404
2017/11/22 09:58:28 [WARNING] Host 10.0.3.21:5300 health check returned HTTP code 404
2017/11/22 09:58:32 [WARNING] Host 10.0.3.21:5300 health check returned HTTP code 404
2017/11/22 09:58:36 [WARNING] Host 10.0.3.21:5300 health check returned HTTP code 404

on 10.0.3.20:
tshark -i any -d udp.port==5300,dns port 5300 | wc -l
tshark: WARNING: Protocol "dns" matched 3 dissectors, first one will be used
Running as user "root" and group "root". This could be dangerous.
Capturing on 'any'
30 

on 10.0.3.21: 
tshark -i any -d udp.port==5300,dns port 5300 | wc -l
tshark: WARNING: Protocol "dns" matched 3 dissectors, first one will be used
Running as user "root" and group "root". This could be dangerous.
Capturing on 'any'
30 

did i misinterpret the docs or is this really a bug

**Comment by miekg** [comment]
confirmed; it's a bug - and a stupid one :( If the HC fails it would be smart to actually increase the failure count.

**Comment by miekg** [comment]
I'll have (small) PR to fix this - I'll ponder a test case to catch these regressions.
