### ISSUE TITLE
plugin/cache: add per ip cache

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1248]
plugin/autopath *is* useful, but due to how we cache (packet per question) we may cache to wrong data for the wrong pod. This can be fixed by adding to ability to cache on a per source IP basis.

On the implementation side:
This will increase the amount of memory used, if we just add the source IP in the mix - maybe that will suffice as a first impl and then later we can optimize.

**Comment by chrisohaver** [comment]
Kubernetes' plugin implementation of autopath is dependent on the pod's namespace.  So a per namespace cache would work, reducing cache size/memory used vs a per ip cache.  It would require a lookup in the local pod cache for each incoming query - which I think is already done when autopath is enabled for kubernetes.

**Comment by miekg** [comment]
Interesting, that would in deep be better for memory; OTOH per-src-ip can be re-used for caching EDNS client subnet queries.

Adding some kind of indication on how to cache makes sense; i.e. if autopath or kubernetes in general returns a `cache:bla` key in the context (or something) we might just use that to create the cache key ID.

**Comment by miekg** [comment]
So, we can use a context - figured so much - but I did need to check: contexts only work downwards in the api call, you can't communicate back upwards.

Incoming lookup are a good point as well - and that sense it might be easier to just allow per-ip caches...

**Comment by miekg** [comment]
nice to have, but not being worked on.
