### ISSUE TITLE
How to do "catch-all" (wildcard)?

### ISSUE THREAD

**Issue by wiradikusuma** [coredns/coredns#1255]
I use `auto` plugin:

	. {
	    auto {
	        directory /etc/coredns/zones (.+)\.zone {1}
	    }
	}

and have this working properly (filename: `foo.com.zone`):

	$ORIGIN foo.com.
	@       3600 IN SOA ns1.mysuperns.com. admin.mysuperns.com. ( ... )

	3600 IN NS ns1.mysuperns.com.
	3600 IN NS ns2.mysuperns.com.

	@    IN A some.ip.address

How do I make this into wildcard, essentially "point whatever domain queried to some.ip.address"?

**Comment by miekg** [comment]
iirc the *auto* plugin checks if the file exist before doing this. So you can't make this a wildcard thing with coredns itself.

If you want this I think the easiest is to write a plugin your self, the *whoami* plugin implements 90% of what you want I think. Please submit that plugin for inclusion on https://coredns.io/explugins/ (if you decide to do this)

**Comment by miekg** [comment]
Or look at *erratic* which basically does what you want already even more than the *whoami* plugin.

**Comment by miekg** [comment]
Adding wont-fix, because this can't be done in *auto*.
