### ISSUE TITLE
Meta data or label support for identity/whoami?

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#1256]
I have a unique scenario where I would like to deploy multiple CoreDNS servers in a cluster. I want each CoreDNS server in the cluster to expose certain information like label or meta-data.

CoreDNS currently support whoami plugin that could be used to show the local IP of the CoreDNS server. Though it would be nice to allow CoreDNS to be assigned with a arbitrary label or metadata and expose it through DNS or HTTP.

For example, let's say I want to deploy 3 CoreDNS servers on 3 hosts. One host is deployed in Tokyo and another two hosts are deployed in California. I would like to have the first host with the label of:
`location=tokyo` and the rest two host with the label of: `location=california`.

A feature like the above will helps a lot in a distributed system and expand the usage of CoreDNS in more interesting ways.

**Comment by miekg** [comment]
Like the `-local` option in SkyDNS? https://github.com/skynetservices/skydns#commandline-flags
Or why not use the *chaos* plugin ?

**Comment by yongtang** [comment]
Ah chaos plugin seems to be almost there.

Maybe we could an additional `label.coredns`, in addition to the existing `version.bind`, `version.server`, `authors.bind`, `hostname.bind`, `id.server`?

That could be served as the identity of `coredns`, just like `bind` (with `version.bind`,`authors.bind`).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Meta data or ..." ]
>Ah chaos plugin seems to be almost there.
>
>Maybe we could an additional `label.coredns`, in addition to the existing `version.bind`, `version.server`, `authors.bind`, `hostname.bind`, `id.server`?
>
>That could be served as the identity of `coredns`, just like `bind` (with `version.bind`,`authors.bind`).

Or implement an *nsid* plugin: https://tools.ietf.org/html/rfc5001

Problem with adding another label is that you define another TLD...

/Miek

--
Miek Gieben

**Comment by yongtang** [comment]
I am not very familiar with NSID protocol but give it a try in #1273 nevertheless.
