### ISSUE TITLE
rewrite: Support wildcard domain matching

### ISSUE THREAD

**Issue by jpds** [coredns/coredns#1260]
I'd like to use the rewrite plugin to change all requests to Ubuntu mirrors as follows:

```
rewrite name *.archive.ubuntu.com mirror.local.com
```

However, the rewrite plugin doesn't currently support wildcards.

**Comment by miekg** [comment]
That's a nice idea/enhencement

**Comment by greenpau** [comment]
@jpds , I think this is resolved in #1297 

```
rewrite name regex (.*)\.archive.ubuntu.com {1}.mirror.local.com
```

or

```
rewrite name regex (.*)\.archive\.ubuntu\.com mirror.local.com
```

**Comment by greenpau** [comment]
> That's a nice idea/enhencement

@miekg , is the issue ripe for closing?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] rewrite: Supp..." ]
>> That's a nice idea/enhencement
>
>@miekg , is the issue ripe for closing?

looks like it :) (sorry haven't been following closely as John was doing most of 
it)

**Comment by johnbelamaric** [comment]
#1297
