### ISSUE TITLE
k8s plugin: valid queries throw errors

### ISSUE THREAD

**Issue by Morriz** [coredns/coredns#1265]
Hi, if I use `nslookup` on valid k8s service names, the intermediary steps that don't satisfy the request write errors in the logs (why?). So `nslookup kubernetes` (from `monitoring` namespace) shows:
```
29/Nov/2017:23:16:11 +0000 [ERROR 0 kubernetes.monitoring.svc.cluster.local. A] no items found
29/Nov/2017:23:16:11 +0000 [ERROR 0 kubernetes.svc.cluster.local. A] invalid query name
29/Nov/2017:23:16:11 +0000 [ERROR 0 kubernetes.cluster.local. A] invalid query name
```
But even if I do `nslookup kubernetes.default` do see these errors:
```
29/Nov/2017:23:18:44 +0000 [ERROR 0 kubernetes.default.monitoring.svc.cluster.local. A] no items found
```
Maybe this should only be written at level debug?

**Comment by johnbelamaric** [comment]
This is in v0.9.10 or master?

@chrisohaver

**Comment by Morriz** [comment]
Ah, yes, I am using a helm chart with `coredns/coredns:006` image.

**Comment by Morriz** [comment]
upgrading the image to `0.9.10` gives this error:
```
plugin/errors: invalid log file: stderr
```
should I file an issue for that?

**Comment by Morriz** [comment]
Nevermind, I read the docs, and see that there are no more files used, just stdout and stderr. Nice.

So by upgrading I don't see the original errors any more, but now this:
```
plugin/kubernetes: /etc/coredns/Corefile:6 - Error during parsing: unknown property 'cidrs'
```

**Comment by Morriz** [comment]
Ok, the `cidrs` section is gone, by removing that I am clear.

**Comment by chrisohaver** [comment]
> intermediary steps that don't satisfy the request write errors in the logs (why?)

FYI, This is due to the kubernetes deep search path and high n-dots. Those errors are logged because they are in fact individual queries made from the client. See the autopath plugin for more background and a unique fix for this.

**Comment by chrisohaver** [comment]
> See the autopath plugin for more background and a unique fix for this.

Actually, it looks like we don’t cover the background of the issue in docs. #747 provides some background.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] k8s plugin: v..." ]
>Ah, yes, I am using a helm chart with `coredns/coredns:006` image.

I've made a PR to update that chart to the latest CoreDNS: https://github.com/kubernetes/charts/pull/2771
Zero traction on that PR, so I'm sure what the state of that Chart is... I see 
they still use '011' which is almost three releases ago.

/Miek

--
Miek Gieben

**Comment by Morriz** [comment]
Ok, nice @miekg, but I see the chart pr is incomplete and will throw an error regarding the cidrs section. See my finding above. Also, there are now more options for the kubernetes plugins (like endpoints etc) which are not found in your pr. It would be thorough to incorporate them. Maybe other plugins too?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] k8s plugin: v..." ]
>Ok, nice @miekg, but I see the chart pr is incomplete and will throw an error regarding the cidrs section. See my finding above. Also, there are now more options for the kubernetes plugins (like endpoints etc) which are not found in your pr. It would be thorough to incorporate them. Maybe other plugins too?

so far nobody sent any feedback, so I haven't spent anymore time on it - feel 
free to comment on the PR though.
