### ISSUE TITLE
Rewrite: Move from Caddy plugin implementation to the std plugin pkg

### ISSUE THREAD

**Issue by mxschmitt** [coredns/coredns#1279]
Hello,

I'd like to discuss a bit about the `Caddy` plugin implementation in CoreDNS and the replacement of it to the std [plugin](https://golang.org/pkg/plugin/) package which was introduced in Go 1.8.
Generally, I like to use a plugin architecture with a given structure and wide usage like in Caddy. But I think that it can be easier and cleaner to move to the new plugin engine.

Pros:
- Easier plugin plugin and play system: there's no need to compile always completely new from scratch
- Cleaner code: there is no need to import as _ package which is in my opinion really dirty

Cons:
- It's a beta feature
> The plugin support is currently incomplete, only supports Linux, and has known bugs. Please report any issues. [Source](https://golang.org/pkg/plugin/)
- No windows support: Not all architectures are yet supported

In general, there isn't it so easy to switch from one to another plugin engine instantly. We need to support the old method additional some time span and then remove it.

Thank you for your ideas and minds about this topic.

**Comment by miekg** [comment]
I agree the recompiling to add a plugin is somewhat cumbersome. I rather not go after this alone, but wait for Caddy to make a move and follow that.

**Comment by yongtang** [comment]
See some discussion in Caddy:
https://caddy.community/t/go-1-8-plugin-model/934/30

**Comment by miekg** [comment]
closing here, 'cause nothing will change in the foreseeable future.
