### ISSUE TITLE
Feature request: response templating

### ISSUE THREAD

**Issue by rtreffer** [coredns/coredns#1289]
We have a few places where we resolve either A records or PTR records based on templates. So far we've usually templated out whole RFC 1035 zone files.
We also have cases where we know that an appended search domain won't resolve and we could short-circuit it to NXDOMAIN.

This is related to the `reverse` plugin which was not an option due to the limited templating and limited scope.

***I'd like to suggest (and implement) a template plugin that can generate responses based on the incoming query and a response template.***

It would combine
* A [regexp](https://golang.org/pkg/regexp/) match
* [Go templates](https://golang.org/pkg/text/template/)
* [RFC 1035 style RR fragments](https://github.com/miekg/dns/blob/3bbde607ac2132f47c307b292594a1af4f619fde/scan.go#L105)

I managed to get the following working locally (Note: this is only my draft to see if it would work, everything up for debate):
```
.:1053 {
    proxy . 8.8.8.8

    template ANY ANY "[.]invalid[.]$" {
      rcode NXDOMAIN
      answer "invalid. 60 {{ $class }} SOA a.invalid. b.invalid. (1 60 60 60 60)"
    }
    template IN A "ip-10-(?P<b>[0-9]*)-(?P<c>[0-9]*)-(?P<d>[0-9]*)[.]example[.]$" {
      answer "{{ $name }} 60 IN A 10.{{ $.b }}.{{ $.c }}.{{ $.d }}"
    }
    template IN PTR "(?P<d>[0-9]*).(?P<c>[0-9]*).(?P<b>[0-9]*).10.in-addr.arpa.arpa.$" {
      answer "{{ $name }} 60 IN PTR ip-10-{{ $.b }}-{{ $.c }}-{{ $.d }}.example."
    }
    template IN MX ip-10-(?P<b>[0-9]*)-(?P<c>[0-9]*)-(?P<d>[0-9]*)[.]example[.]$ {
      answer "{{ $name }} 60 IN MX 10 {{ $name }}"
      additional "{{ $name }} 60 IN A 10.{{ $.b }}.{{ $.c }}.{{ $.d }}"
    }
}
```

The only problematic thing I've found so far is that the caddyfile parser tries to replace `{$...}` which means `{{$name}}` would break caddy/coredns while `{{ $name }}` works.

Wiring this up is pretty straight forward, simpler than reverse and way more flexible at the cost of more you need to know to use it (regexp, go templates, RFC 1035 syntax)

**Comment by miekg** [comment]
This is an awesome idea.

**Comment by miekg** [comment]
That Go templating clash with Caddy's syntax is a bit unfortunate though, and pretty non-obvious when it bytes you (I guess)

**Comment by rtreffer** [comment]
We can actually get away without that. I tried to pull of this gem from prometheus to make go templates more accessible: https://github.com/prometheus/prometheus/blob/master/rules/alerting.go#L205

But that's a bad idea if variables can cause issues like this. I'll go with normal go template notation (e.g. `.Group.a`) instead. That should work :man_shrugging:

**Comment by miekg** [comment]
> rcode NXDOMAIN

In the *log* plugin we use: `class [success|denial|error|all]`. It's good to aim for some uniformity between the plugins, do IMO `rcode DENIAL` (or `denial`) would be better here.

We should/cloud also add a convience macro that does all the things the *reverse* plugin does.

**Comment by rtreffer** [comment]
This is on master.
