### ISSUE TITLE
Delegations with DNSSEC plugin

### ISSUE THREAD

**Issue by schors** [coredns/coredns#1290]
Refer #1211

Must be in AUTHORITY SECTION If delegation detected:
1. Referral to a signed zone. The DS RR contains the data which the resolver will need to validate the corresponding DNSKEY RR in the child zone's apex. DS RR from source! We need to **sign** DS record. https://tools.ietf.org/html/rfc4035 (B.4.  Referral to Signed Zone and C.4)
2. Referral to an unsigned zone. The NSEC RR proves that no DS RR for this delegation exists in the parent zone. https://tools.ietf.org/html/rfc4035 (B.5.  Referral to Unsigned Zone and C.5)

Hmmm.... B.8.  DS Child Zone No Data Error

**Comment by miekg** [comment]
True. But consider this scenario:
unsigned zone (A) + delegation to *another* unsigned zone (B.A): both use on the fly signing. 

When we get a delegation from A to B.A is needs to have a DS record. Do we ask the user to "upload" that DS record for us in zone A? If the answer is yes, then we should sign it.

Disproving the DS in the delegation is interesting as well - pretty sure the *file* plugin will do that wrong as well.

**Comment by schors** [comment]
Why do we believe that the key for B.A will be the same as for A In this case?
```
a {
    dnssec {
        key file Ka.+013+43550
    }
    proxy . 10.10.10.10
}
b.a {
    dnssec {
        key file Kb.a.+013+24330
    }
    proxy . 10.10.10.10
}
```

But I think this is a special case. The basic scheme should work first.

**Comment by miekg** [comment]
> Why do we believe that the key for B.A will be the same as for A In this case?

It's not, it's two different keys (that's were my initial impl. went wrong). I'm fine with, "there needs to be a DS which we will sign", if not we will disprove the DS with an NSEC record.

**Comment by schors** [comment]
In general, I would not yet implement an automatic DS. I would be based on the data that the plugin received on the input. Otherwise we will get an additional task to check whether we are serving a subsidiary zone. Delegating to oneself is a dirty special case
