### ISSUE TITLE
Check for all plugins being healthers not just hardcoded list

### ISSUE THREAD

**Issue by jameshartig** [coredns/coredns#1291]
Instead of hard-coding a list of healthers (https://github.com/coredns/coredns/blob/master/plugin/health/healther.go#L41), can we instead just loop over the `registry` and cast them all to Healther to see if they implement it? We would need a new external method called `Handlers()` (or similar) instead of just `Handler()`.

Reasoning: We implement our own plugins and currently we can do that by just adding lines to `plugin.cfg` in the build process, but if our plugins want to expose health information, we'd have to also patch the healther.go file, and the less patching we have to do, the better.

I'm willing to write a PR to do this, but wanted to make an issue first to discuss.

**Comment by johnbelamaric** [comment]
Certainly makes sense to me, honestly I thought that we already did that.

**Comment by miekg** [comment]
No, took easy way out here. Essentially same code as in federation and autopath.

Making this more generic makes sense.
