### ISSUE TITLE
plugin.cfg should allowed '_' as key

### ISSUE THREAD

**Issue by wenerme** [coredns/coredns#1292]
I need to import extra db driver, but plugin.cfg need a key.

https://github.com/wenerme/wps/tree/master/coredns/plugin/pdsql#install-driver

```
pdsql_mysql:github.com/jinzhu/gorm/dialects/mysql
pdsql_sqlite:github.com/jinzhu/gorm/dialects/sqlite
```

should be

```
_:github.com/jinzhu/gorm/dialects/mysql
_:github.com/jinzhu/gorm/dialects/sqlite
```

**Comment by miekg** [comment]
Why does this need to be in the `plugin.cfg` and not just in imported in your code?

**Comment by wenerme** [comment]
I think import all driver is not wise, that's why I put the plugin for me in `plugin.cfg`, instead include all the plugins by default.

**Comment by miekg** [comment]
I don't know a good solution, but plugin.cfg is not the place for this
