### ISSUE TITLE
CoreDNS distributed plugin with NSID

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#1295]
In a cloud environment when combined with auto-scaling groups (e.g., in AWS), there might be a need to assign each machine with a domain name that depends on its functionality. For example, let's say there are 5 machines in an auto-scaling groups and they are expected be assigned with domain name of:
```
worker1.tf.local. -> 172.28.10.1
worker2.tf.local. -> 172.28.10.5
worker3.tf.local. -> 172.28.10.9
ps1.tf.local.     -> 172.28.10.15
ps2.tf.local.     -> 172.28.10.16
```

It might be possible to achieve the above scenario in CoreDNS:
1. Each node announce the domain it want to use with CoreDNS' NSID plugin, e.g., node 1 (172.28.10.1) have NSID of `worker1.tf.local.` exposed, node 2 (172.28.10.5) have NSID of `worker2.tf.local.` exposed.
2. Each node tries to talk to every IP address within the subnet of `172.28.10.0/24`, and find out the NSID (if available) of all  the rest of the nodes. The list of the domains (and its IP) will be stored in memory.
3. Then each node will serve the DNS queries if the queried domain is in the above list in memory.
4. Each node can also update the domain name list (and IP) with a TTL.

Note in cloud like AWS duplication of domain names (from multiple nodes) could be avoided through information exposed in AWS API. Any even if there is a collision, the CoreDNS could simply publish the domain name with multiple A record.

This could be a useful feature where external storage or external k-v store (like zookeeper or etcd) is undesired, as they require additional maintenance efforts.

**Comment by miekg** [comment]
This is living in coredns/distributed
