### ISSUE TITLE
plugin/metrics: bind to all interfaces by default

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1302]
Prometheus plugin defaults to bind to localhost. Typically a prometheus server would not run locally on the same host as coredns.  IMO, defaulting to bind to all interfaces would be a more useful default.

**Comment by miekg** [comment]
... but an insecure default.

Doesn't `prometheus 0.0.0.0:9153` do what you want?

**Comment by chrisohaver** [comment]
What does coredns itself bind to by default?
