### ISSUE TITLE
feature: plugin/rewrite: rewrite ANSWER SECTION

### ISSUE THREAD

**Issue by greenpau** [coredns/coredns#1313]
Consider a DNS request for `ftp-us-west-1.coredns.rocks`. DNS server is `coredns`.

```
$ dig @10.1.1.1 ftp-us-west-1.coredns.rocks

; <<>> DiG 9.8.3-P1 <<>> @10.1.1.1 ftp-us-west-1.coredns.rocks
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8619
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ftp-us-west-1.coredns.rocks. IN A

;; ANSWER SECTION:
ftp.service.us-west-1.consul. 0	IN A	10.10.10.10
ftp.service.us-west-1.consul. 0	IN A	10.20.20.20
ftp.service.us-west-1.consul. 0	IN A	10.30.30.30
```

The rule that made it happen is:

```
rewrite name regex (.*)-(us-west-1)\.coredns\.rocks {1}.service.{2}.consul
```

The `ANSWER SECTION` contains entries for `ftp.service.us-west-1.consul.`

An upstream DNS server may consider the mismatch between `QUESTION`  and `ANSWER` as a MITM attack and would not return the answer:

```
;; ANSWER SECTION:
ftp.service.us-west-1.consul. IN A
```

I propose extended the rule engine for response re-writing (but only when there is a match in a first place).

```
rewrite name regex REQ_MATCH REQ_REPLACE RESP_MATCH RESP_REPLACE
rewrite name regex (.*)-(us-west-1)\.coredns\.rocks {1}.service.{2}.consul (.*)\.service\.(.*)\.consul {1}-{2}.coredns.rocks
```

@johnbelamaric , @miekg , your thoughts?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] feature: plugin/r..." ]
>Consider a DNS request for `ftp-us-west-1.coredns.rocks`. DNS server is `coredns`.
>
>```
>$ dig @10.1.1.1 ftp-us-west-1.coredns.rocks
>
>; <<>> DiG 9.8.3-P1 <<>> @10.1.1.1 ftp-us-west-1.coredns.rocks
>; (1 server found)
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8619
>;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
>
>;; QUESTION SECTION:
>;ftp-us-west-1.coredns.rocks. IN A
>
>;; ANSWER SECTION:
>ftp.service.us-west-1.consul. 0	IN A	10.10.10.10
>ftp.service.us-west-1.consul. 0	IN A	10.20.20.20
>ftp.service.us-west-1.consul. 0	IN A	10.30.30.30
>```

random thought (busy hacking on google/metallb), but why are these TTLs 0?

**Comment by greenpau** [comment]
> random thought (busy hacking on google/metallb), but why are these TTLs 0?

Consul configuration with caching disabled. See [DNS Caching](https://www.consul.io/docs/guides/dns-cache.html)

>> By default, Consul serves all DNS results with a **0 TTL** value. This prevents any caching. The advantage is that each DNS lookup is always re-evaluated, so the most timely information is served. However, this adds a latency hit for each lookup and can potentially exhaust the query throughput of a cluster.

*****

> metallb

@miekg , thank you for mentioning it. Never heard of it. Will read about BGP in it. Sounds like fun! 😸

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] feature: plug..." ]
>>> By default, Consul serves all DNS results with a **0 TTL** value. This prevents any caching. The advantage is that each DNS lookup is always re-evaluated, so the most timely information is served. However, this adds a latency hit for each lookup and can potentially exhaust the query throughput of a cluster.

ack, noted!

>> metallb
>
>@miekg , thank you for mentioning it. Never heard of it. Will read about BGP in it. Sounds like fun! 😸

np :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] feature: plug..." ]
>Closed #1313 via #1318.

Can someone write a few lines in the wiki release doc about this? Thanks!

/Miek

--
Miek Gieben

**Comment by greenpau** [comment]
@miekg, I think @johnbelamaric added a line in 1.0.5.

**Comment by johnbelamaric** [comment]
yes, but please submit a PR for the README updates, I just noticed they are not done

**Comment by greenpau** [comment]
@johnbelamaric , will do!
