### ISSUE TITLE
allow binding to a specific IP

### ISSUE THREAD

**Issue by caffeinejolt** [coredns/coredns#1314]
I wish coredns allowed binding to a specific IP and/or interface.  Is there any plan to add that?

**Comment by johnbelamaric** [comment]
You can already do that with the bind plugin (for an IP).


On Dec 14, 2017, at 6:35 PM, caffeinejolt <notifications@github.com<mailto:notifications@github.com>> wrote:


I wish coredns allowed binding to a specific IP and/or interface. Is there any plan to add that?

**Comment by caffeinejolt** [comment]
Doh: https://coredns.io/plugins/bind/

I falsely assumed that would be part of the core and not a plugin - my bad!
