### ISSUE TITLE
Consider supporting Service Fabric drop-in DNS replacement

### ISSUE THREAD

**Issue by AceHack** [coredns/coredns#1330]
Please consider adding support for Service Fabric as coredns drop-in replacement for service fabric DNS.

This should work for both windows and linux versions of service fabric
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice

Here is the service fabric issue for reference
https://github.com/Azure/service-fabric-issues/issues/727

**Comment by yongtang** [comment]
@AceHack This might be an interesting area. Do you have specific details about what you would expect for CoreDNS to work on Azure?

**Comment by AceHack** [comment]
Service Fabric is Microsoft's free orchestration engine that runs on-premises or in any cloud.  They currently have a built-in cluster DNS server but it's missing some core concepts like namespaces and such.  It was an afterthought and has a weak app DNS suffix only.  I would love to see CoreDNS plugins and extensibility expanded to include Service Fabric support.  Also, you guys have a ton of community support, maybe some of that community will hear about Service Fabric and starting contributing.

Service Fabric was my first love so to speak when it comes it orchestration engines but after using Kubernetes I've realized how far behind Service Fabric is in most things container related.  Service Fabric does have a first-class in-process stateful application/service/actor development experience but it comes at the cost of vendor lock-in SDKs.  Kubernetes has a huge advantage when it comes to deploying 3rd party applications, and most other things too for that matter.

One other thing CoreDNS could allow for is easy Service Fabric/Kubernetes cross-cluster communications.  I know a lot more would need to happen here like Service Fabric supporting CNI to fully allow this but it's a start, I also have an issue open for CNI in Service Fabric too.  I would love to see an Istio expansion between the two clusters in the future.

SF CNI - https://github.com/Azure/service-fabric-issues/issues/726

Here is some more info on Service Fabric if you are interested
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-overview
https://azure.microsoft.com/en-us/resources/samples/service-fabric-dotnet-getting-started/


I'm really trying to take the best of the Kubernetes landscape and combine it with the best of the Service Fabric landscape and hopefully, both projects get better because of it.

Thanks.

**Comment by miekg** [comment]
Where is the API defined that needs to be implemented?

**Comment by AceHack** [comment]
You can see [here](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/18667d8fabdf5edccd4e9782726c1316eff55dd8/src/Microsoft.ServiceFabric.Services/Client/ServicePartitionResolver.cs) for a client library that calls into the service fabric name service.  At the lowest level all these end up as REST calls to the service fabric http endpoints but I can't find the service fabric naming service REST documentation.

**Comment by miekg** [comment]
Well, without any API documention this can't actually be done?

**Comment by yongtang** [comment]
I haven't made much progress in understanding Azure's DNS and its SDK. Though I realized it probably makes sense to have AWS route53 support for coredns as well. A lot of kubernetes clusters are deployed in AWS (and soon with coredns providing DNS for k8s) so there is a natural need for that.
I will work on route53 support first.

**Comment by miekg** [comment]
@AceHack can you come up with a spec? Otherwise there is little use in keeping this issue open.
