### ISSUE TITLE
plugin/kubernetes: should we answer this?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1331]
I have a service called coredns:
~~~
% kubectl get svc coredns
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
coredns   LoadBalancer   10.104.110.40   192.168.1.252   53:32377/UDP   9m
~~~

Now this returns something:
```
% dig svc coredns.pod.cluster.local

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25762
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;coredns.pod.cluster.local.	IN	A

;; ANSWER SECTION:
coredns.pod.cluster.local. 5	IN	CNAME	*.
*.			5	IN	A	10.96.0.1
*.			5	IN	A	10.104.110.40
*.			5	IN	A	10.96.0.10

;; Query time: 27 msec
````

**Comment by chrisohaver** [comment]
What does the corefile look like, and how is the service/endpoints defined (etc)?

**Comment by miekg** [comment]
Cluster coredns is 1.9 kubeadm setup (can access cluster because not a home), so that standard that we had (didn't include `pod insecure` I think, but I'll double check).

coredns deploy is defined in the attached yaml file
[coredns.yaml.txt](https://github.com/coredns/coredns/files/1600168/coredns.yaml.txt)

**Comment by chrisohaver** [comment]
The attached yaml doesn't have a `kubernetes` stanza...

**Comment by miekg** [comment]
Sorry to be ignorant here, but what would that do?

**Comment by chrisohaver** [comment]
Ah - i see - you didn't attach the yaml of the cluster-dns coredns.  I meant to ask for that corefile, not the corefile of the service you are querying. 

A few things that are confusing:

`dig svc coredns.pod.cluster.local` seems like an unusual query.  This is querying the name `svc` ... for type `coredns.pod.cluster.local `.  I'm guessing a typo in the comment? 

In `coredns.pod.cluster.local` the "coredns" segment is the namespace ... which means it's an incomplete name (behavior not defined in spec). Do you have a namespace named `coredns`?  Is the service `coredns` in a namespace  also named`coredns`?  This should not be a problem - just confusing.

The spec only supports dashed IP addresses for pod type dns-names. For example: If `pods insecure` or `pods verified` are enabled, and your coredns load balancer service is in a namespace called `coredns` then `10-104-110-40.coredns.pod.cluster.local` should have a record.

It's possible that the bare namespace query of a pod type dns name is causing coredns to take on a wildcard behavior.  Though I didnt think we supported wild cards for pod type dns queries.

The `CNAME` bit is mysterious.  CNAMES should only come into play with external services, and when autopath is enabled... which it is not by default. 

That coredns is giving a CNAME answer for a bare namespace is probably  wrong.  Where are the A record coming from for `*.` ?

**Comment by chrisohaver** [comment]
IMO, if `coredns` is a namespace, then `coredns.pod.cluster.local.` should return `NODATA`.

I can't think of any configuration where the odd cname/wildcard answer would be valid..

**Comment by chrisohaver** [comment]
BTW - I cannot replicate this behavior with default coredns deployed as cluster-dns (with pods insecure enabled).

**Comment by miekg** [comment]
Thanks for looking in to. Yes I see I left out the namespace. I'll doublecheck this evening/tomorrow.

**Comment by chrisohaver** [comment]
FYI - I may have inadvertently tested on `kube-dns` earlier when I could not replicate the issue.

Testing on coredns, I don't see this exact behavior, but i see equally wrong/confusing behavior, where any pod query (existing or not) returns a full list of all services (not pods ... services).

So, it looks like pod lookups are _extremely_ broken.  Looking into it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>FYI - I may have inadvertently tested on `kube-dns` earlier when I could not replicate the issue.
>
>Testing on coredns, I don't see this exact behavior, but i see equally wrong/confusing behavior, where any pod query returns a full list of all services.
>
>So, it looks like pod lookups are _extremely_ broken.  Looking into it.

Ok :(

I wonder why this isn't captured in any testing which is already pretty 
extensive (but that's a later concern)

**Comment by chrisohaver** [comment]
Ugh.  I just noticed that minikube addon manager spun up an old custom build of coredns for some reason... I need to disable addon manager - it seems to act unpredictably when switching between minikube profiles.

**Comment by chrisohaver** [comment]
OK - now running 1.0.1 coredns... :)

I can replicate the issue.  It looks like if you pass an "invalid" ip segment to a pod query, you'll get these bizzare responses... a CNAME that points to a series of A records of all services.  For example:

```
dnstools# host -v blah.nothere.pod.cluster.local.
Trying "blah.nothere.pod.cluster.local"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10919
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 20, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;blah.nothere.pod.cluster.local.	IN	A

;; ANSWER SECTION:
blah.nothere.pod.cluster.local.	5 IN	CNAME	blah.
blah.			5	IN	A	192.168.99.100
blah.			5	IN	A	10.0.0.243
blah.			5	IN	A	10.0.0.121
blah.			5	IN	A	10.0.0.93
blah.			5	IN	A	10.0.0.110
blah.			5	IN	A	10.0.0.1
blah.			5	IN	A	10.0.0.244
blah.			5	IN	A	172.17.0.254
blah.			5	IN	A	172.17.0.255
blah.			5	IN	A	10.0.0.151
blah.			5	IN	A	10.0.0.120

...

```

Also if you don't pass an ip segment, it treats is as a wildcard, and does the same thing

**Comment by chrisohaver** [comment]
> I wonder why this isn't captured in any testing which is already pretty extensive (but that's a later concern)...

The query pod tests are not very extensive.  And there are no negative tests for pod queries, hence this escaped bug.

**Comment by miekg** [comment]
I'll try to distill this into a (failing) test.

**Comment by chrisohaver** [comment]
> I'll try to distill this into a (failing) test.

I can add it, should be very easy.

**Comment by miekg** [comment]
sgtm.
(I'll still poke around, cause I want to understand the bug more precisely)

**Comment by chrisohaver** [comment]
OK cool.

Per code, looks like it only affects `pods insecure`, not `pods verified`.

The reason appears to be that we don't validate the ip segment is an actual IP before defining it as the host.  If the host is empty, or a non-ip string, the Backend later treats it as a `CNAME`, and chaos ensues.  Not sure yet why that chaos includes adding a list of all services...  but that's downstream of the initial bug.

Easy fix is to check that the ip segment of the query is a valid ip before sending off to the backend.
Might be worth understanding why the backend adds all services when looking up the `CNAME` target `A` records to make sure there isn't another bug lurking there.

**Comment by miekg** [comment]
I don't like this validating step, i.e. we should do the right thing regardless of the crap in the qname. Obviously strange things happen here....

**Comment by chrisohaver** [comment]
> I don't like this validating step

OK, thats cool.  I'll leave it to you then.
