### ISSUE TITLE
Metrics Request: I'm going to be overloaded

### ISSUE THREAD

**Issue by swade1987** [coredns/coredns#1342]
It'd be great if CoreDNS exposed a metric stating when it's becoming overloaded so users know when they need to scale.

**Comment by miekg** [comment]
We might utilize a simple query to does a simple healtcheck query (dig @localhost +norec . NS), or better yet call the Server's ServeDNS and measure the latency and export that in a histogram...

Another way would be to utilize the current exported latency metrics, but this involves network latency as well, which may or may not tell you something about CoreDNS. In my view, leaving the network out makes it easier to reason about "is this pod/process" overloaded.

**Comment by miekg** [comment]
Note that the decision "I'm overloaded" should be left to an external control loop.
