### ISSUE TITLE
kubernetes/dns/issue/116: check if we have the same problem

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1343]
See https://github.com/kubernetes/dns/issues/116

Check and test if we have the same problem.

**Comment by chrisohaver** [comment]
~~Yes, we do.~~

~~Seems like it would be an easy fix, but I don't see an early exit in findServices() ... which implies that the API may only be returning one of the endpoints - or we squash the record downstream.  Need to debug more to understand what is happening.~~

**Comment by chrisohaver** [comment]
Oops.  Correction - **No, we don't have the issue.**  The minikube cluster I tested on had both kube-dns and coredns addons active ... result was that kube-dns was processing the requests.
  
```
dnstools# host -t A depl-1-service.default.svc.cluster.local.
depl-1-service.default.svc.cluster.local has address 172.17.0.11
depl-1-service.default.svc.cluster.local has address 172.17.0.12

dnstools# host -t A depl-1-host.depl-1-service.default.svc.cluster.local.
depl-1-host.depl-1-service.default.svc.cluster.local has address 172.17.0.11
depl-1-host.depl-1-service.default.svc.cluster.local has address 172.17.0.12

```

**Comment by miekg** [comment]
W00T. Thanks for checking.
