### ISSUE TITLE
How to handle queries when not healthy/ready?

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1347]
See https://github.com/kubernetes/dns/issues/186

I think we could add a `next.Healther()` check here:

https://github.com/coredns/coredns/blob/master/plugin/plugin.go#L73

and return SERVFAIL if the next plugin is not healthy.

**Comment by chrisohaver** [comment]
Sounds good.  

That would (undesirably) block processing of a request by any ready plugins down-chain of an unready plugin (even if the up-chain plugin is not supposed to process the request).  But working around that would require changes to every plugin that can be unready.

**Comment by miekg** [comment]
But we already know this when the query goes in, i.e. see #1329 But I'm not sure globally blocking a query would be a good idea.

I think this should implemented on a per plugin basis, as to make it a plugin-local decision. 

Also for kubernetes specifically, we already spins for HasSynced on startup, so we shouldn't have 186 here. 

Can HasSynced() actually be false again?

**Comment by johnbelamaric** [comment]
Not according to this comment:

https://github.com/kubernetes/client-go/blob/master/tools/cache/controller.go#L127

So I guess this is a non-issue for us.

**Comment by miekg** [comment]
Note, that even with HasSynced () we have this crazy sleep 3 in the integration tests... so something might be still off here?

**Comment by chrisohaver** [comment]
> so something might be still off here?

The integration tests have not been updated to work with the health-aware implementation.  Note that simply removing the sleep delays is not enough.  The integration test would have to delay sending queries until the coredns service has a ready pod.
