### ISSUE TITLE
plugin/kubernetes: DNS records for services

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1357]
I've got this service definition:
~~~
apiVersion: v1
kind: Service
metadata:
  name: coredns
spec:
  ports:
  - name: coredns
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: coredns
  type: LoadBalancer
  loadBalancerIP: 192.168.1.252
~~~

describing the service shows:
~~~
% kubectl describe service coredns
Name:                     coredns
Namespace:                default
Labels:                   <none>
Annotations:              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"coredns","namespace":"default"},"spec":{"loadBalancerIP":"192.168.1.252","port...
Selector:                 app=coredns
Type:                     LoadBalancer
IP:                       10.96.77.39
IP:                       192.168.1.252
LoadBalancer Ingress:     192.168.1.252
Port:                     coredns  53/UDP
TargetPort:               53/UDP
NodePort:                 coredns  30332/UDP
Endpoints:                10.244.1.46:53,10.244.1.47:53,10.244.2.51:53 + 1 more...
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
~~~

A dig returns the clusterIP, so far so good:
~~~
% dig coredns.default.svc.cluster.local.
...
coredns.default.svc.cluster.local. 5 IN	A	10.96.77.39
~~~
For a headless service I would get all pod IPs (so far so good).

Now I query: `*.coredns.default.svc.cluster.local`, which does return the pods:

~~~
*.coredns.default.svc.cluster.local. 5 IN A	10.244.1.46
*.coredns.default.svc.cluster.local. 5 IN A	10.244.1.47
*.coredns.default.svc.cluster.local. 5 IN A	10.244.2.51
*.coredns.default.svc.cluster.local. 5 IN A	10.244.3.41
~~~
Note that this is super handy, but it's a bit strange and makes headless vs a normal service rather special.

**Comment by chrisohaver** [comment]
This is expected, and behaves per k8s cluster dns spec.
You can query endpoint dns names directly regardless of what type of service they sit behind.

**Comment by rikatz** [comment]
As this is expected (and a great feature), this is not part of https://github.com/kubernetes/dns/blob/master/docs/specification.md

I've tested this behaviour in SkyDNS and it doesn't returns me the endpoints/PODs IPs, instead it returns the ClusterIP.

So my question is: should the SPEC of KubeDNS be changed, or should we just document this in CoreDNS?

I'm asking this because I've been looking exactly for this behaviour, but it's not documented anywhere :) As CoreDNS is the future of Kubernetes DNS, I think those 'question/answer' should be documented somewhere, as is the SkyDNS specification :)

Thank you!!

**Comment by rikatz** [comment]
And by the way, this is documented here: https://coredns.io/plugins/kubernetes/

About 'Wildcards', but the behaviour is not documented, only that wildcards exists :) I'll do some tests and improve this Kubernetes Docs ;)

Thanks for the great work guys

**Comment by johnbelamaric** [comment]
Yes, we can update the spec, but we should bump the schema version in the spec (which requires a bump in the record returned by CoreDNS as well). This way, the version of the schema running is discoverable.

**Comment by rikatz** [comment]
Hum, nice.

About this record, I've noticed that it always returns the PODs in the same order. So this must not be used as a RR DNS records, as the first IP will always be the same (and OS as Linux doesn't randomize the answer received)

**Comment by johnbelamaric** [comment]
See the `loadbalancer` plugin, it may help with that.

**Comment by chrisohaver** [comment]
The k8s spec says that all endpoints must have an a record ... in this snip...

>There must also be an A record of the following form for each ready endpoint with hostname of <hostname> and IP address <endpoint-ip>. If there are multiple IP addresses for a given hostname, then there must be one such A record returned for each IP.
>
> Record Format:
> * `<hostname>.<service>.<ns>.svc.<zone>. <ttl> IN A <endpoint-ip>`

Wildcards behavior is described very tersely in the plugin documentation.

> If a label is a valid wildcard (*, or the word “any”), then that label will match all values.

So, it follows that if you put a wildcard in the `hostname` field, you will get all of the endpoints in the service.

**Comment by rikatz** [comment]
@chrisohaver So SkyDNS is not following the Specs from kubernetes? Maybe I'm also using an old version (need to check here).

Anyway I've made this more clear in the docs, if this is some that is interesting. Otherwise I can close the PR without being merged :)

**Comment by chrisohaver** [comment]
No, your changes to the docs are good.  They illustrate a use case, which is always helpful in docs.
I have approved them already.  Thanks!

**Comment by rikatz** [comment]
@chrisohaver Thanks :) I'll try to make some further tests and improve the Docs (at least kubernetes, that are my case) ;)
