### ISSUE TITLE
plugin/template: exported metrics

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1362]
/cc @rtreffer 

the metrics exported by *template* have the regexp as a label? How does that look in real life? (Haven't run and grabbed any metrics). Are those regexp-strings actually usable was labels? Slight feeling this maybe too unwieldy?

**Comment by rtreffer** [comment]
Looks like I messed up registration. I have to fix that.

Real world would look like this:
```
coredns_template_matches_total{regex="^ip-(?P<a>10)-(?P<b>[0-9]*)-(?P<c>[0-9]*)-(?P<d>[0-9]*)[.]dc[.]example[.]$"} 3
```

Why? I want to give users a way to find the broken section in the config. Metrics are good to detect it and the regex helps to find the source of the problem.

Some sort of debug logging might help, too.

**Comment by miekg** [comment]
That looks really ugly to be honest. Would some other identifier be better, like the sequence number of the regexp used? First one in the config gets value 1, second 2, etc. ?

**Comment by rtreffer** [comment]
With the zone rework (#1360) zone + type + class should work as a replacement, wdyt?

**Comment by miekg** [comment]
yes that would be nicer

**Comment by rtreffer** [comment]
Fixed in master.
