### ISSUE TITLE
RRSIG caching issue

### ISSUE THREAD

**Issue by Isolus** [coredns/coredns#1378]
After 8 days of operation (with file and without changing the zone file) the cached signatures are still served (and they are only signed for 8 days).
[dnssec.go#L40](https://github.com/coredns/coredns/blob/master/plugin/dnssec/dnssec.go#L40) states that "Signatures will be cached for a short while.".
But I can't find any code where expired or old signatures are dropped.

**Comment by miekg** [comment]
hmmm, me neither :(
I 100% sure I thought about, but somehow that didn't translated in to code.

**Comment by miekg** [comment]
If you change `eightDays  = 8 * 24 * time.Hour` into something smaller like `1 * 24 * time.Hour` you should see failures earlier. Could you easily try #1385 ?

**Comment by Isolus** [comment]
I'll try and report.

But if I understand the code correctly we will run into the following problem:
We have an RRSIG in the coredns cache which is valid now and not yet expired.
However, given the TTL, the signature will expire while still in the cache of a resolver.

And even if we subtract the TTL for the validity check, we don't consider a possible clock drift between the server and a validator.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] RRSIG caching..." ]
>I'll try and report.
>
>But if I understand the code correctly we will run into the following problem:
>We have an RRSIG in the coredns cache which is valid now and not yet expired.
>However, given the TTL, the signature will expire while still in the cache of a resolver.
>
>And even if we subtract the TTL for the validity check, we don't consider a possible clock drift between the server and a validator.

You're right we need to do this at 3/4 of the validity period and then regen.
