### ISSUE TITLE
plugin removal policy

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1384]
We currently have 34 plugins and we're keep adding new ones. We should also have some rules on how to remove/deprecate plugins.

Why I'm a thinking about this? Mostly because of the new *template* plugin, which is a superset of *reverse* (I think).  So if it is possible to use *template* in the same way as *reverse*, should we then deprecate *reverse*?

Note under deprecating I consider moving it to its own repo (under the coredns org); including it by default for a release; and then dropping it from `plugin.cfg`

**Comment by rtreffer** [comment]
My wishlist for deprecation / removal as a user is
- A user-facing warning (e.g. on startup)
- A removal deadline (e.g. will be removed in the next CoreDNS release)
- Migration information (if possible)
- A good error message post-removal (e.g. "Plugin reverse was removed, please use template / see ....")
- Reason for deprecation/removal and "Is the decision final" (e.g. lack of contribution/maintenance is something that could change again

Doing all of this is likely overkill.
I'd be keen to at least get a good error message post-removal.

**Comment by miekg** [comment]
As we are going to remove some plugins this may be a good time to exercise that list, thanks @rtreffer 

E.g. we could add a generic setup function that can be used to emit such a warning.
