### ISSUE TITLE
Create generic test to test for class and type mnemonics case-sensitivity in plugins

### ISSUE THREAD

**Issue by cricketliu** [coredns/coredns#1393]
The template plugin doesn't understand "any" or "in" (in lowercase) as classes, or "any" as a type.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Class and type mn..." ]
>The template plugin doesn't understand "any" or "in" (in lowercase) as classes, or "any" as a type.

This is a result of using miekg/dns `StringToClass` and friends which only 
defines these as uppercase. I don't think we want to allow lowercase though as 
this makes them stand out a bit.

Interesting that you mention it though; I always thought these had to be 
uppercase? Do you have an RFC ref?

**Comment by rtreffer** [comment]
At least `dig` seem to accept any case. This is the first time I've heard of lower case mnemonics to be honest, I'd really like to see a RFC section about mnemonics case.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Class and typ..." ]
>At least `dig` seem to accept any case. This is the first time I've heard of lower case mnemonics to be honest, I'd really like to see a RFC section about mnemonics case.

come join the centi-thread: https://github.com/miekg/dns/issues/577

/Miek

--
Miek Gieben

**Comment by cricketliu** [comment]
RFC 1035 section 2.3.3 does say:  "For all parts of the DNS that are part of the official protocol, all
comparisons between character strings (e.g., labels, domain names, etc.)
are done in a case-insensitive manner."

**Comment by miekg** [comment]
No way :) I did not know that. But discussion should be punted towards
miekg/dns.

**Comment by rtreffer** [comment]
This also implies that mixed-case is allowed....
```
# dig www.google.com AaAa +short
2a00:1450:4016:80c::2004
```

Another fun thing I found while searching for DNS and case: DNS _should_ preserve the case wherever possible. E.g. `www.google.com` should be answered with `www.google.com` while `WWW.GOOGLE.COM` should be answere with `WWW.GOOGLE.COM`.

I'm not sure if we do that....

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Class and typ..." ]
>This also implies that mixed-case is allowed....
>```
># dig www.google.com AaAa +short
>2a00:1450:4016:80c::2004
>```
>
>Another fun thing I found while searching for DNS and case: DNS _should_ preserve the case wherever possible. E.g. `www.google.com` should be answered with `www.google.com` while `WWW.GOOGLE.COM` should be answere with `WWW.GOOGLE.COM`.
>
>I'm not sure if we do that....

Good point. I made an effort in the plugins I wrote to do this. But not every 
plugin has tests for this.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
We could probably `strconv.ToUpper` them all there.

**Comment by miekg** [comment]
See #/1403

**Comment by miekg** [comment]
#1403 is a dup

**Comment by miekg** [comment]
closing this with infeasible. This is impossible to do in a generic way, because the number of permutations. Also seems more applicable to per plugin tests.
