### ISSUE TITLE
CoreDNS 1.0.4

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1397]
Because of https://github.com/miekg/dns/issues/627 we need a new release of CoreDNS.

My plan is to use the 1.0.3 tag, recompile with a patched miekg/dns and release that as 1.0.4. Then 1.0.5 can follow quite quickly with a bunch of fixes and updates.

**Comment by miekg** [comment]
I've got a release up on github - which should mitigate the issue I'm just check with Tom if that's really true. The release looks a bit messy; I've build it from a branch, but it looks gh-release tag it from master :/

Prolly going to follow up with 1.0.5 rather quickly which will be released from master - still with patched miekg/dns unless we've then publically committed the fix to miekg/dns.

**Comment by johnbelamaric** [comment]
We should move the tag to f1c8bdae which is the commit it is actually built on.

**Comment by miekg** [comment]
move is: remove tag, checkout that commit, re-tag, push?

**Comment by johnbelamaric** [comment]
yes, done

**Comment by miekg** [comment]
yeah, released.
