### ISSUE TITLE
Duplicate NS entries after zone transfer

### ISSUE THREAD

**Issue by Isolus** [coredns/coredns#1400]
I'm using two coredns instances. One uses the file plugin and the other uses the secondary plugin. After each change of a zone file, the transfer succeeds. The answers from the primary instance are correct. But the secondary starts to answer with the old and the new NS records (all other answers seem to be correct too):

This is the result after 4 changes to the zone file:
```# dig -t NS example.org @localhost

; <<>> DiG 9.9.5-9+deb8u14-Debian <<>> -t NS example.org @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60058
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;example.org.		IN	NS

;; ANSWER SECTION:
example.org.	3600	IN	NS	ns1.example.net.
example.org.	3600	IN	NS	ns2.example.net.
example.org.	3600	IN	NS	ns1.example.net.
example.org.	3600	IN	NS	ns2.example.net.
example.org.	3600	IN	NS	ns1.example.net.
example.org.	3600	IN	NS	ns2.example.net.
example.org.	3600	IN	NS	ns1.example.net.
example.org.	3600	IN	NS	ns2.example.net.

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Thu Jan 18 10:02:00 CET 2018
;; MSG SIZE  rcvd: 178```

**Comment by miekg** [comment]
We reading the same email list :)

We're apparently not clearing the NS set on receiving the new zone - which I can see happening, 'cause we're treating the zone apex a bit special.

Having a test for this would +1, but it's prolly pretty hard to setup properly.

**Comment by miekg** [comment]
I'm using coredns as a secondary for (I think) a BIND9 and don't see this NS duplication. Which could mean this sits in the sending side of the transfer, but then it would be strange if it doesn't show up in the primary. It's a bug, so being weird is allowed.

**Comment by miekg** [comment]
a `dig axfr` should show the problem as well? I'll need more info on your setup to understand this. Can you add this?

**Comment by Isolus** [comment]
The config for the secondary looks like this:
```
example.org {
        dnssec {
                key file /home/coredns/config/K<...>.private
        }
	secondary example.org {
                transfer from <primary-ip>
        }
	errors
}
```

`dig afxr` on primary:
```
dig axfr @<primary-ip> exmaple.org

; <<>> DiG 9.9.5-9+deb8u14-Debian <<>> axfr @<primary-ip> exmaple.org
; (1 server found)
;; global options: +cmd
exmaple.org.	3600	IN	SOA	ns1.exmaple.net. dnsmaster.exmaple.net. 2018011701 200 100 604800 3600
exmaple.org.	3600	IN	NS	ns1.exmaple.net.
exmaple.org.	3600	IN	NS	ns2.exmaple.net.
exmaple.org.	3600	IN	A	<...>
exmaple.org.	3600	IN	AAAA	<...>
exmaple.org.	3600	IN	SOA	ns1.exmaple.net. dnsmaster.exmaple.net. 2018011701 200 100 604800 3600
;; Query time: 141 msec
;; SERVER: <primary-ip>#53(<primary-ip>)
;; WHEN: Thu Jan 18 12:13:49 CET 2018
;; XFR size: 20 records (messages 2, bytes 1162)
```

`dig afxr` on secondary:
```
dig axfr @<secondary-ip> exmaple.org

; <<>> DiG 9.9.5-9+deb8u14-Debian <<>> axfr @<secondary-ip> exmaple.org
; (1 server found)
;; global options: +cmd
exmaple.org.	3600	IN	SOA	ns1.exmaple.net. dnsmaster.exmaple.net. 2018011801 200 100 604800 3600
exmaple.org.	3600	IN	NS	ns1.exmaple.net.
exmaple.org.	3600	IN	NS	ns2.exmaple.net.
exmaple.org.	3600	IN	NS	ns1.exmaple.net.
exmaple.org.	3600	IN	NS	ns2.exmaple.net.
exmaple.org.	3600	IN	AAAA	<...>
exmaple.org.	3600	IN	A	<..>
exmaple.org.	3600	IN	SOA	ns1.exmaple.net. dnsmaster.exmaple.net. 2018011801 200 100 604800 3600
;; Query time: 0 msec
;; SERVER: <secondary-ip>#53(<secondary-ip>)
;; WHEN: Thu Jan 18 12:51:54 CET 2018
;; XFR size: 22 records (messages 2, bytes 1256)
```

**Comment by miekg** [comment]
And the primary uses the *file* plugin with reload enabled (I assume).

Interesting bug.

**Comment by Isolus** [comment]
Yes, the config of the primary is
```
example.org {
        dnssec {
                key file /home/coredns/config/K<...>.private
        }
        file /home/coredns/config/example.org.zone example.org {
                transfer to <secondary-ip>
        }
        errors
}
```

**Comment by miekg** [comment]
~~OK, seeing it.~~ ... And a bunch of other things. Problem here is that testing is super complicated :/
scratch that I manually duplicated the NS record.

**Comment by miekg** [comment]
Is it possible to narrow it down some? I've a PR in flight #1406, but that fixes other things (makes me wonder why things worked in the first place).

i.e. what happens when your remove the dnssec plugin? Is it possible to test that?

**Comment by Isolus** [comment]
I've created a new zone without the dnssec plugin. It still happens.

**Comment by Isolus** [comment]
I think the problem is that in `TransferIn()` in `plugin/file/secondary.go` in line 19 we copy the zone. But the copy is weird. We drop the Tree, but use the old Apex (including the NS set).

In line 41 we insert the data in the copy. But Insert just appends NS entries to `z.Apex.NS`. We never delete the old ones.

**Comment by miekg** [comment]
Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Duplicate NS ..." ]
>I think the problem is that in `TransferIn()` in `plugin/file/secondary.go` in line 19 we copy the zone. But the copy is weird. We drop the Tree, but use the old Apex (including the NS set).
>
>In line 41 we insert the data in the copy. But Insert just appends NS entries to `z.Apex.NS`. We never delete the old ones.

this is, indeed, pretty obvious. Wondering why I'm having trouble replicating 
this in a test.... :/

**Comment by miekg** [comment]
#1413 and #1406 should fix this and other issues. I'll likely merge this today.
