### ISSUE TITLE
NSEC RRs sometimes contain the requested type

### ISSUE THREAD

**Issue by Isolus** [coredns/coredns#1401]
In case of a NODATA response the requested type is filtered out of a NSEC RR. In case of a NXDOMAIN, it's rewritten to a NODATA response, but the requested type isn't filtered out.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/1399

Why would I need to filter out the requested type if the response is NXDOMAIN?

**Comment by Isolus** [comment]
NXDOMAIN is changed to NODATA. And NODATA responses should contain one NSEC record to tell the resolver which types exist on the requested name.
So if the type is present, we say this entry doesn't exist, but we although say it exists.
Someone notified me that e.g. [DNSViz](http://dnsviz.net/) sees this as error `NSEC proving non-existence of _25._tcp.mail.exmaple.org/TLSA: The TLSA bit was set in the bitmap of the NSEC RR corresponding to the SNAME (_25._tcp.mail.exmaple.org).`

**Comment by miekg** [comment]
oh yeah, of course we also change the response type, meaning this check is wrong:
`if mt != response.NoData {`

**Comment by miekg** [comment]
Would like to replicate this in a test first though.

**Comment by miekg** [comment]
PR updated. PTAL

**Comment by Isolus** [comment]
Looks good and works for me.

**Comment by miekg** [comment]
Closed via #1399
