### ISSUE TITLE
Check and test all plugins for case preservation

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1403]
DNS is case preservation protocol. I.e. a qname that comes in as Example.COM needs to come out like that.

The *file* plugin does some of this right (and has some casing tests IIIRC), but we should check all plugins for this by writing tests for them. 

This is a bit annoying to do but a great way to learn about the coredns code base (and about DNS).

**Comment by yongtang** [comment]
Not familiar with DNS protocol overall though I remember DNS is also case-insensitive. So we may need to be careful to make sure it is both `case-insensitive` and `case-preserving`.

**Comment by miekg** [comment]
it would be nice if this would be a top-level test function that rotates through all plugins - problem there is that you don't know a good default syntax before hand.

Another approach is to have a simple test helper function that does this per plugin as to minimize the code that needs to be added.

**Comment by miekg** [comment]
See #1393
