### ISSUE TITLE
plugin/secondary: add metrics

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1407]
Metrics about zone transfers (and especially failures) should be added:
* failing to refresh
* retry active
* ... ?

**Comment by SuperQ** [comment]
The ideas that come to mind for me are:

* gauge: last updated timestamp
* gauge: last updated serial number
* gauge: last update success boolean
* counter: refresh total
* counter: refresh time total
* counter: refresh errors total

**Comment by calebice** [comment]
@fturib if this is something that is still relevant (hasn't been updated since April) I can add some of these listed metrics into the secondary plugin.

**Comment by SuperQ** [comment]
Yes, I sadly haven't had the time to work on it myself. These metrics would be great.

**Comment by fturib** [comment]
@miekg , @SuperQ : could you advice here on what you would like to implement. @calebice is willing to help on CoreDNS project, and is looking for first issue to fix ...

**Comment by calebice** [comment]
I figured this would be a good beginning issue as I've got prior experience working with Prometheus metrics and collection!

**Comment by SuperQ** [comment]
The metrics I listed above still seem like a good first pass. I'm happy to review any naming convention and related monitoring issues.

To add some literal metric names:

Given these prefixes:
```
Namespace: plugin.Namespace,
Subsystem: subsystem,
```

Gauges:
* `last_updated_seconds`
* `last_updated_serial`
* `last_update_success`

Counters:
* `refreshes_total`
* `refreshes_seconds_total`
* `refreshes_failed_total`

Each of these metrics should have a `zone` label.

**Comment by miekg** [comment]
sgtm, happy review any pr

**Comment by jiachengxu** [comment]
Hi @calebice , are you currently working on this issue? Can I take it?

**Comment by calebice** [comment]
Hi @jiachengxu , 

Yes, I am working on this issue presently!

**Comment by palash25** [comment]
~~Hi, so if I have understood this correctly solving this issue would require implementing the aforementioned metric types (just like prometheus does  https://github.com/prometheus/client_golang /blob/master/prometheus/gauge.go ) and then using them in the plugin or are theyalready implemented somewhere and that code could be reused here or can we just import and use the metrics type from the prometheus clients here? cc @miekg @SuperQ~~ 


Nevermind I found it.

**Comment by miekg** [comment]
any work-in-progress or ideas we can look at?

**Comment by palash25** [comment]
I just found how some of the metrics are used in the codebase, will try to make a WIP PR in few days if I can.

**Comment by palash25** [comment]
@miekg I have made a WIP PR let me know if I am heading in the right direction with this or not.

**Comment by hprateek43** [comment]
Is this merged or still pending ? If pending, I can pick this up

**Comment by palash25** [comment]
My PR is awaiting a review @hprateek43 https://github.com/coredns/coredns/pull/2550  had it been merged it would have shown up in the thread. I haven't abandoned this issue/PR if you want to make PRs please pick another issue from the queue.

**Comment by miekg** [comment]
Yes. This has been sitting in the queue for way too long.
