### ISSUE TITLE
plugin/file: only reload when file was modified

### ISSUE THREAD

**Issue by zhujinghui** [coredns/coredns#1423]
currently, file plugin reload file by periodically(1m by default) read file, see https://github.com/coredns/coredns/blob/master/plugin/file/reload.go#L25. This brings some unnecessary work if file actually not changed at all. 

One best practice is using inotify to watch file and only reload when file is changed. Does it sounds worth doing ? Will send a PR to address this if the idea looks good.

**Comment by miekg** [comment]
We had inotify - didn't work at all. Search through some of the closed issues.
