### ISSUE TITLE
GeoDNS functionality

### ISSUE THREAD

**Issue by vteslia** [coredns/coredns#143]
Hi,

do you have a plan for implementation GeoDNS functionality (may be as middleware) in CoreDNS?

**Comment by miekg** [comment]
no, no current plans from my side (personally don't have an immidiate need for it).

https://github.com/abh/geodns implements this and yes this can be done as a middleware. Will be interesting to see if you can use an existing middleware (like `file`) and insert geodns on top of that.

**Comment by miekg** [comment]
Noone is working on this.
