### ISSUE TITLE
 make coredns failed; cannot find package "github.com/coredns/coredns/core/plugin"

### ISSUE THREAD

**Issue by nycmoma** [coredns/coredns#1436]
@ ubuntu server 16.04.3 LTS
commit fcfb998b86f85872126a8968963212df7abb8d97
Date:   Thu Jan 25 15:33:08 2018 +0000

 test:~/coredns$ make coredns
.... OUTPUT....
go get -u github.com/alecthomas/gometalinter
gometalinter --install golint
Installing:
  deadcode
  dupl
  errcheck
  gas
  goconst
  gocyclo
  goimports
  golint
  gosimple
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  megacheck
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  unused
  varcheck
  vet
gometalinter --deadline=1m --disable-all --enable=gofmt --enable=golint --enable=vet --exclude=^vendor/ --exclude=^pb/ ./...
go generate coredns.go
(cd /home/ubuntu/go/src/github.com/mholt/caddy 2>/dev/null              && git checkout -q master 2>/dev/null || true)
(cd /home/ubuntu/go/src/github.com/miekg/dns 2>/dev/null                && git checkout -q master 2>/dev/null || true)
(cd /home/ubuntu/go/src/github.com/prometheus/client_golang 2>/dev/null && git checkout -q master 2>/dev/null || true)
(cd /home/ubuntu/go/src/golang.org/x/net 2>/dev/null                    && git checkout -q master 2>/dev/null || true)
(cd /home/ubuntu/go/src/golang.org/x/text 2>/dev/null                   && git checkout -q master 2>/dev/null || true)
go get -u github.com/mholt/caddy
go get -u github.com/miekg/dns
go get -u github.com/prometheus/client_golang/prometheus/promhttp
go get -u github.com/prometheus/client_golang/prometheus
go get -u golang.org/x/net/context
go get -u golang.org/x/text
(cd /home/ubuntu/go/src/github.com/mholt/caddy              && git checkout -q v0.10.10)
(cd /home/ubuntu/go/src/github.com/miekg/dns                && git checkout -q v1.0.4)
(cd /home/ubuntu/go/src/github.com/prometheus/client_golang && git checkout -q v0.8.0)
(cd /home/ubuntu/go/src/golang.org/x/net                    && git checkout -q release-branch.go1.9)
(cd /home/ubuntu/go/src/golang.org/x/text                   && git checkout -q e19ae1496984b1c655b8044a65c0300a3c878dd3)
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=fcfb998" -o coredns
coredns.go:9:2: cannot find package "github.com/coredns/coredns/core/plugin" in any of:
	/usr/local/go/src/github.com/coredns/coredns/core/plugin (from $GOROOT)
	/home/ubuntu/go/src/github.com/coredns/coredns/core/plugin (from $GOPATH)
coredns.go:6:2: cannot find package "github.com/coredns/coredns/coremain" in any of:
	/usr/local/go/src/github.com/coredns/coredns/coremain (from $GOROOT)
	/home/ubuntu/go/src/github.com/coredns/coredns/coremain (from $GOPATH)
Makefile:12: recipe for target 'coredns' failed
make: *** [coredns] Error 1
.... 

helped: 
test:~/coredns$ go get github.com/coredns/coredns/core/plugin

**Comment by miekg** [comment]
`test:~/coredns`
doesn't look like you checked out coredns in your $GOPATH

**Comment by miekg** [comment]
did you get this to work?

**Comment by nycmoma** [comment]
yep, it looks like I had permissions problem. sorry.
