### ISSUE TITLE
coredns is exiting when the AWS SDK for Go in the route53 plugin cannot resolve route53.amazonaws.com.

### ISSUE THREAD

**Issue by psoaresgit** [coredns/coredns#1438]
If coredns is the configured resolver on the host where it's run using the route53 plugin, coredns will exit:
```
Jan 25 16:51:31 localhost.localdomain coredns[18196]: 2018/01/25 16:51:31 /etc/coredns/Corefile:13 - Error during parsing: aws error: 'RequestError: send request failed                                                                                                                            
Jan 25 16:51:31 localhost.localdomain coredns[18196]: caused by: Get https://route53.amazonaws.com/2013-04-01/hostedzone/A1B23CD4EFGHI5/rrset?maxitems=1: dial tcp: lookup route53.amazonaws.com: no such host'
```
```
$ cat /etc/resolv.conf 
nameserver 127.0.0.1
```
```
$ cat Corefile
. {
    forward . tls://9.9.9.9 {
        except zone.my.tld
        tls_servername dns.quad9.net
    }
    errors
    log
    cache
}
zone.my.tld {
    route53 zone.my.tld:A1B23CD4EFGHI5 {
        aws_access_key <snip> <snip>
    }
    errors
    log
    cache
}
```
If some other reachable resolver, other then coredns itself, is configured for the host, coredns will run and return responses for zone.my.tld.

Switching to use coredns after coredns runs on the local host also works (perhaps until re-resolution of route53.amazonaws.com might be required).

Perhaps the route53 plugin could change to resolving route53.amazonaws.com with coredns internally within a custom resolver function for the AWS SDK for Go:
https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#ResolverFunc

Also perhaps coredns does not need to exit on errors from the AWS SDK for Go.

**Comment by miekg** [comment]
@yongtang is this something that should be fixed?

**Comment by yongtang** [comment]
Ah, yes. Missed the notification last time. Let me assign it to myself.

**Comment by fantuz** [comment]
> If some other reachable resolver, other then coredns itself, is configured for the host, coredns will run and return responses for zone.my.tld.

Expected. But doesn't solve the issue of having a unique (universal) Coredns resolver.

>Switching to use coredns after coredns runs on the local host also works (perhaps until re-resolution of route53.amazonaws.com might be required).

**nscd** might be the "culprit" for stale/undesired cache. You can manually empty nscd cache with ```nscd --invalidate=hosts```.

>Perhaps the route53 plugin could change to resolving route53.amazonaws.com with coredns internally within a custom resolver function for the AWS SDK for Go: https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#ResolverFunc

This is probably  the preferred way to solve the issue, in a "plugin-oriented" context such as this thread, IMHO. Bravo @psoaresgit 

Another solution other than using an external resolver, would be to run a dnsmasq (127.0.0.2) for the specific route53 service/zones and/or even manually edit /etc/hosts ? Or implement alternative resolver in coredns, a sort of black/whitelisting which anyway is not in DNS philosophy...

My favourite solution (hardcore but KISS) to such kind of problems is a "iptables DNS parser", which in turn would NAT and redirect queries based on specific content (position in the packet). 
Use the fantastic module: _u32_. Downside: better to force DNS request on TCP (you can filter out SYN, match for sequence 1 etc), anyway the module works on IP layer so UDP should fit (in my case, I did it some time ago, forcing few hosts to to use TCP/DNS, so cannot be more precise nor helpful).
Creating a custom U32 IPTABLES filter is not that difficult (http://ipset.netfilter.org/iptables-extensions.man.html) once we know how the route53 queries looks like :+1: 
That would avoid too much of rework, but not optimal solution as iptables might not be available.

Finally, the ideal solution I see here. would be to end up with a Coredns function similar to the one present in CURL: the '--resolve'. Such option is there for exactly that same reason, see it as an hosts file.
```curl --resolve foo.example.com:443:127.0.0.1 https://foo.example.com:443/```
Not saying that will be manageable, nor dynamic. I am saying such bypass could mitigate the issue...

That is, route53 is essential service on AWS. I believe Google Cloud would suffer similar sympthoms with its DNS API (not aware of a coredns plugin yet)...

HTH, please correct me if I said wrong,
Max

**Comment by fantuz** [comment]
OT, just for reference, regarding Google:

- GCP DNS APIs -> https://cloud.google.com/dns/api/v1/
- ALPHA STAGE GO API CLIENT -> https://github.com/google/google-api-go-client/tree/master/dns
- API -> https://github.com/google/google-api-go-client/blob/master/dns/v2beta1/dns-api.json
