### ISSUE TITLE
Comma-separated endpoint in coredns not working

### ISSUE THREAD

**Issue by alexgaganashvili** [coredns/coredns#1446]
I'm using the following for the endpoint parameter:

`endpoint https://fqdn1:443,https://fqdn2:443,https://fqdn3:443`

Here's what the logs are showing:

`2018/01/27 00:05:14 [WARNING] Host https://fqdn1:443 health check probe failed: Get http://fqdn1:443/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
2018/01/27 00:05:14 [WARNING] Host https://fqdn2:443 health check probe failed: Get http://fqdn2:443/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
2018/01/27 00:05:14 [WARNING] Host https://fqdn3:443 health check probe failed: Get http://fqdn3:443/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`

It looks as though it were trying to perform a health check using the http scheme (Get http://) whereas 443 is used for secure connection.

It works when only one endpoint is specified.

Thanks

**Comment by fturib** [comment]
@alexgaganashvili : can you share the whole corefile you are using for this test (I mean with endpoint comma separated and the health configuration) ?

We may have to dive in that code of health checking.

Thanks

**Comment by fturib** [comment]
@alexgaganashvili : never mind ... the line 'endpoint' you provided is enough.

**Comment by fturib** [comment]
I understand from the code:

First, it applies only if you are using coreDNS as an external DNS Service of k8s.
1- the health check on API endpoints happen only if there is more than one endpoints
2- this check is always tested against http, although the scheme provided is not http.

NOTE: I do not think that changing the format comma-separated will fix that issue.

**Comment by alexgaganashvili** [comment]
@fturib I now have the endpoints space-separated - and it works.

**Comment by fturib** [comment]
@alexgaganashvili : good to know, and happy for you ... but I am a bit puzzled.
if your configuration is still the same: 

> endpoint https://fqdn1:443 https://fqdn2:443 https://fqdn3:443

Then maybe you allowed the traffic http on these points ? I mean maybe http://fqdn1:443 is now replying a valid information ?

**Comment by alexgaganashvili** [comment]
@fturib, in my apiserver config I define port 443 for secure connections:
`--secure-port=443`
