### ISSUE TITLE
think about global plugins

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1452]
Plugins like reload, health, prometheus (metrics) are global as they span Servers; we need to think about how this works:
* allow them exist outside server blocks?
* document them better?

~~Caddy allows a non-server block stanza that does something. At the time I couldn't possibly come up with what this should be for DNS, so I basically ignored it. But I think it makes sense to allow:~~

~~~ corefile
health
prometheus

. { 
  whoami
}
~~~
Update: Caddy *doesn't* allow this. It only support the example below (i.e. no server blocks at all does something)

We should then also support
~~~ corefile
whoami
~~~
Which we could default to `.` as well.
Not sure what the implication will be; I think it will help people write Corefiles.

**Comment by fturib** [comment]
I agree with that presentation. Would more clear.

**Comment by miekg** [comment]
Note that the caddyfile parse *we* use already supports this, we just error later in the process.
(as an fyi)

**Comment by miekg** [comment]
This is then also possible:
~~~
health
prometheus

. { 
  whoami
  prometheus
}

example {
   whoami
}
~~~
Shoud `example` then have metrics?

**Comment by miekg** [comment]
https://caddyserver.com/docs/caddyfile
> A Caddyfile with only one entry may consist simply of the label line(s) followed by the definition on the  next line(s), as shown above. However, a Caddyfile with more than one entry must enclose each 
> definition in curly braces { }. The opening curly brace { must be at the end of the label line, and the
 > closing curly brace } must be the only token on its line:

So what I did in https://github.com/coredns/coredns/issues/1452#issuecomment-363241245 is illegal, which means we need to think of something else.

~~~
cache
whoami
~~~
could be legal in CoreDNS, but isn't right now (using *cache`* here) to side step, "global" plugins.

**Comment by johnbelamaric** [comment]
Why not just

```
global {
  health
  prometheus
}

.:53 {
  whoami
}
```

Or if you don't want to reserve `global` use some `@global` or something.

**Comment by miekg** [comment]
meh.

Updated the initial comment; as that is wrong. What problem are we solving now?
~~~
. {
  whoami
}

com {
  whoami
  prometheus
}
~~~
where `.` doesn't get metrics and com does, makes perfect sense to me (modulo bugs in the metrics plugin of course)

**Comment by johnbelamaric** [comment]
Sure, metrics could be per server block. But what about `reload`? Is that the only truly global one we have (assuming metrics bugs are fixed)? Should `health` be global or per server block (or per *server* instance)?

**Comment by miekg** [comment]
Ideally `health` should do this as well (but this can only work if /health is keyed of zones or something??)

`reload` is even weirder in that respect - but this should just be mentioned in the docs.

**Comment by miekg** [comment]
Note: I love that *reload* **is** is plugin

But should reload actually be a command line flag?

What if I make a *port* plugin that specifies the listening port for the process?

**Comment by fturib** [comment]
Maybe we could also have some plugins that we would like to share as resource at a global level : **cache** for instance.

**Comment by johnbelamaric** [comment]
It could be a command line flag, I just though it would be better to not change that if we can avoid it. If we did that, the only downside would be that then its options can't be modified by a reload.

**Comment by miekg** [comment]
re: *global* cache; I'm not convinced that would make much difference, you could still have a "catch all" zone stanza for `.` and cache there.

For a cache I *do* want: a cache that is shareable between coredns instances. I.e. I have 4 coredns instances in my k8s cluster; having a shared cluster cache would help me.

In having something cross zone stanzas is (still) strange in coredns

**Comment by miekg** [comment]
So while working on health and prometheus and reloading the following thought occurred:

* health and metrics are both global (i.e. affect the process), but still different

With prometheus you can add metrics and it sort of works as expected (modulo the metrics overwrite bug  - but that is fixeable)

With health all instances in separate server blocks are unique; there is no global Register function as prometheus has; this is not intuitive and should be fixed in CoreDNS.

A plugin should be able to say: i'm global; this is my registration function; so when other Server Blocks call that it will just work.

**Comment by miekg** [comment]
As for configuring we should just emphesis snippets more: 
https://caddyserver.com/docs/caddyfile#snippets

i.e. the following works:
~~~
(mysnippet) {
    prometheus :10143
}

. {
    forward . 127.0.0.1 {
        tls_servername dns
    }
    import mysnippet
}

com {
    whoami
    import mysnippet
}
~~~

As far the *cache* example, i.e. cross servers; I don't think that will be easy to do. If I would have such a use case I rather solve it for multiple CoreDNS instances as well, meaning it want to network cache like redis and use the https://coredns.io/explugins/redisc/ plugin.
