### ISSUE TITLE
revisit MAINTAINERS

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1454]
Check if the current set of maintainers is still up to date.

**Comment by stp-ip** [comment]
While doing that we might go with the more general OWNER files similar to Kubernetes. Would also give the option to have an owner for plugins etc.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] revisit MAINT..." ]
>While doing that we might go with the more general OWNER files similar to Kubernetes. Would also give the option to have an owner for plugins etc.

Good plan! Was pondering a bit how to do this for plugins.

**Comment by stp-ip** [comment]
fyi: https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md

**Comment by miekg** [comment]
I'll try to use some git magic to come up with a PR. Wish there was an easy way to use some github integration that uses OWNERS.

https://github.com/kubernetes/test-infra/tree/master/prow is mentioned, but I have no idea how to set that up.

**Comment by stp-ip** [comment]
Haven't worked with the test-infra specifically. But yeah prow is the main infra used for providing commands such as /approve /assign /lgtm and it basically just needs a kubernetes cluster and github account and secrets.

**Comment by miekg** [comment]
that almost sounds doable :-)

**Comment by stp-ip** [comment]
Mungegithub was used before for /approve, but that was deprecated afaik, maybe one of the awesome people from test-infra can help especially with where the current docs differ. cc @spiffxp @fejta @cblecker (thanks for any help. really appreciated)

**Comment by miekg** [comment]
This has been done. I'll need to look into setting up the whole framework for actually assigning owners to bugs and PRs.
