### ISSUE TITLE
Plugin/Reload - incompatible with global var in plugin packages

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1455]
Reloading the corefile is done in 2 steps:
1- verify that file is correct by applying once the configuration in Caddy
2- restart the servers

If the step 1 goes to the end, but with an error in the corefile, then each plugin has been called for 'setup'.
Some plugin are using package global vars (metrics, reload .. at least).
It can happen these variables are reinit with the nes corefile, but as the step1 globally fails, the service is still continuing with the former configuration. But meanwhile, those global vars are inited to the new values .... which leads to impredictable beahvior.

NOTE: that is very true with the plugin RELOAD itself that save the data in a global var (instead in configPlugin ... ). Which make the plugin confused after a reload that failed. It is not able to reload on the next period.

**Comment by fturib** [comment]
Found it while using this plugin for my tests on proxy ...
I am working on finding a solution.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Plugin/Reload..." ]
>Found it while using this plugin for my tests on proxy ...
>I am working on finding a solution.

Ok, otherwise we can delay its use by removing it from plugin.cfg ?

**Comment by johnbelamaric** [comment]
This likely applies to all reloads, via this plugin or signals. I did test this particular plugin in that circumstance, though, so I am surprised to see this.

**Comment by miekg** [comment]
Is this what you're trying to fix in #1485?

**Comment by miekg** [comment]
is this (or was this) a problem with reload? Or do you have specific examples of failing plugin (other than reload)?

**Comment by fturib** [comment]
When I opened this issue, that was to raise a concern about the other plugins that does not support RELOAD operation.

I mean, the plugins that may not deallocate / reallocate the resources when the server is restarted. 

Most concerning are the "global" plugins, as they usually allocate resources in global way - global variable for example, and/or opened an http server on specific address that has to be closed on the right time.

I guess we should verify on each plugin:
* are the events balanced for allocation/deallocation - in other words what happen "onStart", "onShutdown", "onRestart", "onFinalShutdown".
* is there some global variable that may be accessed simultaneously by the server still running and the new server that is starting (due to graceful restart ...). Maybe that needs mutex, or redesign if the RESTART was not thought at first time.


NOTE: since then, some UT on RELOAD itself shows needs of mutex around some of the properties that can be accessed by several threads ... (specifically at time of restart). 
the fixes are in this PR : #1485

**Comment by miekg** [comment]
+1 to check plugins and then pull some of the checking code into our CI

**Comment by miekg** [comment]
can this be closed?

**Comment by fturib** [comment]
My opinion is we still have some issue here. 
If the RELOAD fails, because of global vars, we have inconsistent state on the initial SERVER.

But lets close for now. And i will open another one proposing a solution to avoid the global vars.
