### ISSUE TITLE
plugin/rewrite: fails to rewrite responses for SRV queries

### ISSUE THREAD

**Issue by greenpau** [coredns/coredns#1460]
@achille-roussel, reported that the plugin works with "basic A queries but for some reasons dig doesn't like it on SRV queries".

@achille-roussel documented the failing configuration in [#1394](https://github.com/coredns/coredns/issues/1394#issuecomment-361016336) 

This behavior is expected, because the plugin/rewrite supports the rewriting of responses for A records only.

The culprit is here https://github.com/coredns/coredns/blob/master/plugin/rewrite/reverter.go#L41

```golang
name := rr.(*dns.A).Hdr.Name
```

There has to be a logic in `ResponseReverter` that indicates how to cast a record.

@miekg , @johnbelamaric , any suggestion how to do it in the most efficient way?

Further, perhaps, there is a need to rewrite `ADDITIONAL SECTION`:

```
;; ANSWER SECTION:
redis.us-west-2a.service.consul. 0 IN	CNAME	us-west-2b.redis.service.consul.
us-west-2b.redis.service.consul. 0 IN	SRV	1 1 6379 453fdf18f226.node.dc1.consul.

;; ADDITIONAL SECTION:
453fdf18f226.node.dc1.consul. 0	IN	A	127.0.0.1
```

**Comment by miekg** [comment]
That line can be become:
~~~
name := rr.Header().Name
~~~
The additional section should just list records that are referenced from the answer section, like like in the example you use.
There shouldn't be a need to CNAME chain things in the additional section.

**Comment by greenpau** [comment]
> name := rr.Header().Name

@miekg , 👍  Will open PR for it.

I think I would need to change this [one](https://github.com/coredns/coredns/blob/master/plugin/rewrite/reverter.go#L56) too.

**Comment by miekg** [comment]
Yep, there too.
