### ISSUE TITLE
plugin/kubernetes: API connections to secure endpoint list fails

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1464]
Secure API connections fail if the list of endpoints is > 1. 

See tests in `/coredns/ci/test/kubernetes/excluster_test.go` `TestKubernetesSecureAPIFallthrough`
The test is currently being skipped. coredns/ci#30

**Comment by chrisohaver** [comment]
@yongtang - Have you had a chance to look into this?

**Comment by chrisohaver** [comment]
IMO, we should either:
1. Fix this issue ... or 
2. Remove the api endpoint failover list feature

Without secure connections working, this feature is not very useful/practical.

**Comment by yongtang** [comment]
What is the issue related to multiple api endpoint?

**Comment by chrisohaver** [comment]
> What is the issue related to multiple api endpoint?

yes.

**Comment by chrisohaver** [comment]
We should remove the feature if this is not going to be fixed.

**Comment by miekg** [comment]
so, lets remove it
