### ISSUE TITLE
plugin/consul: proposal

### ISSUE THREAD

**Issue by achille-roussel** [coredns/coredns#1467]
Hello,

This is a follow up to https://github.com/coredns/coredns/issues/1394.

## Background
Response RTT of queries to the Consul DNS interface increases linearly with the number of service instances registered to Consul. We have deployments of few thousand service instances, and resolving a name takes 100 to 700 milliseconds, and is CPU-bound (which means with increasing concurrency Consul will max out the number of cores available).

The Consul [documentation](https://www.consul.io/docs/guides/dns-cache.html) advocates for using a DNS caching layer by configuring a TTL for DNS responses it returns, which coredns could do. However when the goal is to spread load to all running instances of a service, having a DNS cache gets in the way since all new connections within the TTL would be routed the few addresses returned in the response.

## Proposal
This proposal is an attempt to address the Consul's inefficient DNS interface by providing a more efficient implementation as a CoreDNS plugin.

Here are the few ideas that the implementation would be based on:
- The behavior must mirror Consul's DNS interface, supporting filtering of the result set based on a tag set on the prefix of A/AAAA queries (as in `<tag>.<name>.service.consul`), or based on the protocol part of SRV queries (as in `_<service>._<tag>.service.consul`).
- The implementation would maintain an in-memory cache of Consul catalog for services names that get resolved (LRU-style to expire entries that haven't been queried in a while), which would get periodically refreshed. The cache would index entries by service name and tags, providing constant time lookups.
- Instead of shuffling the entire list of service addresses on every query, the implementation would pick one (or few) random addresses to answer the query, which would also be a O(1) operation. Round-robin could also be considered as a load balancing strategy instead of random.

## Considerations
It is possible that Consul's inefficient DNS interface should be fixed instead of providing a replacement within CoreDNS. However, Consul's implementation is less modularized, the issue seems harder to address within Consul, the release cycle could be slower as well.

The CoreDNS plugin system makes the change much more approachable. Providing a solution to a scalability issue of a popular system like Consul could help bring more momentum to CoreDNS as well. This could also be the foundations for adding more features to a Consul DNS interface that may not be supported by Consul itself.

All feedback are welcome!

**Comment by grobie** [comment]
I have implemented an internal custom DNS server for Consul 4 years ago, mainly to support our custom naming schema which already existed before we switched to Consul as backend, but also to fix some performance issues (which might have been fixed in the meantime) and to add some special features we needed.

> The Consul documentation advocates for using a DNS caching layer by configuring a TTL for DNS responses it returns, which coredns could do. However when the goal is to spread load to all running instances of a service, having a DNS cache gets in the way since all new connections within the TTL would be routed the few addresses returned in the response.

As we heavily rely on DNS for service discovery, we have always used local caches on each node to remove the RTT to DNS servers. The key is to cache the whole response locally and to tell your caching server to randomize the set before returning it to clients. Unbound supports that via the `rrset-roundrobin` config option, CoreDNS via the `loadbalance` plugin. This spreads requests evenly over all instances returned in the cached response.

> Instead of shuffling the entire list of service addresses on every query, the implementation would pick one (or few) random addresses to answer the query, which would also be a O(1) operation. Round-robin could also be considered as a load balancing strategy instead of random.

This only covers one use case. There are many DNS SRV clients out there needing the complete resource list to do their job.

> It is possible that Consul's inefficient DNS interface should be fixed instead of providing a replacement within CoreDNS. However, Consul's implementation is less modularized, the issue seems harder to address within Consul, the release cycle could be slower as well.

I can't speak for the CoreDNS project, but this sounds like avoiding a conversation with the Consul project and pushing the burden of maintaining a complex client which has many different users and requirements onto a different project. Your latency requirements can be easily solved today with a caching DNS server in front of Consul's DNS server. We switched to CoreDNS for that a few weeks ago.

**Comment by miekg** [comment]
+1 to what has been said by @grobie 

Note you're complete free to write this plugin, but it will, most likely, has to be an external plugin.

**Comment by achille-roussel** [comment]
My initial understanding about where the performance bottlenecks are in Consul was wrong. After further analysis, it comes from multiple data store lookups, sorting, filtering, parsing, etc... which is done on every name resolution. This is deeply integrated with how Consul works, basically the DNS server is built as an internal proxy to the API, and has no access to the data store to potentially skip all this work and provide an efficient implementation. It would be a considerable rewrite to make it happen and our needs for a short term solution cannot afford to wait for such changes. They would also be released in the next version of Consul, which would require a large scale upgrade on our infrastructure. This is why the decoupling and ease provided by building this into CoreDNS becomes interesting.

I agree that a lot of those issues are specific to a problem we have, but this is what we do right? Find solution to the issues we face.

I had not considered using the load balancer with caching of the full response set, mainly because service name resolution over TCP were always failing for services with the largest number of tasks (timing out, or exceeding the maximum size supported by the client). I'll try to implement it with CoreDNS 👍 

I understand the desire for not wanting to increase the maintenance burden on the project. Would the load balancing plugin approach not work, I'd go the route of writing an external plugin.

Thanks a lot for this quick and valuable feedback!

**Comment by achille-roussel** [comment]
## Follow up
I tried to use the `cache` and `loadbalance` plugins to get a more efficient DNS interface to Consul (using resolution over TCP between CoreDNS and Consul). It worked great most of the time, however some services we run have few hundred instances, which caused Consul to generate a response that was larger than the maximum size than DNS allows.

I filed the issue there https://github.com/segmentio/coredns-consul, but I don't expect it to be fixed any time soon, let alone back ported to older Consul versions, so I implemented the plugin originally described in this proposal.

For anybody interested, here it is: https://github.com/segmentio/coredns-consul

Building software with CoreDNS was a pleasure, I gotta say you guys did a really nice work with this project. I'm excited to see what it holds for the future!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/consul..." ]
>## Follow up
>I tried to use the `cache` and `loadbalance` plugins to get a more efficient DNS interface to Consul (using resolution over TCP between CoreDNS and Consul). It worked great most of the time, however some services we run have few hundred instances, which caused Consul to generate a response that was larger than the maximum size than DNS allows.

Maximum? As in 64K with tcp? Or just udp buffer size issues?

>I filed the issue there https://github.com/segmentio/coredns-consul, but I don't expect it to be fixed any time soon, let alone back ported to older Consul versions, so I implemented the plugin originally described in this proposal.
>
>For anybody interested, here it is: https://github.com/segmentio/coredns-consul

If I have time I might take a look. Is it good enough to link from 
coredns.io/explugins?

>Building software with CoreDNS was a pleasure, I gotta say you guys did a really nice work with this project. I'm excited to see what it holds for the future!

Good to hear!

/Miek

--
Miek Gieben

**Comment by grobie** [comment]
> Maximum? As in 64K with tcp? Or just udp buffer size issues?

Pretty sure it's that limit. We faced the same issue and it's a reason we started migrating to different service discovery mechanisms.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/consul..." ]
>> Maximum? As in 64K with tcp? Or just udp buffer size issues?
>
>Pretty sure it's that limit. We faced the same issue and it's a reason we started migrating to different service discovery mechanisms.

Ack.

Note that that limit (64K) is arbitrary choosen and if you control both client 
and server you can just add another byte to the length field... :/ (/me ducks).

Would be interested to see what actually breaks in miekg/dns if you do this, as
0x0000 is a non-sense value for the length you could even implement:
`if first 2 bytes eq 0; then read next 3 for actual length`


YMMV, and it wasn't me who you gave you this idea. :-)

**Comment by achille-roussel** [comment]
@miekg Yes it’s the 64KB limit that we reached on consul when resolving names over TCP. 

Playing with the protocol to get around this limitation is surely fun, but it gets tricky to implement at scale when you have hundreds of services written in more than one language ;)

The plugin is good enough to advertise on coredns.io, we started deploying it to production today and so far it’s working (still young tho, we’ll probably polish some edge cases along the way). 

@grobie if you’re still using consul, give the plugin a try ;) it mirrors consul’s DNS interface.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/consul..." ]
>@miekg Yes it’s the 64KB limit that we reached on consul when resolving names over TCP.
>
>Playing with the protocol to get around this limitation is surely fun, but it gets tricky to implement at scale when you have hundreds of services written in more than one language ;)
>
>The plugin is good enough to advertise on coredns.io, we started deploying it to production today and so far it’s working (still young tho, we’ll probably polish some edge cases along the way).

Ok, just send to PR to, see https://coredns.io/2017/07/23/add-external-plugins/

**Comment by grobie** [comment]
> @grobie if you’re still using consul, give the plugin a try ;) it mirrors consul’s DNS interface.

We're still using Consul as backend for services not running in Kubernetes, but as I mentioned earlier we use a different naming approach (as we started doing DNS service discovery before consul existed). The majority of our services also uses advanced clients to talk to other services, taking into account failure rates, latency, etc. when choosing to which instance to talk to and need the full list of available instances. As instances can fail any moment, returning a single resource record from consul doesn't work for us.
