### ISSUE TITLE
Plugin/Forward - implement Healther interface

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1474]
### My concern

I need to reply the health of a Forward directive

### Proposition of implementation

What defines the health is that for each Forward in each bloc list, the ServeDNS can happen, which means: 
- at least one of the Upstream of that bloc is able to handle the request (is not down).

in other words if the ServDNS ends up in this line : _return dns.RcodeServerFailure, errNoHealthy_ then it is considered as non healthy

until a request can be served by this Forward bloc.

### Not decided

Do we want that the first unhealthy bloc toggle the global health of CoreDNS to DOWN, or do we want to be able to tune what bloc to monitor ? (That means adding an option 'report_health' on the blocs Forward you want to participate to the global health).

**Comment by miekg** [comment]
If we use the upstream health as the health for forward we create a dependency on the network; if there is a network blip all coredns-es will report unhealthy even though they could probably serve from cache... Also *forward* will spray to a random upstream in this situation.

This is not a good idea.
