### ISSUE TITLE
plugin/forward: implement gRPC protocol for Upstream hosts

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1476]
Before being able to switch from PROXY to FORWARD, I need to talk gRPC language with the remote DNS server.

I am not sure how to implement, 
what can be reused from current PROXY plugin  ? 
I guess we need a design in current Proxy struct inside Forward to be able to add the gRPC client stuff.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] ExtPlugin/Forward..." ]
>Before being able to switch from PROXY to FORWARD, I need to talk gRPC language with the remote DNS server.
>
>I am not sure how to implement,
>what can be reused from current PROXY plugin  ?
>I guess we need a design in current Proxy struct inside Forward to be able to add the gRPC client stuff.

I'm inclined to go with a new plugin that does this - and not bolt it on 
forward.

Yes this will lead to some code and feature duplication, but will be far easier 
to maintain in the long run.

Thinking along similar lines with the https_google thing.

**Comment by miekg** [comment]
coming back to this and now I think it should be done in *forward*. Mainly because grpc is a first class citizen in CoreDNS (we are a server as well). There are some tricky bits implementation wise:
* the `dial` in persistence.go  possible options, maybe as an empty interface to have the grpc.DialOpts
* the `yield` needs to specify what kind of conn it is yielding (udp/tcp/tls/grpc)
* I hope grpc.ClientConn is also a dns.Conn, we can probably fix that which means we would have a `WriteMsg`, which will probably be cleaner
* the health check needs a smaller tweak, because the grpc isn't support in miekg/dns

**Comment by miekg** [comment]
if we make grpc.ClientConn and dns.Conn a lot of problems disappear (except the health check protocol)

**Comment by miekg** [comment]
Even with a dns.Conn there is no generic dns.Dial so that will still have to be custom

**Comment by miekg** [comment]
Ok, current IETF hackathon to get DNS over HTTPs in miekg/dns proofs this route is futile (I'm sending a report on this to the DoH list). So gRPC will forever be outside miekg/dns as will DoH (some helper functions may be upstreamed.

So for the *forward* plugin, I'll need to figure out how to add gRPC and DoH, which will probably mean it will not use the connection pooling from *forward* as those protcols have that all implement inside their (Go) implementation. This leaves connecting to a domain name (as proposed by DoH), i.e. not an IP. This is not supported yet in CoreDNS, but we're thinking about it in #1592)

**Comment by inigohu** [comment]
I'm working on how to add **gRPC** protocol in Forward plugin and I have this approach.

Create a _Proxy_ interface with 3 implementations: _DNSProxy_, _GrpcProxy_ and _DoHProxy_. Each one with their _Connect_ implementation and connection pooling.

```go
 type Proxy interface {
     Connect(ctx context.Context, state request.Request, opts options) (*dns.Msg, error)
     ...
 }
```

This way, Forward struct will have a slice of different proxies

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>I'm working on how to add **gRPC** protocol in Forward plugin and I have this approach.
>
>Create a _Proxy_ interface with 3 implementations: _DNSProxy_, _GrpcProxy_ and _DoHProxy_. Each one with their _Connect_ implementation and connection pooling.
>
>```go
> type Proxy interface {
>     Connect(ctx context.Context, state request.Request, opts options) (*dns.Msg, error)
>     ...
> }
>```
>
>This way, Forward struct will have a slice of different proxies

I think that makes sense. Each of the impl. can live in the own sub-package to 
keep things sorted.

How is healthchecking done? Another interface?

**Comment by inigohu** [comment]
> How is healthchecking done? Another interface?

Yes, a HealthChecker interface that defines a Check function

```go
// HealthChecker checks the upstream health.
type HealthChecker interface {
	Check() error
}
```
```go
// Proxy defines an upstream host.
type Proxy interface {
	Connect(ctx context.Context, state request.Request, opts options) (*dns.Msg, error)
	...
}
```
```go
type grpcProxy struct {}
func (gp *grpcProxy) Connect(ctx context.Context, state request.Request, opts options) (*dns.Msg, error) {...}
func (gp *grpcProxy) Check() error {...}
```

If you think that this makes sense, I can start working on it.

**Comment by inigohu** [comment]
@miekg Friendly ping

**Comment by stp-ip** [comment]
As a general sidenote. If we move out the upstream implementations into their own subpackages, it might also be easier to use them as libraries within other projects. Currently it's hard to use CoreDNS as a library and it might not be a good idea to do that, but personally I always hate duplicating work. For example AdguardTeam with their open source project [Adguard Home](https://github.com/AdguardTeam/AdGuardHome) dropped CoreDNS and is now creating their own upstream library on top of miekg/dns: https://github.com/AdguardTeam/dnsproxy

Just thought that's nice context to take into account, if we revamp the upstream code and move into more subpackages.

**Comment by miekg** [comment]
I saw that. Is there more info as I haven't used coredns as a lib myself, but seen issues obviously.

Is that proxy any good? :)

@inigohu I would love to see some code; but be careful not repeat mistakes I made in proxy - 'cause what you propose sounds a bit what I tried there.

**Comment by stp-ip** [comment]
The proxy is minimal. Just thought the added context besides our tries with forward and proxy are good for a new implementation.

Looking into easier plugin usage and dep management as an overall goal, which might make adding it as a library easier. Besides that it's structure around being the server being started and not part of something, which some people seem to not like for a library. Will dig a bit deeper on specifics.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>The proxy is minimal. Just thought the added context besides our tries with forward and proxy are good for a new implementation.
>
>Looking into easier plugin usage and dep management as an overall goal, which might make adding it as a library easier. Besides that it's structure around being the server being started and not part of something, which some people seem to not like for a library. Will dig a bit deeper on specifics.

thanks

**Comment by miekg** [comment]
See #2667, closing this
