### ISSUE TITLE
Feature: Ability to listen locally IPv4 and Ipv6 in the same instance of CoreDNS

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1478]
### Target
Basically, we would like to support a configuration that target only local DNS request, but for both Ipv4 and Ipv6 stacks.

```
.:53 {
  bind 127.0.0.1
  .. whatever config here ...
  proxy 8.8.8.8:53
}

.:53 {
  bind ::1
  .. whatever config here ...
  proxy 8.8.8.8:53
}
```

Issue: there is an initial validation of the headers of bloc-lists that prevent to listen the same domains on the same port ... *but the listening address is not included*.

The reason is that this check is done *before* the configuration is setup. It is based *only* on the headers of the blocs.

### Proposition

Move up the bind address in the header, in a compatible way with today's syntax.
Something like : <domain>:IP:Port
if the IP is not present, then <domain>:Port would be understood.

NOTE: Bind is still supported, it would overwrite the proposed address in the header.
(no change in the BIND plugin).

### Implementation

I think that it is enough to modify the function that parse and check the header of each ServerBlock in the function InspectServerBlocks of core/dnsserver/register.go

**Comment by miekg** [comment]
This has come up before (has an issue I believe). Extending the zone syntax is not an option; it complicates it and is not very extensible. Multiple IPs will be the next feature request.

**Comment by fturib** [comment]
What is the proposition for defining multiple IP ? Using the BIND plugin ?

**Comment by miekg** [comment]
#1208

**Comment by fturib** [comment]
I agree with #1208 : the extension of bind is not possible as the Server are already build at time of parsing bind (which lead to an error on BIND if it is used twice on different stanza listening the same port)

However, this needs to run several coredns instance, is right now a blocker on Infoblox projects for using coredns as expected.

John B advised me a syntax on the zone that would be compatible with existing syntax.
I mean : whoever want to keep current syntax can continue to use it, who needs to use an extended syntax to specify the listening IP can use it.

current syntax is supported

- . {...} => will listen on *:53
- .:5353 {..} => will listen on *:5353
- myzone.com:53 {..} => listen on *:53

enhanced syntax is also supported

- .:127.0.0.1:54 => will listen on 127.0.0.1:54
- myzone.com:[::1]:78 => will listen on [::1]:78

In coredns, the impact is only on parsing this zone (the Config or server already accept a ListeningAddr) and the sorting of Server per ListeningAddAndPort is already implemented.
The validation of compatibility of zones, port, IP is changed to include check opverlaps between single IP and 'all IP'.

I made a try yesterday Including the UT on parsing the zone syntax, so far it seems to work as I expected. 
Though I have not yet implemented Integration test to prove that the Servers are correctly listening, I did Manual test + Debugging session that showed it is the case.
In fact I guess that Caddy was made to have the Listening IP defined in this head of bloc-lists.


Let me know if that is a path that we can go (I can submit a WIP PR on my code of yesterday if that help to see how it looks like)
Here I cannot workaround the need for Infoblox with an external plugin.

Thanks!

**Comment by miekg** [comment]
It's not (alone) backwards compat. It's an ugly syntax extension. The syntax itself it completely non-extensible, so this will surely bite us in the future.

Maybe some massive hack to get *bind* to do what we want could work? Otherwise just run another process

**Comment by fturib** [comment]
About each of the remarks/options:

## massive hack of bind

Currently the 'setup' function is called too late : the servers are already defined.
However, there is maybe a pre-process on the StanzaBlocList that is defined on Caddy level we could take advantage of .. I will look into.

## about ugly syntax, non-extensible

Would a syntax with a dedicated @option at end of the keys  be more nice and extensible ?
Let suppose we can define an extra special key that add an option for each of the keys of the same bloc

```
<zone> <zone> @<options> {
   ...
}

```
In that case, we can maybe have that special key in a syntax that can be extensible for future.
a format like `@<option-key>=<value>` and repeat the option of the key value pairs in the same key

exemple:

```
example.com mydomain.com @bind=127.0.0.1 @bind=[::1] {
    log
    error
    proxy . 8.8.8.8:53
}
```

Need to define (unless already existing in caddy  .. I will have look) the syntax of this extra optionals keys.

**Would it work for you ?**

If not, could you propose a syntax you see as suitable here ?

## Backward compatible

What do you mean buy _it's not (alone) backwards compat_ ?
As long as you can continue to write the same existing stanza and they keep the same meaning ?

**Comment by fturib** [comment]
After a second look, dedicating a specific KEY as an option for the whole list of keys is easy to manage in register.go/InspectServerBlocks

We would need to agree on a syntax to that special key.

- how to recognize this key ?
- do we allow a set of option-keys(for several options) 
- format of each key as key=value

`@<option-name>=<value>`
he only option I know right now is 'bind'.

NOTE: do we keep the port on each zone, or do we accept to have the port on the @bind option ?

Examples

Syntax 1:
```
example.com otherdomain.com 10.0.0.0/16  @bind=127.0.0.1:4502 @bind=[::1]:4502 {
...
}
```
another possibility for syntax:
Syntax2:
```
example.com otherdomain.com 10.0.0.0/16  [bind=127.0.0.1:4502] [bind=[::1]:4502] {
...
}
```

What make sense is that this optional keys act on the configuration of the Stanza, BEFORE we create the real Servers listening the socket.

**Comment by miekg** [comment]
See https://github.com/coredns/coredns/issues/1478#issuecomment-362553479
But ugly `bind` hack I meant not fiddling with the zone syntax *at all*. I don't care that you can make it work, I don't want to see any extensions in this syntax

So why can't you use multiple processes?

**Comment by fturib** [comment]
I had a look into the time of parsing the file and setup of the plugin.
Looks like "bind" info is available at time of building the servers.
So, I guess I can manage a way to take the options from the a plugin instead of from the zone syntac line. 

I will make a try and a proposition following that line - do not change at all the zone syntax line ....

**Comment by miekg** [comment]
> **So why can't you use multiple processes?**

**Comment by fturib** [comment]
So far I have not the detail of the reason that solution cannot work for that project.
I am asking them.

**Comment by grobie** [comment]
> So why can't you use multiple processes?

The most prominent reason I'd not want to run separate processes just to listen on multiple interfaces / IP addresses would be cache utilization. Having to duplicate all configuration files would be unexpected as well. If CoreDNS aims to be a replacement for bind9, unbound, etc. I'd expect a configuration directive to support multiple IP addresses.

Why would extending the `bind` plugin to handle multiple interfaces an ugly hack?

**Comment by fturib** [comment]
@miekg : out of the usage needed by Infoblox, I would think that when you use CoreDNS as a simple forwarder/dispatcher of queries, on initial client machine or one of local on-prem machines, it would be a security best practice to be able to listen only the dedicated interfaces.

And in that case, because that is only as forwarder hosted on client machine, you need lowest memory footprint you can. Which means, as possible, only one CoreDNS.

In other word that feature for listening on each interfaces with one CoreDNS only would be a fit for use case of local DNS forwarder ...

Am I wrong ? that use case does not exist ? (out of infoblox)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Feature: Abil..." ]
>> So why can't you use multiple processes?
>
>The most prominent reason I'd not want to run separate processes just to listen on multiple interfaces / IP addresses would be cache utilization. Having to duplicate all configuration files would be unexpected as well. If CoreDNS aims to be a replacement for bind9, unbound, etc. I'd expect a configuration directive to support multiple IP addresses.
>
>Why would extending the `bind` plugin to handle multiple interfaces an ugly hack?

That would be relatively easy...

The original attempt was to include the binding port in the uniqueness of a 
zone, so that:

~~~
. {
 bind ::1
}
~~~

and

~~
. {
  bind 127.0.0.1
}
~~~

would be allowed. This is now considered the same zone (i.e. `. on port 53`).

Actually a small change to dnsserver/register.go can remove *that* particular 
check. The dupe checking uses `za.String()` there, but we don't use that in 
the server path at all. I.e. on duplicate we could just add `-1` to the key in 
the map. Downside is that I don't know what happens when you have duplicate 
servers (without `bind`): which one of them gets queries.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Feature: Abil..." ]
>@miekg : out of the usage needed by Infoblox, I would think that when you use CoreDNS as a simple forwarder/dispatcher of queries, on initial client machine or one of local on-prem machines, it would be a security best practice to be able to listen only the dedicated interfaces.
>
>And in that case, because that is only as forwarder hosted on client machine, you need lowest memory footprint you can. Which means, as possible, only one CoreDNS.
>
>In other word that feature for listening on each interfaces with one CoreDNS only would be a fit for use case of local DNS forwarder ...
>
>Am I wrong ? that use case does not exist ? (out of infoblox)

No, that makes sense. Note *technically* this can be still done with multiple 
processes.

**Comment by fturib** [comment]
@miek, about your proposition is another way to allow this mutliple binding, without changing the BIND plugin. That can work, and make less change of code than what I proposed.

I n my current proposition I already had to change the dup checker to take care of the issue you are pointing. 

So I guess I can have an implementation following your proposition rather quickly.

**About technical aspects:**

NOTE: that still need to extend internally the keys because the Configs are saved in a map[key]. And ensure the Host.normalise() is able to retrieve the Host from that key.
 

Are you ok I go this way ?

**Comment by fturib** [comment]
Hum... if we do that way, are we really sharing the cache between the servers ?

**Comment by fturib** [comment]
Anyway, cache may be a good candidate for the 'global' plugins

**Comment by miekg** [comment]
This is currently 1 `conf.ListenHost`, which `bind` can update. See `groupConfigsByListenAddr` on how these are grouped. The big disconnect (I think) which we inherited from Caddy when I copied this code; is the default is listen on *all* addresses and with `bind` you can pick 1 - and there is nothing in between. I.e. coming back to the original use case, Part 1 is that this:
~~~
. {
 bind ::1 127.0.0.1
 whoami
}
~~~
make sense, and doesn't work today. Part 2 is:
~~~
. {
 bind ::1 127.0.0.1
 whoami
}

. {
  bind 192.168.1.1
 whoami
}
~~~
And having that work without the complaint that the zone is already defined.

Maybe Caddy has fixed some of this already; I haven't look at that code in ages.

**Comment by fturib** [comment]
Hum... I am not sure I follow.
my current PR here aims to allow properly these use cases : (part1 and part2) https://github.com/coredns/coredns/pull/1501
no ?

for Part2, the IP will be accepted by the socket listener only if correspond to an interface.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Feature: Abil..." ]
>Hum... I am not sure I follow.
>my current PR here is covering these use cases : https://github.com/coredns/coredns/pull/1501
>no ?

I would like to keep these two parts in two separate PRs, to ease reviewing and 
reasoning about each change.

**Comment by fturib** [comment]
That means isolating 
for 1: the OverlapChecker + Key enhancement
for 2: the ability to generate extra Keys and have BIND participate to that generation.

**Comment by fturib** [comment]
Question for 2:
It is a hack to have BIND, that is a plugin and should be parsed AFTER the key validation, participate to the Key processing.

- right now I made 'less a hack' by allowing Registering keyEnhancers (sort of mini-plugin for Key processing).
is it too heavy ? Would we prefer a Hack for BIND only .. maybe move the code of BIND in dnsserver/register .. (without changing the way we write the stanza). ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Feature: Abil..." ]
>That means isolating
>for 1: the OverlapChecker + Key enhancement
>for 2: the ability to generate extra Keys and have BIND participate to that generation.

I'm not sure I'm following here, but yes... Although I my mind 
1. multiple listen addresses (configured by `bind`)
2. "overlapping" zone+port support

**Comment by fturib** [comment]
@miekg : I am re-reading your definition of Part1 and Part2. I am ok with the definition, but not with the Stanza.

### Part1 : BIND can update the config.ListenHost **only ONE**
we can support the following configurations:

```
. {
 bind 127.0.0.1
 whoami
}

. {
 bind ::1
 whoami
}

. {
  bind 192.168.1.1
 whoami
}

```
 

### Part2 : Bind is allowed to write **several* addresses somehow, and we generate on the fly the needed keys (on the same BlocServer)

We can support the following configuration:

```
. {
 bind 127.0.0.1 ::1
 whoami
}

. {
  bind 192.168.1.1
 whoami
}

```

**Comment by fturib** [comment]
We need to make Part1 before Part2. In other words, view from code, making part2 will include anyway Part1.

**Comment by miekg** [comment]
ok, that's sgtm, I personally feel just allowing multiple addresses is the easier change, but ymmv

**Comment by fturib** [comment]
Hum.. after a second though, I am not sure that help **from the point of view of the code** to separate the parts.

I need to dive into before replying here ...

**Comment by fturib** [comment]
After looking sequence of operation in the code, we may go the way proposed by Miek, but move the validation of overlapping in another place.

That means, at the end, proposing changes in 2 parts:

1- accept multiple address in BIND plugin
2- allow overlapping zones+port, if on different addresses.

I can reuse some code of my PR, but globally will be more simple than the proposed PR.

**Comment by fturib** [comment]
I reopened this issue as the Part 2 is not done yet.

Thanks for review and merge of part1.

I expect to open the PR for part 2 =  "allow overlapping zones+port, if on different addresses", by  today or tomorrow.

**Comment by fturib** [comment]
All parts are now implemented.
