### ISSUE TITLE
plugin/kubernetes: support for multiple clusters (for Istio)

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1483]
Istio requires the ability to resolve cluster IPs for services from multiple clusters. In essence this means putting multiple `kubernetes` plugins in the same server block, and serving records from all of them.

These could be all mapped to the same `cluster.local` domain (in which case `fallthrough` would be needed), or to separate domains.

@costinm PTAL

**Comment by miekg** [comment]
> These could be all mapped to the same cluster.local domain

this is already a terrible design from the DNS perspective.

>  (in which case fallthrough would be needed), or to separate domains.

separate domains sounds *way* saner. 

I don't even think we should support the first option.

**Comment by johnbelamaric** [comment]
Yes, agreed, separate domains makes more sense - though as I recall @costinm suggested that some Istio users want it the other way.

**Comment by miekg** [comment]
yeah I can understand the user's need, but they prolly don't fully understand the finesses of the fine DNS protocol :)

**Comment by johnbelamaric** [comment]
This will be in here: https://github.com/coredns/kubernetai

**Comment by costinm** [comment]
Regarding the 'insane' option: Istio attempts to expose a 'mesh' of services, and allow user flexibility in how he names. You may have app1.namespace.mydomain.com run in a k8s clusters A and B, and app2.namespace.cluster.mydomain.com to be in k8s clusters B and C, and maybe move around to cluster D.  User shouldn't have to change the name he uses in the app. 
The insane part is that he may get different cluster IPs, so istio will need to generate capture config for all.

**Comment by costinm** [comment]
Added https://github.com/istio/istio/issues/3361 to track on our side.

**Comment by johnbelamaric** [comment]
We may want to consider an option to turn off endpoint records, if Istio only cares about cluster IPs (which come from services). That would avoid a watch on endpoints for a bunch of clusters.

**Comment by csbell** [comment]
While individual endpoints may routable between clusters, ClusterIPs (aka Kubernetes services) are not routable outside of a single cluster (even if nodes from multiple clusters come from the same routable subnet). This is why istio taps into k8s endpoints rather than k8s services to route over its mesh.

**Comment by johnbelamaric** [comment]
@csbell I see your point. As I understand it Istio will map the cluster IPs back to names internally and then apply their policies to the endpoints. So, yeah, I am not sure in many cases that this will be useful outside of with Istio. You would need something more to get it to work for real multi-cluster SD. I'll think about that.

**Comment by johnbelamaric** [comment]
This has been implemented as at the `kubernetai` external plugin.
