### ISSUE TITLE
plugin/rewrite: incorrect D0 option in the REPLY

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1489]
## Description 

on any DNS Server, the REPLY will be filtered differently if the D0 flag of the QUERY is set or not.
(see RFC 4035 , https://www.ietf.org/rfc/rfc4035.txt, 3.2.1.  The DO Bit).

on CoreDNS, we change (sometime) the QUERY by adding a OPT record and set the D0 bit to 1.
That is done in the rewriting process of the QUERY.

The plugin ensure to revert back the QUERY when it is resolved, **but does not take care to re-write the REPLY depending the D0 bit of the initial query**.

## Reproduction case

Corefile to use:
```
.:5356 {
    bind 127.0.0.1
    log
    errors
    proxy . 8.8.8.8:53 {
        protocol dns force_tcp
    }
}
.:5358 {
    log
    errors
    rewrite edns0 local set 0xffee 0xfa123467
    proxy . 8.8.8.8:53 {
        protocol dns force_tcp
    }
}
```

Run the query : (through the rewrite plugin)

$ `dig @127.0.0.1 -p 5358 nxdomaingmail.com`

You will see the reply with all NSSEC records - where it should not
```
; <<>> DiG 9.8.3-P1 <<>> @127.0.0.1 -p 5358 nxdomaingmail.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50989
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 8, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 512
;; QUESTION SECTION:
;nxdomaingmail.com.		IN	A

;; AUTHORITY SECTION:
com.			846	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1517863063 1800 900 604800 86400
com.			846	IN	RRSIG	SOA 8 1 900 20180212203743 20180205192743 46967 com. OrKJy64oov/K7WN8FoF3tRhOxP/JE0nbZ6wkJky0AksDncjJGsnJwDJQ V5Pwn2i5uEEcA/ZqvNEMH2+mcpOygCZQjiSkRKFMw+xqdxoPkDPqFIdu IdF9dbM3ZWDvgpj7eUbZ4FynZ6b4kAE9xG7CBqF3tgJDZTLdw0QGTjmI d4E=
CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86346 IN NSEC3 1 1 0 - CK0Q1GIN43N1ARRC9OSM6QPQR81H5M9A NS SOA RRSIG DNSKEY NSEC3PARAM
CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86346 IN RRSIG NSEC3 8 2 86400 20180209054646 20180202043646 46967 com. mVmBPeghE+f4Lr/9Pg4mTbPCqb8dTwuGQN6c6LgxoPjNHU617WYZdB8c fc9hfpNVDbGHyDILG8g0qEmgAMmuxzZctHXKphDxlG/rNmimJp1tdLyq 0phOn1VLen53hS7JL2pt+MdP34+8G8Im00APE1tKbppTZQXe2JLCMECh eVU=
JE04P52G6CGCCVK2G8T67P9PQDA7H4Q5.com. 86346 IN NSEC3 1 1 0 - JE0560TT74LKOLF3QEHMGI4V2PPSTLUG NS DS RRSIG
JE04P52G6CGCCVK2G8T67P9PQDA7H4Q5.com. 86346 IN RRSIG NSEC3 8 2 86400 20180210053049 20180203042049 46967 com. HLZ0a8ZkRgt0taIxuwejBEGcf85Y1xGmYyW7+MSz1SDnJylXEJMTDv/9 pgE/kTX/639StwwIm013MpL4yAjF0+bNYvyYNp22ARsU7qT57KHpHRZe ooL+1/SxBFpBqG/WHFJSF+6GqcihsEt35v4dcJGVhm4cqH2gqtnyTsnU WpU=
3RL20VCNK6KV8OT9TDIJPI0JU1SS6ONS.com. 86346 IN NSEC3 1 1 0 - 3RL3ODP8D910939I655B97GAQU6VE1Q7 NS DS RRSIG
3RL20VCNK6KV8OT9TDIJPI0JU1SS6ONS.com. 86346 IN RRSIG NSEC3 8 2 86400 20180210052511 20180203041511 46967 com. a0m6Y8gUH0nvyXqxHquEBJd+Cnhh1j/EeLDIiuw42IgHOSJp1PPUOHmC /gBH2neM8bNERviZK95C8nMUgAxyr9F5HA2ccRVcdQbuUbemXdSNlOlZ vjyPRTsXmxkFOwYTN8kguYbMOBBQv7TIQUpRT/XUz6Wbj941DYR+Pc7m 2xI=

;; Query time: 24 msec
;; SERVER: 127.0.0.1#5358(127.0.0.1)
;; WHEN: Mon Feb  5 15:39:00 2018
;; MSG SIZE  rcvd: 1009
```

Run the query : (without the rewrite plugin)

$ `dig @127.0.0.1 -p 5356 nxdomaingmail.com`

**The reply is the one expected according to RFE**

```
; <<>> DiG 9.8.3-P1 <<>> @127.0.0.1 -p 5356 nxdomaingmail.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 15169
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;nxdomaingmail.com.		IN	A

;; AUTHORITY SECTION:
com.			821	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1517863033 1800 900 604800 86400

;; Query time: 24 msec
;; SERVER: 127.0.0.1#5356(127.0.0.1)
;; WHEN: Mon Feb  5 15:38:56 2018
;; MSG SIZE  rcvd: 108


```

**Comment by fturib** [comment]
Note, the log generated by CoreDNS also see the same issue:

See the difference on the reply for the same request ...

```
127.0.0.1 - [05/Feb/2018:15:38:56 -0500] 15169 "A IN nxdomaingmail.com. udp 35 **false 512**" NXDOMAIN qr,rd,ra 111 24.421743ms
127.0.0.1 - [05/Feb/2018:15:39:00 -0500] 50989 "A IN nxdomaingmail.com. udp 55 **true 4096**" NXDOMAIN qr,rd,ra 1133 24.177436ms
```

**Comment by johnbelamaric** [comment]
I don't think there is any reason to do SetDo in there. I don't know why I did that. I think it was probably just a copy/paste thing, maybe I pulled the code from somewhere else?

**Comment by greenpau** [comment]
> The plugin ensure to revert back the QUERY when it is resolved, but does not take care to re-write the REPLY depending the D0 bit of the initial query.

@fturib , one of the ways to do it is via `ResponseRules`. See:

* https://github.com/coredns/coredns/blob/367ed65f226a9e7bd137ffc41aead6d16452854d/plugin/rewrite/reverter.go#L11
* https://github.com/coredns/coredns/blob/367ed65f226a9e7bd137ffc41aead6d16452854d/plugin/rewrite/reverter.go#L24

Perhaps adding `SetDo` (or similar) to `ResponseRule` ... 🤔

**Comment by fturib** [comment]
@johnbelamaric : If I read the RFE, I think it is expected to

**Comment by fturib** [comment]
Sorry .. I pushed the wrong button.

**Comment by johnbelamaric** [comment]
That's the DNSSEC RFC. I don't think EDNS0 automatically implies the DO bit should be set. @miekg or @cricketliu can you clarify?

**Comment by cricketliu** [comment]
On Feb 6, 2018, at 10:22 AM, John Belamaric <notifications@github.com<mailto:notifications@github.com>> wrote:


That's the DNSSEC RFC. I don't think EDNS0 automatically implies the DO bit should be set. @miekg<https://github.com/miekg> or @cricketliu<https://github.com/cricketliu> can you clarify?

Yes, it's certainly possible to use EDNS0 without DO set.

cricket

**Comment by johnbelamaric** [comment]
Thanks - so it would seem the solution is just to take out the line that does the SetDo.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/rewrit..." ]
>Thanks - so it would seem the solution is just to take out the line that does the SetDo.

unless the original query had it
(sorry following from afar - not sure if this has been mentioned)

/Miek

--
Miek Gieben

**Comment by johnbelamaric** [comment]
Yes, this is unrelated to the original query - the requested change would leave it the same as the original query, which the current code does not.
