### ISSUE TITLE
on-the-fly v6 generation

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#149]
As coredns middleware.

on-the-fly v6 reverse generation.

**Comment by miekg** [comment]
See http://all-knowing-dns.zekjur.net/

**Comment by project0** [comment]
This is exactly what i am currently working on, but for v4 and v6 ;-). I need this for the AWS internal dns zones (compute.internal)

**Comment by miekg** [comment]
Interesting!

Meaning you're preparing a PR for a new coredns middleware?

**Comment by stp-ip** [comment]
Seems done.
