### ISSUE TITLE
plugin/reverse: no owner

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1502]
The (soon to be pushed) OWNERS file for the *reverse* plugin is empty. This doesn't mean it is not maintained but it should have someone stepping up. If not then we should slowly remove it.
1. Move it to coredns/reverse
2. Remove it from plugin.cfg

**Comment by project0** [comment]
@miekg sry for being not present, i was a little bit busy the last time. 
I think the reverse plugin has been superseded by the template plugin (cc @rtreffer).
What do you think?

**Comment by miekg** [comment]
np. Good to hear from you.

Yeah. *template* should be able to emulate *reverse*. Should update that readme.md with how to do this.
