### ISSUE TITLE
CoreDNS continues to look for zone data files in old root after root directive added

### ISSUE THREAD

**Issue by cricketliu** [coredns/coredns#1508]
I initially configured a test zone like so:

```
. {
        proxy . 8.8.8.8
        cache
        chaos CoreDNS-1.0.5 cricket@infoblox.com
        log
        errors

        file db.foo.example foo.example {
                transfer to *
        }
}
```

That worked fine.  But then I moved db.foo.example into /etc/coredns, added a new RR to the zone, added the statement "root /etc/coredns" to Corefile, and then sent SIGUSR1 to coredns.  coredns read the modified zone data file (yay!) but continues to look in the old location, according to coredns's error output:

```
2018/02/08 18:30:45 [INFO] Reloading
2018/02/08 18:30:45 [INFO] Reloading complete
2018/02/08 18:30:56 [INFO] Successfully reloaded zone "foo.example." in "/etc/coredns/db.foo.example" with serial 2018020801
127.0.0.1 - [08/Feb/2018:18:30:56 +0000] 35360 "A IN www.foo.example. udp 57 false 4096" NOERROR qr,aa,rd,ra 93 224.587µs
2018/02/08 18:31:14 [INFO] Successfully reloaded zone "foo.example." in "/etc/coredns/db.foo.example" with serial 2018020801
2018/02/08 18:31:26 [ERROR] Failed to open zone "foo.example." in "db.foo.example": open db.foo.example: no such file or directory
2018/02/08 18:31:45 [ERROR] Failed to open zone "foo.example." in "db.foo.example": open db.foo.example: no such file or directory
```

(Note the two errors at the end.)

Perhaps coredns isn't deleting the old configuration for the zone?

**Comment by cricketliu** [comment]
Sure enough, committing the whole configuration to a new image and then starting a new container with that image clears up the problem.  My uneducated guess is that the old zone's context simply isn't being cleaned up.

**Comment by johnbelamaric** [comment]
Looks like a similar issue to #1455 and #1472 and #1473 

Plugins written without reload in mind.

**Comment by miekg** [comment]
yes, the z.reload() isn't killed I guess. Probably was too lazy to implement that. As the Go saying goes "don't start a goroutine if you don't know how to stop it"

**Comment by miekg** [comment]
Note that even if we had some kind of reload test infrastructure, actually catching this would be super tricky. I.e. would need to grep for errors in the logs?
