### ISSUE TITLE
figure out a way to test process reload

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1510]
The *reload* plugin uncovered quite a few bugs in other plugins not honoring updated config while doing a reload. This is partly because of lack of testing, i.e. an actual process reload is impossible while running a go test (afaict). So you either need to work around it, or forgo testing this.

To make things easier we would need to invest in some test helper function(s), that either performs such a reload or calls the right methods to fake the reload.

**Comment by johnbelamaric** [comment]
It certainly can be done in the CI. Harder to do in a unit test.

**Comment by johnbelamaric** [comment]
You can call instance.Reload, that might be good enough to flush out most bugs.

**Comment by johnbelamaric** [comment]
Restart I think not reload.

**Comment by miekg** [comment]
Figured something like https://github.com/coredns/coredns/pull/1561 may or may not be useful. Haven't actually used in a test.

**Comment by miekg** [comment]
#1561 didn't work, because I had a thing where only the CoreDNS logging would notify me of the problem.
Which can be done of course; but now you're looking a test function that:
* gets 2 corefiles (`a` and `b`)
* starts coredns with `a`
* replaces `a` with `b`
* reload coredns
* performs a validation function which if you care about logs should attach it self before hand to the coredns process to capture those

So to echo @johnbelamaric here: this will be very hard to do in a unit test; esp if we want to make it generic enough for all use cases.

So CI it is, but even there it can be tricky. Maybe some silly shell scripting can help here; after all it's starting processes, replacing files, sending signals and grepping output (in most cases)

**Comment by greenpau** [comment]
@miekg , what if `coredns`
* maintained a set of timers that had information like `start_datatime`, `restarted_at`
* then `metrics` plugin exposes that information
* take metrics prior to reload
* reload
* take metrics after the reload
* analyze the metrics ...

it is just a thought. Idk whether it makes sense

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] figure out a ..." ]
>@miekg , what if `coredns`
>* maintained a set of timers that had information like `start_datatime`, `restarted_at`
>* then `metrics` plugin exposes that information
>* take metrics prior to reload
>* reload
>* take metrics after the reload
>* analyze the metrics ...
>
>it is just a thought. Idk whether it makes sense

But sometimes the reload fails so you can't even get new metrics... Or you need 
to test the metrics plugin itself. Or you hit #1455 where some setup fails (but 
still is done), and you're trying to resurrect the old process.

**Comment by greenpau** [comment]
> But sometimes the reload fails so you can't even get new metrics...

@miekg , 👍

**Comment by miekg** [comment]
test/reload_test.go has the latest, closing here as those test seem to be pretty good at catching some stuff.
