### ISSUE TITLE
avahi / Bonjour / mDNS plugin for CoreDNS?

### ISSUE THREAD

**Issue by vielmetti** [coredns/coredns#1519]
I am using Avahi on a Raspberry Pi (running Hypriot) to advertise a hostname.local on the local network. My DNS is a Mac laptop running with the default config on localhost installed per the Homebrew instructions, which looks up /etc/hosts and then forwards everything to Google DNS. It moves from place to place.

I didn't see any docs or code that mentioned Avahi, and thought that at minimum it would be good to mention that somewhere in the docs, and ideally provide some kind of doc example of how to use and configure a network that uses it. 

I also searched for Bonjour in the docs and code Github repos and didn't find them.

I expect to serve up a .local domain with whatever hosts happen to be advertising on the local network.

update: looks like #317 (a reference to mDNS, another name for this) is relevant.

second update: the Mac command that digs out the data I want is 

```
$ dns-sd -G v4 idaeus.local
DATE: ---Sat 10 Feb 2018---
14:55:14.640  ...STARTING...
Timestamp     A/R Flags if Hostname                               Address                                      TTL
14:55:14.837  Add     2  4 idaeus.local.                          10.10.10.192                                 120
```

**Comment by greenpau** [comment]
> I expect to serve up a .local domain with whatever hosts happen to be advertising on the local network.

@vielmetti , it is a very nice use case! 👍 I guess you would need `plugin/mdns` 😄  In which case, you would need to create it. I would start https://github.com/miekg/dns/issues/348#issuecomment-214746020. Then, I would look [here](https://github.com/grandcat/zeroconf).

**Comment by greenpau** [comment]
@vielmetti , imagine that we have that `plugin/mdns`. What would be the configuration stanza look like in CoreDNS configuration? e.g.

```
  mdns {
     ...
  }
```

**Comment by vielmetti** [comment]
Good question, @greenpau . mDNS tends to be pretty self-configuring, in the sense that if you follow the standards you get pretty much the same experience everywhere. I could see a default to the mdns domain serving up `.local` and then an override optional that would map the mDNS domain to some other TLD, but beyond that everything should work by autodiscovery.

**Comment by greenpau** [comment]
@vielmetti , I will clatify a bit ...

mDNS protocol defines the communication, packet structure, etc. Considering CoreDNS deamon would subscribe to `224.0.0.251` and listen to queries:

- What domain would it serve?
- Do you maintain a bind file for .local?
- Do you allow auto registration?
- Will you rewrite?
- Will you proxy?
- etc.

**Comment by vielmetti** [comment]
All good questions @greenpau .

I think there are really two separate threads here. One would be "coredns as an mdns server", providing answers to queries for an appropriate name  or set of names on .local, analogous to [avahi-daemon](http://manpages.ubuntu.com/manpages/trusty/man5/avahi-daemon.conf.5.html). The other is "coredns as mdns client", able to look up names in the .local domain on that multicast address.

My initial use case is more 'client' than 'server', as described in the initial post the initial use case would be for my portable Macbook to look up resources on whatever net it happens to be on.

**Comment by greenpau** [comment]
> my portable Macbook to look up resources on whatever net it happens to be on.

@vielmetti , what are the resources? Is it a zone? How are they populated?

> I expect to serve up a .local domain with whatever hosts happen to be advertising on the local network.

Is the plugin the one who should be assembling `.local` domain in runtime based on the multicast advertisements?

**Comment by vielmetti** [comment]
So I'm rereading the RFC https://tools.ietf.org/html/rfc6762

which reads in part

```
   Any DNS query for a name ending with ".local." MUST be sent to the
   mDNS IPv4 link-local multicast address 224.0.0.251 (or its IPv6
   equivalent FF02::FB).  The design rationale for using a fixed
   multicast address instead of selecting from a range of multicast
   addresses using a hash function is discussed in Appendix B.
   Implementers MAY choose to look up such names concurrently via other
   mechanisms (e.g., Unicast DNS) and coalesce the results in some
   fashion.  Implementers choosing to do this should be aware of the
   potential for user confusion when a given name can produce different
   results depending on external network conditions (such as, but not
   limited to, which name lookup mechanism responds faster).
```

I think that encapsulates the minimal needs pretty well.

**Comment by johnbelamaric** [comment]
In theory this should work for the client portion:

```
.:53 {
 log
 forward local 224.0.0.251:5353 {
	health_check 0
	max_fails 0
 }
 proxy . /etc/resolv.conf
}
```

But it doesn't...not sure why. `dig -p 5353 @224.0.0.251` works but not the above.

**Comment by johnbelamaric** [comment]
Ah. Looks like it sends multicast replies not unicast. They define a special bit to ask for a unicast reply. So I guess there is some work to be done here.

**Comment by johnbelamaric** [comment]
Or maybe not for one-shot queries. Sigh. I can't look into it more now, maybe tomorrow.

```
   The most basic kind of Multicast DNS client may simply send standard
   DNS queries blindly to 224.0.0.251:5353, without necessarily even
   being aware of what a multicast address is.  This change can
   typically be implemented with just a few lines of code in an existing
   DNS resolver library.  If a name being queried falls within one of
   the reserved Multicast DNS domains (see Sections 3 and 4), then,
   rather than using the configured Unicast DNS server address, the
   query is instead sent to 224.0.0.251:5353 (or its IPv6 equivalent
   [FF02::FB]:5353).  Typically, the timeout would also be shortened to
   two or three seconds.  It's possible to make a minimal Multicast DNS
   resolver with only these simple changes.  These queries are typically
   done using a high-numbered ephemeral UDP source port, but regardless
   of whether they are sent from a dynamic port or from a fixed port,
   these queries MUST NOT be sent using UDP source port 5353, since
   using UDP source port 5353 signals the presence of a fully compliant
   Multicast DNS querier, as described below.

   A simple DNS resolver like this will typically just take the first
   response it receives.  It will not listen for additional UDP
   responses, but in many instances this may not be a serious problem.
   If a user types "http://MyPrinter.local." into their web browser, and
   their simple DNS resolver just takes the first response it receives,
   and the user gets to see the status and configuration web page for
   their printer, then the protocol has met the user's needs in this
   case.




Cheshire & Krochmal          Standards Track                    [Page 8]
 
RFC 6762                      Multicast DNS                February 2013


   While a basic DNS resolver like this may be adequate for simple host
   name lookup, it may not get ideal behavior in other cases.
   Additional refinements to create a fully compliant Multicast DNS
   querier are described below.
```

**Comment by miekg** [comment]
For some (fun) background reading on what is supported in the dns lib: https://github.com/miekg/dns/issues/423

From the theoretical standpoint I think the following:
* any mdns implementation can just start with a bare bones config, just `mdns` might be enough.
* IIRC mdns means you listen for broadcast dns requests and then answer them. These requests might be blocked by CoreDNS even before they are given to a Server; for further processing.

All in all, looks like a nice project for someone with a bit of time on their hands :)

**Comment by johnbelamaric** [comment]
I am not clear after reading that why the simple resolver case doesn't work.

**Comment by johnbelamaric** [comment]
Ok, yeah, the issue is we aren't setting the unicast bit so it is replying to the multicast address. See the "QM" here, it should be "QU":

```
09:38:04.200191 IP (tos 0x0, ttl 1, id 15185, offset 0, flags [none], proto UDP (17), length 79)
    ann-m-jbelamaric.home.59541 > 224.0.0.251.mdns: [udp sum ok] 31280+ [1au] A (QM)? ann-m-jbelamaric.local. ar: . OPT UDPsize=4096 (51)
```

So, the simplest fix is to notice we are doing multicast and set that bit, and then we can be a client at least.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] avahi / Bonjo..." ]
>Ok, yeah, the issue is we aren't setting the unicast bit so it is replying to the multicast address. See the "QM" here, it should be "QU":
>
>```
>09:38:04.200191 IP (tos 0x0, ttl 1, id 15185, offset 0, flags [none], proto UDP (17), length 79)
>    ann-m-jbelamaric.home.59541 > 224.0.0.251.mdns: [udp sum ok] 31280+ [1au] A (QM)? ann-m-jbelamaric.local. ar: . OPT UDPsize=4096 (51)
>```
>
>So, the simplest fix is to notice we are doing multicast and set that bit, and then we can be a client at least.

Where should that bit be set? On the socket? I.e. dns.ResponseWriter in this 
context?

**Comment by johnbelamaric** [comment]
From the RFC:

```
   To avoid large floods of potentially unnecessary responses in these
   cases, Multicast DNS defines the top bit in the class field of a DNS
   question as the unicast-response bit.  When this bit is set in a
   question, it indicates that the querier is willing to accept unicast
   replies in response to this specific query, as well as the usual
   multicast responses.  These questions requesting unicast responses
   are referred to as "QU" questions, to distinguish them from the more
   usual questions requesting multicast responses ("QM" questions).  A
   Multicast DNS querier sending its initial batch of questions
   immediately on wake from sleep or interface activation SHOULD set the
   unicast-response bit in those questions.
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] avahi / Bonjo..." ]
>From the RFC:
>
>```
>   To avoid large floods of potentially unnecessary responses in these
>   cases, Multicast DNS defines the top bit in the class field of a DNS
>   question as the unicast-response bit.  When this bit is set in a
>   question, it indicates that the querier is willing to accept unicast
>   replies in response to this specific query, as well as the usual
>   multicast responses.  These questions requesting unicast responses
>   are referred to as "QU" questions, to distinguish them from the more
>   usual questions requesting multicast responses ("QM" questions).  A
>   Multicast DNS querier sending its initial batch of questions
>   immediately on wake from sleep or interface activation SHOULD set the
>   unicast-response bit in those questions.
>```

ohhhh. Super easy then.

/Miek

--
Miek Gieben

**Comment by johnbelamaric** [comment]
Yeah. So, we could do this a few ways though, depending on how much flexibility we want to give. I mean, we could:

- auto-detect that we are going to 224.0.0.251 or IPv6 equiv and set the bit in proxy/forward and in that case maybe also automatically go to 5353 unless they explicitly give a different port
- add an mdns-proxy plugin that grabs queries for `.local` - but that may mess with folks like k8s that abuse the `.local` domain

If we implement full mDNS we also might have to alter this behavior, we should think about how that will com into play.

**Comment by johnbelamaric** [comment]
of course in the k8s case you don't have to enable mdns-proxy. so, i think that's probably the better option. less magic. and we can do full mdns later with a different plugin

**Comment by johnbelamaric** [comment]
Sigh. I should probably read the whole RFC instead of just bits and pieces at a time...

According to [section 6.7](https://tools.ietf.org/html/rfc6762#section-6.7), just the `proxy` should work. Because our source port won't be 5353. However, it doesn't in practice work, at least not on my mac.

Now, just setting the unicast bit may not *always* work. It's kind of convoluted:

https://tools.ietf.org/html/rfc6762#section-5.4

the operative paragraph (with added emphasis):

>   When receiving a question with the unicast-response bit set, a
>   responder **SHOULD _usually_** respond with a unicast packet directed back
>   to the querier.  However, if the responder has not multicast that
>   record recently (within one quarter of its TTL), then the responder
>   **SHOULD _instead_** multicast the response so as to keep all the peer
>   caches up to date, and to permit passive conflict detection.  In the
>   case of answering a probe question (Section 8.1) with the unicast-
>   response bit set, the responder should always generate the requested
>   unicast response, but it may also send a multicast announcement if
>   the time since the last multicast announcement of that record is more
>   than a quarter of its TTL.

That's really annoying. Why not "in addition" not "instead"? Makes it harder. The exception to the rule is for "probes", which basically are queries with qtype ANY. But given that in that context it is expecting you to fully implement the RFC, I am not sure how it will behave in the wild.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] avahi / Bonjo..." ]
>Yeah. So, we could do this a few ways though, depending on how much flexibility we want to give. I mean, we could:
>
>- auto-detect that we are going to 224.0.0.251 or IPv6 equiv and set the bit in proxy/forward and in that case maybe also automatically go to 5353 unless they explicitly give a different port
>- add an mdns-proxy plugin that grabs queries for `.local` - but that may mess with folks like k8s that abuse the `.local` domain
>
>If we implement full mDNS we also might have to alter this behavior, we should think about how that will com into play.

Where does for proxying requirement come from?

Regarding `.local` I would assume you still need configure a Corefile, i.e.:

 ~~~
 .local {
       mdns
}
~~~

Does mdns for the `.local` domain.

**Comment by johnbelamaric** [comment]
I think we need to distinguish between being a simple proxy that forwards queries to the multicast address and being a full-fledged mdns server that does DNS-SD and fully implements the mDNS RFC. And fully implementing that RFC is not a quick and simple task.

**Comment by greenpau** [comment]
@miekg , mDNS topic interest me a lot. I would like to work on this feature, because it would make CoreDNS more popular for the use with home networks.

I plan understanding how `plugin/pprof` works and try mimicking relevant behavious to `plugin/mdns`. The  `plugin/pprof`  looks suitable because it implement a separate listener (in mDNS case I would need creating multicast listener). Any words of advice?

**Comment by greenpau** [comment]
... 🤔 💭 ... let's say our server listens to DNS requests on UDP/5353
- a multicast packet arrived, destination port 5353
- coredns process would not get the packet unless the process listens to 224.0.0.251 group: https://golang.org/pkg/net/#ListenMulticastUDP

I would say if `mdns` is enabled, then "main" server cannot listen on port 5353, because the interfaces would conflict.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] avahi / Bonjo..." ]
>@miekg , mDNS topic interest me a lot. I would like to work on this feature, because it would make CoreDNS more popular for the use with home networks.

+1

>I plan understanding how `plugin/pprof` works and try mimicking relevant behavious to `plugin/mdns`. The  `plugin/pprof`  looks suitable because it implement a separate listener (in mDNS case I would need creating multicast listener). Any words of advice?

Note that pprof only opens a non-dns socket (which mdns sort also is).

Opening your own sockets may clash with what the server itself is already 
opening. but in this case I think it's best to experiment a litte inside the 
plugin to see how this pans out, esp because mdns is so different.

Interaction with other dns plugins can also be interesting; can these responses 
be cached? How does that work?

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] avahi / Bonjo..." ]
>... 🤔 💭 ... let's say our server listens to DNS requests on UDP/5353
>- a multicast packet arrived, destination port 5353
>- coredns process would not get the packet unless the process listens to 224.0.0.251 group: https://golang.org/pkg/net/#ListenMulticastUDP
>
>I would say if `mdns` is enabled, then "main" server cannot listen on port 5353, because the interfaces would conflict.

Should we extend the *bind* plugin to say something about this? Actually it may 
not be need to extend it, we just need to take this (or any other multi case 
address) into account.

But then I wonder how other plugins work with this:

~~~
.:5353 {
    bind 224.0.0.251
    cache
    forward . 1.1.1.1
    mdns
}
~~~

That works for the listening, but do other plugins now need to check for mdns 
(could extend to the Match function to do this).

/Miek

--
Miek Gieben

**Comment by greenpau** [comment]
> Should we extend the *bind* plugin to say something about this

@miekg, interesting point 👍 [Here](https://github.com/coredns/coredns/blob/master/core/dnsserver/register.go#L114-L146), the servers get created. In case of DNS, it points [here](https://github.com/coredns/coredns/blob/master/core/dnsserver/server.go#L30-L46). The first impression is that the sockets a being configured in "github.com/miekg/dns".

👨‍🔬  The next stop is `server [2]*dns.Server // 0 is a net.Listener, 1 is a net.PacketConn (a *UDPConn) in our case.`

**Comment by miekg** [comment]
Yeah this might get hairy, but worth a try.

**Comment by celebdor** [comment]
If anybody wants to give it a shot, there's https://github.com/openshift-metalkube/coredns-mdns

**Comment by trown** [comment]
I have been successfully using this plugin (github.com/openshift-metal3/coredns-mdns). I put up a PR to add this https://github.com/coredns/coredns/pull/2832

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] avahi / Bonjo..." ]
>I have been successfully using this plugin (github.com/openshift-metal3/coredns-mdns). I put up a PR to add this https://github.com/coredns/coredns/pull/2832

Nice. I'll find some time to review that. 

Thanks!
