### ISSUE TITLE
plugin/rewrite: no metrics

### ISSUE THREAD

**Issue by greenpau** [coredns/coredns#1520]
The `plugin/rewrite` has no metrics. It would be nice to have a counters of request rewrites and response rewrites, e.g.:

* `coredns_rewrite_request_name`
* `coredns_rewrite_answer_name`

or something similar to that. At the moment, I did not have a chance to dive in to how `plugin/metrics` is being implemented. It will be a good opportunity to learn it.

**Comment by miekg** [comment]
should be relative easy to do

**Comment by jiachengxu** [comment]
Hi @miekg and @greenpau, I am interested in this issue, can I try to take it?
Here are some questions and my thoughts, PTAL.
- What metrics do we need?
IMO, every `FIELD` should have a counter, e.g.:
for request rewrites:
    - `rewrite_request_name_total`
    - `rewrite_request_type_total`
    - `rewrite_request_class_total`
    - `rewrite_request_edns0_total`

    for response rewrites:
    - `rewrite_response_ttl_total`
    - `rewrite_response_name_total`

- What labels should the rewrite metrics have?
To be honest, I don't really know. Do you have any suggestions?

Please feel free to correct me and I am looking forward to fixing this!

Thanks,
Jiacheng

**Comment by greenpau** [comment]
@jiachengxu, go for it! I think domain name label would be appropriate.

**Comment by greenpau** [comment]
@jiachengxu, when it comes to rewriting a name. There could be source and destination domain.

Also, consider a metric “rewrite_enabled” ... that is to tell whether a rewrite plugin is enabled.

**Comment by greenpau** [comment]
@jiachengxu, additionally, think about configuration metrics. For example, “rewrite_rules_total” metric for the total number of configured rules. Perhaps, a label “type” is warranted ... this way you know how many rules of which type were configured.

**Comment by greenpau** [comment]
@jianchengxu, for name rewrites, it would be interesting to count how many rewrites resulted in “noop”, i.e. name is being matched, but not substituted upstream.

**Comment by jiachengxu** [comment]
Hi @greenpau, thanks for your reply!
> when it comes to rewriting a name. There could be source and destination domain.
Also, consider a metric “rewrite_enabled” ... that is to tell whether a rewrite plugin is enabled.  

Yes, I think it makes sense to have a metric `rewrite_enabled`.

> Additionally, think about configuration metrics. For example, “rewrite_rules_total” metric for the total number of configured rules. Perhaps, a label “type” is warranted ... this way you know how many rules of which type were configured.

If I understood correctly, the label "type" here means `FIELD`, i.e., `name`, `type`, `class`, `ttl`,`edns0` and `answer` could be the possible values of the label "type".

> for name rewrites, it would be interesting to count how many rewrites resulted in “noop”, i.e. name is being matched, but not substituted upstream.

Yes, this also makes sense.

**Comment by jiachengxu** [comment]
To summarize, I also put the labels together with metrics:
- for request rewrites:
    - `rewrite_request_name_total{server, match_type, src_domain_name, dest_domain_name}` (the label `match_type` here is the match type, i.e., [exact|prefix|suffix|substring|regex])
    - `rewrite_request_name_noop_total{server, match_type, src_domain_name}`
    - `rewrite_request_type_total{server, src_type, dest_type}`
    - `rewrite_request_class_total{server, src_class, dest_class}`
    - `rewrite_request_edns0_total{server}`

 -  for response rewrites:
    - `rewrite_response_ttl_total{server, match_type, ttl}`
    - `rewrite_response_name_total{server, src_domain_name, dest_domain_name}`

- for the number of rules configured:
    -  `rewrite_rules_total{server, field_type}`(the label `field_type` here means `FIELD` type, i.e.,`name`, `type`, `class`, `ttl`,`edns0` and `answer`.

- for monitoring if rewrite plugin is enabled:
    - `rewrite_enabled{server}`

@greenpau please free to correct me if I missed anything 😄 .

**Comment by jiachengxu** [comment]
I also found [CAUTION about the label](https://prometheus.io/docs/practices/naming/#labels) on Prometheus official website:
> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

From the above statements, I think source and destination domain names are "undounded sets of values", so maybe I should use label for them. What do you think? @greenpau

**Comment by greenpau** [comment]
@jiachengxu , regarding `rewrite_enabled{server}`. What if you created a global metric `plugin_enabled`. Then, if `rewrite` is being used, you could have `plugin_enabled{name="rewrite"}`?

> To summarize, I also put the labels together with metrics

Regarding this stuff ... `rewrite_request_edns0_total`, `rewrite_request_class_total`, etc.
This is where have `edns0` and `class` as metric labels is more beneficial, because it is easily extensible to new types of rewrites. This, `rewrite_request_success_total` would be more appropriate.

> From the above statements, I think source and destination domain names are "undounded sets of values", so maybe I should use label for them. What do you think?

Fair point. However, by and large, you are recording domains, not individual records. The list of domain would be limited to what one configures. Don't think it is a big issue.

**Comment by jiachengxu** [comment]
@greenpau 
>  regarding rewrite_enabled{server}. What if you created a global metric plugin_enabled. Then, if rewrite is being used, you could have plugin_enabled{name="rewrite"}?

Yes, it makes sense. I think it could be an enhancement for the metrics plugin, I created the issue #2273 for that.

> Regarding this stuff ... rewrite_request_edns0_total, rewrite_request_class_total, etc.
This is where have edns0 and class as metric labels is more beneficial, because it is easily extensible to new types of rewrites. This, rewrite_request_success_total would be more appropriate.

I agree with you on putting these metrics to a single one and using a label for a different type. The thing is that, it is easy to put the `rewrite_request_type_total` and `rewrite_request_class_total` together into `rewrite_request_success_total{server, type,  src, dest}`, but I don't know how to fit the `rewrite_request_name_total` and `rewrite_request_edns0_total` in it because `name` and `edns0` could have other labels(e.g., match type for `name` . `local`,`nsid` and `subnet` options for `edns0`.) I can remove these labels and fit them into `rewrite_request_success_total{server, type, src, dest}`, but I am not sure if I should do that. If I don't put them together, then the metric name `rewrite_request_success_total` is not appropriate.

Also, I want to point out that the meaning of `src` and `dest` in the `rewrite_request_success_total{server, type, src, dest}` is different for different type, i.e., if the type is `class`, `src` means source class, and `dest` means destination class, while for `name` type, `src` and `dest` are source domain name and destination domain name.

**Comment by greenpau** [comment]
> I agree with you on putting these metrics to a single one and using a label for a different type.

> Also, I want to point out that the meaning of src and dest

@jiachengxu , all good thoughts. Perhaps, having different metrics is more benefitial. Do that then.

**Comment by jiachengxu** [comment]
@greenpau, I will try to do that, and thanks for the discussion!

**Comment by greenpau** [comment]
@jiachengxu , any progress on the subject?

**Comment by jiachengxu** [comment]
@greenpau , sorry that I just started it after all school work done, will send a PR recently :)

**Comment by palash25** [comment]
Hi @jiachengxu are you still working on this? if not then I would like to give this a try.

**Comment by jiachengxu** [comment]
Hi @palash25 , No, I haven't gotten time for this, just go ahead with it.
