### ISSUE TITLE
Plugin/Kubernetes - some Pod mode queries are not replying the right answer

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1532]
Tested against the last Kubenernetes (MAIN branch). 

## High level after investigation

it looks like the function namespaces(...) has 2 issues:
- it does not work anymore against the last version of Kubernetes. I mean does not return the right answer.
- it is addressing directly the API, on each query that match its usage (pod query on insecure mode, svc query if widlcard service on non wildcard namespace).
=> Which means it has a very slow execution ... 

```
func (k *Kubernetes) namespace(n string) bool {
	ns, err := k.APIConn.GetNamespaceByName(n)
	if err != nil {
		return false
	}
	return ns.ObjectMeta.Name == n
}
```

### Pod queries

**with the option 'pods insecure' on,** 

Valid queries for pods gets an NXDOMAIN whereas  a NOERROR with an A record on the provided IP is expected:

```
10.192.3.2 - [14/Feb/2018:22:34:51 +0000] "A IN 10-192-2-8.default.pod.cluster.local. udp 66 false 4096" NXDOMAIN qr,aa,rd,ra 119 1.534808ms
10.192.3.2 - [14/Feb/2018:22:35:41 +0000] "A IN 10-192-3-2.default.pod.cluster.local. udp 66 false 4096" NXDOMAIN qr,aa,rd,ra 119 4.527718ms
```

But if the query is about a wildcard, then the answer is the one expected:

`10.192.3.2 - [14/Feb/2018:22:55:16 +0000] "A IN 010-192-03-02.any.pod.cluster.local. udp 65 false 4096" NOERROR qr,aa,rd,ra 81 87.368µs
`
```
/ # dig 010-192-03-02.any.pod.cluster.local. A

; <<>> DiG 9.10.4-P3 <<>> 010-192-03-02.any.pod.cluster.local. A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13109
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;010-192-03-02.any.pod.cluster.local. IN	A

;; ANSWER SECTION:
010-192-03-02.any.pod.cluster.local. 5 IN A	10.192.3.2
```

### Service Queries

When queying . wildcard service, on an namespace that exist but has no services, then the reply is NXDOMAIN instead of NODATA expected

`10.192.3.2 - [15/Feb/2018:15:05:30 +0000] "A IN *.test.svc.cluster.local. udp 54 false 4096" NXDOMAIN qr,aa,rd,ra 107 81.831µs
`
```
root@kube-master:/# kubectl get namespaces
NAME          STATUS    AGE
default       Active    21h
kube-public   Active    21h
kube-system   Active    21h
test          Active    24s
root@kube-master:/# kubectl get services --all-namespaces
NAMESPACE     NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             ClusterIP   10.96.0.1       <none>        443/TCP         21h
kube-system   kube-dns               ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP   21h
kube-system   kubernetes-dashboard   NodePort    10.107.45.190   <none>        80:31138/TCP    21h
root@kube-master:/# 

/ # dig *.test.svc.cluster.local. A

; <<>> DiG 9.10.4-P3 <<>> *.test.svc.cluster.local. A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 15560
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;*.test.svc.cluster.local.	IN	A

;; AUTHORITY SECTION:
cluster.local.		300	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1518707130 7200 1800 86400 30

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Thu Feb 15 15:05:30 UTC 2018
;; MSG SIZE  rcvd: 107

```

**Comment by chrisohaver** [comment]
I am currently implementing the work-around I suggested earlier, to add a watch on namespace when pod insecure is on, and use that cache instead of direct API calls (this is much more efficient anyways).

For the wildcard case, we don't need to actually make these calls at all - we could remove them.  But the above fix should fix both cases.

**Comment by chrisohaver** [comment]
> When queying . wildcard service, on an namespace that exist but has no services, then the reply is NXDOMAIN instead of NODATA expected
> `10.192.3.2 - [15/Feb/2018:15:05:30 +0000] "A IN *.test.svc.cluster.local. udp 54 false 4096" NXDOMAIN qr,aa,rd,ra 107 81.831µs`

Hmm.  Seems like the answer should be NXDOMAIN because there are no services that match `*.` ... `test.svc.cluster.local` != `*.test.svc.cluster.local.`

- test.svc.cluster.local` should be NODATA
- `*.test.svc.cluster.local.` should be NXDOMAIN (if nothing matches)

I guess it's a matter of opinion since wildcard-queries is not a standard, and we are the only project implementing it.

**Comment by chrisohaver** [comment]
Verified #1533 fixes `pod insecure` queries in k8s master.
