### ISSUE TITLE
move go files under /plugin/etcd into /plugin/etcd/etcd2

### ISSUE THREAD

**Issue by zhujinghui** [coredns/coredns#1537]
pacakage /plugin/etcd/msg should be also useful for Etcd3 plugin, so maybe we should move the go files under /plguin/etcd/ into /plugin/etcd/etcd2, in the future we can create a /plugin/etcd/etcd3 folder to put Etcd3 plugin, and both Etcd3 and Etcd2 plugin can import /plugin/etcd/msg package. 

WDTK? cc @johnbelamaric

**Comment by miekg** [comment]
Before we move any files we should figure what we want.

1. We can create a new *etcd3* plugin which duplicates quite a bunch of the *etcd* plugin
2. Extend the *etcd* plugin and give it a *etcd3* option to select the etcd3 protocol

I think creating a new plugin make most sense as noone actually wants to use etcd version 2 protocol, but that is all we have. After an *etcd3* plugin is functional we will delete the etcd code.

IOW: all work can be done without touching any etcd code.

**Comment by zhujinghui** [comment]
Sounds good to me.
