### ISSUE TITLE
hosts plugin only works once when specified multiple times

### ISSUE THREAD

**Issue by schoentoon** [coredns/coredns#1539]
When specifying the hosts plugin multiple times in the Corefile, only the last entry will actually work.

```
. {
	hosts /tmp/hosts {
		fallthrough
	}
	hosts /tmp/hosts2 {
		fallthrough
	}
}
```

In the above example only entries from /tmp/hosts2 will get resolved. My use-case for having 2 hosts entries instead of just 1 is that one of them is generated only the fly and maintained by a third party process and the second one is static, maintained manually.

**Comment by miekg** [comment]
This is mostly WAI, but should probably be documented better (there are more plugins that can only be defined ones in a block).

You can also use an inline host file and just specifying the static hosts inside the (first) `hosts` stanza, see the [docs](https://coredns.io/plugins/hosts/), last example.

**Comment by schoentoon** [comment]
I didn't expect this to be WAI as I didn't see anything in the documentation about plugins only being allowed once, nor did I get any errors on startup about the 2 hosts entries. Perhaps make it at least warn about loading the same plugin twice and document it.
As for my use-case, do the inline host entries work next to the file loaded? I'm assuming it does and that would probably solve my entire issue :sweat_smile:

**Comment by miekg** [comment]
> I didn't expect this to be WAI as I didn't see anything in the documentation about plugins only being allowed once, nor did I get any errors on startup about the 2 hosts entries

dnssec plugin suffers from the same, but at least documented it... Making it work or erroring on it is all on the plugin that implements the setup function, so either way requires some effort. Short term fix is being more vocal about this in the docs.

> As for my use-case, do the inline host entries work next to the file loaded? I'm assuming it does and that would probably solve my entire issue 

yes

**Comment by schoentoon** [comment]
I just tested it locally and that solution works, only issue I have with it that it doesn't pick up changes without restarting. But I imagine that wouldn't be a small fix either :joy:. Being more vocal about this in docs seems like a great fix honestly, but I think creating a different issue for that would be a better idea.

**Comment by miekg** [comment]
reloeading changes every once in a while seems like a nice to have though /cc @pmoroney

**Comment by pmoroney** [comment]
Just to verify, you are talking about reloading changes in the in line hosts file in the Corefile?

**Comment by miekg** [comment]
ah no! We already check for changes. (/me just reread the first paragraph of the README.md). Nevermind, reloading CoreDNS should pick up those in-line changes automatically
