### ISSUE TITLE
middleware/proxy: dns.google.com

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#155]
dns.google.com implements dns over https (but not dns over TLS - which is now an RFC). We can implement this in the proxy middleware. Adding another directive like "tls-google" would make it talk https+json protocol to this service.

The endpoint would then need to dns.google.com which we should resolve (on every lookup?). Problem is how do we resolve this address then?

**Comment by miekg** [comment]
https://developers.google.com/speed/public-dns/docs/dns-over-https

has a "spec", basically `data` in the json reply has the text representation of the record:

```
"Authority": [
    {
      "name": "miek.nl.",
      "type": 6,
      "TTL": 1799,
      "data": "linode.atoom.net. miek.miek.nl. 1465445581 14400 3600 604800 14400"
    }
```

easiest way seems to concatenate these in a new string and then call `NewRR()` on it, `TypeToString` the type integer and your basically done. Form a new msg and return that to the client.

The proxy middleware should just have an extra directive `tls google` which enabled the special json over https protocol.

**Comment by splack** [comment]
Hey Miek, are you saying that there is a boot strapping issue with a lookup to dns.google.com needing a lookup of dns.google.com?

The spec seems to suggest that DNSSEC should be used to validate dns.google.com is correct. I'm guessing the TTL should be honored to avoid the DNS+HTTPS for each lookup.

The spec seems to be designed to avoid the insecure or incomplete implementations of host OS DNS resolution. If so, using HTTPS would need to implement and improve the typical host OS resolver function.

There would also need to be a way to trust the certificate issuer (chain) and possibly pin it too, i.e. all the normal HTTP+TLS security stuff.

> Google Public DNS offers DNSSEC-validating resolution over an encrypted HTTPS connection using a web-friendly API that does not require browser or OS configuration or installing an extension. DNS-over-HTTPS greatly enhances privacy and security between a client and a recursive resolver, and complements DNSSEC to provide end-to-end authenticated DNS lookups.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/prox..." ]

> Hey Miek, are you saying that there is a boot strapping issue with a lookup to 
> dns.google.com needing a lookup of dns.google.com?

yes.

> The spec seems to suggest that DNSSEC should be used to validate dns.google.com 
> is correct. I'm guessing the TTL should be honored to avoid the DNS+HTTPS for 
> each lookup.

yep. So we need to re-lookup ever so often.

> The spec seems to be designed to avoid the insecure or incomplete 
> implementations of host OS DNS resolution. If so, using HTTPS would need to 
> implement and improve the typical host OS resolver function.

That's quite a biggy, "One does not simply implement a secure resolver". Maybe 
we should just use another proxy for resolving this name:

So:

```
proxy . dns.google.com {
    resolve 8.8.8.8 8.8.4.4
    tls google # tls *without* google, would implement DNS over TLS
}
```

Which would use 8.8.8.8/4.4 to resolve dns.google.com? Using name in `resolve` 
would obviously be a failure. Using resolve when to 'To's are all IP addresses 
is also an error.

> There would also need to be a way to trust the certificate issuer (chain) and 
> possibly pin it too, i.e. all the normal HTTP+TLS security stuff.

I believe net/http gives you all these goodies.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
Come to think of it, thi should be a separate middleware (i.e. not in the proxy). It does http, let's copy the original proxy from caddy and use that, maybe httpproxy. 

...Or maybe it is so similar to the proxy we should just do it there. The re-resolving of the name might even be useful there.

**Comment by miekg** [comment]
See https://github.com/pforemski/dingo
(that code is GPLv3 though)

**Comment by miekg** [comment]
this is done, see the httpproxy and later the normal proxy middleware.
