### ISSUE TITLE
plugins `startup` and `shutdown` are deprecated

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1550]
They are superseded by `on` (also enabled), but we should remove them, following our deprecation policy: announce, disable (but still include), remove. Where the disable phase, needs a minor (I thought) release.

**Comment by miekg** [comment]
hmmm, caddy already deleted them:
~~~
startupshutdown/startupshutdown.go      | 98 ------------------------------------------------------------------------------------------------
 startupshutdown/startupshutdown_test.go | 69 -------------------------------------------------------------------
 5 files changed, 2 insertions(+), 169 deletions(-)
 delete mode 100644 startupshutdown/startupshutdown.go
 delete mode 100644 startupshutdown/startupshutdown_test.go
~~~

**Comment by miekg** [comment]
We should probably also start vendoring caddy, not 100% how something like the `on` plugin then would reference a caddy plugin (using the full vendored path maybe?)

**Comment by miekg** [comment]
ok, doing so and then a `dep ensure` already pulls in caddy.

**Comment by miekg** [comment]
But checking the PR locally  means I can't compile any plugins anymore:
~~~
# github.com/miekg/redis
./setup.go:32:21: cannot use c (type *"github.com/mholt/caddy".Controller) as type *"github.com/coredns/coredns/vendor/github.com/mholt/caddy".Controller in argument to dnsserver.GetConfig
./setup.go:39:28: cannot use c (type *"github.com/mholt/caddy".Controller) as type *"github.com/coredns/coredns/vendor/github.com/mholt/caddy".Controller in argument to dnsserver.GetConfig
~~~

**Comment by johnbelamaric** [comment]
Shouldn't you just reference it the normal way? That's what the vendor support is for, it will check the vendor dir first.

**Comment by miekg** [comment]
This deprecation is going out with 1.1.0, closing this here.
