### ISSUE TITLE
snippet import doesn't work (or I'm doing it wrong)

### ISSUE THREAD

**Issue by sean-abbott** [coredns/coredns#1554]
Hello!  I'm trying to use snippets a la the caddy file documentation: https://caddyserver.com/docs/caddyfile#snippets

My Corefile looks essentially like

```
(myzone) {
    proxy myzone.net x.x.x.x:53 x.x.y.y:53 {
        policy round_robin
        fail_timeout 1s
        max_fails 1
    }
}

. {
    proxy thezone.net x.x.x.x:53 x.x.y.y:53 {
        policy round_robin
        fail_timeout 1s
        max_fails 1
    }

    import myzone

    errors
    log
    cache 30
    bind 0.0.0.0
}
```

But I'm getting ` Error during parsing: File to import not found: myzone`

What am I doing wrong?  Thanks!

 (The reason I want to do it this way is because terraform's templating is bad and I need a way to conditionally use the snippeted code.  Yes, I can try this with actually using another file, but it would be nice if it worked via snippets)

**Comment by miekg** [comment]
Works for me with coredns-1.0.6 (you eluded the version used).

~~~ corefile
(myzone) {
    proxy myzone.net 1.1.1.1:53 1.1.2.2:53 {
        policy round_robin
        fail_timeout 1s
        max_fails 1
    }
}

. {
    proxy thezone.net 1.1.1.1:53 1.1.2.2:53 {
        policy round_robin
        fail_timeout 1s
        max_fails 1
    }

    import myzone

    errors
    log
    cache 30
    bind 0.0.0.0
}
~~~

running
~~~
% ./coredns -dns.port=1105 -conf=Corefile-test
.:1105 on 0.0.0.0
2018/02/23 11:20:10 [INFO] CoreDNS-1.0.6
2018/02/23 11:20:10 [INFO] linux/amd64, go1.10, 
CoreDNS-1.0.6
linux/amd64, go1.10, 
~~~

**Comment by sean-abbott** [comment]
My bad on the version:

```
$ docker run --rm -it coredns/coredns --version
CoreDNS-1.0.6
linux/amd64, go1.10, 83b5eadb
```

But now it works. I wonder what I was doing wrong? That file was basically a copy paste of my original. 

oh well. I apologize for the time waste.

**Comment by miekg** [comment]
strange, hope there is not a weird whitespace issue that could trigger this..
