### ISSUE TITLE
plugin/forward: queries are not sent to forward instance with longest matching zone

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#1555]
With proxy, we do this:

```
.:10053 {
 log
 proxy foo.com 192.168.1.100
 proxy . /etc/resolv.conf
}
```

As expected, queries for `foo.com` are sent to 192.16.1.100 (which doesn't exist):
```
ANN-M-JBELAMARIC:coredns jbelamaric$ dig -p 10053 @127.0.0.1 www.foo.com

; <<>> DiG 9.9.7-P3 <<>> -p 10053 @127.0.0.1 www.foo.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Now try just changing `proxy` to `forward`:

```
.:10053 {
 log
 forward foo.com 192.168.1.100
 forward . /etc/resolv.conf
}
```

and then

```
ANN-M-JBELAMARIC:coredns jbelamaric$ dig -p 10053 @127.0.0.1 www.foo.com

; <<>> DiG 9.9.7-P3 <<>> -p 10053 @127.0.0.1 www.foo.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23862
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.foo.com.			IN	A

;; ANSWER SECTION:
www.foo.com.		255	IN	CNAME	newdigiadmin-1201528726.us-east-1.elb.amazonaws.com.
newdigiadmin-1201528726.us-east-1.elb.amazonaws.com. 60	IN A 34.205.105.133
newdigiadmin-1201528726.us-east-1.elb.amazonaws.com. 60	IN A 52.73.158.41

;; Query time: 21 msec
;; SERVER: 127.0.0.1#10053(127.0.0.1)
;; WHEN: Thu Feb 22 17:52:16 EST 2018
;; MSG SIZE  rcvd: 134

ANN-M-JBELAMARIC:coredns jbelamaric$
```

Uh oh.

**Comment by miekg** [comment]
your second `forward` line overwrites the first. This WAI.
I'm more amazed that *proxy* actually manages to squeeze out a somewhat functional setup in this case...

I'm pondering making the parser just barf on plugin duplicates for some plugin, unless a plugin specifically announces it can handle this case.

**Comment by johnbelamaric** [comment]
proxy specifically codes for this situation, I believe. And it's very useful. It's how we do stub domains.

**Comment by johnbelamaric** [comment]
At least I think it is. Maybe we do separate server blocks. Nonetheless, I think it's a sensible way for proxy to behave.

**Comment by chrisohaver** [comment]
IMO,  consciously intended or not considered, it's extremely counter intuitive behavior to allow multiple declarations and behave this way.  Should be "fixed" or at least documented.

We do use multiple `proxy` in one bock the k8s readme stub-domain examples. Although, we use separate blocks in the `kubeadm` conversion, but only because it was easier to template that way.

**Comment by johnbelamaric** [comment]
Here is the relevant function in `proxy`. I think this is how `forward` should behave too:

https://github.com/coredns/coredns/blob/master/plugin/proxy/proxy.go#L153

**Comment by fturib** [comment]
It is useful for some plugin, here is a stanza of usage of REWRITE and FALLBACK are built to be used with duplicate directives in the same bloc.

**Comment by miekg** [comment]
This corefile does the same
~~~
foo.com {
  log
  forward . 192.168.1.100
}

. {
  log
  forward . /etc/resolv.conf
}
~~~
so I don't directly see how it the fault of the plugin.

if you want to route on names; we have server for that.

**Comment by johnbelamaric** [comment]
Yeah, you can achieve it that way. It's just not very natural or convenient in my opinion. And if nothing else, it should puke on the second forward statement. If all but one will be ignored, then we should only allow one.

**Comment by miekg** [comment]
yes, this is not intuitive. I mean if *we* even make these mistakes.

I've looked a bit in checking this from the parsing side but looks tricky and fragile. Some kind of helper function "I-can-only-be-called-once" is a better idea (no clue how that would look though)

**Comment by chrisohaver** [comment]
Could loop only once in `NewStaticUpstreams`?

**Comment by chrisohaver** [comment]
> Could loop only once in NewStaticUpstreams?

NM - thats in `proxy` :)

loop once in `parseForward`...

**Comment by miekg** [comment]
yep, @chrisohaver  is spot on: this diff checks for it:

~~~
diff --git a/plugin/forward/setup.go b/plugin/forward/setup.go
index 779d085a..078d1da8 100644
--- a/plugin/forward/setup.go
+++ b/plugin/forward/setup.go
@@ -84,7 +84,14 @@ func parseForward(c *caddy.Controller) (*Forward, error) {
 
        protocols := map[int]int{}
 
+       i := 0
+
        for c.Next() {
+               if i > 0 {
+                       println("looping")
+                       return nil, fmt.Errorf("there can only be one")
+               }
+               i++
                if !c.Args(&f.from) {
                        return f, c.ArgErr()
                }
~~~
making this into some helper function obscures it too much i think. I'll sprinkle it throughout, i.e. dnssec plugin even lists this issue in its Bugs section.
