### ISSUE TITLE
add etcd examples

### ISSUE THREAD

**Issue by f0** [coredns/coredns#156]
Hi,

can u add examples how the etcd structure looks like?

regards f0

**Comment by miekg** [comment]
Read this for the time being: https://github.com/skynetservices/skydns/blob/master/README.md

**Comment by f0** [comment]
@miekg  thx, so a record for a.test.local looks like this, but does not work....

/dns/local/test/a '{"host":1.1.1.1, "priority":20}'

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] add etcd exampe..." ]

> @miekg  thx, so a record for a.test.local looks like this, but does not work....
> 
> /dns/local/test/a '{"host":1.1.1.1, "priority":20}'

No, need to be prefixed with /skydns and no dns so

/skydns/local/test/a 

and then your service, where ip is a string and prio is a int (i think), you'll 
need to quote the string

/Miek

## 

Miek Gieben

**Comment by f0** [comment]
@miekg  ok so the /skydns is not changeable?

**Comment by miekg** [comment]
See https://github.com/miekg/coredns/blob/master/middleware/etcd/README.md
use `path`

**Comment by f0** [comment]
@miekg  also with /skydns/local/test/a '{"host":1.1.1.1}'   it does not work, this is the Corefile

```
.:53 {
    etcd test.local {
        endpoint http://localhost:2379
        errors stdout
        log stdout
     }
}
```

**Comment by miekg** [comment]
see https://github.com/miekg/coredns/issues/156#issuecomment-224353058 above

this is btw a nice feature for the debug queries - returned malformed entries.

**Comment by f0** [comment]
@miekg   sorry if i am dump but it does not work...

```
etcdctl get /skydns/local/test/a
{"host":"1.1.1.1"}
```

```
dig a.test.local @localhost

; <<>> DiG 9.10.2-P4 <<>> a.test.local @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 21689
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;a.test.local.                  IN      A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jun 07 19:39:23 CEST 2016
;; MSG SIZE  rcvd: 41
```

**Comment by f0** [comment]
@miekg ok i am dumb :) now it works, i do not correct restart after switching to /skydns ... thx for your help

**Comment by miekg** [comment]
Cool. Docs can be improved. Feel free to file issue and or a pr.

**Comment by f0** [comment]
@miekg hm does the reverse lookup also works like in skydns?

**Comment by miekg** [comment]
Probably not. Didn't implement that yet, but should be easy to add. Thought
wasn't used much :)

**Comment by f0** [comment]
hm for a propper DNS you need reverse lookups....
