### ISSUE TITLE
CoreDNS 1.1.0 release

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1569]
Release tracking for 1.1.0. We are deprecating two plugins, meaning we should up the major version, hence 1.1.0 (and not 1.0.7).

* Two plugins deprecated: *shutdown* and *startup*

**Comment by miekg** [comment]
Deprecation issue ##1550

**Comment by miekg** [comment]
I would like to see ##1492 fixed though. Might take a close look.

**Comment by miekg** [comment]
@johnbelamaric didn't we also want to change the context.Context thingy in Request (or something, forgot exactly)

**Comment by johnbelamaric** [comment]
Yeah, context should be there first parameter and not buried in a struct. We put it in state to avoid breaking stuff, but really it should move to be the first param in any func that takes it.

**Comment by miekg** [comment]
I'm bumping the metrics thing to 1.1.1 and preparing to do a 1.1.0 early this week.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/releases/tag/v1.1.0
