### ISSUE TITLE
middleware/etcd: implement ReverseRecords (PTR) 

### ISSUE THREAD

**Issue by f0** [coredns/coredns#157]
at the moment reverse lookups are not implemented, a dns Server should support PTRs

**Comment by miekg** [comment]
I'm not convinced and there are some tricky corner cases here.

Can you point out a scenario where this would fail for you?

**Comment by f0** [comment]
There are some tools in the world and they do sanity checks, e.g reverse lookup if the ip and name are consistent (if i remeber correct etcd does this)

**Comment by miekg** [comment]
but coredns uses etcd as it backend (in this case), so that would be a weird cyclic dependency. Granted reverse zones in general should work, see #159 for that.

**Comment by f0** [comment]
thanks
