### ISSUE TITLE
plugin/log: add client's port number in default

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1572]
makes sense to log the client's port number as well. Should be a relatively easy change, but currently
IPv6 addrs aren't logged with brackets, meaning we can't just slam a port number next to it: `::1:80` should be `[::1]:80` this probably needs a few tweaks here and there.

**Comment by fantuz** [comment]
This RFC describes URI and accounts for IPv6: https://tools.ietf.org/html/rfc3986 see chapter 3.2.2
```
[2001:db8:85a3:8d3:1319:8a2e:370:7348]:443
```
As you correcly say, bracketing seems to be the preferred (URI) representation of such IPv6 et port combination.

Also according to newest/different RFC, IPv6 should be enclosed in square brackets https://tools.ietf.org/html/rfc6874 (Representing IPv6 Zone Identifiers in Address Literals and Uniform Resource Identifiers)

HTH
