### ISSUE TITLE
CoreDNS : outside Kubernetes cluster, Unauthorized responses.

### ISSUE THREAD

**Issue by nlamirault** [coredns/coredns#1576]
Hi,
I would like to test a CoreDNS server outside my Kubernetes cluster. I create this configuration file : 

```
.:8153 {
    kubernetes jarvis {
        endpoint https://192.168.1.36:6443
        tls /etc/kubernetes/pki/apiserver.crt /etc/kubernetes/pki/apiserver.key /etc/kubernetes/pki/ca.crt
    }
    proxy . 8.8.8.8:53
    prometheus 0.0.0.0:8253
    health 0.0.0.0:8781
}
```

This is the output logs : 

```
$ coredns --conf /srv/docker/coredns/Corefile  -log
E0301 15:39:32.168235   15143 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:312: Failed to list *v1.Service: Unauthorized
E0301 15:39:32.169942   15143 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:314: Failed to list *v1.Endpoints: Unauthorized
E0301 15:39:32.191193   15143 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:319: Failed to list *v1.Namespace: Unauthorized
E0301 15:39:33.212841   15143 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:319: Failed to list *v1.Namespace: Unauthorized
E0301 15:39:33.227990   15143 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:312: Failed to list *v1.Service: Unauthorized

```

Any idea how to fix that ?
Thanks.

**Comment by johnbelamaric** [comment]
That's the api server's cert and key. Try instead using the ones from your kubectl configuration for that server - that will authenticate as you and assuming you have the permissions to read all namespaces it should work.

**Comment by nlamirault** [comment]
@johnbelamaric is the "view" role on the cluster sufficient?
According to the [RBac documentation](https://kubernetes.io/docs/admin/authorization/rbac/#default-roles-and-role-bindings)

```
Allows read-only access to see most objects in a namespace. It does not allow viewing roles or rolebindings. It does not allow viewing secrets, since those are escalating.
```

**Comment by johnbelamaric** [comment]
It needs to be a ClusterRole and ClusterRoleBinding. Here are the ones we usually use:

https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed

**Comment by johnbelamaric** [comment]
You could also try with the default system:kube-dns cluster role but it doesn't grant all the permissions needed for all the features.

**Comment by nik786** [comment]
@johnbelamaric 

Im using this config file
cat core.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        log stdout
        health
        # Replace cluster.local with your cluster domain
        kubernetes cluster.local
        proxy . /etc/resolv.conf
        cache 30
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: coredns
  template:
    metadata:
      labels:
        k8s-app: coredns
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: coredns
        image: coredns/coredns
        imagePullPolicy: Always
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: coredns
  # Replace with your cluster DNS IP
  clusterIP: 10.254.0.20
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP

Im facing certificate issue...
kubectl logs pod/coredns-6f5cd47744-tfhsj -n kube-system | head -n 10
E0524 11:15:24.765434       1 config.go:326] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
E0524 11:15:24.898197       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:320: Failed to
