### ISSUE TITLE
Mesos plugin

### ISSUE THREAD

**Issue by ror6ax** [coredns/coredns#1590]
Hi guys, great project you have there!

I was wondering if it makes any sense to use CoreDNS as a replacement for MesosDNS due to lack of intergation? Maybe this would be a good idea for one more plugin? 

Thanks!

**Comment by miekg** [comment]
If someone builds it, I'm willing to include it in CoreDNS.

**Comment by johnbelamaric** [comment]
Sure! I spoke with the Mesosphere team a year or so ago about this. They were very open to the idea, but the issue at that time was that Mesos-DNS was deeply embedded in the provisioning of DC/OS itself and so they thought it would be challenging to do.

**Comment by tookko** [comment]
To my understanding Mesos-DNS just polls the Mesos HTTP API and updates its internal state accordingly. While it might be challenging to integrate it with DC/OS deployment, integrating with Apache Mesos should not have similar issues.

**Comment by johnbelamaric** [comment]
Ok, good. As Miek said, we can include it if someone builds it :)
