### ISSUE TITLE
Expanding the Route 53 plugin RR type coverage

### ISSUE THREAD

**Issue by simonclausen** [coredns/coredns#1595]
Hi,

It would be interesting for me to have the route 53 support other RR types than A and AAAA. I'm specifically interested in PTR records and zones.

So I'm trying to understand what, if any, issues there may be in expanding the functionality of the plugin.

Looking at the plugin implementation, it seems it should be possible to expand with functions handling the additional types. But I don't have much experience with neither the Route 53 API, CoreDNS or Go, so that may just be my unawareness getting in the way.

Does anyone have any thoughts? Consider this an invite for discussion :)

**Comment by miekg** [comment]
yes, expanding the coredns should be relatively easy; just expand the `switch state.QType()` and add new types. But you do need to find out of these are supported by the amazon API (SRV records would also be nice)

**Comment by simonclausen** [comment]
Roger, thanks!

I'll trow in a cautious "I hope I will have time to try that out soon'ish".

Here is the documentation available on Route 53 record types for reference: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html

**Comment by yongtang** [comment]
Added #1606 for PTR support.
