### ISSUE TITLE
No way to configure glog

### ISSUE THREAD

**Issue by obeattie** [coredns/coredns#1597]
The `kubernetes` plugin uses the Kubernetes client libraries, which in turn use [`golang/glog`](https://godoc.org/github.com/golang/glog) to log certain events. By default, `glog` outputs to files, and while it registers certain flags to allow customisation of this behaviour, it is not exposed in CoreDNS.

This is problematic for several reasons:

* `glog` does not itself perform any log file management, so without something like `logrotate` running alongside CoreDNS (especially problematic if running CoreDNS containerised) the log files just accumulate.
* It is desirable in some environments to run CoreDNS in a container with a read-only root filesystem for security reasons. Without a way to disable the file-based logging, [this causes CoreDNS to exit](https://github.com/golang/glog/blob/23def4e6c14b4da8ac2ed8007337bc5eb5007998/glog.go#L691) whenever anything is logged via `glog`.

**Comment by miekg** [comment]
We should configure glog to dump to stdout; just like all other logs from coredns

**Comment by johnbelamaric** [comment]
Agreed. We may want to offer a way to tweak the verbosity level too, though.

**Comment by miekg** [comment]
Doesn't seem easily doable (punting to stdout), exposing glog options also
doesn't feel right.

**Comment by miekg** [comment]
Evil thought: can we capture the `glog` namespace and rewrite things to our own liking?
Bit dangerous but glog's api is pretty stable. Seems also a fun thing to test (think it will fail, btw, due to vendoring)

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/1598
contains a potential fix, some casual testing with another plugin and call glog statement myself seems to indicate this does help, but please test in a k8s env.
