### ISSUE TITLE
https

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#16]
There is a https/acme let's encrypt implementation in the code, the only use would prolly be DNS over TLS; this needs to happen (i.e. implemented)

**Comment by jsimonetti** [comment]
Other use case could be to support ACME DNS-01.

**Comment by miekg** [comment]
See https://community.letsencrypt.org/t/dns-challenge-is-in-staging/8322 and https://lincolnloop.com/blog/letsencrypt-dns-challenge/

Is there an official spec for this thing?

**Comment by jsimonetti** [comment]
The only one I can find is a draft, which expired the same time that blogpost was made:
https://tools.ietf.org/html/draft-ietf-acme-acme-01

Edit: Section 7.5 explains the DNS-01 challenge mechanism

**Comment by miekg** [comment]
Closing here as we have full support for DNS over TLS.
