### ISSUE TITLE
Clean up conf directory

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#160]
We added a `conf` directory. Check to see if this a) needs to be extra tests or that we extend this. My gut feeling is that this should be moved to (external) documentation and tests.

**Comment by miekg** [comment]
@mrichmon I'm not a fan of the `conf/` dir, this should end up in some docs somewhere or (for k8s) in the README.md there.

I hold a similar view on the `contrib/` dir - yes this is super handy for testing, starting, but it add clutter  to the directory layout IMHO

**Comment by mrichmon** [comment]
The `conf` directory can go without much loss. As you state, this can be captured in a readme.

I'm not sure how to get away from scripts to start up kubernetes and populate with some expected services to allow integration testing. The logic could be re-coded in go but bash is more likely to be understood by people just looking to use CoreDNS. So I think there are a couple of options:
1. rename/move contrib to something that works better for you.
2. remove contrib from the repo and implicitly decide against inclusion of automated integration tests for k8s.
3. re-code the automated integration tests for k8s into something more acceptable. (Implicitly making testing harder -- the current implementation allows different parts of the k8s setup to be run manually.)

Preferences/thoughts?

**Comment by miekg** [comment]
I've removed the conf/ dir some time ago.
