### ISSUE TITLE
plugin/host: allow CNAMEs?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1601]
If you create a k8s service in a cluster you some name ala `<name>.<namespace>.svc.cluster.local`. If you know want a vanity name for this you need an external nameserver to point this name (or the IP address of the service).

Or you can setup a zone (in another coredns) and CNAME your vanity name to the above name (so you can be IP address agnostic).

Or we can create a new plugin that does this cnaming for you - similar to the look ups the host plugin does.

Or we can extend the host plugin to do this for you.

Or it may be already possible with the template and or rewrite plugins (haven't looked into this)

**Comment by johnbelamaric** [comment]
You can do this with rewrite, see https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/

That should probably be updated with the answer rewrites now too.

Even better than this though would be if we automatically served names based on the same rules as the external DNS project (https://github.com/kubernetes-incubator/external-dns).

**Comment by chrisohaver** [comment]
You can do this with CNAMEs using the `template` plugin.
I use this combo to create a CNAME chain loop with a kubernetes external service in the k8s `upstream` integration tests... see `TestUpstreamLoopBreak` in `coredns/ci/test/upstream_test.go`
