### ISSUE TITLE
plugin/rewrite: log bypass

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1610]
It is possible to use the rewrite feature to modify the domain name, which
then exceeds the maximum (254) length. The DNS query is still forwarded to the defined DNS
server, which will respond with “Format Error”. Those FormErrors are not properly logged.

**Comment by etinquis** [comment]
I think #1972 fixes this.

I tried to [reproduce](https://github.com/etinquis/coredns/commit/2396e5ab5e6db13761edd43f75b15a52b163f14d), but was seeing that the invalid name errors from #1972 were getting logged.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/rewrit..." ]
>I think #1972 fixes this.
>
>I tried to [reproduce](https://github.com/etinquis/coredns/commit/2396e5ab5e6db13761edd43f75b15a52b163f14d), but was seeing that the invalid name errors from #1972 were getting logged.

/close
