### ISSUE TITLE
High CPU load with ETCD backend

### ISSUE THREAD

**Issue by m4r10k** [coredns/coredns#1625]
Hi!

We are using Coredns with Etcd as backend and we had an issue today that the Coredns caused full CPU load on three instances. The three Coredns are installed on three Etcd instances and the Etcd instances are not use by anything else.

After adding some entries to the Etcd the Coredns'es spinned up to 100% CPU load (multicore on-prem server). After deleting the last entries and restarting the Coredns the CPU keeps on 1%.

Unfortunately I cannot see any option to enable some kind of debug output. Is there a kind of a switch to enable debug output? I would like to see what is going on inside the Coredns to triage what is causing the problem.

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] High CPU load wit..." ]
>Hi!
>
>We are using Coredns with Etcd as backend and we had an issue today that the Coredns caused full CPU load on three instances. The three Coredns are installed on three Etcd instances and the Etcd instances are not use by anything else.
>
>After adding some entries to the Etcd the Coredns'es spinned up to 100% CPU load (multicore on-prem server). After deleting the last entries and restarting the Coredns the CPU keeps on 1%.
>
>Unfortunately I cannot see any option to enable some kind of debug output. Is there a kind of a switch to enable debug output? I would like to see what is going on inside the Coredns to triage what is causing the problem.

Inside the etcd there is not that much that you can enable (would be a nice 
feature though - for other plugins as well).

The pprof plugin can be used the gather where coredns is spending it's time 
which might show a hotspot.

**Comment by m4r10k** [comment]
@miekg true, we think Etcd is not the problem, the Coredns uses the CPU but it might be because I am writing the DNS entries to Etcd with a custom Golang program. I will enable the pprof to get the hotspot map of whats going on inside Coredns. It seems like, that some entries in Etcd are maybe "poisoned". Thanks for response, we will dig into it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] High CPU load..." ]
>@miekg true, we think Etcd is not the problem, the Coredns uses the CPU but it might be because I am writing the DNS entries to Etcd with a custom Golang program. I will enable the pprof to get the hotspot map of whats going on inside Coredns. It seems like, that some entries in Etcd are maybe "poisoned". Thanks for response, we will dig into it.

cool, let us know how it goes.

I'll follow up with the debug thought - probably means some more complex logic 
around logging (which current just uses the `log` package)

**Comment by m4r10k** [comment]
Yeah, some kind of (real) debug logs would be nice to have. Currently we have only a low count of DNS resolves, therefore debug logging would be an option. If massive resolves are coming in, debug log would not be convenient but for low traffic it might be an option. Not everyone saws pprof in real live for sure :smirk:

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] High CPU load..." ]
>Yeah, some kind of (real) debug logs would be nice to have. Currently we have only a low count of DNS resolves, therefore debug logging would be an option. If massive resolves are coming in, debug log would not be convenient but for low traffic it might be an option. Not everyone saws pprof in real live for sure :smirk:

yes, filled #1626 for tracking

--
Miek Gieben

**Comment by m4r10k** [comment]
@miekg here we go. Attached the CPU profile. The `github.com/miekg/dns.compressionLenSlice` uses lots of cpu and this it how it feels like on the server. No memory usage but the cpu is going on top. As I told before, maybe I mess up something by writing to Etcd with my tool but the entries I write to Etcd are resolvable via Coredns, so they work as they should but something goes wrong internally. Tell me if you need more information on it. Tested with `v1.0.6` and `v1.1.0`.

```
 top
52.11s of 75.72s total (68.82%)
Dropped 172 nodes (cum <= 0.38s)
Showing top 10 nodes out of 77 (cum >= 3.36s)
      flat  flat%   sum%        cum   cum%
    10.86s 14.34% 14.34%     17.16s 22.66%  runtime.mapaccess2_faststr
     9.75s 12.88% 27.22%      9.75s 12.88%  github.com/miekg/dns.NextLabel
     5.56s  7.34% 34.56%     53.31s 70.40%  github.com/miekg/dns.compressionLenHelper
     5.07s  6.70% 41.26%     17.88s 23.61%  runtime.mallocgc
     4.78s  6.31% 47.57%     64.61s 85.33%  github.com/miekg/dns.compressionLenSlice
     4.63s  6.11% 53.68%      4.63s  6.11%  runtime.memeqbody
     4.03s  5.32% 59.01%     32.98s 43.56%  github.com/miekg/dns.Split
     3.03s  4.00% 63.01%      5.10s  6.74%  runtime.scanobject
     2.35s  3.10% 66.11%      2.35s  3.10%  runtime.nextFreeFast (inline)
     2.05s  2.71% 68.82%      3.36s  4.44%  runtime.gcmarknewobject
```

[pprof.coredns.samples.cpu.001.pb.gz](https://github.com/coredns/coredns/files/1836753/pprof.coredns.samples.cpu.001.pb.gz)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] High CPU load..." ]
>@miekg here we go. Attached the CPU profile. The `github.com/miekg/dns.compressionLenSlice` uses lots of cpu and this it how it feels like on the server. No memory usage but the cpu is going on top. As I told before, maybe I mess up something by writing to Etcd with my tool but the entries I write to Etcd are resolvable via Coredns, so they work as they should but something goes wrong internally. Tell me if you need more information on it. Tested with `v1.0.6` and `v1.1.0`.
>
>```
> top
>52.11s of 75.72s total (68.82%)
>Dropped 172 nodes (cum <= 0.38s)
>Showing top 10 nodes out of 77 (cum >= 3.36s)
>      flat  flat%   sum%        cum   cum%
>    10.86s 14.34% 14.34%     17.16s 22.66%  runtime.mapaccess2_faststr
>     9.75s 12.88% 27.22%      9.75s 12.88%  github.com/miekg/dns.NextLabel
>     5.56s  7.34% 34.56%     53.31s 70.40%  github.com/miekg/dns.compressionLenHelper
>     5.07s  6.70% 41.26%     17.88s 23.61%  runtime.mallocgc
>     4.78s  6.31% 47.57%     64.61s 85.33%  github.com/miekg/dns.compressionLenSlice
>     4.63s  6.11% 53.68%      4.63s  6.11%  runtime.memeqbody
>     4.03s  5.32% 59.01%     32.98s 43.56%  github.com/miekg/dns.Split
>     3.03s  4.00% 63.01%      5.10s  6.74%  runtime.scanobject
>     2.35s  3.10% 66.11%      2.35s  3.10%  runtime.nextFreeFast (inline)
>     2.05s  2.71% 68.82%      3.36s  4.44%  runtime.gcmarknewobject
>```
>
>[pprof.coredns.samples.cpu.001.pb.gz](https://github.com/coredns/coredns/files/1836753/pprof.coredns.samples.cpu.001.pb.gz)

Calculating compression pointers it kind of expensive (in this library); but is 
done to make the best out of 512 bytes buffers clients usually have.

Seems odd to spend this much time in it; do you any idea how large the returned 
answer is? I have to double check myself why dns.Split shows up here, that looks 
out of place.

**Comment by m4r10k** [comment]
Hmm, I don't have the bytes on the network, but what I can give you is:
#### Coredns query log
```
10.x.x.x - [22/Mar/2018:09:49:09 +0100] 31899 "A IN x.x.x. udp 55 false 4096" NOERROR qr,aa,rd,ra 71 10.948041ms
10.x.x.x - [22/Mar/2018:09:49:14 +0100] 6664 "A IN x.x.x.. udp 55 false 4096" NOERROR qr,aa,rd,ra 71 13.960164ms
10.x.x.x - [22/Mar/2018:09:49:22 +0100] 3114 "A IN x.x.x.. udp 51 false 4096" NOERROR qr,aa,rd,ra 67 21.980204ms
```
#### Dig
```
[09:48 mario@xxx~/coredns]$ dig +nocmd +noall +answer  @10.y.y.y x.x.x
x.x.x. 3600	IN	A	10.x.x.x
[09:49 mario@xxx ~/coredns]$ dig +nocmd +noall +answer  @10.y.y.y x.x.x
x.x.x. 3600	IN	A	10.x.x.x
[09:49 mario@xxx ~/coredns]$ dig +nocmd +noall +answer  @10.y.y.y x.x.x
x.x.x. 3600	IN	A	10.x.x.x
[09:49 mario@xxx ~/coredns]$ dig +nocmd +noall +answer  @10.y.y.y x.x.x
x.x.x.	3600	IN	A	10.x.x.x
```

**Comment by miekg** [comment]
Those response sizes are all under 100 bytes, i.e. 1 RR... that should not
cause this. How much qps is this server receiving?

**Comment by m4r10k** [comment]
Only `298` during this test run. Somehow I manage it to kill Coredns with my little insert tool by triggering a race condition. :see_no_evil: I wrote you an additional email.
