### ISSUE TITLE
nslookup for domain with 25 A records timing out with cache enabled

### ISSUE THREAD

**Issue by jpiper** [coredns/coredns#1627]
I've been having issues with CoreDNS 1.1.0 timing out on specific nslookup (and golang) requests in my kubernetes cluster. For some reason this doesn't happen on `dig`.

My config looks like this:

```
.:53 {
    errors
    health
    log
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      upstream
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
}
```

and the upstream `/etc/resolv.conf` looks like
```
options single-request

search d1.corporation.com corp.corporation.com corporation.com

nameserver X.X.X.X
nameserver X.X.X.X
```
and I'm seeing

```
# nslookup domain1.corp.com
;; connection timed out; no servers could be reached
```

However, I was getting `nslookup` requests hang/timeout, even though on the host everything is fine. I managed to work out that the `cache 30` is causing issues.

The specific DNS result for the domain I'm looking up is rather long, I'm not sure if this causing the issue with the cache. I've had to obfuscate the domains for privacy reasons.

```
domain1.corp.com. 86400 IN	CNAME	domain2.corp.com.
domain2.corp.com. 8 IN CNAME domain3.corp.com.
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
domain3.corp.com. 7 IN A X.X.X.X
```

**Comment by jpiper** [comment]
I wonder if this has something to do with it, from the end of my dig request:

```
;; Query time: 0 msec
;; SERVER: X.X.X.X#53(X.X.X.X)
;; WHEN: Thu Mar 22 03:39:11 GMT 2018
;; MSG SIZE  rcvd: 939
```

Which seems to be larger than the 512 byte limit as specified in https://tools.ietf.org/html/rfc1035

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] nslookup for ..." ]
>I wonder if this has something to do with it, from the end of my dig request:
>
>```
>;; Query time: 0 msec
>;; SERVER: X.X.X.X#53(X.X.X.X)
>;; WHEN: Thu Mar 22 03:39:11 GMT 2018
>;; MSG SIZE  rcvd: 939
>```
>
>Which seems to be larger than the 512 byte limit as specified in https://tools.ietf.org/html/rfc1035

dig handles this fine, nslookup is not setting anything and expecting a smaller 
packet, which it should get (the code checks the size of the request buffer).

What version of CoreDNS is this and can you maybe capture a tcpdump?

**Comment by jpiper** [comment]
This is version 1.1.0 (official docker image) unfortunately due to the sensitive network environment I’m not able to run a tcpdump :(

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] nslookup for ..." ]
>This is version 1.1.0 (official docker image) unfortunately due to the sensitive network environment I’m not able to run a tcpdump :(

:-(

Can you find out of the timeout happens in the path: coredns <-> upsteam or
nslookup <-> coredns ?

/Miek

--
Miek Gieben

**Comment by jpiper** [comment]
I'll try and do my best :)

I find it odd that disabling the cache makes everything OK. at the moment I've just got CoreDNS deployed with no cache

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] nslookup for ..." ]
>I'll try and do my best :)
>
>I find it odd that disabling the cache makes everything OK. at the moment I've just got CoreDNS deployed with no cache

OK, that's a good data point.
Feel free to send me extra info (if you can) privately.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I think 1.1.1 should fix this

**Comment by jpiper** [comment]
I’ll give 1.1.1 a spin and let you know - what do you think is the root cause?

**Comment by jpiper** [comment]
Yep, 1.1.1 looks like it fixes this!
