### ISSUE TITLE
plugin/cache add ECS support

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [coredns/coredns#1628]
ATM plugin/cache doesn't use ECS for cache entry key generation - only name and query type.
Example: we have two clients from Tokio and LA.
Tokio client set ECS and get google.com IP for Tokio region,
after that LA client that also set ECS will get google.com IP for Tokio region from cache untill TTL expired.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/cache add ..." ]
>ATM plugin/cache doesn't use ECS for cache entry key generation - only name and query type.
>Example: we have two clients from Tokio and LA.
>Tokio client set ECS and get google.com IP for Tokio region,
>after that LA client that aslo set ECS will get google.com IP for Tokio region from cache untill TTL expired.

dup of #1248 (nice for autopath as well)

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Note that this leads to (bascially) 0% cache hits because so few clients can use the specific IP cache and care needs to be taken to make this memory efficient.

**Comment by UladzimirTrehubenka** [comment]
ECS is a different thing.
If we add subnet to cache entry key we get cached answers for whole subnet.
BTW Unbound has this feature.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/cache ..." ]
>ECS is a different thing.
>If we add subnet to cache entry key we get cached answers for whole subnet.
>BTW Unbound has this feature.

Indeed, but the cache goes from qname/qtype/qclass to 
qname/qtype/qclass/cidr-range as the key.

I'm all for having this in the cache plugin, but doing a naive implementation 
will blow the memory use.

**Comment by efansoftware** [comment]
Could this be reconsidered? More demands for ECS nowadays. 
And given that #1248 was closed but not implemented.
