### ISSUE TITLE
Wildcard

### ISSUE THREAD

**Issue by bogaertg** [coredns/coredns#1633]
Does coredns support wildcard entry ?

I have a coredns et etcd docker in rancher.

i try to add wildcard for domain *.example.com

i use rest api of etcd.
this is my database 👍 
```json
{
   "action":"get",
   "node":{
      "key":"/skydns/com/example",
      "dir":true,
      "nodes":[
         {
            "key":"/skydns/com/example/toto",
            "value":"{\"host\":\"35.204.229.143\",\"port\":80}",
            "modifiedIndex":4,
            "createdIndex":4
         },
         {
            "key":"/skydns/com/example/tata",
            "value":"{\"host\":\"35.204.229.143\",\"port\":80}",
            "modifiedIndex":5,
            "createdIndex":5
         },
         {
            "key":"/skydns/com/example/*",
            "value":"{\"host\":\"35.204.229.143\",\"port\":80}",
            "modifiedIndex":6,
            "createdIndex":6
         },
         {
            "key":"/skydns/com/example/.*",
            "value":"{\"host\":\"35.204.229.143\",\"port\":80}",
            "modifiedIndex":9,
            "createdIndex":9
         }
      ],
      "modifiedIndex":4,
      "createdIndex":4
   }
}
``` 

Can you give me the syntax for a wildcard entry ?

Regards

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Wildcard (#1633)..." ]
>Does coredns support wildcard entry ?
>
>I have a coredns et etcd docker in rancher.
>
>i try to add wildcard for domain *.example.com

You can't add a wildcard like this in the etcd backend. Just having something
under example.com in etcd should make it returned on a query for
`example.com`.

**Comment by bogaertg** [comment]
I don't understant. 

I want to use following domain names : 

- gitlab.example.com -> IP
- sonarqube.example.com -> IP
- nexus.example.com -> IP

This domain name is redirected on the same IP.

I want to put only one record in my DNS ? Can i have only one record for all sub-domain of example.com or i have to set an record for all domain name ?

Regards

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Wildcard (#16..." ]
>I don't understant.
>
>I want to use following domain name :
>
>gitlab.example.com -> IP
>sonarqube.example.com -> IP
>nexus.example.com -> IP
>
>This domain name is redirected on the same IP.
>
>I want to put only one record in my DNS ? Can i have only one record for all sub-domain of example.com or i have to set an record for all domain name ?

With the *etcd* plugin this is not possible (we don't have a generic DB backend 
interface yet). You probably just want to use the *host* or *file* middleware?

/Miek

--
Miek Gieben

**Comment by bogaertg** [comment]
So, etcd backend don't support DNS wildcard.
