### ISSUE TITLE
Plugin/rewrite: Extend rewrite plugin to support external plugins

### ISSUE THREAD

**Issue by rajansandeep** [coredns/coredns#1638]
Implement a hook which allows the rewrite plugin to support external plugins that will be an extension to the rewrite plugin.

Eg. The rewrite plugin would support an external plugin which extends the edns0 variable rule which allows returning the client's mac address.

This would make extending the rewrite plugin easily and avoid clutter

**Comment by budaki** [comment]
Pls help me open my plugins

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Plugin/rewrite: E..." ]
>Implement a hook which allows the rewrite plugin to support external plugins that will be an extension to the rewrite plugin.
>
>Eg. The rewrite plugin would support an external plugin which extends the edns0 variable rule which allows returning the client's mac address.
>
>This would make extending the rewrite plugin easily and avoid clutter

Can't this be done, by just chaining plugins?

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
> Can't this be done, by just chaining plugins?

@miekg, Do you mean by creating a new plugin that wraps the existing rewrite code (which would need to be exposed/refactored to accommodate), and adds the new feature? For example, as it is done similarly in `auto` (wrapping `file`) and `kubernetai` (wrapping `kubernetes`) - a new `rewriteclientmac` plugin wrapping `rewrite`?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Plugin/rewrit..." ]
>> Can't this be done, by just chaining plugins?
>
>@miekg, Do you mean by creating a new plugin that wraps the existing rewrite code (which would need to be exposed/refactored to accommodate), and adds the new feature? For example, as it is done similarly in `auto` (wrapping `file`) and `kubernetai` (wrapping `kubernetes`) - a new `rewriteclientmac` plugin wrapping `rewrite`?

I was thinking using the normal wrapping of a responseWriter, but that doesn't 
work, because you can then only influence the return packet. So disregard that 
:-)o

I have no good ideas for this yet, but want to warn to not proliferate too many 
plugin types, we already have quite a few.


/Miek

--
Miek Gieben

**Comment by rajansandeep** [comment]
I was thinking of three ways where I can implement eg. getting the mac address of the client.

- Extend the existing rewrite plugin by adding an edns0 variable called {client_mac}
- Create an external plugin which wraps the rewrite plugin (like how `kubernetai` is done)
- Add a hook to the rewrite plugin, which enables other external plugins to define new variables that can be used in the existing rewrite plugin.

**Comment by fturib** [comment]
## Extend the existing rewrite plugin

do we want to add the libraries to collect MAC through "arp" command into the internal REWRITE plugin ?

=> if we are OK, then **I think that is the most simple solution** for this particular use case of {client_mac}.

```
.53 {
   rewrite edns0 local set 0xffdd {mac_client}
   forward . 8.8.8.8
}
```

## Extension of the "variable interpreter" with other plugins

If we are not OK, then we need to find a way to extend the REWRITE operations using other plugins. I guess that the rewrite operation is so popular that we should think of a way to extend it easily with external plugins : each user/installation could add its own "variable" and populate the value for each DNS request with a customized data, proper to the customer.

Today it is {client_mac} for the MAC Address of the client issuing the query, tomorrow could be some CustomerID or BusinessInfo that depends of any local DB.

### I guess we have 2 possibilities:

#### other flavors of REWRITE (wrappers around current REWRITE plugin)
modify REWRITE plugin, transform its logic of rewriting (at least for "edns0 local") into library, maybe adding convenient functions for parsing the stanza and call rewrite, allowing other plugins to share reuse the code, with some customization of functions. It will work a little like FALLBACK is reusing the syntax and the main library of PROXY (for upstream queries)

```
.53 {
   rewrite-mac edns0 local set 0xffdd {mac_client}
   rewrite-customer edns0 local set 0xffcc {customer_id} {
       db:xxxx.sql
   }
   forward . 8.8.8.8
}
```

#### Plugins for the "Variable interpretor" of REWRITE
modify REWRITE plugin, allowing the "Variable interpretor" part to host external interpretors. In that case other plugins could subscribe to be "Variable interpretor" for one variable. This would work a little like METRICS (each plugin that want to provide metrics information is subscribing to METRICS), or like HEAHLT plugin (each plugin that want to contribute implement a dedicated interface "healther").

```
.53 {
   rewrite edns0 local set 0xffdd {mac_client}
   rewrite edns0 local set 0xffcc {customer_id}
   # populate the {mac-client} with the MAC Address collected on the arp tables
   mac
   # populate the {customer_id} with an information provided from DB - most likely based on some info collected in the DNS query.
   customer db:xxxx.sql
   forward . 8.8.8.8
}
```

### Personally, I would vote for the "plugins for "Variable Interpreter" solution  (the last one described above), which match the 3rd one proposed by @rajansandeep in preceding comment.

1. For any plugin that could provide an "interpretation" there will be ONLY that piece to provide.  This plugin can focus on its purpose, maybe have dedicated option to provide optional infos, there will be no hassle about REWRITE activity : its syntax or the need to handle ServeDNS (in the right order of plugin).
1. Like for HEALTH or METRICS, a plugin can contribute to a global plugin and have a main activity on the DNS query.
1. Plugins are more easy to share between CoreDNS users, than several versions of the REWITE plugin.

**Comment by johnbelamaric** [comment]
I like the "plugins for "Variable Interpreter"" as well. In fact I think this is more general purpose than just for rewrite. I would propose a MetaData function that any plugin could implement that would accept the same parameters as ServeDNS (or at least, Context and the request), and return a context with a meta-data map populated. Something like:

```
type MetaDataer interface {
		MetaData(context.Context, dns.ResponseWriter, *dns.Msg) (context.Context, error)
```

Or alternately it could return a `map[string][string]`. We could then have a `metadata` plugin that will go through and call this on all plugins in the chain, and collect up all that metadata in the context before passing it on down the chain.

This could allow all sorts of interesting use cases. For example, the Kubernetes plugin could implement a MetaData function that populates the metadata based on the client IP - things like the client pod name and namespace. Those could then be used in `rewrite` or in `policy` or even in `log` with the same variable syntax used for `rewrite`.

**Comment by johnbelamaric** [comment]
If it returns `Context` it should probably be called `WithMetaData`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Plugin/rewrit..." ]
>I like the "plugins for "Variable Interpreter"" as well. In fact I think this is more general purpose than just for rewrite. I would propose a MetaData function that any plugin could implement that would accept the same parameters as ServeDNS (or at least, Context and the request), and return a context with a meta-data map populated. Something like:
>
>```
>type MetaDataer interface {
>		MetaData(context.Context, dns.ResponseWriter, *dns.Msg) (context.Context, error)
>```
>
>Or alternately it could return a `map[string][string]`. We could then have a `metadata` plugin that will go through and call this on all plugins in the chain, and collect up all that metadata in the context before passing it on down the chain.
>
>This could allow all sorts of interesting use cases. For example, the Kubernetes plugin could implement a MetaData function that populates the metadata based on the client IP - things like the client pod name and namespace. Those could then be used in `rewrite` or in `policy` or even in `log` with the same variable syntax used for `rewrite`.

Agreed, sounds like a good thing to have. Pretty clean as well.

**Comment by eugen-kleiner-mesh** [comment]
I am working on it.

**Comment by eugen-kleiner-mesh** [comment]
I have a proposal for improvement (initialy the idea goes from @fturib).
Calculating all metadata for every query can be time consuming, but all metadata is not always needed. So I propose we calculate the variables only on demand.
Metadataer interface may look like:
```
type Metadataer interface {
	//List of variables which are provided by current metadataer. Must remain constant.
	MetadataVarNames() []string
	// Returns metadata variable by varName.
	Metadata(varName string, context.Context, dns.ResponseWriter, *dns.Msg) interface{}
}
```
In this case metadata will scan metadaters for `MetadataVarNames` and can know which metadataer provides which variables and store key/valGetter only on startup instead of getting key/value for every query. key/value are calculated only on demand and stored as cache.
If someone will need "all metadata variables", then it can be retrieved too because metadata has all available variables list.

If we introduce the improvement above then calculating metadata will have no impact on performance until some of plugins need it. So the metadata can be "always enabled" (means, make it as pkg or utility instead of plugin). Additional plugin which does nothing seems to be an overcomplication for end user. Also, because you wanted to support the rewrite "built-ins" with no metadata enabled anyway it makes sense to not to introduct an additional plugin.

@johnbelamaric, @miekg what do you think?

**Comment by johnbelamaric** [comment]
The only problem is that for things like the `policy` plugin, we may be pushing all the metadata out to an external service. So, there is no way to do the "on-demand" function in that case. Well, I guess that plugin could demand all of them - or even the subset it needs. So, yeah, this makes sense to me. Should be more efficient and less configuration. What's not to like?
