### ISSUE TITLE
etcd tests failing to build

### ISSUE THREAD

**Issue by splack** [coredns/coredns#164]
I'm not sure if this is related to #100?

$ go test github.com/miekg/coredns/middleware/etcd

# github.com/miekg/coredns/middleware/etcd
middleware/etcd/debug_test.go:31: undefined: set
middleware/etcd/debug_test.go:31: undefined: etc
middleware/etcd/debug_test.go:32: too many arguments to delete
middleware/etcd/debug_test.go:34: undefined: etc in etc.Debug
middleware/etcd/debug_test.go:34: cannot assign to etc.Debug
middleware/etcd/debug_test.go:35: undefined: etc in etc.Debug
middleware/etcd/debug_test.go:35: cannot assign to etc.Debug
middleware/etcd/debug_test.go:40: undefined: etc in etc.ServeDNS
middleware/etcd/debug_test.go:40: undefined: ctx
middleware/etcd/debug_test.go:69: undefined: set
middleware/etcd/debug_test.go:69: too many errors
FAIL    github.com/miekg/coredns/middleware/etcd [build failed]

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] etcd tests failing ..." ]

> I'm not sure if this is related to #100?

No, needs a build +etcd which I forgot a add there.

> $ go test github.com/miekg/coredns/middleware/etcd

works now, but does not test anything, you'll need:

$ go test -tags=etcd github.com/miekg/coredns/middleware/etcd

(and a running etcd)

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
Closed via 255aa2e5d5314cbc65b0f0f7c6c068acc134e53b
