### ISSUE TITLE
Route53 cname (and maybe srv) support

### ISSUE THREAD

**Issue by sean-abbott** [coredns/coredns#1640]
So, spent some time poking around today to see what it would take to add cname resolution to the route 53 plugin.

The (very much not pull request or even fully working) result is here: https://github.com/sean-abbott/coredns/blob/route53_cname_records/plugin/route53/route53.go

So. It does appear that we can leverage upstream.  But. Right now, it appears that the route53 plugin makes an assumption about the time of query that is being made.

Right now, my thought is basically, check the response type from AWS for the switch instead of state.QType (even with a default QType of A, there still appear to be an accurate route53 response with a RecordSet[]['Type'] set to the actual variety of record).

If the zone matches the setup for the plugin recursively handle the request within the plugin. Otherwise, for a cname, upstream the response and aggregate them.

It's possible this could interact poorly with being able to re-write certain requests, to it might be better to just upstream every recursive call.

So is this worth pursuing and would you be amenable to a PR if I get it working? Is there an approach you would suggest? Are there any concerns you have?

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Route53 cname (an..." ]
>So, spent some time poking around today to see what it would take to add cname resolution to the route 53 plugin.
>
>The (very much not pull request or even fully working) result is here: https://github.com/sean-abbott/coredns/blob/route53_cname_records/plugin/route53/route53.go

Just send a PR with `WIP:` prefixed, will make it easier to see what changes you 
have made.

>So. It does appear that we can leverage upstream.  But. Right now, it appears that the route53 plugin makes an assumption about the time of query that is being made.
>
>Right now, my thought is basically, check the response type from AWS for the switch instead of state.QType (even with a default QType of A, there still appear to be an accurate route53 response with a RecordSet[]['Type'] set to the actual variety of record).
>
>If the zone matches the setup for the plugin recursively handle the request within the plugin. Otherwise, for a cname, upstream the response and aggregate them.
>
>It's possible this could interact poorly with being able to re-write certain requests, to it might be better to just upstream every recursive call.

Rewrite, as in the rewrite plugin? Generally you should be able to just focus on 
you plugin and not the interaction with other ones.

>So is this worth pursuing and would you be amenable to a PR if I get it working? Is there an approach you would suggest? Are there any concerns you have?

I don't know a whole lot about the aws route53's protocol, but adding more 
qtypes seems worth while.

/Miek

--
Miek Gieben

**Comment by sean-abbott** [comment]
Sorry that took so long. There's the basics. Let me know if I should move forward with this.?

**Comment by sean-abbott** [comment]
I wasn't planning on directly using re-write, I was worried that something might not work if I find a zone that's not in AWS and send it back to the top of the plugin chain. But that's probably not an issue.

**Comment by sean-abbott** [comment]
Actually, I've spent all afternoon looking for what i think will be answered by #1645, so may wait for that.

**Comment by miekg** [comment]
think recent improvements in the route53 plugin made this obsolete
