### ISSUE TITLE
plugin/forward: request to improve tls option

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#1641]
Currently tls option of forward plugin accepts exactly three parameters: CERT KEY CA

Since this option is related to client side of tls connection, it would be useful to allow skipping client certificate in case if client authentication by server is not required. This is the similar approach which is used in proxy plugin, protocol grpc.

So, tls will accept from 0 to 3 parameters, as described at https://github.com/coredns/coredns/blob/master/plugin/proxy/README.md , i.e.

- None - No client authentication is used, and the system CAs are used to verify the server certificate.
- CACERT - No client authentication is used, and the file CACERT is used to verify the server certificate.
- CERT KEY - Client authentication is used with the specified cert/key pair. The server certificate is verified with the system CAs.
- CERT KEY CACERT - Client authentication is used with the specified cert/key pair. The server certificate is verified using the CACERT file.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/forward: r..." ]
>Currently tls option of forward plugin accepts exactly three parameters: CERT KEY CA
>
>Since this option is related to client side of tls connection, it would be useful to allow skipping client certificate in case if client authentication by server is not required. This is the similar approach which is used in proxy plugin, protocol grpc.
>
>So, tls will accept from 0 to 3 parameters, as described at https://github.com/coredns/coredns/blob/master/plugin/proxy/README.md , i.e.
>
>- None - No client authentication is used, and the system CAs are used to verify the server certificate.
>- CACERT - No client authentication is used, and the file CACERT is used to verify the server certificate.
>- CERT KEY - Client authentication is used with the specified cert/key pair. The server certificate is verified with the system CAs.
>- CERT KEY CACERT - Client authentication is used with the specified cert/key pair. The server certificate is verified using the CACERT file.

Yep this should match up.

**Comment by miekg** [comment]
Fixed via #1643

**Comment by spijet** [comment]
Is it possible to use this approach in `kubernetes` plugin too? So CoreDNS could use an external CA file to verify the API server's certificate and use a service account for everything else.
