### ISSUE TITLE
upstream "self" default?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1645]
Should we make upstream to ourselves the default and drop any other uses of upstream?
We get caching, metrics and all other plugin goodies for free that way.

**Comment by chrisohaver** [comment]
Yes to making it the default (with a way to disable?). 
Dropping `upstream` would reduce complexity in the theoretical `loop` plugin (less upstreams to monitor).  It would also clean a bunch of code out of the few plugins that implement it. But it would be backward incompatible change.  We may want to continue to allow blank `upstream`, even though it is redundant with the default, to avoid backward incompatibility in the default kubernetes deployment of coredns corefile.  Or perhaps this is the time to remove it entirely (_before_ CoreDNS goes GA in K8s).

**Comment by chrisohaver** [comment]
There is an alternate loop safe way we can implement `CNAME` look ups without looping to self.
It could be done with an early-in-the-chain plugin, using a non-writer, sends requests down the chain, but then looks at the result for before writing to the client.  For each unresolved `CNAME` it sees (`CNAME` without `A` Records), it creates an `A` record request, and sends that down the chain, adding the result (if any) to the results.  Continuing until it has tried looking up each unique `CNAME` in the result.

This method didn't occur to me until after I modified the existing `upstream` to self.

It's backward incompatible.  Don't know if it's worth re-implemeting this now.  But it does fit the "do it as a plugin if you can" axiom.  And if we are removing `upstream` anyways ...

**Comment by miekg** [comment]
> would also clean a bunch of code out of the few plugins that implement it. But it would be backward incompatible change. We may want to continue to allow blank upstream

Thanks @chrisohaver for the feedback.

Having a way to disable it is indeed needed, but making it the default and removing the directive entirely looks like a nice cleanup. Does depend on a (good) loop detection.

**Comment by chrisohaver** [comment]
A benefit of resolving CNAMEs via a separate plugin is that it would automatically resolve CNAMEs added to the response by other plugins... no need to integrate CNAME resolution into each plugin.

**Comment by miekg** [comment]
With *loop* being a new plugin all pieces are there that allows us to do this. I would like to drop the keyword entirely, but I'm not sure that's possibly, specifically where you want to resolve these names but don't want to be a (open) forwarder. 

Having ACL like syntax for forward would allow this, i.e. `allow ip-range` or something, so only coredns itself can forward queries.

**Comment by chrisohaver** [comment]
Interesting.  Well, for now we can make it the default behavior, but still allow someone to specify `upstream <dest>`... which would then resolve directly without need for an open forwarder.

The `policy` plugin (under development) will enable the ACL behavior you describe.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] upstream "sel..." ]
>Interesting.  Well, for now we can make it the default behavior, but still allow someone to specify `upstream <dest>`... which would then resolve directly without need for an open forwarder.

true, and that seems to be an easy (backwards comp.) way to solve this.
>
>The `policy` plugin (under development) will enable the ACL behavior you describe.

ack. But I would like some syntax (modelled after pf?) to allow ACLs directly in 
the Corefile (or some dyn. backend - but that may be wishful thinking)

/Miek

--
Miek Gieben

**Comment by fturib** [comment]
I expect to setup a README in the coredns/plugin to propose a syntax for Corefile.
I hope will be there by tomorrow cob.

**Comment by chrisohaver** [comment]
> ack. But I would like some syntax (modelled after pf?) to allow ACLs directly in
the Corefile (or some dyn. backend - but that may be wishful thinking)

The forthcoming policy plugin design allow ACLs to be defined directly in the Corefile, based on metadata, with no external process required.

**Comment by miekg** [comment]
this has been implemented
