### ISSUE TITLE
Add support for CloudFlare's new 1.1.1.1 DNS-over-HTTPS service

### ISSUE THREAD

**Issue by skpy** [coredns/coredns#1650]
CloudFlare [just announced](https://blog.cloudflare.com/announcing-1111/) a new DNS resolver at [1.1.1.1](https://1.1.1.1/), and supports [DNS-over-HTTPS](https://developers.cloudflare.com/1.1.1.1/dns-over-https/).  It would be great to expand the proxy service in CoreDNS to support this, in addition to Google's DNS-over-HTTPS service.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/1619

TLS is already supported with the forward plugin:
~~~
    forward . tls://1.1.1.1 {
        tls_servername tls.cloudflare-dns.com
    }
~~~

**Comment by miekg** [comment]
DoH is still a draft btw

**Comment by skpy** [comment]
> TLS is already supported with the forward plugin

Yup, and I'm looking forward to using that!  DOH is interesting, and since now at least two different services publicly offer it (Google and CloudFlare), even if in different implementations, it seems useful to me to diversify the ways in which one makes DNS lookups.

The linked PR is exciting.  Thanks for all your work on CoreDNS!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add support f..." ]
>> TLS is already supported with the forward plugin
>
>Yup, and I'm looking forward to using that!  DOH is interesting, and since now at least two different services publicly offer it (Google and CloudFlare), even if in different implementations, it seems useful to me to diversify the ways in which one makes DNS lookups.
>
>The linked PR is exciting.  Thanks for all your work on CoreDNS!

np :-)

Client/proxy support will probably depend on some work happening in miekg/dns
https://github.com/miekg/dns/issues/652

With the ideas there we can also fold gRPC in the forward plugin.

**Comment by tmthrgd** [comment]
@skpy You can find my really rough DoH work at https://github.com/miekg/dns/pull/649 and https://github.com/miekg/dns/pull/651. Neither are likely fit to merge, but still might prove interesting.

**Comment by kingforaday** [comment]
If you have trouble testing with the forwarders, tls or otherwise, to 1.1.1.1 on some networks, just be aware there are routing [issues ](https://blog.cloudflare.com/fixing-reachability-to-1-1-1-1-globally/)due the 1.1.1.1 being inactive for so long people re-purposed the use and it is causing significant issues for Cloudflare globally.

**Comment by cbuijs** [comment]
Instead of 1.1.1.1 use 1.0.0.1 as alternative (or both).

1.1.1.1 was used for a longtime as portal address (mostly Cisco solutions), in Hotels, airports, etc and a lot in test/lab environments.

**Comment by ciokan** [comment]
Is this feature planned in any way?

**Comment by stp-ip** [comment]
It's already available. Take a look at the forward plugin. It can upstream via DNS, DoH, DoT and DoG.

**Comment by ciokan** [comment]
> It's already available. Take a look at the forward plugin. It can upstream via DNS, DoH, DoT and DoG.

I found everything above except for DoH.. https://github.com/coredns/coredns/tree/master/plugin/forward

**Comment by stp-ip** [comment]
Sorry my bad. DoH as a server component was added, but we don't have a client implementation yet, which would be added to forward. The tracking issues was https://github.com/coredns/coredns/issues/1874.

What's the reason you want to use DoH over DoT out of interest?

**Comment by ciokan** [comment]
I want to provide dns for a vpn server and see how it behaves behind the great wall. Curiosity and experimentation mainly, nothing specific

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add support f..." ]
>I want to provide dns for a vpn server and see how it behaves behind the great wall. Curiosity and experimentation mainly, nothing specific

This should not be too hard to add, so if you want to take a whack at it.

/plugin: forward

**Comment by RehanSaeed** [comment]
Am I correct in thinking that the correct configuration to setup Cloudflare with TLS, the backup 1.0.0.1 server and a health check is:

```yaml
forward . tls://1.1.1.1 tls://1.0.0.1 {
    tls_servername cloudflare-dns.com
    health_check 5s
}
```

I'm using Azure AKS which lets you [use a ConfigMap that overrides the default settings](https://github.com/Azure/AKS/releases/tag/2019-02-07). I think this would look like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  azurestack.server: |
    azurestack.local:53 {
        forward . tls://1.1.1.1 tls://1.0.0.1 {
          tls_servername cloudflare-dns.com
          health_check 5s
        }
    }
```

**Comment by miekg** [comment]
yes, that should work

**Comment by ciokan** [comment]
also make sure to install `ca-certificates` on your container. I just lost 2 hours with weird 509 errors.

**Comment by miekg** [comment]
that's what we do in our docker container: https://github.com/coredns/coredns/blob/master/Dockerfile

**Comment by RehanSaeed** [comment]
I use the ASP.NET Core or Node base Docker images. I'm guessing that those images have the CA certs pre-installed on them but will keep that in mind if I see certificate errors. I guess I can `exec` into a container and try `curl`'ing something to confirm.
