### ISSUE TITLE
Can't compile with external plugins

### ISSUE THREAD

**Issue by mafonya** [coredns/coredns#1656]
I do everything as listed in this doc: https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/, but no one of the external plugins seems to appear in `./coredns -plugins` after `make`.
Is something broken in a way the external plugins compile with the code?

UPD:
Actually what I see is - no matter how I change the `plugin.cfg` file (even if I leave it empty), after `make` the `./coredns -plugins` will show the same list of default plugins.

**Comment by mafonya** [comment]
UPD2
I found the problem: In coredns.go the path to plugin import is `_ "github.com/coredns/coredns/core/plugin"` instead of `_ "./core/plugin"`. So it doesn't matter what you do in your local FS.

@miekg do you think this is a problem? Should I submit a pull request to change this?
Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Can't compile..." ]
>UPD2
>I found the problem: In coredns.go the path to plugin import is `_ "github.com/coredns/coredns/core/plugin"` instead of `_ "./core/plugin"`. So it doesn't matter what you do in your local FS.
>
>@miekg do you think this is a problem? Should I submit a pull request to change this?
>Thanks!

Hmm, this just follow the current Go guidelines where you should have your code. 
Having a relative import path looks strang-ish? Esp for a one-off as all other 
code in coredns use the full path as well.

**Comment by miekg** [comment]
Is this still a problem?
