### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Doooooo0o** [coredns/coredns#1660]
Hi there,

on a bare-metal setup with SSL components, I have self signed certs everywhere, but coreDNS throws me 

```bash
Failed to list *v1.Namespace: Get https://my_api_endpoint:6443/api/v1/namespaces?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
```

even though I've that coreFile :

```yaml
  Corefile: |
    .:53 {
        errors
        health
        kubernetes k8 in-addr.arpa ip6.arpa {
          tls /kubernetes.pem /kubernetes-key.pem /ca.crt
          endpoint https://my_api_endpoint:6443
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }
```

is there any config line to bypass x509 errors due to unknown CA?

**Comment by chrisohaver** [comment]
> is there any config line to bypass x509 errors due to unknown CA?

No there is not.

**Comment by Doooooo0o** [comment]
it's not possible to run coreDNS on a self signed kubernetes cluster so?

**Comment by chrisohaver** [comment]
You'd need to import the CA to the client that is running CoreDNS.

**Comment by Doooooo0o** [comment]
so in terms of dockerfile, do you think this'll be enough?

```dockerfile
FROM coredns/coredns:1.1.1
COPY ca.crt kubernetes-key.pem kubernetes.pem /
RUN mkdir -p /usr/share/ca-certificates/extra/ \
    && cp ca.crt /usr/share/ca-certificates/extra/ca.crt \
    && cp ca.crt /usr/share/ca-certificates/ \
    && update-ca-certificates
```

**Comment by chrisohaver** [comment]
Seems right.  Though I have not personally added CA certs to a docker image - i don't know if docker does something special there.

I should mention that if you are running coredns _in_ the kubernetes cluster itself (which is most typical), you should connect in-cluster (i.e. remove the `tls` and `endpoint`).

**Comment by Doooooo0o** [comment]
noted, thanks @chrisohaver I'll try right away

**Comment by Doooooo0o** [comment]
doesn't seem to work, I've run from that dockerfile:

```dockerfile
FROM coredns/coredns:1.1.1

COPY ca.crt kubernetes-key.pem kubernetes.pem /
RUN cp /ca.crt /usr/local/share/ca-certificates/ \
    && update-ca-certificates
```

When I grep a string from my ca.crt, in ca-certificates.crt bundle I can find my cert:

```bash
/ # grep MIIDuDCCAqCgAwIBAgIUIICzPwwPLJeiCCJfFd6s0 /etc/ssl/certs/ca-certificates.crt 
MIIDuDCCAqCgAwIBAgIUIICzPwwPLJeiCCJfFd6s0[...]
```

But i still get the [previously shown](https://github.com/coredns/coredns/issues/1660#issue-311162964) error

**Comment by chrisohaver** [comment]
On second thought - importing the CA should not be necessary, since it's included in the connection request.  Not sure if the error implies that the CA cert (ca.crt) is not actually the CA that signed the keys - or that that k8s API server doesn't trust the CA.

Can you connect to the cluster with `kubectl` using those certs?

**Comment by Doooooo0o** [comment]
same error indeed, I'll check on that

**Comment by Doooooo0o** [comment]
works fine :-) thanks @chrisohaver
