### ISSUE TITLE
plugin/forward: can't handle truncated responses

### ISSUE THREAD

**Issue by grobie** [coredns/coredns#1669]
Tested against current master a0f294e550e9369bab711d9ae4ec79c942eeb792.

Any truncated message will be responded with a FormErr by plugin/forward, due to a state mismatch https://github.com/coredns/coredns/blob/a0f294e550e9369bab711d9ae4ec79c942eeb792/plugin/forward/forward.go#L133-L137

That's the result of the proxy implementation always returning `nil` if miekg/dns returns an error, even it's just the pseudo `ErrTruncated`. That affects the implementation in `truncated()` and later on in `Match()`. https://github.com/coredns/coredns/blob/a0f294e550e9369bab711d9ae4ec79c942eeb792/plugin/forward/connect.go#L69

It'd be great to see more test coverage in the plugin/forward implementation given its growing complexity.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/forward: c..." ]
>It'd be great to see more test coverage in the plugin/forward implementation given its growing complexity.

Agreed. Things never stay simple :/

**Comment by grobie** [comment]
In v1.1.1 plugin/forward will retry and eventually respond with ServFail to truncated messages.
