### ISSUE TITLE
plugin/forward: make read timeout configurable

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#1678]
The recently added dynamic timeout feature (#1659) may give worse results than fixed timeout under some circumstances, e.g. at high load when upstream servers are overloaded. Dynamic timeout allows us re-sending unanswered queries faster, and this could be a problem, because we make upstream server load even higher.

In my tests I saw RTT (round trip time) as minimal as 10μs. For comparison, transmission of 50 bytes (400 bits) over 100Mbit network takes about 4μs. So, we can easily catch timeout at the moment when message was partially read which results in truncated messages 

Therefore, I propose to introduce minimal timeout. The reason why we added dynamic timeout feature is to have more attempts to re-send query (probably to different upstreams) during limited period (5 seconds).  Even if we set minimal timeout to 200ms we will get around 25 attempts which is quite enough. No sense to retry faster and create additional server load.

I propose to add a timeout option to forward plugin like below
```
forward .:53 {
    timeout MAX MIN RATIO WEIGHT
}

```
If user specifies only the first parameter (**MAX**) then dynamic timeout will not be used

**MAX** - maximum read timeout which is currently defined by constant `timeout ` 
https://github.com/coredns/coredns/blob/e671e22e657b2fcb1580abd311e9c340b20b9e96/plugin/forward/proxy.go#L93

**MIN** - minimum read timeout. Timeout is based on average RTT but cannot be less than MIN
**RATIO** - desired timeout/RTT ratio. I.e. timeout will be calculated as (average  RTT) * RATIO
**WEIGHT** - defines how much average RTT is influenced by current RTT, i.e. avgRTT = avgRTT + (newRTT-avgRTT)/WEIGHT like in function below
https://github.com/coredns/coredns/blob/e671e22e657b2fcb1580abd311e9c340b20b9e96/plugin/forward/connect.go#L27-L30

**Comment by miekg** [comment]
I think we should do this, but not export it as something you can tweak. We should dynamically do the right thing without bothering the user with config tweaks IMO

**Comment by rdrozhdzh** [comment]
We can make the last two (the most sophisticated) parameters optional, with some default values. 
But I would give user ability to set max and min timeout, since user may better know capabilities of his networks. I.e. if coredns and resolver are in the same network (or even on the same host) it would be reasonable to decrease max timeout. On the other hand, min timeout may work better for distant networks or under high load
