### ISSUE TITLE
plugin/cache: capacity/eviction behavior

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1684]
Observationally via performance tests i was running, I noticed that when I was setting a cache capacity to 0 in CoreDNS, performance was identical to setting a high capacity cache.  This suggested that setting cache capacity to zero does not effectively disable cache, as a user might expect.

Looking over the cache code, (If I understand correctly)...

- It seems that the cache is made up of 256 shards, each of which have a minimum cardinality of 512.  Which means that the minimum cache size is effectively 131,072.  This is higher than the maximum cache capacity indicated in the README (10,000).

- It also appears that cache eviction is done at the shard level, meaning that eviction will occur when a single shard is filled.  I believe this means that we will start evicting entries before the entire cache actually reaches full capacity.

@miekg, is my understanding above correct?  If so, are these problems to fix? Or expected behaviors to document?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/cache: cap..." ]
>Observationally via performance tests i was running, I noticed that when I was setting a cache capacity to 0 in CoreDNS, performance was identical to setting a high capacity cache.  This suggested that setting cache to zero does not effectively disable cache, as a user might expect.
>
>Looking over the cache code, (If I understand correctly)...
>
>- It seems that the cache is made up of 256 shards, each of which have a minimum cardinality of 512.  Which means that the minimum cache size is effectively 131,072.  This is higher than the maximum cache capacity indicated in the README (10,000).

Oops, yes. I think the 10.000 is meant to be per shard, but this def. needs 
clarification in the README.

>- It also appears that cache eviction is done at the shard level, meaning that eviction will occur when a single shard is filled.  I believe this means that we will start evicting entries before the entire cache actually reaches full capacity.

Also true, yes we evict per shard.

>@miekg, is my understanding above correct?  If so, are these problems to fix? Or expected behaviors to document?

Documenting sgtm - fix are welcome as well, but what do you want to fix/do?

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
> what do you want to fix/do?

We might want to have a way of actually disabling caches (e.g. disable negative cache).  AFAIK using negative cache is a best practice in DNS ... but I don't know if there is a reason someone might want to disable it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/cache:..." ]
>> what do you want to fix/do?
>
>We might want to have a way of actually disabling caches (e.g. disable negative cache).  AFAIK using negative cache is a best practice in DNS ... but I don't know if there is a reason someone might want to disable it.

you mean 'denial 0' should disable caching for negative responses for instance?
That would make sense, not sure if that works today.

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
Setting a cache capacity to zero (e.g. 'denial 0') doesn't disable that cache -  the minimum shard size of 512 doesn't allow it. Setting to zero results in a cache size of 512 per each 256 shards (131,072 total).
