### ISSUE TITLE
ETCD: A record and NS record for dns zone name

### ISSUE THREAD

**Issue by m4r10k** [coredns/coredns#1685]
Hi!

Following situation: I have to provide a zone, for example `abc.def.gh`. This zone should contain an A record with the same name as the zone eg.  `abc.def.gh 1.1.1.1` and of course multiple host entries eg  `gg.abc.def.gh 2.2.2.2` and so on.

The problem is, that the path in the ETCD cannot be a directory and a key at the same time:
```
/my-prefix/gh/def/abc {"host": "1.1.1.1", "ttl":"60"}
/my-prefix/gh/def/abc/gg {"host": "2.2.2.2", "ttl":"60"}
```

This leads to the situation that I am not able to create the NS entries if I would like to use the zonename as host too, because the entry `/my-prefix/gh/def/abc/dns/ns/ns1` is not usable if the `/my-prefix/gh/def/abc` is already a *key*.

Bind config would be:
```
abc.def.gh.	IN	NS	bind.
abc.def.gh.	IN	A	1.1.1.1
```

Am I missing something?

**Comment by m4r10k** [comment]
Hmm, and solving (work around) this by creating group records does not work too, because on asking the main domain (zone) all ip addresses are returned recursively. :smile: 
```
By default SkyDNS will returns all records under a name. Suppose you want we have bar.skydns.local... TODO.
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] ETCD: A recor..." ]
>Hmm, and solving (work around) this by creating group records does not work too, because on asking the main domain (zone) all ip addresses are returned recursively. :smile:
>```
>By default SkyDNS will returns all records under a name. Suppose you want we have bar.skydns.local... TODO.
>```

yes, the etcd plugin is no replacement for a real zone file, ones the sql plugin 
gets any traction we may implement an etcd driver for that (but don't hold your 
breath)

**Comment by m4r10k** [comment]
The great benefit of ETCD is, that it can be easily clustered and that there is a "standard" API interface for it. I would like to avoid patching files on disk (or an share) to achieve dynamic updates. The current setup with ETCD as backend is really slick, reliable and easy to sustain. I do not know, but can I mix the plugins?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] ETCD: A recor..." ]
>The great benefit of ETCD is, that it can be easily clustered and that there is a "standard" API interface for it. I would like to avoid patching files on disk (or an share) to achieve dynamic updates. The current setup with ETCD as backend is really slick, reliable and easy to sustain. I do not know, but can I mix the plugins?

Indeed, etcd is great and it would be good to have more complete support for 
actually storing zones in there (not the limited set of RRs we allow now).

No you can't mix etcd and file because there are both, the final source of 
information, so it's either etcd XOR file.

/Miek

--
Miek Gieben

**Comment by m4r10k** [comment]
Luckily  I have to provide different domains and in the ETCD backed zone, i must not provide an A record for the zone name itself :+1: 

Therefore I can make use of both, the ETCD plugin with dynamic updates if no A record for the zone name itself is used and the AUTO plugin to load the zone witch requires the A record for the zone name but no dynamic updates via an api interface :see_no_evil: 

Looks like this:
```
. {
    etcd abc.com efg.com {
        stubzones
	path /...
        endpoint ...
        tls ...
    }

    auto hjk.com {
        directory /...
    }

    bind ...
    loadbalance
    proxy . ...
}
```
So yes, this is a work around.

But I would like to drop in a suggestion for the ETCD plugin. What do you think about the idea to use a special entry for the A record(s) used for the zone name itself like it is for the dns ns already (`/my-prefix/gh/def/abc/dns/ns/ns1`). For example:
```
/my-prefix/gh/def/abc/dns/a/a1
```
On an query for the A of the zone itself (`ig +short abc.def.gh A @ns`) respond with the entries under `/my-prefix/gh/def/abc/dns/a/...` if provided, otherwise continue with the default behavior.

I think that would be a valid progression and a fair compromise because the `dns` name as such is already messed up as directory under the given domain ...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] ETCD: A recor..." ]
>Luckily  I have to provide different domains and in the ETCD backed zone, i must not provide an A record for the zone name itself :+1:
>
>Therefore I can make use of both, the ETCD plugin with dynamic updates if no A record for the zone name itself is used and the AUTO plugin to load the zone witch requires the A record for the zone name but no dynamic updates via an api interface :see_no_evil:
>
>Looks like this:
>```
>. {
>    etcd abc.com efg.com {
>        stubzones
>	path /...
>        endpoint ...
>        tls ...
>    }
>
>    auto hjk.com {
>        directory /...
>    }
>
>    bind ...
>    loadbalance
>    proxy . ...
>}
>```
>So yes, this is a work around.

LOL, coredns++ :-)

>But I would like to drop in a suggestion for the ETCD plugin. What do you think about the idea to use a special entry for the A record(s) used for the zone name itself like it is for the dns ns already (`/my-prefix/gh/def/abc/dns/ns/ns1`). For example:
>```
>/my-prefix/gh/def/abc/dns/a/a1
>```
>On an query for the A of the zone itself (`ig +short abc.def.gh A @ns`) respond with the entries under `/my-prefix/gh/def/abc/dns/a/...` if provided, otherwise continue with the default behavior.
>
>I think that would be a valid progression and a fair compromise because the `dns` name as such is already messed up as directory under the given domain ...

True, this indeed sounds like a small thing we could add. Open for PRs
