### ISSUE TITLE
kubernetes cluster domain returns services (dig cluster.local)

### ISSUE THREAD

**Issue by dlamotte** [coredns/coredns#1687]
Unsure if this is defined behavior or not, but I'm running against CoreDNS 1.1.1 and I noticed that when I `dig cluster.local` it returns `A` records for all services in the cluster (at least as far as I can tell).

I'm in the process of changing that base domain to my company's domain (k8s.company.com).  I was hoping to use k8s.company.com to resolve the apiserver IP, but if I choose to use CoreDNS as the authority for this as well, I cannot because it resolves to the kubernetes services.  I'm doing the following to host the kubernetes records and authority.

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        cache
        errors
        health
        file /etc/coredns/company.com.zone company.com
        kubernetes k8s.company.com in-addr.arpa ip6.arpa {
          fallthrough k8s.company.com in-addr.arpa ip6.arpa
        }
        log
        prometheus :9153
        proxy . /etc/resolv.conf
    }
  company.com.zone: |
    $ORIGIN company.com.

    ; default ttl
    $TTL 7200

    ;                   authority-domain  domain-of-zone-admin
    company.com.  IN  SOA   ns.company.com.       hostmaster.company.com. (
                        1       ; zone-serial-number
                        7200    ; refresh-time
                        900     ; retry-time
                        1209600 ; expire-time
                        86400 ) ; negative caching ttl

    ; resource record
    ; name   ttl    record-class  record-type   record-data
    ; company.com.      IN            NS            ns ; ns.company.com
    k8s.company.com  IN            A               10.1.1.5 ; kubernetes apiserver
```

With this configuration, I cannot do `dig k8s.company.com` and get `10.1.1.5`.  I get the services in the cluster.

I tried _hacking_ a solution with `rewrite` but was unsuccessful.

**Comment by chrisohaver** [comment]
> returns A records for all services in the cluster. 

No, it’s not supposed to do that. There was a similar issue in the past when querying bare namespaces.  This should be fixed. Thanks for reporting it.

**Comment by chrisohaver** [comment]
> With this configuration, I cannot do dig k8s.company.com and get 10.1.1.5. I get the services in the cluster.

This is partly because file comes after kubernetes in the plugin.cfg order...(order in your config doesn’t matter). If file was before kubernetes, then you could put “fallthrough” in file so that queries other than “k8s.company.com” fallthrough to k8s instead of sending nxdomain to the client.

**Comment by dlamotte** [comment]
Thanks! That requires I recompile with that change, right?

**Comment by chrisohaver** [comment]
Actually. I just checked, and file does list fallthrough as an option. 

However you can use the template plugin instead. And this is before kubernetes already.

**Comment by dlamotte** [comment]
Using `template` worked!  I was wondering if that would be a good workaround.  Still looking forward to this fix regardless though 😄

**Comment by chrisohaver** [comment]
@dlamotte fix merged

**Comment by dlamotte** [comment]
I'm trying out and testing this new fix.  But I can't seem to convince the `kubernetes` plugin to fall through to the `file` plugin in this case.  I am getting a `NOERROR` status which I think ensures it won't fall through.  Should it be `NXDOMAIN` instead of `NOERROR`?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] kubernetes cl..." ]
>I'm trying out and testing this new fix.  But I can't seem to convince the `kubernetes` plugin to fall through to the `file` plugin in this case.  I am getting a `NOERROR` status which I think ensures it won't fall through.  Should it be `NXDOMAIN` instead of `NOERROR`?

No, we can't do that, because a resolver then assume nothing exists under 
cluster.local or {pod,svc}.cluster.local, so it has to be NODATA and then we 
don't fallthrough - because the name exists.

**Comment by johnbelamaric** [comment]
I think you can hack around this with `rewrite`. Something like this (not tested!):

```
 rewrite {
   name exact k8s.company.com. apiserver.k8s.company.com.
   answer name apiserver.k8s.company.com. k8s.company.com.
 }
```

**Comment by dlamotte** [comment]
Ok cool.  No worries.  I can use the `template` hack 😄 Thanks again!

**Comment by johnbelamaric** [comment]
Ok, cool. Above doesn't work because `answer` only works with `regex`. This works:

```
 rewrite {
   name regex ^k8s.company.com.$ google.com.
   answer name google.com. k8s.company.com.
 }
```
