### ISSUE TITLE
Forward plugin doesn't support a sequential policy

### ISSUE THREAD

**Issue by sdonovan01** [coredns/coredns#1691]
The forward plugin currently only support random and round_robin policies for upstream server selection.  The default DNS resolution behavior is to check the first nameserver... then the second... and so on until all nameservers have been queried or a match is found.  Neither of these policies accomplish this.  I am suggesting that a new policy be added to the forward plugin named 'sequential' that provides the default DNS resolution behavior mentioned above.

I've looked at the forwarder code it it should be pretty simple to add this functionality.  I'll submit a pull request if it is agreed that this functionality is useful and the pull request will be accepted.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Forward plugin do..." ]
>The forward plugin currently only support random and round_robin policies for upstream server selection.  The default DNS resolution behavior is to check the first nameserver... then the second... and so on until all nameservers have been queried or a match is found.  Neither of these policies accomplish this.  I am suggesting that a new policy be added to the forward plugin named 'sequential' that provides the default DNS resolution behavior mentioned above.
>
>I've looked at the forwarder code it it should be pretty simple to add this functionality.  I'll submit a pull request if it is agreed that this functionality is useful and the pull request will be accepted.

Yep that will be accepted. Note we have that policy in *proxy* and it's called 
"first" there, allthough now that I see it mentioned I quite like 'sequential'.

**Comment by miekg** [comment]
... and fixed!
