### ISSUE TITLE
1.1.2 release

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1697]
See the milesone tracker for what needs to be done: https://github.com/coredns/coredns/milestone/16

If you want something in 1.1.2 now is the time to ask.

**Comment by m4r10k** [comment]
So yes, #1700 would be nice, but obviously this will take some days to figure out the best way to go, though.

**Comment by miekg** [comment]
Also note that #1696 is significantly more work than just adding a server label to metrics, as these get set in places where we don't have the context. So I'm pondering releases 1.1.2 as-is and doing this in 1.1.3 (keeps the release small-ish as well).

@m4r10k noted: but that PR is also not in a finished state. (and releases are cheap anyway)

**Comment by m4r10k** [comment]
@miekg I'm right there with you! Not a must at this point! :+1:

**Comment by miekg** [comment]
released: https://coredns.io/2018/04/23/coredns-1.1.2-release/
