### ISSUE TITLE
 plugin/rewrite: exceeded the number of arguments for a name rule

### ISSUE THREAD

**Issue by feresberbeche** [coredns/coredns#1708]
Corefile
> .:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
    }
    rewrite continue {
    name regex ldap.feres.lab ldap.default.svc.cluster.local  
    answer name ldap.default.svc.cluster.local ldap.feres.lab  
    type ANY A 
    }
    proxy . /etc/resolv.conf
    cache 30
}

I got this error even though it's correct 
I tried putting the type filed in another line outside rewrite continue but it still dosen't work and I got that error,
Also when I do `kubectl edit -n kube-system configmap coredns` the core file appear mal formatted 

>   Corefile: ".:53 {\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa
    ip6.arpa {\n       pods insecure\n       upstream\n       fallthrough in-addr.arpa
    ip6.arpa\n    }\n    rewrite stop {\n    name regex ldap.feres.lab ldap.default.svc.cluster.local
    \ \n    answer name ldap.default.svc.cluster.local ldap.feres.lab  \n    type
    ANY A \n    }\n    proxy . /etc/resolv.conf\n    cache 30\n}\n"

**Comment by chrisohaver** [comment]
Regarding the the kubectl formatting thing - this is a kubectl behavior.  It does this sometimes when it sees special characters in a config.  For example, if there is a tab in the config, it will strip them and replace line breaks with \n's like above.

**Comment by chrisohaver** [comment]
looks like rewrite parsing has a bug.  The following functionally equivalent config works for me...
```
        rewrite continue {
          name regex ldap.feres.lab ldap.default.svc.cluster.local
          answer name ldap.default.svc.cluster.local ldap.feres.lab
        }
        rewrite continue type ANY A
```

... but when I add the type rule in the block with the others, it barfs.

**Comment by feresberbeche** [comment]
I didn't get an error when I tried that 
but the rewrite ANY to A didn't work

> dnstools# dig ANY ldap.feres.lab
; <<>> DiG 9.11.1-P1 <<>> ANY ldap.feres.lab
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27237
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 9ebdc78b49e024e5 (echoed)
;; QUESTION SECTION:
;ldap.feres.lab.                        IN      ANY
;; AUTHORITY SECTION:
cluster.local.          24      IN      SOA     ns.dns.cluster.local. hostmaster.cluster.local. 1524236689 7200 1800 86400 30
;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Apr 20 15:07:03 UTC 2018
;; MSG SIZE  rcvd: 122

When I tried this 

>         rewrite continue type ANY A
>         rewrite continue {
>           name regex ldap.feres.lab ldap.default.svc.cluster.local
>           answer name ldap.default.svc.cluster.local ldap.feres.lab
>         }

The rewrite ANY to A worked but not the rewrite name and answer
it seems to ignore the second rewrite everytime.

**Comment by chrisohaver** [comment]
OK - I think this [original reported issue] isn't a bug - but error messages should be less mysterious, and the docs could explain better...

An answer rewrite rule only works in conjunction with one other request rewrite rule.
They are associated with one another by putting them in a block.  This is the only valid use of a block for `rewrite`.
```
        rewrite continue {
          name regex ldap.feres.lab ldap.default.svc.cluster.local
          answer name ldap.default.svc.cluster.local ldap.feres.lab
        }
        rewrite continue type ANY A
```
In the above example, answers of `ldap.default.svc.cluster.local` are rewritten to `ldap.feres.lab`, only if the question was rewritten from `ldap.feres.lab` `ldap.default.svc.cluster.local`.
The answer rewrite doesnt care if the type was changed or not in the type rule.

**Comment by feresberbeche** [comment]
yeah but when putting two rewrites, only the first one works. and it dosen't resolve the issue.

**Comment by chrisohaver** [comment]
> but the rewrite ANY to A didn't work

The type rewrite works when I try it...

```
dnstools# dig google.com -t ANY
;; Question section mismatch: got google.com/A/IN
```

**Comment by feresberbeche** [comment]
I can't seem to get them both working at the same time.
Here is my Corefile, maybe there is something wrong with it 

> 
>   Corefile: |
>     .:53 {
>         errors
>         health
>         kubernetes cluster.local in-addr.arpa ip6.arpa {
>            pods insecure
>            upstream
>            fallthrough in-addr.arpa ip6.arpa
>         }
>         rewrite continue {
>           name regex ldap.feres.lab ldap.default.svc.cluster.local
>           answer name ldap.default.svc.cluster.local ldap.feres.lab
>         }
>         rewrite continue type ANY A
>         proxy . /etc/resolv.conf
>         cache 30
>     }

**Comment by chrisohaver** [comment]
Hmm. What version of coredns are you running?  I'm testing in 1.1.1 ...

**Comment by feresberbeche** [comment]
[INFO] CoreDNS-1.0.6

**Comment by chrisohaver** [comment]
Odd, I see no significant changes to rewrite between 1.0.6 and 1.1.1.

**Comment by feresberbeche** [comment]
I updated to 1.1.1 and still the same thing, only one of the rewrites works. now it seems to be only the type ANY to A.

**Comment by chrisohaver** [comment]
FYI, I just opened #1711 ... which I discovered while looking into this issue. Seems related-ish.

See if this following works (order important)...
```
      rewrite continue type ANY A
      rewrite stop {
        name regex ldap\.feres\.lab ldap.default.svc.cluster.local
        answer name ldap\.default\.svc\.cluster\.local ldap.feres.lab
      }
```

**Comment by chrisohaver** [comment]
There isn't a functional bug here, but the error messages are unhelpful.
I'll see if I can make the error messages more clear, so we can close this out.
