### ISSUE TITLE
plugin/rewrite:  response rewrite with continue option fails

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1711]
CoreDNS 1.1.1 ...
I found that the `continue` option causes a response re-write rule to not work.

For example...
```
      rewrite continue {
        name regex test\.local kubernetes.default.svc.cluster.local
        answer name kubernetes\.default\.svc\.cluster\.local test.local
      }
```
... fails to rewrite the response ...
```
dnstools# dig test.local. -t A
;; Question section mismatch: got kubernetes.default.svc.cluster.local/A/IN
```
... while ...
```
      rewrite stop {
        name regex test\.local kubernetes.default.svc.cluster.local
        answer name kubernetes\.default\.svc\.cluster\.local test.local
      }
```
... works fine ...
```
dnstools# dig test.local. -t A

; <<>> DiG 9.11.1-P1 <<>> test.local. -t A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39949
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: bf7f5bede8bb8ece (echoed)
;; QUESTION SECTION:
;test.local.			IN	A

;; ANSWER SECTION:
test.local.		5	IN	A	10.0.0.1

;; Query time: 0 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Fri Apr 20 18:54:20 UTC 2018
;; MSG SIZE  rcvd: 67
```

**Comment by feresberbeche** [comment]
Do you have any idea when this issue will be solved, cause I am working on a project that needs multiple name, answer rewrites, therefore rewrite continue is needed. do you know anyway to overcome this bug or when the next release is coming, thank you

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/rewrit..." ]
>Do you have any idea when this issue will be solved, cause I am working on a project that needs multiple name, answer rewrites, therefore rewrite continue is needed. do you know anyway to overcome this bug or when the next release is coming, thank you

don't think anyone volunteered themselves for fixing this, so I don't know.

**Comment by chrisohaver** [comment]
> needs multiple name, answer rewrites

As long as the same queries don't need to be modified more than once you should be ok with a series of stop rewrites.  Do you have a case where you would need to modify a single query with more than one name/answer rewrite rule?  If so, perhaps you can combine them into one rule.

[ To clarify a bit: a "stop" rewrite rule will only stop checking rewrites if the rule is matched. If the rule is not matched, it still continues to check the next rule. ]
