### ISSUE TITLE
Forward plugin recurse's on itself when pointed at /etc/resolv.conf

### ISSUE THREAD

**Issue by sdonovan01** [coredns/coredns#1712]
We are running CoreDNS as a replacement for dnsmasq.  We are running it on 127.0.0.1:53.  In one of our server blocks we would like to be able to do something like:
```
. {
    forward . /etc/resolv.conf
}
```
with a resolv.conf that looks like:
```
nameserver 127.0.0.1     # local
nameserver xx.xx.xx.xx   # primary
nameserver yy.yy.yy.yy   # secondary

options timeout:1
search local service.dev.ourdomain1.com ourdomain2.com
```
When the CoreDNS forward plugin is configured with a random or round_robin policy you will occasionally get recursive loops when you are forwarded to the 127.0.0.1 proxy because CoreDNS is what is running on 127.0.0.1:53.  If the policy is random or round_robin you will eventually be forwarded to the primary or secondary nameserver and everything unwinds itself correctly (but inefficiently).  

This seems like a minor bug.  CoreDNS should be capable of being configured to ignore the 127.0.0.1 nameserver entry in resolv.conf when it is listening on 127.0.0.1:53.  This becomes a major bug if you set the policy to sequential (infinite loop). 

We could just pull out the primary and secondary IPs and do something like:
```
. {
    forward . xx.xx.xx.xx yy.yy.yy.yy
}
```
Which is what we are doing with our on-prem infrastructure.  When running in the cloud our resolv.conf is created on the fly at boot so we would have to create our Corefile on the fly as well.  I really don't like doing this kind of "just in time" configuration.

If I do a pull request to add a 'ignore_localhost' config option to the forward plugin to exclude 127.0.0.1 from the servers list if the file you are reading in is named resolv.conf will you accept it?

I'm guessing that the proxy plugin has the same issue.  If so... I'll do both.

**Comment by miekg** [comment]
There are many ways you can shoot your self in the foot, checking if localhost may are not be involved is on one facet. See https://github.com/coredns/coredns/issues/1647 for a broader discussion on a new plugin *loop*.

**Comment by miekg** [comment]
closing here, for now CoreDNS doesn't care. see #1647 for solution discussion
