### ISSUE TITLE
plugin:health SIGUSR1: listen tcp :8080: bind: address already in use

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [coredns/coredns#1722]
Observed for CoreDNS 1.1.2 with Corefile
```
.:53 {
	health
	forward . 8.8.8.8:53
	errors
}
```
some graceful restarts failed:
```
.:53
2018/04/23 17:52:57 [INFO] CoreDNS-1.1.2
2018/04/23 17:52:57 [INFO] linux/amd64, go1.9.2, 
CoreDNS-1.1.2
linux/amd64, go1.9.2, 
2018/04/23 17:53:14 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:14 [INFO] Reloading
2018/04/23 17:53:14 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 17:53:16 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:16 [INFO] Reloading
2018/04/23 17:53:16 [INFO] Reloading complete
2018/04/23 17:53:18 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:18 [INFO] Reloading
2018/04/23 17:53:18 [INFO] Reloading complete
2018/04/23 17:53:19 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:19 [INFO] Reloading
2018/04/23 17:53:19 [INFO] Reloading complete
2018/04/23 17:53:20 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:20 [INFO] Reloading
2018/04/23 17:53:20 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 17:53:21 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:21 [INFO] Reloading
2018/04/23 17:53:21 [INFO] Reloading complete
2018/04/23 17:53:23 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:23 [INFO] Reloading
2018/04/23 17:53:23 [INFO] Reloading complete
2018/04/23 17:53:24 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:24 [INFO] Reloading
2018/04/23 17:53:24 [INFO] Reloading complete
2018/04/23 17:53:25 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:25 [INFO] Reloading
2018/04/23 17:53:25 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 17:53:26 [INFO] SIGUSR1: Reloading
2018/04/23 17:53:26 [INFO] Reloading
2018/04/23 17:53:26 [INFO] Reloading complete
```

**Comment by fturib** [comment]
You always reload the same corefile ?
so it is not reliable ?

**Comment by UladzimirTrehubenka** [comment]
Yes, the same Corefile

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin:health SIG..." ]
>Observed for CoreDNS 1.1.2 with Corefile
>```
>.:53 {
>	health
>	forward . 8.8.8.8:53
>	errors
>}
>```

meh :(

**Comment by miekg** [comment]
uh: linux/amd64, go1.9.2, 

Using the `coredns` binary from the released tar files I **can't** replicate this, even with:
~~~
 % while true; do kill -SIGUSR1 $(pidof coredns); done
~~~
CoreDNS logs:
~~~
...
2018/04/23 18:55:47 [INFO] SIGUSR1: Reloading
2018/04/23 18:55:47 [INFO] Reloading
2018/04/23 18:55:47 [INFO] Reloading complete
2018/04/23 18:55:47 [INFO] SIGUSR1: Reloading
2018/04/23 18:55:47 [INFO] Reloading
2018/04/23 18:55:47 [INFO] Reloading complete
2018/04/23 18:55:47 [INFO] SIGUSR1: Reloading
2018/04/23 18:55:47 [INFO] Reloading
2018/04/23 18:55:47 [INFO] Reloading complete
2018/04/23 18:55:47 [INFO] SIGUSR1: Reloading
2018/04/23 18:55:47 [INFO] Reloading
....
~~~~

**Comment by johnbelamaric** [comment]
Is there traffic to the health endpoint in either case?

**Comment by miekg** [comment]
ah, good point. Not in my case

**Comment by chrisohaver** [comment]
I know its a small sample size... but the timing of the failures in the first example seems steady at 5 seconds ...  but the probe period is 10 seconds in the default k8s deployment.

**Comment by miekg** [comment]
Now running 2 `while true` loops, still OK: curl side:
~~~
OKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKcurl: (56) Recv failure: Connection reset by peer
OKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKcurl: (55) Send failure: Connection reset by peer
OKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKcurl: (55) Send failure: Connection reset by peer
OKOKOKOKOKOKOKOKOKOKcurl: (56) Recv failure: Connection reset by peer
OKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOK
~~~

**Comment by miekg** [comment]
It this stand alone or in a pod in a k8s cluster?

**Comment by chrisohaver** [comment]
was going to say I could not reproduce this... But then after having it do a reload too many times, kubernetes thought the pod was unhealthy, and restarted it... 

After it restarted... it fails on every reload...

```
.:53
CoreDNS-1.1.2
linux/amd64, go1.10.1, 582f91f3
2018/04/23 18:18:55 [INFO] CoreDNS-1.1.2
2018/04/23 18:18:55 [INFO] linux/amd64, go1.10.1, 582f91f3
2018/04/23 18:18:55 [ERROR] SIGUSR1: listen tcp :53: bind: address already in use
2018/04/23 18:18:56 [INFO] SIGUSR1: Reloading
2018/04/23 18:18:56 [INFO] Reloading
2018/04/23 18:18:56 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:18:56 [INFO] SIGUSR1: Reloading
2018/04/23 18:18:56 [INFO] Reloading
2018/04/23 18:18:56 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:18:57 [INFO] SIGUSR1: Reloading
2018/04/23 18:18:57 [INFO] Reloading
2018/04/23 18:18:57 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:18:58 [INFO] SIGUSR1: Reloading
2018/04/23 18:18:58 [INFO] Reloading
2018/04/23 18:18:58 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:18:58 [INFO] SIGUSR1: Reloading
2018/04/23 18:18:58 [INFO] Reloading
2018/04/23 18:18:58 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:18:59 [INFO] SIGUSR1: Reloading
2018/04/23 18:18:59 [INFO] Reloading
2018/04/23 18:18:59 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:19:00 [INFO] SIGUSR1: Reloading
2018/04/23 18:19:00 [INFO] Reloading
2018/04/23 18:19:00 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:19:00 [INFO] SIGUSR1: Reloading
2018/04/23 18:19:00 [INFO] Reloading
2018/04/23 18:19:00 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:19:01 [INFO] SIGUSR1: Reloading
2018/04/23 18:19:01 [INFO] Reloading
2018/04/23 18:19:01 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:19:02 [INFO] SIGUSR1: Reloading
2018/04/23 18:19:02 [INFO] Reloading
2018/04/23 18:19:02 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/23 18:19:02 [INFO] SIGUSR1: Reloading

```

**Comment by johnbelamaric** [comment]
It restarted the container not the pod, since it must be in the same network namespace in order to have this issue. But it didn't kill the first container? That's weird.

**Comment by miekg** [comment]
I've seen this as well (long time ago in my cluster) - Think I filled an issue.

yeah: https://github.com/coredns/coredns/issues/1518

with our friends metrics, but still super weird, because these a new pods with no relation to the old ones.

**Comment by chrisohaver** [comment]
> It restarted the container not the pod

Ah ok.  Yes, I see the pod name stayed the same. How does this work for pods with > 1 container?

**Comment by chrisohaver** [comment]
I was able to replicate the behavior I described above again, after two tries.

1. send SIGUSR1 to coredns in a loop (with a 0.5 second sleep). 
2. coredns reload events all logged as successful
3. constant interruption to health probe causes kubernetes to give CPR the pod (restart container in pod)
4. when container comes back up, sometimes things get in a state where all reloads fail.

Note: I cannot reproduce a state where sometimes reloads work, and sometimes they fail (as in Ulad's example).  Just one or the other... and only after k8s gives the pod CPR...

(I'm also doing all this in minikube ... fwiw)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin:health SIG..." ]
>Observed for CoreDNS 1.1.2 with Corefile
>```
>.:53 {
>	health
>	forward . 8.8.8.8:53
>	errors
>}
>```
>some graceful restarts failed:

While tedious and hard it would be good to narrow down what happens here. It 
seems very much related to running in k8s - and thus Docker - as I can't see this 
happening outside of such environment (yet).

**Comment by miekg** [comment]
~~~
% docker run test/coredns -conf /Corefile
.:53
CoreDNS-1.1.2
linux/amd64, go1.10.1, c9b5cedb-dirty
2018/04/24 06:33:11 [INFO] CoreDNS-1.1.2
2018/04/24 06:33:11 [INFO] linux/amd64, go1.10.1, c9b5cedb-dirty
172.17.0.1:53013 - [24/Apr/2018:06:34:38 +0000] 29774 "MX IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd 78 373.716µs
172.17.0.1:55983 - [24/Apr/2018:06:34:40 +0000] 41603 "MX IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd 78 158.252µs
~~~
sending the signal:
~~~
% while true; do sudo kill -SIGUSR1 $(pidof coredns); i=$(( i=i+1 )); echo $i; done
~~~
Not seeing failed reload after 764 attempts.
Health is also OK:
~~~
%  while true; do curl -s http://172.17.0.2:8080/health; done
~~~
Interestingly though the OKs don't stutter like they do when running without docker, they succeed even during the reload.

**Comment by UladzimirTrehubenka** [comment]
Observed on my local env (not k8s):
go 1.9.2 - issue exists
go 1.10 - no errors

**Comment by miekg** [comment]
lol - if you're inclined it might be nice to diff src/net/ in Go from 1.9.2 to 1.10
(maybe Go is now setting some socket opt automatically on Linux?)

**Comment by fturib** [comment]
I am using 1.9.4, on a Mac OS
I ran ./crodns with the simple config propose by @UladzimirTrehubenka, (not using docker)
I setup the 2 loop of SIGUSR1 and curl localhost/health proposed by @miekg  (both loop without sleep time).

and I get the issue quiet often ... 

```
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [ERROR] SIGUSR1: listen tcp :8080: bind: address already in use
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete
2018/04/24 08:40:13 [INFO] SIGUSR1: Reloading
2018/04/24 08:40:13 [INFO] Reloading
2018/04/24 08:40:13 [INFO] Reloading complete

```


- If I add "sleep" in the loop of SIGUSR1 I get the same "already in use" but much less often.

- if I run only ONE loop SIGUSR1 (not http) - with no sleep, I get the issue quite often. (about let say average of 1 out of 3 reload)

- if I run only ONE loop SIGUSR1 (not http) - with 0.5 sleep, I get the issue less often. (let say average of 1 out of 6 reload)

- if I run only ONE loop SIGUSR1 (not http) - with 5 sec sleep, I still get the issue but less often (average of 1 out of 20 reloads).

NOTE: in my case, the next reload, usually is successful. Which means it looks like the "tcp listener" is not completely stopped - in some case, which prevent the next start to be successful.

Maybe need an option to ensure that TCP Listener are completely down when exiting the listener.close(). 
If the 5 sec has the issue, it means maybe sometime it is not closed at all ! In that case, why the next try is ok ?

NOTE: now, Listener is closed at "OnRestart()" => Before the new Corefile is loaded, and "OnFinalShutdown()" .. before the whole CoreDNS is stopped.

NOTE: my understanding of the function of the signal process in Caddy is that you cannot process a SIGNAL while another one is already in progress : it listen the series of signal from inside a channel.

**Comment by fturib** [comment]
From the Release Notes of Go 1.10 (here : https://golang.org/doc/go1.10)

> **net**
> The Conn and Listener implementations in this package now guarantee that when Close returns, the underlying file descriptor has been closed. (In earlier releases, if the Close stopped pending I/O in other goroutines, the closing of the file descriptor could happen in one of those goroutines shortly after Close returned.)

**Comment by johnbelamaric** [comment]
@fturib, that’s the smoking gun...

**Comment by fturib** [comment]
Yes, I think that is the root cause of this issue:
- Test on 1.10 and 1.9.x show consistency with that explanation.
- I tested on my earlier PR which do the same work, but without closing because we reuse the listener : it just work fine.

IMO, we can consider that RELOAD or SIGUSR1 will not happen with that frequency, meaning that issue should not be a problem.

Also, you may encounter whatever issue during a restart, first of it an invalid corefile. 
So you need to come up with solution when reload is not successful.

I do not think that trying to workaround worth it. Better to wait 1.10 is spread out.

I propose to close with "Will not fix". What do you think ?

**Comment by UladzimirTrehubenka** [comment]
Ok, we are going to use go 1.10

**Comment by chrisohaver** [comment]
Just to make sure it's clear, the issue I saw was not related to go 1.10 vs 1.9 ... since I reproduced it a few times using the 1.10 build ...  So it must be a different core issue.

I'm OK with consciously ignoring it if everyone else is.  I have only reproduced it via rapidly sending SIGUSR1's... which is not a practical use case.

**Comment by miekg** [comment]
close - I've still haven't locally replicated with with go 1.10.1
