### ISSUE TITLE
middleware/dnstap

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#174]
http://dnstap.info/

grpc logging output written to a socket (or whatever) where it is picked up by dnstap (cmd line) tool. Should include this in the logging/error middleware

**Comment by johnbelamaric** [comment]
@miekg any reason not to do this? we have existing code that relies on dnstap we would like to leverage.

**Comment by miekg** [comment]
No cycles? Never cared/used much of dnstap. Feel free to reopen.

Consider my remark above; should be a separate middleware if possible

**Comment by johnbelamaric** [comment]
Ok, yes, a separate middleware makes sense. Thanks.

**Comment by miekg** [comment]
We have this! Thanks to @varyoo
