### ISSUE TITLE
v1.1.2 SIGUSR1 reloading not work

### ISSUE THREAD

**Issue by yybear** [coredns/coredns#1755]
Because when I used SIGUSR1 only, I found sometime it worked, sometime it didn't (I don't know why, the reload log was ok ), so I want to use SIGUSR1, Reloading plugin together to make sure the changes of ConfigMap would be work.  

I use the coredns 1.1.2 (enable the Reload plugin) to test reloading ConfigMap.
after i changed the ConfigMap, then sending "kill -SIGUSR1 1". 
the log is:
2018/04/29 01:08:34 [INFO] Reloading
2018/04/29 01:08:34 [INFO] plugin/reload: Running configuration MD5 = _**eaa78891e80640df4601ea455f117a30**_
2018/04/29 01:08:34 [INFO] Reloading complete
2018/04/29 01:08:41 [INFO] **SIGUSR1: Reloading**
2018/04/29 01:08:41 [INFO] Reloading
2018/04/29 01:08:41 [INFO] plugin/reload: Running configuration MD5 = _**eaa78891e80640df4601ea455f117a30**_
2018/04/29 01:08:41 [INFO] Reloading complete
2018/04/29 01:09:02 [INFO] **SIGUSR1: Reloading**
2018/04/29 01:09:02 [INFO] Reloading
2018/04/29 01:09:02 [INFO] plugin/reload: Running configuration MD5 = **_eaa78891e80640df4601ea455f117a30_**
2018/04/29 01:09:02 [INFO] Reloading complete
2018/04/29 01:09:19 [INFO] **SIGUSR1: Reloading**
2018/04/29 01:09:19 [INFO] Reloading
2018/04/29 01:09:19 [INFO] plugin/reload: Running configuration MD5 = **_eaa78891e80640df4601ea455f117a30_**
2018/04/29 01:09:19 [INFO] Reloading complete
2018/04/29 01:09:44 [INFO] Reloading
2018/04/29 01:09:44 [INFO] plugin/reload: Running configuration MD5 = **_00e4b42de34fc164e65a85a306e0a347_**
2018/04/29 01:09:44 [INFO] Reloading complete
2018/04/29 01:09:56 [INFO] Reloading
2018/04/29 01:09:56 [ERROR] plugin/reload: Corefile changed but reload failed: file tcp [::]:53: fcntl: bad file descriptor
2018/04/29 01:10:07 [INFO] Reloading
2018/04/29 01:10:07 [ERROR] plugin/reload: Corefile changed but reload failed: file tcp [::]:53: fcntl: bad file descriptor
2018/04/29 01:10:09 [INFO] Reloading
2018/04/29 01:10:09 [ERROR] plugin/reload: Corefile changed but reload failed: file tcp [::]:53: fcntl: bad file descriptor
2018/04/29 01:11:07 [INFO] **SIGUSR1: Reloading**
2018/04/29 01:11:07 [INFO] Reloading
2018/04/29 01:11:07 [INFO] plugin/reload: Running configuration MD5 = _**00e4b42de34fc164e65a85a306e0a347**_
2018/04/29 01:11:07 [INFO] Reloading complete
2018/04/29 01:11:24 [INFO] **SIGUSR1: Reloading**
2018/04/29 01:11:24 [INFO] Reloading
2018/04/29 01:11:24 [INFO] plugin/reload: Running configuration MD5 = **_00e4b42de34fc164e65a85a306e0a347_**
2018/04/29 01:11:24 [INFO] Reloading complete
2018/04/29 01:12:11 [INFO] Reloading
2018/04/29 01:12:11 [ERROR] plugin/reload: Corefile changed but reload failed: file tcp [::]:53: fcntl: bad file descriptor
2018/04/29 01:12:13 [INFO] Reloading
2018/04/29 01:12:13 [ERROR] plugin/reload: Corefile changed but reload failed: file tcp [::]:53: fcntl: bad file descriptor
2018/04/29 01:12:16 [INFO] Reloading
2018/04/29 01:12:16 [ERROR] plugin/reload: Corefile changed but reload failed: file tcp [::]:53: fcntl: bad file descriptor
2018/04/29 01:12:20 [INFO] Reloading
2018/04/29 01:12:20 [INFO] plugin/reload: Running configuration MD5 = **_4703d8c78979d990eaa1dd1c35a0c650_**
2018/04/29 01:12:20 [INFO] Reloading complete

The MD5 is not changed after changed the ConfigMap, so coreDNS did not reload the ConfigMap.
but when Reload plugin reloading , it worked.

another question is when using SIGUSR1 and Reload plugin together, there ars some errors in the logs

**Comment by iandk** [comment]
Same problem, the reload plugin doesn't reload after config changes.

**Comment by fturib** [comment]
For what I can experience, there is a long delay between the edit/save of configMap (k8s object) and the update of "Corefile" (the configuration of coredns) in the CoreDNS pod. 
It takes between 30 sec to 2 mn to propagate the change from ConfigMap to Corefile.

I am wondering, if you just trigger SIGUSR1 signal too early.

Because anyway the propagation of the change of ConfigMap is slow, I would advise to not use the SIGUSR1 in same time as reload. but maybe have a reload triggered more often:

```
.:53 {
  xxxx
  reload 10s
}
```

Using SIGUSR1 with "reload' should not hurt, but the log looks awkward, because "reload" is listening any creation of new instance and log anyway the MD5 of the core file of that instance. 
So you get the MD5 information from reload, but the restart operation itself is done and logges by SIGUSR1 mechanism.

**Comment by chrisohaver** [comment]
> there is a long delay between the edit/save of configMap (k8s object) and the update of "Corefile" 

Yes, it can take some time for pods to see updated updated configmap files.  This is a Kubernetes delay.  It's a factor of the kubelet sync time which is 1 minute by default) and the configmap cache time, which is (i think) also 1 minute by default. Hence the variable delay up to 2 minutes.
If you send a reload signal to the pod before this sync occurs, coredns will just reload the old config.

**Comment by yybear** [comment]
> It takes between 30 sec to 2 mn to propagate the change from ConfigMap to Corefile.


but it's weird, in my case I set reload interval to 5s, every time after I changed the Corefile, the Reload plugin would get a different MD5 of the Corefile and do the right things.

**Comment by fturib** [comment]
@yybear : are you saying "every time after I changed the Corefile" - what do you mean ?
- you edit the Configmap in k8s, and 5s later it is already in the Corefile file on CoreDNS pod
- or : you edit the Corefile directly - I mean the file on the CoreDNS pod ?

**Comment by yybear** [comment]
@fturib I edit the Configmap in k8s, and I test again, you are right, it would spend some time to get a different MD5 of the Corefile.

2018/05/04 06:09:56 [INFO] Reloading
2018/05/04 06:09:56 [INFO] plugin/reload: Running configuration MD5 = 109b60e2cdb26c982b894055ee3d1112
2018/05/04 06:09:56 [INFO] Reloading complete



2018/05/04 06:11:11 [INFO] Reloading
2018/05/04 06:11:11 [INFO] plugin/reload: Running configuration MD5 = 089e9449f01b86991e480758dc05afaa
2018/05/04 06:11:11 [INFO] Reloading complete


2018/05/04 06:12:21 [INFO] Reloading
2018/05/04 06:12:21 [INFO] plugin/reload: Running configuration MD5 = e073fc180912b657a71d30edb434c7e9
2018/05/04 06:12:21 [INFO] Reloading complete


2018/05/04 06:14:48 [INFO] Reloading
2018/05/04 06:14:48 [INFO] plugin/reload: Running configuration MD5 = 041b81642c94be265bb0fdf9394ba2d4
2018/05/04 06:14:48 [INFO] Reloading complete

**Comment by iandk** [comment]
At least in my case I dont use K8 and edit the zone file directly, but it doesn't get updated, even after a few minutes.

**Comment by chrisohaver** [comment]
@iandk, use the `auto` plugin instead of the `file` plugin to automatically reload changes to a zone file. The `reload` plugin is for reloading changes to the Corefile.

**Comment by iandk** [comment]
Currently my Corefile looks like this, what do I have to change in order to be able to use automatic reloads?
```
my.domain {
file db.my.domainlog
errors
}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] v1.1.2 SIGUSR..." ]
>Currently my Corefile looks like this, what do I have to change in order to be able to use automatic reloads?
>```
>my.domain {
>file db.my.domainlog
>errors
>}
>```

add `reload` to the plugins

**Comment by iandk** [comment]
Didn't work unfortunately

**Comment by chrisohaver** [comment]
@iandk,  In an earlier comment, you wrote that you were making changes to your _zone file_ ...  So just to be clear...

for automatic reloads of the _Corefile_ use the `reload` plugin.
for automatic reloads of the _zone file_ use the `auto` plugin.

for example, doing both ...
```
my.domain {
   reload
   auto . path/to/zone/file/directory
   errors
}
```

[edited: fixed `auto` syntax above example, per comments below.  this example is untested]

**Comment by iandk** [comment]
Thank you for your answer, my config looks exactly like this, but unfortunately names won't get resolved anymore.

The log shows the following:
```
[2a01:xxx:xxx:2c0e::8]:44090 - [10/May/2018:14:30:33 +0000] 31493 "A IN www.xxxxx.xx. udp 42 false 4096" SERVFAIL qr,rd 42 57.688µs
10/May/2018:14:30:33 +0000 [ERROR 0 www.xxxx.xx. A] plugin/auto: no next plugin found
```

My Corefile:
```
. {
    reload 10s
    erratic
}
carve.pw {
reload
auto db.carve.pw
log
errors
}
```

**Comment by johnbelamaric** [comment]
`auto` syntax is:


auto [ZONES...] {
    directory DIR [REGEXP ORIGIN_TEMPLATE [TIMEOUT]]
    no_reload
    upstream [ADDRESS...]
}



So right now it is just serving db.carve.pw<http://db.carve.pw>. Looks like `file` and `auto` have different config.



On May 10, 2018, at 10:33 AM, Ian <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your answer, my config looks exactly like this, but unfortunately names won't get resolved anymore.

The log shows the following:

[2a01:xxx:xxx:2c0e::8]:44090 - [10/May/2018:14:30:33 +0000] 31493 "A IN www.xxxxx.xx<http://www.xxxxx.xx>. udp 42 false 4096" SERVFAIL qr,rd 42 57.688µs
10/May/2018:14:30:33 +0000 [ERROR 0 www.xxxx.xx<http://www.xxxx.xx>. A] plugin/auto: no next plugin found


My Corefile:

. {
    reload 10s
    erratic
}
carve.pw<http://carve.pw> {
reload
auto db.carve.pw<http://db.carve.pw>
log
errors
}

**Comment by fturib** [comment]
@yybear : is this still an issue ?

**Comment by miekg** [comment]
closing
