### ISSUE TITLE
go/src/github.com/coredns/coredns/pb/dns.pb.go:113: cannot use handler (type func("context".Context, interface {})

### ISSUE THREAD

**Issue by balupton** [coredns/coredns#1756]
`go install -v github.com/cloudflare/cloudflared/cmd/cloudflared` with result:

```
github.com/coredns/coredns/pb
github.com/mholt/caddy
# github.com/coredns/coredns/pb
go/src/github.com/coredns/coredns/pb/dns.pb.go:113: cannot use handler (type func("context".Context, interface {}) (interface {}, error)) as type grpc.UnaryHandler in argument to interceptor
go/src/github.com/coredns/coredns/pb/dns.pb.go:122: cannot use _DnsService_Query_Handler (type func(interface {}, "context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value
# github.com/mholt/caddy
go/src/github.com/mholt/caddy/plugins.go:42: undefined: sync.Map
go/src/github.com/mholt/caddy/plugins.go:275: undefined: sync.Map
go/src/github.com/mholt/caddy/plugins.go:276: undefined: sync.Map
go/src/github.com/mholt/caddy/plugins.go:293: undefined: sync.Map
```

`uname -a` is

```
Linux par1_origin_0 4.14.33-mainline-rev1 #1 SMP Sun Apr 8 12:40:59 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```

`go version` is

```
go version go1.8.3 linux/arm64
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] go/src/github.com..." ]
>`go install -v github.com/cloudflare/cloudflared/cmd/cloudflared` with result:
>
>github.com/coredns/coredns/pb
>github.com/mholt/caddy
># github.com/coredns/coredns/pb
>go/src/github.com/coredns/coredns/pb/dns.pb.go:113: cannot use handler (type func("context".Context, interface {}) (interface {}, error)) as type grpc.UnaryHandler in argument to interceptor
>go/src/github.com/coredns/coredns/pb/dns.pb.go:122: cannot use _DnsService_Query_Handler (type func(interface {}, "context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

We forcefully moved everything over to "context", so this is probably biting 
you?

>go/src/github.com/mholt/caddy/plugins.go:42: undefined: sync.Map
>go/src/github.com/mholt/caddy/plugins.go:275: undefined: sync.Map

you Go install is too old, it seems.

/Miek

--
Miek Gieben

**Comment by balupton** [comment]
Thanks. Upgrading go to 1.10.1 has made cloudflared return a different error, so I guess the issue lays over there.

https://github.com/cloudflare/cloudflared/issues/22#issuecomment-385231340
