### ISSUE TITLE
High CPU usage compared to dnsmasq

### ISSUE THREAD

**Issue by hanikesn** [coredns/coredns#1757]
We're running coredns 1.1.2 in our Kubernetes clusters and Coredns uses about 10x CPU resources compared to kube-dns:

![bildschirmfoto von 2018-04-30 14-46-15](https://user-images.githubusercontent.com/630711/39427763-45c37822-4c85-11e8-98b7-8821a5e5429e.png)

The high spikes are our application loadtests were reach about 13k reqs/s. Usually we have 1.5 to 3k req/s distributed between 4 pods. With a cache hit ratio of >99.5% and about 15 upstream req/s.

This is our configuration:
```
    .:53 {
        errors
        health
        kubernetes cluster.io in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }
```

**Comment by miekg** [comment]
Is it possible to pprof this? You can just add the pprof plugin to your
config

**Comment by hanikesn** [comment]
Sure, I just ran `go tool pprof http://localhost:6053/debug/pprof/profile`. Though it looks like this new instances uses less CPU than the old ones. I will upload another profile later.  Tell me if you need anything more specific:
[pprof.coredns.samples.cpu.001.pb.gz](https://github.com/coredns/coredns/files/1960717/pprof.coredns.samples.cpu.001.pb.gz)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] High CPU usag..." ]
>Sure, I just ran `go tool pprof http://localhost:6053/debug/pprof/profile`. Though it looks like this new instances uses less CPU than the old ones. I will upload another profile later.  Tell me if you need anything more specific:
>[pprof.coredns.samples.cpu.001.pb.gz](https://github.com/coredns/coredns/files/1960717/pprof.coredns.samples.cpu.001.pb.gz)

% go tool pprof pprof.coredns.samples.cpu.001.pb.gz
File: coredns
Type: cpu
Time: Apr 30, 2018 at 1:30pm (UTC)
Duration: 30s, Total samples = 470ms ( 1.57%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top 10
Showing nodes accounting for 270ms, 57.45% of 470ms total
Showing top 10 nodes out of 151
      flat  flat%   sum%        cum   cum%
      60ms 12.77% 12.77%       60ms 12.77%  runtime.futex
      60ms 12.77% 25.53%       60ms 12.77%  syscall.Syscall
      30ms  6.38% 31.91%       30ms  6.38%  runtime.epollwait
      20ms  4.26% 36.17%       20ms  4.26%  runtime.casgstatus
      20ms  4.26% 40.43%       20ms  4.26%  runtime.heapBitsSetType
      20ms  4.26% 44.68%       60ms 12.77%  runtime.newproc1
      20ms  4.26% 48.94%       20ms  4.26%  runtime.usleep
      20ms  4.26% 53.19%       20ms  4.26%  sync.(*RWMutex).RLock
      10ms  2.13% 55.32%       20ms  4.26%  github.com/miekg/dns.packDomainName
      10ms  2.13% 57.45%       10ms  2.13%  github.com/miekg/dns.sprintName


syscall.Syscall is the opening of new udp sockets, using the *forward* plugin 
instead of *proxy* may help.

The RLock on the mutex can from the cache (I think - need to double check).
For each shard in the cache we take that mutex. It could be the monitoring that
takes the Len() of the cache... While pondering this, might make sense to rip 
this out...

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
FYI @miekg, I'm in the process of running k8s perf-tests on CoreDNS vs kube-dns... I plan to compare `proxy` vs `forward` in CoreDNS while I'm at it.

**Comment by miekg** [comment]
https://github.com/uber/go-torch is helpful to make a flame graph of this. https://github.com/coredns/coredns/pull/1760 should help here. I can't shave stuff of the syscall.Syscall business because that's how we write to the udp socket.

There is probably room for some more optimization here.

**Comment by hanikesn** [comment]
So I rant torch twice for 30 seconds (wasn't able to change the default):
[coredns-torch.zip](https://github.com/coredns/coredns/files/1969869/coredns-torch.zip) (github doesn't allow svg uploads)
I'm at kubecon btw if you want to take a closer look in person.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] High CPU usag..." ]
>So I rant torch twice for 30 seconds (wasn't able to change the default):
>[coredns-torch.zip](https://github.com/coredns/coredns/files/1969869/coredns-torch.zip) (github doesn't allow svg uploads)
>I'm at kubecon btw if you want to take a closer look.

I am, ping on miek@miek.nl (or on twitter @miekg)

**Comment by hanikesn** [comment]
So this is a more detailed flamegraph.
[coredns-torch-300.zip](https://github.com/coredns/coredns/files/1970984/coredns-torch-300.zip)

**Comment by hanikesn** [comment]
Somehow https://github.com/golang/go/issues/18236 seems related.

**Comment by johnbelamaric** [comment]
@vasili-v did some past investigations into the performance differences between dnsdist and CoreDNS . It looked like when you got too many goroutines - too many requests in-flight - performance dropped; like the bookkeeping started to dominate the work. I wonder if https://github.com/miekg/dns/pull/664 will help here?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] High CPU usag..." ]
>@vasili-v did some past investigations into the performance differences between dnsdist and CoreDNS . It looked like when you got too many goroutines - too many requests in-flight - performance dropped; like the bookkeeping started to dominate the work. I wonder if https://github.com/miekg/dns/pull/664 will help here?

That would be a good data point. Is it possible to try this?

I.e. patch this in miekg/dns and 'go build'; deploy and profile?

**Comment by miekg** [comment]
There have been other optmizations in coredns as well,  miekg/dns#664 has been merged and is used when you build coredns.

**Comment by miekg** [comment]
There has been all whole bunch of optimization being flowing into miekg/dns and coredns but we will always use more cpu than kube-dns - this will be ongoing as we try to make things faster and better.
