### ISSUE TITLE
Plugin/Forward - ability to access the Proxy from external plugin

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1762]
### Enhancement

For an external plugin, we need to get access to functions of the FORWARD package that are currently private:

- forward.list() - list all the upstream connection defined 
- proxy.connect(...) - send a DNS msg to the upstream connection

I think it is safe to make this 2 function public.

@ekleiner is currently validating before sending a PR for this enhancement.

### Context

We developed an external plugin dedicated for our use case. It is monitoring the upstream connection of a PROXY plugin.
We would like to move that monitoring over an upstream connection of a FORWARD plugin.

our plugin is a kind of superset of the "health check", but we have very specific options tied to our use case 
- DNS query is kind of dedicated
- We need to handle reporting and event when the connection if found down or not healthy.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Plugin/Forward - ..." ]
>### Enhancement
>
>For an external plugin, we need to get access to functions of the FORWARD package that are currently private:
>
>- forward.list() - list all the upstream connection defined
>- proxy.connect(...) - send a DNS msg to the upstream connection
>
>I think it is safe to make this 2 function public.
>
>@ekleiner is currently validating before sending a PR for this enhancement.

OK, sgtm
