### ISSUE TITLE
Signal handling breaks parent code

### ISSUE THREAD

**Issue by sssilver** [coredns/coredns#1763]
Hi,

cloudflared imports github.com/coredns/coredns, which imports github.com/mholt/caddy.

It looks like coredns calls `TrapSignals()`, which installs its own signal handler for SIGTERM/SIGINT/etc, and since in UNIX/Linux there can only be one handler per process for these signals, that causes our own handlers in cloudflared to not get triggered.

The signal handler stuff in caddy makes sense for situations when it's being ran as a server, however when it's being used as a lib, it should probably be more mindful of what the parent code may choose to do with its own signal handlers.

For now, we have just commented out `trapSignalsCrossPlatform()` and some handlers in `trapSignalsPosix()` in the caddy package that we actually wanna handle in our own codebase. However, this is not a long-term solution. Ideally, we would be able to just pull coreDNS (and its transitive dependency caddy) from the origin and use it without having this issue.

Would it be possible to stop trapping signals in coredns?

Many thanks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Signal handling b..." ]
>Hi,
>
>cloudflared imports github.com/coredns/coredns, which imports github.com/mholt/caddy.
>
>It looks like coredns calls `TrapSignals()`, which installs its own signal handler for SIGTERM/SIGINT/etc, and since in UNIX/Linux there can only be one handler per process for these signals, that causes our own handlers in cloudflared to not get triggered.
>
>The signal handler stuff in caddy makes sense for situations when it's being ran as a server, however when it's being used as a lib, it should probably be more mindful of what the parent code may choose to do with its own signal handlers.
>
>For now, we have just commented out `trapSignalsCrossPlatform()` and some handlers in `trapSignalsPosix()` in the caddy package that we actually wanna handle in our own codebase. However, this is not a long-term solution. Ideally, we would be able to just pull coreDNS (and its transitive dependency caddy) from the origin and use it without having this issue.
>
>Would it be possible to stop trapping signals in coredns?

If you use CoreDNS as library it shouldn't set TrapSignals() as this is only 
done in coremain/run.go

Ah it seems we're picking this up in the metrics package (and we shouldn't)

plugin/metrics/setup.go:	"github.com/coredns/coredns/coremain"
plugin/metrics/setup.go:	buildInfo.WithLabelValues(coremain.CoreVersion, coremain.GitCommit, runtime.Version()).Set(1)
plugin/chaos/setup.go:	// Set here so we pick up AppName and AppVersion that get set in coremain's init().

**Comment by sssilver** [comment]
Should we fix this and submit a PR?

**Comment by miekg** [comment]
Yes, but the metric is still useful, so please try to keep it.

**Comment by sssilver** [comment]
Quick question -- why are so many of the dependencies (including Caddy) listed in the `ignored` section of Gopkg.toml?

**Comment by miekg** [comment]
Build breaks if we do that. Hope vgo will fix all that

**Comment by sssilver** [comment]
Would you be happy if we moved `caddy.TrapSignals()` from `init()` to `Run()` in `coremain/run.go`?

**Comment by miekg** [comment]
Oh yeah that would work

**Comment by sssilver** [comment]
https://github.com/coredns/coredns/pull/1764 is ready for review.
