### ISSUE TITLE
docker: run as non-root

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1767]
Can't find the original issue anymore (think we had one on this). But after seeing Liz's keynote this morning at kubecon we should def. run as non-root for CoreDNS in the Docker container.

Couple a things:
1: https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L48 uses port 53 explicitly, meaning dns.port=xxxx won't work
2. binding on a higher port and then redirecting port 53 to this higher port can't be done in the Dockerfile?
3. If 2 is true, then this is a backwards incompatible change.

**Comment by miekg** [comment]
we should probably also move away from alpine w/ busybox and just use Debian

**Comment by m4r10k** [comment]
@miekg Inside the Dockerfile you can only specify the service port itself, not the port mapping. If you run an image with `docker run -P ....` then the metadata of the image will be used to find the service port and map a dynamic port to it eg `32768:53`. If you want to use a defined node port, you have to use a explicit port mapping with `docker run -p 3333:53` or in this case `docker run -p 53:<serviceport>`.

So yes, this might break something. But we might be able to allow a defined user to start a process on an privileged port. And I would not go away from Alpine, as it is small and does not contain loads of stuff. I have tested the following:
```
/ # chown nobody:nobody /coredns
/ # chown nobody:nobody /Corefile
/ # su - nobody
3cc35cfeb289:~$ ./coredns
2018/05/15 08:16:35 listen tcp :53: bind: permission denied
3cc35cfeb289:~$ exit

/ # apk add libcap
(1/1) Installing libcap (2.25-r1)
Executing busybox-1.27.2-r7.trigger
OK: 16 MiB in 21 packages

/ # setcap CAP_NET_BIND_SERVICE=+eip /coredns
/ # su - nobody
3cc35cfeb289:~$ ./coredns
.:53
2018/05/15 08:17:46 [INFO] CoreDNS-1.1.2
2018/05/15 08:17:46 [INFO] linux/amd64, go1.10.1, 582f91f3
CoreDNS-1.1.2
linux/amd64, go1.10.1, 582f91f3
^C2018/05/15 08:17:48 [INFO] SIGINT: Shutting down

```
Therefore, we could add the libcap in the Dockerfile and run the chmods and setcap commands. Afterwards we can start the coredns as normal, unprivileged (beside the low port usage) user, without changing the default port. :smile: 
```
3cc35cfeb289:~$ ps -ef
PID   USER     TIME   COMMAND
    1 root       0:00 ash
   65 nobody     0:00 -ash
   94 nobody     0:00 ./coredns
  108 nobody     0:00 ps -ef
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] docker: run a..." ]
>@miekg Inside the Dockerfile you can only specify the service port itself, not the port mapping. If you run an image with `docker run -P ....` then the metadata of the image will be used to find the service port and map a dynamic port to it eg `32768:53`. If you want to use a defined node port, you have to use a explicit port mapping with `docker run -p 3333:53` or in this case `docker run -p 53:<serviceport>`.

Indeed, so this is a breaking change for every one relying on the current impl 
:-(

/Miek

--
Miek Gieben

**Comment by m4r10k** [comment]
@miekg Yes, but no. I've found a way to stay on the privileged port but to use an unprivileged user for the process. That works as given in the PR. It is a compromise to not change the default port 53 but to have a unprivileged user running the process without root permissions. But it requires `libpcap` with `setcap CAP_NET_BIND_SERVICE=+eip /coredns`

**Comment by nberlee** [comment]
Adding securityContext in the `coredns` pod section of the deployment works for me. It drops all privileges except for `CAP_NET_BIND_SERVICE` and set the container in read-only mode. It does not seem to break anything for me.
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - net_bind_service
            drop:
            - all
          readOnlyRootFilesystem: true
```

**Comment by dR3b** [comment]
@miekg 
```
we should probably also move away from alpine w/ busybox and just use Debian
```
Why not using docker scratch?

https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

**Comment by m4r10k** [comment]
@dR3b @miekg I would suggest this way (`FROM scratch`) also. The less software is in the container which is not needed by the service itself the better.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] docker: run a..." ]
>@miekg
>```
>we should probably also move away from alpine w/ busybox and just use Debian
>```
>Why not using docker scratch?
>
>https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

How do we copy up to date certs in this image? I.e. the debian equivalent of
apt-get install ca-certificates

**Comment by stp-ip** [comment]
Something along the lines of `COPY /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/` where the certs are coming from a build container or are requested during the build.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] docker: run a..." ]
>Something along the lines of `COPY /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/` where the certs are coming from a build container or are requested during the build.

that can work

**Comment by dR3b** [comment]
```
FROM scratch
ADD ca-certificates.crt /etc/ssl/certs/
ADD coredns /
EXPOSE 53 53/udp
CMD ["/coredns"]
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] docker: run a..." ]
>```
>FROM scratch
>ADD ca-certificates.crt /etc/ssl/certs/
>ADD coredns /
>CMD ["/coredns"]
>```

indeed, a full Dockerfile would then become:

~~~
FROM debian:stable-slim

RUN apt-get update && apt-get -uy upgrade
RUN apt-get -y install ca-certificates && update-ca-certificates

FROM scratch

COPY --from=0 /etc/ca-certificates /etc/ca-certificates
COPY --from=0 /etc/ssl /etc/ssl
ADD coredns /coredns

EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]
~~~

This starts, but I haven't double checked it the certs are found and used. Image 
size is 33MB which is roughly only the coredns binary.


/Miek

--
Miek Gieben

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/1843

**Comment by dR3b** [comment]
And a little smaller:
```
FROM alpine as alpine
RUN apk add -U --no-cache ca-certificates

FROM scratch
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD coredns /coredns

EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] docker: run a..." ]
>```
>FROM alpine as alpine
>RUN apk add -U --no-cache ca-certificates
>
>FROM scratch
>COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
>
>ADD coredns /coredns
>
>EXPOSE 53 53/udp
>ENTRYPOINT ["/coredns"]
>```


I want to drop alpine as well

**Comment by m4r10k** [comment]
>I want to drop alpine as well

Why? After the Docker build the result is a scratch image with some certificate files, a coredns binary and a config. Or are you thinking about the actuality of the certificates of the Alpine distribution?

**Comment by m4r10k** [comment]
Or are you thinking about `musl` during the coredns build itself? Because it is compiled to run with Alpine?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] docker: run a..." ]
>>I want to drop alpine as well
>
>Why? After the Docker build the result is a scratch image with some certificate files, a coredns binary and a config. Or are you thinking about the actuality of the certificates of the Alpine distribution?

musl and busybox concerns. With a builder image this doesn't matter too much and 
as such I rather move to a mainstream Linux distro that I know.

**Comment by m4r10k** [comment]
> musl and busybox concerns. With a builder image this doesn't matter too much and
as such I rather move to a mainstream Linux distro that I know.

👍 Then coredns should go on with Debian  `stable-slim` I guess.

**Comment by paba19** [comment]
Hello, thanks for your work.

After the multi stage build change I don't see libpcap and setcap in the image any longer. Therefore I don't seem to be able to run it as non root user - despite the fact I've set NET_BIND_SERVICE in my manifest.

Any plan to add back in libpcap and setcap?

Thanks a lot!

**Comment by miekg** [comment]
No we don't plan to add those back.
