### ISSUE TITLE
Use bot for coredns

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1779]
I forked Derek and wrote Dreck: https://github.com/miekg/dreck that can help with PRs and issues. It's a bit underdocumented, but it can run as a caddy plugin and I'll set up `dreck.miek.nl` for it to serve off.

allows you to do things (if you're in the top-level OWNERS) file:

~~~
/assign: user
~~~
to assign to a user and multiple other things - this stuff also works from email.

I'm pondering to add auto-assign to assign reviewers on PRs based on the OWNERS file, but that isn't implemented yet.

**Comment by stp-ip** [comment]
For ideas: https://github.com/kubernetes/test-infra/tree/master/prow

**Comment by miekg** [comment]
I've reworked Dreck a bit and installed it as CorBot on the CoreDNS organisation.

I'll enable it, but updating the top-level OWNERS file

**Comment by miekg** [comment]
This is live now.
