### ISSUE TITLE
middleware/firewall

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#178]
Make a middleware that allows to filter address (or on anything basically). This should make it easy to allow some IPs to recurse and block others for instance.

**Comment by miekg** [comment]
https://github.com/CZ-NIC/knot-resolver/wiki/HTTP-2-interface-&-DNS-firewall#dns-firewall

rename this middleware to _firewall_?

**Comment by stp-ip** [comment]
Would help with hidden/stealth master/primary setups.
Currently I am using an external firewall to blacklist every request except for the AXFR/IXFR transfer IPs.

If one could add that to coredns itself, it would simplify our current setup.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/fire..." ]

> Would help with hidden/stealth master/primary setups.
> Currently I am using an external firewall to blacklist every request except for the AXFR/IXFR transfer IPs.
> 
> If one could add that to coredns itself, it would simplify our current setup.

Yes, that would be the plan. First we need to invent some kind of firewall
language - or better yet - steal a good one from other servers.

**Comment by stp-ip** [comment]
Preliminary suggestion:

```
firewall [ZONES... ] {
    block/forbid [IP or IP range]
    block/forbid [IP or IP range]
    allow [IP or IP range]
    allow [IP or IP range]
}
```

Per zone firewall.
If only block is used everything else is allowed by default.
If only allow is used everything else is blocked by default.
If both are used everything is blocked by default and allow whitelists as usual. <- another option would be to disallow both as block then doesn't really make sense anyway.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/fire..." ]

> Preliminary suggestion:
> 
> ```
> firewall [ZONES... ] {
>    block/forbid [IP or IP range]
>    block/forbid [IP or IP range]
>    allow [IP or IP range]
>    allow [IP or IP range]
> }
> ```
> 
> Per zone firewall.
> If only block is used everything else is allowed by default.
> If only allow is used everything else is blocked by default.
> If both are used everything is blocked by default and allow whitelists as usual. <- another option would be to disallow both as block then doesn't really make sense anyway.

Thanks for the suggestion, something like this looks sane. Still want to see
some prior art on other impl (if possible).

Also if we're doing ranges and ACLing we should look at the AXFR/transfer stuff
as _or_ make a decision this happens in the firewall layer - we needs TSIG stuff
here as well, me thinks

/Miek

## 

Miek Gieben

**Comment by yongtang** [comment]
How about RPZ in bind9?
https://dnsrpz.info

**Comment by stp-ip** [comment]
Talking about AXFR etc. it might lead to the firewall supporting the allowed/blocked types. Aka, but not sure, if that is actually needed.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/fire..." ]

> How about RPZ in bind9?
> https://dnsrpz.info

Ack. I was also considering local ACL-ing to be fw issue. Maybe that requires
another middleware. Anyway nice things to think about after k8s is fixed and
current middleware stabilizes :-)

**Comment by SuperQ** [comment]
It would be nice to re-open this so we could allow public-facing servers that handle zones, and also recursion for local users.  For example:

```
example.org {
  file ...
}
. {
  firewall {
    allow 10.0.0.0/8
    deny all
  }
  proxy
}
```

**Comment by fturib** [comment]
Looks like this talk is continuing on #1337
