### ISSUE TITLE
java.net.UnknownHostException with rewrite name

### ISSUE THREAD

**Issue by august0715** [coredns/coredns#1788]
I meet java.net.UnknownHostException when I use coreDns rewrite plugin in kubernetes.

coreDns config:

```
.:53 {
 errors
 log stdout
 health
 kubernetes cluster.local 20.0.0.0/16
 rewrite name kms.services.dev.ofc kms.default.svc.cluster.local
 proxy . /etc/resolv.conf
 cache 60
 }
```

java error stack
```
^V^ [ERROR] [2018-05-09 16:06:09.478] [test_0] [com.ciicgat.sdk.lang.controller.Controller:42]  kms.services.dev.ofc
java.net.UnknownHostException: kms.services.dev.ofc: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.ciicgat.sdk.lang.controller.Controller$1.run(Controller.java:37)
	at java.lang.Thread.run(Thread.java:748)
^V^ [ERROR] [2018-05-09 16:06:14.479] [test_0] [com.ciicgat.sdk.lang.controller.Controller:42]  kms.services.dev.ofc
java.net.UnknownHostException: kms.services.dev.ofc
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.ciicgat.sdk.lang.controller.Controller$1.run(Controller.java:37)
	at java.lang.Thread.run(Thread.java:748)
^V^ [ERROR] [2018-05-09 16:06:19.483] [test_0] [com.ciicgat.sdk.lang.controller.Controller:42]  kms.services.dev.ofc
java.net.UnknownHostException: kms.services.dev.ofc: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.ciicgat.sdk.lang.controller.Controller$1.run(Controller.java:37)
	at java.lang.Thread.run(Thread.java:748)
^V^ [ERROR] [2018-05-09 16:06:24.483] [test_0] [com.ciicgat.sdk.lang.controller.Controller:42]  kms.services.dev.ofc
java.net.UnknownHostException: kms.services.dev.ofc
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.ciicgat.sdk.lang.controller.Controller$1.run(Controller.java:37)
	at java.lang.Thread.run(Thread.java:748)
```

Pod's `/etc/resolv.conf` content is
```
[root@for-test-jar-fd574ffdd-2dj6h apache-tomcat]# cat /etc/resolv.conf 
nameserver 20.0.0.11
search default.svc.cluster.local. svc.cluster.local. cluster.local.
options ndots:5
```

Pod's `/etc/hosts` content is
```
[root@for-test-jar-fd574ffdd-2dj6h apache-tomcat]# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
1.0.7.90	for-test-jar-fd574ffdd-2dj6h
```

**But it's strange that when I use `nslookup` or `dig` or `curl` ,there's no error!**
```
[root@for-test-jar-fd574ffdd-2dj6h apache-tomcat]# nslookup kms.services.dev.ofc
Server:		20.0.0.11
Address:	20.0.0.11#53

Name:	kms.default.svc.cluster.local
Address: 20.0.125.17
```
```
[root@for-test-jar-fd574ffdd-2dj6h apache-tomcat]# dig kms.services.dev.ofc

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> kms.services.dev.ofc
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30450
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kms.services.dev.ofc.		IN	A

;; ANSWER SECTION:
kms.default.svc.cluster.local. 3 IN	A	20.0.125.17

;; Query time: 1 msec
;; SERVER: 20.0.0.11#53(20.0.0.11)
;; WHEN: Wed May 09 16:11:07 CST 2018
;; MSG SIZE  rcvd: 94
```

```
[root@for-test-jar-fd574ffdd-2dj6h apache-tomcat]# curl kms.services.dev.ofc/isLive -v
* About to connect() to kms.services.dev.ofc port 80 (#0)
*   Trying 20.0.125.17...
* Connected to kms.services.dev.ofc (20.0.125.17) port 80 (#0)
> GET /isLive HTTP/1.1
> User-Agent: curl/7.29.0
> Host: kms.services.dev.ofc
> Accept: */*
> 
< HTTP/1.1 200 
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 09 May 2018 08:11:33 GMT
< 
* Connection #0 to host kms.services.dev.ofc left intact
```

**Just the Java application cannot work!**

coreDns version:1.1.2
k8s version:1.10

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] java.net.UnknownH..." ]
>[root@for-test-jar-fd574ffdd-2dj6h apache-tomcat]# dig kms.services.dev.ofc
>
>; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> kms.services.dev.ofc
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30450
>;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
>
>;; OPT PSEUDOSECTION:
>; EDNS: version: 0, flags:; udp: 4096
>;; QUESTION SECTION:
>;kms.services.dev.ofc.		IN	A
>
>;; ANSWER SECTION:
>kms.default.svc.cluster.local. 3 IN	A	20.0.125.17
>
>;; Query time: 1 msec
>;; SERVER: 20.0.0.11#53(20.0.0.11)
>;; WHEN: Wed May 09 16:11:07 CST 2018
>;; MSG SIZE  rcvd: 94
>```

This is most likely because Java sees the answer not being in the same domain as 
dev.ofc and assumes "a bad thing" is happening and calls NXDOMAIN.

A fix would be to CNAME the name:

kms.services.dev.ofc.		IN	CNAME   kms.default.svc.cluster.local.
kms.default.svc.cluster.local. 3 IN	A	20.0.125.17

Thought we did that some where in rewrite though.

**Comment by chrisohaver** [comment]
If it’s the answer != question problem, then response rewrite should work. It an option in the rewrite plugin that allows you to rewrite the question in the response, so it matches the original question. We didn’t do the cname fix in rewrite (it’s in autopath, which I don’t think we can apply in this use case). The response rewrite docs are kinda hidden further down in the rewrite readme.

On May 9, 2018, at 5:26 AM, Miek Gieben <notifications@github.com<mailto:notifications@github.com>> wrote:

[ Quoting <notifications@github.com<mailto:notifications@github.com>> in "[coredns/coredns] java.net.UnknownH..." ]
>[root@for-test-jar-fd574ffdd-2dj6h apache-tomcat]# dig kms.services.dev.ofc
>
>; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> kms.services.dev.ofc
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30450
>;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
>
>;; OPT PSEUDOSECTION:
>; EDNS: version: 0, flags:; udp: 4096
>;; QUESTION SECTION:
>;kms.services.dev.ofc. IN A
>
>;; ANSWER SECTION:
>kms.default.svc.cluster.local. 3 IN A 20.0.125.17
>
>;; Query time: 1 msec
>;; SERVER: 20.0.0.11#53(20.0.0.11)
>;; WHEN: Wed May 09 16:11:07 CST 2018
>;; MSG SIZE rcvd: 94
>```

This is most likely because Java sees the answer not being in the same domain as
dev.ofc and assumes "a bad thing" is happening and calls NXDOMAIN.

A fix would be to CNAME the name:

kms.services.dev.ofc. IN CNAME kms.default.svc.cluster.local.
kms.default.svc.cluster.local. 3 IN A 20.0.125.17

Thought we did that some where in rewrite though.

**Comment by august0715** [comment]
I try to CNAME  `kms.services.dev.ofc` to the k8s service name `kms.default.svc.cluster.local`, so I do not need to change the dns config in code when I migrate application to the k8s cluster, we have many apps.

**Comment by august0715** [comment]
@chrisohaver I actually know the rewrite plugin's purpose，but it cannot work well with Java, it is a bug. It's       simple to write an alias plugin use CNAME. Is there any plan?

**Comment by johnbelamaric** [comment]
You need to use the `answer` rewrite, too:

```
 rewrite {
   name regex kms.services.dev.ofc kms.default.svc.cluster.local
   answer name kms.default.svc.cluster.local  kms.services.dev.ofc
}
```

**Comment by chrisohaver** [comment]
@shadowpriest, did you try the _response_ rewrite?  (not just _request_ rewrite). It's not in your original example, so thats why I suggested it in my comment above.

Here are the docs: https://github.com/coredns/coredns/tree/master/plugin/rewrite#response-rewrites

Also, see John's example above.

**Comment by august0715** [comment]
OK

**Comment by sandrom** [comment]
actually I have the same issue even *though* I have the answer section:

```
20:11:41,097 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-48) Failed to make identity provider oauth callback: java.net.UnknownHostException: api.minikube.oltd.de: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
```

rule:
```
rewrite name regex api.minikube.oltd.de gw-nginx-ingress-controller.osramid.svc.cluster.local answer name gw-nginx-ingress-controller.osramid.svc.cluster.local api.minikube.oltd.de
```

dig:
```
dnstools# dig https://api.minikube.oltd.de

; <<>> DiG 9.11.3 <<>> https://api.minikube.oltd.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39467
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 211a82771a5d9332 (echoed)
;; QUESTION SECTION:
;https://api.minikube.oltd.de.	IN	A

;; ANSWER SECTION:
api.minikube.oltd.de.	5	IN	A	10.107.94.27

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Thu Jul 26 20:10:36 UTC 2018
;; MSG SIZE  rcvd: 105
```

also curl from the same node works perfectly. just java sucks. Any Idea what else could be stalling there?

**Comment by chrisohaver** [comment]
Just a sanity check... `dig api.minikube.oltd.de` also works?

**Comment by sandrom** [comment]
@chrisohaver 
yes, i actually switched away from https in favor of http today trying to see if it makes a difference (it didn't :( )

```
dnstools# dig api.minikube.oltd.de

; <<>> DiG 9.11.3 <<>> api.minikube.oltd.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3306
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 6293977174e5ce81 (echoed)
;; QUESTION SECTION:
;api.minikube.oltd.de.		IN	A

;; ANSWER SECTION:
api.minikube.oltd.de.	5	IN	A	10.107.94.27

;; Query time: 1 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Jul 27 12:51:37 UTC 2018
;; MSG SIZE  rcvd: 97
```

it's really rather puzzling

**Comment by laurentcaille** [comment]
@sandrom can you try this ? 

```
rewrite {
    name regex (api\.minikube\.oltd\.de\.)$ gw-nginx-ingress-controller.osramid.svc.cluster.local 
    answer name gw-nginx-ingress-controller.osramid.svc.cluster.local api.minikube.oltd.de
}
```

with this regex, coredns will answer on api.minikube.oltd.de. only.

**Comment by dominicqi** [comment]
@sandrom  Have you solved the problem? I have the same problem. I found not all jdk docker image has this problem java:8u111 has this problem but java:8u111-jdk-alpine not.

**Comment by sandrom** [comment]
@dominicqi sadly not sufficiently as it seemed to pop up occasionally, but we basically retired our java services and got rid of the Problem this way. One way to solve it - worked as they were just temporary anyway :)

**Comment by dominicqi** [comment]
@sandrom it work for me. I wrote the wrong domain name

**Comment by jenciso** [comment]
In this comment, I found the solution to that problem https://github.com/coredns/coredns/issues/2347#issuecomment-442934925

**Comment by sobvan** [comment]
I also ran into this issue and solved it by replacing the base java image that I used. For me the config provided in the answer https://github.com/coredns/coredns/issues/1788#issuecomment-412098354 works with 
```
FROM adoptopenjdk/openjdk11:alpine-jre
```
as base image for my docker file.
