### ISSUE TITLE
plugin/ads: block ads

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#179]
See https://github.com/pi-hole/pi-hole

We could do something similar in CoreDNS.

**Comment by miekg** [comment]
Closing because nobody is working on it.

**Comment by pmoroney** [comment]
Also the hosts middleware can do this, since there are many hosts files available on the internet that are built for this purpose.

**Comment by spaddex** [comment]
For people ending up, might want to check out the plugin: [https://github.com/c-mueller/ads](https://github.com/c-mueller/ads)

**Comment by relvira** [comment]
@miekg I recently started using coredns and would like to contribute to the project. This is a feature that I would personally like to use, so please let me know if it still makes sense to build this as a plugin and I'll be happy to contribute.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ad..." ]
>@miekg I recently started using coredns and would like to contribute to the
>project. This is a feature that I would personally like to use, so please let
>me know if it still makes sense to build this as a plugin and I'll be happy to
>contribute.

yes, I think this make sense to add, there has been a lot of discussion on how to get the
block lists into coredns (as your use of DNS is limited), please make sure you read all
that.

/title plugin/ads: block ads

**Comment by relvira** [comment]
Can you point me to those discussions so I make sure to give them a read before I start thinking on how to do this?

Thank you!
