### ISSUE TITLE
SizeAndDo should not echo all options back when no EDNS was originally set in response.

### ISSUE THREAD

**Issue by chantra** [coredns/coredns#1797]
The current behaviour of [SizeAndDo](https://github.com/coredns/coredns/blob/0e5e59c327387472c60fb5f2f2c7d84a89b879c9/request/request.go#L138) is to copy the original dns.OPT into the response .

Assuming some code logic similar to:

```
	if o := r.IsEdns0(); o != nil && o.Version() != 0 {
		a := new(dns.Msg)
		a.SetRcode(r, dns.RcodeBadVers)
                state.SizeAndDo(resp)
		w.WriteMsg(a)
                return 0, nil
	}
```

Upon receiving a request with:
```
dig  +norec +noad +edns=1 +noednsneg +ednsopt=100 soa mydomain.com
```

dig shows that EDNS option is echoed back:
```
; <<>> DiG 9.10.5 <<>> +norec +noad +edns=1 +noednsneg +ednsopt=100 soa mydomain.com @::1 -p 1053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: BADVERS, id: 24844
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; OPT=100
;; QUESTION SECTION:
;mydomain.com.              IN      SOA

;; Query time: 41 msec
;; SERVER: ::1#1053(::1)
;; WHEN: Sun May 13 22:27:44 PDT 2018
;; MSG SIZE  rcvd: 49

```

The issue here is the `; OPT=100` bit.

It seems the correct behaviour when setting EDNS for the answer when EDNS was not yet present, would be to set it with 0 options. e.g something like:
```diff
	o.Hdr.Name = "."
	o.Hdr.Rrtype = dns.TypeOPT
	o.SetVersion(0)
	o.Hdr.Ttl &= 0xff00 // clear flags

	if odo {
		o.SetDo()
	}
-
+	o.Option = o.Option[:0]
	m.Extra = append(m.Extra, o)
	return true
```

**Comment by miekg** [comment]
Can you clarify:
>It seems the correct behaviour when setting EDNS for the answer when EDNS was not yet present, would be to set it with 0 options. e.g something like:

But in your example EDNS **is** present? Or do you mean specific options?

**Comment by chantra** [comment]
On Mon, May 14, 2018 at 11:42 PM Miek Gieben <notifications@github.com>
wrote:

> Can you clarify:
>
> It seems the correct behaviour when setting EDNS for the answer when EDNS
> was not yet present, would be to set it with 0 options. e.g something like:
>
> But in your example EDNS *is* present? Or do you mean specific options?
>

Sorry. I meant that EDNS was not *yet* present *in* the answer payload, so
we end up copying the original request EDNS payload verbatim into the
answer.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] SizeAndDo sho..." ]
>On Mon, May 14, 2018 at 11:42 PM Miek Gieben <notifications@github.com>
>wrote:
>
>> Can you clarify:
>>
>> It seems the correct behaviour when setting EDNS for the answer when EDNS
>> was not yet present, would be to set it with 0 options. e.g something like:
>>
>> But in your example EDNS *is* present? Or do you mean specific options?
>>
>
>Sorry. I meant that EDNS was not *yet* present *in* the answer payload, so
>we end up copying the original request EDNS payload verbatim into the
>answer.

IIRC there are indeed some rules subscribed in the RFCs about this. Do you have 
a direct ref to what should be purged. I took a shortcut here, because EDNS 
another one of those DNS gems

**Comment by chantra** [comment]
There is https://tools.ietf.org/html/rfc6891#section-6.1.2

```
Any OPTION-CODE values not understood by a responder or requestor
   MUST be ignored.  Specifications of such options might wish to
   include some kind of signaled acknowledgement.  For example, an
   option specification might say that if a responder sees and supports
   option XYZ, it MUST include option XYZ in its response.
```
which basically says that we should ignore whatever is not supported.

So, if by the time we call `SizeAndDo`, not a single EDNS option is set, it basically means that the application does not understand any of the options (or it would have had some of them set, hence, we would have hit https://github.com/coredns/coredns/blob/0e5e59c327387472c60fb5f2f2c7d84a89b879c9/request/request.go#L146 and simply set the size and DO bit.

Maybe instead of nuking `o.Option` as suggested in my previous comment, the right step is to set a brand new dns.OPT for the message `m` and set Size, flags, DO bit and all on this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] SizeAndDo sho..." ]
>There is https://tools.ietf.org/html/rfc6891#section-6.1.2
>
>```
>Any OPTION-CODE values not understood by a responder or requestor
>   MUST be ignored.  Specifications of such options might wish to
>   include some kind of signaled acknowledgement.  For example, an
>   option specification might say that if a responder sees and supports
>   option XYZ, it MUST include option XYZ in its response.
>```
>which basically says that we should ignore whatever is not supported.

Ack. So we support everything? What breaks?

It also depends what plugins are loaded, so we don't know before hand what is 
supported and what not. This is especially difficult if the server returns an 
error in which you (still?) need to echo the edns0 cruft you can understand.

**Comment by chantra** [comment]
> Ack. So we support everything? What breaks?

My understanding is that only some specific options may specify that the responder includes it in the response. In this specific example, if you send EDNS option 100 (via `+ednsopt=100` with dig command), the option will be echoed back, which I understand it should not.

I just realized that in the case of BADVERS, it may be caught by coredns using https://github.com/coredns/coredns/blob/bffb955f6952c197d17f028f30b6bee069b15f2b/plugin/pkg/edns/edns.go#L14 during `ServeDNS` entrypoint in 
https://github.com/coredns/coredns/blob/bffb955f6952c197d17f028f30b6bee069b15f2b/core/dnsserver/server.go#L222
and will correctly have no options set (except that RCODE is not properly set and https://gist.github.com/chantra/ed2050f58a1aa5efee94527abb61daa6 may help here)

Now, at least for the whoami plugin, coredns still end up replying the unknown option:

```
dig @localhost -p 1053 a  whoami.example.org +norec  +ednsopt=100

; <<>> DiG 9.10.6 <<>> @localhost -p 1053 a whoami.example.org +norec +ednsopt=100
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47028
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; OPT=100
;; QUESTION SECTION:
;whoami.example.org.		IN	A

;; ADDITIONAL SECTION:
whoami.example.org.	0	IN	AAAA	::1
_udp.whoami.example.org. 0	IN	SRV	0 0 49426 .

;; Query time: 0 msec
;; SERVER: ::1#1053(::1)
;; WHEN: Wed May 16 00:10:43 PDT 2018
;; MSG SIZE  rcvd: 139
```
which I understand is not correct based on https://ednscomp.isc.org/compliance/summary.html : 
```
EDNS - Unknown Option
dig +norec +ednsopt=100 soa zone @server	[1]
expect: SOA
expect: NOERROR
expect: OPT record with version set to 0
expect: that the option will not be present in response
See RFC6891, 6.1.2 Wire Format
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] SizeAndDo sho..." ]
>> Ack. So we support everything? What breaks?
>
>My understanding is that only some specific options may specify that the responder includes it in the response. In this specific example, if you send EDNS option 100 (via `+ednsopt=100` with dig command), the option will be echoed back, which I understand it should not.
>
>I just realized that in the case of BADVERS, it may be caught by coredns using https://github.com/coredns/coredns/blob/bffb955f6952c197d17f028f30b6bee069b15f2b/plugin/pkg/edns/edns.go#L14 during `ServeDNS` entrypoint in
>https://github.com/coredns/coredns/blob/bffb955f6952c197d17f028f30b6bee069b15f2b/core/dnsserver/server.go#L222
>and will correctly have no options set (except that RCODE is not properly set and https://gist.github.com/chantra/ed2050f58a1aa5efee94527abb61daa6 may help here)
>
>Now, at least for the whoami plugin, coredns still end up replying the unknown option:
>
>```
>dig @localhost -p 1053 a  whoami.example.org +norec  +ednsopt=100
>
>; <<>> DiG 9.10.6 <<>> @localhost -p 1053 a whoami.example.org +norec +ednsopt=100
>; (2 servers found)
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47028
>;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 3
>
>;; OPT PSEUDOSECTION:
>; EDNS: version: 0, flags:; udp: 4096
>; OPT=100
>;; QUESTION SECTION:
>;whoami.example.org.		IN	A
>
>;; ADDITIONAL SECTION:
>whoami.example.org.	0	IN	AAAA	::1
>_udp.whoami.example.org. 0	IN	SRV	0 0 49426 .
>
>;; Query time: 0 msec
>;; SERVER: ::1#1053(::1)
>;; WHEN: Wed May 16 00:10:43 PDT 2018
>;; MSG SIZE  rcvd: 139
>```
>which I understand is not correct based on https://ednscomp.isc.org/compliance/summary.html :
>```
>EDNS - Unknown Option
>dig +norec +ednsopt=100 soa zone @server	[1]
>expect: SOA
>expect: NOERROR
>expect: OPT record with version set to 0
>expect: that the option will not be present in response
>See RFC6891, 6.1.2 Wire Format
>```

Ack. But this is not an easy fix, unless we add some mechanism (interface?) 
whereby coredns can inspect the plugins to edns option that are supported...

**Comment by miekg** [comment]
The list is here https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-11

Right now coredns plugins (if loaded) implement; NSID and (maybe) edns-client-subnet. None of the other ones.

We can create a list of supported codes (and export that var so external users can update it). DNSCOOKIE support is on my wish list as well, as is padding and maybe the DNSSEC signaling.

**Comment by rdrozhdzh** [comment]
JFI, from rewrite plugin readme - 

> Currently supported are EDNS0_LOCAL, EDNS0_NSID and EDNS0_SUBNET

**Comment by miekg** [comment]
not sure if this still is an issue (or an issue with a specific plugin)
