### ISSUE TITLE
CNAME target resolution plugin

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1810]
Currently, adding `A` records for `CNAME` targets in a response must be implemented per plugin that may generate a `CNAME`. 

Alternately, We could do this with an early-in-the-chain plugin, using a non-writer, that sends requests down the chain, but then looks at the response for before writing to the client. For each unresolved `CNAME` it sees (a `CNAME` without an `A` record for the target), it creates an `A` record request by sending the target name down the chain and adding the result (if any) to the response. It would continue until it has tried looking up each unique `CNAME` in the response.

This method is also loop safe for `CNAME` chain loops without relying on a depth limit like the current recursive method.

As a separate plugin, it enables `CNAME` target resolution for any current/future plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] CNAME target reso..." ]
>Currently, adding `A` records for `CNAME` targets in a response must be implemented per plugin that may generate a `CNAME`.
>
>Alternately, We could do this with an early-in-the-chain plugin, using a non-writer, that sends requests down the chain, but then looks at the result for before writing to the client. For each unresolved CNAME it sees (CNAME without A Records), it creates an A record request, and sends that down the chain, adding the result (if any) to the results. Continuing until it has tried looking up each unique CNAME in the result.
>
>This method is also loop safe for CNAME chain loops without relying on a depth limit like the current recursive method.
>
>As a separate plugin, it enables `CNAME` target resolution for any current/future plugin.

I like the plugin idea, but might re-inspecting every packet for cname impair 
performance too much?

**Comment by chrisohaver** [comment]
It would look at the record type of every answer in the response one time.  I don't think that would be a big hit, but I could be wrong.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CNAME target ..." ]
>It would look at the record type of every answer in the response one time.  I don't think that would be a big hit, but I could be wrong.

Yeah, I might be overly concerned. This will clean up a lot of places that need 
CNAME resolving, so I welcome a plugin that simplifies it.
