### ISSUE TITLE
Manual: empty sections

### ISSUE THREAD

**Issue by ahmetb** [coredns/coredns#1821]
There are quite a few empty sections on the manual document:

> ![image](https://user-images.githubusercontent.com/159209/40281349-84c2f99a-5c15-11e8-88de-1f1bca298d37.png)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Manual: empty sec..." ]
>There are quite a few empty sections on the manual document:
>
>> ![image](https://user-images.githubusercontent.com/159209/40281349-84c2f99a-5c15-11e8-88de-1f1bca298d37.png)

yep. please file issues on https://github.com/coredns/coredns.io or better yet, 
help write the manual :)

**Comment by ahmetb** [comment]
No idea how I ended up at the wrong repo. Will reopen at coredns.io repo. I don't know enough to write the contents.
