### ISSUE TITLE
Self CNAME target resolution (upstream) stopped working

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1826]
Recently, `upstream` stopped working for self lookups of CNAME targets.

It was working early yesterday.

Integration tests (coredns/ci) started failing today. I verified it also fails on a local build of master, so it's probably not a coredns/ci environment issue.
 
I don't see anything obvious in the commits.  Possibly something changed in an import (that is not version controlled).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Self CNAME target..." ]
>Recently, `upstream` stopped working for self lookups of CNAME targets.
>
>It was working early yesterday.
>
>Integration tests (coredns/ci) started failing today. I verified it also fails on a local build of master, so it's probably not a coredns/ci environment issue.

With just a `make test` or w/ k8s tests run as well?
"go test ./test ./plugin/..." runs without a hitch, but we might not unit test 
this (should be good to add though).

The only major CI thing of the last few days has been the Go upgrade


/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
> "go test ./test ./plugin/..." runs without a hitch, but we might not unit test
this

We don't.  Its hard to do without an integration test - hence, its in the integration tests.

> The only major CI thing of the last few days has been the Go upgrade.

Yes, but CI passed after the update to Go...so it's probably not that.  I just started debugging now looks to be related to the context loop counter.

**Comment by chrisohaver** [comment]
This started working on my local system.  Went to lunch, came back resumed debugging, noticed it was working again.   I also noticed that my IDE is now suddenly confused about the `github.com/miekg/dns` import ... even though it can compile, it complains that `github.com/miekg/dns` has no buildable source, and that SetReply() doesn't exist...

**Comment by miekg** [comment]
Nothing happened in that repo and we pinned that to 1.0.6 10 days ago...

**Comment by chrisohaver** [comment]
Yeah - i think it's just coincidence.  The CI still fails in the same way.

`upstream` continues to work OK on my laptop... which is frustrating in a way, because now I cannot debug the failure using the IDE debugger.

The upstream tests do use `template`, and there were changes there recently.  looking into that.

**Comment by chrisohaver** [comment]
> The upstream tests do use template, and there were changes there recently.

... and those changes looks completely innocuous.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/tree/upstream-test add a test that I expect to resolve the cname, but it doesn't

**Comment by miekg** [comment]
I know what this is! It's the DoH stuff; were I overwrote the LocalAddr and RemoteAddr - I wonder what would break; we should totally have a test for this in the unit tests as well.

Le'me revert (will roll forward actually) and see if that helps.
