### ISSUE TITLE
[corbot]: add /release

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1835]
Releases are (or already were) somewhat time consuming and require a somewhat special setup (if we are going to build full multi-arch docker containers the setup *will* be special).

Now corbot seems to be working well enough it may be time to add a `/release: <VERSION>` command that does the heavy lifting.

The problem is that we need a clean build env, so we can use docker

## Process
Open an issue for the new release and at some point, call `/release: 1.2.0` which kicks off the build; any errors will be communicated back to the issue. Only releasers can do this.

## Impl
The OWNERS file is extended with `releasers` that are allowed to kick this off. Further more it needs a section that tells how to release (name TBD), that points to a (shell?) script that kick of the release.
The caddy config hold pointers to GITHUB_ACCESS_TOKEN and a docker login.

Can you build docker in docker containers? And multi-arch with ssl certs and friends will be harder, but we don't do that know; having a github repo also allows us to setup this up once and for all.

We need a new repo for this with all the supporting code; I propose github.com/coredns/release

**Comment by stp-ip** [comment]
Docker in docker is possible usually done via -privileged flag and/or mounting the docker socket: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

Another option would be multi step builds. Building the binary in the first container and then using the binary in the second: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by miekg** [comment]
https://github.com/miekg/dreck has all the features needed to pull this off, it also runs commands as the user nobody. I don't want to make it too powerful meaning the release process should change a bit. like:

1. send pr that changes the version to the new version (ideally this should tag as well)
  an automatic 'make -f Makefile.doc *would* be nice, but lets leave that out.
  
   * maybe dreck can tag if you put /tag in a PR, that would be nice.

2. open an issue and do a /release: <VERSION>, that builds all the artifacts. Bonus points for getting things like the set of people who contributed to the release relayed back in the comment, so writing the release notes becomes easier.

**Comment by miekg** [comment]
this is done
