### ISSUE TITLE
coredns certificate  issue

### ISSUE THREAD

**Issue by nik786** [coredns/coredns#1838]
Deployment of CoreDns on Kubernetes 1.10
~~~
cat /opt/core-dns/Corefile 
.:53 {
       	log stdout
           health
       	kubernetes cluster.local
           proxy . /etc/resolv.conf
           cache 30
}
~~~

kubectl delete --namespace=kube-system rc kube-dns-v20

kubectl delete --namespace=kube-system svc kube-dns

kubectl create -f coredns-de.yaml

kubectl create -f coredns-svc.yaml

kubectl get --namespace=kube-system deployments -n kube-system

kubectl get --namespace=kube-system pods -n kube-system

kubectl get --namespace=kube-system svc -n kube-system

kubectl create -f nginx.yaml

kubectl get services -n kube-system

kubectl run -i -t --image=infoblox/dnstools:k8sblog --restart=Never dnstest

curl nginx.kubernetes.default.svc.cluster.local
 not able to resolve

kubectl logs pod/coredns-gqgswyqhg     -n kube-system

it does nt have valid certificates

can any one tell me how to integrate certificate and sync with kubernetes 1.10??

**Comment by chrisohaver** [comment]
My guess is that certs are not properly installed on the cluster.
Nothing special should be required in CoreDNS configs.  Kubernetes will always include the installed certs in every pod it spins up... So if coredns has the wrong certs, I believe it means that K8s has invalid certs installed.

**Comment by chrisohaver** [comment]
Also, not sure if this was a typo above, but ... 
`nginx.kubernetes.default.svc.cluster.local` should not be expected to have a record. The correct name would be... `nginx.default.svc.cluster.local`
