### ISSUE TITLE
Use 'docker manifest' instead of 'manifest-tool' in Makefile.release

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#1848]
Manifest creation has recently been added to docker cli docker/cli#138.
So at some point we should move to the built-in docker manifest creation instead of using the (soon to be deprecated) manifest-tool.

**Comment by chrisohaver** [comment]
FWIW, I just noticed that "docker manifest" is still labeled as "experimental" in docker's docs.
https://docs.docker.com/edge/engine/reference/commandline/manifest/

**Comment by miekg** [comment]
still experimental

**Comment by miekg** [comment]
current solution seems to work fine.
