### ISSUE TITLE
plugin/Forward : ability to configure the dialTimeout 

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1849]
Currently we are using CoreDNS with forward and upstream to cloud AWS (using dns over tls)
Depending the network used we may have very slow connection and need to extend the dial timeout.
(right now issue with network over wifi..)

I cannot say right now what would be the timeout to be defined, and if this dialTimeout would be tunable in our configuration setup.

There is a similar issue here about readTimeout : #1678 that has been solved without adding the option in stanza.

We are specifically stuck with the dialTimeout, but should we rather propose a global "timeout" in the stanza that would cover ALL timeouts, in order to simplify the configuration for everyone ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/Forward : ..." ]
>Currently we are using CoreDNS with forward and upstream to cloud AWS (using dns over tls)
>Depending the network used we may have very slow connection and need to extend the dial timeout.
>(right now issue with network over wifi..)
>
>I cannot say right now what would be the timeout to be defined, and if this dialTimeout would be tunable in our configuration setup.
>
>There is a similar issue here about readTimeout : #1678 that has been solved without adding the option in stanza.
>
>We are specifically stuck with the dialTimeout, but should we rather propose a global "timeout" in the stanza that would cover ALL timeouts, in order to simplify the configuration for everyone ?

Can we not do the same thing as we did with readTimeout?

**Comment by fturib** [comment]
Do you mean by increasing/decreasing the dial timeout based on precedent tentatives ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/Forwar..." ]
>Do you mean by increasing/decreasing the dial timeout based on precedent tentatives ?

yes (we use avg in the read/write timeout)

**Comment by fturib** [comment]
NOTE: looks like there is an issue in the underlying library that manage the Dial. Which make useless for now to change this dialTimeout.
I created the issue https://github.com/miekg/dns/issues/689 to clarify

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/Forwar..." ]
>NOTE: looks like there is an issue in the underlying library that mange the Dial. I created the issue https://github.com/miekg/dns/issues/689 to clarify

Ack, saw it. I might be time to create a dns.Client2 to create some sanity 
there...
