### ISSUE TITLE
Plugin/Kubernetes: A records for services with Load Balancer IP (External-IP)

### ISSUE THREAD

**Issue by leeliu** [coredns/coredns#1851]
#### Feature request:
Some type of DNS naming scheme to answer with `External-IP` for services in addition to Cluster IP/Pod IPs. (ie: `test.default.svc.cluster.local` currently points to `10.28.0.3`. Be nice if `test.default.extsvc.cluster.local` (or whatever naming scheme) could point to `35.129.2.3`.)

#### Use case:
- a coredns server within a cluster that an external domain can delegate a subdomain NS's to
- coredns answers with public load balancer IPs (`External-IP`) of running services
- perhaps an annotation on the service itself to allow different dns name than service name?
- we currently do this with route53 manually but would be nice to not have route53 as a dependency to manage internal cluster records

#### Example:
I have `example.com` where I delegate `NS` records for `core.example.com` to coredns pods running within the cluster. Allow coredns to configured to answer that it's the authoritative NS for `core.example.com`. Queries should resolve `test.core.example.com` to `35.129.2.3`. Bonus if `test` itself can be configured to be a different dns name than the internal service name through some type of annotation on the service.

**Comment by ngortheone** [comment]
Very much interested in described functionality. Are there any existing solutions or at least workarounds to get this done?

**Comment by chrisohaver** [comment]
This is feasible to add as a feature, and there is wide interest.  We discussed this very briefly during maintainers meeting.   We need to settle on how to implement it at a high level. @miekg, @johnbelamaric

dns-wise:
* should the external records be in an entirely new domain (e.g. `entirely.new.domain.com`)
* should the external records be in the same domain, under a different subdomain (e.g. `ext.cluster.local`)

code-wise:
* As a new option in _kubernetes_ plugin
* As a new plugin that shares the API connection with _kubernetes_ plugin.

**Comment by johnbelamaric** [comment]
The user should be able to specify the domain to use for this, there is no reason to use something like `external.local`. Instead, this should work like any other plugin that manages a zone, except that it gets the data from the K8s api. for example, even if my cluster domain is `cluster.local` my external might be `services.mycompany.com`.

For this reason I think it makes sense to be a different plugin.

**Comment by chrisohaver** [comment]
> For this reason I think it makes sense to be a different plugin.

A single plugin _can_ serve more than one zone...

```
kubernetes mycluster.local services.mycompany.com in-addr.arpa ip6.arpa {
  external services.mycompany.com
  fallthrough in-addr.arpa ip6.arpa
}
```

vs ... separate plugin (let's name it `externalkube` in this example)

```
externalkube services.mycompany.com in-addr.arpa ip6.arpa {
  fallthrough in-addr.arpa ip6.arpa
}
kubernetes mycluster.local in-addr.arpa ip6.arpa {
  fallthrough in-addr.arpa ip6.arpa
}
```

... or if a user wants to only serve external services, and not internal services (e.g. a separate out-of-cluster coredns that serves external IPs)...

In one plugin ...

```
kubernetes services.mycompany.com in-addr.arpa ip6.arpa {
  external services.mycompany.com
  disable-local
  fallthrough in-addr.arpa ip6.arpa
}
```

vs separate plugin ...

```
externalkube services.mycompany.com in-addr.arpa ip6.arpa {
  fallthrough in-addr.arpa ip6.arpa
}
```

I think a litmus test for whether something should be a separate plugin or extend an existing one, is if it could be used on its own.  I.e. If we write the new plugin such that it _requires_ the presence of a kubernetes plugin in use, then it's a bad candidate for a separate plugin (take the federation plugin for example, which requires kubernetes).

In this case, the plugin makes sense to use on its own, so it's a good candidate for a separate plugin.
