### ISSUE TITLE
Docker creation is broken now

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1853]
Makefile.release is broken after #1843 , see comment: https://github.com/coredns/coredns/pull/1843#issuecomment-394450384

Maybe things can be made simpler because we don't need to run apk (or the debian equiv apt-get) when we create the docker image.

**Comment by miekg** [comment]
/cc @yongtang who wrote most of this

I think we can drop everything in `Makefile.release` and just make sure:
a) we copy the right coredns binary into the right arch image
b) manifest tool (or the beta docker manifest) the correct image to the correct arch

**Comment by yongtang** [comment]
@miekg Thanks. Let me take a look.
