### ISSUE TITLE
Pod doesn't resolve service host properly

### ISSUE THREAD

**Issue by Reyes7** [coredns/coredns#1863]
I have a problem, because one of my pod with application doesn’t resolve address to mongodb statefullset, which I defined in configmap for Coredns. But another pods resolves this address properly. Everything works fine when I add ip and host name to /etc/hosts, but I would like to avoid this solution. Can anybody help?

Configmap configuration:

<img width="549" alt="screen shot 2018-06-07 at 10 58 00 am" src="https://user-images.githubusercontent.com/11554473/41092200-aa0fb850-6a48-11e8-9a3a-3d0e64d6d18b.png">

Configuration was set:

<img width="1894" alt="screen shot 2018-06-07 at 11 18 44 am" src="https://user-images.githubusercontent.com/11554473/41092230-bc04fea8-6a48-11e8-801d-125c47073b20.png">

I see that my test pod resolve address: 

<img width="624" alt="screen shot 2018-06-07 at 10 45 13 am" src="https://user-images.githubusercontent.com/11554473/41092317-e58d0298-6a48-11e8-9a81-a123539a1eb8.png">

but another one pod:

<img width="1509" alt="screen shot 2018-06-07 at 11 20 03 am" src="https://user-images.githubusercontent.com/11554473/41092377-06213592-6a49-11e8-8839-b6a7a06143ff.png">

**Comment by johnbelamaric** [comment]
Try adding in the answer/response rewrite. The client is probably rejecting the response because of the name difference.

**Comment by johnbelamaric** [comment]
https://github.com/coredns/coredns/tree/master/plugin/rewrite#response-rewrites

**Comment by chrisohaver** [comment]
> The client is probably rejecting the response because of the name difference.

Yes - Java in particular requires the query name in the question and answer match.
Where as nslookup apparently isn't so picky.

**Comment by Reyes7** [comment]
Thank you for Your hints but it didn’t solve my problem. I've combined with the answer section in configmap for Coredns. However, I still get the same error with MangoDB. 

My last configuration for Coredns:
<img width="570" alt="screen shot 2018-06-10 at 8 03 28 pm" src="https://user-images.githubusercontent.com/11554473/41204964-fe34409a-6ceb-11e8-94d0-c66833070301.png">

I see, that configuration has been successfully loaded:
<img width="593" alt="screen shot 2018-06-10 at 8 07 17 pm" src="https://user-images.githubusercontent.com/11554473/41204981-3c1978bc-6cec-11e8-9c24-73115e13cc84.png">

test with dig:
<img width="800" alt="screen shot 2018-06-10 at 8 10 10 pm" src="https://user-images.githubusercontent.com/11554473/41204989-59a7912a-6cec-11e8-8756-3e25b06e532c.png">

**Comment by chrisohaver** [comment]
Two things to check...

1. In your last test, you ran the `dig` test from the coredns pod, which will not query coredns (coredns pod runs with the "default" pod dns policy meaning that it will query using /etc/resolv.conf, not "itself"). Try testing using another pod.
2. Has CoreDNS reloaded the config?  I see you don't have the `reload` plugin enabled, so it will not reload the config automatically.  You can reload by killing the coredns pods, and letting the deployment spin new ones back up, or by sending a SIGUSR1 to the coredns process in each coredns pod/container.

**Comment by Reyes7** [comment]
Thank you very much for your help, my problem was solved yesterday. It turned out that the problem wasn’t on Coredns side, but on the side of Docker image with application.

My application is working on Tomcat container, so I built it on image tomcat:8-jre8. I really do not know why but the simple application in this image can’t properly resolve host mongodb-vm.test.com. It is really funny because network programs such as dig and nslookup which were running on pod, resolved the address properly.

To find where the problem is I created simple class where I tried to resolve host mongodb-vm.test.com over methods from InetAddress. I transformed my simple class in two other ways:

   1) Simple class that was running through the javac.
   2) Class from pt. 1 that was running as a servlet on tomcat container.
   3) Spring-boot application.

sources: https://github.com/Reyes7/kube-tools/tree/master/host-resolver

All my applications I put into tomcat:8-jre8. image. In the first two cases host wasn’t resolved properly, but only spring-boot application was. After this test, I changed base image to tomcat:8.5.31-jre8-alpine and all my three applications started to resolve the MongoDB address properly and finally worklog also. I checked my test applications and worklog on other tomcat images from alpine and all my applications resolved host correctly,

If someone knows the reason why the applications don’t resolve the rewritten address via Coredns in tomcat:8-jre8 image, I will be grateful for the answer.

**Comment by miekg** [comment]
I think what @johnbelamaric say in https://github.com/coredns/coredns/issues/1863#issuecomment-395392244 is correct and the previous (glibc?) resolver rejects the response. Musl libc's resolver might be more lenient here; but this can break with every upgrade.

**Comment by jenciso** [comment]
That post solve this problem https://github.com/coredns/coredns/issues/2347#issuecomment-442934925
