### ISSUE TITLE
CNAME resolution failing across secondary zones

### ISSUE THREAD

**Issue by xalimar** [coredns/coredns#1864]
I believe I'm running into a bug due to having a second zone that could be part of the first zone, so CNAMEs from the first zone aren't being checked against the second zone.

**Scenario:**
Two zones configured as secondaries
  1. example.com
  2. foo.example.com

A CNAME record in example.com that points to an A record in foo.example.com

    bar.example.com. CNAME bar.foo.example.com
    bar.foo.example.com A 192.168.1.1

**The problem:**
Coredns returns the CNAME record to a dig query but not the A record

**Expected result:**
Coredns returns both the CNAME and A record to the dig query

**Dig examples:**

    /etc/coredns # dig @localhost bar.example.com
    
    ; <<>> DiG 9.11.2-P1 <<>> @localhost bar.example.com
    ; (2 servers found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56085
    ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ; COOKIE: f2701ad5b57f128e (echoed)
    ;; QUESTION SECTION:
    ;bar.example.com.                 IN      A
    
    ;; ANSWER SECTION:
    bar.example.com.          30      IN      CNAME   bar.foo.example.com.
    
    ;; AUTHORITY SECTION:
    example.com.              30      IN      NS      ns1.example.com.
    example.com.              30      IN      NS      ns2.example.com.
    example.com.              30      IN      NS      ns3.example.com.
    example.com.              30      IN      NS      ns4.example.com.
    
    ;; Query time: 0 msec
    ;; SERVER: ::1#53(::1)
    ;; WHEN: Fri Jun 08 00:01:19 UTC 2018
    ;; MSG SIZE  rcvd: 272
    
    
    /etc/coredns # dig @localhost bar.foo.example.com
    
    ; <<>> DiG 9.11.2-P1 <<>> @localhost bar.foo.example.com
    ; (2 servers found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48063
    ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ; COOKIE: 6f0d661a65a5adf5 (echoed)
    ;; QUESTION SECTION:
    ;bar.foo.example.com.           IN      A
    
    ;; ANSWER SECTION:
    bar.foo.example.com.    30      IN      A       192.168.1.1
    
    ;; AUTHORITY SECTION:
    foo.example.com.              30      IN      NS      ns1.example.com.
    foo.example.com.              30      IN      NS      ns2.example.com.
    foo.example.com.              30      IN      NS      ns3.example.com.
    foo.example.com.              30      IN      NS      ns4.example.com.
    
    ;; Query time: 0 msec
    ;; SERVER: ::1#53(::1)
    ;; WHEN: Fri Jun 08 00:03:36 UTC 2018
    ;; MSG SIZE  rcvd: 279

**Working dig example when CNAME and A are reversed**

    /etc/coredns # dig @localhost foo.foo.example.com
    
    ; <<>> DiG 9.11.2-P1 <<>> @localhost foo.foo.example.com
    ; (2 servers found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14960
    ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ; COOKIE: 303eaf5099996a90 (echoed)
    ;; QUESTION SECTION:
    ;foo.foo.example.com.              IN      A
    
    ;; ANSWER SECTION:
    foo.foo.example.com.       30      IN      CNAME   foo.example.com.
    foo.example.com.          30      IN      A       192.168.1.1
    
    ;; AUTHORITY SECTION:
    foo.example.com.              30      IN      NS      ns1.example.com.
    foo.example.com.              30      IN      NS      ns2.example.com.
    foo.example.com.              30      IN      NS      ns3.example.com.
    foo.example.com.              30      IN      NS      ns4.example.com.
    
    ;; Query time: 0 msec
    ;; SERVER: ::1#53(::1)
    ;; WHEN: Fri Jun 08 00:28:26 UTC 2018
    ;; MSG SIZE  rcvd: 313
    

**Corefile being used**

    /etc/coredns # cat Corefile
    .:53 {
        cache 30
        errors
        health
        loadbalance round_robin
        log
        prometheus 0.0.0.0:9153
        proxy . /etc/resolv.conf
        secondary example.com {
          transfer from 192.168.2.5
          transfer from 192.168.2.6
          upstream
        }
        secondary foo.example.com {
          transfer from 192.168.2.5
          transfer from 192.168.2.6
          upstream
        }
    }

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] CNAME resolution ..." ]
>I believe I'm running into a bug due to having a second zone that could be part of the first zone, so CNAMEs from the first zone aren't being checked against the second zone.

Ack.

>    foo.example.com.          30      IN      A       foo.168.1.1

Did you typo this? Let me see if can easily repro this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] CNAME resolution ..." ]
>I believe I'm running into a bug due to having a second zone that could be part of the first zone, so CNAMEs from the first zone aren't being checked against the second zone.

yep, and it's a bug (maybe) hosting parent and child in the same server is 
always tricky.

The check to resolve *external* names is to see if it's subdomain of the current 
zone, in lookup.go:

~~~
  314         if elem == nil {                  
+ 315                 println(z.origin, targetName)
  316                 if !dns.IsSubDomain(z.origin, targetName) {
  317                         rrs = append(rrs, z.externalLookup(state, targetName, qtype)...)
  318                 }                         
  319                 return rrs, z.ns(do), nil, Success
  320         }                                 
  321                                           
  322         i := 0                           
~~~

And because foo is a subdomain we don't do this.

We could relax this check, but this may be expensive, because of the extra 
lookup. Also this code does not know about other zones that coredns may or may 
not have...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] CNAME resolution ..." ]
>I believe I'm running into a bug due to having a second zone that could be part of the first zone, so CNAMEs from the first zone aren't being checked against the second zone.

Deleting that check:

~~~
% dig @localhost -p 1043 cname.coredns.io

; <<>> DiG 9.10.3-P4-Debian <<>> @localhost -p 1043 cname.coredns.io
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10546
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cname.coredns.io.		IN	A

;; ANSWER SECTION:
cname.coredns.io.	600	IN	CNAME	cname.foo.coredns.io.
cname.foo.coredns.io.	600	IN	A	127.0.0.1

;; AUTHORITY SECTION:
coredns.io.		600	IN	NS	linode.atoom.net.

;; Query time: 0 msec
;; SERVER: ::1#1043(::1)
;; WHEN: Fri Jun 08 16:07:05 UTC 2018
;; MSG SIZE  rcvd: 171
~~~

Maybe if `upstream` is given *without* args we should not do the isSubdomain 
check?

**Comment by xalimar** [comment]
Thanks for the quick response!  I tested the change locally and it appears to work.  I don't have an opinion on what the best implementation is, but `upstream` given without args seems reasonable to me if there's not a terrible performance hit.
