### ISSUE TITLE
Combine answers from multiple external DNS into one

### ISSUE THREAD

**Issue by artyomturkin** [coredns/coredns#1865]
Is there a way to query multiple external DNS instances and combine their answers into one?

**Example (with Hashicorp Consul):**

Given:
- 2 Consul datacenters are deployed
- Application is deployed to both DCs

CoreDNS will:
1. Rewrite incoming query
2. Forward (or proxies) to both Consul instances simultaneously
3. Combine both answers into one
4. Shuffle addresses in the combined answer
5. Rewrite outgoing answer

At this moment I have a setup that will perform 1 and 5, but it will only query local instance of Consul (Consul will query the second instance itself, but only if the first does not have the app in question, using Consul Prepared Queries).

**Comment by miekg** [comment]
No there is no such thing; but should be relative easy to write a plugin that does this(*)



(*): if you know Go and a bit of DNS

**Comment by johnbelamaric** [comment]
#4 is done by the loadbalancer plugin. But the core part of multiple simultaneous queries being combined would be a new plugin.

**Comment by artyomturkin** [comment]
Thanks for the reply. I'll look into writing the plugin then. Which one would in your opinion be a better starting point: proxy or forward plugin?

Or would it be better to add fanout lb strategy to proxy plugin?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Combine answe..." ]
>Thanks for the reply. I'll look into writing the plugin then. Which one would in your opinion be a better starting point: proxy or forward plugin?
>
>Or would it be better to add fanout lb strategy to proxy plugin?

Doesn't matter that much. I think use can just re-use proxy (pkg/upstream) code 
and use multiple. You're code can then glue the answers together.

**Comment by byrnedo** [comment]
@artyomturkin did you ever write that plugin? Interested in same thing.
