### ISSUE TITLE
plugin/metrics - error creating the listener does not prevent CoreDNS to start

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1868]
I think (from the code) that it happen on each start or reload, but my use case is on Reload where a failing to listen the port does not prevent to switch to the new CoreDNS instance, although the error is reported in the log.

Looking into the code, I think comes from these lines:

in file `plugin/pkg/uniq/uniq.go`
```
// ForEach iterates for u executes f for each element that is 'todo' and sets it to 'done'.
func (u U) ForEach() error {
	for k, v := range u.u {
		if v.state == todo {
			v.f() . <==== an ERROR raised by f() does not trigger an ERROR on ForEach()
		}
		v.state = done
		u.u[k] = v
	}
	return nil
}
```

**Comment by miekg** [comment]
I think we discussed this at length in an issue and/or pull request? And this was the best we came up with?
(return err here is easy, but can/may have other implication when reloading)

**Comment by fturib** [comment]
Hum .. let me re-read that review then.
Right now the problem is that we implemented an external plugin that kick-off the reload on demand, and reply if the reload was OK. With this error not raised, we reply OK but the Metrics feature does not work.

**Comment by fturib** [comment]
Other implication is: if you raise an error at reload, then the server will keep running on the old instance. And there is nothing to cleanup the already started new instance. 
So, at the end we are in 'improper' state for the plugin that work by global variable (not limited to one instance). We are in improper state in both cases : going forward with the new instance or going backward with the old instance.

**Comment by fturib** [comment]
Maybe a better way is to get a status of each of the Plugins.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/metric..." ]
>Hum .. let me re-read that review then.
>Right now the problem is that we implemented an external plugin that kick-off the reload on demand, and reply if the reload was OK. With this error not raised, we reply OK but the Metrics feature does not work.

If you raise an error, the reload fails and something else fails then. Can't 
remember...

**Comment by fturib** [comment]
About raising an Error : you are right it will not cover all use cases.
Because we are stopping listener when restart . . that means before loading a new Instance of CoreDNS, if any error happen during the setup/start, this new instance will be cancelled and coreDNS will consider continuing on the initial instance - which has now the listener closed and no event to set it up again.

Any Error (in any plugin .. or invalid corefile) will cancel the new Instance and go back to the former instance. Linked or not to the Prometheus plugin.

Finally, i think that is more efficient to provide a feedback on Health of Prometheus plugin and let any monitoring fix the problem, if any, by a full restart of the CoreDNS pod or container.

**Comment by fturib** [comment]
Proposition from @miekg is to make simple : just raise a fatal ERROR that will exit CoreDNS.
and let monitoring of the process do its job.

see https://github.com/coredns/coredns/pull/1983#issuecomment-406857679

**Comment by fturib** [comment]
@miekg , @chrisohaver : I think here the choice should be global for the application.

When something is wrong enough such as CoreDNS or a plugin cannot provide the service expected:
- should we exit CoreDNS (with an error code) and let monitoring handle. ?
- should we continue but let Health inform of that invalid status ?

I am ok either way, just try to get a consensus and consistency on behavior of CoreDNS.

other question: if we exit when the service is not ok, what is the use case of plugin Health  ?

**Comment by miekg** [comment]
Depends on severity, which is at the discretion of the plugin. In the case
I can see metrics just calling fatalf when there is such problem.

**Comment by fturib** [comment]
The point is: in Metrics, if an error occurs when starting the Listener, there is no way it can be repaired by itself.

So, let use Health for use case where it is an external status missing, but can come back to normal : it worth to wait a little before deciding to stop the process.

I am ok with that definition.

**Comment by fturib** [comment]
@miekg : I am flagging "good first issue", as I have some guys interested to start to contribute to CoreDNS. I will point them these more easy issues for starting.

**Comment by miekg** [comment]
Ok. Sgtm!

**Comment by fturib** [comment]
@calebice is working on this issue.
