### ISSUE TITLE
cache: proxied result is not cached

### ISSUE THREAD

**Issue by ahmetb** [coredns/coredns#1870]
I have a config like:

```
example.com.:1053 {
  proxy . 127.0.0.1:8053 {
      protocol grpc insecure
  }
  cache 5
  errors
  log
}
```

with this, I'm issuing `dig A foo.example.com` queries to it every second, and I can clearly see in the backend that it gets a query every second.

I expected coredns frontend to cache it for 5 seconds.

For the record, here's the reply I get via dig:

```
dig A foo.example.com

; <<>> DiG 9.10.6 <<>> A foo.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44158
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;foo.example.com. IN A

;; ANSWER SECTION:
foo.example.com. 0	IN A 127.0.0.1

;; Query time: 90 msec
;; SERVER: 2401:fa00:fa::1#53(2401:fa00:fa::1)
;; WHEN: Tue Jun 12 10:37:29 PDT 2018
;; MSG SIZE  rcvd: 137
```

My answer doesn't have AA (authoritative answer) bit set, but is it necessary to have the response cached (I can't see it in the docs).

**Comment by miekg** [comment]
The TTL is zero. We don't cache these iirc

**Comment by ahmetb** [comment]
That makes sense.
Thanks.
