### ISSUE TITLE
proxy: AA bit from backend is sometimes not included

### ISSUE THREAD

**Issue by ahmetb** [coredns/coredns#1871]
I'm running coredns proxy plugin with a grpc backend:

```
example.com.:1053 {
    proxy . 127.0.0.1:8053 {
        protocol grpc insecure
    }
    log
}
```

in my backend I'm setting the `AA` bit like:

```go
	r := new(dns.Msg)
	r.SetReply(m)
	r.Authoritative = true
	[...]
```

and when I make a query, coredns `log` plugin shows this:

```
10.128.0.10:52198 - [12/Jun/2018:17:59:15 +0000] 37945 "A IN [redacted].[domain]. udp 137 true 4096" NOERROR qr,aa,cd 218 999.069µs
```

This log line contains the `AA` bit. But `dig` doesn't show the `aa` bit in the `flags:` section:

```
dig A [redacted.domain]

; <<>> DiG 9.10.6 <<>> A [redacted.domain]
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9569
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;[redacted.domain]. IN A

;; ANSWER SECTION:
[redacted.domain]. 19 IN A 127.0.0.1

;; Query time: 92 msec
;; SERVER: 2401:fa00:fa::1#53(2401:fa00:fa::1)
;; WHEN: Tue Jun 12 10:59:15 PDT 2018
;; MSG SIZE  rcvd: 137
```

**Comment by miekg** [comment]
This is because when we give it out of the cache we clear the bit (because 
cache). If we get the first time round it is directly from the auth (or at least 
has the aa bit set) we relay it directly.

Not sure if there is something in the DNS spec that says:

1) always clear from aa when replying from a cache
2) never cache non-aa answers (iirc we ignore that bit when we decide what to 
   cache)

**Comment by miekg** [comment]
ah, oops there is no cache.

**Comment by miekg** [comment]
Can you replicate by dropping complexity, i.e. no grpc, plain dns? Do you see this with the forward plugin  as well?

**Comment by ahmetb** [comment]
I think I figured this out: I wasn't querying the authoritative DNS server, I was just using my corporate network's public DNS resolution (as the `;; SERVER: 2401:fa00:fa::1#53(2401:fa00:fa::1)` line shows). This explains why `AA` bit is missing (and `RA` present).
