### ISSUE TITLE
plugin/forward: add grpc and DoH

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1874]
Add these two transports.

* For grpc I don't think we can re-use tcp conns, it does this by itself?
* For DoH we should create our own clients the miekg/dns impl works, but I think it's better to do it again (and someday merge *that* in miekg/dns). Another question I have it; it you have a TLS conn can you re-use that for DoH and vice versa?

**Comment by ahmetb** [comment]
background discussion at #1842

**Comment by miekg** [comment]
Started on DOH support. This will be completely outside the current transport and connection caching as the http package *also* does this that.

**Comment by miekg** [comment]
In *proxy* we made this all nice and all with interfaces which back fired a bit when we added https_google which just didn't fit. We face the same situation here; forward caching connections, DoH using `net/http`, so don't use (bascially) 80% of the functionality.

setup.go also assume it needs to start the connection managed go-routines, etc.

I'm torn between doing stuff with just `switch` or try to create on interface. Tried the interface route already and that let to 5 or 6 methods.

HC client now also assumes dns as well.

**Comment by miekg** [comment]
Inclined to just put more stuff in struct `Proxy`

**Comment by piaoyu** [comment]
@ahmetb  I saw your blog   https://ahmet.im/blog/coredns-grpc-backends/ ,it's great.
I  making  a dnsApi use grpc not just for dns query but dns add and delete to manager the dns  record for service discovery manage.   
But I confuse  that  the dns.Msg Struct (RFC 1034 and1035) can't find somewhere to put the ip in ? @miekg

**Comment by miekg** [comment]
dns.Msg struct is the binary DNS data, as described in RFC 1034/1035. If
you want to add ip addresses it needs to be added in the answer section as
A or AAAA records.

**Comment by piaoyu** [comment]
@miekg  Thanks. But  it is  confuse that it' in the answer section but not in question section. Because it's not the dns answer . I just want to add A or AAAA records to the backend store.
