### ISSUE TITLE
Pod doesn't resolve service domain via clusterip of coredns, but node ok

### ISSUE THREAD

**Issue by zhuleiandy888** [coredns/coredns#1879]
【1】coredns configmap data , coredns 1.1.3
[root@10.10.200.231 install_coredns]# kubectl edit configmap/coredns -n kube-system

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      upstream\n   
   fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    proxy . /etc/resolv.conf\n    cache 30\n    reload\n}\n"},"kind":"ConfigMap","metadata":{"annotation
s":{},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: 2018-06-14T07:59:37Z
  name: coredns
  namespace: kube-system
  resourceVersion: "1201939"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: e27f406f-6fa8-11e8-aaac-00163e2ea3c2
```
【2】、cluster detail info
```
[root@10.10.200.231 ~]# kubectl get svc -o wide -n kube-system|grep dns   
kube-dns               ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP    1d        k8s-app=kube-dns

[root@10.10.200.231 ~]# kubectl get pod -o wide -n kube-system|grep dns
coredns-6969b598c-gt9ff                                          1/1       Running   0          2h        10.244.0.200    ops-edudocker03-test-csyali-bje.vhallyun.domain

[root@10.10.200.231 ~]# kubectl get svc -o wide |grep test
test-dns-service   ClusterIP   10.102.128.208   <none>        8082/TCP         3h        app=vhall-test
```
【3】 Have a problem

on node:
[root@10.10.200.231 zl_test]# dig @10.96.0.10 test-dns-service.default.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> @10.96.0.10 test-dns-service.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45463
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test-dns-service.default.svc.cluster.local. IN A

;; ANSWER SECTION:
test-dns-service.default.svc.cluster.local. 5 IN A 10.102.128.208

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Jun 15 18:13:18 CST 2018
;; MSG SIZE  rcvd: 129

on pod:
[root@vhall-test-5b747457bc-9r2hd /]# cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
[root@vhall-test-5b747457bc-9r2hd /]# dig test-dns-service.default.svc.cluster.local
;; reply from unexpected source: 10.244.0.200#53, expected 10.96.0.10#53
;; reply from unexpected source: 10.244.0.200#53, expected 10.96.0.10#53
;; reply from unexpected source: 10.244.0.200#53, expected 10.96.0.10#53

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> test-dns-service.default.svc.cluster.local
;; global options: +cmd
;; connection timed out; no servers could be reached

but not via 10.96.0.10:

[root@vhall-test-5b747457bc-9r2hd /]# dig test-dns-service.default.svc.cluster.local @10.244.0.200

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> test-dns-service.default.svc.cluster.local @10.244.0.200
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25492
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test-dns-service.default.svc.cluster.local. IN A

;; ANSWER SECTION:
test-dns-service.default.svc.cluster.local. 5 IN A 10.102.128.208

;; Query time: 0 msec
;; SERVER: 10.244.0.200#53(10.244.0.200)
;; WHEN: Fri Jun 15 10:17:53 UTC 2018
;; MSG SIZE  rcvd: 129

**Comment by chrisohaver** [comment]
Interesting.
What networking add on are you using in the kubernetes cluster?

What does the kube-dns service definition look like? i.e. ...
`kubectl get svc kube-dns -n kube-system -o yaml`

**Comment by chrisohaver** [comment]
A couple more questions: 
What happens when you query the coredns pod ip directly?
What has the ip `10.244.0.200` - i.e where is that IP configured?

**Comment by zhuleiandy888** [comment]
【1】、The cluster use flannel network. flannel assigns IP addresses automatically for coredns pod --10.244.0.200.

【2】、The kube-dns service definition:
```
[root@10.10.200.231 ~]# kubectl get svc kube-dns -n kube-system -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"k8s-app":"kube-dns","kubernetes.io/cluster-service":"true","kubernetes.io/name":"CoreDNS"},"name":"kube-dns","namespace":"kube-system"},"spec":{"clusterIP":"10.96.0.10","ports":[{"name":"dns","port":53,"protocol":"UDP"},{"name":"dns-tcp","port":53,"protocol":"TCP"}],"selector":{"k8s-app":"kube-dns"}}}
    prometheus.io/scrape: "true"
  creationTimestamp: 2018-06-14T07:59:38Z
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "1087175"
  selfLink: /api/v1/namespaces/kube-system/services/kube-dns
  uid: e28301ab-6fa8-11e8-aaac-00163e2ea3c2
spec:
  clusterIP: 10.96.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

【3】、The ip 10.244.0.200 -- that's the coredns's pod ip, 10.96.0.10 is the clusterip of coredns service.
```
[root@10.10.200.231 ~]# kubectl get pod -n kube-system -o wide|grep coredns
coredns-6969b598c-gt9ff                                          1/1       Running   0          3d        10.244.0.200    ops-edudocker03-test-csyali-bje.vhallyun.domain
[root@10.10.200.231 ~]# kubectl get svc -n kube-system -o wide|grep kube-dns 
kube-dns               ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP    4d        k8s-app=kube-dns
[root@10.10.200.231 ~]# kubectl describe svc/kube-dns -n kube-system   
Name:              kube-dns
Namespace:         kube-system
Labels:            k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=CoreDNS
Annotations:       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"k8s-app":"kube-dns","kubernetes.io/cluster-ser...
                   prometheus.io/scrape=true
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP:                10.96.0.10
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:         10.244.0.200:53
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:         10.244.0.200:53
Session Affinity:  None
Events:            <none>
```

【4】、When i query the coredns pod ip directly：

when i query the coredns pod ip directly,  it's normal working in everywhere, but use clusterip（10.96.0.10）of coredns service have a error in every pod  container:   like below this:
```
[root@vhall-test-5b747457bc-9r2hd /]# dig test-dns-service.default.svc.cluster.local
;; reply from unexpected source: 10.244.0.200#53, expected 10.96.0.10#53
;; reply from unexpected source: 10.244.0.200#53, expected 10.96.0.10#53
;; reply from unexpected source: 10.244.0.200#53, expected 10.96.0.10#53

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> test-dns-service.default.svc.cluster.local
;; global options: +cmd
;; connection timed out; no servers could be reached
```
the error show that:    coredns pod(ip=10.244.0.200) reply the request directly not via 10.96.0.10.

Thank you for your time of explaining for me, do you need any else infomation?

**Comment by chrisohaver** [comment]
Since querying the coredns pod directly works as expected, it seems like this is some kind of address translation issue in Kubernetes.

What happens when you query the via the cluster ip over tcp?

**Comment by chrisohaver** [comment]
this issue in Kubernetes looks to be the same (or at least closely related)...

https://github.com/kubernetes/kubernetes/issues/21613

There are 2 suggested fixes at the end of the comments (one for ubuntu, one for centos).

**Comment by zhuleiandy888** [comment]
Thanks a lot !
I changed the configuration file :  /etc/sysctl.conf:
   net.bridge.bridge-nf-call-ip6tables = 1
   net.bridge.bridge-nf-call-iptables = 1
   net.bridge.bridge-nf-call-arptables = 1
The problem has been resolved,  will it cause other problems ?

**Comment by chrisohaver** [comment]
I can't say for certain on your network/system.  But I do know that k8s installer tools such as `kubeadm` will warn you if for example `net.bridge.bridge-nf-call-iptables` is not set to `1` when initializing the cluster.  This is, based on my weak understanding, required to allow bridged packets to traverse iptables rules.  In k8s the Cluster IPs "exist" only as a set of iptables forwarding rules, that forward packets to the pod ips.  Without it set, it seems that the returning packets dont get routed through the iptables rules, and therefore their source IPs are not changed.

**Comment by chrisohaver** [comment]
@zhuleiandy888, can we close this?  Thanks!

**Comment by zhuleiandy888** [comment]
@chrisohaver     
      Yes, you're right. It's currently in stable operation. thanks a lot!

**Comment by 0xyeti** [comment]
@zhuleiandy888 @chrisohaver  I have exactly same issue with you, except that all nodes in my cluster have these lines already:
```
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-arptables = 1
```
Inside the pod, I can't connect to the dns cluster ip. Do you have any idea?

**Comment by tadman** [comment]
As a note, if you're running this on a Proxmox server, the `/etc/sysctl.d/pve.conf` has settings that are the exact opposite of these, so you'll need to adjust that config file.
