### ISSUE TITLE
Can not stop caddy instance immediately

### ISSUE THREAD

**Issue by jiachengxu** [coredns/coredns#1880]
Hi there, I am trying to add some integration tests for my own plugin, and I want to let serval CoreDNS servers  up at first, then stop one of them and let it up later. But it seems that the server is not stopped after I call the `node.Stop()` because I have some output for debugging and I can still see the output of the "stopped" server. And I also check if there are any errors returned by the `node.Stop()`. Did I miss something?

```
var node1 *caddy.Instance
        
//Generate list of 4 corefiles
corefiles := generateCorefiles(4)

//first 4 server are up
for i, corefile := range corefiles {
    node, udp, _, err := CoreDNSServerAndPorts(corefile)
    if err != nil {
        t.Fatalf("Could not get CoreDNS serving instance: %s,%d", err, i)
    }
//Want to stop this server later.
    if i == 1 {
        node1 = node
    } else {
	defer node.Stop()
    }
}

//Only stop the node1.
err := node1.Stop()
if err != nil {
    t.Fatalf("Can not stop node 1: %s", err)
//No error here.
}
//Seems that node1 is not stopped.
```
Also, it would be great to have some documentations in the test package to show how to run integration tests.

Thanks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Can not stop cadd..." ]

>//Seems that node1 is not stopped.

Are you sure you actually stopping the node here (i.e. it *is* the pointer you 
saved earlier?) This should work, but without more debugging it is hard to say 
what is wrong.

>Also, it would be great to have some documentations in the test package to show how to run integration tests.

Which one? The CI integrations? Those are so large that they are put in the 
their own repo (github.com/coredns/ci). The test on travis only depend on etcd 
being up (see Makefile). What does would you like to see added?

/Miek

--
Miek Gieben

**Comment by jiachengxu** [comment]
Hi Miek, 
Thanks for your reply. 
I think I found the problem: `node.Stop()` doesn't stop my goroutine in the `setup` function of my plugin.
What I did: For easier debugging, I created a simple plugin named `hellowrold`, all the codes are as follows:
`setup.go`
```
package helloworld

import (
	"fmt"
	"time"

	"github.com/coredns/coredns/core/dnsserver"
	"github.com/coredns/coredns/plugin"

	"github.com/mholt/caddy"
)

func init() {
	caddy.RegisterPlugin("helloworld", caddy.Plugin{
		ServerType: "dns",
		Action:     setup,
	})
}

func setup(c *caddy.Controller) error {
	c.Next()
	if c.NextArg() {
		return plugin.Error("helloworld", c.ArgErr())
	}
	go func() {
		for {
			time.Sleep(5 * time.Second)
			fmt.Println("Hello world!")

		}
	}()

	dnsserver.GetConfig(c).AddPlugin(func(next plugin.Handler) plugin.Handler {
		return Helloworld{}
	})

	return nil
}
```
So every 5 seconds, it just prints "Hello world!", and nothing much.

`helloworld.go`
```//Package helloworld is a hello world for coredns
package helloworld

import (
	"context"

	"github.com/miekg/dns"
)

//Helloworld is a hello world for coredns
type Helloworld struct{}

//ServeDNS implements the plug.Handler interface
func (hw Helloworld) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) (int, error) {
	return 0, nil
}

//Name implements the Handler interfaceName implements the Handler interface
func (hw Helloworld) Name() string { return "helloworld" }
```
And I added a simple test file in the `test` folder:
`hellowrold_test.go`
```
package test

import (
	"strconv"
	"testing"
	"time"
)
func TestHelloWorld(t *testing.T) {

	port := strconv.Itoa(1053)
	corefile := `.:` + port + ` {
		helloworld
	}`

	node, _, _, err := CoreDNSServerAndPorts(corefile)
	if err != nil {
		t.Fatalf("Could not get CoreDNS serving instance!")
	}
	node.Stop() //Stop node here, and then sleep for 15 second to see if still can print "hello world"
	time.Sleep(15 * time.Second)

}
```
The test doesn't do anything, just sleep 15 seconds after the node is stopped, and check if it still can print "Hello world".

I used the following command to run the test:
```
 go test -v -run 'TestHelloWorld'
```
And the outputs are as follows:
```
=== RUN   TestHelloWorld
Hello world!
Hello world!
Hello world!
--- PASS: TestHelloWorld (15.00s)
PASS
ok  	github.com/coredns/coredns/test	15.046s
```
So it still prints 3 "Hello world!" after the node is stoped. So what does the `node.Stop()` exactly do? Did I miss something?

**Comment by jiachengxu** [comment]
> Which one? The CI integrations? Those are so large that they are put in the
their own repo (github.com/coredns/ci). The test on travis only depend on etcd
being up (see Makefile). What does would you like to see added?

My bad... I didn't check the makefile before.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Can not stop ..." ]
>	go func() {
>		for {
>			time.Sleep(5 * time.Second)
>			fmt.Println("Hello world!")
>
>		}
>	}()

What is stopping this goroutine when you call node.Stop() ?

/Miek

--
Miek Gieben

**Comment by jiachengxu** [comment]
Ok, I see. node.Stop() doesn't stop the goroutine. I thought node.Stop() is the same as I "kill" the coredns process from the terminal by using "ctrl+c"(i.e., the goroutine will be closed.) So what should I do to trigger the goroutine with the node.Stop()?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Can not stop ..." ]
>Ok, I see. node.Stop() doesn't stop the goroutine. I thought node.Stop() is the same as I "kill" the coredns process from the terminal by using "ctrl+c"(i.e., the goroutine will be closed.) So what should I do to trigger the goroutine with the node.Stop()?

Just the normal thing you should do in Go; you started the goroutine so it is 
your responsibilty to tear is down, with a waitgroup, a mutex or sending it a 
signal using a channel.

**Comment by jiachengxu** [comment]
Ok, I know how to do this. I added the caddy.OnShutdown() callback in the setup function to close the channel and call node.ShutdownCallbacks() in the test since the node.Stop() doesn't call OnShutdown. And it works.
Thanks for your help!
