### ISSUE TITLE
Rewrite Plugin: Suffix Matching Doesn't Work

### ISSUE THREAD

**Issue by naftulikay** [coredns/coredns#1881]
I am using CoreDNS 1.1.3, latest at time of writing, on CentOS 7 amd64.

I have the following configuration:

```
. {
  rewrite name suffix naftuli.local c.naftuli-test.internal
  forward . 169.254.169.254:53
}
```

The expectation is that the following will happen:

```shell
$ dig +short @127.0.0.1 bastion.naftuli.local
10.0.0.4
```

However, I get no results with the configuration above. If I replace `suffix` with `substring`, the query works as expected.

It appears that the suffix matcher is broken for the rewrite plugin.

> As an aside, regular expressions do also work, but my exact use case is suffixes only:
> ```
> . {
>   rewrite name regex ([^.]+).naftuli\.local\b {1}.c.naftuli-test.internal
>   forward . 169.254.169.254:53
> }
> ```

**Comment by johnbelamaric** [comment]
If it is a suffix, it should end in the trailing "." of a FQDN.

**Comment by naftulikay** [comment]
I am trying both of the following:

### source

`.` for just the source name:

```
. {
  rewrite name suffix cloud.naftuli.wtf. c.naftuli-test.internal
  forward . 169.254.169.254:53
}
```

### source + target

`.` for both the source and target:

```
. {
  rewrite name suffix cloud.naftuli.wtf. c.naftuli-test.internal.
  forward . 169.254.169.254:53
}
```

### it don't work

Neither of these resolve properly, but it's clear that CoreDNS is forwarding correctly:

```
$ dig +short @127.0.0.1 $(hostname).cloud.naftuli.wtf
$ dnsdomainname
c.naftuli-test.internal
$ dig +short @127.0.0.1 $(hostname).$(dnsdomainname)
10.127.0.2
```

What config changes must I make? I'm not sure if I'm doing anything wrong here.

**Comment by chrisohaver** [comment]
I just looked at the unit tests, to confirm that "suffix" rules are indeed tested, and I noticed that the test case also has _leading_ dots... e.g.

```
  rewrite name suffix .cloud.naftuli.wtf. .c.naftuli-test.internal.
```

**Comment by greenpau** [comment]
@naftulikay , were you able to follow the advice of @johnbelamaric  and @chrisohaver ? Did it work for you?

**Comment by naftulikay** [comment]
@greenpau this works:

```
. {
  rewrite name suffix .cloud.naftuli.wtf. .c.naftuli-test.internal.
  forward . 169.254.169.254:53
}
```

Thanks everybody! Might be worth adding some warnings or something when suffix rules aren't surrounded by periods, as I would never have figured this out on my own :+1:

Thanks for updating the docs!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Rewrite Plugi..." ]
>@greenpau this works:
>
>```
>. {
>  rewrite name suffix .cloud.naftuli.wtf. .c.naftuli-test.internal.
>  forward . 169.254.169.254:53
>}
>```
>
>Thanks everybody! Might be worth adding some warnings or something when suffix rules aren't surrounded by periods, as I would never have figured this out on my own :+1:
>
>Thanks for updating the docs!

For rewrite suffix we might default to adding a closing dot?

**Comment by greenpau** [comment]
> For rewrite suffix we might default to adding a closing dot?

@miekg , 👍 Will work on it.

Keeping this open for the upcoming PR.
