### ISSUE TITLE
Forward plugin sometimes returns FORMERR

### ISSUE THREAD

**Issue by zloo** [coredns/coredns#1899]
Hi there,

we're using coredns in our kubernetes clusters as the resolver. We have a rather basic setup:
```
    . {
      errors
      health
      prometheus 0.0.0.0:9153
      log . "{remote}:{port} - [{when}] {>id} {type} {class} {name} {proto} {size} {>do} {>bufsize} {rcode} {>rflags} {rsize} {duration}" {
        class error
      }
      cache 30
      kubernetes tt-k8s1.ko.seznam.cz 172.16.0.0/12 {
        tls /coredns/tls/coredns.pem /coredns/tls/coredns-key.pem /coredns/tls/ca.pem
        upstream 10.250.20.222 10.250.50.222
      }
      forward . 10.250.20.222 10.250.50.222
    }
```

with 10.250.20.222 and 10.250.50.222 being our internal DNS servers handling recursive DNS queries for the rest of the domains, including internal domains as well as all outgoing queries. 

We're using coredns 1.1.2 at the moment.

Sometimes FORMERR errors keep showing up for a few minutes, and they disappear after less than 10 minutes. They show up like this in the log:
```
10.64.38.104:59837 - [27/Jun/2018:12:13:14 +0200] 56625 A IN www.mapy.cz. udp 29 false 512 FORMERR qr,rd 29 205.372µs
10.66.206.49:37658 - [27/Jun/2018:12:12:51 +0200] 31387 AAAA IN grafana.com. udp 29 false 512 FORMERR qr,rd 29 219.374µs
```

It seems that the requests are served from cache because of the µs latencies - if they would try to connect to the upstream DNS servers, it would take at least a millisecond.

I managed to do a raw dig for a failing domain when the issue was happening:
```
$ dig puzzle.ng.seznam.cz @10.65.142.169

; <<>> DiG 9.10.3-P4-Ubuntu <<>> puzzle.ng.seznam.cz @10.65.142.169
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 46786
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'

;; QUESTION SECTION:
;puzzle.ng.seznam.cz.		IN	A

;; Query time: 1 msec
;; SERVER: 10.65.142.169#53(10.65.142.169)
;; WHEN: Wed Jun 27 12:12:56 CEST 2018
;; MSG SIZE  rcvd: 37
```

and I tried a subsequent query with +noedns:

```
$ dig +noedns puzzle.ng.seznam.cz @10.65.142.169

; <<>> DiG 9.10.3-P4-Ubuntu <<>> +noedns puzzle.ng.seznam.cz @10.65.142.169
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 47898
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;puzzle.ng.seznam.cz.		IN	A

;; Query time: 1 msec
;; SERVER: 10.65.142.169#53(10.65.142.169)
;; WHEN: Wed Jun 27 12:13:05 CEST 2018
;; MSG SIZE  rcvd: 37
```

I'm 100% certain the upstream DNS resolvers were working correctly, because I tried issuing the same query and they returned the answer correctly.

I also don't see anything else in the log, just the FORMERR errors. I would expect to see some upstream connection errors if coredns would expect the upstream servers to be unavailable.

I've only seen this happen to a single coredns instance in the cluster at the same time.

It seems to me that the coredns instance thinks that the upstream DNS servers are unavailable, when in reality they are. I'd appreciate any help or advice :) Thank you

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Forward plugin so..." ]
>I've only seen this happen to a single coredns instance in the cluster at the same time.
>
>
>It seems to me that the coredns instance thinks that the upstream DNS servers are unavailable, when in reality they are. I'd appreciate any help or advice :) Thank you

That shouldn't result in a FORMERR though; it is possible to capture a tcpdump?

/Miek

--
Miek Gieben

**Comment by zloo** [comment]
I'll try to, though this usually stops happening faster than I can react and dumping all of the DNS traffic all the time is impossible. I'll let you know once I have the dump.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>I'll try to, though this usually stops happening faster than I can react and dumping all of the DNS traffic all the time is impossible. I'll let you know once I have the dump.

pondering if CoreDNS could automatically write a pcap in such cases

**Comment by zloo** [comment]
that would be an awesome feature! 

I forgot to mention that this usually happens only once or twice per week, so it might take some time to catch the tcpdump.

also, thank you and the whole team for this awesome project :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>that would be an awesome feature!
>
>I forgot to mention that this usually happens only once or twice per week, so it might take some time to catch the tcpdump.

per week! OK.

>also, thank you and the whole team for this awesome project :)

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Forward plugin so..." ]
>$ dig puzzle.ng.seznam.cz @10.65.142.169
>
>; <<>> DiG 9.10.3-P4-Ubuntu <<>> puzzle.ng.seznam.cz @10.65.142.169
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 46786
>;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
>;; WARNING: recursion requested but not available
>
>;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'
>
>;; QUESTION SECTION:
>;puzzle.ng.seznam.cz.		IN	A
>
>;; Query time: 1 msec
>;; SERVER: 10.65.142.169#53(10.65.142.169)
>;; WHEN: Wed Jun 27 12:12:56 CEST 2018
>;; MSG SIZE  rcvd: 37
>```
>
>and I tried a subsequent query with +noedns:
>
>```
>$ dig +noedns puzzle.ng.seznam.cz @10.65.142.169
>
>; <<>> DiG 9.10.3-P4-Ubuntu <<>> +noedns puzzle.ng.seznam.cz @10.65.142.169
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 47898
>;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
>;; WARNING: recursion requested but not available
>
>;; QUESTION SECTION:
>;puzzle.ng.seznam.cz.		IN	A
>
>;; Query time: 1 msec
>;; SERVER: 10.65.142.169#53(10.65.142.169)
>;; WHEN: Wed Jun 27 12:13:05 CEST 2018
>;; MSG SIZE  rcvd: 37
>```

What should this return in the normal case, btw? I'm getting NXDOMAIN, so I'm 
assuming it is not publically available.

**Comment by zloo** [comment]
yes, that's an internal domain, which is actually a cname to another domain. But the same happens with all of the other domains as well, some of them internal, some of them publicly available, some of them from the open internet / outside of our company.

I've combed through the logs and most (95%+) of the domains in logs are from these upstream DNS servers, but sometimes there's even an internal kubernetes domain. But, all of the internal kubernetes domains that had the FORMERR log line were non-existing domains.

It seems that this is not related to the forward plugin after all.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>yes, that's an internal domain, which is actually a cname to another domain. But the same happens with all of the other domains as well, some of them internal, some of them publicly available, some of them from the open internet / outside of our company.
>
>I've combed through the logs and most (95%+) of the domains in logs are from these upstream DNS servers, but sometimes there's even an internal kubernetes domain. But, all of the internal kubernetes domains that had the FORMERR log line were non-existing domains.
>
>It seems that this is not related to the forward plugin after all.

Hmmm. Odd. The cache doesn't cache error responses:
https://github.com/coredns/coredns/blob/master/plugin/cache/cache.go#L67

So that would imply the original response is correct from that perspective, but 
then is garbled. The EDNS error from dig; points in to something like DNS 
Cookies or some other EDNS0 rcode that we not completely handle correctly.

**Comment by zloo** [comment]
It might also be something weird with our upstream DNS servers. There is a new initiative - https://dnsflagday.net/ - that seeks to eliminate workarounds for broken dns servers, we might be hitting something like that with our upstream dns servers. I have no idea how to debug that though.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>It might also be something weird with our upstream DNS servers. There is a new initiative - https://dnsflagday.net/ - that seeks to eliminate workarounds for broken dns servers, we might be hitting something like that with our upstream dns servers. I have no idea how to debug that though.

Yeah, I know. Might as well be coredns who's broken here, although I don't 
suspect that.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>It might also be something weird with our upstream DNS servers. There is a new initiative - https://dnsflagday.net/ - that seeks to eliminate workarounds for broken dns servers, we might be hitting something like that with our upstream dns servers. I have no idea how to debug that though.

But coming back to what you see; coredns hands out an answer that is formerr for 
the client (at least in the edns0 part, if interpret that correctly). The EDNS0 
record is not cached, but added when we reply. I'm implying to say this should 
never happen; but obviously does. Extremely hard to tell with a tcpdump.

**Comment by zloo** [comment]
you mean "Extremely hard to tell without a tcpdump", right?

I agree with everything you said though.

**Comment by rdrozhdzh** [comment]
@zloo, do you see the FORMERR for each and every query during several minutes, or you get the error for some queries and other queries work fine?

**Comment by chrisohaver** [comment]
_Not related at all to the FORMERR issue you are seeing_... But If I recall correctly, the `tls` directive in `kubernetes` is ignored unless you are running CoreDNS from outside the cluster.  In this case, you are running CoreDNS in a pod in the cluster, so it is using the certificates set up in the pod.  So, you should be able to remove that and shorten the config a bit.

**Comment by zloo** [comment]
@rdrozhdzh that's what i'm going to find out next time i catch it. I was only able to try the two digs above, and then the instance healed itself somehow.

@chrisohaver thanks :)

**Comment by miekg** [comment]
ha, wait, (was just scanning the code for something unrelated), we do this:

~~~
		// Check if the reply is correct; if not return FormErr.
		if !state.Match(ret) {
			formerr := state.ErrorMessage(dns.RcodeFormatError)
			w.WriteMsg(formerr)
			return 0, nil
		}
~~~
This means the reply isn't what we are expecting, meaning someone is doing something nasty.

**Comment by zloo** [comment]
That's interesting. I stumbled upon this part before. I couldn't find what `truncated` actually does though.

It would also be helpful to log `upstreamErr` - if the formerrs actually come from this code, we could use a bit more logging here :)
If I understand the code correctly, then the code at lines 149-151 are never called.

**Comment by miekg** [comment]
No, there is a continue way up, so we can fall out of the for loop when the deadline is exceeded and execute this bit.

**Comment by krzysztof-bronk** [comment]
I've stumbled upon the exact same issue, except in one case, the error was persistent. I had 5 identical CoreDNS pods and 1 of them was consistently throwing FORMERR. I also thought it's related to forward/proxy. Nothing else in the system/chain seemed bugged. Pod recreation fixed the issue...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>I've stumbled upon the exact same issue, except in one case, the error was persistent. I had 5 identical CoreDNS pods and 1 of them was consistently throwing FORMERR. I also thought it's related to forward/proxy. Nothing else in the system/chain seemed bugged. Pod restart fixed the issue...

OK so we should log here (problem is that this opens a dos, but ww can probably 
live with that for now).
And maybe we should retry the query when we see this.

It's really odd that caching seems involved here, though. I try to setup a test 
to replicated it.

**Comment by miekg** [comment]
As said previous a tcpdump would help, you can potentially patch in #1902

**Comment by miekg** [comment]
I've merged #1902, if you just compile a new binary (from master) and enable debug, something should  - hopefully - show up.

**Comment by zloo** [comment]
I just returned to this issue, and I see that you already released version 1.2.0 today. I assume that it contains #1902 as well?

**Comment by chrisohaver** [comment]
> I assume that [1.2.0] contains #1902 as well?

yes

**Comment by krzysztof-bronk** [comment]
I've just had it happen on Production, but I did not have any dump prepared so all I got for you is similar to what zloo posted.

Again, a single pod out of 5 was having this issue. The domain resolution was pretty much randomly returning FORMERR. Note: it was working fine sometimes.

`; <<>> DiG 9.9.4-RedHat-9.9.4-51.amzn2.2 <<>> my.internal.domain @172.30.80.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 36471
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'

;; QUESTION SECTION:
;my.internal.domain.  IN  A

;; Query time: 2 msec
;; SERVER: 172.30.80.1#53(172.30.80.1)
;; WHEN: Thu Jul 12 15:42:41 CEST 2018
;; MSG SIZE  rcvd: 42

=============================================================

; <<>> DiG 9.9.4-RedHat-9.9.4-51.amzn2.2 <<>> my.internal.domain @172.30.80.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22325
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;my.internal.domain.  IN  A

;; ANSWER SECTION:
my.internal.domain. 0 IN  CNAME lb.service.consul.
lb.service.consul. 0 IN A 10.147.0.152
lb.service.consul. 0 IN A 10.147.0.62
lb.service.consul. 0 IN A 10.147.0.103

;; Query time: 2 msec
;; SERVER: 172.30.80.1#53(172.30.80.1)
;; WHEN: Thu Jul 12 15:42:50 CEST 2018
;; MSG SIZE  rcvd: 159`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>I've just had it happen on Production, but I did not have any dump prepared so all I got for you is similar to what zloo posted.
>
>Again, a single pod out of 5 was having this issue. The domain resolution was pretty much randomly returning FORMERR. Note: it was working fine sometimes.

My gut feeling is that some upstream is acting up sometimes or something.
Again hard to say without some more evidence. Can you run with debug on for a 
couple of days - should not really impact performance are antything.


/Miek

--
Miek Gieben

**Comment by zloo** [comment]
we're currently running debug on 1.2.0 on all our instances. when the issue pops up again, i'll supply the logs.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>we're currently running debug on 1.2.0 on all our instances. when the issue pops up again, i'll supply the logs.

should have added which upstream replies here. Anyway lets hope something turns 
up soon, so we can get to the bottom of this.

**Comment by krzysztof-bronk** [comment]
I got inside the pod and run a bunch of nslookups against 127.0.0.1 and the upstreams in /etc/resolv.conf

127.0.0.1 (CoreDNS) was throwing FORMERR about 60% of the time. Sometimes nslookup would just straight away FORMERR, sometimes it would return the CNAME and even A's and then still end up with FORMERR. Sometimes there would be a warning thrown about ID mismatch.

Resolution against upstreams directly was 100% successful at the same time...

Not terribly useful but it might be telling that upstreams are fine, and also other pods are 100% fine at the same time.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>I got inside the pod and run a bunch of nslookups against 127.0.0.1 and the upstreams in /etc/resolv.conf
>
>127.0.0.1 (CoreDNS) was throwing FORMERR about 60% of the time. Sometimes nslookup would just straight away FORMERR, sometimes it would return the CNAME and even A's and then still end up with FORMERR. Sometimes there would be a warning thrown about ID mismatch.
>
>Resolution against upstreams directly was 100% successful at the same time...

Can you tcpdump?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>we're currently running debug on 1.2.0 on all our instances. when the issue pops up again, i'll supply the logs.

If I'm suspecting anything (hard to say without more evidence) it could possibly 
the connection cleanup - it seems we're getting out of sync. Again *not sure if 
this is the case*!

Can you set `expire` in config to an insanely high value? `expire 3000h` or 
something?

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I've got a PR that simplifies this code quite a bit.

**Comment by zloo** [comment]
Let me wait until monday, to see if the issue isn't magically fixed somehow, so we know that it manifests after the upgrade.



Regarding logging which upstream sent the reply - it really doesn't matter in our case, as they all use the same IP addresses.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>Let me wait until monday, to see if the issue isn't magically fixed somehow, so we know that it manifests after the upgrade.
>
>
>
>Regarding logging which upstream sent the reply - it really doesn't matter in our case, as they all use the same IP addresses.

See https://github.com/coredns/coredns/pull/1973

So non-conclusive local testing seems to show an improvement.

I wonder how I can properly unit tests this

**Comment by zloo** [comment]
Just following up - the issue has not popped up since upgrading to 1.2.0. I'll let you know as soon as it manifests.

**Comment by miekg** [comment]
Odd... Can't recall any major changes. From what version did you upgrade
again?

**Comment by zloo** [comment]
we were using 1.1.2

I didn't see any major updates either, maybe the bug hasn't manifested yet. Let's give it some more time, it usually manifested once per week, so it's not that uncommon to not see it this long.

**Comment by rdrozhdzh** [comment]
I suspect the #1889 might fix the problem

**Comment by miekg** [comment]
If that is true, we are probably wrong in returning FORMERR for such replies.

**Comment by sepich** [comment]
Hello, I was struggling from same intermittent FORMERR and done some captures. 
Kubernetes 1.11 default config with logs:
```
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        reload
    }
```
Coredns container is at 192.168.128.51 (tried versions 1.1.2 and 1.2.0 and both are affected). Dump below is for 1.2.0
<details><summary>Doing dig from another container at 192.168.128.54:</summary>

```
$ kubectl run -it --rm --restart=Never --image=infoblox/dnstools:latest dnstools
If you don't see a command prompt, try pressing enter.
dnstools# dig auth.dev.myonlinedata.net

; <<>> DiG 9.11.3 <<>> auth.dev.myonlinedata.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6169
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;auth.dev.myonlinedata.net.	IN	A

;; ANSWER SECTION:
auth.dev.myonlinedata.net. 30	IN	A	10.99.133.204

;; Query time: 166 msec
;; SERVER: 192.168.127.10#53(192.168.127.10)
;; WHEN: Tue Jul 31 09:15:05 UTC 2018
;; MSG SIZE  rcvd: 95

dnstools# dig auth1.dev.myonlinedata.net

; <<>> DiG 9.11.3 <<>> auth1.dev.myonlinedata.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 40064
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 93a697b6731e2145 (echoed)
;; QUESTION SECTION:
;auth1.dev.myonlinedata.net.	IN	A

;; Query time: 1 msec
;; SERVER: 192.168.127.10#53(192.168.127.10)
;; WHEN: Tue Jul 31 09:15:19 UTC 2018
;; MSG SIZE  rcvd: 67

dnstools# dig auth2.dev.myonlinedata.net

; <<>> DiG 9.11.3 <<>> auth2.dev.myonlinedata.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33944
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;auth2.dev.myonlinedata.net.	IN	A

;; ANSWER SECTION:
auth2.dev.myonlinedata.net. 30	IN	A	10.99.133.204

; <<>> DiG 9.11.3 <<>> auth3.dev.myonlinedata.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 7061
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: fab13988f67820c6 (echoed)
;; QUESTION SECTION:
;auth3.dev.myonlinedata.net.	IN	A

;; Query time: 3 msec
;; SERVER: 192.168.127.10#53(192.168.127.10)
;; WHEN: Tue Jul 31 09:15:30 UTC 2018
;; MSG SIZE  rcvd: 67

dnstools# dig auth.dev.myonlinedata.net

; <<>> DiG 9.11.3 <<>> auth.dev.myonlinedata.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 8944
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: f61f7286ff9a7433 (echoed)
;; QUESTION SECTION:
;auth.dev.myonlinedata.net.	IN	A

;; Query time: 3 msec
;; SERVER: 192.168.127.10#53(192.168.127.10)
;; WHEN: Tue Jul 31 09:15:36 UTC 2018
;; MSG SIZE  rcvd: 66
```
</details>
Dump: https://securisync.intermedia.net/im/s/oj7x1pMWCtmP2yEhQiYMlz000fc297

From dump it is clear that upstream DNS 10.9.0.11 was responding with FORMERR.
`/etc/resolv/conf` has 3 IPs and issue is reproducible each time coredns making request to 10.9.0.11 (some Windows AD DC)
But if i do same requests right from Kubernetes host 192.168.0.7 it always succeeds:

<details><summary>Same from host:</summary>

```
aryabov@debian:~$ dig auth.dev.myonlinedata.net @10.9.0.10

; <<>> DiG 9.10.3-P4-Debian <<>> auth.dev.myonlinedata.net @10.9.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37798
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;auth.dev.myonlinedata.net.	IN	A

;; ANSWER SECTION:
auth.dev.myonlinedata.net. 34604 IN	A	10.99.133.204

;; Query time: 1 msec
;; SERVER: 10.9.0.10#53(10.9.0.10)
;; WHEN: Tue Jul 31 02:21:53 PDT 2018
;; MSG SIZE  rcvd: 70

aryabov@debian:~$ dig auth1.dev.myonlinedata.net @10.9.0.10

; <<>> DiG 9.10.3-P4-Debian <<>> auth1.dev.myonlinedata.net @10.9.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31989
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;auth1.dev.myonlinedata.net.	IN	A

;; ANSWER SECTION:
auth1.dev.myonlinedata.net. 85969 IN	A	10.99.133.204

;; Query time: 1 msec
;; SERVER: 10.9.0.10#53(10.9.0.10)
;; WHEN: Tue Jul 31 02:21:58 PDT 2018
;; MSG SIZE  rcvd: 71

aryabov@debian:~$ dig auth2.dev.myonlinedata.net @10.9.0.10

; <<>> DiG 9.10.3-P4-Debian <<>> auth2.dev.myonlinedata.net @10.9.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12249
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;auth2.dev.myonlinedata.net.	IN	A

;; ANSWER SECTION:
auth2.dev.myonlinedata.net. 86399 IN	A	10.99.133.204

;; Query time: 180 msec
;; SERVER: 10.9.0.10#53(10.9.0.10)
;; WHEN: Tue Jul 31 02:22:01 PDT 2018
;; MSG SIZE  rcvd: 71

aryabov@debian:~$ dig auth3.dev.myonlinedata.net @10.9.0.10

; <<>> DiG 9.10.3-P4-Debian <<>> auth3.dev.myonlinedata.net @10.9.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13340
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;auth3.dev.myonlinedata.net.	IN	A

;; ANSWER SECTION:
auth3.dev.myonlinedata.net. 86400 IN	A	10.99.133.204

;; Query time: 180 msec
;; SERVER: 10.9.0.10#53(10.9.0.10)
;; WHEN: Tue Jul 31 02:22:05 PDT 2018
;; MSG SIZE  rcvd: 71
```
</details>
Dump: https://securisync.intermedia.net/im/s/me4yYGKpTyFJgHbvxPa5SI000fc297

Request flags in the second dump looks the same as in first one.
What could be the issue? As other domains resolves at 10.9.0.11 successfully by coredns.
For now have to remove this IP from `resolv.conf`

**Comment by rdrozhdzh** [comment]
just found a link to https://kevinlocke.name/bits/2017/01/20/formerr-from-microsoft-dns-server-for-dig/
Can this be related to our problem?

**Comment by miekg** [comment]
Thanks for the details!

FORMERR on edns can be a possibility, but we don't use funky options, just
the normal standard ones-this could still be an issue, but would weird.

Glad 1.2.0 didn't fix it, because they would be super strange.

**Comment by miekg** [comment]
We should probably retry without edns if we get FORMERR from an upstream.

**Comment by zloo** [comment]
I'm not sure if working around upstream server issues is the correct thing to do. That could lead down a rabbit hole, which lead to some other DNS servers dropping support for these workaround, as I linked before - https://dnsflagday.net/ . If you still want to workaround these issues, i think it shouldn't be the default, but something explicit in the configuration, like `workaroundBrokenUpstreamServers`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>I'm not sure if working around upstream server issues is the correct thing to do. That could lead down a rabbit hole, which lead to some other DNS servers dropping support for these workaround, as I linked before - https://dnsflagday.net/ . If you still want to workaround these issues, i think it shouldn't be the default, but something explicit in the configuration, like `workaroundBrokenUpstreamServers`

If this FORMERR thing tied to Windows upstreams? Or is it a more general 
problem?

The DNS spec actually has text that you should retry without EDNS on FORMERR, so 
it's not super whacky.

**Comment by zloo** [comment]
our upstream resolvers run on linux, altough they do resolve anything on the internet, so they could be reaching out to windows servers. the first hop is always linux, so the issue should not be tied to windows upstreams

**Comment by krzysztof-bronk** [comment]
Ours are Windows indeed

**Comment by miekg** [comment]
this will be fun then: https://ednscomp.isc.org/compliance/summary.html

Can some of you run through that last and report back what these servers do?

**Comment by zloo** [comment]
hello again,

my last followup, as I'm leaving the company tomorrow: since running 1.2.0, the issue never manifested

my colleagues are monitoring the issue and if it resurfaces, they should report here.

we're also in the process of migrating our upstream dns servers to other software for unrelated reasons, so if our upstream DNS was causing these issues, it should also disappear soon.

thank you everyone for your help.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Forward plugi..." ]
>hello again,
>
>my last followup, as I'm leaving the company tomorrow: since running 1.2.0, the issue never manifested
>
>my colleagues are monitoring the issue and if it resurfaces, they should report here.
>
>we're also in the process of migrating our upstream dns servers to other software for unrelated reasons, so if our upstream DNS was causing these issues, it should also disappear soon.
>
>thank you everyone for your help.

thanks for pinging back, appreciated.

**Comment by miekg** [comment]
Haven't seen this coming back. closing.

**Comment by UladzimirTrehubenka** [comment]
@miekg  We see the issue again (with CoreDNS 1.3.1), BTW forward.go should be fixed (missing Id param):
-debug.Hexdumpf(ret, "Wrong reply for id: %d, %s/%d", state.QName(), state.QType())
+debug.Hexdumpf(ret, "Wrong reply for id: %d, %s %d", ret.Id, state.QName(), state.QType())

**Comment by miekg** [comment]
Please send a small pr for that.

A reproducible test case would help, now its just shooting in the dark

**Comment by rdrozhdzh** [comment]
see related issue #2636
