### ISSUE TITLE
question: reverse lookup zone management

### ISSUE THREAD

**Issue by greenpau** [coredns/coredns#1909]
What could be the approach to manage reverse lookup zones in the following scenario?
* multiple compute domains, i.e. different consul datacenter/clusters
* IP address space is crossing  compute domain boundaries, e.g. 10.1.1.0/24 may reside in multiple compute domains

One way is to consolidate all of PTR records in a zone file and refresh that zone file.

Any other suggestions?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] question: reverse..." ]
>What could be the approach to manage reverse lookup zones in the following scenario?
>* multiple compute domains, i.e. different consul datacenter/clusters
>* IP address space is crossing  compute domain boundaries, e.g. 10.1.1.0/24 may reside in multiple compute domains
>
>One way is to consolidate all of PTR records in a zone file and refresh that zone file.
>
>Any other suggestions?

What are you looking for; how to implement it (i.e. zone file, database)? Or 
more on how to manage it?

If you can manage to make the reverse unique per compute domain you can get away 
with the normal DNS delegations...


/label: question

**Comment by greenpau** [comment]
> What are you looking for; how to implement it (i.e. zone file, database)? Or

@miekg , thank you for the question! I have IP/name in MongoDB. Perhaps there is mongodb backend plugin of some sorts? It would be neat to have a dynamic lookup by querying a db.

> If you can manage to make the reverse unique per compute domain ...
 
@miekg , unfortunately not :-(

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] question: rev..." ]
>> What are you looking for; how to implement it (i.e. zone file, database)? Or
>
>@miekg , thank you for the question! I have IP/name in MongoDB. Perhaps there is mongodb backend plugin of some sorts? It would be neat to have a dynamic lookup by querying a db.

That should not be too hard, i.e. I whipped up a redis shared cache thing a 
while back. So it should not be too hard to make a plugin that talks to mongo.

**Comment by greenpau** [comment]
> That should not be too hard, i.e. I whipped up a redis shared cache thing a while back. So it should not be too hard to make a plugin that talks to mongo.

@miekg , I think you just gave me a better idea. In theory, compute domains (e.g. different k8s clusters) could send IP address assignment to `redis`. Then, `coredns` could pick it up from there. Is that what you did?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] question: rev..." ]
>> That should not be too hard, i.e. I whipped up a redis shared cache thing a while back. So it should not be too hard to make a plugin that talks to mongo.
>
>@miekg , I think you just gave me a better idea. In theory, compute domains (e.g. different k8s clusters) could send IP address assignment to `redis`. Then, `coredns` could pick it up from there. Is that what you did?

No, this only caches, but feel free to fork and make it work for your use-case.

**Comment by greenpau** [comment]
@miekg , will check [it](https://github.com/miekg/redis) out 👍
