### ISSUE TITLE
metadata variables

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1911]
The variables defined in the variables package are thin wrapper over request.Request. So now we created 2 ways to access them.

Also every plugin already have access to those value because they have the request and response writer, I don't consider this metadata.

This can only create confusion, hence I propose the variables package is removed.

**Comment by fturib** [comment]
In that case we need to reintegrate into the Rewrite plugin to no break compatibility.

**Comment by fturib** [comment]
Maybe we can keep the pkg/variables but no add these variables to Metadata : that let ability for plugins that want a generic process of the all information to have an easy access and a standard name for those variables.

I mean in that case, plugins that needs to see those variables as metadata can just merge the two sets locally.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] metadata vari..." ]
>In that case we need to reintegrate into the Rewrite plugin to no break compatibility.

for now, yes.

**Comment by miekg** [comment]
closed via 99800a68
