### ISSUE TITLE
Stub zones don't work

### ISSUE THREAD

**Issue by kdima** [coredns/coredns#192]
We tried running coredns with stubzones enabled but they did not get picked up. After some investigation we found the following issue.
https://github.com/miekg/coredns/blob/master/middleware/etcd/stub.go#L16 is operating on the value receiver. So when a new stubzone is discovered it is added to a different instance of Etcd.

It is possible to confirm it by checking the memory addresses of Etcd inside https://github.com/miekg/coredns/blob/master/middleware/etcd/stub.go#L16 and inside https://github.com/miekg/coredns/blob/master/middleware/etcd/handler.go#L13 they will be different.

**Comment by miekg** [comment]
A (maybe) less hacky alternative: #198
Still lacks a test case, because it is somewhat non-trivial. Could you check if this works for you?

**Comment by miekg** [comment]
This is working - could still use a test though, but closing for now.
