### ISSUE TITLE
document watch feature

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1924]
@johnbelamaric can you document the watch feature ... somewhere?
We also need a blurp in the release docs: https://github.com/coredns/coredns/wiki/CoreDNS-1.2.0-Release-Notes

**Comment by johnbelamaric** [comment]
Yes, will do. Probably not till tomorrow though. When are you thinking to release? I also want to rework the README for metadata.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] document watc..." ]
>Yes, will do. Probably not till tomorrow though. When are you thinking to release? I also want to rework the README for metadata.

No, there is no rush. No immediate plan for a release.

**Comment by miekg** [comment]
I'm planning to remove the watch, when it comes back these things need to be taking care off.
