### ISSUE TITLE
Switch docker image to use alpine

### ISSUE THREAD

**Issue by stamm** [coredns/coredns#1926]
Hi! I've been using coredns in my new k8s cluster for a while.

Sometimes I needed to login in container with coredns to test some network issue. But I couldn't do it, because of scratch.
And I have suggestion: maybe you can change docker image from using scratch to alpine?

**Comment by chrisohaver** [comment]
We recently moved away from alpine.  #1843.
It's unlikely that we will move back to alpine at this time.

**Comment by stamm** [comment]
Ok, I get you.
Thanks for the answer.
