### ISSUE TITLE
Differences between gorouine in setup function and onStartup callback

### ISSUE THREAD

**Issue by jiachengxu** [coredns/coredns#1927]
Hi,
I am a little bit confused about the goroutine in `setup` function of `setup.go` and `onStartup`  callback of `*caddy.Controller`. For example:
```
func setup(c *caddy.Controller) error {
    go func() {
        do something...
    }()

    ...
}
```
```
func setup(c *caddy.Controller) error {
    c.OnStartup(func() error {
        do something...
    }
    return nil
    })

    ...
}
```
What is the difference between the two scenarios?  In my opinion, the `setup` function will be called only once (is this correct?),  but the `OnStartup` callback will also be called when the server restarts.

Thanks in advance,
Jiacheng

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Differences betwe..." ]
>Hi,
>I am a little bit confused about the goroutine in `setup` function of `setup.go` and `onStartup`  callback of `*caddy.Controller`. For example:
>```
>func setup(c *caddy.Controller) error {
>    go func() {
>        do something...
>    }()
>
>    ...
>}
>```
>```
>func setup(c *caddy.Controller) error {
>    c.OnStartup(func() error {
>        do something...
>    }
>    return nil
>    })
>
>    ...
>}
>```
>What is the difference between the two scenarios?  In my opinion, the `setup` function will be called only once (is this correct?),  but the `OnStartup` callback will also be called when the server restarts.

The setup function is called for every occurence of (in this case) plugin name, 
so yes. OnStartup and OnRestart are called on server restarts.

/Miek

/label: question

**Comment by jiachengxu** [comment]
> The setup function is called for every occurence of (in this case) plugin name,
so yes. OnStartup and OnRestart are called on server restarts.

Yes...I am still not confident about that, so actually when the server starts/restarts the `setup` function will not be called?
And also, will the `setup` function be called before the server starts? (I guess it is like a setup step, in this step,  everything is configured(for example, we can configure what should be invoked when the server starts by using the OnStartup callback, and also other callbacks), then the server starts. 

Thanks,
Jiacheng

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Differences b..." ]
>> The setup function is called for every occurence of (in this case) plugin name,
>so yes. OnStartup and OnRestart are called on server restarts.
>
>Yes...I am still not confident about that, so actually when the server starts/restarts the `setup` function will not be called?

uh, yeah the corefile is reparsed on restarts as well, as it may have changed.

/Miek

--
Miek Gieben

**Comment by jiachengxu** [comment]
Ok, thanks!
