### ISSUE TITLE
zones expire on secondary

### ISSUE THREAD

**Issue by Isolus** [coredns/coredns#1931]
I'm using CoreDNS as a secondary DNS server (with plugin/secondary).
If I just wait without touching a zone file or coredns, the zone expires on the secondary after the time given in the SOA record.

Looking at `plugin/file/secondary.go` this behaviour seems to be a result of the `z.shouldTransfer()` checks. If the check returns "no", nothing happens (but we need to reset the tickers).

**Comment by miekg** [comment]
yep, the expire needs to be restarted on every refresh (regardless if we transfer).

Do you have a PR?

**Comment by miekg** [comment]
fixed via #1933
