### ISSUE TITLE
plugin/forward: proposal to add "prefer_udp" option

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#1937]
Currently we have a "force_tcp" option in forward plugin for using TCP as a transport to upstream server even when the request comes in over UDP
I propose to add a similar option for using UDP even in case if incoming request was received by TCP. This could give some benefits in following configuration which we use in our company

**client** ---udp--> **coredns1/forward** ---tls--> **coredns2/forward** --------> **resolver**

In current implementation the query from coredns2 to resolver is always sent over TCP, because coredns2 receives it from TCP (TLS) channel, though, the original query is sent by client via UDP. I.e. we establish a lot of tcp connections to external server and this is a problem, because resolvers may have some limitations related to incoming/outgoing TCP connections (e.g. number of simultaneous connections). Also communication over UDP would likely be faster than TCP

So, when "prefer_udp" option is configured, the forward plugin will first try sending a query to upstream via UDP (in case if query size is not too big). If resolver returns the response with Truncated flag set, than _the forward plugin_ will resend the query to resolver via TCP.

Of course, there may be some overhead in case if original client query was knowingly sent via TCP (because UDP was not suitable for this query). In this case forward might send extra unneeded UDP queries. It would be nice if forward could know the original client protocol to avoid sending useless queries, but I'm not sure if this is possible

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/forward: p..." ]
>Currently we have a "force_tcp" option in forward plugin for using TCP as a transport to upstream server even when the request comes in over UDP
>I propose to add a similar option for using UDP even in case if incoming request was received by TCP. This could give some benefits in following configuration which we use in our company
>
>**client** ---udp--> **coredns1/forward** ---tls--> **coredns2/forward** --------> **resolver**
>
>In current implementation the query from coredns2 to resolver is always sent over TCP, because coredns2 receives it from TCP (TLS) channel, though, the original query is sent by client via UDP. I.e. we establish a lot of tcp connections to external server and this is a problem, because resolvers may have some limitations related to incoming/outgoing TCP connections (e.g. number of simultaneous connections). Also communication over UDP would likely be faster than TCP
>
>So, when "prefer_udp" option is configured, the forward plugin will first try sending a query to upstream via UDP (in case if query size is not too big). If resolver returns the response with Truncated flag set, than _the forward plugin_ will resend the query to resolver via TCP.
>
>Of course, there may be some overhead in case if original client query was knowingly sent via TCP (because UDP was not suitable for this query). In this case forward might send extra unneeded UDP queries. It would be nice if forward could know the original client protocol to avoid sending useless queries, but I'm not sure if this is possible

This is a valid request. Should we name it `force_udp`? Or does that fully 
describe it?

**Comment by rdrozhdzh** [comment]
Initially, I also thought of `force_udp`. However, we cannot force UDP for _all_ queries unlike forcing TCP. That's why I'm proposing `prefer_udp`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>Initially, I also thought of `force_udp`. However, we cannot force UDP for _all_ queries unlike forcing TCP. That's why I proposing `prefer_udp`

fair enough

**Comment by miekg** [comment]
Closed via #1944
