### ISSUE TITLE
forward: ignore nameserver from resolv.conf

### ISSUE THREAD

**Issue by sascha-andres** [coredns/coredns#1938]
I like CoreDNS to forward to DHCP servers retrieved by DHCP. But I also want to have CoreDNS as the first nameserver in /etc/resolv.conf. How can I tell CoreDNS to ignore 127.0.0.1 as a forwarder?

**Comment by sascha-andres** [comment]
Found #1647

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] forward: ignore n..." ]
>I like CoreDNS to forward to DHCP servers retrieved by DHCP. But I also want to have CoreDNS as the first nameserver in /etc/resolv.conf. How can I tell CoreDNS to ignore 127.0.0.1 as a forwarder?

if you just write the dhcp nameservers to a difference file and point the 
forwarder to that?

**Comment by sascha-andres** [comment]
@miekg  Thought about that, but I switch networks frequently so I would need to change that file every time. Did not found a way to tell Ubuntu to generate a resolv.dhcp.conf or something like this

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] forward: igno..." ]
>@miekg  Thought about that, but I switch networks frequently so I would need to change that file every time. Did not found a way to tell Ubuntu to generate a resolv.dhcp.conf or something like this

Ubuntu just uses ISC dhcp client, there's a bunch of scripts /etc/dhcp (IIRC), 
you should be able to hook into that.
