### ISSUE TITLE
Create cname to different domain

### ISSUE THREAD

**Issue by stamm** [coredns/coredns#1940]
For example I need to answer for domains ***.k8s** (for example: **service.ns.k8s**, **test.k8s**) with ips under **l5d.l5d-system.svc.cluster.local** in kubernetes cluster.
```
$ nslookup l5d.l5d-system.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   l5d.l5d-system.svc.cluster.local
Address: 10.97.186.66
```

I want to get answer like this:
```
$ nslookup test.k8s
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   test.k8s
Address: 10.97.186.66
```

I don't want to harcode ip, like this:
```
template ANY A test {
  answer  "{{ .Name }} 60 IN A 10.97.186.66"
}
```

How can I do it?
I tried different approaches:
1) Tried template, but it doesn't work:

```
template ANY A test {
  answer  "{{ .Name }} 60 IN A l5d.l5d-system.svc.cluster.local"
}
```

and this:

```
template ANY CNAME test {
  answer  "{{ .Name }} 60 IN CNAME l5d.l5d-system.svc.cluster.local"
}
```

2) Secondly I tried to use rewrite

```
rewrite name regex ^(.+)\.k8s\.$ l5d.l5d-system.svc.cluster.local
```

but response is not for domain test.k8s:

```
nslookup test.k8s
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   l5d.l5d-system.svc.cluster.local.-test
Address: 10.97.186.66
```

I tried to add answer block, but I can't get origin domain in answer block

```
rewrite stop {
  name regex ^(.+)\.k8s\.$ l5d.l5d-system.svc.cluster.local
  answer name .* {0}-test
}
```

So, I can't do anything with it

```
$ ping test.k8s
ping: unknown host
$ curl test.k8s
curl: (6) Could not resolve host: test.k8s
```

How I can I create workaround for this behavior?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Create cname to d..." ]
>I don't want to harcode ip, like this:
>```
>template ANY A test {
>  answer  "{{ .Name }} 60 IN A 10.97.186.66"
>}
>```

So this works?

>```
>template ANY A test {
>  answer  "{{ .Name }} 60 IN A l5d.l5d-system.svc.cluster.local"
>}
>```

And l5d.l5d... isn't resolved properly? Do you have have `upstream` enabled in 
your config?

/plugin: rewrite
/plugin: template
/label: question

**Comment by stamm** [comment]
> So this works?
Yeas, template with `answer  "{{ .Name }} 60 IN A 10.97.186.66"` works

> And l5d.l5d... isn't resolved properly? Do you have have `upstream` enabled in
your config?

You are right! I tried upstream and it works! But you need to answer for both A and CNAME request.

General I've got this configuration:
```
.:53 {
	reload 5s
	log
	errors
	health
	template ANY A k8s {
		match "^([^.]+)\.([^.]+)\.k8s\.$"
		answer "{{ .Name }} 60 IN CNAME l5d.l5d-system.svc.cluster.local"
		upstream 127.0.0.1:53
	}
	template ANY CNAME k8s {
		match "^([^.]+)\.([^.]+)\.k8s\.$"
		answer "{{ .Name }} 60 IN CNAME l5d.l5d-system.svc.cluster.local"
		upstream 127.0.0.1:53
	}
	kubernetes cluster.local in-addr.arpa ip6.arpa {
			pods insecure
			upstream
			fallthrough in-addr.arpa ip6.arpa
	}
	prometheus :9153
	proxy . /etc/resolv.conf
	cache 30
}
```

Thanks for help!
But maybe add this to documentation, like list of howtos?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Create cname ..." ]
>Thanks for help!
>But maybe add this to documentation, like list of howtos?

Feel free to open a PR to add this non-working + fix to the example section of 
template/README.md
