### ISSUE TITLE
Error building due to genproto

### ISSUE THREAD

**Issue by sssilver** [coredns/coredns#1942]
Hi,

Through Golang's `dep` we depend on CoreDNS, which depends on google.golang.org/genproto/googleapis/rpc/status. When building our project, now compilation fails with:

> `../../vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:111:28: undefined: proto.InternalMessageInfo`

What's the remedy for this?

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Error building du..." ]
>Hi,
>
>Through Golang's `dep` we depend on CoreDNS, which depends on google.golang.org/genproto/googleapis/rpc/status. When building our project, now compilation fails with:
>
>> `../../vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:111:28: undefined: proto.InternalMessageInfo`
>
>What's the remedy for this?

proto.InternalMessageInfo is defined in 
vendor/github.com/golang/protobuf/proto/lib.go

% grep InternalMessageInfo lib.go
// InternalMessageInfo is a type used internally by generated .pb.go files.
type InternalMessageInfo struct {

which is also vendored, so I don't know.

/Miek

/label: question
