### ISSUE TITLE
Fallback if forward fails

### ISSUE THREAD

**Issue by DaspawnW** [coredns/coredns#1945]
In DNSMASQ /kubedns I implemented a solution to use a /etc/k8s/hosts/hostsfile if our DNS Servers are not present (I know this should never happen, but it does).

So to let it work in DNSMASQ I added an empty hosts file that can be updated as configmap in kubernetes
```
--addn-hosts=/etc/k8s/hosts/hostsfile
--server=/<our-internal-root-domain>/<ip-1>
--server=/<our-internal-root-domain>/<ip-2>
```
If we have an incident we can manually update the configmap and add all our hosts. Then DNS will work again. This is only relevant for some internal domains that are well known.

So my idea is to do this also in CoreDNS I've created a server block that listens for our domain and forwards to the dns server.
```
    <our-internal-root-domain>:53 {
        log
        forward . <ip-1> <ip-2>
        cache 300
    }
```

Is it possible to do a fallback to the hostsfile if the forwarders are not present and how to handle it if it's not possible.
The old solution with DNSMASQ had the advantage, that in case of an incident we simply updated the configmap and restarted kube-dns. I think in CoreDNS we have to change the Corefile then?

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Fallback if forwa..." ]
>In DNSMASQ /kubedns I implemented a solution to use a /etc/k8s/hosts/hostsfile if our DNS Servers are not present (I know this should never happen, but it does).

Wait, with static name in them?

>So to let it work in DNSMASQ I added an empty hosts file that can be updated as configmap in kubernetes
>```
>--addn-hosts=/etc/k8s/hosts/hostsfile
>--server=/<our-internal-root-domain>/<ip-1>
>--server=/<our-internal-root-domain>/<ip-2>
>```
>If we have an incident we can manually update the configmap and add all our hosts. Then DNS will work again. This is only relevant for some internal domains that are well known.
>
>So my idea is to do this also in CoreDNS I've created a server block that listens for our domain and forwards to the dns server.
>```
>    <our-internal-root-domain>:53 {
>        log
>        forward . <ip-1> <ip-2>
>        cache 300
>    }
>```
>
>Is it possible to do a fallback to the hostsfile if the forwarders are not present and how to handle it if it's not possible.
>The old solution with DNSMASQ had the advantage, that in case of an incident we simply updated the configmap and restarted kube-dns. I think in CoreDNS we have to change the Corefile then?

It's not possible as a fallback (and I would caution at using fallbacks only in 
emergency, because those code paths are then never regularly exercised). 

What you can do in CoreDNS is to use the host plugin, point it to a hostfile and 
add `fallthrough` to it's config. This does mean CoreDNS will always first check 
the hostfile before forwarding the query.

/label: question
/plugin: forward

**Comment by DaspawnW** [comment]
Hi @miekg ,

yes you are right, it sounds a bit strange but in our cloud environment we have dns forwarder and they are sometimes have outtakes, then we can use "static" one we generate by our own and for such an outtake it's enough ;-)

Thank you very much for your help, it worked perfect!

```
    <our-internal-root-domain>:53 {
        errors
        hosts /etc/k8s/hosts/hostsfile {
            fallthrough
        }
        forward . <ip-1> <ip-2>
        cache 300
    }
```
