### ISSUE TITLE
Publish sha256sums on release

### ISSUE THREAD

**Issue by fntlnz** [coredns/coredns#1964]
Since on release binaries for various platforms and architectures are published, it's important to have a declared sha256sum for each binary in order to be able to verify the downloaded archive.

The [`coredns-bin`](https://aur.archlinux.org/packages/coredns-bin/) package on aur would directly benefit from this for example.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Publish sha256sum..." ]
>Since on release binaries for various platforms and architectures are published, it's important to have a declared sha256sum for each binary in order to be able to verify the downloaded archive.
>
>The [`coredns-bin`](https://aur.archlinux.org/packages/coredns-bin/) package on aur would directly benefit from this for example.

I was pondering doing this already, thanks for filing an issue. I wonder if your 
current release automation (Makefile.release) will just upload sha256 files if 
we add them.

**Comment by yongtang** [comment]
👍 for sha256sum release

**Comment by fntlnz** [comment]
@miekg that's right, now what it does is that it downloads the binary to hash it but it's not just unpractical I don't have any way to check that I'm publishing a safe release.

**Comment by yongtang** [comment]
k8s add sha256 in the description:
https://github.com/kubernetes/kubernetes/releases

I am wondering if we should add sha256 in the description, or add an additional file coredns-1.xxx.sha256 file to achieve that?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Publish sha25..." ]
>k8s add sha256 in the description:
>https://github.com/kubernetes/kubernetes/releases
>
>I am wondering if we should add sha256 in the description, or add an additional file coredns-1.xxx.sha256 file to achieve that?

I find separate files easier to deal with as you then don't have to deal with 
parsing some description. We also have way more tar files...

**Comment by fntlnz** [comment]
Awesome @miekg !
