### ISSUE TITLE
[kubernetes] Accept Kubeconfig File for Kubernetes Auth

### ISSUE THREAD

**Issue by Rigdon** [coredns/coredns#1965]
Currently the kubernetes plugin only accepts separate cert, key, and cacert files for authentication to remote Kubernetes clusters. Many other applications and services accept a valid Kubeconfig file for cross-cluster authentication and it would be very convenient to be able to authenticate the same way. This also helps solve the issue that currently it is necessary to issue long-lived certificates and tie them into RBAC policies in the remote Kubernetes cluster. This feature would allow users to create Service Accounts instead.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] [kubernetes] Acce..." ]
>and services accept a valid Kubeconfig file for cross-cluster authentication 
>and it would be very convenient to be able to authenticate the same way. This 

/label: plugin/kubernetes
/label: enhancement

**Comment by chrisohaver** [comment]
I suppose the option would require specifying the context, as well as the path to the kubeconfig file. For example...

~~~
kubernetes cluster.local  {
    kubeconfig context path-to-kubeconfig
}
~~~

**Comment by johnbelamaric** [comment]
#2053
