### ISSUE TITLE
etcd: resolving takes up to 5 seconds

### ISSUE THREAD

**Issue by f0** [coredns/coredns#197]
Hi, 

quering a SRV record from coredns with etcd backend takes between 20 and 5000 ms  (random)
quering an A record is always fast (~15ms)
using etcdctl ls --recursive for the tree take ~10ms
It seems  there is some performace problem or is this expected ?
(with caching enabled, the forst request is slow, then some are really fast (0ms), and the again one slow)

```
dig -t SRV nodes.sysmon.local @localhost

; <<>> DiG 9.10.3-P4 <<>> -t SRV nodes.sysmon.local @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42969
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 31, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nodes.sysmon.local.        IN  SRV

;; ANSWER SECTION:
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2577.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2607.example.net.
nodes.sysmon.local. 10  IN  SRV 10 3 9100 hw2067.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2140.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2612.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2581.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2617.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2621.example.net.
nodes.sysmon.local. 12  IN  SRV 10 3 9100 hw1950.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2613.example.net.
nodes.sysmon.local. 10  IN  SRV 10 3 9100 hw2614.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2620.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2580.example.net.
nodes.sysmon.local. 9   IN  SRV 10 3 9100 hw2606.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2419.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2615.example.net.
nodes.sysmon.local. 9   IN  SRV 10 3 9100 hw2619.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2583.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2582.example.net.
nodes.sysmon.local. 14  IN  SRV 10 3 9100 hw1951.example.net.
nodes.sysmon.local. 10  IN  SRV 10 3 9100 hw2618.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2579.example.net.
nodes.sysmon.local. 10  IN  SRV 10 3 9100 hw2421.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2575.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2420.example.net.
nodes.sysmon.local. 12  IN  SRV 10 3 9100 hw1927.example.net.
nodes.sysmon.local. 10  IN  SRV 10 3 9100 hw2616.example.net.
nodes.sysmon.local. 8   IN  SRV 10 3 9100 hw2584.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2578.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2605.example.net.
nodes.sysmon.local. 11  IN  SRV 10 3 9100 hw2576.example.net.

;; Query time: 5367 msec
;; SERVER: ::1#53(::1)
;; WHEN: Mon Aug 01 19:53:09 CEST 2016
;; MSG SIZE  rcvd: 892
```

regards f0

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] etcd: resolving tak..." ]

> Hi,
> 
> quering a SRV record from coredns with etcd backend takes between 10 and 5000 ms  (random)
> It seems  there is some performace problem or is this expected ?

Is see a lot of example.net answers? Is everything in etcd a local name or is
upstream resolving required?

Does debug queries https://miek.nl/2016/May/22/debug-queries-in-coredns-with-the-etcd-middleware/
shed any light?

Do you have tcp dumps?

/Miek

## 

Miek Gieben

**Comment by f0** [comment]
@miekg 
the names are modified (replaced the real domain by example.net.....)

but you point me in the right direction, after adding the upstream directive with the correct nameserver the time is down to ~80ms (without caching)

i do not have a tcpdump, but i can create one if nedded

but i think the problem is fixed with adding the correct upstream dns servers

regards f0

**Comment by miekg** [comment]
Yes, that makes sense. I wonder though if I could add something to debug queries to make this obvious that this is happening...

**Comment by f0** [comment]
@miekg  maybe a hint that the names are not resolving?

**Comment by miekg** [comment]
Yes, something like that. Should be fairly easy.
