### ISSUE TITLE
Same podIP for multi pods in the same cluster 

### ISSUE THREAD

**Issue by xiajidexue** [coredns/coredns#1970]
Cluster info:
Kubernetes: v11.1
CoreDNS: v1.1.4

![image](https://user-images.githubusercontent.com/6821543/42684011-83beaac2-86c1-11e8-9d37-852ad33ec548.png)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Same podIP for mu..." ]
>Cluster info:
>Kubernetes: v11.1
>CoreDNS: v1.1.4
>
>![image](https://user-images.githubusercontent.com/6821543/42684011-83beaac2-86c1-11e8-9d37-852ad33ec548.png)

/label: needs info
/plugin: kubernetes

**Comment by xiajidexue** [comment]
my mistake as missing flannel configuration in docker
