### ISSUE TITLE
hosts plugin is flapping in kubernetes deployment

### ISSUE THREAD

**Issue by wpalmeri** [coredns/coredns#1975]
In a kubernetes deployment, I would like coredns to serve `/etc/hosts` as well. The server is flapping between NXDOMAIN responses and successfully returning a record from the hosts file. This is a hard blocker on us migrating away from kube-dns, where dnsmasq will correctly serve up `/etc/hosts`. There are no useful indicators in the kube-dns logs. Caching disabled to verify the behavior. Any advice how to investigate further?

```
root@dnsutils-699457ff4-zpgb5:/# nslookup kube-worker02.qa2
Server:         192.168.255.10
Address:        192.168.255.10#53

Name:   kube-worker02.qa2
Address: XX.XX.XX.XX

root@dnsutils-699457ff4-zpgb5:/# nslookup kube-worker02.qa2
Server:         192.168.255.10
Address:        192.168.255.10#53

** server can't find kube-worker02.qa2: NXDOMAIN
```
Core file for reference:
```
Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local 192.168.255.0/24 {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough
        }
        hosts {
          fallthrough
        }
        proxy . /etc/resolv.conf
        prometheus :9153
        reload
        loadbalance
        log {
          class denial error
        }
    }
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] hosts plugin is f..." ]
>behavior. Any advice how to investigate further?

We re-read the host file every 5 seconds and it seems we read an empty file or 
something. To investigate further you will probably need to add some logging
to the host plugin to see what it actually reads.
(happy to take some of those log and convert them into log.Debug's to help to 
aid in future debugging)

/plugin: hosts
/label: bug

**Comment by wpalmeri** [comment]
A colleague figured it out. I simplified the above Corefile and was inadvertently mounting /etc/hosts to the same dir as the configmap and the two mounts were competing with each other 🙃. Thanks for the tip, more debug logging definitely would be appreciated in CoreDNS.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] hosts plugin ..." ]
>A colleague figured it out. I simplified the above Corefile and was inadvertently mounting /etc/hosts to the same dir as the configmap and the two mounts were competing with each other 🙃. Thanks for the tip, more debug logging definitely would be appreciated in CoreDNS.

Agreed, but I rather not sprinkle this randomly in places where *I* think it 
should be done. Do have any specific on what you would like to see outputted 
for such loggging?

**Comment by chrisohaver** [comment]
In this case perhaps a warning if, when hostfile is parsed it is not in the expected format.

**Comment by wpalmeri** [comment]
a debug log for number of entries in the host file would be super helpful too :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] hosts plugin ..." ]
>a debug log for number of entries in the host file would be super helpful too :)

https://github.com/coredns/coredns/pull/1985

/Miek

--
Miek Gieben
