### ISSUE TITLE
plugin/rewrite: set arbitrary TTL value

### ISSUE THREAD

**Issue by greenpau** [coredns/coredns#1981]
`consul` returns entries with TTL 0, i.e. no cache. Looking to rewrite the TTL to a value higher than 0. Currently, `plugin/rewrite` does not support it (or maybe it does).

Prior to modifying the `plugin/rewrite`, qq: does anyone have a way of modifying TTL value with another plugin?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/rewrite: s..." ]
>`consul` returns entries with TTL 0, i.e. no cache. Looking to rewrite the TTL to a value higher than 0. Currently, `plugin/rewrite` does not support it (or maybe it does).

but this is on the way back, i.e. replies from some upstream, so rewrite is of 
not use.

>Prior to modifying the `plugin/rewrite`, qq: does anyone have a way of modifying TTL value with another plugin?

you need a tiny new plugin that wraps the ResponseWriter and changes the TTL 
when it writes to the client. TTL code can copied/used from pkg/dnsutil/ttl.go

/Miek

--
Miek Gieben

**Comment by greenpau** [comment]
> but this is on the way back, i.e. replies from some upstream, so rewrite is of not use.

@miekg,  e.g., currently, `plugin/rewrite` matches on name and then changes name in the answer:

```
    rewrite stop {
        name regex (.*)-(us-west-1)\.coredns\.rocks {1}.service.{2}.consul
        answer name (.*)\.service\.(us-west-1)\.consul {1}-{2}.coredns.rocks
    }
```

When it comes to TTL, I think this could be implemented [here](https://github.com/coredns/coredns/blob/master/plugin/rewrite/reverter.go#L37). 🤔 💭

```
    rewrite continue {
        name regex (.*)-(us-west-1)\.coredns\.rocks {1}.service.{2}.consul
        answer ttl 15
    }
```

@miekg, what do you think about this? 

> you need a tiny new plugin that wraps the ResponseWriter and changes the TTL

@miekg , ack. ... more 🤔

**Comment by miekg** [comment]
Oh yes. You can do some noop rewrite and then adjust the ttl on the way
back. Should work as well.
