### ISSUE TITLE
plugin/metrics - plugin loose control of the listener after several reloads

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1982]
On Restart, plugin close the listener and set the uniqAddr to "todo" in order to be restarted on next "onStart: event.

But the SAME function to call is registered, which means on next "uniqAddr.ForEach" the function 'OnStart" of the now old plugin will be called, and the corresponding "onRestart" will never be called.

After 2 reloads, the Listener is no more closed.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/metrics - ..." ]
>On Restart, plugin close the listener and set the uniqAddr to "todo" in order to be restarted on next "onStart: event.
>
>But the SAME function to call is registered, which means on next "uniqAddr.ForEach" the function 'OnStart" of the now old plugin will be called, and the corresponding "onRestart" will never be called.
>
>After 2 reloads, the Listener is no more closed.

/label: bug
/plugin: reload

**Comment by fturib** [comment]
Easy way to fix this is to ensure that the Metrics that is shutingdown is releasing its token from UniqAddr

change : uniqAddr.Todo(m.Addr)
by : uniqAddr.Unset(m.Addr)

Then next instance of Metrics, at reload, will refill that uniqAddr with a todo.

**Comment by fturib** [comment]
NOTE: that code is in the PR #1969. But we need to keep only that change ... (make it simple and easy).

**Comment by calebice** [comment]
@fturib I am looking into this. It seems like the code changes required were incorporated into [#1969](https://github.com/coredns/coredns/pull/1969). It seems straightforward enough, but it might take me a little longer to get this set as a pull request. I intend to use this as an opportunity to dig around the code base.

**Comment by fturib** [comment]
@calebice : thanks!

**Comment by fturib** [comment]
@zacheddy is currently working it.

**Comment by ekleiner** [comment]
Note: I have opened an issue about adding OnRestartFailed() to caddy and plan to add it soon. So it may affect the decision about the fix for this bug. See: https://github.com/mholt/caddy/issues/2250

**Comment by fturib** [comment]
I assigned this Issue to me, but that is a placeholder for @ZachEddy
