### ISSUE TITLE
windows coredns etcdv3 failed to do Readme 

### ISSUE THREAD

**Issue by JaysLiang** [coredns/coredns#1984]
First I am sorry that I am noob about DNS. Here when I follow the Readme to start coredns with localhost:2379 etcd. then I use etcdctl version 3 to add  key value 
% etcdctl put /skydns/arpa/in-addr/10/0/0/127 '{"host":"reverse.skydns.local."}' 
% dig @localhost -x 10.0.0.127 +short 
nothing happened .so get rid of the "+short"
% dig @localhost -x 10.0.0.127
no answer . I am very confused! here is information
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;127.0.0.10.in-addr.arpa.       IN      PTR

;; AUTHORITY SECTION:
10.in-addr.arpa.        10800   IN      SOA     localhost. nobody.invalid. 1 3600 1200 604800 10800

**Comment by jiachengxu** [comment]
Can you provide more details please? i.e.,
- Which corefile did you use for starting your CoreDNS instance?
- Which port did your CoreDNS server listen on? (If you specify a port for your CoreDNS server, you should use `dig -p port @localhost -x 10.0.0.127 +short` instead.

**Comment by JaysLiang** [comment]
@JiachengXu  I just use default port 53. And I use this config file In Ubutun. Still get nothing.
Here is the config file. (Correct me if I'm wrong. Thanks!)
. {
        etcd skydns.local 10.0.0.0/24 {
                stubzones
                path /skydns
                endpoint http://localhost:2379
        }
        cache 160 skydns.local
        loadbalance
}

**Comment by JaysLiang** [comment]
@JiachengXu  I just look for other Issue. I find you commit this example. Is the config file setting wrong?

**Comment by jiachengxu** [comment]
Hey, I tested your Corefile on an Ubuntu (But I used 1053 port instead of 53 since I am not the root and cannot listen on 53) and it works. Can you specify a port to see if it works, please?  Thanks.
Also. can you do `etcdctl version` to make sure your API version is 3 or higher?

**Comment by JaysLiang** [comment]
@JiachengXu Maybe mysystem have some problem. I just use my anther server  centos. It works!!! I will recheck my ubutun and windows config. Thanks very much！

**Comment by jiachengxu** [comment]
Nice! Enjoy it!

**Comment by jiachengxu** [comment]
And can you post your solution here after you figure out the reason? It can be helpful for other people :)

**Comment by JaysLiang** [comment]
@JiachengXu  Ok, Ubutun is OK! I have find the reason! the etcdctl in window when put key, will delete quote. I think this is a bug of etcdctl. If I find the solution. I will comment here.
etcdctl put /skydns/arpa/in-addr/10/0/0/127 '{"host":"reverse.skydns.local."}'
### in linux 
/skydns/arpa/in-addr/10/0/0/127
{"host":"reverse.skydns.local."}
### on windows is like that
/skydns/arpa/in-addr/10/0/0/127
'{host:reverse.skydns.local.}'

**Comment by JaysLiang** [comment]
Here is solution on windows!  on windows use command should like that
### Windows cmd
etcdctl put /skydns/arpa/in-addr/10/0/0/127 {"""host""":"""reverse.skydns.local."""}
