### ISSUE TITLE
Adding NS Records to Kubernetes Zone

### ISSUE THREAD

**Issue by automaticserver** [coredns/coredns#1987]
As far as we can see there is no mechanism implemented in the case of serving a kubernetes zone to replicate that to other slaves. A BIND slave is during zone transfer responding, that the NS record is missing.

A manual AXFR request on that CoreDNS instance shows a SOA record and a lot of service record but no NS record - so I can confirm the message of BIND.

So how to deal with that situation? We want to publish the kubernetes internal zone with slave DNS servers. Can you fix that somehow and give a way to specify such records?

We're thinking of add a second layer of DNS which adds some entries and expose that to BIND. But that sounds really ugly.

manual AXFR:

```
$ dig @192.168.0.10 k8s-1.example.com AXFR | egrep "NS|SOA"
k8s-1.example.com.      0       IN      SOA     ns.dns.k8s-1.example.com. hostmaster.k8s-1.example.com. 1532073999 7200 1800 86400 30
k8s-1.example.com.      0       IN      SOA     ns.dns.k8s-1.example.com. hostmaster.k8s-1.example.com. 1532073999 7200 1800 86400 30
```

message BIND:

```
Jul 20 07:43:38 dns-24 named[589]: zone k8s-1.example.com/IN: has no NS records
Jul 20 07:43:38 dns-24 named[589]: transfer of 'k8s-1.example.com/IN' from 192.168.0.10#53: failed while receiving responses: bad zone
Jul 20 07:43:38 dns-24 named[589]: transfer of 'k8s-1.example.com/IN' from 192.168.0.10#53: Transfer status: bad zone
```

CoreDNS-Config (partially):
```
    .:53 {
        errors
        health
        kubernetes k8s-1.example.com in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
          transfer to 10.10.10.21
          transfer to 10.10.10.22
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```
`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Adding NS Records..." ]
>As far as we can see there is no mechanism implemented in the case of serving a kubernetes zone to replicate that to other slaves. A BIND slave is during zone transfer responding, that the NS record is missing.
>
>A manual AXFR request on that CoreDNS instance shows a SOA record and a lot of service record but no NS record - so I can confirm the message of BIND.
>
>So how to deal with that situation? We want to publish the kubernetes internal zone with slave DNS servers. Can you fix that somehow and give a way to specify such records?
>
>We're thinking of add a second layer of DNS which adds some entries and expose that to BIND. But that sounds really ugly.

NSD serves such zones just fine.

We can't just add records under the apex because this is not defined in the DNS 
spec for kubernetes. It may be easy to support something like:

~~~
cluster.local. IN NS kube-dns.kube-system.svc.cluster.local.
~~~

Except no such svc name is exported by default.

/plugin: kubernetes
/label: question

**Comment by automaticserver** [comment]
Hi Miek,

thank you for your quick reply. The DNS specification says the following:

https://tools.ietf.org/html/rfc2181#section-6

> 6.1. Zone authority
>
>   The authoritative servers for a zone are enumerated in the NS records
>   for the origin of the zone, which, along with a Start of Authority
>   (SOA) record are the mandatory records in every zone.

So if BIND fails to accept the zone it follows exactly the specification.

I would suggest to add a configuration statement inside of the CoreDNS to be able to specify required records. Even the SOA record should be part of that, cause there is no generic SOA for everybody and every use case.

However, I would be happy if there is some CoreDNS solution at all. The point with the feature of overwriting specific records inside a zone file doesn't work, cause the DNS slave requests a full zone transfer which have to include the NS record. It doesn't asks for a specific A or CNAME record, where you could then the use the fallthrough mechanism. Am I right with that?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Adding NS Rec..." ]
>Hi Miek,
>
>thank you for your quick reply. The DNS specification says the following:
>
>https://tools.ietf.org/html/rfc2181#section-6
>
>> 6.1. Zone authority
>>
>>   The authoritative servers for a zone are enumerated in the NS records
>>   for the origin of the zone, which, along with a Start of Authority
>>   (SOA) record are the mandatory records in every zone.
>
>So if BIND fails to accept the zone it follows exactly the specification.

yeah, sure. But if you expecting the DNS, as used in kubernetes, to be anything 
close to the DNS spec you're in for a hard time.

>I would suggest to add a configuration statement inside of the CoreDNS to be able to specify required records. Even the SOA record should be part of that, cause there is no generic SOA for everybody and every use case.

Hmmm, not sure about that. If we go that route it should be an endpoint that 
lives in the cluster and can be created/used by the normal k8s tools. Having 
part of this config live in coredns's configmap creates a weird split.

>However, I would be happy if there is some CoreDNS solution at all. The point with the feature of overwriting specific records inside a zone file doesn't work, cause the DNS slave requests a full zone transfer which have to include the NS record. It doesn't asks for a specific A or CNAME record, where you could then the use the fallthrough mechanism. Am I right with that?

fallthrough won't help here, because that data will never be included in the zone 
transfer.

As said, if you want to host the DNS data in a dns server NSD works perfectly 
fine right now. I don't see why we should change something

**Comment by automaticserver** [comment]
Hi Miek,

it is clear, that Kubernetes doesn't want to implement every DNS scenario/feature in the world. But in my opinion a required DNS entry (to be compatible to other DNS servers) should be there.

In my opinion it's not the task of Kubernetes itself to fullfill that. Today DNS is not very deep integrated in Kubernetes and as long it's in this way, the interfacing parts for DNS should provide the things, which are requested by the DNS specification.

For the SOA entry CoreDNS does it. What is missing to be able to configure that SOA entry and what is missing is to provide the NS record and to configure that. Because that stuff is special, the Kubernetes Plugin of CoreDNS should do that, provide a syntax to configure the stuff.

So a question would be: do you think it's possible to implement it there? Or do you have other suggestions? I mean: it's not possible for everyone to use NSD and NSD works cause it's not picky about the DNS specification (RFC).

**Comment by miekg** [comment]
So what would you propose as the mechanism for adding ns records and to
what name(s) should they point? Preferably this must work with dnssec as
well, so we need store dnskeys, and potentially DS records in the apex.

**Comment by automaticserver** [comment]
DNSSEC is an optional feature, especially for a authoritative DNS server. Nobody has to sign a zone.

Because the feature of NS/SOA is tightly coupled to the kubernetes area, I would recommend to add this as an configuration statement inside the context of the kubernetes plugin.

```
kubernetes k8s.example.com {
  soa ns1.example.com. info.example.com. 1532441718 7200 1800 86400 30
  ns ns1.example.com
  ns ns2.example.com
}
```

FYI: I've just tried with NSD a zone transfer and the transfer itself worked: but even if now the DNS zone is on another server, the zone is still invalid of course. So in fact that is not a real benefit. NSD on the other side seems to be a quiet dead project. Documentation is offline, commit rate is low.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Adding NS Rec..." ]
>DNSSEC is an optional feature, especially for a authoritative DNS server. Nobody has to sign a zone.
>
>Because the feature of NS/SOA is tightly coupled to the kubernetes area, I would recommend to add this as an configuration statement inside the context of the kubernetes plugin.
>
>```
>kubernetes k8s.example.com {
>  soa ns1.example.com. info.example.com. 1532441718 7200 1800 86400 30
>  ns ns1.example.com
>  ns ns2.example.com
>}
>```

that won't fly in the context of kubernetes, it needs to be dynamically
configured, backed/pointing by/to something running in the cluster.

As mentioned previously any solution needs to be dynamic and can't be staticly 
configured in the corefile.

You've now also created 2 new subdomains 'ns1' and 'ns2' that didn't exists
before (there is only 'svc' and 'pod'), that's also a major change. 

Futher more what should the IP address for ns1 and ns2 be?

>FYI: I've just tried with NSD a zone transfer and the transfer itself worked:
>but even if now the DNS zone is on another server, the zone is still invalid of
>course. So in fact that is not a real benefit. NSD on the other side seems to
>be a quiet dead project. Documentation is offline, commit rate is low.

NSD is a well maintained project and I hold it in high regard and I'm pleased to 
learn that it served the zone fine.

**Comment by miekg** [comment]
Using CRDs might work: https://github.com/coredns/coredns/issues/1999

**Comment by dionysius** [comment]
Wait a second, don't we just miss one entry we should know? I mean, assume following zone (real world example using kubeadm with kubernetes v1.11.1):

```
:~$ kubectl -n kube-system exec -ti coredns-78fcdf6894-slx9c -- dig AXFR cluster.local @localhost

; <<>> DiG 9.11.2-P1 <<>> AXFR cluster.local @localhost
;; global options: +cmd
cluster.local.		0	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1533652270 7200 1800 86400 30
kubernetes.default.svc.cluster.local. 0	IN A	10.96.0.1
kubernetes.default.svc.cluster.local. 0	IN SRV	0 100 443 kubernetes.default.svc.cluster.local.
_https._tcp.kubernetes.default.svc.cluster.local. 0 IN SRV 0 100 443 kubernetes.default.svc.cluster.local.
kube-dns.kube-system.svc.cluster.local.	0 IN A	10.96.0.10
kube-dns.kube-system.svc.cluster.local.	0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
_dns._udp.kube-dns.kube-system.svc.cluster.local. 0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
kube-dns.kube-system.svc.cluster.local.	0 IN A	10.96.0.10
kube-dns.kube-system.svc.cluster.local.	0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
_dns-tcp._tcp.kube-dns.kube-system.svc.cluster.local. 0	IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
tiller-deploy.kube-system.svc.cluster.local. 0 IN A 10.103.104.194
tiller-deploy.kube-system.svc.cluster.local. 0 IN SRV 0 100 44134 tiller-deploy.kube-system.svc.cluster.local.
_tiller._tcp.tiller-deploy.kube-system.svc.cluster.local. 0 IN SRV 0 100 44134 tiller-deploy.kube-system.svc.cluster.local.
cluster.local.		0	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1533652270 7200 1800 86400 30
;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Aug 07 14:35:39 UTC 2018
;; XFR size: 14 records (messages 1, bytes 1265)
```

The only thing missing is the NS record. Since core-dns is already a service (kubernetes.default.svc.cluster.local), the service clusterIP will already be correct (because coredns lists all services). So we should only have one more entry (which BTW have to come directly after SOA):

```
cluster.local.		0	IN	NS	kube-dns.kube-system.svc.cluster.local.
```

But then, what is the meaning of `ns.dns.cluster.local`, we could just add `kube-dns.kube-system.svc.cluster.local` there directly?

So I expect/assume this should be the correct and full transfer output:

```diff
:~$ kubectl -n kube-system exec -ti coredns-78fcdf6894-slx9c -- dig AXFR cluster.local @localhost

; <<>> DiG 9.11.2-P1 <<>> AXFR cluster.local @localhost
;; global options: +cmd
- cluster.local.		0	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1533652270 7200 1800 86400 30
+ cluster.local.		0	IN	SOA	kube-dns.kube-system.svc.cluster.local. hostmaster.cluster.local. 1533652270 7200 1800 86400 30
+ cluster.local.		0	IN	NS	kube-dns.kube-system.svc.cluster.local.
kubernetes.default.svc.cluster.local. 0	IN A	10.96.0.1
kubernetes.default.svc.cluster.local. 0	IN SRV	0 100 443 kubernetes.default.svc.cluster.local.
_https._tcp.kubernetes.default.svc.cluster.local. 0 IN SRV 0 100 443 kubernetes.default.svc.cluster.local.
kube-dns.kube-system.svc.cluster.local.	0 IN A	10.96.0.10
kube-dns.kube-system.svc.cluster.local.	0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
_dns._udp.kube-dns.kube-system.svc.cluster.local. 0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
kube-dns.kube-system.svc.cluster.local.	0 IN A	10.96.0.10
kube-dns.kube-system.svc.cluster.local.	0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
_dns-tcp._tcp.kube-dns.kube-system.svc.cluster.local. 0	IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
tiller-deploy.kube-system.svc.cluster.local. 0 IN A 10.103.104.194
tiller-deploy.kube-system.svc.cluster.local. 0 IN SRV 0 100 44134 tiller-deploy.kube-system.svc.cluster.local.
_tiller._tcp.tiller-deploy.kube-system.svc.cluster.local. 0 IN SRV 0 100 44134 tiller-deploy.kube-system.svc.cluster.local.
- cluster.local.		0	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1533652270 7200 1800 86400 30
+ cluster.local.		0	IN	SOA	kube-dns.kube-system.svc.cluster.local. hostmaster.cluster.local. 1533652270 7200 1800 86400 30
;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Aug 07 14:35:39 UTC 2018
;; XFR size: 14 records (messages 1, bytes 1265)
```

So followup question: How do we know who we (the coredns service) are? I think easy: [we get `{SVCNAME}...` environment info in pods](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables) which we use then to search ourself in the service list above:
```
:~$ kubectl -n kube-system exec -ti coredns-78fcdf6894-slx9c -- printenv | grep KUBE_DNS_SERVICE_HOST
KUBE_DNS_SERVICE_HOST=10.96.0.10
```

**Comment by chrisohaver** [comment]
> So followup question: How do we know who we (the coredns service) are? I think easy: we get {SVCNAME}... environment info in pods which we use then to search ourself in the service list above:

Currently we only keep pod information when we enable `pods verified` (which maintains a pod cache and watch).  But we don't enable this by default due to increased memory requirements.   We could look this up once at start up, without monitoring pods via `pods verified` mode.  Technically the service -> pod selectors could change after coredns starts, but I think that would be atypical.

In fact, I think we used to do this... but it may have been refactored out.

**Comment by dionysius** [comment]
To save memory, it can also be a well-known name and well-known namespace, which is static and configured in the `DeploymentSpec.Template.Env` or other possible options. Similiar to the service name "kube-dns" in namespace "kube-system" defined in the [deployment](https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L138). When one uses that deployment yaml, it ensures the names will match (the namespace though can be inherited and found out from the pod itself, because it will still be in that)

**Comment by chrisohaver** [comment]
> In fact, I think we used to do this... but it may have been refactored out.

Actually what I was thinking of was that we used create an A record for "ns.dns.cluster.local." that pointed to the dns service cluster IP.   So, not related.

**Comment by chrisohaver** [comment]
`NS` record and `A` record for the name server were already served by kubernetes plugin, but not working quite right. However, they were omitted from the transfer response.

I've got this fixed up and working locally.  Just need to pretty it up a bit and will send PR soon.

**Comment by miekg** [comment]
this would actually be nice to merge - if there is anything

**Comment by chrisohaver** [comment]
I was diverted to other tasks, and then the whole memory thing... i'll try to dig this back up.

**Comment by miekg** [comment]
is this relevant or can it be closed?
