### ISSUE TITLE
dnsserver.Port behaves differently

### ISSUE THREAD

**Issue by jiachengxu** [coredns/coredns#1988]
Hey,
I am trying to get the port which my CoreDNS server is specified to listen on in the  `setup` function of my plugin, and what is the appropriate way to do that?

I tried to use `dnsserver.Port` to do that, but it behaves differently as following:
- If I specify the port in the Corefile, `dnsserver.Port` always gives me port 53.
- If I specify the port in the command line, i.e., `--dns.port=1053`, then it gives me 1053.

Did I miss something?
Thanks,
Jiacheng

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] dnsserver.Port be..." ]
>Hey,
>I am trying to get the port which my CoreDNS server is specified to listen on in the  `setup` function of my plugin and, and what is the property way to do that?

You can't do that from the plugin. This is done by the server "framework" on 
startup and you're not supposed to override that.

/Miek

--
Miek Gieben

**Comment by jiachengxu** [comment]
Actually, I don't want to override it, I just want to get it, for example, print it. But it behaves differently if I specify the port in different ways(i.e., in command line and a corefile). So do you mean that I even can not get it?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] dnsserver.Por..." ]
>Actually, I don't want to override it, I just want to get it, for example, print it. But it behaves differently if I specify the port in different ways(i.e., in command line and a corefile). So do you mean that I even can not get it?

but why?

**Comment by jiachengxu** [comment]
> but why?

For instance, I want to write the CoreDNS server information to etcd, like IP address of server, and the port which the server is listenning on.

**Comment by miekg** [comment]
You probably need to do that in setup function where you have access to
dnsserver.GetConfig and get the ListenHosts.

**Comment by fturib** [comment]
@JiachengXu : from your initial description, you expect to have access to the listening port from within the Setup function of your plugin.

@miekg is right : you need to get the conf.ListenHosts ... attribute (which is an array). But it may not be initialized at the time of the Setup. So you need to get that information within the OnStartup event.


See an example in plugin/loop here: https://github.com/coredns/coredns/blob/master/plugin/loop/setup.go 
- lines 35 to 62

NOTE: ListenHosts will have several values ONLY if you use the BIND plugin with serveral IP defined.

**Comment by jiachengxu** [comment]
Thank you @fturib and @miekg, finally it works!
