### ISSUE TITLE
plugin/loop - test request is sent only to the first domain

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#1995]
Therefore, we do not test the subsequent domains.

For instance, with this corefile, that define a loop on the second domain only (isidore.com), the Loop does not detect anything:

```
francois.com:5362, isidore.com:5362 {
     loop
     proxy . 127.0.0.1:5361 {
        protocol dns force_tcp
     }
     log
     errors
}
```

if an another external CoreDNS is running with a configuration that loop only on the second domain, then it will not be detected by the above CoreDNS.

external DNS that reply a loop for isidore.com - and not for francois.com
```
# no loop on francois.com
francois.com:5361 {
     loop
     proxy . 8.8.8.8:53 {
        protocol dns force_tcp
     }
     log
     errors
}
# loop on isidore.com
isidore.com:5361 {
     loop
     proxy . 127.0.0.1:5362 {
        protocol dns force_tcp
     }
     log
     errors
}
```

**Comment by fturib** [comment]
Wait a minute ... my test is wrong.

**Comment by chrisohaver** [comment]
related ...  I believe the following loop would not get detected, since the zone of loop is `.`, and it wont try a query in `stub.domain.com.`

```
. {
     loop
     proxy stub.domain.com. 127.0.0.1
     proxy . 8.8.8.8
}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/loop -..." ]
>related ...  I believe the following loop would not get detected, since the zone of loop is `.`, and it wont try a query in `stub.domain.com.`
>
>```
>. {
>     loop
>     proxy stub.domain.com. 127.0.0.1
>     proxy . 8.8.8.8
>}
>```

yes.

**Comment by chrisohaver** [comment]
This is actively being working on.

**Comment by miekg** [comment]
who's working on this and what's the eta for this relatively simple change?

**Comment by chrisohaver** [comment]
@ZachEddy, were you still working on this?
