### ISSUE TITLE
Support multiple cache plugin per server block

### ISSUE THREAD

**Issue by steven-sheehy** [coredns/coredns#1998]
The cache plugin is not repeatable within a server block.  . If we want to cache different static zones, we can simply create a separate server block with different zones and it works fine. However, with the autopath plugin, the zone is more dynamic and is not really known/visible until after it is inside the server block (if I'm understanding things correctly). My configuration is below:
```
    .:53 {
         debug
         errors
         health
         log . {
           class all
         }
         autopath @kubernetes
         kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods verified
            resyncperiod 1m
            upstream
            fallthrough in-addr.arpa ip6.arpa
         }
         prometheus :9153
         proxy . /etc/resolv.conf
         cache 30
     }
```
So if I lookup "mypod", autopath will expand it to mypod.production.svc.cluster.local, etc only once inside .:53 server block. What I'd like to do is cache only the cluster.local for 30s since kubernetes IPs can change pretty often and the rest for 3600s.
```
    .:53 {
...
         cache 30 cluster.local
         cache 3600
     }
```

Is there any way to do this without multiple cache blocks?

**Comment by miekg** [comment]
>...
>         cache 30 cluster.local
>         cache 3600
>     }
>```
>
>Is there any way to do this without multiple cache blocks?

No really (now). I do like your request however and don't see why *cache* 
couldn't be changed to allow it.

/plugin: cache
/label: enhancement

**Comment by chrisohaver** [comment]
> What I'd like to do is cache only the cluster.local for 30s since kubernetes IPs can change pretty often and the rest for 3600s.

In this situation, *cache* already behaves this way.

*cache* will keep things around for as long as their TTL, then expire them. The duration parameter for *cache* is a maximum cache time.  i.e. It wont cache anything for longer than this duration, even if the TTL is longer.
In your example, records in `cluster.local` will have a default TTL of 5 seconds (the *kubernetes* plugin default).  So you can set *cache* to 3600 in that block - `cluster.local` records will still only persist for 5 seconds.

**Comment by chrisohaver** [comment]
BTW - Really cool to see *autopath* in use in the field.

**Comment by steven-sheehy** [comment]
@chrisohaver 👍

Any plans to push autopath as default in kubeadm now that coredns is the default? I think it would be good to make it more widespread and I don't see any drawbacks to it. This would allow ndots=5 to be set back to 1 at some point.

**Comment by chrisohaver** [comment]
> Any plans to push autopath as default in kubeadm

Not yet.  I believe we still document it as "experimental" (because it uses some DNS trickery). But could change as we get more confidence with feedback from the field.

We will be sending out a "CoreDNS in Kubernetes" users survey to see how much adoption the various kubernetes related features/plugins are getting (including autopath).

It's also on my todo list to finish a blog I started (a long time ago) about autopath, specifically in the context of how it helps alleviate the symptoms of the k8s ndots problem, so people know it's there.

**Comment by fturib** [comment]
survey is available here : https://www.surveymonkey.com/r/SKZQSLK
