### ISSUE TITLE
plugin/kubernetes: support crd

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#1999]
We could add support for CRDs in the *kubernetes* plugin. This would allow coredns to provide other records than the default k8s ones. 

Should double check if Istio doesn't already define these or something similar.

**Comment by miekg** [comment]
This explains it well: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/
It means storing DNS records in json (WCPGW). So we would need to decide how that should look. Maybe just put the text representation (with all its warts) in there as `dnsSpec`.

There would also be some severe limitations (I think), do delegation, no wildcards. And we may need some naming on how to find the CRD in the first place.

**Comment by miekg** [comment]
hmm resource names can't contains slashes: 
~~~
from server for: "my-crontab2.yaml": invalid resource name "blaat/another-contrab-object": [may not contain '/']
~~~~
So this is a flat list, meaning every query would involve, getting them *all* and sorting through them, maybe we can play trick with names. Don't know if the API allows you to retrieve a subset.

**Comment by dionysius** [comment]
Hi Miek

Kubernetes [supports fieldSelector on CRDs](https://github.com/kubernetes/kubernetes/pull/53345), but yet only on fields which are implementation independent (metadata etc). This is the [followup request for arbitary fields](https://github.com/kubernetes/kubernetes/issues/53459), which seems going stale.

You always have the choice for labelSelectors, which you can use in CRDs, but the downside is, that these fields are then not a part of the CRD spec.

How many entries do we expect so we have to consider filtering?

**Comment by miekg** [comment]
Don't know what a reasonable number is, I guess at some point retrieving
the entire list becomes too slow.

With fall through we can probably also make this into a separate plugin,
which would allow for some experiments without disturbing the main
kubernetes plugin.

**Comment by miekg** [comment]
should probably store the base64 rdata as specified by the DoH draft.
