### ISSUE TITLE
talk to the root servers instead of 8.8.8.8?

### ISSUE THREAD

**Issue by DemGiran** [coredns/coredns#2001]
I am trying to understand how DNS works, so that I can bypass dns servers like 8.8.8.8 or opendns.  

Upon reading the documenntation I noticed that you used this:

```
.:53 {
    forward . 8.8.8.8:53
    log
}
```

So that basically means that I will still go through an external dns server.

Ideally I would like to talk to the root servers directly and have them redirect me to the domain registrar dns servers. Can I do something like this? why are you forwarding to google dns?

**Comment by miekg** [comment]
You need to add a resolver to coredns, like the unbound plugin:
https://coredns.io/explugins/unbound/

/label: question
