### ISSUE TITLE
plugin/reload: reload doesn't work for windows if port doesn't change

### ISSUE THREAD

**Issue by eugen-kleiner-mesh** [coredns/coredns#2002]
The issue is reproducible on windows system only.
To reproduce start coredns with the next Corefile:
```
.:5354 {
      whoami
      reload 2s
}
```
Then add log plugin to change the MD5 sum and trigger reload with no big Corefile changes.
```
.:5354 {
      whoami
      reload 2s
      log
}
```
Reload failed, `file tcp [::]:5354: not supported by windows` error is shown in console. Coredns remains running old configuration.
```
E:\>coredns.exe
2018/07/25 20:52:16 Unable to load high precison timer, defaulting to time.Now()
.:5354
2018/07/25 20:52:16 [INFO] CoreDNS-1.2.0
2018/07/25 20:52:16 [INFO] windows/amd64, go1.10.3, 2e322f6
CoreDNS-1.2.0
windows/amd64, go1.10.3, 2e322f6
2018/07/25 20:52:16 [INFO] plugin/reload: Running configuration MD5 = 130ebbb8cd1e9617a343a814e107c1d4
2018/07/25 20:52:21 [INFO] Reloading
2018/07/25 20:52:21 [ERROR] plugin/reload: Corefile changed but reload failed: file tcp [::]:5354: not supported by windows
```
The same steps work fine for linux.

**Comment by fturib** [comment]
Some Investigation already happened on this issue:

from @ibvrubleg
> I have investigated this issue. It seems that the problem is caused by the fact that Candy (which is used inside CoreDNS) tries to duplicate opened sockets during reloading configuration and creation of a new instance of the server, but duplication of sockets is not supported by standard Go library on Windows.
> 
> Related links:
> https://github.com/golang/go/issues/10350
> https://github.com/golang/go/issues/9503

**Comment by eugen-kleiner-mesh** [comment]
Additional details I found based on @ibvrubleg's initial investigation :

When caddy is reloading it tries sharing the existing socket with a new process (see [cadddy.go:startServers()](https://github.com/mholt/caddy/blob/master/caddy.go#L739)). And  [listener.File()](https://github.com/mholt/caddy/blob/master/caddy.go#L739) function (and few functions after it) depends on not implemented for windows part of net library in go. I don't see the way to fix it in in caddy because I don't know the alternative way to share the sockets which would work fine for Windows. Also, it makes no sense to start a bug in caddy because according to [Matt's comment](https://caddy.community/t/serve-a-new-host-without-restart/856/2) and [official documentation](https://caddyserver.com/features) caddy supports Graceful Reloads only for Unix systems due to lack of POSIX signals in Windows. So, until they develop api control they officially don't support windows reloads and don't care about our issue.

Regarding the fix in go net library:
The issue is described at https://github.com/golang/go/issues/10350 and https://github.com/golang/go/issues/9503.
The main reason is that functions [dup()](https://github.com/golang/go/blob/ef9217e7bd9c854e4f8d2d79ff8aec550130cbc4/src/net/fd_windows.go#L241), [fileConn()](https://github.com/golang/go/blob/master/src/net/file_windows.go#L12), [fileListener()](https://github.com/golang/go/blob/master/src/net/fd_windows.go#L241), [filePacketConn()](https://github.com/golang/go/blob/master/src/net/file_windows.go#L22), are not implemented in go net library for windows.

**Comment by miekg** [comment]
So...  Not a coredns issue?

**Comment by fturib** [comment]
True, that is not directly a CoreDNS issue.

Here maybe we can contribute on an acceptable way to workaround this problem.
- fix lack of implementation in Go for windows ? - I am wondering why it is not done. Is there a specific problem for Windows ? or nobody care ?
- caddy reload w/o graceful restart ?
- help caddy project to go ahead on the api control ?
- is there a way to handle it in Reload plugin ?

**Comment by miekg** [comment]
don't think people care about windows anymore, and I don't like to carry windows specific code (that upstream Go decided against?) to work around problems

**Comment by fturib** [comment]
@tmthrgd : I see that for the issue #2138 you filed an upstream issue on go/net.
For current issue, we identified already existing "windows not yet implemented" issues in go/net that prevent the reload mechanism of Caddy to work properly for Windows, and therefore his current issue in  CoreDNS.

Please see [comment above](https://github.com/coredns/coredns/issues/2002#issuecomment-407846243)

Question is : are you familiar enough with the fixing process in go repository and could advise on how we could help to get to have those issues fixed in coming releases of go ?

**Comment by tmthrgd** [comment]
@fturib Unfortunately I'm not and I don't know much about Windows system calls and IO either. All I can suggest is opening issues upstream where they don't already exist.

*You could work around this issue on Windows by switching up how you take over connections. If you issued the `Accept` (and `Read` calls) in separate goroutines and used channels to reimplement the `net` interfaces, you could make it work. It's probably not worth all the difficulty that would entail though.*

**Comment by miekg** [comment]
looks like a stale issue, that will be closed soon.
