### ISSUE TITLE
In-cluster names not being resolved

### ISSUE THREAD

**Issue by Queuecumber** [coredns/coredns#2005]
I have a fresh install of coredns that was done using kubeadm and I am unable to resolve the in-cluster names. For example, the heapster pod is printing 

```
https://kubernetes.default/api/v1/namespaces?resourceVersion=0: dial tcp: lookup kubernetes.default on 10.0.100.10:53: no such host
```

10.0.100.10 is the correct address for the coredns service, and I have confirmed that telling heapster to look up the full name: `kubernetes.default.svc.cluster.local` resolves correctly. According to the kubernetes documentation, pods should be able to resolve simply `kubernetes.default`. Have I done something wrong here? I'm new to this so I don't know what extra information I can provide to diagnose, please let me know if you need something specific beyond what I put below:

CoreDNS config:

```
.:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    reload
}
```

Networking with kube-router, cni config:

```
{
  "name":"kubernetes",
  "type":"bridge",
  "bridge":"kube-bridge",
  "isDefaultGateway":true,
  "ipam": {
    "type":"host-local"
  }
}
```

**Comment by chrisohaver** [comment]
> I have confirmed that telling heapster to look up the full name: kubernetes.default.svc.cluster.local resolves correctly. According to the kubernetes documentation, pods should be able to resolve simply kubernetes.default. Have I done something wrong here?

Yes, it should work, assuming that the heapster pod is honoring the `/etc/resolv.conf` settings.  Kubernetes will build `/etc/resolv.conf` of each pod it spins up based on the pod's DNS Policy.  The default DNS policy is "ClusterFirst"... which means that it will contain a search list that searches the local cluster first.  It looks like...
```
search pod-namespace.svc.cluster.local svc.cluster.local cluster.local mydomain.com
```

Can you exec `cat /etc/resolv.conf` on the heapster pod to see what is in there?

**Comment by Queuecumber** [comment]
Hi, this turned out to be a misconfiguration with kubeadm, somehow the cluster domain name was set to different things in different places causing the resolv.conf to be written differently from what coredns was expected hence the lookups failed unless fully qualified. Sorry for clogging your issue tracker.

**Comment by chrisohaver** [comment]
No problem - thanks for following up and explaining what happened.  It's good to record these events in case others have the same/similar problem.
