### ISSUE TITLE
Coredns stop resolve kubernetes svc domain when upstream unreachable.

### ISSUE THREAD

**Issue by BSWANG** [coredns/coredns#2006]
Coredns stop resolve kubernetes svc domain when upstream failed. The kubernetes svc domain is an internal domain, shouldn't be affected by upstream dns unreachable.

### How to reproduce:
1. Deploy a kubernetes cluster use coredns as cluster dns service.  
2. Create an service A
3. Can resolve service A in pod
4. Stop coredns external upstream dns server
5. The service A can not resolve anymore

Expected: The service still can be resolved, not affected by upstream dns unreachable.

### coredns version:

CoreDNS-1.0.6
linux/amd64, go1.10, 83b5eadb

**Comment by chrisohaver** [comment]
CoreDNS-1.0.6 is quite old.  Please update to a more recent version and see if that fixes things.
If not, please share your Corefile (coredns configuration).

**Comment by BSWANG** [comment]
@chrisohaver I upgrade my cluster dns CoreDNS version to latest 1.2.0. But the latest 1.2.0 also have this issue.

**Comment by chrisohaver** [comment]
OK - can you share your coredns configuration?

**Comment by BSWANG** [comment]
@chrisohaver my coredns configuration is from kubeadm: 

```
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }
```

You can get this config in https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L294

**Comment by BSWANG** [comment]
Sorry, My mistake. The `dig` & `drill` will not append the search domain on resolve.
When append `default.svc.cluster.local` domain. Both 1.0.6 & 1.2.0 work.

**Comment by chrisohaver** [comment]
@miekg, fyi `/label: works-as-intended` is not adding the "works as intended label", So I added it manually.

**Comment by miekg** [comment]
Thanks. Prolly misspelled it. Don't want to spam the comments with error
and warnings from the bot.
