### ISSUE TITLE
Cname resolving fails

### ISSUE THREAD

**Issue by f0** [coredns/coredns#201]
Hi, i have trouble with coredns and cnames, this is the structure (domain names are changed)

```
dig  test@example.com @10.61.10.100

; <<>> DiG 9.10.4-P2-RedHat-9.10.4-1.P2.fc24 <<>> test@example.com @10.61.10.100
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17640
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;test@example.com.  IN  A

;; ANSWER SECTION:
test@example.com. 3600 IN   CNAME   cname@example.net.
cname@example.net.  2534    IN  A   10.61.9.72

;; Query time: 0 msec
;; SERVER: 10.61.10.100#53(10.61.10.100)
;; WHEN: Thu Aug 04 09:45:14 CEST 2016
;; MSG SIZE  rcvd: 105
```

coredns can not resov the name test.example.com because its a CNAME

regards f0

**Comment by miekg** [comment]
You  have to give some more information here... the dig output you posted shows it resolves just fine.

What is not working exactly? What is in etcd? This code is lifted from SkyDNS, so I would be amazed if it is 100% not working.

**Comment by f0** [comment]
ok let me explain:

this is a minimal corefile that shows the problem

```
.:53 {
    prometheus
    loadbalance
    proxy example.net  10.61.12.200:53 10.61.12.201:53 
    proxy example.com  10.61.10.100:53 10.61.10.101:53 
}
```

example.com and example.net are  outside of coredns , and test@example.com has the CNAME cname@example.net in the example.com  DNS Server

if i ask coredns for cname@example.net directly it does work, if i ask for test@example.com -> it fails

the dig from the initial post is a query against one of the example.com nameservers

Is it clear now?

**Comment by miekg** [comment]
oh yes. No this won't work... because... both upstream servers are authoritative for their zones. So _they_ won't recursively resolve the name and CoreDNS won't do that either (it isn't a recursor). Your upstream needs to be something that does the recursion for you.

At some point CoreDNS might get a real recursion middleware layer, until then you need to a) fix your setup to not have cross domain CNAMEs or b) make the upstream do the recursions for you.

**Comment by f0** [comment]
hm, ok thx i have fixed the upstream to not provide a CNAME
