### ISSUE TITLE
Caddy version?

### ISSUE THREAD

**Issue by sssilver** [coredns/coredns#2011]
What version of Caddy does coredns point at? Some Caddy issues are fixed on the current master, but it seems that coredns pulls a branch that's not master?

**Comment by chrisohaver** [comment]
v0.10.11

It's controlled in the coredns Makefile.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Caddy version? (#..." ]
>What version of Caddy does coredns point at? Some Caddy issues are fixed on the current master, but it seems that coredns pulls a branch that's not master?

What issues?

**Comment by sssilver** [comment]
https://github.com/mholt/caddy/pull/2238 helps it not break on macOS.
