### ISSUE TITLE
CoreDNS resolve slow after update to 1.2.0

### ISSUE THREAD

**Issue by sascha-andres** [coredns/coredns#2015]
I upgraded to version 1.2.0 and lookups took up to 20s. Downgrading to 1.1.4 resolved that issue.

The configuration file looks like this:

```
. {
    bind 172.17.0.1 127.0.0.1 ::1
    cache 600
    hosts {
      fallthrough
    }
    errors
    forward . /run/coredns/resolv.conf
    # prometheus localhost:9253
    # log
}
```

**Comment by miekg** [comment]
Could you easily try: https://github.com/coredns/coredns/pull/1973/
(closed PR and we're not pursuing it; just want to rule things out)

**Comment by rdrozhdzh** [comment]
another possible reason - #1852. We increased default/max dial timeout up to 30s. Though, seems this PR is already included in 1.1.4

**Comment by sascha-andres** [comment]
@miekg build #1973 but this has not helped:

|DNS Lookup|TCP Connection|TLS Handshake|Server Processing|Content Transfer|
|---|---|---|---|---|
|10001ms|7ms|55ms|44ms|0ms|

**Comment by sascha-andres** [comment]
@rdrozhdzh you're right, #1852 is in 1.1.4 already

**Comment by miekg** [comment]
Can you git bisect?

Also I don't understand your table, TLS and tcp?
