### ISSUE TITLE
RA flag is set unconditionally

### ISSUE THREAD

**Issue by Isolus** [coredns/coredns#2024]
While using coredns as authoritative name server for a .de domain, the predelegation check of the nic complains about "Recursive queries should not be allowed (resolver)".

In plugin/file (and in others) we have `m.Authoritative, m.RecursionAvailable = true, true` unconditionally. I think `m.RecursionAvailable` should only be true if recursion is available.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] RA flag is set un..." ]
>While using coredns as authoritative name server for a .de domain, the predelegation check of the nic complains about "Recursive queries should not be allowed (resolver)".
>
>In plugin/file (and in others) we have `m.Authoritative, m.RecursionAvailable = true, true` unconditionally. I think `m.RecursionAvailable` should only be true if recursion is available.

This means you need to check if proxy is loaded and only set it then. This 
creates problems for external plugins, because we can't compile in a list for 
all external plugins (explugins/unbound comes to mind). So this means a plugin 
must signal it can do recursive queries, so the server can see that. Probably a 
interface with a simple (noop) function so we can check for that?

**Comment by miekg** [comment]
show me an implementation that actually cares about this, otherwise I'll close this issue as it's not that important.

**Comment by Isolus** [comment]
The DENIC Predelegation Check (you can find an online version here: https://www.denic.de/en/service/tools/nast/ ) cares about this. Everytime you update a .de domain (e. g. DNS Servers, DNSSEC key material) the check is performed and reported. At the moment this is only displayed as a warning but if you have a registrar who treats warnings as errors, you can't change anything for your domain.
But even if you are allowed to skip this warning, it's a scary warning to everyone who doesn't have some deeper knowledge of DNS. And I don't like to ask friends or customers to skip a scary warning. That trains bad behavior.

I was thinking about your proposed solution. Is it clear at compile time whether a plugin allows recursive requests? Or you can imagine plugins where the behavior depends on the configuration?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] RA flag is se..." ]
>The DENIC Predelegation Check (you can find an online version here: https://www.denic.de/en/service/tools/nast/ ) cares about this. Everytime you update a .de domain (e. g. DNS Servers, DNSSEC key material) the check is performed and reported. At the moment this is only displayed as a warning but if you have a registrar who treats warnings as errors, you can't change anything for your domain.
>But even if you are allowed to skip this warning, it's a scary warning to everyone who doesn't have some deeper knowledge of DNS. And I don't like to ask friends or customers to skip a scary warning. That trains bad behavior.

Oh, those pre-delegation checks are the worst. You can write a plugin that 
fakes the entire set of things it cares about. Would be a fun thing to do.

>I was thinking about your proposed solution. Is it clear at compile time whether a plugin allows recursive requests? Or you can imagine plugins where the behavior depends on the configuration?

hmmm, compile time. That may work. That would *also* work for edns0 option, so 
we don't need a runtime map.

**Comment by miekg** [comment]
this cant be done compile time because the configuration is runtime

**Comment by miekg** [comment]
Please file some PRs to remove that (from the file plugin for instance).

The very simple *whoami* plugin doesn't set these flags.

**Comment by miekg** [comment]
Fixed via #2408
