### ISSUE TITLE
Pods cant resolve other pods

### ISSUE THREAD

**Issue by merdincz** [coredns/coredns#2026]
Hi i've just upgraded our kubernetes cluster from 1.10.0 to 1.11.2 after that my all end points can't resolve from pods but i can reach via IP address. 

I have 1 master and 3 node at different datacenters.

I have two endpoints on different namespaces with named gitlab and redis.

I tried to use dnstools for examine it;
```
dnstools# host kubernetes
kubernetes.default.svc.cluster.local has address 10.96.0.1
dnstools# host 10.105.20.72
72.20.105.10.in-addr.arpa domain name pointer gitlab.devops.svc.cluster.local.
dnstools# host 10.96.227.182
182.227.96.10.in-addr.arpa domain name pointer redis.logging.svc.cluster.local.
```

dnstools resolv.conf;

```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local localdomain
options ndots:5
```
I am trying to reach that records via busybox with;

```
kubectl exec busybox -- nslookup redis.logging.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10:53


*** Can't find redis.logging.svc.cluster.local: No answer
```

Busybox using same resolv.conf as dnstool

```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local localdomain
options ndots:5
```
I can reach services via IP address but can't fqdn.

Core-dns doesn't show any error or log about this.

```
.:53
2018/08/09 12:22:32 [INFO] CoreDNS-1.1.3
2018/08/09 12:22:32 [INFO] linux/amd64, go1.10.1, b0fd575c
2018/08/09 12:22:32 [INFO] plugin/reload: Running configuration MD5 = 2a066f12ec80aeb2b92740dd74c17138
CoreDNS-1.1.3
linux/amd64, go1.10.1, b0fd575c
```

**Environment**:
- Kubernetes version (use `v1.11.1`):
- OS (e.g. from /etc/os-release): centos-release-7-5.1804.1.el7.centos.x86_64
- Kernel (e.g. `uname -a`): Linux RMPH014 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Edit:

My corefile;
```
Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }

```

**Comment by fturib** [comment]
@merdincz : thanks to put all the details here.
I think first point would be to check if CoreDNS is receiving and processing any DNS request.

Can you add the "log" plugin in your corefile ?

```
Corefile: |
       .....
        cache 30
        reload
        log
    }
```

(after edit the config-map, wait 2mn that the update on the pod + reload of coredns take effect)
And then running the same tests from busybox, and collecting the logs of the coredns pod.

**Comment by chrisohaver** [comment]
What version of busy box?  There are some busy box releases with broken DNS...

https://github.com/kubernetes/kubernetes/issues/66924#issuecomment-411804435

**Comment by chrisohaver** [comment]
Replica issue of kubernetes/kubernetes#67196 (cross posted)

**Comment by chrisohaver** [comment]
Closing this duplicate issue, since I don't have rights to close the other one. kubernetes/kubernetes#67196

**Comment by merdincz** [comment]
Hi @chrisohaver 

My busybox version: BusyBox v1.29.2 (2018-07-31 20:19:16 UTC)

I was suspected from core-dns but i think it is not related with core-dns let me explain is why.

I have a svc which named with kube-dns;

`kube-system     service/kube-dns             ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP           1d        k8s-app=kube-dns`

configuration;
```
Name:              kube-dns
Namespace:         kube-system
Labels:            k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=CoreDNS
Annotations:       prometheus.io/port=9153
                   prometheus.io/scrape=true
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP:                10.96.0.10
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:         172.17.0.7:53
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:         172.17.0.7:53
Session Affinity:  None
Events:            <none>

```

I have 1 master 3 node at the moment i tried to reach dns from nodes and master with;

`curl 10.96.0.10:53`

I wasn't be able to take any response from my master and 3 nodes except one of them. If i run busybox the node which i get response i can see logs on coredns but others not. I stuck on now, I don't know why master and other nodes can't reach to DNS service.

**Comment by chrisohaver** [comment]
For the version of busybox you are using, some people are reporting that DNS lookups are not working properly.  From the link I sent above...

> It looks like DNS inside busybox does not work properly.
> At least it **works for me with busybox images <= 1.28.4**

So, perhaps try an older busybox image - just to be sure.

On which node/nodes are the DNS pods scheduled?  Is there a correlation with connectivity from pods on those nodes.

**Comment by merdincz** [comment]
Thank you @chrisohaver it seems like network layer issue like you said. I will re-open other issue.
