### ISSUE TITLE
No any DELETE-operation in Cache ?

### ISSUE THREAD

**Issue by ckcd** [coredns/coredns#2035]
Hi,

I just read the code of "Cache" plugin, I was wondering about the cache delete:

First, There are `Cache.Remove` and `Shard.Remove` which are used to delete items, However, no methods call these two func.

Second, In "handler.go / get" of cache plugin, if the `i.(*item).ttl(now) <= 0` then the item will NOT be used, but why not delete this item ?
```
func (c *Cache) get(now time.Time, state request.Request, server string) (*item, bool) {
	k := hash(state.Name(), state.QType(), state.Do())

	if i, ok := c.ncache.Get(k); ok && i.(*item).ttl(now) > 0 {
		cacheHits.WithLabelValues(server, Denial).Inc()
		return i.(*item), true
	}

	if i, ok := c.pcache.Get(k); ok && i.(*item).ttl(now) > 0 {
		cacheHits.WithLabelValues(server, Success).Inc()
		return i.(*item), true
	}
	cacheMisses.WithLabelValues(server).Inc()
	return nil, false
}
```

Third, when a shard is full, `Add` will call `evict` to randomly delete a item rather traverse the shard to find items whose ttl <=0 , so maybe there is a bad situation: a item is added and never be used again, but the randomly methods nerver chose these lucky item ,so the useless item will be always existed ?

**Comment by fturib** [comment]
I think the cache has been reworked to be completely oriented for a better performance under high QPS. Which means high level of threading.
Which means for the cache, try to limit the usage of locks, and if possible keep usage of RLock. At this time was introduces the split into shards.

What is a little more concerning is the way we choose the one to remove from the shard : randomely instead of picking an obsolete entry.

Could fix that eviction choice without impacting the performance ?

**Comment by miekg** [comment]
Random eviction is a performance choice as well. In my initial testing a
LRU required so many locks it didn't perform at all.

Prefetch should offset the random eviction.

We should delete the unused code btw.

**Comment by ckcd** [comment]
@miekg Thks for your answer,

so in your test the "random eviction" performance is better, does it relay on number of items (e.g. 256*512 in defalut)?

And should we delete the obsoleted items in '"func (c *Cache) get" while `i.(*item).ttl(now) <= 0` ?

Thks~

**Comment by miekg** [comment]
The sharded cache is *also* done for performance so concurrent go-routines don't all want to use the same lock.

If we have unused code a PR that deletes it is welcome.
