### ISSUE TITLE
Enabling autopath in Kubernetes causes IPv6 issues

### ISSUE THREAD

**Issue by bcorijn** [coredns/coredns#2039]
Hi all,

I enabled CoreDNS on my kops-managed Kubernetes 1.10.5 cluster last week and had it running in parallel to kube-dns to evaluate performance. Since my applications do a lot of external dns-requests, I was especially interested in enabling the autopath feature, to optimize all the search domain queries a bit. 

However, I noticed that as soon as I enabled `pods verified` and `autopath @kubernetes` in my config, I would start getting `ENETUNREACH` errors from some applications trying to connect to IPv6 addresses. My cluster/VPC is not set up to be able to connect outwards on IPv6, so it makes sense to see these errors if the application is trying to reach an IPv6 address. 

Trying to debug manually, I first of all noticed that for a query like `dig google.com ANY @<pod-IP>` I would get different kind of results from different pods. Some returned only an A record, some returned A and NS, some returned A, NS and AAAA and others returned A, NS, AAAA, SOA and TXT. I guess it somehow depends on what is in the cache, but I expected something a bit more consistent? Kube-DNS seems to behave similarly though.
However, I noticed from time to time I would see a short moment where only an AAAA record was returned, which would cause my application to connect on IPv6 (IPv4 is always preferred, unless there are not v4 records). I have not been able to replicate this without the pods verified and autopath enabled. Only using `pods verified` without autopath also seems to behave as expected. 

Happy to debug further, but am a bit lost myself on what could cause this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Enabling autopath..." ]
>Hi all,
>
>Trying to debug manually, I first of all noticed that for a query like `dig google.com ANY @<pod-IP>` I would get different kind of results from different pods. Some returned only an A record, some returned A and NS, some returned A, NS and AAAA and others returned A, NS, AAAA, SOA and TXT. I guess it somehow depends on what is in the cache, but I expected something a bit more consistent? Kube-DNS seems to behave similarly though.

dig ANY <name> is never a good debug tool, so I can't comment on this.

>However, I noticed from time to time I would see a short moment where only an AAAA record was returned, which would cause my application to connect on IPv6 (IPv4 is always preferred, unless there are not v4 records). I have not been able to replicate this without the pods verified and autopath enabled. Only using `pods verified` without autopath also seems to behave as expected.
>
>Happy to debug further, but am a bit lost myself on what could cause this.

With autopath the queries are made by your upstream coredns binary (instead of 
being forwarded), this could account for the difference in behavior.

Might be good to see some pcaps of when you only see AAAA's being returned.

**Comment by chrisohaver** [comment]
The inconsistent behavior of `ANY` is strange (not good). `ANY` queries are afaict widely maligned (I think due to complexity of implementation and lack of standards).  Nevertheless, we should behave consistently.

@bcorijn: Are these affected applications using `ANY` queries to look up address records?

**Comment by chrisohaver** [comment]
A good read: https://blog.cloudflare.com/what-happened-next-the-deprecation-of-any/

**Comment by bcorijn** [comment]
Fair enough on the dig point. I will try to write a minimal test-case tomorrow where I can reproduce it and capture the traffic from that container/those requests.

These applications are nodeJS apps, which afaik request both A and AAAA and return whatever they can: 

>Resolves a hostname (e.g. 'nodejs.org') into the first found A (IPv4) or AAAA (IPv6) record. All option properties are optional. If options is an integer, then it must be 4 or 6 – if options is not provided, then IPv4 and IPv6 addresses are both returned if found.

So I suspect some of the resolutions only get an IPv6 back (or at least within the timeout), which causes these errors. Could it be that some of the A requests get delayed as in issues like these: https://github.com/kubernetes/kubernetes/issues/56903 ?

**Comment by chrisohaver** [comment]
> Could it be that some of the A requests get delayed as in issues like [k8s drops packets]

Could be  ... if the app doesn't retry the first failed `A` before trying for `AAAA`.

... And that would kinda fall in line with why only `autopath` is affected, since with autopath, the dns communication is routed through another node (where coredns lives), as opposed to the pod querying upstream directly (no node-node routing).

**Comment by bcorijn** [comment]
@chrisohaver as far as I'm aware, the app won't retry as long as it gets at least one IP back. If that happens to be an IPv6, it will still consider the resolution succesfull (at least if I don't re-configure these applications to explicitly NOT do v6 resolution).

What I don't fully understand is why enabling autopath for my kubernetes plugin, affects the DNS resolution of external names such as google.com and facebook.com (these are the two I see most often logged). I thought autopath would only affect resolutions that matched my kubernetes `cluster.local.` domain? 

Just as extra information, this is the config I am currently running (without the additional `autopath @kubernetes` line- largely the default one of the kops deployment:
```
    .:53 {
        errors
        health
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```

**Comment by chrisohaver** [comment]
As a hack, you can block all AAAA queries with the `template` plugin.  (I didn't test syntax below, but i think it should work)

```
    .:53 {
        errors
        health
        template ANY AAAA . {
          rcode NXDOMAIN
        }
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```

> What I don't fully understand is why enabling autopath for my kubernetes plugin affects the DNS resolution of external names 

This is because with `autopath`, coredns does the domain search on behalf of the client.  That includes the final `.` domain.  There isn't a way for coredns to tell the client to do that final query on it's own  - the client still thinks its on the first domain in the search list, so it would pick back up where it left off, by querying the 2nd domain in the list.

**Comment by chrisohaver** [comment]
I suppose returning `NXDOMAIN` (or any other negative response) would not solve the issue, since the `A` query is presumably lost, the client would get no answer, and still be unable to resolve the address. Perhaps if `template` had a way to not answer at all...

**Comment by cerivera** [comment]
@bcorijn, did you ever resolve this?  We've got the same problem from our node apps after enabling `autopath`.

cc @rocktavious

**Comment by chrisohaver** [comment]
@cerivera, can you give an example of a `dig` query and output that shows the problem you are seeing?

**Comment by cerivera** [comment]
@chrisohaver we bumped our node image to 10.14.2 and haven't been able to reproduce the problem.  

We were previously on a custom base image and manually installing node 8.9.4.

**Comment by bcorijn** [comment]
@cerivera I moved back to mainly using kubedns because I could not come up with a good solution at that time. It has been on my to-do list to look into it again. Good to hear though that it is solved for you with node 10.14, I'll have to try that out.

**Comment by chrisohaver** [comment]
@bcorijn - kube-dns doesn't have an 'autopath' feature ... and this issue in coredns is only seen with autopath option?  or did you also see it without autopath enabled?

**Comment by bcorijn** [comment]
@chrisohaver this only manifested itself when using autopath, which was the main selling point for me to move from kube-dns to coredns at the time (I am aware kubedns does not do this). Without autopath my kube-dns was more lightweight for more or less the same performance, so I moved back to using kube-dns for a while. I will try to test/debug this a bit more in the coming days with more recent versions of coredns, kubernetes and node.

**Comment by rocktavious** [comment]
@bcorijn - FWIW - coredns is the accepted k8s DNS solution now and is being used in newer versions by default - so figuring out the issue will be necessary if you want to move up to newer versions of k8s.
@chrisohaver if it would help i can share our coredns configuration - but it seems like @cerivera has solved the issue by upgrading his node version.  #spooky

**Comment by bcorijn** [comment]
@rocktavious Yeah, it's been on my agenda as I know I _need_ to tackle it, but debugging these kind of occasional DNS issues is not easy, so I need to have enough time for it.
@cerivera Was it specifically Node 10.14 that fixed it, or did you just update in one way step from 8 to 10? Did the base image change in any other way (Debian vs Alpine for example)?

**Comment by cerivera** [comment]
@bcorijn, @rocktavious, the issue showed up again today :(  I think it was a fluke that we didn't see it yesterday after bumping node

Update: Definitely less frequent.  We were seeing the error on every deploy, and now we've only seen it once in 24 hours.  We went from a Fedora base to Alpine during the node bump.

**Comment by miekg** [comment]
Are there pcaps?

**Comment by bcorijn** [comment]
So I have been testing with this a bit again (running coredns 1.3.1 this time), enabling autopath and pods verified immediately gave ENETUNREACH errors again. I updated to Node.JS 10.15 as @cerivera suggested, and although I must say I was not expecting that to work at all, it appeared to have made the errors go away.
...for a few hours. After that they came back as strong as they had been before. I will take a look if it was just the app restart that caused it or if there's something else in play.

@miekg How should I approach capturing those? I can't reproduce these errors on a small/manual scale so far. I am more than happy to try and provide something, but I just don't really know how to do so efficiently.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Enabling auto..." ]
>So I have been testing with this a bit again (running coredns 1.3.1 this time), enabling autopath and pods verified immediately gave ENETUNREACH errors again. I updated to Node.JS 10.15 as @cerivera suggested, and although I must say I was not expecting that to work at all, it appeared to have made the errors go away.
>...for a few hours. After that they came back as strong as they had been before. I will take a look if it was just the app restart that caused it or if there's something else in play.
>
>@miekg How should I approach capturing those? I can't reproduce these errors on a small/manual scale so far. I am more than happy to try and provide something, but I just don't really know how to do so efficiently.

you need to (somehow) run tcpdump in the path the sees the dns queries; on the 
eth0 interface in the docker container for instance, or if that fails on the 
nodes' interface.

**Comment by deepak-malhotra** [comment]
> As a hack, you can block all AAAA queries with the `template` plugin. (I didn't test syntax below, but i think it should work)
> 
> ```
>     .:53 {
>         errors
>         health
>         template ANY AAAA . {
>           rcode NXDOMAIN
>         }
>         kubernetes cluster.local. in-addr.arpa ip6.arpa {
>           pods insecure
>           upstream
>           fallthrough in-addr.arpa ip6.arpa
>         }
>         prometheus :9153
>         proxy . /etc/resolv.conf
>         cache 30
>         reload
>     }
> ```
> 
> > What I don't fully understand is why enabling autopath for my kubernetes plugin affects the DNS resolution of external names
> 
> This is because with `autopath`, coredns does the domain search on behalf of the client. That includes the final `.` domain. There isn't a way for coredns to tell the client to do that final query on it's own - the client still thinks its on the first domain in the search list, so it would pick back up where it left off, by querying the 2nd domain in the list.

@chrisohaver the template plugin works perfectly fine for me . Thanks for the suggestion . I was also tempted to try the DNS option of single-request-reopen but that didn't help.
