### ISSUE TITLE
the coredns match specific zone for query

### ISSUE THREAD

**Issue by mingqing** [coredns/coredns#2047]
https://github.com/coredns/coredns.io/blob/master/content/manual/plugins.md

> If there are multiple Servers configured that listen on the queried port, it will check which one has the most specific zone for this query (longest suffix match). E.g. if there are two Servers, one for example.org and one for a.example.org, and the query is for www.b.example.org, it will be routed to the latter.

I think if query is www.b.example.org it will be routed to the first(example.org), if the last Servers configured is b.example.org it will be routed it?

**Comment by chrisohaver** [comment]
Yes, `www.b.example.org` would be routed to `example.org`, because it is not in the zone `a.example.org`.
