### ISSUE TITLE
coredns 1.2.1 release

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2056]
if memory serves me well; we need a new release about now-ish.

**Comment by fturib** [comment]
Yes ! :)

We need it to go asap.

There is still one PR for Milestone 1.2.1 : https://github.com/coredns/coredns/pull/2042
It is ready, but we are maybe not on same line for it's opportunity to merge.

If we need some time to talk about it ... then better to leave that PR for next release, and have 1.2.1 quickly.

What do you think ?

**Comment by miekg** [comment]
Looking through the changelog we only have bug fixes and the loop plugin.

**Comment by miekg** [comment]
aha
~~~
coredns-s390x: digest: sha256:4012e29e354b375bad28093411fe8bb08257548c88ba85eca18c0bc4baacc836 size: 739
manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x --template coredns/coredns:coredns-ARCH --target coredns/coredns:1.2.1
make: manifest-tool: Command not found
Makefile.release:123: recipe for target 'docker-push' failed
make: *** [docker-push] Error 127
~~~

**Comment by miekg** [comment]
and no sha256 files :/

Trying to remember how I did the docker upload last time... Think I just rebuild on my laptop and pushed from there.

**Comment by miekg** [comment]
Release is here, I'll do release note and coredns.io later this evening or tomorrow.

filed #2059 to fix the remaining issues.

**Comment by fturib** [comment]
@miekg : Thanks a lot! 
@chrisohaver : can you update the deployment,
@rajansandeep : can y you then follow-up with PRs on kubernetes
ME: ask Tim H to push this image to gcr.io

**Comment by dghubble** [comment]
@fturib did this get pushed? The last CoreDNS release I see on gcr.io is 1.1.3 https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/coredns?gcrImageListsize=50

**Comment by chrisohaver** [comment]
@dghubble, The push to gcr.io has not happened yet (we have already made the request to google to push it).  It is on coredns's dockerhub account though.  `coredns/coredns:1.2.1`  and so is `coredns/coredns:1.2.2`
