### ISSUE TITLE
release: list reviewers seperately  

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2064]
Reviewers do an important job, we should call that out in the release notes.

Not sure how to get the list

**Comment by chrisohaver** [comment]
perhaps iterate through all PRs in the given release,  hitting github API  for each PR here ... https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request

not elegant, but may be the only way.

**Comment by miekg** [comment]
bloody hard to implement and I lacked the time to hack it up in dreck
