### ISSUE TITLE
release: 1.2.2

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2066]
Help out with https://github.com/kubernetes/kops/issues/5652
a new release is easiest for them, so just kick of 1.2.2

**Comment by miekg** [comment]
grrr fuck, I def. need a way to test this stuff.

**Comment by miekg** [comment]
Wee /o\ forgot to merge the 1.2.2 PR, so this a re-release of 1.2.1, not super bad, but should probably revert and release from the v1.2.1 tag *again*. It has the cache fix though.

**Comment by miekg** [comment]
ah, cood for the files here in github.com this is a noop: v1.2.1 is still the same release. so we pushed to docker agin.

Let me try to fix the sha256 thing, and release 1.2.2

**Comment by miekg** [comment]
hmm, looking through the output, it looks to be more luck (curl was broken) than anything else

**Comment by fturib** [comment]
@miekg : Thanks for this release !
