### ISSUE TITLE
Dynamic Updates (rfc2136) or API 

### ISSUE THREAD

**Issue by mitchellmaler** [coredns/coredns#2073]
Hello, 

We are looking to switch to using CoreDNS and wondered if CoreDNS has an API or supports dynamic updates? We have a lot of ansible and other automations which add and remove records to DNS and hoping CoreDNS supports something similar without having to expose the etcd API.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Dynamic Updates (..." ]
>Hello,
>
>We are looking to switch to using CoreDNS and wondered if CoreDNS has an API or supports dynamic updates? We have a lot of ansible and other automations which add and remove records to DNS and hoping CoreDNS supports something similar without having to exposing the etcd API.

No there is currently nothing of the sorts. Dynamic updates are a big change 
that have far reaching impact, so I don't see this happening any time soon, if 
at all.

There is also no write api, although the is an outstanding PR to add something 
like that.

Current best bet is having a database being provisioned and have that exposed 
(read-only) to coredns.

**Comment by johnbelamaric** [comment]
Yes, the goal is to build an internal write API that plugins can implement
if they so choose. Then, we would have to implement the external APIs for
that - gRPC, REST, DDNS. It will be a while. The auth is the hardest part
of those, I think. @fturib may be able to say more on timelines.
