### ISSUE TITLE
make fails for the tag v1.1.3 

### ISSUE THREAD

**Issue by champashankar** [coredns/coredns#2078]
I'm running the make command on the tag v1.1.3, fails with the below error. But on the same setup master branch works fine. Could you please have a look.

root@platcon5:/home/champa/coredns_v1.1.3/coredns# make
** presubmit/context
** presubmit/test-lowercase
go get -u github.com/alecthomas/gometalinter
gometalinter --install goimports
Installing:
  deadcode
  dupl
  errcheck
  gochecknoglobals
  gochecknoinits
  goconst
  gocyclo
  goimports
  golint
  gosec
  gosimple
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  megacheck
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  unused
  varcheck
( gometalinter --deadline=2m --disable-all --enable=goimports --vendor --exclude=^pb/ ./... || true )
core/dnsserver/server_grpc.go:1::warning: file is not goimported (goimports)
plugin/kubernetes/handler_ignore_emptyservice_test.go:1::warning: file is not goimported (goimports)
plugin/tls/tls_test.go:1::warning: file is not goimported (goimports)
go generate coredns.go
# Not vendored so external plugin compile, avoiding:
# cannot use c (type *"github.com/mholt/caddy".Controller) as type
# *"github.com/coredns/coredns/vendor/github.com/mholt/caddy".Controller like errors.
(cd /root/go/src/github.com/mholt/caddy 2>/dev/null              && git checkout -q master 2>/dev/null || true)
(cd /root/go/src/github.com/miekg/dns 2>/dev/null                && git checkout -q master 2>/dev/null || true)
(cd /root/go/src/github.com/prometheus/client_golang 2>/dev/null && git checkout -q master 2>/dev/null || true)
go get -u github.com/mholt/caddy
go get -u github.com/miekg/dns
go get -u github.com/prometheus/client_golang/prometheus/promhttp
go get -u github.com/prometheus/client_golang/prometheus
(cd /root/go/src/github.com/mholt/caddy              && git checkout -q v0.10.11)
(cd /root/go/src/github.com/miekg/dns                && git checkout -q v1.0.6)
(cd /root/go/src/github.com/prometheus/client_golang && git checkout -q v0.8.0)
go get -u github.com/alecthomas/gometalinter
gometalinter --install golint
Installing:
  deadcode
  dupl
  errcheck
  gochecknoglobals
  gochecknoinits
  goconst
  gocyclo
  goimports
  golint
  gosec
  gosimple
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  megacheck
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  unused
  varcheck
gometalinter --deadline=2m --disable-all --enable=gofmt --enable=golint --enable=vet --vendor --exclude=^pb/ ./...
plugin/tls/tls_test.go:1::warning: file is not gofmted with -s (gofmt)
Makefile:82: recipe for target 'linter' failed
make: *** [linter] Error 1
root@platcon5:/home/champa/coredns_v1.1.3/coredns#

And While browsing, i got the some one posting the similar error "https://github.com/coredns/coredns/issues/1891", so i took the commits from #1892, then i end up with different error
root@platcon5:/home/champa/coredns_v1.1.3/coredns# make
** presubmit/context
test/grpc_test.go
test/etcd_test.go
test/etcd_cache_test.go
request/request.go
** presubmit/context: please use std lib's 'context' instead
** presubmit/test-lowercase
test/secondary_test.go:         t.Fatalf("failed to create zone: %s", err)
test/reverse_test.go:           t.Fatalf("failed to create zone: %s", err)
test/proxy_test.go:             t.Fatalf("failed to create zone: %s", err)
test/proxy_test.go:             t.Fatalf("failed to create zone: %s", err)
test/proxy_test.go:             t.Fatalf("failed to created zone: %s", err)
test/proxy_test.go:             t.Fatalf("could not get CoreDNS serving instance: %s", err)
test/proxy_test.go:             t.Fatalf("could not get udp listening port")
test/cache_test.go:             t.Fatalf("failed to create zone: %s", err)
test/external_test.go:          t.Fatal("dns.example plugin should be there")
test/ds_file_test.go:           t.Fatalf("failed to create zone: %s", err)
test/file_test.go:              t.Fatalf("failed to create temp file: %s", e)
test/wildcard_test.go:          t.Fatalf("failed to create zone: %s", err)
test/plugin_test.go:            t.Fatalf("failed to create zone: %s", err)
test/plugin_dnssec_test.go:             t.Fatalf("failed to create zone: %s", err)
test/proxy_http_health_test.go:         t.Fatalf("failed to create zone: %s", err)
** presubmit/test-lowercase: please start with an upper case letter when using t.Fatal*()
Makefile:103: recipe for target 'presubmit' failed
make: *** [presubmit] Error 1
root@platcon5:/home/champa/coredns_v1.1.3/coredns#

**Comment by miekg** [comment]
/label: duplicate 
See #2085
