### ISSUE TITLE
Configure CoreDNS proxy plugin to use strict-order when quering upstream nameservers

### ISSUE THREAD

**Issue by kcao3** [coredns/coredns#2081]
Hello,

Here is an example of CoreDNS proxy plugin where it proxies everything using the host's resolv.conf's nameservers:

. {
proxy . /etc/resolv.conf
}

Assuming there are MULTIPLE nameservers entries defined in /etc/resolv.conf.

Does anyone know if CoreDNS has a feature similar to the **strict-order** feature of dnsmasq, where it will try each query with each server strictly in the order they appear in /etc/resolv.conf listed above?

**Comment by chrisohaver** [comment]
I expect `policy sequential`  should do it, though I have not verified in the code to be sure.

```
. {
    proxy . /etc/resolv.conf {
        policy sequential
    }
}
```

**Comment by kcao3** [comment]
Excellent!  I'll give it a try and let you know if it actually works or not. Thanks!

**Comment by kcao3** [comment]
It works!
