### ISSUE TITLE
CoreDNS spaw many process , 100% cpu

### ISSUE THREAD

**Issue by kop2018** [coredns/coredns#2083]
Hi all 
i'm using coredns with kubernetes running on ubuntu 18.04. 
I have problem is kubernetes node spawn many process coredns ,
cpu reach 100% . 
![screen shot 2018-09-03 at 9 17 09 am](https://user-images.githubusercontent.com/41512882/45008772-a4858c80-b02e-11e8-92d3-2758afd9271d.png)

Here is my setting 

**Node etc/resolv.conf :**

```
nameserver 127.0.0.53
search ap-northeast-1.compute.internal
```

**run/systemd/resolve/resolve.conf:**

```
nameserver 10.0.0.2     **#I don't know who generate this line ?**
search ap-northeast-1.compute.internal
```

**CoreFile**

```
.:53 {
    errors
    log stdout
    debug
    health
    kubernetes mydomain.test in-addr.arpa ip6.arpa {
      pods insecure
      upstream /etc/resolv.conf
      fallthrough in-addr.arpa ip6.arpa
    }
    proxy . /etc/resolv.conf
    cache 30
}
```

Does problem relate my setting wrong ?
Do you have any suggestion resolve it ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] CoreDNS spaw many..." ]
>Hi all
>i'm using coredns with kubernetes running on ubuntu 18.04.
>I have problem is kubernetes node spawn many process coredns ,
>cpu reach 100% .

you probably created a resolving loop. You need either change /etc/resolv.conf 
or make coredns not use that. Note that 1.2.1 and above have loop plugin that 
should detect this and stop the process (coredns.io/plugins/loop).

/label: question
/label: kubernetes

/Miek

--
Miek Gieben

**Comment by kop2018** [comment]
Hi Miekg
I'm using kubespray install kubernetes cluster on aws
my coredns version is 1.2.2
I will try install loop plugin for coredns
Do you think install plugin is best choose for this case ?
If don't use loop plugin , could you suggest change Node resolv.conf  ?
change both /run/systemd/resolve/resolve.conf & /etc/resolve.conf 
Thank you

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS spaw ..." ]
>Hi Miekg
>I'm using kubespray install kubernetes cluster on aws
>my coredns version is 1.2.2
>I will try install loop plugin for coredns
>Do you think install plugin is best choose for this case ?
>If don't use loop plugin , could you suggest change Node resolv.conf  ?
>change both /run/systemd/resolve/resolve.conf & /etc/resolve.conf
>Thank you

I don't know you have to talk to the kubespray people to fix their setup (on 
Ubuntu)

**Comment by kop2018** [comment]
Hi Miekg
I've apply loop plugin
after kill coredns process on Node to reload config 
it start new pod throw this log then terminated .

```
{"log":".:53\n","stream":"stdout","time":"2018-09-04T06:57:02.337329001Z"}
{"log":"2018/09/04 06:57:02 [INFO] CoreDNS-1.2.2\n","stream":"stdout","time":"2018-09-04T06:57:02.33740131Z"}
{"log":"2018/09/04 06:57:02 [INFO] linux/amd64, go1.11, eb51e8b\n","stream":"stdout","time":"2018-09-04T06:57:02.337414947Z"}
{"log":"CoreDNS-1.2.2\n","stream":"stdout","time":"2018-09-04T06:57:02.337420833Z"}
{"log":"linux/amd64, go1.11, eb51e8b\n","stream":"stdout","time":"2018-09-04T06:57:02.337426571Z"}
{"log":"2018/09/04 06:57:02 [FATAL] plugin/loop: Seen \"HINFO IN 4873264821232888814.6218532710403833842.\" more than twice, loop detected\n","stream":"stdout","time":"2018-09-04T06:57:02.337986749Z"}
```
Here is my Corefile after add plugin 
```
.:53 {
    loop
    forward . 127.0.0.1 
    errors
    health
    kubernetes mydomain.test in-addr.arpa ip6.arpa {
      pods insecure
      upstream /etc/resolv.conf
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
}
```
Is that correct ? Do you have any suggestion ?
Thank you

**Comment by chrisohaver** [comment]
@vd10, 

```
forward . 127.0.0.1 
```

That line causes a direct self loop, which will cause infinite lookup recursion. Hence the loop detects it.
The `127.0.0.53` in the resolv.conf file strongly suggests that you may be running `systemd-resolved` on your host nodes, which replaces `/etc/resolv.conf`, and moves the "original" resolv.conf file to another location. If so, you'll need to point `kubelet` to the correct `resolv.conf` file path: 
```
--resolv-conf=/run/systemd/resolve/resolv.conf
```

`kubeadm` 1.11 and later automatically detects `systemd-resolved` and points `kubelet` to the right file.  I dont know what version of `kubeadm` `kubespray` uses to deploy k8s (or if it uses `kubeadm` at all, but I suspect it does).

**Comment by kop2018** [comment]
Hi @chrisohaver 
i've fixed problem with this :

```
.:53 {
    errors
    log stdout
    debug
    health
    kubernetes mydomain.test in-addr.arpa ip6.arpa {
      pods insecure
      upstream /etc/resolv.conf
      fallthrough in-addr.arpa ip6.arpa
    }
    proxy . /etc/resolv.conf
    cache 30
}

```
remove the `/etc/resolv.conf` on the host and run `ln -s  /run/systemd/resolve/resolve.conf /etc/resolv.conf`
then delete coredns process to reload again

Thank you

**Comment by chrisohaver** [comment]
@vd10,

I see why that would work, but by doing it that way, you are breaking `systemd-resolved` on your host system. If you don't care about `systemd-resolved` on your host system, be sure to disable it (e.g. with systemctl).  If it's still enabled, it may try to restore `/etc/resolv.conf` back to how it wants it on restart.

If you do want to leave `systemd-resolved` enabled on your host system, then the correct fix is to inform `kubelet` that the resolv.conf file is on another path... with the flag ... 

```
--resolv-conf=/run/systemd/resolve/resolv.conf
```

**Comment by kop2018** [comment]
@chrisohaver
I will try your suggestion to fix this problem completely
Thank you
