### ISSUE TITLE
make on s390x passed with commit no #1891 on top of v1.1.3 for ubuntu

### ISSUE THREAD

**Issue by champashankar** [coredns/coredns#2085]
Hi,

I was getting the below error, then got to know that this is similar to #1891  . Later i took the code commits from #1892 and merged those changes on v1.1.3. With this I'm able to build the binary "coredns" and able to generate the dockerimage as well.
Is it possible to have these changes in this repo with a new branch, so it would be reserved at one place.
If so, please let me know, I'll make a new branch and raise a PR.

Error faced before the #1892 changes on v1.1.3
root@platcon5:/home/champa/coredns_v1.1.3/coredns# make
** presubmit/context
** presubmit/test-lowercase
go get -u github.com/alecthomas/gometalinter
gometalinter --install goimports
Installing:
deadcode
dupl
errcheck
gochecknoglobals
gochecknoinits
goconst
gocyclo
goimports
golint
gosec
gosimple
gotype
gotypex
ineffassign
interfacer
lll
maligned
megacheck
misspell
nakedret
safesql
staticcheck
structcheck
unconvert
unparam
unused
varcheck
( gometalinter --deadline=2m --disable-all --enable=goimports --vendor --exclude=^pb/ ./... || true )
core/dnsserver/server_grpc.go:1:warnig file is not goimported (goimports)
plugin/kubernetes/handler_ignore_emptyservice_test.go:1:waning file is not goimported (goimports)
plugin/tls/tls_test.go:1:waning file is not goimported (goimports)
go generate coredns.go
Not vendored so external plugin compile, avoiding:
cannot use c (type *"github.com/mholt/caddy".Controller) as type
*"github.com/coredns/coredns/vendor/github.com/mholt/caddy".Controller like errors.

(cd /root/go/src/github.com/mholt/caddy 2>/dev/null && git checkout -q master 2>/dev/null || true)
(cd /root/go/src/github.com/miekg/dns 2>/dev/null && git checkout -q master 2>/dev/null || true)
(cd /root/go/src/github.com/prometheus/client_golang 2>/dev/null && git checkout -q master 2>/dev/null || true)
go get -u github.com/mholt/caddy
go get -u github.com/miekg/dns
go get -u github.com/prometheus/client_golang/prometheus/promhttp
go get -u github.com/prometheus/client_golang/prometheus
(cd /root/go/src/github.com/mholt/caddy && git checkout -q v0.10.11)
(cd /root/go/src/github.com/miekg/dns && git checkout -q v1.0.6)
(cd /root/go/src/github.com/prometheus/client_golang && git checkout -q v0.8.0)
go get -u github.com/alecthomas/gometalinter
gometalinter --install golint
Installing:
deadcode
dupl
errcheck
gochecknoglobals
gochecknoinits
goconst
gocyclo
goimports
golint
gosec
gosimple
gotype
gotypex
ineffassign
interfacer
lll
maligned
megacheck
misspell
nakedret
safesql
staticcheck
structcheck
unconvert
unparam
unused
varcheck
gometalinter --deadline=2m --disable-all --enable=gofmt --enable=golint --enable=vet --vendor --exclude=^pb/ ./...
plugin/tls/tls_test.go:1:warnng file is not gofmted with -s (gofmt)
Makefile:82: recipe for target 'linter' failed
make: *** [linter] Error 1
root@platcon5:/home/champa/coredns_v1.1.3/coredns#

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] make on s390x pas..." ]
>Hi,
>
>I was getting the below error, then got to know that this is similar to #1891  . Later i took the code commits from #1892 and merged those changes on v1.1.3. With this I'm able to build the binary "coredns" and able to generate the dockerimage as well.
>Is it possible to have these changes in this repo with a new branch, so it would be reserved at one place.
>If so, please let me know, I'll make a new branch and raise a PR.

PR for what?

**Comment by champashankar** [comment]
V1.1.3 build failed on s390x ubuntu machine. Later merging the changes from #1891 to v1.1.3 worked. So my question was is it possible to have a branch separately for s390x in this repo.

**Comment by miekg** [comment]
No, starting per arch branches will add a lot of overhead. If there is
something that can, and should be, fixed in master it should be done there.

**Comment by miekg** [comment]
`plugin/tls/tls_test.go:1:warnng file is not gofmted with -s (gofmt)` is go version dependent, so you may need an older Go compile.
