### ISSUE TITLE
setting upstream

### ISSUE THREAD

**Issue by bw2** [coredns/coredns#2089]
Is deploying this config map the correct way to set core-dns upstream to 8.8.8.8 on minikube?
```
kind: ConfigMap
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream 8.8.8.8
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
metadata:
  creationTimestamp: 2018-09-09T18:24:22Z
  name: coredns
  namespace: kube-system
  resourceVersion: "198"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
```
Asking in relation to https://github.com/kubernetes/minikube/issues/2027

**Comment by johnbelamaric** [comment]
The `upstream` in the `kubernetes` clause should just stay `upstream`. That is only used for resolving CNAMEs within the kubernetes plugin. If you change it from a bare `upstream` then external services that refer to a stub domain won't work.

Really what you want is to change the `proxy . /etc/resolv.conf` to `proxy . 8.8.8.8`, which forces anything not handled by CoreDNS to be sent to 8.8.8.8. Or you can change it in your host /etc/resolv.conf.
