### ISSUE TITLE
DS Record

### ISSUE THREAD

**Issue by DJohnD** [coredns/coredns#209]
Hello @miekg 

how do I get a DS Record for my zone? I cannot use DNSSEC without this record.

P.S.: What key does CoreDNS generate if I am doing dnssec [zone]?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] DS Record (#209)..." ]

> Hello @miekg
> 
> how do I get a DS Record for my zone? I cannot use DNSSEC without this record.

You'll need to convert it yourself from the key that you are using.

dig DNSKEY <zonename> @nameserver

and convert that key to a DS record and upload those to your registry.

Yes, I'm planning on making this all better :)

Also: are you using on-the-fly signing? If so, I should add a warning there that
the key is only stored in memory (yes I know). So you'll loose it when CoreDNS
restarts.... (yes, yes, all on the TODO list).

**Comment by anoncam** [comment]
hey @miekg did this DS record question ever get updated in coredns?  We have children zones that are missing a DS record and was wondering if we could do this yet with coredns or needed to create the DS record ourselves as stated above.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] DS Record (#2..." ]
>hey @miekg did this DS record question ever get updated in coredns? We have
>children zones that are missing a DS record and was wondering if we could do
>this yet with coredns or needed to create the DS record ourselves as stated
>above.

no, IIR nothing got changed here, so you need to add it manually...
