### ISSUE TITLE
plugin/kubernetes: Reduce memory footprint at scale

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#2095]
Relating to CoreDNS OOM death in kubernetes/kubernetes#68613.

Evidence suggests that the endpoint store grows too large in the scale tests, wherein ~100K Endpoints exist. In CoreDNS, all of these endpoints are stored in client-go endpoint store cache.

One partial solution would be to not store endpoints for cluster IP services.  Endpoints records are technically not needed per the DNS Spec.  I suspect that kube-dns operates this way.  Note that in the scale tests where CoreDNS is OOM killed, no headless services are created, which means that if we skip ClusterIP Endpoints, we would end up not stashing any Endpoints in the store at all.  This could explain why kube-dns does not get OOM killed in the same test.

Skipping ClusterIP endpoints would however disable a CoreDNS feature that allows wildcard searching for all endpoints in a cluster IP service. Someone tweeted about how awesome this feature was a while back.  So, it could be missed.  Perhaps we could make it an option to enable (with a warning about memory impact on large clusters, as we warn with `pods verified` mode).

Another solution would be to optimize the data we store for endpoints, so that only the data we need to construct the record is kept.

**Comment by miekg** [comment]
I think OOMing trumps any feature that is not part of the DNS spec, so let's not complicate things by adding options that will lead to bad behavior later on.

*Not* storing something sounds like a simple fix...?

**Comment by chrisohaver** [comment]
>  let's not complicate things by adding options

agreed.

And yes, It looks to be a simple fix. I think there would be some race conditions early, that might force us to have to store some endpoints if we receive events for them before we receive the service events.  But that is short lived, and i think by schema, Services must exist before an Endpoint can be created anyways.

However, @johnbelamaric did a quick test, and it seems that endpoint objects would not take up enough memory to account for the OOM.  So, there may be something else going on here.

**Comment by chrisohaver** [comment]
> And yes, It looks to be a simple fix.

Actually, this looks to be more complicated than I thought.  I don't yet see how to hook into the watch store function.

**Comment by miekg** [comment]
Why doesn't skydns have this issue?

**Comment by chrisohaver** [comment]
skydns == kube-dns ?

On Sep 15, 2018, at 9:34 AM, Miek Gieben <notifications@github.com<mailto:notifications@github.com>> wrote:


Why doesn't skydns have this issue?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>skydns == kube-dns ?

Sorta

kube-dns = skydns+dnsmasq

**Comment by chrisohaver** [comment]
I don't know for sure, but I think kube-dns may not use the k8s API cache/stores, instead saves data to their own barebones maps (just enough to build DNS records ).  

We can drill further there to confirm how kube-dns does it, but after @johnbelamaric's endpoint test, it _really looks like endpoints are not the issue_... so for now it looks like a dead end.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>I don't know for sure, but I think kube-dns may not use the k8s API cache/stores, instead saves data to their own barebones maps (just enough to build DNS records ).
>
>We can drill further there to confirm how kube-dns does it, but after @johnbelamaric's endpoint test, it _really looks like endpoints are not the issue_... so for now it looks like a dead end.

hmm, sadface.

I don't know if we can implement it, but per plugin statistics/metrics would be 
nice in the pprof.

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
some differences I see in implementation of endpoint watching/storing, none are likely to be significant.

- Both do use a k8s client cache/store Informer (contrary to what I speculated above). Although kube-dns's vendored client is about a year old, CoreDNS uses the client from the last release (1.11).
- CoreDNS uses an indexed informer, kube-dns does not (I doubt an index would account for a 30% bump)
- In addition to the client store, kube-dns also stores pre-computed DNS records for each item. So you'd expect the memory usage to be slightly greater in kube-dns, however for cluster IP services, it does not create records for endpoints. Since the e2e scale tests comprise only cluster IP services, kube-dns doesn't create/store any endpoint DNS records in these tests.
- CoreDNS computes all records from the client store on demand, as requests come in, so there is no addtl memory overhead there (in context of e2e tests).

**Comment by johnbelamaric** [comment]
Renamed - it's not clear it is the endpoints cache that is the issue.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>Renamed - it's not clear it is the endpoints cache that is the issue.

The scale test @fturb mentions in the kubernetes issue, can we see where the 
memory ends there?

**Comment by chrisohaver** [comment]
There were several tests...

- 500 Nodes: 38MB
- 2000 Nodes: 93MB
- 5000 Nodes: We never got to run this.  The k8s teams finally firmly said they would not accept any changes this late in the release, so the test was never executed.

Will try to run the 5k node test next week or so, after 1.12 delivers.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>There were several tests...
>
>- 500 Nodes: 38MB
>- 2000 Nodes: 93MB
>- 5000 Nodes: We never got to run this.  The k8s team finally firmly said they would not accept any changes this late in the release, so the test was never executed.
>
>Will try to run the 5k node test next week or so, after 1.12 delivers.

So you said kubedns k8s client lib are a year old? What if we downgrade our to 
the same level (hoping stuff would still compile), that would at least narrow 
down where things goes.

Can *we* do a 2000 nodes test easily and pprof?

**Comment by chrisohaver** [comment]
> What if we downgrade our client lib to the same level as kube-dns ... to narrow things down

We can try - I think we would have to adapt code a bit - i recall having to make some changes in one or two of the client updates. May prove painful, but worth a shot to see if it's easy.

> Can *we* do a 2000 nodes test easily and pprof?

I don't think Infoblox will do a 2000 node test. I'll ask management if we can.  If not, maybe CNCF can help out here.

It may be more feasible to add pprof collection to the k8s e2e test framework. I don't think it would be hard.

**Comment by chrisohaver** [comment]
> Can we do a 2000 nodes test easily and pprof?

We _can_ do a test with `kubemark`... it's a node simulator, that can create a cluster with 5000 virtual nodes that attach to a single real node master.  You cannot run real pod backed endpoints on the cluster.  But we can create services, and static endpoints.  Now that I think of it. we may be able to create a few pods on the master, and then create endpoints for each service that target the same pods.  This could work for what we need - I had not thought of this before.

**Comment by miekg** [comment]
Nice.

Note that I think the cache can also be made to use less memory (we already
discussed this), but doing it on an RRSet basis. It does open some can of
worms on how trustworthy the cached data is, but prolly worth doing.

**Comment by chrisohaver** [comment]
> Note that I think the cache can also be made to use less memory

Cool, although these e2e tests do not currently exercise (or use at all for that matter) the cache.
We'll propose adding QPS testing to the tests in 1.13...

**Comment by miekg** [comment]
Sgtm, but we should prolly preempt that by setting up something ourselves.
Wondering how other projects do scale tests like this.

**Comment by chrisohaver** [comment]
We can run 500 and 2000 node scale tests as pre-submit tests for "free" via in kubernetes/kubernetes PRs.  As long as all changes needed are in kubernetes/kubernetes, we can open a PR, then execute the tests via `/test test-name`.  We can extend/modify these tests to collect additional info in the same PR.  If we extend the tests in a clean general use manner, we can propose to the scalability team to adopt the tests additions (such as i did in kubernetes/kubernetes#68683 - which I'm hoping the scalability team will merge in 1.13).  The only test that is isn't available for pre-submit testing is the 5000 node test.

**Comment by chrisohaver** [comment]
Regarding Indexing... we do use indexing, whereas kube-dns does not.
We define indexing functions, and if we are leaking memory to heap in those function, perhaps it could add up, before GC can sweep it up.

I see we use `+` to concatenate namespace and name for an index key... I recall that using `+` to concatenate strings in Go will allocate some amount to heap in the Go compiler.  In the e2e tests, service names and namespace names are autogenerated (so they are long > 30 characters each). 

If `+` indeed leaks to heap, and it leaks both strings it concatenates to heap, then ...
150000 endpoints * 32 bytes * 2 = 9.6MB ... less than the difference we saw between coredns and kubedns.

 Seems unlikely.  But I figured i'd mention it anyways - in case it jostles some ideas loose.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>Regarding Indexing... we do use indexing, whereas kube-dns does not.
>We define indexing functions, and if we are leaking memory to heap in those function, perhaps it could add up, before GC can sweep it up.
>
>I see we use `+` to concatenate namespace and name for an index key... I recall that using `+` to concatenate strings in Go will allocate some amount to heap in the Go compiler.  In the e2e tests, service names and namespace names are autogenerated (so they are long > 30 characters each).
>
>If `+` indeed leaks to heap, and it leaks both strings it concatenates to heap, then ...
>150000 endpoints * 32 bytes * 2 = 9.6MB ... less than the difference we saw between coredns and kubedns.
>
> Seems unlikely.  But I figured i'd mention it anyways - in case it jostles some ideas loose.

10MB seems worth while in itself.

All those caches we set up, those are needed to keep our calls to the API 
down? Doesn't plugin/cache essentially do the same. IOW: can we drop *all* of 
that caching/indexing?

**Comment by chrisohaver** [comment]
> 10MB seems worth while in itself.

Yes - it could be a bit higher too - it depends on how many events we get per endpoint.  During the ramp up period, we may get more than one updates for each endpoint makes. e.g. when they are first created, when they transition from unready to ready, other changes ? 

> All those caches we set up, those are needed to keep our calls to the API
down?

Yes

>Doesn't plugin/cache essentially do the same. IOW: can we drop *all* of that caching/indexing?

Sort of, but I think it's problematic.  We could do a refactor so that we build records and populate the cache ahead of time.  But we'd need to make their TTLs >= to the API refresh period (currently 5 minutes). Or - we'd need to set up a separate cache for these objects. I'm assuming there is a way to set up an API watch without a store (cache)... but I don't know for sure.  if there isn't, then we just have two stores of the same info.  Also, one nice thing about having all service/endpoint information on reference in the store is that we can use this information for dynamic decision making (policy).

We're going to run some tests...  hopefully today...
* with indexing disabled entirely
* with indexing enabled, but with indexing functions modified to use strings.Builder (introduced in go 1.10).

**Comment by chrisohaver** [comment]
Ah - The API refreshes also would call the indexing functions for every existing endpoint, every 5 minutes during the test.  The 5k node test lasts 16+ hours i think.  Although this would be one for each whole endpoints object, which is the same cardinality of the service objects.  Still, thats a lot of index function calls over the course of the test.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>We're going to run some tests...  hopefully today...
>* with indexing disabled entirely
>* with indexing enabled, but with indexing functions modified to use strings.Builder (introduced in go 1.10).

ack.

Can we use fnv64 in the index functions?

/Miek

--
Miek Gieben

**Comment by aledbf** [comment]
> Ah - The API refreshes also would call the indexing functions for every existing endpoint, every 5 minutes during the test

Maybe this should be revised? From the last kubecon: https://github.com/kubernetes/community/blob/b3349d5b1354df814b67bbdee6890477f3c250cb/events/2018/05-contributor-summit/clientgo-notes.md#best-practices
`A: controller automatically relists on connection issues, resync interval is only for external resources`

We (ingress-nginx) had similar issues with the informer resync in clusters using > 10000 ingresses, 10000 services, 20000 endpoints scaling the controller to 10. After switching the default resync period to 0 helped us to remove latency from the sync and more importantly the load from apiserver.

**Comment by chrisohaver** [comment]
>  `controller automatically relists on connection issues` ... After switching the default resync period to 0 helped us to remove latency from the sync and more importantly the apiserver.

Ah thanks!  Good to know!

**Comment by chrisohaver** [comment]
> Can we use fnv64 in the index functions?

I thought that the hashing is done by the store/index object for us - i.e. we pass a unique key, and it does the hashing calc / lookups behind the scenes. But now i have my doubts... I could be wrong here.  If I'm wrong, then we have maximally inefficient indexes...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>> Can we use fnv64 in the index functions?
>
>I thought that the hashing is done by the store/index object for us - i.e. we pass a unique key, and it does the hashing calc / lookups behind the scenes. But now i have my doubts... I could be wrong here.  If I'm wrong, then we have maximally inefficient indexes...

Please check (if your checking). 

I also have my doubts on the kube-dns setup, 170MB doing nothing useful is 
insane. That we even require more memory is just the cherry on top.

**Comment by chrisohaver** [comment]
> Please check (if you're checking). 

The docs, though not entirely clear, suggest that we are doing the indexing appropriately.  Although I see that the default indexing function is to index on "namespace/name" of the object being stored.  Our indexing functions ("name.namespace") are essentially doing the same as the default - so we should be able to remove the indexing functions, and just use the defaults.

>I also have my doubts on the kube-dns setup, 170MB doing nothing useful is insane.

Well - this is in an extreme scale case (so, insane in, insane out, I suppose), but yes this is how the go client Informer behaves.  In the opposite extreme (for the sake of framing the solution set), we could skip using the Informer, and do round trips to the API each query.  This would save on memory, but at the obvious expense of performance. Like you said earlier, we could use rely on our own cache.

Maybe thats the way to go ... in that case we'd basically sit at around ~18 MB in the e2e scale tests (even the 5k node test).   It has reaching implications into some other areas of code that peek into the API store (e.g. autopath), they'd need to peek into the cache instead.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>>I also have my doubts on the kube-dns setup, 170MB doing nothing useful is insane.
>
>Well - this is in an extreme scale case (so, insane in, insane out, I suppose), but yes this is how the go client Informer behaves.  In the opposite extreme (for the sake of framing the solution set), we could skip using the Informer, and do round trips to the API each query.  This would save on memory, but at the obvious expense of performance. Like you said earlier, we could use rely on our own cache.

yeah, I wonder about; are we double caching for $REASONS, without knowing 
exactly why?

>Maybe thats the way to go ... in that case we'd basically sit at around ~18 MB in the e2e scale tests (even the 5k node test).   It has reaching implications into some other areas of code that peek into the API store (e.g. autopath), they'd need to peek into the cache instead.

That actually sgtm; we also control our cache better than k8s' cache; minttl, 
maxttl that sort of thing.

**Comment by chrisohaver** [comment]
> we could use rely on our own cache.
With our TTLs of 5 seconds - I think this would perform very poorly in practice.

> yeah, I wonder about; are we double caching for $REASONS, without knowing exactly why?

It's for performance reasons - when a DNS cache entry expires, we have to pull from the API.  It's much faster to pull from the local API client cache/store that by making a round trip to the API.  IOW, it makes cache misses very cheap.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>> we could use rely on our own cache.
>With our TTLs of 5 seconds - I think this would perform very poorly in practice.
>
>> yeah, I wonder about; are we double caching for $REASONS, without knowing exactly why?
>
>It's for performance reasons - when a DNS cache entry expires, we have to pull from the API.  It's much faster to pull from the local API client cache/store that by making a round trip to the API.  IOW, it makes cache misses very expensive.

True, but we have prefetch working (thanks to @grobie).

**Comment by chrisohaver** [comment]
As it stands now, we could deploy k8s with no DNS cache for the cluster.local domain.  We probably would not have much of a performance hit.  Although, that would not drop the memory usage in the e2e scale tests, since they do not have DNS query load.

**Comment by chrisohaver** [comment]
OK, 500 node test results fiddling with index...

* **string concat optimization**: no significant mem footprint change
* **removing index entirely**: mem footprint with index is 25% bigger than footprint with no index.

So, it seems that the bulk of the difference between kube-dns and coredns is indeed the API cache/store indexes.

**Comment by miekg** [comment]
Thanks for the update. This matched nicely with the increase we saw.

Immediate steps: disable that indexing?

And thinking further along, and repeating what I've said in this thread:
not using this mechanism entirely?

On a side note: did you get a memory profile? Where is this memory being
used?

**Comment by johnbelamaric** [comment]
As I recall, with no indexes performance was abysmal.

So, you are saying instead of keeping the K8s objects cached, we populate
our own DNS response cache? This is a radical change, and I am not
convinced it would help that much. For example, a single Endpoint object is
going to render a bunch of DNS records - A, SRV, PTR, AAAA before long.
We'd be copying data into each of those records, and a lot of them will
never be looked up. Think of the records generated for an AXFR. I am not
sure it will be much or even any smaller.

I also think the TTLs are an issue. The DNS cache is going to expire those,
even though *we know* they are not expired because we didn't get a "watch"
changing them. Right now the TTL is 5 seconds and always "fresh" for DNS
cache misses. Prefetch doesn't help because that's a DNS pre-fetch, not a
K8s pre-fetch. And it would perform badly if it were a K8s pre-fetch
(shouldn't need that with watch).

A better strategy would be to customize the objects we store; i.e.,
implement our own K8s object cache that slims things down to just what we
need. This assumes you can do a watch without using a built-in cache.

**Comment by chrisohaver** [comment]
Well yes it was abysmal. I’d like to keep the index too,  but we are under strict (and IMO dubious) memory requirements at scale, and currently under no performance restrictions. IMO this trade of memory for performance makes sense in real life in virtually all real life scenarios. Maybe we can adjust the index to reduce its size to accommodate the requirements. Such as just indexing on namespace. It would be less effective, but it may be smaller. Or perhaps dropping to default indexing would work better. We have time to experiment here. There’s also the possibility I could be implementing the indexing incorrectly.  Perhaps we could hash the keys manually to force the index to be shorter/deeper. Trade off.

John, I am on the same page, and I agree with you on all points.  I’ll look into the possibility of a customized store or disabling the built in store.

We could also look into adapting horizontal scaling guidelines for coredns.  E.g. adjust the “default” node:replica ratios recommended in the k8s DNS autoscaler based on perf testing.  Kubedns and coredns currently have different cpu/memory profiles, so it makes sense that they may scale horizontally in a different way. If Coredns uses more memory but can serve higher qps with less cpu than because things are indexed, then we may be able to use less coredns replicas, and therefor less total memory.

Anyways. We have a lot longer than 1 weekend to look into this now. So we have time to discuss.

On Sep 21, 2018, at 6:48 PM, John Belamaric <notifications@github.com<mailto:notifications@github.com>> wrote:

As I recall, with no indexes performance was abysmal.

So, you are saying instead of keeping the K8s objects cached, we populate
our own DNS response cache? This is a radical change, and I am not
convinced it would help that much. For example, a single Endpoint object is
going to render a bunch of DNS records - A, SRV, PTR, AAAA before long.
We'd be copying data into each of those records, and a lot of them will
never be looked up. Think of the records generated for an AXFR. I am not
sure it will be much or even any smaller.

I also think the TTLs are an issue. The DNS cache is going to expire those,
even though *we know* they are not expired because we didn't get a "watch"
changing them. Right now the TTL is 5 seconds and always "fresh" for DNS
cache misses. Prefetch doesn't help because that's a DNS pre-fetch, not a
K8s pre-fetch. And it would perform badly if it were a K8s pre-fetch
(shouldn't need that with watch).

A better strategy would be to customize the objects we store; i.e.,
implement our own K8s object cache that slims things down to just what we
need. This assumes you can do a watch without using a built-in cache.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>As I recall, with no indexes performance was abysmal.

Ack.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>A better strategy would be to customize the objects we store; i.e.,
>implement our own K8s object cache that slims things down to just what we
>need. This assumes you can do a watch without using a built-in cache.

Ack. So this means not using (e.g.) *api.Service in controller.go, but a smaller 
structure?

**Comment by miekg** [comment]
I've starting looking through this (rather dense) code.

It looks like if we hook into the cache's ProcessFunc we can add our own 
stripped down `runtime.Object`s; I'm just going to try things with the simplest 
one we need (prolly *api.Pod), and see how far I can get.

This doesn't solve creating index keys with "a" + "." + "b", would be neat to 
solve that too.

Does anyone know/remember why we have `cache.NewIndexInformers` and not simpler 
`cache.NewInformers`?

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
> Does anyone know/remember why we have `cache.NewIndexInformers` and not simpler
`cache.NewInformers`?

Because we wanted to maintain indexes, for for better QPS performance.

**Comment by chrisohaver** [comment]
> Ack. So this means not using (e.g.) *api.Service in controller.go, but a smaller
structure?

Yes.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>> Does anyone know/remember why we have `cache.NewIndexInformers` and not simpler
>`cache.NewInformers`?
>
>Because we wanted to maintain indexes, for for better QPS performance.

Did we have benchmark data on this? I've looked throught the (rather complex) 
k8s caching code and in the end the Store takes a single string for a map 
lookup.

One of the things I could not understand is why these indexers return a string 
slice of which we only fill the first element. Expanding them break the tests, 
because when we look for things we create a single string as a key. 

Also with *numerous* println's i didn't see those Lister functions being called, 
but I may have missed something there.

/Miek

--
Miek Gieben

**Comment by johnbelamaric** [comment]
At scale, performance was several orders of magnitude worse without the
indexes.

**Comment by chrisohaver** [comment]
> One of the things I could not understand is why these indexers return a string
slice of which we only fill the first element.

Based on the index function type, I initially thought we would add each key part (name and namespace) as separate items in the array, but the index lookup functions only accept a single string, not an array of strings.  So, their implementation doesn't seem to line up. I'm not sure why there is an array of strings in the index creation func type.  Maybe it's an incomplete thought.

**Comment by chrisohaver** [comment]
> Also with *numerous* println's i didn't see those Lister functions being called,
but I may have missed something there.

Lister functions are used when the indexes cannot be used - e.g. for wildcard queries, and also probably zone transfer.

**Comment by chrisohaver** [comment]
@miekg, 

@rajansandeep and I were digging into the code with a debugger. It looks like the built in index funcs in `NewIndexerInformer` expect the objects in the object store to implement Object (apimachinery/pkg/apis/meta/v1).  Since they do not, the index funcs error, and the store remains empty.  That means we need to implement our own `DeletionHandlingMetaNamespaceKeyFunc` and `MetaNamespaceKeyFunc` that work with our objects, or we need to add `ObjectMeta` and or `TypeMeta` to our objects so they implement Object.

We also need to take care not to not link/point to the original api.objects when creating our objects.  Otherwise I think the original api.Objects will stay on the heap - which in the end could result in consuming more memory.

[oops, i posted this comment in the wrong issue - meant to put it [here](#2128)]

**Comment by chrisohaver** [comment]
FYI - We are running another test - With all indexes enabled _except_ for the Reverse Endpoints index.  

The reverse Endpoints index has a larger key cardinality compared to the other indexes.  It indexes endpoints by their full IP, which means its cardinality is 150k in the 5k node scale test.  The other 3 indexes enabled by default are all 1/15th that size (10k each for forward service, reverse service, and forward endpoints).

If this test shows that it's this index that accounts for the majority of the index size, we can play around with shrinking this index e.g. by making the key non unique, indexing on part of the IP, or hashing-down the IP...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>@miekg, Sandeep and I were digging into the code with a debugger. It looks like the built in index funcs in `NewIndexerInformer` expect the objects in the object store to implement Object (apimachinery/pkg/apis/meta/v1).  Since they do not, the index funcs error, and the store remains empty.  That means we need to implement our own `DeletionHandlingMetaNamespaceKeyFunc` and `MetaNamespaceKeyFunc` that work with our objects, or we need to add `ObjectMeta` and or `TypeMeta` to our objects so they implement Object.

Ah, thanks that makes total sense and explains why my PR is failing currently. 
Redoing those functions for our use-case make sense.

>We also need to take care not to not link/point to the original api.objects when creating our objects.  Otherwise I think the original api.Objects will stay on the heap - which in the end could result in consuming more memory.

Ack.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>FYI - We are running another test - With all indexes enabled _except_ for the Reverse Endpoints index.
>
>The reverse Endpoints index has an larger key cardinality compared to the other indexes.  It indexes endpoints by their full IP, which means its cardinality is 150k in the 5k node scale test.  The other 3 indexes enabled by default are all 1/15th that size (10k each for forward service, reverse service, and forward endpoints).
>
>If this test shows that it's this index that accounts for the majority of the index size, we can play around with shrinking this index e.g. by making the key non unique, indexing on part of the IP, or hashing-down the IP...

Can the index by non-unique?

Another thought I had was just using fnv64 for this as the index key (or 
something that directly outputs a string.

**Comment by chrisohaver** [comment]
> Can the index by non-unique?

I expect so, since the index funcs return a list of objects that match the index, not a single object.

**Comment by miekg** [comment]
We can write our own versions. I'm only slightly concerned with the comment
that these functions by default check if they missed a watch update when a
delete is happening. I.e. can we go into a situation where we're replying
with stake data.

Anyway I'll rework what I have right now for service to see if that makes
the ci pass.

**Comment by chrisohaver** [comment]
> We are running another test - With all indexes enabled _except_ for the Reverse Endpoints index.

OK, the tests showed that the reverse endpoint index accounts for ~75% of the index size.  Removing it drops CoreDNS to below kube-dns in 2k node test, and also below kube-dns at 5k projections.

So, I'll try reducing the key size.

**Comment by chrisohaver** [comment]
> So, I'll try reducing the key size.

I was only able to run the 500 node test (we hit a quota wall for the 2k node tests), but from that result, it looks like reducing the key cardinality (to a max of ~20k) didn't significantly reduce the total index size.

I'm trying an alternate tactic - similar to how kube-dns does this. Kube-dns does not support reverse lookups of endpoints if the endpoints are for Cluster IP services.  This adheres to the dns spec, which only requires reverse lookups on endpoints to work for headless services. From that I am inferring that they maintain a map of [ip]endpoint for endpoints of _headless services only_.  I suspect this is how kube-dns is passing e2e scale tests in < 170mi since (IIRC) there are zero headless services created in the e2e scale tests. Incidentally for kube-dns, the 170mi limit is for the "kubedns" container only - dnsmasq (cache) and sidecar (health/stats) which run about 30MB together do not count toward that limit.

I'm testing some code today that does the same in CoreDNS - removing the reverse endpoint index, and replacing it with a map that only contains headless services endpoints.  This should enable us to run at 5K nodes under the 170mi mark, and also under the kube-dns _total_ memory usage (total usage = kubedns+dnsmasq+sidecar).

If we plan to go this route, we could add an option to enable reverse lookups of all endpoints (including cluster IP endpoints), since it is a useful/intuitive behavior - in which case we'd just use the existing `epIPIndex` in the indexerInformer.  It's quite possible (likely?) that the client-go indexers are more efficient (cpu) than maintaining our own map.

**Comment by chrisohaver** [comment]
Ran into a race condition - when we receive endpoint add events from the API, we get them _before_ we get the service add event.  That means we don't know if the endpoint's service is a Cluster IP.

Tracing kube-dns code, it seems it will not add the reverse map entry in this case.  Still trying to figure out how it avoids this race condition.

Side note: when tracing over the kube-dns code and cache code again, I see that we could probably remove our _forward_ indexes on endpoint and service, and use the built in name/namespace key.  The Informer (without indexers) does maintain a name/namespace key map to the store by default, so CoreDNS's forward indexes are redundant with the built in default map keys.  I initially though these were an either/or thing, but it seems that both exist at the same time.  It would save a bit of extra space at scale.  It also simplifies/shortens the code.

**Comment by miekg** [comment]
Thinking and looking through the client-go code; it seems to me that the indexers are used to select a cache. This improves throughput because of cache sharding (just like we do in the cache plugin). I.e. I mean we *could* implement our own `cache.Store`. However the current failure in the ci-test will probably not be solved by this.

**Comment by chrisohaver** [comment]
Summary so far of memory reduction efforts...

[Reference chart](https://docs.google.com/spreadsheets/d/e/2PACX-1vRJCdyf82bXGwox34qdzKk5NnPhvdVfPMl8skJH7lLU9NbP8EZhQpN22gH8rOMn1RxcC8auzER7GL8K/pubchart?oid=626024915&format=interactive)

Store: Custom Store  saves 10%
Index: Use default keys saves 5%
Index: Custom endpoint ip map saves 17% 

Store change is in #2128
Index changes are in #2143

The custom endpoint IP map change is profoundly favored by the absence of headless services in the tests.  The other changes are not favored by the tests.

The changes should be compatible.

Concerning functional impact:
- Custom store: no functional impact
- Default keys - no functional impact
- Custom endpoint map - no `PTR` records for cluster IP endpoints (same as kube-dns), though they still get `A` records.

Concerning CPU impact: Some of these changes decrease the amount of cpu processing, some increase.
- Custom store - increases (object conversion).
- Default keys - decreases (removes redundant index maintenance).
- Custom endpoint map - not sure (swaps out indexing maintenance for map custom map maintenance)

**Comment by fturib** [comment]
I understand, with latest results we have now:
- Custom store - gain estimated 27%
- Custom endpoint map (with impact on the feature) - similar gain.

Each of these solution will put CoreDNS in position to not increase the memory limit at all (if the numbers are confirmed for 5k node).

In order to confirm the numbers on a scale test with 5k nodes, we need to:
- release an image with the optimized CoreDNS (the best of optimizations)
- push that image in gcr.io
- merge a CoreDNS as "default", with the new release image

QUESTIONS:
- are both solutions ready to be merged ?
- what is the order of the merge so, we can "compose" them and adds-up as much as possible the optimization
- when can we do a release of CoreDNS with optimization ?


(please comment if I miss steps here)

**Comment by chrisohaver** [comment]
You are correct on what we need to do to get the 5k results.
Both solutions are not ready to be merged.
Not sure what you mean by "order of merge" - the order of the merge will not affect the degree of optimization.

For the index/key PR, I have another day of getting unit tests done, then it should be ready.
I expect the merge of these two PRs will take a couple of days. They touch a lot of the same code, so I expect many conflicts.

**Comment by chrisohaver** [comment]
@miekg @johnbelamaric @fturib: Will/should we fully merge the endpoint map PR (#2143)? 

There are two parts to (#2143):
* _Keys_: Use default keys for forward lookups instead of indexes. (shaves 5% memory)
* _Endpoint Map_: Custom endpoint ip map and only store headless endpoints (shaves 17% memory)

To a degree the _Endpoint Map_ part of it is tailored specifically to pass the tests (following suit of kube-dns which does the same). If we don't want to merge that part, I'll not waste more time writing unit tests for code we wont merge.

The _Keys_ part makes sense to merge regardless.

**I'm leaning toward no: Do not merge the _Endpoint Map_ part.**  Since it adds more code to maintain, adds yet another k8s plugin option, reduces default configuration functionality, and would probably impact performance.

**I'm holding off on writing the endpoint map tests until we make a decision here.**

**Comment by johnbelamaric** [comment]
Yeah, I agree. If it's not necessary and it reduces functionality, let's
withhold it for now. Once we see the 5k tests, if it doesn't go as well as
we expect, we can add this back in.

**Comment by chrisohaver** [comment]
I've broken the _Keys_ change out into a separate PR ... #2167 
I'm proposing we merge #2167  instead of #2143.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>Yeah, I agree. If it's not necessary and it reduces functionality, let's
>withhold it for now. Once we see the 5k tests, if it doesn't go as well as
>we expect, we can add this back in.

agreed

**Comment by chrisohaver** [comment]
Well, Bad news: Test results finally in, and the "custom store + keys" build is taking up more memory than the just "custom store"...  There are some possible reasons...

* The merge somehow introduced some issue/inefficiency increasing memory consumption.
* The "keys" change actually increases memory consumption.
* I made an error when testing the "custom store" build (built wrong branch/pushed wrong binary)
* Perhaps there is a high degree of variability with the tests.

I am re-testing on master @ 8432f1420732e61cb1a7ebb9d6446db6f43aa850 (immediately before the "keys" merge).

**Comment by chrisohaver** [comment]
i think we are done here for now...
