### ISSUE TITLE
upstream is optional in etcd

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2099]
The upstream in etcd is optional (according to the README), but it is not allowed in the setup.

**Comment by miekg** [comment]
did we fix this?

**Comment by callebjorkell** [comment]
I'm seeing this issue on 1.2.5 at least.

**Comment by jiachengxu** [comment]
Hi @dilyevsky , are you working on this issue?  If not, can I take it?

**Comment by dilyevsky** [comment]
@jiachengxu have gotten the time to tackle this yet, feel free to take this
