### ISSUE TITLE
go get is failing

### ISSUE THREAD

**Issue by tgvaughan** [coredns/coredns#2101]
When getting coredns using `go get coredns/coredns` in the golang:latest docker image, the following error results:

```
# github.com/coredns/coredns/plugin/metrics
src/github.com/coredns/coredns/plugin/metrics/metrics.go:43:49: too many arguments in call to prometheus.NewProcessCollector
	have (int, string)
	want (prometheus.ProcessCollectorOpts)
```

This only appeared within the last few weeks, and seems similar to [this recent issue](https://github.com/zalando/skipper/issues/781) which had to do with a breaking change in prometheus.

BTW thanks for the awesome tool!  I've been using coredns for a few months now to encrypt home network DNS traffic and it's been very simple to use.

**Comment by miekg** [comment]
Thanks!

CoreDNS is not go gettable, for reasons explained in the Makefile.

But we should upgrade to a newer version of the Prometheus anyway and apply
the change submitted in a recent pr.

**Comment by tgvaughan** [comment]
Interesting!  I've been using `go get` to install CoreDNS in the golang docker container for a few months: I wonder why this has been working?  In any case, feel free to close the issue if `go get` failing is more-or-less expected behaviour.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] go get is fai..." ]
>Interesting!  I've been using `go get` to install CoreDNS in the golang docker container for a few months: I wonder why this has been working?  In any case, feel free to close the issue if `go get` failing is more-or-less expected behaviour.

Current setup is expected to fail. Vgo and go modules will hopefully make that a 
thing of the past.

/close

**Comment by analogue** [comment]
golang + coredns newcomer here. Trying to build coredns with the unbound plugin and running into this issue based on the directions documented in the README.

https://github.com/coredns/coredns#compilation-from-source

Would appreciate the documentation being updated or the issue fixed :-)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] go get is fai..." ]
>golang + coredns newcomer here. Trying to build coredns with the unbound plugin and running into this issue based on the directions documented in the README.
>
>https://github.com/coredns/coredns#compilation-from-source
>
>Would appreciate the documentation being updated or the issue fixed :-)

did you run 'make'? That does to the right thing; the issue will be fixed when 
we move to go modules. Yes this sucks, but it's the best we could do with the 
current go build system

**Comment by analogue** [comment]
Figured out what a go "workspace" is and set it up correctly - that was the cause of `make` failing. Apologies for the false alarm!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] go get is fai..." ]
>Figured out what a go "workspace" is and set it up correctly - that was the cause of `make` failing. Apologies for the false alarm!

/close
