### ISSUE TITLE
coredns maintainers email list

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2105]
Hi, all current CoreDNS maintainers:

@bradbeam
@chrisohaver
@dilyevsky
@fastest963
@fturib
@greenpau
@grobie
@isolus
@johnbelamaric
@miekg
@pmoroney
@rajansandeep
@stp-ip
@superq
@varyoo
@yongtang

We (I and @fturib) want to start a maintainers *mailing* list. This list can be used for things that not directly require a github issue (or whatever something you wish to discuss).

Please ping me (miek@miek.nl) your email address (I only have your github handle) if you want to be on this list.

There are no plans to make this list open for everyone (i.e. non-maintainers) as of yet. We may decide to publish archives after some duration, but none of this is written in stone.

Thanks!

**Comment by greenpau** [comment]
@miekg , greenpau@outlook.com.

**Comment by fturib** [comment]
ftur@infoblox.com

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] coredns maint..." ]
>@miekg , greenpau@outlook.com.

done

**Comment by miekg** [comment]
maintainers@coredns.io is live with the majority of peeps here added. Thanks!

(hope to add everyone in the end)

**Comment by miekg** [comment]
closing, has been setup; not everyone is on this list yet, but closing is done.
