### ISSUE TITLE
Run benchmark test in the CI

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2109]
We currently don't run any of the benchmark tests in the CI - we should.

Two options:
1. enable `--bench` in the current .travis.yml
2. new travis conf (can you have more than 1?) for just the bench, so they don't pollute the tests them selves.

Extra bonus points if we can show a diff from master with `benchcmp`  (if that is still the tool du jour)

**Comment by miekg** [comment]
We have a solution in place, but its a bit spammy (reports back into a comment) and not trustworthy because runtime varies to much on travis.

We should
a) run this on real hardward
b) use the Checks api from github

**Comment by chrisohaver** [comment]
There's an example of the checks API in the coredns/ci repo... if we want to update from travis.

But if we move it to the coredns/ci (which runs on hardware), that already uses checks api, so we could just append it to the log output of coredns/ci.
