### ISSUE TITLE
The date format in logs should be the same

### ISSUE THREAD

**Issue by eugen-kleiner-mesh** [coredns/coredns#2114]
To reproduce you can start coredns with the config which forwards plugin which points to not existing  dns server.
Corefile:
```
.:53 {
    bind 127.0.0.2
    forward . 127.0.0.54:53
    log
    errors
}
```
Run ```dig github.com @127.0.0.2``` and see the logs from coredns:
```
127.0.0.1:42936 - [21/Sep/2018:00:09:46 +0300] 15164 "A IN github.com. udp 52 false 4096" SERVFAIL qr,rd 52 1.000780352s
2018/09/21 00:09:46 [ERROR] 0 github.com. A: read udp 127.0.0.1:59513->127.0.0.54:53: read: connection refused
```
```21/Sep/2018:00:09:46 +0300``` differs from ```2018/09/21 00:09:46``` though it is the same date.

**Comment by eugen-kleiner-mesh** [comment]
All plugins use "github.com/coredns/coredns/plugin/pkg/log" to output logs, but log plugin uses different way. So, I think it should be fixed either in log plugin or in log pkg.

**Comment by miekg** [comment]
Good point. Would be better if that was unified.

**Comment by fturib** [comment]
### Re-install the TimeZone in the time format.

Please, review the change of code : the TimeZone has been shift out, and I think it is important to be able to compare the date with other logs ...

FYI - @ynikanchyk, @ibvrubleg

**Comment by miekg** [comment]
Looking *again* at this change. Dropping of the timezone is the wrong thing today and still leaves the date format being different.

Also in `errors/errors.go`:
~~~
clog.Errorf("%d %s %s: %v", rcode, state.Name(), state.Type(), err)
~~~
`rcode` isn't the rcode but the return value from the handler which is something different. Should probably remove that as well.

**Comment by rdrozhdzh** [comment]
I would prefer the time format like RFC3339 (`2006-01-02T15:04:05Z07:00`) to be used by all plugins, i.e. it should be implemented in` plugin/pkg/log` instead of standard go log format.

And all plugins (including log and errors) should use `plugin/pkg/log` package for printing logs

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] The date form..." ]
>I would prefer the time format like RFC3339 (`2006-01-02T15:04:05Z07:00`) to be used by all plugins, i.e. it should be implemented in` plugin/pkg/log` instead of standard go log format.
>
>And all plugins (including log and errors) should use `plugin/pkg/log` package for printing logs

seems like an even better approach

**Comment by eugen-kleiner-mesh** [comment]
So, it means that the date in log plugin should be an unconfigurable prefix?

**Comment by rdrozhdzh** [comment]
Log plugin will continue support of `{when}` placeholder (since it just uses `plugin/pkg/replacer` package). Though, users will likely stop including this placeholder in their format settings to avoid date/time duplication. Perhaps, we should also remove it from default format if we switch to `plugin/pkg/log`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] The date form..." ]
>Log plugin will continue support of `{when}` placeholder (since it just uses `plugin/pkg/replacer` package). Though, users will likely stop including this placeholder in their format settings to avoid date/time duplication. Perhaps, we should also remove it from default format if we switch to `plugin/pkg/log`

yeah, as said previously unifying this would be nice. Note that dropping 
`{when}` is a end-user visible change, meaning we need a deprecation cycle for 
coredns releases.

**Comment by miekg** [comment]
the solution we merged drops the timezone; I'm reverting that one. This needs a better solution as discussed.

**Comment by ynikanchyk** [comment]
> Log plugin will continue support of `{when}` placeholder
> users will likely stop including this placeholder in their format settings to avoid date/time duplication

It looks like we have here another issue: `{when}` is described as "time of the query" on https://coredns.io/plugins/log/ but the actual implementation just uses `time.Now()` which definitely can be much later than time of the query. It would be no duplication after this inconsistency is fixed per documentation.

**Comment by miekg** [comment]
I think what @rdrozhdzh says in https://github.com/coredns/coredns/issues/2114#issuecomment-425371662 is the best way forward: a standard why of outputting time. Also moving `{when}` to the front of the log plugin seems sane(r). Question is should to a whole deprecation dance for just this change?

**Comment by miekg** [comment]
except the std log pkg doesn't support rfc3339... Anyway #2245 out for review.

**Comment by miekg** [comment]
fixed.
