### ISSUE TITLE
Watch functionality has no tests?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2131]
The gprc Watch functionality sorta builds upon the kubernetes watch functionality; there are however no tests? During #2128 nothing breaks during testing which is hard to believe.

**Comment by miekg** [comment]
Also makes sense to move this code into a watch.go file.

**Comment by miekg** [comment]
func TestServiceFQDN(t *testing.T) exists, but it uses api.Pod instead of object.Pod, same is true for the other tests.

**Comment by johnbelamaric** [comment]
yeah, minimal tests. also I never got to the docs, so it's sort of a stealth feature right now

**Comment by miekg** [comment]
watch has been removed for the time being; when it comes back it does need a bunch of tests.
