### ISSUE TITLE
CoreDNS fails on DNS Resolution of 90% of queries

### ISSUE THREAD

**Issue by phspagiari** [coredns/coredns#2133]
Hey there,

We are trying to move from KubeDNS to CoreDNS but we are facing a lot of errors in dns resolution as soon as we move to CoreDNS and scale down KubeDNS.

### Infrastructure information:
 - Cloud Provider: AWS
 - Kubernetes Version: 1.10.8
 - Network Plugin: Calico 2.6.7
 - ETCD: 3.2.24
 - Cluster size: 110+ nodes / 1200+ pods

### Installation and config
 - Used https://github.com/coredns/deployment/tree/master/kubernetes to create the resource files.
 - For config we tried a lot of combinations, but mostly:
```
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

and:
```
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream 10.164.0.2 8.8.8.8 8.8.4.4
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . 10.164.0.2 8.8.8.8 8.8.4.4
        cache 30
        loop
        reload
        loadbalance
    }
```
 - `10.164.0.2` is the AWS DNS Server of our VPC
 - Also, we tried with and without the values on upstream and proxy.
 - Applied the YAMLs, scaled down kube-dns.

### Errors
As soon as we moved to CoreDNS we start to see errors regarding dns resolution (inside a pod):

```
/ # host kubernetes.default
kubernetes.default.svc.cluster.local has address 172.20.0.1
;; connection timed out; no servers could be reached
```

```
/ # host kubernetes.default
;; connection timed out; no servers could be reached
```

##### Sometimes (10% of the case) the resolution works:
```
/ # host kubernetes.default
kubernetes.default.svc.cluster.local has address 172.20.0.1
```

##### We also experienced the same errors with external domains:
```
/ # host google.com
;; connection timed out; no servers could be reached
```

##### Doing a dig +trace

```
/ # dig +trace kubernetes.default.svc.cluster.local

; <<>> DiG 9.12.2-P1 <<>> +trace kubernetes.default.svc.cluster.local
;; global options: +cmd
.			5	IN	NS	B.ROOT-SERVERS.NET.
.			5	IN	NS	C.ROOT-SERVERS.NET.
.			5	IN	NS	D.ROOT-SERVERS.NET.
.			5	IN	NS	E.ROOT-SERVERS.NET.
.			5	IN	NS	F.ROOT-SERVERS.NET.
.			5	IN	NS	G.ROOT-SERVERS.NET.
.			5	IN	NS	H.ROOT-SERVERS.NET.
.			5	IN	NS	I.ROOT-SERVERS.NET.
.			5	IN	NS	J.ROOT-SERVERS.NET.
.			5	IN	NS	K.ROOT-SERVERS.NET.
.			5	IN	NS	L.ROOT-SERVERS.NET.
.			5	IN	NS	M.ROOT-SERVERS.NET.
.			5	IN	NS	A.ROOT-SERVERS.NET.




couldn't get address for 'B.ROOT-SERVERS.NET': failure
couldn't get address for 'C.ROOT-SERVERS.NET': failure
couldn't get address for 'H.ROOT-SERVERS.NET': failure
couldn't get address for 'I.ROOT-SERVERS.NET': failure
couldn't get address for 'J.ROOT-SERVERS.NET': failure
couldn't get address for 'M.ROOT-SERVERS.NET': failure
;; Received 431 bytes from 172.20.0.10#53(172.20.0.10) in 1 ms

.			86400	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2018092501 1800 900 604800 86400
.			86400	IN	RRSIG	SOA 8 0 86400 20181008170000 20180925160000 41656 . ON1axQXesZwQ4VG30hJEBu52hAOuZ1lXzlDC0DsHJJf7d68YfsP8D9cA O4mrYDGAR2tMn3M0tSzaMf6e2zIZUKEA0XPaIZPQmR9Sex377qt4KYbu 0LAFU8lGHRMMzCv2YF63AxCmB9wITjou6cVBibrRhbGZAt+iIJWl2A8n 2CnadAHjJ6u5rpijlTBB+SHe29eOg7PrCxSJcmlpVptOW4mwWOlj7aIL raqLjm2sHZAfAcswaU5h7bykf6L5zj7rqGSiM0DTShMfgOG99/QLhtTG ihmrnQ3UMiekkm3bEeKdoKm2DpyubFLpDgSynn3zLurEXgLIx4l8fd54 bjEPJg==
.			86400	IN	NSEC	aaa. NS SOA RRSIG NSEC DNSKEY
.			86400	IN	RRSIG	NSEC 8 0 86400 20181008170000 20180925160000 41656 . milXHsYIs90fTa1CWeAXypFHpxn8DZfU9IHpyHOtXAkepf2QkKJwq9/j vwyS6VMKeYUK0V5i6wGdg6ilEITK4RdCC4oxdQT69bv2dTDHcVAAtH8i WUk7mpQEu6bVvsHJn2La4Arqiy/+xkrRoodkHsu3iYQ0dXs1eD4rKyed 38rUFfR/CHY+qAV3+11JG6kCnR8N/tF8js4LEmZFa2AByVHo+IKVJa+7 827JZ7PprJ1DhmhQSsnA9eefF1KpvnHgApASLw3pqHM1jfcRe8j6Kob2 7fUvGBuOFlGrm5D7uhYIqOqj/h4flk7RNKw5USbne+f2bRbXtofrMq2f Fb5m5w==
loans.			86400	IN	NSEC	locker. NS DS RRSIG NSEC
loans.			86400	IN	RRSIG	NSEC 8 1 86400 20181008170000 20180925160000 41656 . b7iW0u5F1o0AijO1Qw5keTVSIbAX8Mj8GYe+e5+vf6unpsBcGC9Npb9T tNmMLWDdyKs5KDVkh4LzQKZqoalNjgyC+RYcBiCvGuedgcd5QgOqASsU Jd0phQw5OTYeSHGI9Pg/qBNMGD8M9ECHSKxrSvaq6fdGrcOKSF7iZvid XkEF5U6Un+ZnALFlIWRY4UgKOORapq95dlBZg+hKMazRfOVXmqsgWfeO Dz5v7FEXa0ilbG6c/niLkm0FGQP3UcTpqcuxxY0h5ehSyiRV+ZqKZeGD NcDXEb9PrFgV1So763IFrTRFLjuI59b9Fhu03Oix0TSAF9wvvoFS2Ozu 9sJdEQ==
;; Received 1085 bytes from 192.112.36.4#53(G.ROOT-SERVERS.NET) in 37 ms
```
Sometimes the dig hangs on the failures of ROOT SERVERS. 

CoreDNS didn't reproduce any error on any pod, only bootstrap log lines.

All applications running on our cluster start experiencing connection issues (internally and externally), like this example of a NewRelic Graph:
![image](https://user-images.githubusercontent.com/968339/46050997-7bc45480-c10d-11e8-8dbb-a6b1fa0ef30c.png)

Also, this is the result of the query `sum(rate(coredns_dns_response_rcode_count_total[1m])) by (rcode)` on Prometheus:
![image](https://user-images.githubusercontent.com/968339/46051046-b4fcc480-c10d-11e8-941f-cb998400f6d4.png)

We tried to change some plugins of CoreDNS, changed some values but no luck and the rollback was nedeed.

I will be more than happy to provide more data (if we have access to) and I will really appreciate any help from you guys.

**Comment by chrisohaver** [comment]
If you enable logging in CoreDNS, e.g. ...

```
.:53 {
        log
        errors
        health
        ...
```

Are either of the CoreDNS pods logging that they have receiving a request or logging an error when there is a client time out?

More detail on how to enable logging and get logs for CoreDNS [here](https://github.com/chrisohaver/website/blob/68ffe0f9fe43958f48171261e44d71ee89c24b4b/content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md).

**Comment by chrisohaver** [comment]
Regarding the high NXDOMAIN:NOERROR ratio, a high ratio is normal in Kubernetes.  This is due to the ClusterFirst DNS policy that Pods use by default.  An external dns lookup from a Pod will result in ~4 futile cluster/local domain searches before searching for the bare domain name.  E.g. When a pod resolves `coredns.io`, it will first try to resolve `coredns.io.default.svc.cluster.local`, `coredns.io.svc.cluster.local`, `coredns.io.cluster.local`, `coredns.io.myinternaldomain.com`, before trying `coredns.io`

**Comment by phspagiari** [comment]
@chrisohaver Oh, that makes totally sense (the high `NXDOMAIN` ratio). I will enable the `log` plugin and see what shows up.

I tried a different approach and applied the `coredns` with a different service on kubernetes (with different `ClusterIP`). So I was able to test directly using as custom DNS Server with `dig`, like: `dig @coredns.kube-system +trace kubernetes.default`

I started to see the same "hangs" on queries, but I realised when I removed the `Tolerations` to coredns run also on master nodes, the hangs stopped. I still don't know why but when I have `coredns` pods running on master nodes the DNS start falling.

Since I only got this problem on our production cluster, I will try again later tonight and return with more results (also with logs).

**Comment by chrisohaver** [comment]
FYI, I dont think `dig` will follow search domains by default, so for a search of a short name like `kubernetes.default`, you need to add the `+search` option... 

> I realised when I removed the Tolerations to coredns run also on master nodes, the hangs stopped. I still don't know why but when I have coredns pods running on master nodes the DNS start falling.

That suggests pod network issue on the master node.  If so, it would affect any pod running on master.

**Comment by phspagiari** [comment]
I'm not sure if it's a network issue since we run lots of pods on master nodes without problems (even our etcd runs on master nodes). I will dig more to make sure if this is really a symptom and not a coincidence.

**Comment by chrisohaver** [comment]
If the network is a little flaky, it could hit DNS UDP traffic a lot harder, since a single dropped packet in UDP can result in a timeout, whereas with TCP a dropped packet is recoverable with TCP handshaking.

You could try TCP DNS queries to see if they are more reliable when DNS pods are on the master node.

etcd I believe runs on hostNetwork, which means it uses the interfaces of the host node it's running on - e.g. it doesnt get assigned an IP in the pod cidr by the network plugin.

**Comment by phspagiari** [comment]
@chrisohaver after long tests and digging we can confirm: you are right 😄. One of our masters was hitting network problems, since the symptoms wasn't so clear (a lot of pods running ok and just CoreDNS having problems), we needed to do many tracings and debuggings to find the problem. After a rollout of this master everything started to working again. 

Thank you Chris, I really appreciated your help!

**Comment by therevoman** [comment]
@phspagiari would you mind sharing how you traced and debugged the issue.   i have a client experiencing a similar issue.
