### ISSUE TITLE
Windows is not supported

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#2138]
Latest version of CoreDNS always reports that something is not supported by Windows:
```
2018/09/27 15:24:01 Using high precision timer
.:53
2018/09/27 15:24:01 [INFO] CoreDNS-1.2.2
2018/09/27 15:24:01 [INFO] windows/amd64, go1.11,
CoreDNS-1.2.2
windows/amd64, go1.11,
2018/09/27 15:24:01 not supported by windows
```
CoreDNS continues to work as nothing wrong is happened, but it doesn't respond on any DNS requests. It is reproducible with any configuration, even with the default one.

I believe that it is related to #2002, but now it happens always, not only on config reload. It is clear that it is caused by poor support of Windows in the Go network library, but if Windows is claimed as supported by CoreDNS and Caddy, the issue should be workarounded somehow.

**Comment by fturib** [comment]
Hum .. that needs a Windows to debug CoreDNS in order to see at least what/when in the code is triggered this message.
@ibvrubleg : do you have ability (I am thinking you may have a windows, at least for test) to point the line that raise the message ?

**Comment by ghost** [comment]
@fturib, I've played with debugger a bit. The message is displayed [here](https://github.com/mholt/caddy/blob/master/caddy.go#L808). I'll look into it a bit deeper.

**Comment by fturib** [comment]
I see .. not easy to found out where it is really located, and if it is Caddy or CoreDNS.
Would be great if you can find the code line that relay the error from Go libs ...

**Comment by ghost** [comment]
@fturib, these calls lead us to the error:

1. [startServers](https://github.com/mholt/caddy/blob/master/caddy.go#L791)
2. [ServePacket](https://github.com/coredns/coredns/blob/master/core/dnsserver/server.go#L133)
3. [ActivateAndServe](https://github.com/miekg/dns/blob/master/server.go#L390)
4. [setUDPSocketOptions](https://github.com/miekg/dns/blob/master/udp.go#L57) (actually, both IPv6 and IPv4 versions of the code return EWINDOWS)
5. [SetControlMessage](https://github.com/miekg/dns/blob/master/vendor/golang.org/x/net/ipv6/endpoint.go#L81)
6. [setControlMessage](https://github.com/miekg/dns/blob/master/vendor/golang.org/x/net/ipv6/control_windows.go#L15)

**Comment by fturib** [comment]
hum this call of "setUDPSocketOptions" is here since 2014 ...
and within that call all is in place since 12/4/2017 ... (including the non implementation of setControlMessage)

so... what changed lately ?

**Comment by fturib** [comment]
the creation of the ListenPacket() [changed slightly on 19/9/18 with the refactoring ParseHostOrFile](https://github.com/coredns/coredns/blob/ae2a0c62b71f18e594bc5565b00fb8a4d6ef44fc/core/dnsserver/server.go#L147).
If that is really the origin, it means that before that change, the ListenPacket was returning a IPConn instead of UDPConn... is that possible we did not notice ?

**Comment by ghost** [comment]
It seems, [this commit](https://github.com/miekg/dns/commit/bfbb1715afbeb1e50ce72970d31f71564ae94c6f) breaks Windows support. According to [the PR](https://github.com/miekg/dns/pull/738), it was merged without testing because "who runs windows these days".

**Comment by miekg** [comment]
Tagged miekg/dns 1.0.12 with this rollback in.

**Comment by miekg** [comment]
closed via #2150

**Comment by fturib** [comment]
Great !
Thanks @ibvrubleg to investigate and find the root cause !

**Comment by tmthrgd** [comment]
I've filed a bug upstream as golang/go#27966.
