### ISSUE TITLE
autopath + k8s expected behaviour?

### ISSUE THREAD

**Issue by Globegitter** [coredns/coredns#2142]
I am just testing coredns (1.2.2 on a kops managed cluster running k8s 1.10.7) + autopath, which sounds great in theory, but after enabling it and looking at the monitors I am not so sure what to make of the results and if it improved anything or not (or will improve anything over the longer run).
What I am seeing is:
 - Number of requests go down by about 40% (from ~50 to ~30rps)
 - NXDOMAIN responses go down by about 60% (from ~40 to ~15rps)
 - NOERROR responses go up by about 60% (from ~10 to ~16rps)
 - response time goes up ~2-4x (median: from around 215μs up to 850μs-1ms, 90th: from around 16ms up to 70ms, 99th: form 230ms-320ms to 390ms-750ms)
 - caching seems to disappear entirely (at least any metrics for it)
- memory usage has not changed significantly

The first three points seem to make sense to me, but I am a bit surprised about the cache just seemingly to disappear and the metrics for the response time going up that much. Is that to be expected? 

I have seen https://github.com/coredns/coredns/issues/1248 which could relate the caching behaviour, but just curios to hear if this all sounds normal or if there is possibly something to be improved about our setup.

**Comment by fturib** [comment]
About the cache disappearing, I think that is tied to an issue on metrics with reload (cache is still there, but not the metrics, after a reload) see : https://github.com/coredns/coredns/issues/2111

**Comment by johnbelamaric** [comment]
The response time metrics going up is probably because for those queries in which auto path is necessary, it all gets counted in a single response time. Overall the response time is going to be less for those queries than if it had to do the same actual requests from the client.

**Comment by Globegitter** [comment]
@johnbelamaric That is what I thought, I just did not expect it to go up by that much and in combination with the missing cache metrics was a bit alarmed. But since the cache issue is indeed a bug I suppose it all makes sense - thanks.
