### ISSUE TITLE
TTL for negative responses

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#2158]
The plugin/cache documentation says

> For the negative cache, the SOA's MinTTL value is used. A TTL of zero is not allowed.

My question what is the reason for this? Why TTL of SOA record is ignored and why zero TTL is not allowed? 
How external resolver can prevent caching negative (e.g. NXDOMAIN) responses?

Let's consider the following case.

Client -> coredns+cache -> upstream resolver -> name server

If client queries non-existent domain, upstream resolver will return NXDOMAIN and cache the response say for 1900 seconds. If SOA minTTL => 1800 then coredns will cache this response for 1800 seconds.
Lets assume that next minute the requested domain is added to name server.
Client will still be getting NXDOMAIN from coredns cache for next 1800 seconds, then the request will pass to upstream resolver and response will be taken from its cache with SOA record's TTL 100. And coredns will cache this response for another 1800 seconds.
So, client won't be able to access the new site for 3600 seconds in total despite that domain name exists and upstream server could give us positive response (if we ask for it) in last 1700 seconds of 3600.

Also, in description of TTL field at https://www.ietf.org/rfc/rfc1035.txt (3.2.1. Format) I can see a note

> For example, SOA records are always distributed with a zero TTL to prohibit caching.

On practice, I didn't see that resolvers send SOA record with zero TTL. But at least, seems, it makes sense to return SOA with TTL = 0 to prevent caching on client side. So, I am surprised that coredns/cache doesn't honor this TTL value.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] TTL for negative ..." ]
>The plugin/cache documentation says
>
>> For the negative cache, the SOA's MinTTL value is used. A TTL of zero is not allowed.

See https://tools.ietf.org/html/rfc2308.html. I you want zero you should put 
zero in that field.

**Comment by rdrozhdzh** [comment]
I looked through RFC 2308 and it states

> The TTL of this
>    record is set from the minimum of the MINIMUM field of the SOA record
>    and the TTL of the SOA itself, and indicates how long a resolver may
>    cache the negative answer.

This is related to Negative Answers from Authoritative Servers. And I didn't find any info on how should behave proxy if it gets response from upstream resolver. I believe it should behave the similar way, i.e. use a minimal value of SOA.MINIMUM and SOA TTL, or just use SOA TTL since it was already compared to SOA.MINIMUM in upstream resolver or authoritative server. And I didn't find any explanation of 
> A TTL of zero is not allowed

Also, I'm not sure that it is a good idea to forge SOA record on upstream resolver side to prevent caching it on client side.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] TTL for negat..." ]
>I looked through RFC 2308 and it states
>
>> The TTL of this
>>    record is set from the minimum of the MINIMUM field of the SOA record
>>    and the TTL of the SOA itself, and indicates how long a resolver may
>>    cache the negative answer.
>
>This is related to Negative Answers from Authoritative Servers. And I didn't find any info on how should behave proxy if it gets response from upstream resolver. I believe it should behave the similar way, i.e. use a minimal value of SOA.MINIMUM and SOA TTL, or just use SOA TTL since it was already compared to SOA.MINIMUM in upstream resolver or authoritative server. And I didn't find any explanation of

>> A TTL of zero is not allowed

This is old text when the cache actually didn't allow zero ttl records, i.e. not 
true anymore.

>Also, I'm not sure that it is a good idea to forge SOA record on upstream resolver side to prevent caching it on client side.

TTLs are hints to caching, so you're free to do what you want basically.

**Comment by rdrozhdzh** [comment]
So, @miekg, you don't want the current implementation to be changed, right?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] TTL for negat..." ]
>So, @miekg, you don't want to change current implementation, right?

No feelings about that; if something is off with neg ttl (or too different 
compared to pos ttl) feel free to fix it.

**Comment by fturib** [comment]
I read the code of the cache, and I understand that you can handle TTL of 0, if the TTL fits inside the range of the cache.

1- TTL of msg is computed based on the TTL of subparts of the msg
2- TTL is adapted to fit inside the range of the cache
3- if TTL is 0 at time to set into the cache, the operation of adding to cache is skipped (it makes no sense to add an expired info in the cache).

In other words, if you wish to respect the SOA TTL=0 coming from upstream, then you need your negative cache to have a range down to 0. (by default the minimum value is 5 sec).

You need then a stanza:
```
cache {
   denial 1800 0
}
```

Doing so, your negative cache will be active, but all negative replies with an SOA TTL=0 will be not cached.


### Questions
- Am I correct ?
- We may need to reformulate the README of the cache ?
- Does it make sense to have the default MinTTL for negative cache to 0 (instead of 5sec) ?

**Comment by rdrozhdzh** [comment]
Negative DNS response looks like
```
$ dig @8.8.8.8 guydgewuyf.net +noedns

; <<>> DiG 9.11.2 <<>> @8.8.8.8 guydgewuyf.net +noedns
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50487
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;guydgewuyf.net.			IN	A

;; AUTHORITY SECTION:
net.			899	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1539251608 1800 900 604800 86400
```
Here we have `status: NXDOMAIN` and SOA record in AUTHORITY section.
coredns ignores TTL value of SOA RR (899 in the example above) for negative responses and instead uses SOA.MINIMAL_TTL value (86400 in the example above). Then this value is adjusted to be between MinTTL and TTL settings of `denial` option of cache plugin, i.e. between 5 and 1800 by default, which results in 1800 

So, if we get 
```
net.			0	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1539251608 1800 900 604800
```
in response (i.e. SOA TTL = 0), then this response will be put in negative cache with TTL 1800 by default
See related code
https://github.com/coredns/coredns/blob/c8fb66f8cc60ff17b916b033982c5491f23cdcc9/plugin/pkg/dnsutil/ttl.go#L35-L40

**Comment by fturib** [comment]
@rdrozhdzh : Thanks for your detailed explanation ! (I was missing the point TTL and MIN-TTL)

Looking back to the [RFC2308: Negative Caching of DNS Queries (DNS NCACHE)](https://tools.ietf.org/html/rfc2308.html) pointed by Miek, 
I agree with you, we are not computing the TTL the way it is expected.
and I copy a part you already pointed above in the comments:

> **3 - Negative Answers from Authoritative Servers**
> 
>    Name servers authoritative for a zone MUST include the SOA record of
>    the zone in the authority section of the response when reporting an
>    NXDOMAIN or indicating that no data of the requested type exists.
>    This is required so that the response may be cached.  **The TTL of this
>    record is set from the minimum of the MINIMUM field of the SOA record
>    and the TTL of the SOA itself**, and indicates how long a resolver may
>    cache the negative answer.  The TTL SIG record associated with the
>    SOA record should also be trimmed in line with the SOA's TTL.
> 

I extract the information here:

**The TTL of this record is set from the minimum of the MINIMUM field of the SOA record _and the TTL of the SOA itself_**

And, right now, we are just taking MINIMUM field of the SOA record but NOT combining with TTL of the SOA itself.


So, I understand it is a missed of current computation, and we should fix it.
Could you send a PR for this change ?

IMO, we should just compute the min(SOA.TTL, SOA.minTTL) in case of NameError...  But you may have a better idea here.

**Comment by rdrozhdzh** [comment]
To be honest, I tend to feel that cache plugin should process SOA TTL the same way as other record types, i.e. only TTL field from RR header should be taken into account.

The logic mentioned above (minimum of the MINIMUM field of the SOA record and the TTL of the SOA itself), is relevant only for authoritative servers, i.e. the servers which create DNS response from their data sources like Master File. Perhaps plugins like `file` should follow this rule.

Intermediate name servers (proxies, forwarders) which receive this SOA record from other authoritative server should not calculate minimal value, because it should already been calculated by authoritative server and passed as TTL field of SOA header. There is no sense to calculate minimum again on each proxy.

So, each proxy server (and `cache` plugin as well) should just process SOA TTL the same way as other records. I.e. we should remove the code specific for SOA record in negative queries.

However, if @miekg is not ok with removing this specifics then we could at least calculate minimum of two values as proposed by @fturib. That's why I would like to know first which change (or no change) is preferable to @miekg

**Comment by chrisohaver** [comment]
I agree with @rdrozhdzh, that I think the RFC is intending to refer to the authoritative server that _creates_ the negative response response - _not_ for an intermediate server that is relaying the response along from an upstream source.  The the latter case, we should apply our min/max values of the _cache_, not the SOA min.

**Comment by rdrozhdzh** [comment]
One more incompatibility is related to the lines 
https://github.com/coredns/coredns/blob/c8fb66f8cc60ff17b916b033982c5491f23cdcc9/plugin/pkg/dnsutil/ttl.go#L17-L20

The RFC2308 states 
```
   Negative responses without SOA records SHOULD NOT be cached as there
   is no way to prevent the negative responses looping forever between a
   pair of servers even with a short TTL.
```

i.e. we should return TTL=0 (and don't cache) if no SOA record

**Comment by chrisohaver** [comment]
> ... no way to prevent the negative responses looping forever between a pair of servers ...

that doesn't make sense to me.

**Comment by chrisohaver** [comment]
> Negative responses without SOA records SHOULD NOT be cached ...

I recall that `dnsmasq` has an option to inject an SOA with a small TTL into SOA-less negative responses.  But it's not default behavior.  Similarly, our default behavior should probably follow the SHOULDs in the RFCs.  i.e. this should probably be an option.

**Comment by chrisohaver** [comment]
>  i.e. this should probably be an option.

On the other hand, the upstream authoritative server is violating an RFC MUST by not including an SOA in the negative response. So injecting an SOA with a small TTL is "fixing things."  So - maybe this is fine default behavior.

The reason that the RFC gives for not doing this still doesn't make sense to me.

**Comment by rdrozhdzh** [comment]
Perhaps, I had to cite two paragraphs from RFC2308 to make it clearer. Though, I still not fully understand what they mean

>    Negative responses without SOA records SHOULD NOT be cached as there
>    is no way to prevent the negative responses looping forever between a
>    pair of servers even with a short TTL.
> 
>    Despite the DNS forming a tree of servers, with various mis-
>    configurations it is possible to form a loop in the query graph, e.g.
>    two servers listing each other as forwarders, various lame server
>    configurations.  Without a TTL count down a cache negative response
>    when received by the next server would have its TTL reset.  This
>    negative indication could then live forever circulating between the
>    servers involved.
> 

I personally don't mind keeping the small TTL for such cases if everyone is ok with this.

Another minor issue in the code
https://github.com/coredns/coredns/blob/c8fb66f8cc60ff17b916b033982c5491f23cdcc9/plugin/pkg/dnsutil/ttl.go#L17-L20
is that we can have an OPT record in Additional section and nothing else, which is not caught by the code above
