### ISSUE TITLE
Plugin/Errors - add a "consolidate" option to limit the logging of errors

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#2168]
## Presentation

@rdrozhdzh extended plugin ERRORS for Infoblox purposes.
This extension would be useful for everyone.

The changes added (from standard ERRORS plugin of CoreDNS) are:
* added a consolidate option to prevent intensive logging of errors of particular type
* updated README.md
* added unit tests, including concurrent one
* used github.com/coredns/coredns/plugin/pkg/log to make log consistent with other plugins

Please, have a look at this repo : https://github.com/infobloxopen/coredns-plugin-errors

The plan would be to just integrate this new ERRORS plugin as the standard one.

## Adding "consolidate" option in ERRORS

Extra knobs are available with an expanded syntax:

```
errors {
	consolidate DURATION REGEXP
}
```
Option consolidate allows collecting several error messages matching the regular expression REGEXP during DURATION. After the DURATION since receiving the first such message, the consolidated message will be printed to standard output, e.g.

> 2 errors like '^read udp .* i/o timeout$' occurred in last 30s

Exemple of syntax:
```
. {
    forward . 8.8.8.8
    errors {
        consolidate 5m ".* i/o timeout$"
        consolidate 30s "^Failed to .+"
    }
}

```

**Comment by rdrozhdzh** [comment]
thank you @fturib for presenting this feature.

The changes comparing to original 'errors' plugin could be easily reviewed here https://github.com/infobloxopen/coredns-plugin-errors/pull/3/commits/eb323591a433420049495348c562ceb6f6f1d6bc

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Plugin/Errors - a..." ]
>## Presentation
>
>@rdrozhdzh extended plugin ERRORS for Infoblox purposes.
>This extension would be useful for everyone.
>
>The changes added (from standard ERRORS plugin of CoreDNS) are:
>* added a consolidate option to prevent intensive logging of errors of particular type
>* updated README.md
>* added unit tests, including concurrent one
>* used github.com/coredns/coredns/plugin/pkg/log to make log consistent with other plugins
>
>Please, have a look at this repo : https://github.com/infobloxopen/coredns-plugin-errors

Nice! (haven't looked at the impl. yet)

Doing this also for logging makes sense.

**Comment by fturib** [comment]
@rdrozhdzh : can you add the PR to integrate the coredns-plugin-errors in CoreDNS  as replacement of errors ?
