### ISSUE TITLE
add the ability to connect to a kubernetes endpoint using a token.

### ISSUE THREAD

**Issue by raffaelespazzoli** [coredns/coredns#2169]

**Comment by fturib** [comment]
@raffaelespazzoli : 
- any description on what would be the config in the Corefile in that case ? 
- And maybe pointing the documentation of the token feature in Kubernetes ?

Thanks!

**Comment by raffaelespazzoli** [comment]
a fragment of the `Corefile` would look like this:
```
...
ca_cert: <ca cert_file>
token: <token>
...
```

a token can be extracted from a service account's secret as described here:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens

**Comment by miekg** [comment]
think this can be closed.
