### ISSUE TITLE
performance of CoreDNS and kube-dns ?

### ISSUE THREAD

**Issue by ckcd** [coredns/coredns#2170]
Hi,
First of all, thanks for this nice repo,

I'm use kube-dns in kubernetes and NOW I want to use CoreDNS to replace it, before the replacement I want to test and compare the extreme performance (such as QPS and Average Latency) of these DNS resolver, but I don't have enough perf tools to achieve this goal,

1. For now, I'm using [dnsperf](https://github.com/akamai/dnsperf) to do some tests, this is something like:
```
$ dnsperf -s 172.16.0.10 -d input_file -c 10 -T 10

Statistics:

  Queries sent:         16457
  Queries completed:    16125 (97.98%)
  Queries lost:         232 (1.41%)
  Queries interrupted:  100 (0.61%)

  Response codes:       NOERROR 16099 (99.84%), SERVFAIL 3 (0.02%), NXDOMAIN 23 (0.14%)
  Average packet size:  request 30, response 59
  Run time (s):         66.381314
  Queries per second:   242.914746

  Average Latency (s):  0.334600 (min 0.107757, max 26.445763)
  Latency StdDev (s):   0.319399
```

But:
1. this dnsperf needs to prepare a input file, for now I only test a list of public domain such as `google.com`, AND I don't know how to test the preformance of cluster service (and endpoints);
2. I see someone talk about `kubemark`, but I don't know if it is helpful.
 
can anyone tell me some dns perf tools ?

Or is there any compare results of CoreDNS and kube-dns ?

thanks !!!

**Comment by stp-ip** [comment]
We have a perf-tests repository with a few helpful scripts and benchmarks: https://github.com/coredns/perf-tests

**Comment by chrisohaver** [comment]
We have adapted the kubernetes dns [perf-tests](https://github.com/kubernetes/perf-tests/tree/master/dns) to work with CoreDNS and kube-dns.

We did some comparisons of kube-dns and CoreDNS with cache _disabled_.
