### ISSUE TITLE
ability to use the kuberntes plugin more than once per server block

### ISSUE THREAD

**Issue by raffaelespazzoli** [coredns/coredns#2174]
Hi,

I'd like an instance of coredns to be able to manage names for multiple kubernetes clusters. Here is the configuration that I am using:

```
.:53 {
    errors
    health
    
    kubernetes cluster.raffa1 in-addr.arpa ip6.arpa {
        endpoint https://console.raffa1.casl-contrib.osp.rht-labs.com:8443 
        upstream
        kubeconfig /etc/clusters/kubeconfig_raffa1 raffa1
    }
    
    kubernetes cluster.raffa2 in-addr.arpa ip6.arpa {
        endpoint https://console.raffa2.casl-contrib.osp.rht-labs.com:8443 
        upstream
        kubeconfig /etc/clusters/kubeconfig_raffa2 raffa2
    }
    
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```
the coredns server is failing to start with this error:
```
2018/10/10 01:06:10 plugin/kubernetes: this plugin can only be used once per Server Block
```
why does this limitation exist? 
Is there a way to workaround it?

**Comment by rajansandeep** [comment]
@raffaelespazzoli I suggest you use the [kubernetai](https://github.com/coredns/kubernetai) plugin instead of kubernetes plugin for multiple kubernetes clusters.

**Comment by chrisohaver** [comment]
> why does this limitation exist?

A PR to allow multiple declarations for `kubernetes` was rejected from `coredns/coredns`, IIRC the reasoning given was that it complicated the code for too narrow a use case. Hence it's in a separate repo ([kubernetai](https://github.com/coredns/kubernetai)) as an external plugin.

This could possibly change if the `kubernetai` plugin gets more use/traction. E.g. if it's used in a k8s sanctioned cross-cluster service discovery solution.
