### ISSUE TITLE
Conditional forward

### ISSUE THREAD

**Issue by bcho** [coredns/coredns#2176]
Hi, is this possible to do conditional forward? One example may be:

```
.:5353 {
  forward_if . 8.8.8.8 {
    match_regex '/some.regex.to.match/'
    # fall through if not match
  }
  
  // fall through to default rule
  forward . 1.1.1.1
}
```

I know the simplest way to do should be expand the`match_regex` part to multiple server blocks, but in some scenario, we may not easily to generate every case with its own block. (Or, maybe use redis / etcd as backend?) Any suggestions for this use case?

**Comment by chrisohaver** [comment]
Not really ... aside from the right justified domain match (e.g. `forward example.com 1.1.1.1`). 
There is an ACL-like/policy plugin in development that may allow for conditional routing.

But given the plugins that exist now, you might be able to manage some conditional routing with combination `rewrite` and `forward`.  Although I think it would be quite convoluted and involve self-forwarding.

There is an `except` option in `forward` which is conceptually similar, so IMO it would be acceptable to add a `match` option to `forward`.

**Comment by bcho** [comment]
Thanks for your quick reply!

> There is an except option in forward which is conceptually similar, so IMO it would be acceptable to add a match option to forward.

Yep, but I am afraid the `match` will become thing like nginx's evil if with great performance penalty, as well as too many implementation details for `forward`. :joy:

**Comment by chrisohaver** [comment]
> Yep, but I am afraid the match will become thing like nginx's evil if with great performance penalty

Well only for those who use it.  It could be a substring match instead of a regex if regex performance is a concern.

> as well as too many implementation details for forward...

I don't think thats the case, but I don't steer the ship.

**Comment by bcho** [comment]
Taking `match` for example, I may want something beyond simple string matching,  maybe something like overriding the forward's [match][] method:

```
func (f *Forward) match(state request.Request) bool {
	if !plugin.Name(f.from).Matches(state.Name()) || !f.isAllowedDomain(state.Name()) {
		return false
	}

         if !f.matchFunc(state) {
           return false
         }

	return true
}
```

I will leave this issue open and do some local prototypes first.

[match]: https://github.com/coredns/coredns/blob/49c776df4cdd1948c9fedbb4ec4b313969d9dfa1/plugin/forward/forward.go#L165-L171

**Comment by miekg** [comment]
I'm not a fan of adding these kind of checks/features in every plugin.

This issue also seems stale, so I'm inclined to close it.
