### ISSUE TITLE
Is corebot registered for pull_request_review event?

### ISSUE THREAD

**Issue by dilyevsky** [coredns/coredns#2178]
Hey @miekg on #2160 I tried to `/merge` in approval comment but corebot ignored it. I can see the code is there to parse command out of `pull_request_review` event (https://github.com/miekg/dreck/blob/f21dcd0a47968af9248162cd798423133d04b8b8/http.go#L139) so I suspect the webhook doesn't have the event toggled. Should it be enabled?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Is corebot regist..." ]
>Hey @miekg on #2160 I tried to `/merge` in approval comment but corebot ignored it. I can see the code is there to parse command out of `pull_request_review` event (https://github.com/miekg/dreck/blob/f21dcd0a47968af9248162cd798423133d04b8b8/http.go#L139) so I suspect the webhook doesn't have the event toggled. Should it be enabled?

No, you're probably not in the "right" list or something. I have the logs, would 
be nice to be able to link to them (somehow)

**Comment by dilyevsky** [comment]
Well it did obey the command in regular issue comment so that's weird because it basically follows the same select-case for both review and comment. Logs would be nice yeah

**Comment by miekg** [comment]
solved by owners update (i think)
