### ISSUE TITLE
plugin/cache: min TTL defaults should be 0

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#2189]
Having a configurable minimum TTL is a nice option (#2055), but it should IMO default to zero.  Otherwise the default behavior will keep some records in cache longer than the authoritative source intended intended - which I don't think is a good default behavior.  

This should be the case for both positive and negative minimum cache TTLs. Currently they both default to 5 seconds.

I think #2055 unintentionally changed the default behavior from a 0 minimum TTL, to 5 seconds TTL.

**Comment by chrisohaver** [comment]
closing - see comment in #2198

**Comment by aaronriekenberg** [comment]
I think it might be reasonable to have 0 as the default minimum TTL for the cache plugin, but just want to note this change was not unintentional in https://github.com/coredns/coredns/pull/2055 to set the default minTTL and minNTTL to dnsutil.MinimalDefaultTTL or 5 seconds.

I originally set the default minTTL and minNTTL to 0 in that PR, and got a review comment from @mikeg to use dnsutil.MinimalDefaultTTL (5s) instead: https://github.com/coredns/coredns/pull/2055#discussion_r214089712

The concern was consistency with the commentary in pkg/dnsutil/ttl.go (https://github.com/coredns/coredns/blob/master/plugin/pkg/dnsutil/ttl.go#L68)

**Comment by chrisohaver** [comment]
> just want to note this change was not unintentional in #2055

Ah OK, Thanks for clarifying.  I didn't see that comment.
