### ISSUE TITLE
plugin/rewrite: Always fix answer when question is rewritten

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#2202]
In `rewrite`, when we change the question in a request, we need to fix the question in the response to match the original question.  If you don't do this some DNS clients complain of a mismatch between the question and answer.  The `rewrite` plugin allows you to do this with "answer" rules.

IMO, since you always want to rewrite the question in the answer to match the original question, this should be the default behavior.  There should be no need to specify an answer rule.  This would make rewrite rules easier to write, and would do away with the verbose "answer" rewrite syntax.  It also cleans up the code a bit, removing the parsing and special checks for the answer rules.

**Comment by greenpau** [comment]
> There should be no need to specify an answer rule. This would make rewrite rules easier to write, and would do away with the verbose "answer" rewrite syntax. 

@chrisohaver , hope you doing well! I am getting back to the rewrite code base. Have some some to tinker. I agree with what you are saying. At the same time, there could be times when "answer" clause is necessary. I can't think about a specific use case at the moment :thinking: :thinking: return multiple CNAMEs, etc.

I also think that we could improve on the syntax of `rewrite` rules. 

I want to take think opportunity and connect this issue with https://github.com/coredns/coredns/issues/2389. I am planning working on it. Let's see how we can improve.
