### ISSUE TITLE
V1.2.3 error in log: expected type *object.Service, but watch event object had type *v1.Service

### ISSUE THREAD

**Issue by yvespp** [coredns/coredns#2204]
With CoreDNS v1.2.3 and the Kubernetes plugin I see this error repeated in the logs: `expected type *object.Service, but watch event object had type *v1.Service`

Also I had a problem where a Kubernetes service resolved to the ip of the previous service (service was recreated). After I restarted the CoreDNS pods the service name resolved to the correct ip. I don't know if this is related, I can open a separate issue for that if you want.

```
.:53
--
2018/10/17 05:46:19 [INFO] CoreDNS-1.2.3
2018/10/17 05:46:19 [INFO] linux/amd64, go1.11.1, 8cc8afa
CoreDNS-1.2.3
linux/amd64, go1.11.1, 8cc8afa
2018/10/17 05:46:19 [INFO] plugin/reload: Running configuration MD5 = 3f70d93c15ac6136048442dcd6ecff9e
E1017 05:51:27.152064 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 05:51:27.649655 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 05:51:43.654331 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 05:53:30.222916 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 05:53:30.222975 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 05:53:30.224090 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 05:55:47.969295 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 05:56:18.743997 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:02:25.223889 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:02:25.223924 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:02:25.225441 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:02:25.226529 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:02:25.227622 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:03:03.489166 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:03:03.502140 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:03:04.502926 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:03:04.595740 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:04:19.370279 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:04:21.599097 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:04:21.603576 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
E1017 06:08:37.673572 1 reflector.go:386] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: expected type *object.Service, but watch event object had type *v1.Service
...
2018/10/17 08:37:47 [INFO] SIGTERM: Shutting down servers then terminating
```

Config (Helm template):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coredns.fullname" . }}
data:
  Corefile: |-
    .:53 {
        errors
        health
        kubernetes {{ .Values.clusterDomain }} in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        file /etc/coredns/ingress.db {{ .Values.ingressDomain }}
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
  ingress.db: |
    {{ .Values.ingressDomain }}.     IN      SOA     sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600
    *.{{ .Values.ingressDomain }}.   IN      A       172.23.23.23
```

**Comment by miekg** [comment]
They might. The memory stuff was a big PR, and we might have missed a thing
even with the testing. IOW I was afraid something might pop up. Hopefully a
fix is easy and we can add some extra tests for this. Alternative is
pulling that pr and try again :/

**Comment by chrisohaver** [comment]
The existing integration tests were not designed to check the client-go watch function.  
But since the memory PR, we are re-implementing part of the that - so in retrospect, we should have added some tests.  Specifically, that changing a service _after_ CoreDNS starts actually gets updated in CoreDNS - which may be what is missed here.  There are significant repercussions if thats the case.  Looking into it...

**Comment by chrisohaver** [comment]
FWIW, I verified, testing manually, that this issue causes CoreDNS to be unaware of any changes to services after CoreDNS starts up... i.e. service changes collected from the service watch.

At a glance, this does not look like a simple fix - but i'm not very familiar with the client-go watch code, so I could be missing something obvious.

**Comment by miekg** [comment]
I was afraid of that behavior.. :-( Can we as a start have such a test in the CI?

**Comment by fturib** [comment]
@miekg : it means this release 1.2.3 is invalid for Kubernetes plugin. 
How should we inform of it ? (I mean known bugs .. ).
Maybe adding a text in the https://coredns.io/2018/10/16/coredns-1.2.3-release :

**WARNING:** a  bug was found after this release on Kubernetes plugin. We recommend to not use this release when using Kubernetes plugin.

**Comment by chrisohaver** [comment]
> Can we as a start have such a test in the CI?

A test in the CI would be easy to add.

**Comment by miekg** [comment]
yes 1.2.3 is fobar wrt to the k8s plugin

**Comment by miekg** [comment]
potential PR: https://github.com/coredns/coredns/pull/2208
(without an actual test I can't tell if this would work, I would make sense, for endpoints we still had `api.Endpointst` in there because kubernetes/client-go is basically type less Go code)

**Comment by chrisohaver** [comment]
>potential PR: #2208
(without an actual test I can't tell if this would work, I would make sense, for endpoints we still had api.Endpointst in there because kubernetes/client-go is basically type less Go code)

I can test this right now on my laptop...

**Comment by chrisohaver** [comment]
> I can test this right now on my laptop...

Woot! it works! 

I'll add the test to CI now...

**Comment by fturib** [comment]
Great !
I think we need the CI test enhanced before we making a new release.
Be sure we have at least that now know use case verified. (for service and endpoints).

**Comment by miekg** [comment]
Yes, leaving this open until we have a test; then we can kick of a release.

**Comment by miekg** [comment]
release notes, 1.2.4 PR are all ready to be done.

**Comment by fturib** [comment]
That bug makes that the Services are not stored, so we have under estimated the memory in the scale test. We do not know how much, because the endpoints were stored.

I asked @rajansandeep to launch a scale test 2k nodes on Kubernetes, in ordre to confirm we are still ok (I mean below the expected limit) for the memory optimization.

We should have the result by tomorrow morning.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] V1.2.3 error ..." ]
>That bug makes that the Services are not stored, so we have under estimated the memory in the scale test. We do not know how much, because the endpoints were stored.

ah, good point. We might be back to square 1 on this :/

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
Yes - thats what I was referring to when I said "significant repercussions" above ... I should have been more specific. :(

Hopefully it's not too bad - Endpoints are larger because they scale up in size during the test (number of addresses/ports in each endpoints object scales up).  Services stay static at 10K and don't scale up.  We'd be in worse shape of we missed the Endpoints.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] V1.2.3 error ..." ]
>Yes - thats what I was referring to when I said "significant repercussions" above ... I should have been more specific. :(
>
>Hopefully it's not too bad - Endpoints are larger because they scale up in size during the test (number of addresses/ports in each endpoints object scales up).  Services stay static at 10K and don't scale up.  We'd be in worse shape of we missed the Endpoints.

yeah, I would be expecting to still see some benefit.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] V1.2.3 error ..." ]
>Yes - thats what I was referring to when I said "significant repercussions" above ... I should have been more specific. :(
>
>Hopefully it's not too bad - Endpoints are larger because they scale up in size during the test (number of addresses/ports in each endpoints object scales up).  Services stay static at 10K and don't scale up.  We'd be in worse shape of we missed the Endpoints.

I think we should release 1.2.4 regardless, the scale tests can wait, bit odd to 
add warning and fluff and don't have a release.

**Comment by chrisohaver** [comment]
CI test merged.

**Comment by miekg** [comment]
Ok, cool. Merging 1.2.4 version bump and kicking a release.

Worst case we didn't fix the mem stuff and we're back to square on, can't have a broken release being the latest.

**Comment by fturib** [comment]
I am ok to release 1.2.4 that fix issue asap.
We will continue to validate with scale test before electing the 1.2.4 as the one to push for Kunbernetes,

**Comment by chrisohaver** [comment]
@miekg,  

Good results with memory tests: the fixed code takes up a bit more memory, but not much.  Projecting to 5K nodes, we should come in around 160MB per instance, up from 140MB... which still has us comfortably below the memory requirement of 178MB.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] V1.2.3 error ..." ]
>@miekg,
>
>Good results with memory tests: the fixed code takes up a bit more memory, but not much.  Projecting to 5K nodes, we should come in around 150MB per instance, up from 140MB... which still has us comfortably below the memory requirement of 178MB.

Nice! (and *pfew*)

**Comment by chrisohaver** [comment]
I just noticed I wrote 150 - should have written 160 ... typo ...  still under the limit though.
