### ISSUE TITLE
resolver plugin

### ISSUE THREAD

**Issue by semihalev** [coredns/coredns#2216]
Hello community,

I and Miek discussed about the my recursive dns server project [(sdns)](https://github.com/semihalev/sdns) into CoreDNS plugin.

The project currently installed as recursive server on a private network, I checked latest, there was `1000/qps` and there is no issue or performance problem. Of course there are tons of different new idea, optimization, unknown issues etc.

If you think the project fit to CoreDNS, I would be happy to work about this.

**Here the some key features**
* Linux/BSD/Darwin supported
* DNS RFC compatibility
* Concurrent DNS lookups within listed servers
* DNS caching
* DNSSEC validation
* DNS over TLS support
* DNS over HTTPS support
* RTT priority within listed servers
* Basic IPv6 support (client<->server)
* Query based rate limit
* Access list
* Black-hole internet advertisements and malware servers
* HTTP API support
* Outbound IP selection

If you decide to continue about this and review the project, we can discuss some key improvements in this topic.

Thanks.

**Comment by yongtang** [comment]
Thanks @semihalev! I think CoreDNS is always inclusive and welcoming for any contributions.

**Comment by yongtang** [comment]
I could see lots of things has been done in  [(sdns)](https://github.com/semihalev/sdns),if there is any thing the community could help for improvement?

**Comment by semihalev** [comment]
There is no windows support, used some syscall signal notifies, if delete the notifies (not important) , it can be support windows also.

**Comment by miekg** [comment]
I think a full-blown resolver plugin would be a perfect fit for coredns.
There are some process things to figure out, mostly where the code lives
and how much control you want exercise on the resolver code.

We also need to do a careful review of the code

**Comment by yongtang** [comment]
Depending on the code size, and who maintains it, I think there might be several options:
1) As part of the `coredns/coredns` code base.
2) As a separate repo in `coredns` org.
3) As a external plugin (but bundled with the default coredns build)

**Comment by miekg** [comment]
@semihalev do you have any design documents? I.e. how does the resolver loop work, when does it exit, how does the cache work, how is the TTL determined etc?

**Comment by semihalev** [comment]
I don't have design documents, if necessary i can prepare. 

I started the project because there is no useful dns recursor server made with Go and Miek's dns library. I tested most of them.

I will create simple resolver loop call graph, I will share asap. This is very complex.

Caching:
There are 3 cache method. 

1. **Query Cache**
_Conditions:_ Response code doesn't matter and if found a RR in `(*dns.Msg).Answer` or `(*dns.Msg).Ns`
_Key_: MD5 hash with Question string formatted
_Cache:_ `*dns.Msg` `(*rl).RateLimiter` `time.Now()`
_Expire control:_ via RR's TTL, when one of RR's TTL < elapsed, then cache will remove, only for `dns.RcodeNameError` responses, all TTL replace with default expire time

2. **Error Cache**
_Conditions:_  Response code doesn't matter and if not found a RR in `(*dns.Msg).Answer` and `(*dns.Msg).Ns`
_Key_: MD5 hash with Question string formatted
_Cache:_ `time.Now()`
_Expire control:_ via default expire time from config

3. **AuthServer Cache**
_Conditions:_ Response code success and found a `*dns.NS` RR in `(*dns.Msg).Ns`
_Key_: MD5 hash with Question string formatted
_Cache:_ `[]*AuthServers` `[]*dns.DS` (parent zone RRs)  `time.Now()`
_Expire control:_ via RR's TTL, when one of RR's TTL < elapsed, then cache wil be remove

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] resolver plug..." ]
>I don't have design documents, if necessary i can prepare.
>
>I started the project because there is no useful dns recursor server made with Go and Miek's dns library. I tested most of them.
>
>I will create simple resolver loop call graph, I will share asap. This is very complex.

Thanks, i'm looking a bit through the code now.

There is some supporting code that you get for free in coredns, meaining this 
(as a plugin) would be smaller.

The cache and coredns's cache might clash or lead to double caching - but that's 
a later concern.

**Comment by johnbelamaric** [comment]
Nice! For #1, I think it will need to bake a while first. I mean, we should
start as an external plugin, and eventually integrate it directly. We could
host it as a repo on coredns org before then, but that would mean assigning
copyright to CNCF.

**Comment by miekg** [comment]
@semihalev are you willing to work on this? We don't need to host it under the coredns org, we can just start with it as an external plugin.

**Comment by semihalev** [comment]
I'm working on this, refactored whole structure, removed cache, edns, metrics and other internal modules from resolver so sdns is support middleware now. I will remove internal log module also. If you  like, i will convert [resolver](https://github.com/semihalev/sdns/tree/master/middleware/resolver) middleware as a coredns external plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] resolver plug..." ]
>I'm working on this, refactored whole structure, removed cache, edns, metrics and other internal modules from resolver so sdns is support middleware now. I will remove internal log module also. If you  like, i will convert [resolver](https://github.com/semihalev/sdns/tree/master/middleware/resolver) middleware as a coredns external plugin.

oh, nice. Yeah, let's start with. Even if it is an *external* plugin we could 
potentially still ship it by default.

Nice!

**Comment by miekg** [comment]
think we should aim to merge something here and say it's experimental. @semihalev you something that we merge?

**Comment by miekg** [comment]
Still cool to have, but seems to have stalled.

**Comment by SuperQ** [comment]
@semihalev, are you still interested in making this an official plugin?
