### ISSUE TITLE
Weird bug in PR #220

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#222]
This has not been merged, but when I start Coredns with following Corefile:

```
miek.nl:1053 {
    file miek.nl.signed {
        transfer to *
    #    transfer to 185.49.141.42
    }
    chaos CoreDNS "Miek Gieben" "miek@miek.nl"
    rewrite ANY HINFO
    errors stdout
    log stdout
    prometheus
}
```

coredns starts and then crashes because of a `panic` I added in `GetConfig()`:

```
len Keys 1
[miek.nl:1053]
Zone miek.nl. Port 1053
saveConfig miek.nl.:1053
{Keys:[miek.nl.:1053] Tokens:map[log:[{File: Line:9 Text:log} {File: Line:9 Text:stdout}] prometheus:[{File: Line:10 Text:prometheus}] file:[{File: Line:2 Text:file} {File: Line:2 Text:miek.nl.signed} {File: Line:2 Text:{} {File: Line:3 Text:transfer} {File: Line:3 Text:to} {File: Line:3 Text:*} {File: Line:5 Text:}}] chaos:[{File: Line:6 Text:chaos} {File: Line:6 Text:CoreDNS} {File: Line:6 Text:Miek Gieben} {File: Line:6 Text:miek@miek.nl}] rewrite:[{File: Line:7 Text:rewrite} {File: Line:7 Text:ANY} {File: Line:7 Text:HINFO}] errors:[{File: Line:8 Text:errors} {File: Line:8 Text:stdout}]]}
setup prometheus miek.nl.:1053
panic: WARNING saveConfig called with: miek.nl.

goroutine 1 [running]:
panic(0x16b9060, 0xc4203a3db0)
    /home/miek/upstream/go/src/runtime/panic.go:500 +0x1a1
github.com/miekg/coredns/core/dnsserver.GetConfig(0xc42008e5a0, 0xc4202405f0)
    /home/miek/g/src/github.com/miekg/coredns/core/dnsserver/config.go:36 +0x11d
github.com/miekg/coredns/middleware/errors.setup(0xc42008e5a0, 0x3, 0x191718e)
    /home/miek/g/src/github.com/miekg/coredns/middleware/errors/setup.go:68 +0x1f7
github.com/mholt/caddy.executeDirectives(0xc420200f70, 0x7ffc10228d2c, 0x8, 0x22b6ba0, 0
```

Now if I comment out `prometheus` stuff works:

```
len Keys 1
[miek.nl:1053]
Zone miek.nl. Port 1053
saveConfig miek.nl.:1053
{Keys:[miek.nl.:1053] Tokens:map[file:[{File: Line:2 Text:file} {File: Line:2 Text:miek.nl.signed} {File: Line:2 Text:{} {File: Line:3 Text:transfer} {File: Line:3 Text:to} {File: Line:3 Text:*} {File: Line:5 Text:}}] chaos:[{File: Line:6 Text:chaos} {File: Line:6 Text:CoreDNS} {File: Line:6 Text:Miek Gieben} {File: Line:6 Text:miek@miek.nl}] rewrite:[{File: Line:7 Text:rewrite} {File: Line:7 Text:ANY} {File: Line:7 Text:HINFO}] errors:[{File: Line:8 Text:errors} {File: Line:8 Text:stdout}] log:[{File: Line:9 Text:log} {File: Line:9 Text:stdout}]]}
file called
len configs 1
hello conf
:1053
miek.nl.
middlewares 5
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192"
```

For some reason when prometheus calls `GetConfig()` the config hasn't been fully setup? Or something? The `setup` code for prometheus looks not different than the rest.

Bit stumped here.

**Comment by miekg** [comment]
@mholt do you have any smart insights here?

**Comment by miekg** [comment]
All other middlewares look OK, only when I enable `prometheus`, it or _other_ `setup` function fail.

**Comment by mholt** [comment]
I'm a little lost here. Are you saying that it is not loading a config [here](https://github.com/miekg/coredns/blob/29ee43125330fd015593418bbebdfaabfecdd096/core/dnsserver/config.go#L30) when it should be?

The HTTP server makes its configs in the InspectServerBlocks() function. Make sure [this works as you expect](https://github.com/miekg/coredns/blob/29ee43125330fd015593418bbebdfaabfecdd096/core/dnsserver/register.go#L78) if you follow that same pattern.

**Comment by miekg** [comment]
Thanks for looking!

Indeed a new key is added somewhere (`miek.nl.`, without a port curiously). Note that `saveConfig` is also called in `GetConfig` - where you added the comment this is only needed for tests (https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go#L176)

For _some_ reason if prometheus is enabled _another_ host config is added:

```
{Keys:[miek.nl.:1053] Tokens:map[log:[{File: Line:9 Text:log} {File: Line:9 Text:stdout}] prometheus:[{File: Line:10 Text:prometheus}] file:[{File: Line:2 Text:file} {File: Line:2 Text:miek.nl.signed} {File: Line:2 Text:{} {File: Line:3 Text:transfer} {File: Line:3 Text:to} {File: Line:3 Text:*} {File: Line:5 Text:}}] chaos:[{File: Line:6 Text:chaos} {File: Line:6 Text:CoreDNS} {File: Line:6 Text:Miek Gieben} {File: Line:6 Text:miek@miek.nl}] rewrite:[{File: Line:7 Text:rewrite} {File: Line:7 Text:ANY} {File: Line:7 Text:HINFO}] errors:[{File: Line:8 Text:errors} {File: Line:8 Text:stdout}]]}
setup prometheus miek.nl.:1053
panic: WARNING saveConfig called with: miek.nl.
```

Those last two lines, the `.Key` in the controller is `miek.nl.:1053` but then this `miek.nl.` pops up, out of nowhere.

**Comment by mholt** [comment]
Strange, are you sure the key is only ever being read and not changed to add (or remove) the port? (Sorry I have a lot of things going on right now or I would dive in myself...)

**Comment by miekg** [comment]
at this point I'm not sure of anything.

I'll poke some more. 

Thanks!

**Comment by miekg** [comment]
I _think_ this has to do with my use of `ServerBlockKeys`, https://github.com/miekg/coredns/blob/29ee43125330fd015593418bbebdfaabfecdd096/middleware/dnssec/setup.go#L39
Because those strings get added. I need to double check of course and see how I did do this in the current CoreDNS.

**Comment by miekg** [comment]
@mholt it was due to assigning the `ServerBlockKeys` to an internal slice and then working on that...
changed to using `copy`.

Makes total sense that it was something stupid like that.
