### ISSUE TITLE
plugin/forward: translate io.EOF to something more meaningful

### ISSUE THREAD

**Issue by ynikanchyk** [coredns/coredns#2230]
The primary issue: CoreDNS log doesn't provide enough information about the reason of DNS troubles. More specific, with `forward` plugin configured for TLS upstream, sometimes CoreDNS reports in the log errors like this:

2018/09/07 00:11:28 [ERROR] 0 a1441.g4.akamai.net. A: EOF

It could be nice to have more specific information about such a error e.g. exact IP address of the upstream used.

**Comment by miekg** [comment]
please send to PR for this, think this is a valid request.

**Comment by miekg** [comment]
stalled.
