### ISSUE TITLE
1.2.5 release tracking bug

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2232]
Tracking bug for 1.2.5 release

**Comment by miekg** [comment]
wip notes: https://github.com/coredns/coredns/wiki/CoreDNS-1.2.5-Release-Notes

**Comment by miekg** [comment]
I'll send the PR and do the release tomorrow morning UTC (probably)  and then fix up the release notes during the day. Some good fixes and a few features; would be good to do a release.

As we further automate releases I can't see no reason to up the cadence (if there is actually something to release of course)

**Comment by miekg** [comment]
released and notes updated.

/cc @fturib

**Comment by fturib** [comment]
Great!

We are following with validations on Kubernetes side in order to bump the version of CoreDNS to 1.2.5
Thanks!
