### ISSUE TITLE
Recurrent CoreDNS Maintainers public meeting

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#2236]
Hi CoreDNS Maintainers,

CNCF is offering to organize our periodic meeting.
I mean : create a zoom link, add to the CNCF Calendar, open a playlist on youtube for publication of the recording ...

It requires we agreed on a time and period for that meeting.

To mimic what exist already for CNCF Meetings of Kubernetes's SIG meetings, I would propose:

* Periodic: Every other week
* Duration: 1h
* Time: early in Pacific Time so it is not too late in UTC time ... but I am not sure if we have people that would like to attend from other zones.

**The initial proposition is**:

* Every other Tuesdays
* from 17h to 18h UTC - warning it will NOT follow the change of daylight per countries ..

Thanks to comment on this issue with either your agreement, or other propositions, or your constraints. 
Please inform if you are not in a timezone between UTC and Pacific.

I will keep this issue open until Tuesday 10/30th EOD and take into account as much as possible the replies for defining the meeting time.
Francois

**Comment by chrisohaver** [comment]
SGTM

**Comment by miekg** [comment]
I think if we want/need meeting we should coordinated on the maintainers list and/or open an issue to schedule one.
