### ISSUE TITLE
Add versioning info

### ISSUE THREAD

**Issue by mrichmon** [coredns/coredns#224]
CoreDNS will need versioning information at some point. Areas to consider:
- Use semantic versioning.
- Provide version in startup log.
- Report version and exit when flagged with command-line argument such as `-version`.
- Consider including the github commit in the long-form version string. e.g `v1.1.0 (9ac3cab1b7b1b1e78f86ce3c6a80fbee312162e6)`
- Things to document:
  - How to manage archiving of source for each versioned release? (tagging master, creating a branch for each version, etc)
  - How to record/archive versions of dependencies for each versioned release?
  - What conditions trigger incrementing a version field?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] Add versioning info..." ]

> CoreDNS will need versioning information at some point. Areas to consider:
> - Use semantic versioning.

Not a fan...I rather follow the systemd versioning: just increment a number for
a new "release". Consider my "releasing" for Go DNS: master-branch is production
ready - not releases.

> - Provide version in startup log.

ack.

> - Report version and exit when flagged with command-line argument such as `-version`.

work-in-progress

> - Consider including the github commit in the long-form version string. e.g `v1.1.0 (9ac3cab1b7b1b1e78f86ce3c6a80fbee312162e6)`

Caddy's build.bash

> - Things to document:

s/document/automate

> - How to manage archiving of source for each versioned release? (tagging master, creating a branch for each version, etc)

Just tag master

> - How to record/archive versions of dependencies for each versioned release?

Why? And why makes this explicit?

> - What conditions trigger incrementing a version field?

Don't have this problem with the systemd's versioning scheme - one of the reason
I like it.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
Adding other things to think about, `plugin_generate.go` which add CoreDNS to caddy, should disable the http plugin. This is just removing that particular import line from `run.go` - not hard, but it is just not happening at this point.

**Comment by mrichmon** [comment]
> Not a fan...I rather follow the systemd versioning: just increment a number for
> a new "release". Consider my "releasing" for Go DNS: master-branch is production
> ready - not releases.

The earlier comment from you on the CNCF document seemed to be in favor of semantic versioning. But any scheme works.

> > ```
> > - What conditions trigger incrementing a version field?
> > ```
> > 
> > Don't have this problem with the systemd's versioning scheme - one of the reason
> > I like it.

There is still the question of what triggers the increment of the version field. Are you assuming increment on every PR?

> > - How to record/archive versions of dependencies for each versioned release?
> >   Why? And why makes this explicit?

This is possibly me over-thinking things.

The concern is that with dynamic compilation of the code via the Caddy website, how do I get the same behavior from the binary if libraries have been updated. That is, I download v300 today and then download v300 in 3 months time. I may see different behavior if libraries have been updated/fixed/broken.

I'm going to switch back to debugging some tests. At least those ghosts really exist. ;)

**Comment by miekg** [comment]
On 22 Aug 2016 9:54 pm, "Michael Richmond" notifications@github.com wrote:

> > Not a fan...I rather follow the systemd versioning: just increment a
> > number for
> > a new "release". Consider my "releasing" for Go DNS: master-branch is
> > production
> > ready - not releases.
> 
> The earlier comment from you on the CNCF document seemed to be in favor
> of semantic versioning. But any scheme works.
> 
> > > - What conditions trigger incrementing a version field?
> > > 
> > > Don't have this problem with the systemd's versioning scheme - one of
> > > the reason
> > > I like it.
> 
> There is still the question of what triggers the increment of the version
> field. Are you assuming increment on every PR?

No. Just when we feel like it, which is similar to semver anyway.

> > > How to record/archive versions of dependencies for each versioned
> > > release? Why? And why makes this explicit?
> 
> This is possibly me over-thinking things.
> 
> The concern is that with dynamic compilation of the code via the Caddy
> website, how do I get the same behavior from the binary if libraries have
> been updated. That is, I download v300 today and then download v300 in 3
> months time. I may see different behavior if libraries have been
> updated/fixed/broken.

The answer is vendoring, but I dislike that as well. We should prolly just
follow caddy here.

> I'm going to switch back to debugging some tests. At least those ghosts
> really exist. ;)

😀 Good

**Comment by miekg** [comment]
See #232. I'm ready to do a CoreDNS-001 release and create some tooling around it.

**Comment by miekg** [comment]
We should also echo where we are listening, caddy outputs:
`http://:2015`
I propose we do something like:
`domain://example.org:53`

**Comment by miekg** [comment]
Closing for now as I've just pushed out CoreDNS-001 and documented the process in Makefile.release.
Think the current stuff is "good enough".
