### ISSUE TITLE
CoreDNS 1.2.5 returns large responses compared to upstream

### ISSUE THREAD

**Issue by usalim** [coredns/coredns#2242]
Looks like CoreDNS is [still not](https://github.com/coredns/coredns/issues/2224) compressing responses in all cases.

DNS query for *A* record of domain `app.datadoghq.com.` leads to a response of size 682. In comparison the upstream DNS server (`1.1.1.1` in repro) is retuning a response of size 238.

Behavior is consistent for both `proxy` and `forward`. 

Here is a minimal repro against CoreDNS 1.2.5.
Last line of dig output shows *MSG SIZE*.

```
$ cat /tmp/Corefile
.    {
 forward . 1.1.1.1
}
$ docker run -d --name cdns-1.2.5 -p 5354:53/tcp -p 5354:53/udp -v /tmp/Corefile:/Corefile --entrypoint "/coredns"  coredns/coredns:1.2.5 -conf /Corefile
cdns-1.2.5
9c7086b992390b26f87c5f2d55467a5f4e10bc6cf72c947aa7a5f390f06d9127
$ dig @127.0.0.1 -p 5354 A  app.datadoghq.com.

; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 5354 A app.datadoghq.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64555
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;app.datadoghq.com.		IN	A

;; ANSWER SECTION:
app.datadoghq.com.	5	IN	CNAME	alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com.
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 54.208.252.45
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 107.23.209.202
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 34.197.177.186
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 34.207.51.240
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 52.70.197.48
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 54.165.203.141
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 54.172.103.190
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 54.174.194.200

;; Query time: 8 msec
;; SERVER: 127.0.0.1#5354(127.0.0.1)
;; WHEN: Fri Oct 26 16:48:43 PDT 2018
;; MSG SIZE  rcvd: 682

$ dig @1.1.1.1 A  app.datadoghq.com.

; <<>> DiG 9.10.6 <<>> @1.1.1.1 A app.datadoghq.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28842
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;app.datadoghq.com.		IN	A

;; ANSWER SECTION:
app.datadoghq.com.	5	IN	CNAME	alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com.
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 52.1.132.44
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 52.2.38.207
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 52.20.19.187
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 34.199.158.117
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 34.202.99.66
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 34.230.143.239
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 34.231.27.185
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 5 IN A 34.234.25.12

;; Query time: 50 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri Oct 26 16:48:53 PDT 2018
;; MSG SIZE  rcvd: 238
```

**Comment by usalim** [comment]
Is this considered a bug?

**Comment by fturib** [comment]
By default, the size of UDP buffer is 4096, so the reply you get from CroeDNS, although is not compressed still fit in the buffer.

If you setup a UDP buffer with a smaller size, let say 512, then you get the a compression as expected (see below).


```
ftur-MBP13:~ ftur$ dig @127.0.0.1 -p 5354 +bufsize=512 A  app.datadoghq.com.

; <<>> DiG 9.12.1 <<>> @127.0.0.1 -p 5354 +bufsize=512 A app.datadoghq.com.
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
ftur-MBP13:~ ftur$ dig @127.0.0.1 -p 5354 +bufsize=512 A  app.datadoghq.com.

; <<>> DiG 9.12.1 <<>> @127.0.0.1 -p 5354 +bufsize=512 A app.datadoghq.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13062
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;app.datadoghq.com.		IN	A

;; ANSWER SECTION:
app.datadoghq.com.	9	IN	CNAME	alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com.
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 14 IN A 52.0.54.2
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 14 IN A 52.7.15.179
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 14 IN A 52.54.251.90
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 14 IN A 52.72.174.105
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 14 IN A 52.87.65.174
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 14 IN A 52.206.71.16
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 14 IN A 54.173.212.143
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 14 IN A 54.209.137.245

;; Query time: 11 msec
;; SERVER: 127.0.0.1#5354(127.0.0.1)
;; WHEN: Mon Nov 05 18:00:17 EST 2018
;; MSG SIZE  rcvd: 238
```

(adding to the comment)
on a second try with the same query, I used std log for CoreDNS and get this information:

`2018-11-06T09:59:00.844-05:00 [INFO] 127.0.0.1:52745 - 21346 "A IN app.datadoghq.com. udp 59 false 512" NOERROR qr,rd,ra 683 0.009388819s`

=> the bufsize provided by the client is 512 (as expected)

**Comment by fturib** [comment]
The question is : should the reply compression always followed the exact same compression behavior as the upstream server ?

**Comment by fturib** [comment]
I was wondering why the default size of msg is not 512 ....
And I made the DNS query with a NO EDNS option .... then the size of buffer is 512 ... and msg compressed

```
ftur-MBP13:~ ftur$ dig @127.0.0.1 -p 5354 +noedns A  app.datadoghq.com.

; <<>> DiG 9.12.1 <<>> @127.0.0.1 -p 5354 +noedns A app.datadoghq.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33671
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;app.datadoghq.com.		IN	A

;; ANSWER SECTION:
app.datadoghq.com.	41	IN	CNAME	alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com.
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 8 IN A 54.82.148.176
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 8 IN A 54.84.176.82
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 8 IN A 54.86.228.209
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 8 IN A 54.236.156.149
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 8 IN A 34.192.143.1
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 8 IN A 34.198.82.36
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 8 IN A 34.226.167.94
alb-web-shard0-1841758435.us-east-1.elb.amazonaws.com. 8 IN A 52.200.124.77

;; Query time: 3776 msec
;; SERVER: 127.0.0.1#5354(127.0.0.1)
;; WHEN: Mon Nov 05 18:37:19 EST 2018
;; MSG SIZE  rcvd: 227
```


(adding to the comment)
on a second try with the same query, I used std log for CoreDNS and get this information:

`2018-11-06T09:59:40.441-05:00 [INFO] 127.0.0.1:60554 - 9819 "A IN app.datadoghq.com. udp 35 false 512" NOERROR qr,rd,ra 671 0.00960673s`

=> the bufsize provided by the client is 512 (because no EDNS option)

**Comment by fturib** [comment]
If i re-execute the initial query, without specific option provided to `dig`

then there is a EDNS0 extra record sent that contain the max bufsize. And it is set to 4096


```
ftur-MBP13:~ ftur$ dig @127.0.0.1 -p 5354 +noedns A  app.datadoghq.com.

; <<>> DiG 9.12.1 <<>> @127.0.0.1 -p 5354 A app.datadoghq.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13666
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;app.datadoghq.com.		IN	A

;; ANSWER SECTION:
app.datadoghq.com.	49	IN	CNAME	alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com.
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 52.22.28.111
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 54.84.203.116
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 54.85.221.18
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 54.209.52.85
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 34.197.189.101
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 34.202.99.66
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 34.230.143.239
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 34.231.27.185

;; Query time: 11 msec
;; SERVER: 127.0.0.1#5354(127.0.0.1)
;; WHEN: Tue Nov 06 10:08:13 EST 2018
;; MSG SIZE  rcvd: 682
```

Log from CoreDNS : buffer size received is 4096

`2018-11-06T10:08:13.788-05:00 [INFO] 127.0.0.1:64559 - 13666 "A IN app.datadoghq.com. udp 59 false 4096" NOERROR qr,rd,ra 683 0.011643615s
`

**Comment by fturib** [comment]
IMO, it is working as expected : compression happen only if the size of the msg to send is larger than the size of the buffer the client can receive.

@usalim : what is your take ?

**Comment by usalim** [comment]
Thanks for explaining the behavior.
I am somewhat surprised by the fact that client sends it's buffer size as part of the call.

It's confusing that behavior (size of response) compared to upstream can be different -- although the difference is limited to encoding. This is not an issue in our environment so I can't say it's a bug. It is unexpected though.

I presume the motive behind optional compression is saving compute resources. Is there an option to
1. make a trade off on cpu vs. network and always compress?
2. follow upstream's lead on whether to compress or not?

Thanks for your detailed response.

**Comment by fturib** [comment]
For what I understand there is no option yet to trigger a compression.
It is automatic iff the msg does not fit the buffer (and truncated if the compressed msg does not fit in the buffer).

I will let @miekg give his opinion on the relevance to add such option.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS 1.2.5..." ]
>For what I understand there is no option yet to trigger a compression.
>It is automatic iff the msg does not fit the buffer (and truncated if the compressed msg does not fit in the buffer).
>
>I will let @miekg give his opinion on the relevance to add such option.

you can't in DNS. Of course *we* can invent such an option and implement it in 
CoreDNS, but it shouldn't matter to clients.

/close
/label: dns

**Comment by w9n** [comment]
Hi,

AFAIU the maximum DNS response size over udp is 512 bytes according to [rfc1035](https://tools.ietf.org/html/rfc1035#section-2.3.4).

If a response is bigger it actually breaks netdns of all go binaries compiled with go <1.11...

golang/go#28419

**Comment by chrisohaver** [comment]
@w9n, CoreDNS will compress messages that exceed 512 bytes, unless the client allows a larger maximum size by sending the corresponding edns0 option in the request.

**Comment by w9n** [comment]
@chrisohaver thank you for the quick reply.

But there is no edns0 option specified in the first post

```
$ dig @127.0.0.1 -p 5354 A  app.datadoghq.com.
```
...
```
;; MSG SIZE  rcvd: 682
```
I am facing the same behavior with 1.2.4 on a k8s cluster

**Comment by chrisohaver** [comment]
@w9n, `dig` in particular sends a buffer size > 512 by default. I think the exact number depends on the dig version or perhaps the environment... on my system it defaults to 4096 - I think this is most common. In the OP's description it appears to be 1452. `; EDNS: version: 0, flags:; udp: 1452`

`$ dig @127.0.0.1 -p 5354 A  app.datadoghq.com.` // sends dig's default bufsize
`$ dig @127.0.0.1 -p 5354 A  app.datadoghq.com. +noedns` // sends no bufsize, so coredns uses 512
`$ dig @127.0.0.1 -p 5354 A  app.datadoghq.com. +bufsize=1000` // uses bufsize of 1000

**Comment by w9n** [comment]
hmm okay but why does @fturib comment has
```
; EDNS: version: 0, flags:; udp: 1452
```
and logs 4096 (miss copy in the command?)

> If i re-execute the initial query, without specific option provided to `dig`
> 
> then there is a EDNS0 extra record sent that contain the max bufsize. And it is set to 4096
> 
> ```
> ftur-MBP13:~ ftur$ dig @127.0.0.1 -p 5354 +noedns A  app.datadoghq.com.
> 
> ; <<>> DiG 9.12.1 <<>> @127.0.0.1 -p 5354 A app.datadoghq.com.
> ; (1 server found)
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13666
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1452
> ;; QUESTION SECTION:
> ;app.datadoghq.com.		IN	A
> 
> ;; ANSWER SECTION:
> app.datadoghq.com.	49	IN	CNAME	alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com.
> alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 52.22.28.111
> alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 54.84.203.116
> alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 54.85.221.18
> alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 54.209.52.85
> alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 34.197.189.101
> alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 34.202.99.66
> alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 34.230.143.239
> alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 49 IN A 34.231.27.185
> 
> ;; Query time: 11 msec
> ;; SERVER: 127.0.0.1#5354(127.0.0.1)
> ;; WHEN: Tue Nov 06 10:08:13 EST 2018
> ;; MSG SIZE  rcvd: 682
> ```
> Log from CoreDNS : buffer size received is 4096
> 
> `2018-11-06T10:08:13.788-05:00 [INFO] 127.0.0.1:64559 - 13666 "A IN app.datadoghq.com. udp 59 false 4096" NOERROR qr,rd,ra 683 0.011643615s `

In my cluster I have this, which should be definitely broken.. Ill try to make the setup reproducible:

```
root@bla-54755857fb-mdgzb:/go# dig +noedns app.datadoghq.com.

; <<>> DiG 9.10.3-P4-Debian <<>> +noedns app.datadoghq.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10136
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 4, ADDITIONAL: 7

;; QUESTION SECTION:
;app.datadoghq.com.		IN	A

;; ANSWER SECTION:
app.datadoghq.com.	23	IN	CNAME	alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com.
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 23 IN A 34.232.99.50
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 23 IN A 52.45.241.11
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 23 IN A 52.1.78.4
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 23 IN A 52.6.42.28
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 23 IN A 34.232.89.208
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 23 IN A 52.204.64.237
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 23 IN A 34.225.159.203
alb-web-shard1-1950469440.us-east-1.elb.amazonaws.com. 23 IN A 34.196.139.131

;; AUTHORITY SECTION:
us-east-1.elb.amazonaws.com. 23	IN	NS	ns-235.awsdns-29.com.
us-east-1.elb.amazonaws.com. 23	IN	NS	ns-934.awsdns-52.net.
us-east-1.elb.amazonaws.com. 23	IN	NS	ns-1793.awsdns-32.co.uk.
us-east-1.elb.amazonaws.com. 23	IN	NS	ns-1119.awsdns-11.org.

;; ADDITIONAL SECTION:
ns-934.awsdns-52.net.	23	IN	A	205.251.195.166
ns-934.awsdns-52.net.	23	IN	AAAA	2600:9000:5303:a600::1
ns-1119.awsdns-11.org.	23	IN	A	205.251.196.95
ns-1793.awsdns-32.co.uk. 23	IN	A	205.251.199.1
ns-1119.awsdns-11.org.	23	IN	AAAA	2600:9000:5304:5f00::1
ns-235.awsdns-29.com.	23	IN	A	205.251.192.235
ns-1793.awsdns-32.co.uk. 23	IN	AAAA	2600:9000:5307:100::1

;; Query time: 20 msec
;; SERVER: 172.20.0.2#53(172.20.0.2)
;; WHEN: Thu Jan 10 21:25:00 UTC 2019
;; MSG SIZE  rcvd: 1215
```
log:
``
172.31.0.0:35469 - [10/Jan/2019:21:25:00 +0000] 10136 "A IN app.datadoghq.com. udp 35 false 512" NOERROR qr,rd,ra 1215 0.019408932s
``

**Comment by chrisohaver** [comment]
>  (miss copy in the command?)

Yes, more or less ...  if you look at the edit history in that comment, the response is from a second query which was later deleted.  The second query did not specify the `+noedns` option, hence the presence of the edns section in the output.  Very confusing result.
