### ISSUE TITLE
plugin/Log - accept Metadata in the logging string

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#2250]
Allow log format string accept metadata information

Supposing that those metadata exist, provided by other plugin
- mac/address
- request/client_id
- ..
- <plugin>/<name>

Allow the Log format string to accept any of those metadata:
```
.:53 {
   log . "{name} {type} MAC:{mac/address} from {request/client_id}"
   ...
}
```
would be a valid format.

**Comment by miekg** [comment]
implemented in #2251
