### ISSUE TITLE
Convert CIDR records into several ".in-addr.arpa" entries if number of leading bits in mask is not multiple of 8

### ISSUE THREAD

**Issue by ynikanchyk** [coredns/coredns#2252]
The current implementation of `normalizeZone` in `address.go`/`normalize.go` modules provides limited support for CIDR records. More specific, for zone "172.16.0.0/12" it provides "172.in-addr.arpa" what seems wrong. It could be nice to have several entries "16.172.in-addr.arpa 17.172.in-addr.arpa <...> 31.172.in-addr.arpa" as result.
We had already the mention of RFC2317 in #838.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Convert CIDR reco..." ]
>The current implementation of `normalizeZone` in `address.go`/`normalize.go` modules provides limited support for CIDR records. More specific, for zone "172.16.0.0/12" it provides "172.in-addr.arpa" what seems wrong. It could be nice to have several entries "16.172.in-addr.arpa 17.172.in-addr.arpa <...> 31.172.in-addr.arpa" as result.
>We had already the mention of RFC2317 in #838.

if need that level, you'll need to add those zones yourself. 
CoreDNS does check if the reverse falls in the correct interval before handling 
the request.

**Comment by ynikanchyk** [comment]
> CoreDNS does check if the reverse falls in the correct interval before handling the request.

Not sure if I understood you. If I need two reverse zones to be processed in same manner with current implementation, I won't be able to do this: zones "10.6.84.0/26 10.6.84.128/26" would provide the error "cannot serve dns://84.6.10.in-addr.arpa.:53 - it is already defined".

**Comment by johnbelamaric** [comment]
@ynikanchyk you can spell out the whole zone instead of using the CIDR format, which is just shorthand.
