### ISSUE TITLE
Logging reports incorrect message size

### ISSUE THREAD

**Issue by stuartnelson3** [coredns/coredns#2258]
Discovered while reproducing https://github.com/coredns/coredns/issues/2257

```
# ... dig output ...
;; Query time: 1 msec
;; SERVER: ::1#1053(::1)
;; WHEN: Thu Nov 01 14:15:59 CET 2018
;; MSG SIZE  rcvd: 4119
```

```
[::1]:51981 - [01/Nov/2018:14:15:59 +0100] 263 "SRV IN http.web.stnn.rocket.srv.db.s-cloud.net. udp 81 false 4096" NOERROR qr,tc,rd,ra 6943 0.001206116s
```

It appears that dig reports the msg size as 4119, but the logging plugin says it is 6943.

I haven't checked, but this response bytes reported in the prometheus plugin could also be wrong.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Logging reports i..." ]
>Discovered while reproducing https://github.com/coredns/coredns/issues/2257
>
>```
># ... dig output ...
>;; Query time: 1 msec
>;; SERVER: ::1#1053(::1)
>;; WHEN: Thu Nov 01 14:15:59 CET 2018
>;; MSG SIZE  rcvd: 4119
>```
>
>```
>[::1]:51981 - [01/Nov/2018:14:15:59 +0100] 263 "SRV IN http.web.stnn.rocket.srv.db.s-cloud.net. udp 81 false 4096" NOERROR qr,tc,rd,ra 6943 0.001206116s
>```
>
>It appears that dig reports the msg size as 4119, but the logging plugin says it is 6943.
>
>I haven't checked, but this response bytes reported in the prometheus plugin could also be wrong.

I think this did work, but recently the scrubbing was moved to the server and 
now the log plugin is too early. So this is the raw size. I think the only 
sensible thing here is to mention this in the docs.


/plugin: log
