### ISSUE TITLE
proxy not working when pointing at /etc/resolv.conf

### ISSUE THREAD

**Issue by jforman** [coredns/coredns#2264]
Stat: Kubernetes 1.11.4, coredns 1.2.4 and 1.2.5 tested
Running on Ubuntu 18.10 cloud minimal images as VMs via libvirt/kvm.

I encountered the loop problem with my kubernetes cluster:
2018/11/03 00:27:22 [FATAL] plugin/loop: Forwarding loop detected in "." zone. Exiting. See https://coredns.io/plugins/loop#troubleshooting. Probe query: "HINFO 6140459771340927376.6741848550363288421.".

Using the method of redefining the resolv-conf parameter on the kubelet, I went that direction:
root     3669  1.4  4.3 750800 88968 ?        Ssl  Oct31  51:40 /opt/kubernetes/bin/kubelet .... --resolv-conf /run/systemd/resolve/resolv.conf --v=2

ubuntu@deva-worker1:~$ ls -al /run/systemd/resolve/resolv.conf 
-rw-r--r-- 1 systemd-resolve systemd-resolve 586 Nov  2 00:46 /run/systemd/resolve/resolv.conf

But I still seem to be tripping the loop detection when firing up CoreDNS.

$ kubectl logs coredns-68cb5545b6-64szh -n kube-system
.:53
2018/11/03 00:28:59 [INFO] CoreDNS-1.2.4
2018/11/03 00:28:59 [INFO] linux/amd64, go1.11.1, 7343c70
CoreDNS-1.2.4
linux/amd64, go1.11.1, 7343c70
2018/11/03 00:28:59 [INFO] plugin/reload: Running configuration MD5 = 2e2180a5eeb3ebf92a5100ab081a6381
2018/11/03 00:29:05 [FATAL] plugin/loop: Forwarding loop detected in "." zone. Exiting. See https://coredns.io/plugins/loop#troubleshooting. Probe query: "HINFO 3351455344959186562.3480717695556959356.".

Am I missing something here? Did I miss more configuration changes needed to handle systemd-resolv playing games with resolv.conf?

**Comment by chrisohaver** [comment]
That's all that should be needed.  Did you add the flag to kubelet on every node?

There was an issue found, and recently fixed (#2255), that causes loop to falsely detect a forwarding loop if an upstream DNS server is non-responsive.

**Comment by jforman** [comment]
@chrisohaver That looks to have fixed it. Adding --resolv-conf on each kubelet and keeping 'proxy . /etc/resolv.conf' in my Corefile was the right combination. Thanks!
