### ISSUE TITLE
add blacklists plugin

### ISSUE THREAD

**Issue by danderson** [coredns/coredns#2267]
I'm using CoreDNS as my home DNS cache/forwarder/authoritative server. I also have a domain blacklist, which is currently implemented as a hosts file that resolves the blacklisted domains to 0.0.0.0.

This is okay, but not ideal: CoreDNS responds to blacklisted requests with NOERROR and an A record, so most clients will try to dial 0.0.0.0 and then fail.

It would be better to return NXDOMAIN for blacklist hits, but AFAICT there's no clean way of doing this:

 - You can't encode "please respond NXDOMAIN" in /etc/hosts style files.
 - The bind-style zonefiles don't help me, because they're siloed per zone (though I could just have a zone for . I guess), and only let me specify whitelists of authoritative matches.
 - To us the template plugin I must construct one giant regex (in my case ~1.5MiB) and stick it in the main coredns config.
 - I can't implement "lookaside" with the forward plugin (e.g. "NXDOMAIN if localhost:1234 says NXDOMAIN, else fallthrough"), so in practice I would just need to run some other DNS server like Pihole, and then what's the point of using CoreDNS.

What I would like is a `blacklist` plugin that takes a bunch of blacklist files (e.g. format TBD - e.g. one entry per line, exact match only?) and an RCODE to return (default to REFUSED), and does fast matching + periodic file reloading similar to the hosts plugin. That way I can update the blacklist externally and CoreDNS just updates automagically.

First, WDYT? Did I miss an obvious way to do what I want? Is it a bad idea to do the thing I want?

Second, does it sound reasonable for a core plugin? I'm not super interested in setting up a custom build of CoreDNS for myself, so the implication is putting it in core (with proper tests, conformance, etc.).

I'm willing to implement this plugin if it sounds like a reasonable idea. I'm also happy to take suggestions for other ways to achieve this (e.g. add feature to existing plugin or something).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Better support fo..." ]
>I'm using CoreDNS as my home DNS cache/forwarder/authoritative server. I also have a domain blacklist, which is currently implemented as a hosts file that resolves the blacklisted domains to 0.0.0.0.
>
>This is okay, but not ideal: CoreDNS responds to blacklisted requests with NOERROR and an A record, so most clients will try to dial 0.0.0.0 and then fail.
>
>It would be better to return NXDOMAIN for blacklist hits, but AFAICT there's no clean way of doing this:
>
> - You can't encode "please respond NXDOMAIN" in /etc/hosts style files.
> - The bind-style zonefiles don't help me, because they're siloed per zone (though I could just have a zone for . I guess), and only let me specify whitelists of authoritative matches.
> - To us the template plugin I must construct one giant regex (in my case ~1.5MiB) and stick it in the main coredns config.
> - I can't implement "lookaside" with the forward plugin (e.g. "NXDOMAIN if localhost:1234 says NXDOMAIN, else fallthrough"), so in practice I would just need to run some other DNS server like Pihole, and then what's the point of using CoreDNS.
>
>What I would like is a `blacklist` plugin that takes a bunch of blacklist files (e.g. format TBD - e.g. one entry per line, exact match only?) and an RCODE to return (default to REFUSED), and does fast matching + periodic file reloading similar to the hosts plugin. That way I can update the blacklist externally and CoreDNS just updates automagically.
>
>First, WDYT? Did I miss an obvious way to do what I want? Is it a bad idea to do the thing I want?

https://github.com/miekg/block

although it doesn't do all the things PiHole does, i.e. configure how to respond 
when things are blocked.

>Second, does it sound reasonable for a core plugin? I'm not super interested in setting up a custom build of CoreDNS for myself, so the implication is putting it in core (with proper tests, conformance, etc.).
>
>I'm willing to implement this plugin if it sounds like a reasonable idea. I'm also happy to take suggestions for other ways to achieve this (e.g. add feature to existing plugin or something).

I think this is valid use-case, esp if you're willing to be put in the owners 
file, etc. :)

/Miek

--
Miek Gieben

**Comment by danderson** [comment]
> [ Quoting <notifications@github.com> in "[coredns/coredns] Better support fo..." ]
> https://github.com/miekg/block although it doesn't do all the things PiHole does, i.e. configure how to 
respond when things are blocked.

\o/ Awesome, that saves me a bunch of work to figure out how the internals of CoreDNS fit together!

> I think this is valid use-case, esp if you're willing to be put in the owners file, etc. :) /Miek

Yup, I meant "if this can go in core, I'm happy to write/own/maintain it."

I guess I'll clone your implementation and start hacking on the missing bits. Thanks!

**Comment by miekg** [comment]
Cool :-)
Note the big missing piece here is how to download block lists if you don't
have a working resolver.

**Comment by danderson** [comment]
Ideas for that:

- If the blocklist plugin fails open, we can just use the system resolver unconditionally, even if it's configured to use CoreDNS. Initial queries will be a no-op through the blocklist plugin, until it's downloaded blocklists. Then the blocking activates.
  - There should be an option for local caching of blocklists (in e.g. /var/cache/coredns), so the fail-open behavior only happens during bootstrapping when you download for the first time.
  - If there's a local cache, we can also have an option for "fail closed if there's no blocklist", and just say "you need to solve the bootstrapping problem yourself"
- Is it possible in the CoreDNS plugin architecture to "inject" queries into the downstream plugins? e.g. if blocklist is before forward/unbound/etc. in the plugin order, the blocklist plugin could just make up the queries it needs and send them to downstream plugins for resolution.
  - This only works if you've configured CoreDNS as a recursive resolver/forwarder of some kind, but otoh it doesn't make sense to use a blocklist with an authoritative resolver...
- Just don't support downloading/refreshing at all. Make it work exactly like the host/file/auto plugins, loads a blocklist from local disk and it's your problem to update them.

WDYT? I'm leaning towards the first option, it seems like the simplest and only has minor downsides (failopen during bootstrap).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Better suppor..." ]
>Ideas for that:
>
>- If the blocklist plugin fails open, we can just use the system resolver unconditionally, even if it's configured to use CoreDNS. Initial queries will be a no-op through the blocklist plugin, until it's downloaded blocklists. Then the blocking activates.
>  - There should be an option for local caching of blocklists (in e.g. /var/cache/coredns), so the fail-open behavior only happens during bootstrapping when you download for the first time.
>  - If there's a local cache, we can also have an option for "fail closed if there's no blocklist", and just say "you need to solve the bootstrapping problem yourself"
>- Is it possible in the CoreDNS plugin architecture to "inject" queries into the downstream plugins? e.g. if blocklist is before forward/unbound/etc. in the plugin order, the blocklist plugin could just make up the queries it needs and send them to downstream plugins for resolution.
>  - This only works if you've configured CoreDNS as a recursive resolver/forwarder of some kind, but otoh it doesn't make sense to use a blocklist with an authoritative resolver...
>- Just don't support downloading/refreshing at all. Make it work exactly like the host/file/auto plugins, loads a blocklist from local disk and it's your problem to update them.
>
>WDYT? I'm leaning towards the first option, it seems like the simplest and only has minor downsides (failopen during bootstrap).

usually what we do is have an upstream that uses CoreDNS itself (`upstream` with 
no arguments). If that works you can resolve name and download the blocklist.

First option seems easiest to start with. Note the current block plugin does 
start the file on disk (can't remember if it looks there first though).

**Comment by joonas-fi** [comment]
I would love to see blacklisting implemented here, because I like coredns better than the alternatives:

- I don't like dnscrypt-proxy because it hangs for me from time to time (restarting the service fixes it), taking my network down. Also the author [is against adding metrics](https://github.com/jedisct1/dnscrypt-proxy/issues/337) or even discussing it further (replies to that issue are blocked), which I very much would like to have.
- I don't like pi-hole because it runs PHP, needs multiple binaries to run (even the containerized version looks too unclean), has metrics but it does not have latency metrics

I would like to point out that it would be nice to have metrics on number of blocked requests (not just the total number of requests). Not sure if it's architecturally possible easily.

**Comment by miekg** [comment]
All those things are easily doable within coredns, although an actual
webgui would probably need to be done separately.

**Comment by dichro** [comment]
I'm considering writing a module for this.

The goal is to apply public blocklists to internal DNS queries. 

Configuration will be simple:

blocklist URL
blocklist URL {
  refresh 2h
  expire 7d
  response_code NXDOMAIN // or maybe this should just be the default; not sure how useful having a configurable response is?
}
blocklist override {
  always_allow employer.com
  always_allow myadnetwork.com
  block competitor.com
}

The module will manage its own fetching and schedule. A unified database of all blocklists will be stored on-disk in leveldb; queries will hit it directly using only leveldb's own internal caching (Bloom filters should keep misses fast and hits will be fast on SSD and in-cache; for disk access to slow down the query path it'd need to be a large working set (ie, large number of clients?) of blocked queries and spinning disk; could include some config options to trade memory for performance if that turns into a problem for someone).

Simple metrics via prometheus, likely at per-blocklist-URL granularity. Fancier dashboards could be done via dnstap to some external visualization, but I don't think I'll care enough.

Is someone else already working on this? I'm aware of miekg/block and c-mueller/ads.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add blacklist..." ]
>I'm considering writing a module for this.
>
>The goal is to apply public blocklists to internal DNS queries.
>
>Configuration will be simple:
>
>blocklist URL
>blocklist URL {
>  refresh 2h
>  expire 7d
>  response_code NXDOMAIN // or maybe this should just be the default; not sure how useful having a configurable response is?
>}
>blocklist override {
>  always_allow employer.com
>  always_allow myadnetwork.com
>  block competitor.com
>}
>
>The module will manage its own fetching and schedule. A unified database of all blocklists will be stored on-disk in leveldb; queries will hit it directly using only leveldb's own internal caching (Bloom filters should keep misses fast and hits will be fast on SSD and in-cache; for disk access to slow down the query path it'd need to be a large working set (ie, large number of clients?) of blocked queries and spinning disk; could include some config options to trade memory for performance if that turns into a problem for someone).
>
>Simple metrics via prometheus, likely at per-blocklist-URL granularity. Fancier dashboards could be done via dnstap to some external visualization, but I don't think I'll care enough.
>
>Is someone else already working on this? I'm aware of miekg/block and c-mueller/ads.

ok, cool. No one is working on this. miekg/block is just a toy, don't know 
c-mueller/ads

**Comment by joonas-fi** [comment]
I wrote a simple encrypting DNS proxy that blocks ad queries, in Go: https://github.com/function61/function53

It has autoupdates for blocklist, but doesn't currently have any whitelisting.

Just mentioning this if any of it is of any help/inspiration..

**Comment by dichro** [comment]
By way of update, I'm scribbling in https://github.com/dichro/coredns-blocklist. There's a seemingly-working but unpolished in-memory-only plugin in there that I've just switched my home network over to. I've also pushed a docker image up to https://hub.docker.com/r/dichro/coredns-blocklist with a default config that monitors the same five blocklists as miekg's sample.

There's still a lot to do, but progress is happening!

**Comment by miekg** [comment]
Nice.

Note for a future PR. It's easiest to feed that to us in pieces. My
preference would be: readme, then setup and tests, then ServeDNS part(s)

**Comment by dichro** [comment]
Sure, I'd be happy to do that if this becomes a thing that you would want to have in-tree. In the meantime, just one minor question: what should I set User-Agent to when fetching blocklists? Is there a coredns policy on such things?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add blacklist..." ]
>Sure, I'd be happy to do that if this becomes a thing that you would want to have in-tree. In the meantime, just one minor question: what should I set User-Agent to when fetching blocklists? Is there a coredns policy on such things?

No such thing exists. What the Pi-Hole do/use?

**Comment by danderson** [comment]
I believe most blocklists are hosted on Github, so really the only purpose of the user agent is so that github knows who to contact if CoreDNS somehow starts a DDoS of blocklist fetching. Probably just "User-Agent: coredns" would be fine.

**Comment by stone-z** [comment]
As this is still one of the top search results for coredns blacklisting, for anyone interested, we made a plugin for alerting (but not blocking) on prohibited domains. It's a side project, so no warranty provided, but maybe it will meet someone's use case
https://github.com/giantswarm/coredns-warnlist-plugin

**Comment by theckman** [comment]
For anyone involved in this thread, I'm currently working on a CoreDNS plugin that will read the Pi-hole's `gravity.db` file to implement blocking of domains in a mechanism that _should_ be nearly identical to the Pi-hole instance.

I'm pursuing this because I use CoreDNS at home as a redundant resolver for my Pi-hole, where it either forwards requests to the Pi-hole or DNS over TLS to CloudFlare if the Pi-hole is offline. The end goal is to read a rsync'd `gravity.db` file from the Pi-hole instance, to have blocks when falling back to CloudFlare.

It should also support the groups / clients that you define in Pi-hole, so blocks can be done on a per IP basis right on the CoreDNS instance (which is functionality I lost by setting up the redundancy with CoreDNS, but wasn't using it). No real ETA, but I can drop a note here once I have the repo to show for it.

**Comment by reesericci** [comment]
It's a year later and wondering if there has been any progress on creating a quality blacklist plugin?

**Comment by mrbluecoat** [comment]
https://github.com/relekang/coredns-blocklist
