### ISSUE TITLE
plugin/metrics: add a metric to monitor which plugin(s) is(are) enabled

### ISSUE THREAD

**Issue by jiachengxu** [coredns/coredns#2273]
The initial idea is from #1520 , and we want to add a metric to monitor if the plugin `rewrite` is enabled.  @greenpau discussed this with me, and we think it would be better to have a global metric named `pulgin_enabled{server, name}`, so we can easily monitor all enabled plugins. 

I would like to work on this, but I don't really know how to get the list of enabled plugins. Does anyone know how to do that? 

Thanks,
Jiacheng

**Comment by greenpau** [comment]
cc: @miekg

**Comment by fturib** [comment]
The list of plugins for a server is available : https://github.com/coredns/coredns/blob/master/core/dnsserver/register.go#L185
```
func (c *Config) Handlers() []plugin.Handler {
..
}
```

see an example of usage in https://github.com/coredns/coredns/blob/master/plugin/health/setup.go#L31-L39

**Comment by greenpau** [comment]
> The list of plugins for a server is available

@fturib , 👍

**Comment by jiachengxu** [comment]
@fturib , thanks, will try that 👍 .

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/metrics: a..." ]
>The initial idea is from #1520 , and we want to add a metric to monitor if the plugin `rewrite` is enabled.  @greenpau discussed this with me, and we think it would be better to have a global metric named `pulgin_enabled{server, name}`, so we can easily monitor all enabled plugins.
>
>I would like to work on this, but I don't really know how to get the list of enabled plugins. Does anyone know how to do that?

Why is this needed? I ask, because, to me it's a bit weird to export the config 
file as a metric. I.e. incoming QPS is a metric, number of configured servers 
and plugins are defined in the config, why do we export that info again as a 
metric?

**Comment by greenpau** [comment]
> Why is this needed? 

@miekg , for the tracking of runtime changes to the configuration servers, i.e. when things are enabled/disabled. For example, suppose you enabled debug and forgot about it. You may have an alert that would say if "debug" plugin is enabled for more than 24 hours, then alert.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/metric..." ]
>> Why is this needed?
>
>@miekg , for the tracking of runtime changes to the configuration servers, i.e. when things are enabled/disabled. For example, suppose you enabled debug and forgot about it. You may have an alert that would say if "debug" plugin is enabled for more than 24 hours, then alert.

I can see that as a use-case. But why would you push/change things in production 
without having a similar change in version control? I.e that should be your 
alert.

I'm not against this per se, but I can see some road block on the 
implementation.

If the impl. will be sane, then sgtm

/Miek

--
Miek Gieben

**Comment by greenpau** [comment]
> But why would you push/change things in production without having a similar change in version control?

@miekg , I agree, ideally it should be like that. At the same time, not everyone is following processes 😃 Someone might change runtime and others would not know about it. I find this type of monitoring useful, but that's just me.

Regarding the performance implications, I think the metric generation for the configuration type things could happen either on startup and reload. Thus, it is probably light-weight in that sense.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/metric..." ]
>> But why would you push/change things in production without having a similar change in version control?
>
>@miekg , I agree, ideally it should be like that. At the same time, not everyone is following processes 😃 Someone might change runtime and others would not know about it. I find this type of monitoring useful, but that's just me.
>
>Regarding the performance implications, I think the metric generation for the configuration type things could happen either on startup or reload. Thus, it is probably light-weight in that sense.

ok!

**Comment by greenpau** [comment]
@miekg , not to mention malicious modification of DNS. 😢
