### ISSUE TITLE
Health Check for TCP forwarding should use the TCP connection

### ISSUE THREAD

**Issue by justinsb** [coredns/coredns#2275]
I'm using a `forward` block with `force_tcp`.  On a cache miss, I occasionally see 250ms responses, and sometimes ~500ms and (even more rarely) 750ms timeouts.

Looking at the code, I saw that health checks on the forward block (1) always use UDP, even when `force_tcp` is set and (2) likely wouldn't use the same TCP connection even so.

I'm not certain if this is root cause for my slow response times, but I think that health checks would ideally keep the upstream TCP connection alive, rather than going over a different transport which might not even be supported (if I'm specifying `force_tcp`).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Health Check for ..." ]
>I'm using a `forward` block with `force_tcp`.  On a cache miss, I occasionally see 250ms responses, and sometimes ~500ms and (even more rarely) 750ms timeouts.
>
>Looking at the code, I saw that health checks on the forward block (1) always use UDP, even when `force_tcp` is set and (2) likely wouldn't use the same TCP connection even so.
>
>I'm not certain if this is root cause for my slow response times, but I think that health checks would ideally keep the upstream TCP connection alive, rather than going over a different transport which might not even be supported (if I'm specifying `force_tcp`).

I doubt this is HC related. We be good to dig deeper though (tcpdump?)

/label: proxy

**Comment by justinsb** [comment]
You are correct - I've verified it is likely not root cause for my slow response times (I added lots of logging, I see a new TCP connection and what looks like the first read times out after 200ms).  I'm working on getting a packet dump, but I suspect that it will be a different issue.  (i.e. I think this issue is correct, even if it wasn't the cause of my personal issue?)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Health Check ..." ]
>You are correct - I've verified it is likely not root cause for my slow response times (I added lots of logging, I see a new TCP connection and what looks like the first read times out after 200ms).  I'm working on getting a packet dump, but I suspect that it will be a different issue.  (i.e. I think this issue is correct, even if it wasn't the cause of my personal issue?)

indeed, this issue is real the HC should use the same protocol as the data. 
(That was part of the reason to write the forward plugin in the first place)

**Comment by miekg** [comment]
After some time, I'm going to the reverse conclusion. Why is this exactly a problem? Having HC just use UDP seems actually fine to me (now)

**Comment by chrisohaver** [comment]
For an upstream that can only be reached via tcp, health checking will always fail if HC always uses udp.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Health Check ..." ]
>For an upstream that can only be reached via tcp, health checking will always fail if HC always uses udp.

udp + tcp are both a MUST in the RFCs; we do not accommodate things that 
blatantly fail to implement the standard

**Comment by chrisohaver** [comment]
> udp + tcp are both a MUST in the RFCs;

So should HC check both?

**Comment by miekg** [comment]
how do you deal with conflicts?

**Comment by chrisohaver** [comment]
It depends on the protocols forward will use with the upstream.  It seems reasonable that HC should report that an upstream healthy if it is reachable on at least one protocol that the forward plugin will use when forwarding requests to that upstream.
* If only forwarding to the upstream over tcp, then HC should report healthy if it can be reached via tcp.
* If forwarding to the upstream over both tcp/udp, then HC should report healthy if it can be reached via at least one of tcp or udp.

**Comment by miekg** [comment]
complex hc options help noone
