### ISSUE TITLE
Question: how to merge partial zones

### ISSUE THREAD

**Issue by raffaelespazzoli** [coredns/coredns#2276]
I have a situation where different part of a system see know about DNS records of a zone. When merge together they represent an entire DNS zone.
different core DNS plugins can retrieve the partial information. Is there a way to merge together these records and serve them via coredns?

If interested in my specific use case, you can find more information here:
https://blog.openshift.com/connecting-multiple-openshift-sdns-with-a-network-tunnel-part-2-service-proxying-and-discovery/

I haven't found anything in my research and I think in these situation a merge plugin would be useful.
Is there any plan to build something like that?

**Comment by fturib** [comment]
@raffaelespazzoli : I am not sure I understand your question here. The link you provide explains how to resolve this case with CoreDNS.

What is the point you are focusing on this doc ?

**Comment by raffaelespazzoli** [comment]
@fturib I should have been more specific. The last sentence in the `coredns` section is where the issue is raised. I quote the sentence here:
"It would be nice to have an additional domain called `cluster.all` that returns the merge of all the responses to a given query from all the connected clusters. I believe it’s not currently possible to create that configuration with the currently available coredns plugins." 

Ideally a configuration for my particular use case would look like the following:
```
cluster.all:53 {
    merge {
        {
        rewrite stop {
            name substring svc.cluster.all svc.cluster.raffa1
            answer substring svc.cluster.raffa1 svc.cluster.all
        kubernetai cluster.raffa1 {
            kubeconfig ...
        }
        }
        {
        rewrite stop {
            name substring svc.cluster.all svc.cluster.raffa2
            answer substring svc.cluster.raffa2 svc.cluster.all
        kubernetai cluster.raffa1
        }
        kubernetai cluster.raffa2 {
            kubeconfig  ...
        }
        }

    }
}```

**Comment by fturib** [comment]
I understand now ...
However you do not need a merge per say : the rewriting (the answer part) you propose should automatically "merge" the replies under the same zone.

What I not clear is the "split" part : for incoming queries, if they are all on the same "cluster.all" zone, how do you know which one should be rewrite in "cluster.raffa1" and which ones should be in "cluster.raffa2" ?

**Comment by fturib** [comment]
Let say all incoming queries are on the domain "xxxx.cluster.all", how would you know the queries that are coming from the cluster.raffa1 ? the queries that are coming from belongs 

does it depends of the client that send the query ?
does it depends on the interface your receive the query ?
something else ?

From the document I understand that it depends of the requestor (the client that send the query).

=> If you can have one of the two following solution, then you can implement your split and therefore use a 'cluster.all' zone for all your clusters.

A- separate the incoming queries per port:
- each client of raffa1 sending the query on a specific port - let say 5350
- each client of raffa2 sending the query on a specific port - let say 5351

B- or separate the incoming queries per interface
- each client of raffa1 sending the query on a specific IP of the CoreDNS pod
- each client of raffa2 sending the query to another specific IP of the CoreDNS port

**Comment by raffaelespazzoli** [comment]
@fturib perhaps an example can explain.
let's say we have a Kubernetes service named `product` in namespace `myns` deployed in both clusters.
it will get an entry called `product.myns.svc.cluster.local` in both of the clusters, but the associated IPs will be different (let's call them IP1 and IP2).
With the setup described in the article those services will also get the following entries: `product.myns.svc.cluster.raffa1` and `product.myns.svc.cluster.raffa2`.

What I'd like to happen is that in the `cluster.all` zone there be this entry `product.myns.svc.cluster.all` and  when an nslookup is done to that name, both IP1 and IP2 are returned (hence the merge). Or of the loadbalance plugin is on, then one of the IP is returned at random.

**Comment by fturib** [comment]
@raffaelespazzoli : so you would like to resolve:
- listen for zone "cluster.local"
- resolve against ALL the kubernetai plugins (all in same time) - with a translation of domain
- return the union of all replies, each of which would have a translation back to the "cluster.local" zone

**Comment by raffaelespazzoli** [comment]
@fturib correct.

**Comment by chrisohaver** [comment]
Interesting.

It could be done as a merge plugin that accepts a list of zones it would merge into another zone... e.g.

```
merge cluster.local {
  cluster.raffa1
  cluster.raffa2
}
```

The plugin could work very similarly to [*autopath*](https://github.com/coredns/coredns/tree/master/plugin/autopath) ... stripping the primary zone (e.g. cluster.local), and trying a query for each zone in the list (e.g. cluster.raffa1, cluster.raffa2)... Except that when it finds answers, it keeps trying each zone in the list and appends all answers (autopath stops when it gets an answer from one of the zones).  It would then overwrite the zones of answers in each zone to the primary zone before sending to the client.

**Comment by raffaelespazzoli** [comment]
@chrisohaver I like your proposal, much cleaner config.

**Comment by raffaelespazzoli** [comment]
@miekg why was this closed? What was the decision? Will the merge plugin be developed?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Question: how..." ]
>@miekg why was this closed? What was the decision? Will the merge plugin be developed?

unless you step forward? There are no plans AFAICT to create anything.

(was also under the impression this was a question which is now answered)
