### ISSUE TITLE
support for DNS record health checks

### ISSUE THREAD

**Issue by raffaelespazzoli** [coredns/coredns#2277]
commercial global load balancers can associate a health check to a WIP. This allows the global load balance to automatically disable a DNS record should the application behind it become unavailable.
For example this this: https://www.yourserver.se/blog/20-powergslb-powerdns-backend-with-monitoring

Is there any plan to support this feature with coredns?
would is be a good plugin to have?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] support for DNS r..." ]
>commercial global load balancers can associate a health check to a WIP. This allows the global load balance to automatically disable a DNS record should the application behind it become unavailable.

WIP => VIP?

>For example this this: https://www.yourserver.se/blog/20-powergslb-powerdns-backend-with-monitoring
>
>Is there any plan to support this feature with coredns?
>would is be a good plugin to have?

The loadbalance plugin would be a good candidate.

But it would be good to iterate on the exact design.

--
Miek Gieben

**Comment by raffaelespazzoli** [comment]
WIP stands for a Wide IP (here is a some reference: https://techmonkeys.readthedocs.io/en/latest/baboon-proxy/global%20trafficmanager/wideips.html)

in terms of design here is what is in my mind:
1. the way the health check definition and the status of a individual endpoint is defined/stored may vary from different types of storage (i.e. backend plugins). We should introduce this notion in a non disruptive way.
2. a separate agent/process might query the back storage run the healthcare and update the availability status. This operation is asynchronous to any DNS query. Each record might have different health check settings with regards to frequency, number of attempts etc... We can use the pod readiness check as a model.
3. the DNS serving part needs to be aware of these feature and return only the records that are currently available.
This feature is probably only possible when we control the storage of the record, such as for etcd, redis, and maybe the file plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] support for D..." ]
>WIP stands for a Wide IP (here is a some reference: https://techmonkeys.readthedocs.io/en/latest/baboon-proxy/global%20trafficmanager/wideips.html)
>
>in terms of design here is what is in my mind:
>1. the way the health check definition and the status of a individual endpoint is defined/stored may vary from different types of storage (i.e. backend plugins). We should introduce this notion in a non disruptive way.

>2. a separate agent/process might query the back storage run the healthcare and update the availability status. This operation is asynchronous to any DNS query. Each record might have different health check settings with regards to frequency, number of attempts etc... We can use the pod readiness check as a model.

yes, this is best done in a new process. CoreDNS than just queries this every N 
seconds to get an update for the healthy backends.

>3. the DNS serving part needs to be aware of these feature and return only the records that are currently available.
>This feature is probably only possible when we control the storage of the record, such as for etcd, redis, and maybe the file plugin.

That's not needed, a plugin can do this, but it needs to know how A and AAAA 
(and maybe others) map to the health backends information available.

>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/coredns/coredns/issues/2277#issuecomment-436985461
/Miek

--
Miek Gieben

**Comment by g13013** [comment]
Why is this issue closed ?

**Comment by m-yosefpor** [comment]
should we reconsider opening this?

**Comment by chrisohaver** [comment]
> Why is this issue closed ?

I presume because it went idle for 3 months in the midsts of design iteration.

> should we reconsider opening this?

Yes, if someone is interested in picking up where the discussion stopped.

**Comment by ajaymahto15** [comment]
Hi Team, 

Any updates on this feature request? This is a requirement for one of our projects. 
If there's one, can someone pass on the details / links or do we need to write the plugin yet.

**Comment by pablocolson** [comment]
Same here :)
