### ISSUE TITLE
How to add a DNS record easily?

### ISSUE THREAD

**Issue by EarlYan** [coredns/coredns#2278]
In some circumstances, what if i don't have nameserver, for example it's empty in /etc/resolv.conf, how do make coredns works?
In kube-dns, i use dnsmasq, using --addn-hosts to mount a ConfigMap outside. So i can edit it to add a DNS record myself.
Should i use dnsmasq with coredns, or there is a another way to solve this problem?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] How to add a DNS ..." ]
>In some circumstances, what if i don't have nameserver, for example it's empty in /etc/resolv.conf, how do make coredns works?
>In kube-dns, i use dnsmasq, using --addn-hosts to mount a ConfigMap outside. So i can edit it to add a DNS record myself.
>Should i use dnsmasq with coredns, or there is a another way to solve this problem?

Why are you not able to do something simular w/ coredns? I don't know what 
--addn-hosts does, but sounds similar to the hosts plugin.

**Comment by EarlYan** [comment]
Thanks for answering, i have already solved this problem using hosts plugin. Mount a hosts file into container. It can add additional or customized DNS record.
