### ISSUE TITLE
i/o timeout when set upstream

### ISSUE THREAD

**Issue by xieydd** [coredns/coredns#2287]
When i set a upstream dns server, i find the dns solved is slow, and the log of coredns pod is ：
```
[ERROR] 2 mirrors.unisound.ai. AAAA: unreachable backend: read udp 10.99.17.97:60877->10.10.10.252:53: i/o timeout
```
AFAIK， many people meet the error.
@chrisohaver Can you help me ?

**Comment by chrisohaver** [comment]
What version of CoreDNS are you using?

**Comment by xieydd** [comment]
@chrisohaver I use the version 1.1.3

**Comment by chrisohaver** [comment]
What does your Corefile look like?

**Comment by xieydd** [comment]
```
.:53 {
        errors
        health
        kubernetes cluster.local 10.100.0.0/24 {
          pods insecure
          upstream 10.10.10.252
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```
@chrisohaver Thanks a lot

**Comment by chrisohaver** [comment]
If `10.10.10.252` is your upstream server, try the following...

```
.:53 {
        errors
        health
        kubernetes cluster.local 10.100.0.0/24 {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . 10.10.10.252
        cache 30
        reload
 }
```

If this works, it means `/etc/resolv.conf` may not actually contain your upstream servers.

**Comment by xieydd** [comment]
I am sorry , I can`t connect the cluster now, i will test it tomorrow. Thanks for your reply timely。
@chrisohaver 👍

**Comment by xieydd** [comment]
@chrisohaver Maybe I'm not making myself clear，the dns solve slowly ,but finally it can be solved.
And i test your suggestion yet, it not work，haha.

**Comment by chrisohaver** [comment]
OK, thanks for clarifying. Do you get reliable behavior when querying the upstream server directly from a Pod in the cluster?

**Comment by xieydd** [comment]
The log above is that i run `nslookup mirrors.unisound.ai` result, and another problem is that , when i set upstream , the pod can't solve `kubernetes.default` and `kubernetes.default.svc` but can solve `kubernetes` and `kubernetes.default.svc.local` , it is confused. @chrisohaver

**Comment by chrisohaver** [comment]
Can you clarify whet you mean by "when i set upstream"?  What exactly are you doing there?

If you are referring to the `upstream` option in the `kubernetes` plugin, this is only used for CNAME resolution, which isn't coming into play in your examples.

Based on the error, (a timeout on an AAAA request), it could mean a the upstream server is not responding to AAAA record requests... or perhaps more generally the network is flaky and dropping some upstream requests randomly, causing timeouts, client retries, and delays.

**Comment by xieydd** [comment]
Afaik, if i `nslookup kubernetes.default` iit will search the `/etc/resolv.conf` and in `/etc/resolv.conf` , it has the `search svc.cluster.local`, but it doesn`t work , and it search the upstream server. @chrisohaver

**Comment by chrisohaver** [comment]
Some versions of busybox contain a broken `nslookup` that ignores the search in `/etc/resolv.conf`.
Aside from that, `nslookup` is not the best troubleshooting tool because it doesn't have a good verbose option.  `dig` is better for troubleshooting, it has less ambiguous output.

I still don't know for sure what you mean by "when i set upstream".  Can you please clarify that?

**Comment by xieydd** [comment]
@chrisohaver  Thanks for your suggestion,when i don't set the upstream `upstream 10.10.10.252` , `nslookup kubernetes.default` is successful , but when i set `upstream 10.10.10.252` , `nslookup kubernetes.default` will fail , and the log of coredns is 
```
[ERROR] 2 mirrors.unisound.ai. AAAA: unreachable backend: read udp 10.99.17.97:60877->10.10.10.252:53: i/o timeout
```

**Comment by chrisohaver** [comment]
Thats odd, because there should be absolutely zero connection between the `upstream` setting, and that behavior.  `upstream` is only used for resolution of `CNAME` records (externalName services), which are not involved here at all.  There must be something else going on.

**Comment by xieydd** [comment]
I will use `dig` wo check my network environment, Thanks for your reply 👍

**Comment by chrisohaver** [comment]
Note that `dig` does not follow search list in `/etc/resolv.conf` by default, you need to pass the `+search` option for it to do that.

**Comment by ghost** [comment]
i encountered the same problem
i use  kubeadm  to start the cluster, everything is fine but CoreDNS
pod can't resolve the service name from DNS
![image](https://user-images.githubusercontent.com/38696086/50382216-31834d00-06d5-11e9-9e11-8a82e22e6584.png)

![image](https://user-images.githubusercontent.com/38696086/50382221-45c74a00-06d5-11e9-98c4-92a1f94053f8.png)

**Comment by DimitrijeManic** [comment]
@JadeRing I was facing the same issue as you were, I was able to resolve this by configuring `/etc/netplan/50-cloud-init.yaml` on the `worker node` and setting the nameserver to '8.8.8.8' instead of my `192.168.1.1`. 

I think the issue could be that the pods are on a different subnet and are not able to access my DNS on 192.168.1.1. 

another potential issue could be this [known issue](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues) regarding some distros (Ubuntu) and the `--resolv-conf` flag

**Comment by dinhanhhuy** [comment]
same here, can we re-open this issue
<img width="1111" alt="Screen Shot 2019-08-09 at 5 38 33 PM" src="https://user-images.githubusercontent.com/20637671/62773550-9c4e9080-bacc-11e9-9433-f565f2f2fe38.png">
<img width="1200" alt="Screen Shot 2019-08-09 at 5 39 03 PM" src="https://user-images.githubusercontent.com/20637671/62773552-9ce72700-bacc-11e9-927e-7420a4f1e0a3.png">

**Comment by chrisohaver** [comment]
@dinhanhhuy, It looks like there is some kind of networking configuration problem in your Kubernetes cluster, not a configuration problem with CoreDNS.  Your Kubernetes cluster is not creating a route to 8.8.8.8.
