### ISSUE TITLE
middleware/kubernetes dns.TypeTXT handling floods logs

### ISSUE THREAD

**Issue by toxeek** [coredns/coredns#2290]
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-18T14:14:00Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Deployed on AWS via KOPS.

We've noticed a flood in the coreDNS logs,

*2018/11/12 14:14:35 [ERROR] 2 localhost.svc.cluster.local. TXT: kubernetes: TXT query can only be for dns-version: localhost.svc.cluster.local.
2018/11/12 14:14:36 [ERROR] 2 localhost.kube-system.svc.cluster.local. TXT: kubernetes: TXT query can only be for dns-version: localhost.kube-system.svc.cluster.local.
2018/11/12 14:14:36 [ERROR] 2 localhost.kube-system.svc.cluster.local. TXT: kubernetes: TXT query can only be for dns-version: localhost.kube-system.svc.cluster.local*

Looks like use fmt.Errorf() may be unnecessary? 
https://github.com/coredns/coredns/blob/e55d4016333b734a91fdbd052df7eb7c461b3403/middleware/kubernetes/kubernetes.go#L95

I've found this commit where it used to be handled differently,
https://gitlab.dev.cncf.ci/coredns/coredns/commit/a5fb0b3c6e78ef0e1fb7a64617f7b3c0652f8f40#c057aa3189033e047bf59d4f80eb526e5ccae008_102_93

This is related to the 'dns-version' TXT record that should be available,
https://github.com/kubernetes/dns/blob/master/docs/specification.md#22---record-for-schema-version

And my guess is that we aren't doing any intentional DNS TXT RRS based queries.

**Comment by chrisohaver** [comment]
> we aren't doing any intentional DNS TXT RRS based queries.

Per the logs, a Pod in your cluster is doing TXT queries of `localhost` ...

Regardless, I think we can just return `NXDOMAIN` here, no need to report an error.

**Comment by toxeek** [comment]
Hi @chrisohaver,

thanks for getting back promptly. I'll see what we may be doing in that/those pods, quite odd as we don't have any requirements based on issuing this type of query but thanks for pointing that one out.

> Regardless, I think we can just return NXDOMAIN here, no need to report an error.

That may be a good thing to do, may be a little bit less 'noisier' 👍
