### ISSUE TITLE
plugin/forward: dynamic read timeout - is it useful?

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#2306]
We have introduced this feature some time ago - see #1659, #1680, #1889.

The main reason for this was faster retrying in case of lost UDP query/response (i/o timeout) and having more attempts to retry in 5s interval, see also closed #1624

However, now I think this feature doesn't work fine in many cases and may be a reason for troubles like #2265. 

This is because we cannot reliably predict a reasonable timeout for next query based on RTT of previous queries. The time needed to resolve domain name varies significantly between different queries. It may depend on how many labels the queried domain name has, or which records have already been cached (or evicted from cache) on resolver side, or how responsive authoritative domain name servers for particular zone, the protocol used (UPD or TCP), etc

So, I propose to remove dynamic read timeout logic. I would also prefer to have the query timeout value configurable. I know @miekg you don't like knobs like this, but IMO this option would be really helpful for many people, since the timeout is highly dependent on environment in which coredns works, and we cannot predefine an ideal constant which would work perfectly for everyone.

As for similar feature for dynamic dial timeout (#1852) we may want to keep it, since dialTimeout doesn't depend on queried domain and dialing time may give more consistent values.

Any thoughts?

**Comment by miekg** [comment]
> This is because we cannot reliably predict a reasonable timeout for next query based on RTT of previous queries

How so? I think that can be very helpful. And if not; punning this to a user doesn't really solve the problem?


Seems #2265 is on the dial side, not the reading from the socket

**Comment by rdrozhdzh** [comment]
According to this feature, the timeout for next query is set twice bigger than average RTT from previous 4 queries. As I explained before, RTTs of subsequent queries may differ significantly, much more than twice. If dynamic timeout appears too little for current query, we reset timeout to MAX for _this_ proxy, close connection and do another attempt (likely via another proxy).

Regarding #2265, I'm not 100% sure that the problem is related to dynamic timeout. But the possible scenario could look like following

User browse some site, resolves some links related to this site. As result coredns opens say 20 TLS connections to 1.1.1.1 to resolve domain names. After visiting several pages on this site DNS queries works quite fast because they all likely got cached. As result the dynamic timeout is set to some little value, say 200ms
Now lets assume user go to another site which has a lot of links to other resources. coredns receives say 20 new DNS requests and tries to complete them within timeout 200ms. But these new domains are not cached yet and need more time for resolving. As result, all queries get timed out. All 20 connections get closed. And we retry all these 20 DNS queries again with MAX timeout and via new connections. And setting up these TLS connections consumes a lot of CPU. Due to this, or by another reason, the dialing may also get timed out (because of little dynamic dial timeout previously set). And we increase dial timeout and do one more attempt. Finally, we resolve all the queries but by the cost of additional retries

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>According to this feature, the timeout for next query is set twice bigger than average RTT from previous 4 queries. As I explained before, RTTs of subsequent queries may differ significantly, much more than twice. If dynamic timeout appears too little for current query, we reset timeout to MAX for _this_ proxy, close connection and do another attempt (likely via another proxy).

But we track dialtimeout completely separately from this. Doing the above 
calculation for read/write timeout doesn't seem completely off to me.

>Regarding #2265, I'm not 100% sure that the problem is related to dynamic timeout. But the possible scenario could look like following
>
>User browse some site, resolves some links related to this site. As result coredns opens say 20 TLS connections to 1.1.1.1 to resolve domain names. After visiting several pages on this site DNS queries works quite fast because they all likely got cached. As result the dynamic timeout is set to some little value, say 200ms

>Now lets assume user go to another site which has a lot of links to other resources. coredns receives say 20 new DNS requests and tries to complete them within timeout 200ms. But these new domains are not cached yet and need more time for resolving. As result, all queries get timed out. All 20 connections get closed. And we retry all these 20 DNS queries again with MAX timeout and via new connections. And setting up these TLS connections consumes a lot of CPU. Due to this, or by another reason, the dialing may also get timed out (because of little dynamic dial timeout previously set). And we increase dial timeout and do one more attempt. Finally, we resolve all the queries but by the cost of additional retries

That sounds possible. But this would mean we can just adjust our algorithm. I.e.  
calculating 1 avg is pretty crude. Have more of a min/max in the calcuation as 
well (or only a min-max as the band we operate in)?

**Comment by miekg** [comment]
The initial symptom in #2265 is "DialWithDialer timed out", which may mean we're just to aggressive for tls connections. This can be easily tested.

**Comment by rdrozhdzh** [comment]
> But we track dialtimeout completely separately from this.

right, I'm talking about read timeout

> Doing the above calculation for read/write timeout doesn't seem completely off to me.

As I said, read timeout depends on how long upstream server (resolver) serves the query. And this time may significantly vary depending on domain name.
If we subsequently query *github.com*, *facebook.com*, *google.com*, *wikipedia.org* and get average response time = 10ms it doesn't mean that *in.a.galaxy.far.far.away* will be resolved in 20ms (twice higher time than average RTT of previous queries)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>As I said, read timeout depends on how long upstream server (resolver) serves the query. And this time may significantly vary depending on domain name.
>If we subsequently query *github.com*, *facebook.com*, *google.com*, *wikipedia.org* and get average response time = 10ms it doesn't mean that *in.a.galaxy.far.far.away* will be resolved in 20ms (twice higher time than average RTT of previous queries)

ack. Yes, I think this might be contributing here. I think we can be smarter how 
we calculate this timeout (not clear atm how though)
