### ISSUE TITLE
Please Add Response Rate Limiting (RRL) to coreDNS

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#2311]
I've started using coreDNS as an old-fashioned authoritative DNS server for several smaller domains that I own as well as for maintaining a large zone of malicious domains (for RPZ security filtering). After finding and getting a fix for a memory leak (https://github.com/miekg/dns/issues/786) in the large malicious zone, coreDNS has been stable and working very well as an old-fashioned authoritative DNS server.

However, I'm concerned now about generic UDP abuse of the authoritative servers and want to request that coreDNS implement Response Rate Limiting (RRL) as a mechanism to mitigate this. BIND and NSD (as well as several others) have been doing RRL since 2012/2013 and it seems to work well at preventing the abuse/misuse of authoritative DNS servers. 

* http://www.redbarn.org/dns/ratelimits
* http://ss.vix.su/~vixie/isc-tn-2012-1.txt

US Cert recommends RRL to prevent this type of abuse as well (https://www.us-cert.gov/ncas/alerts/TA13-088A):

"While the most common form of this attack that US-CERT has observed involves DNS servers configured to allow unrestricted recursive resolution for any client on the Internet, attacks can also involve authoritative name servers that do not provide recursive resolution. The attack method is similar to open recursive resolvers, but is more difficult to mitigate since even a server configured with best practices can still be used in an attack. In the case of authoritative servers, mitigation should focus on using Response Rate Limiting to restrict the amount of traffic."

Thanks for the consideration,

Brad

**Comment by miekg** [comment]
Yes we should. A RRL plugin should not be too hard to write.

**Comment by miekg** [comment]
thanks!

**Comment by semihalev** [comment]
Just a suggestion, you can implement RRL with RFC 7873 cookies.

**Comment by stevemcquaid** [comment]
Thanks @semihalev https://github.com/semihalev/sdns/commit/e4730059a173bab8ecc1374a841eddef9e2db001 ;)

**Comment by nsinghisking** [comment]
@semihalev , Thanks for taking this on, just wondering if you have a prototype for me to try

**Comment by semihalev** [comment]
@nsinghisking if you like, I have a server running this.

**Comment by fturib** [comment]
@semihalev : you server is a CoreDNS running with this feature ? 

@stevemcquaid : I see you assigned this issue to yourself, are you in the process of building a RRL plugin for CoreDNS ?

**Comment by semihalev** [comment]
@fturib no, running on sdns as @stevemcquaid linked. I'm working on resolver plugin for CoreDNS.

**Comment by stevemcquaid** [comment]
@fturib yes - chugging along on RRL-only as a plugin.

**Comment by chrisohaver** [comment]
@stevemcquaid, Thanks, do you have an ETA?  And at a high level, are you more or less replicating the behavior of an existing solution (e.g. BIND).

**Comment by chrisohaver** [comment]
@stevemcquaid, I have a need for a Bind-like RRL feature in CoreDNS.
Are you close to a solution?  If no, I'll need to start designing/implementing this.  If yes, do you have a work in progress you can share yet?  Perhaps we can collaborate.

**Comment by chrisohaver** [comment]
FYI, I'm going to get started on this, with the goal of essentially replicating the BIND RRL feature as documented in BIND docs.

**Comment by chrisohaver** [comment]
See ... https://github.com/coredns/rrl if you want to try it out.  It's still pretty fresh, and has only been lightly tested.

**Comment by miekg** [comment]
external plugin exists.
