### ISSUE TITLE
Enable message compression.

### ISSUE THREAD

**Issue by edganiukov** [coredns/coredns#2312]
CoreDNS version: 1.2.6

So far, message compression is applied when client buffer size is smaller then message size. I have a case, when message size is bigger then 2048 bytes, this leads to IP-package fragmentation, unlike KubeDNS which always compresses messages.

Would be great to have possibility to enable compression for all cases.

**Comment by miekg** [comment]
I would not want to make this configurable. But just enabling this always
makes sense. That still wouldn't solve fragmentation though. Esp. for
service discovery where you sometimes just have large responses.

**Comment by edganiukov** [comment]
> I would not want to make this configurable. But just enabling this always makes sense. That still wouldn't solve fragmentation though. Esp. for service discovery where you sometimes just have large responses.

Fair enough. 
Basically, in my case compression solves the issue I have - CoreDNS returns 2500 bytes, KubeDNS  740 bytes, whereas I have no issues within Kubernetes cluster (resolving directly with CoreDNS), I am not able to resolve through chain of DNS servers (using zone delegation) - I receive only first fragment (1520 bytes). Fore sure it is related to our network setup, but I am not controlling it and it is quite complicated to find a problem. 

I don't know about other DNS servers, but KubeDNS compresses by default all messages, so it seems good to have compression by default in CoreDNS.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Make message ..." ]
>> I would not want to make this configurable. But just enabling this always makes sense. That still wouldn't solve fragmentation though. Esp. for service discovery where you sometimes just have large responses.
>
>Fair enough.
>Basically, in my case compression solves the issue I have - CoreDNS returns 2500 bytes, KubeDNS  740 bytes, whereas I have no issues within Kubernetes cluster (resolving directly with CoreDNS), I am not able to resolve through chain of DNS servers (using zone delegation) - I receive only first fragment (1520 bytes). Fore sure it is related to our network setup, but I am not controlling it and it is quite complicated to find a problem.
>
>I don't know about other DNS servers, but KubeDNS compresses by default all messages, so it seems good to have compression by default in CoreDNS.

Yes, I think this makes sense. Although we good but slightly smug, and only 
compress if the msg size is larger then 14xx (for ipv4) or 1280 (for ipv6) as an 
optimization.

**Comment by miekg** [comment]
These defaults are added, we're not going expose a knob.
