### ISSUE TITLE
Proposal: Modify dns.ResponseWriter.WriteMsg to return bytes written

### ISSUE THREAD

**Issue by stuartnelson3** [coredns/coredns#2317]
As mentioned in https://github.com/coredns/coredns/issues/2258, response sizes are being incorrectly reported because the `ScrubWriter`, which modifies the `dns.Msg` being sent to the client, was moved to being in the server. The way that the code is set up, the `ScrubWriter` gets wrapped with other writers in various plugins, and when a plugin finally writes to the `ResponseWriter`, each layer in this middleware chain is able to access the message to be written, and the potential error that results from writing.

My proposal is, in addition to returning an error from writing, to also return the actual amount of bytes written.

The main motivation is allowing the prometheus and logging plugins to report the correct amount of bytes written. The method would also be more in line with the various `Write*` methods in the [stdlib](https://golang.org/pkg/io/#Writer).

As an example, `dns.Recorder` sets a `Len` struct member by calculating the length of the message it receives. If `WriteMsg` were to return the  length of the message written, it would result in less work being done (logging and prometheus plugins no longer have to calculate the message length themselves), and the value returned from the `ScrubWriter`, the actual number of bytes written, would be available to the `Recorder`.

```diff
 // WriteMsg records the status code and calls the
 // underlying ResponseWriter's WriteMsg method.
-func (r *Recorder) WriteMsg(res *dns.Msg) error {
+func (r *Recorder) WriteMsg(res *dns.Msg) (int64, error) {
        r.Rcode = res.Rcode
        // We may get called multiple times (axfr for instance).
        // Save the last message, but add the sizes.
-       r.Len += res.Len()
+       n, err := r.ResponseWriter.WriteMsg(res)
+       r.Len += n
        r.Msg = res
-       return r.ResponseWriter.WriteMsg(res)
+       return n, err
 }
```

This would require changes not only to coredns, but potentially to several external plugins. I believe providing the actual count of bytes written is worth it, however.

**Comment by miekg** [comment]
Sadly calling Len is not entirely a fast operation as we iterate over the
entire message. So to do this we probably need a very strong justification.

**Comment by stuartnelson3** [comment]
Unless I'm mistaken, this change would result in less work, with the scrubwriter calling `Len()`, and then the result being passed back up the call chain the to any middleware interested in it. The current code in master has the recorder calling `Len()` on its own, which would be additional invocations of this method.

**Comment by miekg** [comment]
OK, pleases send a PR. Doing less work sounds good :)

**Comment by stuartnelson3** [comment]
Sorry for the long delay, been busy with work stuff. It appears the refactoring should be pretty simple, even though it will touch a lot of files:

https://github.com/coredns/coredns/search?q=WriteMsg&unscoped_q=WriteMsg
https://github.com/miekg/dns/search?q=WriteMsg&unscoped_q=WriteMsg

I'll try to get to this soon, but I'm leaving these searches here in case someone else wants to get involved. It should be a fairly simple change, might be a good first PR for someone.

**Comment by miekg** [comment]
this can't be done, because it's a backward incompat change.

**Comment by stuartnelson3** [comment]
The change is backwards incompatible if it's made in `dns`, but would you be open to only changing it within `coredns`?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Proposal: Mod..." ]
>The change is backwards incompatible if it's made in `dns`, but would you be open to only changing it within `coredns`?

No, that's too much of a hassle.
