### ISSUE TITLE
log configuration question

### ISSUE THREAD

**Issue by visheyra** [coredns/coredns#2323]
Hello all.

I try to removes the logs for a particular domain that is already defined inside my configuration. I'm running coredns `1.1.3` inside kubernetes.

My corefile is the following:

```
    .:53 {
        loadbalance round_robin
        errors
        log . {
          class error
          class denial
          class success
        }
        log cluster.local {
          class error
          class denial
        }
        health
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```

The idea is not to log the NOERROR lines when a name from cluster.local is resolved (in other word, a name from inside my cluster). But this is not working so far.

Do you is there is a way to achieve such goal ?

**Comment by visheyra** [comment]
in other words is there any way to use a negation on the match field ?

**Comment by stp-ip** [comment]
Splitting up the config should do.
That might add more duplication and issues with prometheus so.

**Comment by stp-ip** [comment]
So using something along the lines of:
```
    .:53 {
        loadbalance round_robin
        errors
        log . {
          class error
          class denial
          class success
        }
        health
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
    cluster.local:53
        loadbalance round_robin
        errors
        log cluster.local {
          class error
          class denial
        }
        health
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```

No negative matching available.

**Comment by visheyra** [comment]
Thank you very much guys. Everything is working fine by now. Just note that I had to update the [healthcheck](https://coredns.io/plugins/health) otherwise the port would not bind.
