### ISSUE TITLE
my coredns is always restart!

### ISSUE THREAD

**Issue by liaoqiArno** [coredns/coredns#2325]
[root@k8s-node131 ~]# kubectl  get pods -n kube-system -o wide
NAME                                       READY   STATUS    RESTARTS   AGE   IP                NODE          NOMINATED NODE
calico-etcd-6hrmh                          1/1     Running   0          89m   192.168.226.131   k8s-node131   <none>
calico-kube-controllers-85cf9c8b79-xh7rh   1/1     Running   0          90m   192.168.226.133   k8s-node133   <none>
calico-node-f944w                          2/2     Running   3          90m   192.168.226.131   k8s-node131   <none>
calico-node-fzgx7                          2/2     Running   1          90m   192.168.226.132   k8s-node132   <none>
calico-node-qnsqs                          2/2     Running   0          90m   192.168.226.133   k8s-node133   <none>
coredns-576cbf47c7-4sftw                   1/1     Running   6          90m   192.168.124.3     k8s-node133   <none>
coredns-576cbf47c7-snjz6                   1/1     Running   5          90m   192.168.124.4     k8s-node133   <none>

I just deployded a k8s cluster， but I find the dns containers is always restart。

[root@k8s-node131 kubernetes]# kubectl logs -f coredns-576cbf47c7-4sftw  -n kube-system 
E1120 07:14:54.483662       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:355: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:14:54.483810       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:14:54.484112       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:350: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:15:25.485339       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:355: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:15:25.485675       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:15:25.487416       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:350: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:15:56.486462       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:355: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:15:56.487787       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:15:56.489089       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:350: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
2018/11/20 07:16:04 [INFO] SIGTERM: Shutting down servers then terminating
E1120 07:16:27.487176       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:355: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:16:27.488541       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1120 07:16:27.489990       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:350: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout

the logs  look   it's timeout.
who can tell me the reason?

think you very much!

**Comment by chrisohaver** [comment]
Looks like the kubernetes API is not reachable.

**Comment by liaoqiArno** [comment]
> Looks like the kubernetes API is not reachable.
I used kubeadm create cluster.
I don't know how resolve it....

**Comment by ChrisPhillips-cminion** [comment]
I believe this is a k8s issue, i have been trying to diagnose this for a week, glad to finally see someone else having this. Which version of k8s are you on?

**Comment by ckcd** [comment]
In my opinion, the road from pod(coredns) to service(10.96.0.1) is unreachable, which means your `calico` has some problem.

you can do some simple tests to ensure this, such as `telnet 10.96.0.1 443`

**Comment by nabheet** [comment]
I am having this same problem too on flannel. I am not sure how to resolve it.

**Comment by ChrisPhillips-cminion** [comment]
I blogged how i fixed it here
https://medium.com/@cminion/quicknote-kubernetes-networking-issues-78f1e0d06e12
 
 
 
 
----- Original message -----From: Nabheet Sandhu <notifications@github.com>To: coredns/coredns <coredns@noreply.github.com>Cc: ChrisPhillips-cminion <chris.phillips@uk.ibm.com>, Comment <comment@noreply.github.com>Subject: Re: [coredns/coredns] my coredns is always restart! (#2325)Date: Sun, Dec 2, 2018 12:30 AM 
I am having this same problem too on flannel. I am not sure how to resolve it.
—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread. 
 Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

**Comment by liaoqiArno** [comment]
> I am having this same problem too on flannel. I am not sure how to resolve it.

I think you should make sure where is the network plugin, If it's not on master,caused coredns always restart.

**Comment by nabheet** [comment]
Thank you for replying. I actually resolved the issue. I was not following the instructions for flannel precisely by not setting the pod-cidr while initializing the k8s master. 

`kubeadm init --pod-network-cidr=10.244.0.0/16`

It wasn't clear to me that Flannel only works with that cidr above.

My issue is resolved.

**Comment by SnakeHacker** [comment]
Ubuntu 16.04
1. add dns-nameservers 8.8.8.8 to /etc/network/interfaces
2. restart node
since defalut dns is 127.0.1.1( cat /etc/resolv.conf)

**Comment by edisonan** [comment]
how do you fix it?

**Comment by p00ryasa** [comment]
> telnet 10.96.0.1 443

Unable to connect to remote host: No route to host

**Comment by chrisohaver** [comment]
@pmehdinejad, assuming you did the telnet command from a pod (and not from a node), then this suggests an issue with the network addon (`flannel`, based on your posts in other issues)

**Comment by laith-leo** [comment]
> Thank you for replying. I actually resolved the issue. I was not following the instructions for flannel precisely by not setting the pod-cidr while initializing the k8s master.
> 
> `kubeadm init --pod-network-cidr=10.244.0.0/16`
> 
> It wasn't clear to me that Flannel only works with that cidr above.
> 
> My issue is resolved.

It is weird, why it only works with 10.244.0.0 network?

**Comment by nabheet** [comment]
I think it is because of this https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L127. You can change that value to match your needs.

**Comment by boncaitp** [comment]
> I believe this is a k8s issue, i have been trying to diagnose this for a week, glad to finally see someone else having this. Which version of k8s are you on?

1.8.6

**Comment by Davidrjx** [comment]
i think node iptables rule is root cause

**Comment by liaoqiArno** [comment]
> i think node iptables rule is root cause

I found that  the network plugin pod must install on the master. the mean of it , add kubeadm join node after  network plugin.

**Comment by Inv0k-er** [comment]
> I found that the network plugin po

Can you describe your answer. I had that problem and I dont know how to resolv.

**Comment by liaoqiArno** [comment]
> > I found that the network plugin po
> 
> Can you describe your answer. I had that problem and I dont know how to resolv.

You just keep calico pod on your master node.

**Comment by lnto3408** [comment]
I'd like to share my experience when the coredns keep restarting. 
I occurred the issue when I faced below:
1. network issue between master node to worker node
-> this case, you may fix the network issue first. 

2. DNS issues, if the node doen't have a nameserver or the nameserver cannot be reachable, then the coredns keep restarting

3. I also applied the different IP subnet for CIDR like below:

` kubeadm init --pod-network-cidr=10.144.0.0/16`

and I applied flannel (for more details https://github.com/coreos/flannel) 
The flannel yaml file contains net-conf.json part which configured the default network for 10.244.0.0/16 and I fixed the issue after modifying the network as I configured 10.144.0.0/16 like below:


  net-conf.json: |```

    {
      "Network": "10.144.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
```

and save it and apply 

`kubectl apply -f kube-flannel.yml`



```
$kubectl get pod -n kube-system
NAME                              READY   STATUS    RESTARTS   AGE
coredns-5d4dd4b4db-275hk          1/1     Running   150        10h
```

finally starting to work. 

I hope you can fix the issues using my experience.

thanks

**Comment by laurelgithub** [comment]
> I am having this same problem too on flannel. I am not sure how to resolve it.

when u init , use 'kubeadm init ...' without --pod-network-cidr=xxx ? and the pod's address is the same as machine's address
