### ISSUE TITLE
CoreDNS caches out-of-date k8s dns results 

### ISSUE THREAD

**Issue by wavezhang** [coredns/coredns#2327]
CoreDNS version：
 
`1.1.3
`

Corefile:
```
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           transfer 127.0.0.1
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }
```
I'm using coredns as dns service for k8s, when I recreate svc/pod or pod,  coredns cache plugin will cache NXDOMAIN reply even though svc/pod is alreay created.

**Comment by wavezhang** [comment]
A possible solution is， CoreDNS cache plugin use k8s api to watch svc/pod changes, when changes detected, remove corresponds cache items if exists.

**Comment by erikandLambo** [comment]
I don't know anything your talking about but can I help somehow

**Comment by wavezhang** [comment]
@yongtang

**Comment by chrisohaver** [comment]
Kubernetes plugin keeps it's own local store of objects that are updated when the objects change (in a sense, it keeps its own cache).

So, I think you can achieve what you want by disabling the cache plugin for kubernetes entries (i.e. `cluster.local` zone).  You can do this by splitting the config into two sections, and not including the cache plugin for the `cluster.local` zone... something like...

```
    cluster.local:53 in-addr.arpa:53 ip6.arpa:53 {
        errors
        kubernetes . {
           pods insecure
           transfer 127.0.0.1
           upstream
        }
    }
    
    .:53 {
        errors
        proxy . /etc/resolv.conf
        cache 30
        prometheus :9153
        health
    }
```

**Comment by chrisohaver** [comment]
Actually - I think the example I gave wont work for reverse lookups of IPs that are not in the cluster.

**Comment by yongtang** [comment]
I think a separate channel monitoring the changes in the source k8s api might help in this case.

**Comment by chrisohaver** [comment]
> I think a separate channel monitoring the changes in the source k8s api might help in this case.

Since kubernetes plugin keeps its own cache - there is little/no benefit of also keeping it in the cache plugin.  This plays out in performance testing.  So, IMO, disabling caching for the k8s zones is the simplest most practical approach.

**Comment by chrisohaver** [comment]
To get the above example to work for reverse lookups of IPs that are not in the cluster, you'd need to make the reverse zones specific to your actual Pod/Service IP ranges... e.g.... if cidrs are 10.96.0.0/16 and 192.168.0.0/16 for services/pods ...

```
    cluster.local:53 96.10.in-addr.arpa:53 168.192.in-addr.arpa:53 {

```

**Comment by yongtang** [comment]
May have to take a look at the k8s plugin. Will it monitor the changes from api out-of-band?

**Comment by chrisohaver** [comment]
> May have to take a look at the k8s plugin. Will it monitor the changes from api out-of-band?

Yes, it already does, and it updates a local "cache" in the k8s plugin (k8s client store).  So, you should be able to disable cache plugin for k8s zones with negligible performance penalty.

**Comment by yongtang** [comment]
@wavezhang Can you disable the cache plugin and see if it resolves the issue?

**Comment by wavezhang** [comment]
Problem fixed using following config, thx
```
    cluster.local:53 in-addr.arpa:53 ip6.arpa:53 {
        errors
        kubernetes cluster.local {
           pods insecure
           transfer 127.0.0.1
           upstream
        }
    }
    
    .:53 {
        errors
        proxy . /etc/resolv.conf
        cache 30
        prometheus :9153
        health
    }
```
