### ISSUE TITLE
releasing CoreDNS

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#233]
I need/want some script that make releasing super-easy.
- tag master with version+1
- create zip/tar (github can do this)
- generate release notes - highlevel ones and git log attached (or something)
- announce

**Comment by aledbf** [comment]
@miekg maybe https://github.com/progrium/gh-release can help

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] releasing CoreD..." ]

> @miekg maybe https://github.com/progrium/gh-release can help

oh, that is nice and handles a large chunk of the dedious work. It also tags
automatically. Still ponder about a changelog, but leaning towards "don't give
a shit, check git" and just add a few lines that hightlight the release.
(which may or may not end up in some file in Git)

**Comment by mrichmon** [comment]
I've wondered about creating a file `coremain/version.go` that contains:

```
package coremain
const coreVersion = "001"
```

Or contains:

```
package coremain

const coreName    = "CoreDNS"
const coreVersion = "001"
const serverType  = "dns"
```

This might simplify the release script that you are suggesting.

**Comment by miekg** [comment]
Yes that makes sense. And then have the script fix the version when you
release it.

**Comment by miekg** [comment]
Just looking at Caddy (again, and why not?), they have _extensive_ changelogs in the form of blog posts https://caddyserver.com/blog/caddy-0_9-released, which is something I like because it's external from you repo. This would boil down releasing to
1) up version (automatically find last tag, up version from there?)
2) commit
3) gh-release <something> <something>
4) write blog ... on miek.nl (for now?) or coredns.io?

**Comment by miekg** [comment]
CoreDNS-001 has been released. Release process is codified in Make.release (and comments in that file)
