### ISSUE TITLE
NXDOMAIN not served when using wildcards

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2334]
I'm running into the issue that I expected CoreDNS to return with NXDOMAIN on a TXT record that doesn't exist in the special case a wildcard A record exists on the parent zone.
Am I missing something form the DNS spec and is this just intended behaviour?

CoreDNS version
```
1.2.6
```

Corefile
```
.:5354 {
  file /zones/example.test example.test {
    transfer to *
  }
  cache
  forward . 8.8.8.8
  errors stdout
  log
}
```

example.test
```
@                   3600 IN SOA     ns.example.com. domains.example.com. (
                                      2017101010   ; serial
                                      5m           ; refresh
                                      5m           ; retry
                                      1w           ; expire
                                      12h    )     ; minimum

@                  86400 IN NS      ns.example.net.
@                  86400 IN NS      ns.example.nl.


*.example.test.   IN A 127.0.0.1
_record._.example.test. IN TXT "some record"
```

AXFR
```
example.test.		5	IN	SOA	ns.example.com. domains.example.com. 2017101010 300 300 604800 43200
example.test.		5	IN	NS	ns.example.net.
example.test.		5	IN	NS	ns.example.nl.
*.example.test.		5	IN	A	127.0.0.1
_record._.example.test.	5	IN	TXT	"some record"
example.test.		5	IN	SOA	ns.example.com. domains.example.com. 2017101010 300 300 604800 43200
```

dig random.example.test -> NOERROR
dig \_record.\_.example.test -> NOERROR
dig \_record.random.example.test -> NOERROR (expected NXDOMAIN)

**Comment by erikandLambo** [comment]
I think someone who knows programming got into my network and did this mess

**Comment by miekg** [comment]
`dig _record.random.example.test -> NOERROR (expected NXDOMAIN)`

matches the wildcard and wildcards extend to the entire tree, meaning this name exists. IIRC this is how it should work, but I have to re-read the relevant RFCs again to make sure.

/label: question
/label: dns

**Comment by stp-ip** [comment]
For a CNAME wildcard I think this would be correct. I thought A and AAAA records would be different so.

**Comment by miekg** [comment]
Wildcards apply to names, not types.

**Comment by chrisohaver** [comment]
Reading over RFC 4592 again ... Wildcards only match one segment each.
i.e. `_record.random.example.test` should not match `*.example.test `, but would match `*.*.example.test `

excerpt ...

```
The following responses would not be synthesized from any of the
   wildcards in the zone: 

[other examples removed]

QNAME=ghost.*.example., QTYPE=MX, QCLASS=IN
           because *.example. exists

   The final example highlights one common misconception about
   wildcards.  A wildcard "blocks itself" in the sense that a wildcard
   does not match its own subdomains.  That is, "*.example."  does not
   match all names in the "example." zone; it fails to match the names
   below "*.example.". To cover names under "*.example.", another
   wildcard domain name is needed--"*.*.example."--which covers all but
   its own subdomains.
```

**Comment by chrisohaver** [comment]
entire context...
https://tools.ietf.org/html/rfc4592#section-2.2.1

**Comment by miekg** [comment]
From the same section:

      QNAME=foo.bar.example. QTYPE=TXT, QCLASS=IN
           the answer will be "foo.bar.example. IN TXT ..."
           because bar.example. does not exist, but the wildcard
           does.

`*.example.               3600     TXT   "this is a wildcard"`

matches the wildcard, and the type exist, so a normal reply.

**Comment by stp-ip** [comment]
Thanks for clarifying. Was testing other implementations and that also confirmed it.
Weird but correct.

**Comment by miekg** [comment]
A name under a wildcard should also work. Believe file plugin has tests for
this.

**Comment by stp-ip** [comment]
Yeah that works. It was just the hiccup that I expected a NXDOMAIN, but instead it's NOERROR and an empty record as far as my tests and the RFC go.
