### ISSUE TITLE
DNS Privacy: Implement Support for RFC 7858, DNSCurve, or DNSCrypt

### ISSUE THREAD

**Issue by paragonie-scott** [coredns/coredns#234]
https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt

It would be really awesome if we could use DNSCurve and/or DNSCrypt with CoreDNS, in the same way that Caddy provides TLS by default.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] DNSCurve / DNSCrypt..." ]

> https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt
> 
> It would be really awesome if we could use DNSCurve and/or DNSCrypt with CoreDNS, in the same way that Caddy provides TLS by default.

yes...

except that TLS is an IETF standard and well, DNSCurve, isn't. I think reason
effort voor DNS over HTTPS make more sense.

Having said that, a middleware (or proxy patch) to support DNSCurve is welcome.

/Miek

## 

Miek Gieben

**Comment by paragonie-scott** [comment]
DNS over TLS, you mean? :)

If RFC 7858 is supported, this is an adequate solution in my mind.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] DNSCurve / DNSC..." ]

> DNS over TLS, you mean? :)

Yes :-)

> If RFC 7858 is supported, this is an adequate solution in my mind.

It's not, but I want to see it supported, so it will happen eventually.

I also like `dns.google.com`, which is HTTPS + json, bad sadly not a standard
either.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
Nobody is working on this, nor is anythng planned.

**Comment by johnbelamaric** [comment]
#511 also covers the same use case, just with a different protocol.
