### ISSUE TITLE
Unexpected behaviour of logging settings

### ISSUE THREAD

**Issue by argais** [coredns/coredns#2340]
CoreDNS 1.1.3 and 1.2.6 (tested both).

I'm seeing unexpected behaviour when setting logs to only denial/errors, it might be me misunderstanding the settings, but I can't really tell from the docs at this point.

Expected:
Only errors and denials in logs (like SERVFAILs, NXDOMAINs...)

Actual result:
Errors + denials + a lot of NOERROR calls.

Default of log all was way too much, so I changed `log` to

```
      log . {
        class denial error
      }
```

But I still see a bunch of log entries for A, AAAA records for stuff on the search path.

This is a k8s 1.8 cluster deployed with kops.

Corefile:

```
    .:53 {
      errors
      log . {
        class denial error
      }
      health
      kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods verified
          upstream
          fallthrough in-addr.arpa ip6.arpa
      }
      autopath @kubernetes
      prometheus 0.0.0.0:9153

      # forward everything else to the aws vpc dns endpoint
      proxy . 10.143.0.2

      cache {
        success 10000
        denial 1024 10
      }
      nsid
      reload
    }
```

A newly created pod gets this resolv.conf 

```
/ # cat /etc/resolv.conf
nameserver 100.64.0.10
search default.svc.cluster.local svc.cluster.local cluster.local ec2.internal
options ndots:5
```
(btw if there is any way, that isn't changing the podspec, to change those ndots I'd appreciate a tip, no idea where the 5 is coming from, its not on the node...)

Some log entries
```
[coredns-6f8c45d8b7-tngh5] 2018-11-27T16:25:26.705Z [INFO] 100.111.182.65:58546 - 48925 "AAAA IN addon-kube-state-metrics.kube-system.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd,ra 165 0.000205336s
[coredns-6f8c45d8b7-tngh5] 2018-11-27T16:25:34.534Z [INFO] 100.124.40.132:36798 - 44983 "AAAA IN autoscaling.us-east-1.amazonaws.com.kube-system.svc.cluster.local. udp 83 false 512" NOERROR qr,rd,ra 186 0.002225558s
[coredns-6f8c45d8b7-tngh5] 2018-11-27T16:25:43.291Z [INFO] 100.111.182.65:58300 - 61920 "AAAA IN addon-kube-state-metrics.kube-system.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd,ra 165 0.000241365s
```
If they're NOERROR they shouldnt be showing here right?

From a test pod a query to the A record (e.g. / # host -t AAAA addon-kube-state-metrics.kube-system.svc.cluster.local
addon-kube-state-metrics.kube-system.svc.cluster.local.default.svc.cluster.local has no AAAA record) returns the ip just fine, to the AAAA it says there is no record (expected)

```
/ # host -t AAAA addon-kube-state-metrics.kube-system.svc.cluster.local
addon-kube-state-metrics.kube-system.svc.cluster.local.default.svc.cluster.local has no AAAA record
```
but the logs still log the NOERROR :/ if there is no record shouldnt this be an NXDOMAIN, or something else?

is there any way I can have these kind of queries out of my logs?

right now its a test environment, so I can fiddle with it, but once I move this to production with a couple thousand pods and an absurd load, my logging servers are going to blow with these extra entries...

please let me know if I can provide any other information, or try anything else, like I said, right now its a testing environment :) 

cheers,

fernando.

**Comment by fturib** [comment]
From the code perspective, the class `denial` correspond to NXDOMAIN but also NODATA which means a reply NOERROR with no data provided.

That is the case if you are authoritative for one name on one type, but there is no entry for another type.

I think in your case, 
you can reply "A addon-kube-state-metrics.kube-system.svc.cluster.local" with an IP
but "AAAA addon-kube-state-metrics.kube-system.svc.cluster.local" will have no IP -> it is a NOERROR with no data replied.

To get rid of these NODATA that show up as NOERROR, you would have to remote `denial` from your log options. 
In that case you will not log the NXDOMAIN

**Comment by argais** [comment]
Thanks @fturib this makes sense to me, I'll update my core file to remove logging for the denial class then.

fernando.
