### ISSUE TITLE
plugin/cache: prefetch for special domain

### ISSUE THREAD

**Issue by ckcd** [coredns/coredns#2343]
Hi,

I'm using coredns 1.2.6 in k8s 1.9, and there are some important domains (e.g. mycompany.com) in my cluster, these domains are also sensitive that cannot fail during dns request. So I want to make the dns-items of these important domains always in cache.

So i consider the `prefetch`. But as i found, the prefetch only using `AMOUNT` `DURATION` `PERCENTAGE` to describe target as show in below, but can not set special domain with its name. which means only the domain that be request frequently can trigger  `prefetch`, and if some domain is important but not frequent enough, it can not trigger `prefetch`.

```
cache [TTL] [ZONES...] {
    success CAPACITY [TTL] [MINTTL]
    denial CAPACITY [TTL] [MINTTL]
    prefetch AMOUNT [[DURATION] [PERCENTAGE%]]
}
```
> `prefetch` will prefetch popular items when they are about to be expunged from the cache. Popular means AMOUNT queries have been seen with no gaps of DURATION or more between them. DURATION defaults to 1m. Prefetching will happen when the TTL drops below PERCENTAGE, which defaults to 10%, or latest 1 second before TTL expiration. Values should be in the range [10%, 90%]. Note the percent sign is mandatory. PERCENTAGE is treated as an `int`.

So I was considering that **if it's necessary** to add a feature for `prefetch` to support assign special domain by name. or it's just a unusual feature?

please consider that and give me some advise, if we all think that it's necessary, i can do some support and give a PR.

thanks !!!

**Comment by miekg** [comment]
I don't see how some domain can be more important than other resolve from a DNS perspective?

If you really have this requirement I'm very curious at your local DNS setup to make this happen.

> are also sensitive that cannot fail during dns request

what's your SLO? How do you measure the SLI? "Cannot fail" is a pipe dream.

**Comment by ckcd** [comment]
@miekg  thanks for your suggestion,

actually, in my k8s cluster, the coredns setup is normal, but because of some reason other than coredns, such as stability of upstream, or packets lost of iptables, the dns request in cluster cannot be 100% success, which is normal in my opinion because nothing SLA canbe 100%, but some users in the cluster cannot tolerate even one dns request fail (maybe there client codes has no retry or what ever).

So this is the situation, i am confused ... T_T, for now, i has a workaround that using a special client to query these important domain to coredns frequently, so that these dns-items canbe always in cache.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/cache:..." ]
>@miekg  thanks for your suggestion,
>actually, in my k8s cluster, the coredns setup is normal, but because of some reason other than coredns, such as stability of upstream, or packets lost of iptables, the dns request in cluster cannot be 100% success, which is normal in my opinion because nothing SLA canbe 100%, but some users in the cluster cannot tolerate even one dns request fail (maybe there client codes has no retry or what ever).
>So this is the situation, i am confused ... T_T, for now, i has a workaround that using a special client to query these important domain to coredns frequently, so that these dns-items canbe always in cache.

Can you put in a host file on disk and use the *hosts* plugin?

**Comment by ckcd** [comment]
> Can you put in a host file on disk and use the *hosts* plugin?

yes, i consider that method, i also has another idea that insert hosts into client pod. but both methods can not handle the change of domain's ip address.

**Comment by miekg** [comment]
If you can not handle a DNS interruption/latency hit for this important you
have more important architectural issues in your system. Just making cache
fetch this one domain isn't going to improve that situation.
