### ISSUE TITLE
plugin/route53: can't handle wildcard names properly

### ISSUE THREAD

**Issue by dilyevsky** [coredns/coredns#2345]
I noticed names like `*.example.com` don't work even though they are supported by the underlying plugin code (`file` plugin). Turns out AWS api actually returns stars double-escaped. Here a snippet from aws cli output:

```
 {
            "ResourceRecords": [
                {
                    "Value": "docker.example.com"
                }
            ], 
            "Type": "CNAME", 
            "Name": "\\052.docker.example.com.", 
            "TTL": 300
        }, 
```

Need to look out for this and un-escape the star.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] [route53]: can't ..." ]
>I noticed names like `*.example.com` don't work even though they are supported by the underlying plugin code (`file` plugin). Turns out AWS api actually returns stars double-escaped. Here a snippet from aws cli output:
>
>```
> {
>            "ResourceRecords": [
>                {
>                    "Value": "docker.example.com"
>                }
>            ],
>            "Type": "CNAME",
>            "Name": "\\052.example.com.",
>            "TTL": 300
>        },
>```
>
>Need to look out for this and un-escape the star.

Wow. Does Amazon actually claim this is supported? wildcard are tricky no matter 
what backend

/Miek

--
Miek Gieben

**Comment by dilyevsky** [comment]
Yes but only if asterisk is the leftmost label of a record - https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html#domain-name-format-asterisk

> wildcard are tricky no matter what backend

Yeah they are pretty messy. Luckily r53 is limited enough that it should be covered by existing code in `plugin/file`.
