### ISSUE TITLE
Custom DNS Entries For Kubernetes using rewrite not working always

### ISSUE THREAD

**Issue by dorsany** [coredns/coredns#2347]
**Issue**:
We are trying to implement secure communication (https) between our pods (containers) with our CA certificate (we have purchased one) inside our kubernetes cluster.

**What we need**:
So In order to solve our issue, we are trying to set our core dns to resolve custom A records with service discovery. In another words, I need that 1 container will be resolvable by domain that I will choose to another domain (different services)

**What we expect**:
We expect that other domains (not just my-namespace.svc.cluster.local) will be resolvable:
from _inside_ the apigw container: ```ping api.my.domain```
This should return the ip of the ```api``` container.

**How I tried to solve**:
So we tried to use the ```rewrite``` with the following ```ConfigMap``` file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite name regex (.*)\.my\.domain {1}.default.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

**Results**:
This bring some wired results:
for ```curl``` or ```wget``` is working from the apigw to the api. but for ```ping``` or especially ```dns.js``` in our node js is not working.

We are getting the node js error:
```
Nov 29 07:38:18 apigw gateway[36]: warn: [EG:policy]  Error: getaddrinfo ENOTFOUND api.my.domain api.my.domain:5443
Nov 29 07:38:18 apigwgateway[36]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
Nov 29 07:38:21 apigwnode: gethostby*.getanswer: asked for "api.my.domain.default.svc.cluster.local", got "api.default.svc.cluster.local"
Nov 29 07:38:26 apigwnode: gethostby*.getanswer: asked for "api.my.domain.default.svc.cluster.local", got "api.default.svc.cluster.local"
```
looks like ```dns.js``` library can't work with my ```rewrite``` rule while other Apps like ```curl``` can.

I also tried to add ```$``` in the rewrite: ```rewrite name regex (.*)\.my\.domain$ {1}.default.svc.cluster.local```
but it cause to the curl and wget not to work either.

any idea of how to solve my issue? 
is the ```rewrite``` rule is not right?
maybe a different way? like create another zone for ```my.domain``` and maybe sync it some how from the default zone (in my case ```default.svc.cluster.local```)

**Versions**:

kubectl:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

kubeadm
```
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:54:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
cni version:
```
v0.10.0-s390x
#using: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

os:
```
Ubuntu 18.04.1 LTS
```

FYI - Coredns is already builtin in the version above

related articles:
https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/
https://github.com/coredns/coredns/tree/master/plugin/rewrite
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
https://github.com/kubernetes/kubernetes/issues/39792

**Comment by chrisohaver** [comment]
Looks like you need to also do a _response_ rewrite.  Some clients don't like it when the answer they get contains a question that does not match the question they asked.  The response rewrite can alter the question in the response, so it matches the original request. IMO _rewrite_ should just do this for you automatically for all rewrites, but alas it does not.

See the section on _Response Rewrites_ in the docs https://coredns.io/plugins/rewrite/
In your config, this would looks something like...

```
    rewrite stop {
        name regex (.*)\.my\.domain {1}.default.svc.cluster.local
        answer name (.*)\.default\.svc\.cluster\.local {1}.my.domain 
    }
```

**Comment by dorsany** [comment]
Hello @chrisohaver ,
I have tried replace my ```rewrite``` rule with your new ```rewrite``` rule. but now I don't get any more resolve to my costume domain ```my.domain```

nslookup output results after the change:
```
root@apigateway:/home/apigateway# nslookup
> apigateway.default.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   apigateway.default.svc.cluster.local
Address: 10.244.1.2
>
>
>
>
>
> apigateway.my.domain
Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find apigateway.my.domain: NXDOMAIN

```

**Comment by chrisohaver** [comment]
The syntax may be off a bit - I didn't test it (hence "something like").

**Comment by chrisohaver** [comment]
I tested it, and it works for me as written...

```
CTOs-MacBook-Pro:~ cohaver$ dig @localhost -p5399 kubernetes.my.domain.

; <<>> DiG 9.10.6 <<>> @localhost -p5399 kubernetes.my.domain.
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30223
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kubernetes.my.domain.		IN	A

;; ANSWER SECTION:
kubernetes.my.domain.	5	IN	A	10.0.0.1

;; Query time: 0 msec
;; SERVER: ::1#5399(::1)
;; WHEN: Thu Nov 29 11:00:38 EST 2018
;; MSG SIZE  rcvd: 74
```

**Comment by dorsany** [comment]
with this configuration:
```
  Corefile: |
    .:53 {
        errors
        health
        rewrite stop {
           name regex (.*)\.my\.domain {1}.default.svc.cluster.local
           answer name (.*)\.default\.svc\.cluster\.local {1}.my.domain
        }        
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
        loadbalance
    }
```


I can get the following results:
```
root@apigateway:/home/apigateway# dig @10.96.0.10 -p53 apigateway.my.domain

; <<>> DiG 9.9.5-9+deb8u16-Debian <<>> @10.96.0.10 -p53 apigateway.my.domain
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39269
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;apigateway.my.domain.             IN      A

;; ANSWER SECTION:
apigateway.my.domain.      5       IN      A       10.244.1.8

;; Query time: 1 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Thu Nov 29 19:10:20 IST 2018
;; MSG SIZE  rcvd: 79


root@apigateway:/home/apigateway# ping apigateway.my.domain
ping: unknown host apigateway.my.domain

root@apigateway:/home/apigateway# nslookup
> apigateway.my.domain
Server:         10.96.0.10
Address:        10.96.0.10#53

Non-authoritative answer:
Name:   apigateway.my.domain
Address: 10.244.1.8

```

and my node js app still getting the errors:
```
Nov 29 19:17:43 apigateway node: gethostby*.getanswer: asked for "apigateway.my.domain.default.svc.cluster.local", got "apigateway.my.domain"
Nov 29 19:17:43 apigateway gateway[35]: [EG:db] error: Error in Redis: Error: getaddrinfo ENOTFOUND apigateway.my.domain apigateway.my.domain:6379
Nov 29 19:17:45 apigateway node: gethostby*.getanswer: asked for "apigateway.my.domain.default.svc.cluster.local", got "apigateway.my.domain"
Nov 29 19:17:45 apigateway gateway[35]: [EG:db] error: Error in Redis: Error: getaddrinfo ENOTFOUND apigateway.my.domain apigateway.my.domain:6379
Nov 29 19:17:45 apigateway node: gethostby*.getanswer: asked for "api.my.domain.default.svc.cluster.local", got "api.my.domain"
```

same results if I also adding additional ```rewrite``` rule to the coredns configmap:
```rewrite name regex (.*)\.my\.domain {1}.default.svc.cluster.local```

**Comment by chrisohaver** [comment]
Try anchoring the regex matches to the end with `\.$`... the rewrite is matching the search domains, and doing the rewrite incorrectly ...

e.g.

```
        rewrite stop {
           name regex (.*)\.my\.domain\.$ {1}.default.svc.cluster.local
           answer name (.*)\.default\.svc\.cluster\.local\.$ {1}.my.domain
        }        

```

**Comment by johnbelamaric** [comment]
Add "log" to your Corefile, then let us know what the CoreDNS log look like
when you try the ping. What does resolv.conf look like on that container?

**Comment by johnbelamaric** [comment]
Ahh...right.

**Comment by dorsany** [comment]
working !!!
Thank you so much..

Final coredns configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite stop {
           name regex (.*)\.my\.domain\.$ {1}.default.svc.cluster.local
           answer name (.*)\.default\.svc\.cluster\.local\.$ {1}.my.domain
        }          
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
        loadbalance
    }
```

**Comment by skadem07** [comment]
how do we ignore a string "bla"
for example if i'm trying for set of records
testinternalau.prod.net -> au-test-internal1.prod.net
testinternalmx.prod.net -> mx-test-internal1.prod.net 
testinternalbla.prod.net -> ca-test-internal1.prod.net

I want to ignore only this `testinternalbla.prod.net` and include other 2.

        rewrite name regex testinternal(.*)\.prod\.net {1}-test-internal1.prod.net

**Comment by chrisohaver** [comment]
@skadem07, Not ideal, but you could put a "change nothing" rewrite rule for the name you want to exclude before the other rule. e.g. ...

```
rewrite name exact testinternabla.prod.net. testinternabla.prod.net.
rewrite name regex testinternal(.*)\.prod\.net\. {1}-test-internal1.prod.net.
```

edit: no need to make the first rule regex.

**Comment by skadem07** [comment]
> @skadem07, Not ideal, but you could put a "change nothing" rewrite rule for the name you want to exclude before the other rule. e.g. ...
> 
> ```
> rewrite name exact testinternabla.prod.net. testinternabla.prod.net.
> rewrite name regex testinternal(.*)\.prod\.net\. {1}-test-internal1.prod.net.
> ```
> 
> edit: no need to make the first rule regex.

The reason i want to ignore , because i need to add another rule for `testinternalbla.prod.net -> ca-test-internal1.prod.net`

would this work?
```
rewrite name regex testinternal^((?!bla).)*\.prod\.net\$ {1}-test-internal1.prod.net
rewrite substring testinternabla.prod.net ca-test-internal1.prod.net
```

**Comment by chrisohaver** [comment]
No, Go regex doesn't support look aheads ... but this simpler config would work...

```
rewrite name exact testinternabla.prod.net. ca-test-internal1.prod.net.
rewrite name regex testinternal(.*)\.prod\.net\. {1}-test-internal1.prod.net.
```

**Comment by skadem07** [comment]
So don't they overlap?does the first take precedence?

**Comment by chrisohaver** [comment]
> So don't they overlap?does the first take precedence?

Yes, according to: https://github.com/coredns/coredns/blob/master/plugin/rewrite/README.md#syntax

Also, you should add beginning/end anchors to your regex string, otherwise it could match the middle of a longer domain.
