### ISSUE TITLE
Kubernetes Expose External Load Balancer IPs

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#2349]
Issue to collaboratively discuss possible implementations for Exposing External Load Balancer IPs in K8s.

related feature requests:
#1851
kubernetes/dns#242

**Comment by chrisohaver** [comment]
**1) Separate plugin**:  make it a Separate plugin, and move code duplicated/shared with kubernetes plugin to shared pkg. (this approach is rejected, see #2337)

**2) Minimal lines of code**: Don't do it as a new plugin, add it as an option to the existing kubernetes plugin.  see example in https://github.com/coredns/coredns/issues/1851#issuecomment-431501196

**3) inter-plugin dependent**: make it a separate plugin, that directly includes parts of the existing kubernetes plugin.  shared code stays in kubernetes dir instead of moving to pkg.  would probably be similar in size to 1, just organized differently.

**4) Fake plugin approach**:  add the functionality to the existing k8s plugin, but expose the option via another plugin that does nothing except store options that the existing k8s plugin references.  In think this is ugly as hell, but it does present itself to the user as a separate plugin, and has minimal lines of code.

Other ideas?

**Comment by chrisohaver** [comment]
@johnbelamaric @miekg

**Comment by chrisohaver** [comment]
FWIW, I prefer 2, doing this in the kubernetes plugin. This was my original inclination.  It's much simpler.

**Comment by miekg** [comment]
Yeah. I think your right in that assessment.

**Comment by chrisohaver** [comment]
> Yeah. I think your right in that assessment.

Cool, @johnbelamaric if you are OK with it not being a separate plugin, then I can whip this out very quickly, probably in time for kube-con.

**Comment by johnbelamaric** [comment]
Yes, I am OK with that. I would expect then that there would be two
recommended deployment models:

1) All-in-one: Same CoreDNS instances handle cluster DNS that handle
external resolution.
2) Segregated: Run a separate CoreDNS for the external domains, and don't
include the cluster domain in the zones list for the k8s plugin.

Does #2 work? I mean, do we make assumptions about the zones we are
handling being cluster domain?

**Comment by chrisohaver** [comment]
both should work.  The existing code can be adapted.
I plan to add a single option called external... `external zone [zone...]`
It will define which zones will be used for exposing external IPs.
Those zones must be in the plugin's defined zones (or server block zones).
If all non-reverse zones are listed as external, then no internal records are exposed.

example: Expose only external (i.e. segregated)

```
kubernetes myzone.com in-addr.arpa ip6.arpa {
  external myzone.com
}
```

example: Expose both internal and external (i.e. all-in-one)

```
kubernetes cluster.local myzone.com in-addr.arpa ip6.arpa {
  external myzone.com
}
```

example: Expose only internal (default)

```
kubernetes cluster.local in-addr.arpa ip6.arpa
```

**Comment by johnbelamaric** [comment]
Nice! So the name will be <service-name>.myzone.com in this case? Or is the
namespace included? You know people are going to want to mess with that.

**Comment by chrisohaver** [comment]
Namespace included.  It has to be, because service name is not unique.

e.g. for service named `svc1` in namespace `ns`: `svc1.ns.example.com`

Records will be structured in the same way as #2337 did this.

_Rewrite_ could be used to inject namespace into the name (PTR records excluded).
Or _template_ could be used to create `CNAME`s... e.g. `svc1.example.com -> svc1.ns.example.com`

We can perhaps, add an option to drop the name space when only exposing one namespace (i.e. with the existing `namespace` option).
But I'd wait to see if there is a demand for it.

**Comment by miekg** [comment]
done in #2379
