### ISSUE TITLE
embed coredns in own app with subset of plugins

### ISSUE THREAD

**Issue by vtolstov** [coredns/coredns#2351]
I want to create some service that embeds coredns with some plugins and predefined config (embedded via something like go-bindata or created pragmatically) i found in godoc github.com/coredns/coredns/core/dnsserver but does not understand how to integrate it

**Comment by johnbelamaric** [comment]
Here are examples:

https://github.com/coredns/kubernetai

https://github.com/kubernetes/dns/tree/master/cmd/node-cache

**Comment by vtolstov** [comment]
thanks for help!

**Comment by vtolstov** [comment]
sorry, i'm too fast to close, now i now how to include plugins, now last question - how to configure for example bind plugin in run time (without config file)

**Comment by vtolstov** [comment]
As i see i need to invoke https://godoc.org/github.com/coredns/coredns/core/dnsserver#GetConfig, 
how to get caddy.Controller?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] embed coredns..." ]
>As i see i need to invoke https://godoc.org/github.com/coredns/coredns/core/dnsserver#GetConfig,
>how to get caddy.Controller?

By including it: 
https://github.com/coredns/example/blob/master/setup.go#L8

**Comment by vtolstov** [comment]
I see that, but it magically provided in setup function to plugins, but if i don't write plugin, but embed coredns in my app?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] embed coredns..." ]
>I see that, but it magically provided in setup function to plugins, but if i don't write plugin, but embed coredns in my app?

that doesn't change anything, because caddy is calling that setup function.

**Comment by vtolstov** [comment]
so caddy.Controller in my case can be empty struct?

**Comment by vtolstov** [comment]
if i pass empty caddy.Controller struct to GetConfig i have error:
```
anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x106f33b]

goroutine 1 [running]:
github.com/mholt/caddy.(*Controller).Context(...)
        /xxx/vendor/github.com/mholt/caddy/controller.go:109
github.com/coredns/coredns/core/dnsserver.GetConfig(0xc0004c1d30, 0x15522c0)
        /xxx/vendor/github.com/coredns/coredns/core/dnsserver/config.go:63 +0x6b
/xxx/service/coredns.Service(0x2121ce0, 0xc0000d9780, 0x4, 0x4, 0x5)
        /xxx/service/coredns/service.go:109 +0x769
main.init.6()
        /xxx/coredns.go:13 +0x63
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] embed coredns..." ]
>if i pass empty caddy.Controller struct to GetConfig i have error:
>```
>anic: runtime error: invalid memory address or nil pointer dereference
>[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x106f33b]
>
>goroutine 1 [running]:
>github.com/mholt/caddy.(*Controller).Context(...)
>        /xxx/vendor/github.com/mholt/caddy/controller.go:109
>github.com/coredns/coredns/core/dnsserver.GetConfig(0xc0004c1d30, 0x15522c0)
>        /xxx/vendor/github.com/coredns/coredns/core/dnsserver/config.go:63 +0x6b
>/xxx/service/coredns.Service(0x2121ce0, 0xc0000d9780, 0x4, 0x4, 0x5)
>        /xxx/service/coredns/service.go:109 +0x769
>main.init.6()
>        /xxx/coredns.go:13 +0x63
>```

Which is understandable. We should have some good docs on this, because more 
people might be interested.

If you're willing to help write those, I'm willing to invest some time to help 
you here.

**Comment by vtolstov** [comment]
вс, 2 дек. 2018 г., 21:04 Miek Gieben notifications@github.com:

>
> Which is understandable. We should have some good docs on this, because
> more
> people might be interested.
>
> If you're willing to help write those, I'm willing to invest some time to
> help
> you here.


I can write some docs about creating microservice using go-micro and
coredns. If that suitable.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] embed coredns..." ]
>вс, 2 дек. 2018 г., 21:04 Miek Gieben notifications@github.com:
>
>>
>> Which is understandable. We should have some good docs on this, because
>> more
>> people might be interested.
>>
>> If you're willing to help write those, I'm willing to invest some time to
>> help
>> you here.
>
>
>I can write some docs about creating microservice using go-micro and
>coredns. If that suitable.

That would be nice as a blog on coredns.io as well.

I was more thinking about using coredns as a library and how to get started with 
all that.

**Comment by vtolstov** [comment]
Ok, so for now im stuck at ability to configure coredns and plugins
programatic, without config.
If this is huge change to coredns i can embed neede config in assets, but
this not so good as first case..

вс, 2 дек. 2018 г., 21:25 Miek Gieben notifications@github.com:

**Comment by vtolstov** [comment]
> I was more thinking about using coredns as a library and how to get started with
all that.

and yes, i'm plan to use coredns as library

**Comment by johnbelamaric** [comment]
Have you considered implementing your own CaddyfileLoader and using it
instead of what is done here:
https://github.com/coredns/coredns/blob/master/coremain/run.go#L33 ?

**Comment by vtolstov** [comment]
I can implement it, but how i can pass it (you link to init function in coremain package, and function does not variable, so i can't change it). Also as i see i need to construct full file , so this is something different when expected (pass config struct) =).
But if this is only one case to embedding with own config, i'm try. But you must change confLoader to variable with default value, but in my case i can override it. Bundle config file in assets and pass []byte via my own function from assets.

**Comment by vtolstov** [comment]
simple patch, i'm not sure about moving parts from init to Run...
```diff
diff --git a/vendor/github.com/coredns/coredns/coremain/run.go b/vendor/github.com/coredns/coredns/coremain/run.go
index 63ac6f354d09..5989c6f7beef 100644
--- a/vendor/github.com/coredns/coredns/coremain/run.go
+++ b/vendor/github.com/coredns/coredns/coremain/run.go
@@ -18,6 +18,11 @@ import (
        "github.com/mholt/caddy"
 )

+var (
+       DefaultconfLoader    = confLoader
+       DefaultdefaultLoader = defaultLoader
+)
+
 func init() {
        caddy.DefaultConfigFile = "Corefile"
        caddy.Quiet = true // don't show init stuff from caddy
@@ -30,15 +35,16 @@ func init() {
        flag.BoolVar(&version, "version", false, "Show version")
        flag.BoolVar(&dnsserver.Quiet, "quiet", false, "Quiet mode (no initialization output)")

- caddy.RegisterCaddyfileLoader("flag", caddy.LoaderFunc(confLoader))
- caddy.SetDefaultCaddyfileLoader("default", caddy.LoaderFunc(defaultLoader))
-
        caddy.AppName = coreName
        caddy.AppVersion = CoreVersion
 }

 // Run is CoreDNS's main() function.
 func Run() {
+
+       caddy.RegisterCaddyfileLoader("flag", caddy.LoaderFunc(DefaultconfLoader))
+       caddy.SetDefaultCaddyfileLoader("default", caddy.LoaderFunc(DefaultdefaultLoader))
+
        caddy.TrapSignals()

        // Reset flag.CommandLine to get rid of unwanted flags for instance from glog (used in kubernetes).
```

but i still does not understand how to configure plugins at run time (or it does not possible with current api, and i need to config plugins via conf file only)

**Comment by vtolstov** [comment]
and i think that for my case and future people we need to provide only to override defaultLoader

**Comment by vtolstov** [comment]
```diff
diff --git a/vendor/github.com/coredns/coredns/coremain/run.go b/vendor/github.com/coredns/coredns/coremain/run.go
index 63ac6f354d09..f6106cab8111 100644
--- a/vendor/github.com/coredns/coredns/coremain/run.go
+++ b/vendor/github.com/coredns/coredns/coremain/run.go
@@ -18,6 +18,10 @@ import (
        "github.com/mholt/caddy"
 )

+var (
+       DefaultConfigLoader = defaultLoader
+)
+
 func init() {
        caddy.DefaultConfigFile = "Corefile"
        caddy.Quiet = true // don't show init stuff from caddy
@@ -31,7 +35,6 @@ func init() {
        flag.BoolVar(&dnsserver.Quiet, "quiet", false, "Quiet mode (no initialization output)")

        caddy.RegisterCaddyfileLoader("flag", caddy.LoaderFunc(confLoader))
- caddy.SetDefaultCaddyfileLoader("default", caddy.LoaderFunc(defaultLoader))

        caddy.AppName = coreName
        caddy.AppVersion = CoreVersion
@@ -39,6 +42,8 @@ func init() {

 // Run is CoreDNS's main() function.
 func Run() {
+       caddy.SetDefaultCaddyfileLoader("default", caddy.LoaderFunc(DefaultConfigLoader))
+
        caddy.TrapSignals()

        // Reset flag.CommandLine to get rid of unwanted flags for instance from glog (used in kubernetes).
```

**Comment by vtolstov** [comment]
also as i see, flag.Parse bring race condition if i'm use coredns as embed library. Because my service already do flag.Parse. So i need something that says that this is embed, and skip flag parsing.

**Comment by vtolstov** [comment]
@miekg sorry for noise, what do you think?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] embed coredns..." ]
>also as i see, flag.Parse bring race condition if i'm use coredns as embed library. Because my service already do flag.Parse. So i need something that says that this is embed, and skip flag parsing.

you need your own flagSet then.

**Comment by vtolstov** [comment]
this not helps with overriding by coredns log and signal handler =(

**Comment by miekg** [comment]
signal should be this: `caddy.TrapSignals()` why do you need to intercept that?
What do you want/need to do with the logging?

**Comment by vtolstov** [comment]
I have overrited default log with zap. You package override format and
logger,so before dns server started i have my format, after - you.

For signals i think that sometimes my signal handler cant get signals
because caddy. I need to check.

пт, 7 дек. 2018 г., 9:37 Miek Gieben notifications@github.com:

**Comment by vtolstov** [comment]
also coredns append own flags to my program flags, but it completely useless. What next steps to beautifully integration of coredns?

**Comment by miekg** [comment]
Flags should be made main binary only. I think we did some work there

**Comment by johnbelamaric** [comment]
Right, you should not be using coremain/run.go - instead you should create
your own equivalent.

**Comment by vtolstov** [comment]
Yes, thanks. now looks good:
```go
dnsserver.Quiet = true
dnsserver.Directives = append(dnsserver.Directives, "micro")
caddy.DefaultConfigFile = "Corefile"
caddy.Quiet = true
caddy.AppName = "org.micro.coredns"
caddy.AppVersion = "0.0.1"
caddy.SetDefaultCaddyfileLoader("default", caddy.LoaderFunc(confLoader))
corefile, err := caddy.LoadCaddyfile("dns")
if err != nil {
  return nil, err
}
instance, err := caddy.Start(corefile)
if err != nil {
  return nil, err
}
caddy.EmitEvent(caddy.InstanceStartupEvent, instance)

func confLoader(serverType string) (caddy.Input, error) {
  return caddy.CaddyfileInput{
    Contents: []byte(`
.:5353 {
  errors
  health
  micro
}
`),
    ServerTypeName: serverType,
  }, nil
}
```

**Comment by vtolstov** [comment]
@miekg @johnbelamaric how to deal with inderect dep from metrics plugin to coremain?
github.com/coredns/coredns/plugin/metrics/setup.go:
```
buildInfo.WithLabelValues(coremain.CoreVersion, coremain.GitCommit, runtime.Version()).Set(1)
```
i want to remove all calls to coremain in my embeded case

**Comment by johnbelamaric** [comment]
Probably need to separate out that version info into its own package,
upstream.

**Comment by vtolstov** [comment]
@johnbelamaric can you do that?

**Comment by johnbelamaric** [comment]
I don't think I'll have time any time soon. But I can review a PR...
