### ISSUE TITLE
plugin/route53: Throttling: Rate exceeded

### ISSUE THREAD

**Issue by mattlqx** [coredns/coredns#2353]
I have about 10 coredns daemons running with the route53 plugin setup for about 6 zones. All the daemons share the same instance profile credentials to read from Route 53. I'm seeing a good amount of `Throttling: Rate exceeded` messages in the log. Would it be difficult to make the refresh rate of the zones configurable? I don't necessarily need sub-10 second convergence of a zone and I'd like to not hammer the API and reach AWS's rate limits.

The throttling sometimes results in a daemon failing to start when it gets a 400 returned back from the API. I'd like to be able to control the rate the running daemons are refreshing zones to prevent these kinds of delayed starts as well.

I'm not entirely sure at what level AWS is rate limiting by account, by credential or something else, but I'd really not like to generate a whole new credential/user per coredns instance.

**Comment by dilyevsky** [comment]
Currently the refresh is set to `1 * time.Minute` https://github.com/coredns/coredns/blob/95c9e14dcf65a9c3b97aa1be611fae664f99f7e6/plugin/route53/route53.go#L87 but it refreshes all zones at once. Shouldn't be difficult to have it configured but I'm thinking it probably has more to do with either the number of simultaneous zones or total number of records (they are paginated at 100 by default). Could you provide the total number of records you have configured between all of those zones?

**Comment by dilyevsky** [comment]
Oh also just in case - your are using `>v1.2.3` right?

**Comment by dilyevsky** [comment]
After reading through https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests this is likely:

```
All requests
Five requests per second per AWS account. If you submit more than five requests per
second, Amazon Route 53 returns an HTTP 400 error (Bad request). The response header
also includes a Code element with a value of Throttling and a Message element with a
value of Rate exceeded.
```

**Comment by mattlqx** [comment]
Yes, v1.2.6.

I do have a fair amount of records...

Zone A  1600
Zone B  800
Zone C  100
Zone D  150

The remaining ones only have a handful.

**Comment by mattlqx** [comment]
Thanks for the info on the rate limiting. Perhaps a configurable for pagination might help also or just make it something more like 1000 or 5000? I'm not sure there's a disadvantage to doing so.

**Comment by dilyevsky** [comment]
1000 records is max that can be returned in a single call and with multiple
zones that are small it’s possible to hit this as well so I’m going to add
a ratelimiter.

**Comment by piersf** [comment]
Hello there,

Is there any update on this? We are also seeing throttling errors in the coredns logs. Is there a workaround?


Thanks

**Comment by miekg** [comment]
tentatively closing
