### ISSUE TITLE
missing changelog for all releases

### ISSUE THREAD

**Issue by nikopen** [coredns/coredns#2355]
Hi!!

I'd like to have a single changelog so I can grep through keywords of interest and easily find changes affecting these keywords.

From what I see there's currently only the Release Notes in the Wiki right?

I'm thinking of making a CHANGELOG.txt having all Release Notes appended to it for the moment. 

How does that sound?

**Comment by miekg** [comment]
The coredns.io has all release notes in the content/blog directory. They're
names coredns-version.md

**Comment by nikopen** [comment]
I'm thinking about a single file containing all release notes in this repo (coredns/coredns) as changelog.md,

it makes reviewing upgrades much simpler.

**Comment by miekg** [comment]
If you provide the automation to distill this from git logs I'm all ears. I
agree something versioned would be nice
