### ISSUE TITLE
how to catch zone transfer notification in plugin

### ISSUE THREAD

**Issue by vtolstov** [coredns/coredns#2359]
I'm try to understand plugin system in coredns, i want to do saving on zone transfers.
I understand that i can monitor ttl/refresh and init zone transfer from slave, but how can i catch zone notify from master? I found transferer interface but it for master that want notify slaves...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] how to catch zone..." ]
>I'm try to understand plugin system in coredns, i want to do saving on zone transfers.
>I understand that i can monitor ttl/refresh and init zone transfer from slave, but how can i catch zone notify from master? I found transferer interface but it for master that want notify slaves...

https://github.com/coredns/coredns/blob/master/plugin/file/notify.go

shows how to intercept a notify from within a plugin. The whole *file*'s plugin 
xfr could be copied for your use-case.

/Miek

--
Miek Gieben

**Comment by vtolstov** [comment]
thanks, i need to deeper look to file plugin.
