### ISSUE TITLE
Storage interface

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#236]
There should be some storage abstraction so that middleware shouldn't care about where to store things. Need to think about the exact interface we need for this.

For now the following things need this:
- dnssec - where to store the generated key(s) and possibly the ds(s).
- secondary - where to store the transferred zones

Also see `net/http`s `FileSystem` which has one method: `Open(string) (File, error)`
Where `File` is:

```
type File interface {
    io.Closer
    io.Reader
    io.Seeker
    Readdir(count int) ([]os.FileInfo, error)
    Stat() (os.FileInfo, error)
}
```

Anything holding us back from using _this_ interface and implementing it in a CoreDNS way?

**Comment by mrichmon** [comment]
Maybe consider a search path in this implementation. E.g. Path of [ "~/.coredns", "/etc/coredns", "/coredns" ]

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Storage interfa..." ]

> Maybe consider a search path in this implementation. E.g. Path of [ "~/.coredns", "/etc/coredns", "/coredns" ]

not sure if the added complexity is needed for this case. It primary purpose is
storing assets (which the user should not necessary see). In caddy it store the
ssl certs there, for instance.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
Has been merged, might see some subsequent changes. But good enough for now. See #242
