### ISSUE TITLE
 pull access denied for coredns, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by christrt9** [coredns/coredns#2361]
I install kubeadm and coredns can't download the image. :S 

kubeadm: 1.12.3
coredns: latest ? :) 

sudo docker pull coredns
Using default tag: latest
Error response from daemon: pull access denied for coredns, repository does not exist or may require 'docker login'

**Comment by chrisohaver** [comment]
try...
```
sudo docker pull coredns/coredns
```
