### ISSUE TITLE
Difference in handling nested specific records under wildcard zone from other DNS providers

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2365]
There seems to be a difference in answer handling between CoreDNS and other providers. Namely Google, DNSmadeEasy and Gandi were tested.

Now to my edge case:
```
* 300 IN CNAME txtd.io.
_redirect 300 IN TXT "v=txtv0;to=https://about.example.test;type=host"
_redirect._ 300 IN TXT "v=txtv0;to=https://example.test/{label1};type=host"
_redirect.test 300 IN TXT "v=txtv0;to=https://example.test/{label1};type=host"
```

dig TXT \_redirect -> works everywhere
dig TXT \_redirect.\_ -> works everywhere
dig TXT \_redirect.test -> works everywhere

dig CNAME random -> works everywhere
dig CNAME test -> works only with CoreDNS (other providers return NOERROR with the SOA)

Was reading through https://www.ietf.org/rfc/rfc1912.txt and especially section 2.7.
They don't explicitely go into the detail of nested zones so.

Not really thinking it's a bug on either case, but wanted to add it as an edge case to our issues just in case someone else runs against this difference.

Also happy for any suggestions, ideas or other RFCs that clarify this.

**Comment by miekg** [comment]
I think coredns is wrong here

**Comment by miekg** [comment]
what does bind do here? Is the wildcard on the zone level? Because that is not allowed (CNAME and other data,etc)

**Comment by stp-ip** [comment]
The wildcard is located on a zone such as `wildcard.example.com`. That should be allowed from all providers and works as expected. I would have interpreted the RFCs the same way as CoreDNS does, but we should be consistent here I think.

(unfortunate as I was relying on this working in general ^^ anyway new workaround for my test cases)

**Comment by miekg** [comment]
Can you give a full repro? I would like to fix this
