### ISSUE TITLE
CAA record using etcd backend

### ISSUE THREAD

**Issue by jremond** [coredns/coredns#2366]
Hello,

I would like to add a CAA record in my coredns server. I use the etcd backend.
All I have been able to find is :
- https://github.com/coredns/coredns/pull/2084
- https://github.com/skynetservices/skydns/issues/321

My understanding is that the etcd backend mirrors the functionnalities of skydns (that's why I looked in that repository).

Is there any restriction on adding support for this type of record ?

Thanks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] CAA record using ..." ]
>Hello,
>
>I would like to add a CAA record in my coredns server. I use the etcd backend.
>All I have been able to find is :
>- https://github.com/coredns/coredns/pull/2084
>- https://github.com/skynetservices/skydns/issues/321
>
>My understanding is that the etcd backend mirrors the functionnalities of skydns (that's why I looked in that repository).
>
>Is there any restriction on adding support for this type of record ?

Yes, it's not supported. The etcd is fairly limited in what record types it 
supports.

/plugin: etcd
/label: question

/Miek

--
Miek Gieben

**Comment by jremond** [comment]
Is this by design or if a correct implementation is provided it could be merged ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CAA record us..." ]
>Is this by design or if a correct implementation is provided it could be merged ?

This was by design, we could extend msg.Service if we want to.

**Comment by miekg** [comment]
I've come to the conclusion the current etcd plugin isn't a generic zone backend, so we can't treat it that way and adds all the RR types we need.

If we want to store all kinds of DNS data in etcd we need to new plugin.
