### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by zainal-abidin-assegaf** [coredns/coredns#2369]
I'm running coredns in coreos kubernetes v1.12.3, and i have error in journalctl :

Dec 06 16:03:04 manager-02 kube-apiserver[1665]: I1206 16:03:04.496015    1665 log.go:172] http: TLS handshake error from 10.9.38.139:34346: remote error: tls: bad certificate
Dec 06 16:03:04 manager-02 kube-apiserver[1665]: I1206 16:03:04.509167    1665 log.go:172] http: TLS handshake error from 10.9.38.139:34350: remote error: tls: bad certificate
Dec 06 16:03:04 manager-02 kube-apiserver[1665]: I1206 16:03:04.735070    1665 log.go:172] http: TLS handshake error from 10.9.38.142:49742: remote error: tls: bad certificate
Dec 06 16:03:04 manager-02 kube-apiserver[1665]: I1206 16:03:04.786983    1665 log.go:172] http: TLS handshake error from 10.9.38.135:39342: remote error: tls: bad certificate
Dec 06 16:03:05 manager-02 kube-apiserver[1665]: I1206 16:03:05.092803    1665 log.go:172] http: TLS handshake error from 10.9.38.143:47566: remote error: tls: bad certificate
Dec 06 16:03:05 manager-02 kube-apiserver[1665]: I1206 16:03:05.194854    1665 log.go:172] http: TLS handshake error from 10.9.38.137:57552: remote error: tls: bad certificate
Dec 06 16:03:05 manager-02 kube-apiserver[1665]: I1206 16:03:05.203419    1665 log.go:172] http: TLS handshake error from 10.9.38.137:57554: remote error: tls: bad certificate
Dec 06 16:03:05 manager-02 kube-apiserver[1665]: I1206 16:03:05.288622    1665 log.go:172] http: TLS handshake error from 10.9.38.140:45194: remote error: tls: bad certificate

I used docker gcr.io/google_containers/coredns:1.2.6

May be i need to create custom certificates, please let me know what kubectl secret name should i used for coredns working without TLS handshake error,

Thank you

**Comment by chrisohaver** [comment]
This looks like a general cluster issue, not specific to coredns.  It may be better to take the question to kubernetes/kubernetes.  Or, if you built your cluster using kubeadm, kubernetes/kubeadm.

**Comment by zainal-abidin-assegaf** [comment]
It's deployed in vmware vsphere 5.5,

from kubectl describe, there is coredns-token :

core@manager-01 ~ $ kubectl describe pod coredns-58fc8d8b7-dvn6l -n kube-system
Name:               coredns-58fc8d8b7-dvn6l
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               worker-001/10.9.38.134
Start Time:         Fri, 07 Dec 2018 10:09:19 +0700
Labels:             k8s-app=kube-dns
                    pod-template-hash=58fc8d8b7
Annotations:        seccomp.security.alpha.kubernetes.io/pod: docker/default
Status:             Running
IP:                 10.244.13.2
Controlled By:      ReplicaSet/coredns-58fc8d8b7
Containers:
  coredns:
    Container ID:  docker://f71526aaef027b04f9aa112704fe3aae825fa3435b8dcb45ae265b5fe286f9c2
    Image:         gcr.io/google_containers/coredns:1.2.6
    Image ID:      docker-pullable://gcr.io/google_containers/coredns@sha256:81936728011c0df9404cb70b95c17bbc8af922ec9a70d0561a5d01fefa6ffa51
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Running
      Started:      Fri, 07 Dec 2018 10:09:21 +0700
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  1000Mi
    Requests:
      cpu:        500m
      memory:     500Mi
    Liveness:     http-get http://:8080/health delay=120s timeout=5s period=30s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-6g42r (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-6g42r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-6g42r
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age    From                                  Message
  ----     ------     ----   ----                                  -------
  Normal   Scheduled  2m44s  default-scheduler                     Successfully assigned kube-system/coredns-58fc8d8b7-dvn6l to worker-001.mncplaymedia.com
  Normal   Pulled     2m42s  kubelet, worker-001.mncplaymedia.com  Container image "gcr.io/google_containers/coredns:1.2.6" already present on machine
  Normal   Created    2m42s  kubelet, worker-001  Created container
  Normal   Started    2m42s  kubelet, worker-001  Started container
  Warning  Unhealthy  20s    kubelet, worker-001  Liveness probe failed: HTTP probe failed with statuscode: 503
