### ISSUE TITLE
need docs about Corefile

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#237]
- Semantics
- Syntax (how to specify zones, multiple zones)
- Anything else
- Quick start?

**Comment by jcdickinson** [comment]
[trim]

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] need docs about..." ]

> # Development Quick Start (Windows)

Nice. I think it makes sense to make a section for this in the (almost empty)
Github wiki? You should have access.

Thanks!

**Comment by jcdickinson** [comment]
> You should have access.

Nope, no edit options on the web and I can't seem to push to .wiki.git (forking doesn't work either).

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] need docs about..." ]

> > You should have access.
> 
> Nope, no edit options on the web and I can't seem to push to .wiki.git (forking doesn't work either).

Ah, was only open to collaborators. Fixed.

**Comment by miekg** [comment]
Happening if/when we have a new website design.
