### ISSUE TITLE
plugin/forward: preserve EDNS0 (or something)

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2373]
#2328 highlighted some RFC paragraph that we may need to preserve the EDNS0 option on a request. We currently throw those away (That PR doesn't changes that but it more strict in what is allowed).

**Comment by stp-ip** [comment]
Is this still relevant? Seems like all compliance is fixed or am I missing a special case here?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>Is this still relevant? Seems like all compliance is fixed or am I missing a special case here?

It's DNS, there is probably always a corner case that will not work. For now we 
seem good to go.
