### ISSUE TITLE
coredns 1.3.0 tracking bug

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2375]
There is a nice set of fixes being committed since the 1.2.6. Time to kick out another release.

**Comment by johnbelamaric** [comment]
Yeah, I'd like to see #2356 in there if possible, I plan to introduce it at KubeCon next week.

When we get #2335 I think it warrants a 1.3, wdyt?

**Comment by miekg** [comment]
From a semver perspective it does not. We can number it whatever we like,
but there is no backwards incompatible change so the minor version does not
need changing

**Comment by johnbelamaric** [comment]
Semver is usually:

patch version = bug fixes
minor version = backwards compatible new functionality
major version = breaks backwards compat

https://semver.org/

**Comment by miekg** [comment]
TIL "new functionality"

1.3.0 it will be.
