### ISSUE TITLE
Piping in Corefile does not work

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#238]
```
% ./coredns -conf ~/Corefile
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
```

vs

```
% cat ~/Corefile | ./coredns -conf stdin
no action found for directive 'prometheus' with server type '' (missing a plugin?)
```

**Comment by yongtang** [comment]
I tried locally and it seems to be fine (with a proxy Corefile):

```
ubuntu@ubuntu:~/coredns$ sudo su
root@ubuntu:/home/ubuntu/coredns# cat Corefile 
.:53 {
    proxy . 8.8.8.8:53
    log stdout
}
root@ubuntu:/home/ubuntu/coredns# cat Corefile | ./coredns -conf stdin
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
^Croot@ubuntu:/home/ubuntu/coredns# ./coredns -conf Corefile
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
^Croot@ubuntu:/home/ubuntu/coredns# 
```

Could the issue be specific to prometheus plugin Corefile?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Piping in Coref..." ]

> I tried locally and it seems to be fine (with a proxy Corefile):
> 
> ```
> ubuntu@ubuntu:~/coredns$ sudo su
> root@ubuntu:/home/ubuntu/coredns# cat Corefile
> .:53 {
>    proxy . 8.8.8.8:53
>    log stdout
> }
> root@ubuntu:/home/ubuntu/coredns# cat Corefile | ./coredns -conf stdin
> WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
> ^Croot@ubuntu:/home/ubuntu/coredns# ./coredns -conf Corefile
> WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
> ^Croot@ubuntu:/home/ubuntu/coredns#
> ```

Indeed works:

```
% ./coredns -conf stdin << EOF
heredoc> .:53 {
heredoc> proxy . 8.8.8.8:53
heredoc> log stdout
heredoc> }
heredoc> EOF
listen tcp :53: bind: permission denied 
```

> Could the issue be specific to prometheus plugin Corefile?

unlikely, seems that fix in Caddy fixed it.

/Miek

## 

Miek Gieben
