### ISSUE TITLE
plugin/proxy: gRPC BackoffMaxDelay

### ISSUE THREAD

**Issue by inigohu** [coredns/coredns#2387]
Hi,

I need the possibility to add **BackoffMaxDelay** parameter to grpc protocol in the Proxy plugin.

- Version: 1.2.6
- Corefile:

```
. {
    health :8081
    debug
    log
    proxy . 10.5.0.6:8080 {
    	protocol grpc insecure
	}
}
```

The reason is that I want to test my backend service that is being used by the Proxy plugin. To make an e2e test, I start my backend service and make a request to coreDNS.  

The grpc client backoff delay is exponential, and the maxDelay is 2 minutes. The coreDNS proxy has a 16 seconds of *tryDuration*.

This means that if the coreDNS is running, but not my backend service, the grpc client backoff delay will increase until 2 minutes. After that, if I run my test (start backend service and make a request), I get an error because the grpc connection has not been made yet (grpc backoff delay is bigger than *tryDuration*).

Would be great to have an extra parameter for **BackoffMaxDelay**

```
{
    ...
    proxy . 10.5.0.6:8080 {
    	protocol grpc insecure 1s
	}
    ...
}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/proxy: gRP..." ]
>Hi,
>
>I need the possibility to add **BackoffMaxDelay** parameter to grpc protocol in the Proxy plugin.

i want to actually retire this plugin; one on the things holding that back is 
that the forward plugin doesnt support gRPC.

To not answer your question: I would like to see the grpc support moved to grpc 
and then think about your feature request.

/plugin: proxy
/label: enhancement
