### ISSUE TITLE
CoreDNS support for multiple Corefiles

### ISSUE THREAD

**Issue by rtheis** [coredns/coredns#2392]
This is a request for CoreDNS to support multiple Corefile `-conf` arguments.  When deploying CoreDNS in a Kubernetes clusters, the Corefile is often provided via a single `configMap` volume mount (e.g. https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/coredns).  This works well for many use cases.  However, when providing a managed service or installation, there's a desire to provide both a default Corefile along with a Corefile that may be customized by the cluster administrator.  This makes it much easier to manage changes to be pushed to the default Corefile while maintaining a file for cluster administrator customizations.

**Comment by miekg** [comment]
you can just use `import` for this: https://coredns.io/explugins/import/

**Comment by rtheis** [comment]
Sweet, I think that will do the trick.  Thanks

**Comment by rtheis** [comment]
Oh wait, this is not enabled by default which is problematic.

**Comment by miekg** [comment]
wait, what. It should

**Comment by yongtang** [comment]
I think it is enabled:
```
root@ubuntu:/go/src/github.com/coredns/coredns# ./coredns 
.:53
2018-12-14T15:47:56.363Z [INFO] CoreDNS-1.2.6
2018-12-14T15:47:56.363Z [INFO] linux/amd64, go1.11.2, fed307bf
CoreDNS-1.2.6
linux/amd64, go1.11.2, fed307bf
^C[INFO] SIGINT: Shutting down
root@ubuntu:/go/src/github.com/coredns/coredns# cat Corefile
.:53 {
  import Corefile2
  whoami
}
root@ubuntu:/go/src/github.com/coredns/coredns# cat Corefile2
errors
root@ubuntu:/go/src/github.com/coredns/coredns# 
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS suppo..." ]
>I think it is enabled:

yeah, this is a weird one, kind of a plugin, but not really.

What is not working for you?

**Comment by fturib** [comment]
The directive "import" is directly supported by Caddyfile - and the doc is pointing to the right Caddyfile source code.

I am not sure why this is describe as an external plugin. Although it is said "enabled by default".

**Comment by rtheis** [comment]
I didn't actually try the plugin but based my response on the documentation which I would say is a little confusing.  Since `import` is documented as an external plugin and such plugins have the following disclaimer: `Out of tree plugins for CoreDNS. A plugin listed here is not automatically endorsed by the CoreDNS team. Issues should be reported to respective owner(s) of the plugin.`.  I incorrectly assumed that it wasn't enabled by default.  Thanks for your help.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS suppo..." ]
>I didn't actually try the plugin but based my response on the documentation which I would say is a little confusing.  Since `import` is documented as an external plugin and such plugins have the following disclaimer: `Out of tree plugins for CoreDNS. A plugin listed here is not automatically endorsed by the CoreDNS team. Issues should be reported to respective owner(s) of the plugin.`.  I incorrectly assumed that it wasn't enabled by default.  Thanks for your help.

*technically* this is correct, but it is indeed a bit confusing.

**Comment by rtheis** [comment]
It may be helpful to clarify the doc for this.  Otherwise, this issue can be closed.  Thanks for your help.

**Comment by miekg** [comment]
this has been moved around and hopefully be made more explicit
