### ISSUE TITLE
nslookup and dig works as expected but not able to ping

### ISSUE THREAD

**Issue by praveenkumar** [coredns/coredns#2393]
I am trying to add a zone to Corefile and able to get the information using `dig` and `nslookup` command but `ping` doesn't work as expected.

```console
$ ./coredns 
tt.testing.:53
2018-12-14T14:36:48.216+05:30 [INFO] CoreDNS-1.2.6
2018-12-14T14:36:48.216+05:30 [INFO] darwin/amd64, go1.11.2, 756749c
CoreDNS-1.2.6
darwin/amd64, go1.11.2, 756749c
2018-12-14T14:36:56.428+05:30 [INFO] 127.0.0.1:49308 - 51871 "A IN test1-api.tt.testing. udp 38 false 512" NOERROR qr,aa,rd,ra 74 0.000129238s
2018-12-14T14:37:03.786+05:30 [INFO] 127.0.0.1:58374 - 25757 "A IN test1-api.tt.testing. udp 50 false 4096" NOERROR qr,aa,rd,ra 74 0.00005645s

$ cat Corefile 
tt.testing {
    log
    errors
    file test1-api
}

$ cat test1-api 
$ORIGIN tt.testing.
@    3600   IN      SOA     ns.tt.testing. root.tt.testing. (
                              5         ; serial
                         604800         ; refresh
                          86400         ; retry
                        2419200         ; expire
                          36000         ; minimum
			  )

; Name Server Information
test1-api     IN      A       127.0.0.1
test1-etcd-0     IN      A    127.0.0.1

$ nslookup test1-api.tt.testing 127.0.0.1
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	test1-api.tt.testing
Address: 127.0.0.1

$ dig @127.0.0.1 test1-api.tt.testing

; <<>> DiG 9.10.6 <<>> @127.0.0.1 test1-api.tt.testing
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25757
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;test1-api.tt.testing.		IN	A

;; ANSWER SECTION:
test1-api.tt.testing.	3600	IN	A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Dec 14 14:37:03 IST 2018
;; MSG SIZE  rcvd: 74

$ ping test1-api.tt.testing
ping: cannot resolve test1-api.tt.testing: Unknown host
```

Any clue why this is not working with ping? 

I did try to add `upstream` for file plugin but same result.

**Comment by rdrozhdzh** [comment]
With `nslookup` and `dig` you directly specify which DNS server to use. Ping uses default DNS server configured in system, and seems this is not the coredns you are running at 127.0.0.1

**Comment by praveenkumar** [comment]
@rdrozhdzh I am running CoreDns server at `127.0.0.1` as you can see from the dig command where I mentioned `@127.0.0.1` not sure what you mean that coredns not running at `127.0.0.1`?

**Comment by rdrozhdzh** [comment]
I mean that default DNS server configured in your system is different, i.e. NOT your coredns

**Comment by praveenkumar** [comment]
@rdrozhdzh I updated the dns info to `/etc/resolve.conf` I think that should do right? Or there is other way in the MacOS?

```
$ cat /etc/resolv.conf 
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 127.0.0.1
nameserver 192.168.43.1
```

**Comment by miekg** [comment]
those changes have a high chance of being overwritten

**Comment by rdrozhdzh** [comment]
Looks good for linux, not sure about MacOS specifics. Did you run
```
scutil --dns
```
to check DNS config (as suggested in comment above)?

Other possible reason is that system fails to resolve most of DNS queries (i.e. all except *.tt.testing) via 127.0.0.1 and therefore prefers using 192.168.43.1

**Comment by praveenkumar** [comment]
@miekg @rdrozhdzh Ack, I am reading how to update `nameserver` properly on the mac, will comment back once get something.

**Comment by gbraad** [comment]
@praveenkumar on macOS you also have something called the `resolver`. I'll get back later (edit this comment) to provide the info. Have something that came up...

Also make sure you are connected, as on macOS the DNS will NOT work when the interface is not in a connected state. There are workarounds for this, which I will add. TTYL

**Comment by praveenkumar** [comment]
Finally I am able to update the nameserver details correctly and able to ping. Putting here in case someone hit same kind of issue.

```console
----- Check first what is the dns configuration you have -----
$ scutil --dns
DNS configuration

resolver #1
  nameserver[0] : 192.168.43.1
  if_index : 5 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 192.168.43.1
  if_index : 5 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

----- As you can see coredns server which is running on the 127.0.0.1 is not listed -----
----- If you try to use https://github.com/coredns/coredns/issues/2393#issuecomment-447272191 it will not solve the problem ------

---- use resolver config ----
$ cat /etc/resolver/tt.testing 
nameserver 127.0.0.1

---- Check again the dns configuration ----
$ scutil --dns
DNS configuration
[...]
resolver #8
  domain   : tt.testing
  nameserver[0] : 127.0.0.1
  flags    : Request A records, Request AAAA records
  reach    : 0x00030002 (Reachable,Local Address,Directly Reachable Address)
[...]

---- Now I can able to ping without any issue ----
$ ping test1-api.tt.testing
PING test1-api.tt.testing (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.044 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.078 ms 
```

@rdrozhdzh @miekg I am closing this issue but I do think something this can be added in the documents?

**Comment by erikandLambo** [comment]
Is this good for the owner of the location again

**Comment by gbraad** [comment]
Some of the backstory can be found in https://github.com/minishift/minishift/issues/201. For Minishift we tried to develop a local DNS solution, but ran into issues with macOS. This is because macOS actually has `/etc/resolver/[domain-file]` and the legacy libc resolver from `/etc/resolv.conf`. Some of the applications understand how to handle this, and some don't. If not mistaken `ping` did use resolver, while dig did not. I will dig further in the issues and the history of the PR, and retry some of this stuff and will add results here (currently not on my mac).

--- 
Note; message did not get posted until I got home. Seems OP already closed it in the mean time. If more info is needed, let me know.

**Comment by erikandLambo** [comment]
I don't know anything but I'm the owner of this location or 27 post St San Jose

On December 14, 2018 5:33:15 AM Gerard Braad <notifications@github.com> wrote:
> Some of the backstory can be found in minishift/minishift#201. For 
> Minishift we tried to develop a local DNS solution, but ran into issues 
> with macOS. This is because macOS actually has /etc/resolver/[domain-file] 
> and the legacy libc resolver from /etc/resolv.conf. Some of the 
> applications understand how to handle this, and some don't. If not mistaken 
> ping did use resolver, while dig did not. I will dig further in the issues 
> and the history of the PR, and retry some of this stuff and will add 
> results here (currently not on my mac).
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by sanfx** [comment]
I got the whole thing working straight away, I can get correct result using dig,nslookup and ping works. However I noticed to make the myown.home.domin work in browser I have to explicitly type http:// infront of it(like http://myown.home.domain), otherwise browser redirects it to a search engine.

apologies for posting at the wrong place.
