### ISSUE TITLE
plugin/loop: show query path when dying

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2395]
Currently the loop plugin dies with:
~~~
2018/12/12 13:33:22 [FATAL] plugin/loop: Seen "HINFO IN 7087784449798295848.7359092265978106814." more than twice, loop detected
~~~

We have the source IP (and port) at this point to we should def. add those. We should(?) know the upstream server.
But this should be amended to become:
~~~
2018/12/12 13:33:22 [FATAL] plugin/loop: Seen "HINFO IN 7087784449798295848.7359092265978106814." more than twice (from IP1, IP2, IP3), loop detected
~~~
Or whatever looks cool. We can also log each incoming one use the normal log syntax, although that means you need to shift through multiple log lines which is always difficult.

**Comment by MissEnXi** [comment]
@miekg  can I take it?

**Comment by erikandLambo** [comment]
No

**Comment by erikandLambo** [comment]
But you can help me

**Comment by erikandLambo** [comment]
And whatever we can share, but in person

**Comment by MissEnXi** [comment]
@erikandLambo 
I don't understand you, and if you are doing this, just do it.
Thanks.

**Comment by erikandLambo** [comment]
I don't know what I'm doing

**Comment by MissEnXi** [comment]
@erikandLambo 
> I don't know what I'm doing

so you means that you don't understand the case, right?

maybe you should read #2391 carefully. or ask @miekg for some help.

**Comment by erikandLambo** [comment]
What does that all mean in lameins term

**Comment by miekg** [comment]
Hi. I already send a PR #2400 to address this.
