### ISSUE TITLE
grpc health

### ISSUE THREAD

**Issue by gertcuykens** [coredns/coredns#2405]
https://coredns.io/plugins/health/

Please consider adding https://github.com/grpc/grpc/blob/master/doc/health-checking.md

Thanks

**Comment by miekg** [comment]
to have upstrream health filter through to the server health? This would mean any network hiccup makes coredns unhealthy. Esp when you have a cluster of them, they probably share fate and they *all* go unhealthy at the same time - probably not something you want.

**Comment by gertcuykens** [comment]
Hmm no just the same as the health plugin but different endpoint so you can use a grpc client instead of http client to check if /heath is ok. Or did I understood health wrong? I thought it was a http endpoint to check if the dns server and its plugin's are ok?

**Comment by gertcuykens** [comment]
Something like this
```go
func Client() (pb.HealthClient, *grpc.ClientConn) {
	pool, err := x509.SystemCertPool()
	creds := credentials.NewClientTLSFromCert(pool, os.Getenv("HOSTNAME"))
	if err != nil {
		log.Fatalf("Failed to generate credentials %s", err)
	}
	conn, err := grpc.Dial(":https", grpc.WithTransportCredentials(creds), grpc.WithDefaultCallOptions(grpc.UseCompressor("gzip")))
	if err != nil {
		log.Fatalf("Could not connect to backend: %s\n", err)
	}
	return pb.NewHealthClient(conn), conn
}
```
```
	client, conn := Client()
	defer conn.Close()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	msg, err := client.Check(ctx, &pb.HealthCheckRequest{})
	if err != nil {
		log.Fatalf("%v %v", client, err)
	}
	log.Print(msg)
```
Same as plain http2 but then just some grpc stuff around it following the grpc health spec

**Comment by gertcuykens** [comment]
I think if you add Check to your https://github.com/coredns/coredns/blob/master/pb/dns.proto we are already halve way there?

```
service DnsService {
	rpc Query (DnsPacket) returns (DnsPacket);
	rpc Watch (stream WatchRequest) returns (stream WatchResponse);
        rpc Check (HealthCheckRequest) returns (HealthCheckResponse);
}
```

**Comment by miekg** [comment]
Depending on the plugin (proxy or forward) the health checking is done differently. proxy checks http endpoint (iirc). Forward checks in band and thus uses the same protocol as the dns queries.

**Comment by gertcuykens** [comment]
Ok lets park it for now because I think I underestimate the work involved and backward compatibility issues to add Check in the proto DnsService directly. But for a grpc service kind of view I think this makes grpc more elegant.

**Comment by johnbelamaric** [comment]
Health checking CoreDNS and health checking the upstream are different
things. So, you can add the health check to the gRPC server interface, that
would be OK. We would leave proxy and forward health checking working as
they are.

**Comment by miekg** [comment]
health has been reduced to overall server health, marking this obsolete
