### ISSUE TITLE
Windows 10 go get -u github.com/coredns/coredns

### ISSUE THREAD

**Issue by gertcuykens** [coredns/coredns#2406]
I get following error message in windows 10 not sure if i missed something in the readme ?
```sh
➜ go get -u github.com/coredns/coredns
# github.com/coredns/coredns/core/dnsserver
..\..\go\src\github.com\coredns\coredns\core\dnsserver\register.go:252:5: cannot use new(Server) (type *Server) as type caddy.GracefulServer in assignment:
        *Server does not implement caddy.GracefulServer (missing WrapListener method)
```

**Comment by miekg** [comment]
Use make and the supplied Makefile

/label: question

**Comment by gertcuykens** [comment]
Ok thanks, closing but I do hope we can maybe have a go module solution instead of a make. Could be wrong but I think go modules is capable of doing the same as the make file part that is responsible for compiling so you can just do `go get -u github.com/coredns/coredns` Anyway I will investigate more and open a new go modules ticket once I dig some deeper in the make file

**Comment by gertcuykens** [comment]
Going to add this for other windows users if they stumble on this issue and can't use make
Basically do this in MSYS2
```sh
#!/bin/bash
go get github.com/mholt/caddy
go get github.com/miekg/dns
go get github.com/prometheus/client_golang/prometheus/promhttp
go get github.com/prometheus/client_golang/prometheus
(cd /c/Users/gertc/go/src/github.com/mholt/caddy              && git checkout -q v0.11.1)
(cd /c/Users/gertc/go/src/github.com/miekg/dns                && git checkout -q v1.1.1)
(cd /c/Users/gertc/go/src/github.com/prometheus/client_golang && git checkout -q v0.9.1)
go get github.com/coredns/coredns
```
That said I do believe all of the dependencies use tags so I think go modules can handle this if coredns switches to go modules?

**Comment by miekg** [comment]
Yes go modules should work. So far noone bothered to implement that
