### ISSUE TITLE
coredns doesn't offer hostname A records for pods

### ISSUE THREAD

**Issue by dionysius** [coredns/coredns#2409]
Hi, I've a pretty simple kubernetes cluster created with kubeadm. I have this issue with both:
- Pods with a Hostname set ([Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records-1))
- Pods with Hostname and Subdomain set ([Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields))

I'll focus on the Hostname only case for now:

> The Pod spec has an optional hostname field, which can be used to specify the Pod’s hostname. When specified, it takes precedence over the Pod’s name to be the hostname of the pod. For example, given a Pod with hostname set to “my-host”, the Pod will have its hostname set to “my-host”.

This is what Corefiles `endpoint_pod_names` is for, to apply for this. So far so good.

```
$ kubectl -n kube-system get configmaps coredns -o json | jq -r '.data.Corefile'
.:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       endpoint_pod_names
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    reload
}
```

I have the following pod as example:
```
$ cat nginx-dnsexample.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: headless-example
spec:
  hostname: myhostname
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
    resources: {}
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
```

I have the following headless service as example:
```
$ cat nginx-headless.yaml 
apiVersion: v1 
kind: Service 
metadata: 
  name: headless-service 
spec: 
  clusterIP: None
  ports: 
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: headless-example
```

So, that means I would expect an A record for this pod called `myhostname.headless-service.default.svc.cluster.local`

```
$ kubectl -n kube-system exec -ti coredns-78fcdf6894-p4j7x -- dig AXFR cluster.local @localhost | grep myhostname
( no results )
$ kubectl -n kube-system exec -ti coredns-78fcdf6894-p4j7x -- dig myhostname.headless-service.default.svc.cluster.local +short
( no results )
$ kubectl -n kube-system exec -ti coredns-78fcdf6894-p4j7x -- dig kubernetes.default.svc.cluster.local @localhost +short
10.96.0.1
```

As you can see, there is no A record created for this pod. For completeness, this is what coredns offers when requesting a zone transfer:

```
$ kubectl -n kube-system exec -ti coredns-78fcdf6894-p4j7x -- dig AXFR cluster.local @localhost

; <<>> DiG 9.11.2-P1 <<>> AXFR cluster.local @localhost
;; global options: +cmd
cluster.local.		0	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1545212204 7200 1800 86400 30
headless-service.default.svc.cluster.local. 0 IN A 10.244.0.21
nginx.headless-service.default.svc.cluster.local. 0 IN A 10.244.0.21
_http._tcp.headless-service.default.svc.cluster.local. 0 IN SRV	0 100 80 nginx.headless-service.default.svc.cluster.local.
_https._tcp.headless-service.default.svc.cluster.local.	0 IN SRV 0 100 443 nginx.headless-service.default.svc.cluster.local.
kubernetes.default.svc.cluster.local. 0	IN A	10.96.0.1
kubernetes.default.svc.cluster.local. 0	IN SRV	0 100 443 kubernetes.default.svc.cluster.local.
_https._tcp.kubernetes.default.svc.cluster.local. 0 IN SRV 0 100 443 kubernetes.default.svc.cluster.local.
kube-dns.kube-system.svc.cluster.local.	0 IN A	10.96.0.10
kube-dns.kube-system.svc.cluster.local.	0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
_dns._udp.kube-dns.kube-system.svc.cluster.local. 0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
kube-dns.kube-system.svc.cluster.local.	0 IN A	10.96.0.10
kube-dns.kube-system.svc.cluster.local.	0 IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
_dns-tcp._tcp.kube-dns.kube-system.svc.cluster.local. 0	IN SRV 0 100 53 kube-dns.kube-system.svc.cluster.local.
tiller-deploy.kube-system.svc.cluster.local. 0 IN A 10.103.140.68
tiller-deploy.kube-system.svc.cluster.local. 0 IN SRV 0 100 44134 tiller-deploy.kube-system.svc.cluster.local.
_tiller._tcp.tiller-deploy.kube-system.svc.cluster.local. 0 IN SRV 0 100 44134 tiller-deploy.kube-system.svc.cluster.local.
cluster.local.		0	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1545212204 7200 1800 86400 30
;; Query time: 5 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Dec 19 09:39:18 UTC 2018
;; XFR size: 30 records (messages 2, bytes 2905)

```

Do I do anything wrong? keep in mind this is unrelated to resolv.conf, I asked coredns directly. Yes, I have restarted the coredns pods after changing the Corefile so they apply to the newest config.

For additional info like coredns version, refer to this pod description:
```
$ kubectl -n kube-system get pod coredns-78fcdf6894-p4j7x -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-12-18T13:26:52Z
  generateName: coredns-78fcdf6894-
  labels:
    k8s-app: kube-dns
    pod-template-hash: "3497892450"
  name: coredns-78fcdf6894-p4j7x
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-78fcdf6894
    uid: ae0205f8-01fb-11e9-8a40-fa163e10c0b6
  resourceVersion: "123629"
  selfLink: /api/v1/namespaces/kube-system/pods/coredns-78fcdf6894-p4j7x
  uid: 94995053-02c8-11e9-8a40-fa163e10c0b6
spec:
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: k8s.gcr.io/coredns:1.1.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: coredns
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 9153
      name: metrics
      protocol: TCP
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - all
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: coredns-token-n2rmn
      readOnly: true
  dnsPolicy: Default
  nodeName: master
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: coredns
    name: config-volume
  - name: coredns-token-n2rmn
    secret:
      defaultMode: 420
      secretName: coredns-token-n2rmn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-12-18T13:26:52Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-12-18T13:26:54Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-12-18T13:26:52Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e2f8dec13df4512b5bb73034f6fa6c8d6d0aa3bfe8e236036d9cb4213592f61a
    image: k8s.gcr.io/coredns:1.1.3
    imageID: docker-pullable://k8s.gcr.io/coredns@sha256:db2bf53126ed1c761d5a41f24a1b82a461c85f736ff6e90542e9522be4757848
    lastState: {}
    name: coredns
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-12-18T13:26:54Z
  hostIP: 172.17.0.55
  phase: Running
  podIP: 10.244.0.15
  qosClass: Burstable
  startTime: 2018-12-18T13:26:52Z
```

**Comment by dilyevsky** [comment]
Did you also create an endpoint? My understanding is pod requires an endpoint (via headless service) for it to have an non-dashed-IP A record setup .

From https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods:

```
If there exists a headless service in the same namespace as the pod and with the same name
as the subdomain, the cluster’s KubeDNS Server also returns an A record for the Pod’s fully
qualified hostname. For example, given a Pod with the hostname set to “busybox-1” and the
subdomain set to “default-subdomain”, and a headless Service named “default-subdomain” in
the same namespace, the pod will see its own FQDN as
“busybox-1.default-subdomain.my-namespace.svc.cluster.local
```

**Comment by fturib** [comment]
I agree with @dilyevsky, your pod's name will be returned for:

- for all A records of a **headless** services, on each endpoint that have a **hostname property empty**. (the hostname will then be substituted with the name of the pad).

**Comment by dionysius** [comment]
Thank you for pointing the headless service. This is also what I've read and discovered, but missed that part above. I then have some A records, but they're still not in the format I would expect. I can provide more details tomorrow.

**Comment by johnbelamaric** [comment]
The name will be

<pod-name>.<service-name>.<namespace>.svc.<cluster-zone>

And only if pod subdomain is the same as service-name, I believe.

**Comment by dionysius** [comment]
Thank you for your help. I've updated the post above to reflect with a headless service. So we'll now begin with a DNS record now, as you described: `<pod-name>.<service-name>.<namespace>.svc.<cluster-zone>`

What I'm looking for, is a DNS record with: `<pod-hostname>.<service-name>.<namespace>.svc.<cluster-zone>`

I've the following example to reflect the special case, when `podspec.subdomain` is the same string as the `service.name`:

```
$ cat nginx-dnsexample-withsubdomain.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: default
  labels:
    app: headless2-example
spec:
  hostname: myhostname
  subdomain: specific-headless
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
    resources: {}
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
```

```
$ cat nginx-headless-withsubdomain.yaml 
apiVersion: v1 
kind: Service 
metadata: 
  name: specific-headless
spec: 
  clusterIP: None
  ports: 
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: headless2-example
```

Now we have the following DNS records:

```
s$ kubectl -n kube-system exec -ti coredns-78fcdf6894-zcht7 -- dig AXFR cluster.local @localhost | grep specific-headless
specific-headless.default.svc.cluster.local. 0 IN A 10.244.0.22
myhostname.specific-headless.default.svc.cluster.local.	0 IN A 10.244.0.22
_http._tcp.specific-headless.default.svc.cluster.local.	0 IN SRV 0 100 80 myhostname.specific-headless.default.svc.cluster.local.
_https._tcp.specific-headless.default.svc.cluster.local. 0 IN SRV 0 100 443 myhostname.specific-headless.default.svc.cluster.local.
```

As you can see, I now have what I was looking for :+1: .

I've made a short example, where subdomain does not match the service name, and we end up back with the pod-name.

**But to summerize**
You only have `<pod-hostname>.<service-name>...`, if your `service.name` is exactly the same as the `podspec.subdomain`. In all other cases (subdomain missing, subdomain not matching, etc.) you end up having `<pod-name>.<service-name>...`

So this has been solved by itself

**Comment by krishnakoney** [comment]
I am trying to setup a simple Kubernetes multi-cluster(2 clusters) networking. I am not using any specific CNI for this. My idea is to modify the cluster's DNS server to add other cluster's DNS server SRV/A record sothat container(in cluster_1) can communicate with container(in cluster_2).

Is there any way I can add a new SRV/A records programmatically to the coreDNS server running as coreDNS pod in the kerbernetes cluster environment?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] coredns doesn..." ]
>Is there any way I can add a new SRV/A records programmatically to the coreDNS server running as coreDNS pod in the kerbernetes cluster environment?

you can use the file plugin to add an entire zonefile (which can be loaded via a
configmap), or see the hosts plugin (doesn't do SRV though), to add hosts.

**Comment by krishnakoney** [comment]
Thanks Miek.
If I use file plugin to add a Zone File(a different cluster), Will I be able to communicate to a container(cluster) in that mentioned in that Zone file ?

Is there any Kubernetes tool to update/add a new zone file of the Cluster's coreDNS configuration ?

If cluster_1 has to pass the dns request to cluster_2 then What are the alternatives ? Is it by adding SRV/A records to the cluster's core_dns server ? (or) by using Forward plugin to add Upstream_Server(of cluster_2) ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] coredns doesn..." ]
>Thanks Miek.
>If I use file plugin to add a Zone File(a different cluster), Will I be able to communicate to a container(cluster) in that mentioned in that Zone file ?

coredns doesn't care about, so it depends on what kind of address you hand out and what
whacky networking you use in k8s.

>Is there any Kubernetes tool to update/add a new zone file of the Cluster's coreDNS configuration ?

the file plugin will reload changed contents every so often.

>If cluster_1 has to pass the dns request to cluster_2 then What are the alternatives ? Is it by adding SRV/A records to the cluster's core_dns server ? (or) by using Forward plugin to add Upstream_Server(of cluster_2) ?

you problaby don't want to set this up like this

**Comment by krishnakoney** [comment]
Thanks Miek.
I will try to add a new Zonal for adding Cluster to Cluster DNS name resolution as you suggested via modifying the coredns configmap

**Comment by johnbelamaric** [comment]
You may also want to take a look at:

https://github.com/coredns/multicluster-dns
