### ISSUE TITLE
Coredns file plugin doesn't resolve SRV record as expected

### ISSUE THREAD

**Issue by yboaron** [coredns/coredns#2411]
I'm almost sure that the root cause for this is mis-configuration of the corefile.

So, I followed the instructions from this blog  [1]
and created the following [2] K8S manifest file to create local DNS server,  the server runs in a K8s pod.
This DNS should serve a single zone and should use the file plugin.
After the Pod is in running state, I run dig (serverIP==Pod's IP)  with the service-name (moshe.example.org.)  I don't receive the IP address (192.168.11.11) as I expected.
You can find the output of dig command in [3].

10x!

[1] https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/
[2]https://github.com/yboaron/coredns_service/blob/master/deployment.yaml
[3] 10.0.0.80 is the IP of the pod that runs coredns.
[stack@rrrt devstack]$ dig @10.0.0.80  moshe.example.org

; <<>> DiG 9.9.4-RedHat-9.9.4-72.el7 <<>> @10.0.0.80 moshe.example.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26494
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;moshe.example.org.             IN      A

;; AUTHORITY SECTION:
example.org.            0       IN      SOA     sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600

;; Query time: 1 msec
;; SERVER: 10.0.0.80#53(10.0.0.80)
;; WHEN: Wed Dec 19 07:11:47 UTC 2018
;; MSG SIZE  rcvd: 116

[stack@rrrt devstack]$

**Comment by johnbelamaric** [comment]
you asked for an A record. try `dig -t srv moshe.example.org @10.0.0.80`

**Comment by yboaron** [comment]
@johnbelamaric,  it works! 

10x and happy holidays!

[stack@rrrt devstack]$ dig -t srv moshe.example.org @10.0.0.80

; <<>> DiG 9.9.4-RedHat-9.9.4-72.el7 <<>> -t srv moshe.example.org @10.0.0.80
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5124
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;moshe.example.org.             IN      SRV

;; ANSWER SECTION:
moshe.example.org.      0       IN      SRV     8080 10 10 example.org.

;; ADDITIONAL SECTION:
example.org.            0       IN      A       192.168.11.11

;; Query time: 1 msec
;; SERVER: 10.0.0.77#53(10.0.0.77)
;; WHEN: Wed Dec 19 19:19:17 UTC 2018
;; MSG SIZE  rcvd: 110

[stack@rrrt devstack]$
