### ISSUE TITLE
log plugin logs NOERROR with class denial error 

### ISSUE THREAD

**Issue by ialidzhikov** [coredns/coredns#2412]
Our Corefile starts with:
```
errors
log . {
    class denial
    class error
}
[...]
```

However in the coredns stdout we see a lot of `NOERROR` log entries. Also in the log plugin README.md it is not described to which class correspongs `NOERROR`. My understanding from reading the README.md is that `NOERROR` is a success log entry and I do not expect to see `NOERROR` entries with configuration for `classes denial error`.

**Comment by fturib** [comment]
I think you are seeing the same problem as described in this issue : #2340.

NODATA - which means a reply code NOERROR with no data associated will be log into the `class denial`.

**Comment by miekg** [comment]
WAI

**Comment by KristianZH** [comment]
Hi. I have a question about this plugin too. 
With the following configuration:
```
errors
log . {
    class error
}
[...]
```

 in the coredns stdout i see a lot of `NXDOMAIN`, but the documentation says that this type of message belongs to the class `denial`. So how can i remove this type of logs?

**Comment by fturib** [comment]
Besides the NXDOMAIN, you may have an error, which would qualify those messages to be in `class error`.
for instance, if the SOA record is not returned.

**Comment by ialidzhikov** [comment]
Thank you, @fturib . It was so helpful. Maybe it would be useful to add a note in log plugin README.md   that with only `class error` you could also see messages about `NXDOMAIN` - we removed `class denial` and it was frustrating to see again `NXDOMAIN` and we thought that our config is not working. Now with the clarification from your side it is clear. Maybe also a statement about NOERROR? However I will close the issue.
