### ISSUE TITLE
plugin/log - how to set multi name

### ISSUE THREAD

**Issue by ckcd** [coredns/coredns#2417]
Hi, I'm using CoreDNS  v1.3.0 in K8S v1.9,

I want to use `log` plugin to log multi domains, such as `a.com` and `b.com`, but i find the `log` plugin can only set ONE name.

```
log [NAME] [FORMAT] {
    class CLASSES...
}
```
e.g. 
```
log a.com
```

And obviously `log a.com b.com` is bad because the second args is `FORMAT`.

is there any methods to set multi name ?

**Comment by miekg** [comment]
Either send a pr to fix this in the log plugin, or split your zones into
multiple server blocks and use log in each of them.

**Comment by ckcd** [comment]
@miekg 
Thanks for you reply !

The second methods seems too tedious,

I will take the first suggestion and do some code, hope can do it and give a pr.
