### ISSUE TITLE
Permanent failure of only proxy upstream

### ISSUE THREAD

**Issue by gjtempleton** [coredns/coredns#2427]
* What we're seeing:
  * We had a misbehaving CoreDNS pod suddenly only returning NOERROR and SERVFAIL responses to requests for addresses external to our K8s cluster
  * On investigation we discovered that this started occurring after 3 health check failures on the only upstream configured for our proxy plugin
  * The upstream never seems to be checked again, therefore the pod just continues returning errors until manually terminated
  * From the code it looks like this isn't the intended behaviour, given the lines to attempt to return the value of `uh.Fails` to `0`
  * We never see any more log lines about health checking the relevant upstream 

* Our setup

  * Running in Kubernetes in AWS
  * Autoscaling deployment using a cluster proportional autoscaler

* CoreDNS version: v1.0.5

* CoreFile: 

``` 
# cat /etc/coredns/Corefile


<LOCAL_PROD_DOMAIN>:53 {
    errors

    health
    prometheus :9153
    proxy . <INTERNAL_DNS_IP1> <INTERNAL_DNS_IP2> {
        protocol dns force_tcp
    }
    cache 300
}

<LOCAL_CORP_DOMAIN>:53 {
    errors

    health
    prometheus :9153
    proxy . <INTERNAL_DNS_IP1> <INTERNAL_DNS_IP2> {
        protocol dns force_tcp
    }
    cache 300
}

.:53 {
    errors

    health
    autopath @kubernetes
    kubernetes cluster.local {
        pods verified
        upstream 169.254.169.253
        fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . 169.254.169.253
    cache 300
}
```

* Seemingly relevant logs:

```
2019/01/01 00:06:42 [WARNING] Host 169.254.169.253:53 health check probe failed: Get http://169.254.169.253:53: EOF
2019/01/01 00:07:37 [WARNING] Host 169.254.169.253:53 health check probe failed: Get http://169.254.169.253:53: EOF
2019/01/01 00:07:56 [WARNING] Host 169.254.169.253:53 health check probe failed: Get http://169.254.169.253:53: EOF

#Followed by a huge volume of logs of this style:
02/Jan/2019:04:42:08 +0000 [ERROR 2 <non_local_address1>.<k8s_ns>.svc.cluster.local. A] unreachable backend: no upstream host
02/Jan/2019:04:42:08 +0000 [ERROR 2 <non_local_address1>.<k8s_ns>.svc.cluster.local. AAAA] unreachable backend: no upstream host
02/Jan/2019:04:42:09 +0000 [ERROR 2 <non_local_address2>.eu-central-1.compute.internal. AAAA] unreachable backend: no upstream host
02/Jan/2019:04:42:09 +0000 [ERROR 2 <non_local_address2>.eu-central-1.compute.internal. A] unreachable backend: no upstream host
02/Jan/2019:04:42:09 +0000 [ERROR 2 <non_local_address2>.eu-central-1.compute.internal. AAAA] unreachable backend: no upstream host
02/Jan/2019:04:42:09 +0000 [ERROR 2 <non_local_address2>.eu-central-1.compute.internal. A] unreachable backend: no upstream host
02/Jan/2019:04:42:09 +0000 [ERROR 2 <non_local_address3> AAAA] unreachable backend: no upstream host
```
Graph of Prometheus responses:
![prometheus_time_series_collection_and_processing_server](https://user-images.githubusercontent.com/6452486/50603287-ec6bd180-0eb1-11e9-8273-70dcbf5679f8.png)

I've had to terminate the pod unfortunately to resolve the issue, however I did successfully run nslookup etc. from the pod before this.

**Comment by chrisohaver** [comment]
In 1.0.5, I believe health checking in `proxy` was erroneously enabled by default (contradicting the documentation at the time). This was rectified in CoreDNS 1.0.6 (#1441, #1440).

If you want to enable upstream health checking, I'd recommend using the `forward` plugin in place of `proxy`.  `forward` has a different/improved strategy for monitoring health of upstreams.

In "the future" I think the plan is to deprecate `proxy`, and only support `forward` moving ... forward.  But I don't think there is a time schedule on that.

**Comment by gjtempleton** [comment]
Thanks so much for the quick response.

Looks like this is indeed the issue we've seen, though I don't know how I didn't find that issue to begin with!

I'll close this as a duplicate and prioritising updating the version we're running then and re-open if we see it in the future (though I doubt we will.)
