### ISSUE TITLE
Headless service name resolution delay

### ISSUE THREAD

**Issue by svallala** [coredns/coredns#2434]
Hi,

     I have following configuration in the coredns configmap.

        .:53 {
            errors
            health
            kubernetes cluster.local 21.172.in-addr.arpa 19.172.in-addr.arpa 18.172.in-addr.arpa {
               pods verified
               fallthrough 21.172.in-addr.arpa 19.172.in-addr.arpa 18.172.in-addr.arpa
            }
            forward . /etc/resolv.conf {
               policy sequential
               health_check 5s
            }
            prometheus :9153
            cache 30
            reload
        }

I was testing the name resolution of a headless service. In the pod entrypoint I was timing how long it takes for name resolution to succeed using nslookup <hostname>, it takes 30 seconds. If I change the config with "cache 5", then it takes 5 seconds. Trying to understand the role of cache plugin here. If my application entrypoint relies on name resolution immediately on start, then should I just get rid of the cache plugin?

What are the drawbacks of removing the cache plugin, even after I remove the line, it takes couple of seconds for the name resolution to work. I am forced to put a sleep in my entrypoint, how long does it take for coredns to resolve a newly created headless service?

Any help is much appreciated.

Thanks
Shravan

**Comment by chrisohaver** [comment]
The cache plugin keeps a local cache in coredns of dns responses.  It's mainly used to keep copies of upstream responses locally to reduce the traffic to upstream servers.  If you remove the cache plugin, the amount of traffic to your upstream dns servers will increase.

`cache 30` for example, will cache responses for a maximum of 30 seconds.  However, if the TTL of a record is < 30 then it will only be cached for a duration equal to its TTL.  

If you queried the headless service before it was created, then the negative response would be cached.  However, the TTL for records served by the kubernetes plugin defaults to 5 seconds, so those negative responses should only be cached by the cache plugin for 5 seconds.

If you set the TTL for kubernetes to zero (i.e. `ttl 0`, which is allowed in the latest version of coredns), then kubernetes records wont enter the cache.

The kubernetes plugin has a kind of built in cache of its own, which keeps indexed records of every service, endpoint, and pod (for pods verified). These records are updated via an asynchronous watch on the k8s API.  So, kubernetes plugin answers very quickly even if none of its records get cached by the cache plugin.

> how long does it take for coredns to resolve a newly created headless service?

If you are creating the headless service at the same time as creating the pods that it selects, it will take some time for the pods to spin up and be ready. But once the pods are ready, coredns is updated almost instantaneously.  I suppose in a cluster with an extremely busy/slow api, it could take some noticeable time for coredns to receive notification of the new service, but I have never actually witnessed this.

**Comment by svallala** [comment]
Thanks for the response.

Based on your explanation unable to figure out the delay of 30 seconds that I see when I have "cache 30" line in the config.

I am creating the headless service and the pods that it selects at the same time. The delay I am seeing is in the name resolution in the entrypoint of the pod that the service selects. Since the POD is deployed, will it be considered ready? If yes, then it should be able to resolve in the entrypoint isn't it?

Its not a loaded system and I am consistently seeing the delay in name resolution following the cache plugin setting. If I set the cache plugin to 10 seconds, then the delay in name resolution in the entrypoint falls down to 10 seconds. Any ideas?

I am using 1.2.2 version, but the same is the behavior with 1.2.6.

Thanks
Shravan

**Comment by chrisohaver** [comment]
Alternately, you could try turning off negative caching...

```
cache 30 {
    denial 0
}
```

**Comment by chrisohaver** [comment]
> Based on your explanation unable to figure out the delay of 30 seconds that I see when I have "cache 30" line in the config.

I think that negative response SOA records may not honor the per plugin TTL settings... i.e. negative responses will always default to a static large number and then get capped by the cache.  If so, setting TTL to 0 in the kubernetes plugin would not prevent negative responses from entering the cache.

A way of fixing this would be to add a new option to the cache plugin to exclude certain domains.

**Comment by svallala** [comment]
Thanks Chris, I will use the "denial 0" option and check if it works for my use case. Regarding the new option in cache plugin, will you provide this option in the next releases?

**Comment by chrisohaver** [comment]
> Regarding the new option in cache plugin, will you provide this option in the next releases?

I'll propose it, but it's ultimately up to the project owner.

**Comment by svallala** [comment]
'denial 0" option in cache plugin didn't work. For now I am setting the cache to 2, just get around the issue. Thanks for your prompt responses regarding this issue.

**Comment by chrisohaver** [comment]
> 'denial 0" option in cache plugin didn't work.

It should have.  It means something else is wrong.

**Comment by dvaldivia** [comment]
Is there a way to tell the cache plugin to invalidate some cached value immediately @chrisohaver ?

**Comment by chrisohaver** [comment]
> Is there a way to tell the cache plugin to invalidate some cached value immediately @chrisohaver ?

No there is not.

But in the context of this issue, it would make more sense to disable cache for the Kubernetes DNS zone (e.g. `cluster.local`). Although there is not currently a way to disable cache for a specific zone,  I have recently opened #5540 to add this option. 

The _kubernetes_ plugin already keeps its own cache that is more or less updated in real time via change events from the K8s API.  The redundant caching by the _cache_ plugin provides no benefit, and just adds the update latency described in this issue.  The only reason the _cache_ plugin is deployed by default is to cache responses from upstream servers, the redundant caching kubernetes records is a side effect.

In the interim, there is a workaround now, which while not ideal, does theoretically work.  Essentially you could remove caching from the main server block, and forward upstream requests to a second server block. That second server block forwards upstream and does caching.  e.g. stripped down to minimal options for clarity ... 

```
. {
  kubernetes cluster.local
  forward . localhost:5399
}

.:5399 {
  cache 30
  forward . /etc/resolv.conf
}
```

 It creates an extra internal hop, which isn't ideal - and IMO makes it unfit as a "default Kubernetes" configuration. But it does prevent kubernetes records from getting redundantly cached.

**Comment by ensonic** [comment]
#5540 is merged. with that how would it be applied?:
```
. {
  kubernetes cluster.local
  cache {
    disable denial cluster.local
  }
}
```

**Comment by chrisohaver** [comment]
> #5540 is merged. with that how would it be applied?:
> 
> ```
> . {
>   kubernetes cluster.local
>   cache {
>     disable denial cluster.local
>   }
> }
> ```

That looks right.
