### ISSUE TITLE
plugin/proxy: support host name in proxy TO

### ISSUE THREAD

**Issue by andy2046** [coredns/coredns#2440]
this is a feature/enhancement request

in Kube cluster I use `stubDomans` to forward `consul.local` DNS query to consul cluster, but now only IP address is supported, it will be great if I can use `consul.service.internal` in proxy as shown below, as the IP is ephemeral but host name is not

```
.:53 {
    kubernetes cluster.local {
        upstream
    }
    proxy consul.local consul.service.internal:53
    proxy . 8.8.8.8:53
}
```

if this request is accepted, I will raise a PR to update

https://github.com/coredns/coredns/blob/06efc07f46399f2d194614b52d4268a624cfe3eb/plugin/pkg/parse/host.go#L50-L51

to

```go
                  if net.ParseIP(addr) == nil {
			// Not an IP address.
			if IPs, err := net.LookupIP(addr); err == nil && len(IPs) > 0 {
				servers = append(servers, fmt.Sprintf("%s:%s", IPs[0].String(), port))
				continue
			} else {
				ss, err := tryFile(host)
				if err == nil {
					servers = append(servers, ss...)
					continue
				}
			}
			return servers, fmt.Errorf("not an IP address or file: %q", host)
		}
```

git diff
```
--- a/plugin/pkg/parse/host.go
+++ b/plugin/pkg/parse/host.go
@@ -20,7 +20,7 @@ func HostPortOrFile(s ...string) ([]string, error) {

                trans, host := Transport(h)

-               addr, _, err := net.SplitHostPort(host)
+               addr, port, err := net.SplitHostPort(host)
                if err != nil {
                        // Parse didn't work, it is not a addr:port combo
                        if net.ParseIP(host) == nil {
@@ -49,10 +49,15 @@ func HostPortOrFile(s ...string) ([]string, error) {

                if net.ParseIP(addr) == nil {
                        // Not an IP address.
-                       ss, err := tryFile(host)
-                       if err == nil {
-                               servers = append(servers, ss...)
+                       if IPs, err := net.LookupIP(addr); err == nil && len(IPs) > 0 {
+                               servers = append(servers, fmt.Sprintf("%s:%s", IPs[0].String(), port))
                                continue
+                       } else {
+                               ss, err := tryFile(host)
+                               if err == nil {
+                                       servers = append(servers, ss...)
+                                       continue
+                               }
                        }
                        return servers, fmt.Errorf("not an IP address or file: %q", host)
                }
```

**Comment by miekg** [comment]
See the dicussion in https://github.com/coredns/coredns/pull/1592

/plugin: proxy
/label: enhancement

**Comment by andy2046** [comment]
@miekg thanks for update, looked into #1592, so we need a new plugin to handle this or it can be handled in pkg kubernetes?

my understanding is we need a plugin to resolve the host name to ip and keep watching it and if it changes we need to update Corefile config as well

**Comment by miekg** [comment]
Short answer: I will not merge such a PR. It's tricky to get right and your
assuming there is another resolver running somewhere. We're a DNS server,
putting names in the config does not make sense.

**Comment by chrisohaver** [comment]
The ability to do this was very recently merged in kube-dns.

https://github.com/kubernetes/dns/pull/279

This change permits configurations in kube-dns that we cannot replicate in coredns, complicating upgrades/migrations (from kubedns -> coredns).

**Comment by johnbelamaric** [comment]
If we use our normal upstream to resolve (ie, resolve against ourselves),
wouldn't that work? I believe we have loop-detection built into that
(beyond the loop plugin).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/proxy:..." ]
>If we use our normal upstream to resolve (ie, resolve against ourselves),
>wouldn't that work? I believe we have loop-detection built into that
>(beyond the loop plugin).

not on startup, so it needs:

1) to be async. 
2) avoid the catch-22 of resolving names with the forwarder we're configuring
3) re-resolve every TTL
4) hold on to last-known-good when resolve fails
5) error out when resolve has failed for N TTLs and upstream start failing
6) start/stop any healthcheckers
7) fail the coredns start when actually resolving fails twice
8) metrics and good logs for all these failure modes

In the proxy plugin this happens for the google_https endpoint and was/is a bit
of a shit show (healtchecking never worked)


/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/proxy:..." ]
>If we use our normal upstream to resolve (ie, resolve against ourselves),
>wouldn't that work? I believe we have loop-detection built into that
>(beyond the loop plugin).

I'm not worried that much about loops, but how is:

~~~
forward . www.example.com
~~~

going to work?

What's our normal upstream?

**Comment by johnbelamaric** [comment]
By our "normal upstream" I meant the normal logic of resolving using
ourselves.

In this case, it's not going to work, it's going to SERVFAIL, because of
the loop detection built into `upstream`. You are right that that is a bit
wonky at startup though. We would need to defer the lookup until after
startup. Alternatively the system resolver if we get a SERVFAIL back from
ourselves.

So basically from your list:

#1 yes, it would have to be async
#2 internal loop detection avoids a runaway process, it just means you
SERVFAIL on these queries
#3, 4, 5 yep, should do those...
#6 huh? not clear how this is different with a name vs an IP?
#7 no, I don't think that's needed, we just let the internal loop detection
(not the loop plugin) send SERVFAIL back
#8 yep
