### ISSUE TITLE
plugin/etcd: Empty host fields in services need to be ignored

### ISSUE THREAD

**Issue by callebjorkell** [coredns/coredns#2443]
In coredns 1.2.6, for a domain with services with empty `Host` fields, various queries (tested with `CNAME`, `A`, and `SRV` lookups) will contain answers with the domain `.`. The correct behaviour for this seems to be to skip all services that have an empty `Host` field for all queries other than `TXT`. For domains that have no other services defined, this should also work, since the expected result here is a NODATA response.

Initial discussion in PR #2425

**Comment by callebjorkell** [comment]
I suppose some sort of filter function inside of `backend_lookup.go` would be in order? Seems like the best place to put it to not have to include filtering on the generic `ServiceBackend.Services` call. I guess it would still also be possible to include it in that interface as a boolean (like `exact`) but that seems to me like the wrong place to put that.

**Comment by callebjorkell** [comment]
that is, I'd suggest a filter like:

```golang
func filterHosts(services *[]msg.Service) []msg.Service {
	var ret []msg.Service
	for _,s := range *services {
		if s.Host != "" {
			ret = append(ret, s)
		}
	}
	return ret
}
```
and possibly a similar one for the `Text` field for `TXT` queries, but this is already implemented separately, so it's not strictly speaking needed.

**Comment by callebjorkell** [comment]
All the other query types (at least as far as I can see) should call this filter to get rid of the "hostless" services before constructing an answer for the client.

**Comment by callebjorkell** [comment]
how does this sound @miekg ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/etcd: ..." ]
>that is, I'd suggest a filter like:
>
>```golang
>func filterHosts(services *[]msg.Service) []msg.Service {
>	var ret []msg.Service
>	for _,s := range *services {
>		if s.Host != "" {
>			ret = append(ret, s)
>		}
>	}
>	return ret
>}
>```
>and possibly a similar one for the `Text` field for `TXT` queries, but this is already implemented separately, so it's not strictly speaking needed.

I think this approach can work; but because we share this with k8s (something we 
should probably break up), we need to make it configurable and add a filterFunc 
that can be used in etcd, but not in k8s.

Another approach is too copy backend.go and friends to k8s and etcd respectively 
and just do the changes, but that is considerable more work.

**Comment by callebjorkell** [comment]
I see, but is this really something that should work differently in k8s? I can't think of a way that this would be OK in k8s either, or does k8s rely on this behaviour for something (sounds hackish) where answers are returned even though there is no defined host in the `msg.Service`?

**Comment by fturib** [comment]
cc  @chrisohaver for his opinion on last comment.

**Comment by chrisohaver** [comment]
Can we avoid adding `msg.Service` with empty `Host` string to the array in the first place, instead of filtering them out afterwards?

**Comment by callebjorkell** [comment]
We could, but that would require adding that new parameter to the Services interface, or alternative a new function altogether, as an empty `Host` field is perfectly OK for TXT answers (but that's the only one afaik).

**Comment by callebjorkell** [comment]
... That is, most of the time the ServiceBackend should not return "Hostless" services, but sometimes it should.

**Comment by chrisohaver** [comment]
The request type is known, in `state`, which is already a parameter with `state.QType()`.  Can we check that value before adding empty Hosts to []msg.Service ?

**Comment by callebjorkell** [comment]
Oh yeah, would you look at that. I hadn't realized that that info already got passed down into the `ServiceBackend`. I do find it slightly leaky for the ServiceBackend to need to know about the types of QTypes should have hosts, and which should not, but I do like it better than the other options. If you guys agree I could try to put something together for that tomorrow (hopefully).

**Comment by callebjorkell** [comment]
After having thought about it a bit, I'm fine with adding this filtering into the etcd ServiceBackend if that is what you'd prefer. It will definitely solve the problem for the etcd backed requests, and it will also definitely solve for my own use case. It does impose similar changes/behaviour on all other ServiceBackend implementation though (right now only k8s?). If that's not seen as an issue, I have nothing further :slightly_smiling_face:.

**Comment by chrisohaver** [comment]
Or this could be fixed in backend without doing an extra traversal of the services, in the existing traversals. e.g. 

```
func A(b ServiceBackend ...
...
 for _, serv := range services {
+    if serv.Host == "" {
+       continue
+    }
```

**Comment by chrisohaver** [comment]
Nevermind - I see this was more or less your approach in #2425, but @miekg prefers this filtering solution instead.

**Comment by callebjorkell** [comment]
Moved the check down into the deepest reaches of the etcd plugin now, hopefully this works better now.
