### ISSUE TITLE
nslookup from within pods fail for service names.  However, nslookup from host with pod-IP of coredns as nameserver works

### ISSUE THREAD

**Issue by coderdba** [coredns/coredns#2444]
Version of CoreDNS 
k8s.gcr.io/coredns 1.2.6 

Content of /etc/resolv.conf in the busybox pod:
search policy-demo.svc.cluster.local svc.cluster.local cluster.local corp.target.com
nameserver 10.96.0.10
options ndots:5

Output of nslookup command from within the busybox pod/container:
# nslookup nginx
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'nginx'

The nginx service:
NAMESPACE     NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
policy-demo   nginx         ClusterIP   10.105.224.53   <none>        80/TCP          12d

Coredns pod (and a few other pods):
# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE    IP               NODE   NOMINATED NODE   READINESS GATES
kube-system   calico-etcd-cw79p                          1/1     Running   1          15d    192.168.11.110   kc0    <none>           <none>
kube-system   calico-kube-controllers-5d94b577bb-9ccj5   1/1     Running   3          15d    192.168.11.110   kc0    <none>           <none>
kube-system   calico-node-dc5ct                          1/1     Running   0          12d    192.168.11.111   kc1    <none>           <none>
kube-system   calico-node-j6zg8                          1/1     Running   22         15d    192.168.11.110   kc0    <none>           <none>
kube-system   coredns-86c58d9df4-dcl97                   1/1     Running   1          15d    192.168.0.3      kc0    <none>           <none>
kube-system   coredns-86c58d9df4-kh5wv                   1/1     Running   1          15d    192.168.0.4      kc0    <none>           <none>

**Comment by chrisohaver** [comment]
Recent (and no so recent) versions of busybox have a corrupt `nslookup` that always ignores the search domains in `/etc/resolv.conf`.  Try the fully qualified domain `nginx.policy-demo.svc.cluster.local.`.

**Comment by coderdba** [comment]
Hi Chris,

I tried that and got the same problem.

I wonder whether kube-dns (coredns actually) has the right dns entries of services 
- or - 
is the nslookup even going to kube-dns or not (see observation 2 below)

Some observations:  (with both latest and 1.28 version of busybox)
Note: item 1 (nslookup) behaves slightly differently in latest and 1.28 version of busybox

With latest busybox:
1. nslookup command does not even show the nameserver in the pod /etc/hosts - which is the clusterIP of kube-dns (which is coredns)
/ # nslookup nginx.policy-demo.svc.cluster.local
;; connection timed out; no servers could be reached

2. traceroute of cluster-ip of nginx - goes directly to the host /etc/resolv.conf and tries to find through only nameservers defined in the host resolv.conf
/ # traceroute 10.105.224.53
traceroute to 10.105.224.53 (10.105.224.53), 30 hops max, 46 byte packets
 1  10.0.2.15 (10.0.2.15)  0.005 ms  0.007 ms  0.005 ms --> THIS IS THE HOST IP (VBOX VM NAT)
 2  10.0.2.2 (10.0.2.2)  0.765 ms  0.007 ms  0.004 ms
 3  *  *  *
 4  101.2.1.125 (101.2.1.125)  2.613 ms  2.606 ms  1.956 ms
 5  101.2.1.236 (101.2.1.236)  1.664 ms  2.077 ms  1.518 ms
 6  101.1.72.89 (101.1.72.89)  9.724 ms  11.270 ms  9.626 ms
 7  101.1.64.1 (101.1.64.1)  349.007 ms  338.101 ms  315.760 ms
 8  101.1.64.2 (101.1.64.2)  317.668 ms  274.918 ms  259.287 ms

3. wget of nginx service custer-ip itself works fine from busybox

With busybox 1.28:
1. nslookup:
/ #  nslookup nginx.policy-demo.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10
nslookup: can't resolve 'nginx.policy-demo.svc.cluster.local'

2.  same behavior as in latest busybox
3.  same behavior as in latest busybox

Thanks!!

**Comment by chrisohaver** [comment]
Can you clarify what you mean by in the title of the issue: "However, nslookup from host with pod-IP of coredns as nameserver works"

Please share your coredns Corefile (from the coredns configmap).

Please share the contents of the coredns log.

**Comment by coderdba** [comment]
Hi,

Sorry, I used the term ‘host’ for ‘node’.

——————————————————
On Master: (hostname kc0)
——————————————————

COREDNS PODS
```
[root@kc0 ~]# pods |grep dns
kube-system   coredns-86c58d9df4-dcl97                   1/1     Running   2          17d   192.168.0.6      kc0    <none>           <none>
kube-system   coredns-86c58d9df4-kh5wv                   1/1     Running   2          17d   192.168.0.5      kc0    <none>           <none>
```
COREDNS POD IP PINGABLE
```
[root@kc0 ~]# ping 192.168.0.6
PING 192.168.0.6 (192.168.0.6) 56(84) bytes of data.
64 bytes from 192.168.0.6: icmp_seq=1 ttl=64 time=0.061 ms
```
RESOLV.CONF ON MASTER NODE (of the master node kc0 itself)
```
[root@kc0 ~]# cat /etc/resolv.conf
search policy-demo.svc.cluster.local
nameserver 192.168.0.6   —>  This is the IP of the pod i have entered manually
```

NSLOOKUP THE CLUSTER IP OF NGINX SERVICE
```
[root@kc0 etc]# nslookup  10.105.224.53
Server:		192.168.0.6
Address:	192.168.0.6#53

53.224.105.10.in-addr.arpa	name = nginx.policy-demo.svc.cluster.local.
```

NSLOOKUP OF THE NGINX SERVICE
```
[root@kc0 etc]# nslookup nginx.policy-demo.svc.cluster.local
Server:		192.168.0.6
Address:	192.168.0.6#53

Name:	nginx.policy-demo.svc.cluster.local
Address: 10.105.224.53

[root@kc0 etc]# nslookup nginx
Server:		192.168.0.6
Address:	192.168.0.6#53

Name:	nginx.policy-demo.svc.cluster.local
Address: 10.105.224.53
```
——————————————— 
NOW, FROM WITHIN BUSYBOX (CREATED ON MASTER)
——————————————— 

NOTE: I notice that the Address1 does not have :53 port attached to its IP address.

```
[root@kc0 etc]# kubectl run --namespace=policy-demo access0 --rm -ti --image busybox:1.28 -- /bin/sh
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
/ # cat /etc/resolv.conf
nameserver 10.96.0.10
search policy-demo.svc.cluster.local svc.cluster.local cluster.local corp.target.com
options ndots:5
```

NSLOOKUP BY NGINX SERVICE-NAME FAILS
```
/ # nslookup nginx.policy-demo.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'nginx.policy-demo.svc.cluster.local'
```

NSLOOKUP BY CLUSTER IP OF NGINX JUST RETURNS THE IP ITSELF
```
/ # nslookup 10.105.224.53
Server:    10.96.0.10
Address 1: 10.96.0.10

Name:      10.105.224.53
Address 1: 10.105.224.53
```
———————————
COREFILE
———————————
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```
Thanks.

**Comment by coderdba** [comment]
————————————————
LOGS FROM COREDNS PODS
————————————————

NOTE: 10.0.2.15 is the NAT IP of virtualbox VM that is the master

On master, resolv.conf:  (note, that these nameservers are company’s - not the pod/cluster IP of coredns)
search corp.mycompany.com
nameserver <nameserver1 IP>
nameserver <nameserver2 IP>
```
root@kc0 ~]# pods |grep coredns
kube-system   coredns-86c58d9df4-dcl97                   1/1     Running   3          17d   192.168.0.7      kc0    <none>           <none>
kube-system   coredns-86c58d9df4-kh5wv                   1/1     Running   3          17d   192.168.0.8      kc0    <none>           <none>
```
NOW, CREATED BUSYBOX AND DID 
1. nslookup nginx
2. nslookup nginx.policy-demo.svc.cluster.local

FIRST POD
```
[root@kc0 ~]# kubectl logs --namespace=kube-system pod/coredns-86c58d9df4-dcl97 -c coredns
.:53
2019-01-11T05:35:11.432Z [INFO] CoreDNS-1.2.6
2019-01-11T05:35:11.432Z [INFO] linux/amd64, go1.11.2, 756749c
CoreDNS-1.2.6
linux/amd64, go1.11.2, 756749c
 [INFO] plugin/reload: Running configuration MD5 = 2394cf331ea25e9aacc36ddf69fafcdb
2019-01-11T05:35:31.442Z [INFO] 127.0.0.1:35714 - 33653 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.009730188s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:59622-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:34.436Z [INFO] 127.0.0.1:46008 - 31332 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.003463407s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:42092-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:37.437Z [INFO] 127.0.0.1:57485 - 15788 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.002684803s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:57998-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:40.439Z [INFO] 127.0.0.1:37389 - 24779 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.003147722s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:34882-><NAMESERVER2 IP> :53: i/o timeout
2019-01-11T05:35:43.439Z [INFO] 127.0.0.1:48527 - 43082 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.002736565s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:40021-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:46.453Z [INFO] 127.0.0.1:60082 - 23479 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.011064001s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:50387-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:49.453Z [INFO] 127.0.0.1:54767 - 36885 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.010987482s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:45057-><NAMESERVER2 IP> :53: i/o timeout
2019-01-11T05:35:52.454Z [INFO] 127.0.0.1:54029 - 22696 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.010596859s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:40178-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:55.457Z [INFO] 127.0.0.1:40736 - 63050 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.013236405s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:57299-><NAMESERVER2 IP> :53: i/o timeout
2019-01-11T05:35:58.45Z [INFO] 127.0.0.1:60905 - 40930 "HINFO IN 6943969105224694106.541383633054051657. udp 56 false 512" SERVFAIL qr,rd 56 20.004786018s
 [ERROR] plugin/errors: 0 6943969105224694106.541383633054051657. HINFO: unreachable backend: read udp 192.168.0.7:43934-><NAMESERVER1 IP> :53: i/o timeout
```
SECOND POD
```
[root@kc0 ~]# kubectl logs --namespace=kube-system pod/coredns-86c58d9df4-kh5wv -c coredns
.:53
2019-01-11T05:35:12.577Z [INFO] CoreDNS-1.2.6
2019-01-11T05:35:12.577Z [INFO] linux/amd64, go1.11.2, 756749c
CoreDNS-1.2.6
linux/amd64, go1.11.2, 756749c
 [INFO] plugin/reload: Running configuration MD5 = 2394cf331ea25e9aacc36ddf69fafcdb
2019-01-11T05:35:32.581Z [INFO] 127.0.0.1:58277 - 52764 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.004311987s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:53295-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:35.6Z [INFO] 127.0.0.1:34997 - 26117 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.022537074s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:47704-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:38.581Z [INFO] 127.0.0.1:48726 - 44286 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.00246124s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:34317-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:41.59Z [INFO] 127.0.0.1:37535 - 33135 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.009592869s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:33543-><NAMESERVER2 IP> :53: i/o timeout
2019-01-11T05:35:44.584Z [INFO] 127.0.0.1:42536 - 6078 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.002890565s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:45488-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:47.597Z [INFO] 127.0.0.1:44063 - 27711 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.014233216s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:60202-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:50.606Z [INFO] 127.0.0.1:39350 - 751 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.005796451s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:41470-><NAMESERVER2 IP> :53: i/o timeout
2019-01-11T05:35:53.61Z [INFO] 127.0.0.1:43980 - 4914 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.009197625s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:32769-><NAMESERVER1 IP> :53: i/o timeout
2019-01-11T05:35:56.617Z [INFO] 127.0.0.1:36012 - 42395 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.015513177s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:49979-><NAMESERVER2 IP> :53: i/o timeout
2019-01-11T05:35:59.621Z [INFO] 127.0.0.1:59607 - 49350 "HINFO IN 8107871744847485095.4039094654292338621. udp 57 false 512" SERVFAIL qr,rd 57 20.005645379s
 [ERROR] plugin/errors: 0 8107871744847485095.4039094654292338621. HINFO: unreachable backend: read udp 192.168.0.8:57826-><NAMESERVER1 IP> :53: i/o timeout
```

**Comment by chrisohaver** [comment]
OK - this may be a cluster-ips cross-node networking problem ...

You have logging enabled in CoreDNS, but there is no record of the DNS query for `nginx` being received, so it seems that Kubernetes cluster is not properly routing the request to the CoreDNS pod.

Of the three pods in play (coredns, busybox, and nginx), what nodes are they being scheduled on?
Per chance are  busybox, and nginx scheduled on one node, and coredns on a separate node?

On a side note: The "unreachable backend" errors indicate that your upstream dns server (the one in `/etc/resolv.conf`) is non-responsive.  This will cause problems for _external_ lookups, but would not affect internal lookups of k8s services.

**Comment by coderdba** [comment]
Hi,

nginx is running on worker node kc1.
coredns is running on two pods - both on master node kc0.
busybox - tried from both kc0 (master) and kc1 (worker) - but found the same behavior.

My thought is similar to yours - that coredns is not receiving the query.  
However, if I place the pod IP of coredns in the master node's /etc/resolv.conf, then it does resolve.  - So, cluster IP of coredns service (kube-dns) is not receiving the request somehow from busybox, while pod-ip does receive when queried from outside of busy box.  

Thanks
Gowrish

**Comment by chrisohaver** [comment]
Try scheduling the coredns pods on the worker node and see if that changes anything.
Assuming you have no-schedule taint on the master, you could do this by removing the tolerance in the coredns deployment.

**Comment by coderdba** [comment]
Hi,

I scaled coredns pod to create two more replicas - which it created in worker node kc1.

With that (now 2 pods each in master and worker), nslookup went to look in our company's nameserver !

/ # nslookup nginx
Server:    10.96.0.10
Address 1: 10.96.0.10 nameserver1.mycompany.com

nslookup: can't resolve 'nginx'

Then, I scaled back coredns to 2 nodes - which terminated the two pods in worker node kc1.
Now, nslookup started behaving like before  - not resolving the name.
/ # nslookup nginx
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'nginx'

And, this happens with nslookup of anything - even non existent thing like 'nslookup x'

**Comment by coderdba** [comment]
Hi,

It looks like the problem was because the pods-network-cidr I used overlapped with the IP range of my VMs on which K8 was running.
IP of the nodes - 192.168.11.10, 192.168.11.11 and so on
CIDR - 192.168.0.0/16

FIX:
Change CIDR to a different range:  172.16.0.0/16

With this fix, nslookup, curl and interpod communication is working fine.

Thank you

**Comment by coderdba** [comment]
Working now - fix as mentioned in the last comment above.
