### ISSUE TITLE
Get an error message  when trying to do : "Check out the project and do dependency resolution"

### ISSUE THREAD

**Issue by shlao** [coredns/coredns#2447]
Build CoreDNS from scratch with the following steps
1. Install golang
$ go version
go version go1.11.2 linux/amd64

2.  Check out the project and do dependency resolution
$ go get github.com/coredns/coredns
   github.com/coredns/coredns/core/dnsserver
go/src/github.com/coredns/coredns/core/dnsserver/register.go:252:5: cannot use new(Server) (type *Server) as type caddy.GracefulServer in assignment:
        *Server does not implement caddy.GracefulServer (missing WrapListener method)

3. git master
$ git log
commit 18f25dbef3a33092925e48e7d7f9c8d8f744cd05

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Get an error mess..." ]
>
>Build CoreDNS from scratch with the following steps
>1. Install golang
>$ go version
>go version go1.11.2 linux/amd64
>
>2.  Check out the project and do dependency resolution
>$ go get github.com/coredns/coredns
>   github.com/coredns/coredns/core/dnsserver
>go/src/github.com/coredns/coredns/core/dnsserver/register.go:252:5: cannot use new(Server) (type *Server) as type caddy.GracefulServer in assignment:
>        *Server does not implement caddy.GracefulServer (missing WrapListener method)
>
>3. git master
>$ git log
>commit 18f25dbef3a33092925e48e7d7f9c8d8f744cd05

You need to git clone and then make

**Comment by shlao** [comment]
@miekg  Thanks,  the building process is successful.
But  It is better that no error message arises  when following the [guide](https://github.com/coredns/coredns#compilation-from-source)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Get an error ..." ]
>@miekg  Thanks,  the building process is successful.
>But  It is better that no error message arises  when following the [guide](https://github.com/coredns/coredns#compilation-from-source)

Ah thanks. Yes that needs to be changed.

**Comment by shlao** [comment]
PR-2449 is great 
I have been verified it as follow: 
$ mkdir -p $GOPATH/src/github.com/coredns
$ git clone https://github.com/coredns/coredns $GOPATH/src/github.com/coredns/coredns
$ cd $GOPATH/src/github.com/coredns/coredns; make
