### ISSUE TITLE
plugin/forward: provide the IP of proxy that resolve the DNS request as metadata

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#2450]
My target is to be able to Log that information.

As Plugin Log is accepting metadata under the format {/label},
I propose that plugin Forward implements `Provider`, and return that IP under the label `forward/resolving_proxy`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/forward: p..." ]
>My target is to be able to Log that information.
>
>As Plugin Log is accepting metadata under the format {/label},
>I propose that plugin Forward implements `Provider`, and return that IP under the label `forward/resolving_proxy`

think this is already exported with the metrics, so not sure what it adds to use 
the logs for this as well as that is as much larger impact on performance.
