### ISSUE TITLE
race condition for health status during new cluster init

### ISSUE THREAD

**Issue by jorhett** [coredns/coredns#2453]
Kubernetes 1.13.1 from repo, includes coredns 1.2.6 with stock Corefile

```
# kubectl -n kube-system logs coredns-86c58d9df4-jgqqb
.:53
2019-01-09T22:59:24.456Z [INFO] CoreDNS-1.2.6
2019-01-09T22:59:24.456Z [INFO] linux/amd64, go1.11.2, 756749c
CoreDNS-1.2.6
linux/amd64, go1.11.2, 756749c
 [INFO] plugin/reload: Running configuration MD5 = f65c4821c8a9b7b5eb30fa4fbc167769
 [ERROR] plugin/errors: 2 8872486159225130306.222904406079301335. HINFO: unreachable backend: read udp 10.32.0.5:51857->10.228.113.141:53: i/o timeout
 [ERROR] plugin/errors: 2 8872486159225130306.222904406079301335. HINFO: unreachable backend: read udp 10.32.0.5:55687->10.228.113.90:53: i/o timeout
 [ERROR] plugin/errors: 2 static.nvd.nist.gov.rsc.humad.com. AAAA: unreachable backend: read udp 10.32.0.5:33561->10.228.113.141:53: i/o timeout
 [ERROR] plugin/errors: 2 8872486159225130306.222904406079301335. HINFO: unreachable backend: read udp 10.32.0.5:57755->10.228.113.90:53: i/o timeout
 [ERROR] plugin/errors: 2 8872486159225130306.222904406079301335. HINFO: unreachable backend: read udp 10.32.0.5:55204->10.228.113.141:53: i/o timeout
 [ERROR] plugin/errors: 2 8872486159225130306.222904406079301335. HINFO: unreachable backend: read udp 10.32.0.5:55493->10.155.105.203:53: i/o timeout
 [ERROR] plugin/errors: 2 static.nvd.nist.gov. AAAA: unreachable backend: read udp 10.32.0.5:56258->10.228.113.141:53: i/o timeout
 [ERROR] plugin/errors: 2 ip-10-206-6-94.rsc.humad.com. A: unreachable backend: read udp 10.32.0.5:38391->10.155.105.203:53: i/o timeout
 [ERROR] plugin/errors: 2 ip-10-206-6-189.rsc.humad.com. AAAA: unreachable backend: read udp 10.32.0.5:46450->10.228.113.141:53: i/o timeout
 [INFO] SIGTERM: Shutting down servers then terminating
```
Testing using dnstools, all of the named servers were responding just fine. Turns out this was due to the healthcheck failing:
```
Liveness probe failed: Get http://10.32.0.4:8080/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I confirmed that the health plugin wasn't answering via curl on the node hosting the container. It could query DNS from startup time until the healthcheck killed it.

I fixed it by hacking out the readiness check. `kubectl edit deployment coredns -n kube-system` and deleting that block. The DNS containers stayed up, and the health check is now responding.

**Comment by johnbelamaric** [comment]
The Kubernetes plugin will return "not healthy" while waiting for the
initial apiserver sync to be complete. If you have a lot of services, it
could be that that is taking too long. Then, it may in turn get killed by
the kubelet and restarted, which will begin a new process that starts to
load the data again...

You could increase the `initialDelaySeconds` in the liveness probe of the
container, rather than removing the check altogether.

**Comment by johnbelamaric** [comment]
@rajansandeep, @fturib, @chrisohaver the HasSynced() check makes more sense
as a readiness probe than a health check. We may want to implement a
parallel "Readier" ("Readyer"?) interface and put the HasSynced() in there
instead.

**Comment by jorhett** [comment]
> The Kubernetes plugin will return "not healthy" while waiting for the initial apiserver sync to be complete. If you have a lot of services, it could be that that is taking too long.

Not in this case, it was a test sandbox cluster with jenkins, prometheus, grafana... and that's about it. Not even a half dozen deployments.

Also of note: it wasn't that the health check was returning unhealthy, it was not "answering the phone" -- it would time out without a response.

**Comment by chrisohaver** [comment]
>@rajansandeep, @fturib, @chrisohaver the HasSynced() check makes more sense
as a readiness probe than a health check. We may want to implement a
parallel "Readier" ("Readyer"?) interface and put the HasSynced() in there
instead.


There is a dusty to-do to review and fix this ... https://github.com/coredns/deployment/issues/63

There are two types of health checks in k8s _readiness_, and _liveness_.  Readiness controls whether or not traffic will be routed to the pod.  Liveness controls when we kill the pod and spin up a new one.
What we have now is really a readiness check, but labeled as a liveness check, which can be problematic.

I don't think we need to add a new Readier interface... i think we can use the existing health check in both capacities. 

We could change what we have now, to be labeled a _readiness_ check.  While the readiness check reports not ready, k8s will not route traffic to it... but it doesn't kill the pod.  If liveness check failures exceed tolerances, then the pod is restarted.

A _liveness_ check could just check that we get any response at all from the health check, with appropriate delay and tolerances copied from the exiting check.

**Comment by chrisohaver** [comment]
> Also of note: it wasn't that the health check was returning unhealthy, it was not "answering the phone" -- it would time out without a response.

hmm - thats not the intended/expected behavior...  It should respond with a "not healthy" ... so that may need to be fixed.  There is one issue that can cause the health plugin to stop responding.  If it's still around, it occurs when the reload plugin tries to load an invalid config change ... which doesn't appear to have been the case here.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] race conditio..." ]
>> The Kubernetes plugin will return "not healthy" while waiting for the initial apiserver sync to be complete. If you have a lot of services, it could be that that is taking too long.
>
>Not in this case, it was a test sandbox cluster with jenkins, prometheus, grafana... and that's about it. Not even a half dozen deployments.
>
>Also of note: it wasn't that the health check was returning unhealthy, it was not "answering the phone" -- it would time out without a response.

The shared (between plugin) health is I think a mistake. Even when the endpoint 
is not ready (when cycling your API servers (see other bugs) you cache might be 
perfectly fine.

As such I propose to return health to its original status; server is up and 
running

As the kubernetes health has a network component in it *as well* any network 
hiccup will kill the server; def. not something you wont; hence: remove it.

**Comment by miekg** [comment]
this has been replaced with a *ready* plugin.
