### ISSUE TITLE
CoreDNS 1.3.1 tracking bug

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2455]
Tracking bug for 1.3.1 release.

Small release, useful for announcing some backward incompat stuff going out in the next (1.4.0) release.

**Comment by yongtang** [comment]
Deprecation of multiple endpoints is in #2454 (note it depends on another PR coredns/ci#85)

**Comment by miekg** [comment]
Might not call this release done until I understand: https://github.com/coredns/coredns/issues/2459

**Comment by miekg** [comment]
announced and released.
