### ISSUE TITLE
High memory usage in k8s (was: plugin/cache: change to per RRset)

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2469]
Currently we cache whole packets (dns.Msg structs), this works, but can be inefficient because

1. that's more data, than we need to a client
2. RRsets can be more easily shared between replies.

There are of course some things that are more complex

* the additional data can be cached, but you have to mark it as such (*additional). Not 100% sure what the actual standard in the industry. Not RFC comes to mind

Other than that it might actually be not that hard. DNSSEC must of course be supported. We can re-use the current data structures, except point to RRsets. The assembling of a message is slightly more work. Even the `class` should just work, if done right of course.

**Comment by szuecs** [comment]
To show the numbers in our tests, created by https://github.com/mikkeloscar/go-dnsperf

RPS
![image](https://user-images.githubusercontent.com/50872/51237106-16be9400-1974-11e9-88c3-7bbb37ea0b91.png)

Memory
![image](https://user-images.githubusercontent.com/50872/51237184-33f36280-1974-11e9-8979-9a3d08b3fce3.png)

During an outage we had 18k RPS and 800MB memory consumption per CoreDNS instance. Before the outage we had 3.5k RPS and 64MB memory consumption per CoreDNS instance.


The usage pattern in test and outage are to have a couple of external (not cluster.local) DNS names to resolve. 
[CoreDNS configuration](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/coredns-local/configmap.yaml )
[CoreDNS deployment](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/coredns/deployment-coredns.yaml)


Do you have a goroutine per request model similar to `http.ServeHTTP` in stdlib?

**Comment by fturib** [comment]
@szuecs : Just an information about the use case you brought (and thanks for sharing it!):

The default cache size has been downsized in CoreDNS v1.2.2: instead of 110k entries (in former versions including yours - and you cannot tune lower), you have now, by default, 10k entries. And you can now set its value down to 1024. (Each value is per cache, and there are 2 caches - one for positives replies, one for negative replies). 

The effect, I believe is this "plateau" after the burst of 8k/qps : the cache is full, and keeps the memory high (143MBi in your case).

**It does not explain the peek** at 250MiB, although - If I am right about the cache, and it is full at smaller capacity - the hight of the peek should be lower.

**Comment by miekg** [comment]
> Do you have a goroutine per request model similar to http.ServeHTTP in stdlib?

yes, although it runs in a worker model; each worker processes 50? (a 100? forgot goroutines) before quitting and then we start a new one.

Did you see an abnormal increase in goroutines as well?

Regarding the cache:

I'll update here once I have a per-RR idea, because it does make things complex in some parts and I wonder how much re-use we actually see by storing RRsets.
Another idea I had was to rip out things we currently cache, but are clearly not needed. We could through away all whole bunch of meta data.
It also still needs to perform (and we need to perf tests it as well), so there are a bunch of design constraints the make this hard.

**Comment by szuecs** [comment]
@miekg dropping parts of metadata that you don’t need would be very good to reduce the memory size. I will check tomorrow again the metrics and get back to you.

**Comment by miekg** [comment]
So we currently cache
~~~
type item struct {
	Rcode              int
	Authoritative      bool
	AuthenticatedData  bool
	RecursionAvailable bool
	Answer             []dns.RR
	Ns                 []dns.RR
	Extra              []dns.RR

	origTTL uint32
	stored  time.Time

	*freq.Freq
}
~~~
this is not completely crazy. Stripping this is possible, but then we need to reassemble it which take time, but this might be OK.

Are you sure the memory is allocated by the cache plugin btw?

**Comment by miekg** [comment]
NXDOMAIN and NODATA responses can be collapsed probably per domain, that should save a bunch, assuming that is the majority of responses. 

Of course the same benefit will be had, if we implemented RRset cache

**Comment by szuecs** [comment]
@miekg looks also like a legit data structure to cache for me. Not sure what dns.RR contains for the different members.

The test was done with less than 100 different domain names to resolve to record types A/AAAA/CNAME. I think CoreDNS will likely not try to cache duplicates more than once.

It could be also a Go bug that if you have too many incoming requests it piles up the Go runtime memory. I have no idea, if this was the case. Best would be to measure it and check Go runtime metrics for Heap vs. container memory usage.

**Comment by miekg** [comment]
To flesh some ideas:

1. Use RRset cache, so identical RRset are only cached once - this is a big rewrite. We would still need a way to lookup what's needed for a specific response. I.e. suppose we store all data in an RRset cache and you look up www1.miek.nl +dnssec, which returns
~~~
; AUTHORITY SECTION:
www.miek.nl.		14399	IN	NSEC	miek.nl. CNAME RRSIG NSEC
www.miek.nl.		14399	IN	RRSIG	NSEC 8 3 14400 20190305031301 20190203031301 12051 miek.nl. JNEwymzVB75rImXQoSCfJe+QZt3SdDSNn7WZyiz8HX8S6p2lmRdiVhUw 691ERDce43EtAQQ0PNryfr7K+VKndkDptMbX3kSd7Gj6U7upDwUId5i9 Ir/C62Uf1YWgdpFTrnyZN05YwsvaGLV3enKfHoVVzuSBS+zxjtjik5Jw iHs=
miek.nl.		14399	IN	NSEC	a.miek.nl. A NS SOA HINFO MX AAAA RRSIG NSEC DNSKEY
miek.nl.		14399	IN	RRSIG	NSEC 8 2 14400 20190305031301 20190203031301 12051 miek.nl. wGUXHrOuXGmF0hdFk2gTt+5haPykpl6PUN0HLDHg2zQkqC4BwdHvVDe7 cguRqp9HOBOUBzIto6sBTIxpYtcpYTcLvo1ALTH29mNBt7SZQecZGEz1 d4YygQHvk+7tgjHsmF260KHugKlh2SNxgcN/5qUAA8jaTOxgvTP+yg7a 4oQ=
miek.nl.		1799	IN	SOA	linode.atoom.net. miek.miek.nl. 1549167181 14400 3600 604800 14400
miek.nl.		1799	IN	RRSIG	SOA 8 2 1800 20190305031301 20190203031301 12051 miek.nl. PFC/zV6S+2lKfnD6DGPTMigEc1e6zHTLQXkExgCqVn+SubEf44hCR9E4 3jiKWY0Gg4hBcAF/mMY1TgB4zEyowAq3omwIAM8dOx77khO5dfujWMmg tHnn8H+rAf/iDLH+DVCZ9r1Ikv22xRNQTRURbwWvtWK6MiFiyGGcFrcr Z8I=
~~~
For this to work we should also cache that `www.miek.nl` returns such a response. I was thinking this would need a second level. I.e. we store all the rrset here *and* a list like:
~~~
miek.nl SOA, NSEC
www.miek.nl NSEC
~~~
(the RRSIG is implied). Then when constructing the response we find this and lookup the rrsets for these types and create a reply. This is more expensive for a few answers, but allows re-use of the RRsets.

2. Keep parts of the current impl. And ditch the authority section, ditching the additional section might be harder as we want to keep IP address for the SRV records (e.g)

Another thing that struck me while thinking about this, is that we probably cache unneeded NXDOMAINs. I.e. when `www.miek.nl` does not exist, `a.www.miek.nl` can't exist so we can just not cache those and reply with response for `www.miek.nl` - this is also not a hard change, but requires multiple lookups to determine a higher NXDOMAIN is cached.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/2527 out for review (and possibly to test).

Got another idea, but it will probably impact performance, but we might just need a separate pass for that, to just pack the rrdata we save, pull out ownername, TTL, class, we're copying these *anyway* to we can just modify them in the process.

**Comment by miekg** [comment]
OK, and circling back, any further optimization will need to come from a larger rewrite to per rrset: https://github.com/coredns/coredns/issues/2469#issuecomment-460067450 option nr 1.

So we keep two caches actually, one with shortened data from the reply, in case of the DNSSEC reply for www1.miek.nl:
~~~
miek.nl. , SOA	
miek.nl., RRSIG	
miek.nl., NSEC	
miek.nl.  RRSIG	
www.miek.nl., NSEC	
www.miek.nl.	RRSIG	
~~~
possibly optimize to only store miek.nl once. Expiration and prefetch will be done on this item, just like in the current cache.

This then references by name,type a second cache with the actual RRs, in this case that holds:
~~~
miek.nl. SOA ...
miek.nl. RRSIG(NSEC, SOA)
miek.nl. NSEC
www.miek.nl. NSEC
www.miek.nl. RRSIG
~~~
And then the saving only come for other NXDOMAINs (in this case) the reference the same SOA record.
Care must be taken when we remove an item from the cache that we then also remove the referenced RRSets.

In essence we could consider the RRset cache some sort of backing store for the first cache.

**Comment by fturib** [comment]
@szuecs: did you make the same try and check the memory with an image of CoreDNS that is >= 1.2.2 ?
I am wondering how much work on memory is really needed when the number of entries in the cache is reduced to 10k (instead of the current 110k you have right now with the image 1.2.0).

Although you say you have less than 100 different domain ... 
so, the memory consumption should not come from the cache, right ?

**Comment by szuecs** [comment]
@fturib yes it should not be from the cache as far as I understand. Also the ndots 5 + search path -> 10 dns requests per hostname to resolve does not explain the memory usage with the cache.

**Comment by szuecs** [comment]
I wrote in a tweet this information:

- CoreDNS with 100Mi could handle ~5-6k RPS (beyond that crashing CoreDNS)
- CoreDNS with 1000Mi could handle ~10-11k RPS (beyond that crashing CoreDNS)
- dnsmasq in front we can handle with 100Mi 35k RPS without crash

RPS was measured on a single node m4.2xlarge in AWS FRA.
The setup will very fast fill your conntrack settings, so we installed an iptables rule to bypass conntrack tables for the node local path: `applicationPod ->  dnsmasq -> coredns`

**Comment by miekg** [comment]
Thanks. Was about the run a similar test.

Memory usage seems to be the core culprit here and leading to cache
eviction slowing the whole thing down, single cache miss and waiting for a
resolve slows thing down immensely.

**Comment by miekg** [comment]
@chrisohaver and @fturib might also want to help here to get a fix out (and figure out how to can easily test for this, 'cause a unit test won't cut it [Also see #2523])

**Comment by fturib** [comment]
Sorry, but I am very busy with escalations on other project that take my whole time, week-end included.

This Issue is a bit confusing:
- it is created for a cache refactoring
- and there is a description of a perf test . that has memory issues, but nothing right now linked it to a cache memory issue (AFAIK).

@miekg : when you say "might also want to help here to get a fix out" I guess you refer to the problem raised here by @szuecs. Am I Correct?
@szuecs : can you create a separated ticket for your problem ?

**QUESTION to @szuecs:**
>I wrote in a tweet this information:
>
>* CoreDNS with 100Mi could handle ~5-6k RPS (beyond that crashing CoreDNS)
>* CoreDNS with 1000Mi could handle ~10-11k RPS (beyond that crashing CoreDNS)
>* dnsmasq in front we can handle with 100Mi 35k RPS without crash

This test is run under the same conditions as [test reported above](https://github.com/coredns/coredns/issues/2469#issuecomment-454710185) ?
I mean:
- CoreDNS v 1.2.0
- and a Corefile configuration that includes `template` and `pprof` (I am not sure of the impact of these plugins when it comes to QPS tests)

**Comment by miekg** [comment]
So I'm trying to look into memory only at this point. And I have a hard time replicating things. This is with a stripped down coredns, i.e. only prometheus, forward, cache and whois (and various variants to try things out).

Standard Corefile:
~~~
. {
    #forward . 192.168.87.1
    cache
    prometheus
    whoami
}
~~~

I query this with a alexa top-1m list (in 1k, 10k, 100k increments) - in this case it hits whoami and returns a silly response like.
~~~
;; ADDITIONAL SECTION:
blogspot.com.		5	IN	AAAA	::1
_udp.blogspot.com.	5	IN	SRV	0 0 49638 .
~~~
This *is* cached however.

Prometheus queries it and I can get pprof for allocs. This maxes out for `process_resident_memory_bytes` to about 50 M, goroutine count is below 200.

It went from 1k names to 10k that increased the memory from 38M to 50M (that's clearly a lot of memory). 10k items in a single cache is also the default max and that looks OK as well.

I'll dig some more and add some collaborating data to this issue.

**Comment by fturib** [comment]
I am not sure we are on the same page for the issue explained by @szuecs.

He said on a [comment above](https://github.com/coredns/coredns/issues/2469#issuecomment-460058895):
>The test was done with less than 100 different domain names to resolve to record types A/AAAA/CNAME. I think CoreDNS will likely not try to cache duplicates more than once.

So I [asked a confirmation:](https://github.com/coredns/coredns/issues/2469#issuecomment-461597357)
>Although you say you have less than 100 different domain ...
>so, the memory consumption should not come from the cache, right ?

And @szuecs replied:
>@fturib yes it should not be from the cache as far as I understand. Also the ndots 5 + search path -> 10 dns requests per hostname to resolve does not explain the memory usage with the cache.


Am I mis-understanding something ? 
Or the cache is involved in another way ?

**Comment by szuecs** [comment]
We used this config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    application: coredns
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```
If you need the version from the outage and start params of the deployment: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dc008aa07ae480d9ba25dc9f6ca8d9d56aa813f4/cluster/manifests/coredns/deployment-coredns.yaml

> Sorry, but I am very busy with escalations on other project that take my whole time, week-end included.
> 
> This Issue is a bit confusing:
> 
>     * it is created for a cache refactoring
> 
>     * and there is a description of a perf test . that has memory issues, but nothing right now linked it to a cache memory issue (AFAIK).
> 
> 
> @miekg : when you say "might also want to help here to get a fix out" I guess you refer to the problem raised here by @szuecs. Am I Correct?
> @szuecs : can you create a separated ticket for your problem ?

yes

> 
> **QUESTION to @szuecs:**
> 
> > I wrote in a tweet this information:
> > 
> > * CoreDNS with 100Mi could handle ~5-6k RPS (beyond that crashing CoreDNS)
> > * CoreDNS with 1000Mi could handle ~10-11k RPS (beyond that crashing CoreDNS)
> > * dnsmasq in front we can handle with 100Mi 35k RPS without crash
> 
> This test is run under the same conditions as [test reported above](https://github.com/coredns/coredns/issues/2469#issuecomment-454710185) ?
> I mean:
> 
>     * CoreDNS v 1.2.0

Yes: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/coredns-local/daemonset-coredns.yaml

> 
>     * and a Corefile configuration that includes `template` and `pprof` (I am not sure of the impact of these plugins when it comes to QPS tests)

Current tests are done with https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/coredns-local/configmap-local.yaml

**Comment by szuecs** [comment]
I created #2593 as follow up

**Comment by miekg** [comment]
gonna mark this a dup of #2593
