### ISSUE TITLE
plugin/auto not reloading files

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2471]
Marking this down as a possible issue for now.
Will debug and try to pinpoint this sooner than later.

**Comment by stp-ip** [comment]
So this seems to fail reloading:
```
      auto {
        directory /etc/source/files/zones/ (.*) {1} 30
        transfer to *
      }
```

This works:
```
      auto {
        directory /etc/source/files/zones/ (.*) {1}
        reload 30s
        transfer to *
      }
```

Debugging...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/auto n..." ]
>So this seems to fail reloading:
>```
>      auto {
>        directory /etc/source/files/zones/ (.*) {1} 30
>        transfer to *
>      }
>```
>
>This works:
>```
>      auto {
>        directory /etc/source/files/zones/ (.*) {1}
>        reload 30s
>        transfer to *
>      }
>```
>
>Debugging...

geh. Odd. Curious to any outcomes here.

**Comment by stp-ip** [comment]
Had a bit to take another stab at it.

So a few things to write it down already:
* `reload` is the interval to reload a zone. So if it changes on disk, the change will be read in.
* `timeout` is the interval to walk the directory. So if a file/zone got added or removed, the zone would be added or removed.
* we only test removing a file and switching symlinks within the watcher tests

The file plugin takes care of checking if a file is updated.

So they are needed in combination. While writing this #2516 comes up with defaulting it within auto, which sets the reload timer so file is actually checking it.
That way the removal and addition of files is checked (via auto) and the actual zones or SOA is checked (via file).

**Comment by miekg** [comment]
this is now fixed?

**Comment by stp-ip** [comment]
Yes fixed and in the process of moving to a simpler config.
