### ISSUE TITLE
Move to gomods

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2474]
Gomods is the new kid on the block and simplifies the GOPATH issues and in the long term vendoring. Any thoughts on moving to gomods? Caddy didn't yet so it might make it harder.

**Comment by miekg** [comment]
We should probably. Don't know how hard it is and it doesn't solve a direct
problem we have atm

**Comment by stp-ip** [comment]
I agree, but wanted to track it nonetheless. Might be a good starter issue so.

**Comment by Xuanwo** [comment]
https://github.com/coredns/coredns/pull/2503 will finish this job.

**Comment by miekg** [comment]
this is done!
