### ISSUE TITLE
 What would be the best way to add support for my library drbl-peer? plugins?

### ISSUE THREAD

**Issue by elico** [coredns/coredns#2475]
I wrote a golang library named https://github.com/elico/drbl-peer
and I was thinking about a way to integrate this library with coredns when it's in proxy mode.

The idea is that the library will first process the A/AAAA queries and will return a specific "blackhole" ip that will block access to specific sites based on public blacklists in real-time.

**Comment by johnbelamaric** [comment]
I think you may want to integrate it in the upcoming firewall plugin #2335, as another type of engine. @fturib

**Comment by miekg** [comment]
Yes, just make a plugin that does this. See https://github.com/miekg/block for something similar

**Comment by miekg** [comment]
think this is answered and can be closed.
