### ISSUE TITLE
coredns binary includes go's testing package

### ISSUE THREAD

**Issue by bfallik** [coredns/coredns#2476]
It appears that the coredns 1.3.1 linux arm binary is built such that it's pulling in the [go testing package](https://golang.org/pkg/testing/) as a dependency. As a go developer myself I've done this accidentally in the past. Usually the test code is harmless but it bloats the binary, confuses the help output, and could potentially cause more confusion if a user invokes a testing argument that attempts to run test or benchmarks.

Obviously feel free to close this issue if this is intentional or expected.

```
$ tar xvf coredns_1.3.1_linux_arm.tgz 
coredns
$ ./coredns --help
Usage of ./coredns:
  -conf string
    	Corefile to load (default "Corefile")
  -cpu string
    	CPU cap (default "100%")
  -dns.port string
    	Default port (default "53")
  -pidfile string
    	Path to write pid file
  -plugins
    	List installed plugins
  -quiet
    	Quiet mode (no initialization output)
  -test.bench regexp
    	run only benchmarks matching regexp
  ...
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] coredns binary in..." ]
>Obviously feel free to close this issue if this is intentional or expected.

iirc it only take one go file to import something, this can be in the coredns 
code or in any of deps...

**Comment by bfallik** [comment]
@miekg yes, that's correct.

I don't know my way around this code base but it looks like (at least) two packages import "testing" outside of `xxx_test.go` files:
```
$ git grep '\"testing\"' | grep -v _test.go
Gopkg.lock:    "testing",
plugin/metrics/test/scrape.go:	"testing"
plugin/test/helpers.go:	"testing"
```

"plugin/test" seems to be imported from all of the plugin test code but also from
```
$ git grep 'plugin/test\"' | grep -v test.go
plugin/erratic/xfr.go:	"github.com/coredns/coredns/plugin/test"
plugin/file/fuzz.go:	"github.com/coredns/coredns/plugin/test"
plugin/pkg/fuzz/do.go:	"github.com/coredns/coredns/plugin/test" 
```

I didn't dig into `plugin/metrics`.

Two strategies I've used in the past are to either split up packages so that code to support testing never imports `testing` or to use an interface to avoid the dependency. So for example `plugin/test/helpers.go` should either 
* expect an interface that implements the subset of functions from `testing.T` instead of accepting a concrete testing.T, or
* split up plugin/test so that test predicates functions (like `test.Header()`) are in a different package from the code that's intended to be shared with the plugins

**Comment by miekg** [comment]
Thanks for the summery. Should all be easily fixed.

How do you propose we catch future occurrences?

**Comment by bfallik** [comment]
@miekg we created a little script that invokes `go list` to check dependencies for this
```
#!/bin/bash
set -e

TMPL=$(cat <<"EOF"
{{- if (eq .Name "main") -}}
{{range $v := .Deps -}}
 {{if (eq $v "testing") -}}
  {{$.ImportPath | printf "%s imports testing\n"}}
 {{- end}}
{{- end}}
{{- end -}}
EOF
)

go list -f "$TMPL" "$@"
```

**Comment by miekg** [comment]
Ah nice we can probably stuff that in .presubmit

**Comment by bfallik** [comment]
excellent

**Comment by miekg** [comment]
Hmm, for some reason that script only barfs out that the main binary imports testing, but doesn't see any of the packages.

**Comment by yongtang** [comment]
I used the following:
```
go list -f '{{ join .Deps  "\n"}}' | grep testing
```

Before PR #2479 there are `testing` packages, but since PR #2479 has been merged, looks like the issue has been resolved.

**Comment by yongtang** [comment]
@bfallik I am closing this issue as it has been resolved, but feel free to re-open if the issue persists.

**Comment by yongtang** [comment]
Added a PR #2480 for presubmit check as a follow up.

**Comment by bfallik** [comment]
thanks @yongtang and @miekg
