### ISSUE TITLE
middleware/kubernetes: TLS support

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#248]
Need TLS support for the K8s endpoint.

**Comment by aledbf** [comment]
@johnbelamaric just in case, if you do not specify the endpoint and run `coredns` as a pod inside the cluster it will use SSL and the configured service account.

**Comment by johnbelamaric** [comment]
@aledbf, are you saying the client code already does that automatically or that you would like it to work that way?

**Comment by aledbf** [comment]
> the client code already does that automatically

Yes (if is running  inside the cluster)

**Comment by johnbelamaric** [comment]
Ok, I tried it yesterday with the pre-TLS code and got an error but maybe the way the client is being initialized is wrong or maybe something is wrong in my k8s setup. I will try again Monday.

**Comment by miekg** [comment]
Is still still an easy, or can it be closed?

**Comment by johnbelamaric** [comment]
We can close this issue, we have the TLS support now, but I still haven't had a chance to try out what @aledbf is suggesting.
