### ISSUE TITLE
plugin/hosts: doesn't respond with NXDOMAIN for non-existing names when `log` plugin is disabled

### ISSUE THREAD

**Issue by akolosov-a** [coredns/coredns#2482]
CoreDNS: 1.3.1

The `hosts` plugin should respond with `NXDOMAIN` status when it can't find an entry for the requested name. In fact it does so ONLY when the `log` plugin is also enabled in the server section. If there is no `log` plugin, CoreDNS responds nothing and DNS requests for non-existing names time out.

Minimal `Corefile` to reproduce the issue (without `log` plugin):
```
test {
    hosts {
        10.0.0.1 host1.test
    }
}
```

Check:
```bash
$ dig host1.test @localhost
...
;; QUESTION SECTION:
;host1.test.			IN	A

;; ANSWER SECTION:
host1.test.		3600	IN	A	10.0.0.1
...
$ dig host2.test @localhost

; <<>> DiG 9.10.6 <<>> host2.test @localhost
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Minimal `Corefile` to reproduce the issue (with `log` plugin enabled):
```
test {
    log
    hosts {
        10.0.0.1 host1.test
    }
}
```

Check:
```bash
$ dig host1.test @localhost
...
;; QUESTION SECTION:
;host1.test.			IN	A

;; ANSWER SECTION:
host1.test.		3600	IN	A	10.0.0.1
...
$ dig host2.test @localhost
...
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43774
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
...
```

Moreover, `log` plugin helps only when it logs all the requests. With `class error` option set for `log` plugin, CoreDNS also doesn't respond to the requests.

Usage of an external file for hosts entries also doesn't affect the described behaviour.

Enabling `debug` and `errors` plugins doesn't affect the issue also and no additional information can be seen from the logs if those plugins are enabled.

**Comment by akolosov-a** [comment]
I found an easy fix for that, but I'm not sure if it doesn't affect other plugins:
```diff
diff --git a/plugin/plugin.go b/plugin/plugin.go
index 3ff518ab..d556c25b 100644
--- a/plugin/plugin.go
+++ b/plugin/plugin.go
@@ -92,6 +92,8 @@ func ClientWrite(rcode int) bool {
                fallthrough
        case dns.RcodeFormatError:
                fallthrough
+       case dns.RcodeNameError:
+               fallthrough
        case dns.RcodeNotImplemented:
                return false
        }
```

After that fix the NXDOMAIN response is returned properly without the `log` plugin enabled:

```bash
$ dig host2.test @localhost
...
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 2822
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
...
```

So, the problem is not actually in `hosts` plugin, but in the code of determination of wether plugin has written a response by itself or not, here: https://github.com/coredns/coredns/blob/3533065ed20a7fe14cc00968e3fa8c1beff072b2/plugin/plugin.go#L87

**Comment by akolosov-a** [comment]
Or maybe still better solution is to respond with `NXDOMAIN` right from the plugin itself like the `file` plugin does: https://github.com/coredns/coredns/blob/3533065ed20a7fe14cc00968e3fa8c1beff072b2/plugin/file/file.go#L92

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/hosts: doe..." ]
>CoreDNS: 1.3.1
>
>The `hosts` plugin should respond with `NXDOMAIN` status when it can't find an entry for the requested name. In fact it does so ONLY when the `log` plugin is also enabled in the server section. If there is no `log` plugin, CoreDNS responds nothing and DNS requests for non-existing names time out.

That's indeed odd; the host plugin should probably do this; or maybe not... 
/etc/hosts is not part of the DNS spec; so I'm not sure what the correct 
behavior should be a NODATA response might be safest.

**Comment by miekg** [comment]
Doing this locally just works;
~~~
test.:1053
2019-02-09T17:51:32.789Z [INFO] CoreDNS-1.3.1
2019-02-09T17:51:32.789Z [INFO] linux/amd64, go1.11.4, 
CoreDNS-1.3.1
linux/amd64, go1.11.4, 
2019-02-09T17:51:33.697Z [INFO] [::1]:37907 - 22476 "A IN host1.test. udp 39 false 4096" NOERROR qr,aa,rd 54 0.000064292s
2019-02-09T17:51:34.441Z [INFO] [::1]:47244 - 45517 "A IN host1.test. udp 39 false 4096" NOERROR qr,aa,rd 54 0.000052338s
~~~
Taking your corefile and adding the log plugin.

**Comment by akolosov-a** [comment]
Yes, as I said, it works if you add `log` plugin, but doesn't work without the `log` plugin.

**Comment by miekg** [comment]
it worked with both for me (iirc)

**Comment by akolosov-a** [comment]
The problem is about resolving a non-existing name with the `hosts` plugin. Please try to resolve `host2.test` with this configuration. It doesn't respond to it without `log` plugin.

**Comment by miekg** [comment]
host will never reply nxdomain as this is not required for hosts.

**Comment by akolosov-a** [comment]
Well, then it shouldn't reply NXDOMAIN with `log` plugin enabled either.

**Comment by akolosov-a** [comment]
And at least reply SERVFAIL instead of just timing out.
