### ISSUE TITLE
Rendering corefile into json/yaml & back

### ISSUE THREAD

**Issue by jaxxstorm** [coredns/coredns#2485]
I suspect I know the answer to this, but I figured I'd ask anyway.

I'm trying to build a Corefile with a configuration management system. I looked at the way Caddy handles these files and it seems [there's some JSON language support in there](https://github.com/mholt/caddy/issues/1248#issuecomment-259884591)?

Anyway, is it possible to pass a JSON based config file, or am I looking at writing a plugin?

**Comment by miekg** [comment]
You can't by default, but you can create a caddy config file loader, that
reads whatever you want. We default to the standard loader, so afaict there
is no (easy) way to use your new loader in coredns.

**Comment by miekg** [comment]
closing here, as there isn't much to add, you need to write a config loader.
