### ISSUE TITLE
plugin/proxy - UT TestStop is flaky

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#2507]
- it sometimes fails on my local machine (and surprisingly .. no more today)
- starts to fail now on the Travis CI - see https://travis-ci.org/coredns/coredns/jobs/484495359
from this build https://travis-ci.org/coredns/coredns/builds/484495355?utm_source=github_status&utm_medium=notification
- although a manual kicked test with Travis on the same code was then successful.

```
=== RUN   TestStop
=== RUN   TestStop/Test_0
=== RUN   TestStop/Test_1
=== RUN   TestStop/Test_2
--- FAIL: TestStop (0.07s)
    --- FAIL: TestStop/Test_0 (0.01s)
        proxy_test.go:61: Test 0, Expected healthchecks to hit test server, got none
    --- PASS: TestStop/Test_1 (0.02s)
    --- PASS: TestStop/Test_2 (0.03s)
=== RUN   TestAllowedDomain
--- PASS: TestAllowedDomain (0.00s)
=== RUN   TestProxyParse
--- PASS: TestProxyParse (0.01s)
=== RUN   TestResolvParse
--- PASS: TestResolvParse (0.00s)
=== RUN   TestMaxTo
--- PASS: TestMaxTo (0.00s)
FAIL
FAIL	github.com/coredns/coredns/plugin/proxy	0.122s
```

**Comment by miekg** [comment]
proxy will soon be deleted

**Comment by miekg** [comment]
proxy has been removed, this is now obsolete.
