### ISSUE TITLE
CoreDNS uses a lot memory during initialization phase

### ISSUE THREAD

**Issue by zhouhaibing089** [coredns/coredns#2511]
We are running CoreDNS 1.2.6 with the following Corefile:

```nginx
.:53 {
    errors
    health
    pprof :6060
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        upstream
        fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```

And we have around 5167 endpoints objects in the kubernetes cluster. We find whenever it restarts, it is going to consume a lot of memory. (approaching to 1G)

<img width="981" alt="screen shot 2019-01-28 at 3 34 13 pm" src="https://user-images.githubusercontent.com/4516999/51873489-38276480-2312-11e9-85f4-3b809036f406.png">

It will go back to a normal state with memory usage around 300MB.

This can also be confirmed with go pprof:

**With Alloc Space**

```console
$ go tool pprof --alloc_space http://10.22.205.211:6060/debug/pprof/heap
Fetching profile over HTTP from http://10.22.205.211:6060/debug/pprof/heap
Saved profile in /home/haibzhou/pprof/pprof.coredns.alloc_objects.alloc_space.inuse_objects.inuse_space.012.pb.gz
File: coredns
Type: alloc_space
Time: Jan 28, 2019 at 4:05pm (GMT+7)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1336.06MB, 95.87% of 1393.59MB total
Dropped 55 nodes (cum <= 6.97MB)
Showing top 10 nodes out of 71
      flat  flat%   sum%        cum   cum%
  313.02MB 22.46% 22.46%   313.02MB 22.46%  strings.Join
  264.61MB 18.99% 41.45%   264.61MB 18.99%  bytes.makeSlice
  138.01MB  9.90% 51.35%   245.51MB 17.62%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*EndpointAddress).Unmarshal
  124.94MB  8.97% 60.32%   370.46MB 26.58%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*EndpointSubset).Unmarshal
  112.98MB  8.11% 68.42%   112.98MB  8.11%  github.com/coredns/coredns/vendor/k8s.io/apimachinery/pkg/runtime.(*Unknown).Unmarshal
  107.50MB  7.71% 76.14%   107.50MB  7.71%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*ObjectReference).Unmarshal
  100.26MB  7.19% 83.33%   469.27MB 33.67%  github.com/coredns/coredns/plugin/kubernetes.endpointFQDN
   64.92MB  4.66% 87.99%    64.92MB  4.66%  github.com/coredns/coredns/plugin/kubernetes/object.ToEndpoints
      59MB  4.23% 92.22%       59MB  4.23%  strings.Replace
   50.82MB  3.65% 95.87%    50.82MB  3.65%  github.com/coredns/coredns/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert
```

**Without Alloc Space**

```console
$ go tool pprof http://10.22.205.211:6060/debug/pprof/heap
Fetching profile over HTTP from http://10.22.205.211:6060/debug/pprof/heap
Saved profile in /home/haibzhou/pprof/pprof.coredns.alloc_objects.alloc_space.inuse_objects.inuse_space.013.pb.gz
File: coredns
Type: inuse_space
Time: Jan 28, 2019 at 4:07pm (GMT+7)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 155.78MB, 98.29% of 158.49MB total
Dropped 35 nodes (cum <= 0.79MB)
Showing top 10 nodes out of 37
      flat  flat%   sum%        cum   cum%
   61.47MB 38.78% 38.78%    61.47MB 38.78%  github.com/coredns/coredns/plugin/kubernetes/object.ToEndpoints
      38MB 23.98% 62.76%    65.50MB 41.33%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*EndpointAddress).Unmarshal
   27.50MB 17.35% 80.11%    27.50MB 17.35%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*ObjectReference).Unmarshal
   26.80MB 16.91% 97.02%    26.80MB 16.91%  github.com/coredns/coredns/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert
       1MB  0.63% 97.66%        1MB  0.63%  github.com/coredns/coredns/plugin/kubernetes/object.ToService
    0.50MB  0.32% 97.97%    27.81MB 17.54%  github.com/coredns/coredns/vendor/k8s.io/client-go/tools/cache.(*threadSafeMap).Add
    0.50MB  0.32% 98.29%    27.30MB 17.23%  github.com/coredns/coredns/vendor/k8s.io/client-go/tools/cache.(*threadSafeMap).updateIndices
         0     0% 98.29%    65.50MB 41.33%  github.com/coredns/coredns/plugin/kubernetes.endpointsListFunc.func1
         0     0% 98.29%    89.77MB 56.64%  github.com/coredns/coredns/plugin/kubernetes/object.NewIndexerInformer.func1
         0     0% 98.29%       66MB 41.64%  github.com/coredns/coredns/vendor/github.com/gogo/protobuf/proto.Unmarshal
```

The total in-used memory is around 160MB, but the allocated memory comes to around 1400MB. This sounds scary, we can also see that most of the allocations are coming from `dnstuil.Join` where it calls `strings.Join` heavily.

**Comment by chrisohaver** [comment]
Thanks for the detailed report.  That's higher memory usage than I would expect based on the k8s scale testing.

In the k8s end to end scale cluster tests, the cluster starts with 0 endpoints, then scales up to 150K, and then back down to 0.  This spin up/down takes a very long time (hours), perhaps giving garbage collection enough time to keep the allocations from stacking up.  IIRC, those reports only report one memory stat, I do not know if it reports in-use or allocations (I suspect the former).  The test does not restart CoreDNS at any time. If it did so while the endpoints are scaled up, perhaps it might show this type of issue. 

> The total in-used memory is around 160MB...

At 5K endpoints, I'd expect the memory usage after init to be much lower than 160MB.  For example, at 15K endpoints (smallest cluster size in the k8s scale tests) we found that the max memory usage was around 70 MB. With 150K endpoints, CoreDNS used about 180MB.

So there are two things going on here, big spike in memory allocation during initialization, and higher than expected memory usage post initialization.

**Comment by zhouhaibing089** [comment]
@chrisohaver: Thanks for your response.

The problem seems to be strings allocation, as I can see:

`kubernetes.endpointFQDN` constructs a lot of strings(parsing each of its addresses, and replace `.` in ip to `-`), and heavily call `strings.Join` to build up the FQDN.

This may be related: https://github.com/golang/go/issues/16930 by the way. The 5 minutes scavenger interval also matches with the dashboard above.

**Comment by johnbelamaric** [comment]
I suspect that this cluster has very large Endpoints objects for headless
services. @chrisohaver I think we only keep the Endpoints addresses for
headless services, right?

**Comment by chrisohaver** [comment]
> I think we only keep the Endpoints addresses for headless services, right?

Hmm, I thought we kept all endpoints, regardless of them being headless or not.  But perhaps I recall incorrectly...

**Comment by zhouhaibing089** [comment]
I think it keeps all the endpoints objects:

```go
// endpointFQDN returns a list of k8s cluster dns spec service FQDNs for each subset in the endpoint.
func endpointFQDN(ep *object.Endpoints, zone string, endpointNameMode bool) []string {
	var names []string
	for _, ss := range ep.Subsets {
		for _, addr := range ss.Addresses {
			names = append(names, dnsutil.Join(endpointHostname(addr, endpointNameMode), serviceFQDN(ep, zone)))
		}
	}
	return names
}

func endpointHostname(addr object.EndpointAddress, endpointNameMode bool) string {
	if addr.Hostname != "" {
		return addr.Hostname
	}
	if endpointNameMode && addr.TargetRefName != "" {
		return addr.TargetRefName
	}
	if strings.Contains(addr.IP, ".") {
		return strings.Replace(addr.IP, ".", "-", -1)
	}
	if strings.Contains(addr.IP, ":") {
		return strings.Replace(addr.IP, ":", "-", -1)
	}
	return ""
}
```

Every address in every endpoints will have a FQDN record.

**Comment by chrisohaver** [comment]
`endpointFQDN` and `endpointHostname` are (were) only called when processing dns queries - not during cache/store initialization/updates.  Unless something changed when we went to the custom store solution...  is that pre-calculating names now when adding to the object store?

**Comment by zhouhaibing089** [comment]
If I read the code correctly:

`kubernetes.endpointFQDN` is called by `sendEndpointsUpdates`, which in turn is called by `sendUpdates`.

The `sendUpdates` is an event handler for every events coming from API server(`onAdd`, `onUpdate` and `onDelete`). During initialization phase, I'm afraid that `onAdd` will be invoked for all the objects coming from APIServer.

**Comment by chrisohaver** [comment]
>  is that pre-calculating names now when adding to the object store?

Just checked, it doesn't appear to have changed. `endpointFQDN` and `endpointHostname` are only called when processing DNS queries - not by the k8s api cache/store initialization/updates.

**Comment by chrisohaver** [comment]
`sendEndpointsUpdates` ah - related to the watch code...

hmm...

**Comment by zhouhaibing089** [comment]
I'm pretty new to the coredns codebase, but sounds like there is a hope to avoid that case if we do not have to call `endpointFQDN` during initialization phase.

**Comment by chrisohaver** [comment]
@johnbelamaric, @miekg, 

At one point we proposed to put code in to side step this processing when there were not watches defined.  But... I semi-recall we didn't end up doing that because we still needed to do the calculation of changes for ... zone transfers was it?

**Comment by johnbelamaric** [comment]
yes, we need that calc for zone transfers. but just the calc, not actually generating watch events

**Comment by chrisohaver** [comment]
> yes, we need that calc for zone transfers. but just the calc, not actually generating watch events

yeah - we can still skip the updates in sendEndpointsUpdates, exiting early if there are no watches.

i'll draft a PR...

**Comment by johnbelamaric** [comment]
Awesome, thanks.

**Comment by zhouhaibing089** [comment]
I can still see the high memory usage. 😢 But with a different memory profile now.

```console
$ go tool pprof --alloc_space http://10.22.204.120:6060/debug/pprof/heap
Fetching profile over HTTP from http://10.22.204.120:6060/debug/pprof/heap
Saved profile in /home/haibzhou/pprof/pprof.coredns.alloc_objects.alloc_space.inuse_objects.inuse_space.038.pb.gz
File: coredns
Type: alloc_space
Time: Jan 29, 2019 at 1:04pm (GMT+7)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1037.26MB, 89.10% of 1164.17MB total
Dropped 169 nodes (cum <= 5.82MB)
Showing top 10 nodes out of 96
      flat  flat%   sum%        cum   cum%
  265.59MB 22.81% 22.81%   265.59MB 22.81%  bytes.makeSlice
  142.79MB 12.27% 35.08%   169.34MB 14.55%  compress/flate.NewWriter
  134.51MB 11.55% 46.63%   227.51MB 19.54%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*EndpointAddress).Unmarshal
  115.50MB  9.92% 56.55%      116MB  9.96%  github.com/coredns/coredns/vendor/k8s.io/apimachinery/pkg/runtime.(*Unknown).Unmarshal
  112.83MB  9.69% 66.25%   340.35MB 29.24%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*EndpointSubset).Unmarshal
   94.09MB  8.08% 74.33%    94.09MB  8.08%  github.com/coredns/coredns/plugin/kubernetes/object.ToEndpoints
      93MB  7.99% 82.32%       93MB  7.99%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*ObjectReference).Unmarshal
   45.13MB  3.88% 86.19%    45.13MB  3.88%  github.com/coredns/coredns/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert
   17.27MB  1.48% 87.68%    17.27MB  1.48%  github.com/coredns/coredns/vendor/golang.org/x/net/http2.glob..func5
   16.55MB  1.42% 89.10%    16.55MB  1.42%  compress/flate.(*compressor).initDeflate (inline)
```

and

```console
$ go tool pprof http://10.22.204.120:6060/debug/pprof/heap
Fetching profile over HTTP from http://10.22.204.120:6060/debug/pprof/heap
Saved profile in /home/haibzhou/pprof/pprof.coredns.alloc_objects.alloc_space.inuse_objects.inuse_space.039.pb.gz
File: coredns
Type: inuse_space
Time: Jan 29, 2019 at 1:05pm (GMT+7)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 164.10MB, 98.79% of 166.11MB total
Dropped 30 nodes (cum <= 0.83MB)
Showing top 10 nodes out of 42
      flat  flat%   sum%        cum   cum%
   75.56MB 45.49% 45.49%    75.56MB 45.49%  github.com/coredns/coredns/plugin/kubernetes/object.ToEndpoints
   34.50MB 20.77% 66.26%       59MB 35.52%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*EndpointAddress).Unmarshal
   24.60MB 14.81% 81.07%    24.60MB 14.81%  github.com/coredns/coredns/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert
   24.50MB 14.75% 95.82%    24.50MB 14.75%  github.com/coredns/coredns/vendor/k8s.io/api/core/v1.(*ObjectReference).Unmarshal
       2MB  1.20% 97.03%        2MB  1.20%  github.com/coredns/coredns/vendor/k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc
    1.32MB  0.79% 97.82%    26.54MB 15.98%  github.com/coredns/coredns/vendor/k8s.io/client-go/tools/cache.(*threadSafeMap).Add
       1MB   0.6% 98.42%        1MB   0.6%  github.com/coredns/coredns/plugin/kubernetes/object.ToService
    0.62MB  0.37% 98.79%    25.22MB 15.18%  github.com/coredns/coredns/vendor/k8s.io/client-go/tools/cache.(*threadSafeMap).updateIndices
         0     0% 98.79%        1MB   0.6%  github.com/coredns/coredns/core/plugin.init
         0     0% 98.79%       59MB 35.52%  github.com/coredns/coredns/plugin/kubernetes.endpointsListFunc.func1
```

**Comment by johnbelamaric** [comment]
Ok, so I have to wonder again:

1) @zhouhaibing089 do you have very large Endpoints objects?
2) If so, are they for clusterIP or headless services?
3) If they are for clusterIP, can we skip loading Endpoints for those services (not even unmarshal them...?) @chrisohaver ?

I don't recall why we keep endpoints for cluster IP services.

**Comment by zhouhaibing089** [comment]
With more context, we are seeing OOMs because people are doing LnP tests around kube-proxy, and created endpoints objects with many addresses inside it:

```console
$ kubectl get endpoints lnp-test-mxbk6 -n kp-lnp-2
NAME             ENDPOINTS                                                             AGE
lnp-test-mxbk6   172.24.246.235:80,172.24.246.236:80,172.24.246.238:80 + 147 more...   71m
```

Precisely, 150 addresses in a single endpoint object.

The corresponding service object is ClusterIP.

```console
$ kubectl get svc -n kp-lnp-2  lnp-test-mxbk6 -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-01-29T19:17:12Z
  generateName: lnp-test-
  name: lnp-test-mxbk6
  namespace: kp-lnp-2
  resourceVersion: "13523284131"
  selfLink: /api/v1/namespaces/kp-lnp-2/services/lnp-test-mxbk6
  uid: 7b05903f-23fa-11e9-a776-3cfdfe570720
spec:
  clusterIP: 192.168.29.55
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lnp-kube-proxy-88
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by johnbelamaric** [comment]
Ok. 150 is not huge but it's decent in size. The Endpoints object gets very large, because it contains all addresses for the service. If any one of those changes, the entire new Endpoints is sent down the wire and needs to be processed. This is a known issue with Endpoints and there are some folks looking at improving it.

Nonetheless, I still wonder if we need them for clusterIP services.

**Comment by zhouhaibing089** [comment]
Should it be related to the initial listing from apiserver where a lot of decodings are happening? When CoreDNS is running stable, a single change on an endpoints object may not cause too much changes on memory usage.

Maybe there can be some enhancement on k8s reflector framework, so link to https://github.com/kubernetes/kubernetes/issues/73497 as well.

**Comment by miekg** [comment]
Seems to be upstream issue. Closing here.
