### ISSUE TITLE
SRVFAIL if one of the DNS in resolv.conf is not reachable 

### ISSUE THREAD

**Issue by paphillon** [coredns/coredns#2514]
If one of the nameserver in the /etc/resolv.conf is not reachable, there are intermittent errors in query resolution that affects services running on k8s and are dependent on external name lookup

I am not sure if it's a bug or some configuration error.

```
CoreDNS-1.3.1 / 1.1.3 has the issue
linux/amd64, go1.11.4, 6b56a9c
```

```
.:1053 {
    cache 30
    errors
    health
    kubernetes cluster.local 172.200.0.0/24 {
      pods verified
    }
    loadbalance round_robin
    prometheus 0.0.0.0:9153
    proxy . /etc/resolv.conf
    reload
}
```

```
2019-01-29T08:06:47.904Z [INFO] plugin/reload: Running configuration MD5 = 9865fe5c7f944f5c3d50b57dfbe11e7f
2019-01-29T08:13:09.676Z [ERROR] plugin/errors: 2 kafka-dev-1.corp.abc.com. A: unreachable backend: read udp 172.200.0.212:46620->10.116.102.247:53: i/o timeout
2019-01-29T08:15:50.899Z [ERROR] plugin/errors: 2 kafka-dev-2.corp.abc.com.openstacklocal. A: unreachable backend: read udp 172.200.0.212:38899->10.116.102.247:53: i/o timeout
```
```
172.200.0.212  is the coreDNS Pod IP
10.116.102.247 is the DNS server that is not reachable
PING 10.116.102.247 (10.116.102.247): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
```

**Comment by fturib** [comment]
How many nameservers are defined in /etc/resolv.conf ?
Can you verify how many of them are reachable (from the CoreDNS Pod if possible)

**Comment by paphillon** [comment]
@fturib There are three nameservers in the resolv.conf. Yes, out of three nameservers 2 are reachable and the third one is not as that DNS was in another data center that was decommissioned and that is how we found out about this issue.

We did remove the unreachable nameserver for now, but this problem can happen if there is a network issue that prevents one of the DNS to respond.

**Comment by paphillon** [comment]
Update: Instead of using proxy plugin I changed it to forward, this seems to resolve the issue and I can also confirm from the metric 'coredns_forward_healthcheck_failure_count_total'. 

Is there any major difference choosing one over the other? Sorry, DNS is not my area of expertize.

```
        forward . /etc/resolv.conf {
            health_check 1s
        }
 
```

**Comment by fturib** [comment]
It is safe to use `forward` instead of `proxy`.
This change was done also very recently for the default deployment in Kubernetes (see https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed).

The health_check has been reworked in `forward` (the issue you are describing above seems close to an health-check issue or to the logic associated).

also `forward` has much better performance when it comes to query/second sent to the upstream.

**Comment by paphillon** [comment]
@fturib  Thank you for confirming!
