### ISSUE TITLE
default action for empty Corefile

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#252]
When caddy gets and empty caddyfile it serves any .html pages it found in the local directory.
It may be nice for CoreDNS to do the same, serve all db.<name> files it finds as zones (with origin <name>).

If we were to do this, it has implication for the file middleware. That would need a similar feature, i.e. an empty corefile would be equivalent with

```
*:53 {
   file *
}
```

or something, note: both wildcards are not supported at this moment.

So there are pros and cons. I _think_ having a default action makes some sense, but not at all cost.

**Comment by mrichmon** [comment]
It might make sense to achieve this by automatically writing out a default Corefile if no Corefile can be found. This together with a log message like "Unable to find Corefile... generating default configuration in ./Corefile" would help point users to the Corefile as the way to define CoreDNS behavior.

I can see value in a default providing either:
- serving all db files in the current directory (as you suggest).
- serving a fixed db file such as "coredns.db".
- serving a TXT record or similar that contains "If you see this record you have started CoreDNS without a configuration file."
- default to the whoami middleware?

**Comment by miekg** [comment]
I think the `whoami` middleware makes a lot of sense. This might also just be a useful middleware no matter what.

Writing the Corefile get difficult fast; current directory not writable, what would be a good default, etc. etc. I better leave that (small) can of worms closed.

**Comment by miekg** [comment]
https://github.com/miekg/coredns/pull/264 adds whoami middleware. Next I will hook at into the default Corefile.

**Comment by miekg** [comment]
Done with 001 release
