### ISSUE TITLE
plugin/forward does not use fallback on SERVFAIL

### ISSUE THREAD

**Issue by willwp** [coredns/coredns#2524]
Coredns fallback plugin is not working with forward, on SERVFAIL.  Want to fallback to 8.8.8.8, see Corefile.  The fallback plugin page states that it works with proxy.  We know that forward is the preferred because proxy becoming deprecated.

**Comment by fturib** [comment]
`fallback` **is re-using** `proxy` to send the request upstream.
It does not mean that it will not work with `forward` is the way you show it.

if you want a similar plugin that **re-use** `forward` to send the request upstream, then you should look at `alternate` (see github.com/coredns/alternate)

**Comment by willwp** [comment]
I have alternate working with SERVFAIL to 9.9.9.9.   Is it possible to have a second alternate for SERVFAIL to 8.8.8.8 (the same rcode)? Finished with this issue, thank you.

. {
       cache 3600
       forward . tls://1.1.1.1 tls://1.0.0.1 {
               tls_servername cloudflare-dns.com
               health_check 5s
               max_fails 1
               expire 90s
       }
       alternate SERVFAIL . tls://9.9.9.9 {
                tls_servername dns.quad9.net
                health_check 5s
                max_fails 0
                expire 90s
       }
}

**Comment by fturib** [comment]
hum ... from doc, you can use only once the rcode.
But `alternate` has the same syntax as forward, so you could use both `9.9.9.9` and `8.8.8.8` on the same `alternate SERVFAIL` stanza.

did you try: ?

```
alternate SERVFAIL . tls://9.9.9.9 8.8.8.8 {
tls_servername dns.quad9.net
health_check 5s
max_fails 0
expire 90s
}
```

you may want a specific `policy` to choose between the 2 remote servers. See corresponding doc in `forward`.
