### ISSUE TITLE
plugin/k8s_external - Support for zone transfer

### ISSUE THREAD

**Issue by fturib** [coredns/coredns#2526]
That would need:
- define what would be the SERIAL for SOA
- collect all Services using Externaler interface, and generate all the corresponding records.

NOTE: I have prepared locally a change that seems OK (not sure though).
Will shoot a PR later today.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/k8s_extern..." ]
>That would need:
>- define what would be the SERIAL for SOA

this is already done, as we support axfr in k8s already.

>- collect all Services using Externaler interface, and generate all the corresponding records.

interface? why?

/Miek

--
Miek Gieben

**Comment by johnbelamaric** [comment]
> this is already done, as we support axfr in k8s already.

You only need to bump the serial number if services of type loadbalancer or
with ExternalIPs change. So that should be a much smaller set of changes
than in the normal k8s plugin.

**Comment by miekg** [comment]
see discussion in #2585 a new plugin is better.
