### ISSUE TITLE
plugin/auto|file: Add deprecation notice for NO_RELOAD

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2536]
Similar notice as done in #2516 for TIMEOUT.

Necessary for full deprecation.

**Comment by naeemkhan12** [comment]
I would like to work on this.

**Comment by nzoueidi** [comment]
Hey, can I work on this issue? :)

**Comment by stp-ip** [comment]
That sounds awesome. A good example on how this can be implemented is available in the mentioned PR #2516

**Comment by ihac** [comment]
@nzoueidi Hi, are you still working on this? If not I'd like to help.
According to @stp-ip 's plan ([Issue 2537](https://github.com/coredns/coredns/issues/2537)), this work seems to be straightforward. But I'm not sure whether we need to fully deprecate `no_reload` and `timeout` right now.
If we're going to add deprecation notice for `no_reload` (not fully deprecated), I think a single warning statement in `plugin/file/setup.go` and `plugin/auto/setup.go` should be enough.
WDYT? @stp-ip

**Comment by stp-ip** [comment]
Yeah both should not be fully deprecated yet. Just the note for now and then in the next release we can add the deprecation in the release note and according to our deprecation policy prepare the actual deprecation in the future for both no_reload and the various timings.

Also haven't heard from @nzoueidi on progress.

**Comment by stp-ip** [comment]
For reference: https://github.com/coredns/coredns#deprecation-policy

**Comment by nzoueidi** [comment]
Sorry for the delay. Yes I am working on it. 
Looks like by tonight or tomorrow I will push a PR.

**Comment by miekg** [comment]
this is now closeable?
