### ISSUE TITLE
plugin/auto|file: fully deprecate TIMEOUT + NO_RELOAD

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2537]
Current (PR #2516) workings:
TIMEOUT & RELOAD not set -> 60s for both
TIMEOUT set -> use value for both
RELOAD set -> use value for both
TIMEOUT & RELOAD set -> use specific values

Deprecated implementation TIMEOUT:
TIMEOUT set -> error
RELOAD not set -> 60s default
RELOAD set -> use specific value

Deprectated implementation NO_RELOAD:
NO_RELOAD set -> error

Release notes:
```
Breaking: plugin/auto removes TIMEOUT and NO_RELOAD. plugin/file removes NO_RELOAD. Both plugin/file and plugin/auto now only allows the usage of RELOAD.
```

**Comment by stp-ip** [comment]
@nzoueifi as you worked on the previous PR. Do you want to take this up?
That would mean the final deprecation would be done in 1.6.0

**Comment by stp-ip** [comment]
Or @ihac :)

**Comment by ihac** [comment]
@stp-ip Thanks for reminding. I'll create a pr today.

**Comment by miekg** [comment]
We can just include it in 150, I can wait a bit
