### ISSUE TITLE
autopath and stub domains

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#2539]
A common deployment pattern in kubernetes is to define a series of stub domains with `forward` (or the soon to be deprecated `proxy`). A simplified example:

```
.:53 {
  kubernetes cluster.local
  proxy . 8.8.8.8
}

stub.domain:53 {
  proxy . 1.2.3.4
}
```

A problem arises when introducing _autopath_...

```
.:53 {
  autopath cluster.local @kubernetes
  kubernetes cluster.local {
    pods verified
  }
  proxy . 8.8.8.8
}

stub.domain:53 {
  proxy . 1.2.3.4
}
```

Here, when a Pod makes a DNS query for `test.stub.domain`,  CoreDNS receives a request for `teststub.domain.namesapce.svc.cluster.local.`, _autopath_ kicks in as expected, and tries the `cluster.local` domains to no avail, then passes `test.stub.domain.` along to the next plugin, which is a proxy to `8.8.8.8`, not the stub domain proxy to `1.2.3.4` (where it _should_ go).

One way around this is to stuff multiple _proxy_ in the same block...

```
.:53 {
  autopath cluster.local @kubernetes
  kubernetes cluster.local {
    pods verified
  }
  proxy stub.domain 1.2.3.4
  proxy . 8.8.8.8
}
```

This works, because _proxy_ allows > 1 instance per block.  But _forward_ does not allow this, and we are deprecating _proxy_ soon. So we need a solution for _forward_.

Two possible fixes I can think of:
1. have _autopath_ feed domains that don't match it's zone back to it's server instead of to the next plugin (akin to _upstream_).
2. allow multiple _forward_ plugins per block

**Comment by chrisohaver** [comment]
I think `#1` above is more correct, since it's a more general solution and would work with any plugin that should process that domain.  

IOW, if _autopath_ synthesizes a query name that doesn't match the domain of it's current block, it should be feeding that synthesized query back to the server to make sure gets handled by the correct block with a zone that matches the domain.

**Comment by chrisohaver** [comment]
Some folks running into this issue: #2532, #2552

**Comment by chrisohaver** [comment]
@miekg, I can look into fixing this via "have _autopath_ feed domains that don't match it's zone back to it's server instead of to the next plugin (akin to _upstream_)."
Please let me know if that solution meets with your approval. And I'll proceed if it does. Thanks

**Comment by miekg** [comment]
Why doesn't this work?

~~~
cluster.local:53 {
  autopath @kubernetes
  kubernetes  {
    pods verified
  }
}
.:53 {
  proxy stub.domain 1.2.3.4
  proxy . 8.8.8.8
}
~~~

multiple forwards in one block is indeed a thing we need to fix.

**Comment by chrisohaver** [comment]
> Why doesn't this work?

Autopath synthesizes qnames that are not in the same zone. E.g., when autopathing `google.com`, it tries...
`google.com.default.svc.cluster.local`
`google.com.svc.cluster.local`
`google.com.cluster.local`
`google.com.stub.domain` (if `stub.domain` is a search domain on the nodes)
`google.com`

Autopath always passes the synthesized queries to the next plugin, which is kubernetes.  kubernetes has the domain `cluster.local`, inherited form the server block. Both `google.com.stub.domain ` and `google.com` are not in that zone, so they get passed to next plugin.  There is no next plugin, so we SERVFAIL.

It should instead, IMO, be feeding `google.com.stub.domain ` and `google.com` back to "itself" (as upstream does), so they would get routed to the `.:53` chain.

Additionally, fixing by allowing multiple instances per block just fixes it for those plugins that permit multiple instances . For example, CoreDNS could be authoritative for `stub.domain` (e.g. `etcd` or `file`), in which case we'd need to support multiple instances per block for those plugins too.

**Comment by chrisohaver** [comment]
> For example, CoreDNS could be authoritative for `stub.domain` (e.g. `etcd` or `file`), in which case we'd need to support multiple instances per block for those plugins too.

Those are bad examples, because, per docs, they already permit > 1 instance per block (or at least the docs don't say they do not).  But not all plugins do.

**Comment by miekg** [comment]
We're not going to add more `fallthrough`'s, a proper corefile should fix this, and *autopath* was a hack, so things may not work like you want them to work.

**Comment by chrisohaver** [comment]
This wasn't about adding more `fallthrough` at all.  But whatever.
