### ISSUE TITLE
Remove watch functionally

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2548]
See discussion in #2513

It's complex (and large), causes maintenance issue and is not used.

**Comment by stp-ip** [comment]
We definitely need more data on how watch functionality might impact performance, but for this to be reasonable performance GRPC itself needs to be improved performance wise.

**Comment by miekg** [comment]
This pr is not about performance, but cutting some code out.

We haven't got current perf figures for gRPC.

**Comment by stp-ip** [comment]
Was adding the context that this currently is not a good option on production as far as our tests and talk prep went and this is mostly due to gRPC. Don't have a specific argument on removing the code or not.

**Comment by miekg** [comment]
Ok and thanks for that.

Code can be brought back once we have a coherent plan to support and use
this. (Will still be fiddly, because there is little chance this will apply
cleanly by then)
