### ISSUE TITLE
Split horizon

### ISSUE THREAD

**Issue by karasz** [coredns/coredns#255]
Is there any intention of implementing split horizon feature? If not, what are the reasons?

**Comment by miekg** [comment]
Probably not: it an feature that is easily abused, and makes debugging much
harder. It is (not always) also a sign that you are abusing the DNS and
there a probably other ways that will work better.

But having a clean implementation in a middle ware might me change my mind
😀

**Comment by miekg** [comment]
Nobody is working on this, nor are there plans to do so. Closing for now.
