### ISSUE TITLE
Autopath returns SERVFAIL  on a custom server block

### ISSUE THREAD

**Issue by skygeo** [coredns/coredns#2552]
Hi

version of coredns: 1.3.1

I am currently trying to split my config from one server block into two, one for Kubernetes cluster.local domain and one for everything else. The reason behind this change is to to get detailed prometheus metrics per domain. Sadly, this seem to break the autopath plugin, returning SERVFAIL. I've been looking into it for quite some time and I still don't see where my config is wrong. Is this a bug or a feature? Thanks for your help!

##  Original config:

*coredns config*
```
.:53 {
        errors
        health :8080
        autopath @kubernetes
        kubernetes cluster.local {
            pods verified
            upstream 169.254.169.253
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . 169.254.169.253
        cache 300
    }
```
*example DNS queries*
```
# From a random pod in the default namespace
root@dnsutils:/# host kubernetes
kubernetes.default.svc.cluster.local has address 10.254.0.1
root@dnsutils:/# host kubernetes.default.svc.cluster.local
kubernetes.default.svc.cluster.local.default.svc.cluster.local is an alias for kubernetes.default.svc.cluster.local.
kubernetes.default.svc.cluster.local has address 10.254.0.1
root@dnsutils:/# host www.google.com
www.google.com.default.svc.cluster.local is an alias for www.google.com.
www.google.com has address 74.125.193.104
www.google.com has address 74.125.193.105
www.google.com has address 74.125.193.99
www.google.com has address 74.125.193.147
www.google.com has address 74.125.193.106
www.google.com has address 74.125.193.103
www.google.com has IPv6 address 2a00:1450:400b:c03::68
```

## Config with autopath returning SERVFAIL

*coredns config*
```
    cluster.local:53 {
        errors
        health :8085
        autopath @kubernetes
        kubernetes cluster.local {
            pods verified
            upstream
        }
        prometheus :9153
        cache 300
    }

    .:53 {
        errors
        log
        health :8080
        prometheus :9153
        proxy . 169.254.169.253
        cache 300
    }
```
*Example DNS queries*
```
# From a random pod in the default namespace
root@dnsutils:/# host kubernetes
kubernetes.default.svc.cluster.local has address 10.254.0.1
root@dnsutils:/# host kubernetes.default.svc.cluster.local
Host kubernetes.default.svc.cluster.local.default.svc.cluster.local not found: 2(SERVFAIL)
root@dnsutils:/# host www.google.com
Host www.google.com.default.svc.cluster.local not found: 2(SERVFAIL)
```

*Logs from coredns*
```
2019-02-11T16:08:19.624Z [INFO] 10.231.155.147:58676 - 23028 "A IN kubernetes.default.svc.cluster.local.default.svc.cluster.local. udp 80 false 512" SERVFAIL qr,rd 80 0.000100093s
2019-02-11T16:08:19.624Z [ERROR] plugin/errors: 0 kubernetes.default.svc.cluster.local.default.svc.cluster.local. A: plugin/kubernetes: no next plugin found
```

## One more thing

After playing with the config, it turns out that *adding the . zone to the kubernetes plugin fixes everything. I don't understand why?

```
    cluster.local:53 {
        errors
        health :8085
        autopath @kubernetes
        kubernetes . cluster.local {
            pods verified
            upstream
        }
        prometheus :9153
        cache 300
    }

```

**Comment by chrisohaver** [comment]
Coincidentally, I described why this occurs, and how we can fix it in #2539...

**Comment by chrisohaver** [comment]
> After playing with the config, it turns out that *adding the . zone to the kubernetes plugin fixes everything. I don't understand why?

It's probably not actually working. I believe this would make the error go away, but still render it unable to resolve those queries. By adding the dot, you are making kubernetes authoritative for all zones, which means it would try to resolve queries outside fo the cluster (which it cant).

**Comment by skygeo** [comment]
I am not sure the other issue explains why a call to kubernetes.default.svc.cluster.local also result in a SERVFAIL ? Does it?

**Comment by chrisohaver** [comment]
`/etc/resolv.conf` also contains local domains of the _nodes_. So, if the nodes have `mydomain.org` as a search domain, the search line will look something like ...

```
search default.svc.cluster.local svc.cluster.local cluster.local mydomain.org
```

With that search path, it will always try to search in `mydomain.org` before searching the query name by itself.  e.g.  `kubernetes.default.svc.cluster.local.mydomain.org `, which would pass to the next plugin, and give you the SERVFAIL.

Without seeing the search list, I can't say for certain if that is what happening.  You could spin up a pod and cat `/etc/resolv.conf`. Or to see it in action, turn logging on, and autopath off, to see each of those queries as they are constructed by the client.

**Comment by skygeo** [comment]
Yes. This is correct
```
root@dnsutils:/# cat /etc/resolv.conf
nameserver 10.254.0.10
search default.svc.cluster.local svc.cluster.local cluster.local eu-west-1.compute.internal
options ndots:5
```

Thanks for your help!
