### ISSUE TITLE
fyi: Zalando post-mortem DNS outage

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2554]
https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/docs/postmortems/jan-2019-dns-outage.md

**Comment by stp-ip** [comment]
Just a FYI item that might be interesting. No specific action item currently and therefore closing as this might already reach the correct people. Will try to see, if any specific action items could be worked in long-term.

**Comment by miekg** [comment]
Thanks that would good to know if there any action items  for us. Haven'the
post mortem myself yet.

**Comment by fturib** [comment]
Great to share that information.
Interesting case. 

> We are working on a solution where we will run CoreDNS fronted by dnsmasq on every node. This setup outperforms any other setup we have considered and tested. 

That is almost the "node-local" configuration, but I guess with a more efficient cache.

**Comment by miekg** [comment]
We could probably do more there, although dnsmasq may be hard to beat, we
should be able to get close if we figure out where our bottlenecks are
exactly.

**Comment by chrisohaver** [comment]
FYI, @rajansandeep pointing out to me, the charts are not from the actual incident...

> Note: Graphs depicted are not from the actual incident, but from a later point in time when CoreDNS was scaled to handle the spikes.

**Comment by johnbelamaric** [comment]
Thanks that was interesting. I think also rate limiting may help. I don't quite get though why our memory spiked so high. I thought we ran a limited number of workers / go routines. Do we have a fixed buffer size that they are working off of? Or do we just keep accepting packets and queuing them up until we run out of memory?

We could get more predictable memory consumption (or limit anyway) by dropping new requests over a limit. That would likely reduce the severity of the issue (and give time for autoscalers to kick in).

**Comment by chrisohaver** [comment]
yes was thinking the same of RRL... coincidentally, I'm going to start look into the RRL as a plugin this week, as there is a need for that feature at Infoblox.  

dnsmasq has a max in-flight limit on packets, after which it drops them - iirc, the buffer length is configurable.  would help.

The graphs are curious in that the memory begins to ramp up before the query spike... Not sure how to explain that.

cache size might be a factor, especially if using a coredns before the cache fix.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] fyi: Zalando ..." ]
>Thanks that was interesting. I think also rate limiting may help. I don't quite get though why our memory spiked so high. I though we ran a limited number of workers / go routines. Do we have a fixed buffer size that they are working off of? Or do we just keep accepting packets and queuing them up until we run out of memory?

We keep accepting, but we do fire up worker go-routines that handle 50 (have to 
check the source) packets before returning, but there is no limit on the number 
of workers.

**Comment by miekg** [comment]
We should also first try to repro this with an instrumented binary, before
jumping to any conclusions.

**Comment by miekg** [comment]
Now discussed in #2593
