### ISSUE TITLE
Forward UDPSize issue

### ISSUE THREAD

**Issue by bcebere** [coredns/coredns#2556]
Hi,
I had an issue with the forward plugin.

Setup:
 - one upstream server for the forward plugin.

If the upstream server returns an response over UDP greater than the conn.UDPSize, the result is interpreted as an error and the plugin retries in a loop the same question. 

I think the plugin should drop the request if it can't handle a response not truncated and that the minimal UDP buffer size should be configurable. I don't know if it's ok to auto-adjust the UDP size on error.

I added a gists with a patch, I can't make a pull request. If it's not a bad idea.

https://gist.github.com/bcebere/0ddaf4320b9ead8a29c376276c1f845d

Thanks

**Comment by miekg** [comment]
This might be a bug. I'll take a closer look.


/plugin: forward
/label: bug

**Comment by miekg** [comment]
I don't understand the issue and I can't spend the time to properly debug this.

**Comment by bcebere** [comment]
All I was trying to say is that this line
`	if conn.UDPSize < 512 {
		conn.UDPSize = 512
	}`

is enforcing the 512 bytes limit and this threshold should be added to the forward config instead.

And in the current setup, if the forward plugin receives a packet greater than 512 bytes, it will loop to the upstream server, with the same size, instead of failing with error.

**Comment by bcebere** [comment]
Anyway, I'll will close the issue, if it's not a real problem.
