### ISSUE TITLE
Customize forward plugin to support the mdns client use case

### ISSUE THREAD

**Issue by yboaron** [coredns/coredns#2557]
I'm trying to customize the forward plugin to support the mdns client use case according to what was suggested at [1], I updated the code to set 'QU' bit (the upper bit of question.Class)  to enforce unicast reply and use the following Corefile:

.:53 {
 log
 forward local 224.0.0.251:5353 {
        health_check 0
        max_fails 0
 }
 proxy . /etc/resolv.conf
}

But it doesn't work, the unicast reply is rejected with destination port unreachable error, I assume that it's because of the asymmetric IP addresses in the forward packets.
 The forward packets dump (10.0.9.119 is the coredns machine IP)  could be found at [2].

Any help will be highly apperciated
Thanks
Yossi

[1] https://github.com/coredns/coredns/issues/1519

[2]
No.     Time           Source                Destination           Protocol Length Info
      1 0.000000       10.0.9.119            224.0.0.251           MDNS     83     Standard query 0xb041 A dfdfdf.local, "QU" question OPT

Frame 1: 83 bytes on wire (664 bits), 83 bytes captured (664 bits)
Ethernet II, Src: fa:16:3e:b6:05:76 (fa:16:3e:b6:05:76), Dst: IPv4mcast_fb (01:00:5e:00:00:fb)
Internet Protocol Version 4, Src: 10.0.9.119, Dst: 224.0.0.251
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
    Total Length: 69
    Identification: 0x05b7 (1463)
    Flags: 0x4000, Don't fragment
    Time to live: 1
    Protocol: UDP (17)
    Header checksum: 0x7f7f [validation disabled]
    [Header checksum status: Unverified]
    Source: 10.0.9.119
    Destination: 224.0.0.251
User Datagram Protocol, Src Port: 42021, Dst Port: 5353
    Source Port: 42021
    Destination Port: 5353
    Length: 49
    Checksum: 0xf4b4 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 0]
Multicast Domain Name System (query)
    Transaction ID: 0xb041
    Flags: 0x0120 Standard query
    Questions: 1
    Answer RRs: 0
    Authority RRs: 0
    Additional RRs: 1
    Queries
        dfdfdf.local: type A, class IN, "QU" question
            Name: dfdfdf.local
            [Name Length: 12]
            [Label Count: 2]
            Type: A (Host Address) (1)
            .000 0000 0000 0001 = Class: IN (0x0001)
            1... .... .... .... = "QU" question: True
    Additional records
        <Root>: type OPT
            Name: <Root>
            Type: OPT (41)
            .001 0000 0000 0000 = UDP payload size: 0x1000
            0... .... .... .... = Cache flush: False
            Higher bits in extended RCODE: 0x00
            EDNS0 version: 0
            Z: 0x0000
                0... .... .... .... = DO bit: Cannot handle DNSSEC security RRs
                .000 0000 0000 0000 = Reserved: 0x0000
            Data length: 0

No.     Time           Source                Destination           Protocol Length Info
      2 0.004240       10.0.9.116            10.0.9.119            MDNS     88     Standard query response 0xb041 A dfdfdf.local, "QU" question A 10.0.9.116

Frame 2: 88 bytes on wire (704 bits), 88 bytes captured (704 bits)
Ethernet II, Src: fa:16:3e:8e:8f:f6 (fa:16:3e:8e:8f:f6), Dst: fa:16:3e:b6:05:76 (fa:16:3e:b6:05:76)
Internet Protocol Version 4, Src: 10.0.9.116, Dst: 10.0.9.119
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
    Total Length: 74
    Identification: 0x491c (18716)
    Flags: 0x4000, Don't fragment
    Time to live: 255
    Protocol: UDP (17)
    Header checksum: 0x0b9c [validation disabled]
    [Header checksum status: Unverified]
    Source: 10.0.9.116
    Destination: 10.0.9.119
User Datagram Protocol, Src Port: 5353, Dst Port: 42021
    Source Port: 5353
    Destination Port: 42021
    Length: 54
    Checksum: 0x22ae [unverified]
    [Checksum Status: Unverified]
    [Stream index: 1]
Multicast Domain Name System (response)
    Transaction ID: 0xb041
    Flags: 0x8400 Standard query response, No error
    Questions: 1
    Answer RRs: 1
    Authority RRs: 0
    Additional RRs: 0
    Queries
        dfdfdf.local: type A, class IN, "QU" question
            Name: dfdfdf.local
            [Name Length: 12]
            [Label Count: 2]
            Type: A (Host Address) (1)
            .000 0000 0000 0001 = Class: IN (0x0001)
            1... .... .... .... = "QU" question: True
    Answers
        dfdfdf.local: type A, class IN, addr 10.0.9.116
            Name: dfdfdf.local
            Type: A (Host Address) (1)
            .000 0000 0000 0001 = Class: IN (0x0001)
            0... .... .... .... = Cache flush: False
            Time to live: 10
            Data length: 4
            Address: 10.0.9.116
    [Unsolicited: True]

No.     Time           Source                Destination           Protocol Length Info
      3 0.004283       10.0.9.119            10.0.9.116            ICMP     116    Destination unreachable (Port unreachable)

Frame 3: 116 bytes on wire (928 bits), 116 bytes captured (928 bits)
Ethernet II, Src: fa:16:3e:b6:05:76 (fa:16:3e:b6:05:76), Dst: fa:16:3e:8e:8f:f6 (fa:16:3e:8e:8f:f6)
Internet Protocol Version 4, Src: 10.0.9.119, Dst: 10.0.9.116
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0xc0 (DSCP: CS6, ECN: Not-ECT)
    Total Length: 102
    Identification: 0x00fe (254)
    Flags: 0x0000
    Time to live: 64
    Protocol: ICMP (1)
    Header checksum: 0x51ef [validation disabled]
    [Header checksum status: Unverified]
    Source: 10.0.9.119
    Destination: 10.0.9.116
Internet Control Message Protocol
    Type: 3 (Destination unreachable)
    Code: 3 (Port unreachable)
    Checksum: 0x242f [correct]
    [Checksum Status: Good]
    Unused: 00000000
    Internet Protocol Version 4, Src: 10.0.9.116, Dst: 10.0.9.119
        0100 .... = Version: 4
        .... 0101 = Header Length: 20 bytes (5)
        Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        Total Length: 74
        Identification: 0x491c (18716)
        Flags: 0x4000, Don't fragment
        Time to live: 255
        Protocol: UDP (17)
        Header checksum: 0x0b9c [validation disabled]
        [Header checksum status: Unverified]
        Source: 10.0.9.116
        Destination: 10.0.9.119
    User Datagram Protocol, Src Port: 5353, Dst Port: 42021
        Source Port: 5353
        Destination Port: 42021
        Length: 54
        Checksum: 0x22ae [unverified]
        [Checksum Status: Unverified]
        [Stream index: 1]
    Multicast Domain Name System (response)
        Transaction ID: 0xb041
        Flags: 0x8400 Standard query response, No error
        Questions: 1
        Answer RRs: 1
        Authority RRs: 0
        Additional RRs: 0
        Queries
            dfdfdf.local: type A, class IN, "QU" question
                Name: dfdfdf.local
                [Name Length: 12]
                [Label Count: 2]
                Type: A (Host Address) (1)
                .000 0000 0000 0001 = Class: IN (0x0001)
                1... .... .... .... = "QU" question: True
        Answers
            dfdfdf.local: type A, class IN, addr 10.0.9.116
                Name: dfdfdf.local
                Type: A (Host Address) (1)
                .000 0000 0000 0001 = Class: IN (0x0001)
                0... .... .... .... = Cache flush: False
                Time to live: 10
                Data length: 4
                Address: 10.0.9.116
        [Unsolicited: True]

**Comment by miekg** [comment]
I thought that supporting mdns requires changes on the network level as
well, i.e. just unicast isn't enough you need to retro fit multicast in
there as well

**Comment by yboaron** [comment]
@miekg  thanks for the feedback.
yep, seems that you are right, forcing unicast reply is not enough, as forward plugin 'expects' symmetric traffic (reply.ip_src should be equal to query.ip_dst).
So, instead of forcing 'QU' reply, we need to add support for multicast traffic.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Customize for..." ]
>@miekg  thanks for the feedback.
>yep, seems that you are right, forcing unicast reply is not enough, as forward plugin 'expects' symmetric traffic (reply.ip_src should be equal to query.ip_dst).
>So, instead of forcing 'QU' reply, we need to add support for multicast traffic.

Yes, this has been discussed before. It looks like just adding mdns support is 
not that easy. I think you need to start from the server side and make it listen
on multicast addresses as well `mdns://` as a new schema and go from there.
