### ISSUE TITLE
Pull out 'stubzones' from the etcd middleware

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#256]
The etcd middleware handles stubzones (just like SkyDNS). The k8s middleware needs something similar. Can we pull stubzone out and make it its own middleware? We could add some static configuration in the process:

```
stubzones example.org 8.8.8.8:53
```

this is very like the proxy middleware.

```
stubzones {
        etcd <config>
}
```

This would re-use a lot of config from the etcd middleware. I think. The same could be applied to k8s middleware, although I am not sure where the config should live in that case.

**Comment by miekg** [comment]
@mrichmon do you, by any chance, know if there is an API for this in k8s or do always need to query to (remote) etcd?

**Comment by miekg** [comment]
etcd middleware has these options:

```
etcd [zones...] {
    stubzones
    path /skydns
    endpoint endpoint...
    upstream address...
    tls cert key cacert
    debug
}
```

For a stubzones-outside-the-etcd-middleware we would need something like this (dunno yet if the `[zones..]` arg is need as well

```
stubzones {
    etcd_backend {
      path /stub
      endpoint endpoint...
      tls cert key cacert
   }
}
```

_But_ we can also store this in a zone file which lists the "delegation" in rfc1035 format as SRV records?: 

```
example.org IN SRV 0 0 <port> target.nameserver
target_nameserver IN A 127.0.0.1
target_nameserver IN AAAA ::1
```

The stubzone config would then look similar to the file middleware:

```
stubzones {
    file_backend dbfile {
       no_reload
    }
}
```

This would mean some interesting cross middleware imports.

**Comment by johnbelamaric** [comment]
Maybe instead any given middleware configuration could be given a name or alias that could be referenced in the stub zones middleware? Because I expect that if you are primarily using etcd or files, then that would also be where you would stuff the stub zones. So, something like:

```
etcd [zones...] {
    alias etcd_config_1
    path /skydns
    endpoint endpoint...
    upstream address...
    tls cert key cacert
    debug
}

stubzones {
    backend etcd_config_1
}
```

**Comment by miekg** [comment]
Not sure that expectations holds, at least that would make it somewhat less flexible. You can of course have a dummy etcd entry and reference that.

If we are going to do the aliases we should take to mholt@ to make it a generic Caddyfile feature (not ready to fork the caddyfile parsing just yet).

It does make sense to cut back on the config duplication though, I believe [imports](https://caddyserver.com/docs/import) serve this purpose.

**Comment by mrichmon** [comment]
@miekg I don't know if k8s has an API to access data related to stubzones. However, I have not looked for this API. I am undecided about whether stubzone support makes sense for the kubernetes middleware.

One way to think of the "alias" proposal is to default the alias to the middleware name. That would then allow:

```
kubernetes prod.core.local {
    namespace prod
}

stubzones {
    backend kubernetes
}
```

But I'm not too concerned about trying to reduce data replication in the Corefile. If this is a concern then it seems like some mechanism to define a block of values that can then be referenced symbolically would be more flexible. e.g.

```
my_options_1 {
      path /stub
      endpoint endpoint...
      tls cert key cacert 
}

etcd [zones...] {
    stubzones
    my_options_1
    upstream address...
    debug
}

stubzones {
    etcd_backend {
      my_options_1 
   }
}
```

It's not clear to me how any of these proposals would handle the cases of:
- multiple kubernetes middleware instances being defined (only one of which has stubzones).
- a kubernetes middleware instance that uses a file-based backend for stubzones.

**Comment by miekg** [comment]
Thanks for the input.

I think I will go ahead and try to at least pull it out of the etcd middleware and allow a `file` backend as well. Corefile duplication is another issues (if we care about that)
