### ISSUE TITLE
plugin/hosts fallthrough results in NXDOMAIN

### ISSUE THREAD

**Issue by juselius** [coredns/coredns#2564]
I'm trying to use the hosts plugin to augment and override host names in our organization's DNS domain. Using the Corefile below results in both resolving the name **and** in NXDOMAIN for every host defined in the hosts section. Everything works, but it's a bit confusing getting NXDOMAIN after a successful lookup.

I'm using coredns version 1.2.5.

```
.:10053 {
             errors
             health :10054
             kubernetes cluster.local in-addr.arpa ip6.arpa {
                  pods insecure
                  upstream
                  fallthrough in-addr.arpa ip6.arpa
              }
              prometheus :10055
              proxy . /etc/resolv.conf
              hosts  {
                    10.253.18.100 myservice.mydomain.com
                    fallthrough
              }
              cache 30
              loop
              reload
              loadbalance
}
```

**Comment by miekg** [comment]
Can you show some responses, preferable using `dig`

**Comment by juselius** [comment]
@miekg sorry for the late reply.  Here is the output from nslookup and dig on a container:

```
root@busynix-df88cb5d6-lhc9x /# nslookup myservice.mydomain.com
Server:		10.0.0.254
Address:	10.0.0.254#53

Name:	myservice.mydomain.com
Address: 10.253.18.100
** server can't find myservice.mydomain.com: NXDOMAIN
```

```
root@busynix-df88cb5d6-lhc9x /# dig myservice.mydomain.com
; <<>> DiG 9.12.3-P1 <<>> myservice.mydomain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11012
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;myservice.mydomain.com.		IN	A

;; ANSWER SECTION:
myservice.mydomain.com.	30	IN	A	10.253.18.100

;; Query time: 0 msec
;; SERVER: 10.0.0.254#53(10.0.0.254)
;; WHEN: Mon Feb 18 17:32:55 UTC 2019
;; MSG SIZE  rcvd: 70
```

As you can see, it both finds the host, and then it doesn't.

**Comment by miekg** [comment]
host will be never a full fledged plugin, just like /etc/hosts isn't a complete zone.

**Comment by mrdima** [comment]
Having the same "issue", nslookup does both an A and AAAA query...The NXDOMAIN is because you only have an IPv4 entry in the hostsfile and not an IPv6 entry and coredns will forward it to the resolver (or maybe not in your case)...it shouldn't give issues I suppose. CoreDNS kind of behaves differently in the IPv6 response if you do passthrough or not (in my setup), but I think that is to be expected.

**Comment by miekg** [comment]
If the name exists, but the record does it should return NODATA and not
fall through. If this doesn't happen it's a bug

**Comment by chrisohaver** [comment]
> If the name exists, but the record does it should return NODATA and not fall through. If this doesn't happen it's a bug

Missing a "not": If the name exists but the record does _not_, it should return NODATA and not
fall through.

**Comment by chrisohaver** [comment]
Glancing at the code - it looks like hosts will fall through when there are 0 records of the requested type. This is inconsistent with `fallthrough` implementations in other plugins which only fall through for NXDOMAINs.

So looks like a bug.

**Comment by mrdima** [comment]
Ok, if this is a bug, will this issue be re-opened or does a new one need to be created?

**Comment by ykhr53** [comment]
I've made a PR for this issue.
