### ISSUE TITLE
plugin/etcd: support zone transfers

### ISSUE THREAD

**Issue by ramnes** [coredns/coredns#2585]
As far as I understand, `plugin/etcd` doesn't support zone transfers so far, and that would be a great feature for us, in combination with ExternalDNS plugged to our Kubernetes cluster's CoreDNS.

I don't know much about Go nor AXFR, but if this is something that you guys are interested in, and if no one else does it, I'll eventually try to tackle this feature.

**Comment by miekg** [comment]
This could be done in similar vein as the k8s implements it and should be fairly straight forward.

Note:
* you need some (cheap) way to detect changes in etcd (or use a time based system, where you assume things changes every minute or so)
* you can't get about fetching remote CNAMEs, i.e. everything transferable is in etcd.

**Comment by miekg** [comment]
After this (or during) we can also unify all the code dealing with this, and just make each plugin implement an interface after which they can do zone transfers.

**Comment by ramnes** [comment]
Why not before, so that we can directly use that said interface for the etcd plugin? :)

**Comment by miekg** [comment]
sure; I think you may only need an Records() method that returns the records and a SOA() for the SOA. Still need some code in the plugin to handle to axfr request and send it though.

**Comment by JensErat** [comment]
Same for the dnssec-plugin, which does not support AXFR.

**Comment by miekg** [comment]
but the dnssec plugin doesn't own any data, so there is nothing transfer. Or are you proposing that we sign an axfr?

**Comment by JensErat** [comment]
Yes. I somewhat have the feeling that AXFR should be its own plugin pretty much at the end of the plugin chain that just allows anything else to happen before. And dnssec is just in front -- consider signing Kubernetes (zone transfers), ...

Right now, it's pretty hard running CoreOS as primary DNS server, as there is no reliable zone transfer. In my opinion, a good solution for a CoreDNS operator would be any plugin has a "transfer" interface (like already somewhat proposed in here) and chained plugins can also enrich those transfer zones (like dnssec or any of the others rewriting). So in the end an AXFR provides a complete dump of what CoreOS would respond itself, at least wherever reasonably possible.

**Comment by miekg** [comment]
thought about doing that (i.e. transfer as  a plugin). At the time I couldn't work out how that should work.

**Comment by ramnes** [comment]
To be honest this is exactly what I thought I would see in the codebase before realizing that every plugin was implementing AXFR on its own side. So yeah, I'd love to see an AXFR plugin, that would make CoreDNS much simpler and accessible in my opinion.

> thought about doing that (i.e. transfer as a plugin). At the time I couldn't work out how that should work.

And what about now? :)

If I take an example from the README, I would love to be able to modify it and write something in those lines:

```
example.org:1053 {
    file /var/lib/coredns/example.org.signed
    axfr {
        transfer to *
        notify 2001:500:8f::53
    }
    errors
    log
}
```
(or even to throw away the `axfr {...}` structure and just put everything at the same level)

From my very naive perspective, I guess that every module that owns records should expose a function that lists all records, which would be read by the axfr module.

**Comment by miekg** [comment]
Yeah. Something like that could work and would remove a bunch of duplicated
code. Requires a method or interface to be implemented by the plugin, have
to figure out how to call the correct one.

**Comment by ramnes** [comment]
How do you want to move forward on this @miekg? Do you want me to open issue related to the refactoring? Or should I try to tackle this first and then we'll see for the refactoring later?

**Comment by miekg** [comment]
I think a new plugin makes perfect sense. Let's see how that looks and what
plugins need to implement

Thanks!

**Comment by JensErat** [comment]
I've been reading through the code for a while now, and I am not entirely sure whether the transfer plugin makes really sense/is required. It _might_ be to handle XFR allowance in general, but neither for offering etcd transfers (which I don't really care about) nor to sign them (and maybe I should stop hijacking this issue and open a new one -- but so far the argumentation is somewhat general).

Are those assumptions correct?

- When an XFR happens, the usual plugin chain is walked through. The first plugin able to answer will do so, using the `ResponseWriter` passed through.
- The `dnssec` plugin could also implement the `ResponseWriter` interface and hook into there. Doing so, it could fetch a transfer and sign the individual result lines. The cache plugin already gets transfers passed through, but ignores them.

Considering this, it might make sense to provide a transfer plugin which handles decisions on whether to allow a transfer (or denies the request otherwise), but everything else could be handled easily using the existing plugin structure: any "zone providing" plugin would have to implement XFR queries, any "zone enriching" plugin like dnssec would implement the `ResponseWriter` interface to fiddle with the answer.

I'm pretty sure I am wrong on this assumption, but cannot really provide an argument why:

- It makes not really sense to offer for example etcd and file plugins available for the same zone.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/etcd: ..." ]
>I've been reading through the code for a while now, and I am not entirely sure whether the transfer plugin makes really sense/is required. It _might_ be to handle XFR allowance in general, but neither for offering etcd transfers (which I don't really care about) nor to sign them (and maybe I should stop hijacking this issue and open a new one -- but so far the argumentation is somewhat general).
>
>Are those assumptions correct?

I think you are. The problems seems to be that the transfer plugin doesn't know 
what plugin will be authoritative for the transfer so it can call out it and get 
the data. If it waits for a reply the transfer has already been triggered in 
some plugin down the chain and there is nothing for the transfer plugin to do 
(extra).

>- It makes not really sense to offer for example etcd and file plugins available for the same zone.

yep, that the crux, I think I've found the words in the above paragraph to say 
why this can't work.

Would be good to put this somewhere in some doc.

**Comment by JensErat** [comment]
So any reasonable kind of transfer plugin would just validate authorization (may the server receive a transfer for that zone?) and either deny or do nothing at all. Another plugin down the chain will take care of providing the actual zone transfer. Still makes sense to me, or is there a better way _not_ to replicate this behavior? Then again -- how to deal with a reasonable default (which would be deny)?

The DNSSEC signing part would still make sense? If so, I would open a new issue and have a try at implementing the DNSSEC part.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/etcd: ..." ]
>So any reasonable kind of transfer plugin would just validate authorization (may the server receive a transfer for that zone?) and either deny or do nothing at all. Another plugin down the chain will take care of providing the actual zone transfer. Still makes sense to me, or is there a better way _not_ to replicate this behavior? Then again -- how to deal with a reasonable default (which would be deny)?

yes, but now you create the problem where different plugins want different 
options.

Think the de-duplication is only possible on the code level which means putting 
(more) stuff in plugin/pkg/... 

>The DNSSEC signing part would still make sense? If so, I would open a new issue and have a try at implementing the DNSSEC part.

yes, I think signing an entire transfer can be useful.

/Miek

--
Miek Gieben

**Comment by ramnes** [comment]
> > It makes not really sense to offer for example etcd and file plugins available for the same zone.
>
> yep, that the crux, I think I've found the words in the above paragraph to say why this can't work.

Why not thought? I would expect something like this to work:

```
.:53 {
    kubernetes cluster.local
    etcd skydns.local {
        path /skydns
        endpoint http://localhost:2379
        upstream
    }
    axfr {
        transfer to *
        notify 2001:500:8f::53     
   }
}
```

**Comment by miekg** [comment]
Transfer what? Now add a file stanza in there as well for a different zone

**Comment by ramnes** [comment]
Whatever the AXFR request asks for! Am I missing something?

**Comment by miekg** [comment]
Maybe there is a way. Each plugin will know what zones it is authoritative
for, so transfer can ask when it sees an incoming request. It just needs a
list of plugins to ask (this is already done in the ready and autopath
plugins for instance). First one replying with OK wins.

As highlighted in this discussion how to deal with plugins that use
different settings for zone transfers? Don't care about that?

**Comment by ramnes** [comment]
> As highlighted in this discussion how to deal with plugins that use different settings for zone transfers? Don't care about that?

From my naive perspective, then you'd do multiple blocks:

```
cluster.local:53 {
    kubernetes
    axfr {
        transfer to *
        notify 2001:500:8f::53     
   }
}

skydns.local:53 {
    etcd {
        path /skydns
        endpoint http://localhost:2379
        upstream
    }
    axfr {
        transfer to *
    }
}
```

**Comment by miekg** [comment]
That good work. Think it's time to see some code and how this can fit
together.

**Comment by ramnes** [comment]
Another idea that I just came with would be to allow the plugin to take zones (or not):

```
.:53 {
    kubernetes cluster.local
    etcd skydns.local {
        path /skydns
        endpoint http://localhost:2379
        upstream
    }
    axfr {
        transfer to *
    }
    axfr skydns.local {
        notify 2001:500:8f::53
   }
}
``` 

This would have the advantage of making `transfer from` possible to implement, which could even deprecate the `secondary` plugin so that there is only one plugin for all AXFR stuff, either of both ways.

Plus, my previous example would still be valid.

**Comment by JensErat** [comment]
I also like the idea of providing a dedicated notify option. When this is changed anyway, I'd opt for adding a [notify-source option like bind9 has](http://www.zytrax.com/books/dns/ch7/xfer.html#notify-source) -- if a server has multiple interfaces, you can be sure the wrong one will be picked up for sending the notify (and the receiving server will refuse).

I'm not sure whether having a common transfer plugin would be better than having dedicated receive and send plugins -- is there any reasonable shared functionality that could not be extracted to some kind of package? `transfer` would probably be a better name than `axfr`; maybe CoreDNS will support incremental transfers at some time.

I agree with ramnes proposal of having multiple server blocks if you need different transfer options.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/etcd: ..." ]
>Another idea that I just came with would be to allow the plugin to take zones (or not):
>
>```
>.:53 {
>    kubernetes cluster.local
>    etcd skydns.local {
>        path /skydns
>        endpoint http://localhost:2379
>        upstream
>    }
>    axfr {
>        transfer to *
>    }
>    axfr skydns.local {
>        notify 2001:500:8f::53
>   }
>}
>```
>
>This would have the advantage of making `transfer from` possible to implement, which could even deprecate the `secondary` plugin so that there is only one plugin for all AXFR stuff, either of both ways.

lgtm

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/etcd: ..." ]
>I also like the idea of providing a dedicated notify option. When this is changed anyway, I'd opt for adding a [notify-source option like bind9 has](http://www.zytrax.com/books/dns/ch7/xfer.html#notify-source) -- if a server has multiple interfaces, you can be sure the wrong one will be picked up for sending the notify (and the receiving server will refuse).
>
>I'm not sure whether having a common transfer plugin would be better than having dedicated receive and send plugins -- is there any reasonable shared functionality that could not be extracted to some kind of package? `transfer` would probably be a better name than `axfr`; maybe CoreDNS will support incremental transfers at some time.
>
>I agree with ramnes proposal of having multiple server blocks if you need different transfer options.

fair enough, but probably a worth a new issue?

**Comment by miekg** [comment]
the new transfer plugin might make this a lot easier.

**Comment by miekg** [comment]
please reopen when someone start to work on it

**Comment by joeyjy** [comment]
> please reopen when someone start to work on it

Hi @miekg 
I'm using etcd as dns records backend. I'm tring to do an axfr transfer using `dig @myCoreDNSServerIP axfr mydomain.com`, but only receive a SOA response and `Transfer failed` notification.
```
; <<>> DiG 9.9.4-RedHat-9.9.4-74.el7_6.1 <<>> @myCoreDNSServerIP axfr mydomain.com
; (1 server found)
;; global options: +cmd
mydomain.com. 5   IN      SOA     ns.dns.mydomain.com. hostmaster.mydomain.com. 1655704991 7200 1800 86400 30
; Transfer failed.
```
Is there anything I missed in configuration? My Corefile is below:
```
.:53 {
    etcd mydomain.com 10.in-addr.arpa {
        stubzones
        path /coredns
        endpoint http://10.9.90.9:2379 http://10.9.90.17:2379 http://10.9.89.8:2379

        upstream /etc/resolv.conf

        fallthrough
    }
    prometheus
    cache 30
    loadbalance
    forward . /etc/resolv.conf
    log
    transfer {
        to *
    }
}
```
And my dns records stored in etcd is like following:
```
/coredns/com/mydomain/pod03
{"host":"10.62.130.133","ttl":10}
/coredns/arpa/in-addr/10/62/130/133
{"host":"pod03.mydomain.com","ttl":10}
```
Thanks!

**Comment by chrisohaver** [comment]
@joeyjy, the etcd plugin does not support zone transfers.

**Comment by joeyjy** [comment]
> @joeyjy, the etcd plugin does not support zone transfers.

Oh, I see...Thanks @chrisohaver
