### ISSUE TITLE
How to do CNAME

### ISSUE THREAD

**Issue by ckcd** [coredns/coredns#2596]
Hi, 

I want `CoreDNS` do `CNAME` for my cluster, for example when i `dig example1.org`, `CoreDNS` trans it to `example2.org` and return to me a `CNAME` and a `A`, which maybe looks like:

```
$ dig example1.org

;; ANSWER SECTION:
example1.org.		168	  IN	CNAME	example2.org.
example2.org.	        168	  IN	A	1.1.1.1
```

is there any `plugin` can do this `CNAME` ?

Thanks !!!

**Comment by chrisohaver** [comment]
`file` plugin would work for your example.

For a CNAME in the k8s cluster domain, you could define an ExternalName Service in k8s.
