### ISSUE TITLE
plugin/errors: both cLogger and eLogger are not needed

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2605]
The struct fields `cLogger` and `eLogger` are not needed and can be easily removed, they look only to be added for testing which can be done like is done in the *log* package.

Hence this can be removed and cleaned up.

**Comment by rdrozhdzh** [comment]
@miekg could you please refer the similar code in _log_ package?

**Comment by miekg** [comment]
This pattern can be re-used: https://github.com/coredns/coredns/blob/master/plugin/log/log_test.go#L29

also the use of regular expression might need a rethink, although this is not directly in the query path.

**Comment by rdrozhdzh** [comment]
ok, I guess I understood now.
You want the test to parse log output instead of intercepting logging functions, right?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/errors..." ]
>ok, I guess I understood now.
>You want the test to parse log output instead of intercepting logging functions, right?

yes, just examing the output should work here as well.

**Comment by rdrozhdzh** [comment]
ok, I will rework the test.

Regarding regular expressions, do you think we can replace them with smth more light-weight like comparing to substrings? We'll need to test if this could give us any benefits comparing to regexp

**Comment by miekg** [comment]
Yes substring match will most definitely be faster. But as said this is
outside the direct serving path, so YMMV.

**Comment by miekg** [comment]
closed via #2657
