### ISSUE TITLE
CoreDNS 1.4.0 tracking issue

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2612]
Track CoreDNS 1.4.0 release

**Comment by stp-ip** [comment]
I assume we won't cut a 1.3.2 release.
Would love to have #2536 in 1.4.0 (#2516 is already merged) and ideally the deprecation notice in 1.4.0 or 1.3.2 release notes.
That would let us remove the code in 1.5.0 or 1.6.0.

Both deprecations are already documented within our docs.

Release notes:
```
Deprecation: plugin/auto deprecates TIMEOUT and recommends the use of RELOAD #2516.
Deprecation: plugin/auto and plugin/file deprecates NO_RELOAD and recommends the use of RELOAD set to 0 #2536.
```

**Comment by miekg** [comment]
Ack, but I want to kick off a release soonish, maybe this weekend. Accumulated quite a lot of bug fixes and features.

**Comment by miekg** [comment]
https://coredns.io/2019/03/03/coredns-1.4.0-release/
