### ISSUE TITLE
plugin/forward responds with FORMERR at high query rate

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#2636]
The problem is reproduced only at high load, when incoming QPS higher than total QPS of upstream servers. At such conditions, almost all outgoing UDP ports to upstream are in use, so it is high probability that as soon as we close any UDP connection another goroutine will open new connection on the same port.

So, we get incoming DNS request and open UDP connection to upstream, wait 2 seconds (timeout) and close this connection (don't return it to cache). Then we do the same with next DNS request - open new UDP connection (since we don't have connections in cache) and this new connection is opened with the same source port as that connection we used before. At this point we may receive response from upstream (for previous query) and send new request - in any order. So, when we read response we expect that we got response for latest query whereas we got response for previous query.

To fix this, we should drop all responses with incorrect id when reading response from connection

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/forward re..." ]
>The problem is reproduced only at high load, when incoming QPS higher than total QPS of upstream servers. At such conditions, almost all outgoing UDP ports to upstream are in use, so it is high probability that as soon as we close any UDP connection another goroutine will open new connection on the same port.
>
>So, we get incoming DNS request and open UDP connection to upstream, wait 2 seconds (timeout) and close this connection (don't return it to cache). Then we do the same with next DNS request - open new UDP connection (since we don't have connections in cache) and this new connection is opened with the same source port as that connection we used before. At this point we may receive response from upstream (for previous query) and send new request - in any order. So, when we read response we expect that we got response for latest query whereas we got response for previous query.
>
>To fix this, we should drop all responses with incorrect id when reading response from connection

ok, make sense. Should we log those?

**Comment by rdrozhdzh** [comment]
hm, I'm not sure about logging - this may just create extra load to coredns

**Comment by miekg** [comment]
Closed via #2637
