### ISSUE TITLE
New upstream update is not reflecting inside of pod in /etc/resolv.conf file

### ISSUE THREAD

**Issue by cmpmohan47** [coredns/coredns#2639]
Issue:

I have updated coredns configmap with new upstream server details (8.8.8.8 and  8.8.4.4).  but same upstream server details is not reflecting inside of new POD in /etc/resolv.conf file. coredns pod is running on kubernetes 1.13 version

please find below 3 steps what i followed and let me know if im right path to update upstream and stub domains?

1)I have edited coreDNS as below to add upstream server(8.8.8.8 8.8.4.4)

 kubectl  --namespace=kube-system edit configmap coredns
configmap/coredns edited

2) kubectl  --namespace=kube-system describe configmap coredns
Name:         coredns
Namespace:    kube-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","data":{"Corefile":".:53 {\n    log\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n    ...

Data
====
Corefile:
----
.:53 {
    log
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream 8.8.8.8 8.8.4.4
       fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}

Events:  <none>

3)  I deleted the coredns pod i,e recreated it

**Comment by chrisohaver** [comment]
The above is not the right way to do upstream and stub domains... see ...

https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
