### ISSUE TITLE
kubernetes option endpoint_pod_names does not work as documented

### ISSUE THREAD

**Issue by PeterGrace** [coredns/coredns#2640]
I am using CoreDNS docker container version 1.3.1 as a replacement for kube-dns in my cluster.

When attempting to lookup a pod name with hostname elastichq-pod, NXDOMAIN is returned.  However, if I look up the pod name as provided in `kubectl get pods`, it resolves:

```
root@dnsutils-7c6fd675dc-glcvn:/# host elastichq-pod.elastichq.monitoring.svc.cluster.local
Host elastichq-pod.elastichq.monitoring.svc.cluster.local not found: 3(NXDOMAIN)

root@dnsutils-7c6fd675dc-glcvn:/# host elastichq-7bbffb6f49-cxqc8.elastichq.monitoring.svc.cluster.local
elastichq-7bbffb6f49-cxqc8.elastichq.monitoring.svc.cluster.local has address 10.42.3.39
```

The pod does have the appropriate hostname under spec:
```
$ kubectl get pod -n monitoring elastichq-7bbffb6f49-cxqc8 -o jsonpath={.spec.hostname}
elastichq-pod
```

I have configured coredns as follows:
```
    .:53 {
        cache 30
        log
        errors
        health
        kubernetes cluster.local {
            transfer to *
            pods insecure
            endpoint_pod_names
        }
        loadbalance round_robin
        prometheus 0.0.0.0:9153
        proxy . /etc/resolv.conf
    }
```

The docs for endpoint_pod_names are thus:

>endpoint_pod_names uses the pod name of the pod targeted by the endpoint as the endpoint name in A records, e.g., endpoint-name.my-service.namespace.svc.cluster.local. in A 1.2.3.4 By default, the endpoint-name name selection is as follows: Use the hostname of the endpoint, or if hostname is not set, use the dashed form of the endpoint IP address (e.g., 1-2-3-4.my-service.namespace.svc.cluster.local.) If this directive is included, then name selection for endpoints changes as follows: **Use the hostname of the endpoint**, or if hostname is not set, use the pod name of the pod targeted by the endpoint. If there is no pod targeted by the endpoint, use the dashed IP address form.

Does anyone have some tips on what I might be doing wrong?

**Comment by chrisohaver** [comment]
Per code, looks like the hostname is retrieved via the endpoints object ... Can you confirm that the Endpoints object also has the hostname in it (as should be expected)?  e.g. 

```
 kubectl get endpoints -n monitoring elastichq -o jsonpath={.subsets[*].addresses[*].hostname}
```

**Comment by PeterGrace** [comment]
There is no hostname in the endpoint object.  That's interesting; shouldn't the endpoint gather the hostname of the pod?  There's a name field, but not hostname:

```
subsets:
- addresses:
  - ip: 10.42.4.63
    nodeName: k8snode02
    targetRef:
      kind: Pod
      name: elastichq-65f7cf6677-gjn5q
      namespace: monitoring
      resourceVersion: "2911507"
      uid: 17f17c05-3d50-11e9-b841-060c2954d618
```

the hostname is definitely set in the pod, though:

```
$ kubectl exec -n monitoring -ti elastichq-65f7cf6677-gjn5q /bin/sh
/src # hostname
elastichq-pod
/src #
```

**Comment by miekg** [comment]
looks stale
