### ISSUE TITLE
plugin/forward: stop processing query after 6 seconds

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2663]
When forwarding queries you don't have control over how long a query will take to resolve. For local queries (in mem database or something close-by) things are easier because faster.

As (client) resolver timeout after 5 seocnds anyway, we can probably drop queries if we're still dealing with them after 6 seconds.

Not sure if you need to write anything to the client after that time, I think not because it's probably resending the query anyway.

**Comment by miekg** [comment]
This can easily be *setup* with `context.WithTimeout` (https://godoc.org/context#WithTimeout). The other side and actually checking is more problematic? Or can this easily be done at the entry point of each ServeDNS, or even in the core server code? Depends a bit how far along we are in the starting of the goroutine.

**Comment by miekg** [comment]
I have an easy change, but since I lack an easy test, @WinstonPrivacy can you easily test a branch/pr?

**Comment by miekg** [comment]
#2711

**Comment by WinstonPrivacy** [comment]
Yes, we will try this.

**Comment by willwp** [comment]
@miekg giving this a quick try for @WinstonPrivacy.

**Comment by willwp** [comment]
@miekg ran the following test on the same setup as @WinstonPrivacy. 
CoreDNS branch cancel, go v1.12
```
.:53 {                                                       
       cache 3600                                        
       forward . tls://1.1.1.1 tls://1.0.0.1 {
               tls_servername cloudflare-dns.com
               health_check 5s                  
               max_fails 1                      
               expire 90s                       
       }                                        
       alternate SERVFAIL . tls://9.9.9.9 tls://149.112.112.112 {
                tls_servername dns.quad9.net                     
                health_check 5s                                  
                max_fails 1                                      
                expire 90s                                       
       }                                    
       cancel 5s               
       prometheus 0.0.0.0:9090
       pprof 0.0.0.0:6053     
}                             
.:54 {                        
       cache 3600                                      
       forward . tls://1.1.1.1 tls://1.0.0.1 {         
               tls_servername cloudflare-dns.com       
               health_check 5s                         
               max_fails 1                             
               expire 90s                       
        }                                       
        alternate SERVFAIL . tls://9.9.9.9 tls://149.112.112.112 {
               tls_servername dns.quad9.net                       
               health_check 5s                                    
               max_fails 1                                        
               expire 90s                                         
        }                                                         
        cancel 5s                          
}                
```
I ran the following command
`dnsperf -s 192.168.102.1 -p 53 -d queryfile-example-10million-201202 -l 300 -c 30 -Q 2000`
Along with several devices streaming video, and gaming
CoreDNS cpu spiked, and Memory demand spiked.  I stopped the above dnsperf test after ~120 seconds.   CoreDNS remained in a peak state resource demand state: high CPU, and high memory.  The CoreDNS service only calmed down after our monitoring service restarted the service.  Attached is the Prometheus data
![Memory](https://user-images.githubusercontent.com/40573407/54969580-aa03df00-4f4c-11e9-81e7-20a3fccedf54.png)
![MemStats_GoRoutines](https://user-images.githubusercontent.com/40573407/54969582-ae2ffc80-4f4c-11e9-942f-c74252b9f24b.png)
![ProcessCPU_ReqCount](https://user-images.githubusercontent.com/40573407/54969585-af612980-4f4c-11e9-819a-df7c9f644a0d.png)

**Comment by chrisohaver** [comment]
That #2711 doesn't help very much lines up with our observations in testing (time is spent locked on writing to the client). #2711 could help if, for example upstream servers are very slow to respond.  But this doesn't need to be the case for the memory spike to occur.

Have you tried the _throttle_ plugin proposed by @fturib #2706?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>@miekg giving this a quick try for @WinstonPrivacy.

ack, but it didn't do anything yet, as the forward plugin doesn't check the 
context status (yet). It also remains to be seen if we really hang on to 
go-routines for more than 6 seconds.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>That #2711 doesn't help very much lines up with our observations in testing (time is spent locked on writing to the client). #2711 could help if, for example upstream servers are very slow to respond.  But this doesn't need to be the case for the memory spike to occur.
>
>Have you tried the _throttle_ plugin proposed by @fturib #2706?

 #2706 can be summerized as: if we don't do any work, nothing will break
 (execpt your application won't get any DNS service)

**Comment by chrisohaver** [comment]
I had accidentally posted that comment this issue, thinking it was the QPS memory spike issue, and deleted it immediately after.  Email still went out though. Nevertheless...

> #2706 can be summerized as: if we don't do any work, nothing will break
 (execpt your application won't get any DNS service)

_Throttle_ limits the number of concurrent queries.  It doesn't start dropping _everything_ once the the limit is reached, just those that would exceed the number of concurrent queries.  It still serves the queries that are already in flight. I would imagine that a limit on the number of concurrent queries is not atypical for DNS servers.  This prevents memory from blowing up beyond the available resources during QPS spikes that exceed expected maximum rate. It's akin to a pressure release valve, that drops packets to prevent an even worse situation - explosion.  If the requirement is to handle those spikes _without_ dropping queries, then one should scale up so coredns _can_ handle them (horizontally/vertically).

**Comment by miekg** [comment]
the 6 s rule is already true in forward:
~~~
	deadline := time.Now().Add(defaultTimeout)
	start := time.Now()
	for time.Now().Before(deadline) {
~~~
and `defaultTimeout` is 5 seconds, even.

We may want to explicitly cancel the context, but I think the *cancel* plugin is slight neater way of accomplishing that.
