### ISSUE TITLE
Remove `defer` from hotpath

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2664]
there are a bunch of `defer`s in the hotpath, in `core/dnsserver/server.go` we do this for error handling. There may be other places, it would be good to remove this from these functions.

**Comment by yongtang** [comment]
Defer used to have performance issue before:
https://medium.com/i0exception/runtime-overhead-of-using-defer-in-go-7140d5c40e32

I haven't investigated recently though so not sure if golang has improved in this area or not. But overall I think it is always not bad to avoid using defer, unless there are too many exit path.

**Comment by miekg** [comment]
There are defers in the low-level socket writing functions, not sure if the effort here is worth it, unless a benchmark says so.
