### ISSUE TITLE
CoreDNS 1.5.0 Release tracking bug

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2669]
I think the next release should be numbered 1.5.0 as we heavily deprecating things left and right. Filing the tracking bug.

We've tracked down the weird behavior where coredns would hug the cpu (and didn't release) and use large amounts of memory. This should be slightly better; but a lot of goroutines still equates to memory being used. Not sure how long I would want to hold up a release, while we work to improve this - several bugs have been filled.

**Comment by fturib** [comment]
@miekg : do you have an idea of timeline you expect for this 1.5.0 ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS 1.5.0..." ]
>@miekg : do you have an idea of timeline you expect for this 1.5.0 ?

soon, I think. We root-caused the cpu/mem situation and rollback some code to 
make that work better, so releasing that seems good. After that we can work on
improvements.

**Comment by miekg** [comment]
accumulated enough to have a release, I'm kicking of a release somewhere today.

**Comment by miekg** [comment]
<strike>what I figured, go modules broke this :( also little to no output in the logs.</strike>
Scratch that, build is fine. *sigh*

**Comment by miekg** [comment]
did it manually.
