### ISSUE TITLE
go modules: cache download in travis

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2684]
@yongtang can we cache the downloads of the modules in travis? Seems multiple tests stage now all download the modules again? Or some other way to not do this?

**Comment by yongtang** [comment]
@miekg Added the cache for go mod in Travis CI in PR #2686.

With caching, there are some improvement:

Before: https://travis-ci.org/coredns/coredns/builds/505455464

- 8min50s
- 4min7s
- 4min38s
- 5min56s

After: https://travis-ci.org/coredns/coredns/builds/505582381

- 7min
- 3min27s
- 3min24s
- 5min16s

**Comment by miekg** [comment]
I also merged, do net test etcd; that gives another speedup.

This is btw also more robust. So +1

closed via #2686
