### ISSUE TITLE
etcd setup test Error

### ISSUE THREAD

**Issue by jjmengze** [coredns/coredns#2692]
Does anyone know why?

When I was in this commit f798d18bddddd61ed5469e1ce43dd19522630426, I went to the test plugin/etcd/setup_test.go and got the following error.

```bash
$GO111MODULE=on go test -v -tags 'etcd' -run=TestSetupEtcd
=== RUN   TestSetupEtcd
--- FAIL: TestSetupEtcd (0.01s)
    setup_test.go:95: Test 6: Expected no error but found one for input etcd {
        			endpoint http://localhost:2379
        			credentials username password
        		}
        			. Error was: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>
FAIL
exit status 1
FAIL	github.com/coredns/coredns/plugin/etcd	0.015s
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] etcd setup test E..." ]
>Does anyone know why?

yes, there is no etcd running, and this test expects one.

**Comment by jjmengze** [comment]
@miekg thanks a lot !

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] etcd setup test E..." ]
>Does anyone know why?

/plugin: etcd
/label: question
