### ISSUE TITLE
Dedup some code between grpc and proxy plugin

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2695]
Now that there are two *forwarding* plugins (*forward* and *grpc*), there is some code duplicated between the two; it worth checking if some of it can be factored into a couple of common packages under /plugin/pkg

**Comment by inigohu** [comment]
Both have the same _policy_ implemented. Maybe we can move that to pkg.

**Comment by miekg** [comment]
yeah, could be although that not a lot of code, nor is it complex. I.e. this is not a call to avoid duplication at any cost. Maybe there is not tangible to extract.

**Comment by palash25** [comment]
Hi, @miekg I would like to take this up. Besides `policy.go` I see the following duplicate methods between these two plugins

```go
func (f *Forward) Len() int { return len(f.proxies) }

func (f *Forward) isAllowedDomain(name string) bool

func (f *Forward) match(state request.Request) bool

func (f *Forward) List() []*Proxy { return f.p.List(f.proxies) }
```

could make small changes to them; to not be defined on a particular struct and pass an interface as an argument instead and move these to the pkg dir. 

For example

```go
func match(plugin interface{}, state request.Request) bool
```


not sure if this is a desirable change or not let me know if you would like something like this to be included in the PR too.

**Comment by miekg** [comment]
I think match and isAllowedDomain (they are used together anyway) is good to be abstracted into a shared package.

The signature for match would be better as: `match(state request.Request, name ...string) bool`

What would be a good name for this package? We could put `isAllowedDomain` in pkg/dnsutil ? Or something?

**Comment by palash25** [comment]
> What would be a good name for this package? We could put isAllowedDomain in pkg/dnsutil ? Or something?

For now I am putting them in a file called match.go under pkg/dnsutil

Other alternatives could be a separate package called `pkg/utils` or `pkg/forward` (since these are utility functions used only by the forwarding plugins)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Dedup some co..." ]
>> What would be a good name for this package? We could put isAllowedDomain in pkg/dnsutil ? Or something?
>
>For now I am putting them in a file called match.go under pkg/dnsutil
>
>Other alternatives could be a separate package called `pkg/utils` or `pkg/forward` (since these are utility functions used only by the forwarding plugins)

dnsutil sgtm

**Comment by sharmaansh21** [comment]
I don't think anyone is looking into it, I can work in it.

**Comment by palash25** [comment]
Sure go ahead @sharmaanshul2102

**Comment by miekg** [comment]
see 5e04c272 which cleans up the policy bits, further things can be dedupped, but overdoing it is also a risk. Closing.

**Comment by chrisohaver** [comment]
5e04c27 reverted due regression. reopening this issue in case we want to try to tackle this again.

**Comment by rdrozhdzh** [comment]
Policy could be implemented as simple as below
```
const (
	PolicyRandom = iota
	PolicyRoundRobin
	PolicySequential
)

type Policy struct {
	start uint32
	total uint32
	First func() int
}

func NewPolicy(total, pType int) Policy {
	if total < 1 {
		panic("policy: bad total")
	}
	p := Policy{total: uint32(total)}
	switch pType {
	case PolicyRandom:
		p.First = func() int {
			return rand.Intn(int(p.total))
		}
	case PolicyRoundRobin:
		p.First = func() int {
			return int(atomic.AddUint32(&p.start, 1) % p.total)
		}
	case PolicySequential:
		p.First = func() int {
			return 0
		}
	default:
		panic("policy: bad policy type")
	}
	return p
}

func (p Policy) Next(cur int) int {
	return (cur + 1) % int(p.total)
}
```
`p.First()` returns index of the first element
`p.Next(i)` returns index of next element

No interfaces, no needs to allocate temporary lists on each query, can be used in both grpc and forward plugins.
