### ISSUE TITLE
Reverse plugin still has README, even though it was removed

### ISSUE THREAD

**Issue by Feder1co5oave** [coredns/coredns#2702]
https://coredns.io/plugins/reverse/ still contains documentation of the `reverse` plugin, even though it was deprecated after #1502 and then removed in #1713. No mention of this is present on that page, nor on the plugin list: https://coredns.io/plugins/.

Putting it in the Corefile causes coredns to issue a "reverse directive unknown", as it should.

I guess this violates the non-mandatory rules for plugin deprecation proposed in https://github.com/coredns/coredns/issues/1384#issuecomment-357668950

**Comment by miekg** [comment]
that should have been removed, please open a pr/issue against the coredns.io repo
