### ISSUE TITLE
Request for increasing number of concurrent supported releases

### ISSUE THREAD

**Issue by rtheis** [coredns/coredns#2708]
This request is triggered from discussions for https://github.com/kubernetes/kubernetes/issues/75414 where it was noted that the CoreDNS project has historically maintained a single release track.  Given that CoreDNS is now the default cluster DNS for Kubernetes and likely gaining additional usage after CNCF graduation, I'd like the CoreDNS project to consider increasing the number of supported `major.minor` releases.  Of primary interest is an increased support window for critical bug fixes and security vulnerabilities.  Thank you for your consideration.

**Comment by miekg** [comment]
We have this defined in https://github.com/coredns/coredns/blob/master/SECURITY-RELEASE-PROCESS.md

For normal bugfixes, I don't think we have the people power to manage this.

/Miek

--
Miek Gieben

**Comment by rtheis** [comment]
@miekg Thanks for the link.  Is there a document detailing how long folks can expect support for a given `major.minor` release for bug fixes and/or security patches?  I didn't see that detailed in your referenced link (apologies if I missed it).

**Comment by chrisohaver** [comment]
One challenge to sticking to a single release track relates to CoreDNS' comparatively rapid release and deprecation schedule.  CoreDNS goes from announcement to removal of a deprecated feature in 2 releases, and releases occur every 1-2 months roughly.  If we were to always include the latest CoreDNS version in each K8s release, this can result in a ~feature disappearing~ option becoming invalid or plugin being removed without warning from one k8s version to the next.  

The conflicting velocities can also put us in a difficult situation where for example, we need to fix critical bug in CoreDNS in a prior release of Kubernetes. The version of CoreDNS with the fix may be many versions ahead, and using it could result in introducing backward incompatible changes in a K8s patch release.

**Comment by miekg** [comment]
I don't see how another's project release schedule should impact us?

And I also don't understand how "features" disappear.

**Comment by chrisohaver** [comment]
The question is: "Are we going to release security and critical bug fixes on previous releases."

I think the answer is that we should.

Follow up questions:
"For which previous releases will we do this?" 1? 2? more?
"What defines a critical bug fix?" project leader decides?

**Comment by miekg** [comment]
If you have folks that are willing to take on this work, then yes please. Otherwise it can't happen.

**Comment by rtheis** [comment]
@miekg Thank you.  I completely understand that more contributors are needed to make this happen.  I'll see what I can do on my end.
