### ISSUE TITLE
External CNAME queries from pods get k8s TTL of 5

### ISSUE THREAD

**Issue by InAnimaTe** [coredns/coredns#2710]
Any request which is a CNAME gets a `5` TTL value, even with `MINTTL` changes in configuration.

```
image: k8s.gcr.io/coredns:1.1.3
```

```
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        autopath @kubernetes
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 3600 {
            success 19968 3600 120
        }
        reload
    }
```

```
engage-7c74d44698-wc6tj# dig database.coderpcc8yvnx.us-east-1.rds.amazonaws.com

; <<>> DiG 9.12.3 <<>> database.coderpcc8yvnx.us-east-1.rds.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18823
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;database.coderpcc8yvnx.us-east-1.rds.amazonaws.com. IN A

;; ANSWER SECTION:
database.coderpcc8yvnx.us-east-1.rds.amazonaws.com. 5 IN CNAME ec2-34-197-171-188.compute-1.amazonaws.com.
ec2-34-197-171-188.compute-1.amazonaws.com. 5 IN A 34.197.171.188

;; Query time: 6 msec
;; SERVER: 10.3.0.10#53(10.3.0.10)
;; WHEN: Thu Mar 21 16:38:10 UTC 2019
;; MSG SIZE  rcvd: 239

engage-7c74d44698-wc6tj# dig google.com

; <<>> DiG 9.12.3 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4700
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		60	IN	A	172.217.15.78

;; Query time: 2 msec
;; SERVER: 10.3.0.10#53(10.3.0.10)
;; WHEN: Thu Mar 21 16:38:12 UTC 2019
;; MSG SIZE  rcvd: 65
```

**Comment by InAnimaTe** [comment]
Actually, the `dig google.com` seems to prove that MINTTL isn't working either. Unless I just really don't understand how these TTL values work in relation to cache @chrisohaver ^^^

**Comment by chrisohaver** [comment]
Looks like a bug.  According to the README setting MINTTL should override the cache minimum.  So, your configuration should cache items for 120 at least.

**Comment by chrisohaver** [comment]
I tested this on master, and it works as expected.  ~What version of coredns are you using?~
oh - you already said, I didnt see...

**Comment by chrisohaver** [comment]
1.1.3 is a bit old, and apparently has this MINTTL bug.  I'd recommend updating to 1.2.6 (version that was published with K8s 1.13).

**Comment by chrisohaver** [comment]
Oh - it's not a bug in 1.1.3.  MINTTL wasn't a feature yet in 1.1.3.  I guess the parser in 1.1.3 tolerated extra cruft at the end of the `success` line.  So basically it's being ignored.

**Comment by chrisohaver** [comment]
Also, FWIW, Something i noticed in your Corefile, unrelated to this issue:  If you want to use `autopath` you must also use `pods verified` in the `kubernetes` stanza.  Otherwise `autopath` won't actually do anything.

**Comment by InAnimaTe** [comment]
Ok so I just deployed the following configuration to production which is a 1.13 cluster running `1.2.6` of coredns. All seems to be well.

```
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 1800 {
            success 19968 3600 60
        }
        loop
        reload
        loadbalance
    }
```

Question: Since I've set a min TTL for successes, this seems to also apply for k8s calls i.e. `blah.default.svc.cluster.local`. So, what would setting `ttl` under the `kubernetes` config block do in this case? Which takes precedence?

**Comment by InAnimaTe** [comment]
Also, I'm going to close this as I minttl does seem to be working for cname's as well so not really an issue here.

Apologies for not trying this against latest codebase (or at least stable release) before opening an issue. Really appreciate the help.
