### ISSUE TITLE
Add Debian package to release

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2725]
Personally like Debian, so I would like to add Debian packages to each release. Remains to be seen how easy this is and it does make sense to not depend on a Debian system to create one (although this isn't an issue right now)

rpm might work as well, but I don't care for it.

**Comment by yongtang** [comment]
Big +1 👍 for having Debian package. As far as I know `.deb` is just an archiver file (`ar`) so a Debian system is not truly needed to build `.deb`.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add Debian pa..." ]
>Big +1 👍 for having Debian package. As far as I know `.deb` is just an archiver file (`ar`) so a Debian system is not truly needed to build `.deb`.

there is fpm, but ironically that's not packaged in debian. I've got a simple 
(debian based) tooling that does this: https://github.com/coredns/deployment/tree/master/debian

**Comment by bfallik** [comment]
FWIW I've been using https://github.com/coredns/deployment to build armhf packages for my rpi. It's worked well for me so far.

**Comment by miekg** [comment]
That works and even has sane systemd file handling (something a nfpm deb would miss). Maybe this can be kicked off automatically from a release. I.e. the whole point is to reduce human toil in this endeavour.

**Comment by bfallik** [comment]
Yup, the systemd handling worked well for me.

+1 for triggering these builds automatically.

What currently cross-compiles the binaries that end up attached to the github release? Could that be coerced into building deb (and rpm?) packages as well? I don't know if Debian has anything similar but [copr](https://copr.fedorainfracloud.org/) works great in Fedora. I think we could simply point copr at a coredns srpm and it would produce rpm packages (and associated yum repos) automatically.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add Debian pa..." ]
>Yup, the systemd handling worked well for me.
>
>+1 for triggering these builds automatically.
>
>What currently cross-compiles the binaries that end up attached to the github release? Could that be coerced into building deb (and rpm?) packages as well? I don't know if Debian has anything similar but [copr](https://copr.fedorainfracloud.org/) works great in Fedora. I think we could simply point copr at a coredns srpm and it would produce rpm packages (and associated yum repos) automatically.

ah, that's nice. Don't think Debian has that.

We probably have enough infrastructure in place to already do parts of this, 
i.e. up on release:

* download the deployment repo
* build whatever needs building
* put them some where

**Comment by miekg** [comment]
I'll keep it out here and do something in coredns/deployment. The big thing I want is to run directly from git (as a debian package) and make that easy.

fpm like things work but don't give you a full/correct deb package, esp control file for systemd don't seem to fully work (yes you can put the right file in the right place - but that's not the same thing AFAICT)

**Comment by miekg** [comment]
This repo is all that's needed: https://github.com/coredns/debian This builds from git; we can potentially pull it down on release and build a deb. Other distros can be added as well, ie. coredns/redhat, or coredns/rpm or whatever. I have no interest in those though.

**Comment by bfallik** [comment]
@miekg is your plan to retire the packaging in https://github.com/coredns/deployment/tree/master/debian ?

Right now I have automation that builds debs from the https://github.com/coredns/deployment repo. It's simple and works but I wonder if I should port my automation to clone the source from https://github.com/coredns/coredns and then overlay https://github.com/coredns/debian before building the debs?

What is the version relationship between the two repos? If I want to build a specific tag of coredns what version of debian do I get?

I could retire my automation if there were prebuilt armhf debs available but I'm not sure if that's on your radar.

Thanks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add Debian pa..." ]
>@miekg is your plan to retire the packaging in https://github.com/coredns/deployment/tree/master/debian ?
>
>Right now I have automation that builds debs from the https://github.com/coredns/deployment repo. It's simple and works but I wonder if I should port my automation to clone the source from https://github.com/coredns/coredns and then overlay https://github.com/coredns/debian before building the debs?
>
>What is the version relationship between the two repos? If I want to build a specific tag of coredns what version of debian do I get?
>
>I could retire my automation if there were prebuilt armhf debs available but I'm not sure if that's on your radar.

I have nothing planned here; I just wanted something quick 'n dirty; the debian 
one in deployment downloads a *released* version, I needed something for git.

Unifying them in coredns/debian makes sense I guess?

**Comment by bfallik** [comment]
@miekg OK. I'll just continue to use deployment/debian to package the released version since that suits my needs. If you do end up unifying them I can adjust my scripts accordingly.

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add Debian pa..." ]
>@miekg OK. I'll just continue to use deployment/debian to package the released version since that suits my needs. If you do end up unifying them I can adjust my scripts accordingly.

feel free to propose something; help is appreciated

**Comment by bfallik** [comment]
Sorry @miekg , I'm not sure what you want me to propose. I'm happy to try and help as well but I'm not sure what help you're looking for.

I have (somewhat ancient) experience building debs and rpms. My current need is for released coredns packages for my homelab rpi, so I built some very basic automation to create a suitable build environment and then cross compile coredns into a Debian package for installation. deployment/debian suits my current needs.

**Comment by miekg** [comment]
Ack. That's fine. I think what I need is a simple Debian dir that you clone
into coredns and it will either build a released version or from a git-hash.

Of course releases are just tags, so this might be really simple to pull
off.
