### ISSUE TITLE
Request for mips build

### ISSUE THREAD

**Issue by spigell** [coredns/coredns#2745]
Greetings. Thank you for great dns server. Could you please add to releases build for mips64 arch. I have build coredns for my usg router with `GOARCH=mips` environment variables and it seems to be working. 

```
root@ubnt:~# /home/admin/coredns -version
CoreDNS-1.4.0
linux/mips, go1.12, c144da25-dirty

```
Thank you.

**Comment by miekg** [comment]
Sgtm. Can you send a pr to add this arch?

**Comment by spigell** [comment]
https://github.com/coredns/coredns/pull/2746
