### ISSUE TITLE
out of tree middleware

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#275]
Some of Caddy's middleware is not included in the main repo, I'm not sure what the rules are here, but we need some set of guidelines that will tell an author if a middleware will be included in the source repo or stay outside of it.

**Comment by artbin** [comment]
Maybe we need api for dynamic load middleware?

**Comment by miekg** [comment]
There isn't an obvious way to do this as Go does not support dynamic loading. Caddy compiles the whole thing with your plugin included. It used to use `caddyext` that automated this (to some extend), but this has changed with caddy 0.9. Not sure what the currrent way it, but you can choose the plugin on caddy's download page, it will then compile your binary and over it for download. We could do something similar, and/or ask Caddy to host CoreDNS as well.

**Comment by miekg** [comment]
This has been fixed in 439d8b8
