### ISSUE TITLE
Rewrite plugin should update the authority and additional sections of the response

### ISSUE THREAD

**Issue by akissa** [coredns/coredns#2770]
When the rewrite plugin is used to alter the question it should alter the authority and additional sections of the response as well.

At the moment using the answer rule does update the answer to match the rewritten question but that leaves the authority and additional sections out of sync.

For example rewriting example.com to example.net will have a response with example.com's name server resource records in the additional section

Client DNS servers such as bind then reject the response as bogus (lame servers).

**Comment by chrisohaver** [comment]
I wonder if this confuses some sensitive non-server dns clients (for negative responses).
There are some clients that still get confused even though we sync the answer/question.  Perhaps they are not liking the non-matching neg-cache SOAs in the negative responses when running through local search domains.

```
; <<>> DiG 9.10.6 <<>> @localhost -p5399 blah.example.com.
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 41559
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;blah.example.com.		IN	A

;; AUTHORITY SECTION:
infoblox.com.		1220	IN	SOA	thens.infoblox.com. dns.infoblox.com. 2006462726 10800 1080 1209600 3600

;; Query time: 15 msec
;; SERVER: 127.0.0.1#5399(127.0.0.1)
;; WHEN: Mon Apr 08 09:38:03 EDT 2019
;; MSG SIZE  rcvd: 127

```

**Comment by chrisohaver** [comment]
@greenpau

**Comment by greenpau** [comment]
> Perhaps they are not liking the non-matching neg-cache SOAs in the negative responses when running through local search domains.

@akissa , please let me know the following:
* rewrite rule
* dig output with the enabled rule

**Comment by akissa** [comment]
I have dug deeper and found that my bind refuses to resolve the domains as it does a lookup without recursion flag set to lookup the name servers when it gets the actual name servers which of course are different from the fronting name servers it does not resolve the query.

You can replicate that behaviour by

`dig +norecurse @localhost -p5399 blah.example.com.`

For normal NS lookup's i use the template plugin to fake those response but it is not possible to do that when the client sends a query for the A record without the recursion flag set, the query is rewritten to the actual name server which returns its own information which is not what the client should be seeing.

**Comment by akissa** [comment]
@greenpau Let me get you the requested info.

**Comment by akissa** [comment]
Config

```
example.ext:5300 {
  template IN NS example.ext {
    answer "example.ext. 43200 IN NS ns1.example.ext."
    additional "ns1.example.ext. 38400 IN A 127.0.0.1"
  }
  rewrite stop {
    name regex (.*)\.example\.ext {1}.baruwa.com
    answer name (.*)\.baruwa\.com {1}.example.ext
  }
  forward . 192.168.1.2
  log
}
```

Query 1

```
dig A www.example.ext @127.0.0.1 -p 5300

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.68.rc1.el6_10.1 <<>> A www.example.ext @127.0.0.1 -p 5300
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28475
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 3, ADDITIONAL: 6

;; QUESTION SECTION:
;www.example.ext.		IN	A

;; ANSWER SECTION:
www.example.ext.	13184	IN	A	84.200.48.198

;; AUTHORITY SECTION:
baruwa.com.		13026	IN	NS	ns3.baruwa.com.
baruwa.com.		13026	IN	NS	ns1.baruwa.com.
baruwa.com.		13026	IN	NS	ns2.baruwa.com.

;; ADDITIONAL SECTION:
ns1.baruwa.com.		64797	IN	A	xx.xxx.xx.xx
ns1.baruwa.com.		64797	IN	AAAA	xxx:xxx:xxx::xx
ns2.baruwa.com.		64797	IN	A	xxx.xxx.xxx.xx
ns2.baruwa.com.		64797	IN	AAAA	xxx:xxx:xxx:xxx::xxx:xxx
ns3.baruwa.com.		64797	IN	A	xxx.xxx.xxx.xxx
ns3.baruwa.com.		64797	IN	AAAA	xxx:xxx:xxx:xxx:xxx:xxx:xxx:xxx

;; Query time: 2 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Mon Apr  8 17:14:22 2019
;; MSG SIZE  rcvd: 394
```

Negative responses always set the SOA as follows.

```
dig A xxxxxx.example.ext @127.0.0.1 -p 5300

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.68.rc1.el6_10.1 <<>> A xxxxxx.example.ext @127.0.0.1 -p 5300
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 62730
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;xxxxxx.example.ext.		IN	A

;; AUTHORITY SECTION:
baruwa.com.		10800	IN	SOA	ns1.baruwa.com. andy.topdog.za.net. 2016053355 10800 3600 604800 38400

;; Query time: 176 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Mon Apr  8 17:20:55 2019
;; MSG SIZE  rcvd: 116
```


As you can see, there should be a way to rewrite the authority and additional sections to the "correct" values.

**Comment by akissa** [comment]
@greenpau Supplied as requested.

**Comment by greenpau** [comment]
> As you can see, there should be a way to rewrite the authority and additional sections to the "correct" values.

@akissa , I got it now. Do you think that the client has the issue with `AUTHORITY` or `ADDITIONAL` section? (🤔 💭 .. perhaps it is only the `ADDITIONAL`)?

**Comment by greenpau** [comment]
@chrisohaver , what do you think about having the following? do it automatically for `additonal`?

```
  rewrite stop {
    name regex (.*)\.example\.ext {1}.baruwa.com
    answer name (.*)\.baruwa\.com {1}.example.ext
    answer authority (.*)\.baruwa\.com {1}.example.ext
    answer additional (.*)\.baruwa\.com {1}.example.ext
  }
```

**Comment by chrisohaver** [comment]
> Do you think that the client has the issue with AUTHORITY or ADDITIONAL section?

The client in this case is a bind dns server, so it may be looking at the response with more scrutiny than a simple dns client (e.g. validating the AUTH section).

Adding these as options is good.  I don't know what defaults make most sense. It seems to make sense that the AUTH section should match too, even though apparently most clients ignore it.
Maybe also an `all` option ...
```
  rewrite stop {
    name regex (.*)\.example\.ext {1}.baruwa.com
    answer all (.*)\.baruwa\.com {1}.example.ext
  }
```

**Comment by akissa** [comment]
I am not sure i would think it is with the NS records in the authority section.

Maybe the approach should be to allow for broader rewriting on the authority and additional sections using standalone rules that are not embedded in the `question-answer` block.

Something similar to what happens to the rewriting of TTL's that would provide better leeway, so maybe have rules for authority and additional ? Users can then supply multiple rules to rewrite anything in those sections as some name servers are not in the base domain that is rewritten in the `question-answer` block.

**Comment by greenpau** [comment]
> Maybe also an all option ...

@chrisohaver , 👍

**Comment by greenpau** [comment]
> Something similar to what happens to the rewriting of TTL's that would provide better leeway, so maybe have rules for authority and additional ?

@akissa , side question, do you use TTL rewrites? just curious if that use case is important to you.

**Comment by akissa** [comment]
@greenpau No i do not use TTL rewrites but was looking through the source code and thinking about how the enhancement could be implemented. I initially thought of adding the `authority` and `additional` rules in the `question-answer` block but looking at the source code that will not be flexible as it does not allow for multiple rules in the block coz the code at the moment and checks for specific number of rules in the block. Refactoring the whole logic in the `question-answer` block may not be viable ?

**Comment by chrisohaver** [comment]
> Refactoring the whole logic in the question-answer block may not be viable ?

IMO refactoring the syntax of rewrites would be welcomed by new users. But it could introduce backward incompatibilities which could be annoying for users that have already managed to get things to work in the current syntax.

**Comment by greenpau** [comment]
> But it could introduce backward incompatibilities which could be annoying for users that have already managed to get things to work in the current syntax.

@chrisohaver , 👍

**Comment by chrisohaver** [comment]
Related question came up on slack... 

If rewriting the additional section, you'll also want to rewrite SRV targets.  Otherwise the targets wont match the additional section records.

**Comment by chrisohaver** [comment]
IOW - when rewriting the answer, we should also rewrite SRV targets.

And in the same vein, we should rewrite CNAME canonical names, if we don't already.

**Comment by akissa** [comment]
@chrisohaver I am trying out an implementation and i ran into this issue as well. One idea i had for the NS records would be to some how map the replacements being made to the authority section to updated or new entries in the additional but i have not figured out how to do that yet. Changes in the authority can leave orphaned records in additional if not taken into consideration.

**Comment by akissa** [comment]
I have written a out of tree plugin that addresses most of the requirements i have and the issues raised there. It is still a work in progress as there are no automated tests but actual testing works for me.
https://github.com/akissa/rewriteng

**Comment by greenpau** [comment]
@chrisohaver , do you want to keep this open?

**Comment by chrisohaver** [comment]
@greenpau, I have no preference.
