### ISSUE TITLE
Intermittent long resolution delays for cluster.local

### ISSUE THREAD

**Issue by ajpauwels** [coredns/coredns#2777]
I'm running into odd delayed resolution issues when resolving cluster.local addresses.

Context is that I want to be able to access a pod externally at, say, pod1.domain1.com, and then be capable of referencing that pod using the same FQDN internally without having it actually exit the cluster (so pod1.domain1.com would be resolved by coredns and then routed directly to the appropriate service).

To do that, I added some rewrite entries in the Corefile to catch domain1.com and domain2.com requests and route them to the internal service name. These changes are outlined below (10.0.0.10 is the internal coredns IP):
```
  domain1.server: |
    domain1.com:53 {
        errors
        cache 30
        rewrite stop {
            name regex (.+)\.(.+)\.(.+)\.com {2}-{3}-{1}.{2}-{3}.svc.cluster.local
            answer name (.+)-(.+)-(.+)\.(.+)-(.+)\.svc.cluster.local {3}.{1}.{2}.com
        }
        proxy . 10.0.0.10
    }
  domain2.server: |
    domain2.com:53 {
        errors
        cache 30
        rewrite stop {
            name regex (.+)\.(.+)\.(.+)\.com {2}-{3}-{1}.{2}-{3}.svc.cluster.local
            answer name (.+)-(.+)-(.+)\.(.+)-(.+)\.svc.cluster.local {3}.{1}.{2}.com
        }
        proxy . 10.0.0.10
    }
```

This is actually working great...most of the time. Sometimes, that resolution will take 10+ seconds and even time out. But if I then re-run `nslookup`, it works perfect, and very fast.

I've identified that the issue only comes up if I make a bad (non-recognized) lookup beforehand. Console logs below:
```
root@xxx:/# nslookup pod1.domain1.com 
Server:		10.0.0.10
Address:	10.0.0.10#53

** server can't find pod1.domain1.com: SERVFAIL

root@xxx:/# nslookup operations.pod1.domain1.com
;; connection timed out; no servers could be reached

root@xxx:/# nslookup operations.pod1.domain1.com
Server:		10.0.0.10
Address:	10.0.0.10#53

Name:	operations.pod1.domain1.com
Address: 10.0.183.77

root@xxx:/# nslookup operations.pod1.domain1.com
Server:		10.0.0.10
Address:	10.0.0.10#53

Non-authoritative answer:
Name:	operations.pod1.domain1.com
Address: 10.0.183.77
```

The first one fails as expected. The second one fails, but it shouldn't. On the third try, it doesn't fail, but it took about 6 seconds to resolve. And then on the fourth one, it resolved immediately.

I assume the immediate resolution is due to caching, but I don't think that initial resolution should be taking 6 seconds, and it certainly shouldn't be failing the first time around. Any ideas?

**Comment by chrisohaver** [comment]
One thing to try, before diving in deeper ...

In general with rewrites, you should anchor the ends of your regexes with `\.$` unless you really want to match the middle of a query name. Not doing so can cause issues that manifest in confusing ways, particularly in conjunction with they way that k8s pod search domains work.

**Comment by chrisohaver** [comment]
Can you give us the whole Corefile?

**Comment by chrisohaver** [comment]
```
root@xxx:/# nslookup pod1.domain1.com 
Server:		10.0.0.10
Address:	10.0.0.10#53

** server can't find pod1.domain1.com: SERVFAIL
```

Don't know the whole corefile, but, is this causing an infinite self forwarding loop? `pod1.domain1.com ` doesn't match the re-write rule, so the server forwards the request unchanged to `10.0.0.10`, which is itself?

Is CoreDNS crashing and restarting?

**Comment by ajpauwels** [comment]
@chrisohaver You are spot on! Just re-ran the invalid `nslookup` and watched both coredns pods crash and then come back, which would explain the delay (waiting for pods to start).

Will re-write regexes to include the line terminator, meanwhile, here is the Corefile, I assume there's something I need to change here to avoid that infinite loop:
```
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import custom/*.override
    }
    import custom/*.server
```

**Comment by chrisohaver** [comment]
I think you can do this in one server block.  This removes the precarious self forwarding mechanism, and also results in one less hop per query.

```
    .:53 {
        errors
        health
        rewrite continue {
            name regex (.+)\.(.+)\.domain1\.com\.$ {2}-domain1-{1}.{2}-domain1.svc.cluster.local
            answer name (.+)-(.+)-(.+)\.(.+)-(.+)\.svc.cluster.local {3}.{1}.{2}.com
        }
        rewrite stop {
            name regex (.+)\.(.+)\.domain2\.com\.$ {2}-domain2-{1}.{2}-domain2.svc.cluster.local
            answer name (.+)-(.+)-(.+)\.(.+)-(.+)\.svc.cluster.local {3}.{1}.{2}.com
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import custom/*.override
    }
```

**Comment by ajpauwels** [comment]
Unfortunately I don't think AKS wants me touching the main `coredns` file, if I place a `.:53` block inside the `coredns-custom` configmap, will that overwrite the default settings?

**Comment by ajpauwels** [comment]
Unfortunately I don't think AKS wants me touching the main `coredns` configmap with the Corefile. I'm not sure how they enforce it, I assume they probably don't but reserve the right to make any changes to the configmap containing the Corefile at any time, making me lose my changes.

If I place a `.override` block inside the `coredns-custom` configmap, will that be functionally equivalent? Or will it just cause the same problem seeing as the block would still be after all the other config?

EDIT: They do enforce it :( You can edit but it gets reverted back within seconds.

**Comment by chrisohaver** [comment]
> If I place a .override block inside the coredns-custom configmap, will that be functionally equivalent?

Yes. Order of different plugins does not matter.  i.e. It doesn't matter that the rewrite rules are on the bottom, they still get executed first.  Order of plugin execution is dictated by [plugin.cfg](https://github.com/coredns/coredns/blob/master/plugin.cfg).

**Comment by ajpauwels** [comment]
Perfect, just did it and everything works great, requests to `pod1.domain.com` now immediately returns saying it couldn't resolve host and the pods don't crash. Thanks very much Chris!
