### ISSUE TITLE
Reverse zones should be calculated for the full CIDR range

### ISSUE THREAD

**Issue by mdgreenfield** [coredns/coredns#2779]
When specifying a reverse DNS zone using CIDR notation the full range of zones are not calculated.

For example, a CIDR of `10.129.60.0/22` currently only results in a single `60.129.10.in-addr.arpa.`, however, the full CIDR range should include zones for:

- `60.129.10.in-addr.arpa.`
- `61.129.10.in-addr.arpa.`
- `62.129.10.in-addr.arpa.`
- `63.129.10.in-addr.arpa.`

**Comment by mdgreenfield** [comment]
I will see about putting together a PR to address this issue.

**Comment by rdrozhdzh** [comment]
see related issue #2252

**Comment by chrisohaver** [comment]
@miekg, in the README we say that CIDR zones work on non x8 boundaries (e.g. 25)

> This even works for CIDR (See RFC 1518 and 1519) addressing, i.e. 10.0.0.0/25, CoreDNS will then check if the in-addr request falls in the correct range.

Is this true?  I can't find where this check is done.

**Comment by chrisohaver** [comment]
> For example, a CIDR of 10.129.60.0/22 currently only results in a single 60.129.10.in-addr.arpa., 

I think it would actually create `129.10.in-addr.arpa`, falling to /16, next lowest multiple of 8.

**Comment by mdgreenfield** [comment]
In the beginning of the logs I'm seeing `60.129.10.in-addr.arpa.:53` for `10.129.60.0/22`

**Comment by chrisohaver** [comment]
So, it casts a smaller net?  Thats broken...

**Comment by mdgreenfield** [comment]
It looks like https://github.com/ynikanchyk/coredns/pull/2 addresses this issue.

I updated `core/dnsserver/address_test.go` with the example I provided (`10.129.60.0/22`) and found the actual result (`dns://60.129.10.in-addr.arpa.:53`) using `master`. 

I ran the same test with https://github.com/ynikanchyk/coredns/pull/2 and found that generated the following, which looks correct to me:

- `dns://60.129.10.in-addr.arpa.:53`
- `dns://61.129.10.in-addr.arpa.:53`
- `dns://62.129.10.in-addr.arpa.:53`
- `dns://63.129.10.in-addr.arpa.:53`

**Comment by ynikanchyk** [comment]
One of the problem with my https://github.com/ynikanchyk/coredns/pull/2 is that it affects a number of plugins. Someone should introduce valid test cases for every plugin affected to enforce his decisions regarding if specific plugin should accept reverse zone entries in its configuration and how such entries are treated when normalized to a number of ".in-addr.arpa" entries from the point of view of functionality of this plugin.

**Comment by miekg** [comment]
Reverse entries are nothing special, any plugin should deal with them.

**Comment by mdgreenfield** [comment]
I've cherry-picked the commits from the PR and am making sure tests pass with appropriate test coverage.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Reverse zones sho..." ]
>When specifying a reverse DNS zone using CIDR notation the full range of zones are not calculated.
>
>For example, a CIDR of `10.129.60.0/22` currently only results in a single `60.129.10.in-addr.arpa.`, however, the full CIDR range should include zones for:
>
>- `60.129.10.in-addr.arpa.`
>- `61.129.10.in-addr.arpa.`
>- `62.129.10.in-addr.arpa.`
>- `63.129.10.in-addr.arpa.`

I'm wonder why filter func doesn't already do the right thing, if not that would 
require a few tweaks

**Comment by chrisohaver** [comment]
> I'm wonder why filter func doesn't already do the right thing, if not that would
require a few tweaks

I think it does the right thing.  The issue may be with plugins that check their own zones and pass to next plugin when the zone doesn't match.  When a CIDR is not a /0 /8 /16 /24 /32, the zone created is _narrower_ than the CIDR (i.e. mask is rounded up).  If the mask is instead "rounded down" for the zone, then the filter func would work OK. The filter func would remain unchanged - it would still check for the actual original CIDR.  Only the zone representation would be rounded down.  For example:

Currently, a CIDR of `60.129.60.0/22`  results in `60.129.10.in-addr.arpa.` (which in itself is a /24)
Even with the filter func in place, a plugin that checks its zones would pass to the next plugin for a query of `1.61.129.10.in-addr.arpa.`.  This is because `1.61.129.10.in-addr.arpa.` is not in `60.129.10.in-addr.arpa.`.

If instead we translate `60.129.60.0/22`  to `129.10.in-addr.arpa.` (a /16), then a plugin that checks its zones would allow it through.

Alternately, we could say that all plugins should also check the filter func, but I think that rounding the mask down to nearest 8 when computing the reverse zone is cleaner.

**Comment by mdgreenfield** [comment]
The problem looks to starts further up in the `core/dnsserver/server.go` `ServeDNS` function.

When the query comes in, `ServeDNS` tries to identify the server block/plugin chain to use so it iterates over each segment of the request. https://github.com/coredns/coredns/blob/5aafa987b2d7127a2eef9d67788d9b338cff54d2/core/dnsserver/server.go#L230-L239

The problem is that there is only ever one zone created for reverse zones which does not fully encompass all the zones on a non-octal boundary.

With a server block CIDR notation of `192.168.1.0/22`, a request like `56.2.168.192.in-addr.arpa.` is attempting be matched against a zone of `1.168.192.in-addr.arpa.`

In this example, each of the following are tried:
- `56.2.168.192.in-addr.arpa.`
- `2.168.192.in-addr.arpa.`
- `168.192.in-addr.arpa.`
- `192.in-addr.arpa.`

But unfortunately, the zone will never match.

**Comment by chrisohaver** [comment]
> The problem looks to starts further up

Ah, thanks I missed that. Well, I think rounding the zone down (in SplitHostPort()) would still fix the issue, for the same reason.

**Comment by chrisohaver** [comment]
Using your example ...

A server block CIDR notation of `192.168.1.0/22` should instead create a zone of `168.192.in-addr.arpa.` as if the CIDR was a /16 (16 = 22 rounded down to closest multiple of 8).

In this way, a query for `56.2.168.192.in-addr.arpa.` will match the zone, and also the filter func.
A query for `56.254.168.192.in-addr.arpa.` will match the zone, but not pass the filter func.

**Comment by mdgreenfield** [comment]
I think that should work. 

One downside I think is that if two separate server blocks such as a `192.168.1.0/22` and a `192.168.4.0/22` are declared, each configured with the `metrics` plugin, both would report metrics with the same zone because both would round up to the `/16` which is slightly misleading. But maybe not a concern?

The advantage to doing this, however, is that not every plugin needs to be modified and the changeset should be relatively small.

**Comment by chrisohaver** [comment]
Yes, for reverse zones, perhaps metrics should report in the original CIDR if it exists, not the wider zone.  But that may be complicated, I don't know if metrics has access to the actual cidr.

I suspect that making the zone wider, and then further narrowing it with filter func was the original intent.  I recall in discussions that this is how it was going to work.  This is why [earlier](https://github.com/coredns/coredns/issues/2779#issuecomment-482138696) I expected `/22` to result in a 2 octet zone, not the 3 octet zone that you had observed.

**Comment by mdgreenfield** [comment]
AFAICT, metrics does not have access to the original CIDR, only `serverBlockKeys` (e.g. `dns://1.168.192.in-addr.arpa.:0`).

**Comment by miekg** [comment]
> With a server block CIDR notation of 192.168.1.0/22, a request like 56.2.168.192.in-addr.arpa. is attempting be matched against a zone of 1.168.192.in-addr.arpa.
> 
> In this example, each of the following are tried:
>
>  56.2.168.192.in-addr.arpa.
>    2.168.192.in-addr.arpa.
>   168.192.in-addr.arpa.
>    192.in-addr.arpa.
>
> But unfortunately, the zone will never match.

Thanks that makes sense. I think a smaller PR is required to fix this here and make plugins just not care, they get a name and normally they should just handle it. I.e. some of them might want to call Match, but this is hardly a requirement. 

Can we extend this first, i.e that the matching in server works?

**Comment by miekg** [comment]
I'll try to come up with an alternative approach here or rip the entire thing out.
