### ISSUE TITLE
plugin/rewrite: honor original prefix-length in ECS option

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#2780]
From https://tools.ietf.org/html/rfc7871#section-7.1.3
```
   Forwarding Resolvers essentially appear to be Stub Resolvers to
   whatever Recursive Resolver is ultimately handling the query, but
   they look like a Recursive Resolver to their client.  A Forwarding
   Resolver using this option MUST prepare it as described in
   Section 7.1.1, "Recursive Resolvers".  In particular, a Forwarding
   Resolver that implements this protocol MUST honor SOURCE PREFIX-
   LENGTH restrictions indicated in the incoming query from its client.
```

In current implementation, if ECS option presents in original query the rewrite plugin replaces it with its own pre-configured source prefix-length. 

If original prefix-length is less than configured one it should not be overwritten.

**Comment by greenpau** [comment]
@rdrozhdzh , do you want to keep this open?

What would be the example of a rewrite rule that would ***"replace it with its own pre-configured source prefix-length."***?

**Comment by rdrozhdzh** [comment]
corefile
```
.:1053 {
    forward . 8.8.8.8
    rewrite edns0 subnet set 24 56
}
```
Test case: send DNS query with subnet option which specifies first 8 bits of client IP. RFC 7871 requires that coredns MUST NOT pass bigger part of my IP then specified in subnet option. In fact, coredns (rewrite plugin) passes 24 bits of my address:
```
$ dig @10.0.2.15 -p 1053 youtube.com +subnet=10/8

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> @10.0.2.15 -p 1053 youtube.com +subnet=10/8
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11586
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; CLIENT-SUBNET: 10.0.2.0/24/16
;; QUESTION SECTION:
;youtube.com.			IN	A

;; ANSWER SECTION:
youtube.com.		286	IN	A	172.217.212.190
youtube.com.		286	IN	A	172.217.212.93
youtube.com.		286	IN	A	172.217.212.136
youtube.com.		286	IN	A	172.217.212.91

;; Query time: 211 msec
;; SERVER: 10.0.2.15#1053(10.0.2.15)
;; WHEN: Mon Dec 09 16:11:03 +03 2019
;; MSG SIZE  rcvd: 159
```

If I specify subnet as 0/0 which means I don't want any forwarder to pass any part of my address I get the same result

The same issue is applicable to conf option **replace**. In some cases this issue can be workarounded (if suitable) by configuring rewrite as
```
    rewrite edns0 subnet append 24 56
```

**Comment by greenpau** [comment]
@rdrozhdzh , thank you for the explanation. I will work on it.

**Comment by rdrozhdzh** [comment]
@greenpau, some time ago I submitted a PR #3015 which fixes this issue (and another RFC violation issue). Perhaps it would be easier to review it and modify if needed

**Comment by greenpau** [comment]
> @greenpau, some time ago I submitted a PR #3015 which fixes this issue (and another RFC violation issue). Perhaps it would be easier to review it and modify if needed

@rdrozhdzh , let's have a PR per issue. I am OK with you creating a separate PR addressing only this particular issue.

**Comment by miekg** [comment]
this looks very much stale. Closing
