### ISSUE TITLE
external domain dns resolution occasionally failed

### ISSUE THREAD

**Issue by willmao** [coredns/coredns#2784]
os version: Linux 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
docker version: 17.03.3
kubernetes version: 1.12.7
coredns version: 1.2.2
corefile:
```
----
.:53 {
    log vod.api.qcloud.com {
      class all
    }
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      upstream
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . "/etc/resolv.conf"
    cache 30
    loop
    reload
    loadbalance
}
```

coredns resolution log:
```
172.20.0.91:49764 - [13/Apr/2019:03:01:45 +0000] 57264 "AAAA IN vod.api.qcloud.com. udp 36 false 512" SERVFAIL qr,rd,ra 36 0.000409173s
172.20.0.91:49764 - [13/Apr/2019:03:01:45 +0000] 15300 "A IN vod.api.qcloud.com. udp 36 false 512" NOERROR qr,rd,ra 126 0.000671671s
```
recently we began to use coredns when we upgraded our k8s cluster to 1.12.7, we noticed that some external domain resolution fails occasionally.

I don't know how to debug this issue, is there anyone can help ?

Thank you!

**Comment by chrisohaver** [comment]
Try using the `forward` plugin instead of `proxy`.  The issue could be due to an unhealthy upstream dns server, which `forward` handles better.  

`proxy . "/etc/resolv.conf"` -> `forward . /etc/resolv.conf`

**Comment by willmao** [comment]
it seems that this issue is caused by the glibc 2.19, after upgrade our docker image with glibc 2.14, it works fine!

use `ldd --version` to check the glibc version.

hope this can help others who meet with similar issue.
