### ISSUE TITLE
new plugin: any

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2785]
propose to add *any* plugin to the default plugin. I personally have a `rewrite` to write ANY to HINFO, the *any* plugin is cleaner and gives a rational.

See: https://github.com/coredns/any

**Comment by stp-ip** [comment]
I agree this is a big enough issue that the any plugin seems good.

Would this be something doable as a default vor 1.6.0? It feels like ANY queries are mostly used for abuse so manually enabling that plugin seems less optimal.

But definitely voting for adding it as a built-in plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] new plugin: a..." ]
>I agree this is a big enough issue that the any plugin seems good.
>
>Would this be something doable as a default vor 1.6.0? It feels like ANY queries are mostly used for abuse so manually enabling that plugin seems less optimal.

This can go in at any points, even for a 1.5.1 release

**Comment by stp-ip** [comment]
Yeah the plugin itself yes.
Was just thinking, if it might make sense to have any enabled for all corefiles and how that might work.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] new plugin: a..." ]
>Yeah the plugin itself yes.
>Was just thinking, if it might make sense to have any enabled for all corefiles and how that might work.

ah, so. That might make sense, but currently we're not defaulting to a set of 
plugins that are always there. You also create the problem of folks that now 
want to disable such a plugin.

Think the current approach of just being explicit should be followed here.

**Comment by stp-ip** [comment]
Fair point.
