### ISSUE TITLE
plugin to  load balance

### ISSUE THREAD

**Issue by Lionelpang** [coredns/coredns#2786]
Can coredns be used as intelligent routing? For example, a.com has two back-end services, 192.168.3.3 and 192.168.3.2, respectively. When one of these services fails, the rotation training mechanism is used to return the two services.

**Comment by Lionelpang** [comment]
Each request resolution returns a different value

**Comment by miekg** [comment]
No it can't, yet. I've got some designs I may be able to publish on how
this can work.
