### ISSUE TITLE
pkg/upstream uses *current* server

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2787]
If you use `upstream` you probably expect your query to be handled by coredns' process, in the current incarnation of `upstream` is will use the current `*server` handling your request. This means a corefile
~~~
. {
  forward . /etc/resolv.conf
}
cluster.local {
  kubernetes
  upstream
}
~~~
will *not* lead to queries being resolved inside the `cluster.local` server block, because those (probably external) queries will not match cluster.local, nor is there a forward stanza. Only in badly written Corefiles this happens to work:

~~~
. {
  forward . /etc/resolv.conf
  kubernetes cluser.local {
     upstream
  }
}
~~~
because the current server happens to match on `.`. A problem here is that coredns can listen to different addresses depending on it's config. Although it may be possible to just call all know server in sequence? There may be other bits of info we can use that can make this work transparently.

This will mean that if `upstream` is present the query will be resolved by coredns (again), maybe using a forward (and/or proxy) precent in another server block

**Comment by chrisohaver** [comment]
> Only in badly written Corefiles

Can you explain why that example is "badly written"?

**Comment by miekg** [comment]
example is in the issue

**Comment by chrisohaver** [comment]
Yes, I see the example. And you refer to it as "badly written." 
 Can you _explain why_ that example is "badly written"?

**Comment by chrisohaver** [comment]
In the first example, do you mean ...
```
. {
  forward . /etc/resolv.conf
}
cluster.local {
  kubernetes {
    upstream
  }
}
```

**Comment by miekg** [comment]
you should only handle zone your authoritative for, not some wildcard and then fall through or what ever. See https://github.com/coredns/deployment/issues/131 which you closed without even bothering.

coming back to this issue. The original `upstream` *argument* may be needed here, because you need to point to a server or at least there must be some indication where to send the query, off course this information is present in the binary; just not at the moment a plugin executes upstream. hmmm

**Comment by miekg** [comment]
A potential idea could be to do the following
~~~ corefile
. {
    whoami
}
cluster.local {
   kubernetes
   upstream .
}
~~~
Where `upstream .` says resolve any upstream queries using the server for `.`, we don't require a transport because we just call the `ServeDNS` function. Optionally this can have a port number to disambiguate different servers running the same zone, but on different ports. This falls down if we using *bind*, which would then require syntax ala `zone @ ip: port` which is starting to get ridiculous.

Just having a zone also mimics *forward* that has that an a server.

Another option is to make forward only carry *one* other server and that server must be the one for `.` but it can be over-ridden. 

To make each query not carry a full context we can inspect the `upstreams` being used and only add the server where an upstream is specified. This can be done before hand and just saved, even in a map, because we know we only write to it before the server starts.

**Comment by miekg** [comment]
<strike>pfff. Implementation wise this tricky. Bottom line; this needs to be fixed, `upstream` in it's current form is broken (works in a minimal subset of Corefiles). </strike>

Think the cleanest way is to have plugins implement an `Upstreamer` interface which makes the server put in the correct `*Server*` during config compile, meaning that upstream doesn't have to look at the context anymore, it can just call the configured server.

**Comment by johnbelamaric** [comment]
In your initial example, it seems to me that it is working as intended. I
wouldn't expect ordinary queries to be resolved by the `upstream`. The
`upstream` for resolving the CNAME targets, and that should work fine. I
think re-entering the routing of the current server makes sense. If you
want to direct it to a different server (i.e., port) in this process,
you'll have to use forward.

**Comment by johnbelamaric** [comment]
I think you're trying to use upstream for the wrong thing. It's not
supposed to be equivalent to forward.

**Comment by miekg** [comment]
if the cname target is outside your configured zone, it should be rejected by the config; as that server is not authoritative for it, i.e. a cname target for www.example.org can never be resolved by a forwarder in a config ala:
~~~
cluster.local {
     kubernetes
     forward . 8.8.8.8
}
~~~
as *forward* will never see the `www.example.org` name: it will be a REFUSED.

**Comment by johnbelamaric** [comment]
Yes, that is a broken Corefile that won't work. You would need

```
cluster.local {
  kubernetes
}

. {
  forward . 8.8.8.8
}
```
Which seems reasonable to me.

**Comment by miekg** [comment]
Except for kubernetes (coredns/deployment repo) we make the thing (wrongly) authoritative for `.`; so it *happens* to work; but that's just coincidental. I.e. if you make a proper server block that is authoritative for `cluster.local` as we do in the last 2 comments,  upstream doesn't work.

update: (or at least it only works for names under cluster.local)

**Comment by miekg** [comment]
A way to fix this is with a `Upstreamer` interface that will make the server, after config parsing, put the correct `*Server` in the upstream's config. This means in turn that `upstream.Lookup` doesn't need to consult a context it can just request. 

This can default to the current server (this is what happens now), or an error if no server is mentioned. I like the latter, but for backwards compat reasons the first seems more prudent. We could also default to a `.` server as a default; *if that is available* and error out if not. 

That last option is also backwards compatible with the only way which *upstream* could have worked and is more explicit.

**Comment by johnbelamaric** [comment]
I think the one I posted should work, but I can't try it right now. IIRC, all the server blocks for the same address/port get merged into one server, the upstream should pass back through the routing, so it should work.

**Comment by miekg** [comment]
Ok, tried it and it works :/ Sorry for the noise; this **is** good, because we can just change things around and make `Server`s not handle queries they are not authoritative for. @johnbelamaric one of your previous comments nailed it.

**Comment by miekg** [comment]
For full reproduction, use the file plugin, with a zone:
~~~
% more db.miek.nl          
$ORIGIN miek.nl.
@       IN      SOA     linode.atoom.net. miek.miek.nl. ( 1282630060 4H 1H 7D 4H )

a	IN 	A       127.0.0.1
wat     IN      CNAME   www.example.org.
~~~
and a corefile:
~~~
miek.nl {
    file db.miek.nl {
        upstream
    }
    log
}

. {
    forward . 8.8.8.8
    log
}
~~~
And the query `wat.miek.nl A` you get a response. This still works, because the server are indeed the one and same.

If you make the `.` zone listen on a different address: `.:1054`, i.e.
~~~
.:1054 {
    forward . 8.8.8.8
    log
}
~~~
you *don't* get a resolved cname, Same is true if you *bind* to a different IP address, i.e a `bind` in one of these serverblocks breaks your cname resolving. This is not super obvious; this might require a bunch of docs (somewhere??)

update: note even with expanded upstream syntax; this won't be solved unless you allow for some ugly syntax; and there is some elegance to it; that only your current (shared) server is allows to resolve.

**Comment by miekg** [comment]
I looked a bit where this could be documented, but in the plugin's readmes it doesn't really fit and complicates things and most folks won't run into this because it will happen to just work. Maybe something for the manual which I need to go over again as well.

closing here.
