### ISSUE TITLE
Maintaining sql conn in plugin

### ISSUE THREAD

**Issue by ldelossa** [coredns/coredns#2788]
I want to use CoreDNS to replace a custom built DNS server I'm working on. This DNS server communicates with a Postgres DB. I'm looking at writing a plugin but I do not want to spawn a connection per DNS query. Does the current plugin structure allow keeping a consistent handle to a database object between calls? 

thanks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Maintaining sql c..." ]
>I want to use CoreDNS to replace a custom built DNS server I'm working on. This DNS server communicates with a Postgres DB. I'm looking at writing a plugin but I do not want to spawn a connection per DNS query. Does the current plugin structure allow keeping a consistent handle to a database object between calls?

The plugin structure in CoreDNS doesn't mandate anything of this sort; so yes 
you can just maintain a handle to a database.

Note something like this already exists in the form of this plugin: https://github.com/wenerme/wps
https://coredns.io/explugins/pdsql/

/label: question

**Comment by ldelossa** [comment]
Thank you that is very helpful. I am obviously at the beginning of
evaluating Coredns. Are plugins compiled into the binary or are they loaded
at runtime and the source plugin folder must be available?

**Comment by miekg** [comment]
They are compiled in. Mostly because the go language doesn't allow dynamic
loaded plugins. Compiling them in is quick and easy though

**Comment by ldelossa** [comment]
Thank you! Yes this is actually easier and means you just deploy the
binary. Thanks for answering my questions! I will join the slack channel
now to ask more general questions there.

**Comment by miekg** [comment]
Ok. I'm not on the slack channel, because I'm trying to have a life :-) We
have a coredns-discuss ML though

**Comment by ldelossa** [comment]
LOL. Understandable. Will subscribe there also :). Thank you.
