### ISSUE TITLE
Randomize order of records in the template plugin

### ISSUE THREAD

**Issue by akissa** [coredns/coredns#2796]
It would be good to have an option or default randomization of RR records that are created by the template plugin.

At the moment the records are returned in the same order in which they are configured in
the configuration.

Code for shuffling RR items already [exists](https://github.com/coredns/coredns/blob/master/plugin/loadbalance/loadbalance.go#L28) in the loadbalance plugin and could be reused
for this.

**Comment by miekg** [comment]
It's better to do this in the loadbalance plugin than adding code directly
here in the template plugin.

**Comment by akissa** [comment]
You are right, it did not occur to me that the loadbalance plugin is generic. Closing this.
