### ISSUE TITLE
Loadbalance plugin does not randomize NS answers

### ISSUE THREAD

**Issue by akissa** [coredns/coredns#2797]
The loadbalance plugin does not randomize NS answers. I picked this up while trying to randomize NS records set using the [template plugin](https://github.com/coredns/coredns/issues/2796)

**Comment by miekg** [comment]
Probably makes sense to add an option to loadbalance to specify additional
records to shuffle. Like "type NS ... " or something like that.

**Comment by akissa** [comment]
Actually in this case it is the `answer section` that is not being shuffled, the `additional section` `A` records are being shuffled.

The query is `dig NS example.com` The answer section returns `NS` records, the additional section has `A` records. The `NS` records in the answer are not shuffled, the `A` records in the additional section are shuffled.

**Comment by akissa** [comment]
The code in question is [here](https://github.com/coredns/coredns/blob/master/plugin/loadbalance/loadbalance.go#L33), only a few types are selected for shuffling, NS records are not one of the selected types.

**Comment by chrisohaver** [comment]
>...  in this case it is the _answer section_ that is not being shuffled, the _additional section_ A records _are_ being shuffled.

IMO it doesn't make sense to shuffle the _additional_ section.  It's there for reference from the answer section, so the order should not matter, and randomizing it is a waste of time.

**Comment by chrisohaver** [comment]
> IMO it doesn't make sense to shuffle the additional section. It's there for reference from the answer section, so the order should not matter, and randomizing it is a waste of time.

No, i take it back, there can be multiple records of the same name in the additional section, so randomizing it _can_ matter.

**Comment by akissa** [comment]
@chrisohaver What am trying to address here is the `answer section`. I have 5 NS servers, the top two are being hit hardest because it seems the clients always pick the first one/two answers. As the responses from the template plugin will always return in the same order the top two answers see most of query the traffic.

You are right that randomizing the `additional section` does not have much effect as those are simply helper records to prevent the second query to resolve the name in the answer.

**Comment by chrisohaver** [comment]
> What am trying to address here ...

I understand the issue. I was just making comment in response to your tangental observation on the additional section being randomized.  Initially I was thinking it was unnecessary, but then soon after I realized it is necessary.
