### ISSUE TITLE
coredns pod visits  coredns service timeout

### ISSUE THREAD

**Issue by willzgli** [coredns/coredns#2803]
I ues kubespray v1.13.5 to deploy a k8s service,but error occurs
Bellow is the version of coredns and error log.

Version of CoreDNS :v1.5.0  & v1.4.0

```
Corefile:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
      addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

Logs:

```
[root@k8s-node-1 ~]# kubectl logs -f -n kube-system coredns-9d85fb698-tnrgn
.:53
2019-04-29T12:26:42.180Z [INFO] plugin/reload: Running configuration MD5 = 1335ba7188be742fe37cd05805faa0fa
2019-04-29T12:26:42.180Z [INFO] CoreDNS-1.5.0
2019-04-29T12:26:42.180Z [INFO] linux/amd64, go1.12.2, e3f9a80
CoreDNS-1.5.0
linux/amd64, go1.12.2, e3f9a80
2019-04-29T12:26:48.181Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:51809->10.233.0.3:53: i/o timeout
2019-04-29T12:26:51.181Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:52463->10.233.0.3:53: i/o timeout
2019-04-29T12:26:52.181Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:44654->10.233.0.3:53: i/o timeout
2019-04-29T12:26:53.181Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:35028->10.233.0.3:53: i/o timeout
2019-04-29T12:26:56.181Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:44331->10.233.0.3:53: i/o timeout
2019-04-29T12:26:59.182Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:38640->10.233.0.3:53: i/o timeout
2019-04-29T12:27:02.182Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:57424->10.233.0.3:53: i/o timeout
2019-04-29T12:27:05.182Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:56166->10.233.0.3:53: i/o timeout
2019-04-29T12:27:08.182Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:59509->10.233.0.3:53: i/o timeout
2019-04-29T12:27:11.183Z [ERROR] plugin/errors: 2 8373768935828175380.8715076686105595443. HINFO: read udp 10.233.113.56:56157->10.233.0.3:53: i/o timeout
```

![image](https://user-images.githubusercontent.com/28667591/56897562-63605200-6ac1-11e9-9096-fdab9a6be2e7.png)

The 10.233.0.3:53 is coredns service and  10.233.113.56 coredns pods .
When I configure  /etc/resolv.conf on host which the coredns pod is running on, the coredns pods is running, but keeping content of  the /etc/resolv.conf  is empty, the pods will not run, and the log in coredns pods  tells me timeout.

**Comment by chrisohaver** [comment]
> The 10.233.0.3:53 is coredns service and 10.233.113.56 coredns pods .
> `10.233.113.56:56157->10.233.0.3:53: i/o timeout`

This means you have CoreDNS pointing to itself for upstream queries.  This will cause an infinite forwarding loop ...  which is bad.  You should instead configure your hosts `/etc/resolv.conf` to contain the nameserver on your local network, or a public DNS such as 8.8.8.8 (but it definitely should not be the coredns service IP).

A side note: The loop plugin _should_ be catching this and exiting ... but it seems that it is not working correctly.  It appears to be receiving the same probe query repeatedly, but not exiting.

**Comment by chrisohaver** [comment]
> but it seems that it is not working correctly

Actually - Is it possible that you truncated the log?  If loop detection is working the last entry in the log should be an error from the *loop* plugin, stating that a loop was detected.

**Comment by AlawnWong** [comment]
i meet the same problem. 
how to fix it ？

**Comment by chrisohaver** [comment]
> i meet the same problem.
> how to fix it ？

If it is actually the same problem, then as stated above: 

>"... you have CoreDNS pointing to itself for upstream queries. This will cause an infinite forwarding loop ... which is bad. You should instead configure your hosts' `/etc/resolv.conf` to contain the nameserver on your local network, or a public DNS such as 8.8.8.8 (but it definitely should not be the coredns service IP)."

**Comment by yacinelazaar** [comment]
Hey @chrisohaver,

I have encountered the same error with the DNS service logging so:
```
│ coredns-5c98db65d4-hjzc2:coredns 2019-10-01T17:23:08.180Z [INFO] linux/amd64, go1.11.4, 6b56a9c                                                                            │
│ coredns-5c98db65d4-hjzc2:coredns CoreDNS-1.3.1                                                                                                                             │
│ coredns-5c98db65d4-hjzc2:coredns linux/amd64, go1.11.4, 6b56a9c                                                                                                            │
│ coredns-5c98db65d4-hjzc2:coredns 2019-10-01T17:23:08.180Z [INFO] plugin/reload: Running configuration MD5 = 5d5369fbc12f985709b924e721217843                               │
│ coredns-5c98db65d4-hjzc2:coredns 2019-10-01T17:23:14.185Z [ERROR] plugin/errors: 2 3955625595227571762.8196026466306475879. HINFO: read udp 192.168.221.193:47168->10.0.2. │
│ 3:53: i/o timeout                                                                                                                                                          │
│ coredns-5c98db65d4-hjzc2:coredns 2019-10-01T17:23:17.210Z [ERROR] plugin/errors: 2 3955625595227571762.8196026466306475879. HINFO: read udp 192.168.221.193:49778->10.0.2. │
│ 3:53: i/o timeout
```

I tested two similar setups with vagrant, one with Calcio and the other uses Flannel:
- I have the same logs for the kube-dns service (just the pod IP's change depending on the pod CIDR)
- Calcio pods and Flannel pods show no errors whatsover.
- With Calcio i was able to do nslookup using busybox to kubernetes.default or external domains.
- With Flannel i was not able to do neither.
- Pods's `/etc/resolv.conf` point to 10.96.10.0 (DNS service IP)
- Hosts's `/etc/resolv.conf` point to 10.0.2.3 (Don't know what that address is for. I know that 10.0.2.2 is the VirtualBox Nat gateway)

My questions are:
- How should i interpret the dns service's logs?
- Besides opening Hosts for 8285 udp and pass bridged IP traffic to iptables on the hosts, What am I missing to get the Flannel CNI working? (So far its not resolving anything)

**Comment by chrisohaver** [comment]
> I have encountered the same error

This isn't the same error... the original error showed a timeout connecting to the coredns service, which causes an infinite a forwarding loop.  Your error shows a timeout connecting to the upstream dns server (10.0.2.3).

**Comment by chrisohaver** [comment]
@yacinelazaar, before troubleshooting DNS, I'd recommend verifying IP networking is functional first... verify that ...
* pods can connect to one another via IP address
* pods can connect to cluster services via IP address
* pods can connect to systems external to the cluster via IP address. 

If after verifying that, DNS still doesn't work, we can help you here.

**Comment by yacinelazaar** [comment]
@chrisohaver 
I run the tests and it turns out there are issues with flannel's setup.

Tested on Kubernetes VMs cluster (1 Master / 2 Workers).
Test were run using 2 dns-tools pods (one in each worker) and an Nginx service with a single endpoint.

Results:
- Using Flannet:
	- Pods cant ping each other (tested across nodes)
	- Pods can curl service IP from pod if service has an endpoint on the same machine as the pod otherwise it can't
	- Pods can ping outside IP (google 216.58.198.78)
- Using Calcio:
	- Pods can ping each other (in different nodes)
	- Pods can curl service IP
	- Pods can ping outside IP

Set aside Flannel issues (Im working on those), I'm still seeing the same errors with the dns pods even with Calcio as a cni (timeouts from dns pods to 10.0.2.3)

**Comment by chrisohaver** [comment]
> with Calcio as a cni (timeouts from dns pods to 10.0.2.3)

Can you reach 10.0.2.3 from a pod via dns?  e.g. from a pod, `dig @10.0.2.3 example.com`

**Comment by KeithTt** [comment]
I encountered similar problem, but it only occurred occasionally.

It seems this has something to do with flannel?

**Comment by tadman** [comment]
I had an issue where the system had a default route for a private network IP interface, which caused the traffic to get redirected to the wrong upstream.

Resolved by checking that there's only one default route that's valid.

**Comment by shruthidharani-4313** [comment]
@tadman I am also facing the same issue. I have built a rancher cluster with 3 interfaces (eth0, eth1- private and eth2- public) using multus-cni. And on the worker node, I could see the default route is eth0. Also I have installed a pod in the default namespace of rancher cluster. I have one container inside that pod and I am getting eth0 as default route inside that container. With this route, my pod/container is able to communicate coredns without any issues. But I don't need to send all traffic via default eth0 interface. So I changed the default route as eth2 instead of eth0 on both worker node and inside my container. I added explicit route to reach kubernetes nameserver via eth0. Once I changed the default route to eth2 instead of eth0, container is getting intermittent failure to reach coredns saying "no servers could be reached". Is this the same issue you faced? and can you please explain how you resolved this issue?

**Comment by tadman** [comment]
@shruthidharani-4313 In my case there was more than one default route, and removing the extraneous ones resolved the routing issue.

Check your routing table and ensure there's one and only one default route, and that it's on the correct interface.

**Comment by shruthidharani-4313** [comment]
@tadman Yes, I do have only one default route that is on eth2 (which I brought in via multus-cni). 
```
Inside worker node:
$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.31.7.1       0.0.0.0         UG    0      0        0 eth2
10.43.0.0       192.168.6.1     255.255.255.0   UG    0      0        0 eth0   
```
added the last route to communicate kubernetes nameserver via eth0, before adding this explicit route, nameserver has not reached even for one time. After adding this route, nameserver was reachable intermittently. I do have other routes  for eth1 and eth2 which is not pasted here just to avoid lengthy output.

Inside container, I had route table as below:
```
[root@user]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.31.7.1      0.0.0.0         UG    0      0        0          eth2
10.30.5.0       0.0.0.0         255.255.255.0   U     0      0        0     eth1
10.31.7.0       0.0.0.0         255.255.255.0   U     0      0        0     eth2
**10.43.0.0       169.254.1.1     255.255.0.0     UG    0      0        0 eth0**  => added this similar to worker node
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0      0  eth0
```

**Comment by tadman** [comment]
@shruthidharani-4313 What matters most is that your DNS server(s) are accessible via the routing table. There's containers you can deploy to test this, but busybox comes with some basic tools to get started. Maybe have a poke around there and see what routing issues there are, or even use `tcpdump` on the parent node to see if your packets are even making it out.

Sometimes you need to tear down your CNI and reinstall it. I've had to pull and reapply Flannel several times when it starts behaving unpredictably.

**Comment by shruthidharani-4313** [comment]
@tadman Thanks, when I install dnstools to check dns resolution, it is working properly since dnstools pod will have only single interface (eth0). But in my case it is multi interface and have added routes to reach that dns server. When I directly dig to that server (dig @server) works fine but when it goes via kubernetes nameserver it is not.

**Comment by tadman** [comment]
@shruthidharani-4313 Beyond my level of expertise on the subject. If you do find a fix, worth adding a note here for posterity.
