### ISSUE TITLE
[file/auto] Split "transfer from" code from secondary

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2805]
For auto we still mention "transfer from", which is probably just copied over from file docs.

For file we still have "transfer from" within the code, which is imported by secondary. This feels like a weird dependance? We are not really documenting the usage within file itself.

Maybe I missed something, but I think within file we should remove all mentions of "transfer from" in the docs and split this functionality into "secondary" instead.

Will dig into the code mode and see, if we import file even more.

**Comment by stp-ip** [comment]
Route 53 is also using file code. One plugin depending on another feels problematic in the long run. I might see the benefit for auto building on file, but route53 building on file might be copied into external plugins later on basing their work on route53 and then failing, when we refactor file etc.

Thoughts?

**Comment by miekg** [comment]
There is discussion on having a transfer plugin that handles the details for this, but no code has been surfaced as yet.

Cross dependencies can work, but usually thing are split off into plugin/pkg/... if we're sharing between plugins.

The doc cleanups sgtm.

**Comment by miekg** [comment]
See https://github.com/coredns/coredns/pull/4069
closing this one in favor of that PR
