### ISSUE TITLE
Question about load balancing behavior.

### ISSUE THREAD

**Issue by shindanim** [coredns/coredns#2815]
coredns version :  v1 default coredns in kubernetes v1.11

Hello, 
I have a question about coredns behavior.

My service is composed of a frontend and a backend. 
The frontend calls grpc with service name as parameter.
I believe ther seirvice discovery is done through coredns.

But the problem is load balancing.
There are some unreachable pods and some pods get too many requests compared to the otehr pods.
![coredns_problem](https://user-images.githubusercontent.com/15517737/57197361-518b1d00-6fa1-11e9-9e42-fb8783d1d4aa.PNG)
Once frontend select the backend service, the connection would not be changed. 

According the cordns document, basic load balancing is by coredns if the service is not "headless".
All of my backend services is "normal" service. 
Following topology is my expectation.
![coredns_expected](https://user-images.githubusercontent.com/15517737/57197367-65368380-6fa1-11e9-94cb-c9a2d997dd37.PNG)

Why is the basic load balancer with round-robin not working as documented?
Do I need to install a new coredns apart from tault coredns?
he def
Or should I put in a service that acts as a load balancer between the frontend and the backend?

**Comment by johnbelamaric** [comment]
Load balancing is not done by CoreDNS, except in the case of a headless
service where it will shuffle the DNS records in the response (and even
that is not reliable, some client libs will sort the records coming back
and undo this).

For cluster IP services, the load balancing is done by kube-proxy creating
specific iptables rules that randomly (not round-robin) send traffic to
different backends.

For gRPC, the recommendation from that team (last I checked ~ 1 year ago),
is to use client side load balancing. That means, you use a headless
service in K8s, load the records for all backends (typically via an SRV
request but you can get it from an A request too if you know the port
already), and use the gRPC client load balancing facilities. That is, the
grpc client libs will create connections to each backend, and only use the
healthy ones.

John

**Comment by shindanim** [comment]
@johnbelamaric 
My problem has been solved after applying your advice :)
Thanks a lot !

**Comment by 0Ams** [comment]
@johnbelamaric Hello~!
I have some questions about the above.

I'm also experiencing a similar situation to the above. 
When a service acquires an IP (pod) address through the "coreDNS" domain address, it is concentrated only on a specific IP (POD).

Referring to the above, is it right to distribute the results of "IP (pod)" in the headless service instead of distributing the "IP (pod)" access to the response in "coredns"?

If so, I would like to know which action the loadbalance is set for the loadbalance option of the corens corefile setting.

ps. I used coredns:1.8.0
