### ISSUE TITLE
why there are only two coredns in 3 nodes?

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#2819]
Deat All
I have one question:
These days I installed the k8s with kubeadm. And there are 3 nodes: 1 master and 2 nodes. But every time I tried, there are only two nodes with coredns pod.
I am a fresh man, please give me some suggestions, thanks !
----------------------------------
Here is the log:
#pod info
[root@huawei1 ~]# kubectl get pod -n kube-system
NAME                                   READY   STATUS    RESTARTS   AGE
coredns-fb8b8dccf-j6xsx                1/1     Running   0          22m
coredns-fb8b8dccf-whvzc                1/1     Running   0          22m
etcd-huawei1.zhxu                      1/1     Running   0          50m
kube-apiserver-huawei1.zhxu            1/1     Running   0          50m
kube-controller-manager-huawei1.zhxu   1/1     Running   4          50m
kube-flannel-ds-amd64-29pxq            1/1     Running   1          46m
kube-flannel-ds-amd64-8tcmf            1/1     Running   1          46m
kube-flannel-ds-amd64-z2gld            1/1     Running   0          46m
kube-proxy-2w8xk                       1/1     Running   1          47m
kube-proxy-n8cd8                       1/1     Running   1          49m
kube-proxy-xfw95                       1/1     Running   0          51m
kube-scheduler-huawei1.zhxu            1/1     Running   3          50m

#node info
[root@huawei1 ~]# kubectl get node
NAME           STATUS   ROLES    AGE   VERSION
huawei1.zhxu   Ready    master   65m   v1.14.1
huawei2.zhxu   Ready    <none>   61m   v1.14.1
huawei3.zhxu   Ready    <none>   63m   v1.14.1

#image info
[root@huawei1 ~]# docker image ls
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy                v1.14.1             20a2d7035165        3 weeks ago         82.1MB
k8s.gcr.io/kube-apiserver            v1.14.1             cfaa4ad74c37        3 weeks ago         210MB
k8s.gcr.io/kube-scheduler            v1.14.1             8931473d5bdb        3 weeks ago         81.6MB
k8s.gcr.io/kube-controller-manager   v1.14.1             efb3887b411d        3 weeks ago         158MB
quay.io/coreos/flannel               v0.11.0-amd64       ff281650a721        3 months ago        52.6MB
k8s.gcr.io/coredns                   1.3.1               eb516548c180        3 months ago        40.3MB
k8s.gcr.io/etcd                      3.3.10              2c4adeb21b4f        5 months ago        258MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        16 months ago       742kB

**Comment by zhxu1987** [comment]
<!-- 
Deat All
I have one question:
These days I installed the k8s with kubeadm. And there are 3 nodes: 1 master and 2 nodes. But every time I tried, there are only two nodes with coredns pod.
I am a fresh man, please give me some suggestions, thanks !
----------------------------------
Here is the log:
#pod info
[root@huawei1 ~]# kubectl get pod -n kube-system
NAME                                   READY   STATUS    RESTARTS   AGE
coredns-fb8b8dccf-j6xsx                1/1     Running   0          22m
coredns-fb8b8dccf-whvzc                1/1     Running   0          22m
etcd-huawei1.zhxu                      1/1     Running   0          50m
kube-apiserver-huawei1.zhxu            1/1     Running   0          50m
kube-controller-manager-huawei1.zhxu   1/1     Running   4          50m
kube-flannel-ds-amd64-29pxq            1/1     Running   1          46m
kube-flannel-ds-amd64-8tcmf            1/1     Running   1          46m
kube-flannel-ds-amd64-z2gld            1/1     Running   0          46m
kube-proxy-2w8xk                       1/1     Running   1          47m
kube-proxy-n8cd8                       1/1     Running   1          49m
kube-proxy-xfw95                       1/1     Running   0          51m
kube-scheduler-huawei1.zhxu            1/1     Running   3          50m

#node info
[root@huawei1 ~]# kubectl get node
NAME           STATUS   ROLES    AGE   VERSION
huawei1.zhxu   Ready    master   65m   v1.14.1
huawei2.zhxu   Ready    <none>   61m   v1.14.1
huawei3.zhxu   Ready    <none>   63m   v1.14.1

#image info
[root@huawei1 ~]# docker image ls
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy                v1.14.1             20a2d7035165        3 weeks ago         82.1MB
k8s.gcr.io/kube-apiserver            v1.14.1             cfaa4ad74c37        3 weeks ago         210MB
k8s.gcr.io/kube-scheduler            v1.14.1             8931473d5bdb        3 weeks ago         81.6MB
k8s.gcr.io/kube-controller-manager   v1.14.1             efb3887b411d        3 weeks ago         158MB
quay.io/coreos/flannel               v0.11.0-amd64       ff281650a721        3 months ago        52.6MB
k8s.gcr.io/coredns                   1.3.1               eb516548c180        3 months ago        40.3MB
k8s.gcr.io/etcd                      3.3.10              2c4adeb21b4f        5 months ago        258MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        16 months ago       742kB

**Comment by chrisohaver** [comment]
This is because the Deployment has 2 replicas.
A single coredns instance can serve a whole cluster.  You don't need one on every node.

**Comment by ghost** [comment]
Thanks for your reply! I got it.

发送自 Windows 10 版邮件应用

发件人: chrisohaver
发送时间: 2019年5月7日 20:45
收件人: coredns/coredns
抄送: zhxu1987; Author
主题: Re: [coredns/coredns] why there are only two coredns in 3 nodes?(#2819)

This is because the Deployment has 2 replicas.
A single coredns instance can serve a whole cluster. You don't need one on every node.
