### ISSUE TITLE
plugin/hosts updating hosts file does not override current configuration

### ISSUE THREAD

**Issue by scalarindetail** [coredns/coredns#2836]
If the current content of the host file served by the host plugin for `example.com` is 
```
<IPv4_1>   example.com
```
and then if I modify the same file with a new IP address.
```
<IPv4_2>   example.com
```
From now one, the answer section will reflect the content of the previous configuration and the new one.
```
dig @localhost example.com
...
;; ANSWER SECTION:
example.com.		3600	IN	A	<IPv4_1>
example.com.		3600	IN	A	<IPv4_2>

```
I would have expected the new configuration to override the old one like the file plugin is doing in such a scenario but it seems to append it instead. Is it the normal behavior ?
Thank you

core dns version : 1.5.0

**Comment by miekg** [comment]
What's your corefile?

**Comment by miekg** [comment]
looks stale, intent to close this soon
