### ISSUE TITLE
The gopkg.in/DataDog/dd-trace-go.v0/opentracing dependency is broken

### ISSUE THREAD

**Issue by yurivict** [coredns/coredns#2838]
In the FreeBSD port it first wants ```dd-trace-go.v0```:
```
plugin/trace/trace.go:22:2: cannot find package "gopkg.in/DataDog/dd-trace-go.v0/opentracing" in any of:
	/usr/ports/dns/coredns/work/src/github.com/coredns/coredns/vendor/gopkg.in/DataDog/dd-trace-go.v0/opentracing (vendor tree)
	/usr/local/go/src/gopkg.in/DataDog/dd-trace-go.v0/opentracing (from $GOROOT)
	/usr/ports/dns/coredns/work/src/gopkg.in/DataDog/dd-trace-go.v0/opentracing (from $GOPATH)
```

But after I add it, it also wants the same package ```dd-trace-go``` without ```v0```:
```
vendor/gopkg.in/DataDog/dd-trace-go.v0/opentracing/span.go:7:2: cannot find package "github.com/DataDog/dd-trace-go/tracer" in any of:
	/usr/ports/dns/coredns/work/src/github.com/coredns/coredns/vendor/gopkg.in/DataDog/dd-trace-go.v0/vendor/github.com/DataDog/dd-trace-go/tracer (vendor tree)
	/usr/ports/dns/coredns/work/src/github.com/coredns/coredns/vendor/github.com/DataDog/dd-trace-go/tracer
	/usr/local/go/src/github.com/DataDog/dd-trace-go/tracer (from $GOROOT)
	/usr/ports/dns/coredns/work/src/github.com/DataDog/dd-trace-go/tracer (from $GOPATH)
```

Now I am stuck with the FreeBSD port.
Adding ```dd-trace-go``` without ```v0``` doesn't help.

It also doesn't seem right that both ```v0``` and non-```v0``` versions are imported into the same project.

**Comment by miekg** [comment]
is this with master? Seems odd and def. something we want to fix.

**Comment by yurivict** [comment]
This is with version 1.5.0

**Comment by yurivict** [comment]
master has the same problem

**Comment by sharmaansh21** [comment]
Same here Ubuntu 18.04
```
go get github.com/coredns/coredns
package github.com/DataDog/dd-trace-go/tracer: cannot find package "github.com/DataDog/dd-trace-go/tracer" in any of:
	/home/anshul/.gvm/gos/go1.12.5/src/github.com/DataDog/dd-trace-go/tracer (from $GOROOT)
	/home/anshul/.gvm/pkgsets/go1.12.5/global/src/github.com/DataDog/dd-trace-go/tracer (from $GOPATH)

```

**Comment by yongtang** [comment]
I am using make (with `GOOS=freebsd`) and it seems to be working fine with master.

**Comment by yurivict** [comment]
I'm trying not to just build it, but to create a port for it. In the ports framework all dependencies need to be pre-downloaded. In the process of doing this, it finds this problem with conflicting versions.

Perhaps Go has some magic way to resolve this internally. But it is impossible to let Go directly download dependencies from github in the port context because of security issues that this creates: Go doesn't check fingerprints of downloaded files, relying only on https, which is a weaker security level compared to fingerprints.

**Comment by yongtang** [comment]
@yurivict We are using go mod for dependency management. I am wondering if it makes a difference if you prefix `GO111MODULE=on ` for all the go command you run on freebsd?

**Comment by yurivict** [comment]
```GO111MODULE=on``` causes go to download a lot of modules from github for some reason.

**Comment by yurivict** [comment]
IMO, it's a clear problem that both v0 and a regular version are used. One just can't mix two versions in one program. Go probably contains some hack to work with this, but you should just use one version or another only.

**Comment by stp-ip** [comment]
Use `go mod vendor` or use `go mod download` and copy over the cache it creates to where you need it and use it as offline source via `export GOPROXY=file://your/cache/path`.

As far as I can see this is a problem with how Go is used and not with CoreDNS. Aka can't reproduce this. Let me know, if the above solves the problem.

**Comment by yurivict** [comment]
There is a FreeBSD framework support for go that has hundreds of ports using it.
I can't just create a large workaround for this project because of this problem.

**Comment by yurivict** [comment]
The same package clearly can't be used with two different names/versions. This is obviously a bug.

**Comment by yurivict** [comment]
I managed to solve this.

**Comment by stp-ip** [comment]
Go modules specifically was created to address the two different versions problem. So in my view still not a bug within CoreDNS, but moving to the latest version would be great. If you want to push a PR that would be great.

**Comment by sharmaansh21** [comment]
They do have some readme for how to migrate, I can look into it today.
