### ISSUE TITLE
There's no central lifecycle mechanisms for plugins to hook into

### ISSUE THREAD

**Issue by maguro** [coredns/coredns#2843]
I have a plugin that collects info in the background.  It would be nice if it could be notified that it should shutdown.  I think that putting something in to support this will be tough because of coredns' reliance on caddy.

If the consensus is that it's ok if everything suddenly gets killed, then feel free to close this issu.,e

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] There's no centra..." ]
>I have a plugin that collects info in the background.  It would be nice if it could be notified that it should shutdown.  I think that putting something in to support this will be tough because of coredns' reliance on caddy.
>
>If the consensus is that it's ok if everything suddenly gets killed, then feel free to close this issu.,e

Look at ready and health for instance, you need to setup OnRestart and other 
helper functions.

/label: question

**Comment by johnbelamaric** [comment]
See the On* methods in caddy.Controller, I think that is what you are looking for:

https://godoc.org/github.com/mholt/caddy#Controller

**Comment by maguro** [comment]
Many thanks!
