### ISSUE TITLE
plugin/file: autosign for DNSSEC

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2848]
I want to pick up some DNSSEC work that I need for my own zones again.

This will add an `autosign` directive to the *file* (maybe *auto* as well?), that automatically signs your zones. This directive will not:
* perform keyrollovers
* perform algorithm rollovers
It will
* sign your zone (every Thursday), with fixes inception and expiration (copied from *dnssec* plugin)
* automatically generate a signing key (CSK - 1 key to zone and upload to parent)
* use predefined key (if flags are correct) to sign

The latter can be used to do a key rollover, i.e. generate a new key *and* an old key to facilitate a (manual) key rollover [this needs slightly more thought).

The SOA's serial will use Unix epoch (no choice) and CoreDNS will rewrite your zonefile to make this happen. Comments are eaten, but I wonder if we can change miekg/dns to allow more comments to be returned.

**Comment by miekg** [comment]
See https://github.com/miekg/dns/issues/978 for comments in zone files.

**Comment by miekg** [comment]
Personally I only have a need for signing the zone. I'm trying to write the file/README.md to see what's needed here. I'm thinking:

* something generates key(s) (CSK)
* coredns will sign and add CDS and RRSIG etc to the zone and then wait for it to reload - which is already enabled

Not supported are all the cool bits; alg rollover and the like, automatic upload. Automatic upload to a provider may be support in the future (good thing to keep in mind on how the directive in the Corefile needs to look)

So from the coredns side this just needs a scheduler to resign *and* something the generate keys. Now dnssec-keygen exists and works, but it may make sense to duplicate it in Go for this simple use-case. This requires a coredns-keygen command.

**Comment by miekg** [comment]
Also needs:

* pointer to keys to be used for signing
* directory to write to

CoreDNS doesn't use disk currently, Caddy uses a disk abstraction, something ala http.FileSystem. It's time to make a decision here. Afterwards we can also store secondary zone and it makes sense to keep those directive named the same.

**Comment by stp-ip** [comment]
Was thinking about this a bit. Just a few thoughts for now :)

Simplest:
* provide a tool to make signing zone files easy, which get deployed via file/auto

More advanced:
* single CoreDNS
* autocreate all certs on first start (if not available)
* promp to upload to the parent zone (later auto upload via DNS provider similar to caddy?)
* autosign similar to dnssec plugin (why do it within file/auto specifically?)

The filestore abstraction reuse from caddy would help with us getting providers. It doesn't make a huge difference, if one stores TLS certs or signing certs within that backend store. Also the code is already available including the local storage part.

DNS providers are also available and could be reused.

I'm still hazy on the why we want this compared to the dnssec plugin? Easier experience?

What's the best practice in cert rollover and resigning? Also why would one want to rollover and resign on mostly static records? Couldn't find much info on that.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/file: ..." ]
>Was thinking about this a bit. Just a few thoughts for now :)
>
>Simplest:
>* provide a tool to make signing zone files easy, which get deployed via file/auto

That's basically what the *sign* plugins boils down to, moves a signed zone file 
in the right location.

>More advanced:
>* single CoreDNS
>* autocreate all certs on first start (if not available)

There are no certs, only a public/private key pair that's used to create. 
Auto-creating is an option though.

>* promp to upload to the parent zone (later auto upload via DNS provider similar to caddy?)

Adding CDS records should make this easier and may remove to the need to 
implement (or copy) all this. Although it may be worth to look into this.

>* autosign similar to dnssec plugin (why do it within file/auto specifically?)

Yep, I want to copy some settings and config option from the dnssec plugin; 
other than that; that plugin is separate.

>The filestore abstraction reuse from caddy would help with us getting 
>providers. It doesn't make a huge difference, if one stores TLS certs or 
>signing certs within that backend store. Also the code is already available 
>including the local storage part.

Good to know.

>What's the best practice in cert rollover and resigning? Also why would one 
>want to rollover and resign on mostly static records? Couldn't find much info 
>on that.

DNSSEC key rollover are a useless thing, mostly pushed on a pure crypto agenda. They 
bare little relation to what's needed. The sign plugin will just not support 
them; this is easier to implement and makes the whole thing less fragile.

The (now closed) sign PR had the beginnings of a README to explain how the 
plugin should work.

**Comment by miekg** [comment]
See #2957
