### ISSUE TITLE
middleware/kubernetes Why multiple zones?

### ISSUE THREAD

**Issue by aledbf** [coredns/coredns#285]
In kubernetes 1 cluster means 1 zone.

**Comment by aledbf** [comment]
@mrichmon ping

**Comment by mrichmon** [comment]
I'm not sure I understand the statement "1 cluster means 1 zone". 

I can use a single kubernetes cluster to run services that I want to expose in different zones. eg "prod.mycompany" vs "staging.mycompany".

**Comment by johnbelamaric** [comment]
I think @aledbf is referring to the way you pass --cluster-zone to kubelet.

**Comment by johnbelamaric** [comment]
Sorry, --cluster-domain

**Comment by aledbf** [comment]
> I'm not sure I understand the statement "1 cluster means 1 zone".
> Sorry, --cluster-domain

Exactly. The use case is to replace `kube-dns` with just coredns (running inside the k8s cluster)

**Comment by johnbelamaric** [comment]
That support though doesn't prevent that use cases.

**Comment by miekg** [comment]
Has this been answered? (think yes)

**Comment by johnbelamaric** [comment]
Well, sort of. Internally, only the one zone is needed. Although you also need to specify the in-addr.arpa zone to get reverse to work.

I think other zones become more relevant when we add external IPs. So, you could use a label or annotation to identify the zone for an external IP. We can then AXFR that zone to secondary servers.
