### ISSUE TITLE
localhost in k8s pod not worked when upstream nameserver  unavailable

### ISSUE THREAD

**Issue by kingsqv** [coredns/coredns#2850]
coredns version:1.2.6
k8s version: 1.13.5
confimap:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . "/etc/resolv.conf"  
        cache 30
        loop
        reload
        loadbalance
    }
```
When nameserver in /etc/resolv.conf can't be reachable, the pod of k8s can't use localhost to connected.  but can use 127.0.0.1 ,when use kube-dns it works fine.
our project in offline environment，is it a bug or configuration problem does have some solution ?
Thanks

**Comment by chrisohaver** [comment]
From your description, it sounds like the version of kube-dns you are using has a (probably hard coded) response for localhost with ip of `127.0.0.1`.  

I think the correct way for this to work is that all Pods should have a local entry for localhost in `/etc/hosts`, such that the DNS server is never involved when looking up `localhost`.  

Nevertheless, if you are depending on the DNS server to answer a query for localhost with 127.0.0.1, then you can create a static record with coredns using the _hosts_ plugin.  For example:

```
        hosts /etc/hosts localhost {
         127.0.0.1 localhost
        }
```

Also, if you know that your upstream servers in `/etc/resolv.conf` are never going to be reachable, you should not forward requests to them.  i.e. remove `proxy` and `upstream`, and subsequently `fallthrough` is meaningless if there is nothing to fall through to...


```
    .:53 {
        errors
        health
        hosts /etc/hosts localhost {
         127.0.0.1 localhost
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
    }
```

**Comment by kingsqv** [comment]
Thank you for your reply.
when  in this case ，the pod's /ets/hosts has 127.0.0.1 localhost record,so I am very confused，why localhost can not work。It seems that the localhost be sent to coredns. I don't know What's wrong。
maybe k8s 。but kube-dns is fine at the same situation. and this is  inevitable.

if I change coredns's configmap Remove proxy and upstream that means pods nerver reache outside domains even if the nameserver can reachable again。 it's not a good practice。

I want to konw why coredns not like kube-dns can compatible with this situation。

**Comment by chrisohaver** [comment]
> the pod's /etc/hosts has 127.0.0.1 localhost record, so I am very confused，why localhost can not work

Your pod, for whatever reason, is ignoring the /etc/hosts.  This isn't something that CoreDNS or kube-dns can control.

> but kube-dns is fine at the same situation
> I want to konw why coredns not like kube-dns can compatible with this situation

I proposed a possible reason in my previous comment (first sentence).

> if I change coredns's configmap Remove proxy and upstream that means pods nerver reache outside domains even if the nameserver can reachable again。 it's not a good practice

You said your environment was in an "offline environment"... I interpreted that as it does not have access to any outside resources, including external DNS servers _by design_.  If it this is just a temporary network issue, then of course leave them in place.
