### ISSUE TITLE
the format of corefile in configmap

### ISSUE THREAD

**Issue by GeorgeGuo2018** [coredns/coredns#2851]
Hi,there

I want to edit the options in corefile which belongs to a coredns configmap,
using client.core_v1_api.read_namespaced_config_map('coredns', 'kube-system').get('data').get('Corefile').get('.:53') , i can get the corefile of ".:53".

but how can i edit the option in this core file, for example,changing "cache 30" to "cache 50"?
it seems that the core file i get was treated as string type in the program.
Is there any convenient ways to  do this?

Any reply would be appreciated.

**Comment by chrisohaver** [comment]
> it seems that the core file i get was treated as string 

Yes, Configmap values are strings, the Corefile is a single Configmap value.

Editing the Configmap via API would require string manipulation.

You could look at [this package](https://github.com/coredns/deployment/blob/master/kubernetes/migration/corefile/corefile.go) I recently wrote to facilitate editing Corefiles.  Specifically `New()` and `Corefile.ToString()`

**Comment by GeorgeGuo2018** [comment]
> > it seems that the core file i get was treated as string
> 
> Yes, Configmap values are strings, the Corefile is a single Configmap value.
> 
> Editing the Configmap via API would require string manipulation.
> 
> You could look at [this package](https://github.com/coredns/deployment/blob/master/kubernetes/migration/corefile/corefile.go) I recently wrote to facilitate editing Corefiles. Specifically `New()` and `Corefile.ToString()`

@chrisohaver  Thanks a lot
