### ISSUE TITLE
SERVFAIL returned for TXT when expecting ENODATA(nxdomain) from kubernetes plugin and mongodb client

### ISSUE THREAD

**Issue by laggeduout** [coredns/coredns#2852]
I am a user of AWS EKS, we had version 1.10 running that comes with kube-dns, as this version is soon to be EOL by the AWS EKS service team we opted to upgrade to 1.12 and swap out kube-dns for coredns per the AWS recommendation.

We run mongodb inside EKS from the `@stable/mongodb-replicaset` helm chart (https://github.com/helm/charts/tree/master/stable/mongodb-replicaset).

We noticed that our containers that use mongodb connections started to fail, digging into it We found the the mongodb nodejs client lib performs a TXT record lookup on the cluster address e.g `DIG TXT mongodb-client.XXX-prod.svc.cluster.local`

In the case of kube-dns the DNS server would return nxdomain, but in the case of coredns this  returns SERVFAIL, this difference causes the mongo nodejs client to abort

Looking inside the nodejs lib for mongo client it is expecting ENODATA (nxdomain) https://sourcegraph.com/github.com/mongodb/node-mongodb-native/-/blob/lib/url_parser.js#L89

I tried to dig into the source for CoreDNS around the error that is logged 'TXT: kubernetes: TXT query can only be for dns-version'

I got to here:

https://gitlab.cncf.ci/coredns/coredns/blob/windows/plugin/kubernetes/kubernetes.go#L94

I am not sure who is in the wrong in this case, if coreDNS is expected to return SERVFAIL when a TXT record does not expect using the kubernetes plugin or if the mongo client lib always expecting ENODATA(nxdomain) is a little to specific as the response may very in the case of kube-dns vs coredns.

===Config File===
`
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }
`

**Comment by johnbelamaric** [comment]
Looks like a legit bug, we should be returning either NXDOMAIN (if there is no record at that name), or no data (if there is another, non-TXT record at that name).

**Comment by chrisohaver** [comment]
Actually, I think it's more "DNS correct" to reply `NODATA` in this case, since an `A` record exists for the same name.

We could probably get away with replying `NXDOMAIN` though.  `SERVFAIL` is definitely not right.

**Comment by johnbelamaric** [comment]
FYI for a workaround you can use a rewrite rule to write any TXT to NXDOMAIN.

**Comment by johnbelamaric** [comment]
or rather maybe a template rule

**Comment by laggeduout** [comment]
Thanks for the fast response - I will give the rewrite rule a go. 
Do you have any example for the suggested rewrite?

**Comment by laggeduout** [comment]
I agree, NODATA looks to be the best response for this.

**Comment by chrisohaver** [comment]
@laggedout, what version of CoreDNS are you using.  It looks like this was fixed a while back to always reply `NODATA`...  which technically isn't 100% correct, but should work for you.

**Comment by chrisohaver** [comment]
Appears to have been fixed in #2291 which would have made it into CoreDNS 1.3.0 ...

**Comment by laggeduout** [comment]
I am using 1.2.2 from '602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/coredns:v1.2.2' this was the one AWS EKS advised here - https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

**Comment by chrisohaver** [comment]
1.2.2 was the version of CoreDNS delivered with K8s 1.12, but you should be able to upgrade to 1.3.1 without issue to get the fix.

**Comment by laggeduout** [comment]
Yea, sounds good - the fix looks fine also - I will test it out and report back.

**Comment by laggeduout** [comment]
Switched the image to coredns/coredns:1.3.1 and it works as expected :)  - I will also raise with AWS EKS team to advise them, thanks for your help!

**Comment by laggeduout** [comment]
Just for the record EKS service team report:

I can see there is an internal ticket already opened with EKS team to make latest coredns images available in official ECR repo.

I think we are good to close this issue now.

**Comment by prasadvamsi** [comment]
> CoreDNS

We have the same issue here. Using AWS, EKS and CoreDNS and MongoDB Atlas with SRV protcol.
EKS version: 1.12
CoreDNS : Image:  602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/coredns:v1.2.2

Refered this article: https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

Tried to update CoreDNS from 1.2.2 to whatever is the latest as below.

[ec2-user@ip-nnnnn ~]$ eksctl version                                                                                                             [ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.35"}                                                                                          [ec2-user@ip-nnnnnn ~]$ eksctl utils update-coredns --name EKS-xxxxxxx --approve                                                              [ℹ]  using region us-east-1                                                                                                                           [ℹ]  "coredns" is already up-to-date

As you can see above it says CoreDNS is already up-to-date.
Should I be doing anything different. Can you help me with instructions to upgrade CoreDNS ?

Thanks much.

**Comment by johnbelamaric** [comment]
You probably need to ask AWS about that.

**Comment by laggeduout** [comment]
You can do this by setting the image to use a newer version such as:

image: coredns/coredns:1.3.1

I edited it by running:

kubectl edit deployments coredns --namespace kube-system

**Comment by johnbelamaric** [comment]
In general yes, but I don't know if EKS will reconcile back to the their
supported version.

**Comment by laggeduout** [comment]
The above steps came from a support case with AWS EKS team.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] SERVFAIL retu..." ]
>The above steps came from a support case with AWS EKS team.

looks we can't do anymore here.

/close

**Comment by prasadvamsi** [comment]
> You can do this by setting the image to use a newer version such as:
> 
> image: coredns/coredns:1.3.1
> 
> I edited it by running:
> 
> kubectl edit deployments coredns --namespace kube-system

@
Thank you so much for the info. Issue of coredns was resolved.

**Comment by nickdgriffin** [comment]
@johnbelamaric They won't, I've been running versions higher than the "standard" for that version of K8s and it has gone unchanged. The EKS upgrade instructions also say that AWS won't touch add-ons.
