### ISSUE TITLE
Use dependabot ?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2858]
Start using https://github.com/marketplace/dependabot-preview. Thanos uses it and it creates PRs for updates deps. 

CoreDNS has *a lot* of deps, so not sure how spammy this will be, but right now this is a manual affair and as such a bit of a hit and miss.

**Comment by yongtang** [comment]
The biggest issue might be the DataDog/tracing dependency. It is only indirectly dependent yet it always gives me trouble when I tried to update the mod.

In the go.mod we added the following line:
```
replace github.com/DataDog/dd-trace-go v0.6.1 => github.com/datadog/dd-trace-go v0.6.1
```

But apparently this line only works with a specific dependency (not even sure which one) and any automatic update will break.

I will spend more time to investigate this dependency.

**Comment by sharmaansh21** [comment]
@yongtang After this https://github.com/coredns/coredns/pull/2868 I don't think we need to worry about 
```
replace github.com/DataDog/dd-trace-go v0.6.1 => github.com/datadog/dd-trace-go v0.6.1
```
I don't have proper context, so I may be wrong.

**Comment by yongtang** [comment]
@sharmaanshul2102 Yes once DataDog dependency could be updated several related issues could be resolved.

**Comment by yongtang** [comment]
With DataDog fix merged in, I am almost able to pull a `go get -u` to automatically update all the dependencies. The only issue so far is client-go. Looks like client-go breaks compatibility:
```
# k8s.io/client-go/rest
/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

Related to https://github.com/kubernetes/apimachinery/issues/63

Will spend some time on this issue.

**Comment by yongtang** [comment]
Looks like `client-go` have go.mod in place for master (not in release yet). Hopefully soon it might be possible to resolve the above encountered issues.

**Comment by yongtang** [comment]
I think we may have to wait for client-go fix to use dependabot. But other than client-go it looks like everything else could be updated automatically.

**Comment by miekg** [comment]
I haven't look into configuring dependabot, but it sends PRs for each change - I'll hook it up and see what happens.

**Comment by miekg** [comment]
Adding this. It need write access to the repo which strikes me as odd. I did enable it (for now) though, but it's something to keep in mind.

See https://app.dependabot.com/accounts/coredns/projects/57294 for "our" config - will plop a yaml file in our repo if we decide to keep on using this.

**Comment by yongtang** [comment]
I think there are a couple of issues:
1. When dependabot updates the go.mod, it didn't capture the replace. For example, in go.sum we have
   ```
   replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.12
   ```
   When updates `github.com/miekg/dns v1.1.12` to `v1.14` (See PR #2899), it could easily find out that:
    ```
    replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.12
    ```
    should be changed to
    ```
    replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.14
    ```
    as well. But it is not. This caused a duplication of libraries.
2. It seems dependabot could also easily run `go mod tidy` at the end of the updates to clean up unused dependencies. But this is also not in place yet. This causes `go.sum` to only increase (e.g., PR #2903).

**Comment by yongtang** [comment]
For `replace` field, I opened an issue https://github.com/dependabot/feedback/issues/538 in dependabot GitHub.

For `go mod tidy` there is already an issue in dependabot GitHub :(https://github.com/dependabot/feedback/issues/215)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Use dependabo..." ]
>I think there are a couple of issues:
>1. When dependabot updates the go.mod, it didn't capture the replace. For example, in go.sum we have
>   ```
>   replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.12
>   ```
>   When updates `github.com/miekg/dns v1.1.12` to `v1.14` (See PR #2899), it could easily find out that:
>    ```
>    replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.12
>    ```
>    should be changed to
>    ```
>    replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.14
>    ```
>    as well. But it is not. This caused a duplication of libraries.
>2. It seems dependabot could also easily run `go mod tidy` at the end of the updates to clean up unused dependencies. But this is also not in place yet. This causes `go.sum` to only increase (e.g., PR #2903).

So, not useful ?

We can use it as a way to alert us for updates - which I think is useful.

But yeah, if we can't blindly merge the PRs, it kinda goes against what we need 
from it.

**Comment by yongtang** [comment]
It is not ready for automatically update and merge.

But yes I think it is useful to alert us for updates of dependencies.

**Comment by yongtang** [comment]
Created a PR #2904 to see if the workflow could be:
- dependabot opens PR automatically as an alert.
- manually create PR with additional fixes, and close dependabot's PR automatically when merged.

**Comment by miekg** [comment]
Ok. We can put a nomerge label or something on these so we cut down on the
spam. Might add a feature to dreck to make this easy.

**Comment by yongtang** [comment]
I am wondering if dependabot could open one PR for multiple dependency updates? I think that will make it easy to keep track.

**Comment by chrisohaver** [comment]
I think at first we'll see a whole bunch (as we did), but then we'd just see them trickle in as things change.

**Comment by hmarr** [comment]
We definitely do want to run `go mod tidy` in due course, by the way - it's just blocked on a slightly larger piece of work we need to do first. Feel free to subscribe to [this issue](https://github.com/dependabot/feedback/issues/215) for updates on it.

I'm also going to look into handling `replace` directives a bit more elegantly (see https://github.com/dependabot/feedback/issues/538#issuecomment-504510997).

**Comment by yongtang** [comment]
Thanks @hmarr for the work on dependabot. Looking forward to see `go mod tidy` 👍

**Comment by miekg** [comment]
Closing for now - we use it, it looks useful. Let's see how it works out longer term.
