### ISSUE TITLE
plugin/grpc: host name resolution in config TO

### ISSUE THREAD

**Issue by inigohu** [coredns/coredns#2864]
I've been making some tests around these issues #2440 #2730.
Using `grpc.Dial`, I've found that you can add the [DNS authority server](https://github.com/grpc/grpc/blob/master/doc/naming.md#resolver-plugins). This way there is no need to make a lookup to resolve the host. The grpc Dial is async and you can set the CoreDNS server to resolve that host by itself for example.

In this Corefile examples, I've created a dns_authority property. This will create a `grpc.Dial("dns://dnshost:port/myhost:port", dialOpts...)`
```
. {
  grpc . myhost:port {
    dns_authority dnshost:port
  }
}
```

I've also made tests in Kubernetes, trying to resolve a host service and it works. 
```
mydomain {
  grpc . myservice.default.svc.cluster.local:8080 {
    dns_authority 127.0.0.1:53
  }
}
.:53 {
  errors
  log
  debug
  health
  kubernetes cluster.local in-addr.arpa ip6.arpa {
     pods insecure
     upstream
     fallthrough in-addr.arpa ip6.arpa
  }
  prometheus :9153
  forward . /etc/resolv.conf
  loop
  cache 30
  reload
  loadbalance
}
```
In this case `grpc.Dial` will resolve host of the kubernetes service through coreDNS itself using the kubernetes plugin. And the loop will prevent any loop resolution.

**Comment by glerchundi** [comment]
Would resolve our issue as well as we're manually setting/modifying our Kubernetes cluster specifications on each `kube-dns` change. Also the full cluster CI testing is a pain in the ass as we need to be aware of what is being executing where all the time and keep in sync before deploying other components that depend on the cluster dns.

What does people of CoreDNS think about this, @miekg @yongtang @chrisohaver @johnbelamaric

**Comment by johnbelamaric** [comment]
A couple thoughts:

1) This makes me wonder about generic grcp dial options, is there a way we can support them?
2) I think we need a more general solution to this problem. It just came up again on slack. It's not just this plugin or even just forward-type plugins. See:
 * https://github.com/coredns/coredns/issues/2440
 * https://github.com/coredns/coredns/pull/1592

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/grpc: ..." ]
>A couple thoughts:
>
>1) This makes me wonder about generic grcp dial options, is there a way we can support them?
>2) I think we need a more general solution to this problem. It just came up again on slack. It's not just this plugin or even just forward-type plugins. See:
> * https://github.com/coredns/coredns/issues/2440
> * https://github.com/coredns/coredns/pull/1592

It usually starts out like that, but then things mysteriously break.

Unless there is a way to resolve a name without *any* reliance on something 
outside coredns, this is bound to not end well.

This is a DNS server, that means you can't have a (cyclic) dependency on the 
protocol you're serving and somehow pretend this is OK.
