### ISSUE TITLE
Redirecting logs to a file on host

### ISSUE THREAD

**Issue by systm32** [coredns/coredns#2865]
I want to redirect the logs of coredns pod to a file on host. How can I do that?

**Comment by chrisohaver** [comment]
Pod logs live in `/var/log/containers` on the host. They are however not raw, each line of the log is encapsulated in json.

Why do you need the logs on the host?

**Comment by systm32** [comment]
I need logs on the host so that multiple restarts of the pods can be debugged later. Basically we have other pods where we generally redirect the stderr/out like "sh -c /usr/bin/dummy >> /logs/dummy.stdout.log 2>> /logs/dummy.stderr.log" and /logs is mounted on host. 
I want to do the same for the coredns pod. I thought there must be option in log plugin of coredns where I can specify the file we want to redirect the logs but didn't find out.

**Comment by johnbelamaric** [comment]
No, the log plugin no longer supports logging to a file. That is not a best
practice in Kubernetes or really in containerized applications at all.
Instead, you should use a logging agent. See
https://kubernetes.io/docs/concepts/cluster-administration/logging/#basic-logging-in-kubernetes

If you are desperate then you can build a new image that runs coredns via a
shell script that redirects where ever you want.

Or you can do something crazy like running a second container in the pod
with a shared PID namespace, find the PID of the coredns process, and cat <
/proc/$PID/fd/1 > your.log

Both of those are not great ideas though.
