### ISSUE TITLE
How the cache plugin gets response item?

### ISSUE THREAD

**Issue by MikeLing** [coredns/coredns#2869]
Hi guys, I'm new to coredns and I'm trying to figure out where the cache gets the reponse item after `forward` makes response.  Could someone kindly tell me how cache works? or which document I should look into? 
Thank you very much!

**Comment by chrisohaver** [comment]
Cache stores all responses (from any plugin in the same server block), into an in-memory cache struct.

Are you looking for an explanation as to how the code itself accomplishes this? (ResponseWriter embeds a Cache).

Or are you looking for an explanation of how cache behaves from a user perspective?

**Comment by MikeLing** [comment]
Hey @chrisohaver , thank you!

> Are you looking for an explanation as to how the code itself accomplishes this? (ResponseWriter embeds a Cache).

Yeah, I'm looking for where the Cache get all these responses. I do found we define the ResponseWriter  in Cache plugin and can store and update the response items, but I don't know where the ResponseWriter has been called exactly.

**Comment by chrisohaver** [comment]
> I'm looking for where the Cache get all these responses.

It happens in `/plugin/cache/handler.go` in `ServeDNS()` ... where `c` is the Cache, and `w` is the ResponseWriter ...

https://github.com/coredns/coredns/blob/a657e1f6618ee94c46fa9374dd29c21345710d38/plugin/cache/handler.go#L29-L33

**Comment by miekg** [comment]
answered.
