### ISSUE TITLE
Plugin Any: Add prometheus counter for refused queries 

### ISSUE THREAD

**Issue by milgradesec** [coredns/coredns#2871]

**Comment by sharmaansh21** [comment]
I can look into this :bowtie:

**Comment by miekg** [comment]
Where does *any* refuse queries?
Also there already exists a metrics that returns the rcode for queries:

coredns_dns_response_rcode_count_total{server, zone, rcode} 

https://coredns.io/plugins/metrics/

/Miek

--
Miek Gieben

**Comment by milgradesec** [comment]
Oh i was using terminology from Adguard refuseany plugin (https://github.com/AdguardTeam/AdGuardDNS/tree/master/coredns_plugin/refuseany).
As far as i know ANY queries are blocked as mitigation to DNS amplification attacks, so both plugins have the same purpose but they send different responses , am i right? 

ANY queries in coredns_dns_response_rcode_count_total with plugin/any enabled acts as a blocked counter?

Thanks

**Comment by miekg** [comment]
They are not blocked, they are replied to with a HINFO response.
