### ISSUE TITLE
restore "vendor" folder of coredns repo

### ISSUE THREAD

**Issue by figo** [coredns/coredns#2874]
* the version of CoreDNS you are using
v1.5.0

* issue
the vendors been removed from code repo when switched to `go module`,
this is problematic to enterprise environment that want to keep dependencies in one place
and avoid downloading dependencies at runtime.

* solution
we can keep the default behavior of downloading dependencies at runtime.
but also keep vendors at repo, have Makefile support build from vendors by using
```
go build -mod vendor
```
please refer to https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

**Comment by miekg** [comment]
Sorry, this is standard feature of Go. We're not going to carry to deps any
more.

This entirely solvable in enterprise environments as well, without us doing
anything.

**Comment by figo** [comment]
> Sorry, this is standard feature of Go. We're not going to carry to deps any more. This entirely solvable in enterprise environments as well, without us doing anything.

it actually the standard practice to keep both go module and vendors at repo, i will list two examples:
https://github.com/kubernetes/kubernetes
https://github.com/etcd-io/etcd

**Comment by miekg** [comment]
Sorry, but you can't make your problem our problem. This is bog standard
and I'm glad we're not carrying several megabytes of data in this repo
anymore.

**Comment by johnbelamaric** [comment]
I don't think it's as clear cut as that, Miek. If we don't vendor, then if someone deletes or archives one of our dependencies, we are completely screwed.

**Comment by miekg** [comment]
Well. How do we keep this in sync?

But that's true if a vendor disappears we can't compile unless you use
goproxy which will probably cache everything.

**Comment by johnbelamaric** [comment]
I think go mod manages the vendoring for us. I suppose there is periodic refreshing of it. I haven't dug into the details of it.

**Comment by figo** [comment]
> Well. How do we keep this in sync? But that's true if a vendor disappears we can't compile unless you use goproxy which will probably cache everything.

manually run `go mod vendor` will automatically updating files in vendor folder based on go.mod.
but build it into ci will be better, please refer to this link: https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

**Comment by figo** [comment]
> Sorry, but you can't make your problem our problem. This is bog standard and I'm glad we're not carrying several megabytes of data in this repo anymore.

thank you for quick reply, i should have clarify myself when saying: standard, it is not real standard per-se, but mostly an observed practice in kubernetes community. 

also i see both you as maintainer and us as coredns users on the same side, i raise the issue with the intention of solve it for us and also potentially benefit to others in community.
but @johnbelamaric hit the point in term of why it may matters to coredns community.

thanks again!

**Comment by figo** [comment]
go community has discussed this issue for a while, go will likely to support both cases in an automatic fashion in 1.14, please refer to 
https://github.com/golang/go/issues/27227
https://github.com/golang/go/issues/30240

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] restore "vend..." ]
>> Well. How do we keep this in sync? But that's true if a vendor disappears we can't compile unless you use goproxy which will probably cache everything.
>
>manually run `go mod vendor` will automatically updating files in vendor folder based on go.mod.
>but build it into ci will be better.

*manually* is exactly one of the problems here.

**Comment by figo** [comment]
> *manually* is exactly one of the problems here.

i totally agree, in short term, i added a shell script into CI to automatically check whether go.mod and vendors are in-sync: https://github.com/coredns/coredns/pull/2875/files#diff-262c5420cd9a238bac1d4e3674b0de5e

hope this make sense.
