### ISSUE TITLE
plugin/cache: Create a 'cache' for ongoing requests

### ISSUE THREAD

**Issue by milgradesec** [coredns/coredns#2879]
I constantly see identical requests made two by two (same query duplicated) at the same time and both are forwarded to upstreams, I thought in a cache for ongoing requests, so the first query creates an entry and following identical queries wait and get the cached response from the first query when it arrives.
It will reduce load in databases and requests to upstreams.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/cache: Cre..." ]
>I constantly see identical requests made two by two (same query duplicated) at the same time and both are forwarded to upstreams, I thought in a cache for ongoing requests, so the first query creates an entry and following identical queries wait and get the cached response from the first query when it arrives.
>It will reduce load in databases and requests to upstreams.

In general this is a good thing to do, see client.SingleInflight in 
github.com/miekg/dns, but if we enable something like this we need to be careful 
about the performance implications because you create a process wide mutex for 
upstream requests.

/label: enhancement
/plugin: forward

**Comment by ihac** [comment]
Hi @UWgVXGPsoC 
I'm not pretty sure but two (or more) straight identical DNS requests seem to be rare. Could you please share some contexts where DNS queries are duplicated?

**Comment by milgradesec** [comment]
I'm running coredns in my network with Windows and android devices and as a public DNS server.

I see this many times, same query duplicated and both forwarded
2019-06-22T20:16:04.069+02:00 [INFO] 192.168.1.171:51564 - 14209 "A IN substrate.office.com. udp 38 false 512" NOERROR qr,rd,ra 332 0.031258908s
2019-06-22T20:16:04.082+02:00 [INFO] 192.168.1.171:51564 - 14209 "A IN substrate.office.com. udp 38 false 512" NOERROR qr,rd,ra 332 0.019096344s
