### ISSUE TITLE
plugin/file: misbehaviour in zone with @

### ISSUE THREAD

**Issue by rgl** [coredns/coredns#2880]
When using CoreDNS 1.5.0 with `Corefile`:

```
. {
    file example.org.zone {
        transfer to *
    }
    log
    errors
}
```

And `example.org.zone` file:

```
$TTL 30m
$ORIGIN example.org.

@       in soa      ns  hostmaster (
    2019061101  ; serial number (this number should be increased each time this zone file is changed)
    4h          ; refresh (the polling interval that slave DNS server will query the master for zone changes)
                ; NB the slave will use this value instead of $TTL when deciding if the zone it outdated
    1h          ; update retry (the slave will retry a zone transfer after a transfer failure)
    7d          ; expire (the slave will ignore this zone if the transfer keeps failing for this long)
    4h          ; minimum (the slave stores negative results for this long)
)
        in ns      ns
ns      in a       10.0.0.2
ns      in a       10.0.0.3
www     in a       10.0.1.2
```

The resolution of `www` seems to fail (there is no `A RR` in the answers):

```
C:\Users\Rui Lopes>dig a www.example.org @127.0.0.1

; <<>> DiG 9.14.2 <<>> a www.example.org @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42833
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 338ef5b5d416341d (echoed)
;; QUESTION SECTION:
;www.example.org.               IN      A

;; AUTHORITY SECTION:
example.org.            1800    IN      NS      ns.example.org.

;; ADDITIONAL SECTION:
ns.example.org.         1800    IN      A       10.0.0.2
ns.example.org.         1800    IN      A       10.0.0.3

;; Query time: 6 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jun 11 07:51:04 Hora de VerÒo de GMT 2019
;; MSG SIZE  rcvd: 155
```

But `axfr` seems to return the correct information:

```
C:\Users\Rui Lopes>dig axfr example.org @127.0.0.1

; <<>> DiG 9.14.2 <<>> axfr example.org @127.0.0.1
;; global options: +cmd
example.org.            1800    IN      SOA     ns.example.org. hostmaster.example.org. 2019061101 14400 3600 604800 14400
example.org.            1800    IN      NS      ns.example.org.
ns.example.org.         1800    IN      A       10.0.0.2
ns.example.org.         1800    IN      A       10.0.0.3
www.example.org.        1800    IN      A       10.0.1.2
example.org.            1800    IN      SOA     ns.example.org. hostmaster.example.org. 2019061101 14400 3600 604800 14400
;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jun 11 07:51:41 Hora de VerÒo de GMT 2019
;; XFR size: 6 records (messages 1, bytes 348)
```

When the `@` is removed from the `example.org.zone` file the resolution of `www` works:

```
C:\Users\Rui Lopes>dig a www.example.org @127.0.0.1

; <<>> DiG 9.14.2 <<>> a www.example.org @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45851
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: db0ff5d901bbddb2 (echoed)
;; QUESTION SECTION:
;www.example.org.               IN      A

;; ANSWER SECTION:
www.example.org.        1800    IN      A       10.0.1.2

;; Query time: 11 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jun 11 07:55:12 Hora de VerÒo de GMT 2019
;; MSG SIZE  rcvd: 87
```

But `axfr` fails:

```
C:\Users\Rui Lopes>dig axfr example.org @127.0.0.1
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.14.2 <<>> axfr example.org @127.0.0.1
;; global options: +cmd
; Transfer failed.
```

Do you known what is going on?

**Comment by ihac** [comment]
Also confused about this. But removing (by commenting) the `ns` record seems to work. Is this problem related to recursive request?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] misbehaviour ..." ]
>Also confused about this. But removing (by commenting) the `ns` record seems to work. Is this problem related to recursive request?

Might actually be a bug; I'll take a look

**Comment by miekg** [comment]
If you change your Corefile to:
~~~
example.org {
    file db.example.org {
        transfer to *
    }
    log
    errors
}
~~~
it works as intended. 

What are you intent here. There is no magic happening when reading the zonefile, and the only zone specified is `.` (root-zone) is this is considered a root-zone. Then you NS records tell that the example zone is delegated. This WAI.

Do we need to error here if we read a zone with origin X and the zone itself is origin? Note that `$ORIGIN` can occur anywhere in the zone.

**Comment by ihac** [comment]
Hi @miekg 
Sorry I failed to understand your comment clearly. Could you please explain a little bit more about why we cannot get the `A` record of `www.example.org` in the beginning?

> The resolution of www seems to fail (there is no A RR in the answers):

**Comment by miekg** [comment]
The zone your loading is not example.org but the root zone. You never
explicitly say example.org anywhere in the config.

Basically a configuration error.

Not sure coredns can help you here.

**Comment by rgl** [comment]
@miekg replacing the `.` with `example.org` did the trick. thank you!

it would be nice for it to warn/error when the zone file $ORIGIN is not the same as the one being defined in Corefile.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/file: ..." ]
>@miekg replacing the `.` with `example.org` did the trick. thank you!
>
>it would be nice for it to warn/error when the zone file $ORIGIN is not the same as the one being defined in Corefile.

As said, I'm open to ideas here, because I fear this is far from trivial.

Maybe we can add something to the docs? Or add a new section like "Gotchas"?

**Comment by rgl** [comment]
Indeed, it can be tricky to infer the right thing from the zone file. It should be enough to mention the possible origin mismatch in the `file` documentation.
