### ISSUE TITLE
> CoreDNS

### ISSUE THREAD

**Issue by prasadvamsi** [coredns/coredns#2881]
> CoreDNS

Refer issue #2852 

We have the same issue here. Using AWS, EKS and CoreDNS and MongoDB Atlas with SRV protcol.
EKS version: 1.12
CoreDNS : Image:  602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/coredns:v1.2.2

Refered this article: https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

Tried to update CoreDNS from 1.2.2 to whatever is the latest as below.

[ec2-user@ip-nnnnn ~]$ eksctl version                                                                                                             [ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.35"}                                                                                          [ec2-user@ip-nnnnnn ~]$ eksctl utils update-coredns --name EKS-xxxxxxx --approve                                                              [ℹ]  using region us-east-1                                                                                                                           [ℹ]  "coredns" is already up-to-date

As you can see above it says CoreDNS is already up-to-date.
Should I be doing anything different. Can you help me with instructions to upgrade CoreDNS ?

Thanks much.

_Originally posted by @prasadvamsi in https://github.com/coredns/coredns/issues/2852#issuecomment-500794936_

**Comment by miekg** [comment]
#2852 is answered by @johnbelamaric and closed. Can't see what we can add here, so closing
