### ISSUE TITLE
request may contain many `Question`

### ISSUE THREAD

**Issue by sstoner** [coredns/coredns#2888]
https://github.com/coredns/coredns/blob/c1d7c2e69becba8c9dd700aea9819a4ebde2facb/request/request.go#L359-L368   

when get `Question` type, why does it always return slice 0?     

if I have many `Question` in `request.Msg`,  how to get the rest `Question`'s type  
```go
type Msg struct {
	MsgHdr
	Compress bool       `json:"-"` // If true, the message will be compressed when converted to wire format.
	Question []Question // Holds the RR(s) of the question section.
	Answer   []RR       // Holds the RR(s) of the answer section.
	Ns       []RR       // Holds the RR(s) of the authority section.
	Extra    []RR       // Holds the RR(s) of the additional section.
}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] request contain m..." ]
>https://github.com/coredns/coredns/blob/c1d7c2e69becba8c9dd700aea9819a4ebde2facb/request/request.go#L359-L368
>
>
>when get `Question` type, why does it always return slice 0?
>
>
>if I have many `Question` in `request.Msg`,  how to get the rest `Question`'s type
>```go
>type Msg struct {
>	MsgHdr
>	Compress bool       `json:"-"` // If true, the message will be compressed when converted to wire format.
>	Question []Question // Holds the RR(s) of the question section.
>	Answer   []RR       // Holds the RR(s) of the answer section.
>	Ns       []RR       // Holds the RR(s) of the authority section.
>	Extra    []RR       // Holds the RR(s) of the additional section.
>}
>```

Although the spec allows multiple there is usually only 1 question in any 
packet. Assuming you `r` is a pointer to `dns.Msg`:

~~~
typ := r.Question[0].Qtype
~~~

/label: question
/label: dns
