### ISSUE TITLE
a doubt about the comment about plugin.Handler

### ISSUE THREAD

**Issue by Sherlock-Holo** [coredns/coredns#2892]
I am writing plugins for coredns, when I read `plugin.Handler` comment, it says

> If ServeDNS writes to the response body, it should return a status
> code. If the status code is not one of the following:
> 
> * SERVFAIL (dns.RcodeServerFailure)
> 
> * REFUSED (dns.RecodeRefused)
> 
> * FORMERR (dns.RcodeFormatError)
> 
> * NOTIMP (dns.RcodeNotImplemented)
> 
> CoreDNS assumes no reply has yet been written. All other response
> codes signal other handlers above it that the response message is
> already written, and that they should not write to it also.
> 
> If ServeDNS encounters an error, it should return the error value
> so it can be logged by designated error-handling plugin.
> 
> If writing a response after calling another ServeDNS method, the
> returned rcode SHOULD be used when writing the response.
> 
> If handling errors after calling another ServeDNS method, the
> returned error value SHOULD be logged or handled accordingly.
> 
> Otherwise, return values should be propagated down the plugin
> chain by returning them unchanged.

it confuses me: if B is the next plugin of A, when A call `plugin.NextOrFailure` and then gets the `(rcode, err)`. if B works fine, it should return `(0, nil)`, but for A, it means B doesn't write the response to the writer which A gives B, and A doesn't know how to find out B's repsonse and write it to the writer.

I think it should be:

> if status code is one of the following, CoreDNS assumes no reply has yet been written.

which means if B works fine, return `(0, nil)`, it should write the response to the writer and then A got the return values and knows B works fine and have written the response to the writer.

**Comment by chrisohaver** [comment]
Yeah - i think there is an extraneous `not` in there.  It's also a double negative phrase that is split in the middle with a bullet list. Would be clearer to restructure like this...

>If ServeDNS writes to the response body, it should return a status
code. CoreDNS assumes no reply has yet been written if the status code is one of the following:
>
> * SERVFAIL (dns.RcodeServerFailure)
> * REFUSED (dns.RecodeRefused)
> * FORMERR (dns.RcodeFormatError)
> * NOTIMP (dns.RcodeNotImplemented)
>
> All other response codes signal other handlers above it that the response message is
already written, and that they should not write to it also.
>

IOW...

If ServeDNS returns SERVFAIL, REFUSED, FORMERR, or NOTIMP, a response will be written to the client.  If ServeDNS already send a response to the client, then this would cause the response to be written twice.  In the case that ServeDNS sends a response to the client (with codes above), then it should return a 0 (NOERROR) to prevent the double write.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] a doubt about..." ]
>Yeah - i think there is an extraneous `not` in there.  It's also a double negative phrase that is split in the middle with a bullet list. Would be clearer to restructure like this...
>
>>If ServeDNS writes to the response body, it should return a status
>code. CoreDNS assumes no reply has yet been written if the status code is one of the following:
>>
>> * SERVFAIL (dns.RcodeServerFailure)
>> * REFUSED (dns.RecodeRefused)
>> * FORMERR (dns.RcodeFormatError)
>> * NOTIMP (dns.RcodeNotImplemented)
>>
>> All other response codes signal other handlers above it that the response message is
>already written, and that they should not write to it also.
>>
>
>IOW...
>
>If ServeDNS returns SERVFAIL, REFUSED, FORMERR, or NOTIMP, a response will be written to the client.  If ServeDNS already send a response to the client, then this would cause the response to be written twice.  In the case that ServeDNS sends a response to the client (with codes above), then it should return a 0 (NOERROR) to prevent the double write.

Agreed.

Please, magically turn this into a PR :)

Thanks
