### ISSUE TITLE
Health check function flag

### ISSUE THREAD

**Issue by JasonSwindle** [coredns/coredns#2897]
Howdy,

The current health check pattern is HTTP based, and works great.  It would be great if CoreDNS had a health check as a flag.  So for example

```bash
$ coredns -health
OK
```

This would allow someone to use the Docker health check function or the HTTP function to monitor CoreDNS.

**Comment by miekg** [comment]
That's likely not going to happen.

Why doesn't curling the health endpoint work? What about the readiness
endpoint?

**Comment by JasonSwindle** [comment]
The issue is, I'm not directly using this inside of K8S, so there is no kubelet to do the HTTP GET function.  So I'm having to use a sidecar curl to do the healthcheck as CoreDNS container does not contain curl.

**Comment by miekg** [comment]
So it doesn't work because out of the box you don't have a http client in
the image?

Unless I'm completely misunderstanding this seems like an easy thing to fix
(on your end)

**Comment by JasonSwindle** [comment]
Overall, it is, but I'm aiming to try to solve this for others who are using to extend the use of CoreDNS outside of K8S and use the native Docker health check function vs having to use a sidecar.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Health check ..." ]
>Overall, it is, but I'm aiming to try to solve this for others who are using to extend the use of CoreDNS outside of K8S and use the native Docker health check function vs having to use a sidecar.  This is sounding like a "Won't Fix" issue. :/

ack, but yes, this will be "Won't Fix" from our end.

/label: question
/plugin: health
/label: wontfix
/close
