### ISSUE TITLE
Route53: IAM Credential Failure

### ISSUE THREAD

**Issue by tankbusta** [coredns/coredns#2924]
During an upgrade from CoreDNS 1.2.2 to CoreDNS 1.2.6 we started seeing this error

> /etc/coredns/Corefile:17 - Error during parsing: failed to create Route53 plugin: NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Our Corefile is mostly the stock one in EKS with a few additions (route53)

    .:53 {
        errors
        health
        kubernetes cluster.local {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30

        route53 test.com.:<redacted>{
        }

        route53 test1.com.:<redacted> {
        }
    }

This Corefile works in 1.2.2 but does not in 1.2.6. I'm wondering if somehow #2118 broke the ability for CoreDNS to fetch credentials via IAM?

**Comment by sharmaansh21** [comment]
@tankbusta I think you are right,  `ec2rolecreds` missing, I will send a fix for it.

**Comment by sharmaansh21** [comment]
@tankbusta  is it possible to for you to test your use cases from my PR?

**Comment by miekg** [comment]
this looks fixed from the merged PR.
