### ISSUE TITLE
call Close() on the response writer

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2929]
We're curently not calling Close which for TCP might be a problem. And it show up in AXFR. @jinmeiib is trying to fix things here.

Opening an issue to discuss option as we were having them on pull requests.

Options:

1. The server can call close; but this leads to data race, as these need Close() calls needs to be made by the goroutine writing to them
2. add a WriteMsgAndClose() call in coredns
3. add Close() to the plugins that need them

Note the cache plugin re-uses the response writer for prefetch, it should create a new responsewriter to do that and just let the old one be closed.

**Comment by YanLemon** [comment]
@jinmeiib Is this close problem  relevant to my issue? https://github.com/coredns/coredns/issues/2948

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] call Close() ..." ]
>@jinmeiib Is this close problem  relevant to my issue? https://github.com/coredns/coredns/issues/2948

no

**Comment by YanLemon** [comment]
Thank you.
