### ISSUE TITLE
Releases should contain changelogs.

### ISSUE THREAD

**Issue by SleepyBrett** [coredns/coredns#2930]
Not really acceptable: https://github.com/coredns/coredns/releases/tag/v1.5.1

Am I to believe that the only changes here were changes to the ci pipelines? If so why the minor version bump? https://github.com/coredns/coredns/releases/tag/v1.5.0

I know I'm coming off like an ass, but I run this software in production with a lot of other software, knowing exactly what I'm in store for when I do an upgrade is essential.

**Comment by rajansandeep** [comment]
https://coredns.io/blog/
https://coredns.io/2019/06/26/coredns-1.5.1-release/
