### ISSUE TITLE
plugin/file reload do not update serial of SOA record

### ISSUE THREAD

**Issue by netexr** [coredns/coredns#2932]
1.  coredns version: 1.5.1
2. auto reload when data file chaned was working for master, but serial of SOA record was not update automatically, so slave rejected the push: "Notify from ::1 for example.com.: no serial increase seen"
3. send SIGUSR1 to master process, it works.

**config for master**

> example.com {
>     file db.example.com {
>         transfer to 127.0.0.1:5555
>         transfer to [::1]:5555
>         reload 2s
>     }
>     log
>     errors
> }

**config for slave**

> example.com:5555 {
>     secondary {
>         transfer from 127.0.0.1
>         transfer from ::1
>     }
>     log
>     errors
> }

**Comment by miekg** [comment]
We don't write or update the SOA on reload, your provisioning needs to do
this.

**Comment by netexr** [comment]
I did update the serial number of data file, otherwise master would not get reload.

The problem is that after auto reload, A record is updated, but SOA record not.

I tried again, failure began from second modify.

**Comment by netexr** [comment]
> [INFO] plugin/file: Successfully reloaded zone "example.com." in "db.example.com" with serial **2019062918**

logs print serial is udpate to 2019062918, but I query soa record get 2019062912

> $ dig +short @localhost example.com soa
> sns.dns.icann.org. noc.dns.icann.org. **2019062912** 7200 3600 1209600 3600

**Comment by miekg** [comment]
I still have no idea what the bug is here. Intent to close this soonish
