### ISSUE TITLE
Coredns fails on new pods for a few minutes

### ISSUE THREAD

**Issue by iammuho** [coredns/coredns#2939]
Hello,

I'm facing a problem with CoreDNS on kubernetes cluster.  I've installed the kubernetes as hardway method on AWS so all the controls on me (no EKS etc.)

I've 3 worker node and 3 CoreDNS replicas. At first, I thought our problem is similar to https://github.com/coredns/coredns/issues/2824 but I have managed to handle ec2 terminations in a second so if I've terminated an EC2 server, kube-dns service updates itself immediately. But the problem starts with the new node joins.

When a new node scaled up and a new CoreDNS pod joins to kube-DNS service, we are having DNS problems. New pod, for a while, cannot resolve the DNS, but after a period, everything goes back to normal.

Error from the new pod : 

` 58224 "A IN blabla.eu-central-1.rds.amazonaws.com.blabla.svc.my-cluster.local. udp 140 false 512" NXDOMAIN qr,aa,rd 284 0.000193207s`

But pod is trying to connect : blabla.eu-central-1.rds.amazonaws.com

CoreDNS Config:

`.:53 {
        log
        errors
        health
        ready
        kubernetes my-cluster.local {
          pods verified
          upstream
        }
        prometheus :9153
        loadbalance round_robin
        forward . 8.8.8.8 8.8.4.4
        cache 30
        reload
    }`

- I've Calico and I've scheduled them to different worker nodes so the problem isn't on it.
- I've passed --resolv-conf with 8.8.8.8 upstreams and doesn't work

Hope to find the problem

**Comment by chrisohaver** [comment]
It's expected that a Pod will first try to resolve `blabla.eu-central-1.rds.amazonaws.com.blabla.svc.my-cluster.local.` when resolving `blabla.eu-central-1.rds.amazonaws.com`.

This is due to the cluster first dns policy, which causes Pods to search a series of local cluster domains before searching the bare name.  A Pod in the `blabla` will search the following first...
`blabla.eu-central-1.rds.amazonaws.com.blabla.svc.my-cluster.local.`
`blabla.eu-central-1.rds.amazonaws.com.svc.my-cluster.local.`
`blabla.eu-central-1.rds.amazonaws.com.my-cluster.local.`
It then will search any local domains as configured by the node. Finally, if all other searches return NXDOMAIN, it will search `blabla.eu-central-1.rds.amazonaws.com`.

So, in a successful lookup of an external domain name from a Pod, we should expect to see a series of queries in the cluster domain that result in NXDOMAIN, ending with a successful query/response from an upstream server.

**Comment by iammuho** [comment]
Hey @chrisohaver ,

Thank you for the explanation. But there is a problem definitely on resolving when a pod detach/attach to the service. You can see the logs below;

`2019-07-03T11:15:08.253Z [INFO] 10.9.12.100:54512 - 21283 "AAAA IN blabla.eu-central-1.rds.amazonaws.com.invoicepayment.svc.my-cluster.local. udp 140 false 512" NXDOMAIN qr,rd,ra 140 0.000269273s

2019-07-03T11:15:08.254Z [INFO] 10.9.12.100:54512 - 3555 "A IN blabla.eu-central-1.rds.amazonaws.com.invoicepayment.svc.my-cluster.local. udp 140 false 512" NXDOMAIN qr,rd,ra 140 0.000307277s

2019-07-03T11:15:08.254Z [INFO] 10.9.12.100:49291 - 23517 "AAAA IN blabla.eu-central-1.rds.amazonaws.com.svc.my-cluster.local. udp 125 false 512" NXDOMAIN qr,rd,ra 125 0.000231675s

2019-07-03T11:15:08.272Z [INFO] 10.9.12.100:49291 - 2941 "A IN blabla.eu-central-1.rds.amazonaws.com.svc.my-cluster.local. udp 125 false 512" NXDOMAIN qr,rd,ra 200 0.017750722s

2019-07-03T11:15:08.272Z [INFO] 10.9.12.73:59355 - 64462 "AAAA IN blabla.eu-central-1.rds.amazonaws.com. udp 90 false 512" NOERROR qr,rd,ra 382 0.000070747s

2019-07-03T11:15:08.272Z [INFO] 10.9.12.73:59355 - 62292 "A IN blabla.eu-central-1.rds.amazonaws.com. udp 90 false 512" NOERROR qr,rd,ra 374 0.000053434s`

And after I'm seeing on my Kibana a few 504 pages with an explanation of `Database name couldn't be resolved` 

That takes just a few seconds and I'm using a tool to send traffic for 1m and 10req/s

best,

**Comment by chrisohaver** [comment]
That log looks normal.  I see several expected NXDOMAINs, followed by NOERRORs, for A and AAAA.
This is a normal series of query/response, which suggests that the problem is not with CoreDNS.

**Comment by iammuho** [comment]
Hello @chrisohaver ,

Isn't it possible to disable this search path functioning with .com domains (or at least amazonaws.com domains)

best.

**Comment by stp-ip** [comment]
There is an experimental plugin called autopath, which might work for you, but it does have some issues.
Furthermore using the cluster addon "nodelocal dns cache" could speed up the search path as it's done right on the node including caching the negative responses right on the node.

In the long run there is a KEP open to make autopath aka resolving the searchpath on the server making it only one client request possible: https://github.com/kubernetes/enhancements/pull/967

**Comment by iammuho** [comment]
Hello,

The issue is about the calico routing latency and fixed. Thank you for help

Best,

**Comment by chrisohaver** [comment]
FWIW, just to answer the question even though it ultimately didn't relate to the issue at hand:

> Isn't it possible to disable this search path functioning with .com domains 

No, not via CoreDNS.  The decision to use search domains is entirely made by the client pod. CoreDNS has no control over this (even with plugins such as `autopath`).

The local search domains set up on each pod are derived from the local search domains on the cluster's nodes.
