### ISSUE TITLE
multiple etcd entries

### ISSUE THREAD

**Issue by JrCs** [coredns/coredns#2940]
When i try to use several etcd clusters (one by zone), CoreDNS only reply to the first zone declare in the Corefile.

In my config below, the coredns only reply to `socle.mycompany.org` domain not for  `dev.mycompany.org` or  `devsecu.mycompany.org`.

Version of CoreDNS: 1.5.0
My Corefile:
```
.:53 {
  errors
  health
  log . {
    class denial
  }
  etcd socle.mycompany.org {
    endpoint http://10.203.126.76:2379
    upstream
  }
  etcd dev.mycompany.org {
    endpoint http://10.203.126.77:2379
    upstream
  }
  etcd devsecu.mycompany.org {
    endpoint http://10.203.126.78:2379
    upstream
  }
  forward . /etc/resolv.conf
  # prometheus :9153
  loop
  reload
  loadbalance
}

```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] multiple etcd ent..." ]
>When i try to use several etcd clusters (one by zone), CoreDNS only reply to the first zone declare in the Corefile.
>
>In my config below, the coredns only reply to `socle.mycompany.org` domain not for  `dev.mycompany.org` or  `devsecu.mycompany.org`.

this doesn't work, you need to split this in 2 server block one for each 
domain. Don't know why people keep piling everything in a "." server block

**Comment by JrCs** [comment]
@miekg thanks it works.

**Comment by rhollins** [comment]
Hi @JrCs I'm having the same issue and trying to replicate the fix while using helm chart for coredns.
Basically I need to create multiple zones to work with external dns.

Wonder if you would have a minute to send the snippet of configuration that worked ?

**Comment by dwbxm** [comment]
Hi @rhollins, @JrCs ， I am having the same issue。Is the issue solved？
