### ISSUE TITLE
coredns+etcd and subdomain records

### ISSUE THREAD

**Issue by easokolov** [coredns/coredns#2941]
Hi guys
I try to use coredns with etcd plugin.
When i try to set an A-record for domain like this

    ETCDCTL_API=3 ./etcdctl put /coredns/com/mydomain/x1 '{"host":"1.1.1.1","ttl":60}'

it sets two A-records

    mydomain.com has address 1.1.1.1
    x1.mydomain.com has address 1.1.1.1

Is it correct behavior?

And if i want to set some other record for x2.mydomain.com
    
    ETCDCTL_API=3 ./etcdctl put /coredns/com/mydomain/x2/x1 '{"host":"2.2.2.2","ttl":60}'

it sets some other records

    mydomain.com has address 2.2.2.2
    mydomain.com has address 1.1.1.1
    x2.mydomain.com has address 2.2.2.2
    x1.x2.mydomain.com has address 2.2.2.2

How can i set a record for sub-domain if i don`t want to add it for domain and sub-sub-domain?

CoreDNS-1.5.1
etcd Version: 3.3.13

corefile
---------

    . {
        etcd . {   
            path /coredns
            endpoint http://127.0.0.1:2379
            upstream
        }
        loadbalance round_robin
        log
        errors
    }

logs
-----

    2019-06-28T15:08:53.636+03:00 [INFO] 127.0.0.1:55958 - 1397 "A IN mydomain.com. udp 30 false 512" NOERROR qr,aa,rd 86 0.001742126s
    2019-06-28T15:09:00.023+03:00 [INFO] 127.0.0.1:35086 - 10797 "A IN x1.mydomain.com. udp 33 false 512" NOERROR qr,aa,rd 64 0.001390618s
    2019-06-28T15:09:03.579+03:00 [INFO] 127.0.0.1:54414 - 21633 "A IN x2.mydomain.com. udp 33 false 512" NOERROR qr,aa,rd 64 0.004146104s
    2019-06-28T15:09:08.293+03:00 [INFO] 127.0.0.1:46742 - 17061 "A IN x1.x2.mydomain.com. udp 36 false 512" NOERROR qr,aa,rd 70 0.001658641s

**Comment by miekg** [comment]
I don't think sub domains are supported, might want to call that out in the documentation though

**Comment by easokolov** [comment]
Its a good joke if we talking about DNS-server.

Ok, can I use coredns in any way with 130,000 zones?
Or is it just not my case?

I'm trying coredns + bind zone files, and it starts 2 minutes.
Сourse, its not normal for production.

We are using djbdns right now and it works fine, but we just dont want to rebuild all the database every minute, when something is changed.

**Comment by johnbelamaric** [comment]
etcd plugin is specialized to work like SkyDNS, it's not a general-purpose backend
