### ISSUE TITLE
Add coredns-keygen

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2950]
wip PR #2949 talks about a new utility to create DNSKEY RRs. This is similar to dnssec-keygen from BIND - but simpler in use.

This would mean adding a `coredns-keygen` command. How do people feel about that? 

Not adding anything (in this case) is an option, and just piggy back on dnssec-keygen, but this requires a bind9 install. AFAICT no pure Go, dnssec-keygen exists.

**Comment by stp-ip** [comment]
From experience dnssec-keygen is not easy to use compared to running CoreDNS.
So if it can be made simpler by providing a coredns-keygen, that makes static signing of file based zones easier and in line with CoreDNS, that would be awesome.

**Comment by miekg** [comment]
Cool. Yes I think such a tool make sense and can be made to be simple. For
the time being such tools should live outside of the main repo, we can
always fold them in if we need to.

**Comment by miekg** [comment]
coredns/coredns-utils/coredns-keygen now exist
