### ISSUE TITLE
Caddy's import path has changed

### ISSUE THREAD

**Issue by mholt** [coredns/coredns#2959]
I'm putting out notifications on all Caddy plugins about an unexpectedly-breaking change... sorry. I am not 100% sure it is relevant to this project, but in case it is, here you go:

Caddy's import path (and Go module name) has changed from

```
github.com/mholt/caddy
```

to

```
github.com/caddyserver/caddy
```

Unfortunately, Go modules are not yet mature enough to handle a change like this (see https://golang.org/issue/26904 - "haven't implemented that part yet" but high on priority list for Go _1.14_) which caught me off-guard. Using Go module's `replace` feature didn't act the way I expected, either. Caddy now fails to build with plugins until they update their import paths.

I've hacked a fix into the build server, so downloading Caddy with your plugin from our website should continue working without any changes on your part, for now. However, please take a moment and update your import paths, and do a new deploy on the website, because the workaround involves ignoring module checksums and performing a delicate recursive search-and-replace.

I'm terribly sorry about this. I did a number of tests and dry-runs to ensure the change would be smooth, but apparently some unknown combination of GOPATH, Go modules' lack of maturity, and other hidden variables in the system or environment must have covered up something I missed.

This bash script should make it easy (run it from your project's top-level directory):

```bash
find . -name '*.go' | while read -r f; do
	sed -i.bak 's/\/mholt\/caddy/\/caddyserver\/caddy/g' $f && rm $f.bak
done
```

We use this script in the build server as part of the temporary workaround.

Let me know if you have any questions! Sorry again for the inconvenience.

**Comment by yongtang** [comment]
@mholt Thanks for the head up! I have created a PR #2961 to update caddy to 1.0.1 and the import path changes.

**Comment by yongtang** [comment]
github.com/coredns/ci also needs to be updated. Created a PR https://github.com/coredns/ci/pull/109.

**Comment by miekg** [comment]
Note this applies to everything under the coredns org.
I've updated
* proxy
* examples
* deleted *any*

Further more, none the plugins here https://coredns.io/explugins/ compiles. I've updated
* unbound

Also because of go-modules, tagging a new coredns release makes sense and isn't a biggy. Filed #2964 to track the release.

**Comment by miekg** [comment]
Closing here; further cleanups are expected, but this is the issue for the main repo

**Comment by till** [comment]
Found this issue. I just created a branch from `v1.6.3`. And I am getting the same error.

(I'm editing `plugin.cfg` and running `make` afterwards.)

```
go: github.com/mholt/caddy@v1.0.3: parsing go.mod: unexpected module path "github.com/caddyserver/caddy"
go: error loading module requirements
```

I see how it's fixed. But I am unsure if something else is odd since 1.6.3 was released only a couple days ago?

**Comment by slangens1** [comment]
> Found this issue. I just created a branch from `v1.6.3`. And I am getting the same error.
> 
> (I'm editing `plugin.cfg` and running `make` afterwards.)
> 
> ```
> go: github.com/mholt/caddy@v1.0.3: parsing go.mod: unexpected module path "github.com/caddyserver/caddy"
> go: error loading module requirements
> ```
> 
> I see how it's fixed. But I am unsure if something else is odd since 1.6.3 was released only a couple days ago?

I am seeing the same issue. Any tips or pointers on how to fix?
I am attempting to load pdsql and its not building because of this same unexpected module path error.

**Comment by chrisohaver** [comment]
@slangens1, _pdsql_ still imports the old path.

https://github.com/wenerme/wps/blob/master/coredns/plugin/pdsql/setup.go#L9
https://github.com/wenerme/wps/blob/master/coredns/plugin/pdsql/setup_test.go#L7

If you update that to the new path, it should work.

**Comment by till** [comment]
You have to update all deps yourself. In the plugin you are trying to use.

**Comment by slangens1** [comment]
not ideal but good enough for now.
