### ISSUE TITLE
Socket activation

### ISSUE THREAD

**Issue by artbin** [coredns/coredns#297]
What do you think about systemd socket activation support in coredns? [https://github.com/ArtemKulyabin/coredns/commit/63d829e1768ca6eb8a6ea7894c4b067a41876945](url)

**Comment by miekg** [comment]
caddy has some interesting discussion about it:
- https://github.com/mholt/caddy/pull/777#issuecomment-216007314
- https://github.com/mholt/caddy/issues/778

I do want to follow Caddy here (for a while at least) and not diverge too much from how caddy startsup and how coredns starts up.
I like Matt's comment if this could do be done as a middleware (will be hard probably)

**Comment by fsdrw08** [comment]
but there still no socket activation support in coredns

**Comment by MayCXC** [comment]
@miekg would you be up for an "fd" plugin with no systemd specific behavior? it could work similar to https://github.com/caddyserver/caddy/pull/6573:

```
. {
  fd {$COREDNS_UDP_FD}
}
```

the entire systemd-specific socket activation mechanism is just adding three to an index determined by an environment variable. it is just as easy to add `Environment=COREDNS_UDP_FD=3 COREDNS_DOH_FD=4` to a systemd.service, and then the `socket` plugin can work with `s6-fdholder-store` or any other socket manager instead.
