### ISSUE TITLE
2020 DNS Flagday

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2972]
For the 2020 DNS flag day there are still some remaining bits, see http://dnsflagday.net/2020/#action-authoritative-dns-operators

* the *forward* plugin should set edns buf size to 1220 or 1480 based on outgoing IP familty
* actually truncate on 1220 and 1480 ? We use client edns0 bufsize for this now (likely set to 4096)

**Comment by stp-ip** [comment]
Do we need this for the deprecated proxy plugin?

Or can we see proxy as deprecated?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] 2020 DNS Flag..." ]
>Do we need this for the deprecated proxy plugin?

most likely yes

**Comment by miekg** [comment]
I meant *forward* in the above

**Comment by miekg** [comment]
See https://github.com/dns-violations/dnsflagday/issues/125

I will not implement "set TC" to prevent udp fragmentation, because there is no way of knowing what MTU exists for coredns in all the crazy env it runs. So we will remain compressing *harder* with whatever value that threads comes up with.

**Comment by ykhr53** [comment]
Hi  
I would like to propose a plugin for modifying EDNS0 buffer size.  
*bufsize* plugin allows to overwrite EDNS bufsize. It doesn't need to change *forward* or *cache* plugin.

Here is my idea. https://github.com/ykhr53/coredns/tree/dev-bufsize/plugin/bufsize

Related issues;  
- forward: allow use edns0 https://github.com/coredns/coredns/issues/3386  
- 2020 DNS Flagday https://github.com/coredns/coredns/issues/2972  

It's just an idea came up with and I think it's not enough, much appreciate if you give me more suggestions.
Thanks,

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] 2020 DNS Flag..." ]
>Hi
>I would like to propose a plugin for modifying EDNS0 buffer size.
>*bufsize* plugin allows to overwrite EDNS bufsize. It doesn't need to change *forward* or *cache* plugin.
>
>Here is my idea. https://github.com/ykhr53/coredns/tree/dev-bufsize/plugin/bufsize
>
>Related issues;
>- forward: allow use edns0 https://github.com/coredns/coredns/issues/3386
>- 2020 DNS Flagday https://github.com/coredns/coredns/issues/2972
>
>It's just an idea came up with and I think it's not enough, much appreciate if you give me more suggestions.
>Thanks,

that's a *really* nice idea, thanks for coming up with this. I think this is 
perfectly acceptable as a plugin and fits really well with the general 
architecture of everything being a plugin.

(Being the devils advocate... I can't see any reason why this wouldn't work)

**Comment by ykhr53** [comment]
Thank you! I'm going to write some test scenarios and brush up details for pull request.
Should I create a new issue for this?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] 2020 DNS Flag..." ]
>Thank you! I'm going to write some test scenarios and brush up details for pull request.
>Should I create a new issue for this?

No, I think this one can serve just fine.

**Comment by ykhr53** [comment]
Here is some small scenarios.

# Test
**Environment**  
`go version go1.12.5 linux/amd64`  

**Corefile**  
```
example.org {
    bufsize 512
    file db.example.org
    log
}

. {
    bufsize 512
    forward . 172.31.0.185
    log
}
```

## Case 1: Forward to Recursive Resolver
**Command**  
`$ dig example.com. +bufsize=1500 @localhost`

I took a pcap on Resolver side and confirmed the bufsize of incoming query was set to 512.

## Case 2: RRs return from CoreDNS file plugin
**Command**  
`dig long.example.org. TXT +bufsize=1500 +noall +ans @localhost`

`long.example.org` has a long TXT record which exceeds 512 bytes, so the request should be truncated.  

Here is the result.
```
$ dig long.example.org. TXT +bufsize=1500 +noall +ans @localhost
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.9.4-RedHat-9.9.4-74.amzn2.1.2 <<>> long.example.org. TXT +bufsize=1500 +noall +ans @localhost
;; global options: +cmd
long.example.org.	3600	IN	TXT	"This message will exceed 512 byte." "150AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" "300AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" "450AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" "600AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
```

It looks both work fine.

# Consideration
- Where should this plugin place in `plugin.cfg`  
I set it between *nsid* and *root*, but to be honest I have no idea where the perfect place is.

**Comment by ykhr53** [comment]
As I mentioned on #3386, *bufsize* plugin could be a good solution not only for preparing the DNS Flag Day 2020 but also dealing with IP fragmentation vulnerability.  
I've just written a test, I'll open a PR.

**Comment by miekg** [comment]
bufsize plugin solves this beautifully, closing

**Comment by chantra** [comment]
@miekg and @ykhr53 I just submitted a PR to the flagday website: https://github.com/dns-violations/dnsflagday/pull/148

That being said, I am doing this totally based on documentation and dont have any coredns running that I can play with. If you could check the PR and validate that would be great :)
