### ISSUE TITLE
Reverse plugin still mentioned in various docs

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2978]
https://github.com/coredns/coredns.io/blob/43e5569e18286308259b1b5b92e0916065b36a53/content/manual/plugins-dev.md#fallthrough
https://coredns.io/plugins/reverse/

**Comment by stp-ip** [comment]
For https://coredns.io/plugins/reverse this seems to be a caching issue? As this is run manually on a machine it's hard to fix. 
cc @miekg thoughts?

**Comment by miekg** [comment]
Yes that still manual. Just need to remove the file from the coredns.io repo

**Comment by stp-ip** [comment]
As far as the coredns.io repo goes. The reverse README is already gone, but it still shows on the published page.

**Comment by miekg** [comment]
Push is also manual \o/

**Comment by stp-ip** [comment]
Do we want to move this to Netlify with an autobuild from coredns.io?

**Comment by miekg** [comment]
Don't have time for that migration

**Comment by stp-ip** [comment]
Would volunteer to coordinate/migrate.
Just need perms on the coredns.io repo and would coordinate with CNCF, netlify and ping you, when we can do a DNS switch.

**Comment by miekg** [comment]
That still takes (my) time

**Comment by ammarzuberi** [comment]
The page at  https://coredns.io/plugins/reverse/ still exists, by the way.
