### ISSUE TITLE
Reduce log output for zone transfers

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2979]
Currently file and auto log zone transfers even without `log` being configured, which feels excessive.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Reduce log output..." ]
>Currently file and auto log zone transfers even without `log` being configured, which feels excessive.

log is a bit of misnomer as it only affects the query log.

**Comment by stp-ip** [comment]
One could see the transfer as a query so :)
But I see, what you mean. Will think through how that might work otherwise.

**Comment by miekg** [comment]
I'm not against reducing logs here, but a minimal "I did something" should remain IMO. Please submit a PR.

**Comment by miekg** [comment]
anything to follow up here? I'm contemplating more logging here, as the current setup doesn't allow me to debug something I see on my servers.

**Comment by stp-ip** [comment]
The main issue is probably not the log amount, but the non optionality of
it. It is always there so having debug level (as you are suggesting) amount
without an off switch feels noisy.

**Comment by miekg** [comment]
this has been reduced in the past releases ; is this still an issue?
