### ISSUE TITLE
How to add preStop hook for coredns

### ISSUE THREAD

**Issue by iammuho** [coredns/coredns#2984]
Hello,

When I want to delete a CoreDns pod, kubernetes send a SIGTERM immediately and that causes to get 5xx for on-fly requests. I've tried to add some lifecycle hooks but I think because of `scratch` docker image, I couldn't find any executable under /bin, etc.

`lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 20`

Error:

` Warning  FailedPreStopHook  1s    kubelet, ip-10-9-4-165.eu-central-1.compute.internal  Exec lifecycle hook ([/bin/sh -c sleep 20]) for Container "coredns" in Pod "coredns-5b6f8b8757-m4l4b_kube-system(ba8e8ff2-a165-11e9-b36d-0ab3631e67fe)" failed - error: command '/bin/sh -c sleep 20' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"exec: \\\"/bin/sh\\\": stat /bin/sh: no such file or directory\": unknown\r\n"`

Is there any other docker image or can we solve this problem with a workaround?

**Comment by miekg** [comment]
The docker image is from scratch there is nothing you can run (out of the box)

/label: question
/label: kubernetes

**Comment by johnbelamaric** [comment]
Try setting the lameduck timeout in the health plugin:

https://github.com/coredns/coredns/tree/master/plugin/health

Not sure this works though since we moved to using the *ready* plugin.

**Comment by iammuho** [comment]
Is it possible to create my own docker image? If yes, is there any documentation. I've edited the Dockerfile and built but when I started my pod with my new image, I'm getting a crashloopback.

I've removed the scratch stage and used debian.

```
FROM debian:stable-slim

RUN apt-get update && apt-get -uy upgrade
RUN apt-get -y install ca-certificates && update-ca-certificates

ADD coredns /coredns

EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]
```

**Comment by johnbelamaric** [comment]
Sure of course, just like anything else you can roll your own image. I would expect something like what you have to work, I don't see anything obviously wrong.

**Comment by iammuho** [comment]
When I'm building the docker image, it's built successfully. But when I tried to run it, it throws me below error

```
docker run --name coredns -it geass/coredns:1.0
standard_init_linux.go:190: exec user process caused "exec format error"
```

My docker file:

```
FROM debian:stable-slim

RUN apt-get update && apt-get -uy upgrade
RUN apt-get -y install ca-certificates && update-ca-certificates

ADD coredns /coredns

EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]
```

what might be the problem is?

**Comment by iammuho** [comment]
Okay I've forgot to compile coredns for linux but for mac. Now it's working.

Thank you guys!
