### ISSUE TITLE
Measure Kubernetes DNS programming SLI

### ISSUE THREAD

**Issue by oxddr** [coredns/coredns#2985]
Let's restart discussion about measuring [DNS programming latency SLI](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/dns_programming_latency.md) in CoreDNS. It was started in https://github.com/coredns/coredns/pull/2690, but I'm taking this over from @mm4tt now. 

Before coming to you with any specific design, I wanted to ask you about your input. 
Miek, you seemed to be quite opinionated about how to this should (or should not) be implemented. If you have anything specific in mind, I'd be happy to hear that. 

At this point, on our end we don't have any particular design or implementation so we'd open to all ideas. Perhaps we'd rather avoid using probers if possible. 

Please let me know, if there is additional info I can provide you with. 

/label: kubernetes

cc: @mm4tt @wojtek-t

**Comment by johnbelamaric** [comment]
I'd be happy to hash through this with you and I happen to be sitting in the same room with you right now :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Measure Kubernete..." ]
>Let's restart discussion about measuring [DNS programming latency SLI](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/dns_programming_latency.md) in CoreDNS. It was started in https://github.com/coredns/coredns/pull/2690, but I'm taking this over from @mm4tt now.
>
>Before coming to you with any specific design, I wanted to ask you about your input.
>Miek, you seemed to be quite opinionated about how to this should (or should not) be implemented. If you have anything specific in mind, I'd be happy to hear that.
>
>At this point, on our end we don't have any particular design or implementation so we'd open to all ideas. Perhaps we'd rather avoid using probers if possible.
>
>Please let me know, if there is additional info I can provide you with.

Talking it through with John make sense. As with all new functionally in 
CoreDNS: can it be done in another plugin?

**Comment by oxddr** [comment]
Perfect, I'll take this discussion offline with John for now and come back with its results.

**Comment by miekg** [comment]
this has been added.
