### ISSUE TITLE
[Question] Including the response message in the plugin interface

### ISSUE THREAD

**Issue by tomsanbear** [coredns/coredns#2996]
This is more of an implementation question/future implementation question regarding the plugin interface. The ServeDNS method currently cascades down the writer, and the the DNS request that came in. I have a use case where I'd like to access the information from the response that the forward plugin (or any other plugin potentially) generates. 

There are two ways I can see approaching this:
* Augment the writer to be able to access the last message that was sent back from the writer
* Directly/Indirectly pass the response object through the plugins (there are a couple ways this can be done: 
    * add to method signature
    * pass the 'state' via a request.Request object [example](https://github.com/tomsanbear/coredns/blob/dns-response/request/request.go)

I'm wondering if you can see any glaring issues that might come up with these approaches, or if you have ideas on alternative approaches.

For reference, the main use case I'm looking at here is to be able to log data from the upstream responses, since as far as I can tell we can only pull from the request.

**Comment by chrisohaver** [comment]
> I have a use case where I'd like to access the information from the response that the forward plugin (or any other plugin potentially) generates.

Generally the way I have handled this kind of thing is to create a plugin calls the next plugin in the chain with a non-writer (`/plugin/pkg/nonwriter` a response writer that doesn't send a response to the client).  When the call to next plugin returns, the non-writer contains the response but the response has not been written yet.  The response can be examined/modified and then written to the client when ready.

**Comment by chrisohaver** [comment]
For a read only approach, there is `Recorder` (`/plugin/pkg/dnstest/recorder.go`), which is a writer that copies the last written message to the client into an accessible property.  This sits in package intended to be used in tests ... but for better or for worse, I do see it being used in non test contexts.

**Comment by tomsanbear** [comment]
Thanks for the options!

The recorder seems like the most promising option (I want to send the response back to decrease DNS latency, and then do things with the response), agreed about the whole 'using a test fixture' in real plugin code, maybe if it's getting use that can just be a supported option for plugins to use in the future? 

I understand that the response object was likely omitted to keep the standard writer lean from a memory standpoint.
