### ISSUE TITLE
plugin/forward: Add new latency weighted policy

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#2998]
With various upstreams configured and the network not always behaving as one has planned, it would be interesting to have a latency weighted policy.

We could send an incoming request in parallel every x timeframe and use the top performing upstream until the next test request.

Just a thought and wanted to write it down already.
Might add additional thoughts going forward.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] [forward] Add new..." ]
>With various upstreams configured and the network not always behaving as one has planned, it would be interesting to have a latency weighted policy.
>
>We could send an incoming request in parallel every x timeframe and use the top performing upstream until the next test request.
>
>Just a thought and wanted to write it down already.
>Might add additional thoughts going forward.

I think other (recursive) server call this DNS RTT *banding*.

**Comment by stp-ip** [comment]
Thanks, I think that was the keyword I was missing!

**Comment by erbesharat** [comment]
If it's ok I want to try to work on this issue :)

**Comment by stp-ip** [comment]
Any specific prerequisites for a PR @miekg ?

Some thoughts:
In the bootstrap phase we could either wait for the first query and then send it upstream in parallel, answer with the fastest response and note down response latency to be used to determine the fastest upstream server to be used until the next latency "test".
Alternatively we could do prefetching and contact upstream nameservers with a predefined query and note down the response latency as well. This would enable more continuous and standardizes testing, but might be different due to caches being warm in upstreams, but it might be easier to debug as it's always just one and the same query and could be tweaked via its TTL.

For the TCP/TLS case we could do a follow on query to remove any problems with hot/cold connections.
This could be alleviated by making upstream connections be pre warmed in all cases aka hold a standing connection.

Additionally if the currently top performing upstream doesn't respond or responds with worse latency than the second in the performance list, we will query the next one in line and initiate an additional latency test outside the usual interval.

Retesting will be done either on upstream failures, latency drop of top performing server or on the next interval.

Config suggestion:
```
forward FROM TO... {
    policy latency
    latency_interval 5m
    latency_query ZONE [TYPE] # fallback: ". IN NS" similar to health check
}
```

**Comment by miekg** [comment]
Some quick notes. Maybe banding can be applied for other policies as well,
otherwise just a extra latency policy would suffice as a config option.
Impl:  Have 3 buckets: slow, medium and fast, and have some relative weight
for them. Fill the buckets during querying and move nameservers around in
the buckets as required.

**Comment by stp-ip** [comment]
Starting with a separate policy makes it easier and we also don't mess with anything already deployed.
Also it feels like sequential and round robin are already quite defined and adding in latency weighting seems problematic.

On the implementation idea. Why use buckets? This would lead to better query distribution, but with the downside of less performance, which "latency" probably should optimize for.
For availability we can always do a fallback to the second best performing server and triggering a retest.
I do see value in having a "latency_random" policy, where 1/3 of the fastest upstreams are randomly chosen. But would say this could be added afterwards, if really necessary.

Not sure I get the full picture on filling up the buckets. Do you mean filling them up with latency data sequentially with user queries? This would mean that a small part of user queries would be send to slow servers pushing tail latency up instead of down.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>Not sure I get the full picture on filling up the buckets. Do you mean filling them up with latency data sequentially with user queries? This would mean that a small part of user queries would be send to slow servers pushing tail latency up instead of down.

yes, we don't need to synthesize anything here. Doing a minimal amount of 
buckets prevents starvation of the slower upstream. Also with the connection 
pipeling you need to be careful not to attribute slowness to the connection 
setup. TLS will kill and dominate any connection setup, so I'm not sure what you 
want to measure for those connection.

If you want to add (manual) weights you're coming close to loadbalancing/loadreporting 
which needs more infrastructure than manual tweaking some values in a config 
file.

**Comment by stp-ip** [comment]
> yes, we don't need to synthesize anything here. Doing a minimal amount of
> buckets prevents starvation of the slower upstream. Also with the connection
> pipeling you need to be careful not to attribute slowness to the connection
> setup. TLS will kill and dominate any connection setup, so I'm not sure what you
> want to measure for those connection.

I feel like with the correct rechecking interval and rechecking on failure and/or latency performance drops of say x2/x3 latency starving the slower upstreams makes sense as this would reduce pushing our testing logic into the latency of real users (even if just a tiny portion).

TCP is definitely something that is problematic. The idea I mentioned was that on TCP/TLS connections we force a recheck after the first check comes back or later add connection pre warming so we always have a standing connection even on the first connection.

Sidenote: One could say, that this could lead to problems with low query amounts as the prewarmed connection latency is used instead of the "real world" cold connection. But that's an edge case that could be prevented by configuring the check interval below the connection timeout interval.

> 
> If you want to add (manual) weights you're coming close to loadbalancing/loadreporting
> which needs more infrastructure than manual tweaking some values in a config
> file.

The config values are more about the checking interval and type than anything else. Not sure where you would see us add manual weights in the suggestion.

Main points for immediate implementation in my view:
* add `latency` policy
* single best performing upstream will be used
* configurable recheck interval
* additional recheck for TCP/TLS to prevent connection related latency fudges
* additional recheck for failure or latency drop
* check upstream with default `. IN NS` query
* configurable query ZONE and TYPE

One additional point would be cache impact within upstreams.
This could be prevented by setting the record being used to a specific low TTL zone and type.
The

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>> setup. TLS will kill and dominate any connection setup, so I'm not sure what you
>> want to measure for those connection.
>
>I feel like with the correct rechecking interval and rechecking on failure and/or latency performance drops of say x2/x3 latency starving the slower upstreams makes sense as this would reduce pushing our testing logic into the latency of real users (even if just a tiny portion).
>
>TCP is definitely something that is problematic. The idea I mentioned was that on TCP/TLS connections we force a recheck after the first check comes back or later add connection pre warming so we always have a standing connection even on the first connection.

Another problem, if forwarding, is that the upstream is doing a recursive 
resolve, this can take second(s). Measuring that make no sense.

IOW: if you're not talking to an authoritative you need to *very* careful what 
you're measuring. In fact I think you can only measure this properly by doing 
synthetic queries that you *know* will not be recursively resolved (or handled 
the same in all upstreams).

>Main points for immediate implementation in my view:
>* add `latency` policy

yes

>* single best performing upstream will be used

no, needs to be weighted to spread the load

>* configurable recheck interval

should not be a user visible knob

>* additional recheck for TCP/TLS to prevent connection related latency fudges
>* additional recheck for failure or latency drop
>* check upstream with default `. IN NS` query
>* configurable query ZONE and TYPE

all no. I think you can only do a `. IN NS` query. You also need to know if 
you're dealing with a new conn or a cached one and factor that in. I.e. a server 
can be fast, but really slow in setting up a new connection.

/Miek

--
Miek Gieben

**Comment by denis-tingaikin** [comment]
@stp-ip  Can we solve this problem with https://github.com/coredns/coredns/pull/3652?

**Comment by chrisohaver** [comment]
> Can we solve this problem with #3652?

Fanout sends replicas of every incoming query to all upstreams dns in parallel, whereas this plugin aims to only send probe queries in parallel on an interval (asynchronous to client queries).  
IOW, the latency weighted policy proposed here could lower the load on a underpowered/overworked/slow upstream dns, whereas fanout would send it the full undivided load.

**Comment by stp-ip** [comment]
In agreement with Chris #3652 would at least need a back-off mechanism for the slowest queries I think.

The fanout idea seems tailored to a specific environment where producing multiples of the traffic to reduce latency is ok as lower latency is primary. The specific idea here does try to choose the primary upstream with the best latency using only a small amount of additional queries. Basically compromising perfect latency on each query with general overhead on each query (including upstream overhead).

**Comment by stp-ip** [comment]
So if we go with #3652 to also solve this specific issue, the latency focused option shouldn't be default in my mind. Basically the back-off mechanism similar to the latency weighted upstream choosing mentioned here should be default and the all out full low latency option as currently implemented in fanout should be an option with a documented warning that this leads to queries*x the upstreams configured resources as well as total queries upstream.

**Comment by denis-tingaikin** [comment]
@stp-ip thanks for the clarification. Yes, fanout idea it is just sent replicas of every incoming query to all upstreams dns in parallel and return the **first non-negative** result.

I think the latency weighted policy is good improvements for forward plugin but it does not solve the problem with negative responses.

Let's imagine the next case:

We have the next proxies: A, B, C.
Only proxy C knows the host 'example.com.'.
Proxy B has best latency but it doesn't know the host 'example.com.'.
In this case, forward plugin even with latency weighted policy will return a negative answer for the query 'example.com.'.
NOTE: This case is covered by fanout plugin.

**Comment by stp-ip** [comment]
An upstream not knowing a host feels like a problematic setup. Either it is a resolver and should get the actual answer or it is authoritative and should already know the answer.

Having sometimes correct answers seems like asking for a problem. I do understand why you want to have the fanout plugin in this case, but that's from my DNS understanding a problematic setup and should be fixed by the actual upstreams.

**Comment by denis-tingaikin** [comment]
@stp-ip Interesting...

Let's take a look at the following example:

We have 3 dns servers: A, B, C.

### Server A
Corefile:
```
    .:53 {
      hosts {
            8.8.8.8 example.org //NOTE: you can use another IP
      }
      reload 5s //means that hosts could be updated in runtime
    }
```
IP: 10.244.2.3

### Server B
Corefile:
```
    .:53 {
      hosts {
            8.8.8.8 google.dns
      }
      reload 5s //means that hosts could be updated in runtime
    }
```
IP: 10.244.1.2

### Server C
Corefile: 
```
    .:53 {
      forward . 10.244.2.3 10.244.1.2 
    }
```

### Testing
I've tested this via k8s. 
My steps:
1. Deploy server A, B, C
2. Deploy alpine
3. Set server C as default nameserver for alpine from step2 (just change resolve conf file)
4. Try ping `google.dns` from alpine
5. Try ping `example.org` from alpine

Actual: ping: bad address 'example.org'
Expected: 
```
PING example.org (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=36 time=104.684 ms
64 bytes from 8.8.8.8: seq=1 ttl=36 time=142.524 ms
64 bytes from 8.8.8.8: seq=2 ttl=36 time=103.850 ms
64 bytes from 8.8.8.8: seq=3 ttl=36 time=143.887 ms
64 bytes from 8.8.8.8: seq=4 ttl=36 time=103.303 ms
64 bytes from 8.8.8.8: seq=5 ttl=36 time=154.603 ms
```

The main question here: How can I make Actual = Expected using forward plugin?
NOTE: host list for servers A,B can be updated in runtime.
