### ISSUE TITLE
How can I deploy CoreDNS without RBAC?

### ISSUE THREAD

**Issue by airdive** [coredns/coredns#3023]
I have delete  ServiceAccount, ClusterRole , ClusterRoleBinding in coredns.yaml.sed .

**Comment by stp-ip** [comment]
RBAC is related to Kubernetes and has nothing specific to do with CoreDNS.

RBAC is used when Kubernetes deploys CoreDNS as a component, but CoreDNS itself doesn't have any notion about RBAC so you can just get the binary and run it.

Overall RBAC is usually required by the cluster itself so removing various RBAC components as you mentioned doesn't remove the need for RBAC. Some cluster have the option to disable this, but this is not recommended.

Closing as not relevant for CoreDNS itself. Please open an issue within Kubernetes or Kubernetes/dns, if you feel this is the better place.

**Comment by chrisohaver** [comment]
@airdive, Non-RBAC deployments are briefly covered in the deployment readme ... https://github.com/coredns/deployment/tree/master/kubernetes

>For non-RBAC deployments, you'll need to edit the resulting yaml before applying it:
> * Remove the line serviceAccountName: coredns from the Deployment section.
> * Remove the ServiceAccount, ClusterRole, and ClusterRoleBinding sections.
