### ISSUE TITLE
multiple dns names and use of origin in server block

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3026]
While write the *sign* plugin it ran into the following. With this Corefile something unexpected is happening:
~~~
miek.nl miek.org {
    file plugin/sign/testdata/db.miek.nl.signed miek.nl {
        reload 5s
    }
    file plugin/sign/testdata/db.miek.org.signed miek.org {
        reload 5s
    }

    sign plugin/sign/testdata/db.miek.nl {
        key file plugin/sign/testdata/Kmiek.nl.+013+59725
        directory plugin/sign/testdata
    }
}
~~~
If you start CoreDNS you'll get:

~~~
plugin/file: Successfully reloaded zone "miek.nl." in "plugin/sign/testdata/db.miek.nl.signed" with serial 1563737941
plugin/file: Successfully reloaded zone "miek.org." in "plugin/sign/testdata/db.miek.org.signed" with serial 1563737941
plugin/file: Successfully reloaded zone "miek.nl." in "plugin/sign/testdata/db.miek.nl.signed" with serial 1563737941
plugin/file: Successfully reloaded zone "miek.org." in "plugin/sign/testdata/db.miek.org.signed" with serial 1563737941
~~~
4 times, because the zone stanza is parsed twice, once for miek.nl and once for miek.org. This doesn't do what you expect.

This can be checked for what stanza you're actually parsing, this information *is* available in the `caddy.Controller`, but it might be worth adding a simple function for this to make sure you're setting up for the zone you're called for instead of all of them.

**Comment by johnbelamaric** [comment]
Wow, that's interesting. This setup calls are surprising sometimes. https://github.com/coredns/learning-coredns/tree/master/plugins/setupcheck helps see how it works, but I didn't check this particular case.

I wonder if we want to start having some Corefile debugging/introspection tools to help validate them for stuff like this.

**Comment by miekg** [comment]
yep. Well #3039 for your viewing pleasure :-) I expect a bunch of test to fail though

**Comment by chrisohaver** [comment]
I recall francois bringing this up a few times.  This has special significance for plugins that have a big memory footprint. 

e.g. explained here: https://github.com/coredns/deployment/issues/153#issuecomment-483706256

**Comment by miekg** [comment]
The following plugins needs this treatment as well:
auto
cache
dnssec
etcd
federation
hosts
k8s_external
kubernetes
metadata
route53 - maybe?
secondary
template    
auto
cache
dnssec
etcd
federation
hosts
k8s_external
kubernetes
metadata
route53 - maybe?
secondary
template

**Comment by miekg** [comment]
The lesson is that you need to use multiple server blocks, putting everything under root is a bad idea. 

I see we still haven't learned that lesson for [kubernetes](https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed). Oh well

**Comment by chrisohaver** [comment]
> I see we still haven't learned that lesson for kubernetes. Oh well

Confused. Our current mode of deployment doesn't suffer from this issue, because everything is in one server block that serves one domain.

How would you advise us to deploy kubernetes instead?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] multiple dns ..." ]
>> I see we still haven't learned that lesson for kubernetes. Oh well
>
>Confused. Our current mode of deployment doesn't suffer from this issue, because everything is in one server block that serves one domain.
>
>How would you advise us to deploy kubernetes instead?

have had multiple issues open on these. I'm not going re-iterate them

**Comment by chrisohaver** [comment]
> I'm not going re-iterate them

The suggestions you have made in the past, that I recall, are subject to this plugin duplication issue, wherein we would end up initializing a separate API connection and cache/store for each zone (and reverse zone) in the server block.  This would, according to [this comment](https://github.com/coredns/deployment/issues/153#issuecomment-483706256), cause CoreDNS to take up ~ 3X more memory than it does currently (in a large scale cluster), which would cause failures in k8s e2e scalability tests.

**Comment by miekg** [comment]
I hope to get #3039 merged soon and then do the other plugins, this should be fine from a backwards compat and can just be pushed through as it's a bugfix
