### ISSUE TITLE
Warn if multiple middleware are reponsible for the same set of names

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#303]
The following Corefile does not do what you want:

```
.:2053 {                                                                           
  proxy . 8.8.8.8:53                                                               
  file example.com                                                                 
  errors stdout                                                                    
  log stdout                                                                       
} 
```

Everything ends up in the `example.com` file middleware (because of ordering), now that file line is better written as: `file example.com example.com`, which means only example.com queries are redirected to the file middleware and the rest is proxied as they should be.

The question now becomes what does a user expect? The example.com zonefile sets `$ORIGIN` to example.com. Should we then assume we're only authoritative for that?
Should we check for the root zone? And only then take the previous action? I.e. zone=='.' and $ORIGIN is set to something different? Or make this more generic so that it will _just_ work?

Maybe it's better written as two sections?

```
.:2053 {
   proxy . 8.8.8.8:53
   errors stdout
   log stdout
}

example.com:2053 {
  file db.example.com   # use db. to make it clear this is a file and not a zone.
   errors stdout
   log stdout
}
```

**Comment by stp-ip** [comment]
Another example:

```
.:2053 {
  proxy . 8.8.8.8:53 # proxy all non served zones
  file single/zone2.db zone2 # reads in single zone file + specify which zone to serve
  file single/zone3.db #  reads in single zone file + serve all zones
  file zones.db zone4 zone5 #  reads in zone db file + specify which zone to serve
  file zones.db { #  reads in zone db file + serve all zones
    loadbalance # loadbalance A and AAAA records
    transfer to * # enable public transfers
    transfer to 10.240.1.1 # enable transfers to a specific IP
  }
  rewrite zone1 zone2 # duplicates records for to another zone
  errors stdout
  log stdout
}
```

Hope this makes sense. That's how I understood the docs. As you said it currently does not work due to everything ending up in the file directive.

Having too sections would get really annoying, if you have more zones so.

**Comment by miekg** [comment]
yes, this make sense, though your example is slightly longer.
I see a potential problem here as outlined above, but I also like things to be explicit.  But this needs some kind solution.

**Comment by miekg** [comment]
Wrote blog about it: https://blog.coredns.io/2016/10/13/query-routing/

CoreDNS should at least print a warning (or fail) when this happens.

Not sure if a clean impl. (or how this can be done) though.

**Comment by stp-ip** [comment]
Thanks for writing a blogpost about the issue. After reading, I do my best and see, if I see some improvement suggestions in my mind. Might be next week so.

**Comment by johnbelamaric** [comment]
One thing I am thinking about is that in some cases we may want this. For example, if we change the ordering of kubernetes and etcd so etcd is after k8s, then we could have k8s pass any NXDOMAINs down to etcd instead of returning NXDOMAIN. This would essentially allow the combo of k8s + etcd to do k8s service discovery with dynamic registration (via etcd).

Maybe a separate directive could configure this?

```
pass-through nxdomain (or other rcodes?)
```

or something. It could be middleware specific but maybe it belongs in the general "backend" middleware.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] Warn if multipl..." ]
>One thing I am thinking about is that in some cases we may want this. For example, if we change the ordering of kubernetes and etcd so etcd is after k8s, then we could have k8s pass any NXDOMAINs down to etcd instead of returning NXDOMAIN. This would essentially allow the combo of k8s + etcd to do k8s service discovery with dynamic registration (via etcd).
>
>Maybe a separate directive could configure this?
>
>```
>pass-through nxdomain (or other rcodes?)
>```
>
>or something. It could be middleware specific but maybe it belongs in the general "backend" middleware.

I'm not sure... I've gotten requests that do this for proxy, first go to etcd
and then to the proxy for the same name. This can lead to nasty dns bugs that
are hard to debug.

So again. I see some merit, but I am concerned about the implications, esp for
DNSSEC and debugability.

**Comment by miekg** [comment]
We have fallthrough now. Closing as this is sort of fixed.
