### ISSUE TITLE
plugin/auto Non existent responses return SERVFAIL instead of NXDOMAIN

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#3033]
This works and returns NXDOMAIN:
```
.:5053 {
  file /zones/example.com example.com
  forward . 8.8.8.8
}
```

This will result in a SERVFAIL:
```
.:5053 {
  auto {
    directory /zones/ (.*) {1}
  }
  forward . 8.8.8.8
}
```

**Comment by miekg** [comment]
>This works and returns NXDOMAIN:
>```
>.:5053 {
>  file /zones/example.com
>  forward . 8.8.8.8
>}
>```

I wouldn't call it working because file is loading example.com with an origin of 
`.`  This looks WAI to me.

>This will result in a SERVFAIL:
>```
>.:5053 {
>  auto {
>    directory /zones/ {.*} {1}
>  }
>  forward . 8.8.8.8
>}
>```

yes, because presumably nothing is detected on disk, so SERVFAIL, also looks 
WAI, to me?

/Miek

--
Miek Gieben

**Comment by stp-ip** [comment]
With a query such as `dig example.net` the first config (using file) will use forward to resolve it or give back a NXDOMAIN, if it can't find it upstream.
The second config (using auto) will SERVFAIL and never jump into forward.
This feels wrong as it should just detect the zone and push anything else to forward.

1:
```
.:5053 {
  file /zones/example.com example.com
  forward . 8.8.8.8
}
```
2:
```
.:5053 {
  auto {
    directory /zones/ (.*) {1}
  }
  forward . 8.8.8.8
}
```

Both only have the single zone file for example.com on disk.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/auto N..." ]
>With a query such as `dig example.net` the first config (using file) will use forward to resolve it or give back a NXDOMAIN, if it can't find it upstream.
>The second config (using auto) will SERVFAIL and never jump into forward.
>This feels wrong as it should just detect the zone and push anything else to forward.

you made file authoritative for example.com, everything else is handled for 
forward.

you made auto authoritative for ".", there is nothing left to forward.

this WAI. Use separate server block that specify for specific origins, don't 
assume "." will suffice

>
>1:
>```
>.:5053 {
>  file /zones/example.com example.com
>  forward . 8.8.8.8
>}
>```
>2:
>```
>.:5053 {
>  auto {
>    directory /zones/ (.*) {1}
>  }
>  forward . 8.8.8.8
>}
>```
>
>Both only have the single zone file for example.com on disk.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/coredns/coredns/issues/3033#issuecomment-514518730
/Miek

--
Miek Gieben

**Comment by stp-ip** [comment]
Shouldn't auto be authoritative just for the origins it gets from the regex? In this case it should be `example.com` aka all filenames in the given directory used as origin/zone. So it shouldn't default to `.`.

**Comment by miekg** [comment]
I don't remember exactly how *auto* does this

**Comment by miekg** [comment]
It does in *auto*, but the configuration is leading in if a request even gets routed to the plugin in the first place.
From a technical standpoint that is WAI, we could def. (somewhere) try to make this more clear.

**Comment by SteelCrow** [comment]
This example is not working too:

```
.:53 {
  auto {
    directory /etc/coredns/zones 
  }
  forward . /etc/resolv.conf
}
```

As said in the plugin description default regexp `db\.(.*) {1}` and `ZONES zones it should be authoritative for.  If empty, the zones from the configuration block are used.`

But if I delete "auto" block, all will be working as expect.

So for me it's seems kind of strange.

**Comment by imacks** [comment]
I bumped into this issue today. I have many zone files that are created dynamically, so its not possible to state `auto zone1 zone2` beforehand. Besides, with many domains its going to be a very long Corefile. I was expecting auto to skip to the next plugin if the domain queried is not in the zone files. Is this a bug?

**Comment by imacks** [comment]
I made some changes to solve my issue: [see here](https://github.com/imacks/coredns/blob/83e43697268a5e349d2a0b2ad8cf57180d29cf22/plugin/auto/auto.go#L53).

**Comment by miekg** [comment]
@imacks that makes actually sense and mimics other plugins. Can you submit that as a PR? thanks!
