### ISSUE TITLE
Removing debug plugin does not turn off debug logging

### ISSUE THREAD

**Issue by maguro** [coredns/coredns#3035]
When the debug plugin is configured and then removed, the reloaded configuration does not turn off debug logging.  

One solution is to add a method, `log.D.Clear()`, that `dnsserver.NewServer()` can call before iterating through the configurations.  This seems like a good stop gap measure.

This is not ideal since any debug shutdown messages from the previous incarnation won't get printed.  A better solution may be to have a logger, specific to that plugin's incarnation, passed in during setup.  Old expiring plugins would still be able to print their debug information as they are shutting down while the next incarnations would rely on the reloaded configuration for their loggers.  An added benefit would be that if a plugin does not completely shutdown, it would still print debug logging.

**Comment by maguro** [comment]
I have a PR in the works.

**Comment by miekg** [comment]
would be good to have this ablity (in 1.7.0)
