### ISSUE TITLE
It would be nice to have a trace log level

### ISSUE THREAD

**Issue by maguro** [coredns/coredns#3036]
It would be nice to have a trace log level.  There could be a `trace` plugin to turn it on.  If #3035 is employed, then we could have something like:

    trace {
        plugins gcpdns dnssec
    }

**Comment by johnbelamaric** [comment]
You'll need a different name, `trace` is already there for distributed tracing: https://github.com/coredns/coredns/tree/master/plugin/trace

**Comment by miekg** [comment]
extending the debug plugin? https://coredns.io/plugins/debug/ Or, at least, at more Debug printfs

**Comment by maguro** [comment]
Maybe add a `plugins` block that not only controls log levels for the listed plugins but also provides a way for those plugins to discover if they should go into *debug* mode.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] It would be n..." ]
>Maybe add a `plugins` block that not only controls log levels for the listed plugins but also provides a way for those plugins to discover if they should go into *debug* mode.

that's incompatible with how the Corefile works. I rather have what we have now: 
plugins declare debug output and this get's toggled with the debug plugin.

**Comment by maguro** [comment]
I agree,  backward compatibility with how the `Corefile` currently works is critical.

If the proposed `plugins` block is not declared in the `Corefile` then the default behavior can be "all plugins", achieving complete backward compatibility.  If one, however, wishes to focus on a specific plugin, then the `plugins` block would be quite helpful to minimize the din of debug log messages from the entire chorus of plugins.  This, iiuc, speaks to your concern:

> that's incompatible with how the Corefile works. I rather have what we have now:
> plugins declare debug output and this get's toggled with the debug plugin.

With that said, there are situations where it would be helpful for a plugin to perform some work related to debugging _in addition_ to the simple debug logging that is currently supported.  A plugin writer wishing to support debug behavior can inspect the `Debug` flag in the config; this works out of the box today.  However, it would not be ideal to throw _all_ plugins that participate in the pattern when one is trying to debug a _specific_ plugin instance.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] It would be n..." ]
>With that said, there are situations where it would be helpful for a plugin to perform some work related to debugging _in addition_ to the simple debug logging that is currently supported.  A plugin writer wishing to support debug behavior can inspect the `Debug` flag in the config; this works out of the box today.  However, it would not be ideal to throw _all_ plugins that participate in the pattern when one is trying to debug a _specific_ plugin instance.

that's the hammer you now have. Filtering out plugin info can be done externally 
with grep (or whatever you have for a log pipeline)

**Comment by maguro** [comment]
Wouldn't I have to stop the server and fire up a new piped command with the appropriate patterns?  Seems a bit `awk`ward.  :)

It also doesn't address plugin behavior.

**Comment by miekg** [comment]
giving each plugin a `debug` clutters everything and doesn't solve anything that can be solved with `grep`
