### ISSUE TITLE
plugin/cache: Edge case on prefetch

### ISSUE THREAD

**Issue by erbesharat** [coredns/coredns#3037]
When we use cache with `prefetch 1 24h 25%` config, and then do one request of a record with a ttl of 30, it wouldn't get prefetched. It only gets prefetched if it is continually being requested.

``Percentage: 25, origTTL: 30, ttl: 29, threshold: 8``

For example in this case, after multiplying percentage with `origTTL`, it results in an `8` threshold which is lower than ttl so it wouldn't get prefetched because of this condition:
https://github.com/coredns/coredns/blob/f9bdd382ddf911c88b33d2bbd8f8aa9be2885a39/plugin/cache/handler.go#L40

**Comment by miekg** [comment]
you have a PR in mind we can merge?
