### ISSUE TITLE
Remove federation plugin

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3041]
Kubernetes DNS federation has failed, and the federation plugin serve no useful services. I propose we move it to coredns/federation and out of the main tree

**Comment by chrisohaver** [comment]
Sounds fair.  Following the deprecation policy, I propose we announce it as "deprecated" in the next release (1.6.0 i think). 
Then in a release after that make it a no-op, remove the coredns/ci tests, and move federation out to an external plugin.
Followed by complete removal of the no-op plugin in a release after that.

Regarding the Kubernetes project - we'll declare it deprecated there too in the next release (assuming we deploy 1.6.0).  If there is concern in the K8s dev community about nooping the plugin when it comes to that time, we can build coredns with the external plugin and deploy that image to the gcr.io image repo if necessary.

**Comment by sharmaansh21** [comment]
I will send the PR :bowtie:

**Comment by chrisohaver** [comment]
> I will send the PR :bowtie:

For which parts? (multiple PRs and multiple repositories involved here)

**Comment by sharmaansh21** [comment]
coredns/coredns
coredns/ci

@chrisohaver  where else if you can please point me, I am more than happy to look into it.

**Comment by chrisohaver** [comment]
Cool, another step would be moving the federation plugin to coredns/federation, and preparing it as an external plugin.

**Comment by sharmaansh21** [comment]
@chrisohaver Sorry for the late reply I was on holidays, by external plugin you mean something like this https://github.com/coredns/proxy

**Comment by yongtang** [comment]
Added a PR #3139.

**Comment by miekg** [comment]
that pr was merged.
