### ISSUE TITLE
How to configure internal dns servers with external dns servers 

### ISSUE THREAD

**Issue by avmgithub** [coredns/coredns#3043]
I have the following corefile below.  Please have a look at the 
forward line.

What I want to do is be able to resolve internal server names by using
2 internal dns servers.  And if we want to resolve an external name
like google.com , it will use 8.8.8.8.

But the result of this config is an intermittent NXDOMAIN  if I ping google.com
or intermittent NXDOMAIN if I ping some internal server.

And I think its because I am using forward , the doc says it load balances between
the servers named in the line.

What config change should I do so I can resolve internal server names using 
my own dns servers and at the same time resolve to an external DNS when 
the server names are not found in the internal dns.  thank you

`  Corefile: | 

    .:53 {
        errors
        log
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }   
        prometheus :9153
        proxy . /etc/resolv.conf
        loop
        reload
        loadbalance
        forward . 10.9.217.180 10.9.217.181 8.8.8.8
        cache 30
    }   
`

**Comment by chrisohaver** [comment]
You can create a second server block for your internal zone ... like so...

```
.:53 {
    errors
    log
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        upstream
        fallthrough in-addr.arpa ip6.arpa
    }   
    prometheus :9153
    loop
    reload
    loadbalance
    forward . 8.8.8.8
    cache 30
}

my.internal.zone.:53 {
    errors
    log
    prometheus :9153
    loadbalance
    forward . 10.9.217.180 10.9.217.181
    cache 30
}
```

Note, I have removed *proxy* which was redundant, and eclipsing (or being eclipsed by) _forward_.

**Comment by avmgithub** [comment]
thank you that seem to work , closing

**Comment by abnerrizzi** [comment]
how to make this change permanent ?

**Comment by mariuskimmina** [comment]
What do you mean by "making this change permanent?" 
It's a change in the Corefile, there shouldn't be anything temporary about it.

**Comment by abnerrizzi** [comment]
I am using k3s + coredns.
I did ```kubectl edit configmaps -n kube-system coredns``` and added the information following the pattern suggested by [chrisohaver](https://github.com/chrisohaver).
if I change config map and restart any pod, the DNS will get the new config.

However if I restart one of my masters, corefile is return the orginal state.

**Comment by mariuskimmina** [comment]
Sounds like the issue isn't with CoreDNS itself but rather some other part of your cluster reverting the configuration changes. Without more information on how you deployed CoreDNS, it's hard to pinpoint exactly - and probably better disussed at #coredns on https://slack.cncf.io/
