### ISSUE TITLE
plugin/k8s_external

### ISSUE THREAD

**Issue by fragfutter** [coredns/coredns#3064]
using coredns 1.3.1 and the k8s_external plugin i miss some A records in the dns subzone

<pre>
.:53 {
    errors
    health
    kubernetes k8s.cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    k8s_external k9s.cluster.local in-addr.arpa ip6.arpa {
       ttl 30
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
</pre>

the documentation notes that there is a stub/apex zone. But i'm missing an NS record and an A record
<pre>
dig NS k9s.cluster.local => invalid dns package
dig NS dns.k9s.cluster.local =>  no entry
dig A ns1.dns.k9s.cluster.local => no entry
</pre>

The kubernetes plugin handles them like
<pre>
dig NS k8s.cluster.local => ns.dns.k8s.cluster.local.
dig NS dns.k8s.cluster.local => no entry
dig A ns.dns.k8s.cluster.local => 10.96.x.y
</pre>

**Comment by chrisohaver** [comment]
two separate issue here I think...

1. we should not FORMERR for the NS query.
2. I suppose for the `ns1.dns...` A records ...
   * If CoreDNS is a pod running in the cluster, look up the external IP of the CoreDNS service attached to the pod (there could be > 1 service, so I think report all external ips as A records).
   * If CoreDNS is running outside the cluster, then report its bound IP addresses as A recrods.
