### ISSUE TITLE
middleware/root design suggestion

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#307]
To be similar to the design in caddy it defines the base directory/path to run directives from.

The syntax would look like this:

```
.:2053 {                                                                                                                                 
  root /var/public/dns
  file zone2.db zone2 # file would be located at /var/public/dns/zone2.db
}
```

Some additional considerations:
- Default path would be the current working directory where coredns was run.
- Relative paths use the working directory as base.

Starting coredns in /usr/bin for example would have the following paths associated:
no root set ->  **/usr/bin** (default path)
**root /var/public/dns** -> **/var/public/dns** (overwritten)
**root dns** -> **/usr/bin/dns** (relative using default as base)

**Comment by miekg** [comment]
We should be able to nicely hook this into `./middleware/pkg/storage/fs.go`, which `file` (and possible other middleware) should then use.

**Comment by miekg** [comment]
#330 adds a simpler design, i.e. path.Join with config.Root
