### ISSUE TITLE
/plugin: etcd : How etcd handle subdomain  

### ISSUE THREAD

**Issue by Chengdian-Yang** [coredns/coredns#3078]
/plugin: etcd

Corefile:

```
diamond:53 {
    etcd diamond {
        path /diamond
        endpoint http://localhost:2379
    }
    log
    errors
    cache 30 diamond
}
.:53 {
    forward . /etc/resolv.conf
    log
    errors
    cache
}
```

Put A records to  etcd:

```
/diamond/diamond/example
{"host":"1.1.1.2"}
/diamond/diamond/example/a
{"host":"1.1.1.1"}
```

Query result:

```
dig a.example.diamond @192.168.90.139 +short
1.1.1.1
dig example.diamond @192.168.90.139 +short
1.1.1.1
```

What I expect is example.diamond  -> 1.1.1.2

**Comment by miekg** [comment]
I doesn't work like that, please propose text to make this more clear in the 
readme.

/plugin: etcd
/label: question

**Comment by zgfh** [comment]
@yongtang may help you https://github.com/coredns/coredns/issues/3008

**Comment by zgfh** [comment]
@miekg should I make a PR to create a etcdDns plugin?  for someone what config dns with etcd?

**Comment by Chengdian-Yang** [comment]
@zgfh Expect for your PR. 

Accurate processing between domain and sub-domain is very important for etcd plugin.

Otherwise it can't handle complex cases. Nor can it be applied to production environment.

**Comment by miekg** [comment]
The etcd plugin isn't and will never be a full blown DNS zones plugin.

**Comment by zgfh** [comment]
@miekg I mean create new plugin ,not update the etcd plugin

**Comment by miekg** [comment]
For this we would likely need a good data model on how to store things in
each backend, including perhaps databases. Various efforts have been tried,
but none have been committed to the main tree.

**Comment by Chengdian-Yang** [comment]
So we should us plugin `file` or `host` to solve this problem?

`etcd` is easy-using in adding and modifying records. 

Has any other plugins can provide an api to operate records?

**Comment by miekg** [comment]
I don't know what your use case is and what you want to do.

**Comment by Chengdian-Yang** [comment]
We want to  do CoreDNS HA, so choose plugin etcd as backend.

But etcd can not handle subdomain.

**Comment by johnbelamaric** [comment]
Let's separate out the problems here:

1) Populating a backend data store with zone data
2) Making that datastore HA
3) Serving data from that data store
4) Modifying data in that data store

Today CoreDNS ONLY does 3), and of course you need a different plugin depending on your data store. The etcd plugin in particular is not a general-purpose DNS backend, but a narrow, SkyDNS-like service discovery plugin. If you want a general purpose DNS plugin for etcd, that's awesome and would be welcome.

There is no general-purpose data model (other than raw DNS) for CoreDNS today. There is no "write" API for backends (see #1822 for more). That would be great to have, but it is not a prerequisite for any of this.

If you want to solve 1-4, you can do that with a new custom etcd plugin, or you can look at the different redis or pgsql plugins and perhaps other external ones. Those other data stores also can be HA.

**Comment by miekg** [comment]
as said. *etcd* is not a generic zone backend.

**Comment by nemanjan00** [comment]
Is there any reason you would ever want behaviour that is implemented now?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] /plugin: etcd..." ]
>Is there any reason you would ever want behaviour that is implemented now?

yes, when you do service discovery, as is the purpose of this plugin

**Comment by nemanjan00** [comment]
I was talking about problem with domains and subdomains, and returning records from subdomain for domain
