### ISSUE TITLE
middleware/file enable serving whole directories

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#308]
Instead of specifying every db file and zone it might be interesting to serve whole directories.

Current possibilities:

Single db + serving only specific zones

```
.:2053 {
  file zones.db zone2 zone3
  file zones.db # zones can be omitted + serve all zones
}
```

Single zone db files

```
.:2053 {
  file zone1.db zone1
  file zone2.db zone2
  file zone3.db # zone can be omitted + serve all zones
}
```

Proposed syntax using "dir" as keyword:

```
.:2053 {
  dir zones zone2 zone3 zone4 
  dir zones # parsing all files in zones/ + serve all zones
}
```

Proposed syntax expanding "file" keyword:

```
.:2053 {
  # check if zones is a file or directory, if it's a directory loop through all files and parse
  file zones zone2 zone3 zone4
  file zones # parsing all files in zones/ + serve all zones
}
```

As a user it might be easier to just use file and have it go through directories or use a specific file.

**Comment by miekg** [comment]
This does assume the meta data is identical between zones as well (.i.e. same masters and slaves), which may be a fair assumption. I should only look for children under the top-level defined domain.

How should this deal with collision if it adds `example.com` but `example.com` also has it's own stanza specifying stuff?

**Comment by miekg** [comment]
See #177

**Comment by stp-ip** [comment]
For different meta data one should be using separate configs such as:

```
.:2053 {
  file zones
  # some default metadata
}
example.com:2053 {
  file single/example.com
  # special metadata
} 
```

The more specific the zone definition the more weight it gets. So example.com would use the second config, even so it might also be available within the first set.
As far as I can see that's how caddy also does it with path matching and is most likely already working.

Using this approach one could say that the most specific zone definition for file wins.
Aka "file zones example.com" would win over "file zones2".
"file zones example.com" and "file zones2 example.com" could look at the serial field and the highest serial wins.
As a fallback logging an error and using the first appearance could make sense.
Using order is too implicit, but maybe a necessary fallback.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/file..." ]

> For different meta data one should be using separate configs such as:
> 
> ```
> .:2053 {
>  file zones
>  # some default metadata
> }
> example.com:2053 {
>  file single/example.com
>  # special metadata
> }
> ```
> 
> The more specific the zone definition the more weight it gets. So example.com would use the second config, even so it might also be available within the first set.
> As far as I can see that's how caddy also does it with path matching and is most likely already working.

Yes, the most specific zone stanza will get the query routed it.

> Using this approach one could say that the most specific zone definition for file wins.
> Aka "file zones example.com" would win over "file zones2".

This is indeed a way, but could lead to weird temporary outages, it could just
flip/flop between the to definitions and then something stops working until it
flips back.

Logging may help, but it is probably hard to correlate. It rather not load the
newly discovered zone _at_ all if there is a more specific stanza for it. 

> "file zones example.com" and "file zones2 example.com" could look at the serial field and the highest serial wins.

I would like to something more explicit - if at all possible.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
> > Using this approach one could say that the most specific zone definition for file wins.
> > Aka "file zones example.com" would win over "file zones2".
> 
> This is indeed a way, but could lead to weird temporary outages, it could just
> flip/flop between the to definitions and then something stops working until it
> flips back.

Not sure why it would flop around.
"file zones example.com" would always win over the unspecific "file zones2"

> > "file zones example.com" and "file zones2 example.com" could look at the serial field and the highest serial wins.
> 
> I would like to something more explicit - if at all possible.

The only really specific approach would be to error out with duplicate zones defined within the file directive.
Example error:

```
example.com:2053 {
  file single/example.com
  file zones example.com
}
```

So the approach could be to error and exit, when duplicate zones are loaded within the same zone config (as seen above).
To make it possible to overwrite specific zones without exiting/erroring, one could do something like this:

```
.:2053 {
  file zones
}
example.com:2053 {
  file single/example.com
}
```

Thinking through the various approaches, this might seem the cleanest solution. Usually one has a config for the main cases including default meta-data, default zones and maybe proxying. Everything else could easily be done using zone matching and their own section.

Hope that makes sense.

**Comment by miekg** [comment]
> Not sure why it would flop around.

If you look at SOA serial numbers it might.

> The only really specific approach would be to error out with duplicate zones defined within the file directive.
> Example error:
> 
> ```
> example.com:2053 {
> file single/example.com
>  file zones example.com
> }
> ```

But if this finds and adds a zone `foo.bla.example.com` _and_ you have a section for `bla.example.com` as well, how would you handle that?

```
example.com:2053 {
 file single/example.com
  file zones example.com
}

bla.example.com:2053 {
  file single/bla.example.com
}
```

This would get routed to the second stanza and be never answered from the first one. Maybe that is an solution - silently ignore (but then this weird corner case needs logging and metrics as well, so we can alert on it)

**Comment by stp-ip** [comment]
> > Not sure why it would flop around.
> 
> If you look at SOA serial numbers it might.

Yes true. Didn't think this comment was on the serial number suggestion.
But yeah considering the serial numbers again it seems best to not use them and just error on duplicate stuff.

> But if this finds and adds a zone foo.bla.example.com and you have a section for bla.example.com as well, how would you handle that?
> 
> example.com:2053 {
>  file single/example.com
>   file zones example.com
> }
> 
> bla.example.com:2053 {
>   file single/bla.example.com
> }
> 
> This would get routed to the second stanza and be never answered from the first one. Maybe that is an solution - silently ignore (but then this weird corner case needs logging and metrics as well, so we can alert on it)

I agree that matching is harder with zones/dns than it is with paths for webservers.
Naively I would say that the record, which matches under the most specific zone gets served and an error is logged, that another record was available and maybe prints both records or zones, which are specified?

From a users perspective I think it makes sense, that "bla.example.com" would return records from the second section, but a record for "about.example.com" would use the first section.

Section specific that makes sense, but going down the rabbit hole with multiple "file" lines it gets complex fast.

```
file main.db example.com
file about.db about.example.com
file www.bla.db www.bla.example.com
```

Being consistent with more specific outweighs the rest www.bla.example.com > about.example.com > example.com.  So it needs to parse all zones and rank them accordingly. How these merge is another interesting aspect. main.db wouldn't be used for records of about.db, even so it might contain some.
Still I would say. More specific -> overwrites unspecific + log an error with both records and zones for debugging.

Thanks for taking the time to bear with the ideas.

**Comment by miekg** [comment]
I thought about this some more. 

And I think we already have this 'problem' when you use for instance the `etcd` middleware. This will happily find new names (i.e. bla.foo.example.org). If you have a stanza for `foo.example.org` queries for that name will be routed to that, instead of being answered by the `etcd` middleware. This all happens silently, we should follow the same model here.

This does need some documentation; but in fairness I believe this is just a logical extension of how the routing works. Also _not_ editing your config for new zone is a bug plus.

**Comment by miekg** [comment]
And by adding a new keyword in the file stanza `discover`(?) will be the correct way forward. And writing a blog on the query routing.

**Comment by stp-ip** [comment]
Not sure what your idea is, but keep me in the loop ;)

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/file..." ]

> Not sure what your idea is, but keep me in the loop ;)

2 things: 
- the routing problem already exist with the current features and middleware
- it's easy to extend the file middleware to pickup new zone (precise feature
  TBD)

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
Ok so for the routing problem the plan is a blogpost and documentation. <-- could this be solved better?
For the multi file keyword you propose discover, which discovers all zones from the given directory? <-- still not sure, if a new keyword is needed or it's just either a dir or a file.

Thanks for taking the time. Awesome work.

**Comment by miekg** [comment]
> Ok so for the routing problem the plan is a blogpost and documentation. <-- could this be solved better?
> Open for idea, we will _also_ log, but that still does not make a big splash :)
> And a metric that exports the total number of zones we currently handle.

Zones also need to be dropped when they disappear (obviously). Someone also proposed a `git` middleware, but I'll have to check what that does in Caddy and see if that is applicable to CoreDNS.

> For the multi file keyword you propose discover, which discovers all zones from the given directory? <-- still not sure, if a new keyword is needed or it's just either a dir or a file.

you mean if a dir is referenced do `discover`?

Well I think we need regexp support, where the first matching group will be used as the zone name:
- db.(.*) -> db.miek.nl -> `miek.nl` is the zone (something liek this will probably be the default

**Comment by stp-ip** [comment]
Yeah I proposed the git middleware. Not hugely important, but maybe a nice to have. I will most likely go with the git-sync sidecar container as our infra is running on k8s. (better separation of concerns).

It was mainly a questions why we need the new `discover` keyword.

So proposal for `file` would be () are optional:
- single file -> `file db.example.com (example.com)`
- multiple single files -> `file db.example.com (example.com) \n file db.example.de (example.de)`
- directory of files -> `file records (example.com)`
- regex for files -> `file db.(.*) ({1})`
- blogpost, logging and docs to explain "issues" with routing and possible overwriting issues.

**Comment by miekg** [comment]
I'm figuring the following should work:

```
file DBDIRECTORY  [ZONES...] {
    auto_load db.(.*) {1}
}
```

Which makes it very explicit what you want. `DBDIRECTORY` does not have to exist at the time of parsing.  A fsnotify watch will be set up and files matching the regexp will be loaded (or dropped). 
I need some extra stuff to kill the NOTIFY goroutine, but that is relative minor

**Comment by stp-ip** [comment]
Still the issue with, which zones get loaded where/first is still open.
I'm not sure I agree with the syntax, but I agree it makes it more explicit and merges files/folders/regex into one group. :+1: 

Awesome work. Let me know, when it's ready for testing.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/file..." ]

> Still the issue with, which zones get loaded where is still open.

They all get loaded, regardless of origin (at least that's my plan). If they
will receive queries depends on the Corefile.

> I'm not sure I agree with the syntax, but I agree it makes it more explicit and merges files/folders/regex into one group.

Ack. Syntax is from regexp.ExpandString which does what I need. Don't want to
reinvent something new, but it _is_ different from the syntax used in the _log_
middleware... (idea: it might just rewrite it).

> Awesome work. Let me know, when it's ready for testing.

Planning this for 002 - soon. This feature request and 2 bugs are all that need
to be fixed before I release 002

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
> > Still the issue with, which zones get loaded where is still open.
> 
> They all get loaded, regardless of origin (at least that's my plan). If they
> will receive queries depends on the Corefile.

Oh yeah poor choice of wording. Loading all seems like the right thing to do. So to better say that. What actual origin gets served is still feeling like a race condition ;) (but that might be clarified by the blogpost)

> > Awesome work. Let me know, when it's ready for testing.
> 
> Planning this for 002 - soon. This feature request and 2 bugs are all that need
> to be fixed before I release 002

Awesome.

**Comment by miekg** [comment]
#333 is coming along nicely - you can _probably_ try it out (still has some rough edges probably, if you know Go you can probably extend/tweak it yourself). Oh yeah: the actual handler that serves this data hasn't been written yet :) (Will copy that one mostly from the _file_ middleware). The file discovery (`watcher.go` needs tests as well)

With a Corefile:

```
. {
    auto example.org {
        directory /tmp/corednstest
    }
}
```

It show this in the logs, when I create, mv, rm a file called `db.example.{com, org}` in the `/tmp/corednstest` directory.

```
% ./coredns -log stdout -conf Corefile-auto -dns.port=1053
.:1053
2016/10/16 12:39:06 [INFO] CoreDNS-001
CoreDNS-001
2016/10/16 12:39:10 [INFO] Inserting zone `example.com.' from: /tmp/corednstest/db.example.com
2016/10/16 12:39:19 [INFO] Deleting zone `example.com.'
2016/10/16 12:39:26 [INFO] Inserting zone `example.org.' from: /tmp/corednstest/db.example.org
2016/10/16 12:39:30 [INFO] Deleting zone `example.org.'
^C2016/10/16 12:40:36 [INFO] SIGINT: Shutting down
```

README.md should be able to tell you all you'll need to know - if not please open a bug/pr.

**Comment by miekg** [comment]
#333 is now working in local tests. I'll need to clean it up a bit and add more tests.

**Comment by miekg** [comment]
Closed with merging of #333

**Comment by stp-ip** [comment]
Hadn't had time yet to check it out. Will test it and provide feedback as usual.

**Comment by miekg** [comment]
No problem.
