### ISSUE TITLE
plugin/etcd: should we rename it skydns?

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#3084]
Seems to cause some confusion otherwise.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/etcd: shou..." ]
>Seems to cause some confusion otherwise.

Think a rename would be a bit premature... the question is, do we actually still 
need the currently functionality? or should we define a data model (possibly 
covering relational DBs as well) and make more things possible? All qtypes, zone 
cuts?

(This also allows us to get rid of backend.go and put some optimizations in 
there for the kubernetes plugin)

**Comment by miekg** [comment]
this horse left the barn long ago. should *etcd* be named *skydns* initially? yes, but now, we're too late. Fixing this requires more thought and a general DB backend procotol (maybe). Closing here.
