### ISSUE TITLE
plugin/etcd: upgrade to go.etcd.io/etc import path

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3087]
etcd moved their import paths to go.etcd.io/etc. But if I try to use the new ones I get the following error:

~~~
plugin/etcd/etcd.go:80:22: cannot use r.Kvs (type []*"github.com/coreos/etcd/mvcc/mvccpb".KeyValue) as type []*"go.etcd.io/etcd/mvcc/mvccpb".KeyValue in argument to e.loopNodes
~~~
Some indirect dependencies is pulling down etcd from the older location and *somehow* this gets used when compiling this.

I tried playing around with `replace` and `exclude` in `go.mod` but no avail.
I also don't know how to track down which indirect dep is pulling it on the older name

**Comment by chrisohaver** [comment]
There is `go mod why` ... e.g. ` go mod why -m github.com/coreos/etcd` which helps a little.
That says ...
```
# github.com/coreos/etcd
github.com/coredns/coredns/plugin/etcd
go.etcd.io/etcd/clientv3
github.com/coreos/etcd/auth/authpb
```

Digging into it, it looks that 3.3.13 still references the old path in some files in `go.etcd.io/etcd/clientv3`.  It appears to be fixed in master.

**Comment by miekg** [comment]
https://github.com/etcd-io/etcd/issues/10943 They aim for a release on August 30
