### ISSUE TITLE
middleware/rewrite use for duplicating multiple zones

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#309]
Suggesting a new syntax to make duplicating records from one zone to another easier:

```
rewrite {
  zone1 zone2
  zone3 zone2
}
```

The above duplicates all records from zone2 to also be served with zone1 and zone3.

**Comment by miekg** [comment]
basically qname rewriting. yes I think we should support this.

The rewrite middleware needs quite some work, I'm personally focussing one the 002 milestone bugs, this needs to come later. Unless of course PRs pop up :)

**Comment by miekg** [comment]
Rewriting name is iffy and will break clients (probably).

**Comment by stp-ip** [comment]
Ok so recommendation is to duplicate records on the backends. Which is fine, when documented.
