### ISSUE TITLE
Listen For DoH requests

### ISSUE THREAD

**Issue by amar-h-patel** [coredns/coredns#3094]
The README.md file says CoreDNS supports DoH requests (RFC 8484), but I cannot find any documention specifying how to configure the Corefile to do so.

Thanks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Listen For DoH re..." ]
>The README.md file says CoreDNS supports DoH requests (RFC 8484), but I cannot find any documention specifying how to configure the Corefile to do so.

this works by just saying: 

~~~
https://example.org {
    # plugins
}
~~~

in the corefile

/label: question
