### ISSUE TITLE
reply from unexpected source: 169.254.20.10#53, expected 10.96.3.45#53

### ISSUE THREAD

**Issue by pacoxu** [coredns/coredns#3097]
I want to try the proposal 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md#risks-and-mitigations
![image](https://user-images.githubusercontent.com/2010320/62692936-21ba3e00-ba04-11e9-9506-09dc71421982.png)

- coredns 1.5.2
- node local dns 1.15.3
- Corefile is from kubeadm 1.15

1. 10.96.3.45 is coredns clsuter ip
2. 10.96.0.2 is coredns clsuter ip and node local dns's upstream
3. 169.254.20.10 is node local dns ip

When node local dns is not deployed, user can use 10.96.3.45, which is coredns cluster ip, as dns server.
When node local dns is deployed, we need to config 10.96.3.45 to redirect to 169.254.20.10 like below.

Use iptables to redirect 10.96.3.45   to 169.254.20.10 
```
 iptables -t nat -I PREROUTING 1 -d 10.96.3.45 -p udp -m udp --dport 53 -j DNAT --to-destination 169.254.20.10:53
iptables -t nat -I OUTPUT 1 -d 10.96.3.45 -p udp -m udp --dport 53 -j DNAT --to-destination 169.254.20.10:53
```

When I run nslookup, I got the errors below
```
[root@coredns-master1 ~]# nslookup kubernetes.default.svc.cluster.local 10.96.3.45
;; reply from unexpected source: 169.254.20.10#53, expected 10.96.3.45#53
;; reply from unexpected source: 169.254.20.10#53, expected 10.96.3.45#53
;; reply from unexpected source: 169.254.20.10#53, expected 10.96.3.45#53
;; connection timed out; no servers could be reached
```

node local dns log: 
```
2019-08-08T09:44:51.604Z [INFO] 10.6.115.7:47427 - 33861 "A IN kubernetes.default.svc.cluster.local. udp 54 false 512" NOERROR qr,aa,rd 106 0.002938453s
2019-08-08T09:44:56.601Z [INFO] 10.6.115.7:47427 - 33861 "A IN kubernetes.default.svc.cluster.local. udp 54 false 512" NOERROR qr,rd 106 0.000100925s
2019-08-08T09:45:01.604Z [INFO] 10.6.115.7:47427 - 33861 "A IN kubernetes.default.svc.cluster.local. udp 54 false 512" NOERROR qr,rd 106 0.000246593s

```

It seems that the redirect is success. However, the response contains that the dns server is 169.254.20.10. nslookup requests for 10.96.3.45.

**Comment by johnbelamaric** [comment]
@prameshj PTAL

**Comment by prameshj** [comment]
Can you try binding nodelocaldns on the coredns cluster ip? 
You can specify args for nodelocaldns in the yaml like : "-localip 169.254.20.10,19.96.3.45". Then you shouldn't need the nat rules that you added. 

We added support for multiple listen ip here - https://github.com/kubernetes/dns/pull/303

**Comment by pacoxu** [comment]
@prameshj  thanks a lot.

1. k8s.gcr.io/k8s-dns-node-cache:1.15.3 does not support multi local ips. It's supported in k8s.gcr.io/k8s-dns-node-cache:1.15.4.
-localip 169.254.20.10,10.96.3.45

2. node local dns's configmap should change the "bind" as localip. 
bind 169.254.20.10 10.96.3.45

Finally, the 10.96.3.45 cannot be used as iptables will send requests to coredns pod for cluster ip.
```
iptables -t nat -I OUTPUT 1 -d 10.96.3.45 -o lo -j RETURN

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
cali-OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0            /* cali:tVnHkvAo15HuiPy0 */
RETURN     all  --  0.0.0.0/0            10.96.3.45
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
```

I add the iptables rule above to make 10.96.3.45 redirect to lo.
After I add the iptables above, 10.96.3.45 will be redirect to 169.254.20.10.
After I remove the iptables above, 10.96.3.45 will be redirect to corends pod as cluster ip.


I'm not sure whether there is another way to make 10.96.3.45 as local node dns by default. 
Or we can add the 
```
iptables -t nat -I OUTPUT 1 -d 10.96.3.45 -o lo -j RETURN
```
to node local dns

**Comment by prameshj** [comment]
I am not sure why you need the NAT rules.. we install a rule in raw PREROUTING to skip conntrack(-j NOTRACK) if packet is destined for any of the nodelocaldns ip(if you used 10.9.3.45 as one of the listen IP, this rule will be added for that ip as well). In this case, the packet would skip the nat table rules and be locally delivered since 10.9.3.45 address is bound on a local interface.

Did you observe this was not working?

**Comment by pacoxu** [comment]
@prameshj  for those pods that are running in calico network or cni network. 
The PREROUTING will work. It doesn't matter whether the NAT rule is applied. 

But some pods in my cluster are running with HostNetwork:true. 

For those hostNetwork pods, I had to add 
```
iptables -t nat -I OUTPUT 1 -d 10.96.3.45 -o lo -j RETURN
```

**Comment by prameshj** [comment]
That makes sense now, for the hostNetwork pods... Thanks @pacoxu ! So the only extra iptables rule you added is:

iptables -t nat -I OUTPUT 1 -d 10.96.3.45 -o lo -j RETURN

Does using 2 ip addresses as we discussed in the above comments work for you?

**Comment by pacoxu** [comment]
@prameshj 2 ip addresses work for me.
However, if I use the virtual cluster ip as cluster dns in my cluster, I think only 1 ip is enough.

169.254.20.10 is just for local testing in my case.

As the issue is solved, I closed it now.
