### ISSUE TITLE
Pod can not resolve domain

### ISSUE THREAD

**Issue by fivehundredmiless** [coredns/coredns#3099]
Version: kubernets:  1.15 coredns :  1.3.1

1. Pod can't resolve domain use core dns .

kubectl exec -it busybox-deployment-59755c8c6d-4fqxx sh

/ # nslookup -type=a www.google.com 114.114.114.114
Server:         114.114.114.114
Address:        114.114.114.114:53

Non-authoritative answer:
Name:   www.google.com
Address: 46.82.174.68

/ # cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
/ # ping 10.96.0.10
PING 10.96.0.10 (10.96.0.10): 56 data bytes
64 bytes from 10.96.0.10: seq=0 ttl=64 time=0.117 ms
^C
--- 10.96.0.10 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.117/0.117/0.117 ms
nslookup -type=a www.google.com 10.96.0.10
nslookup: read: Connection refused
nslookup: read: Connection refused

2. I don't know how to login in pod. 

kubectl exec -it coredns-5c98db65d4-4984d sh -n kube-system
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
command terminated with exit code 126
[root@xiucai-maven-registory xiaoguang.xu]# kubectl exec -it coredns-5c98db65d4-4984d bash -n kube-system
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

3. I checked resolv.conf file the hosts running core DNS,AS below

cat /etc/resolv.conf
options timeout:2 attempts:3 rotate single-request-reopen
; generated by /usr/sbin/dhclient-script
nameserver 114.114.114.114
nameserver 114.114.114.114

4. 
kubectl logs coredns-5c98db65d4-4984d -n kube-system
.:53
2019-08-08T15:37:00.404Z [INFO] CoreDNS-1.3.1
2019-08-08T15:37:00.404Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-08-08T15:37:00.404Z [INFO] plugin/reload: Running configuration MD5 = 5d5369fbc12f985709b924e721217843

5. 
Events:
  Type    Reason     Age   From                        Message
  ----    ------     ----  ----                        -------
  Normal  Scheduled  20m   default-scheduler           Successfully assigned kube-system/coredns-5c98db65d4-4984d to xiucai-jumpserver
  Normal  Pulled     20m   kubelet, xiucai-jumpserver  Container image "k8s.gcr.io/coredns:1.3.1" already present on machine
  Normal  Created    20m   kubelet, xiucai-jumpserver  Created container coredns
  Normal  Started    20m   kubelet, xiucai-jumpserver  Started container coredns

please give some suggest,thanks.

**Comment by chrisohaver** [comment]
> Pod can't resolve domain use core dns .

If you target a CoreDNS _Pod_ IP directly does it work? e.g. `nslookup -type=a www.google.com ip-address-of-a-coredns-pod`.  

> I don't know how to login in pod.

You cannot get on a command line of the CoreDNS pod, the container does not allow it.
