### ISSUE TITLE
middleware/file what does "from" actually do?

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#310]
```
file zones.db {
  transfer from 10.240.1.1
}
```

As the zones are served from a file getting and serving changes from another DNS server seems counterintuitive.
I might misunderstand the use so.
For me "transfer to" notifies and transfers changes to another server.
"transfer from" would get transfers from another server.

Thanks for clarifying

**Comment by miekg** [comment]
Transfer form for `file` does not make sense. This is a bug.

Probably cause is the sharing of code between the `secondary` and `file` middleware.
