### ISSUE TITLE
plugin/azure: add support for private zones

### ISSUE THREAD

**Issue by darshanime** [coredns/coredns#3113]
Azure supports hosting private dns zones, `plugin/azure` should support it. 
https://docs.microsoft.com/en-us/azure/dns/private-dns-overview

**Comment by yongtang** [comment]
+1, 👍  See my comment about Google Cloud DNS privately hosted zones: https://github.com/coredns/coredns/pull/3011#issuecomment-522270098

Serving privately hosted zone (created over cloud vendors) by CoreDNS servers on prem is very useful (or more useful) in many situations for hybrid or multi-cloud cluster deployments.

**Comment by rhollins** [comment]
It would be great to see this feature added. We could potentially setup conditional forwarding from on-premise to coredns which could then resolve azure private zones which do not support conditional forwarding.
https://docs.microsoft.com/bs-latn-ba/azure/dns/private-dns-overview#other-considerations

**Comment by darshanime** [comment]
ah, sorry this slipped out. I will finish writing tests for my WIP PR and push this in a few days max 👍

**Comment by lukasmrtvy** [comment]
@darshanime any news ?
