### ISSUE TITLE
Classless reverse DNS handling is flawed

### ISSUE THREAD

**Issue by cpointner** [coredns/coredns#3123]
While #1159 was a step in the right direction i think it is incomplete. Consider the following Corefile:

```
cluster.local 192.168.0.0/17 192.168.128.0/20 {
    bind 127.0.1.53
    log
    errors
    forward . 192.168.128.10 {
        force_tcp
    }
    cache {
        success 9984 30
        denial 9984 5
    }
    prometheus 127.0.0.1:9953
}

. {
    bind 127.0.1.53
    log
    errors
    forward . 10.12.64.11
    cache 600
    prometheus 127.0.0.1:9953
}
```
Using this with coredns (version 1.6.1) i get:

```cannot serve dns://168.192.in-addr.arpa.:53 on 127.0.1.53 - it is already defined```

This is of course because ```192.168.0.0/17``` and ```192.168.128.0/20```, despite being non-overlapping network ranges, share the same parent `in-addr.arpa` zone.

**Comment by chrisohaver** [comment]
see PR #2783 and Issue #2779

**Comment by chrisohaver** [comment]
The work-around is to construct the reverse zones by hand.

**Comment by miekg** [comment]
dup of #2779
