### ISSUE TITLE
plugin/file: prevents etcd from answering

### ISSUE THREAD

**Issue by h3ndrk** [coredns/coredns#3124]
The `etcd` plugin never gets called when the `file` plugin is active (see below). Every query gets answered by the `file` plugin.

The expected behaviour for me is that the `etcd` plugin always gets called first (because it is listed first and both plugins target the same zone).

Only if I comment out the `file` plugin line in the `Corefile` the `etcd` plugin answers (all) queries.

My use case is to serve a single zone with `etcd` precedence, backed by a zone file for static records.

1. Why is the current behaviour maybe correct?
2. Is it possible to achieve my use case? Could you point me in the right direction?

Thanks!

### /conf/Corefile

```
example.com:53 {
    log
    errors
    health
    etcd {
        path /skydns
        endpoint http://localhost:2379
    }
    file /conf/example.com.zone
}
```

### /conf/example.com.zone

```
example.com.          3600 IN SOA master.example.com. postmaster.example.com. ( 2019081302 3600 1200 604800 3600 )
@                     3600 IN NS  master.example.com.
@                     3600 IN NS  backup.example.com.
example.com.          3600 IN A   1.2.3.4
master.example.com.   3600 IN A   1.2.3.4
backup.example.com.   3600 IN A   1.2.3.5
```

## Tests with file

```
$ ETCDCTL_API=3 etcdctl get --prefix /        
/skydns/com/example/test
{"host":"4.3.2.1"}
```

```
$ dig @127.0.0.1 test.example.com    

; <<>> DiG 9.14.4 <<>> @127.0.0.1 test.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 62227
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: b181a445a6260f4c (echoed)
;; QUESTION SECTION:
;test.example.com.		IN	A

;; AUTHORITY SECTION:
example.com.		3600	IN	SOA	master.example.com. postmaster.example.com. 2019081302 3600 1200 604800 3600

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Di Aug 13 20:24:32 CEST 2019
;; MSG SIZE  rcvd: 144
```

```
$ dig @127.0.0.1 example.com 

; <<>> DiG 9.14.4 <<>> @127.0.0.1 example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10092
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 907b329d32bc735c (echoed)
;; QUESTION SECTION:
;example.com.			IN	A

;; ANSWER SECTION:
example.com.		3600	IN	A	1.2.3.4

;; AUTHORITY SECTION:
example.com.		3600	IN	NS	master.example.com.
example.com.		3600	IN	NS	backup.example.com.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Di Aug 13 20:25:16 CEST 2019
;; MSG SIZE  rcvd: 165
```

## Test without file

```
$ ETCDCTL_API=3 etcdctl get --prefix /        
/skydns/com/example/test
{"host":"4.3.2.1"}
```

```
$ dig @127.0.0.1 test.example.com

; <<>> DiG 9.14.4 <<>> @127.0.0.1 test.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36371
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 91271520ee048c28 (echoed)
;; QUESTION SECTION:
;test.example.com.		IN	A

;; ANSWER SECTION:
test.example.com.	300	IN	A	4.3.2.1

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Di Aug 13 20:28:31 CEST 2019
;; MSG SIZE  rcvd: 89
```

```
$ dig @127.0.0.1 example.com 

; <<>> DiG 9.14.4 <<>> @127.0.0.1 example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60947
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 66be67cb20a453a6 (echoed)
;; QUESTION SECTION:
;example.com.			IN	A

;; ANSWER SECTION:
example.com.		300	IN	A	4.3.2.1

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Di Aug 13 20:29:19 CEST 2019
;; MSG SIZE  rcvd: 79
```

**Comment by miekg** [comment]
The order is determined from plugins.cfg, not from the ordering in the
corefile

**Comment by h3ndrk** [comment]
Thanks for your quick answer!
Are there any side-effects when reordering the `plugins.cfg`?

**Comment by chrisohaver** [comment]
> The expected behaviour for me is that the etcd plugin always gets called first (because it is listed first and both plugins target the same zone).

I think you are implying another expectation - that If the etcd plugin produces no answer, then the file plugin should get called _next_.  But this is also not how plugins work by default.  A few plugins do have a "fallthrough" option that does this, but not all do.  Most simply send a negative answer to the client, and the next plugin is not called.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/file: ..." ]
>Thanks for your quick answer!
>Are there any side-effects when reordering the `plugins.cfg`?

well, you change the ordering. I.e. if you move prometheus to the end, you won't 
get any proper monitoring. But for most plugins it doesn't matter much, etcd and 
file can be switched.

**Comment by chrisohaver** [comment]
> Are there any side-effects when reordering the plugins.cfg?

Depends on the plugin, but I think you could swap file and etcd without issue.  You'll need to use the `fallthough` option in *etcd* too ...

**Comment by h3ndrk** [comment]
Thank you both! Awesomely quick!

Your answers made the concepts of CoreDNS a bit more clear for me. I will try the reordering.

Thanks!

**Comment by Ursadon** [comment]
Up. Can CoreDNS-build-team update official Docker container (make the etcd plugin a higher priority than file plugin)?

**Comment by chrisohaver** [comment]
> Up. Can CoreDNS-build-team update official Docker container (make the etcd plugin a higher priority than file plugin)?

No.  If you do not want to build your own, you may be able to accomplish the desired function with local forwarding.  E.g. adapting the example given in the description of this issue ...

```
example.com:53 {
    log
    errors
    health
    etcd {
        path /skydns
        endpoint http://localhost:2379
        fallthrough
    }
   forward . localhost:5353
}

example.com:5353 {
    log
    errors
    file /conf/example.com.zone
}
```

**Comment by johnbelamaric** [comment]
That could mess a lot of people up. An alternative would be looking into making plug-in order configurable in the Corefile. 

Or try Chris's suggestion.
