### ISSUE TITLE
coreDNS1.5.0

### ISSUE THREAD

**Issue by anzejiang** [coredns/coredns#3127]
Hello,coreDNS v1.5.0（Edition） Is there any instability in parsing svcname?

**Comment by anzejiang** [comment]
解析域名、svcname、podname,失败与成功的比例为3/1.

**Comment by chrisohaver** [comment]
@anzejiang, Please elaborate.

**Comment by chrisohaver** [comment]
Feel free to re-open if you can provide more information.
