### ISSUE TITLE
no buildable Go source file in Azure sdk

### ISSUE THREAD

**Issue by Azee77** [coredns/coredns#3161]
* Version 1.6.2
* Error Log : 
github.com/coredns/coredns/plugin/azure/azure.go:16:2: no buildable Go source files in /some_path/source_code/coredns-1.6.2/src/github.com/Azure/azure-sdk-for-go/profiles/latest/dns/mgmt/dns

PS - I dont need Azure. Is there anyway I can bypass this code also ?

**Comment by Azee77** [comment]
so many errors in make : 

go build
# context
context/context.go:404: undefined: time.Until
context/context.go:436: undefined: time.Until
# golang.org/x/sys/unix
golang.org/x/sys/unix/ioctl.go:18: undefined: runtime.KeepAlive
golang.org/x/sys/unix/ioctl.go:28: undefined: runtime.KeepAlive
golang.org/x/sys/unix/syscall_linux.go:99: undefined: runtime.KeepAlive
# google.golang.org/grpc/credentials/internal
google.golang.org/grpc/credentials/internal/syscallconn.go:29: syntax error: unexpected = in type declaration
# github.com/go-acme/lego/challenge/tlsalpn01
github.com/go-acme/lego/challenge/tlsalpn01/tls_alpn_challenge_server.go:90: undefined: http.ErrServerClosed
# github.com/go-acme/lego/v3/challenge/tlsalpn01
github.com/go-acme/lego/v3/challenge/tlsalpn01/tls_alpn_challenge_server.go:90: undefined: http.ErrServerClosed
# go.etcd.io/etcd/vendor/google.golang.org/grpc/credentials/internal
go.etcd.io/etcd/vendor/google.golang.org/grpc/credentials/internal/syscallconn.go:29: syntax error: unexpected = in type declaration
# go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore
go.etcd.io/etcd/vendor/go.uber.org/zap/zapcore/json_encoder.go:142: enc.reflectEnc.SetEscapeHTML undefined (type *json.Encoder has no field or method SetEscapeHTML)
# go.etcd.io/etcd/vendor/golang.org/x/sys/unix
go.etcd.io/etcd/vendor/golang.org/x/sys/unix/ioctl.go:18: undefined: runtime.KeepAlive
go.etcd.io/etcd/vendor/golang.org/x/sys/unix/ioctl.go:28: undefined: runtime.KeepAlive
go.etcd.io/etcd/vendor/golang.org/x/sys/unix/syscall_linux.go:86: undefined: runtime.KeepAlive
# go.etcd.io/etcd/raft/quorum
go.etcd.io/etcd/raft/quorum/majority.go:32: undefined: sort.Slice
go.etcd.io/etcd/raft/quorum/majority.go:33: undefined: strings.Builder
go.etcd.io/etcd/raft/quorum/majority.go:70: undefined: sort.Slice
go.etcd.io/etcd/raft/quorum/majority.go:85: undefined: sort.Slice
go.etcd.io/etcd/raft/quorum/majority.go:89: undefined: strings.Builder
go.etcd.io/etcd/raft/quorum/majority.go:111: undefined: sort.Slice
# github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore
github.com/coreos/etcd/vendor/go.uber.org/zap/zapcore/json_encoder.go:142: enc.reflectEnc.SetEscapeHTML undefined (type *json.Encoder has no field or method SetEscapeHTML)
# github.com/coreos/etcd/vendor/google.golang.org/grpc/credentials/internal
github.com/coreos/etcd/vendor/google.golang.org/grpc/credentials/internal/syscallconn.go:29: syntax error: unexpected = in type declaration
# github.com/coreos/etcd/vendor/golang.org/x/sys/unix
github.com/coreos/etcd/vendor/golang.org/x/sys/unix/ioctl.go:18: undefined: runtime.KeepAlive
github.com/coreos/etcd/vendor/golang.org/x/sys/unix/ioctl.go:28: undefined: runtime.KeepAlive
github.com/coreos/etcd/vendor/golang.org/x/sys/unix/syscall_linux.go:86: undefined: runtime.KeepAlive
# go.etcd.io/etcd/raft/raftpb
go.etcd.io/etcd/raft/raftpb/confchange.go:150: undefined: strings.Builder
go.etcd.io/etcd/raft/raftpb/confstate.go:30: undefined: sort.Slice
# github.com/google/go-cmp/cmp/internal/value
github.com/google/go-cmp/cmp/internal/value/sort.go:22: undefined: sort.SliceStable
# k8s.io/utils/trace
k8s.io/utils/trace/trace.go:100: invalid operation: stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) (mismatched types bool and klog.Verbose)
k8s.io/utils/trace/trace.go:112: invalid operation: stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) (mismatched types bool and klog.Verbose)
# sigs.k8s.io/yaml
sigs.k8s.io/yaml/yaml.go:42: undefined: DisallowUnknownFields
# k8s.io/apimachinery/pkg/runtime
k8s.io/apimachinery/pkg/runtime/converter.go:749: undefined: "reflect".MakeMapWithSize
# golang.org/x/xerrors
golang.org/x/xerrors/frame.go:32: undefined: runtime.CallersFrames

**Comment by miekg** [comment]
our travis does a clean build on every PR. I think you Go version is too old
