### ISSUE TITLE
Need a corefile template ( basic ) which will refresh the new DNS entry without container restart

### ISSUE THREAD

**Issue by Azee77** [coredns/coredns#3162]
Version : 1.6.2

zonefile contents : 
domainname    IN dummySOA.domain dummyuser.domain serial 10 3600 1209600 3600
fqdn  IN A _IP_
FQDN IN CNAME fqdn
and so on

such is the structure

new entries would be added to the file as : 
fqdn  IN A _IP_
FQDN IN CNAME fqdn
and so on

Note : No SOA changes.

How to reload DNS in such cases ?

**Comment by miekg** [comment]
no idea what you're asking, closing this tomorrow.
