### ISSUE TITLE
resolving k8s service domain is sometimes slow

### ISSUE THREAD

**Issue by xieyanker** [coredns/coredns#3163]
Hello, I deploy coredns on my k8s cluster 1.14.3, but my pod resolved k8s service domain slowly sometimes.

And I write a tool to test it as follows: 
```shell
vi test_curl:
    time_namelookup:  %{time_namelookup}\n
       time_connect:  %{time_connect}\n
    time_appconnect:  %{time_appconnect}\n
      time_redirect:  %{time_redirect}\n
   time_pretransfer:  %{time_pretransfer}\n
 time_starttransfer:  %{time_starttransfer}\n
                    ----------\n
         time_total:  %{time_total}\n
```
Then I run ` curl -w "@test_curl" -o /dev/null -s -L "<my-service>:<my-port>/healthz"`

I got mostly:
```shell
    time_namelookup:  0.013
       time_connect:  0.013
    time_appconnect:  0.000
      time_redirect:  0.000
   time_pretransfer:  0.013
 time_starttransfer:  0.015
```
but I also can get slowly sometimes:
```shell
    time_namelookup:  5.513
       time_connect:  5.514
    time_appconnect:  0.000
      time_redirect:  0.000
   time_pretransfer:  5.514
 time_starttransfer:  5.515
```
Can you help me what's wrong with it?

> my CoreDNS version: v1.5.0

> my Corefile:

```shell
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 172.16.3.1 {
          policy sequential
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
```

**Comment by chrisohaver** [comment]
Delays in rough increments of 5 seconds generally mean a timeout/retry from the client (5 seconds being the typical client default timeout).  It usually means that packets are occasionally not reaching CoreDNS.  A common cause is a [conntrack race issue](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts).

**Comment by miekg** [comment]
highly likely not a coredns issue.
