### ISSUE TITLE
forward target doesn't show up in fuzzit

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3190]
793bd324999ed301a7437931213dbbb2d766558f added fuzzing for forward, but it doesn't show up as a target in the fuzzit.

**Comment by yevgenypats** [comment]
Hi @miekg, so I think you should first create the target on Fuzzit. But actually I've just added a [feature](https://github.com/fuzzitdev/fuzzit/issues/25#issuecomment-524527443) that will auto-add the targets on Fuzzit via the CLI. I can try do a PullRequest that will use this new feature.

**Comment by miekg** [comment]
Yep, I'm thinking the same; if we add something in a PR it should probably just create the target; I rather go in and *delete* unused targets (or autoprune them on your side) then proactive need to create ones.

**Comment by miekg** [comment]
closing- this is manual for now.
