### ISSUE TITLE
plugin/auto: Number of handles Too many

### ISSUE THREAD

**Issue by Futurefangyuan** [coredns/coredns#3191]
I have 31 zone files，but use lsof to view 420 handles

information:
[root@coredns.a1-60-55.pub.unp /data/coredns/conf]lsof | grep '/data/coredns/zone/' |wc -l
420

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/auto: Numb..." ]
>
>I have 31 zone files，but use lsof to view 420 handles
>
>information:
>[root@coredns.a1-60-55.pub.unp /data/coredns/conf]lsof | grep '/data/coredns/zone/' |wc -l
>420

Does this increase over time?


/plugin: auto

**Comment by Futurefangyuan** [comment]
It increased for a while, then he will automatically come down ，but The more zones, the more handle， It depends on the configuration  of auto reload time

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/auto: ..." ]
>It increased for a while, then he will automatically come down ，but The more zones, the more handle， It depends on the configuration  of auto reload time

Yep, it seems the reload feature of *file* didn't have a Close() on the 
reader...

/plugin: file

**Comment by Futurefangyuan** [comment]
OK,this looks more like an auto plugin that will overload all zones.
Configuration：
bj01 {
  file /data/coredns/zone/bj01
  auto bj01 {
      directory /data/coredns/zone/bj01
      reload 10s
  }
  cache 10
  reload 10s
  log
  errors
}

bre.dz11.com {
  file /data/coredns/zone/bre.dz11.com
  auto bre.dz11.com {
      directory /data/coredns/zone/bre.dz11.com
      reload 10s
  }
  cache 10
  reload 60s
  log
  errors
}

result：
[root@bre-coredns.a1-60-45.own.unp /data/coredns/conf]lsof  |grep /data/coredns/zone
coredns   645768                                    root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768                                    root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01
coredns   645768 645769                             root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768 645769                             root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01
coredns   645768 645770                             root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768 645770                             root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01
coredns   645768 645771                             root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768 645771                             root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01
coredns   645768 645772                             root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768 645772                             root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01
coredns   645768 645773                             root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768 645773                             root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01
coredns   645768 645774                             root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768 645774                             root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01
coredns   645768 645775                             root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768 645775                             root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01
coredns   645768 645776                             root    7r      REG              253,1      1154   37790931 /data/coredns/zone/bre.dz11.com
coredns   645768 645776                             root   10r      REG              253,1     35650   37790932 /data/coredns/zone/bj01

**Comment by miekg** [comment]
if you miss and match *auto* and *file* and `reload` this will surely happen

**Comment by Futurefangyuan** [comment]
Thank you very much, I got the latest code, the test has fixed this bug!

**Comment by miekg** [comment]
perfect! Thanks for testing.
