### ISSUE TITLE
Need document on how to set up gRPC server

### ISSUE THREAD

**Issue by tori3ama** [coredns/coredns#3192]
Hi,

I'm trying to setup CoreDNS client and server to communicate via gRPC, but totally cannot figure out how to. I tried this config for server:

`.grpc://test.com:4343 {
    forward . 8.8.8.8
}`

and this for client on another machine:

`.:4343 {
    grpc . 192.168.1.19:4343 {
        tls_servername test.com
    }
}`

But looks it's not working and no any error printed. For gRPC server, I think we need http2 and https enabled? If so I'd like to use self-signed cert, but don't know where to specify the certs, and how to let client don't check the cert.
I could neither find related article on Google, so could you add some basic instruction on this? Thanks.

**Comment by tori3ama** [comment]
I think I figured out how to use this feature. Server side doesn't need to specify domain, just add one more tls option as described [here](https://github.com/coredns/coredns/tree/master/plugin/tls). And if I don't want to use https, I need to remove tls option for server and tls_servername for client. Thanks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Need document..." ]
>I think I figured out how to use this feature. Server side doesn't need to specify domain, just add one more tls option as described [here](https://github.com/coredns/coredns/tree/master/plugin/tls). And if I don't want to use https, I need to remove tls option for server and tls_servername for client. Thanks.

do you want/need something added to the grpc/README or anywhere else?

**Comment by tori3ama** [comment]
I think grpc/README is a good place to put it, and maybe just copy the example in tls/README is enough?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Need document..." ]
>I think grpc/README is a good place to put it, and maybe just copy the example in tls/README is enough?

can you propose something?
