### ISSUE TITLE
ascii logo

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3225]
I also wanted to print a small logo when coredns is starting up. Nothing too fancy, couple of lines and easily created (with `figlet` or some such).

After playing a tiny amount of time with I have some candidates I like.

~~~
% figlet -f digital CoreDNS
+-+-+-+-+-+-+-+
|C|o|r|e|D|N|S|
+-+-+-+-+-+-+-+
~~~
This can be amended slightly to have a more RFC protocol feel to it.

old style ascii:
~~~
% figlet -f slant CoreDNS
   ______                ____  _   _______
  / ____/___  ________  / __ \/ | / / ___/
 / /   / __ \/ ___/ _ \/ / / /  |/ /\__ \ 
/ /___/ /_/ / /  /  __/ /_/ / /|  /___/ / 
\____/\____/_/   \___/_____/_/ |_//____/  
~~~

Something along these lines,  bonus points for making it look like the actual logo with the styled chain on the left

**Comment by miekg** [comment]
my terminal displays: https://www.compart.com/en/unicode/U+26D3
~~~
⛓CoreDNS
~~~

**Comment by chrisohaver** [comment]
I like the retro slanted one.  But it takes up a lot of space.

The chain (⛓) one is short and sweet.

**Comment by miekg** [comment]
figlet eats that unicode codepoint. I may try to "improve on it" and see what it leads. Afraid if we don't use plain ascii it will looks weird on most consoles

**Comment by johnbelamaric** [comment]
+1 to:

% figlet -f slant CoreDNS
   ______                ____  _   _______
  / ____/___  ________  / __ \/ | / / ___/
 / /   / __ \/ ___/ _ \/ / / /  |/ /\__ \
/ /___/ /_/ / /  /  __/ /_/ / /|  /___/ /
\____/\____/_/   \___/_____/_/ |_//____/
