### ISSUE TITLE
plugin/file: file.(*Zone).All mem leak?

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#3226]
* Version 1.6.2 (Linux AMD64)
* Conf [coredns.conf.txt](https://github.com/coredns/coredns/files/3555255/coredns.conf.txt)
* Log [coredns.log](https://github.com/coredns/coredns/files/3555256/coredns.log)

I've been running CoreDNS 1.3 since late last year without any issues. On Aug 27, 2019, I upgraded to CoreDNS 1.6.2 and overnight had a memory leak and crash. I've had memory leaks before in other parts of CoreDNS and those have been resolved (thanks to @tmthrgd and @miekg) . 

My use case for CoreDNS may be somewhat unique and has been described in another issue in detail: https://github.com/miekg/dns/issues/786

The out of memory issue appears to be caused by github.com/coredns/coredns/plugin/file.(*Zone).All.

https://github.com/coredns/coredns/blob/master/plugin/file/zone.go#L157

Memory use seems to grow by 1 or 2 MB every minute until no memory is left to consume.

At startup:

9627.24kB 21.41% 71.53% 9627.24kB 21.41% github.com/coredns/coredns/plugin/file.(*Zone).All

About 20 minutes later:

17.63MB 33.81% 76.02% 17.63MB 33.81% github.com/coredns/coredns/plugin/file.(*Zone).All

A bit later:

41.13MB 54.38% 54.38% 41.13MB 54.38% github.com/coredns/coredns/plugin/file.(*Zone).All

Just before crashing:

406.62MB 54.94% 54.94% 406.62MB 54.94% github.com/coredns/coredns/plugin/file.(*Zone).All

Also, if anyone cares to, you can grab the heap live here and watch it grow:

http://rpz-master.aws.cloud.iso.vt.edu:6060/debug/pprof/

That is IPv6 only. It does not accept IPv4 connections.

Thanks,

Brad

**Comment by miekg** [comment]
I wonder why it would *leak*.

Alternatively (and better) is to use the Walk function to do this; the z.All() was an easy way to implement this, but there is no good reason for adding them all to a slice and then ranging over the slice.

**Comment by ghost** [comment]
@miekg. My conclusion may be premature and misleading. Here's the whole capture. It ran once a minute until crashing:

[pprof.txt](https://github.com/coredns/coredns/files/3555535/pprof.txt)

   while : ; do sleep 60 && go tool pprof -top http://rpz-master.aws.cloud.iso.vt.edu:6060/debug/pprof/heap >> pprof.txt; done

**Comment by miekg** [comment]
Can you try: https://github.com/coredns/coredns/pull/3227
(if the tests don't fail :) )

**Comment by ghost** [comment]
OK @miekg I just built the pfile branch and am running it. I'll let you know how it goes.

ubuntu@rpz-master:~$ coredns -version
CoreDNS-1.6.2
linux/amd64, go1.12.9, b733ea72

**Comment by miekg** [comment]
.. and? (sorry bit curious)

**Comment by ghost** [comment]
Can't say for sure yet. Seems to be growing slowly in general memory usage, but it took about 18 to 24 hours to crash before the patch, so it may be awhile. You can profile it live if you like: http://rpz-master.aws.cloud.iso.vt.edu:6060/debug/pprof/

That is an IPV6 Only host. No IPV4.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/file: ..." ]
>Can't say for sure yet. Seems to be growing slowly in general memory usage, but it took about 18 to 24 hours to crash before the patch, so it may be awhile. You can profile it live if you like: http://rpz-master.aws.cloud.iso.vt.edu:6060/debug/pprof/
>
>That is an IPV6 Only host. No IPV4.

thanks (don't have time for that today, so I'll just also wait).

This is a good change regardless, but catching leaks it always tricky-ish.

**Comment by ghost** [comment]
OK, I'll report back tomorrow morning. Thanks for the help.

**Comment by miekg** [comment]
might be a leak in the zone impl. My zones are super static so I don't see it.

**Comment by ghost** [comment]
This zone changes once a day (large change) and has several small additions and subtractions throughout the day. I'd say it's somewhat dynamic, but it does not change all that frequently.

**Comment by ghost** [comment]
It's still looking good @miekg, will know for sure tomorrow morning around 6AM US eastern time.

**Comment by miekg** [comment]
Yeah!

**Comment by ghost** [comment]
@miekg this looks good. It's still running with no major memory growth.

**Comment by miekg** [comment]
Very good. Let's merge.

**Comment by ghost** [comment]
Thanks for the time and help @miekg. I appreciate it. If you ever need something tested, let me know. I'd be glad to try things out.

**Comment by miekg** [comment]
Thanks, I'll keep that in mind, real world usage always trumps whatever testing we currently have.

**Comment by ghost** [comment]
This is sort of interesting. Here's the normal 1.6.2 versus the pfile branch after the same period of time (this was just before the normal one crashed):

    0     0% 98.50%    23.50MB  5.25%  github.com/coredns/coredns/plugin/file.(*Zone).Insert
    0     0% 99.19%   316.52MB 42.77%  github.com/coredns/coredns/plugin/file.(*Zone).Insert

    0     0%   100% 20482.79kB 67.80%  github.com/coredns/coredns/plugin/file.(*Zone).Insert
    0     0%   100% 20482.79kB 67.80%  github.com/coredns/coredns/plugin/file.(*Zone).Insert
`

**Comment by miekg** [comment]
this can be closed?

**Comment by ghost** [comment]
Yes, it is still working for me. Thanks.

**Comment by miekg** [comment]
good :)
