### ISSUE TITLE
Logging - How do you enable and write logs? 

### ISSUE THREAD

**Issue by blaines** [coredns/coredns#3228]
I don't know how to enable logging throughout Coredns. What's the purpose of the log package? https://github.com/coredns/coredns/tree/master/plugin/pkg/log

I read conflicting information like this: https://coredns.io/manual/toc/#logging-from-a-plugin
Where in practice I see this: https://github.com/coredns/coredns/blob/master/plugin/azure/setup.go#L18
and this: https://github.com/coredns/coredns/blob/master/plugin/azure/azure.go#L75

Analogous to that, I don't actually see any documentation to enable these logs. Am I missing something?

Additionally, I don't think the logging plugin logs all queries. Perhaps I've misconfigured it:
Corefile
```
. {
    log {
      class all
    }
    forward . 1.1.1.1:53
}
```
I've tried several permutations including `log .` and configurations before and after `forward` (it's unclear if order is important).

I can make requests for invalid names and they simply don't appear at all.

**Comment by miekg** [comment]
The logs plugins is wrongly named, it should have been "querylog". For the
rest you just get logs.

**Comment by chrisohaver** [comment]
As @miekg says, logging from plugins is enabled by default.  The *log* plugin just enables query logging. 

> it's unclear if order is important

It isn't. (edit: I mean to say that the order is not important ... but i guess it's also not clear)

> I can make requests for invalid names and they simply don't appear at all.

Can you give an example?

**Comment by blaines** [comment]
I'll break this up into additional issues if I want to focus more on the query logs. For now looking at plugin logging I had to put `clog.D.Set()` in my plugin code in order for the logs to appear. Is that expected?

**Comment by chrisohaver** [comment]
I have not had to do that.  Following the pattern of other plugins, I define a package level variable named `log` ... e.g. 

```
var log = clog.NewWithPlugin(pluginName)
```

Then log like so ...
```
	log.Warningf("something bad happened: %v", err)
```

`clog.D.Set()` sets debug mode on - so, perhaps you are logging with `log.Debugf(...)`?  The proper way to turn debug on is with the *debug* plugin...

**Comment by blaines** [comment]
Ahhh! 😂 Yes I've been doing DEBUG logging all along and was super confused. Most of the docs around that were about stack traces. Until I read "A side effect of using debug is that log.Debug and log.Debugf messages will be printed to standard output.".

All of this makes much more sense now. Would it help to make some documentation improvements?

**Comment by miekg** [comment]
Doc improvements are always welcome.

**Comment by blaines** [comment]
I've figured out as well https://coredns.io/explugins/dump/ logs all incoming queries, because log doesn't do that. So that solves that mystery as well 😅@chrisohaver 

Thanks for your help today. Minor confusion, but otherwise it's been easy to work with.

**Comment by miekg** [comment]
ok, closing
