### ISSUE TITLE
Include 'Proxy' plugin in the pre-build bundle

### ISSUE THREAD

**Issue by Mr-Sheep** [coredns/coredns#3234]
Hi,
Due to some special internet problem, I cannot build coreDNS on my local machine to use the proxy plugin.
I noticed that proxy is included in some old releases, so can you please include proxy again?

**Comment by JasonSwindle** [comment]
From what I understand, proxy is no more, and is replace by forward.

**Comment by stp-ip** [comment]
Proxy is deprecated and therefore an external plugin. It won't move back into the prebuilt binaries.

You might be able to built this on a server yourself or use the new proxy.golang.org mirror as a workaround, if workable.

/close

**Comment by stp-ip** [comment]
As @JasonSwindle mentioned. Forward is the replacement of proxy.

**Comment by Mr-Sheep** [comment]
I understand that proxy has been deprecated, but since I can't use forward twice in the same block.
How can I separate my dns traffic.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Include 'Prox..." ]
>From what I understand, proxy is no more, and is replace by forward.

proxy has in-efficient (and broken) healthchecking and the code got too complex 
with all the protocol integrations.

It's not coming back.

It's trivial to compile your own coredns with the plugins you want.

/close
