### ISSUE TITLE
[Feature Request] plugin/hosts metrics

### ISSUE THREAD

**Issue by JasonSwindle** [coredns/coredns#3241]
Howdy,

Currently the plugin `hosts` is a bit of a black-box.   You could have an action take place, and there is no way to understand it happens from a metrics or logging point of view.  It would be great to have a metrics around the number of entries loaded in the hosts file, and if possible, how many have been actions on.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] [Feature Request]..." ]
>Howdy,
>
>Currently the plugin `hosts` is a bit of a black-box.   You could have an action take place, and there is no way to understand it happens from a metrics or logging point of view.  It would be great to have a metrics around the number of entries loaded in the hosts file, and if possible, how many have been actions on.

a gauge of the number of entries is useful, last reload timestamp probably as 
well.

**Comment by yeya24** [comment]
I ' d like to help with this.

**Comment by miekg** [comment]
done and merged. Thank you all.
