### ISSUE TITLE
Add http protocol support

### ISSUE THREAD

**Issue by yegle** [coredns/coredns#3257]
I'm glad that CoreDNS have DoH support. But I already have a reverse proxy that handles my TLS termination. It's fine to reverse proxy to CoreDNS over HTTPS but it seems like a waste of resources. 

Would it be possible to also provide http protocol support?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Add http protocol..." ]
>I'm glad that CoreDNS have DoH support. But I already have a reverse proxy that handles my TLS termination. It's fine to reverse proxy to CoreDNS over HTTPS but it seems like a waste of resources.
>
>Would it be possible to also provide http protocol support?

there is no specification for what you ask - assuming with HTTP, you mean HTTP/1?

If you don't need TLS, it might be possible to force if to 'off', but I haven't 
played with that.

/label: enhancement

**Comment by yegle** [comment]
I mean plaintext HTTP. Given there's really no HTTP/2 implementation w/o SSL/TLS yes I mean HTTP/1.

There's no spec for DNS-over-HTTP, but same applies to DNS-over-grpc. What I want is an HTTP server that handles the same payload specified in RFC8484 but without the SSL termination.

I tried to do something like this yesterday but the 80 port does not respond anything:

```
tls://.:853 http://.:80 {
    tls /fullchain.pem /privkey.pem
    forward . 8.8.8.8:53
}
```

Anything else I should try?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add http prot..." ]
>I mean plaintext HTTP. Given there's really no HTTP/2 implementation w/o SSL/TLS yes I mean HTTP/1.

then no.

>There's no spec for DNS-over-HTTP, but same applies to DNS-over-grpc. What I want is an HTTP server that handles the same payload specified in RFC8484 but without the SSL termination.

**Comment by yegle** [comment]
That's unfortunate. Requiring a reverse proxy to talk to backend via HTTPS seems overkill.

**Comment by tmccombs** [comment]
That's unfortunate. I'd like to use coredns behind an AWS ELB that terminates TLS. I use ACM to manage my certificates, so in order to use CoreDNS I would need to obtain a certificate some other way (ACM doesn't give you access to the private key for certificates). Also, not all reverse proxies support http/2 to the backend (for example AWS ALB's don't).
