### ISSUE TITLE
plugin/ens: Ethereum Name Service backend

### ISSUE THREAD

**Issue by mcdee** [coredns/coredns#3275]
The [Ethereum Name Service](https://ens.domains/) provides the ability to store and resolve DNS information using Ethereum as the backend store.

For the purposes of DNS, Ethereum is being used as a multi-master datastore with DNS information for each domain only able to be updated by the domain's owner (or delegate).  The practical upshot of this is:

  - anyone can update their DNS records without relying on a third party's API/webpage/whatever being available
  - anyone can be set up as an authoritative nameserver and serve domain records without having the ability to change the records themselves

The plugin is available at https://github.com/wealdtech/coredns-ens/ and I would like to explore if this would be accepted as a core plugin.  Some reasons why it may not be suitable are:

  - it's pretty big, due to pulling in all of the `go-ethereum` codebase as a dependency
  - it requires `CGO_ENABLED` to be set to `1` to compile (again thanks to `go-ethereum`)

but I'd love to hear your thoughts on if this can be included.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/ens: Ether..." ]
>The [Ethereum Name Service](https://ens.domains/) provides the ability to store and resolve DNS information using Ethereum as the backend store.
>
>For the purposes of DNS, Ethereum is being used as a multi-master datastore with DNS information for each domain only able to be updated by the domain's owner (or delegate).  The practical upshot of this is:
>
>  - anyone can update their DNS records without relying on a third party's API/webpage/whatever being available
>  - anyone can be set up as an authoritative nameserver and serve domain records without having the ability to change the records themselves
>
>The plugin is available at https://github.com/wealdtech/coredns-ens/ and I would like to explore if this would be accepted as a core plugin.  Some reasons why it may not be suitable are:
>
>  - it's pretty big, due to pulling in all of the `go-ethereum` codebase as a dependency
>  - it requires `CGO_ENABLED` to be set to `1` to compile (again thanks to `go-ethereum`)
>
>but I'd love to hear your thoughts on if this can be included.

Interesting plugin!

We're already pulling in most of the Go code written, so adding another big dep 
doesn't sit well with me...

Setting CGO_ENABLED to 1, makes it impossible to include though.

For now putting it up coredns.io/explugins would be good starting point.

**Comment by mcdee** [comment]
Thanks for the response.  I'll close this and raise a PR to include it as an explugin.
