### ISSUE TITLE
When I add configmap to dns, it makes dns server not avalible.

### ISSUE THREAD

**Issue by mclubing** [coredns/coredns#3276]
CoreDNS-1.3.1 in k8s cluster
k8s: 15.3

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        hosts {
          10.110.152.150 jmenv.tbsite.net
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-09-13T15:08:17Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "1874"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 9a862b50-fde8-400a-b823-a3dd7f7efe2a
```

I add hosts into coredns configmap,and the hosts is working good,  then do nslookup kubernetes.default, I realized coredns wasn't working， Is that a bug or I made some mistake?

**Comment by chrisohaver** [comment]
Have you tried the troubleshooting in https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/?

**Comment by mclubing** [comment]
@chrisohaver , I tried, but it didn't work.
That's strange , after I remove hosts, DNS server returned to avabile.

**Comment by chrisohaver** [comment]
When It doesn't work, what do the coredns logs show?

**Comment by chrisohaver** [comment]
You should add a `fallthrough` to *hosts* ... otherwise it would block all upstream queries...
```
        hosts {
          10.110.152.150 jmenv.tbsite.net
          fallthrough
        }
```

but that shouldn't have affected `kubernetes.default` unless you have a client that is ignoring the search domains (as some versions of busybox do).  Does `kubernetes.default.svc.cluster.local.` work?

**Comment by mclubing** [comment]
```
[root@dev-master traefik]# kubectl logs -f coredns-6967fb4995-7vvlg -n kube-system
.:53
2019-09-13T15:08:51.406Z [INFO] CoreDNS-1.3.1
2019-09-13T15:08:51.406Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-09-13T15:08:51.406Z [INFO] plugin/reload: Running configuration MD5 = 5d5369fbc12f985709b924e721217843
[INFO] Reloading
2019-09-13T15:19:46.016Z [INFO] plugin/reload: Running configuration MD5 = b84f08f1e4b0a1015b4a2453069d9abc
[INFO] Reloading complete
[INFO] Reloading
2019-09-13T15:25:49.025Z [INFO] plugin/reload: Running configuration MD5 = 5d5369fbc12f985709b924e721217843
[INFO] Reloading complete
[INFO] Reloading
2019-09-13T16:05:51.536Z [INFO] plugin/reload: Running configuration MD5 = b84f08f1e4b0a1015b4a2453069d9abc
[INFO] Reloading complete
-------------------------------------------------------
[root@dev-master traefik]# kubectl logs -f coredns-6967fb4995-l64l2 -n kube-system
.:53
2019-09-13T15:08:51.414Z [INFO] CoreDNS-1.3.1
2019-09-13T15:08:51.414Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-09-13T15:08:51.414Z [INFO] plugin/reload: Running configuration MD5 = 5d5369fbc12f985709b924e721217843
[INFO] Reloading
2019-09-13T15:19:46.065Z [INFO] plugin/reload: Running configuration MD5 = b84f08f1e4b0a1015b4a2453069d9abc
[INFO] Reloading complete
[INFO] Reloading
2019-09-13T15:26:33.564Z [INFO] plugin/reload: Running configuration MD5 = 5d5369fbc12f985709b924e721217843
[INFO] Reloading complete
[INFO] Reloading
2019-09-13T16:05:40.463Z [INFO] plugin/reload: Running configuration MD5 = b84f08f1e4b0a1015b4a2453069d9abc
[INFO] Reloading complete
```

**Comment by mclubing** [comment]
> You should add a `fallthrough` to _hosts_ ... otherwise it would block all upstream queries...
> 
> ```
>         hosts {
>           10.110.152.150 jmenv.tbsite.net
>           fallthrough
>         }
> ```
> 
> but that shouldn't have affected `kubernetes.default` unless you have a client that is ignoring the search domains (as some versions of busybox do). Does `kubernetes.default.svc.cluster.local.` work?

Wait a minute. Let me try.

**Comment by chrisohaver** [comment]
Oh - actually - it would also block kubernetes too, since hosts comes before kubernetes in [the plugin chain](https://github.com/coredns/coredns/blob/master/plugin.cfg) (order in corefile does not matter).

**Comment by mclubing** [comment]
> Oh - actually - it would also block kubernetes too, since hosts comes before kubernetes in the plugin chain (order in corefile does not matter).

Yeah, it works, 

[root@dev-master traefik]# kubectl exec curl-6bf6db5c4f-rn725 -- nslookup kubernetes.default
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local

**Comment by mclubing** [comment]
By the way, your doggy is cute.~Haha
