### ISSUE TITLE
1.6.4 release tracking

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3283]
1.6.4 release tracking

* acl plugin added
* transfer plugin added (#3223 in progress) 

Very minor polish. Likely do 1.7.0 after this with transfer as a plugin (if that works out) and moving all transfers out of the plugins into this new plugin)

**Comment by JasonSwindle** [comment]
Add PR  #3277 ?  Or is it still too new to be approved?

**Comment by miekg** [comment]
that's already merged, so it will be in 1.6.4

**Comment by miekg** [comment]
this is irritating
~~~
go: github.com/coredns/coredns@v1.6.3 requires
	go.etcd.io/etcd@v0.0.0-20190823073701-67d0c21bb04c requires
	golang.org/x/net@v0.0.0-20190813000000-74dc4d7220e7: invalid pseudo-version: does not match version-control timestamp (2019-08-13T14:13:03Z)
~~~
Think I fixed it in master

**Comment by miekg** [comment]
woohoo!

**Comment by miekg** [comment]
`linux/amd64, go1.13.1, b139ba3-dirty` is the version string. Hmm.

**Comment by miekg** [comment]
released.
