### ISSUE TITLE
Extended health check: recommentation needed

### ISSUE THREAD

**Issue by gorshunovr** [coredns/coredns#3290]
Hello team.
We have a need to verify that CoreDNS can actually resolve certain host names. I have tried to search the code base if this possibility exists, but found out that it does not exists, and that extended health check interface which could help us to do so has been removed in #2547.

Previously we used to use dig & curl utilities included into coredns image, until alpine-based image has been changed to a debian-based image in #1843. Currently coredns image contains only /etc/ssl/certs and coredns binary itself.

What would be a suggested solution to verify that CoreDNS can actually resolve host names? At the moment we have opted out to build our own sidecar which provides us health checks to the coredns container.

The coredns image we use remains to be a standard upstream image, because it is public and trusted, we didn't want to maintain own rebuilt clone of coredns which would include additional utilities (e.g. dig & curl) and look suspicious to our users.

Thank you.

**Comment by miekg** [comment]
I'm assuming you're concern is focused on the forward plugin, because anything else is mostly dealt with in process.

There are many reasons why an upstream resolve can fail. They way you propose to do thing (and why that code was removed in the first place), is to tie *all individual* coredns instances' health to a shared resource. When that resource goes away all your instances will go unhealthy, while they probably could have limped along serving from caches.

Probing a few interesting names and having that probe export its finding (as promethus metrics?) and setting up your normal dashboarding and alerting pipeline makes sense though.

**Comment by gorshunovr** [comment]
Yes, that's primarily about forward plugin. Don't quote me on that, as I lack knowledge of details of failures we face which are solved by coredns pod restart. When coredns fails to resolve name, it could be coredns problem, network connectivity issue within the cluster or outside of the cluster, or it could be upstream DNS servers failure. Some coredns pod instances continue to work fine at the same time.

Solution with pod restart seems to be an overkill done instead of careful evaluation of what is the real cause of the issue, I admit.

Thank you for your responce, @miekg Miek. And many thanks for a suggestion to get some metrics from dig utility for possible establishment of a baseline, monitoring & alerting.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Extended heal..." ]
>Yes, that's primarily about forward plugin. Don't quote me on that, as I lack knowledge of details of failures we face which are solved by coredns pod restart. When coredns fails to resolve name, it could be coredns problem, network connectivity issue within the cluster or outside of the cluster, or it could be upstream DNS servers failure. Some coredns pod instances continue to work fine at the same time.

I would very much like to learn what you're hitting here, something like this 
should def. be fixed (if it's an actual issue). There can be many reasons, one 
of them being that coredns is screwing up.

>Thank you for your responce, @miekg Miek. And many thanks for a suggestion to get some metrics from dig utility for possible establishment of a baseline, monitoring & alerting.

np
