### ISSUE TITLE
plugin/rewrite Not working in k8s

### ISSUE THREAD

**Issue by SergeSpinoza** [coredns/coredns#3298]
Hi.

CoreDNS version: 1.6.0
Kubernetes version: v1.15.3 (Bare metal, installed via kubespray). 

I try to use rewrite plugin. I add to ConfigMap core dns: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        rewrite stop {
          name regex (.*)\.my\.domain\.$ {1}.navigator32-services-stage.svc.cluster.local
          answer name (.*)\.navigator32-services-stage\.svc\.cluster\.local\.$ {1}.my.domain
        }  
        ready
        # rewrite name nats-stage-client.my.domain nats-stage-client.navigator32-services-stage.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
```

I apply this manifest and restart coredns.

Then I try command (for example): `host nats-stage-client.my.domain` 

and I see in logs: 

```
.:53
2019-09-23T13:42:06.222Z [INFO] plugin/reload: Running configuration MD5 = daa664635e18fdc499460ac35f7d5650
2019-09-23T13:42:06.223Z [INFO] CoreDNS-1.6.0
2019-09-23T13:42:06.223Z [INFO] linux/amd64, go1.12.7, 0a218d3
CoreDNS-1.6.0
linux/amd64, go1.12.7, 0a218d3
2019-09-23T14:17:21.942Z [INFO] 10.233.122.0:37076 - 58005 "A IN nats-stage-client.my.domain.default.svc.cluster.local. tcp 71 false 65535" NXDOMAIN qr,aa,rd 164 0.000288025s
2019-09-23T14:17:21.947Z [INFO] 10.233.122.0:37076 - 23634 "A IN nats-stage-client.my.domain.svc.cluster.local. tcp 63 false 65535" NXDOMAIN qr,aa,rd 156 0.002472497s
2019-09-23T14:17:21.949Z [INFO] 10.233.122.0:37076 - 10253 "A IN nats-stage-client.my.domain.cluster.local. tcp 59 false 65535" NXDOMAIN qr,aa,rd 152 0.000340663s
```

I see that rewrite is not work. What could be the problem?

Thanks.

**Comment by chrisohaver** [comment]
In the host command `host nats-stage-client.my.domain`, the name is not fully qualified (no trailing dot), so the search domain list from `/etc/resolv.conf` is used.  This results in queries for ...

nats-stage-client.my.domain.**default.svc.cluster.local.**
nats-stage-client.my.domain.**svc.cluster.local.**
nats-stage-client.my.domain.**cluster.local.**

Those don't match the rewrite rule.

After querying for those, the pod making the query should try the bare name `nats-stage-client.my.domain.`.  But thats not showing up in the log.

If you have multiple coredns instances, are you checking both logs?

**Comment by SergeSpinoza** [comment]
> In the host command `host nats-stage-client.my.domain`, the name is not fully qualified (no trailing dot), so the search domain list from `/etc/resolv.conf` is used. This results in queries for ...
> 
> nats-stage-client.my.domain.**default.svc.cluster.local.**
> nats-stage-client.my.domain.**svc.cluster.local.**
> nats-stage-client.my.domain.**cluster.local.**
> 
> Those don't match the rewrite rule.
> 
> After querying for those, the pod making the query should try the bare name `nats-stage-client.my.domain.`. But thats not showing up in the log.


If I try `host nats-stage-client.my.domain.` - the logs is empty. 

> If you have multiple coredns instances, are you checking both logs?

Yes, I check both pod logs.

**Comment by chrisohaver** [comment]
I tested your rewrite stanza, and it works for me.

**Comment by SergeSpinoza** [comment]
> I tested your rewrite stanza, and it works for me.

Maybe I need to enable rewrite plugin? How can I verify that it is enabled?

**Comment by chrisohaver** [comment]
No, its enabled by default.

When you query `nats-stage-client.my.domain.` what response do you get?

**Comment by SergeSpinoza** [comment]
> No, its enabled by default.
> 
> When you query `nats-stage-client.my.domain.` what response do you get?

```
# host nats-stage-client.my.domain.
Host nats-stage-client.my.domain. not found: 3(NXDOMAIN)
```

**Comment by chrisohaver** [comment]
And to verify, 
you get an answer for `nats-stage-client.navigator32-services-stage.svc.cluster.local.` ?

**Comment by SergeSpinoza** [comment]
> nats-stage-client.navigator32-services-stage.svc.cluster.local.

Yes, it's works: 

```
# host nats-stage-client.navigator32-services-stage.svc.cluster.local.
nats-stage-client.navigator32-services-stage.svc.cluster.local has address 10.233.5.157
```

**Comment by SergeSpinoza** [comment]
In logs: 

```
2019-09-23T18:14:24.841Z [INFO] 10.233.122.0:40192 - 43614 "A IN nats-stage-client.navigator32-services-stage.svc.cluster.local. tcp 80 false 65535" NOERROR qr,aa,rd 158 0.000525246s
2019-09-23T18:14:24.844Z [INFO] 10.233.122.0:40192 - 30903 "AAAA IN nats-stage-client.navigator32-services-stage.svc.cluster.local. tcp 80 false 65535" NOERROR qr,aa,rd 173 0.000225972s
2019-09-23T18:14:24.845Z [INFO] 10.233.122.0:40192 - 31660 "MX IN nats-stage-client.navigator32-services-stage.svc.cluster.local. tcp 80 false 65535" NOERROR qr,aa,rd 173 0.000200545s
```

**Comment by chrisohaver** [comment]
If you drop the number of coredns replicas to 1, do you see the same behavior?

**Comment by SergeSpinoza** [comment]
I also tried to make a request directly to the CoreDNS through a `dig` - below I publish the server response. The logs are also empty.

```
# cat /etc/resolv.conf
nameserver 169.254.25.10
search default.svc.cluster.local svc.cluster.local cluster.local office.local
options ndots:5
```

```
# dig @169.254.25.10 nats-stage-client.my.domain. A

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @169.254.25.10 nats-stage-client.my.domain. A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 53446
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
; COOKIE: 5333b140ed125aa9 (echoed)
;; QUESTION SECTION:
;nats-stage-client.my.domain.	IN	A

;; AUTHORITY SECTION:
.			30	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2019092300 1800 900 604800 86400

;; Query time: 2 msec
;; SERVER: 169.254.25.10#53(169.254.25.10)
;; WHEN: Mon Sep 23 18:19:44 UTC 2019
;; MSG SIZE  rcvd: 143
```

**Comment by SergeSpinoza** [comment]
> If you drop the number of coredns replicas to 1, do you see the same behavior?

Yes, I have the same problem.

**Comment by chrisohaver** [comment]
> If I try host nats-stage-client.my.domain. - the logs is empty.

Strange.  I must be missing something. I cannot figure out how you are getting an NXDOMAIN, but that response is not logged in CoreDNS logs.

**Comment by SergeSpinoza** [comment]
> > If I try host nats-stage-client.my.domain. - the logs is empty.
> 
> Strange. I must be missing something. I cannot figure out how you are getting an NXDOMAIN, but that response is not logged in CoreDNS logs.

Maybe this is due to the variables in the kubespray, when I install a cluster?

```
# DNS configuration.
# Kubernetes cluster name, also will be used as DNS domain
cluster_name: cluster.local
# Subdomains of DNS domain to be resolved via /etc/resolv.conf for hostnet pods
ndots: 2
# Can be coredns, coredns_dual, manual or none
dns_mode: coredns
# Set manual server if using a custom cluster DNS server
# manual_dns_server: 10.x.x.x
# Enable nodelocal dns cache
enable_nodelocaldns: true
nodelocaldns_ip: 169.254.25.10
nodelocaldns_health_port: 9254
# Enable k8s_external plugin for CoreDNS
enable_coredns_k8s_external: false
coredns_k8s_external_zone: k8s_external.local
# Enable endpoint_pod_names option for kubernetes plugin
enable_coredns_k8s_endpoint_pod_names: false
```

**Comment by chrisohaver** [comment]
Ah... `enable_nodelocaldns: true` ... you have node local cache deployed in your cluster...

This is why.

With node local, any queries that are not for `cluster.local` get sent straight up to the upstream servers, and do not go to the cluster dns (coredns)...

**Comment by SergeSpinoza** [comment]
This is the default kubespray setting. Is it possible to somehow change? Or is this set only during cluster installation?

**Comment by chrisohaver** [comment]
I'm not familiar with kubespray.  I'm also only superficially familiar with node-local-dns.  
Node-local-dns deploys a slimmed down version of coredns on each node.  The full version of coredns still runs in the cluster to (only) answer `cluster.local.` queries. I dont know if the coredns's that run on each node have the rewrite plugin compiled into them.  If they do, then you should be able to add that rewrite rule to their configmap (I'm assuming they all share a configmap).

**Comment by SergeSpinoza** [comment]
Ok. Thanks. I try to do this and will write on this thread.

**Comment by chrisohaver** [comment]
the configmap for node local dns is here i think... 
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml#L29

Try adding your re-write rule to that. The node local dns pods will crash if they dont have the rewrite plugin compiled in.

**Comment by SergeSpinoza** [comment]
Yes, nodelocaldns has no rewrite plugin...

Logs: 
```
no action found for directive 'rewrite' with server type 'dns' (missing a plugin?)
```

**Comment by chrisohaver** [comment]
I'm surprised it's not included, for this reason.
You can try altering the node local dns daemonset to use a full versioned coredns instead.  It's not immediately obvious what version of coredns it's built from, since the project uses a versioning unrelated to coredns's versioning.  I do recall that version used is a bit old.

**Comment by chrisohaver** [comment]
OK, I dug a bit, and looks like they are vendoring coredns 1.2.6... (not a typo of 1.6.2)

https://github.com/kubernetes/dns/blob/master/Gopkg.lock#L80

... which is quite old indeed.

**Comment by SergeSpinoza** [comment]
In Daemonset https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml they use `image: k8s.gcr.io/k8s-dns-node-cache:1.15.3` of nodelocaldns

**Comment by chrisohaver** [comment]
> they use image: k8s.gcr.io/k8s-dns-node-cache:1.15.3 of nodelocaldns

Yes, that is their own versioning though.  It is is built from a base of coredns, that they modify to remove some plugins (to reduce the size i presume).

The vendoring in the project shows that they are using coredns 1.2.6 iiuc.

**Comment by johnbelamaric** [comment]
well, it also adds code for managing conntrack etc. They have tried updating to a newer CoreDNS but are having some issues:

https://github.com/kubernetes/dns/issues/306

**Comment by chrisohaver** [comment]
IOW, if you want to replace it with a full version of coredns, and want to keep the same coredns version, you should replace it with coredns 1.2.6.

There is a reason the project has not updated to a more recent version of coredns... https://github.com/kubernetes/dns/issues/306.

**Comment by chrisohaver** [comment]
> well, it also adds code for managing conntrack etc. 

Ah, yes, here...
https://github.com/kubernetes/dns/tree/master/cmd/node-cache/app

**Comment by SergeSpinoza** [comment]
That is, it turns out then that I need to find an option to disable nodelocaldns, and use only full coreDNS.

**Comment by chrisohaver** [comment]
yes - swapping out for a full version would not work because the nodelocaldns does special things that the stock version of coredns does not do.

So, looks like you need to disable nodelocaldns.

Or if you need nodelocaldns for dns reliability, compile your own version of nodelocaldns with rewrite included. https://github.com/kubernetes/dns/blob/master/cmd/node-cache/main.go

**Comment by SergeSpinoza** [comment]
I came up with the following solution: need to change configmap of nodelocaldns (`kubectl get configmap nodelocaldns -n kube-system -o yaml > nodelocaldns.yaml` and change 

```
.......

.:53 {
        errors
        cache 30
        reload 
        loop
        bind 169.254.25.10
        forward . /etc/resolv.conf
        prometheus :9253
    }
```

to 

```
.....

.:53 {
        errors
        cache 30
        reload 
        loop
        bind 169.254.25.10
        forward . 10.233.0.3 {
            force_tcp
        }
        prometheus :9253
    }

```

then apply it `kubectl apply -f nodelocaldns.yaml`, 

and after that the rewrite rules start to work.
