### ISSUE TITLE
plugin/cache: Save Cache to disk for hot start

### ISSUE THREAD

**Issue by JasonSwindle** [coredns/coredns#3299]
Howdy,

Having the option to save the cache to disk for faster start-ups or better handling from an outage would be wonderful.   Something like Redis does with RDB or so.   Thanks for the great software! :D

**Comment by miekg** [comment]
the are several reason why this would not always work; foremost running in docker/k8s you only have an ephemeral disk, so on restart nothing is cached.

I think a better approach is #3158

**Comment by stp-ip** [comment]
There is a redis cache backend available as an external plugin, which should do what you want: https://coredns.io/explugins/redisc/

Additionally as miek mentioned stale record serving would help with backend (non redis in this case) outages as well.
