### ISSUE TITLE
Proposal for managing whitelists and blacklists

### ISSUE THREAD

**Issue by blaines** [coredns/coredns#3306]
I've put together a spec for a plugin to manage whitelists and blocklists. It seems this has been requested (#2267 #2976) or done (#1934 https://github.com/coredns/policy https://github.com/miekg/block) several times already! So why don't these plugins or ideas solve _my_ problem?

- Configurable whitelist _and_ blacklist capability
- Multiple sources: Initially Corefile based and secondary file based
- Not _only_ remote file support (curl and wget are fine until that needs to be implemented)
- Logging to support an audit trail of allowed or blocked requests (I didn't cover that in my spec though)
- Metrics to enable monitoring of performance and policy outcome
- Simplicity, of logic and configuration

This isn't meant to be particularly a security solution, ad blocker, or privacy defender, but it could be used for those cases.

**What am I asking for?**
I'm trying to avoid lobbing a giant PR into the project and seeking feedback on this idea as a plugin and it's usefulness to the CoreDNS ecosystem.

**Here's my README I'm proposing for the plugin:**
https://github.com/blaines/coredns-lists/blob/master/README.md

If you read this give me a 🎉 if you like it. I'd love to hear feedback.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Proposal for mana..." ]
>Here's my README I'm proposing for the plugin:
>https://github.com/blaines/coredns-lists/blob/master/README.md

that looks nice. The crux of the out-sourcing of getting the lists - yes, using 
wget works, but most folks would expect it to be all managed by CoreDNS. Moving 
that behavior into CoreDNS is where the tricky bit starts because you can't be 
guaranteed you can actually resolve names.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Proposal for mana..." ]
>Here's my README I'm proposing for the plugin:
>https://github.com/blaines/coredns-lists/blob/master/README.md

I like this README driven development, I usually try to do the same :-)

**Comment by blaines** [comment]
Thanks!
> Moving that behavior into CoreDNS is where the tricky bit starts because you can't be guaranteed you can actually resolve names.

Agreed, for the first rev I just want to support a local file and Corefile. Later I'd like to expand on that to compose lists from remote and local sources. For my current needs I already distribute my whitelist file along with CoreDNS, but I expect that to change.

**Comment by miekg** [comment]
This works. Note for the plugin to be included, I expect the updating of the blocklist to be done by *coredns*.

**Comment by blaines** [comment]
Just a quick update, we're working on this! I'll be following up as development progresses, and I'll try to get it public for your review as well.

**Comment by miekg** [comment]
We'll see a PR when we see. Closing this issues for now.

**Comment by stone-z** [comment]
As this is still one of the top search results for coredns blacklisting, for anyone interested, we made a plugin for alerting (but not blocking) on prohibited domains. It's a side project, so no warranty provided, but maybe it will meet someone's use case
https://github.com/giantswarm/coredns-malicious-domain-plugin

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Proposal for ..." ]
>As this is still one of the top search results for coredns blacklisting, for
>anyone interested, we made a plugin for alerting (but not blocking) on
>prohibited domains. It's a side project, so no warranty provided, but maybe it
>will meet someone's use case
>https://github.com/giantswarm/coredns-malicious-domain-plugin

nice. I can put it on coredns.io/explugins if you want?
(or you can raise a PR yourself?)

/Miek

--
Miek Gieben

**Comment by calwalker1** [comment]
Hi I am just resurrecting this thread as I am looking for how best to manage an allowlist/whitelist using CoreDNS.
I am attempting to make a DNS server that resolves all queries to NXDOMAIN apart from queries related to *.example.com. I can see forward has the **except** function which is perfect but is the _opposite_ of what I need to achieve this. I need something like ONLY.
such as:
`forward . 8.8.8.8 {`
`only *.example.com`
`}`
