### ISSUE TITLE
plugin/etcd: using root zone causes invalid dns name

### ISSUE THREAD

**Issue by yelhouti** [coredns/coredns#3316]
Coredns: 1.6.0 (tried also 1.6.2 and 1.6.3)
Corefile:
```
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        etcd . {
          endpoint https://<MY_PUBLIC_IP>:2379
          tls /tls/etcd/cert.pem /tls/etcd/key.pem /tls/etcd/ca.crt
          fallthrough .
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }

```

each 3 seconds I get on the Logs:
[ERROR] plugin/errors: 2 ns.dns.. NS: dns: bad rdata

Any idea on what my be doing this? thanks

**Comment by chrisohaver** [comment]
If you add the _log_ plugin, we might be able to see the error correlated to a recurring query/response.  That _etcd_ is authoritative for `.` seems suspicious...

**Comment by yelhouti** [comment]
@chrisohaver thank for your answer, indead the public_ip request fails, but this should not raise CPU usage to 200%, or Am I missing something?

**Comment by chrisohaver** [comment]
What is a `epublie_ip` request? 

And why do you need etcd to be authoritative for all zones?

**Comment by chrisohaver** [comment]
`epublie_ip` -> `public_ip` ?

Can you share the log after enabling the log plugin?

**Comment by yelhouti** [comment]
typo: `public_ip` 
I'm trying to use external_dns to automatically expose services... 
I disbaled external_dns and remove the public_ip entry the server now works well, but again my server shouldn't crash because another dns server is not reachable

**Comment by yelhouti** [comment]
PS: @chrisohaver thanks for the amazing reactivity

**Comment by chrisohaver** [comment]
Try exposing them within a domain.  As your corefile is now, you are exposing etcd services on the root domain. e.g.  `etcd my.domain {`

**Comment by yelhouti** [comment]
@chrisohaver I would like them to be publically available (these are public domains)
As far as I know, the external-dns container uses another Coredns internally, does what you say, it exposes, domain1.com and domain2.com with my public_ip and the rest is redirect to resolv.conf or some other default

**Comment by miekg** [comment]
the change in *etcd* is probably to use dnsutil.Join instead of blindly adding a "."  to a name. I haven't looked in the code though (and I'm too busy to actually do so)

**Comment by Mumie-hub** [comment]
This problem still exists. For everyone stumbling over this. There is a workaround with the view plugin.
Use the view plugin to not "forward" NS queries to the etcd plugin like so:
```yaml
example.com:53 {
    view default {
      expr type() not in ['A', 'AAAA']
    }
    forward . 1.1.1.1
    cache 30
    loop
    log
}
example.com:53 {
    view etcd {
      expr type() in ['A', 'AAAA']
    }
    etcd example.com {
        fallthrough
        path /skydns
        endpoint http://etcd-service:2379
    }
    forward . 1.1.1.1
    cache 30
    loop
    log
}
```
I hope that helps someone.

**Comment by matthieugouel** [comment]
Thank you, @Mumie-hub, your workaround saved my evening 🙏

I've done a similar approach to have etcd handling A/AAAA record and fallback to a file db if it cannot respond. 
To make it work with NS records as well I used your technique. 

```
   example.com:53 {
      log
      errors
      view etcd {
        expr type() in ['A', 'AAAA']
      }
      etcd {
        endpoint http://[2a06:de00:50:1::f094]:2379
        path /skydns
        fallthrough
      }
      forward . [::1]:5353
   }

   example.com:53 {
     log
      errors
      view etcd {
        expr type() not in ['A', 'AAAA']
      }
      forward . [::1]:5353
   }

   example.com:5353 {
      log
      errors
      file /etc/coredns/db.example.com
   }

  db.example.com: |
   example.com.              IN    SOA   ns.example.com. hostmaster.example.com. (
            2003080800 ; sn = serial number
            172800     ; ref = refresh = 2d
            900        ; ret = update retry = 15m
            1209600    ; ex = expiry = 2w
            3600       ; nx = nxdomain ttl = 1h
            )
   @                            IN          NS          ns0.example.com.
   @                            IN          NS          ns1.example.com.
   ns0.example.com.          IN          AAAA        2a06:de00:50:1::f099
   ns1.example.com.          IN          AAAA        2a06:de00:50:1::f099
```
