### ISSUE TITLE
version string in 1.6.4

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3318]
The version string in 1.6.4 is `linux/amd64, go1.13.1, b139ba3-dirty`

Adding the `-dirty` string is a non-feature we can live without, so we should just remove the entirely.

**Comment by yongtang** [comment]
This is likely due to some files are regenerated during the `make` and git is dirty. Wondering if `make gen` has been triggered?

**Comment by miekg** [comment]
I think that's called from the script: https://github.com/coredns/release/blob/master/release-coredns

But, as said, the whole *dirty* is a bit non-sensical

**Comment by yongtang** [comment]
Yes the name is a little annoying. And we should make sure the release process have no side effort of dirty files, so that user could reproduce the binary from the source code of a git commit (matching the release version) clean.
