### ISSUE TITLE
Documentation for k8s compatibility?

### ISSUE THREAD

**Issue by robertrbruno** [coredns/coredns#3320]
I wanted to see if there was any documentation on what the earliest version of k8s a version of coredns is compatible with?  Right now for instance I am running k8s v1.13.1 with coredns 1.2.6.  I recently had a major issue with coredns and wanted to upgrade coredns to the latest, but wasn't sure if that is a safe thing to do.

Thanks!

**Comment by chrisohaver** [comment]
The latest version of CoreDNS should work in k8s 1.13.1.  The latest version of CoreDNS that has been officially tested/approved in k8s is 1.6.2 (in k8s 1.16 release cycle).

There are some Corefile compatibility issues within CoreDNS when upgrading.  Some plugins and options have become deprecated and removed between CoreDNS versions, for example *proxy* has been removed and replaced with *forward*.  There's a k8s oriented tool to help migrate your Corefile: See https://github.com/coredns/corefile-migration/tree/master/corefile-tool.
