### ISSUE TITLE
plugin/forward: this plugin can only be used once per Server Block

### ISSUE THREAD

**Issue by yun** [coredns/coredns#3350]
Using CoreDNS-1.6.3

Since the `proxy` plugin has been deprecated I have converted my configuration to use the `forward` plugin. However only one `forward` config entry can be defined in a server block.

I used the proxy plugin to securely allow and delegate internal domain names to the correct upstream servers. Basically only whitelisting known domain names. Eg:

```
:53 {
    bind 192.168.6.1

    proxy dev.internal.lan 192.168.1.10 192.168.1.11
    proxy intranet.internal.lan 172.16.10.10 172.16.10.20
}
```
By changing the `proxy` plugin to `forward` will now result into the following error:

> plugin/forward: this plugin can only be used once per Server Block

I would like to see support for multiple `forward` plugin declarations. Or maybe there is some other way I can accomplish this that I have been doing with the `proxy` plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/forward: t..." ]
>```
>:53 {
>    bind 192.168.6.1
>
>    proxy dev.internal.lan 192.168.1.10 192.168.1.11
>    proxy intranet.internal.lan 172.16.10.10 172.16.10.20
>}
>```

split up your Corefile and have a section for dev and intranet

this WAI (currently) as the documenation says.

**Comment by yun** [comment]
Thanks,

I converted it to:

```
dev.internal.lan:53 {
    bind 192.168.6.1
    forward . 192.168.1.10 192.168.1.11
}

intranet.internal.lan:53 {
    bind 192.168.6.1
    forward . 172.16.10.10 172.16.10.20
}
```

This seems to work. I'm closing the issue as this will work for my use case.

**Comment by VeeeneX** [comment]
Seems like it's supported now: https://coredns.io/plugins/forward/ not sure from which version of CoreDNS, though.

**Comment by chrisohaver** [comment]
1.10.1
