### ISSUE TITLE
1.6.5 tracking

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3352]
Opening tracking bug for 1.6.5 - some nice fixed have been merged, several others or pending. miekg/dns also saw some improvements.

Aiming to do a release within 2 weeks (or so)

**Comment by oxddr** [comment]
@miekg, is there any expected timeline for this release to happen?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] 1.6.5 trackin..." ]
>@miekg, is there any expected timeline for this release to happen?

I can release it this week. Master is mostly release ready at any point in time.

**Comment by oxddr** [comment]
That'd be great. I'll track this issue for updates.

**Comment by miekg** [comment]
There are some PR that would be nice to merge, but those can be deferred until the next release.

**Comment by miekg** [comment]
and https://coredns.io/2019/11/05/coredns-1.6.5-release/ done as well.

**Comment by oxddr** [comment]
That was quick, thanks @miekg!
