### ISSUE TITLE
[question] Etcd A record returns inaccurate results

### ISSUE THREAD

**Issue by mritd** [coredns/coredns#3361]
I am trying to redevelop coredns and I have questions when using the etcd plugin:

When I set the `a.xxx.node` record value to `1.1.1.1`

`etcdctl put /coredns/node/xxx/a '{"host":"1.1.1.1","ttl":60}'`

I use the dig command to query a.xxx.node to return the correct result.

``` sh
➜  dig @192.168.2.2 -p 5555 a.xxx.node

; <<>> DiG 9.10.6 <<>> @192.168.2.2 -p 5555 a.xxx.node
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30656
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;a.xxx.node.                    IN      A

;; ANSWER SECTION:
a.xxx.node.             1       IN      A       1.1.1.1

;; Query time: 5 msec
;; SERVER: 192.168.2.2#5555(192.168.2.2)
;; WHEN: Sat Oct 05 21:47:59 CST 2019
;; MSG SIZE  rcvd: 65
```

But when I use the dig command to query xxxx.node, **it will also return results.**

``` sh
➜ dig @192.168.2.2 -p 5555 xxx.node

; <<>> DiG 9.10.6 <<>> @192.168.2.2 -p 5555 xxx.node
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39315
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;xxx.node.                      IN      A

;; ANSWER SECTION:
xxx.node.               1       IN      A       1.1.1.1

;; Query time: 8 msec
;; SERVER: 192.168.2.2#5555(192.168.2.2)
;; WHEN: Sat Oct 05 21:48:26 CST 2019
;; MSG SIZE  rcvd: 61
```

I looked at the code. When the etcd plugin executes the [Services](https://github.com/coredns/coredns/blob/b139ba34f370a4937bf76e7cc259a26f1394a91d/plugin/etcd/etcd.go#L44) method, `exact` is always false, causing the recursive lookup after the etcd data directory is queried.

**My question is:**

The dig command query `xxx.node` returned the correct result of `a.xxx.node`? This is expected behavior from the code design, but I don't understand why it is done?

According to my understanding, all subdomain queries should return me accurate results. Can anyone help me with this question?

**Comment by mritd** [comment]
I noticed that the Service method annotations defined in the ServiceBackend interface are as follows:

``` golang
// ServiceBackend defines a (dynamic) backend that returns a slice of service definitions.
type ServiceBackend interface {
	// Services communicates with the backend to retrieve the service definitions. Exact indicates
	// on exact match should be returned.
	Services(ctx context.Context, state request.Request, exact bool, opt Options) ([]msg.Service, error)

	// Reverse communicates with the backend to retrieve service definition based on a IP address
	// instead of a name. I.e. a reverse DNS lookup.
	Reverse(ctx context.Context, state request.Request, exact bool, opt Options) ([]msg.Service, error)

	// Lookup is used to find records else where.
	Lookup(ctx context.Context, state request.Request, name string, typ uint16) (*dns.Msg, error)

	// Returns _all_ services that matches a certain name.
	// Note: it does not implement a specific service.
	Records(ctx context.Context, state request.Request, exact bool) ([]msg.Service, error)

	// IsNameError return true if err indicated a record not found condition
	IsNameError(err error) bool

	Transferer
}
```

But the Services method implemented by etcd plugin simply calls the Records method, and the call to the exact parameter is reversed, causing a recursive search for the etcd directory.

``` golang
// Services implements the ServiceBackend interface.
func (e *Etcd) Services(ctx context.Context, state request.Request, exact bool, opt plugin.Options) (services []msg.Service, err error) {
	services, err = e.Records(ctx, state, exact)
	if err != nil {
		return
	}

	services = msg.Group(services)
	return
}
```

**Comment by miekg** [comment]
this is by design, if the documentation isn't clear, please (if possible) and a PR

**Comment by mritd** [comment]
@miekg Where can I find the design documentation for this part, I want to know why this is the case, such as the design of the ServiceBackend interface.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] [question] Et..." ]
>@miekg Where can I find the design documentation for this part, I want to know why this is the case, such as the design of the ServiceBackend interface.

This is how SkyDNS worked, there is no design doc

**Comment by mritd** [comment]
Can I understand that this is designed to be compatible with skydns?

**Comment by miekg** [comment]
Have you read the readme, it's literally the first thing mentioned?

**Comment by mritd** [comment]
Ok, let me check the design documentation for skydns.
