### ISSUE TITLE
proxy function need to bring back to the latest verion

### ISSUE THREAD

**Issue by echowings** [coredns/coredns#3368]
## **CoreDNS version**: 1.6.4

##Corefile:
```
.:53 {
    forward . 8.8.8.8 9.9.9.9 {
        except baidu.com
    }
    log
    errors
    proxy . 114.114.114.114 {
    }
}

```
I got error like this

```
Attaching to coredns
coredns    | /root/Corefile:5 - Error during parsing: Unknown directive 'proxy'
coredns    | /root/Corefile:5 - Error during parsing: Unknown directive 'proxy'
coredns    | /root/Corefile:5 - Error during parsing: Unknown directive 'proxy'
coredns    | /root/Corefile:5 - Error during parsing: Unknown directive 'proxy'
coredns    | /root/Corefile:5 - Error during parsing: Unknown directive 'proxy'
coredns    | /root/Corefile:5 - Error during parsing: Unknown directive 'proxy'
coredns    | /root/Corefile:5 - Error during parsing: Unknown directive 'proxy'
```
Is that possible to bring proxy function back to latest version ?  I want to anti-dns pollution with this function.  till now, i have to only reverse back to coredns 1.4.0 to let it works.

**Comment by stp-ip** [comment]
The `forward` plugin is the current iteration of proxy and should work similar enough to proxy.

Why do you need both forward and proxy at the same time within your setup and your corefile?

We decided that proxy won't make it back into the main CoreDNS versions, but you can always compile it in as it's available as an external plugin as a workaround.

**Comment by echowings** [comment]
I find another way to do with it

```shell
dev.internal.lan:53 {
    bind 192.168.6.1
    forward . 192.168.1.10 192.168.1.11
}

intranet.internal.lan:53 {
    bind 192.168.6.1
    forward . 172.16.10.10 172.16.10.20
}
```

**Comment by echowings** [comment]
I need the feature to do anti-dns pollution. like domain names out of china, I will forward it to open dns server. Domain names in china  will forward to dns server in china. 

```bash
. {
    forward . 208.67.222.222 208.67.220.220 {
        except baidu.com
    }


}

baidu.com:53 {
    forward . 114.114.114.114
}
~
```

**Comment by stp-ip** [comment]
As you mentioned forward should work fine and also be more performant in the long run.

**Comment by johnbelamaric** [comment]
The `except` isn't really needed, because the baidu.com queries will be
directed to the second stanza anyway.
