### ISSUE TITLE
how to check debug plugin output

### ISSUE THREAD

**Issue by adamzhangsm** [coredns/coredns#3371]
CoreDNS 1.3.1

Enable debug and log plugin. But don't see any debug information in the CoreDNS log.
May I know where to check this pkg/debug log?  

here is yaml file for coredns-custom
apiVersion: v1
data:
  test.override: |
    log
    **debug**
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system

**Comment by miekg** [comment]
There is no debugging in the kubernetes plugin, so nothing will show, what do 
you want to be printed (so we can add some)

/plugin: kubernetes
/label: enhancement

**Comment by sharmaansh21** [comment]
I can work on this if we have a clear understanding of what needs to done :)

**Comment by miekg** [comment]
I don't know/understand what needs to be done here.
