### ISSUE TITLE
Remove CoreDNS ASCII logo printed on startup

### ISSUE THREAD

**Issue by yannh** [coredns/coredns#3374]
This is in relation to: https://github.com/coredns/coredns/issues/3225

I'd like to point out the way many (most?) people will be confronted to this feature is not by starting CoreDNS in a console, but by looking at their logs in their logging system. So I found this line in our logging system:

 log: / /___/ /_/ / /  /  __/ /_/ / /|  /___/ / 

It took me a frustrating amount of time (and insights from a colleague) to figure out that this was not some kind of debugging output...
I love ASCII art too but how about a boring line with the Version number indicating CoreDNS is starting up ¯\_(ツ)_/¯ ?

**Comment by miekg** [comment]
Ok, this seems to be causing more problems than it's worth. Please send a PR.

**Comment by sharmaansh21** [comment]
@miekg You mean removing https://github.com/coredns/coredns/commit/c466003a943fac7dd78b25b672922a1a0944b59a this code?

**Comment by miekg** [comment]
Sorta a plain revert might not work. Probably best to remove the logo bits
and leave version strings

**Comment by sharmaansh21** [comment]
Gotch will send a PR for the same 👍

**Comment by yannh** [comment]
:wave: sorry for the late reply, quite busy in the last few days but I was hoping to get to this over the week end :) Thanks a lot everyone for beeing so understanding! @sharmaanshul21 ping me if you dont have time to get to it!
