### ISSUE TITLE
plugin/dnssec: ed25519 support

### ISSUE THREAD

**Issue by seankhliao** [coredns/coredns#3379]
*  the version of CoreDNS you are using: 
1.6.4, also on master
*  your Corefile
```
.:553 {
    auto {
        directory /etc/coredns/zone (.*).zone {1}
        transfer to *
        reload 10s
    }
    dnssec example.com {
        key file /etc/coredns/key/Kexample.com.+015+53911 /etc/coredns/key/Kexample.com.+015+40283
    }
    errors
    log
    reload 10s
    whoami
}
```
* logs, if applicable
```
plugin/dnssec: no private key found
```

Given that there is no mention of not supporting it, I expected support for ed25519 dnskeys (algorithm 15).  The upstream library github.com/miekg/dns already supports it, coredns just needs to allow its usage.  I can have submit a PR if needed.

also plugin/sign is probably wrong since the returned privatekey is `ed25519.PrivateKey` and not `*ed25519.PrivateKey`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/dnssec: ed..." ]
>*  the version of CoreDNS you are using:
>1.6.4, also on master
>*  your Corefile
>```
>.:553 {
>    auto {
>        directory /etc/coredns/zone (.*).zone {1}
>        transfer to *
>        reload 10s
>    }
>    dnssec example.com {
>        key file /etc/coredns/key/Kexample.com.+015+53911 /etc/coredns/key/Kexample.com.+015+40283
>    }
>    errors
>    log
>    reload 10s
>    whoami
>}
>```
>* logs, if applicable
>```
>plugin/dnssec: no private key found
>```
>
>Given that there is no mention of not supporting it, I expected support for ed25519 dnskeys (algorithm 15).  The upstream library github.com/miekg/dns already supports it, coredns just needs to allow its usage.  I can have submit a PR if needed.
>
>also plugin/sign is probably wrong since the returned privatekey is `ed25519.PrivateKey` and not `*ed25519.PrivateKey`

PR welcome!
