### ISSUE TITLE
backend_plugin.go SRV lookup

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3381]
The `backend_plugin.go` code does a whole bunch of things that are useful; various maps get allocated, this is mostly done because SkyDNS could return multiple SRVs from etcd. For k8s; this is actually not needed. Looking at the code it may be best to write a small `singleSRV` that handles this case specifically

**Comment by rickywraith** [comment]
From the looks of the CI tests (https://github.com/coredns/ci/blob/master/test/kubernetes/srv_test.go), K8s can return multiple SRV records. Can you clarify this issue for me?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] backend_plugi..." ]
>From the looks of the CI tests (https://github.com/coredns/ci/blob/master/test/kubernetes/srv_test.go), K8s can return multiple SRV records. Can you clarify this issue for me?

ha, it can!? Hmm. I was not aware of this. (cc @chrisohaver , it this a coredns 
thing or offically in the spec?)

**Comment by chrisohaver** [comment]
Not part of k8s dns spec. It's probably part of wildcard queries, which is a CoreDNS only thing AFAIK.

**Comment by chrisohaver** [comment]
oh wait... IIUC now, it is actually part of the spec.  An SRV request of a headless service will return SRV records for each endpoint of the service.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] backend_plugi..." ]
>oh wait... IIUC now, it is actually part of the spec.  An SRV request of a headless service will return SRV records for each endpoint of the service.

oh, ahh... Thanks. Still think this function can be optimized for the k8s case; 
but it's slightly more complicated.

**Comment by chrisohaver** [comment]
Looking at the test cases, we also reply with all available services, when no port/protocol is specified in the query.  I recall this behavior was requested a while back.  This is more general SRV behavior, not k8s specific.

**Comment by miekg** [comment]
More complex than I thought.
