### ISSUE TITLE
http:127.0.0.1:53 no reaponse

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3382]
http:127.0.0.1:53 no reaponse

coredns is running with default config

how to query a domain by http request?

**Comment by chrisohaver** [comment]
https is supported.  There is an example in the readme.

**Comment by zzxap** [comment]
how to start a https server ?
is this right？
https://example.org {
  bind 127.0.0.1
hosts {
    10.6.6.2 sms.service
    10.6.6.3 search.service
  }
}

and how to test it ？ https://127.0.0.1?host=sms.service  ???
how to get A record?
