### ISSUE TITLE
The coredns pods always restart because of OOMKilled

### ISSUE THREAD

**Issue by xieyanker** [coredns/coredns#3388]
Hello, on my k8s, the coerdns pods always restart because of OOMKilled.
The limits memory I set is 170Mi, which is referenced to https://github.com/coredns/deployment/blob/e851a3095d1224b423fd8a12825bfaf79c2f62ba/kubernetes/coredns.yaml.sed#L106
I don't know why coredns consume so many memory resouces, and I wonder how many memory resouce limits shoud I configure?

all of the coredns's pod have restarted serval times.
```shell
root@master1:~# kubectl get pod -A -owide | grep coredns
kube-system    coredns-46qtd                                          1/1     Running     836        25d     172.31.208.52    master2   <none>           <none>
kube-system    coredns-6d9j4                                          1/1     Running     379        9d      172.31.33.64     master3   <none>           <none>
kube-system    coredns-b65fn                                          1/1     Running     164        25d     172.31.161.68    master1   <none>           <none>
```

I use `kubectl describe pod` get the restart reason is `OOMKilled`
```shell
    State:          Running
      Started:      Mon, 21 Oct 2019 11:17:49 +0800
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    0
      Started:      Mon, 21 Oct 2019 11:07:41 +0800
      Finished:     Mon, 21 Oct 2019 11:17:46 +0800
    Ready:          True
    Restart Count:  836
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
```

this is the memory usage when they are running
```shell
root@master1:~# kubectl top pod -nkube-system | grep coredns
coredns-46qtd                              6m           83Mi            
coredns-6d9j4                              6m           106Mi           
coredns-b65fn                              7m           114Mi
```

The coredns verison I use is 1.5.0, and the corefile is as follows:
```yaml
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        hosts {
          10.72.209.1 foo.bar.com
          ttl 60
          reload 1m
          fallthrough
        }
        cache 30
        loop
        reload
        loadbalance
    }
```

**Comment by chrisohaver** [comment]
In kubernetes, CoreDNS memory usage primarily correlates to the number of services/endpoints in the cluster.  If it's taking up significantly more than what [this guide](https://coredns.io/2018/11/15/scaling-coredns-in-kubernetes-clusters/) suggests then something may be awry.

Are you observing unusually high QPS in your cluster?
Does upgrading to a more recent version of CoreDNS help?

Side Note: The `reload` in `hosts` seems superfluous, since no file is specified.

**Comment by xieyanker** [comment]
@chrisohaver Thanks for your reply, 

> Are you observing unusually high QPS in your cluster?

I try to observe the QPS in mycluster by kubernetes/perf-tests/dns, but the image that the test pod use is `k8s.gcr.io/kube-dns-perf-client-amd64:1.1`, cannot work on my `arm64` environment, and I can not found the image for arm.

> Does upgrading to a more recent version of CoreDNS help?

This environment is my product environment, I have no idea to upgrade the version of Coredns. However, the other arm64 environment for test doesn't find this issue.

**Comment by chrisohaver** [comment]
>> Are you observing unusually high QPS in your cluster?

> I try to observe the QPS in mycluster by kubernetes/perf-tests/dns,

No, i don't mean to test the _maximum_ QPS in your cluster.  I mean, "how many queries per second is coredns processing in your cluster now"  IOW "how many queries per second is your application generating now"

**Comment by xieyanker** [comment]
I don't know how to query it
```shell
root@master1:~# kubectl top pod -nkube-system |grep coredns
coredns-2bxm7                              7m           156Mi           
coredns-69rns                              6m           154Mi           
coredns-nlqdh                              6m           156Mi           
root@master1:~# 
root@master1:~# 
root@master1:~# kubectl get pod -A | wc -l
292
root@master1:~# kubectl get svc -A | wc -l
126
```

**Comment by chrisohaver** [comment]
QPS can be inferred from the prometheus metrics that coredns exports.

**Comment by xieyanker** [comment]
@chrisohaver there are some metrics that prometheus has about coredns, can you help me how to infer it?
![coredns](https://user-images.githubusercontent.com/45066503/67450788-15cc3880-f651-11e9-8a98-f0cc16f6a4f6.jpg)
![2019-10-24_112402](https://user-images.githubusercontent.com/45066503/67450802-2381be00-f651-11e9-989d-3d30fb4c6ee6.jpg)
![2019-10-24_112531](https://user-images.githubusercontent.com/45066503/67450804-27154500-f651-11e9-90fd-4502a0e1488f.jpg)

**Comment by chrisohaver** [comment]
should be able to calculate rate from request count total ...

**Comment by xieyanker** [comment]
I thinks there exists 7.07 queries per second

![2019-10-25_163216](https://user-images.githubusercontent.com/45066503/67556040-08907600-f745-11e9-9287-50723f8eb656.jpg)

**Comment by dilyevsky** [comment]
7qps is very low. You should be able to dump heap profile by enabling `pprof` plugin on the server and then using `go tool pprof http://[host]:[port]/debug/pprof/heap`
