### ISSUE TITLE
coredns cache confuse alpine?

### ISSUE THREAD

**Issue by blurpy** [coredns/coredns#3391]
We have a few applications that use alpine docker images. I've figured out by now that DNS is troublesome with alpine, and it's a known issue. So we are moving away from them.

But in any case, I want to document what we experience, in case it's something coredns needs to handle better.

What we see is random DNS-lookup failures in applications (using alpine), but logs in coredns report success (NOERROR).

Example:

> / # date && ping -W 1 -c 1 some.internal.domain
Fri Oct 18 12:54:31 UTC 2019
ping: bad address 'some.internal.domain'

Log:

> [coredns-54ff9cd656-4bg84] 2019-10-18T12:54:31.071Z [INFO] 10.244.19.201:37276 - 3 "A IN some.internal.domain. udp 58 false 512" NOERROR qr,tc,rd,ra 2442 0.0002726s 

We noticed that we had a few applications using debian-slim images and a few using alpine images connecting to the same domain. The alpine lookups failed sometimes while the debian-slim lookups were successful every time. It seemed random, until we noticed that alpine lookups only failed if it happened right after debian-slim lookups.

Here are examples of lookups from alpine working fine:

> / # date && ping -W 1 -c 1 some.internal.domain
Fri Oct 18 12:54:20 UTC 2019
PING some.internal.domain (xxx.23.5.110): 56 data bytes

> / # date && ping -W 1 -c 1 some.internal.domain
Fri Oct 18 12:54:22 UTC 2019
PING some.internal.domain (xxx.23.5.110): 56 data bytes

Logs:

> [coredns-54ff9cd656-49w66] 2019-10-18T12:54:20.34Z [INFO] 10.244.19.201:37500 - 3 "A IN some.internal.domain. udp 58 false 512" NOERROR qr,aa,rd,ra 114 0.001780895s 
> [coredns-54ff9cd656-4bg84] 2019-10-18T12:54:22.29Z [INFO] 10.244.19.201:40206 - 3 "A IN some.internal.domain. udp 58 false 512" NOERROR qr,tc,rd,ra 1414 0.00173813s 

Now, lets try ping from debian-slim:

> / # date && ping -W 1 -c 1 some.internal.domain
Fri Oct 18 13:06:04 UTC 2019
PING some.internal.domain (xxx.23.5.110): 56 data bytes

And then alpine:

> / # date && ping -W 1 -c 1 some.internal.domain
Fri Oct 18 13:06:08 UTC 2019
ping: bad address 'some.internal.domain'

Logs:

> [coredns-54ff9cd656-rhbp5] 2019-10-18T13:06:04.23Z [INFO] 10.244.19.204:34506 - 54425 "A IN some.internal.domain. tcp 58 false 65535" NOERROR qr,rd,ra 2442 0.0038644s 
> [coredns-54ff9cd656-rhbp5] 2019-10-18T13:06:08.398Z [INFO] 10.244.19.201:54328 - 3 "A IN some.internal.domain. udp 58 false 512" NOERROR qr,tc,rd,ra 2442 0.000246628s 

As you can see, both of them are NOERROR, but the alpine lookup failed.

This experiment is consistent. If alpine makes lookups in isolation, it always works. If debian-slim makes lookups right before, alpine lookups always fails.

If we look at the logs we can see that response size varies.
In the examples where alpine does lookups in isolation, the response sizes are 114 and 1414. When it fails, its 2442. What's interesting is that response size to both debian-slim and alpine are identical when it fails. So it looks like coredns is caching the response used for debian-slim, and serving that to alpine, which can't handle it.

Since alpine lookups works in isolation, it seems it may specify some parameter to coredns that makes coredns return a response it can handle. But the cache does not seem to respect that parameter, making it fail "randomly" for some clients.

I'm just speculating, based on what I see.

coredns: 1.2.6
kubernetes: 1.13.10

```
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
```

**Comment by miekg** [comment]
this needs tcpdumps to say something about it.

**Comment by blurpy** [comment]
Sorry for the late feedback. We've been watching our rebuilt apps with debian-slim in production for the last few days, and so far not a single DNS issue.

As long as we have this simple workaround, I can't justify spending any more time on troubleshooting. Feel free to close this issue if no one has the capacity to follow up on it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] coredns cache..." ]
>Sorry for the late feedback. We've been watching our rebuilt apps with debian-slim in production for the last few days, and so far not a single DNS issue.
>
>As long as we have this simple workaround, I can't justify spending any more time on troubleshooting. Feel free to close this issue if no one has the capacity to follow up on it.

alpine, uses libmusl, which doesn't (didn't?) have a compliant DNS implemenation 
as (e.g.) it doesn't do TCP retry. That said we might some changes to make the 
libmusl happy, so things should usually work.

/close
