### ISSUE TITLE
Add a New Health Check

### ISSUE THREAD

**Issue by alexgaganashvili** [coredns/coredns#3392]
Hello,

Could you add a health check so that the container is considered unhealthy when coredns cannot talk to the apiserver?
I keep seeing the following errors every time and again:

1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Unauthorized
1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Unauthorized

The problem tends to go away after I kill bad coredns pods. I can't seem to be able to figure out why the problem occurs in the first place.

Thanks

**Comment by miekg** [comment]
No, we will not add this. The *cache* plugin should handle failures like this. Adding a HC on a shared piece of infrastructure means **all** instances will go down at probably the same time.

**Comment by chrisohaver** [comment]
@alexgaganashvili, To get the behavior you request, you could try altering your coredns Deployment to direct the liveness probe to the _ready_ plugin instead of the _health_ plugin.

But, I'd recommend identifying and remedying your underlying api authentication issue if you can.

**Comment by alexgaganashvili** [comment]
> @alexgaganashvili, To get the behavior you request, you could try altering your coredns Deployment to direct the liveness probe to the _ready_ plugin instead of the _health_ plugin.
> 
> But, I'd recommend identifying and remedying your underlying api authentication issue if you can.

Thank you.
