### ISSUE TITLE
denial logs are showing up, despite log plugin only specifying error class

### ISSUE THREAD

**Issue by ghostsquad** [coredns/coredns#3395]
## Description

`denial` logs are showing up, despite log plugin only specifying `error` class.

Relevant documentation: https://coredns.io/plugins/log/

```
The classes of responses have the following meaning:

    success: successful response
    denial: either NXDOMAIN or nodata responses (Name exists, type does not). A nodata response sets the return code to NOERROR.
    error: SERVFAIL, NOTIMP, REFUSED, etc. Anything that indicates the remote server is not willing to resolve the request.
    all: the default - nothing is specified. Using of this class means that all messages will be logged whatever we mix together with “all”.
```

CoreDns 1.2.6
Kubernetes 1.13.12

Corefile
```
google.com:53 {
      errors
      log . {
        class error
      }
      hosts {
        no_reverse
      }
      loop
    }
```

from a pod in k8s (minikube)
```
dig google.com
```

logs
```
2019-10-23T23:33:20.794Z [INFO] 127.0.0.1:46910 - 6124 "HINFO IN 6899411877052415204.1377161279378477110.google.com. udp 68 false 512" NXDOMAIN qr,rd 68 0.00008281s
 [INFO] plugin/reload: Running configuration MD5 = 3db7ced1f0b7ea5ed85046e685c32ba2
[INFO] Reloading complete
2019-10-23T23:33:50.299Z [INFO] 172.17.0.2:44404 - 45886 "A IN google.com. udp 52 false 4096" NXDOMAIN qr,rd 52 0.000102629s
```

## Expected Behavior

Nothing is logged

## Actual Behavior

Logged `NXDOMAIN` response

**Comment by miekg** [comment]
>## Actual Behavior
>
>Logged `NXDOMAIN` response

does this also happen with a later version? (1.6.4 or master even)

**Comment by miekg** [comment]
tried to replicate with master branch and that failed. So I think this has been long since fixed.

**Comment by ghostsquad** [comment]
@miekg is it safe to use later versions of CoreDNS with lower versions of kubernetes?

We are currently following:
https://github.com/coredns/deployment/blob/master/kubernetes/CoreDNS-k8s_version.md

and

https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

**Comment by chrisohaver** [comment]
> is it safe to use later versions of CoreDNS with lower versions of kubernetes?

Yes, should be safe.

> We are currently following:
https://github.com/coredns/deployment/blob/master/kubernetes/CoreDNS-k8s_version.md

That document shows the version of CoreDNS that was released with Kubernetes at the time of that kubernetes release.
