### ISSUE TITLE
Hosted CoreDNS?

### ISSUE THREAD

**Issue by tmm1** [coredns/coredns#3396]
Are there any SaaS CoreDNS offerings where I can upload a Corefile and have hosted/managed DNS?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Hosted CoreDNS? (..." ]
>Are there any SaaS CoreDNS offerings where I can upload a Corefile and have hosted/managed DNS?

not that I'm aware of.

/label: question

**Comment by stp-ip** [comment]
What is your specific use case?

**Comment by tmm1** [comment]
I'm using the template plugin to power a xip.io style dns server. CoreDNS made this very easy and I have a Corefile using standard plugins that works very well.

Now I want to deploy this somewhere without necessarily wanting to run my own compute instances or manage containers across different clouds for redundancy.

**Comment by miekg** [comment]
Interesting. What would consider a fair price for such a service?

**Comment by tmm1** [comment]
I'm using services like heroku and cloudflare workers already, and would happily pay comparable prices. I wish I could use those to host CoreDNS, but they're both very HTTP centric.

I considered running CoreDNS in DoH mode, but it doesn't seem like I can use DoH as a nameserver for my domain so I'd still end up running a dns->DoH proxy somewhere.

It seems like most of the people using CoreDNS are operating internal dns servers for their kubernetes clusters, so perhaps my use-case is not very common and there isn't enough of a market for a SaaS offering.

**Comment by gaby** [comment]
@tmm1 Mind sharing your CoreFile ? I'm trying to do the same thing.
