### ISSUE TITLE
Getting original requester IP instead of current requester IP.

### ISSUE THREAD

**Issue by normangoh** [coredns/coredns#3397]
Is it possible for CoreDNS to get original requester IP?

For example, using **ping** or **nslookup** or even browsing a domain that my CoreDNS would resolve is getting the IP addresses that is not my public IP. May I know if it is possible to get my public IP instead?

Thank you.

**Comment by miekg** [comment]
The server replies to the IP that it gets. That's it.

/label: question

**Comment by normangoh** [comment]
> The server replies to the IP that it gets. That's it. /label: question

Does it mean that in my example it is impossible to get my IP instead of what is reaching to my DNS when I use **ping** or **nslookup**?

**Comment by chrisohaver** [comment]
Can you describe what you mean by original requestor and current requestor ip?

**Comment by normangoh** [comment]
@chrisohaver Thank you for helping out.

**Exmaple:**

1. When I check my public IP it is **123.123.100.101**.
2. We have a CoreDNS running and we have a domain named **demo.com** that have the nameserver set and point to our CoreDNS.
3. When we do a `ping demo.com` or `nslookup demo.com` or visiting **demo.com** from the browser, the client IP address I got might be like **200.200.200.1** which is not the same as my public IP.

We want to get the original requester IP (which is my public IP). May I know how to do it?

**Comment by chrisohaver** [comment]
Sorry, I'm still not understanding what you mean.  What are you trying to accomplish?

**Comment by normangoh** [comment]
@chrisohaver 
I am trying to get the IP address of the true client and not the last requester IP address if the client request goes through a of different nodes before the request reaches my DNS.

**Comment by normangoh** [comment]
@chrisohaver @miekg
### In development environment
- We are using the following Corefile settings,
```
.:1053 {
  log
  {some other plugins}
}
```
- while running coredns.go -> main() func
- run `dig @127.0.0.1 -p 1054 example.com`
We can see run time logs,
`[INFO] 127.0.0.1:44729 - 10362 "A IN example.com. udp 52 false 4096" NOERROR - 0 0.000041997s`
### In production environment
- We assigned our CoreDNS server to be the nameserver for our domain's DNS record.
- So while we access that domain we should be seeing the requester IP in the log but it is showing random IP instead.

**Comment by chrisohaver** [comment]
Still very unclear. But I am guessing you are trying to have CoreDNS learn the IP address of the client making a request.  CoreDNS uses the source ip address of the packet headers. As a packet traverses through the network, the ip address in the packet headers change (e.g. via network address translation). Only the last ip is available.

The original IP of the client is not part of the DNS payload. The IP in the packet header only matches the original client IP if CoreDNS is on the same subnet as the client (for the most part).

You could use a customized client, or an agent on the client subnet to inject the original client ip address as edns0 data into dns requests.  The endns0 data should survive, as long as it doesnt pass through other DNS forwarders.  But that requires custom dns clients, or a dns forwarding agent (which could be coredns) on the client subnet.
