### ISSUE TITLE
[Feature Request] hosts output in log

### ISSUE THREAD

**Issue by JasonSwindle** [coredns/coredns#3399]
Howdy,

## Issue
Currently when the plugin `hosts` does an action, it does not emit any type of output allowing the operator to understand it took action.  

## Request
Have `hosts` emit something into the logs showing that it took action, what action it took, and for what client.

**Comment by chrisohaver** [comment]
You can enable logging of responses with the `log` plugin.

**Comment by JasonSwindle** [comment]
Howdy,

That is correct, and responses are shown, but you still cannot tell that `hosts` actioned on the request:

## Log entry
```
[INFO] 127.0.0.1:59744 - 58034 "A IN <REDACTED>.com. udp 46 false 4096" NOERROR qr,aa,rd 68 0.000576625s
```

## Dig
```
dig @localhost <REDACTED>.com.

; <<>> DiG 9.10.3-P4-Debian <<>> @localhost <REDACTED>.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58034
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;<REDACTED>.com.		IN	A

;; ANSWER SECTION:
<REDACTED>.com.	3600	IN	A	0.0.0.0

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Oct 25 11:02:53 PDT 2019
;; MSG SIZE  rcvd: 79
```

## Logging level
```
log {
  class all
}
```

**Comment by JasonSwindle** [comment]
Bumping

**Comment by miekg** [comment]
you get an answer from the plugin that is authortiative for the zone. This is WAI

**Comment by chrisohaver** [comment]
> you get an answer from the plugin that is authortiative for the zone.

This issue with the _host_ plugin, is that it is usually not authoritative for the zone.  So it cannot always be inferred from the zone that the _host_ plugin provided the answer.

I briefly looked into this to see if it would be easy to add a "plugin" variable to the available log vars that would hold the name of the plugin that generated the answer, but didn't immediately see a simple solution.
