### ISSUE TITLE
Kubernetes + Calico + CoreDNS: Unreachable Backend, DNS fails to resolve

### ISSUE THREAD

**Issue by sager-tech** [coredns/coredns#3402]
Corefile ConfigMap: 
```
apiVersion: v1
data:
  Corefile: {
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa æ
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-10-26T15:40:03Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "203"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: e0b4e270-f806-11e9-b63b-0242ac110003
```
Logs: 
```
 [ERROR] plugin/errors: 2 7893400373289152203.6025455479212086695. HINFO: unreachable backend: read udp 10.244.1.3:38701->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 7893400373289152203.6025455479212086695. HINFO: unreachable backend: read udp 10.244.1.3:47810->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 7893400373289152203.6025455479212086695. HINFO: unreachable backend: read udp 10.244.1.3:54801->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 7893400373289152203.6025455479212086695. HINFO: unreachable backend: read udp 10.244.1.3:45085->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 7893400373289152203.6025455479212086695. HINFO: unreachable backend: read udp 10.244.1.3:34876->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 amazon.com. A: unreachable backend: read udp 10.244.1.3:58544->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 amazon.com. A: unreachable backend: read udp 10.244.1.3:45441->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 amazon.com. A: unreachable backend: read udp 10.244.1.3:51907->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 amazon.com. A: unreachable backend: read udp 10.244.1.3:36537->192.168.65.1:53: i/o timeout
 [ERROR] plugin/errors: 2 amazon.com. A: unreachable backend: read udp 10.244.1.3:49806->192.168.65.1:53: i/o timeout
```
KIND: 0.6.0-alpha
kubernetes: Major:"1", Minor:"14", GitVersion:"v1.14.3"

-------
 
Deployed KIND, deployed Calico v3.0 based on [this issue](https://github.com/coredns/coredns/issues/2693). The pods all come up as successful and in `Ready` state, but the `coredns` pods logs show the above error. Any deployment done also fails to come up with logs showing the DNS failing to resolve:
```
; <<>> DiG 9.11.3-1ubuntu1.8-Ubuntu <<>> -t A +tries=5 +retry=5 +time=1 amazon.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Any ideas as to why this might be happening?

**Comment by chrisohaver** [comment]
> Any ideas as to why this might be happening?

Likely means that all the Pods in your cluster (not just CoreDNS) cannot reach 192.168.65.1.

Could be a firewall issue somewhere between the Pods, and 192.168.65.1, in which case trying different CNIs probably wont help.

CoreDNS works fine with Kind for me using the default CNI (kindnet).

**Comment by chrisohaver** [comment]
FYI, I'm using kind version v0.4.0.

**Comment by sager-tech** [comment]
@chrisohaver Where is this firewall policy configured? I would like to disable it, would `exec`ing into one of the running pods and running `ufw` help? Or is this configuration elsewhere?

CoreDNS works with me for KIND with kindnet as well, but I need to test policies, so I need another CNI which allows policy configuration.

**Comment by chrisohaver** [comment]
This issue is probably better asked in KinD specific forum, where you can get advice from people who are experts with KinD (which I am certainly not). https://github.com/kubernetes-sigs/kind/issues

**Comment by sager-tech** [comment]
Moving conversation to https://github.com/kubernetes-sigs/kind/issues/1016
