### ISSUE TITLE
kubelet config yaml: resolvConf mis understand docs

### ISSUE THREAD

**Issue by HelloMyDevWorld** [coredns/coredns#3404]
"Add the following to your kubelet config yaml: resolvConf: <path-to-your-real-resolv-conf-file> (or via command line flag --resolv-conf deprecated in 1.10). Your "real" resolv.conf is the one that contains the actual IPs of your upstream servers, and no local/loopback address. This flag tells kubelet to pass an alternate resolv.conf to Pods. For systems using systemd-resolved, /run/systemd/resolve/resolv.conf is typically the location of the "real" resolv.conf, although this can be different depending on your distribution."

How to find that on linux and do that with commands ? Where to find config.yaml how to apply it when ?

**Comment by miekg** [comment]
this seems to be a kubernetes issue, not a coredns one.

**Comment by chrisohaver** [comment]
@patsadow2, Try googling "configure kubelet" or "kubelet config yaml".  Hope that helps!
