### ISSUE TITLE
[Feature Request] Make private field/function in forward plugin public

### ISSUE THREAD

**Issue by chenwng** [coredns/coredns#3409]
Hi,

I am trying to create a plugin, which forwards a query based on some condition.  After I read the forward plugin code, I think I can reuse it for the forwarding part. However, I cannot import and use it directly due to its private fields/function. 

Would you please make those private fields/function public so that they can be imported and re-used in other plugins?

Thanks.

**Comment by chrisohaver** [comment]
We are trying to avoid sharing code directly between plugins.  Shared plugin packages should live in /plugin/pkg.  However, in this case I think the preference would be to replicate (copy-paste) the forward code in your plugin (as similar requests for the forward plugin have been made recently, and the direction was to replicate the code).

**Comment by chenwng** [comment]
Thanks for the reply. I will follow your suggestion.
