### ISSUE TITLE
middleware/etcd: etcd3 support

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#341]
See https://github.com/skynetservices/skydns/pull/299

**Comment by miekg** [comment]
This will probably done as a separate middleware, as there are things different with gRPC, i.e. do we want to enforce TLS?

**Comment by alexzorin** [comment]
How's this going?

Would you accept a PR to update the existing (v2) implementation to support [authentication](github.com/coreos/etcd/client)? Presumably it would be included with v3 support but perhaps it would be of value to backport that particular feature, since it's available since etcd 2.1.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] middleware/etcd..." ]
>How's this going?

I haven't made any progress. Big point in this is that I'm still not sure if
this should be new/separate middleware or done inside the etcd middleware...
(and of course time to actually implement it)

>Would you accept a PR to update the existing (v2) implementation to support [authentication](github.com/coreos/etcd/client)? Presumably it would be included with v3 support but perhaps it would be of value to backport that particular feature, since it's available since etcd 2.1.

I see no actual reason to backport this as this is a more complete feature of
etcd3 (and thus should be done in that middleware).

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I'm tinkering with this myself atm, but no code ready to actually push to a PR

**Comment by amitkumarj441** [comment]
@miekg Any update on this issue?
I'm willing to take up this task. Please let me know the status of this issue and what needs to be done?

**Comment by miekg** [comment]
I haven't had time to brush this up. Ah just found my non-working etcd3 branch: 
https://github.com/coredns/coredns/tree/etcd3
This barely has a functioning `get` if you have that the rest should flow quite naturally.

Note that @VioletRainbows is working on a larger refactoring of all this.

**Comment by zhujinghui** [comment]
Sounds like an interesting project, and I happen to have some ectd experience during my previous internship. I'd like to pick this up as my GSoC 2018 project. But I have a question:

Should the ectd plugin watch etcd to maintain a cache of dns records in coredns's memory， so coredns can reply client query more efficiently, or every time coredns want to reply a client query, it need to ask etcd for data ?

**Comment by miekg** [comment]
No we don't do this in the etcdv2 plugin, we have the *cache* plugin for this which adhere to the TTL we slap on the record.

**Comment by harshavardhana** [comment]
> I haven't had time to brush this up. Ah just found my non-working etcd3 branch:
> https://github.com/coredns/coredns/tree/etcd3
> This barely has a functioning get if you have that the rest should flow quite naturally.

I can't find this branch anymore is the etcd plugin not maintained anymore? will you be accepting patches to bring this support?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/et..." ]
>> I haven't had time to brush this up. Ah just found my non-working etcd3 branch:
>> https://github.com/coredns/coredns/tree/etcd3
>> This barely has a functioning get if you have that the rest should flow quite naturally.
>
>I can't find this branch anymore is the etcd plugin not maintained anymore? will you be accepting patches to bring this support?

Yes, we accept an etcd3 plugin.

/Miek

--
Miek Gieben
