### ISSUE TITLE
Can I use HTTP over HTTPS in the forward plug-in？

### ISSUE THREAD

**Issue by hurongyang** [coredns/coredns#3413]

**Comment by stp-ip** [comment]
Can you go a bit more into the details on what you are trying to do and what you currently have?

**Comment by hurongyang** [comment]
Now that I have created the coredns service on the LAN, I want to use the HTTPS protocol to protect my upstream DNS

**Comment by hurongyang** [comment]
I saw that the proxy plug-in has a protocol parameter that supports https_google, but I used the forward plug-in

**Comment by hurongyang** [comment]
![image](https://user-images.githubusercontent.com/17896811/67918095-f182d580-fbd5-11e9-8d18-2aaf43951f4f.png)

**Comment by stp-ip** [comment]
```
. {
    forward . tls://8.8.8.8 {
       tls_servername dns.google
       health_check 5s
    }
    cache
    log
    errors
}

```

**Comment by stp-ip** [comment]
It's using DNS over TLS.

**Comment by miekg** [comment]
btw: if we want https as a forward like plugin, we should do the same as we did 
with the *grpc* plugin, fork *forward* and make it do https.
