### ISSUE TITLE
High memory usage for loaded zone

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#3414]
Loading a few bigger zones (repo: https://github.com/stp-ip/bitcoinheaders) with a total size of about 600MB leads to a memory usage right out of the gate of 2.7GB.

For comparison bind only uses ~1GB for these zones.

Wanted to note this down for now and iterate on improvements down the road.

Corefile:
```
.:5353 {
  bind 127.0.0.53
  auto {
    directory /bitcoinheaders/zones/ (.*) {1}
    reload 15s
    transfer to *
  } 
  any
  errors
  prometheus 127.0.0.1:9154
}
```

**Comment by miekg** [comment]
this hasn't been optimized at all, all ownername strings are stored as-is, for instance; much can improved there.
