### ISSUE TITLE
Build fails cross compiling for MIPS little endian

### ISSUE THREAD

**Issue by itskenny0** [coredns/coredns#3421]
I'm trying to build CoreDNS for my Ubiquiti ER-X, unfortunately cross compiling for it fails from master.

<pre>
$> GOARCH=mipsle make
[...]
go: downloading github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
go: extracting github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
go: extracting github.com/Azure/go-autorest/autorest/date v0.2.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting github.com/json-iterator/go v1.1.7
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting gopkg.in/square/go-jose.v2 v2.2.2
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: extracting go.opencensus.io v0.22.0
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/google/go-cmp v0.3.0
go: downloading github.com/Azure/go-autorest/autorest/azure/cli v0.3.0
go: extracting github.com/hashicorp/golang-lru v0.5.1
go: extracting github.com/google/go-cmp v0.3.0
go: extracting github.com/Azure/go-autorest/autorest/azure/cli v0.3.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: extracting github.com/pierrec/lz4 v2.0.5+incompatible
go: extracting golang.org/x/text v0.3.2
go: extracting google.golang.org/genproto v0.0.0-20190701230453-710ae3a149df
go: extracting github.com/Azure/azure-sdk-for-go v31.1.0+incompatible
go: downloading github.com/Azure/go-autorest/autorest/to v0.2.0
go: extracting github.com/Azure/go-autorest/autorest/to v0.2.0
** presubmit/test-lowercase
** presubmit/trailing-whitespace
go generate coredns.go
fork/exec /tmp/go-build686217867/b001/exe/directives_generate: exec format error
coredns.go:3: running "go": exit status 1
Makefile:62: recipe for target 'core/plugin/zplugin.go' failed
make: *** [core/plugin/zplugin.go] Error 1
</pre>

**Comment by miekg** [comment]
>fork/exec /tmp/go-build686217867/b001/exe/directives_generate: exec format error

looks like a cached version of this is used for a different arch

--
Miek Gieben

**Comment by jrcichra** [comment]
I was able to get a build by running `go generate coredns.go` before running `GOARCH=mipsle make`
