### ISSUE TITLE
dig -x no ANSWERED SECTION

### ISSUE THREAD

**Issue by nbctcp** [coredns/coredns#3422]
PROBLEMS:
1. when
# dig -x 10.0.1.251
got no ANSWERED SECTION
I just need coredns to answer my PTR record

SW INFO:
CoreDNS-1.6.4

LOGS:
[INFO] 172.17.0.1:39543 - 24409 "PTR IN 251.1.0.10.in-addr.arpa. udp 64 false 4096" NXDOMAIN qr,rd,ra 116 0.014669678s

STEPS:
# docker pull coredns/coredns
# mkdir /root/coredns
# cd /root/coredns
# ls 
Corefile    db.pt1.com
# cat Corefile
. {
    forward . 8.8.8.8 8.8.4.4
    log
    errors
}
pt1.com {
    file /root/db.pt1.com pt1.com
    file /root/db.10.0. 0.10.in-addr.arpa
    log
    errors
}

# cat db.pt1.com
$ORIGIN pt1.com.
@    1d IN SOA ns1.pt1.com. hostmaster.pt1.com. (
                                2019110416 ; serial
                                2h ; refresh (2 hours)
                                1h ; retry (1 hour)
                                2w ; expire (2 weeks)
                                1h ; minimum (1 hour)
                                )
        IN NS    ns1.pt1.com.
@       IN MX 10 mail.pt1.com.
ns1     IN A     10.0.1.251
mail1   IN A     10.0.1.251
mail    IN CNAME mail1
www1    IN A     10.0.1.251
www     IN CNAME www1
smtp1   IN A     10.0.1.253
smtp    IN CNAME smtp1
251.1.0.10.in-addr.arpa. 1d IN PTR mail1.pt1.com.
253.1.0.10.in-addr.arpa. 1d IN PTR smtp1.pt1.com.

# cat db.10.0
$ORIGIN pt1.com.
@    1d IN SOA ns1.pt1.com. hostmaster.pt1.com. (
                                2019110416 ; serial
                                2h ; refresh (2 hours)
                                1h ; retry (1 hour)
                                2w ; expire (2 weeks)
                                1h ; minimum (1 hour)
                                )
        IN NS    ns1.pt1.com.
@       IN MX 10 mail.pt1.com.
251.1 IN PTR mail1.pt1.com.
253.1 IN PTR smtp1.pt1.com.

# docker run -d --name coredns --restart=always --volume=/root/coredns:/root -p 53:53/udp coredns/coredns -conf /root/Corefile

**Comment by miekg** [comment]
you get an nxdomain: `[INFO] 172.17.0.1:39543 - 24409 "PTR IN 251.1.0.10.in-addr.arpa. udp 64 false 4096" NXDOMAIN qr,rd,ra 116 0.014669678s`

helping with dns setup details is not something we can provide

**Comment by miekg** [comment]
you get an nxdomain: `[INFO] 172.17.0.1:39543 - 24409 "PTR IN 251.1.0.10.in-addr.arpa. udp 64 false 4096" NXDOMAIN qr,rd,ra 116 0.014669678s`

helping with dns setup details is not something we can provide
