### ISSUE TITLE
coredns in kubernets can not nslookup service-dns-record

### ISSUE THREAD

**Issue by piwenzi** [coredns/coredns#3428]
* the version of CoreDNS you are using
1.1.2 
* your Corefile
 Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local  in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
* logs, if applicable
os-version:ubuntu-16.04
k8s-version:hyperkube-amd64:v1.14.7

name
1: kubectl run nginx --image=nginx --port=80
2:kubectl expose deploy nginx --port=80 --target-port=80

 root@ubuntu-165:~# kubectl get svc
NAME          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
details       ClusterIP   10.103.189.174   <none>        9080/TCP         3h2m
kubernetes    ClusterIP   10.96.0.1        <none>        443/TCP          3h48m
nginx         ClusterIP   10.104.60.66     <none>        80/TCP           2m59s

3: kubectl run box --image=busybox --restart=Never --command -- sleep 3600

4: root@ubuntu-165:~# kubectl exec -it box -- nslookup nginx
Server:		10.96.0.10
Address:	10.96.0.10:53

** server can't find nginx.default.svc.cluster.local: NXDOMAIN

*** Can't find nginx.svc.cluster.local: No answer
*** Can't find nginx.cluster.local: No answer
*** Can't find nginx.default.svc.cluster.local: No answer
*** Can't find nginx.svc.cluster.local: No answer
*** Can't find nginx.cluster.local: No answer

command terminated with exit code 1

**Comment by chrisohaver** [comment]
Please follow this guide: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

Also: https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax

**Comment by piwenzi** [comment]
thanks!
