### ISSUE TITLE
covernance: max 2 votes per org?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3430]
Thanos' governance added a 2 vote per org max: https://github.com/thanos-io/thanos/blob/c7e787d97bcf8aa2064816b85b0656ec0e55aaed/docs/governance.md#voting

I think this is worth emulating for the same reasons Thanos does it.

**Comment by yongtang** [comment]
At the moment we put a cap on `1/5` of the total number of names in `OWNERS` file.. At the moment, that gives us `14 * 1 / 5 = 2`.

The number `2` could increase in the future if more names are added to `OWNERS` file.

I think either way would work, want to hear how others think though.

**Comment by miekg** [comment]
no commented. Think things are fine as-is. Thanks @yongtang
