### ISSUE TITLE
Using `[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]` instead of `[0-9]{1,3}` would allow responses for only the possible IP ranges.

### ISSUE THREAD

**Issue by Kotfis** [coredns/coredns#3435]
Using `[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]` instead of `[0-9]{1,3}` would allow responses for only the possible IP ranges.
127.0.0.0 -> 127.0.0.255
(not taking into account the specific CIDR specific IPs)

_Originally posted by @stp-ip in https://github.com/coredns/coredns/issues/2977#issuecomment-508696248_

**Comment by chrisohaver** [comment]
@Kotfis, Feel free to reopen this issue, but please provide more information and context before doing so.
Are you reporting an issue? Looking for a new feature? Looking for assistance?
