### ISSUE TITLE
how to log the upstream dns server name/ip

### ISSUE THREAD

**Issue by marcpascual** [coredns/coredns#3436]
coredns version: 1.3.1

I am trying to find out which upstream server my dns requests are being forwarded to. I've been trying some custom log strings but I haven't found what will give me upstream dns server name/ip. my coredns config is as follows:

```
    .:53 {
        errors
	log . "requested by {remote}:{port} to {local}"
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4 1.1.1.1
        cache 1
        loop
        reload
        loadbalance
    }
```

the output I am getting is:
```
[INFO] Reloading
2019-11-09T09:53:39.943Z [INFO] plugin/reload: Running configuration MD5 = 10e6f517bdf15f1c0077f13a24e15cc3
[INFO] Reloading complete
2019-11-09T09:53:39.967Z [INFO] requested by 127.0.0.1:34157 to [::]
2019-11-09T09:53:57.174Z [INFO] requested by 10.1.0.12:49037 to [::]
2019-11-09T09:53:57.175Z [INFO] requested by 10.1.0.12:32883 to [::]
2019-11-09T09:53:57.841Z [INFO] requested by 10.1.0.12:39332 to [::]
2019-11-09T09:53:58.117Z [INFO] requested by 10.1.0.12:56002 to [::]
```
none from the placeholder seems to refer to servers/ip except for {local} and {remote}
https://coredns.io/plugins/log/

**Comment by miekg** [comment]
you can't atm.

it's forward to any of the ips you have defined there. Metrics do expose this info iirc

**Comment by SudoNova** [comment]
Sorry for bumping an old issue, 
suppose you have specified  `forward . 8.8.8.8 192.168.2.30` where the latter can resolve local ips, hereby querying an intranet address might return nxdomin, or the correct ip (default configuration with `policy` set to `random`).
Now 8.8.8.8 can be replaced by a secondary nameserver which for some reasons is not up to date with the primary, or even you might use `forward . /etc/resolv.conf` which is the default configmap on kubernetes, and `/etc/resolv.conf`might contain `nameserver 127.0.0.1`
In all the above cases you'll need to see upstream ip address in logs to diagnose this problem.

**Comment by chrisohaver** [comment]
> suppose you have specified forward . 8.8.8.8 192.168.2.30 where the latter can resolve local ips, hereby querying an intranet address might return nxdomin, or the correct ip (default configuration with policy set to random).

The proper way to handle that is to create another server block for the intranet domain that forwards to the intranet DNS.

> you might use forward . /etc/resolv.conf which is the default configmap on kubernetes, and /etc/resolv.conf might contain nameserver 127.0.0.1

That scenario should be detected by the _loop_ plugin, which is enabled in the default configmap on kubernetes.


A wonky work around could be to temporarily set up self forwarding to local ports with separate logging... e.g.

```
. {
  forward . 127.0.0.1:5388 127.0.0.1:5388 
}

.:5388 {
  log "{remote}:{port} - {>id} \"{type} {class} {name} {proto} {size} {>do} {>bufsize}\" {rcode} {>rflags} {rsize} {duration} via 8.8.8.8"
  forward 8.8.8.8
}

.:5399 {
  log "{remote}:{port} - {>id} \"{type} {class} {name} {proto} {size} {>do} {>bufsize}\" {rcode} {>rflags} {rsize} {duration} via 8.8.4.4"
  forward 8.8.4.4
}
```
