### ISSUE TITLE
add OWNERS file to bufsize

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3440]
@ykhr53 can you add a OWNERS file to bufsize with you in it? I'll send you a github invite for this org as well

**Comment by ykhr53** [comment]
OK, I'll add it! And thank you for the invitation!

**Comment by miekg** [comment]
can you also email me your email? I'll add you to the low-traffic maintainers list

**Comment by ykhr53** [comment]
OWNERS file has been merged and I got an email from you.
I'll close this issue.
