### ISSUE TITLE
Can't access the headless service 

### ISSUE THREAD

**Issue by YasminBZ** [coredns/coredns#3443]
<!-- 
When reporting bugs and requesting assistance, please include:
* the version of CoreDNS you are using
Hello everyone 
I have a problem when trying to call my statefulset headless service , i can't access it neither  from inside the cluster not from outside 
Im using Coredns version : 1.1.3
My Corefile:

apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
          # pods disabled
           endpoint_pod_names
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2019-10-26T16:39:25Z
  name: coredns
  namespace: kube-system
  resourceVersion: "684982"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 2b89c0c2-f80f-11e9-8f90-0800270d9f27

Here is some of my coredns logs:

172.17.0.12:48369 - [13/Nov/2019:19:44:53 +0000] 36565 "A IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,aa,rd,ra 224 118.793µs
172.17.0.12:37395 - [13/Nov/2019:19:44:53 +0000] 9824 "AAAA IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,aa,rd,ra 169 87.211µs
172.17.0.12:44547 - [13/Nov/2019:19:44:53 +0000] 40838 "AAAA IN hello-default.default.svc.cluster.local. udp 84 false 512" NXDOMAIN qr,rd,ra 177 47.113µs
172.17.0.12:40999 - [13/Nov/2019:19:44:53 +0000] 23380 "A IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 224 39.094µs
172.17.0.12:50839 - [13/Nov/2019:19:44:53 +0000] 28061 "AAAA IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 169 52.98µs
172.17.0.12:38892 - [13/Nov/2019:19:44:53 +0000] 49491 "A IN newdeploy-hello-default.fission-function.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 224 75.521µs
172.17.0.12:46358 - [13/Nov/2019:19:44:53 +0000] 27583 "A IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 224 79.137µs
172.17.0.12:50147 - [13/Nov/2019:19:44:53 +0000] 3257 "AAAA IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 169 35.665µs

Any one can help me to solve this problem please .
Thank you

**Comment by YasminBZ** [comment]
Hello everyone 
I have a problem when trying to call my statefulset headless service , i can't access it neither  from inside the cluster not from outside 
Im using Coredns version : 1.1.3
My Corefile:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
          # pods disabled
           endpoint_pod_names
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2019-10-26T16:39:25Z
  name: coredns
  namespace: kube-system
  resourceVersion: "684982"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 2b89c0c2-f80f-11e9-8f90-0800270d9f27

```
Here is some of my coredns logs:

```
172.17.0.12:48369 - [13/Nov/2019:19:44:53 +0000] 36565 "A IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,aa,rd,ra 224 118.793µs
172.17.0.12:37395 - [13/Nov/2019:19:44:53 +0000] 9824 "AAAA IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,aa,rd,ra 169 87.211µs
172.17.0.12:44547 - [13/Nov/2019:19:44:53 +0000] 40838 "AAAA IN hello-default.default.svc.cluster.local. udp 84 false 512" NXDOMAIN qr,rd,ra 177 47.113µs
172.17.0.12:40999 - [13/Nov/2019:19:44:53 +0000] 23380 "A IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 224 39.094µs
172.17.0.12:50839 - [13/Nov/2019:19:44:53 +0000] 28061 "AAAA IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 169 52.98µs
172.17.0.12:38892 - [13/Nov/2019:19:44:53 +0000] 49491 "A IN newdeploy-hello-default.fission-function.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 224 75.521µs
172.17.0.12:46358 - [13/Nov/2019:19:44:53 +0000] 27583 "A IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 224 79.137µs
172.17.0.12:50147 - [13/Nov/2019:19:44:53 +0000] 3257 "AAAA IN hello-default.default.svc.cluster.local. udp 76 false 512" NOERROR qr,rd,ra 169 35.665µs
```
Any one can help me to solve this problem please .
Thank you

**Comment by chrisohaver** [comment]
Can you share full transcript of the queries you are trying, and the result you get?

Also, please share your Stateful Set definition, and Headless Service definition.

**Comment by miekg** [comment]
closing out these anonymous request for help https://berthub.eu/articles/posts/anonymous-help/
