### ISSUE TITLE
How to test coredns with tcp request?

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3447]
tls://example.org:8800 grpc://example.org:9900  {
 hosts {
    10.6.6.2 sms.service
    10.6.6.3 search.service
  }
}
start a tls server

I found a test is  dig @127.0.0.1  sms.service
how to test it with tcp? how to send the params of domain to 127.0.0.1

**Comment by chrisohaver** [comment]
duplicate of #3448
