### ISSUE TITLE
how to test  https server ?how to get A record?

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3448]
start a https server corefile 
https://127.0.1.1  {
bind 127.0.0.1
hosts {
10.6.6.2 sms.service
10.6.6.3 search.service
}
}

 but when request https://127.0.0.1 no request income
and how to test it ？ https://127.0.0.1?host=sms.service ???
how to get the  A record?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] how to test  http..." ]
>how to start a https server ?
>
>https://example.org {
>bind 127.0.0.1
>hosts {
>10.6.6.2 sms.service
>10.6.6.3 search.service
>}
>}
>
>and how to test it ？ https://127.0.0.1?host=sms.service ???
>how to get the  A record?

this is DoH, I actually don't know if an easy way to query it and dig certainly 
doesn't support it yet.

Search for "doh dns query cli" on google or something


/label: question

**Comment by chrisohaver** [comment]
You can try using a proxy ... ala ...

https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/

I have not tried it, but I expect you could just point it to your coredns instance instead of cloudflare.

**Comment by chrisohaver** [comment]
... you could also use coredns itself as a proxy...


https://coredns.io/2016/11/26/dns-over-https/

**Comment by zzxap** [comment]
I post to https://mydomain/dns-query
:method = POST
:scheme = https
:authority = cloudflare-dns.com
:path = /dns-query
accept = application/dns-message
content-type = application/dns-message
content-length = 33

it return 
dns: bad rdata

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] how to test  ..." ]
>I post to https://mydomain/dns-query
>:method = POST
>:scheme = https
>:authority = cloudflare-dns.com
>:path = /dns-query
>accept = application/dns-message
>content-type = application/dns-message
>content-length = 33
>
>it return
>dns: bad rdata

that may or may not be a bug. Sorry the https side of things is relativly new 
and lightly tested, because there wasn't much https DNS out there at the time.

**Comment by zzxap** [comment]
I get the dns with https
https://mydomain/dns-query?dns=4AIBAAABAAAAAAAABnNlYXJjaAdzZXJ2aWNlAAAwAAE

it return below, but not return the ip 10.6.6.3  in the Corefile ->host why?
-----------------------------------
;; opcode: QUERY, status: REFUSED, id: 57346
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;search.service.        IN       DNSKEY
---------------------------------------

**Comment by zzxap** [comment]
https://mydomain/dns-query?dns=Sh4BAAABAAAAAAAABnNreWRucwVsb2NhbAAAMAAB
 not return the host to me
just return the domain 。why？？

**Comment by zzxap** [comment]
dig +short skydns.local @localhost  
can return the host ip
but https can not。it just return domain i request。

**Comment by shynome** [comment]
if anyone also want test DoH server in locale network, you can use `Caddy` reverse proxy `CoreDNS`, then use `dig` check DoH server

1.  init CoreDNS

    ```conf
    # Corefile
    https://.:8053 {
      debug
      log
      hosts {
        127.0.0.1 example.com
      }
      whoami
    }
    ```

2.  set Caddy reverse proxy

    ```conf
    # Caddyfile
    {
      admin off
      servers :8054 {
        # h2c must be enabled, dig use it
        protocols h1 h2 h2c h3
      }
    }

    http://:8054 {
      log
      reverse_proxy http://127.0.0.1:8053
    }
    ```

3.  use dig check DoH server

    ```sh
    dig @127.0.0.1 -p 8054 +http-plain-get +retry=0 example.com
    ```
