### ISSUE TITLE
How coredns configmap is updated while the coredns version is updated in kubernetes plugin?

### ISSUE THREAD

**Issue by skycmoon** [coredns/coredns#3453]
Hi,

I have a question how coredns k8s plugin maintains the coredns ConfigMap because I've not found a good documentation explaining about that. 

I need to make a change (adding stub domains) in the coredns ConfigMap, but I need to know a right way, which is not affected by future coredns upgrade. I don't want a situation that coredns overwrites my changes in the coredns ConfigMap while the coredns is updated. 

And actually, this is also related to a question, how do we properly update coredns ConfigMap while we upgrade the coredns version. I saw `proxy` is changed to `forward` after version 1.4.0. this keyward can be used to the added stub domain. What is the process to deal with this kind of breaking changes? Do you allow both ways upto certain version?

If there is a documentation explaining about those questions, please point the documentation, if not, please answer my question.

Thanks.

**Comment by chrisohaver** [comment]
Upgrades of coredns in kubernetes are controlled by the kubernetes management software you use. For example kubeadm. Each k8s mgmt tool can handle this differently. Kubeadm uses our migration lib, in the coredns/corefile-migration repo. It migrates deprecated plugins such as proxy->forward while retaining custom configs such as stub domain configs. 

As for backward compatibility between versions in coredns,  we follow our deprecation policy described in the readme of this repo - maintaining backward compatibility for a limited time.

**Comment by chrisohaver** [comment]
I should add: 1.16 is the first version of k8s/kubeadm that does corefile migrations during upgrades. Prior to that, the existing corefile was always left untouched during an upgrade. K8s 1.16 included for the first time, a version of coredns that had introduced a k8s related backward compatibility.

**Comment by skycmoon** [comment]
Got it. Thanks for the information.
