### ISSUE TITLE
plugin/file: improve less.go 

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3456]
This is a bit of a mess: https://github.com/coredns/coredns/blob/master/plugin/file/tree/less.go, this needs to be allocation less and maybe sort differently, although canonical ordering may make sense. Moving to a different tree and actually mimicking the dns structure might also make sense, but would make the tree much deeper.

Also `insert` reverse the arguments when calling `Less` https://github.com/coredns/coredns/blob/master/plugin/file/tree/tree.go#L192

**Comment by miekg** [comment]
the reversal of args happens in https://github.com/coredns/coredns/blob/master/plugin/file/tree/elem.go#L101

**Comment by miekg** [comment]
@jpicht this is also slow and generates garbage; might be a potentially something we want to move to miekg/dns as well - once actually good :)

**Comment by jpicht** [comment]
I had a quick hack at it: https://github.com/jpicht/coredns/tree/less
It passes all current tests and makes less roughly 20% faster, not sure if it's actually correct though.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/file: ..." ]
>I had a quick hack at it: https://github.com/jpicht/coredns/tree/less
>It passes all current tests and makes less roughly 20% faster, not sure if it's actually correct though.

Another things are nice there as well:

* `e.name = rr.Header().Name` in newELem() is a good one and nice simplifies
Name().
* ah, you've put all your stuff in name.go - I like the approach, seems sensible
 to cache some of this - I need to take a much closer look to what you did
 though.

I'll most like fork your code back and then add/change/remove things and PR it -
this means you should also retain ownership over the lines of code I didn't
change.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
can be reopened when someone works on it.
