### ISSUE TITLE
https dns query params  this base64 is make from what params?

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3467]
curl -H 'accept: application/dns-message' -v 'https://cloudflare-dns.com/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' | hexdump

q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB this base64 is make from what params?

**Comment by miekg** [comment]
this is not really relevant to this project, not sure where else you can ask these kind of questions though.

**Comment by stp-ip** [comment]
Not sure, but I think this is the DNS wireformat encoded with base64.
So decoding this would lead again to the DNS wireformat.
Some info: https://tools.ietf.org/html/rfc1035#section-4
