### ISSUE TITLE
Get list of hosted zones from running CoreDNS server

### ISSUE THREAD

**Issue by shashidharatd** [coredns/coredns#347]
Hello @miekg  
How do i get list of zones (managed zones/hosted zones) from a running CoreDNS server for which it is authoritative?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] Get list of hosted ..." ]

> Is there any way to get list of zones (managed zones/hosted zones) from a running CoreDNS server for which it is authoritative?

No you can't. Before the _auto_ middleware you should be able to tell from
looking at the Corefile.

How do you envision this to work?

/Miek

## 

Miek Gieben

**Comment by shashidharatd** [comment]
Thanks for clarifying @miekg . Right now we shall get the zones from Corefile. I was just wondering is there any message or api to get that.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Get list of hos..." ]

> Thanks for clarifying @miekg . Right now we shall get the zones from Corefile. I was just wondering is there any message or api to get that.

Ack. We might implement some as Catalog Zones
(https://kb.isc.org/article/AA-01401/0/A-short-introduction-to-Catalog-Zones.html)

There also needs to be a metric exporting the number of zones we are auth for.

I see no reason to close this issue, but this feature will only happen in the
004/005 timeframe.

**Comment by shashidharatd** [comment]
That would be great @miekg

**Comment by stp-ip** [comment]
Timeframe for 009?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Get list of h..." ]
>Timeframe for 009?

dunno, depends on how will work on it.

If we go this route we should probably implement: Catalog Zones:

https://datatracker.ietf.org/doc/draft-muks-dnsop-dns-catalog-zones/
(needs support for the APL record in Go DNS)

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
https://github.com/coredns/coredns/issues/660 is related

**Comment by miekg** [comment]
this will not happen any time soon.
