### ISSUE TITLE
Corefile:5 - Error during parsing: Unknown directive 'pdsql'

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3472]
https://coredns.io/explugins/pdsql/

./Corefile:5 - Error during parsing: Unknown directive 'pdsql'
I hava put 

pdsql:github.com/jinzhu/gorm/dialects/sqlite

to the end of plugin.cfg

my Corefile is 

test.:1053 {
    pdsql sqlite3 ./test.db {
        debug db
        auto-migrate
    }
}

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Corefile:5 - Erro..." ]
>./Corefile:5 - Error during parsing: Unknown directive 'pdsql'

you need to compile with this plugin enabled, see https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/

/close
/label: question

**Comment by zzxap** [comment]
add
pdsql_mysql:github.com/jinzhu/gorm/dialects/mysql
pdsql_sqlite:github.com/jinzhu/gorm/dialects/sqlite
to plugin.cfg
and then 
#go generate
#go build
build github.com/coredns/coredns: cannot load github.com/mattn/go-sqlite3: module github.com/mattn/go-sqlite3@latest (v2.0.0+incompatible) found, but does not contain package github.com/mattn/go-sqlite3

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Corefile:5 - ..." ]
>add
>pdsql_mysql:github.com/jinzhu/gorm/dialects/mysql
>pdsql_sqlite:github.com/jinzhu/gorm/dialects/sqlite
>to plugin.cfg
>and then
>#go generate
>#go build
>build github.com/coredns/coredns: cannot load github.com/mattn/go-sqlite3: module github.com/mattn/go-sqlite3@latest (v2.0.0+incompatible) found, but does not contain package github.com/mattn/go-sqlite3

We do not vet any external modules very much, seems gorm can't be compiled with 
Go modules are something (Go modules is biting us a lot). For my external Go 
modules like 'unbound' I've deleted go.{mod,sum}. entirely.

You can follow up with the author of the module.

/label: external
/label: bug

**Comment by jeffreyacegong** [comment]
added the following in plugin.cfg, compiles and runs. will test with db next. 

pdsql:github.com/wenerme/wps/pdns/model
pdsql_postgres:github.com/jinzhu/gorm/dialects/postgres
