### ISSUE TITLE
can not add plugin pdsql 

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3474]
https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/
https://coredns.io/explugins/pdsql/

1. add import in plugin.cfg, like
pdsql:github.com/jinzhu/gorm/dialects/sqlite
2.go get github.com/jinzhu/gorm/dialects/sqlite
3.go generate
4.go build

it show 

build github.com/coredns/coredns: cannot load github.com/mattn/go-sqlite3: module github.com/mattn/go-sqlite3@latest (v2.0.0+incompatible) found, but does not contain package github.com/mattn/go-sqlite3

add plugin pdsql fail

**Comment by chrisohaver** [comment]
External plugins are independently maintained.
Please raise the issue in the external plugin's repository.
