### ISSUE TITLE
can dig use in public network?

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3475]
in localhost use dig  is ok
dig +short skydns.local @localhost
but it out public network  use git  can not get skydns.local's ip
dig +short skydns.local @32.23.23.22

can dig use in public network?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] can dig use in pu..." ]
>in localhost use dig  is ok
>dig +short skydns.local @localhost
>but it out public network  use git  can not get skydns.local's ip
>dig +short skydns.local @32.23.23.22
>
>can dig use in public network?

off-topic

/close
