### ISSUE TITLE
coredns only for local network?

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3477]
coredns only for local network?

**Comment by yongtang** [comment]
@zzxap please be more specific on exactly the question you want to ask.

**Comment by zzxap** [comment]
I add an A record of a domain.can use dig get the host info
but use DNS over https can not return host info to me.

**Comment by yongtang** [comment]
@zzxap please list the exact steps and Corefile config, as well as the behavior of the dns request/response. Your description is quite vague. Hard to see the issue without more context.

**Comment by miekg** [comment]
closing out these anonymous requests for help see https://berthub.eu/articles/posts/anonymous-help/
