### ISSUE TITLE
can not get dns record out of local

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3484]
dig -t A skydns.local +trace @localhost
this is ok can show host of skydns.local 

dig -t A skydns.local +trace @41.24.219.12
but use this in other network  can not get  host of skydns.local 

is core dns only work for local network？

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] can not get dns r..." ]
>
>dig -t A skydns.local +trace @localhost
>this is ok can show host of skydns.local
>
>dig -t A skydns.local +trace @41.24.219.12
>but use this in other network  can not get  host of skydns.local
>
>is core dns only work for local network？

No, it should listen on all interface, unless you use the *bind* plugin.
