### ISSUE TITLE
please help me i have many domain names how to configure coredns?

### ISSUE THREAD

**Issue by getpool** [coredns/coredns#3485]
hello everyone, i have many domain names that need to be resolved to the same ip. how to configure coredns? please help me, thank you very much.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] please help me i ..." ]
>hello everyone, i have many domain names that need to be resolved to the same ip. how to configure coredns? please help me, thank you very much.

you can play around with the [*file*](https://coredns.io/plugins/file/) plugin, 
but may be get expensive with the number of domains.

I think a tiny plugin that just does what you want is the easiest way (if you 
know Go, and how)

/label: question

**Comment by getpool** [comment]
because there are too many domain names, there is no way to configure them one by one. how to configure this.

**Comment by yongtang** [comment]
You could try hosts plugin which should give you an easy way of config if all you need is a list of hosts to IPs.

**Comment by miekg** [comment]
closing out these anonymous requests for help see https://berthub.eu/articles/posts/anonymous-help/
