### ISSUE TITLE
编译出错！！求解！

### ISSUE THREAD

**Issue by snakwu** [coredns/coredns#3487]
* presubmit/context
** presubmit/filename-hyphen
** presubmit/import-testing
go: finding k8s.io/api latest
build github.com/coredns/coredns: cannot load k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest found (v0.0.0-20191121015604-11707872ac1c), but does not contain package k8s.io/api/admissionregistration/v1alpha1
** presubmit/test-lowercase
** presubmit/trailing-whitespace
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=d56dbffa-dirty" -o coredns
go: finding k8s.io/api latest
build github.com/coredns/coredns: cannot load k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest found (v0.0.0-20191121015604-11707872ac1c), but does not contain package k8s.io/api/admissionregistration/v1alpha1
Makefile:17: recipe for target 'coredns' failed
make: *** [coredns] Error 1

**Comment by snakwu** [comment]
GNU nano 2.9.3                        plugin.cfg                                  
# Directives are registered in the order they should be
# executed.
#
# Ordering is VERY important. Every plugin will
# feel the effects of all other plugin below
# (after) them during a request, but they must not
# care what plugin above them are doing.

# How to rebuild with updated plugin configurations:
# Modify the list below and run `go gen && go build`

# The parser takes the input format of
#     <plugin-name>:<package-name>
# Or
#     <plugin-name>:<fully-qualified-package-name>
#
# External plugin example:
# log:github.com/coredns/coredns/plugin/log
# Local plugin example:
# log:log

metadata:metadata
cancel:cancel
tls:tls
reload:reload
nsid:nsid
bufsize:bufsize
root:root
bind:bind
debug:debug
trace:trace
ready:ready
health:health
pprof:pprof
prometheus:metrics
errors:errors
log:log
dnstap:dnstap
acl:acl
any:any
chaos:chaos
loadbalance:loadbalance
cache:cache
rewrite:rewrite
dnssec:dnssec
autopath:autopath
template:template
transfer:transfer
hosts:hosts
route53:route53
azure:azure
clouddns:clouddns
federation:github.com/coredns/federation
k8s_external:k8s_external
kubernetes:kubernetes
file:file
auto:auto
secondary:secondary
etcd:etcd
loop:loop
forward:forward
grpc:grpc
erratic:erratic
whoami:whoami
on:github.com/caddyserver/caddy/onevent
sign:sign
block:github.com/missdeer/block
proxy:github.com/coredns/proxy

**Comment by stp-ip** [comment]
Would be great to get a cleaner issue decription with an actual problem description and more information.

It seems like you are trying to build CoreDNS and it tries to use a new Kubernetes API version, which isn't yet supported. Maybe some manual updates with your go modules?

**Comment by snakwu** [comment]
ubuntu 18.0.4
 go version 1.13.4
方法：
git clone https://github.com/coredns/coredns
cd coredns
make

我还在plugin.cfg添加了proxy:github.com/coredns/proxy

**Comment by snakwu** [comment]
问题解决
