### ISSUE TITLE
请问，如何编译添加proxy插件，谢谢

### ISSUE THREAD

**Issue by snakwu** [coredns/coredns#3488]
请问，如何编译添加proxy插件，谢谢

**Comment by miekg** [comment]
https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/

**Comment by snakwu** [comment]
我在修改plugin.cfg，添加proxy:github.com/coredns/proxy，然后make，报错，编译不通过
 #3487

**Comment by snakwu** [comment]
这里也有同样的错误！
https://github.com/coredns/proxy/issues/4

**Comment by snakwu** [comment]
希望能修复一下，因为要做域名分流，需要用到proxy插件，谢谢

**Comment by miekg** [comment]
let me take a look in a bit

**Comment by miekg** [comment]
proxy bug, coredns compiles fine

/close

**Comment by snakwu** [comment]
能否修复一下proxy插件，再次感谢

**Comment by liang-hiwin** [comment]
> 能否修复一下proxy插件，再次感谢

用我这个！使用v1.6.6编译出来的集成forward和proxy

- [ ] 
[coredns-v1.6.zip](https://github.com/coredns/coredns/files/3964580/coredns-v1.6.zip)
