### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by liang-hiwin** [coredns/coredns#3490]
build github.com/coredns/coredns: cannot load k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest (v0.0.0-20191121015604-11707872ac1c) found, but does not contain package k8s.io/api/admissionregistration/v1alpha1
Makefile:17: recipe for target 'coredns' failed
make: *** [coredns] Error 1

**Comment by snakwu** [comment]
又是是这个错误，应该是加了proxy插件吧？

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] HELP (#3490)..." ]
>build github.com/coredns/coredns: cannot load k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest (v0.0.0-20191121015604-11707872ac1c) found, but does not contain package k8s.io/api/admissionregistration/v1alpha1
>Makefile:17: recipe for target 'coredns' failed
>make: *** [coredns] Error 1

See https://github.com/coredns/proxy/pull/5

/close

**Comment by liang-hiwin** [comment]
> 又是是这个错误，应该是加了proxy插件吧？
我删除了还是不行啊！
