### ISSUE TITLE
CODEOWNERS: who? where?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3495]
This is a proposal to split the CODEOWNERS up a bit, so that we're not all get assigned a review on some top-level code change. I need at least two persons, otherwise I can't really make code changes. Please ping where you potentially want to be added.

* /plugin/pkg/ @miekg 
* /coremain/ @miekg 
* /core/ @miekg 
* /request/ @miekg 
* /plugin/* @miekg # doesn't inherit through

**Comment by chrisohaver** [comment]
I am willing to do reviews in any of these areas.

**Comment by johnbelamaric** [comment]
Same here.

**Comment by yongtang** [comment]
I can help in any of the above areas.

**Comment by stp-ip** [comment]
Same

**Comment by miekg** [comment]
ok, thanks guys, I'll prepare a PR
