### ISSUE TITLE
TLS does not support domain name input in the configuration file

### ISSUE THREAD

**Issue by liang-hiwin** [coredns/coredns#3496]
`.:5301 {
   forward . tls://9.9.9.9 {
       tls_servername dns.quad9.net
   }
   cache
}
.:5302 {
    forward . tls://1.1.1.1 {
        tls_servername cloudflare-dns.com
    }
    cache
}
.:5303 {
    forward . tls://8.8.8.8 tls://8.8.4.4 {
        tls_servername dns.google
    }
    cache
}`

The configuration given above is normal, but it will make an error if you fill it in tls: //xxx.com.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] TLS does not supp..." ]
>The configuration given above is normal, but it will make an error if you fill it in tls: //xxx.com.

what error? Which version of coredns, etc. etc.

/label needs info

**Comment by thb007** [comment]
`.:5301 {
   forward . tls://9.9.9.9 {
       tls_servername dns.quad9.net
   }
   cache
}
.:5302 {
    forward . tls://gn.kbsml.com {
        tls_servername cloudflare-dns.com
    }
    cache
}
.:5303 {
    forward . tls://8.8.8.8 tls://8.8.4.4 {
        tls_servername dns.google
    }
    cache
}`


root@debian:~/coredns# ./coredns -dns.port 1053
plugin/forward: not an IP address or file: "gn.kbsml.com"
root@debian:~/coredns#

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] TLS does not ..." ]
>plugin/forward: not an IP address or file: "gn.kbsml.com"

ah yes, you can only use IP adresses there as there is no way to resolve them.

/wai
/close
