### ISSUE TITLE
coredns how to add MxRecords and NSrecords

### ISSUE THREAD

**Issue by zzxap** [coredns/coredns#3499]
at this link https://github.com/coredns/coredns/tree/master/plugin/etcd
only say A  AAAA CName TXT records no MxRecords and NSrecords
how to add MxRecords and NSrecords？
like this?
etcdctl put /skydns/local/skydns/x6 '{"ttl":60,"mx":"this is a random text message."}'
etcdctl put /skydns/local/skydns/x6 '{"ttl":60,"ns":"this is a random text message."}'

**Comment by miekg** [comment]
/close 

See https://berthub.eu/articles/posts/anonymous-help/

**Comment by zzxap** [comment]
@miekg why you close my question
