### ISSUE TITLE
Getting config file from environmental variables.

### ISSUE THREAD

**Issue by zignig** [coredns/coredns#350]
With skydns it is possible to set the etcd servers on the command line.

However with coredns a config file is needed , with docker and rkt container this limits the way coredns can be configured as they need to be baked in.

Would it be possible to specify a environmental variable that holds the config so it can be passed on boot?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] Getting config file..." ]

> With skydns it is possible to set the etcd servers on the command line.
> 
> However with coredns a config file is needed , with docker and rkt container this limits the way coredns can be configured as they need to be baked in.
> 
> Would it be possible to specify a environmental variable that holds the config so it can be passed on boot?

Yes, it is possibly to feed it to CoreDNS via stdin - however I haven't used
this yet (nor documented it). Look for Caddyfile stdin/pipe to see what should
be possible. If CoreDNS does not do the same thing as Caddy wrt to config
loading we have a bug.

/Miek

## 

Miek Gieben

**Comment by zignig** [comment]
That's a cool feature that I did not know about.

It works on the command line  cat ConfigFile | coredns -conf stdin

However with rkt (.aci containers) it does not seem to be possible to pipe files into the container.

hmm , I will meditate on this :)

**Comment by miekg** [comment]
On 20 Oct 2016 8:01 am, "Simon Kirkby" notifications@github.com wrote:

> That's a cool feature that I did not know about.
> 
> It works on the command line cat ConfigFile | coredns -conf stdin
> 
> However with rkt (.aci containers) it does not seem to be possible to
> pipe files into the container.

WAT

**Comment by zignig** [comment]
:) 

Hehe,

I currently use   skydns in aci container.

/usr/bin/rkt run --net=host --insecure-options=http astralboot/rocket/
skydns -- -machines="http://127.0.0.1:2379" -addr="0.0.0.0:53" -verbose

when running rocket there does not seem to be a way to pipe the config file to the binary that will be running inside the container. 

you can pass environmental variables in though.

**Comment by miekg** [comment]
Is this a bug or feature in rkt? We could put the whole config in a var?
But I rather have caddy onboard for such a change.

**Comment by zignig** [comment]
I think it's a feature, there was a request for it some time ago. But it breaks the 'container' abstraction as you have to pass file descriptors out of the container. 

Anyway , being able to drop the config into an environment variable and tell caddy/coredns to grab it from there would be cool for all sorts of reasons. Kind a 12 Factor App thing... (if you like that style)

:)

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] Getting config ..." ]

> I think it's a feature, there was a request for it some time ago. But it breaks the 'container' abstraction as you have to pass file descriptors out of the container.
> 
> Anyway , being able to drop the config into an environment variable and tell caddy/coredns to grab it from there would be cool for all sorts of reasons. Kind a 12 Factor App thing... (if you like that style)
> 
> :)

Note you can use env vars _inside_ the Corefile already (again google for
caddyfile environment vars). This may or may not be enough for your use-case.

If you want everything in a env-var please open a bug on the caddy bugtracker
and reference this one. I'm not opposed, but usually mholt@ has opinions and I
don't want diverse too far from caddy just yet.

**Comment by zignig** [comment]
Posted , thanks for your consideration. ;)

**Comment by miekg** [comment]
closed upstream.
