### ISSUE TITLE
How to configure the use of DOH / DOT address?

### ISSUE THREAD

**Issue by liang-hiwin** [coredns/coredns#3507]
The document does not write an example of how to configure DOH / DOT. I do n’t know how to configure it now. Can you give me a specific configuration reference?

**Comment by greenpau** [comment]
@miekg , what does `anonymous` label means?

**Comment by greenpau** [comment]
@thb007 , for DOT please see  this [example](https://github.com/coredns/coredns/blob/master/plugin/tls/README.md#examples).

**Comment by milgradesec** [comment]
tls enabled config:
https://.:443 tls://.:853 {
         tls cert.pem key.pem ca.pem
         forward . 1.1.1.1
}

without tls it uses unencrypted http and tcp
https://.:80 tls://.:853 {
         forward . 1.1.1.1
}

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] How to config..." ]
>@miekg , what does `anonymous` label means?

https://berthub.eu/articles/posts/anonymous-help/

I'm ignoring most of these requests (mostly to keep my sanity)

**Comment by omicron-b** [comment]
@milgradesec any idea why I see this error in CoreDNS when trying to use it with my router?
`http: TLS handshake error from <ip and port>: local error: tls: bad record MAC`

my config:
```
https://.:443 {
    tls /etc/letsencrypt/live/<my domain>/cert.pem /etc/letsencrypt/live/<my domain>/privkey.pem /etc/letsencrypt/live/<my domain>/chain.pem
    forward . 127.0.0.1:53
}
```

**Comment by milgradesec** [comment]
That error means go crypto/tls stack failed to authenticate a TLS record due to invalid/corrupted [MAC](https://en.wikipedia.org/wiki/Message_authentication_code).

What client are you using?

Reference: https://github.com/golang/go/blob/40a144b94f14c3f3fbe06e097a236a5543ada57f/src/crypto/tls/conn.go#L318

**Comment by omicron-b** [comment]
@milgradesec thank you, found a configuration issue on my side, did not read `/etc/letsencrypt/live/<my domain>/README`

The correct config with Lets Encrypt would look like this:
```
https://.:443 {
    tls /etc/letsencrypt/live/<my domain>/fullchain.pem /etc/letsencrypt/live/<my domain>/privkey.pem
}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] How to config..." ]
>@milgradesec thank you, found a configuration issue on my side, did not read /
>etc/letsencrypt/live/<my domain>/README
>
>The correct config with Lets Encrypt would look like this:
>
>https://.:443 {
>    tls /etc/letsencrypt/live/<my domain>/fullchain.pem /etc/letsencrypt/live/<my domain>/privkey.pem
>}

thanks all

/close
