### ISSUE TITLE
HN bugs 

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#351]
Some comments from the HN post the require followup: (these are all documentation bugs)
- I don't know why they don't mention this on the site, but this has been merged back in as a module for Caddy (available at download time).
- It would be great if the site explained why it is different to the alternatives. If I was using Kubernetes for instances, why would I swap out the default service discovery mechanism for this one?
- Is this related to DNS service discovery (DNS-SD, RFC6763), or is it just a very poor choice of words?
- What's the basic difference between coredns and classic bind based dns??

And one via twitter:
- Please explain: caddy, kubernetes, middleware, etc.

Might farm these out into separate bugs

**Comment by stp-ip** [comment]
Seems like all these are answered and should be clear now right?
