### ISSUE TITLE
CoreDNS 1.6.6 Release Tracking

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#3519]
This issue is to keep track of 1.6.6 release. Specifically we want to update the https://github.com/miekg/dns that carries https://github.com/miekg/dns/pull/1044

/cc @miekg

**Comment by yongtang** [comment]
With #3520, #3530, #3531 merged in, I think we are ready for a new release (v1.6.6).

**Comment by yongtang** [comment]
@miekg @stp-ip   I will invoke the release 1.6.5 against master, will see if it works.

**Comment by yongtang** [comment]
@miekg I think the release is not invoked. Can you take a look?

**Comment by miekg** [comment]
loose the colon

**Comment by yongtang** [comment]
v1.6.6 is released 👍 🎉

**Comment by miekg** [comment]
I've got a PR for coredns.io ready locally.

**Comment by stp-ip** [comment]
This reminds me. Still need to dig through the coredns.io automation and update this to the current state. Let's hold me accountable for getting it done in 2019.

**Comment by miekg** [comment]
Also very glad to see that releasing CoreDNS is fairly easy to do. If I hadn't changed the bot; this  would have just all worked.

Thanks for pushing this @yongtang
