### ISSUE TITLE
poll: ui (admin interface) plugin

### ISSUE THREAD

**Issue by greenpau** [coredns/coredns#3522]
**What would you like to be added**:

Administrative user interface (UI) for managing and debugging CoreDNS via a web interface.

Key Features:

* React.js & Material UI driven (feel and look of https://github.com/kubernetes/dashboard)
* API in Golang, described via OpenAPI 3.0, generated by `OpenAPITools/openapi-generator`
* Delivered as part of `coredns` binary, i.e. `--ui` flag

❓ **Question to the Community**:

Do you think CoreDNS project would benefit from UI? If so, how? If not, why not?

**Comment by zouyee** [comment]
For UI/UE requirements, perhaps the command support manage and debug be a little more urgency?
@yongtang @miekg  WDYT ?

**Comment by greenpau** [comment]
> For UI/UE requirements, perhaps the command support manage and debug be a little more urgency?

@zouyee , the CLI probably warrants a separate poll.
* What are the things you would include in "manage and debug" interface of the cli?
* Inevitably, regardless whether it is UI or CLI, it would need an API, thoughts?

For example, per my  "manage and debug" question:

* I want to view CoreDNS logs
* I want to visualize CoreDNS actions on a particular query
* etc.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] poll: ui (adm..." ]
>For UI/UE requirements, perhaps the command support manage and debug be a little more urgency?
>@yongtang @miekg  WDYT ?

what problem are you solving?

**Comment by chrisohaver** [comment]
What specific debugging functions are you thinking of?

incoming/outgoing packet capture?
view active config? (active config not always same as corefile due to config load fail fallback)

**Comment by greenpau** [comment]
What specific debugging functions are you thinking of?

> incoming/outgoing packet capture?

@chrisohaver , absolutely. with the ability to specify a filter.

> view active config? (active config not always same as corefile due to config load fail fallback)

@chrisohaver , yes! Another one viewing zones + searching records in a zone.

Other UI features:
* Rewrite analyzer
* Zone builder: builds a zone file for a domain
* Corefile editor and validator

**Comment by miekg** [comment]
I'm not against (any) UI, but most of it can be a standalone binary. Specifically adding authn/authz to coredns is a nack from me; because that's very hard to get right and complex. I don't want to burden an internet facing binary with that complexity.

**Comment by greenpau** [comment]
> I don't want to burden an internet facing binary with that complexity.

@miekg , fair point. 

I use CoreDNS for my home network. At times, I want to track what my kids are doing on the internet. That's just one use case. Yes, I could put together an Prometheus & ELK stack, but that's an overkill. At the moment, the server does not have an API for querying against a running system. That would limit any UI/CLI tool development.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] poll: ui (adm..." ]
>> I don't want to burden an internet facing binary with that complexity.
>
>@miekg , fair point.
>
>I use CoreDNS for my home network. At times, I want to track what my kids are doing on the internet. That's just one use case. Yes, I could put together an Prometheus & ELK stack, but that's an overkill. At the moment, the server does not have an API for querying against a running system. That would limit any UI/CLI tool development.

I think an API makes sense; figuring out how this should look is a worth while exercise in
itself and would make future expansion possible - including an UI.

Taking your example as a starting point:

* you want to see what is happening for certain clients
* you may want to add a block or limit resolution for some domains?

I really think using your example as a starting point to flesh something out is a good
one.

Would do other DNS servers do?

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
btw caddy2 support some kind of ReST api. But I don't know how authn/authz are handled (if at all)

**Comment by greenpau** [comment]
> But I don't know how authn/authz are handled (if at all)

@miekg , imho it is no longer an issue because of JWT and SAML-based assertions. That is, there is no need to maintain user database. The API only validates SAML assertions and relies on the assertions' content to grant privileges. It is simple as having a config that says ... trust issuer XYZ. If a SAML assertion issued by that issuer has role Admin, authorize the assertion's holder to perform "admin"-type actions.

At the same time, one could pass a token or a set of tokens when starting an API. That is, no reliance on SAML, static passwords.

> btw caddy2 support some kind of ReST api.

As per API, I would say generating the API server code using [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator) is the way to go. Once we have OpenAPI 3.0 spec, it is pretty straightforward to generate API client.

I would say a way forward is creating an OpenAPI spec, without any authentication. It could be as simple as having a few endpoints `/api/v1/config/reload`, `/api/v1/config/view`, etc.

It probably makes sense to mention [WhiteHouse/api-standards](https://github.com/WhiteHouse/api-standards).

**Comment by miekg** [comment]
poll concluded. 

Note all these things can be done externally and write a Corefile which will be automatically reloaded with the reload plugin.

**Comment by aminalaee** [comment]
Has there been any progress with this?
I'll be able to contribute to any internal/extrrnal plugin for this.

**Comment by lknite** [comment]
I was looking for an opensource infoblox alternative, of all the dns servers out there coredns seems like it's the right choice, a gui would make it an even better choice.  My use case is I use external-dns to reflect fqdn / dns / ingress over to a dns server for use within the lab environment.  So, looking for a coredns implementation which I'd spin up in a kubernetes cluster, but which doesn't have any of the *.*.cluster.local dns entries in it.

**Comment by macduff23** [comment]
all about  shell administration , automation / for security sake, but when training jr ops and admin staff a UI can be really helpful - web or UI also provides a secondary interface which is nice to have as back up..

**Comment by ajeygore** [comment]
If at all useful, I wrote this https://github.com/ajeygore/coredns_ui for managing coredns with redis plugin support, but can easily extended to any.
