### ISSUE TITLE
plugin/pkg/parse: Does not handle IPv6 with %zone

### ISSUE THREAD

**Issue by bcrochet** [coredns/coredns#3528]
**What happened**:
With a link local IPv6 address with %zone in resolv.conf, the forward plugin (and more specifically, the HostPortOrFile function in plugin/pkg/parse.go) fails with the message:

plugin/forward: not an IP address or file: "fe80::xxxx:ff:fexx:xxxx%ens3"

(I x'd out the mac address)

**What you expected to happen**:
Forward plugin worked properly

**How to reproduce it (as minimally and precisely as possible)**:
Pass an IPv6 address with %zone or resolv.conf with a nameserver as %zone to HostPortOrFile 

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.6.x
- Corefile:
. {
  foward . fe80::xxxx:ff:fexx:xxxx%ens3
}
- OS (e.g: `cat /etc/os-release`): RHEL 8.1

**Comment by miekg** [comment]
closed via #3527
