### ISSUE TITLE
How can I execute bash inside coredns container to investigate problems or check configuration file

### ISSUE THREAD

**Issue by rhollins** [coredns/coredns#3533]
I deployed coredns inside Kubernetes from chart using the following command:

```
helm install \
  my-coredns \
  stable/coredns \
  --namespace admin \
  --values ./values.yaml
```

**What happened**:

I need to check values inside corefile /etc/coredns/Corefile but I can't get inside container with any command, for example:

kubectl exec -it my-coredns-coredns-7dc847dd95-bgvdr -- /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
command terminated with exit code 126

**What you expected to happen**:

I expect to be able to either run bash or any command like cat so I can view the logs file or configuration files to investigate.

**Comment by rhollins** [comment]
I found out that the corefile is available as configmap although still cant exec into container

**Comment by johnbelamaric** [comment]
The image does not contain a shell. Logs can be viewed with `kubectl`. As you mentioned you have found the config file is available as a ConfigMap.
