### ISSUE TITLE
core/plugin/zplugin.go] Error 1

### ISSUE THREAD

**Issue by liang-hiwin** [coredns/coredns#3540]
go: github.com/coredns/coredns/core/plugin imports
        github.com/coredns/fallback imports
        github.com/mholt/caddy: github.com/mholt/caddy@v1.0.4: parsing go.mod:
        module declares its path as: github.com/caddyserver/caddy
                but was required as: github.com/mholt/caddy
make: *** [Makefile:62: core/plugin/zplugin.go] Error 1

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] core/plugin/zplug..." ]
>go: github.com/coredns/coredns/core/plugin imports
>        github.com/coredns/fallback imports
>        github.com/mholt/caddy: github.com/mholt/caddy@v1.0.4: parsing go.mod:
>        module declares its path as: github.com/caddyserver/caddy
>                but was required as: github.com/mholt/caddy
>make: *** [Makefile:62: core/plugin/zplugin.go] Error 1

/label anonymous
/label external

/close

**Comment by liang-hiwin** [comment]
@miekg Why is it closed? Can you give a solution?

**Comment by chrisohaver** [comment]
The external plugin (fallback) needs to have its caddy imports updated to the current import path.
