### ISSUE TITLE
Using `health` and `prometheus` plugins together, on the same port, results in 404 flapping on their respective endpoints

### ISSUE THREAD

**Issue by lisa** [coredns/coredns#3542]
**What happened**:

Using `health` and `prometheus` plugins in conjunction, on the same port, results in flapping 404s between each endpoint, `/health` and `/metrics`, respectively.

**What you expected to happen**:

I expect both endpoints to work reliably and not periodically return 404s.

**How to reproduce it (as minimally and precisely as possible)**:

Today, HEAD is acb75ea904c2405b7b821d90d8cb7bf6a7e3f7df, which contains this issue:

Clone:

    mkdir -p $(go env GOPATH)/src/github.com/coredns
    cd $(go env GOPATH)/src/github.com/coredns
    git clone https://github.com/coredns/coredns.git

Compile `GO111MODULE=on make`

Use a minimal Corefile:

    . {
      prometheus :8081
      health :8081
      forward . 8.8.8.8 8.8.4.4
    }

Launch, on a non-port 53 port (this host runs a nameserver, so 53 is unavailable): `./coredns -conf Corefile-minimal  -dns.port 22222`

From another terminal, verify it resolves correctly:

    lisa@arsenic ~ $ dig github.com @192.168.86.10 -p 22222 +short
    140.82.113.3

Try to request `/health` endpoint, note how it "flaps":

    lisa@arsenic ~ $ curl http://192.168.86.10:8081/health;echo
    404 page not found
    lisa@arsenic ~ $ curl http://192.168.86.10:8081/health;echo
    404 page not found
    lisa@arsenic ~ $ curl http://192.168.86.10:8081/health;echo
    OK
    lisa@arsenic ~ $ curl http://192.168.86.10:8081/health;echo
    404 page not found

Similar for `/metrics` endpoint:

    lisa@arsenic ~ $ curl -o - -s http://192.168.86.10:8081/metrics | head -n2
    # HELP coredns_build_info A metric with a constant '1' value labeled by version, revision, and goversion from which CoreDNS was built.
    # TYPE coredns_build_info gauge
    lisa@arsenic ~ $ curl -o - -s http://192.168.86.10:8081/metrics | head -n2
    404 page not found
    lisa@arsenic ~ $ curl -o - -s http://192.168.86.10:8081/metrics | head -n2
    # HELP coredns_build_info A metric with a constant '1' value labeled by version, revision, and goversion from which CoreDNS was built.
    # TYPE coredns_build_info gauge

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 

CoreDNS-1.6.6, linux/arm64, go1.12.6, acb75ea9

- Corefile:

        . {
          prometheus :8081
          health :8081
          forward . 8.8.8.8 8.8.4.4
        }

- logs, if applicable: N/A
- OS (e.g: `cat /etc/os-release`):

Based on [Armbian](https://www.armbian.com/), running Rock64 (aarch64) hardware. Go version 1.12.6. Kernel version 5.1.0.

        NAME="Ubuntu"
        VERSION="18.04.3 LTS (Bionic Beaver)"
        ID=ubuntu
        ID_LIKE=debian
        PRETTY_NAME="Ubuntu 18.04.3 LTS"
        VERSION_ID="18.04"
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        VERSION_CODENAME=bionic
        UBUNTU_CODENAME=bionic

- Others:

With a quick git bisect, it appears 2503df90 has introduced this. Prior to that point an address already in use error would print, with the same Corefile (as above). See also #3455, which created pkg/reuseport.

**Comment by miekg** [comment]
these were never intended to work on the same port. Quite supprised you see this flipping
behavior. I would say this works-as-intended, you shouldn't use the same port.

/plugin health
/plugin metrics
/wai

**Comment by lisa** [comment]
@miekg Should behaviour be changed so that it disallows the port reuse in this way? I think a reasonable person might expect both the health and metrics endpoints to work with the port reuse in a consistent way.

**Comment by miekg** [comment]
Don't know. Doing what you ask is some major work. For the time being I
think this could be documented better
