### ISSUE TITLE
 Does anyone need a consul backend like me

### ISSUE THREAD

**Issue by poppyred** [coredns/coredns#3546]
**New consul plugin for coredns**:

**I in the production of heavy use of consul, the hope can have a consul backend support, also can think traditional DNS support wildcard**:

**Comment by sodabrew** [comment]
Subscribe. I am presently investigating https://github.com/segmentio/coredns-plugins/tree/master/consul as well.

**Comment by sodabrew** [comment]
On my first spin with segment's coredns consul plugin, I was not able to get acceptable performance - queries seemed not to be cached despite the flags to serve stale and set a 10s TTL - but I think this is something on my end, I feel like I don't have the hang of CoreDNS configuration yet.

@poppyred Is your PR #3545 new code from scratch? Have you used it at scale? I'm going to try it out next to see how it goes!

**Comment by miekg** [comment]
I would like to _not_ merge any new backends until we have common ground where adding new ones is trivial. The PR luckily doens't add any new dependencies (it seems we've already include the entire internet). But the code is very much cut and pasted from the etcd backend which is a BIG sign things can be improved here. 

So this just needs to live as an external dep.
