### ISSUE TITLE
bind Plugins           Dig results are different

### ISSUE THREAD

**Issue by Futurefangyuan** [coredns/coredns#3549]
1. ip address

 lo: 127.0.0.1
 bond1: 10.64.8.1

2. corefile 
```
. {
  hosts {
    fallthrough
  }
  bind 127.0.0.1
  forward . 114.114.114.114 223.6.6.6 {
    #force_tcp
    max_fails 3
    expire 5s
    health_check 5s
    policy sequential
  }
  health 127.0.0.1:18080
  prometheus 127.0.0.1:9153
  any
  cache 10
  reload 30s
  log
  errors
}

bre.dz11.com {
  file /data/coredns/zone/bre.dz11.com
  auto bre.dz11.com {
      directory /data/coredns/zone/bre.dz11.com
      reload 10s
  }
  cache 10
  reload 15s
  log
  errors
}
```

3. dig  
```
[root@dns.a64-8-1.prod.cpd /data/coredns/conf]
#  dig test.bre.dz11.com @10.64.8.1 +short
10.32.215.1
```
```
[root@dns.a64-8-1.prod.cpd /data/coredns/conf]
#  dig test.bre.dz11.com @127.0.0.1 +short          　　＃This is the wrong resolution address
10.1.61.242
```

**Comment by stp-ip** [comment]
This still holds: https://github.com/coredns/coredns/issues/3498#issuecomment-564472596

**Comment by chrisohaver** [comment]
@Futurefangyuan, I edited your description so it could be readable.  Please look at the simple changes I made so you can see how to do that in the future. Thanks!

Beyond that, more explanation is needed here for others to understand the issue better.

**Comment by JensErat** [comment]
Stumbled over the same issue -- I also wanted to forward only requests from the local network, so I used `bind` to limit the forward block to the internal IP address (you limited to localhost). Result: there are multiple sockets, and the one fetching localhost requests does not take the more specific configuration blocks into account.

Solution: use the new ACL feature instead.
