### ISSUE TITLE
TXT Lookup does not resolve via CNAME

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#3556]
**What would you like to be added**:

Allow CoreDNS to lookup TXT records via CNAME.

**Why is this needed**:

From my observations, DNS servers will normally facilitate an answer to a TXT query via CNAME.  Currently, to the best of my knowledge, this is not supported by CoreDNS.

An example of this request running against a local DNS Server is below.  I've also proven this functionality with several other global DNS servers as well.

```
$ dig @localhos -t TXT cname.example.local

; <<>> DiG 9.10.6 <<>> -t TXT cname.example.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12473
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;cname1.example.local.		IN	TXT

;; ANSWER SECTION:
cname1.example.local.	60	IN	CNAME	cname2.example.local.
cname2.example.local.	60	IN	CNAME	server.example.local.
server.example.local	56	IN	TXT     "test"
```

**Comment by miekg** [comment]
has been merged.
