### ISSUE TITLE
High memory usage with large hosts file

### ISSUE THREAD

**Issue by ricardbejarano** [coredns/coredns#3561]
**What happened**:

CoreDNS has `528Mi` (source: `kubectl top pods`) of memory used for a 858.947 (about `24MiB`) hosts blacklist file.

**What you expected to happen**:

I expected memory usage to be somewhat closer to the size of the hosts file, assuming CoreDNS loads it into memory; or memory usage not increasing at all by reading the file from disk (like Dnsmasq IIRC).

**How to reproduce it (as minimally and precisely as possible)**:

I can provide the blacklist if you need it, or else just generate a hosts file with +800k hosts pointing to `0.0.0.0`.

See my `Corefile` below.

**Environment**:

- the version of CoreDNS: `1.6.6` (but has been happenning to me since I started using CoreDNS months ago).
- Corefile:
```
local:65535 {  # Kubernetes' readiness and liveness probes
  ready
  health
}

(global) {
  log
  errors

  cache 86400 {
    prefetch 5 10m 10%
  }
  dnssec
  loadbalance

  prometheus :9153
}

(blacklist) {
  hosts /etc/hosts.blacklist {
    reload 86400s  # CPU usage spikes during reload so I keep it to once a day
    no_reverse  # in theory this should reduce memory footprint, am I right?
    fallthrough
  }
}

(cloudflare) {
  forward . tls://1.1.1.1 tls://1.0.0.1 {
    tls_servername cloudflare-dns.com
  }
}

.:5300 {  # this weird port is NAT'ed into 53/UDP  (must use port > 1023 because CoreDNS runs as non-root)
  import global
  import blacklist
  import cloudflare
}

tls://.:5301 {  # this weird port is NAT'ed into 853/TCP  (must use port > 1023 because CoreDNS runs as non-root)
  import global
  import blacklist
  import cloudflare
  tls /etc/tls/fullchain.pem /etc/tls/privkey.pem
}
```

- OS (e.g: `cat /etc/os-release`): running in a Kubernetes pod atop an Ubuntu Server 18.04.3 Kubernetes node ([link to the container image](https://github.com/ricardbejarano/coredns), though the same happens with the official CoreDNS image). I don't think this has to do with memory usage as I can replicate this on my laptop with Docker for Mac.

**Comment by miekg** [comment]
maybe dnsmasq mmaps or something, we load it all into memory.

**Comment by ricardbejarano** [comment]
And wouldn't offloading hosts to disk after a user-settable threshold be a good idea?
