### ISSUE TITLE
请问,forward和proxy插件如何做到多个上游dns负载从查询结果中选择最快的ip来访问网站?谢谢

### ISSUE THREAD

**Issue by snakwu** [coredns/coredns#3568]
请问,forward和proxy插件如何做到多个上游dns负载从查询结果中选择最快的ip来访问网站?谢谢

**Comment by miekg** [comment]
> Excuse me, how do the forward and proxy plugins achieve multiple upstream DNS loads to select the fastest IP from the query results to access the website? Thank you

There is no way to do this currently, the implemented policies round-robin between the upstreams.
