### ISSUE TITLE
Enabling External Plugins in Corefile

### ISSUE THREAD

**Issue by alialshamali** [coredns/coredns#3569]
I have been trying to use the redis external plugin using CoreDNS helm chart. I have been trying to enable the plugin but I am totally confused. In the [documentation](https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/) you can enable or disable plugins in the core file without compiling. I can't find the syntax to do that. All I have which is this redis:github.com/hawell/redis so how would I enable redis in the corefile on the fly?

**Comment by missdeer** [comment]
add this line into `plugin.cfg`, maybe follow `cache:cache`, then `make` again

**Comment by alialshamali** [comment]
@missdeer I understood that part, but there no way to rewrite that from the Corefile?

**Comment by missdeer** [comment]
i think Corefile contains runtime configurations only

**Comment by snakwu** [comment]
> i think Corefile contains runtime configurations only

你好,不知道你有否研究过,如果从多个dns上游负载平衡,然后做到在对域名查询出来的多个ip中,挑选ping最低最快的ip来访问网站,谢谢

**Comment by alialshamali** [comment]
@missdeer Thanks will just compile to get the plugin.
