### ISSUE TITLE
DNS requests per Client IP

### ISSUE THREAD

**Issue by narainkrishh** [coredns/coredns#3572]
**What would you like to be added**:
A possibility to query DNS request made per client ip address.

**Why is this needed**:
This will help identify the DNS requests as spread across clients, will help further to be displayed in a grafana dashboard.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] DNS requests per ..." ]
>**What would you like to be added**:
>A possibility to query DNS request made per client ip address.
>
>**Why is this needed**:
>This will help identify the DNS requests as spread across clients, will help further to be displayed in a grafana dashboard.

you can do this by enabling query logging.

If you're looking to have this done via metrics, then 'no', this will not be added,
because of the label cardinality explosion this will cause.
