### ISSUE TITLE
forward i/o timeout 

### ISSUE THREAD

**Issue by qscf** [coredns/coredns#3584]
dns server ip:192.168.11.53
Corefile
```
. {
  bind 0.0.0.0
  forward . 8.8.8.8
  log
  errors
}
```

set dns server (192.168.11.53)
when nslookup taobao.com
the errors :
```
[ERROR] plugin/errors: 2 taobao.com. AAAA: read udp 192.168.11.53:59460->8.8.8.8:53: i/o timeout
```

**but ping is good,**
**the nslookup timeout**

when nslookup taobao.com 8.8.8.8
get the right result:
```
 Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   taobao.com
Address: 140.205.220.96
Name:   taobao.com
Address: 140.205.94.189
```
env：
* vbox centos8
* go1.13.5  
* CoreDNS-1.6.6

I do not know the problem is centos8? or forwad setting?

**Comment by zouyee** [comment]
Sorry, I could not reproduce above issue.
![截屏2020-01-08下午5 40 37](https://user-images.githubusercontent.com/5785605/71967265-061ac400-323e-11ea-9011-1352f31f8030.png)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] forward i/o t..." ]
>Sorry, I could not reproduce above issue.
>![截屏2020-01-08下午5 40 37](https://user-images.githubusercontent.com/5785605/71967265-061ac400-323e-11ea-9011-1352f31f8030.png)

thanks for picking this up.

for future reference, could you also include verbatim paste of things your tried? These
screenhots down render in my email client *and* I can't cut and paste from them (if I need
to)..

Thanks!

**Comment by zouyee** [comment]
**updated: system info**

```
OS system: CentOS Linux release 7.6.1810 (Core)
kernel： 4.14.78-300.el7
arch: x86_64
```

**Dns config**
```
. {
  bind 10.142.21.132 # internal ip
  forward . 8.8.8.8
  log
  errors
}
```
**nslookup result**

```
[root@paasn1 ~]# nslookup taobao.com 10.142.21.132
Server:		10.142.21.132
Address:	10.142.21.132#53

Non-authoritative answer:
Name:	taobao.com
Address: 140.205.220.96
Name:	taobao.com
Address: 140.205.94.189

[root@paasn1 ~]# dig @10.142.21.132 taobao.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> @10.142.21.132 taobao.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10354
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;taobao.com.			IN	A

;; ANSWER SECTION:
taobao.com.		299	IN	A	140.205.220.96
taobao.com.		299	IN	A	140.205.94.189

;; Query time: 272 msec
;; SERVER: 10.142.21.132#53(10.142.21.132)
;; WHEN: 四 1月 09 09:04:25 CST 2020
;; MSG SIZE  rcvd: 91
```

updated **coredns log**
```
[root@kargo ~]# ./coredns
.:53 on 10.142.21.132
CoreDNS-1.6.6
linux/amd64, go1.13.5, d6669de
[INFO] 10.142.114.189:48391 - 8735 "A IN taobao.com. udp 28 false 512" NOERROR qr,rd,ra 80 0.220960927s
[INFO] 10.142.114.189:34496 - 13494 "AAAA IN taobao.com. udp 28 false 512" NOERROR qr,rd,ra 113 0.293183886s
[INFO] 10.142.114.189:58091 - 10354 "A IN taobao.com. udp 39 false 4096" NOERROR qr,rd,ra 91 0.271966126s
```

**Comment by qscf** [comment]
> **Dns config**
> 
> ```
> . {
>   bind 10.142.21.132 # internal ip
>   forward . 8.8.8.8
>   log
>   errors
> }
> ```
> 
> **nslookup result**
> 
> ```
> [root@paasn1 ~]# nslookup taobao.com 10.142.21.132
> Server:		10.142.21.132
> Address:	10.142.21.132#53
> 
> Non-authoritative answer:
> Name:	taobao.com
> Address: 140.205.220.96
> Name:	taobao.com
> Address: 140.205.94.189
> 
> [root@paasn1 ~]# dig @10.142.21.132 taobao.com
> 
> ; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> @10.142.21.132 taobao.com
> ; (1 server found)
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10354
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;taobao.com.			IN	A
> 
> ;; ANSWER SECTION:
> taobao.com.		299	IN	A	140.205.220.96
> taobao.com.		299	IN	A	140.205.94.189
> 
> ;; Query time: 272 msec
> ;; SERVER: 10.142.21.132#53(10.142.21.132)
> ;; WHEN: 四 1月 09 09:04:25 CST 2020
> ;; MSG SIZE  rcvd: 91
> ```
> 
> **coredns log**
> 
> ```
> [root@kargo ~]# ./coredns
> .:53 on 10.142.21.132
> CoreDNS-1.6.6
> linux/amd64, go1.13.4, 908508a-dirty
> [INFO] 10.142.114.189:48391 - 8735 "A IN taobao.com. udp 28 false 512" NOERROR qr,rd,ra 80 0.220960927s
> [INFO] 10.142.114.189:34496 - 13494 "AAAA IN taobao.com. udp 28 false 512" NOERROR qr,rd,ra 113 0.293183886s
> [INFO] 10.142.114.189:58091 - 10354 "A IN taobao.com. udp 39 false 4096" NOERROR qr,rd,ra 91 0.271966126s
> ```

hi，your system？

**Comment by qscf** [comment]
Sorry, I find the problem, the network gateway change from 192.168.11.254 to 192.168.11.1, because I have not change, so nslookup timeout, but ping is good.
