### ISSUE TITLE
Is forward's tls_servername a must?

### ISSUE THREAD

**Issue by snakwu** [coredns/coredns#3585]
If it is more than one tls upstream, how to configure it？

**Comment by snakwu** [comment]
. {                                                                               
    loadbalance round_robin                                                            
    forward . tls://1.1.1.1 tls://8.8.8.8 tls://9.9.9.9 {                              
        health_check 5s                                                                
    }

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Is forward's ..." ]
>. {
>    loadbalance round_robin
>    forward . tls://1.1.1.1 tls://8.8.8.8 tls://9.9.9.9 {
>        health_check 5s
>    }

 from: https://coredns.io/plugins/forward/

Bugs

The TLS config is global for the whole forwarding proxy if you need a different tls_servername for different upstreams you’re out of luck.

/close
/plugin forward

**Comment by snakwu** [comment]
我这样配置有没有问题？
我没有定义tls_servername

**Comment by snakwu** [comment]
我不理解的是，这个tls_servername是必须定义吗，不加这个参数会有什么样的结果？
