### ISSUE TITLE
CoreDNS 1.6.7 Release Tracking

### ISSUE THREAD

**Issue by ydcool** [coredns/coredns#3593]
This issue is to keep track of 1.6.7 release. Specifically we want to add the releasing support for mips64le arch https://github.com/coredns/coredns/pull/3589.

**Comment by ydcool** [comment]
Help wanted: when I run step 2 `make -f Makefile.doc`, the output shows all files in the `man/` folder is up to date while `git diff` shows nothing changed, so does the `go generate`, then what should I do?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS 1.6.7..." ]
>Help wanted: when I run step 2 `make -f Makefile.doc`, the output shows all files in the `man/` folder is up to date while `git diff` shows nothing changed, then what should I do?

See #3595, you'll need to rebase you version change PR on latest master after this is
merged.

**Comment by miekg** [comment]
I'm doing many other things atm - but will kick off a release later today/this week.

**Comment by ydcool** [comment]
Got it! thank you so much, and no hurry ; )

**Comment by ydcool** [comment]
Thank you! 
/close
