### ISSUE TITLE
kubernetes plugin upstrem config 

### ISSUE THREAD

**Issue by zhaofengcumt** [coredns/coredns#3598]
my coredns version is 1.4
and here is my config
```
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```
can anybody tell me the difference between upstream and proxy

**Comment by miekg** [comment]
Upstream tells coredns to use forward to resolve external names.
That option is default on nowadays.

**Comment by zhaofengcumt** [comment]
if k8s plugin can not get a record,then it will use the address configed in upstream. is that right?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] kubernetes pl..." ]
>if k8s plugin can not get a record,then it will use the address configed in upstream. is that right?

yes, but for records retreived from the API server.

this is different from just resolving random names via CoreDNS which just use the *forward*
plugin.

**Comment by zhaofengcumt** [comment]
it still confuses me.  when a request go into k8s plugin ,if it can not find a appropriate record,then it will use the proxy plugin, what if I config it like this where upstream has a given address, in this condition does the proxy plugin work?
```
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
            pods insecure
            upstream 10.96.0.3:53
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

**Comment by chrisohaver** [comment]
> it still confuses me. when a request go into k8s plugin ,if it can not find a appropriate record,then it will use the proxy plugin


Thats not really how it works.  Upstream is only used for resolving CNAME targets to hosts that are not in the kubernetes zone (in your config, `cluster.local.`).  For example, if you have an [ExternalName Service](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) named `extsvc.default.svc.cluster.local.` that points to `www.example.com.`, then kubernetes plugin would reply with a CNAME for `extsvc.default.svc.cluster.local.` and an A record for `www.example.com.` looking up the IP for `www.example.com.` by feeding the name back into the server.  In the default k8s Corefile, that means it gets routed to the proxy plugin.

> what if I config it like this where upstream has a given address, in this condition does the proxy plugin work?

It depends on the version of CoreDNS.  I think in 1.4, the presence of the upstream option and it's parameters is ignored. Eventually (perhaps with the 1.7 release), the presence of the upstream option will be invalid, but for now, it's just ignored (IOW, it's in the process of being deprecated and removed).
