### ISSUE TITLE
How to solve the problem "CoreDNS Pod CrashLoopBackOff"?

### ISSUE THREAD

**Issue by lwx294821** [coredns/coredns#3599]
I have installed a k8s cluster on a physical machine. Bute the log of coredns pod show "Readiness probe failed: Get http://10.233.65.11:8181/ready: dial tcp 10.233.65.11:8181: connect: connection refused".who can help me?

**Comment by zouyee** [comment]
Please provide information according to the problem template.
BTW, Could you execute the following command and paste the results?
`kubectl describe po -n kube-system <coredns-pod-id>`
`kubectl logs --tail 100  -n kube-system <coredns-pod-id>`
