### ISSUE TITLE
[Warning] messages are printed while log is configured for `error`

### ISSUE THREAD

**Issue by zanetworker** [coredns/coredns#3600]
**What happened**:
I keep seeing warning messages although logs is configured for `error` only. Here is an example: 

```
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
```

**What you expected to happen**:
No warning messages should be shown if the log plugin is in `error` mode. 

**Environment**:

- the version of CoreDNS: coredns:1.6.3
- Corefile: `".:8053 { \n    errors\n    log . {\n        class error\n    }\n    health\n
    \   ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n        pods
    insecure\n        upstream\n        fallthrough in-addr.arpa ip6.arpa\n        ttl
    30\n    }\n    prometheus 0.0.0.0:9153\n    forward . /etc/resolv.conf\n    cache
    30\n    loop\n    reload\n    loadbalance round_robin\n    import custom/*.override\n}\nimport
    custom/*.server"`
- Others: kubernetes version 1.16, 1.15, 1.14

**Comment by chrisohaver** [comment]
The _log_ plugin only turns on logging of DNS requests/responses.  It doesn't globally control all logging behavior. So, by specifying `error`,  that means to add logs for dns requests that resulted in error.

The warnings you see appear to be from use of an _import_ in the Corefile.  _import_ is attempting to load in extra configurations from `custom/*.override` etc, and no files match. Hence the warning.

This is, AFAIK, the Azure AKS style of deploying CoreDNS, and is expected.  IIUC, in Azure AKS you are not permitted to change the base Corefile, but you _can_ add configs in `custom` to customize CoreDNS behavior.

**Comment by zanetworker** [comment]
@chrisohaver In general I don’t want to see warning messages, I have control over the configmap but I don’t want to edit it, I am not using AKS in that case. what’s the recommended way to go to completely suppress these messages?

**Comment by chrisohaver** [comment]
Best way would be to remove the imports from the Corefile.  i.e. remove the lines...

```
import custom/*.override
import custom/*.server
```
from your Corefile.

**Comment by zanetworker** [comment]
I still want the imports, we are using them as well ( similar to AKS style) problem is, these logs are confusing. Is there a way to globally disable warnings?

**Comment by chrisohaver** [comment]
> Is there a way to globally disable warnings?

Not that I am aware of.  The warnings will go away once the imports have something to import ... i.e. when there are actually files present matching the pattern, you will no longer see those warnings.  You could try putting empty files in those locations to silence the errors, but I don't know if an empty file may in itself generate another warning.

**Comment by chrisohaver** [comment]
I tested real quick - and found that importing an empty file causes CoreDNS not to start.
However importing a file that has a single comment in it works ok and produces no warning.

e.g. `custom/empty.server` containing ...
```
# empty
```

**Comment by johnbelamaric** [comment]
The short of it though is that there is no way to disable logging
completely; the log plugin is for managing the query log, not the CoreDNS
log in general.

**Comment by zanetworker** [comment]
@chrisohaver thanks for looking into it :)  I will try it out as well, it would have been nice though If I could globally disable logging as well.

@johnbelamaric I guess that would have to work on the binary level, right?

**Comment by johnbelamaric** [comment]
Yeah, that would mostly work. We have a logger that is common across
everything, so we should be able to tweak log levels with it. The specific
messages you have, though, I believe are coming out of the Caddy libraries
and those are probably just spitting to STDERR or STDOUT and not using our
logger.

**Comment by zanetworker** [comment]
I see, thanks for the clarification.

**Comment by kamikaze** [comment]
very annoying message spam in loki/grafana

**Comment by zc-devs** [comment]
Combining https://github.com/k3s-io/k3s/issues/7639#issuecomment-1592172869 and https://github.com/coredns/coredns/issues/3600#issuecomment-575239919 I got
```yaml
# Deploy this manually via kubectl apply -f and restart the Pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.override: |
    #
  stub.server: |
    #
```
CoreDNS-1.10.1, K3s 1.29

**Comment by karlkovaciny** [comment]
> I tested real quick - and found that importing an empty file causes CoreDNS not to start. However importing a file that has a single comment in it works ok and produces no warning.

How did you actually create this `/etc/coredns/custom/empty.server` file given that the CoreDNS pod doesn't have bash, sh, or tar so you can't use kubectl cp?

**Comment by soakes** [comment]
> Combining [k3s-io/k3s#7639 (comment)](https://github.com/k3s-io/k3s/issues/7639#issuecomment-1592172869) and [#3600 (comment)](https://github.com/coredns/coredns/issues/3600#issuecomment-575239919) I got
> 
> ```yaml
> # Deploy this manually via kubectl apply -f and restart the Pod
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: coredns-custom
>   namespace: kube-system
> data:
>   log.override: |
>     #
>   stub.server: |
>     #
> ```
> 
> CoreDNS-1.10.1, K3s 1.29

Thank you @zc-devs for providing the solution , this issue is still present using K3S `v1.28.10+k3s1` which uses `CoreDNS-1.10.1`

I have written the following instructions for those who doesn't quite understand whats needed to be done.  

Running the following resolves the issue:

```
kubectl apply -f - <<'EOF'
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.override: |
    #
  stub.server: |
    #
EOF

kubectl rollout restart deploy/coredns -n kube-system
```

**Before**
```
 ❯ k -n kube-system logs pod/coredns-5f4f679fbd-d4gsj
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
.:53
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[INFO] plugin/reload: Running configuration SHA512 = b941b080e5322f6519009bb49349462c7ddb6317425b0f6a83e5451175b720703949e3f3b454a24e77f3ffe57fd5e9c6130e528a5a1dd00d9000e4afd6c1108d
CoreDNS-1.10.1
linux/amd64, go1.20, 055b2c3
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
```

**After**
```
 ❯ k logs pod/coredns-8466d7cd9c-tkjfb -n kube-system
[INFO] plugin/ready: Still waiting on: "kubernetes"
.:53
[INFO] plugin/reload: Running configuration SHA512 = b941b080e5322f6519009bb49349462c7ddb6317425b0f6a83e5451175b720703949e3f3b454a24e77f3ffe57fd5e9c6130e528a5a1dd00d9000e4afd6c1108d
CoreDNS-1.10.1
linux/amd64, go1.20, 055b2c3
```

**Comment by hek2mgl** [comment]
What was the original rationale for logging the warning message?

I mean, many UNIX daemons incorporate something like a conf.d directory in their configuration, yet I haven't encountered a warning from any of these daemons when their conf.d directory is empty.
