### ISSUE TITLE
plugin/file: does not seem to support fallthrough

### ISSUE THREAD

**Issue by littleplus** [coredns/coredns#3601]
I have a test.com domain, resolve domain name with file plugin.

Now I set up three dns servers for three different places, and prefer to resolve domain on the local dns server, if not found, find it in other two servers. Is there any way to implement it?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/file: does..." ]
>I have a test.com domain, resolve domain name with file plugin.
>
>Now I set up three dns servers for three different places, and prefer to resolve domain on the local dns server, if not found, find it in other two servers. Is there any way to implement it?

no, not with the file plugin. If-not-found-and-then-check-another-server is also very
strange to do in the DNS


/label question
/plugin file

**Comment by stp-ip** [comment]
One use case that in my mind to support this was defaulting to a specific template with file overwriting specific zones.
Tried a stab here, but never got the fall-through to work perfectly #2977 (should try again)

**Comment by littleplus** [comment]
Thank you for your help, I will try #2977 , may be I should consider the structure again.

**Comment by chrisohaver** [comment]
There's an external plugin that may help you here. https://github.com/coredns/alternate
With it, you can forward to a local instance that uses the file plugin. If the result is NXDOMAIN, then you can forward to an alternate server, which could be another local instance or upstream DNS server.

**Comment by littleplus** [comment]
@chrisohaver Seems to get around some of the problems, but it may have a bit long latency for waiting the first server?
