### ISSUE TITLE
Local lookups fail if forwarder not available

### ISSUE THREAD

**Issue by Sc0th** [coredns/coredns#3615]
**What happened**:

If forwarder is not available, local resolutions also fails, if all is well using 

`dig google.com @namserverip` -  expected response provided
`dig myhost1.mydomain.com @nameserverip` - expected internal resolution provided

However if I block 8.8.8.8 port 53 on the firewall making it inaccessible

`dig google.com @namserverip` - server unreachable, as I would expect
`dig myhost1.mydomain.com @nameserverip` - server unreachable, this is unexpected as I would hope that internal resolution would function as normal.

Not sure if this is a feature, bug, or PEBKAC

config looks like this

```
(shared) {
  log
  errors
  reload 30s
  cache
}

.:53 {
  forward . 8.8.8.8
  import shared
}

mydomain.com:53 {
  file /root/mydomain.com.db
  import shared
}

```
**What you expected to happen**:

Internal resolution to continue if external forwarder becomes unavailable.

**How to reproduce it (as minimally and precisely as possible)**:

As above.

**Anything else we need to know?**:

**Environment**:

CentOS7, running as pod inside k8s - not for k8s resolution.

- the version of CoreDNS:1.6.6
- Corefile: As above
- logs, if applicable: Can be provided
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Others:

**Comment by chrisohaver** [comment]
That isn't expected.   But I tested to make sure and confirmed that I don't see this issue.  I tested master, not 1.6.6 - but I don't think that should make a difference.

For a moment I thought this could be related to ClusterFirst search domains (which turns queries like `example.com` into `example.com.default.svc.cluster.local` ) - but then I noticed you are using `dig` to test, which doesn't use search domains  by default.

(Edit: to make sure, can you test the queries with a trailing dot?  e.g. `dig myhost1.mydomain.com. @nameserverip`)

**Comment by johnbelamaric** [comment]
If `dig myhost1.mydomain.com @nameserverip` returns a CNAME to a records outside of `mydomain.com` then this could happen.

**Comment by Sc0th** [comment]
Thanks gents, I just went back to reproduce and gather more logs and I can no longer replicate, I am not sure what on earth I was doing wrong here; all now appears well, apologies for wasting your time!
