### ISSUE TITLE
plugin/health: perform udp query to self?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3617]
Currently the health endpoint just opens a port and wait for GETs. The intention is that if coredns crashes there is obviously no endpoint to check. But I've seen cases where the health port is accessible (for TCP) but coredns itself isn't (UDP). This protocol difference means that coredns is unhealth from a cluster standpoint, but the control plan can't see this.

Now kuberetes can't do UDP health checks, nor should it. So maybe we should change this into the following:
* get GET probe
* health fires off UDP probe to ITSELF
* reports success/failure

The key thing here is ITSELF. We can't use localhost, because that's skips the crazy k8s networking, so we need to kind of (public) endpoint? How do we discover what would be a good one to probe?
Also with multiple servers, should we check them all?
What would be a good probe query? `. NS +norec`? as used by forwarding health checks? How about grpc/tls servers? We may lack TLS certs?

**Comment by miekg** [comment]
Note that health plugin already connects to itself but epoll metric numbers, but this is to localhost and http only thereby circumventing all the questions above.

**Comment by johnbelamaric** [comment]
So, if we can't answer all those questions, they can become part of the config. My take on your questions:

> The key thing here is ITSELF. We can't use localhost, because that's skips the crazy k8s networking, so we need to kind of (public) endpoint? How do we discover what would be a good one to probe?

Configurable, so we don't have to discover it. Whether that's an IP or a name is debatable, but certainly should be able to set an IP. If one is not set, then we utilize our `bind` configuration. This is a problem though, because we can have more than one. And there is just one health for the process. So I guess we check them ALL. If we don't have a `bind` configuration, then I guess `localhost`?

> Also with multiple servers, should we check them all?

Oh, I first read this as multiple processes and I thought you were smoking something. If there are multiple servers in the same process, then yeah, I think all of them. Except...we need to make sure it's a request that ANY of our servers can answer REGARDLESS of the state of any upstream or dependent policy services. We don't want to fiddle with health based on those. Which is your next question....

> What would be a good probe query? . NS +norec? as used by forwarding health checks?

Um. Probably? Presumably we have those compiled in? Or we can create some magic CH-based thing but we don't always enable CH.

> How about grpc/tls servers? We may lack TLS certs?

Has to be in the config if you want to check these endpoints.

**Comment by yongtang** [comment]
I added a candidate project for Summer of Code in #3658. It is not exactly the same healthcheck we discussed here, as the SoC project has a focus of:
1. External health check from a remote pods in Kubernetes clusters
2. Actively restart the coredns node through Kubernetes API (server).

The Summer of Code deliverable is expected to be a standalone program that is outside of the coredns binary.

The health check we discussed here, is expected to be a local UDP/DNS heath check that is supposed to be a coredns (external) plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/health..." ]
>I added a candidate project for Summer of Code in #3658. It is not exactly the same healthcheck we discussed here, as the SoC project has a focus of:
>1. External health check from a remote pods in Kubernetes clusters
>2. Actively restart the coredns node through Kubernetes API (server).
>
>The Summer of Code deliverable is expected to be a standalone program that is outside of the coredns binary.
>
>The health check we discussed here, is expected to be a local UDP/DNS heath check that is supposed to be a coredns (external) plugin.

Ack, maybe that would work better. I.e we could also open an udp port and check that (from
within CoreDNS) the problem is detecting what external IP this would have...

**Comment by yongtang** [comment]
We might be able to do some guessing at runtime?

For example, we could traverse through the network interfaces in golang and find the first non-local IP. We might also just track the DNS query coredns received and use the destination IP of the DNS packets.

The above method might not be ideal and might not be definitive though.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/health..." ]
>We might be able to do some guessing at runtime?
>
>For example, we could traverse through the network interfaces in golang and find the first non-local IP. We might also just track the DNS query coredns received and use the destination IP of the DNS packets.
>
>The above method might not be ideal and might not be definitive though.

with docker and network namespaces this might never work reliable... :-( Also if this
fails, should we then fail starting up?

**Comment by yongtang** [comment]
> with docker and network namespaces this might never work reliable... :-( Also if this
fails, should we then fail starting up?

Yes this is a big issue. Another thing is the "cluster ip" in k8s which apparently translated into interface's IPs through iptables.  Might not be visible inside so information can not be obtained by the process itself. Honestly I never liked the way iptable played in container/k8s networking: re-inventing the wheel in an unnecessary and unreliable way... But, this is already there and it is likely to stay.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/health..." ]
>Yes this is a big issue. Another thing is the "cluster ip" in k8s which apparently translated into interface's IPs through iptables.  Might not be visible inside so information can not be obtained by the process itself. Honestly I never liked the way iptable played in container/k8s networking: re-inventing the wheel in an unnecessary and unreliable way... But, this is already there and it is likely to stay.

on that topic IPVS is a thing and supported by k8s - but yeah, we're not going to solve
the generic issue here, so I'm not sure what to do, other than maybe we can't fix this and
we should stop caring

**Comment by wjayesh** [comment]
I have thought of two approaches that might help with this issue. 

1. How about adding a UDP port on the container alongside the dns and metrics port? It can be exposed through a different service than the already existing KubeDNS service, using a static IP. The httpGet health check can then be disabled. 

2. This approach skips the udp health check and takes a different route that might serve the cause. To check health, we can add an "exec" probe that runs a command inside the container and if it succeeds returns good health. To achieve this, we can add an ENTRYPOINT in our container image that creates a dummy file and to check health we just run a command to open this file.

Please let me know your thoughts on these and how I could contribute to it.
Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/health..." ]
>I have thought of two approaches that might help with this issue.
>
>1. How about adding a UDP port on the container alongside the dns and metrics port? It can be exposed through a different service than the already existing KubeDNS service, using a non static IP. The httpGet health check can then be disabled.
>
>2. This approach skips the udp health check and takes a different route that might serve the cause. To check health, we can add an "exec" probe that runs a command inside the container and if it succeeds returns good health. To achieve this, we can add an ENTRYPOINT in our container image that creates a dummy file and to check health we just run a command to open this file.
>

To make explicit; doing this from inside coredns is now not attempted anymore?

And responding to this comment: I don't like adding more binaries to the office CoreDNS
docker image.

**Comment by wjayesh** [comment]
>To make explicit; doing this from inside coredns is now not attempted anymore?

Yes, as @yongtang [mentioned ](https://github.com/coredns/coredns/issues/3617#issuecomment-582704317)in the requirements "External health check from a remote pods in Kubernetes clusters" , this check can be performed through any external environment. 

If I'm not wrong, the current health check relies on Kubernetes' livenessProbe http function. 

```
livenessProbe:
       httpGet:
          path: /health
          port: 8080
          scheme: HTTP
```
My suggestion is we include a UDP port for health check which is exposed through a different service (`NodePort` maybe) than the already existing KubeDNS service which is of type `ClusterIP` (and therefore not available outside the cluster). 
```
ports:
     - containerPort: xxxx
       name: health
       protocol: UDP
     - .......
       ...

**Comment by yongtang** [comment]
@WJayesh Some clarification here. The Summer-of-Code project in #3658 is a project exclusively dedicated to have CoreDNS health check working in a Kubernetes environment. As such project in #3658 solely focus on external health check and how to interact with Kubernetes.

However, CoreDNS as a standalone project is used in many places, not just for Kubernetes. For example, you can deploy CoreDNS in a standalone EC2 instance on AWS and use Autoscaling group to probe the "health endpoint" to scaling/terminate/relaunch EC2 instances for CoreDNS.

In those situations NodePort/KubeCtl/etc are irrelevant.

For that reason, it is desirable to have a health check that does not depending on any external environment.

Therefore, a healthcheck that performs self-check (as was described in this current issue) is needed. They are related to SoC project in #3658 but does not necessarily overlap.

Unlike external healthcheck with k8s, self-check in this issue have one issue of "which IP to talk to". As was mentioned localhost `127.0.0.1` could not truly test the scenario where networking complex is in play. That is the ongoing discussion here.

**Comment by yongtang** [comment]
For standalone health-check (non-external), I think the following might be helpful to identify a non-local IPs:
1) If Corefile listens `non-0.0.0.0 IP` (or multiple `non-0.0.0.0 IP`) then we could send DNS/UDP to this IP (or list of IPs).
2) If Corefile listens on `0.0.0.0`, and the local interface consists of a `non-localhost/127.0.0.1` IP, we could send DNS/UDP to this IP.
3) If Corefile listens on `0.0.0.0` and only 127.0.0.1 is available, then we could send DNS/UDP to this IP.
4) The standalone health-check plugin also could take an optional IP to check.

Overall, a standalone health-check could be best-effort. Hard to capture all possible scenarios.

**Comment by wjayesh** [comment]
> @WJayesh Some clarification here. The Summer-of-Code project in #3658 is a project exclusively dedicated to have CoreDNS health check working in a Kubernetes environment. As such project in #3658 solely focus on external health check and how to interact with Kubernetes.

Thank you for the detailed clarification. I had clearly missed the big picture. I understand the problem now 👍

**Comment by zouyee** [comment]
According to the description of the issue, I think what is needed is the telemetry reporter, not just the health checker.

**Comment by miekg** [comment]
think this has been concluded.
