### ISSUE TITLE
plugin/forward: put conns back in the cache on Temporary() errror

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3619]
Right now when the forward plugin encounters (any) error the connection will be removed from the pool. It may be an idea to check if the error is temporary and if so put the conn in the cache. I.e. if we get a network blib we drop all conns, and then we need to redo a TLS again esp when we get a bunch of incoming queries.

Maybe related to #3521

**Comment by rdrozhdzh** [comment]
Not sure if that is safe. 
For example, if we get timeout in previous requests (which is probably temporary error) and if we put connection back to the cache, then on next request we will send a new query and could read response for previous query.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>Not sure if that is safe.
>For example, if we get timeout in previous requests (which is probably temporary error) and if we put connection back to the cache, then on next request we will send a new query and could read response for previous query.

the request is discarded if that happens...

**Comment by chrisohaver** [comment]
>> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>> Not sure if that is safe. For example, if we get timeout in previous requests (which is probably temporary error) and if we put connection back to the cache, then on next request we will send a new query and could read response for previous query.

> the request is discarded if that happens...

If it discards a mismatched response, would it keep listening for a response with the correct id, or would it fail.
