### ISSUE TITLE
CoreDNS send traffic in local pod as first choice

### ISSUE THREAD

**Issue by resworld** [coredns/coredns#3628]
I think it will be great if it's possible to send traffic in local pod as first choice (heaviest). Not sure if it's possible to do so.

It is needed because we faced following problem:

When one of the EKS node is terminated from the cluster, but DNS resolver is sending requests to all coreDNS pods, and if one of the coreDNS is located in this node - it will timeout the DNS resolver request. 
We tried to run coreDNS as Daemonset, with idea all of the DNS requests to be send in local pod only (or first choice), but ClusterIP service sends traffic to each pods (no matter if it's local or no).
It will be great if local pod is with high priority of DNS request traffic.

**Comment by stp-ip** [comment]
Take a look at the cluster add on nodelocaldns: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns

That should do what you want with added benefits such as local cache and no CONNtrack table issues.

Also this is more of a kubernetes networking request and not really something on the CoreDNS side itself.

**Comment by johnbelamaric** [comment]
Also https://github.com/kubernetes/enhancements/issues/536
