### ISSUE TITLE
plugin/forward: max concurrent queries

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#3635]
**What would you like to be added**:

An option to set the maximum number of concurrent upstream queries allowed by the _forward_ plugin. If the number of concurrent queries to the upstreams is exceeded, then further queries to the upstreams would be dropped/rejected until the number of concurrent queries falls below the maximum.  This would be an optional setting, defaulting to disabled (no limit).

**Why is this needed**:

Without a maximum number of concurrent connections, a slow upstream connection can cause the number of concurrent connections to grow unbound and exhaust memory. The goal of this option is to lessen the impact of upstream query spikes, but in a way that does not also block other queries to low latency plugins (e.g. served by cache, file, etc).  By imposing the limit in the forward plugin, we don't prevent other plugins from answering while the forwarding limit is reached.

**Comment by miekg** [comment]
this sounds like a good thing to add, think bind9 sets to a 1000 or so, don't really see
an alternative to a manual knob - maybe we think of something better in due time

--
Miek Gieben

**Comment by miekg** [comment]
closed via #3640
