### ISSUE TITLE
Resyncperiod 0 causes the autopath/kubernetes plugin to fail.

### ISSUE THREAD

**Issue by chaudyg** [coredns/coredns#3649]
**What happened**:
Upgrading to coredns 1.6 seems to break the autopath plugin when CoreDNS gets disconnected from the ApiServer.

The resyncperiod flag has been set to 0 in https://github.com/coredns/coredns/issues/2911 . When coredns pods get out-of-sync with the apiserver, autopath breaks for pods newly started, but works for old pods. 

The following two queries are performed at the same time.

The first query is performed from a pod started a while ago. Autopath works.
```
$ host -v  infrabin.infrabin.svc.cluster.local
Trying "infrabin.infrabin.svc.cluster.local.infrabin.svc.cluster.local"
Using domain server:
Name: 172.16.23.62
Address: 172.16.23.62#53
Aliases:

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28404
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;infrabin.infrabin.svc.cluster.local.infrabin.svc.cluster.local.	IN A

;; ANSWER SECTION:
infrabin.infrabin.svc.cluster.local.infrabin.svc.cluster.local.	2 IN CNAME infrabin.infrabin.svc.cluster.local.
infrabin.infrabin.svc.cluster.local. 2 IN A	10.254.170.89

Received 242 bytes from 172.16.23.62#53 in 0 ms
Trying "infrabin.infrabin.svc.cluster.local"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64700
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;infrabin.infrabin.svc.cluster.local. IN	AAAA

;; AUTHORITY SECTION:
cluster.local.		2	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1580738314 7200 1800 86400 30

Received 146 bytes from 172.16.23.62#53 in 0 ms
Trying "infrabin.infrabin.svc.cluster.local"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29503
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;infrabin.infrabin.svc.cluster.local. IN	MX

;; AUTHORITY SECTION:
cluster.local.		2	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1580738314 7200 1800 86400 30

Received 146 bytes from 172.16.23.62#53 in 0 ms
```

When performing the same DNS query from a newly created pod, autopath does not work.
```
$ host -v  infrabin.infrabin.svc.cluster.local
Trying "infrabin.infrabin.svc.cluster.local.infrabin.svc.cluster.local"
Trying "infrabin.infrabin.svc.cluster.local.svc.cluster.local"
Trying "infrabin.infrabin.svc.cluster.local.cluster.local"
Trying "infrabin.infrabin.svc.cluster.local.eu-west-1.compute.internal"
Trying "infrabin.infrabin.svc.cluster.local"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7859
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;infrabin.infrabin.svc.cluster.local. IN	A

;; ANSWER SECTION:
infrabin.infrabin.svc.cluster.local. 30	IN A	10.254.170.89

Received 104 bytes from 10.254.0.10#53 in 0 ms
Trying "infrabin.infrabin.svc.cluster.local"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27224
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;infrabin.infrabin.svc.cluster.local. IN	AAAA

;; AUTHORITY SECTION:
cluster.local.		30	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1580738112 7200 1800 86400 30

Received 146 bytes from 10.254.0.10#53 in 0 ms
Trying "infrabin.infrabin.svc.cluster.local"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34103
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;infrabin.infrabin.svc.cluster.local. IN	MX

;; AUTHORITY SECTION:
cluster.local.		22	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1580738111 7200 1800 86400 30

Received 146 bytes from 10.254.0.10#53 in 0 ms
```

The following graphs shows the requests from CoreDNS to the API server. The LIST verbs goes flat.
![image](https://user-images.githubusercontent.com/7817963/73660181-960e2b00-468f-11ea-80e0-81aa0bfc2fce.png)

The CoreDNS cache does not get updated with the new Pod IPs. And the AutoPath plugins fail here https://github.com/coredns/coredns/blob/master/plugin/kubernetes/autopath.go#L33

**What you expected to happen**:

The autopath plugin should keep on working, even if CoreDNS gets out-of-sync with the Api server.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure how to force CoreDNS to get out-of-sync with the ApiServer

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.6.7
- Corefile: 
```
 .:53 {
        errors
        health {
            lameduck 10s
        }
        ready
        autopath @kubernetes
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods verified
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus 0.0.0.0:9153
        forward . /etc/resolv.conf
        cache 300 {
            prefetch 10
        }
        loop
        reload
        loadbalance
    }
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Others:

**Comment by chrisohaver** [comment]
> **What you expected to happen:** The autopath plugin should keep on working, even if CoreDNS gets out-of-sync with the Api server.

Due to how autopath works, this is impossible.  To correctly infer the search domains, autopath must know what namespace a request is coming from (i.e. the namespace of the client Pod).  To know this, it has to use the k8s API to look up the client Pod via the client's IP address in the DNS request.

The issue here is that CoreDNS has become out of sync with the API.  So the expectation should be that CoreDNS does not go out of sync with the API, or otherwise detects the bad state and auto-corrects in some way (#3590).

The symptom of CoreDNS no longer receiving updates from the API is very close to #3587.

It's unclear to me if this is truly related to the "resyncperiod" option in the K8s API. See https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/PbSCXdLDno0 for a discussion on what the feature actually does (it does not actually "resync" Pod/Services Lists periodically, as one might infer from the name).

**Comment by chrisohaver** [comment]
What version of Kubernetes are you using?

**Comment by chaudyg** [comment]
> So the expectation should be that CoreDNS does not go out of sync with the API, or otherwise detects the bad state and auto-corrects in some way

Much better! Thanks, indeed my expectation were un-realistic.

> What version of Kubernetes are you using?
v1.14.9

**Comment by chrisohaver** [comment]
@chaudyg, were there any errors or unusual messages in the in the logs of the CoreDNS Pod that failed?

**Comment by chaudyg** [comment]
Yes. Errors from resolving dns with kubernetes search path like:
`2019-01-30T15:32:49.027Z [ERROR] plugin/errors: foo.bar.svc.cluster.local.foo.bar.cluster.local. A: plugin/kubernetes: no next plugin found`

**Comment by chrisohaver** [comment]
> 2019-01-30T15:32:49.027Z [ERROR] plugin/errors: foo.bar.svc.cluster.local.foo.bar.cluster.local. A: plugin/kubernetes: no next plugin found

Thats ... bewildering. I don't think this has anything to do with the issue at hand... but is that an actual error message verbatim from logs, or is it doctored/scrubbed?

**Comment by chaudyg** [comment]
Very much doctored :0 . I do not have any `foo` services nor `bar` namespaces. Also I've done it on my phone so Idid mess up one section (sorry). That's better:

```
I2019-01-30T15:32:49.027Z [ERROR] plugin/errors: 2 foo.bar.svc.cluster.local.bar.svc.cluster.local. A: plugin/kubernetes: no next plugin found
```
Now, I am pretty sure the error messages are a consequence and not the cause (this was a while ago, I don't have the graph anymore). We tend to see this when coreDNS get saturated from DNS queries. At the time of the incident, we were handling 120k dns queries per second (new pods were making 5 time more DNS queries than expected).

From reading the thread you shared, I see your point resync != relist.
> https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/PbSCXdLDno0

 However, there is also a comment saying

> Think of the resync as insurance.  You probably want it set more than a few minutes, less than a few hours.  If you're using requeuing correctly and avoiding panics, you aren't likely to benefit from rescanning all the data very often.

Why are we opting out of the 'insurance policy'?

**Comment by chrisohaver** [comment]
I'm diving into the k8s api client-go code to try to get a better understanding of what the option does, and to see if it changing the value could potentially resolve the issue of where we permanently stop receiving events from the API watch.

I don't think you've mentioned yet: How long does it take for the condition to manifest?

**Comment by chrisohaver** [comment]
So, diving into the client-go code it looks like the resync is purely internal to the client.
It does not cause any interaction with the Kubernetes API.

The flow of data from API change event to DNS record is... 

1. the client-go watch receives an event from API
2. the event is pushed to a queue of change events
3. a processor pops items off the queue, and adds them to the indexed store.  The indexed store is what coredns uses to look up objects (e.g. Services) and build DNS records.

The resync occurs between steps 3 and 2.  During a resync, all items from the store are pushed back into to the event queue to get reprocessed in step 3.

If for some unknown reason client-go is not receiving new objects from the API, then a resync wont help.

The resync action seems pointless if all the processor is doing is updating the index store, but if it is performing other actions then a resync could be useful.  In CoreDNS, the processor also updates the SOA serial.  But the SOA serial failing to update would not cause the symptoms described in this issue, and I don't think it's worth re-introducing resync to protect against SOA updates.

**Comment by chrisohaver** [comment]
I can reproduce this issue when the K8s API is under stress resulting in high latency in the object informers, but also has a chance to occur under nominal load (the lag of notifications from the API server is never zero).  See #3765, I suspect these are the same root cause.

**Comment by miekg** [comment]
/label duplicate

See #3765
