### ISSUE TITLE
Add new plugin fanout for CoreDNS

### ISSUE THREAD

**Issue by denis-tingaikin** [coredns/coredns#3653]
Hello CoreDNS!
Currently, at the project [NSM](https://github.com/networkservicemesh/networkservicemesh) we have a [container](https://github.com/networkservicemesh/networkservicemesh/blob/master/build/Dockerfile.nsm-coredns) based on image CoreDNS. 
The difference from the original CoreDNS is a set of plugins. It has additional plugin [fanout](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/cmd/nsm-coredns/main.go#L28).
We want to try to move this plugin into your repository or somehow integrate it into CoreDNS.

## Overview

A CoreDNS fanout plugin will need to be crafted such that:
For each zone configured the fanout plugin can take a list of DNS Server IPs
For each incoming DNS query that hits the CoreDNS fanout plugin, it will be replicated in parallel to each listed IP.
**The first non-negative response from any of the queried DNS Servers will be forwarded as a response to the request.**

## Usecase

This plugin can be useful for goals like 'getting a client a **positive** answer as fast as possible'

For example, we have a list of IPs of proxy DNS servers.
Only the last server of the list is working.

**Expected:** DNS response from the last server will be provided right away.
**Actual:**  DNS response from the last server will be provided after checking all proxies in the list(if using Forward plugin)

Also, I've added a test for this scenario:
Fanout variant: https://github.com/coredns/coredns/pull/3652/files#diff-093df3afe4540b23f73e43ad825f941aR37
The result of a case with (3 bad servers and 1 working server) for my machine is 100 ms.

Forward variant: https://github.com/coredns/coredns/pull/3652/files#diff-093df3afe4540b23f73e43ad825f941aR48
The result of a case with (3 bad servers and 1 working server) for my machine is 4s.

NOTE: if all servers are fine then fanout plugin and the forward plugin works at the same time. (But fanout plugin doesn't guarantee  the order in this case)

## Request/Response diagram

![Fanout Plugin_ Request_Response diagram (2)](https://user-images.githubusercontent.com/49399980/73971204-0ac3bc80-4951-11ea-8169-b42b67f2f76d.png)

## Potential fanout integration options

- [X] Make `fanout` as an internal plugin for CoreDNS.
- [ ] Make `fanout` as an external plugin for CoreDNS.
- [ ] Convert `fanout` plugin into an additional policy for `forward` plugin.
- [ ] Your option.

## Links to docs

1. Abstract diagram of fanout and forward plugins: https://drive.google.com/file/d/1-Ge_YQKUOE5ZQ1Z5SxjV4mO8zfePNBk4/view?usp=sharing
2. Spec: DNS integration for NSM: https://docs.google.com/document/d/1_1ICFEh2M3_Q8MvAQXNngP9UNQLgYgPgr58KYzib4C0/edit#

## Link to PR

1. https://github.com/coredns/coredns/pull/3652 -- PR provides option 1.

## Current status

- [X] Select integration option. _make `fanout` an internal plugin for CoreDNS._
- [X] Provide WIP PR https://github.com/coredns/coredns/pull/3652
- [X] Finish PR  https://github.com/coredns/coredns/pull/3652
- [ ] Pass review

**Comment by stp-ip** [comment]
I feel the general use case might be related to #2998

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add new plugi..." ]
>I feel the general use case might be related to #2998

that seems a more valid approach.

This can be useful for debugging, and probably exist as an external plugin.

**Comment by denis-tingaikin** [comment]
@stp-ip , @miekg  I see next options here:

1) Make `fanout` as an internal plugin for CoreDNS.
2) Make `fanout` as an external plugin for CoreDNS.
3) Convert `fanout` plugin into an additional policy for `forward` plugin.
4) Your option.

The options 2 and 3 look good to me. 
Please share your thoughts.

**Comment by denis-tingaikin** [comment]
@grobie,  @johnbelamaric, @miekg, @rdrozhdzh

I see alternative integration for fanout plugin.
This is small refactoring the `Forward` plugin to add support for parallel queries.

Is it make sense? Can you approve this refactoring?

**Comment by denis-tingaikin** [comment]
@grobie, @johnbelamaric, @miekg, @rdrozhdzh

Forward plugin refactoring to add fanout option:
TODO:
1. Add policy `fanout`
2. Most changes need to do [here](https://github.com/coredns/coredns/blob/master/plugin/forward/forward.go#L72) to add parallelism (if a policy is fanout).
3. Add tests to cover fanout branch
4. Pass CI
5. Pass review


 I can create an Issue for that with more details and also provide demo PR if you approve the idea.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add new plugi..." ]
> @grobie,  @johnbelamaric, @miekg, @rdrozhdzh
>
>I see alternative integration for fanout plugin.
>This is small refactoring the `Forward` plugin to add support for parallel queries.
>
>Is it make sense for you? Can you approve this refactoring?

no, forward is complex enough as it is.

As said this could be a handy debugging feature

**Comment by denis-tingaikin** [comment]
@miekg ok got it. 
Can `fanout` plugin be provided into the main coredns repo or `fanout` should be an external plugin?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add new plugi..." ]
>@miekg ok got it.
>Can `fanout` plugin be provided into the main coredns repo or `fanout` should be an external plugin?

I actually wouldn't mind if this would be a internal plugin - the dependencies are
probably no too big and it can be useful to people and it doesn't something that isn't
really possible right now (with the current set of plugins)

**Comment by denis-tingaikin** [comment]
> I actually wouldn't mind if this would be a internal plugin 

@miekg cool! I'll update my PR. 
I'll let you know when it will ready to review!
Thanks!

**Comment by denis-tingajkin** [comment]
@miekg please take a look https://github.com/coredns/coredns/pull/3652

**Comment by denis-tingaikin** [comment]
@miekg  I've updated the section for `usecase` of this plugin please take a look.
And I also got the next questions:
1. Can you please describe a use case of debugging with `fanaout` plugin? 
2. We plan to use this plugin in production (take a look at `usecase` section). And for this goal, we need some similar functionality of forward plugin (For example health check). Can I refactor forward plugin and move reused functionality into ` /plugin/pkg` to avoid code duplication on the fanout plugin side?
