### ISSUE TITLE
add pseudo-random policy for improving privacy 

### ISSUE THREAD

**Issue by monperrus** [coredns/coredns#3656]
The random policy in coredns is great.

One problem with pure randomization is that  "over time (days, weeks) any resolver you use [...]] will likely acquire enough information about an end user to profile", which is a problem for privacy ([source](https://github.com/getdnsapi/stubby/issues/95#issuecomment-379708650))

One solution for that is a pseudo-random choice: "the choice of the server is consistent: if the same domain is resolved twice, the same upstream server for both queries is used". This is implemented for instance in [nss-tls](https://github.com/dimkr/nss-tls).

What about supporting this new policy in coredns?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] add pseudo-random..." ]
>The random policy in coredns is great.
>
>One problem with pure randomization is that  "over time (days, weeks) any resolver you use [...]] will likely acquire enough information about an end user to profile", which is a problem for privacy ([source](https://github.com/getdnsapi/stubby/issues/95#issuecomment-379708650))
>
>One solution for that is a pseudo-random choice: "the choice of the server is consistent: if the same domain is resolved twice, the same upstream server for both queries is used". This is implemented for instance in [nss-tls](https://github.com/dimkr/nss-tls).
>
>What about supporting this new policy in coredns?

keeping track of all domains and their target indefinitely will lead to an OOM at some
point. Also can't be easily abused by sending bogus queries.

**Comment by chrisohaver** [comment]
Could hash/mod the domain name to determine which upstream to use instead of tracking independently in memory.  Would need to decide how to handle unhealthy upstreams.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add pseudo-ra..." ]
>Could hash/mod the domain name to determine which upstream to use instead of tracking independently in memory.  Would need to decide how to handle unhealthy upstreams.

ooh yeah, that would work. Yep the second issue you highlight was also something I was
thinking about (fallback to random?)



/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
Yes, I think a fallback to random is simple and practical.

**Comment by yongtang** [comment]
In case of unhealthy upstream, I think we could hash again (with definitive args added), so:
1) Hash (IP) and check upstream X.
2) If X is healthy then go with X.
3) If X is unhealthy then hash (IP+ X?) again to get upstream Y.

At the end the order of the upstream we select is maintained X, Y, Z. At any point if there is a healthy one, then we stop.

**Comment by yongtang** [comment]
Update, should be Hash(domain + last selection):

Essentially we could generate a pseudo-random sequence (definite order) with:
```
upstream_selection = 0
while (upstream_selection is not healthy):
    upstream_selection = hash_function(domain_name + upstream_selection)

use upstream_selection
```

**Comment by chrisohaver** [comment]
Yeah - collision rehash works too.  The way I think forward policies work is that the policy always generates the full ordered list (regardless of health status), and then we step thru the list to find the first unhealthy one.

**Comment by chrisohaver** [comment]
... which means we need to be mindful of not listing the same upstream twice. Each subsequent rehash picking from a pool of 1 less upstream than before.

**Comment by yongtang** [comment]
Or the hash function could generate ordered upstream stream list in pseudo-random fashion (every upstream only appears once in the list.) And then the selection is a for loop iterate through the generated list.

**Comment by chrisohaver** [comment]
Yeah, we could create a hash for each upstream+domain f(domain+upstream), then return a list of upstreams sorted on their corresponding hash value.

**Comment by stp-ip** [comment]
Wouldn't hash(IP) have the same privacy issues. Shouldn't it be hash(zone)?
With hash(IP) the same user will always be upstreamed to the same "malicious" upstream.
With hash(zone) the issue would probably be a possible hot path to a single upstream.
We could go with hash(IP+ zone). That way we randomize the used upstream for each zone, but don't pick the same upstream for the same IP all the time.

But maybe my thinking is off.

**Comment by chrisohaver** [comment]
> But maybe my thinking is off.

No, thats what i was saying too ... domain = zone... `f(domain+upstream)` == `f(zone+upstream)`

**Comment by stp-ip** [comment]
Right. Missed your comment. That's what you get from not refreshing before you comment on a stale tab.

**Comment by monperrus** [comment]
Fully agree with the hashing strategy!

**Comment by miekg** [comment]
did we do anything here? Otherwise I'll just close this issue.

**Comment by monperrus** [comment]
Hi @miekg No I haven't seen any commit about this. Would still be highly valuable though. Thanks!
