### ISSUE TITLE
ENV variable expansion occurs too late in processing

### ISSUE THREAD

**Issue by bkcsfi** [coredns/coredns#3657]
**What would you like to be added**:

It appears that ENV variables are expanded after the Corefile has been tokenized, so it is not possible to put multiple tokens in a single ENV variable

It would be helpful to expand all `{$VAR}` before any tokenization

**Why is this needed**:

Consider this example

```
ad.mydomain.com {
    forward . {$WINDOWS_AD_SERVERS}
    cache
}
```

something like this works:

```
$ docker run -e WINDOWS_AD_SERVERS="1.2.3.4" coredns/coredns
```

This does not work

```
$ docker run -e WINDOWS_AD_SERVERS="1.2.3.4 1.2.3.5" coredns/coredns
plugin/forward: not an IP address or file: "1.2.3.4 1.2.3.5"
```

Another example. 

I have a very long list of domains to be served using `auto`  I also want to have secondary servers that will XFER only that list of domains from the master server. I have two corefile files, one for master and one for secondary.

I currently must maintain two copies of the same list of domains in each corefile because I cannot put the list of domains in a `snippet` nor in an ENV var.

comments based on coredns/coredns:1.6.7

**Comment by chrisohaver** [comment]
This is how the upstream caddy/caddyfile parse.go handles things.  It expands env vars at the token level. Any change of behavior there would need to be taken up in the caddy project.

As far as addressing it in coredns/coredns, I suppose we could expand env vars in the Corefile before sending to caddy.  Caddy requires a filename however, so we'd need to write the expanded version to a temp file.

Changing the default behavior would be backward incompatible, so it would probably need to be a non-default option, or an alternate env var syntax in the corefile to indicate they should be expanded pre-parsing.

**Comment by chrisohaver** [comment]
> As far as addressing it in coredns/coredns, I suppose we could expand env vars in the Corefile before sending to caddy.

That said, this is edging closer to just pre-processing the Corefile before CoreDNS gets it, via config mgmt tool of choice.

**Comment by stp-ip** [comment]
I agree with trying to take this up with Caddy. They are currently working on a breaking v2, which could make such a breaking change. So probably best to get that feedback to github.com/caddyserver/caddy

**Comment by chrisohaver** [comment]
If I read the code correctly, it looks like they already plan to do this... In the v2 branch, looks like env vars are replaced before tokenizing...

https://github.com/caddyserver/caddy/blob/v2/caddyconfig/caddyfile/parse.go#L82

**Comment by stp-ip** [comment]
I would say. Close as won't fix for now. Waiting for Caddy v2 support or preprocessing it would help.

Something like this should work:
`cat Corefile_template | envsubst > Corefile`
