### ISSUE TITLE
tcp connection  should  delay close connection or passive close

### ISSUE THREAD

**Issue by wu0407** [coredns/coredns#3659]
**What happened**:
tcpdump tcp traffic of coredns, find coredns send FIN package,  client send the query  in the meantime, coredns reponse RST package, client dns query failed. 
Any option to configure coredns delay  close connection like nginx lingering_close.  
Most connections are actively closed by the client.

**What you expected to happen**:

client query dns result success

**How to reproduce it (as minimally and precisely as possible)**:
unkown

**Anything else we need to know?**:
client-->lvs-->coredns

coredns dump
![coredns-dump](https://user-images.githubusercontent.com/7602218/73920998-7aaa5680-4901-11ea-80cb-bc5b0f4d96a3.png)

[coredns.pcap.gz](https://github.com/coredns/coredns/files/4164136/coredns.pcap.gz)

client dump
![client-dump](https://user-images.githubusercontent.com/7602218/73921031-89910900-4901-11ea-8cf8-9658daba8418.png)
[client.pcap.gz](https://github.com/coredns/coredns/files/4164086/client.pcap.gz)

**Environment**:

- the version of CoreDNS:  1.6.3
- Corefile: 
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health :8088
        ready
        kubernetes k8saliyunhzhcluster.local in-addr.arpa ip6.arpa {

           pods insecure
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n\n    kubernetes k8saliyunhzhcluster.local in-addr.arpa ip6.arpa {\n\n       pods insecure\n       upstream\n       fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    proxy . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2019-10-25T08:07:24Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "82445341"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 7a4bba5c-f6fe-11e9-a515-76fceb3d6a08
```

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Others:
docker 18.09.2
k8s 1.14.8

**Comment by miekg** [comment]
Any PR you had in mind?

**Comment by wu0407** [comment]
I don't know why coredns proactively closed connection.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] tcp connectio..." ]
>I don't know why coredns proactively closed connection.

I tries not to, hence test case or PR would be helpful

**Comment by UladzimirTrehubenka** [comment]
This is because https://github.com/miekg/dns/blob/master/server.go#L18
dns library has following restriction:
// Default maximum number of TCP queries before we close the socket.
const maxTCPQueries = 128
BTW library allows to set unlimited value (-1) but this behaviour cannot be configured with CoreDNS configuration.

**Comment by miekg** [comment]
clients should be able to deal with this.
