### ISSUE TITLE
Does coredns truncate TCP results? 

### ISSUE THREAD

**Issue by JarenGlover** [coredns/coredns#3660]
I am tying to understand if coredns truncate's the results of a TCP request? I an making a TCP query via Python's socket library and only getting back 3 results. However, I know the particular entry has about ~100 IP addresses. I can confirm this via a `dig +tcp +short` command. 

I tried looking at the [request](https://github.com/coredns/coredns/blob/master/request/request.go) and [forward](https://github.com/coredns/coredns/blob/master/plugin/forward/forward.go) code to better understand this but no success. 

Or maybe the cache is doing something special? 

```
Python 2.7.15+ (default`, Jul  9 2019, 16:51:35)
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> print socket.getaddrinfo('jaren.nginx.service.example', 80, 0, socket.SOCK_STREAM)
[(2, 1, 6, '', ('X.X.X.X', 80)), (2, 1, 6, '', ('Y.Y.Y.Y', 80)), (2, 1, 6, '', ('Z.Z.Z.Z', 80))]
```

**Comment by miekg** [comment]
truncating messages while done over TCP is not 100% specified in the RFC, but can be done regardless.

**Comment by JarenGlover** [comment]
@miekg  thanks.  does this mean coredns does truncate? if so, can you point me to the code where this is done? Maybe I overlooked it in request and forward code? - Thanks in advance
