### ISSUE TITLE
Tolerance on Clock Skew

### ISSUE THREAD

**Issue by tfchan0** [coredns/coredns#3661]
**What happened**:
It's not necessary an issue but more questions on how tolerance it is for CoreDNS to handle clock skew.  In several occasions, we observed the system clock goes backward (several minutes) due to messed up time server.  While CoreDNS Pods are running fine, but it fails to perform DNS lookup on headless services (Other K8s services are fine apparently).

After we restart the CoreDNS pod resolves the issue.

**What you expected to happen**:
Wonder if CoreDNS would sustain clock skew.

**How to reproduce it (as minimally and precisely as possible)**:
Manually change the system clock.

**Anything else we need to know?**:
We tried disabling the CoreDNS cache and it seems to be able to sustain clock skew.

**Environment**:

- the version of CoreDNS: 1.6.2
- Corefile:
- logs, if applicable:
No error log, by enabling debug logs, CoreDNS responses NXDOMAIN to the headless services DNS lookup.
- OS (e.g: `cat /etc/os-release`):
- Others: K8s: 1.16.2

**Comment by chrisohaver** [comment]
@tfchan0, There is nothing directly within CoreDNS's kubernetes plugin that would be affected by time skew.  Headless Services are handled no differently than ClusterIP services except that the former derives its answers from the Endpoints data, and the latter from the Services data.

Is this issue consistently reproducible?

**Comment by tfchan0** [comment]
H, @chrisohaver , sorry for late response.  Yes, it is fairly consistent to reproduce the issue.  We tried go back in times at around 15mins by modifying the system clock.  Thanks.

**Comment by chrisohaver** [comment]
> While CoreDNS Pods are running fine, but it fails to perform DNS lookup on headless services (Other K8s services are fine apparently).

Specifically, is _that_ detail consistent?  It's exceedingly strange that only Headless Services are affected and not other types ...

> We tried disabling the CoreDNS cache and it seems to be able to sustain clock skew.

Do you mean that without the cache plugin, CoreDNS does not exhibit the symptoms described with the system clock is changed?
