### ISSUE TITLE
CoreDNS return "No answer" when resolve domain zone address

### ISSUE THREAD

**Issue by rumanzo** [coredns/coredns#3670]
I have kubernetes cluster with CoreDNS and upstream DNS for example with a domain dev.domain
in upstream DNS I have A record kubernetes.dev.com

Some like this:
svc.kubernetes.dev.domain NS kubernetes.dev.domain
kubernetes.dev.domain A 10.0.0.2 ; vip address

And CoreDNS config:
```
.:53 {
        log
        errors
        health {
            lameduck 5s
        }
        ready
        loadbalance round_robin
        kubernetes cluster.local kubernetes.dev.domain  {
          kubeconfig /etc/kubernetes/kubeconfig kubelet-to-kubernetes
          fallthrough
        }
        forward . /etc/resolv.conf {
          max_fails 5
        }
        prometheus :9153
        cache 10 cluster.local  kubernetes.dev.domain
        loop
        reload
    }
```

And problem when I resolve domain from node with calico or from pod:
```
# dig @localhost somepod.somenamespace.svc.kubernetes.dev.domain
; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> @localhost somepod.somenamespace.svc.kubernetes.dev.domain
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 963
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;somepod.somenamespace.svc.kubernetes.dev.domain. IN A

;; ANSWER SECTION:
somepod.somenamespace.svc.kubernetes.dev.domain. 5 IN A 10.10.0.1
somepod.somenamespace.svc.kubernetes.dev.domain. 5 IN A 10.10.0.2
somepod.somenamespace.svc.kubernetes.dev.domain. 5 IN A 10.10.0.3

```
and query zone name

```
# dig @localhost kubernetes.dev.domain

; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> @localhost kubernetes.dev.domain
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17685
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kubernetes.dev.domain.       IN      A

;; AUTHORITY SECTION:
dev.domain. 5      IN      SOA     ns.dev.domain. sysadmin.dev.domain. 2020021100 900 600 2592000 900

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Feb 11 16:51:57 MSK 2020
;; MSG SIZE  rcvd: 175
```

If the CoreDNS at least return NXDOMAIN on this request, fallthrough should have worked, but CoreDNS return "No answer" and option ignore empty_service not work with zone name.

Only solution now use hosts {...} (it works as intended), but this is a bad design. Or am I doing something wrong, please tell me how to do it right.
 

- the version of CoreDNS: 1.6.4

**Comment by chrisohaver** [comment]
If what you want is a zone to be forwarded to a specific dns server (aka stub domain), use a separate serverblock for that zone. Adjusting your example, below will forward all requests in the `dev.domain.` zone to `10.0.0.2` ...

```
dev.domain:53 {
    forward . 10.0.0.2
    cache 10
}

.:53 {
        log
        errors
        health {
            lameduck 5s
        }
        ready
        loadbalance round_robin
        kubernetes cluster.local  {
          kubeconfig /etc/kubernetes/kubeconfig kubelet-to-kubernetes
        }
        forward . /etc/resolv.conf {
          max_fails 5
        }
        prometheus :9153
        cache 10
        loop
        reload
    }
```

**Comment by rumanzo** [comment]
> If what you want is a zone to be forwarded to a specific dns server (aka stub domain), use a separate serverblock for that zone. Adjusting your example, below will forward all requests in the `dev.domain.` zone to `10.0.0.2` ...
> 
> ```
> dev.domain:53 {
>     forward . 10.0.0.2
>     cache 10
> }
> 
> .:53 {
>         log
>         errors
>         health {
>             lameduck 5s
>         }
>         ready
>         loadbalance round_robin
>         kubernetes cluster.local  {
>           kubeconfig /etc/kubernetes/kubeconfig kubelet-to-kubernetes
>         }
>         forward . /etc/resolv.conf {
>           max_fails 5
>         }
>         prometheus :9153
>         cache 10
>         loop
>         reload
>     }
> ```

We want our pods to be resolvable through a company global dns server.
The point is that that kubernetes have two zones, cluster.local and dev.domain. But I can't resolve A record for domain dev.domain through CoreDNS. It doesn't seem strange to me that I want to get A record for the zone address.

**Comment by chrisohaver** [comment]
> We want our pods to be resolvable through a company global dns server.

Do you want clients that are outside of the cluster, to resolve names of Pods inside the cluster?

**Comment by rumanzo** [comment]
> > We want our pods to be resolvable through a company global dns server.
> 
> Do you want clients that are outside of the cluster, to resolve names of Pods inside the cluster?

Yes, it's possible.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS retur..." ]
>> > We want our pods to be resolvable through a company global dns server.
>>
>> Do you want clients that are outside of the cluster, to resolve names of Pods inside the cluster?
>
>Yes, it's possible.

How do you route traffic in that case?

**Comment by rumanzo** [comment]
> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS retur..." ]
> > > We want our pods to be resolvable through a company global dns server. > > Do you want clients that are outside of the cluster, to resolve names of Pods inside the cluster? Yes, it's possible.
> How do you route traffic in that case?

nginx or envoy outside the kubernetes cluster

**Comment by chrisohaver** [comment]
One solution that may or may not do what you want (not 100% clear on your set up and goals): 

Assuming your external clients have routes to cluster Pod IPs, you can use the _rewrite_ plugin, and forward the `dev.domain` zone to CoreDNS exposed by k8s.

In this setup, the CoreDNS Service would be exposed on an external IP or loadbalancer, the company dns would forward the `dev.domain` zone to that exposed IP, CoreDNS using the _rewrite_ plugin, would rewrite any requests in `dev.domain` to `cluster.local`. CoreDNS then servers the request as if it was `cluster.local`, and before sending the response to the client, rewrites the response back to `dev.domain`.

This would not work for cluster IP Services (can't route to them from outside cluster), but should work for headless Services and Endpoints (Pods that are attached to a Service). Pods are not directly addressable in k8s via dns in any meaningful way.  You can use the `endpoint_pod_names` option to use pod names in Endpoints record dns names instead of pod hostnames.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS retur..." ]
>> How do you route traffic in that case?
>
>nginx or envoy outside the kubernetes cluster

so all your pod IP's are routed to an L7 LB and from there they are routed (with iBGP?) to
your cluster?

Or do you have a 100% IPv6 setup that makes this possible?

**Comment by rumanzo** [comment]
> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS retur..." ]
> > How do you route traffic in that case? nginx or envoy outside the kubernetes cluster
> so all your pod IP's are routed to an L7 LB and from there they are routed (with iBGP?) to your cluster? 

Yes, it is

> Or do you have a 100% IPv6 setup that makes this possible?

We don't have ipv6


I think you want to bring me to the idea that we have a strange cluster topology and strange ideas. I understand it. But I’m writing just to draw attention that when we resolving the zone record answers is empty, although there are no difficulties to query the DNS servers described in /etc/resolv.conf and this is consistent with the configuration and logic.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS retur..." ]
>> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS retur..." ]
>> > How do you route traffic in that case? nginx or envoy outside the kubernetes cluster
>> so all your pod IP's are routed to an L7 LB and from there they are routed (with iBGP?) to your cluster?
>
>Yes, it is
>
>> Or do you have a 100% IPv6 setup that makes this possible?
>
>We don't have ipv6
>
>
>I think you want to bring me to the idea that we have a strange cluster topology and strange ideas. I understand it. But I’m writing just to draw attention that when we resolving the zone record answers is empty, although there are no difficulties to query the DNS servers described in /etc/resolv.conf and this is consistent with the configuration and logic.

Yes, I want to tease out what you're doing here, basically because I may want to do the
same at some point.

If you are really doing the above, I wonder how you prevent/noticing routing loops. And
also how keep tabs on the number of v4 addresses you're using, i.e. how are you assigning
POD IP - (I also understand if you can't or won't divulge that info)

**Comment by rumanzo** [comment]
> One solution that may or may not do what you want (not 100% clear on your set up and goals):
> 
> Assuming your external clients have routes to cluster Pod IPs, you can use the _rewrite_ plugin, and forward the `dev.domain` zone to CoreDNS exposed by k8s.
> 
> In this setup, the CoreDNS Service would be exposed on an external IP or loadbalancer, the company dns would forward the `dev.domain` zone to that exposed IP, CoreDNS using the _rewrite_ plugin, would rewrite any requests in `dev.domain` to `cluster.local`. CoreDNS then servers the request as if it was `cluster.local`, and before sending the response to the client, rewrites the response back to `dev.domain`.
> 
> This would not work for cluster IP Services (can't route to them from outside cluster), but should work for headless Services and Endpoints (Pods that are attached to a Service). Pods are not directly addressable in k8s via dns in any meaningful way. You can use the `endpoint_pod_names` option to use pod names in Endpoints record dns names instead of pod hostnames.

It's nice advice, i will try it. Thank you

**Comment by chrisohaver** [comment]
> If the CoreDNS at least return NXDOMAIN on this request, fallthrough should have worked, but CoreDNS return "No answer" and option ignore empty_service not work with zone name.

This is by design.  Answering NXDOMAIN response would break DNS rules, since the domain does exist.

The fallthrough option, by design only falls through for NXDOMAIN.  Fallthrough is not a standard DNS concept, but it is consistently/intentionally implemented this way in the few plugins that support it.

The `ignore empty_service` option also works as designed.  It's intended to treat services that have no Pods as if they did not exist.  The bare domain is not itself a service, so the option doesn't apply.

> It's nice advice, i will try it. Thank you

An example rewrite:

```
    rewrite stop {
        name regex (.*)\.kubernetes\.dev\.domain\.$ {1}.cluster.local.
        answer name (.*)\.cluster\.local\.$ {1}.kubernetes.dev.domain.
    }
```

would allow coredns to answer a query like `myheadless.default.svc.kubernetes.dev.domain.` as if it was actually a query for `myheadless.default.svc.cluster.local.`

**Comment by rumanzo** [comment]
> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS retur..." ]
> > [ Quoting ***@***.***> in "Re: [coredns/coredns] CoreDNS retur..." ] > > How do you route traffic in that case? nginx or envoy outside the kubernetes cluster > so all your pod IP's are routed to an L7 LB and from there they are routed (with iBGP?) to your cluster? Yes, it is > Or do you have a 100% IPv6 setup that makes this possible? We don't have ipv6 I think you want to bring me to the idea that we have a strange cluster topology and strange ideas. I understand it. But I’m writing just to draw attention that when we resolving the zone record answers is empty, although there are no difficulties to query the DNS servers described in /etc/resolv.conf and this is consistent with the configuration and logic.
> Yes, I want to tease out what you're doing here, basically because I may want to do the same at some point. If you are really doing the above, I wonder how you prevent/noticing routing loops. And also how keep tabs on the number of v4 addresses you're using, i.e. how are you assigning POD IP - (I also understand if you can't or won't divulge that info)

We have dedicated cidr for the kubernetes cluster, kubernetes use calico, each pod - 1 ip. It's quite easy to count. If you are intresting network part (bgp and other), this is done by colleagues (network engineers), I do not have complete information.

**Comment by rumanzo** [comment]
> > If the CoreDNS at least return NXDOMAIN on this request, fallthrough should have worked, but CoreDNS return "No answer" and option ignore empty_service not work with zone name.
> 
> This is by design. Answering NXDOMAIN response would break DNS rules, since the domain does exist.
> 
> The fallthrough option, by design only falls through for NXDOMAIN. Fallthrough is not a standard DNS concept, but it is consistently/intentionally implemented this way in the few plugins that support it.
> 
> The `ignore empty_service` option also works as designed. It's intended to treat services that have no Pods as if they did not exist. The bare domain is not itself a service, so the option doesn't apply.
> 
> > It's nice advice, i will try it. Thank you
> 
> An example rewrite:
> 
> ```
>     rewrite stop {
>         name regex (.*)\.kubernetes\.dev\.domain\.$ {1}.cluster.local.
>         answer name (.*)\.cluster\.local\.$ {1}.kubernetes.dev.domain.
>     }
> ```
> 
> would allow coredns to answer a query like `myheadless.default.svc.kubernetes.dev.domain.` as if it was actually a query for `myheadless.default.svc.cluster.local.`

It's solution work correct, thank you. And I do easier:
`
rewrite name suffix .kubernetes.dev.domain. .cluster.local.
`
It's work fine


UPD. I understand why you advice use regex. For rewriting answer section.
