### ISSUE TITLE
RPZ support (DNS sinkhole)

### ISSUE THREAD

**Issue by mrbluecoat** [coredns/coredns#3673]
**What would you like to be added**:

Support for [RPZ](https://en.wikipedia.org/wiki/Response_policy_zone) so CoreDNS can block ad domains on local network.  https://github.com/coredns/coredns/issues/1765#issuecomment-386302417 noted this wasn't available in 2018 but I'm hoping a performant solution can be implemented soon or with plugins?

**Why is this needed**:

Bind, Knot, and PowerDNS support it.  dnsmasq supports a [variant format](https://debian-administration.org/article/535/Blocking_ad_servers_with_dnsmasq).  Offering this would increase interest and use of CoreDNS and would be a valuable resource for network admins since so many public lists exist.

**Comment by mrbluecoat** [comment]
Ref: https://github.com/coredns/coredns/issues/3306

**Comment by mrbluecoat** [comment]
Looks like https://github.com/miekg/block is the closest option at the moment.  I'll try that.

**Comment by miekg** [comment]
if the *file* plugin would support `fallthrough` this doesn't need any implementation but could be done by transfering the rpz zones in and having them be queries first, before upstreaming the query

**Comment by stp-ip** [comment]
Having fallthrough in file and auto would also help with #2977

**Comment by mrbluecoat** [comment]
Another option: https://github.com/relekang/coredns-blocklist
