### ISSUE TITLE
separate latency metrics A/AAAA

### ISSUE THREAD

**Issue by szuecs** [coredns/coredns#3684]
**What would you like to be added**:

I would like to be able to separate metrics for A and AAAA records.

**Why is this needed**:
I investigate an issue, that requires understanding of response latencies per record type.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] separate latency ..." ]
>**What would you like to be added**:
>
>I would like to be able to separate metrics for A and AAAA records.
>
>**Why is this needed**:
>I investigate an issue, that requires understanding of response latencies per record type.

Tha's already done:


~~~ go
var monitorType = map[uint16]struct{}{
	dns.TypeAAAA:   {},
	dns.TypeA:      {},
	dns.TypeCNAME:  {},
	dns.TypeDNSKEY: {},
	dns.TypeDS:     {},
	dns.TypeMX:     {},
	dns.TypeNSEC3:  {},
	dns.TypeNSEC:   {},
	dns.TypeNS:     {},
	dns.TypePTR:    {},
	dns.TypeRRSIG:  {},
	dns.TypeSOA:    {},
	dns.TypeSRV:    {},
	dns.TypeTXT:    {},
	// Meta Qtypes
	dns.TypeIXFR: {},
	dns.TypeAXFR: {},
	dns.TypeANY:  {},
}

const other = "other"
~~~

All these types are exported in the metrics as a `type`

/Miek

--
Miek Gieben

**Comment by szuecs** [comment]
I only see the subset of metrics available: `coredns_dns_request_type_count_total` , not the latency buckets

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] separate late..." ]
>I only see the subset of metrics available: `coredns_dns_request_type_count_total` , not the latency buckets

ah, we probably don't extend it to the buckets.

That seems like a sensible idea.

**Comment by miekg** [comment]
this is not a terribly good idea in retrospect and I'm probably going to revert it
