### ISSUE TITLE
coredns doesn't start on a node which joined back a cluster after connectivity lost

### ISSUE THREAD

**Issue by laaubert** [coredns/coredns#3689]
**What happened**:
I have a 3 nodes cluster, one master and 2 workers.

Here is my scenario:

Initial state:  coredns PODs are deployed on Worker1 and Worker2. Everything is working as expected.

Worker1 lost connectivity (but stays UP and running) with the rest of the cluster so after few minutes, the master create a new coredns POD on Worker2. Again all expected and working.

Connectivity is restored so Worker1 can reconnect with the master. The master will evict all the PODs running on Worker1. Both coredns PODs still running on Worker2. All good.

Now I delete one coredns POD so the master will create a new one on Worker1. This new pod will never start and enters into a crash loop mode.

**What you expected to happen**:
New pod created on Worker1 should start successfully

**How to reproduce it (as minimally and precisely as possible)**:
Please see scenario described above

**Anything else we need to know?**:
I can ping the coredns pod successfully from other pods. I also move my application PODS to Worker1 and as far as I can tell they have no issue to start or to communicate.

I know the issue is between coredns and my CNI plugin (Contiv/VPP) because the only way I found to fix this issue is to reload the Contiv-vswitch pod running on Worker1.

I don't think there is something wrong with coredns itself but what I'm looking for is some help to identify the reason preventing coredns  from starting (is there a specific IP, port it can't reach ?) because I don't see anything in the logs either on coredns or contiv-vpp side

**Environment**:

- the version of CoreDNS:  1.3.1
- Corefile:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-21T07:59:44Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "26488"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: cf2a620d-be77-46d2-81fb-af370d16787f
```
- logs, if applicable:
```
[ansible@k8s-ansible-4 ~]$ kubectl logs coredns-55db8fd794-tbwbn -n kube-system
.:53
2020-02-21T11:58:58.731Z [INFO] CoreDNS-1.3.1
2020-02-21T11:58:58.731Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2020-02-21T11:58:58.731Z [INFO] plugin/reload: Running configuration MD5 = 721adee016c462adbe75d5025a15a26d
2020-02-21T11:58:58.732Z [ERROR] plugin/errors: 2 8959601638220274562.2441050965996509240. HINFO: plugin/loop: no next plugin found

[ansible@k8s-ansible-4 ~]$

Events:
  Type     Reason     Age                    From                    Message
  ----     ------     ----                   ----                    -------
  Warning  Unhealthy  9m28s (x220 over 84m)  kubelet, k8s-ansible-5  Readiness probe failed: Get http://10.14.1.243:8080/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    4m31s (x194 over 71m)  kubelet, k8s-ansible-5  Back-off restarting failed container
```
- OS (e.g: `cat /etc/os-release`): centos7
- Others: Kubernetes version: 1.15.3

**Comment by chrisohaver** [comment]
Looks like k8s is timing out trying to establish a health probe connection.  Likely a network issue (packets not reaching CoreDNS).  When this happens, k8s kills CoreDNS because it thinks it's unhealthy.

If, for example CoreDNS was unable to connect to the k8s API to load service records, You would see errors in the logs.  Not seeing those errors means that CoreDNS connected to the API successfully.

Try disabling the readiness/liveness probes, so CoreDNS doesn't get killed, and see if you can direct DNS queries to the Pod and get responses.

One side issue I see: Your Corefile is missing a `forward` plugin, hence the "loop: no next plugin" error in the log.  Without the forward plugin, CoreDNS will be unable to forward any requests upstream.  This in itself would not cause CoreDNS to fail to start or stop it from answering health probes.

**Comment by laaubert** [comment]
Thanks Chris for your quick reply. 

Your inputs helped to find the root cause which is the Contiv-VPP plugin not reprogramming correctly the link between the host and vpp thus preventing Kubelet from reaching the pods.
