### ISSUE TITLE
CoreDNS as dns server, when doing "nslookup domain" command, I Got ";; Got recursion not available from xx.xx.xx.xx, trying next server"

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#3690]
I use coredns as my dns server, It's IP is 10.0.0.96

Following are my relevent configurations:

My Corefile:
```
.:53 {
  errors
  health
  ready
  hosts  {
    10.0.0.121 harbor.test.abc
    10.0.0.153 chart.test.abc
    10.0.0.114 aaa.test.abc
    reload 1s
    fallthrough
  }
  prometheus :9153
  forward . /etc/resolv.conf
  cache 30
  loop
  reload
  loadbalance
  log
}
```

My Server /etc/hosts:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 dns-server
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.0.0.96 dns-server
```

My /etc/resolv.conf：
```bash
# Generated by NetworkManager
nameserver 127.0.0.1
nameserver 8.8.8.8
nameserver 8.8.4.4
````

when using "nsllokup aaa.test.abc", I got:
```
;; Got recursion not available from 10.0.0.96, trying next server
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find aaa.test.abc: NXDOMAIN
```

when using "dig" command:

```
$ dig aaa.test.abc

; <<>> DiG 9.10.6 <<>> aaa.test.abc
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47275
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;aaa.test.abc.		IN	A

;; ANSWER SECTION:
aaa.test.abc.	30	IN	A	10.0.0.114

;; Query time: 76 msec
;; SERVER: 10.0.0.96#53(10.0.0.96)
;; WHEN: Sat Feb 22 15:00:58 CST 2020
;; MSG SIZE  rcvd: 87
```

How to solve this probelem ";; Got recursion not available from xx.xx.xx.xx, trying next server"?

Tks

**Comment by dilyevsky** [comment]
Don't think `host` plugin supports recursive queries and that's what `nslookup` command appears to be sending.

**Comment by dilyevsky** [comment]
Yup (from `man nslookup`):

```
            [no]recurse
               Tell the name server to query other servers if it does not have the information.

               (Default = recurse; abbreviation = [no]rec)
```

**Comment by ghost** [comment]
> Don't think `host` plugin supports recursive queries and that's what `nslookup` command appears to be sending.

Thanks for your reply.

**Comment by Zhaoyu1123** [comment]
> > Don't think `host` plugin supports recursive queries and that's what `nslookup` command appears to be sending.
> 
> Thanks for your reply.

How to solve this probelem？

**Comment by chrisohaver** [comment]
Per my understanding the `nslookup` behavior doesn't make sense.  If it gets an authoritative `aa` result, then it doesn't matter if the server can recursively query (because it doesn't need to in that case: we already have an authoritative answer). IOW, `nslookup` should accept an `aa` answer regardless of the availability of recursion.

I think a workaround here is to make your client's `/etc/resolv.conf` contain only the coredns ip, and have coredns forward to those other dns servers.  IIRC, `nslookup` will accept the answer if there is only one server in `/etc/resolv.conf`.

**Comment by matthiasschoger** [comment]
Stumbled upon this page when I encountered the same issue.

Found the solution while standing under the shower, maybe someone else will find it helpful :)

There's a plugin for core-dns called "header", which allows to set arbitrary headers in the DNS request or response.
The solution is to add the following lines to a section:
 

> header {
>     response set ra # set RecursionAvailable flag
>  }
> 

This set's the RA flag to the response, which makes everyone happy.
Tested with the file and forward plugins, both reported "WARNING: recursion requested but not available" before, and are now happy with the reply from CoreDNS.

**Comment by chenwei67** [comment]
> 
That's what I do. It does works.

**Comment by chenwei67** [comment]
> Per my understanding the `nslookup` behavior doesn't make sense. If it gets an authoritative `aa` result, then it doesn't matter if the server can recursively query (because it doesn't need to in that case: we already have an authoritative answer). IOW, `nslookup` should accept an `aa` answer regardless of the availability of recursion.
> 
> I think a workaround here is to make your client's `/etc/resolv.conf` contain only the coredns ip, and have coredns forward to those other dns servers. IIRC, `nslookup` will accept the answer if there is only one server in `/etc/resolv.conf`.


That's what I do. It does works.

**Comment by wxmeng04** [comment]
> > Per my understanding the `nslookup` behavior doesn't make sense. If it gets an authoritative `aa` result, then it doesn't matter if the server can recursively query (because it doesn't need to in that case: we already have an authoritative answer). IOW, `nslookup` should accept an `aa` answer regardless of the availability of recursion.
> > I think a workaround here is to make your client's `/etc/resolv.conf` contain only the coredns ip, and have coredns forward to those other dns servers. IIRC, `nslookup` will accept the answer if there is only one server in `/etc/resolv.conf`.
> 
> That's what I do. It does works.

Surely it works but I have two coredns servers to ensure the availability. If you include only one core dns server in `/etc/resolv.conf`, you lose a standby.

**Comment by wxmeng04** [comment]
> Stumbled upon this page when I encountered the same issue.
> 
> Found the solution while standing under the shower, maybe someone else will find it helpful :)
> 
> There's a plugin for core-dns called "header", which allows to set arbitrary headers in the DNS request or response. The solution is to add the following lines to a section:
> 
> > header {
> > response set ra # set RecursionAvailable flag
> > }
> 
> This set's the RA flag to the response, which makes everyone happy. Tested with the file and forward plugins, both reported "WARNING: recursion requested but not available" before, and are now happy with the reply from CoreDNS.

This way works around. Thank you! It's a bit weird really. The reason is that coredns doesn't implement recursive resolution.
