### ISSUE TITLE
Reverse lookup must give preference to endpoints that has hostname field associated

### ISSUE THREAD

**Issue by swamibluedata** [coredns/coredns#3693]
**What would you like to be added**:
We have an application that creates multiple statefulsets as part of deployment. It also creates a single headless service for all the statefulsets and a normal service (NodePort) for each pod. 

The fqdn of the pod is 
```<pod-name>.<headless-service>.<namespace>.svc.cluster.local```

For each pod, there are two endpoint associations. Headless service endpoint and also the normal service endpoint. However the normal service endpoint doesn't have the hostname set.  In this mode the forward lookup of the above fqdn returns the correct pod ip. However reverse lookup  is kind of messed up. It toggles between the above fqdn or ```ip-10-244-5-2.<normal-service>.<namespace>.svc.cluster.local```

Applications running inside the pod depends on this reverse lookup to work consistently and it fails because of the above address.

We don't have this issue with kube-dns however. When handling duplicate endpoints, it looks like coredns must give preference to the endpoints that has hostname associated with it? Sure endpoint_pod_names must also be considered in this case.

**Why is this needed**:

**Comment by chrisohaver** [comment]
The reverse lookup toggles because it was only returning one result.  This should be fixed with #3687.

**Comment by swamibluedata** [comment]
Thanks guys. Confirming that the issue is resolved by using the latest version
