### ISSUE TITLE
Cache Prometheus Metrics descriptions need improvement

### ISSUE THREAD

**Issue by Starblade42** [coredns/coredns#3697]
**What would you like to be added**:
The prometheus metrics descriptions for the Cache plugin are very cryptic. Without knowing the internal logic implementation of CoreDNS it's hard to tell what the significance of the prometheus metrics is.

Specifically, what is `coredns_cache_drops_total`? What is a `drop` in this context? What kind of event is this counter supposed to keep track of? What is the significance of that counter incrementing to a service/consumer that is querying CoreDNS for name resolution?

**Why is this needed**:
When making use of Prometheus metrics to monitor and alert, a passing understanding of what is being indicated by a metric is necessary in order to write useful alerts.

In this case the `coredns_cache_drops_total` metric appeared to be incrementing when we saw what was a DNS resolution critical failure, but we're not sure if that was incidental or core to the issue. Right now we're planning on alerting on this since it's one of the few metrics surfaced by CoreDNS during the incident that was changing.

Please clarify what is being counted by `coredns_cache_drops_total` and what the significance of that is to a cluster operator or consumer of the coredns cache.

Thank you!

**Comment by chrisohaver** [comment]
Yeah, there is essentially no description.

I had to look at the code. This (coredns_cache_drops_total) is incremented when a response is not written to the cache for a specific case.  That specific case is when the question/response are mismatched.  DNS responses contain the query name and record type in them, and if that doesn't match the query name and record type of the client's request, then it's not written to cache.
