### ISSUE TITLE
CoreDNS service (kube-dns) unreachable from pods

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [coredns/coredns#3704]
**What happened**:
Pods are unable to use CoreDNS because it's service IP is unreachable. If we try to use an specific CoreDNS pod to query a domain, it works as expected.

**What you expected to happen**:
For the pods to be able to use the CoreDNS service as is.

**How to reproduce it (as minimally and precisely as possible)**:
Based on the [Kubernetes Debugging DNS Resolution](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/), the following command results in timeout:
```
$ kubectl exec dnsutils nslookup kubernetes.default

;; connection timed out; no servers could be reached

command terminated with exit code 1
```

If I use one specific CoreDNS pod from our cluster (10.96.224.26 in our case), it works as expected:

```
$ kubectl exec dnsutils nslookup kubernetes.default 10.96.224.26

Server:		10.96.224.26
Address:	10.96.224.26#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.96.0.1
```

**Anything else we need to know?**:

Our cluster was initialized with:

```
kubeadm init --pod-network-cidr=10.96.0.0/16
```

And our CNI is Weave.

Here are some other outputs to help understand our cluster:

```
$ kubectl get nodes

NAME             STATUS   ROLES    AGE   VERSION
fesc-lnx-dss10   Ready    master   14d   v1.17.3
fesc-lnx-dss11   Ready    <none>   14d   v1.17.3
fesc-lnx-dss12   Ready    <none>   14d   v1.17.3
fesc-lnx-dss13   Ready    <none>   14d   v1.17.3
```

```
$ kubectl exec dnsutils cat /etc/resolv.conf

nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local fesc.sgusuite.com.br
options ndots:5
```

```
$ kubectl get svc -n kube-system

NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   14d
```

```
$ kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o wide

NAME                      READY   STATUS    RESTARTS   AGE   IP             NODE             NOMINATED NODE   READINESS GATES
coredns-8c4578697-frxlj   1/1     Running   0          20h   10.96.224.26   fesc-lnx-dss11   <none>           <none>
coredns-8c4578697-p2mwn   1/1     Running   0          20h   10.96.96.26    fesc-lnx-dss12   <none>           <none>
coredns-8c4578697-pbq78   1/1     Running   0          20h   10.96.0.3      fesc-lnx-dss10   <none>           <none>
coredns-8c4578697-s8psk   1/1     Running   0          20h   10.96.128.26   fesc-lnx-dss13   <none>           <none>
```

Btw, If I run `nslookup` directly on the master node or any worker node using the CoreDNS service (10.96.0.10) it works just fine:

```
$ nslookup google.com 10.96.0.10

Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.29.14
Name:	google.com
Address: 2800:3f0:4001:80a::200e
```

The problem seems to be querying this from inside the pod only.

**Environment**:

- the version of CoreDNS: CoreDNS-1.6.5

- Corefile:
```
    .:53 {
        log
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

- OS: CentOS 7

**Comment by chrisohaver** [comment]
This is not a CoreDNS issue, rather a Kubernetes networking problem, where traffic to Cluster IPs is not correctly directed to Pods.  I expect that this affects all of your Cluster IP services, not just the CoreDNS service.

From the description, the issue could lie in kube-proxy.

Here's A troubleshooting guide ...
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by chrisohaver** [comment]
`kubeadm init --pod-network-cidr=10.96.0.0/16`

Your pod network and your service network overlap ... which I imagine will cause routing problems.

**Comment by rafaelrenanpacheco** [comment]
@chrisohaver thanks for the fast response!

Indeed they are overlapping, since service-cidr defaults to 10.96.0.0/12.

We will have to reset our cluster and init it with a proper service-cidr range.

Thanks!

**Comment by rafaelrenanpacheco** [comment]
@chrisohaver we reinstalled our cluster with
* `kubeadm init --pod-network-cidr=10.96.0.0/16 --service-cidr=10.97.0.0/16`

and CoreDNS is now working as expected :tada: 

Thanks again!

**Comment by andradedpg** [comment]
@rafaelrenanpacheco 
Im dealing with the same scenario, but currently I'm use Calico CNI.
So, I should be change my cluster initial that way:

`$ kubeadmin init --pod-network-cidr=192.168.0.0/16 --service-cidr=192.169.0.0/16`  

Could you know this is make sense?

Thanks in advance!

**Comment by rafaelrenanpacheco** [comment]
Hello @andradedpg!

> $ kubeadmin init --pod-network-cidr=192.168.0.0/16 --service-cidr=192.169.0.0/16

I would avoid that because `192.169.*.*` is not reserved for private network. These are the ranges for private networks:

```
192.168.0.0 - 192.168.255.255 (65,536 IP addresses)
172.16.0.0 - 172.31.255.255 (1,048,576 IP addresses)
10.0.0.0 - 10.255.255.255 (16,777,216 IP addresses)
```

If you do need to use the `192.168` range, then you may lock the 3rd group in half, like this:

```
Range: 192.168.0.0/17
HostMin: 192.168.0.1
HostMax: 192.168.127.254
Total: 32766

Range: 192.168.128.0/17
HostMin: 192.168.128.1
HostMax: 192.168.255.254
Total: 32766
```

Be aware that you will get a limitation of 32k virtual ips for services and 32k virtual ips for pods.

I made this calculation using this site: http://jodies.de/ipcalc?host=192.168.0.0&mask1=17&mask2=

**Comment by andradedpg** [comment]
> Hello @andradedpg!
> 
> > $ kubeadmin init --pod-network-cidr=192.168.0.0/16 --service-cidr=192.169.0.0/16
> 
> I would avoid that because `192.169.*.*` is not reserved for private network. These are the ranges for private networks:
> 
> ```
> 192.168.0.0 - 192.168.255.255 (65,536 IP addresses)
> 172.16.0.0 - 172.31.255.255 (1,048,576 IP addresses)
> 10.0.0.0 - 10.255.255.255 (16,777,216 IP addresses)
> ```
> 
> If you do need to use the `192.168` range, then you may lock the 3rd group in half, like this:
> 
> ```
> Range: 192.168.0.0/17
> HostMin: 192.168.0.1
> HostMax: 192.168.127.254
> Total: 32766
> 
> Range: 192.168.128.0/17
> HostMin: 192.168.128.1
> HostMax: 192.168.255.254
> Total: 32766
> ```
> 
> Be aware that you will get a limitation of 32k virtual ips for services and 32k virtual ips for pods.
> 
> I made this calculation using this site: http://jodies.de/ipcalc?host=192.168.0.0&mask1=17&mask2=

Great!

So, I assume that can able to do that:
  `$ kubeadmin init --pod-network-cidr=192.168.0.0/17 --service-cidr=192.168.128.0/17`
I will try. Thanks @rafaelrenanpacheco !

**Comment by sithukyaw007** [comment]
Hi all, I am having the similar issue using Calcico

I could not reach too (via curl) ngix via 10.96.0.1 inside control plane node. When I go inside individual node to curl using local IP address (192.168.xxx.xx), it works. How could I resolve this?

Here are the output pod and service

```
~$ kubectl get all -o wide
NAME                         READY   STATUS    RESTARTS   AGE   IP                NODE       NOMINATED NODE   READINESS GATES
pod/dnsutils                 1/1     Running   0          17m   192.168.131.18    c1-node2   <none>           <none>
pod/nginx-6799fc88d8-8w9nx   1/1     Running   0          21m   192.168.222.205   c1-node1   <none>           <none>
pod/nginx-6799fc88d8-hn5z8   1/1     Running   0          21m   192.168.131.16    c1-node2   <none>           <none>
pod/nginx-6799fc88d8-njk4h   1/1     Running   0          33m   192.168.131.15    c1-node2   <none>           <none>

NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE     SELECTOR
service/kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP   4d16h   <none>
service/nginx        ClusterIP   10.98.201.184   <none>        80/TCP    33m     app=nginx
```

**Comment by baokiemanh** [comment]
I got same issue. In my case, I setup cluster (kubeadm) on AWS EC2 instances. 

Solution: After I change Security Group (firewall) setting to allow all traffic then everything back to normal.

I never got this issue when setup cluster on bare metal.

The root cause should be firewall setting on cloud provider.

Hope it help!

**Comment by spgyip** [comment]
I got same issue on Vagrant VMs(centos8). 

But my service cidr and pod  network cidr are not overlapping. Service cidr: `10.96.0.0/12`, pod network cidr: `172.18.0.1/16`.

For example, `svc/kubernetes`'s cluster IP `10.96.0.1`.

Connect success on node:

```
[vagrant@master deployment] nc -w 1 -v 10.96.0.1 6443
Ncat: Connected to 10.96.0.1:6443
```

But fail on pod container:

```
[vagrant@master deployment] kubectl exec -it nginx -- sh
/ # nc -w 1 -v 10.96.0.1 6443
nc: 10.96.0.1 (10.96.0.1:6443): Operation timed out
```

**Comment by spgyip** [comment]
> I got same issue on Vagrant VMs(centos8).
> 
> But my service cidr and pod network cidr are not overlapping. Service cidr: `10.96.0.0/12`, pod network cidr: `172.18.0.1/16`.
> 
> For example, `svc/kubernetes`'s cluster IP `10.96.0.1`.
> 
> Connect success on node:
> 
> ```
> [vagrant@master deployment] nc -w 1 -v 10.96.0.1 6443
> Ncat: Connected to 10.96.0.1:6443
> ```
> 
> But fail on pod container:
> 
> ```
> [vagrant@master deployment] kubectl exec -it nginx -- sh
> / # nc -w 1 -v 10.96.0.1 6443
> nc: 10.96.0.1 (10.96.0.1:6443): Operation timed out
> ```

Well, my issue is not associated with service network, but the pod network with `flannel`. So, ignore this.

**Comment by MykolaBordakov** [comment]
> 
Good day.
Have the same situation.
Where you change configuration of AWS ?

**Comment by asher-lab** [comment]
Thank you for this. Overlapping CIDR block will really cause issue in the cluster and we learn it the hard way.

**Comment by cyb3rfist** [comment]
Traffic can be routed to the pods via a Kubernetes service, or it can be routed directly to the pods. When traffic is routed to the pods via a Kubernetes service, Kubernetes uses a built-in mechanism called kube-proxy to load balance traffic between the pods.

Having an outdated kube-proxy image version can cause the routing issues. In my case it was 1.23 running on k8s cluster 1.27. Upgrading the image fixed the issue for me.

**Comment by Davidrjx** [comment]
overlapping seems one case. in my situation, a test-purpose pod traffic can not reachable from veth peer calixx to tunl0 in IPVS kube-proxy

**Comment by achar007** [comment]
I encountered the same issue in my home lab with VirtualBox, and it was caused by a NAT port forwarding rule I had set up for the control plane VM.
