### ISSUE TITLE
How to build it on openwrt

### ISSUE THREAD

**Issue by XiaoliChan** [coredns/coredns#3722]
The question same as the title, i want to make coredns work on openwrt, how to do.

system: openwrt 19.07
cpu: mt7621

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] How to build it o..." ]
>The question same as the title, i want to make coredns work on openwrt, how to do.
>
>system: openwrt 19.07
>cpu: mt7621

I have no idea. You should check if go supports that arch, if so, coredns should work

**Comment by XiaoliChan** [comment]
> [ Quoting <notifications@github.com> in "[coredns/coredns] How to build it o..." ]
> The question same as the title, i want to make coredns work on openwrt, how to do. system: openwrt 19.07 cpu: mt7621
> I have no idea. You should check if go supports that arch, if so, coredns should work

By the way, my router cpu arch is mips, but i try to download 'coredns_1.6.7_linux_mips.tgz
' release, and i use upx to make it smaller (beacuse of the router storage), i did not work on my router

**Comment by yongtang** [comment]
@XiaoliChan Please be more specific on `did not work`, i.e., the exact steps you tried so that other people could try to reproduce.
