### ISSUE TITLE
remove fedaration from plugin.cfg

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3726]
We're carrying the (now external) *federation* plugin still in `plugin.cfg`; this should be removed in the 1.7.0 release

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] remove fedara..." ]
>/assign

note: there are also references in the kubernetes/README.md to federation that can be
removed I guess.

**Comment by zouyee** [comment]
Do we need to delete related methods that `federation` plugin depends on, such as 
https://github.com/coredns/coredns/blob/master/plugin/kubernetes/local.go#L39-L58

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] remove fedara..." ]
>Do we need to delete related methods that `federation` plugin depends on, such as
>https://github.com/coredns/coredns/blob/master/plugin/kubernetes/local.go#L39-L58

How 'dead' is federation?

My preference would be to remove everything related to federation with 1 commit.

**Comment by chrisohaver** [comment]
> How 'dead' is federation?

Federation v1 (to which this implementation applies) is perpetually stagnated in beta, but Federation v2 is not in beta yet.  IOW, Federation v1 is still the most developed/stable Kubernetes Federation solution (based purely on release versions alpha vs beta).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] remove fedara..." ]
>Federation v1 (to which this implementation applies) is perpetually stagnated
>in beta, but Federation v2 is not in beta yet. IOW, Federation v1 is still the
>most developed/stable Kubernetes Federation solution.


https://v1-16.docs.kubernetes.io/docs/concepts/cluster-administration/federation/

 Deprecated

  Use of Federation v1 is strongly discouraged. Federation V1 never achieved GA status and
  is no longer under active development. Documentation is for historical purposes only.

I don't know what federation v2 is or how it works, but I hope they don't make the same
DNS mistakes.

But it seems safe to say we can rip it all out for 1.7.0

/Miek

--
Miek Gieben
