### ISSUE TITLE
CoreDNS Release: 1.6.8

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3727]
let's do another release

**Comment by miekg** [comment]
Blocked by #3716
Waiting for Go 1.14.1 (or we could hack the release script to use Go 1.13 - but testing the release script is super annoying)

**Comment by miekg** [comment]
Add feature to the release script to compile with different Go version: https://github.com/coredns/release/pull/5
We don't have wait for #3716 anymore.

**Comment by jejer** [comment]
Do we have an ETA on this new release?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS Relea..." ]
>Do we have an ETA on this new release?

either we wait for go 1.14.1 (don't know it's ETA) or we release with go 1.13.8. Eiter way
I'm anxious to get something released, so that we can prepare for 1.7.0.

The cache prefetch fix needs to be merged as well, before we do a new release.

**Comment by stp-ip** [comment]
Informative sidenote:

The Kubernetes community will be switching the promotion process for images in k8s.gcr.io.
The final flip is scheduled in the coming weeks. I have access to do promotions and it comes down to pushing to a staging repo and opening a specific PR for adding versions + hashes (https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/images/k8s-staging-coredns/images.yaml).
Others are aware of the process as well such as @johnbelamaric @rajansandeep.

Didn't promote the last releases as the process wasn't live. Will promote all releases once this one goes out.

Images then are available under k8s.gcr.io/coredns/coredns:vX.X.X in addition to our own images on dockerhub. Also have an issue in my backlog to automate the staging image population with a build repo (kubernetes/k8s.io#533). Aka build CoreDNS from source, auto push to staging and then we (mostly I) only need to open the corresponding PR.

**Comment by miekg** [comment]
damn release script. This what I meant with hard to debug

**Comment by miekg** [comment]
yes, missing \ in the Makefile.release - something which is of course super hard to catch - let's see if I can delete a bunch

**Comment by miekg** [comment]
yes, so, already tagged. Don't want to undo that. So wil up to 1.6.9 and add a 2 character fix to Makefile.release  - will cut and paste 1.6.8 -> 1.6.9 through out, because why not.

objections?

**Comment by stp-ip** [comment]
+1

**Comment by miekg** [comment]
this is to say that the recent change (5adefab0) is actually correct. otherwise I'll revert that change and do it the old(er) way.
