### ISSUE TITLE
plugin/forward: config settings cleanups

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3730]
The forward plugin has some rather convoluted config setups. I.e. functions on Proxy that call other functions on the lower bits (Transport and Healthcheck). For some reason I can't remember `HealthCheck` as an interface; where in reality we only have one impl. here.

This all looks over-engineered and ready to be massively simplified - hopefully with a reduction in LOCs.

**Comment by miekg** [comment]
This might be a "good first issue", because its mostly Go code, not some weird DNS interaction.

**Comment by sandyleo26** [comment]
happy to take a stab at it. Could I have some pointer?

**Comment by denis-tingajkin** [comment]
In fanout plugin this problem is fixed :)

**Comment by denis-tingaikin** [comment]
@miekg 
It is a good idea and it could be also a good refactoring. I interested to do it to reduce code duplication in fanout plugin. You can assign it to me if you don't mind.

**Comment by ajitesh13** [comment]
Hello, @miekg as this is marked as a good-first-issue, can you provide me with some good starting points to work on?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/forwar..." ]
>Hello, @miekg as this is marked as a good-first-issue, can you provide me with
>some good starting points to work on?

I think we did this and then needed to revert because of issues. You should be able to dig
up the commit and figure out what went wrong. We did add a test that catches the
regression that was orinally introduced though.

/Miek

--
Miek Gieben
