### ISSUE TITLE
remove ignored options from kubernetes plugin 

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#3731]
**What would you like to be added**:

remove ignored options from kubernetes plugin:  `upstream`, `resyncperiod`

**Why is this needed**:

code pruning

**Comment by chrisohaver** [comment]
Closing... not really needed - and code pruned is minimal.

**Comment by chrisohaver** [comment]
change of heart... will be removed in 1.7.0 ...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] remove ignore..." ]
>change of heart... will be removed in 1.7.0 ...

/lgtm
