### ISSUE TITLE
plugin/forward: unit test 'TestProxyClose' expects nothing

### ISSUE THREAD

**Issue by denis-tingaikin** [coredns/coredns#3734]
## Problem
The test TestProxyClose doesn't expect anything
https://github.com/coredns/coredns/blob/2d98d520b5c75d31e37dfe72a67b39707a56dc69/plugin/forward/proxy_test.go#L16 
This test could always pass CI and not track some specific issues.

## Solution
Add expectations.

**Comment by miekg** [comment]
indeed, this can be removed.
