### ISSUE TITLE
plugin/cache: Add "delay" option?

### ISSUE THREAD

**Issue by leiless** [coredns/coredns#3745]
Some external plugins may opt to populate its data from the internet `OnStartup()`, for example, to download a domain/zone list.

Which it requires working DNS, and if we put the external plugin before `cache`, which the overall performance will be degraded, and if we put it after `cache` plugin, the cache will be reserved immediately, which some incoming DNS queries may use previously cached answers, which may not optimal for the user located at.

Since the selection between DNS upstream servers may affect the query result, thus if we can add a `delay` option in the `cache` plugin,  it's a `time.Duration`, so when all external plugins did its work(via `sync.WaitGroup`?), or deadline reached, `cache` starts to caching.

A real-life example plugin: https://github.com/c-mueller/ads
> while I would suggest having the `ads` plugin before the `cache` plugin because it will cause the changes in the blocklists to be applied instantly. However the overall performance of the DNS server could degrade when having many regex rules.

And I'm also developing a CoreDNS plugin recently, and I think it's necessary to delay `cache` so other plugins can populate its data from the internet, and finally yield an optimal result for ending users.

I have a working `cache` plugin with `delay` supported, I'm willing to implement it for official `cache` plugin if you don't mind.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/cache: Add..." ]
>I have a working `cache` plugin with `delay` supported, I'm willing to implement it for official `cache` plugin if you don't mind.

this is solving your problem at the wrong level.

Your plugin - if it needs DNS resolution - should try to resolve names in a loop, until it
receives some data. After that it can signal that's ready.

Your plugin also needs to re-resolve these names continuously to adhere to the TTL set on
them.

/Miek

--
Miek Gieben

**Comment by leiless** [comment]
> Your plugin - if it needs DNS resolution - should try to resolve names in a loop, until it
receives some data. After that it can signal that's ready.

Do you mean at plugin `OnStartup` stage?

> Your plugin also needs to re-resolve these names continuously to adhere to the TTL set on
them.

Also, do you mean after I resolved and downloaded some data in `OnStartup`, so I resolve the download URL again?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/cache:..." ]
>> Your plugin - if it needs DNS resolution - should try to resolve names in a loop, until it
>receives some data. After that it can signal that's ready.
>
>Do you mean at plugin `OnStartup` stage?

Probably later, but you can start a goroutine in OnStarup that resolves and re-resolves
the name.

>Also, do you mean after I resolved and downloaded some data in `OnStartup`, so I resolve the download URL again?

yes

**Comment by leiless** [comment]
Thanks for your advice @miekg, I'll close this issue.

**Comment by leiless** [comment]
Hi again, @miekg, currently I use a goroutine to resolve URLs and populate domain names in `OnStartup`.

Since fetching from URL also needs a working DNS upstream server(for example, `/etc/resolv.conf` use `127.0.0.1` nameserver, and CoreDNS bind at port `53`).

Is it wise to rewrite all outbound DNS answers TTLs to a minimal(say `dnsutil.MinimalDefaultTTL`) until the initial population from URLs finished(have a timeout)?

In contrast to you previously said:
> Your plugin also needs to re-resolve these names continuously to adhere to the TTL set on them.

I don't which one is better since the latter one requires you to maintain a set manually?
