### ISSUE TITLE
I used coredns 1.3 in k8s to modify the host resolve. Do I need to restart coredns? How to load dynamically

### ISSUE THREAD

**Issue by licaishui88** [coredns/coredns#3757]
**What happened**:
I used coredns 1.3 in k8s to modify the host resolve. Do I need to restart coredns? How to load dynamically

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
The _hosts_ plugin will reload the host file every 5 seconds (I don't think the interval is configurable as far back as 1.3, but is in more recent versions).

For in-line hosts definitions, use the _reload_ plugin.

**Comment by licaishui88** [comment]
I used reload ，but how can I ensure it have reloaded ，where can look up

发自我的 iPhone

**Comment by chrisohaver** [comment]
You could do a dns query to verify the changes are loaded.

**Comment by chrisohaver** [comment]
Actually - can you describe in more detail what you mean by "modify the host resolve" ...

I initially was thinking you meant you were making changes to hosts in the hosts plugin... but now i'm not sure what you are asking.  What are the contents of your Corefile, and what are you changing?

**Comment by licaishui88** [comment]
![图片](https://user-images.githubusercontent.com/8501446/77129152-e00b6e80-6a8d-11ea-9b93-eebaafb338a3.png)
![图片](https://user-images.githubusercontent.com/8501446/77129157-ed285d80-6a8d-11ea-9e96-585b35a02edb.png)
![图片](https://user-images.githubusercontent.com/8501446/77129191-03361e00-6a8e-11ea-88bf-d2a0a78d462b.png)
My k8s host computer now has an intranet DNS address configured in / etc / resolv.conf, which used to have an extra Internet DNS address. Now I find that the container Ping the internal domain name sometimes resolves to the Internet and sometimes correctly resolves to the intranet address. I wonder if I have modified the host computer's / etc / resolv.conf and not restarted coredns, because I can't think of any other reasons

**Comment by licaishui88** [comment]
> 
> 
> Actually - can you describe in more detail what you mean by "modify the host resolve" ...
> 
> I initially was thinking you meant you were making changes to hosts in the hosts plugin... but now i'm not sure what you are asking. What are the contents of your Corefile, and what are you changing?
My k8s host computer now has an intranet DNS address configured in / etc / resolv.conf, which used to have an extra Internet DNS address. Now I find that the container Ping the internal domain name sometimes resolves to the Internet and sometimes correctly resolves to the intranet address. I wonder if I have modified the host computer's / etc / resolv.conf and not restarted coredns, because I can't think of any other reasons

**Comment by licaishui88** [comment]
> 
> 
> > Actually - can you describe in more detail what you mean by "modify the host resolve" ...
> > I initially was thinking you meant you were making changes to hosts in the hosts plugin... but now i'm not sure what you are asking. What are the contents of your Corefile, and what are you changing?
> > My k8s host computer now has an intranet DNS address configured in / etc / resolv.conf, which used to have an extra Internet DNS address. Now I find that the container Ping the internal domain name sometimes resolves to the Internet and sometimes correctly resolves to the intranet address. I wonder if I have modified the host computer's / etc / resolv.conf and not restarted coredns, because I can't think of any other reasons



> 
> 
> Actually - can you describe in more detail what you mean by "modify the host resolve" ...
> 
> I initially was thinking you meant you were making changes to hosts in the hosts plugin... but now i'm not sure what you are asking. What are the contents of your Corefile, and what are you changing?



My test shows that modifying configmap will overload, but will not reload the contents of the host resolv.conf  file

**Comment by chrisohaver** [comment]
OK - So this has nothing to do with the _hosts_ plugin.  It has to do with reloading the `resolv.conf` file in the _proxy_ plugin.

Since you are not changing your Corefile, _reload_ will not detect any changes. The _reload_ plugin only monitors the direct contents of the Corefile, not any files it references.  Some plugins monitor the files they reference for changes (like _hosts_), but I don't believe the _proxy_ plugin monitors the `resolv.conf` file for changes.  Neither does its replacement _forward_ (_proxy_ was deprecated a some time ago.  CoreDNS 1.3 is quite old). 

CoreDNS will reload the `resolv.conf` file in a Corefile reload.  You can trigger this by sending a SIGHUP to the CoreDNS process.  However, sending a signal to process in a container in K8s is not easy.  The only easy way to get proxy to reload the `resolv.conf` in k8s is to kill all of the CoreDNS Pods (by default there are two) and let the Deployment spin them back up.

>Now I find that the container Ping the internal domain name sometimes resolves to the Internet and sometimes correctly resolves to the intranet address. I wonder if I have modified the host computer's / etc / resolv.conf and not restarted coredns, because I can't think of any other reasons

It's possible that one of the CoreDNS Pods was restarted after `/etc/resolv.conf` changed, and the other was not, such that one has the new upstream and the other still has the old upstream.

**Comment by licaishui88** [comment]
> changed
yes,I restarted the CoreDNS Pods and it works correctly，thank you very much！
