### ISSUE TITLE
Add coredns_hosts_request_count_total metric

### ISSUE THREAD

**Issue by Diaoul** [coredns/coredns#3758]
**What would you like to be added**:
I would like a `coredns_hosts_request_count_total` to be added in the same way `coredns_forward_request_count_total` works.
Could add the `file` sub-filter similar to the `to` one in the `forward` plugin.

**Why is this needed**:
There is currently no metric as to what goes through the `hosts` plugin. The `file` and `auto` plugins have the `zone` sub-filter available, this is not possible for `hosts` as it is responsible for potentially a huge amount of "zones".

**Comment by sharmaansh21** [comment]
I can work on this :)

**Comment by miekg** [comment]
it probably makes sense to remove this kind of per plugin metrics and have a builtin one that export queries seen per plugin. Now adding zones to such a metrics will blow up the metrics from a label cardinality standpoint...

We have metric changes queued for 1.7.0 so the time is now to make this change.

**Comment by miekg** [comment]
hmm, just looking at metrics; we obvs don't have previous plugin information there.

Why do you care about this metric here for host?

**Comment by stp-ip** [comment]
> it probably makes sense to remove this kind of per plugin metrics and have a builtin one that export queries seen per plugin. Now adding zones to such a metrics will blow up the metrics from a label cardinality standpoint...
> 
> We have metric changes queued for 1.7.0 so the time is now to make this change.

Thinking about that. Most of the plugins seem to want to know how often a specific plugin is hit in total.
We could make this into a general top level metric instead. As the middleware handover code caddy it might mean it's hard to do so.

Something along the lines of:
`coredns_plugin_count_total{server, zone, plugin}`

And even the plugin flow total might be interesting, but increases cardinality:
`coredns_plugin_count_total{server, zone, plugin-chain}`

*plugin-chain being "forward-nsid-custom" for example.

**Comment by Diaoul** [comment]
In my case I use hosts as a blacklist, I can see other uses cases where hosts is used for some extra local resolution. It is useful to know how often the hosts is hit. For example to compare to other plugins.
I like the top level idea but we would loose some plugin-specific cardinality.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add coredns_h..." ]
>> it probably makes sense to remove this kind of per plugin metrics and have a builtin one that export queries seen per plugin. Now adding zones to such a metrics will blow up the metrics from a label cardinality standpoint...
>>
>> We have metric changes queued for 1.7.0 so the time is now to make this change.
>
>Thinking about that. Most of the plugins seem to want to know how often a specific plugin is hit in total.
>We could make this into a general top level metric instead. As the middleware handover code caddy it might mean it's hard to do so.
>
>Something along the lines of:
>`coredns_plugin_count_total{server, zone, plugin}`
>
>And even the plugin flow total might be interesting, but increases cardinality:
>`coredns_plugin_count_total{server, zone, plugin-chain}`
>
>*plugin-chain being "forward-nsid-custom" for example.

yes, but code wise it's annoying because the concept of 'who handled the query' is only
available in the plugin that handled the query... Would be neat though to have this
functionally

**Comment by sresthas** [comment]
Can I take this up as my first issue? Any pointers would be helpful.

**Comment by chrisohaver** [comment]
> Can I take this up as my first issue? Any pointers would be helpful.

Adding this metric to the _hosts_ plugin only is fairly straight forward.  
However making this a general metric that every plugin would increment is more complex.

I'd say that if we are OK with adding this metric only to the hosts plugin for now, then this is a good first issue.  But if we want to make this a more general metric that all plugins use, it requires more discussion up front as to how it would be solved.

**Comment by sharmaansh21** [comment]
@twisted-sres something like https://github.com/coredns/coredns/commit/ad352cee88a6be7154e55a2eb0ef1f95ffa858df @chrisohaver, please feel free to correct me if I am wrong.

**Comment by chrisohaver** [comment]
> @twisted-sres something like ad352ce @chrisohaver, please feel free to correct me if I am wrong.

ad352ce missed registering the metric (so the metric was not exposed) #3784 fixed that.

This would be the simple case for adding the metric only to the _hosts_ plugin. 

If instead we want to make this a more general metric that all plugins use (like @stp-ip proposed), we should first discuss here how it could be solved with minimal impact to existing internal and external plugins.

**Comment by ajitesh13** [comment]
Hello, if no one is working on this, can I work on this issue ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add coredns_h..." ]
>Hello, if no one is working on this, can I work on this issue ?

I don't think we should be adding this on a per-plugin basis. Metrics have a cost.

**Comment by ajitesh13** [comment]
Okay @miekg , thanks for responding, I will find some other good-first-issue to work on.

**Comment by f0o** [comment]
> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add coredns_h..." ]
> Hello, if no one is working on this, can I work on this issue ?
> I don't think we should be adding this on a per-plugin basis. Metrics have a cost.

The metrics should only imply cost if the plugin is used tho - or am I mistaken?

It seems that I'm not alone with the desire to fetch the hits/requests from hosts plugin as I just wrote a patch and noticed afterwards that there are 2 other PRs doing about the same thing lol

Personally I'd prefer having a transparent metric handling for those things from the core to show which plugin has been hit how many times - But seeing how we're now half a year later and still at the same point with repeated PRs for it, it might be worth biting the bullet and just take it per-plugin and refactor later.

**Comment by yongtang** [comment]
@f0o One thing I am considering, is that while we discuss `metrics` there are actually two types of `metrics` we are referring to. One refers to metrics that need to be updated based on time (e.g., CPU/memory usage of every sec/min). Another refers to metrics that is only updated based on event (e.g., number of total request). The later (e.g., number of total request) will not change unless there is an associated event (one new request) happening. For that reason I tend to think the later type of metrics can be extracted from logs. Since logs can be processed separately in another process or even another machine and not to hog down the coredns itself, maybe that is a better way of processing such kind of metrics?

**Comment by f0o** [comment]
@yongtang extracting and parsing logs would require a full overhaul of https://coredns.io/plugins/log to include all sorts of extra data that a plugin might want to emit. Let alone the increased I/O caused by writing verbose logs and having to scrape and rotate it.

It seems unnecessary to go the log-route when request-totals are emitted for other plugins just not this one, because then those other plugins might as well get their count-metrics removed as well to follow the norm...

**Comment by yongtang** [comment]
@f0o log does have one advantage in that it can be avoided if user is not interested. Unlike adding to metrics directly which will have an impact on performance no matter if user want it or not.

**Comment by f0o** [comment]
@yongtang I believe emitting counters as logs is the wrong approach - it's counter to the general idea of prometheus scraping... A lot of counters are currently inside coredns that do just act as increment, rewriting them all into log-lines seems not just overkill but also defying the purpose of having metrics to start with


//Edit: https://github.com/coredns/coredns/search?p=1&q=CounterOpts list of all plugins utilizing counters

**Comment by f0o** [comment]
@Diaoul https://github.com/f0o/prom_hosts drop-in-replacement for hosts plugin if you still need it.

It's sad it that ~7 lines of code are being blocked from merging and needed to be forked and applied in an own plugin now instead of using the well-maintained origin.

But well, there it is. It builds fine if you replace the hosts line in the plugins.cfg - I dont have a dockerhub account so I cant provide docker images. However I can publish the binary if you like.
