### ISSUE TITLE
CoreDns requests are extremely slow

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#3759]
**What happened**:

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/43005289/77138761-3c7e8600-6aae-11ea-8b85-c7c01db09c21.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
![image](https://user-images.githubusercontent.com/43005289/77138833-764f8c80-6aae-11ea-9717-42f4e2484df9.png)

CoreDns Version: 1.6.5
Network Model:  
             hostNetwork: true 
             dnsPolicy: ClusterFirstWithHostNet
- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by miekg** [comment]
screenshots are not useful in bug reports. ping times have nothing to do with dns lookups timeing. please give an exact drilldown of where time is spend in the lookup
