### ISSUE TITLE
Option to disable healthcheck when using coredns as a forwarder

### ISSUE THREAD

**Issue by dneray** [coredns/coredns#3767]
**What would you like to be added**:
I would just like a simple option to disable health checking in the config file 

i.e. something like this:
    forward . 127.0.0.1:9953 {
	    disable_healthchecks
    }

**Why is this needed**:
I am using coredns as a forwarder to add metadata to my dns queries in front of a load balanced dns server and health checking is taken care of by my load balancer.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Option to disable..." ]
>**What would you like to be added**:
>I would just like a simple option to disable health checking in the config file
>
>i.e. something like this:
>    forward . 127.0.0.1:9953 {
>	    disable_healthchecks
>    }
>
>**Why is this needed**:
>I am using coredns as a forwarder to add metadata to my dns queries in front of a load balanced dns server and health checking is taken care of by my load balancer.
>

* `max_fails` is the number of subsequent failed health checks that are needed before considering
  an upstream to be down. If 0, the upstream will never be marked as down (nor health checked).
  Default is 2.


/close
/label forward
/label question
