### ISSUE TITLE
CoreDNS Release: 1.6.9

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3774]
tracking the coredns 1.6.9 release.

1.6.8 was released, but the automation broke before the git upload and after the tag in Git - so we just do another one (version numbers are cheap)

Closes: #3727

**Comment by miekg** [comment]
... bit apprehensive to try again :P

**Comment by stp-ip** [comment]
Go go go

**Comment by stp-ip** [comment]
Worst case we check how various consumers are ordering version numbers aka .9 vs .10 ;)

**Comment by miekg** [comment]
binary lives,  notes live: https://coredns.io/2020/03/24/coredns-1.6.9-release/

closing here. I'll tweet as well.

Best release ever, until the next release
