### ISSUE TITLE
codify metric naming?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3778]
We just had a massive metric name clean up which is an annoying backward incompat change.
Now in `test/presubmit_test.go` we already have a bunch of "tests" that check style issues that are specific to CoreDNS.

Can we add a metric naming test to this as well? 

/cc @SuperQ

**Comment by SuperQ** [comment]
Interesting idea. I don't know if there's any linter code out there for metric names. Maybe @beorn7 has some ideas here.

**Comment by beorn7** [comment]
`promtool check metrics` is doing a bit of linting, as in

```
$ curl -s localhost:8080/metrics | promtool check metrics
foo counter metrics should have "_total" suffix
```

I'd say there could be more checks in it, and I guess PRs will be welcome.

`promtool check metrics` could be part of your CI pipeline. Or the `github.com/prometheus/prometheus/util/promlint` package could be used directly.

One might argue that package could live in `prometheus/client_golang`, but I'm getting ahead of myself.

**Comment by miekg** [comment]
ah that's neat. Slight down side of having another tool and the need to stand up prometheus, feed it queries (not all metrics are initialized on start) and then check. But it's good to know it possible.

I want to take a slightly different route and just parse the go code, looks for a prometheus metric declaration, get the type and then check - this can be done from a Go test

**Comment by beorn7** [comment]
No need to run the Prometheus server.

The `promlint` package takes MetricFamily protobufs, IIUC. So you can just write a Go test that calls `Gather` on your metrics registry and feeds them to `promlint`.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] codify metric..." ]
>No need to run the Prometheus server.
>
>The `promlint` package takes MetricFamily protobufs, IIUC. So you can just write a Go test that calls `Gather` on your metrics registry and feeds them to `promlint`.

ok, thanks. I'll look into it!

**Comment by chrisohaver** [comment]
> The promlint package

nice
