### ISSUE TITLE
middleware/kubernetes reverse/PTR support

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#378]
Kube-DNS is the default resolver below, and CoreDNS is running at 10.2.10.35.

```
/ # apk add --update bind-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libcap (2.25-r0)
(2/4) Installing libgcc (5.3.0-r0)
(3/4) Installing bind-libs (9.10.4_p3-r0)
(4/4) Installing bind-tools (9.10.4_p3-r0)
Executing busybox-1.24.2-r11.trigger
OK: 8 MiB in 15 packages
/ # host kubernetes
kubernetes.default.svc.cluster.local has address 10.3.0.1
/ # host 10.3.0.1
1.0.3.10.in-addr.arpa domain name pointer kubernetes.default.svc.cluster.local.
/ # host 10.3.0.1 10.2.10.35
Using domain server:
Name: 10.2.10.35
Address: 10.2.10.35#53
Aliases:

1.0.3.10.in-addr.arpa domain name pointer 10.3.0.1.
/ #
```

**Comment by miekg** [comment]
What are the contents of the Corefile? Are you routing the reverse arpa zone to it?

**Comment by johnbelamaric** [comment]
Ah. No. :)

**Comment by johnbelamaric** [comment]
Corefile is just:

```
.:53 {
    log stdout
    health
    kubernetes cluster.local
    proxy . /etc/resolv.conf
    #cache 30
}
```

**Comment by miekg** [comment]
Ok, well I don't understand the current reverse handling in the k8s middleware, so I would start there.. It is completely special cased for some reason.

**Comment by miekg** [comment]
I think we want to fix this before doing a 003 release, no?

**Comment by johnbelamaric** [comment]
Yeah, probably. I did try with the reverse arpa zone and here is what I get with the latest code:

CoreDNS

```
/ # host 10.3.0.97 10.3.0.11
Using domain server:
Name: 10.3.0.11
Address: 10.3.0.11#53
Aliases:

97.0.3.10.in-addr.arpa has no PTR record
```

Kube-DNS

```
/ # host 10.3.0.97
97.0.3.10.in-addr.arpa domain name pointer foobarman.default.svc.cluster.local.
/ #
```

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/kube..." ]

> Yeah, probably. I did try with the reverse arpa zone and here is what I get with the latest code:

Ack, my k8s knowledge is lacking for this. I got as far that the middleware sees the name
and extracts the IP address. Then it is off to the k8s code which does "the
wrong thing"(TM)

**Comment by johnbelamaric** [comment]
Ok, I have this working for services, I need to add it for pods still. The annoying thing is that there doesn't seem to be a way to get the service and pod CIDRs from the K8s API, so the reverse zones have to be explicitly specified in the kubernetes middleware config.

Ideally, we could pull that data as well as the cluster domain from K8s API. If that were possible, then the default configuration of K8s middleware could just be "kubernetes" without specifying zones or anything else.

**Comment by johnbelamaric** [comment]
Reverse support is there for services, which is all we have forward support for now anyway. Added with #428
