### ISSUE TITLE
DNS-over-HTTPS support in forward plugin

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#3788]
DoH-support in forward plugin: issues like #1929 and #1874. They are all closed but no updates.

Add support for DNS-over-HTTPS described in [RFC 8484](https://tools.ietf.org/html/rfc8484).

[dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy), [cloudflared](https://github.com/cloudflare/cloudflared) (see also [DNS-over-HTTPS proxy](https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/)) and [Adguard dnsproxy](https://github.com/AdguardTeam/dnsproxy) already support this feature.

**Comment by miekg** [comment]
if done it should be a new plugin, just like the plugin/grpc

**Comment by vamage** [comment]
Going to work on this. I've created a v0 of this at https://github.com/coredns/coredns/compare/master...vamage:dohtest mostly stealing from grpc plugin.

**Comment by snakwu** [comment]
> Going to work on this. I've created a v0 of this at https://github.com/coredns/coredns/compare/master...vamage:dohtest mostly stealing from grpc plugin.

Can you provide a separate doh plug-in? thank you very much.

**Comment by miekg** [comment]
closing as this will be done as a new plugin.

**Comment by v-byte-cpu** [comment]
@miekg why this issue was closed ? This plugin was not merged into mainstream

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] DNS-over-HTTP..." ]
>why this issue was closed ? This plugin was not merged into mainstream

https support will need to be done in another plugin, not in forward. Complexity is what
killed the old *proxy* plugin.

/close
/lock
