### ISSUE TITLE
plugin/hosts has no effect

### ISSUE THREAD

**Issue by johdandc** [coredns/coredns#3795]
**What happened**:
I add an ip in hosts like below:
    hosts {
      100.66.23.45 harbor.local
      fallthrough
    }
but I can not ping the harbor.local in pod and the ping would tell me "ping: bad address 'harbor.local'".
**What you expected to happen**:
ping would be ok.
**How to reproduce it (as minimally and precisely as possible)**:
add an ip in hosts like below:
    hosts {
      100.66.23.45 harbor.local
      fallthrough
    }
and then ping in a pod.
**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:1.6.9
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by zouyee** [comment]
Use the following command to determine if  `coredns` works 
`dig @YOURDNSIP harbor.local`
Before pinging, you need to confirm that your dnsresolv has been configured with your dns IP.

**Comment by johdandc** [comment]
/ # nslookup harbor.local 169.254.25.10
Server:    169.254.25.10
Address 1: 169.254.25.10

nslookup: can't resolve 'harbor.local': Name does not resolve

It seems like that the dns ip cannot resolve the name.

But now I want to visit the server in the intranet by the server name and how I should configure the dns or I can only set the /etc/hosts for each pod?

**Comment by chrisohaver** [comment]
Corefile and logs please.

**Comment by johdandc** [comment]
Corefile:
.:53 {
    errors
    health
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      upstream /etc/resolv.conf
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf {
      prefer_udp
    }
    hosts {
      100.66.23.45 harbor.local
      fallthrough
    }
    cache 30
    loop
    reload
    loadbalance
    whoami
}

kubectl logs coredns-7585d78ddb-nwmzt -n kube-system
.:53
[INFO] plugin/reload: Running configuration MD5 = a99576e7b1712135bfa77c7d266e9269
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568

**Comment by chrisohaver** [comment]
Thanks, that configuration and log looks OK...  Please go through the troubleshooting steps in https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/.

**Comment by johdandc** [comment]
After I created a test pod and each step as below:

sh-4.2$ cat /etc/resolv.conf
nameserver 169.254.25.10
search harbor-test.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

sh-4.2$ nslookup harbor.local
Server:         169.254.25.10
Address:        169.254.25.10#53

** server can't find harbor.local: NXDOMAIN

kubectl get pods -n kube-system -l k8s-app=kube-dns
NAME                       READY   STATUS    RESTARTS   AGE
coredns-7585d78ddb-nwmzt   1/1     Running   0          28h

for p in $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name); do kubectl logs --namespace=kube-system $p; done
.:53
[INFO] plugin/reload: Running configuration MD5 = a99576e7b1712135bfa77c7d266e9269
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568

kubectl get svc --namespace=kube-system
NAME                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
coredns                            ClusterIP   10.233.0.3     <none>        53/UDP,53/TCP,9153/TCP   6d23h
etcd                               ClusterIP   None           <none>        2379/TCP                 6d22h
kube-controller-manager-headless   ClusterIP   None           <none>        10252/TCP                6d22h
kube-scheduler-headless            ClusterIP   None           <none>        10251/TCP                6d22h
kubelet                            ClusterIP   None           <none>        10250/TCP                6d22h
metrics-server                     ClusterIP   10.233.22.49   <none>        443/TCP                  6d23h
tiller-deploy                      ClusterIP   10.233.15.78   <none>        44134/TCP                6d23h

kubectl get ep coredns --namespace=kube-system
NAME      ENDPOINTS                                           AGE
coredns   10.233.94.56:53,10.233.94.56:53,10.233.94.56:9153   6d23h

kubectl -n kube-system edit configmap coredns
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          prefer_udp
        }
        hosts {
          100.66.23.45 harbor.local
          fallthrough
        }
        cache 30
        loop
        reload
        loadbalance
        whoami
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      upstream /etc/resolv.conf\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf {\n      prefer_udp\n    }\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"EnsureExists"},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2020-03-24T14:10:21Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: coredns
  namespace: kube-system
  resourceVersion: "1220556"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 40b7350c-9977-4062-8a9d-b62242ad18f6

And what can I do to make my coredns works?

**Comment by johdandc** [comment]
Got it!
Only if the address to resolv match the search config in /etc/resolv.conf in container, the hosts plugin can work.
