### ISSUE TITLE
EKS [Request]:Unable to collect the coredns metrics in datadog 

### ISSUE THREAD

**Issue by UdayabhanuPani** [coredns/coredns#3806]
No

**What happened**:
Hello,

We have coredns configured as a default eks-componemt for us using the kube-dns service in kube-system namespace . We are facing issues while. trying to integrate coredns with Datadog to collect the Coredns Metrics.

It seems we don’t have the metric port 9153 at the kube-dns at service level , which is present for the coredns pod for which it is not able to fetch the metrics and /metrics is not exposed at the service level to enable the prometheus plugin as per the docs:

https://www.datadoghq.com/blog/monitor-coredns-with-datadog/

https://github.com/DataDog/integrations-core/blob/master/coredns/datadog_checks/coredns/data/auto_conf.yaml

Please let me know , if we have a fix in this situation , do we need to upgrade our EKS version or do a manual patch to include the port configuration at service level.

Current EKS version: 1.14 and Platform version: eks.8

**What you expected to happen**:
It was expected to fetch the coredns metrics in datadog after exposing the /metrics path through port 9153.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
DEV

- the version of CoreDNS: 1.3.1
- Corefile: 
[coredns.txt](https://github.com/coredns/coredns/files/4414090/coredns.txt)

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by miekg** [comment]
seems noone has time to help or knows how to help. closing

**Comment by chrisohaver** [comment]
Your kubernetes' coredns service definition probably needs to be updated to be more like...

https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L168-L193

note the exposed metrics port and prometheus annotations
