### ISSUE TITLE
Non-overlapping CIDRs on different server blocks can fatal server

### ISSUE THREAD

**Issue by mattlqx** [coredns/coredns#3808]
**What happened**:

I found that you can use a CIDR in a server block for it to automatically create in-addr.arpa zones for the net block. However, if you're not on a classful boundary with the CIDR, it will "round up". e.g. 172.28.224.0/22 will create a 28.172.in-addr.arpa zone, as would 172.28.228.0/22. Adding subnets that are otherwise non-overlapping in different blocks will attempt to create duplicate in-addr.arpa zones and cause the daemon to fatal.

For example, this:

``` 
172.28.224.0/22 172.28.0.0/19 subdomain1.example.com {
  ...
}

172.28.228.0/22 172.28.32.0/19 subdomain2.example.com {
  ...
}
```

Will result in the server failing to launch with this showing in the logs:
`cannot serve dns://28.172.in-addr.arpa.:53 - it is already defined`

You can get the above working by breaking out each CIDR into /24 subnets so that they'll internally generate x.28.172.in-addr.arpa zones without duplication.

```
172.28.0.0/24 172.28.1.0/24 172.28.2.0/24 172.28.3.0/24 172.28.4.0/24 172.28.5.0/24 172.28.6.0/24 172.28.7.0/24 172.28.8.0/24 172.28.9.0/24 172.28.10.0/24 172.28.11.0/24 172.28.12.0/24 172.28.13.0/24 172.28.14.0/24 172.28.15.0/24 172.28.16.0/24 172.28.17.0/24 172.28.18.0/24 172.28.19.0/24 172.28.20.0/24 172.28.21.0/24 172.28.22.0/24 172.28.23.0/24 172.28.24.0/24 172.28.25.0/24 172.28.26.0/24 172.28.27.0/24 172.28.28.0/24 172.28.29.0/24 172.28.30.0/24 172.28.31.0/24 172.28.224.0/24 172.28.225.0/24 172.28.226.0/24 172.28.227.0/24 subdomain1.example.com {
  ...
}

172.28.32.0/24 172.28.33.0/24 172.28.34.0/24 172.28.35.0/24 172.28.36.0/24 172.28.37.0/24 172.28.38.0/24 172.28.39.0/24 172.28.40.0/24 172.28.41.0/24 172.28.42.0/24 172.28.43.0/24 172.28.44.0/24 172.28.45.0/24 172.28.46.0/24 172.28.47.0/24 172.28.48.0/24 172.28.49.0/24 172.28.50.0/24 172.28.51.0/24 172.28.52.0/24 172.28.53.0/24 172.28.54.0/24 172.28.55.0/24 172.28.56.0/24 172.28.57.0/24 172.28.58.0/24 172.28.59.0/24 172.28.60.0/24 172.28.61.0/24 172.28.62.0/24 172.28.63.0/24 172.28.228.0/24 172.28.229.0/24 172.28.230.0/24 172.28.231.0/24 subdomain2.example.com {
  ...
}
```

**What you expected to happen**:

I expected that CoreDNS would be able to handle this internally, breaking the larger subnets into more managable /24s in-addr.arpas and preventing creation of duplicate zones.

**How to reproduce it (as minimally and precisely as possible)**:

Use the shorter large-CIDR config above.

**Anything else we need to know?**:

The redacted contents of the blocks are primarily just a forward to a server responsible for that subdomain (specifically, it's forwarding to a CoreDNS server running in a Kubernetes cluster providing records via the `kubernetes` plugin).

**Environment**:

- the version of CoreDNS: 1.6.9
- OS (e.g: `cat /etc/os-release`): Official docker image

**Comment by chrisohaver** [comment]
This is a permutation of a known issue with the CIDR notation shortcut for defining reverse zones.
See also #2779, and PRs related to that.
A suitable fix has yet to be agreed upon.

The workaround is to define the reverse zones manually.  As in your example, those zones could also be expressed in CIDR notation, as long as their masks are at 8 bit boundries /8 /16 /24 ...).
