### ISSUE TITLE
Recursive Queries Error 

### ISSUE THREAD

**Issue by mo-ghorbani** [coredns/coredns#3809]
Hi, so I use coredns for resolving my domain address to IP. The problem that I have is that when I check with intodns.com it shows me "Recursive Queries" error. I know that in BIND I have to put 
`recursion no;` to solve the problem but I can't figure out how to solve the problem in coredns? (with docker).
Please help me, thanks.

**Comment by mony123456** [comment]
اشرح لي مشكلتك تفصيلا

في الجمعة، ٣ أبريل، ٢٠٢٠ ٩:١١ ص mohammad <notifications@github.com> كتب:

**Comment by miekg** [comment]
we set the RD flag because of some other reason, it's harmless. 'intodns.com' is just too stupid to tell the difference.
