### ISSUE TITLE
Dynamic DNS responses / scripting

### ISSUE THREAD

**Issue by cyberzlo** [coredns/coredns#3823]
Is this possible to do dynamic DNS responses? What I mean, do script logic for DNS response? Let's say something like calc over DNS, just as example - script can decide on fly what will respond rather than just read it from static DNS zone.

**Comment by stp-ip** [comment]
You could do that with your own custom plugin. https://coredns.io/2016/12/19/writing-plugins-for-coredns/
CoreDNS itself or with the default plugins can't do arbitrary scripting. There are a few that can template responses, but nothing like scripting.

**Comment by miekg** [comment]
I've pondered have a lua plugin which you can then script, but then again I rather use Go and then you should just write a plugin.
