### ISSUE TITLE
middleware/rewrite DNS error with chromium for zone rewrites

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#383]
I was testing the rewrite middleware and it seems it works well with tools like curl, wget and even firefox, but chromium seems to do something strange and returns a DNS error "ERR_NAME_NOT_RESOLVED".

The assumption first was that the rewrite middleware internally rewrites the query.
With something like ```rewrite google.de google.com``` a query for google.de would return the IP of google.com (or in general the entries of google.com). The entries are returned as one would think, but the answer also uses the new zone name.
Example:
```
; <<>> DiG 9.11.0-P1 <<>> @127.0.0.2 google.de
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29109
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.de.		IN	A

;; ANSWER SECTION:
google.com.		299	IN	A	216.58.214.110

;; Query time: 46 msec
;; SERVER: 127.0.0.2#53(127.0.0.2)
;; WHEN: Sun Nov 06 09:55:18 UTC 2016
;; MSG SIZE  rcvd: 70
```
The assumption is that chromium checks the zone in the answer section and as it doesn't match the query assumes it's invalid.
Should we provide a workaround and do complete internal rewrites for names so that the answer zone is the same as the queried one?

**Comment by miekg** [comment]
Can do but that would break DNSSEC, could do it for non signed responses
but that would be weird.

Thanks for the input btw, really helps to understand what we can and can't
do with query rewritting.

**Comment by stp-ip** [comment]
Thanks for the clarification.
Makes sense to keep the current implementation and probably try to fix chromium. Will look into the issue on their side.

Would say the issue is logged now and as there is nothing on the coredns side to do -> closing.

**Comment by stp-ip** [comment]
Zone rewrites can be done using a duplicate zone files or a symlink.
The important part is to use @ as MNAME within the SOA record. This will then be replaced with the actual served zone. Sidenote: This will give issues with DNSSEC.

```
@   IN SOA @ domains.example.net. (
    2016110802   ; serial
    300          ; refresh
    300          ; retry
    2w           ; expire
    60  )        ; minimum

@                        IN NS      ns1.example.com.
@                        IN NS      ns2.example.com.

www                42000 IN CNAME   example.net.
```
