### ISSUE TITLE
Can't listen on one interface/address if port is in use on a different interface

### ISSUE THREAD

**Issue by cbix** [coredns/coredns#3834]
**What happened**:
Coredns wouldn't start for zone block ".:42.42.42.42:53" (exemplary) with 42.42.42.42 being the address of the ens3 interface while there is another service (systemd-resolved) is listening on 127.0.0.53:53 at the loopback interface. Exits with `ListenPacket: listen udp :53: bind: address already in use`.
**What you expected to happen**:
Coredns should regard the given address because it should be possible to specify the listening interface in some way.
**How to reproduce it (as minimally and precisely as possible)**:
Corefile:

    .:42.42.42.42:53 {
      log
    }

`DNSStubListener=yes` (resp. default value) in /etc/systemd/resolved.conf which makes systemd-resolved listen on 127.0.0.53:53 (TCP & UDP). Can be any other process listening on port 53 of localhost.
**Anything else we need to know?**:

**Environment**:
Ubuntu 18.04 (coredns compiled on Arch Linux with go1.14.2
- the version of CoreDNS: `CoreDNS-1.6.9 linux/amd64, go1.14.2, 8013925b-dirty`
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
That syntax `.:42.42.42.42:53` is not expected - I'm not sure how it would behave.
Instead, use the `bind` plugin to bind the server to an ip address. e.g.

```
.:53 {
  bind 42.42.42.42
  log
}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Can't listen ..." ]
>That syntax .:42.42.42.42:53 is not expected - I'm not sure how it would

this is (sadly) a completely valid zone, so there isn't something we can say here.

/close

**Comment by cbix** [comment]
Wasn't aware `bind` did this, I somehow assumed it was a Bind9 backend plugin. Thanks for this!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Can't listen ..." ]
>Wasn't aware bind did this, I somehow assumed it was a Bind9 backend plugin.

this was brought up before, but 'bind' is a good name for this plugin.
