### ISSUE TITLE
[investigation] Got recursion not available from ... trying next server

### ISSUE THREAD

**Issue by ltagliamonte-dd** [coredns/coredns#3835]
I'm upgrading my coredns installation from v1.1.3 to v1.6.7
I'm running coredns in kubernetes with the following setup:
- a set of coredns pods as main k8s cluster DNS available at `10.4.240.10`
- a coredns pod running in the host net namespace on all the k8s nodes, the pod is available at `192.168.0.1` on all the nodes via a dedicated loopback interface created with `ifconfig lo:0 192.168.0.1 up`

both installations uses the same config:
```
    .:53 {
        errors
        health {
          lameduck 5s
        }
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        cache 30
        loadbalance
        reload
    }
```

each pod gets the following resolv.conf:
```
nameserver 192.168.0.1
nameserver 10.4.240.10
search lt-test.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```
as you can see i'm using both installations for fallback.

with coredns v1.1.3 :
```
nslookup google.com
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.14.206
Name:	google.com
Address: 2607:f8b0:400a:801::200e
```

with coredns v1.6.7:
```
nslookup google.com
;; Got recursion not available from 192.168.0.1, trying next server
;; Got recursion not available from 192.168.0.1, trying next server
;; Got recursion not available from 192.168.0.1, trying next server
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.14.206
Name:	google.com
Address: 2607:f8b0:400a:801::200e
```

it looks like this new behavior starts from https://github.com/coredns/coredns/pull/2408 present in release v1.3.1 (tested downgrading and upgrading)

as I read in some other issues on this repo it looks like that nslookup cmd sets by default the recursive flag in the DNS queries, and that flag has been dropped by a bunch of plugins like the k8s one in #2408

What I can't understand is why if I remove one nameserver (independently of which one I remove) from the resolv.conf:
```
nameserver 192.168.0.1
search lt-test.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```
the nslookup behaves correctly with no WARN:
```
nslookup google.com
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.14.238
Name:	google.com
Address: 2607:f8b0:400a:808::200e
```

The dns query it sends in both cases (with 1 or 2 nameservers) contains the recursive flag.
I'm attaching the output of `nslookup -debug -d2 google.com` with 1 nameserver and 2 nameservers and in both it is possible to notice the set of `recursive query`

[2nameserver-warn.zip](https://github.com/coredns/coredns/files/4497691/2nameserver-warn.zip)
[1nameserver-ok.zip](https://github.com/coredns/coredns/files/4497693/1nameserver-ok.zip)

It should behave in the same way with 1 or 2 nameservers, since both nameservers are CoreDNS, running with the same config.
What am i missing?

if I use `nslookup -norecurse` no warning but obviously i don't get a result:
[norecurse.zip](https://github.com/coredns/coredns/files/4497800/norecurse.zip)

**Comment by chrisohaver** [comment]
Does the "system resolver" behave the same way?  Or is this just an nslookup thing?
I'm guessing that nslookup is more "picky" when it knows it can fall back to another server.

As an alternative, have you looked into nodelocal cache in K8s?  It runs a caching CoreDNS instance on every node.  It may mitigate the problems you are aiming to solve with this solution in a different way.

**Comment by ltagliamonte-dd** [comment]
Hello @chrisohaver thank you for the reply I tried with no luck to find the warn message in the nslookup code just to make sure it is just a warn.

What do you mean for "system resolver" how can I test that all is working as expected?

About the nodelocal we need to test it, we had this configuration since k8s 1.10 because nodelocal at that time was in alpha

**Comment by chrisohaver** [comment]
> What do you mean for "system resolver" how can I test that all is working as expected?

Are things other than nslookup falling back to the second dns server in the list?  For example, does using `curl` fallback (could verify by checking CoreDNS logs to see second entry gets the request).  Trying to determine if this behavior is specific to nslookup, or if it is part of the collectively loose "standard" dns lookup behavior.  If this is just an nslookup thing, and you are not relying heavily on nslookup, then this error could be ignored.

> About the nodelocal we need to test it, we had this configuration since k8s 1.10 because nodelocal at that time was in alpha

nodelocal dns has matured significantly in the past 2 years.

**Comment by ltagliamonte-dd** [comment]
@chrisohaver i've enabled log on both installations:
```
log {
   class success denial error
}
```

i've tried the following curl:
```
curl -s mytotalfakedomain > /dev/null
```

and I can see logs only in the daemonset (first IP) in resolv.conf
```
[INFO] 10.4.186.66:42545 - 34903 "AAAA IN mytotalfakedomain.lt-test.svc.cluster.local. udp 63 false 512" NXDOMAIN qr,aa,rd 156 0.000182066s
[INFO] 10.4.186.66:42545 - 12107 "A IN mytotalfakedomain.lt-test.svc.cluster.local. udp 63 false 512" NXDOMAIN qr,aa,rd 156 0.000260273s
[INFO] 10.4.186.66:43883 - 3410 "AAAA IN mytotalfakedomain.svc.cluster.local. udp 53 false 512" NXDOMAIN qr,aa,rd 146 0.000119777s
[INFO] 10.4.186.66:43883 - 25677 "A IN mytotalfakedomain.svc.cluster.local. udp 53 false 512" NXDOMAIN qr,aa,rd 146 0.000136492s
[INFO] 10.4.186.66:53680 - 39530 "A IN mytotalfakedomain.cluster.local. udp 49 false 512" NXDOMAIN qr,aa,rd 142 0.000129654s
[INFO] 10.4.186.66:53680 - 63854 "AAAA IN mytotalfakedomain.cluster.local. udp 49 false 512" NXDOMAIN qr,aa,rd 142 0.000181528s
[INFO] 10.4.186.66:43987 - 48927 "AAAA IN mytotalfakedomain.us-west-2.compute.internal. udp 62 false 512" NXDOMAIN qr,rd,ra 175 0.007657553s
[INFO] 10.4.186.66:43987 - 15129 "A IN mytotalfakedomain.us-west-2.compute.internal. udp 62 false 512" NXDOMAIN qr,rd,ra 175 0.017881386s
[INFO] 10.4.186.66:54833 - 63279 "AAAA IN mytotalfakedomain. udp 35 false 512" NXDOMAIN qr,rd,ra 110 0.00710978s
[INFO] 10.4.186.66:54833 - 61739 "A IN mytotalfakedomain. udp 35 false 512" NXDOMAIN qr,rd,ra 110 0.009301934s
```

All the `rd` in the response flags are because of https://github.com/coredns/coredns/pull/2408
then all the `ra` come from the forward plugin?

if I swap the order of the resolvers I get the same logs in the cluster installation of coreDNS.
This indeed is a progress in this investigation, but how can we make sure that all software behave at the same way? I guess there isn't an universal source of truth.

**Comment by chrisohaver** [comment]
> All the rd in the response flags are because of #2408
> then all the ra come from the forward plugin?

`rd` - recursion desired, is set by the client in the request.
`ra` - recursion available, is set by the server in the response. in this case, it's added by the upstream server that coredns forwards to.

> I guess there isn't an universal source of truth.

I don't think there is for client behavior, but I suspect most ignore the absence of an `ra` flag if they get an answer.  `nslookup` being an exception.

**Comment by ltagliamonte-dd** [comment]
the nslookup behavior with 2 servers (WARN message) and 1 server (NO WARN message) in the resolv.conf was really bugging me, and i think i found the source of it:

https://github.com/isc-projects/bind9/blob/v9_11_15/bin/dig/dighost.c#L4128-L4162

if i correctly understand this code it will print the WARN message only if it has another available query/server to contact.

@chrisohaver: `rd - recursion desired, is set by the client in the request.`
according to the log doc those should be response flags.. so i thought that the `D` in this case is standing for denied.

**Comment by chrisohaver** [comment]
It is a response flag.  It is set by the client, and echoed back in the response by the server.  The `d` is for desired.

**Comment by chrisohaver** [comment]
Note, the message to developers at the [top of the bind library](https://github.com/isc-projects/bind9/blob/v9_11_15/bin/dig/dighost.c#L12-L20): 
```
 * Notice to programmers:  Do not use this code as an example of how to
 * use the ISC library to perform DNS lookups.  Dig and Host both operate
 * on the request level, since they allow fine-tuning of output and are
 * intended as debugging tools.  As a result, they perform many of the
 * functions which could be better handled using the dns_resolver
 * functions in most applications.
```

`nslookup` would wall into the same category, a dns debugging tool.  So that might put you at ease that normal DNS lookups would not necessarily follow this behavior.

**Comment by ltagliamonte-dd** [comment]
Thank you for all the help here @chrisohaver i'm going ahead and close this issue.
It is just a cosmetic issue of using nslookup.

I've also done a quick python test:
```
import socket
addr1 = socket.gethostbyname('myveryfakepythondomain')
print(addr1)
```
and it correctly pointed only to the first nameserver present in `/etc/resolv.conf`
I put in place dashboards and monitoring on my end in order to make sure that the daemonset is used as primary resolver rather than the default deployment.
