### ISSUE TITLE
Cache plugin does not work when DO bit is set

### ISSUE THREAD

**Issue by elliotfehr** [coredns/coredns#3836]
**What happened**:
DNS queries with DO bit set will miss cache 100% of the time

**What you expected to happen**:
CoreDNS to serve subsequent queries from cache

**How to reproduce it (as minimally and precisely as possible)**:
Running `dig @<core-dns-ip> +dnssec google.com` results in a cache miss while removing the `+dnssec` will result in a cache hit. After debugging, https://github.com/coredns/coredns/blob/master/plugin/cache/cache.go#L78 is always false while https://github.com/coredns/coredns/blob/master/plugin/cache/handler.go#L100 reflects the correct value set by the client.

- the version of CoreDNS: master (https://github.com/coredns/coredns/commit/8013925b532d8a9e0d94a583c686a483cb665b80)
Debug logging:
```
[INFO] plugin/cache: handler.go: qname=google.com., qtype=1, do=true
[INFO] plugin/cache: looking up key in cache: 15668015455082718403
[INFO] plugin/cache: cache miss
[INFO] plugin/cache: cache.go: qname=google.com., qtype=1, do=false
[INFO] plugin/cache: [IN google.com.] key: 3507767526084950336 - ttl: 3m20s
[INFO] 127.0.0.1:55203 - 18136 "A IN google.com. udp 39 true 4096" NOERROR qr,rd,ra 54 0.004500154s
```

**Comment by elliotfehr** [comment]
This can happen if the client sets the DO bit on a query that will be forwarded to an upstream that does not support DNSSEC, causing the cached response to not have it set and ultimately setting `do=false` in the cache while the request is generating a key with `do=true` resulting in a key mismatch and a cache miss.

**Comment by mr-feek** [comment]
+1 I have also run into this

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Cache plugin ..." ]
>/cc

does this need a third category in the cache? Admittently this could have been done/better
smarter in the first place.


/Miek

--
Miek Gieben

**Comment by zouyee** [comment]
> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] Cache plugin ..." ]
> /cc
> does this need a third category in the cache? Admittently this could have been done/better smarter in the first place. /Miek
> […](#)
> -- Miek Gieben

For the `do=false` case, if the query fails in the `getIgnoreTTL` method, then try `do=true `case to query again, or introduce a third category in the cache  to satisfies the  scenario？

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Cache plugin ..." ]
>    [ Quoting notifications@github.com in "Re: [coredns/coredns] Cache plugin
>    ..." ]
>    /cc
>    does this need a third category in the cache? Admittently this could have
>    been done/better smarter in the first place. /Miek
>    …
>    -- Miek Gieben
>
>For the do=false case, if the query fails in the getIgnoreTTL method, then try
>do=true case to query again, or introduce a third category in the cache to
>satisfies the scenario？

well, this highlights probably that saving entire messages in the cache is not the best
approach. Couple of options here:

* split the entire cache into caching RRsets - this is what most (all?) DNS servers do
   There are some security things here you need to be aware off. Memory wise this will
   problably be better as well.
   It's however quite some work to pull this off

* requerying in the cache is a bit strange and we should not go there.

* just handle this case (do bit set, upstream doesn't). Which should just fix this.


Note that a RRsets based cache is the best option longer term.

**Comment by miekg** [comment]
While thinking about an RRSet cache (which is pretty complex in itself) I figured that cache should _always_ do a DNSSEC lookup. This would fix this bug as well and do away with the DO and non-DO behaviour.

The change would be: cache will modify the query to add 'request DNSSEC' + some buffer size (2k?) while letting the query through, when the reply comes back we just store it (as we do know). For non-dnssec clients we strip the DNSSEC RRs from the reply.

This would simplify things and solve this bug
