### ISSUE TITLE
DNS64: Does not return synthesized record from forwarder

### ISSUE THREAD

**Issue by artooro** [coredns/coredns#3837]
**What happened**:

Returned 0 answers to AAAA query.

**What you expected to happen**:

I expected the A record to be synthesized by the DNS64 plugin.

**How to reproduce it (as minimally and precisely as possible)**:

Corefile
```conf
.:50053 {
  dns64 64:ff9b::/96
  forward . 8.8.8.8
  log
  errors
}
```

Start coredns with this Corefile, and make DNS query to an IPv4-only site such as twitter.com
```sh
dig AAAA twitter.com @127.0.0.1 -p 50053
```

Response logged by coredns is:
```log
[INFO] 127.0.0.1:61507 - 36252 "AAAA IN twitter.com. udp 40 false 4096" NOERROR qr,rd,ra 126 0.0187902s
```

But the output of the dig command is:
```sh
; <<>> DiG 9.10.6 <<>> AAAA twitter.com @127.0.0.1 -p 50053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36252
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;twitter.com.			IN	AAAA

;; AUTHORITY SECTION:
twitter.com.		291	IN	SOA	ns1.p26.dynect.net. zone-admin.dyndns.com. 2007143386 3600 600 604800 60

;; Query time: 18 msec
;; SERVER: 127.0.0.1#50053(127.0.0.1)
;; WHEN: Sun Apr 19 00:46:07 EDT 2020
;; MSG SIZE  rcvd: 126
```

**Anything else we need to know?**:

Doing an A query to twitter.com works and responds correctly. So it's not an issue of the forward plugin not working.

**Environment**:

- the version of CoreDNS: 1.6.9 (current master branch)
- Corefile: shown above
- logs, if applicable:
```log
.:50053
CoreDNS-1.6.9
darwin/amd64, go1.14.2, 8013925b
[INFO] 127.0.0.1:65482 - 12532 "A IN twitter.com. udp 40 false 4096" NOERROR qr,rd,ra 94 0.0219585s
[INFO] 127.0.0.1:61507 - 36252 "AAAA IN twitter.com. udp 40 false 4096" NOERROR qr,rd,ra 126 0.0187902s
```
- OS (e.g: `cat /etc/os-release`): macOS 10.15.4
- Others:

**Comment by chrisohaver** [comment]
CODEOWNERS doesn't yet have an entry for dns64.

cc @SuperQ

**Comment by SuperQ** [comment]
From the [README](https://github.com/coredns/coredns/blob/master/plugin/dns64/README.md#description).

> The synthesis in only performed if the query came in via IPv6.

The plugin assumes that a query coming from an IPv4 client doesn't need translation.

Try
```
dig AAAA twitter.com @::1 -p 50053
```

**Comment by artooro** [comment]
@SuperQ I knew it must be something obvious. I feel like an idiot. Thank you.

**Comment by SuperQ** [comment]
Maybe we should add a `dig` example to the README. This isn't the first time a user has run into this "feature".

I was thinking about adding an additional boolean config option, `translate-from-v4` but leave it off by default. But I wanted to keep the configuration of this plugin to a minimum.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] DNS64: Does n..." ]
>Maybe we should add a dig example to the README. This isn't the first time a
>user has run into this "feature".

please add something if that makes sense.

CODEOWNERS as @chrisohaver flagged is good to have as well

>I was thinking about adding an additional boolean config option,
>translate-from-v4 but leave it off by default. But I wanted to keep the
>configuration of this plugin to a minimum.

I don't think we should go that route
