### ISSUE TITLE
Why we need route53 plugin

### ISSUE THREAD

**Issue by rverma-jm** [coredns/coredns#3838]
Wondering why we need the route53 plugin at first place.

Trying to simulate different scenarios around route53 usage and wondering what am I missing and in which scenario it would make sense.

Consider initial setup as with below private zones

```
**VPC: management(mgmt)** 
Hosting: grafana
route53 record: promethes.mgmt.internal A 172.138.16.11


**VPC: Non-prod**
Hosting: prometheus , created  a headless service and synced pod IPs with external-dns.
route53 record: promethes.dev.internal A 10.10.10.11

```
Settings enabled
```
enableDnsHostnames
enableDnsSupport
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-ec2-instance.html
```

Scenario 1:
To access `promethes.mgmt.internal` from `mgmt grafana pod`
Worked out of box, no modification required.

Scenario 2: 
To access `promethes.dev.internal` from `mgmt grafana pod`
Need to do VPC peering first.
Enable route53 VPC association to associate `mgmt vpc` with `dev's hosted zone`.
Worked out of box, no modification required.

Am I missing something basic here? 
I was thinking it would be cool if the plugin syncs records from coredns to route53 too, then it make sense that we wouldn't need unnecessary headless services, unfortunately this plugin is only used for syncing from route53.

**What would you like to be added**:
Some documentation around what scenario its useful for route53 plugin

**Why is this needed**:
To better understand usecases.

**Comment by yongtang** [comment]
@rverma-jm See some related discussions https://github.com/coredns/coredns/pull/3442#issuecomment-591633264

Some thing to note is that, 1) DNS by itself uses UDP for data channel which is different from the normal TCP channel your service will use 2) a plain DNS is not truly secure both for being poisoned and for lack of access management. 3) A local DNS server which serves DNS to local process, while receiving DNS data through secure SSL from remote (e.g., AWS route53 or Google Cloud DNS), is much more secure and reliable.

**Comment by rverma-jm** [comment]
@yongtang thanks for the comments, wondering if you are referencing to this when speaknig about security, https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-configure-dnssec.html. I understand that route53 doesn't support dnssec and advise to forward to another dns server.

In that scenario, shall I assume that its more vital for public hosted zone.
However I am not sure about reliability aspect here.

I am entirely new to this dns attack area, can you please add some blog reference or info comment regarding how a local dns server could be useful. 

Thanks, If you need any contribution, please let me know :)

**Comment by yongtang** [comment]
SSL/TCP is obviously more reliable than UDP which data drop could happen even without notice. On the other hand, DNSSEC is not in place for many systems yet. So ideally, you could place coredns on each node serving DNS/UCP as the frontend, and use HTTPS to route53 for reliable (and more secure) data sync up. In this way, you don't need your program or system to change, all you need to do is to points the dns server entry to `127.0.0.1:53`.

**Comment by mattlqx** [comment]
The simple answer is that all your DNS records may not be located in Route 53. CoreDNS is a useful tool for unifying all your DNS sources-of-truth into one accessible location. For my setup, we have all our public facing records in Route 53, with a split-horizon private domain as well. But we also have subdomain forwarders to Active Directory internal and OpenStack domains and direct hosting of Kubernetes plugin subdomains. In most of these cases, NS record delegation would be enough, but you can take advantage of CoreDNS doing the caching this way and having a single configuration file to deploy to all locations that provides "everything" is also powerful.

**Comment by yongtang** [comment]
> The simple answer is that all your DNS records may not be located in Route 53. 

👍 for this comment. In addition to AWS Route 53, IT domain, OpenStack, Kubernetes, in an enterprise or institution DNS could also comes from Google Cloud (the `clouddns` plugin), and Azure (`azure` plugin).

And with CoreDNS plugin that uses cloud API (through https endpoint, not though direct udp), there is no need to peering every VPC/private subnet in a full mesh to just get the DNS data.

**Comment by yongtang** [comment]
@rverma-jm I think the question has been clarified. Will close the issue but fee free to reopen if you need further information.
