### ISSUE TITLE
[Enhancement Request] Make cache plugin metrics reusable

### ISSUE THREAD

**Issue by beyhan** [coredns/coredns#3847]
**What would you like to be added**:
[Bosh-dns](https://github.com/cloudfoundry/bosh-dns-release) is the dns solution used in the [CloudFoundry project](https://github.com/cloudfoundry). The project reuses the `cache` plugin of CoreDNS and we are also working to [reuse the metrics plugin](https://github.com/cloudfoundry/bosh-dns-release/pull/57), which is very useful. We discovered that the CoreDNS `cache` plugin can also provide metrics for itself. Unfortunately, it is not possible to register the metrics of the `cache` plugin without executing the [plugin setup](https://github.com/coredns/coredns/blob/b8d37d709d87dac82524a1720e0c8c955da362a1/plugin/cache/setup.go#L22-L39). It would be nice to make the registration possible also from outside. One option could be to make the [metric collectors public](https://github.com/coredns/coredns/blob/4ccd55e95e9f54a0078d7dda76a447879c2f15a3/plugin/cache/metrics.go#L9-L51).   

**Why is this needed**:
`bosh-dns` uses the CoreDNS cache plugin and would benefit from the metrics, which this plugin can provide.

**Comment by miekg** [comment]
Hi, I'm glad you find this project useful. We can't commit to making internal changes and
then having a (far away) dependency on them. This is not only fragile, we also don't have
any mechanism in place when such change can be backed out again when not needed.

Your best bet is to locally patch out, or in, any functionality you need.

/plugin cache
/label question
/close
