### ISSUE TITLE
A: dns: short read

### ISSUE THREAD

**Issue by Sc0th** [coredns/coredns#3853]
I have coredns running as internal nameserver with forwarders to a local next-dns agent which performs any external lookups over secure DNS

I am seeing this a fair bit in the coredns logs and am at a loss as to what it means, and what I may have mis-configured, or if I am perhaps hitting a bug.

ERROR] plugin/errors: 2 devs.tplinkcloud.com. A: dns: short read
[ERROR] plugin/errors: 2 devs.tplinkcloud.com. A: dns: short read
[ERROR] plugin/errors: 2 devs.tplinkcloud.com. A: dns: short read
[ERROR] plugin/errors: 2 ssl.gstatic.com. A: dns: short read
[ERROR] plugin/errors: 2 google.com. A: dns: short read
[ERROR] plugin/errors: 2 google.com. A: dns: short read

is a relatively common output.

Head of Corefile:

(shared) {
    errors
    reload 30s
    cache
}

.:53 {
    forward . 192.168.60.37:3053 192.168.60.15:3053 {
      policy sequential
    }
    import shared
}

**Comment by miekg** [comment]
looks like your forwarder is returning garbage.

**Comment by Sc0th** [comment]
Any way I can get further detail as to what core is seeing?

**Comment by miekg** [comment]
tcpdump on port 53

**Comment by Sc0th** [comment]
If anyone else comes across this and needs a slightly more beneficial answer, I have found that setting prefer_udp seems to have resolved the problem

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] A: dns: short..." ]
>If anyone else comes across this and needs a slightly more beneficial answer, I
>have found that setting prerfer_udp seems to have resolved the problem

ok, def. odd and points to something severly broken

/close
