### ISSUE TITLE
How to add cname to coredns

### ISSUE THREAD

**Issue by NadamHL** [coredns/coredns#3865]
How to add cname to coredns

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] How to add cname ..." ]
>How to add cname to coredns

/label needs info
/label question

**Comment by NadamHL** [comment]
I hope to use the cname function in coredns to resolve the internally-named domain name to the public domain name, how to achieve it?

**Comment by chrisohaver** [comment]
Still not really clear what you want to do... a simple example would go a long way.

Nevertheless, you may be able to use the _template_ plugin to do what you want.
The _template_ plugin can create a CNAME based on the incoming request.

**Comment by zouyee** [comment]
https://github.com/coredns/coredns/blob/master/plugin/hosts/README.md

**Comment by chrisohaver** [comment]
@zouyee, The hosts plugin doesn't support creating CNAMEs.

@NadamHL, I am closing this. Please feel free to reopen if you have time to better describe what you want to do and why you want to do it with examples.
