### ISSUE TITLE
Looking to use variable in rewrite name and answer name 

### ISSUE THREAD

**Issue by antojobai** [coredns/coredns#3867]
**What would you like to be added**:

Looking to see if I can use the variable like {qname} in rewrite name and answer name options 

Looking to use the rewrite like this 
rewrite stop name regex (.*)\. {1} answer name (.*)\. {qname}

**Why is this needed**:

This rewrite will allow me to return the CNAME answers with the original name in the answer sections.

I already tried the alias plugin, alias works only in the authoritative zone, not for recursive answers

**Comment by chrisohaver** [comment]
the _template_ plugin may be able to do what you want.

**Comment by antojobai** [comment]
Thank you, Chris! for the quick response. Looks like the template may work. I will give that a try.

**Comment by antojobai** [comment]
It looks like the Template plugin in not parsing the response. I'm not able to print the Rdata field 

    template ANY ANY {
      match (.*)\.
      answer "{{ .Name }} 60 IN A {{ .Rdata }}"
      fallthrough
    }

[ERROR] plugin/errors: 2 www.example.com. A: template: answer:1:23: executing "answer" at <.Data>: can't evaluate field Data in type *template.templateData

**Comment by chrisohaver** [comment]
~Describe what you want to do, and~ _Give an example_ of a query and how you want coredns to answer.

**Comment by chrisohaver** [comment]
From your attempt at using template.  It looks like maybe you are trying to collapse CNAME + A responses down to a single A record before sending to the client?  Though, that doesn't seem to line up with your original description. No internal plugins can do that ...  but you can write your own plugin that does.

If that is what you are trying to do, I'm curious what your use case is.

**Comment by antojobai** [comment]
Yes, Chris. You are correct in guessing the requirement. I'm sorry for not explaining that in the beginning. I'm looking to flaten the name in response for both authoritative and recursive queries. I want that to happen for both the name in apex of the zone or else where in the zone. 

Looking for something similar to this functionality mentioned in the below post
https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Looking to us..." ]
>Yes, Chris. You are correct in guessing the requirement. I'm sorry for not
>explaining that in the beginning. I'm looking to flaten the name in response
>for both authoritative and recursive queries. I want that to happen for both
>the name in apex of the zone or else where in the zone.
>
>Looking for something similar to this functionality mentioned in the below post
>https://blog.cloudflare.com/
>introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/

https://coredns.io/explugins/alias/ does that.

Note: external plugin so I can't vouch if it still works/compiles etc.

/Miek

--
Miek Gieben

**Comment by antojobai** [comment]
Thank you, Miek. I tried alias plugin it works only for the CNAME in the apex of the domain and that works for authoritative local DNS zones, not for the recursive queries.

**Comment by chrisohaver** [comment]
I'm still interested in knowing why you need this. You have described what you want to do, but not why you need to do it.  Do you have clients that are confused by or cannot handle CNAME responses?

**Comment by antojobai** [comment]
"Per DNS specifications (RFCs), a domain cannot have a CNAME record and another DNS record of a different type if both records would share the same name. DNS RFCs also require an MX record to correspond to a related A record and not a CNAME. This is problematic when you need a CNAME for your root (for example, a CNAME from example.com to example.herokuapp.com) but also need another type of DNS record at the root domain such as an MX record for mail delivery.

Typically, the aforementioned situation would cause problems receiving email. However, CNAME Flattening ensures the chain of CNAMEs is followed to an A or AAAA record to allow mail delivery while still adhering to DNS RFCs. The CNAME responses are cached and DNS TTLs are respected."

**Comment by chrisohaver** [comment]
@antojobai, that example justifies the need for CNAME fattening at the root, which is what _alias_ already allows.

**Comment by chrisohaver** [comment]
Ah - Do you need this to work for forwarded zones?

**Comment by chrisohaver** [comment]
@antojobai, if you are looking to have the functionality of the _alias_ plugin expanded or fixed in some way, I suggest opening an issue with the maintainers of that plugin https://github.com/serverwentdown/alias.

**Comment by antojobai** [comment]
I will open a request with the alias. Thank you.
