### ISSUE TITLE
kubernetes/client-pod-name and kubernetes/namespace metadata values will not log

### ISSUE THREAD

**Issue by aaronbbrown** [coredns/coredns#3868]
**What happened**:

I attempted to log the metadata labels `/kubernetes/client-namespace` and `/kubernetes/client-pod-name` using a combination of the `log`, `metadata`, and `kubernetes` plugins and the client-namespace and client-pod-name are always `-` in the logs, e.g.:

```
[INFO] A IN kubernetes.default.svc.dev.local. - -
```

**What you expected to happen**:

I expected the value of the pod name and namespace to be output to the logs.

**How to reproduce it (as minimally and precisely as possible)**:

I configured coredns with the following `Corefile`:
```
    .:53 {
        metadata .
        log . "{type} {class} {name} {/kubernetes/client-namespace} {/kubernetes/client-pod-name}"
        errors
        ready
        health
        kubernetes dev.local in-addr.arpa ip6.arpa {
          pods verified
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

Otherwise, it's a vanilla installation of coredns, nearly identical to the manifest in the repo.

I then started an interactive pod and used `dig` to make queries against coredns:
```
$ kubectl run --rm -it --image=tutum/dnsutils  -- bash
root@bash-64cb67db8c-ph6bt:/# dig +short google.com
172.217.13.142
root@bash-64cb67db8c-ph6bt:/# dig +short +tcp kubernetes.default.svc.dev.local
10.125.128.1
root@bash-64cb67db8c-ph6bt:/# dig +short  kubernetes.default.svc.dev.local
10.125.128.1
```

The following output was in my logs:
```
[INFO] A IN kubernetes.default.svc.dev.local. - -
[INFO] A IN google.com. - - -
[INFO] A IN kubernetes.default.svc.dev.local. - -
```

If I add `{/kubernetes/namespace}` to the `log` line, that will correctly show `default` as the namespace. My assumption is that [this check](https://github.com/coredns/coredns/blob/c9d567ab4423d391e5b3bef874185c324b6ed2ed/plugin/kubernetes/metadata.go#L47-L50) is failing, but it leans on a lot of libraries and I haven't been able to debug that.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.6.9
- Corefile:
```
    .:53 {
        metadata .
        log . "{type} {class} {name} {/kubernetes/client-namespace} {/kubernetes/client-pod-name}"
        errors
        ready
        health
        kubernetes dev.local in-addr.arpa ip6.arpa {
          pods verified
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

- logs, if applicable: 
- OS (e.g: `cat /etc/os-release`): Ubuntu 19.10
- Others:

**Comment by chrisohaver** [comment]
This works for me at 1.6.9 ...

```
kubectl run -it --rm --restart=Never --image=infoblox/dnstools:latest dnstools
dnstools# dig +short kubernetes.default.svc.dev.local.
10.96.0.1
```

```
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
...
[INFO] A IN kubernetes.default.svc.dev.local. default dnstools
```

@aaronbbrown, Can you look up the Pod IP-styled dns name of the client pod?  With pods verified on, this _should_ return a record... e.g. if your client pod ip is 1.2.3.4, and its in default, does `dig 1-2-3-4.default.pod.dev.local` return a record?

**Comment by aaronbbrown** [comment]
@chrisohaver thanks for the quick response!

I do get the correct IP back, but the logs do not have the client namespace or pod:
```
root@bash:/# dig +short 10-125-73-130.kube-system.pod.dev.local
10.125.73.130
```

```
[INFO] A IN 10-125-73-130.kube-system.pod.dev.local. - -
[INFO] A IN 10-125-73-130.kube-system.pod.dev.local. - -
```

**Comment by chrisohaver** [comment]
@aaronbbrown, Can you sanity check that an IP that does not belong to a Pod returns nothing? e.g. `dig +short 8-8-8-8.kube-system.pod.dev.local.` should not return 8.8.8.8 (although it would if `pods insecure`)

**Comment by aaronbbrown** [comment]
An invalid pod-ip-style domain correctly returns NXDOMAIN

```
root@bash:/# dig 1-2-3-4.default.pod.dev.local

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> 1-2-3-4.default.pod.dev.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 41353
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;1-2-3-4.default.pod.dev.local.	IN	A

;; AUTHORITY SECTION:
dev.local.		30	IN	SOA	ns.dns.dev.local. hostmaster.dev.local. 1588359452 7200 1800 86400 30

;; Query time: 2 msec
;; SERVER: 10.125.128.10#53(10.125.128.10)
;; WHEN: Fri May 01 18:57:56 UTC 2020
;; MSG SIZE  rcvd: 139
```

**Comment by chrisohaver** [comment]
> An invalid pod-ip-style domain correctly returns NXDOMAIN 

Bizarre ... the only explanation I can fathom atm, is that there are two Pods being returned by the index with that IP, _and_ the first one returned doesn't have a namespace or pod name.  In the dashed-ip pod query, each result is checked for a matching namespace, and ip (which seems redundant if we trust the index).  So if the first entry is some sort of "empty" pod entry, the dashed-ip pod query would work, but the metadata check would not.

**Comment by chrisohaver** [comment]
> the only explanation I can fathom atm ... two Pods being returned by the index with that IP

If thats whats happening, it could also be the root cause of the intermittent autopath failures reported (#3765, and i think on slack too iirc), which rely on the same function.

**Comment by chrisohaver** [comment]
Actually - looking at the way the metadata replacer works, since we are seeing dashes in the log instead of nothing,  it means that the metadata functions themselves are nil - not that they are returning empty values for name and namespace.
... which means that the pod is coming back nil from `podWithIP()`, which can only happen if there are 0 pods in the index for that IP, or if the index is actually returning a nil pointer.
... but if the index was actually returning nil pointers in the list, then dashed-ip pod queries would cause a panic when they are encountered (and they work, as demonstrated above).  

So it must be that the index returns nothing... which is contradictory, because dashed-ip pod queries work, which use the same index.

**Comment by chrisohaver** [comment]
@aaronbbrown, can you add `{remote}` to the log format, to verify the IP CoreDNS sees is the same IP address?

oh...

Do you have "node local cache" deployed in your cluster by any chance?  Node local cache is inherently incompatible with the client pod metadata because it's a middle man between Pods and the cluster DNS, obfuscating the client ip.

**Comment by aaronbbrown** [comment]
@chrisohaver  🎉 Adding `{remote}` was a great clue! I found that the remote IP was the calico `tunl` interface, which was happening because we have `kube-proxy --masquerade-all` on.  Without `--masquerade-all`, queries that hit the cluster domain show the pod name and namespace. It seems external queries still don't have that metadata, but the remote IP _is correct_:

```
$ kubectl run -it --rm --generator=run-pod/v1 --image tutum/dnsutils dig --restart=Never -- sh -c "sleep 10; dig +short google.com; dig +short kubernetes.default.svc.dev.local; dig +search +short kubernetes"
172.217.10.110
10.125.128.1
10.125.128.1
pod "dig" deleted

$ kubectl logs -n kube-system -l k8s-app=kube-dns
[INFO] A IN google.com. 10.125.73.172 - -
[INFO] A IN kubernetes.default.svc.dev.local. 10.125.73.172 default dig
[INFO] A IN kubernetes.default.svc.dev.local. 10.125.73.172 default dig
```

Given that I'm trying to identify use of in-cluster service discovery, this is actually enough to solve my current problem, though it would be nice to figure out why non-cluster domain lookups are without metadata.  Does the `forward` rule bypass the kubernetes `metadata`?

Thanks for your help on this!

**Comment by chrisohaver** [comment]
Cool.

> ... it would be nice to figure out why non-cluster domain lookups are without metadata. Does the forward rule bypass the kubernetes metadata?

As the kubernetes metadata function is written, all of the the kubernetes metadata is skipped when the domain of the search is not in cluster.
None of the other metadata fields have any meaning in this context, because they are based on the queried service. The client pod fields however could be populated. I'll propose a fix.
