### ISSUE TITLE
k8s_external plugin doesn't work with AWS ELB/NLB

### ISSUE THREAD

**Issue by networkop** [coredns/coredns#3878]
When running a Kubernetes cluster on AWS (with AWS cloud provider) k8s_external plugin returns an empty response with just AUTHORITY SECTION included.

**What happened**:
I deployed a `k8s_external` plugin on an AWS-based k8s cluster, queried an external domain and got the following response:

```
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 581
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;my-svc.default.foo.com. IN	A

;; AUTHORITY SECTION:
foo.com.	5	IN	SOA	ns1.dns.foo.com. hostmaster.dns.foo.com. 12345 7200 1800 86400 5
```

This happens because the AWS ELB assigns a DNS alias instead of just an IP address. 

In order to differentiate between AWS and other clouds, the loadbalancer's status field looks different:

```
status:
  loadBalancer:
    ingress:
    - hostname: uuid.eu-west-2.elb.amazonaws.com
```

Compared to, for example, GKE:

```
status:
  loadBalancer:
    ingress:
    - ip: 35.123.9.321

```

**What you expected to happen**: 
I was expecting that `k8s_external` would return a CNAME that points to the `uuid.eu-west-2.elb.amazonaws.com`, e.g.

```
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57815
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 1b5b8301e38cd740 (echoed)
;; QUESTION SECTION:
;my-svc.default.foo.com. IN A

;; ANSWER SECTION:
my-svc.default.foo.com. 30 IN CNAME uuid.eu-west-2.elb.amazonaws.com.
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an EKS cluster
2. Create a service type:Loadbalancer
3. Add the following to Corefile's default zone `k8s_external foo.com`
4. Query the domain `service.namespace.foo.com`

**Anything else we need to know?**:
I was able to relatively easy patch the `kubernetes` and `k8s_external` plugins to return a CNAME in this case. I was wondering if it's something you may consider for a PR, since I'm not sure if this has been considered and dismissed before.

```
--- a/plugin/k8s_external/msg_to_dns.go
+++ b/plugin/k8s_external/msg_to_dns.go
@@ -18,7 +18,8 @@ func (e *External) a(services []msg.Service, state request.Request) (records []d
 
                switch what {
                case dns.TypeCNAME:
-                       // can't happen
+                       rr := s.NewCNAME(state.QName(), s.Host)
+                       records = append(records, rr)
 
                case dns.TypeA:
                        if _, ok := dup[s.Host]; !ok {
diff --git a/plugin/kubernetes/object/service.go b/plugin/kubernetes/object/service.go
index 295715e2..0fdbc2bf 100644
--- a/plugin/kubernetes/object/service.go
+++ b/plugin/kubernetes/object/service.go
@@ -62,6 +62,7 @@ func toService(skipCleanup bool, obj interface{}) interface{} {
        li := copy(s.ExternalIPs, svc.Spec.ExternalIPs)
        for i, lb := range svc.Status.LoadBalancer.Ingress {
                s.ExternalIPs[li+i] = lb.IP
+               s.ExternalIPs[li+i] = lb.Hostname
        }
```

**Environment**:

- the version of CoreDNS: docker.io/coredns/coredns:1.6.9
- Corefile:
```
.:53 {
    errors
    log
    health {
        lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    }
    prometheus 0.0.0.0:9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
    k8s_external foo.com
```

**Comment by chrisohaver** [comment]
Thanks for the thorough report.  IMO, The fix seems to be on the right track.

**Comment by chrisohaver** [comment]
... it should also add the A record for the CNAME target to the answer, similiarly to how other plugins do it, using `upstream.Upstream` to resolve the name.

**Comment by chrisohaver** [comment]
... also, per RFC ... "A CNAME-record cannot exist with any other records for the same name"

IOW, we cannot response with a `CNAME` for the host _and_ an `A` for the IP under the same name...

So we may need to ignore the IP field if a hostname field is populated.
... or add the A record with CNAME target name, along with the Records received via `upstream.Upstream`.

**Comment by chrisohaver** [comment]
... and A/AAAA should be supported.

**Comment by networkop** [comment]
I'm not sure if this is suboptimal, but the way it works for me is my local DNS resolver (e.g. 1.1.1.1) gets a CNAME and then goes and collects the remaining A records, so the final response I get looks like:
```
;; ANSWER SECTION:
service.namespace.foo.com. 10 IN CNAME uuid.eu-west-2.elb.amazonaws.com.
uuid.eu-west-2.elb.amazonaws.com. 40 IN A 35.1.1.1
uuid.eu-west-2.elb.amazonaws.com. 40 IN A 3.2.2.2
```
This way there's less work for CoreDNS to do, because the query most of the time comes from the outside of the cluster.

**Comment by chrisohaver** [comment]
The CNAME targets could be in stub zones, in which case every client would need to know where to direct queries for those stub zones.  In that case it's better to have CoreDNS look them up.

I think in general if a DNS server _can_ add the A record to the response, it should.

... in the RFC: https://tools.ietf.org/html/rfc1034 3.6.2. Aliases and canonical names

**Comment by networkop** [comment]
so, if I understood everything correctly, I also need to:
1. Make k8s_external resolve CNAME and add the necessary A records
2. If CNAME + resolved A records was added, make sure we don't add any more A records for the same `service.Key`

**Comment by chrisohaver** [comment]
1. yes
2. if the load balancer definition in Kubernetes has both a hostname and an IP included, add the IP to the answer if that IP was not already added by step 1.

**Comment by chrisohaver** [comment]
An example:

load balancer section for service `foo.default`
```
status:
  loadBalancer:
    ingress:
    - ip: 1.2.3.4
    - hostname: lb.example
```

initial answer would be:
`CNAME`  foo.default.zone. -> lb.example.

Then the following are added to the answer...
`A` lb.example. -> 1.2.3.4 (added by lookup upstream if it can)
`A` lb.example. -> 1.2.3.4 (added based on the ip in the service def if not already added by upstream lookup)

**Comment by chrisohaver** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#loadbalanceringress-v1-core

The API docs don't strictly say that only ONE of ip or hostname will be populated... but it kinda-sorta implies it.  So perhaps we can safely assume that, and thus simply prefer one, ignoring the other (e.g. if both hostname and ip are there, use the ip, and ignore the hostname).

**Comment by networkop** [comment]
it should be fairly easy to use `dup := make(map[string]struct{})` for that, since it's already checking for duplicate entries.

**Comment by networkop** [comment]
Here's how I've managed to get it done (A record example). Does that look alright?

```
@@ -18,7 +19,14 @@ func (e *External) a(services []msg.Service, state request.Request) 
  switch what {
  case dns.TypeCNAME:
-    // can't happen
+    if resp, err := e.upstream.Lookup(ctx, state, dns.Fqdn(s.Host), dns.TypeA); err == nil {
+      for _, rr := range resp.Answer {
+         if ip, ok := rr.(*dns.A); ok {
+            dup[ip.A.String()] = struct{}{}
+            records = append(records, rr)
+         }
+      }
+    }
```

**Comment by chrisohaver** [comment]
There is no need to look for duplicates in results of `e.upstream.Lookup`.

The mention of duplicate checking above was in the context of adding the IP from the k8s API to the results - which we can safely ignore IMO.

**Comment by networkop** [comment]
right, got it. so am I ok to open a PR for this?

**Comment by chrisohaver** [comment]
> right, got it. so am I ok to open a PR for this?

Yes.
