### ISSUE TITLE
middleware/auto panics on unknown zone

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#388]
When a zone is requested, that is not loaded by auto it leads to a panic:
```07/Nov/2016:09:59:18 +0000 [PANIC unknown-domain.example.com A] middleware/auto/auto.go:66 - runtime error: invalid memory address or nil pointer dereference```

Proxy directive needs to be unused.

**Comment by miekg** [comment]
What is your config for this?

**Comment by stp-ip** [comment]
This panics:

```
    .:5053 {
      auto {
        directory /etc/source/files/zones/ (.*) {1}
      }
      cache 300
      health :8081
      errors stdout
      log stdout
    }
```

This config gives back the domain or NXDOMAIN:

```
    .:5053 {
      proxy . 8.8.8.8:53
      auto {
        directory /etc/source/files/zones/ (.*) {1}
      }
      cache 300
      health :8081
      errors stdout
      log stdout
    }
```

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> This panics:
> 
> ```
>    .:5053 {
>      auto {
>        directory /etc/source/files/zones/ (.*) {1}
>      }
>      cache 300
>      health :8081
>      errors stdout
>      log stdout
>    }
> ```
> 
> This config gives back the domain or NXDOMAIN:
> 
> ```
>    .:5053 {
>      proxy . 8.8.8.8:53
>      auto {
>        directory /etc/source/files/zones/ (.*) {1}
>      }
>      cache 300
>      health :8081
>      errors stdout
>      log stdout
>    }
> ```

Thanks, got a repro (and test and fix)

**Comment by stp-ip** [comment]
Np thanks for the fast fixes.
