### ISSUE TITLE
plugin/file: the DNSSEC plugin and CNAMEs don't work well together

### ISSUE THREAD

**Issue by Isolus** [coredns/coredns#3891]
**What happened**:

A CNAME e. g. `testcname.example.org` to another zone e. g. `subdomain.example.net` was created via the file plugin. Additionally both zones are signed (the zone containing the CNAME is signed via the DNSSEC plugin).

If I try to resolve the A record of `testcname.example.org`, the CNAME resource record and the correct A record are returned. But the answer contains only signatures signed by example.org for both entries.

An answer looks like this:

```
;; ANSWER SECTION:
testcname.example.org.	3600	IN	CNAME	subdomain.example.net.
subdomain.example.net.	300 	IN	A	1.2.3.5
testcname.example.org.	3600	IN	RRSIG	CNAME 13 3 3600 20200522063116 20200514033116 58517 example.org. h2...=
subdomain.example.net.	300 	IN	RRSIG	A 13 3 3600 20200522063116 20200514033116 58517 example.org. Rb...=
```

**What you expected to happen**:

The answer should contain the original signature from `subdomain.example.net` or resolvers complain about an invalid signature. (At least dnsmasq as validating resolver does this.)

It should contain the additonal entry:
```
subdomain.example.net.	300 	IN	RRSIG	A 13 3 3600 20200522063116 20200514033116 58517 example.net. Rb...=
```

**Anything else we need to know?**:

Adding `req.SetEdns0(512, true)` to `Lookup` in `pkg/upstream/upstream.go` resolves this issue. 

But two questions prevent me from creating a pull request:
* I am not sure if it has any side effects. Especially since `Lookup` is used by several plugins.
* Furthermore I can't find anything in the standard if the addtional signature of the zone with the CNAME is necessary, superfluous or undesired for the entry from the other zone.

**Environment**:

- the version of CoreDNS: 1.6.9 and master

**Comment by Isolus** [comment]
I found the answer to my second question (at least in practice): The additional signature must not be there. Only one signature is verified and if the wrong one comes first, the validation fails.

Which brings me to a new problem. The resource records are first collected and then signed. When signing, the information whether the record comes from another zone or not is missing.

My naive approach is not to re-sign a record if a RRSIG record already exists. But this fails if the target zone is not signed.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/file: ..." ]
>I found the answer to my second question (at least in practice): The additional
>signature must not be there. Only one signature is verified and if the wrong
>one comes first, the validation fails.
>
>Which brings me to a new problem. The resource records are first collected and
>then signed. When signing, the information whether the record comes from
>another zone or not is missing.
>
>My naive approach is not to re-sign a record if a RRSIG record already exists.
>But this fails if the target zone is not signed.

yep, this is a bug and should be fixed, not completely trivial to do so, but yes.

/plugin dnssec
/label bug

**Comment by miekg** [comment]
I think this is doing what you propose but not unconditionally:
~~~
diff --git plugin/pkg/upstream/upstream.go plugin/pkg/upstream/upstream.go
index 894488ff..eacb9b4d 100644
--- plugin/pkg/upstream/upstream.go
+++ plugin/pkg/upstream/upstream.go
@@ -25,8 +25,11 @@ func (u *Upstream) Lookup(ctx context.Context, state request.Request, name strin
                return nil, fmt.Errorf("no full server is running")
        }
 
+       size := state.Size()
+       do := state.Do()
        req := new(dns.Msg)
        req.SetQuestion(name, typ)
+       req.SetEdns0(uint16(size), do)
 
        nw := nonwriter.New(state.W)
~~~
this requires the requesting plugin to do the right thing as well though...

**Comment by miekg** [comment]
See https://github.com/coredns/coredns/pull/4055
does that work in your case (might need some *file* changes as well)

**Comment by miekg** [comment]
I believe #4055 should fix this.

**Comment by Isolus** [comment]
I apologise for my late reply. Due to the birth of my daughter I took a break from almost everything.

The solution only solves part of the problem. Now the missing RRSIG record is there. But the A record for `subdomain.example.net.` from the example is still signed again with the key from `example.org.` which causes a validation failure in my validating resolver.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/file: ..." ]
>I apologise for my late reply. Due to the birth of my daughter I took a break
>from almost everything.

understood and congratulations :-)

>The solution only solves part of the problem. Now the missing RRSIG record is
>there. But the A record for subdomain.example.net. from the example is still
>signed again with the key from example.org. which causes a validation failure
>in my validating resolver.

figured that it needed more of a fix - thanks for double checking.

/Miek

--
Miek Gieben
