### ISSUE TITLE
plugin/log: logfile does not output time information

### ISSUE THREAD

**Issue by Futurefangyuan** [coredns/coredns#3892]
I would like to add a date for printing the log file

- the version of CoreDNS:1.6.4
- Corefile:
. {
  hosts {
    fallthrough
  }

  forward . 10.1.249.200 10.100.100.100 {
    #force_tcp
    max_fails 3
    expire 5s
    health_check 5s
    policy sequential
  }

  cache 10
  reload 30s
  log
  errors
}

- Current log format:
[INFO] 127.0.0.1:7090 - 43392 "A IN www.google.com. udp 42 false 4096" NOERROR qr,rd,ra 149 0.001478317s

- My expected log format:
[INFO]  18-Mar-2020 14:54:17.047 127.0.0.1:7090 - 43392 "A IN www.google.com. udp 42 false 4096" NOERROR qr,rd,ra 149 0.001478317s

  or

  [INFO]  2020-05-18 16:30:18:753462147 127.0.0.1:7090 - 43392 "A IN www.google.com. udp 42 false 4096" NOERROR qr,rd,ra 149 0.001478317s
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by miekg** [comment]
By design. Log capture services like journald add it as well.

/close
/plugin log
