### ISSUE TITLE
kubernetes internal parsing always shows that parsing failed, coredns used by internal dns

### ISSUE THREAD

**Issue by NadamHL** [coredns/coredns#3898]
kubernetes internal parsing always shows that parsing failed, coredns used by internal dns

coredns version: 1.3.1
Add A record to the coredns configmap:

apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        hosts {
            172.16.11.11 www.zqliu.com
            fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap

**Comment by chrisohaver** [comment]
Please provide more information when re-opening.
