### ISSUE TITLE
How do coredns print debug logs

### ISSUE THREAD

**Issue by NadamHL** [coredns/coredns#3899]
Coredns how to print debug log, the current coredns log volume is too small to assist in troubleshooting the problem, now encountered kubernetes internal request for domain name resolution, often timeout phenomenon.
(k8s USES coredns as kube-dns)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] How do coredns pr..." ]
>Coredns how to print debug log, the current coredns log volume is too small to
>assist in troubleshooting the problem, now encountered kubernetes internal
>request for domain name resolution, often timeout phenomenon.
>(k8s USES coredns as kube-dns)

load *debug* plugin, but note note (almost none) plugins utilize this yet.

/close
/plugin debug
