### ISSUE TITLE
middleware/kubernetes: Federation Support

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#390]
Clarification on internal, external and hybrid records.

1. regional cluster internal
    * local to the cluster
    * return internal IPs
2. regional cluster external
    * local to the cluster
    * return external IPs
    * should this be done via federation DNS?
3. global cluster mixed
    * federated cluster
    * return internal and external IPs depending on locality see [federation dns](http://kubernetes.io/docs/user-guide/federation/federated-services/#discovering-a-federated-service)
    * proxy to the regional cluster DNS?
4. global cluster external
    * federated cluster
    * return external IPs for all services

Clarify what the current feature set is, what the planned feature set is and how that interacts with the current features available within federated clusters.

CoreDNS could already replace 1. aka skydns.
Should CoreDNS even try to do 2.? Or just fall back to 4.
Can or should CoreDNS replace 3. aka the logic behind the federated DNS stuff.
Is it or will it be possible to let the CoreDNS instance running within the federation control cluster be used as external primary DNS aka 4.?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] middleware/kubernet..." ]

> CoreDNS could already replace 1. aka skydns.

Right now: this. And IIRC kube-dns is skydns + a few other bits. CoreDNS should
be able to take that roll as well.

/Miek

## 

Miek Gieben

**Comment by johnbelamaric** [comment]
There is no federation or external IP support yet, but it is definitely a goal.

Right now, it service A records with the ClusterIP of the services. I will be publishing a blog today or tomorrow on this middleware.

**Comment by stp-ip** [comment]
My intention was basically to add more clarification on what is possible and what might be possible. Always stirring around the possibilities.
Would love to get more insights within the blog post.

**Comment by johnbelamaric** [comment]
Blog post is mostly around just how to deploy it in K8s as the service discovery. But definitely want to discuss possibilities!

**Comment by miekg** [comment]
Is there anything that needs to be done here? Do we have something we can publish?

**Comment by johnbelamaric** [comment]
@stp-ip I think the right place for the discussion of 3 and 4 is https://github.com/kubernetes/dns/issues/29 which is intended to expand the (now standard) DNS spec in K8s to handle federation in a well-defined manner.

For 2 this is relevant: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/2wGQUB0fUuE/9OXz01i2BgAJ

We could create a separate zone for 2 and serve them directly from the same server that is doing the cluster DNS.

**Comment by johnbelamaric** [comment]
Chris is working on supporting the existing federation records. We also are considering implementing a totally new way to do federated DNS. Would love comments for this proposal: https://docs.google.com/document/d/1tvDE7oTAOKEPQr2HQDgCZQFDoVCoiy_ICQmvUIy6h5Y/edit?usp=sharing

This is separate from https://github.com/kubernetes/dns/issues/29 which I think also needs to be addressed.
