### ISSUE TITLE
I want to disable ipv6 parsing

### ISSUE THREAD

**Issue by NadamHL** [coredns/coredns#3904]
I want to disable ipv6 parsing。
Ipv6 resolution requests are configured in coredns to directly reply to NXDOMAIN，However, it did not achieve the desired effect, and ipv6 has taken a long time to resolve

my config：

Corefile: |
  .:53 {
      errors
      health
      template ANY AAAA . {
          rcode NXDOMAIN
          fallthrough
      }
      hosts {
          172.16.17.12 www.zqliu.com
          fallthrough
      }
      kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
      }
    }

coredns version：
     1.3.1

kubernetes version：
    # kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-06T07:09:54Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-06T07:09:54Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by NadamHL** [comment]
![image](https://user-images.githubusercontent.com/39847290/82620586-733a5f00-9c0b-11ea-9f22-1f9def814557.png)

This picture is a screenshot of my grab packet, a udp request.
It took 55s to finish

**Comment by miekg** [comment]
this is not a coredns issue

**Comment by midy177** [comment]
you can try to use Configuration eg:
.:53 {
rewrite stop type AAAA A
loadbalance
reload 30s
log . "{remote} {type} {name} {class} {size} {rcode} {duration}"
cache 3600 
    forward . 10.18.0.124 10.19.0.125 10.16.4.245
}

Mainly add：rewrite stop type AAAA A 
This configuration can redirect IPv6 queries to ipv4
