### ISSUE TITLE
Migrating CoreDNS chart from helm/charts to coredns/charts

### ISSUE THREAD

**Issue by mrueg** [coredns/coredns#3905]
Since https://github.com/helm/charts is going to be deprecated in Nov 2020 (https://github.com/helm/charts#deprecation-timeline) I'd like to start an initial discussion if the CoreDNS chart could find a new home here. Together with @Acaleph @andor44 @shashidharatd, I currently maintain the chart in helm/charts.

**What would you like to be added**:
Ideally a CoreDNS helm chart repository in coredns github namespace as in https://github.com/coredns/charts

**Why is this needed**:
Nov 2020, the helm/charts project will end and users of helm will struggle with deploying CoreDNS through helm.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Migrating CoreDNS..." ]
>Since https://github.com/helm/charts is going to be deprecated in Nov 2020 (
>https://github.com/helm/charts#deprecation-timeline) I'd like to start an
>initial discussion if the CoreDNS chart could find a new home here. Together
>with @acaleph @andor44 @shashidharatd, I currently maintaining the chart in
>helm/charts.
>
>What would you like to be added:
>Ideally a CoreDNS helm chart repository in coredns github namespace as in
>https://github.com/coredns/charts
>
>Why is this needed:
>Nov 2020, the helm/charts project will end and users of helm will struggle with
>deploying CoreDNS through helm.

Thanks for working on this. All 'deployment' type stuff for CoreDNS is contained
in github.com/coredns/deployment where a 'charts' subdir can be created.

/Miek

--
Miek Gieben

**Comment by stuartpb** [comment]
Are the files on https://github.com/coredns/deployment hosted/mirrored somewhere over HTTP(S)? One of the big things a Helm chart needs is a live repository it can be accessed from.

**Comment by yongtang** [comment]
@stuartpb Depending on how helm chart download, but the GitHub itself is https I think?

**Comment by stuartpb** [comment]
Why was this closed? I don't see any sign that the chart's been migrated.
