### ISSUE TITLE
middleware/auto NOTIFY should be done for serving zones only

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#391]
Currently with the auto middleware all zones are loaded within the specified directory and a NOTIFY is sent for every zone loaded. Does this make sense to notify even on zones it doesn't serve?

It might make more sense to only NOTIFY on zones loaded and served.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] middleware/auto NOT..." ]

> Currently with the auto middleware all zones are loaded within the specified directory and a NOTIFY is sent for every zone loaded. Does this make sense to notify even on zones it doesn't serve?

meaning it loads a zone, but the Corefile is specified in such a way that it
will never query the zone that was just loaded?

Indeed that is not possible (right now) - I think we have the zone defs at the
moment we load - so it should not be too hard to suppress the notify or load the
zone at all.

In general though, I kinda like this simplistic behavior; load zone -> notify,
don't care if I actually get queries.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
> meaning it loads a zone, but the Corefile is specified in such a way that it will never query the zone that was just loaded?

Yes exactly.

> Indeed that is not possible (right now) - I think we have the zone defs at the moment we load - so it should not be too hard to suppress the notify or load the zone at all.
> In general though, I kinda like this simplistic behavior; load zone -> notify, don't care if I actually get queries.

The issue is that loading something without actual will to serve it might still confuse a configured secondary server.
It's more to prevent people from doing harm to themselves then it is something essential.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> The issue is that loading something without actual will to serve it might still confuse a configured secondary server.
> It's more to prevent people from doing harm to themselves then it is something essential.

intesting... if a notify comes in from a "strange" IP is should be dropped.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
Should ;)

Just something that reduces issues, reduces load and might not add too much complexity.

Would say not a bug, but an enhancement.

**Comment by miekg** [comment]
This is WAI.
