### ISSUE TITLE
forward support DoH? How should I configure it?

### ISSUE THREAD

**Issue by snakwu** [coredns/coredns#3915]
forward support DoH? How should I configure it?

**Comment by nicki-krizek** [comment]
Tried this as well, the only DoH example I found (in README) is very lacking and I wasn't able to set it up. How do I specify the certificate? What's the URL endpoint - is it just `/`, `/dns-query` or something else? What TLS version are supported? (I got `SSL routines:ssl3_get_record:wrong version number` error when trying with curl)

**Comment by chrisohaver** [comment]
> forward support DoH?

No. The forward plugin supports DNS and TLS (DoT).
