### ISSUE TITLE
Ldap Plugin

### ISSUE THREAD

**Issue by blaggacao** [coredns/coredns#3917]
**What would you like to be added**:
- Add plugin to resolve A, AAAA y PTR RR from ldap backend
- Cache it, configured via corefile

**Why is this needed**:
- LDAP hosts node netgear and iot infrastructure identies
- I don't want to run & manage an additional DNS (outside of the k8s managed stack)

Pseydoexample, no respecting a particular schema conventions:
 ```
Host: node1.cluster1.example.org
IP4: 1.2.3.4
IP6: ...
```

**Comment by zouyee** [comment]
https://coredns.io/2016/12/19/writing-plugins-for-coredns/

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Ldap Plugin (#391..." ]
>What would you like to be added:
>
>  • Add plugin to resolve A, AAAA y PTR RR from ldap backend
>  • Cache it, configured via corefile
>
>Why is this needed:
>
>  • LDAP hosts node netgear and iot infrastructure identies
>  • I don't want to run & manage an additional DNS (outside of the k8s managed
>    stack)
>
>Pseydoexample, no respecting a particular schema conventions:
>
>Host: node1.cluster1.example.org
>IP4: 1.2.3.4
>IP6: ...

that;s an interesting idea. But the schema is probably the hard part.

**Comment by blaggacao** [comment]
I'd probably stick with [Æ-DIR](https://www.ae-dir.com/docs.html#schema-oc-aeNwDevice)'s Schema...

**Comment by blaggacao** [comment]
Starting something here: https://github.com/xoe-labs/coredns-ldap
Please give design feedback here, since I'd aim for it to eventually be included into coredns.

**Comment by blaggacao** [comment]
I think I should just throw over the idea of caching and make it a dynamic backend implemnting the ServiceBackend, just as etcd or kubernetes.

My line of thinking is that ldap is usually deployed locally and does something similar as said tools, just for classic workstation machines and similar things.

Those are relatively static. At the same time they are typically queried infrequently.
This avoiding the hassle of taking caching into account outweighs the benefits of reduced load on ldap server.

Of course this is not true for all cases, but operators can replicate ldap serving it from the same host where coredns runs and therefore more intelligently manage replication concern to their liking.

Is this a terribly bad idea? Should I take more into consideration the possibility of connection problems with an LDAP backend, therefore warranting a fallback cache?

**Comment by johnbelamaric** [comment]
Start without caching. You can always add it if needed. The DNS cache may
be sufficient.

**Comment by blaggacao** [comment]
Good advise, thank! I'm guiding myself line by line by the k8s plugin, assuming it's the most actively maintained and most well-designed.

**Comment by chrisohaver** [comment]
> make it a dynamic backend implementing the ServiceBackend, just as etcd or kubernetes

FWIW,  It's been on my "if I have the time" list to refactor the k8s plugin to not use the ServiceBackend.

**Comment by blaggacao** [comment]
@chrisohaver Oh, why's that? Are there tentative/implicit plans for `ServiceBackend`?

**Comment by chrisohaver** [comment]
> Oh, why's that? 

In my opinion for the _kubernetes_ plugin, it adds complexity in structure and process that really isn't necessary.  

> Are there tentative/implicit plans for ServiceBackend?

Not that I know of.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Ldap Plugin (..." ]
>    Oh, why's that?
>
>In my opinion for the kubernetes plugin, it adds complexity in structure and
>process that really isn't necessary.

this is correct, but mostly this comes from converting to a msg.Service and then to the
wireformat. A generic, and better designed 'backend' plugin helper would be nice, ldap,
consul, kubernetes, and sql could all use this.

**Comment by blaggacao** [comment]
> this is correct, but mostly this comes from converting to a msg.Service and then to the
wireformat. A generic, and better designed 'backend' plugin helper would be nice, ldap,
consul, kubernetes, and sql could all use this.

Absolutely! I made it half way through the code (without counting tests), and I decided to use the "file-api" like azure / route53 plugins do.

My (current) line of thinking still is this:

- host names are extremely static (in a time frame of say 10 min)
- if you do micro-services one probably wouldn't use ldap as backend at all

I'm essentially just [passing a search query which should return hostname, IP pairs](https://github.com/xoe-labs/coredns-ldap/blob/a64423ce00440272aad6a14e5d8b3114edff4487/setup.go#L117-L124) and then, every X seconds, constructs a file per implied zone from it with those entries served by the file plugin.

This minimizes round trips to the ldap servers to 1 per x seconds.

Looking at it this way, probably `ldap` is not a good enough name, as it might allude to too much synchronousness.

**Comment by blaggacao** [comment]
After only a quick search, I couldn't find any standardized attribute for ip6 in the ladp ecosystem, does anybody know more?

**Comment by blaggacao** [comment]
I think I'm getting somewhere. Tests / lints (most) are green.

Therefore, I'd like to share my work and kindly ask for a review.

If there is support or interest, I'd be happy to extract the history and render it a PR to this repo.

If anybody want's to have a quick look, please feel free to head over to: https://github.com/xoe-labs/coredns-ldap/

EDIT: Disregard the Readme, for now, I'll update it tomorrow...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Ldap Plugin (..." ]
>I think I'm getting somewhere. Tests / lints (most) are green.
>
>Therefore, I'd like to share my work and kindly ask for a review.
>
>If there is support or interest, I'd be happy to extract the history and render
>it a PR to this repo.
>
>If anybody want's to have a quick look, please feel free to head over to:
>https://github.com/xoe-labs/coredns-ldap/

before I dive in, get you tell what the data model is?

**Comment by blaggacao** [comment]
```mermaid
stateDiagram
	[*] --> Running
	Running --> Synchronized
	Synchronized --> Outdated
	Outdated --> Synchronized
	Outdated --> [*]
```

[![](https://mermaid.ink/img/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5cdFsqXSAtLT4gUnVubmluZ1xuXHRSdW5uaW5nIC0tPiBTeW5jaHJvbml6ZWRcblx0U3luY2hyb25pemVkIC0tPiBPdXRkYXRlZFxuXHRPdXRkYXRlZCAtLT4gU3luY2hyb25pemVkXG5cdE91dGRhdGVkIC0tPiBbKl1cblx0XHRcdFx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5cdFsqXSAtLT4gUnVubmluZ1xuXHRSdW5uaW5nIC0tPiBTeW5jaHJvbml6ZWRcblx0U3luY2hyb25pemVkIC0tPiBPdXRkYXRlZFxuXHRPdXRkYXRlZCAtLT4gU3luY2hyb25pemVkXG5cdE91dGRhdGVkIC0tPiBbKl1cblx0XHRcdFx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)


`fileZone` -> `file.Zone`
```mermaid
classDiagram
  config --|> ldap
  ldap --|> fileZone
  ldap <|-- ldapRecord
  fileZone : ...
  fileZone: (...)
  class ldapRecord{
    fqdn
    ip4
  }
  class ldap{
    ...
    l.Client.SearchRequest
    ...
    fetch()
    groupByZone()
    update()
  }
  class config{
    ...
    authC
    ...
    syncInterval
    ...
    ldap_url
    base_dn
    filter
    attributes.fqdn
    attributes.ip4
    ...
    parse()
  }				
```
[![](https://mermaid.ink/img/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5cdGNvbmZpZyAtLXw-IGxkYXBcblx0bGRhcCAtLXw-IGZpbGVab25lXG5cdGxkYXAgPHwtLSBsZGFwUmVjb3JkXG5cdGZpbGVab25lIDogLi4uXG5cdGZpbGVab25lOiAoLi4uKVxuXHRjbGFzcyBsZGFwUmVjb3Jke1xuXHRcdGZxZG5cblx0XHRpcDRcblx0fVxuXHRjbGFzcyBsZGFwe1xuICBcdC4uLlxuICAgIGwuQ2xpZW50LlNlYXJjaFJlcXVlc3Rcblx0XHQuLi5cblx0XHRmZXRjaCgpXG5cdFx0Z3JvdXBCeVpvbmUoKVxuXHRcdHVwZGF0ZSgpXG5cdH1cbiAgY2xhc3MgY29uZmlne1xuICAgIC4uLlxuICAgIGF1dGhDXG4gICAgLi4uXG4gICAgc3luY0ludGVydmFsXG4gICAgLi4uXG4gICAgbGRhcF91cmxcbiAgICBiYXNlX2RuXG4gICAgZmlsdGVyXG4gICAgYXR0cmlidXRlcy5mcWRuXG4gICAgYXR0cmlidXRlcy5pcDRcbiAgICAuLi5cbiAgICBwYXJzZSgpXG4gIH1cdFx0IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5cdGNvbmZpZyAtLXw-IGxkYXBcblx0bGRhcCAtLXw-IGZpbGVab25lXG5cdGxkYXAgPHwtLSBsZGFwUmVjb3JkXG5cdGZpbGVab25lIDogLi4uXG5cdGZpbGVab25lOiAoLi4uKVxuXHRjbGFzcyBsZGFwUmVjb3Jke1xuXHRcdGZxZG5cblx0XHRpcDRcblx0fVxuXHRjbGFzcyBsZGFwe1xuICBcdC4uLlxuICAgIGwuQ2xpZW50LlNlYXJjaFJlcXVlc3Rcblx0XHQuLi5cblx0XHRmZXRjaCgpXG5cdFx0Z3JvdXBCeVpvbmUoKVxuXHRcdHVwZGF0ZSgpXG5cdH1cbiAgY2xhc3MgY29uZmlne1xuICAgIC4uLlxuICAgIGF1dGhDXG4gICAgLi4uXG4gICAgc3luY0ludGVydmFsXG4gICAgLi4uXG4gICAgbGRhcF91cmxcbiAgICBiYXNlX2RuXG4gICAgZmlsdGVyXG4gICAgYXR0cmlidXRlcy5mcWRuXG4gICAgYXR0cmlidXRlcy5pcDRcbiAgICAuLi5cbiAgICBwYXJzZSgpXG4gIH1cdFx0IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by miekg** [comment]
we need a generic backend plugin for coredns, not somethign that reinvents the wheel for every protocol.

**Comment by blaggacao** [comment]
Sounds like the right choice.

**Comment by miekg** [comment]
I'm thinking something along the lines of database/sql but then applied to coredns. I should write down what I see as a minimal amount of methods for an interface - but I'm currently constraint in time to give it a proper think

**Comment by blaggacao** [comment]
Maybe @chrisohaver can nudge a little sharing his ideas for the k8s plugin refactor?

**Comment by chrisohaver** [comment]
> mostly this comes from converting to a `msg.Service` and then to the wireformat.

Yeah - I see that as the primary issue as well.

> sharing his ideas for the k8s plugin refactor?

My thoughts here had just been on refactoring k8s plugin not to use the backend,  but not focused on replacing/improving the existing backend (which I think would be a better goal).
