### ISSUE TITLE
IPV6 Support

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#3918]
```
. {
	forward . 8.8.8.8:53 8.8.4.4:53 [2001:4860:4860::8888]:53 [2001:4860:4860::8844]:53
	cache
	errors
	reload
	loop
	log
	health
	dnssec
}
```

The IPV4 forwarding works but the IPV6 Forwarding doesn't work, please help.

**Comment by chrisohaver** [comment]
What version of CoreDNS are you using?

There is a bug (#3900) in CoreDNS since 1.6.7 that causes only the first server in the forward list to be used.

**Comment by ghost** [comment]
`v1.6.9`

**Comment by chrisohaver** [comment]
Does the following work?

```
forward . [2001:4860:4860::8888]:53
```

**Comment by ghost** [comment]
> Does the following work?
> 
> ```
> forward . [2001:4860:4860::8888]:53
> ```

is there any way to add all 4 dns servers?

`PrimaryIPv4,SecondaryIPv4,PrimaryIPv6,SecondaryIPv4`

**Comment by chrisohaver** [comment]
Permutation of #3900

**Comment by chrisohaver** [comment]
> is there any way to add all 4 dns servers?

Yes, but due to bug #3900, only the first is ever used (unless the first is unhealthy).

**Comment by ghost** [comment]
> > is there any way to add all 4 dns servers?
> 
> Yes, but due to bug #3900, only the first is ever used (unless the first is unhealthy).

if i forward everything to the IPV6 will the ipv4 forwarding still work?
