### ISSUE TITLE
Should we do a 1.6.10 release?

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#3925]
We recently resolved #3900, which is not a "security" level concern, but is nonetheless a fairly significant regression.  The bug was introduced in 1.6.7, and there have been critical bug fixes since then (e.g. #3744), so rolling back to 1.6.6 isn't feasible.  ... The bug that #3744 fixes was introduced in 1.6.6, but 1.6.6 also included a security fix, so rolling back to 1.6.5 may be problematic for some.

A complication of releasing a 1.6.10 is that we have already merged some backward incompatible changes into master (e.g. the prometheus metrics naming changes).

**Comment by chrisohaver** [comment]
IMO, since it's not a security issue, it can wait until 1.7.0 is released (IOW, no need to figure out how to do a 1.6.10 release).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Should we do ..." ]
>IMO, since it's not a security issue, it can wait until 1.7.0 is released.

we should probably do that release pretty quickly though

**Comment by brycecarman** [comment]
I personally would like to see a release that contains the recent bug fixes but I'm concerned about the impact of the metrics name changes.

Would you consider duplicating the metrics and marking the old ones as deprecated for the 1.7.X releases and remove them in the future? This is what was done for Kubernetes to allow users to transition over to the new names. 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md#deprecation-plan.
For example see https://github.com/kubernetes/kubernetes/pull/74418/files

**Comment by pnovotnak** [comment]
We've got issues with kubernetes node-local-dns hotspotting our DNS infra and would love a 1.6.10 release. A release with metrics compatibility would probably be a boon for them and would make upstreaming easier.

However, as a workaround, explicitly setting `policy` to `round_robin` seems to work fine*. So in our eyes it's not urgent

*Big gotcha: If your upstreams don't accept UDP (even if `force_tcp` is used), [health checks don't work](https://github.com/coredns/coredns/issues/3938) and when all upstreams are unhealthy, the random policy is used.

**Comment by pnovotnak** [comment]
So, we had `round_robin` and `force_tcp` set – udp health checks were always failing because we hadn't opened UDP on our upstreams. As soon as we did, coredns stopped load balancing at all (where it was _sorta_ load balancing before).

**Comment by chrisohaver** [comment]
@pnovotnak, When all upstreams are unhealthy, a random upstream is selected (which due to the policy selection bug, i think means the first upstream always - hence no load balancing).

In lieu of your PR (#3940), if your upstreams don't support UDP, you can disable health checking with `max_fails 0`...
>* `max_fails` is the number of subsequent failed health checks that are needed before considering an upstream to be down. If 0, the upstream will never be marked as down (nor health checked). Default is 2.

**Comment by chrisohaver** [comment]
> we should probably do that release [1.7.0] pretty quickly though

@miekg, let me know if there is any way I can help make the release happen quickly.  Do you think we can get a release done within the next two weeks?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Should we do ..." ]
>    we should probably do that release [1.7.0] pretty quickly though
>
>@miekg, let me know if there is any way I can help make the release happen
>quickly. Do you think we can get a release done within the next two weeks?

is your k8s fix ready to go. What does John think about it. The transfer stuff should
still be tested (by me) but is less important. If your k8s is ready to go, we should be
able to do a 1.7.0 and go from there.

For the folks wanting a 1.6.10, yes I understand, sadly this requires work from a release
standpoint which isn't done and it doesn't look this is on the horizon - yes this sucks.

**Comment by chrisohaver** [comment]
> is your k8s fix ready to go. What does John think about it. 

#3924, Yes, I'll ping him.

> The transfer stuff should still be tested (by me) but is less important. 

Yeah - I understand if we need to punt all the transfer stuff to a later release.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Should we do ..." ]
>    is your k8s fix ready to go. What does John think about it.
>
>#3924, Yes, I'll ping him.

cool

>    The transfer stuff should still be tested (by me) but is less important.
>
>Yeah - I understand if we need to punt all the transfer stuff to a later
>release.

np, we can release with the current, i think, this should not have major impact just yet,
no/yes?

**Comment by chrisohaver** [comment]
> np, we can release with the current, i think, this should not have major impact just yet,
no/yes?

Yeah - IMO, the transfer stuff can wait until the next release.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Should we do ..." ]
>    np, we can release with the current, i think, this should not have major
>    impact just yet,
>    no/yes?
>
>Yeah - IMO, the transfer stuff can wait until the next release.

ok, cool

**Comment by rtheis** [comment]
We would also like to see a 1.7.x release with duplicate metrics.  Is that being considered?

**Comment by chrisohaver** [comment]
> We would also like to see a 1.7.x release with duplicate metrics. Is that being considered?

I'm not deeply familiar with Prometheus.  As I understand it, duplicating the metrics would also duplicate the underlying data - the drawback being an artificially larger data footprint.  It would be nice if Prometheus provided an "alias" type facility that allowed a client to expose a metric under multiple names, that way you are not literally duplicating metric data.

@miekg, would you be opposed to duplicating metric data for a 1.7.x release to provide a smoother transition for users?

Otherwise, possible user end solutions...

@SuperQ, can `relabel_configs`/`metric_relabel_configs` in the prometheus [scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) be used to rename or create renamed copies of metrics?

A bit of a stretch: but I saw once in a Grafana Dashboard (I cant recall which one), to support multiple versions of a datasource that had changed metric names between versions, the charts were set up with two formulas, one for the old metric name, and one for the new.

Perhaps this should be spun off into a separate issue/discussion.

**Comment by SuperQ** [comment]
Relabel configs rename/copy metrics. It's also easy for Grafana and alerting rules to handle both old and new metrics at the same time.

The formula goes something like this:

```
rate(coredns_dns_blocked_requests_total[1m]) or rate(coredns_request_block_count_total[1m])
```

IMO, there's no need to duplicate metric data. There are easy transition methods for handling this kind of thing. Duplicating is much worse, because it doubles the load on the monitoring system, where the compatible query pattern is light weight.

**Comment by SuperQ** [comment]
For an option for the 1.6.x release. The way I handle this in the node_exporter is when I cut a new minor version, I create a protected `release-X.Y` branch. For additional fixes I create a branch of that branch and use `git cherry-pick` to pull in changes from master.

You can see this workflow in the [node_exporter release-1.0 branch](https://github.com/prometheus/node_exporter/tree/release-1.0).

**Comment by rtheis** [comment]
The challenge for our managed Kubernetes service is that we don't have control over the customer's metrics configuration in Grafana, etc.  So to get the desired fix to our customer's, we need to deliver CoreDNS 1.7.0 via a patch update which will break some of the customers in the sense they will lose metrics and may assume CoreDNS is dead after the patch.  I suppose our alternative is to build our own CoreDNS 1.6.10 release.

**Comment by miekg** [comment]
Fair enough, we knew this would be painful, this is why the  minor version
was increased.

Not having control over X doesn't mean the onus is on us to provide some
kind of transition path and as outlined you can translate easily enough.

We've added tests for metric naming so I'm confident we don't need to do a
mass renaming any time soon.

/close
/lock
