### ISSUE TITLE
forward . /etc/resolv.conf not work sometimes when use local dns

### ISSUE THREAD

**Issue by umrikar** [coredns/coredns#3926]
I have below  coredns configmap and coredns version CoreDNS-1.3.1, kubernetes version v1.14.0

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
```

**What happened**:
   
   i write my local dns in /etc/resolv.conf, but it not work sometimes in pod.
But when i change the /etc/resolv.conf to local dns address

forward . 10.240.0.10

it works always

my /etc/resolv.conf

nameserver 8.8.8.8
nameserver 10.240.0.10

**What you expected to happen**:
     I expect all my queries(for local fqdn) to pass to local dns and get resolved successfully always 

**How to reproduce it (as minimally and precisely as possible)**:
   from any pod try to do nslookup to any local FQDN which is registered on your local DNS

**Comment by chrisohaver** [comment]
If you want to resolve a certain local zone using a private dns, see ...

https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns

**Comment by umrikar** [comment]
> 
> 
> If you want to resolve a certain local zone using a private dns, see ...
> 
> https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns

yes i could see solution you suggested works, but i don't want to modify it manually and i have multiple FQDN's which needs to get resolved by local DNS

**Comment by umrikar** [comment]
Thanks, it works perfect

> 
> 
> If you want to resolve a certain local zone using a private dns, see ...
> 
> https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns

Thanks, it works perfect
