### ISSUE TITLE
changes in /etc/resolv.conf are not taken by coredns pods untill i reboot system

### ISSUE THREAD

**Issue by umrikar** [coredns/coredns#3928]
I have below coredns configmap and coredns version CoreDNS-1.3.1, kubernetes version v1.14.0
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap

**What happened**:
              when i make any changes in /etc/resov.conf add new nameserver or remove.
coredns service doesn't take respective changes and i need to reboot vm to get them reflected.
example if  /etc/resolv.conf on host has dns 
nameserver 10.240.0.10 which is faulty dns and if i change contents of /etc/resolv.conf
as nameserver 8.8.8.8

and i go inside any pod and try to ping google.com then  get failure for name resolution
but when i reboot vm and try to ping google.com from the pod it works
i think coredns pods dont take changes in /etc/resolv.conf directly and need restart, 

also i observed if scale coredns deployment to 1 then outof 2 coredns pods one gets deleted but when i updated deployment with replicas to 2 then it doesn't create 2 pods, it keeps only 1

**What you expected to happen**:
          I expect changes in /etc/resolv.conf on vm should be instantly taken by coredns service

**Comment by zouyee** [comment]
AFAIK, currently, the `reload` plugin periodically checks if the Corefile（not resolv.conf） has changed by reading

**Comment by chrisohaver** [comment]
Yes - the _forward_ plugin only reads the file (e.g. `/etc/resolv.conf`) when CoreDNS starts/restarts.
The _reload_ plugin only checks for changes in the Corefile, not other files referenced by plugins (e.g. the zone file by the _file_ plugin, and resolv.conf by the _forward_ plugin ).

Whether not we periodically check/re-read plugin referenced files is currently left to the plugins themselves.  For example, the _file_ plugin periodically reloads its zone file, which makes sense, since a zone file is inherently dynamic.  Currently, the _forward_ plugin does not periodically check/reload its `resolv.conf` file - probably because its contents are generally static.

Side note: Perhaps it would be useful to add an interface to enable the _reload_ plugin to retrieve a list of files it should monitor from each plugin that implements it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] changes in /e..." ]
>Side note: Perhaps it would be useful to add an interface to enable the reload
>plugin to retrieve a list of files it should monitor from each plugin that
>implements it.

No, we watch the corefile, if you have this setup, you'll need to SIGUSR1 the coredns
process which is easily doable. I think only the host plugin went through the effort of
doing this, and even there you make the case that SIGUSR1-ing would be easier.

**Comment by chrisohaver** [comment]
Unfortunately, sending signals to Pods in Kubernetes is not trivial. https://github.com/kubernetes/kubernetes/issues/24957

**Comment by adammw** [comment]
@miekg are you saying that PRs / improvements to forward plugin to check/re-read the resolv.conf file would not be accepted and we must use the SIGUSR1 approach instead when changing resolv.conf?

**Comment by miekg** [comment]
Why is sigusr1 a bad option? And, no, it's unlikely that we are going to
watch random files for reload.

**Comment by wu0407** [comment]
> Yes - the _forward_ plugin only reads the file (e.g. `/etc/resolv.conf`) when CoreDNS starts/restarts. The _reload_ plugin only checks for changes in the Corefile, not other files referenced by plugins (e.g. the zone file by the _file_ plugin, and resolv.conf by the _forward_ plugin ).
> 
> Whether not we periodically check/re-read plugin referenced files is currently left to the plugins themselves. For example, the _file_ plugin periodically reloads its zone file, which makes sense, since a zone file is inherently dynamic. Currently, the _forward_ plugin does not periodically check/reload its `resolv.conf` file - probably because its contents are generally static.
> 
> Side note: Perhaps it would be useful to add an interface to enable the _reload_ plugin to retrieve a list of files it should monitor from each plugin that implements it.

Currently, we can do this by adding a break line in configmap to trigger reload. and this line break must be within the same curly braces as the “reload” keyword.
```
data:
  Corefile: |
    .:53 {
        log . {combined} {
          class error
        }
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf   {
          max_concurrent 1000
        }
        cache 30
        loop
        reload
        # Add break line in here
        loadbalance
    }
```
https://midbai.com/en/post/gracefully-change-the-dns-server-ip-on-a-kubernetes-cluster/#replacing-the-etcresolvconf-file-in-coredns
