### ISSUE TITLE
Make notify client IP configurable

### ISSUE THREAD

**Issue by JensErat** [coredns/coredns#3929]
**What would you like to be added**:

Add a configuration option to select client IP notify is sent from.

**Why is this needed**:

Usually other name servers only accept notifies from a whitelisted IP address. If you have a machine with multiple interfaces attached, CoreDNS just chooses "some" address without the operator having proper influence on selection.

- - -

I guess all that's needed is adding a configured `Dialer` (https://github.com/miekg/dns/blob/master/client.go#L34) in the respective `notify(...)` functions (eg. https://github.com/coredns/coredns/blob/87bd9dec856b743d65d71f90accc4296d767b109/plugin/file/notify.go#L48). Maybe this is something rather to be implemented in #3121? Otherwise, how would a proper configuration look like -- a `notify from <client-ip>` option in `file` plugins?

**Comment by chrisohaver** [comment]
I assume that the system is (consistently) deciding which interface to use based on the system routing table and destination IP of the notify packet.

**Comment by JensErat** [comment]
I should have rather explained another situation with a VIP for HA purpose added to the machine. You don't really have control over the IP to choose by default, especially if the IP is reconfigured dynamically. You could apply dirty policy based routing hacks, but this calls for issues.

The canonic way of selecting an outgoing IP address is on the socket side. Similar issues will occur with IPv6 notifies, multiple IPv6 addresses on the same interface are much too common.

**Comment by JensErat** [comment]
[Bind has an option](https://serverfault.com/a/692917/98727), [PowerDNS got one](https://doc.powerdns.com/authoritative/settings.html#query-local-address), I guess all the others will also have this address configurable.

**Comment by chrisohaver** [comment]
OK - I think a reasonable behavior would be something like...  If the notify destination IP falls within the subnet of a configured "notify from" interface, sending using that use that interface.  If not, let the system route it.

**Comment by JensErat** [comment]
I don't think this would solve any kind of real world issue. Setting up a proper source IP is important especially when you do _not_ have control over the receiving side, you can usually setup exactly one IP allowed to notify. If the receiving system is in your own subnet, you'll probably be able to configure pretty arbitrary trust anyway.

Example setup: Consider

- a HA pair of DNS servers 192.0.2.10/24 and 192.0.2.11/24
- one of them holding a failover IP from the same network 192.0.2.53/24 (also listed as primary NS)
- you want to notify a nameserver service operator on 198.51.100.100 to update the zones
- the service operator allows exactly one IP address per zone as notify source

If doing so, Linux will usually use the first IP address ever configured for the interface holding the default route. This is the machine IP, since the failover IP is only configured _after_ the machine and service were brought up (and down on the other machine) by design. The machine IP will be used to send the notify, unless either you have the source IP configurable (which is what the other DNS daemons are doing) or apply policy routing/source based routing (which is a great way to mess things up badly).

This is just one scenario where this is required. Multihomed servers/small Linux router boxes (a great place for running CoreDNS, too!) would be another one. Not to think of IPv6/IPv4 selection issues. This might actually be a good thing to make configurable generally for all kinds of outgoing requests, this is what PowerDNS did (on the other hand, bind has it configurable per notify target).

- - - 

This is what [RFC 1996](https://tools.ietf.org/html/rfc1996) says about the notify IP issue:

>    3.10. If a slave receives a NOTIFY request from a host that is not a
>    known master for the zone containing the QNAME, it should ignore the
>    request and produce an error message in its operations log.
> 
>    Note:
>       This implies that slaves of a multihomed master must either know
>       their master by the "closest" of the master's interface
>       addresses, or must know all of the master's interface addresses.
>       Otherwise, a valid NOTIFY request might come from an address
>       that is not on the slave's state list of masters for the zone,
>       which would be an error.

They see this kind of configuration rather at the receiving side -- but then again, those fixed DNS services addresses are usually exactly the pretty static entities that never change, unlike machine IPs, ... And the vast majority of service operators seems to only allow a single address, unlike at least somewhat recommended by the RFC.

**Comment by chrisohaver** [comment]
> I don't think this would solve any kind of real world issue.

Confused.  What is “this”?

**Comment by miekg** [comment]
Can we reuse the bind plugin? Having another knob just for this seems
overkill.

**Comment by chrisohaver** [comment]
> Can we reuse the bind plugin?

You mean send notifies out via the address bound to with the bind plugin?  I initially didn't think so, but as I started to describe why just now, I think it could work.

**Comment by JensErat** [comment]
> Confused. What is “this”?

The proposal of doing some subnet-magic proposed in the message above me.

> Can we reuse the bind plugin? Having another knob just for this seems overkill.

Not to sure about this (but I might be wrong on those thoughts). You'll (at least, I -- and I don't have the feeling the use case is very specific if you consider CoreDNS a general use DNS server) also want to respond to queries from other networks. This will either result in a pretty complex configuration with duplication on zones to serve locally and zones to notify on, or you have to do funny things like forwarding to yourself.

Notifying and listening seems just like two separate concepts.

**Comment by chrisohaver** [comment]
> Notifying and listening seems just like two separate concepts.

I thought the same initially ... But in the context of transfers and notifies, I think it would be very odd to want to receive notifies from a different IP than where you would send the IXFRs.  Usually it would be the same IP, in which case CoreDNS needs to be listening on that IP too.

**Comment by JensErat** [comment]
> I thought the same initially ... But in the context of transfers and notifies, I think it would be very odd to want to receive notifies from a different IP than where you would send the IXFRs. Usually it would be the same IP, in which case CoreDNS needs to be listening on that IP too.

Definitely. But often you're serving the zone to all networks while transmitting to some (you might want to transfer to more than one). I don't think CoreDNS configuration currently allows to "bind" only transfers. I guess the both most simple and flexible approach would be to allow a source IP per transfer line, something like:

```
file DBFILE [ZONES... ] {
    transfer [source IP] to ADDRESS...
    reload DURATION
}
```

Don't like the option name at all, but you get the point. This would even allow something like

```
file DBFILE [ZONES... ] {
    transfer source 192.0.2.10 to 198.51.100.100
    transfer source 192.0.2.20 to 203.0.113.200
    reload DURATION
}
```

Not sure if that would be required, but it would come for free. I think similar configuration would also fit the new transfer approach in #3121.

**Comment by chrisohaver** [comment]
> The proposal of doing some subnet-magic proposed in the message above me.

We have two sets of IPs...  
* a set of remote servers that receive notifies and send us transfer requests.
* a set of local interfaces (with IPs) we want to send notifies out on.

When sending a notify out to a remote server, we need to know which local interface to send it out on.  We can determine that via the interface's subnet. If not that, then you'd need to list the destination.

Which I see you are now proposing above ...

**Comment by JensErat** [comment]
> When sending a notify out to a remote server, we need to know which local interface to send it out on. We can determine that via the interface's subnet. If not that, then you'd need to list the destination.
> 
> Which I see you are now proposing above ...

The server might have multiple interfaces with multiple IP addresses each. It is not really about the (notify) client subnet, but about the specific IP address. In the example above, both physical servers and the failover IP are from the same subnet. I'll edit the ranges into the example.

**Comment by chrisohaver** [comment]
> But often you're serving the zone to all networks while transmitting to some (you might want to transfer to more than one)

Ah, right.  It would not work with bind.

So something like... 

```
transfer <zone> {
  to <destination-ip> [from <interface-ip>]
}
```

.. would be simple, and not require any so-called magic.

**Comment by JensErat** [comment]
> ```
> transfer <zone> {
>   to <destination-ip> [from <interface-ip>]
> }
> ```

I was also already with `from`, but it feels too similar to the secondary's `transfer from` which means something different. And in fact, the same issue occurs over there (but I guess the whole secondary plugin is somewhat deprecated anyway?).

**Comment by chrisohaver** [comment]
We could use `via` instead ...

```
transfer <zone> {
  to <destination-ip> [via <interface-ip>]
}
```

**Comment by JensErat** [comment]
I think `via` is more on the routing side and describes the next hop (if you're doing source-based routing, they also call it _source_ there). Golang calls it [`LocalAdd`](https://golang.org/pkg/net/#Dialer), close to what's PowerDNS is using (`query-local-address`, link above). Bind has `notify-source`. Maybe bind's variant is actually the with best "self-documentation capabilities":

```
transfer <zone> {
  to <destination-ip> [notify-source <local-ip>]
}
```

Some more bytes, but this is just configuration and not bit-optimized DNS protocol. :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Make notify c..." ]
>We could use via instead ...
>
>transfer <zone> {
>  to <destination-ip> [via <interface-ip>]
>}

I like where this discussion is going, but this is *only* source ip and in the crazy DNS
world we also have tsig so this needs to incorperate that as well (at least in the syntax,
not directly in the implementation.

     to <destination-ip> [via <interface-ip>] [with key <key-spec>]

Is that future proof enough?

**Comment by JensErat** [comment]
> I like where this discussion is going, but this is *only* source ip and in the crazy DNS world we also have tsig so this needs to incorperate that as well (at least in the syntax, not directly in the implementation. to <destination-ip> [via <interface-ip>] [with key <key-spec>] Is that future proof enough?

Good point. The choice of UDP or TCP is probably better left to the implementation, and it will probably not fail either way and try the other (did not check this, though). Checking [bind documentation](https://www.zytrax.com/books/dns/ch7/xfer.html) I see at least no _obvious_ additional configuration we might still be missing. Bind allows to specify a client-side port for connection, but this really seems something you shouldn't do to me...

If we're starting to chain multiple options anyway, might be a subsection a better idea? Probably better to read and doesn't matter whether more options will be added in future for that transfer destination. For those two values the single line would probably be sufficient either...

```
  to <destination-ip> {
    [via|notify-source|whatever <interface-ip>]
    [with key <key-spec>]
  }
```

**Comment by chrisohaver** [comment]
I added this to #3420 ... 

The `to` config option now looks like ...

`to <destination-ip> [notify [source <interface-ip>]]`

> Is that future proof enough?

We might also, in the future, want to add a tcp option... e.g. 

`to <destination-ip> [notify [tcp] [source <interface-ip>] [tsig <key>]]`

**Comment by JensErat** [comment]
Looks good to me! Would've provided some code, too; but this felt like a change that definitely had to be discussed before getting hands-on.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Make notify c..." ]
>I added this to #3420 ...
>
>The to config option now looks like ...
>
>to <destination-ip> [notify [source <interface-ip>]]
>
>    Is that future proof enough?
>
>We might also, in the future, want to add a tcp option... e.g.
>
>to <destination-ip> [notify [tcp] [source <interface-ip>] [tsig <key>]]

feels slightly like over-optimizing (the `tcp`) option. But generally just having
this configuration line seems like a way to go. This would also require that we thing of
the receiving side, i.e. what syntax do we need to receive or deny a transfer from the
wrong address or tsig key (feel this could be mostly similar?)

/plugin file
/plugin transfer
/label enhancement

**Comment by JensErat** [comment]
I guess this would be something like

    transfer {
      from ...? [allow-notify [SOURCE_RANGE]...
    }

Regarding the RFC, should the actual IP to transfer from be read from the SOA record? I think currently CoreDNS has a configuration knob anyway.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Make notify c..." ]
>I guess this would be something like
>
>transfer {
>  from ...? [allow-notify [SOURCE_RANGE]...
>}

ack. I want to keep the directives between the two mostly similar. Why would you want a
source-range here and not in the transfer out (for instance?)

>Regarding the RFC, should the actual IP to transfer from be read from the SOA
>record? I think currently CoreDNS has a configuration knob anyway.

nope, sorry, that's dns data which is unrelated to what we're discussing here.

**Comment by JensErat** [comment]
> ack. I want to keep the directives between the two mostly similar. Why would you want a source-range here and not in the transfer out (for instance?)

"Because we can". Why not make it possible to allow an entire range ("just in case the notifying party does not support properly selecting a source IP" ;) ). I guess a subnet test is not really more effort compared to a plain string comparison, and a subrange test is just a more general comparison which would also allow single IPs. We could also call it `source` and allow ranges of course. Pretty much what the ACL plugin/syntax is already doing.

> > Regarding the RFC, should the actual IP to transfer from be read from the SOA record? I think currently CoreDNS has a configuration knob anyway.
> 
> nope, sorry, that's dns data which is unrelated to what we're discussing here.

I agree. Mistook the primary-master-referenced-by-SOA-records stuff, but the primary master isn't really of relevance for notify/transfers of course.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Make notify c..." ]
>    ack. I want to keep the directives between the two mostly similar. Why
>    would you want a source-range here and not in the transfer out (for
>    instance?)
>
>"Because we can". Why not make it possible to allow an entire range ("just in

that's not a valid reason IMO - the IP whitelisting also sounds like a '90 thing that was
just carried over - I think the whole concept of zone transfers is silly we have much
better protocols to transfer data nowadays. So something minimal make sense here.

**Comment by miekg** [comment]
note if we're talking about allowing/disallowing we should also look at the *acl* plugin and see if we can do it there?
(reminded of this because of recent bug report)

**Comment by miekg** [comment]
looks stale
