### ISSUE TITLE
middleware/cache interferes with AXFR

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#393]
It seems that AXFRs sometimes fail due to the SOA record not being served first.
The first non cached response seem to be working, but all subsequent (cached) responses are scrambled and the SOA record is not returned first. This results in a non valid AXFR.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] middleware/cache in..." ]

> It seems that AXFRs sometimes fail due to the SOA record not being served first.
> The first non cached response seem to be working, but all subsequent (cached) responses are scrambled and the SOA record is not returned first. This results in a non valid AXFR.

Hehe ;-)

Yeah, we should attempt to cache those (and IXFR for that matter).

I like your testing - keep it coming :)

**Comment by stp-ip** [comment]
Just to add more info:

```
$ dig example.com AXFR
; <<>> DiG 9.11.0-P1 <<>> example.com AXFR
;; global options: +cmd
example.com.    0   IN  SOA  dns1.stabletransit.com. domains.example.com. 2016110702 300 1800 14400 300
[...]
www.example.com.    0   IN  A 0.0.0.0
example.com.    0   IN  SOA  dns1.stabletransit.com. domains.example.com. 2016110702 300 1800 14400 300
;; Query time: 19 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Nov 07 14:03:24 UTC 2016
;; XFR size: 16 records (messages 2, bytes 1273)

$ dig example.com AXFR

; <<>> DiG 9.11.0-P1 <<>> example.com AXFR
;; global options: +cmd
www.example.com.    5   IN  A 0.0.0.0
example.com.    5   IN  SOA dns1.stabletransit.com. domains.example.com. 2016110702 300 1800 14400 300
; Transfer failed.  Didn't start with SOA answer.
```

This happens both with `cache 0` and `cache 300`
