### ISSUE TITLE
split-horizon based on the namespace of the source IP

### ISSUE THREAD

**Issue by etuttle** [coredns/coredns#3934]
**What would you like to be added**:

Split-horizon DNS, based on the k8s namespace of the source IP.

I've searched through the CoreDNS issues and found a few about split dns and advanced routing  in general (eg #2833).  This request is more limited and more concrete, for better or worse.

I have a WIP implementation at [etuttle:nshorizon](https://github.com/coredns/coredns/compare/master...etuttle:nshorizon).  Right now it does the namespaced lookup only after letting the normal lookup get an empty response.  In hindsight I think that should be reversed.  Other than that, the plugin is pretty straightforward.  All of the service/namespace metadata is already available in CoreDNS.

So this Enhancement Request is to see if the feature would be useful to other people and if it's worth opening a PR and work on getting it merged.

**Why is this needed**:

In my case, I'm working on a kubernetets port.  The existing system uses many EC2 instances running the same group of containers, but each with an isolated docker.  It naturally fits into one kubernetes cluster where the isolation is by namespace instead of by instance.

My need for split-horizon is that the "group of containers" have been developed to use the same `internal.example.org` domain to reach the local instance of a given service.  If CoreDNS had this capability, the group of containers can run pretty much as-is in the namespaced kubernetes environment.

Is there any interest in this idea?

**Comment by chrisohaver** [comment]
A more generalized solution may be to add destination routing to the [firewall](https://github.com/coredns/policy) plugin, as suggested in #2833. 

The [firewall](https://github.com/coredns/policy) plugin can already define rules using metadata, and the kubernetes plugin exposes the client pod namespace as metadata.

**Comment by etuttle** [comment]
Firewall is very cool... it strikes me that all of the fancy policy stuff that you can do in traffic routing (eg, istio) has to start with DNS, and there's your answer.

I see how firewall plus metadata plugin would work.  In my case, it's not a multi-tenancy problem in the sense that the namespaces are free to talk to one another, which makes the problem (and my WIP) a bit simpler.

I'm also working with the constraint that the org I'm working with does not want to run a custom CoreDNS binary.  So I'm 🤞 that nshorizon would be considered for inclusion as an in-tree plugin.  Otherwise, I'll probably end up forking all those container configs and maintain in-k8s and not-in-k8s for a period of time.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] split-horizon..." ]
>A more generalized solution may be to add destination routing to the policy
>plugin, as suggested in #2833.
>
>The policy plugin can already define rules using metadata, and the kubernetes
>plugin exposes the client pod namespace as metadata.

agreed, such flexible behavior should be contained into a few plugins, not spread around
in other plugins.

Split horizon is a debugging nightmare
