### ISSUE TITLE
gRPC plugin doesn't support zone transfers

### ISSUE THREAD

**Issue by TheEnbyperor** [coredns/coredns#3937]
**What would you like to be added**:
Support for AXFR in the gRPC plugin, that is returning a stream of DNS messages rather than a single message. The `bytes msg = 1;` in a gRPC DNS reponse could be made into a `repeated bytes msg = 1;` without breaking protobuf backwards compatibility, or a new rpc could be defined for zone transfers.

**Why is this needed**:
I have written my own postgresql backed DNS server which uses Coredns as a front for handling the difficult parts of communicating with clients, such that I only have to implement a gRPC service. I would like to enable slave replication of zones from this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] gRPC plugin doesn..." ]
>What would you like to be added:
>Support for AXFR in the gRPC plugin, that is returning a stream of DNS messages
>rather than a single message. The bytes msg = 1; in a gRPC DNS reponse could be
>made into a repeated bytes msg = 1; without breaking protobuf backwards
>compatibility, or a new rpc could be defined for zone transfers.
>
>Why is this needed:
>I have written my own postgresql backed DNS server which uses Coredns as a
>front for handling the difficult parts of communicating with clients, such that
>I only have to implement a gRPC service. I would like to enable slave
>replication of zones from this.

this might be easily possible with the new *transfer* plugin where adding.

/plugin grpc
/label enhancement

**Comment by TheEnbyperor** [comment]
Ah yes I did see the transfer plugin and wondered if it'd be applicable.
There's two ways I can see this working:
* Add a new transfer rpc to the gRPC plugin (possibly with a streaming return)
* Send the transfer via the existing rpc

Not really sure which would be better

**Comment by miekg** [comment]
the new transfer plugin will help make this easier, currently this is not supported. CoreDNS 1.8.0 will support the transfer plugin, but someone needs to step up and implement it here.
