### ISSUE TITLE
forward: TCP upstreams are health checked with UDP

### ISSUE THREAD

**Issue by pnovotnak** [coredns/coredns#3938]
**What happened**:

I have a DNS upstream that only responds to TCP requests. Unfortunately, coredns `forward` health checks always fail, it looks like the cause is that [CoreDNS only tries UDP](https://github.com/coredns/coredns/blob/master/plugin/forward/health.go#L32) ([it can't differentiate between TCP DNS and UDP DNS](https://github.com/coredns/coredns/blob/master/plugin/pkg/transport/transport.go#L5)). The most unfortunate side-effect of this bug is that even when `policy round_robin` is used to work around [a bug](https://github.com/coredns/coredns/issues/3900) in `policy random` coredns then falls back to a broken `random` policy.

**What you expected to happen**:

Health checks to TCP upstreams should be checked via TCP protocol.

**How to reproduce it (as minimally and precisely as possible)**:

Create a forwarder that forwards requests to an upstream that only has a TCP listener. Observe health check metrics and upstream request rates.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: kubernetes node-cache v1.15.13 (coredns v1.6.7).
- Corefile:
- logs, if applicable:

        $ k logs -n kube-system node-local-dns-22csh | grep healthchecker
        $ echo $?
        1
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by pnovotnak** [comment]
This is not a valid bug, actually. Just caught a query on the wire and it's TCP – the query itself is failing:

<img width="1065" alt="Screen Shot 2020-06-10 at 4 09 47 PM" src="https://user-images.githubusercontent.com/5713245/84327710-ea8d4f80-ab34-11ea-940f-dbc68de5297e.png">

**Comment by pnovotnak** [comment]
I thought I was mistaken, but I managed to capture some unanswered UDP NS queries 
<img width="1098" alt="Screen Shot 2020-06-10 at 5 30 06 PM" src="https://user-images.githubusercontent.com/5713245/84333269-24198700-ab44-11ea-9656-445bb0b11081.png">

**Comment by pnovotnak** [comment]
Here are some graphs of metrics collected from cache instances. We have 3 upstream IPs for our DNS infra (server is in GMT).

Response volume by code across all three servers. You can see the results of a config reload at around 12:00AM GMT – things are OK for a while, but over time the first IP begins handling all of the traffic. At the very end I reordered the upstream IPs, and the first one was once again selected for the majority of requests.
![Screen Shot 2020-06-10 at 6 04 31 PM](https://user-images.githubusercontent.com/5713245/84333529-de10f300-ab44-11ea-8fdf-1e6d36add63c.png)

Health check failures. You can see the result of terminating a number of pods at the end of today – a number of counter resets.
![Screen Shot 2020-06-10 at 6 04 16 PM](https://user-images.githubusercontent.com/5713245/84333525-dc472f80-ab44-11ea-9fe4-8b4cda07bff7.png)

**Comment by miekg** [comment]
any dns server should support udp and tcp, so this should not be an issue

**Comment by uthark** [comment]
According to the spec, DNS server MUST support UDP and SHOULD support TCP: [Section 6.1.3.2 of the RFC 1123](https://tools.ietf.org/html/rfc1123#section-6.1.3.2)

**Comment by uthark** [comment]
In fact, this feature is easy to add, but this is up to maintainers if they want to have this code upstream.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] forward: TCP ..." ]
>According to the spec, DNS server MUST support UDP and SHOULD support TCP:
>Section 6.1.3.2 of the RFC 1123

this is obsoleted, both udp and tcp are mandatory nowadays.
