### ISSUE TITLE
Forward plugin only uses two of three nameservers from host's /etc/resolv.conf

### ISSUE THREAD

**Issue by cyberjaws** [coredns/coredns#3939]
Tested in K3S 1.17.4
CoreDNS Version 1.6.3

Describe the bug
CoreDNS Doesn't resolve hostnames from a particular nameserver in my local /etc/resolv.conf configured on the host node.

Expected behavior
Local DNS server from host's /etc/resolv.conf is used and hostnames are resolved.

Actual behavior
ping result for another machine on the network by hostname from within a pod yields:
"Temporary failure in name resolution"

Additional context / logs
This is on a RHEL7 box with the usual K3s prereqs set (no selinux, firewalld is off, swap is off, etc).

The RHEL7 VM has the following in its /etc/resolve.conf
```
;generated by /usr/sbin/dhclient-script
search my.local.domain.com
nameserver 10.7.35.11  # Can't resolve hostnames from this server!
nameserver 10.120.40.11
nameserver 10.120.40.12
```

The first nameserver is to the local DNS server for the lab I am using to test in. The latter two are to resolve parent services from upstream servers.

I spin up K3S, start a pod, and then exec into the pod. From inside the pod I can resolve hostnames to the parent services but can NOT resolve to other machines using the first nameserver. In the pod I see my custom search (my.local.domain.com) and the static IP of CoreDNS as the nameserver. I have set the --resolv-conf flag to explicitly use /etc/resolv.conf. Systemd resolve is NOT active on the host.

I can mod the Corefile with a stub domain for my.local.domain.com that forwards to 10.7.35.11 and that seems to work. However I was expecting this behavior without the manual configuration. Have I misunderstood how the forward plugin uses the host's /etc/resolv.conf?

**Comment by chrisohaver** [comment]
> The first nameserver [in /etc/resolv.conf] is to the local DNS server for the lab I am using to test in. The latter two are to resolve parent services from upstream servers.

This isn't how /etc/resolv.conf is intended to be used.  The servers are supposed to be fully redundant - all providing the same answers.

The proper way to direct queries in a private domain to a private dns server is to use a separate server block for that domain. Examples: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns

**Comment by cyberjaws** [comment]
Thank you for the response, I greatly appreciate the clarification. I will work with our sys-admin to see if we can get the DNS down to a single nameserver and retest. In the meantime we have implemented the stub domain per your suggestion and that works well.
