### ISSUE TITLE
middleware/file: CNAME chains

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#394]
cname chains are not support in the *file* middleware.

**Comment by stp-ip** [comment]
Could you clarify the nature of "not supported"?
middleware auto is also not supporting cname chains?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/file..." ]

> Could you clarify the nature of "not supported"?
> middleware auto is also not supporting cname chains?

same thing, no cname -> cname (up to 8 is the normal limit I believe), hasn't
been implemented. Things got a bit tricky with wildcard CNAME chains in DNSSEC,
so I left it there.

I'll do this before a 003 release, 'cause I can see the need :)

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
Fixed with #400
