### ISSUE TITLE
SERVFAIL due to "[ERROR] plugin/errors: dns: overflowing header size"

### ISSUE THREAD

**Issue by Shuanglu** [coredns/coredns#3941]
**What happened**:
Send query to coredns and failed due to "SERVFAIL"
**What you expected to happen**:
successful query
**How to reproduce it (as minimally and precisely as possible)**:
'nslookup us.data.logs.insight.rapid7.com'
**Anything else we need to know?**:
captured the logs/tcpdump for investigation and found below behavior
coredns recieved request from client and it sent to upstream successfully. After got response from upstream, it didn't return the result to client but sent query to check the <Root> NS server and the previous dns query again and again which was over 5s

**Environment**:

- the version of CoreDNS: 1.6.6 in AKS
- Corefile: N/A
- logs, if applicable: 
1. client tcpdump
![image](https://user-images.githubusercontent.com/6046716/84367003-352acc80-ac06-11ea-96c7-8ae9a801189c.png)
2. coredns tcpdump
![image](https://user-images.githubusercontent.com/6046716/84367076-4e337d80-ac06-11ea-8b7e-1b6420903946.png)
3. logs
[INFO] 10.244.2.137:39886 - 31370 "A IN us.data.logs.insight.rapid7.com. udp 49 false 512" NOERROR - 0 5.000450902s
[ERROR] plugin/errors: 2 us.data.logs.insight.rapid7.com. A: dns: overflowing header size
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04
- Others:

**Comment by chrisohaver** [comment]
The NS queries are health checks, which kick in after receiving an invalid response (overflowing header size) during the exchange with the upstream server.

Do you see the error if you use [`force_tcp`](https://github.com/coredns/coredns/tree/master/plugin/forward#syntax)?

**Comment by Shuanglu** [comment]
> The NS queries are health checks, which kick in after receiving an invalid response (overflowing header size) during the exchange with the upstream server.
> 
> Do you see the error if you use [`force_tcp`](https://github.com/coredns/coredns/tree/master/plugin/forward#syntax)?

thanks for the reply. I'll try tcp later. 
In addition, may I know what's the valid header size for coredns or any code we could refer? I only encountered the issue within container.

**Comment by Yaowei-Du** [comment]
Hi @chrisohaver, thanks for your help. The `force_tcp` works.

**Comment by berginv** [comment]
> The NS queries are health checks, which kick in after receiving an invalid response (overflowing header size) during the exchange with the upstream server.
> 
> Do you see the error if you use [`force_tcp`](https://github.com/coredns/coredns/tree/master/plugin/forward#syntax)?

Hi @chrisohaver , Im facing the same issue. Tried `force_tcp` like you suggested. But now I'm receiving the below error

![Image](https://github.com/user-attachments/assets/360bfa98-daed-45b5-bc94-7ac74f7490a6)
