### ISSUE TITLE
middleware/auto using AXFR fails

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#395]
Comparing the file middleware and the auto middleware it seemed like AXFR should be available on both.

AXFRs work using the file middleware (when the cache is disabled).
With the auto middleware all transfers fail with a SRVFAIL.  Even with "coredns -v 5" no errors seem to be provided.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] middleware/auto usi..." ]

> Comparing the file middleware and the auto middleware it seemed like AXFR should be available on both.
> 
> AXFRs work using the file middleware (when the cache is disabled).
> With the auto middleware all transfers fail with a SRVFAIL.  Even with "coredns -v 5" no errors seem to be provided.

what's your config...

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
```
    .:5053 {
      auto example.net {
        directory /etc/source/files/zones/ (.*) {1}
        transfer to *
      }
      file /etc/source/files/zones/example.com example.com {
        transfer to *
      }
      proxy . 8.8.8.8:53
      errors stdout
      log stdout
    }
```

Example.com AXFR works.
Example.net AXFR doesn't work.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> ```
>    .:5053 {
>      auto example.net {
>        directory /etc/source/files/zones/ (.*) {1}
>        transfer to *
>      }
>      file /etc/source/files/zones/example.com example.com {
>        transfer to *
>      }
>      proxy . 8.8.8.8:53
>      errors stdout
>      log stdout
>    }
> ```
> 
> Example.com AXFR works.
> Example.net AXFR doesn't work.

This is WAI, `example.com` sits under where _auto_ will pick up zones, so _auto_
has picked up the zone and _not_ _file_. So queries get routed to _auto_ which is
not auth for `example.com` -> SERVFAIL.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
But that would mean, that example.com fails, what I see is that example.net doesn't work.

I split up the config and tried with separate configured instances:
AXFR works:

```
.:5053 {
      file /etc/source/files/zones/example.com example.com {
        transfer to *
      }
      proxy . 8.8.8.8:53
      errors stdout
      log stdout
    }
```

AXFR doesn't work:

```
.:5053 {
      auto example.com {
        directory /etc/source/files/zones/ (.*) {1}
        transfer to *
      }
      proxy . 8.8.8.8:53
      errors stdout
      log stdout
    }
```

AXFR also fails for:

```
.:5053 {
      auto {
        directory /etc/source/files/zones/ (.*) {1}
        transfer to *
      }
      proxy . 8.8.8.8:53
      errors stdout
      log stdout
    }
```

Same zone, but auto instead of file. It seems auto fails.

Every other query seems to work fine for both file and auto. Only AXFR doesn't work.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> AXFR also fails for:
> 
> ```
> .:5053 {
>      auto {
>        directory /etc/source/files/zones/ (.*) {1}
>        transfer to *
>      }
>      proxy . 8.8.8.8:53
>      errors stdout
>      log stdout
>    }
> ```
> 
> Same zone, but auto instead of file. It seems auto fails.
> 
> Every other query seems to work fine for both file and auto. Only AXFR doesn't work.

Hmmm, can't replicate this...

Corefile

```
.: {
      auto {
        directory /home/miek/test db\.(.*) {1}
        transfer to *
      }
      proxy . 8.8.8.8:53
      errors stdout
      log stdout
}
```

`db.example.org` file in ~/test, starting CoreDNS:

```
./coredns -log stdout -conf ~/Corefile-axfr -dns.port=1053
2016/11/07 16:10:53 [INFO] Inserting zone `example.org.' from: /home/miek/test/db.example.org
.:1053
2016/11/07 16:10:53 [INFO] CoreDNS-002
CoreDNS-002
2016/11/07 16:11:02 [INFO] Outgoing transfer of 18 records of zone example.org. to ::1 started
::1 - [07/Nov/2016:16:11:02 +0000] "AXFR IN example.org. tcp false 65535" NOERROR 845 273.691µs
```

And that AXFR is me digging for the zone transfer.

(done with current master)

**Comment by stp-ip** [comment]
Just build current master and it seems to work there. Will test more, but closing for now. Thanks for testing on your side.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> Just build current master and it seems to work there. Will test more, but closing for now. Thanks for testing on your side.

... still strange... Anyway added test for it.

**Comment by stp-ip** [comment]
Finally I think I got to the core issue I encountered.
It wasn't about file or auto, it was about the transfer usage within auto.
(For file both syntaxes work aka the order of transfer to doesn't matter)

This config fails with auto (sidenote: notify is triggered):

```
.:5053 {
      auto example.com {
        directory /etc/source/files/zones/ (.*) {1}
        transfer to *
        transfer to 8.8.8.8
      }
      proxy . 8.8.8.8:53
      errors stdout
      log stdout
    }
```

This works (sidenote: this doesn't notify 8.8.8.8):

```
.:5053 {
      auto example.com {
        directory /etc/source/files/zones/ (.*) {1}
        transfer to 8.8.8.8
        transfer to *
      }
      proxy . 8.8.8.8:53
      errors stdout
      log stdout
    }
```

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> This config fails with auto (sidenote: notify is triggered):
> 
> ```
> .:5053 {
>      auto example.com {
>        directory /etc/source/files/zones/ (.*) {1}
>        transfer to *
>        transfer to 8.8.8.8
>      }
>      proxy . 8.8.8.8:53
>      errors stdout
>      log stdout
>    }
> ```
> 
> This works (sidenote: this doesn't notify 8.8.8.8):
> 
> ```
> .:5053 {
>      auto example.com {
>        directory /etc/source/files/zones/ (.*) {1}
>        transfer to 8.8.8.8
>        transfer to *
>      }
>      proxy . 8.8.8.8:53
>      errors stdout
>      log stdout
>    }
> ```

Ah, yes, serves me right for not reusing the parsing from the _file_ middleware
..

/Miek

## 

Miek Gieben
