### ISSUE TITLE
pod definitions assume capabilities

### ISSUE THREAD

**Issue by haircommander** [coredns/coredns#3951]
**What happened**:
CRI-O 1.18 dropped the capability NET_RAW by default, as it's not needed for the majority of containers, and is pretty powerful. a user of CRI-O pointed out that coredns assumes NET_RAW, and fails if it's not specified [here](https://github.com/cri-o/cri-o/issues/3872).
(note, I have not verified this myself, but I'm opening this issue to cross reference and start a discussion)

**What you expected to happen**:
a pod run with CRI-O 1.18 does not fail out of the box, because it has requested NET_RAW

**How to reproduce it (as minimally and precisely as possible)**:
run coredns with CRI-O
**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by haircommander** [comment]
interestingly, I was not able to reproduce this. using a local cluster. @kubealex do you have any other details of your installation method

**Comment by kubealex** [comment]
Nothing special, Just install k8s with cri-o as runtime following the
instruction in the website, deploy the CNI plugin (flannel/calico), wait
for coredns pods to come up, get logs and enjoy the i/o timeout mayhem 😂

Il lun 15 giu 2020, 16:53 Peter Hunt <notifications@github.com> ha scritto:

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] pod definitio..." ]
>Nothing special, Just install k8s with cri-o as runtime following the
>instruction in the website, deploy the CNI plugin (flannel/calico), wait
>for coredns pods to come up, get logs and enjoy the i/o timeout mayhem 😂

we don't ask for extra permission. The Dockerfile we're using is pretty plain, maybe it's
in the podspec, but we don't control that directly

**Comment by haircommander** [comment]
@miekg do you know where that pod spec lives?

**Comment by chrisohaver** [comment]
@haircommander https://github.com/coredns/deployment/pull/230

**Comment by haircommander** [comment]
@kubealex is always two steps ahead of me...

**Comment by kubealex** [comment]
> @kubealex is always two steps ahead of me...

:)
