### ISSUE TITLE
Metadata plugin for arbitrary types

### ISSUE THREAD

**Issue by ezeike** [coredns/coredns#3952]
Currently the metadata plugin can only store string data. The ability to store a pointer to my own struct would be ideal for me as right now I have to jam all my functionality into one plugin.

It seems as though the plugin could be modified, or a new one created that can do this. Is there anything about CoreDNS that would prevent this simple solution? Is there a better way to accomplish what I want?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Metadata plugin f..." ]
>Currently the metadata plugin can only store string data. The ability to store
>a pointer to my own struct would be ideal for me as right now I have to jam all
>my functionality into one plugin.
>
>It seems as though the plugin could be modified, or a new one created that can
>do this. Is there anything about CoreDNS that would prevent this simple
>solution? Is there a better way to accomplish what I want?

you should encode it as a string or figure out how to retrieve the data from somehwere
using the string as a key.

/plugin metadata
/label question
