### ISSUE TITLE
forward health check not exp backoff

### ISSUE THREAD

**Issue by wisre** [coredns/coredns#3963]
i has viewed forward plugin health check code ,find that if check result is unhealth, it go into loop ,but the interval is not exp backoff,
![image](https://user-images.githubusercontent.com/15846757/85364206-32f53600-b555-11ea-8095-c0fa45bdecb7.png)

code path: https://github.com/coredns/coredns/blob/master/plugin/pkg/up/up.go

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] forward health ch..." ]
>i has viewed forward plugin health check code ,find that if check result is
>unhealth, it go into loop ,but the interval is not exp backoff,
>image
>
>code path: https://github.com/coredns/coredns/blob/master/plugin/pkg/up/up.go

yes, this is known and intentional

/close
