### ISSUE TITLE
NOTIFY fails

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#398]
During testing the file and auto middleware it seems NOTIFY events failed for me on all fronts. I assume this is a config error, but it seems logging doesn't help here. Tried with -v 0 up to -v 5 and the only error I get is: ```2016/11/07 17:00:17 [ERROR] Failed to send notify for zone 'example.com.' to '8.8.8.8:53'```

Any suggestion to get more debugging logs?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] NOTIFY fails (#398)..." ]

> During testing the file and auto middleware it seems NOTIFY events failed for me on all fronts. I assume this is a config error, but it seems logging doesn't help here. Tried with -v 0 up to -v 5 and the only error I get is: `2016/11/07 17:00:17 [ERROR] Failed to send notify for zone 'example.com.' to '8.8.8.8:53'`
> 
> Any suggestion to get more debugging logs?

`-v` does nothing at the moment.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
Thanks for the clarification.
Will check out the latest version, when the latest changes are merged.
Let's see how far I can go down the rabbit hole tonight or maybe just get it working.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] NOTIFY fails (#..." ]

> Thanks for the clarification.
> Will check out the latest version, when the latest changes are merged.
> Let's see how far I can go down the rabbit hole tonight or maybe just get it working.

Hehe :-)  CNAME chains might be fixed as well, but don't hold your breath.

/Miek

## 

Miek Gieben
