### ISSUE TITLE
Resolving external domains from within pods does not work

### ISSUE THREAD

**Issue by nikolamalesevic** [coredns/coredns#3982]
**What happened**:

Resolving an external domain from within a pod fails with **SERVFAIL** message. In the logs, **i/o timeout** error is mentioned.

I have a feeling that this is more about my configuration than it is a bug with CoreDNS. If so, I hope I am not breaking the code of conduct by asking for help here.

**What you expected to happen**:

External domains should be successfully resolved from the pods.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```

1. Create the pod above (from [Debugging DNS Resolution](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) help page).
1. Run `kubectl exec dnsutils -it -- nslookup google.com`
```
pig@pig202:~$ kubectl exec dnsutils -it -- nslookup google.com
Server:		10.152.183.10
Address:	10.152.183.10#53

** server can't find google.com.mshome.net: SERVFAIL

command terminated with exit code 1
```
3. Also run `kubectl exec dnsutils -it -- nslookup google.com.`
```
pig@pig202:~$ kubectl exec dnsutils -it -- nslookup google.com.
Server:		10.152.183.10
Address:	10.152.183.10#53

** server can't find google.com: SERVFAIL

command terminated with exit code 1
```

**Anything else we need to know?**:

I am using **microk8s** environment in a **Hyper-V virtual machine**.

Resolving DNS from the virtual machine works, and kubernetes is able to pull container images. It's only from within the pods that the resolution is failing meaning I cannot communicate with the Internet from within the pods.

This is OK:
```
pig@pig202:~$ kubectl exec dnsutils -it -- nslookup kubernetes.default
Server:		10.152.183.10
Address:	10.152.183.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.152.183.1
```

**Environment**:

- the version of CoreDNS:
```
image: 'coredns/coredns:1.6.6'
```
- Corefile (taken from ConfigMap):
```
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        log . {
          class error
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4
        cache 30
        loop
        reload
        loadbalance
    }
```
- logs, if applicable:
```
pig@pig202:~$ kubectl logs --namespace=kube-system -l k8s-app=kube-dns -f
[INFO] 10.1.99.26:47204 - 29832 "AAAA IN grafana.com. udp 29 false 512" NOERROR - 0 2.0002558s
[ERROR] plugin/errors: 2 grafana.com. AAAA: read udp 10.1.99.19:52008->8.8.8.8:53: i/o timeout
[INFO] 10.1.99.26:59350 - 50446 "A IN grafana.com. udp 29 false 512" NOERROR - 0 2.0002028s
[ERROR] plugin/errors: 2 grafana.com. A: read udp 10.1.99.19:60405->8.8.8.8:53: i/o timeout
[INFO] 10.1.99.26:43050 - 13676 "AAAA IN grafana.com. udp 29 false 512" NOERROR - 0 2.0002151s
[ERROR] plugin/errors: 2 grafana.com. AAAA: read udp 10.1.99.19:45624->8.8.8.8:53: i/o timeout
[INFO] 10.1.99.26:36997 - 30359 "A IN grafana.com. udp 29 false 512" NOERROR - 0 2.0002791s
[ERROR] plugin/errors: 2 grafana.com. A: read udp 10.1.99.19:37554->8.8.4.4:53: i/o timeout
[INFO] 10.1.99.32:57927 - 53858 "A IN google.com.mshome.net. udp 39 false 512" NOERROR - 0 2.0001987s
[ERROR] plugin/errors: 2 google.com.mshome.net. A: read udp 10.1.99.19:34079->8.8.4.4:53: i/o timeout
[INFO] 10.1.99.32:38403 - 36398 "A IN google.com.mshome.net. udp 39 false 512" NOERROR - 0 2.000224s
[ERROR] plugin/errors: 2 google.com.mshome.net. A: read udp 10.1.99.19:59835->8.8.8.8:53: i/o timeout
[INFO] 10.1.99.26:57447 - 20295 "AAAA IN grafana.com.mshome.net. udp 40 false 512" NOERROR - 0 2.0001892s
[ERROR] plugin/errors: 2 grafana.com.mshome.net. AAAA: read udp 10.1.99.19:51534->8.8.8.8:53: i/o timeout
[INFO] 10.1.99.26:41052 - 56059 "A IN grafana.com.mshome.net. udp 40 false 512" NOERROR - 0 2.0001879s
[ERROR] plugin/errors: 2 grafana.com.mshome.net. A: read udp 10.1.99.19:47378->8.8.8.8:53: i/o timeout
[INFO] 10.1.99.26:56748 - 51804 "AAAA IN grafana.com.mshome.net. udp 40 false 512" NOERROR - 0 2.0003226s
[INFO] 10.1.99.26:45442 - 61916 "A IN grafana.com.mshome.net. udp 40 false 512" NOERROR - 0 2.0001922s
[ERROR] plugin/errors: 2 grafana.com.mshome.net. AAAA: read udp 10.1.99.19:35528->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 grafana.com.mshome.net. A: read udp 10.1.99.19:53568->8.8.8.8:53: i/o timeout
```
- OS (e.g: `cat /etc/os-release`):
```
pig@pig202:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
```

Tried on Ubuntu 18.04.3 LTS, same issue.

- Others:
`mshome.net` search domain comes from Hyper-V network, I assume. Perhaps this will be of help:

```
pig@pig202:~$ nmcli device show eth0
GENERAL.DEVICE:                         eth0
GENERAL.TYPE:                           ethernet
GENERAL.HWADDR:                         00:15:5D:88:26:02
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     Wired connection 1
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/1
WIRED-PROPERTIES.CARRIER:               on
IP4.ADDRESS[1]:                         172.19.120.188/28
IP4.GATEWAY:                            172.19.120.177
IP4.ROUTE[1]:                           dst = 0.0.0.0/0, nh = 172.19.120.177, mt = 100
IP4.ROUTE[2]:                           dst = 172.19.120.176/28, nh = 0.0.0.0, mt = 100
IP4.ROUTE[3]:                           dst = 169.254.0.0/16, nh = 0.0.0.0, mt = 1000
IP4.DNS[1]:                             172.19.120.177
IP4.DOMAIN[1]:                          mshome.net
IP6.ADDRESS[1]:                         fe80::6b4a:57e2:5f1b:f739/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = fe80::/64, nh = ::, mt = 100
IP6.ROUTE[2]:                           dst = ff00::/8, nh = ::, mt = 256, table=255
```

**Comment by nikolamalesevic** [comment]
Finally figured it out - it was a configuration issue and the combination of changes to Kubelet configuration (`resolv-conf` flag) and CoreDNS forwarding address fixed it for me.

More details [here](https://stackoverflow.com/a/62678275/388664).

**Comment by Prashanth-M** [comment]
> Finally figured it out - it was a configuration issue and the combination of changes to Kubelet configuration (`resolv-conf` flag) and CoreDNS forwarding address fixed it for me.
> 
> More details [here](https://stackoverflow.com/a/62678275/388664).

facing the same issue. Have you update the file: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf on all nodes??

**Comment by chrisohaver** [comment]
> Finally figured it out - it was a configuration issue and the combination of changes to Kubelet configuration (resolv-conf flag) and CoreDNS forwarding address fixed it for me.

@nikolamalesevic, FWIW, only one of those changes would be needed.  Setting `resolv-conf` in kublet **or** hard-coding the forward address in the CoreDNS config. The former being the proper fix, and the latter being a bit of a hack (since it doesn't address the issue for any other `dnsPolicy: default` Pods).

With the first fix, for `dnsPolicy: default` pods such as CoreDNS, kubelet uses that file from the _host_ to create `/etc/resolv.conf` in the _pod_.  The path to the `resolv.conf` file in the Pod is always `/etc/resolv.conf` regardless of where the original host's file was located. Pods need to be restarted to see the change.

> facing the same issue. Have you update the file: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf on all nodes??

@Prashanth-M, such a change should be made to all nodes that [use a local dns resolver](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues).

**Comment by chrisohaver** [comment]
@Prashanth-M ... although IIRC, _kubeadm_ detects this, and automatically sets up kubelet properly.

**Comment by Prashanth-M** [comment]
@chrisohaver Thank you. I have updated on each node, its working now.

But strange thing is it was working for last 2 months without any tweaks to kubelet, suddenly this issue occured!!.

**Comment by maze88** [comment]
Partially related, for specific cases:
I had similar errors in my CoreDNS logs too, when running within KinD.
What solved it for me was to pre-create its Docker network (`docker network create kind`).
