### ISSUE TITLE
Bad logging and wrong rcode of disallowed AXFR

### ISSUE THREAD

**Issue by tsarna** [coredns/coredns#3983]
**What happened**:

I set up a secondary that was trying to AXFR a domain from CoreDNS. I added the secondary to the ACLs but forgot to add it in the "transfer to ..." statement, so it failed. But the issue is HOW it failed.

According to the CoreDNS logs, the issue is not on the CoreDNS side:

[INFO] 192.168.1.1:35509 - 19490 "AXFR IN example.com. tcp 59 false 65535" NOERROR qr,aa 9699 0.000554297s

However, dig and tcpdump reveal that CoreDNS is actually sending SERVFAIL instead of NOERROR!

**What you expected to happen**:

1. CoreDNS logs should not lie about what rcode it returns! If it returns SERVFAIL, it should log that. Debugging is unnecessarily complicated when the logs can't be trusted.

2. I don't think SERVFAIL is not the appropriate rcode in this case anyway. I haven't dug into the RFCs, but I suspect either NOTAUTH or maybe REFUSED is appropriate. Running AXFRs with dig against several well known nameservers (8.8.8.8, 1.1.1.1, various TLD name servers, ...), they all seem to use NOTAUTH.

Had the rcode been NOTAUTH and had the log correctly indicated this fact would have steered me to my misconfiguration much more quickly.

**How to reproduce it (as minimally and precisely as possible)**:

Try to axfr a domain from a IP that is not allowed. Eg:

$ dig @core.dns.ip.addr example.com. axfr

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:

docker image coredns/coredns:1.6.9

- Corefile:

(anonymized extract)

...
example.com {
  file /data/zones/example.com {
    transfer to 10.0.0.0/8
   # note 192.168.0.0/16 was added below but forgotten here
  } 
  acl {
    allow net 10.0.0.0/8
    allow net 192.168.0.0/16
    block
  } 
  log
}
...

- logs, if applicable:

(anonymized)
[INFO] 192.168.1.1:35509 - 19490 "AXFR IN example.com. tcp 59 false 65535" NOERROR qr,aa 9699 0.000554297s

Note the NOERROR, bug from dig it's actually SERVFAIL:

...
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 2627
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
...

- OS (e.g: `cat /etc/os-release`):

docker 19.03.11 under Alpine 3.12.0

- Others:

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Bad logging and w..." ]
>What happened:
>
>I set up a secondary that was trying to AXFR a domain from CoreDNS. I added the
>secondary to the ACLs but forgot to add it in the "transfer to ..." statement,
>so it failed. But the issue is HOW it failed.
>
>According to the CoreDNS logs, the issue is not on the CoreDNS side:
>
>[INFO] 192.168.1.1:35509 - 19490 "AXFR IN example.com. tcp 59 false 65535"
>NOERROR qr,aa 9699 0.000554297s
>
>However, dig and tcpdump reveal that CoreDNS is actually sending SERVFAIL
>instead of NOERROR!
>
>What you expected to happen:
>
> 1. CoreDNS logs should not lie about what rcode it returns! If it returns
>    SERVFAIL, it should log that. Debugging is unnecessarily complicated when
>    the logs can't be trusted.

sure, i guess we return the wrong value when we fail to send, that should be a simple fix.
Note that transfer will see some changes when:
https://github.com/coredns/coredns/pull/3972 is finalized.

> 2. I don't think SERVFAIL is not the appropriate rcode in this case anyway. I
>    haven't dug into the RFCs, but I suspect either NOTAUTH or maybe REFUSED is
>    appropriate. Running AXFRs with dig against several well known nameservers
>    (8.8.8.8, 1.1.1.1, various TLD name servers, ...), they all seem to use
>    NOTAUTH.

link to RFC text?

>$ dig @core.dns.ip.addr example.com. axfr
>
>Anything else we need to know?:
>
>Environment:
>
>  • the version of CoreDNS:
>
>docker image coredns/coredns:1.6.9
>
>  • Corefile:
>
>(anonymized extract)

luckily I run such a setup, otherwise anonymized config and setups would make it a lot
harder to replicate.

/Miek

--
Miek Gieben

**Comment by tsarna** [comment]
NOTAUTH is a red herring, sorry. Of course the servers I tested returned NOTAUTH because they were not authoritative. The dual meaning of that rcode is kind of annoying, apparently it only means Not Authorized in a DNSSEC context.

The actual correct code appears to be REFUSED. From RFC 1035 4.1.1, the definition of REFUSED specifically calls out not wishing to perform zone transfer as an example:

> Refused - The name server refuses to perform the specified operation for policy reasons.  For example, a name server may not wish to provide the information to the particular requester, or _a name server may not wish to perform a particular operation (e.g., zone transfer)_ for particular data.

(emphasis added). Later RFCS (eg 5936 for AXFR) don't seem to add anything here.

I set up a BIND 9 server to test this, and confirmed that it sends REFUSED in the case where it is authoritative but acls prohibit transfer.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Bad logging a..." ]
>NOTAUTH is a red herring, sorry. Of course the servers I tested returned
>NOTAUTH because they were not authoritative. The dual meaning of that rcode is
>kind of annoying, apparently it only means Not Authorized in a DNSSEC context.
>
>The actual correct code appears to be REFUSED. From RFC 1035 4.1.1, the
>definition of REFUSED specifically calls out not wishing to perform zone
>transfer as an example:
>
>    Refused - The name server refuses to perform the specified operation for
>    policy reasons. For example, a name server may not wish to provide the
>    information to the particular requester, or a name server may not wish to
>    perform a particular operation (e.g., zone transfer) for particular data.
>
>(emphasis added). Later RFCS (eg 5936 for AXFR) don't seem to add anything
>here.
>
>I set up a BIND 9 server to test this, and confirmed that it sends REFUSED in
>the case where it is authoritative but acls prohibit transfer.

ok, thanks. That sounds logical. Thanks for checking

**Comment by miekg** [comment]
so a deeper is that the *log* plugin runs before the server send a error reply - normally this is done by plugins but to make life easier on those the server takes care of sending errors (in some cases). So this can something lead to this - the current design make it hard to change this; although we may want to pull the log plugin into the server.
