### ISSUE TITLE
only forward to one of several upstream using forward plugin

### ISSUE THREAD

**Issue by ChenLingPeng** [coredns/coredns#3988]
**What happened**:

corefile:
```
.:53 {    
    errors    
    health    
    kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure       
          upstream       
          fallthrough in-addr.arpa ip6.arpa
          ttl 30    
    }    
    prometheus :9153    
    forward . upstream1 upstream2
    cache 30    
    loop    
    reload    
    loadbalance
}
```

DO `nslookup unexist.domain coredns_ip`, the tcpdump shows that coredns only connect to upstream1 and return NXDomain, and not try to connect to upstream2.

**What you expected to happen**:
when upstream1 return NXDomain, try resolve using upstream2

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.6.7
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by miekg** [comment]
upgrade to 1.7.0, it's fixed there

/label question
/label bug
/close

**Comment by ChenLingPeng** [comment]
Am I missing something? 
I tried 1.7.0, and find that every time I do a DNS query using nslookup, only one upstream will be select and to a query. 
even if the response if NXDomain, forward will not try another upstream.

I guess it is because [code here](https://github.com/coredns/coredns/blob/master/plugin/forward/forward.go#L160) don't check _Rcode_ and just return with the first chosen upstream response.

**Comment by ChenLingPeng** [comment]
hi @miekg , how can I reopen this issue?

**Comment by chrisohaver** [comment]
> What you expected to happen: when upstream1 return NXDomain, try resolve using upstream2

If the first server queried returns NXDOMAIN, that’s the answer. A second server is not queried. This is by design. A second server is only queried if the first server queried doesn’t answer at all.

**Comment by ChenLingPeng** [comment]
thanks @chrisohaver
