### ISSUE TITLE
Coredns not coming to ready state because of readiness probe failed.

### ISSUE THREAD

**Issue by akshaysharama** [coredns/coredns#3989]
**What happened**:

I've used IP-tables default policy(input and output chain) as drop. Deploying kubernetes setup using kubespray with ipvs.
coredns is not coming up because of readiness probe failed. 

I've tried telnet to the health and ready endpoint 
admin@localhost:~$ curl http://10.233.121.20:8080/health -vvv
*   Trying 10.233.121.20...
* TCP_NODELAY set
* Immediate connect fail for 10.233.121.20: Invalid argument
* Closing connection 0
curl: (7) Couldn't connect to server

Needed some info for the rules to be added in terms of coredns.

**What you expected to happen**:
coredns should be able to come up

**How to reproduce it (as minimally and precisely as possible)**:
1) Deploy coredns with k8s 
2) make iptables default policy as drop

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
1.6.0
- Corefile:
Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
- logs, if applicable:
1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:51:43.517136       1 trace.go:82] Trace[1025378621]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:51:13.516271398 +0000 UTC m=+14230.451049315) (total time: 30.00073884s):
Trace[1025378621]: [30.00073884s] [30.00073884s] END
E0705 14:51:43.517213       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:51:43.521652       1 trace.go:82] Trace[196203322]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:51:13.520304011 +0000 UTC m=+14230.455081904) (total time: 30.001284823s):
Trace[196203322]: [30.001284823s] [30.001284823s] END
E0705 14:51:43.521703       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
2020-07-05T14:51:44.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:51:54.803Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:52:04.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
I0705 14:52:14.517861       1 trace.go:82] Trace[1720504675]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:51:44.516847373 +0000 UTC m=+14261.451624807) (total time: 30.000962703s):
Trace[1720504675]: [30.000962703s] [30.000962703s] END
E0705 14:52:14.517894       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:52:14.519223       1 trace.go:82] Trace[769763140]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:51:44.518199345 +0000 UTC m=+14261.452975907) (total time: 30.000976729s):
Trace[769763140]: [30.000976729s] [30.000976729s] END
E0705 14:52:14.519269       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:52:14.522788       1 trace.go:82] Trace[399726999]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:51:44.522092188 +0000 UTC m=+14261.456869314) (total time: 30.000658452s):
Trace[399726999]: [30.000658452s] [30.000658452s] END
E0705 14:52:14.522819       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
2020-07-05T14:52:14.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:52:24.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:52:34.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:52:44.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
I0705 14:52:45.519616       1 trace.go:82] Trace[1482577672]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:52:15.518420634 +0000 UTC m=+14292.453198897) (total time: 30.001134661s):
Trace[1482577672]: [30.001134661s] [30.001134661s] END
E0705 14:52:45.520286       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:52:45.520920       1 trace.go:82] Trace[794757810]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:52:15.519533902 +0000 UTC m=+14292.454312549) (total time: 30.001153756s):
Trace[794757810]: [30.001153756s] [30.001153756s] END
E0705 14:52:45.521633       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:52:45.525207       1 trace.go:82] Trace[1006601536]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:52:15.524010871 +0000 UTC m=+14292.458789724) (total time: 30.001152659s):
Trace[1006601536]: [30.001152659s] [30.001152659s] END
E0705 14:52:45.525343       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
2020-07-05T14:52:54.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:53:04.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:53:14.805Z [INFO] plugin/ready: Still waiting on: "kubernetes"
I0705 14:53:16.522729       1 trace.go:82] Trace[73044502]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:52:46.521569384 +0000 UTC m=+14323.456349971) (total time: 30.001104849s):
Trace[73044502]: [30.001104849s] [30.001104849s] END
E0705 14:53:16.522800       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:53:16.523703       1 trace.go:82] Trace[2021478176]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:52:46.52285206 +0000 UTC m=+14323.457629569) (total time: 30.00082609s):
Trace[2021478176]: [30.00082609s] [30.00082609s] END
E0705 14:53:16.523778       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:53:16.526886       1 trace.go:82] Trace[1489563641]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:52:46.526090646 +0000 UTC m=+14323.460869259) (total time: 30.000759918s):
Trace[1489563641]: [30.000759918s] [30.000759918s] END
E0705 14:53:16.526909       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
2020-07-05T14:53:24.803Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:53:34.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:53:44.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
I0705 14:53:47.524961       1 trace.go:82] Trace[274153445]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:53:17.523411502 +0000 UTC m=+14354.458189741) (total time: 30.001444229s):
Trace[274153445]: [30.001444229s] [30.001444229s] END
E0705 14:53:47.525071       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:53:47.525883       1 trace.go:82] Trace[321755968]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:53:17.524525945 +0000 UTC m=+14354.459303956) (total time: 30.0013234s):
Trace[321755968]: [30.0013234s] [30.0013234s] END
E0705 14:53:47.526023       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:53:47.528646       1 trace.go:82] Trace[1113589084]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:53:17.527409691 +0000 UTC m=+14354.462186455) (total time: 30.001195817s):
Trace[1113589084]: [30.001195817s] [30.001195817s] END
E0705 14:53:47.529396       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
2020-07-05T14:53:54.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:54:04.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:54:14.803Z [INFO] plugin/ready: Still waiting on: "kubernetes"
I0705 14:54:18.527026       1 trace.go:82] Trace[341734843]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:53:48.525740256 +0000 UTC m=+14385.460519358) (total time: 30.001231762s):
Trace[341734843]: [30.001231762s] [30.001231762s] END
E0705 14:54:18.527234       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:54:18.527980       1 trace.go:82] Trace[959300889]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:53:48.526820416 +0000 UTC m=+14385.461598127) (total time: 30.001094767s):
Trace[959300889]: [30.001094767s] [30.001094767s] END
E0705 14:54:18.528061       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:54:18.531341       1 trace.go:82] Trace[1087317002]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:53:48.530120349 +0000 UTC m=+14385.464898204) (total time: 30.001185275s):
Trace[1087317002]: [30.001185275s] [30.001185275s] END
E0705 14:54:18.531384       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
2020-07-05T14:54:24.803Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:54:34.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:54:44.804Z [INFO] plugin/ready: Still waiting on: "kubernetes"
I0705 14:54:49.528708       1 trace.go:82] Trace[523826398]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:54:19.527628213 +0000 UTC m=+14416.462405023) (total time: 30.001007736s):
Trace[523826398]: [30.001007736s] [30.001007736s] END
E0705 14:54:49.528951       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:54:49.530141       1 trace.go:82] Trace[892651248]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:54:19.529452988 +0000 UTC m=+14416.464230855) (total time: 30.000638521s):
Trace[892651248]: [30.000638521s] [30.000638521s] END
E0705 14:54:49.530173       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:54:49.532949       1 trace.go:82] Trace[1617244369]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:54:19.531978 +0000 UTC m=+14416.466763708) (total time: 30.000914432s):
Trace[1617244369]: [30.000914432s] [30.000914432s] END
E0705 14:54:49.532981       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
2020-07-05T14:54:54.805Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:55:04.803Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2020-07-05T14:55:14.805Z [INFO] plugin/ready: Still waiting on: "kubernetes"
I0705 14:55:20.530855       1 trace.go:82] Trace[587685285]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:54:50.529309718 +0000 UTC m=+14447.464086769) (total time: 30.001488914s):
Trace[587685285]: [30.001488914s] [30.001488914s] END
E0705 14:55:20.530960       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:55:20.531706       1 trace.go:82] Trace[635978379]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:54:50.53077617 +0000 UTC m=+14447.465554630) (total time: 30.000890867s):
Trace[635978379]: [30.000890867s] [30.000890867s] END
E0705 14:55:20.531861       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
I0705 14:55:20.534615       1 trace.go:82] Trace[2117060549]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-07-05 14:54:50.533810921 +0000 UTC m=+14447.468589295) (total time: 30.000775326s):
Trace[2117060549]: [30.000775326s] [30.000775326s] END
E0705 14:55:20.534674       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout

- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Others:

**Comment by akshaysharama** [comment]
question

**Comment by zouyee** [comment]
```
Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
```
Network problem

**Comment by akshaysharama** [comment]
@zouyee okay thanks.
As i told we are making input and output chain default policy as drop, that's why networking issue.

we want to add some iptables/ipvs rules. can you please help ??

**Comment by TomatoAres** [comment]
This readiness http request is requested by kubelet on host,I curl manually
```sh
# curl -k https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0
[1] 9699
[root@mvlan-node2 ~]# {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services is forbidden: User \"system:anonymous\" cannot list resource \"services\" in API group \"\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "kind": "services"
  },
  "code": 403

```

Network is OK...
