### ISSUE TITLE
Strange load profile for CoreDNS  when using different clients

### ISSUE THREAD

**Issue by zanetworker** [coredns/coredns#3994]
**What happened**:
We run CoreDNS as a deployment with anti-affinities on Kubernetes which was okay until suddenly we find that requests are being directed only to one of the CoreDNS pods and not the others, this triggers our auto-scalers to scale-out the deployment but with no use, finally, the CoreDNS pod (that received all the requests) ends up OOMKilled. 

Here are  some observations: 
- It does not matter whether `IPtables` or `IPVS` are used both yield the same issue.
- The service endpoint rules are correct. 
- This behavior is only reproduced with some DNS clients not all, for example, testing with `dnsperf` I can reproduce the issue, with `host` or `dig` (used with 1000k queries/s)  I can not reproduce the issue and traffic is normally load-balanced.

**What you expected to happen**:
Traffic is load-balanced correctly no matter what clients are being used and no spikes in traffic. 

**How to reproduce it (as minimally and precisely as possible)**:
Execute `dnsperf` from within the cluster to external domain names (large queryfile with external domains) 
```bash
dnsperf -s <service-ip> -d queryfile
```
**Anything else we need to know?**:
`dnsperf` runs in a pod with default autopath / ndots settings:

```
search default.svc.cluster.local svc.cluster.local cluster.local ...region.compute.internal
options ndots:5
```

**Environment**:

- the version of CoreDNS: 1.6.3
- Corefile: 
```
.:8053 {
    errors
    log
    health
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        upstream
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    }
    prometheus 0.0.0.0:9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance round_robin
}
```

**P.S**: I know the issue is most probably not related to CoreDNS but feedback on where to look is appreciated :) Also I think the label should be changed to `Question` instead of bug.

**Comment by chrisohaver** [comment]
> requests are being directed only to one of the CoreDNS pods and not the others

In this event, are all the coredns pods reporting that they are "ready"?  Kubernetes will only forward clusterip destined traffic to ready pods.

**Comment by johnbelamaric** [comment]
`dnsperf` will re-use the same socket which probably causes this behavior. Try the `-c` option. See https://linux.die.net/man/1/dnsperf

**Comment by johnbelamaric** [comment]
(also this is not a CoreDNS issue)

**Comment by zanetworker** [comment]
@johnbelamaric Thanks for the hint
