### ISSUE TITLE
Resolve any name

### ISSUE THREAD

**Issue by Falci** [coredns/coredns#4009]
I'd like to build a web service like a domain parking page. Multiples domains will have their NS pointing to my `ns.parking.example.com`, where I'm running the CoreDNS.

Is it possible to catch any domain query and respond the same A record?
```
. {
  file db.master
}
```
```
$TTL    3600
@       IN      SOA     . root. (3 3600 300 3600 300 ) 
        IN      NS      ns1
        IN      A       12.34.56.78
*       IN      A       12.34.56.78
```

I don't know the name of all domains pointing to my NS.

**Comment by dilyevsky** [comment]
I think you should be able to do that with a [rewrite rules](https://coredns.io/plugins/rewrite/) such as:

```
rewrite name exact * internal.example.com
```

Then just add `hosts` stanza for the internal name mapping it to a fixed IP. I haven't personally tried this though...

Another option could be using [template](https://coredns.io/plugins/template/) plugin.
