### ISSUE TITLE
middleware/cache minimum cache TTL is now 0 should be 5?

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#401]
Setting "cache" before had the effect, that records could be cached using the record TTL with a max of 3600 or 1800. This seems to now default to 0.

"cache" or "cache 0" result in all TTLs on answers being 0.
This should at least be the minimum of 5 or else it might break other DNS software not allowing TTLs under 5s.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] middleware/cache mi..." ]

> Setting "cache" before had the effect, that records could be cached using the record TTL with a max of 3600 or 1800. This seems to now default to 0.

I'm not seeing this.

> "cache" or "cache 0" result in all TTLs on answers being 0.
> This should at least be the minimum of 5 or else it might break other DNS software not allowing TTLs under 5s.

Yes, that could be bad.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
It seems this was another going down the rabbit hole of strange usage to really get the bugs out.

So I have a zonefile for example.com and a symlink to example.com from example.net.
With my config this basically serves example.com entries at example.net.
Example.com queries are fine and have the right TTL.
Example.net queries are fine except the TTL is always 0.

This works fine without the cache directive and with the auto directive, but it seems it falls over with setting the cache to "cache" or "cache 0".

Sidenote: This is done due to the issue with using the rewrite middleware and chromium based browsers. #383

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/cach..." ]

> It seems this was another going down the rabbit hole of strange usage to really get the bugs out.
> 
> So I have a zonefile for example.com and a symlink to example.com from example.net.
> With my config this basically serves example.com entries at example.net.
> Example.com queries are fine and have the right TTL.
> Example.net queries are fine except the TTL is always 0.
> 
> This works fine without the cache directive and with the auto directive, but it seems it falls over with setting the cache to "cache" or "cache 0".

Yes, "cache 0" should be doing something more sensible than setting TTLs to 0,
using the minTTL of the message seems more sensible (i.e. no max).

With just using "cache" I can't get this "ttl 0" behavior btw.

/Miek

## 

Miek Gieben
