### ISSUE TITLE
Add policy plugin to plugin.cfg

### ISSUE THREAD

**Issue by JoachimGross** [coredns/coredns#4019]
**What would you like to be added**:
Our infrastructure team use the "original" plugin from this git repo.
We want to use the policy plugin.
To be able to use the policy plugin we would need the https://github.com/coredns/policy plugin enabled in the [plugin.cfg](https://github.com/coredns/coredns/blob/master/plugin.cfg)

**Why is this needed**:
We want to use the CoreDNS policy plugin in Kubernetes. 

*Question:* Would it be possible to add the policy plugin to https://github.com/coredns/coredns/blob/master/plugin.cfg ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Add policy plugin..." ]
>What would you like to be added:
>Our infrastructure team use the "original" plugin from this git repo.
>We want to use the policy plugin.
>To be able to use the policy plugin we would need the https://github.com/
>coredns/policy plugin enabled in the plugin.cfg
>
>Why is this needed:
>We want to use the CoreDNS policy plugin in Kubernetes.
>
>Question: Would it be possible to add the policy plugin to https://github.com/
>coredns/coredns/blob/master/plugin.cfg ?

we've made it easy to compile and run our own coredns with a custom set of plugins.

See https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/

**Comment by JoachimGross** [comment]
Thank you for your answer. 
I will ask my infrastructure team to build their own CoreDNS with the plugin enabled.

**Comment by chrisohaver** [comment]
@JoachimGross curious to learn more about your use case, if you can share.
