### ISSUE TITLE
middleware/log log reloads

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#402]
Log reloads from file changes for auto and file middlewares.

Might be helpful info, when actual changes went live.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] middleware/log log ..." ]

> Log reloads from file changes for auto and file middlewares.
> 
> Might be helpful info, when actual changes went live.

What do you mean with "live"?

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
When changes of zones get picked up by coredns either via polling or via fsnotify and then are available to be served. So the new version is served.

**Comment by stp-ip** [comment]
There are log messages, but due to #404 or something similar it didn't show up. Ok next time I stop work earlier and dig into the code to verify before. Sorry for the hassle.
