### ISSUE TITLE
Allow specification of SOA parameters

### ISSUE THREAD

**Issue by ajf** [coredns/coredns#4020]
**What would you like to be added**:

We would like to be able to change the SOA data for refresh, retry, expiration.  We generally use kubernetai (kubernetes) plugin so it'd be most useful for that.

I think this is the code here that statically defines it:
   https://github.com/coredns/coredns/blob/master/plugin/backend_lookup.go#L456

**Why is this needed**:

We would like to use auth_zone functionality in unbound to serve CoreDNS as an authoritative zone, and, without NOTIFY functionality for kubernetes plugin, we need to lower the refresh time to < 5 seconds.

If NOTIFY is supported, that'd obviously be preferable, but we have high churn so refresh works fine to reduce the number of AXFR/IXFRs.

**Comment by chrisohaver** [comment]
Seems reasonable.  

I expect NOTIFY will be coming to _kubernetes_ zone transfers in 1.8.0.   It was implemented in #3972. That PR was reverted because it was prematurely merged to the master branch, but I expect it will be reopened and merged for the 1.8.0 release.  However, I'm not sure ATM if the new transfer/notify plugin will immediately work with the _kubernetai_ plugin - specifically becuse the way that _kubernetai_ allows multiple instances in a server block that can fall through to each other (to support multiple clusters in a single zone).

**Comment by miekg** [comment]
I'm apprehensive with exposing config knobs for this, as this data should ideally live in
the backend.

As is done (sort of) with the Serial https://github.com/coredns/coredns/blob/master/plugin/backend_lookup.go#L475

Implementing notifies in k8s is much cleaner solution.

**Comment by chrisohaver** [comment]
> I'm apprehensive with exposing config knobs for this, as this data should ideally live in
the backend.

IIUC, the backend in this case being the kubernetes cluster.  E.g.  by having the SOA config knobs live in a k8s custom resource, that the kubernetes plugin reads.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Allow specifi..." ]
>    I'm apprehensive with exposing config knobs for this, as this data should
>    ideally live in
>    the backend.
>
>IIUC, the backend in this case being the kubernetes cluster. E.g. by having the
>SOA config knobs live in a k8s custom resource, that the kubernetes plugin
>reads.

yes something like that
but requires some speccing out, etc.

**Comment by ajf** [comment]
It seems like it'd be as simple as adding `refresh x` to the plugin configuration for the zone in the kubernetes plugin?   (I do get NOTIFY is a much better solution here, if it could be supported with kubernetai)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Allow specifi..." ]
>It seems like it'd be as simple as adding refresh x to the plugin configuration
>for the zone in the kubernetes plugin? (I do get NOTIFY is a much better
>solution here, if it could be supported with kubernetai)

yes, but as explained, that's a very hacky way to do and we're not going to go that route.

**Comment by chrisohaver** [comment]
> yes, but as explained, that's a very hacky way to do and we're not going to go that route.

To expand on that a bit: In the context of Kubernetes it is awkward/dangerous for admins to need to dive into a CoreDNS configuration file to configure cluster service discovery behavior.  It would fit better in the Kubernetes ecosystem to tool as much of the CoreDNS configuration as we can using something along the lines of Kubernetes' Custom Resource Definitions - thus enabling control via the Kubernetes API.  In retrospect, most of the existing options in the _kubernetes_ plugin could be done this way, and when/if implementing CRDs, we would probably want to migrate the existing options over that can be.  Implementing these options as CRDs could allow for granular K8s managed access control to these settings.
