### ISSUE TITLE
check if metric is registererd

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4024]
See https://github.com/coredns/coredns/pull/4021 We seem to be forgetting to *register* metrics (too often).

The exiting metrics naming test (`test/metric_naming_test.go`) should be extended to test for this as well - at least assuming it's easy enough to do so

**Comment by miekg** [comment]
See this https://github.com/thanos-io/thanos/issues/2102
We need to fix our declaration and registration. I.e. the fix the code not the test

**Comment by chrisohaver** [comment]
>  I.e. the fix the code not the test

I have opted to use `promauto` in some other (simpler) projects.
