### ISSUE TITLE
issue with cache serve_stale

### ISSUE THREAD

**Issue by ltagliamonte-dd** [coredns/coredns#4028]
In my Kubernetes setup coreDNS is installed as daemonset and configured as primary DNS server instead of the default 
 clusterDNS:
```
cat /etc/resolv.conf 
nameserver 192.168.0.1
nameserver 172.30.224.10
```
On all nodes `192.168.0.1` is reserved to a CoreDNS instance.
We also leverage Consul for multi cluster discovery, each node runs a consul-agent a well responding on port 8600.

CoreDNS is configured to proxy all requests to `prod.ddsd` to the local consul-agent.

**What happened**:

This morning after staging test we made the following change to the cache plugin for the consul domain:
from this:
```
        cache 30
```
to this:
```
        cache 30 {
          serve_stale
        }
```

We tested the stale config in staging using `kill -STOP <CONSUL_PID>` and it is working as expected.

After the prod rollout some of our service **(not all)** started to record the following exception:
```
<my-service>.service.prod.ddsd UnknownHostException
```
We solved the issue rolling back the config. Before rolling back I was able to perform a couple of `dig` cmd on one of the affected hosts:
```
root@my-service-65d7df94d4-z99r4:/home# cat /etc/resolv.conf 
nameserver 192.168.0.1
nameserver 172.30.224.10
search my-service.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```
```
root@my-service-65d7df94d4-z99r4:/home# dig @192.168.0.1 my-service2.service.prod.ddsd
; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> @192.168.0.1 my-service2.service.prod.ddsd
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 36780
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: b47773c4d74be425 (echoed)
;; QUESTION SECTION:
;my-service2.service.prod.ddsd.	IN A
;; AUTHORITY SECTION:
prod.ddsd.		0	IN	SOA	ns.prod.ddsd. hostmaster.prod.ddsd. 1595869306 3600 600 86400 30
;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Mon Jul 27 18:00:49 UTC 2020
;; MSG SIZE  rcvd: 156
```

```
root@my-service-65d7df94d4-z99r4:/home# dig @172.30.153.92 -p 8600 my-service2.service.prod.ddsd
; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> @172.30.153.92 -p 8600 my-service2.service.prod.ddsd
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9452
;; flags: qr aa rd; QUERY: 1, ANSWER: 45, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;my-service2.service.prod.ddsd.	IN A
;; ANSWER SECTION:
my-service2.service.prod.ddsd.	10 IN A	172.30.162.195
my-service2.service.prod.ddsd.	10 IN A	172.30.176.129
my-service2.service.prod.ddsd.	10 IN A	172.30.127.94
my-service2.service.prod.ddsd.	10 IN A	172.30.147.147
my-service2.service.prod.ddsd.	10 IN A	172.30.90.252
my-service2.service.prod.ddsd.	10 IN A	172.30.109.9
my-service2.service.prod.ddsd.	10 IN A	172.30.172.228
my-service2.service.prod.ddsd.	10 IN A	172.30.61.29
my-service2.service.prod.ddsd.	10 IN A	172.30.105.91
my-service2.service.prod.ddsd.	10 IN A	172.30.187.179
my-service2.service.prod.ddsd.	10 IN A	172.30.76.242
my-service2.service.prod.ddsd.	10 IN A	172.30.33.31
my-service2.service.prod.ddsd.	10 IN A	172.30.108.6
my-service2.service.prod.ddsd.	10 IN A	172.30.43.74
my-service2.service.prod.ddsd.	10 IN A	172.30.176.175
my-service2.service.prod.ddsd.	10 IN A	172.30.135.14
my-service2.service.prod.ddsd.	10 IN A	172.30.11.1
my-service2.service.prod.ddsd.	10 IN A	172.30.164.225
my-service2.service.prod.ddsd.	10 IN A	172.30.32.250
my-service2.service.prod.ddsd.	10 IN A	172.30.85.24
my-service2.service.prod.ddsd.	10 IN A	172.30.164.247
my-service2.service.prod.ddsd.	10 IN A	172.30.123.112
;; Query time: 0 msec
;; SERVER: 172.30.153.92#8600(172.30.153.92)
;; WHEN: Mon Jul 27 18:01:40 UTC 2020
;; MSG SIZE  rcvd: 787
```
As we can see the CoreDNS is unresponsive (first dig) meanwhile the ConsulAgent correctly responds (second dig).

**How to reproduce it (as minimally and precisely as possible)**:
Atm I can't reproduce the issue in staging (they are exactly the same setup), would love your help.
The reload logs look fine, I didn't record any error and I already made sure that neither coreDNS or consul_agent were under resource duress.

**Environment**:

- the version of CoreDNS: 1.6.7
- Corefile:
```
    .:53 {
        errors
        health :8081 {
          lameduck 5s
        }
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        cache 30
        loadbalance
        reload
    }
    prod.ddsd {
      errors
      cache 30
      forward . 127.0.0.1:8600
    }
```
- logs, if applicable (the zone prod.ddsd got added via `4e5e230dba9095f85a793491f0a4f694` that's why it isn't present in the very beginning of the log file):
```
.:53
[INFO] plugin/reload: Running configuration MD5 = 4e2f6a92d5c13165f31398dd6949fee2
CoreDNS-1.6.7
linux/amd64, go1.13.6, da7f65b
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 5s
[INFO] plugin/reload: Running configuration MD5 = 4e5e230dba9095f85a793491f0a4f694
[INFO] Reloading complete
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 5s
[INFO] plugin/reload: Running configuration MD5 = 5066688528196540eefafb408701f1b2
[INFO] Reloading complete
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 5s
[INFO] plugin/reload: Running configuration MD5 = 4e5e230dba9095f85a793491f0a4f694
[INFO] Reloading complete
```
- OS (e.g: `cat /etc/os-release`): `container image: k8s.gcr.io/coredns:1.6.7`

**Comment by chrisohaver** [comment]
Before diving in, have you evaluated [NodeLocal DNS cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/)?  It's a stable/sanctioned k8s solution that deploys a local caching DNS on each node, routing queries either directly upstream, or to the cluster DNS via TCP for the cluster domain (e.g. cluster.local.).

**Comment by ltagliamonte-dd** [comment]
@chrisohaver thank you for the suggestion, NodeLocal DNS look exactly like my setup, we are running a coreDNS daemonset + the clusterDNS (as fallback) since k8s 1.10.
Will definitely consider NodeLocal DNS for the next cluster iteration.
The issue I've opened doesn't seems related to the setup imho

**Comment by chrisohaver** [comment]
> NodeLocal DNS look exactly like my setup

It is similar in concept - but it's not exactly the same solution.  NodeLocal cache runs coredns on each node also, but as the name alludes they only do caching/forwarding, they don't make connections to the k8s API.  In your solution, it appears that CoreDNS instances on every node connect to the kubernetes api, which puts considerably more strain on the API.

Back to the issue reported: There was a cache bug in 1.6.7  related to the `serve_stale` option and caching negative of responses; issue #3586 fixed in 1.6.9 by #3744. I don't have a clear idea of whats going on in your cluster, but it could be related.

**Comment by ltagliamonte-dd** [comment]
@chrisohaver thank you for pointing me to the the issue #3586 could be related but in my config the cache that received the `stale` config was the one for the dedicated domain `prod.ddsd` that shouldn’t receive any query that results in NXDOMAIN.
Will try to reproduce the issue in staging but look not related, am i missing something ?

**Comment by ltagliamonte-dd** [comment]
@chrisohaver i can't repro the issue following the steps in #3586 what i have noticed instead that using serve_stale for the dedicated domain results in the pre-fetch "being late" as you can see:
```
while true; do dig my-service.service.staging.ddsd; sleep 1; done
```
produces 2 times responses with TTL=0:
```
; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> my-service.service.staging.ddsd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42358
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: f4ef8ca6d1b12ded (echoed)
;; QUESTION SECTION:
;my-service.service.staging.ddsd. IN A

;; ANSWER SECTION:
my-service.service.staging.ddsd. 1 IN	A 10.4.184.19

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Jul 28 16:36:16 UTC 2020
;; MSG SIZE  rcvd: 139


; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> my-service.service.staging.ddsd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43944
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 101938c5e802fbe6 (echoed)
;; QUESTION SECTION:
;my-service.service.staging.ddsd. IN A

;; ANSWER SECTION:
my-service.service.staging.ddsd. 0 IN	A 10.4.184.19

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Jul 28 16:36:17 UTC 2020
;; MSG SIZE  rcvd: 139


; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> my-service.service.staging.ddsd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41997
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: b207b40e5765b608 (echoed)
;; QUESTION SECTION:
;my-service.service.staging.ddsd. IN A

;; ANSWER SECTION:
my-service.service.staging.ddsd. 0 IN	A 10.4.184.19

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Jul 28 16:36:18 UTC 2020
;; MSG SIZE  rcvd: 139


; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> my-service.service.staging.ddsd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64392
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: e5741cad1cbffc01 (echoed)
;; QUESTION SECTION:
;my-service.service.staging.ddsd. IN A

;; ANSWER SECTION:
my-service.service.staging.ddsd. 9 IN	A 10.4.184.19

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Jul 28 16:36:19 UTC 2020
;; MSG SIZE  rcvd: 139
```
the TTL of the record my-service.service.staging.ddsd. is 10s.
Could it be we have a race condition between the prefetch and the DNS request?

**Comment by chrisohaver** [comment]
> could be related  ... look not related ...

IMO, it's worth trying anyways. 

When receiving an NXDOMAIN from the daemonset instance of CoreDNS, what response do you get if you make the same query against the consul agent from the node itself via 127.0.0.1:8600?

**Comment by chrisohaver** [comment]
> the pre-fetch "being late"

This implies that the daemonset instance of coredns is getting some delay in response from the local consul agent.

**Comment by ltagliamonte-dd** [comment]
should the pre-fetch happen before the TTL runs to 0?

**Comment by chrisohaver** [comment]
> should the pre-fetch happen before the TTL runs to 0?

You mean the stale prefetch... No. I don't think that makes sense.

When receiving an NXDOMAIN from the daemonset instance of CoreDNS, what response do you get if you make the same query against the consul agent from the node itself via 127.0.0.1:8600?

**Comment by ltagliamonte-dd** [comment]
I posted the response from coreDNS and consul agent in my very first comment.
Consul agent correctly responds meanwhile coreDNS stays stuck with NXDOMAIN.
I hit multiple times both coreDNS and consul-agent with `dig`. I posted just 1 iteration to keep the bug description short.

About the pre-fetch feature I was expecting that the prefetch would happen like N-ttl seconds before the entry expires in the cache. But i understand that this kind of logic would complicate entries eviction

**Comment by chrisohaver** [comment]
> I posted the response from coreDNS and consul agent in my very first comment.

Not really.
You posted `dig @172.30.153.92 -p 8600 my-service2.service.prod.ddsd` from what looks like a Pod
I asked to test `dig @127.0.0.1 -p 8600 my-service2.service.prod.ddsd` from the node itself.

**Comment by ltagliamonte-dd** [comment]
it is the same endpoint I was testing from a container on the same server that doesn't have hostNetwork=True.
CoreDNS and consul-agent run with hostNetwork.

**Comment by chrisohaver** [comment]
> it is the same endpoint ...

yes, I know it's the same endpoint, but it's a different interface. Just trying to eliminate all possibilities.

> About the pre-fetch feature I was expecting that the prefetch would happen like N-ttl seconds before the entry expires ...

There is the "prefetch" option, which pre-fetches cache items _before_ they expire (by percentage of TTL). This is not enabled by default.
There is also the stale cache "refresh", which only happens once a stale cache item is served to a client.

**Comment by ltagliamonte-dd** [comment]
> There is the "prefetch" option, which pre-fetches cache items _before_ they expire (by percentage of TTL). This is not enabled by default.
> There is also the stale cache "refresh", which only happens once a stale cache item is served to a cl

Oh thank you @chrisohaver didn't notice there was such option!
Do you have any other idea of what can it be this problem i'm facing with `serve_stale` ?

**Comment by ltagliamonte-dd** [comment]
@chrisohaver i tried to repo the issue in my staging environment, creating NXDOMAIN replies using:
```
while true; do dig my-nonexistend-service.service.staging.ddsd; sleep 0.1; done
```
and then trying to resolve an existing service and it does work, my issue is different from the one in #3586

**Comment by ltagliamonte-dd** [comment]
updated to 1.6.9 can't reproduce this issue anymore.
