### ISSUE TITLE
middleware/cache cache is not invalidated on reloading operations

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#403]
Reloading zones from file, auto middleware and others should invalidate the cache.
It seems counterintuitive that a reload is available, but the cache still serves the old zone aka stale data even up to 3600s.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] middleware/cache ca..." ]

> Reloading zones from file, auto middleware and others should invalidate the cache.
> It seems counterintuitive that a reload is available, but the cache still serves the old zone aka stale data even up to 3600s.

No, these things are orthogonal to each other. If your local instance reads data
from disk _and_ you cache this in the same instance you get this behavior.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
I can't see a way were not invalidating the cache on reload makes sense. Would love a use-case, why that would make sense.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/cach..." ]

> I can't see a way were not invalidating the cache on reload makes sense. Would love a use-case, why that would make sense.

Well, there is no correlation between _cache_ and _file_, there are separate
middlewares and don't want to create a connection between them.

I think a better question is: why do you want caching and file/auto middleware
to be enabled for the same zones?

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
I see the reasoning there. Still should probably be clarified in the docs.

Cache is basically for the proxy, which is therefore served for all zones.
So cache will pick up the file zones also.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/cach..." ]

> I see the reasoning there. Still should probably be clarified in the docs.

Ack. Feel free to propose some text. I pondered adding wording like this (don't
do bla), but I don't want to sound to paternalistic. In the end the user
decides how to use the software.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
Something along the lines of "Reloading will not invalidate the cached items. It might still serve stale data until the cache expires." Will push that into my do-docs-backlog.
