### ISSUE TITLE
Wildcard records do not resolve correctly when using the Route53 plugin

### ISSUE THREAD

**Issue by imunic** [coredns/coredns#4035]
**What happened**: Trying to resolve wildcard records while using the route53 plugin results in a NXDOMAIN response.

**What you expected to happen**: Wildcard records to be resolved and the correct response to be returned.

**How to reproduce it (as minimally and precisely as possible)**: Create a private hosted zone called `okd.myc.io`, create either a A or CNAME wildcard record with the following name '*.apps.okd.myc.io' and any value depending on the record type, configure CoreDNS, start it and try to resolve the record using:

`dig -p 1053 @localhost test.apps.okd.myc.io`

**Anything else we need to know?**: Specific records work great, wildcards do not.

**Environment**: 

- the version of CoreDNS: 1.7.0
- Corefile:

```
(common) {
    errors
    log . {
      class denial error
    }
    nsid
}

okd.myc.io:1053 {
    import common
    route53 okd.myc.io.:PRIVATE_HOSTED_ZONE_ID {
      aws_access_key AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
    }
}

```

- logs, if applicable:

```
[INFO] [::1]:52256 - 23778 "A IN test.apps.okd.myc.io. udp 51 false 4096" NXDOMAIN qr,aa,rd 139 0.000084316s
[INFO] [::1]:57990 - 3275 "CNAME IN test.apps.okd.myc.io. udp 51 false 4096" NXDOMAIN qr,aa,rd 139 0.000071072s
```

- OS (e.g: `cat /etc/os-release`): Fedora CoreOS 32.20200715.3.0

- Others: Tested on Fedora CoreOS running CoreDNS 1.7.0 using podman and CoreDNS 1.7.0 binary running on macOS. AWS hosted zone name is `okd.myc.io`, tested with A and CNAME record with name `*.apps.okd.myc.io` and respective value `10.0.255.3`, `lb-web-pub.fsn1.okd.myc.io`.

And also thank you for building this awesome tool!

**Comment by yongtang** [comment]
Think the issue is in line:
https://github.com/coredns/coredns/blob/master/plugin/route53/route53.go#L151

Should be a string instead as `strings.Index(s, substr string)` expect substr.

Created a PR #4038 for the fix.
