### ISSUE TITLE
log.Debugf is silent even when `debug` plugin is loaded

### ISSUE THREAD

**Issue by ashtw** [coredns/coredns#4036]
**What happened**:

The `debug` plugin is loaded but calls to log.Debugf() in my plugin are silent

**What you expected to happen**:

I expected to see log.Debugf() messages in program output

**How to reproduce it (as minimally and precisely as possible)**:

Enable `debug` plugin and look for output from log.Debugf()

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: master branch

**Comment by ashtw** [comment]
See pull request [4037](https://github.com/coredns/coredns/pull/4037)

**Comment by miekg** [comment]
see https://github.com/coredns/coredns/pull/4007
