### ISSUE TITLE
middleware/auto reloading of files with symlinks has issues

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#404]
Running coredns on kubernetes with a sidecar container (git-sync), which does atomic switching of git revs.
This is done by switching a symlink. It seems that something with this setup is preventing reloading of zones.
Neither notifies nor the timeout seems to pick up changes.
Sidenote: I tested it locally without symlinks and the config seems to work fine.
I am still investigating, but wanted to start logging the issue.

I assume the same issue is available in the file middleware.

Version: master

**Comment by miekg** [comment]
ah cool test. Yes, totally possible these are not picked up. Right now we check for writes and creation of files. This is a write in the parent directory, not sure if those will be seen correctly by _fsnotify_

**Comment by stp-ip** [comment]
But then shouldn't the timeout poll the changes? This doesn't seem to happen either.

**Comment by stp-ip** [comment]
Interesting observation:
New zones/files are inserted and therefore picked up fine. It seems there is only an issue with reloading.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> Interesting observation:
> New zones/files are inserted and therefore picked up fine. It seems there is only an issue with reloading.

So what are you expecting here? A new symlink is indeed picked after a rescan of
the directory. But then you change to original file and expect the symlinked
zone to be re-read as well? I'm not sure than can even be done in the case of
symlinks...

**Comment by stp-ip** [comment]
The setup is:
zones -> rev-XXXX
When adding a new zone file (either symlink or raw file) it gets inserted.
When changing a zone with a new rev it doesn't get reloaded.
When changing a zone manually (for testing) within the same rev-XXXX zone doesn't get reloaded.

I would in general expect all file changes to be picked up. It shouldn't matter if the parent directory is symlinked or a file itself is.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> The setup is:
> zones -> rev-XXXX
> When adding a new zone file (either symlink or raw file) it gets inserted.
> When changing a zone with a new rev it doesn't get reloaded.
> When changing a zone manually (for testing) within the same rev-XXXX zone doesn't get reloaded.

I think we can follow the symlink and set the notify on the symlink target,
instead of the symlink it self. Pondering however what happens when you rename
the symlink... I think that should automatically work in the rescan phase.

hmm...

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
What git-sync is doing is it removes the symlink and then recreates it.
And as I said this doesn't seem to be picked up in the rescan phase.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> What git-sync is doing is it removes the symlink and then recreates it.
> And as I said this doesn't seem to be picked up in the rescan phase.

yes, because it existed and then exists again, under the same name - so
currently that means "no change" for scan phase - we could be slightly smarter
here - maybe.

**Comment by stp-ip** [comment]
Ok so the issue here is that within the rescan phase the changes are not picked up as it is only checking the name not the name and timestamp.
Additionally due to the usage of symlinks in the parent directory (maybe for symlinks in general) fsnotify events are not triggered where they should.

First fix would probably be to use timestamp/modification time and name to pick up changes.

Additionally the symlink issue might be similar to the issue concerning hugo and git-sync https://github.com/kubernetes/git-sync/issues/15

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> Ok so the issue here is that within the rescan phase the changes are not picked up as it is only checking the name not the name and timestamp.
> Additionally due to the usage of symlinks in the parent directory (maybe for symlinks in general) fsnotify events are not triggered where they should.
> 
> First fix would probably be to use timestamp/modification time and name to pick up changes.

Yep.

> Additionally the symlink issue might be similar to the issue concerning hugo and git-sync https://github.com/kubernetes/git-sync/issues/15

Might be. In general fsnotify is pretty shit - I had a DIR-level notify, but
that works unreliable (and does not recursive in dirs - so you need to handle
that as well). In the end a per-file fsnotify was better. But I need to think
how symlink (and symlink chains) are supposed to work in this scenario.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> Ok so the issue here is that within the rescan phase the changes are not picked up as it is only checking the name not the name and timestamp.
> Additionally due to the usage of symlinks in the parent directory (maybe for symlinks in general) fsnotify events are not triggered where they should.
> 
> First fix would probably be to use timestamp/modification time and name to pick up changes.

It shouldn't actually; because that where the fsnotify events for the file in
question come in

**Comment by stp-ip** [comment]
Ok I thought the rescan was more like a fallback action instead of a complementary thing.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> Ok I thought the rescan was more like a fallback action instead of a complementary thing.

It is a work around of fsnotify on the directory level not working. If that
would work it would be rightly picking up all your changes.

Maybe in the end it makes sense to entirely give up on fsnotify and only rescan
every 30s (and take timestamp [or hash the file's content]) to pick up
changes.

/Miek

## 

Miek Gieben

**Comment by miekg** [comment]
I might actually drop symlinks altogether, as `path/filepath.Walk` does not follow them anyway...

**Comment by miekg** [comment]
Interestingly a symlinked zone does get picked up by `Walk()`

**Comment by miekg** [comment]
Does https://github.com/miekg/coredns/pull/406 help?

**Comment by stp-ip** [comment]
A symlinked zones does get picked up, but no further changes of that zone will. As far as I saw in my testing.

Will check out the PR later tonight.

**Comment by miekg** [comment]
`touch -h` is probably going to be your friend here.

**Comment by stp-ip** [comment]
It seems that this is fixed now. Am I right that you dropped fsnotify? Changes are picked up during the "fallback" fs rescan.
Tested parent symlink, symlinked file, symlink change, symlinked file change and symlink within a parent symlink.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/auto..." ]

> It seems that this is fixed now. Am I right that you dropped fsnotify? Changes are picked up during the "fallback" fs rescan.

No fsnotify is still watching a file for changes and reloads uncondionally.
(should check the SOA as an optimization and then not reload - should be an easy
fix though)

> Tested parent symlink, symlinked file, symlink change, symlinked file change and symlink within a parent symlink.

Good to hear.

/Miek

## 

Miek Gieben
