### ISSUE TITLE
plugin/cache prefetch not working

### ISSUE THREAD

**Issue by dogzzdogzz** [coredns/coredns#4045]
**What happened**:
coredns seems only send dns query to upstream server when i nslookup some domain name, e.g. abc.com (TTL 60s), 
once nslookup stopped, coredns with below config was supposed to still prefetch abc.com record within 1 hr but actually it never query abc.com again.

- k8s: EKS 1.16
- the version of CoreDNS: 1.6.6, 1.7.0
- Corefile:
```
.:53 {
    log
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    loadbalance
    prometheus :9153
    forward . /etc/resolv.conf {
      prefer_udp
    }
    cache 30 {
      success 9984 30
      denial 9984 5
      prefetch 1 1h 50%
    }
    reload
    loop
}
```

**Comment by miekg** [comment]
we only prefetch when the are queries for it landing within the TTL. *cache* currently doesn't do what you describe.
