### ISSUE TITLE
 SRV: dns: overflow unpacking uint32

### ISSUE THREAD

**Issue by aphuang2013** [coredns/coredns#4046]
**What happened**:
[ERROR] plugin/errors: 2

**What you expected to happen**:
the dig return the SRV record but I expected no error entry in the log 

**How to reproduce it (as minimally and precisely as possible)**:
query AD DNS

**Anything else we need to know?**:
there were 46 SRV records returned

**Environment**:

- the version of CoreDNS: 1.6.9
- Corefile:
- logs, if applicable:
Aug 06 05:43:16 dcs1-dnssec coredns[26900]: [ERROR] plugin/errors: 2 _ldap._tcp.dc._msdcs.xx.xx.xx. SRV: dns: overflowing header size
- OS (e.g: `cat /etc/os-release`): "18.04.4 LTS (Bionic Beaver)"
- Others:

**Comment by zouyee** [comment]
https://github.com/coredns/coredns/issues/3305
