### ISSUE TITLE
middleware/auto reloading of zone symlinks not updating zone

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#405]
Config:
```
.:5053 {
  bind 127.0.0.2
  auto {
    directory zones/ (.*) {1}
    transfer to *
  }
  errors stderr
  log stdout
}
```
Example.net is symlinked to example.com.
When Example.com is changed the log provides the reload message:
```
2016/11/08 09:13:43 [INFO] Successfully reloaded zone `example.com.'
2016/11/08 09:13:43 [INFO] Successfully reloaded zone `example.com.'
```
Additionally example.com is now serving the updated zone. But example.net is still serving stale data.

Should reloading the zone use the zone declaration provided via the regexp not the SOA?

**Comment by miekg** [comment]
See #404
