### ISSUE TITLE
monitoring: add top talkers metrics

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4056]
add a metrics that exposed the top 10 talkers for various things. Incoming qps would be an first choice. This adds unbounded label (source IP), but there will only ever be 10 metrics, so it should OK?

If this is a sensible idea we can extend it to other things we find interesting as well.

**Comment by yongtang** [comment]
+1 👍 , Metrics for everything is very hard for DNS (the lookup table could easily be filled up quickly), but top-10 metrics would make a lot of sense.

Or, to an extent, it could be top-k to allow users making a reasonable adjustment depending on their needs and environment?

**Comment by miekg** [comment]
I'm worried about label cardinality (even w/ this approach)

**Comment by zouyee** [comment]
Regarding this issue, we can extend it a bit and consider how to feed back the current running status of dns, similar to telemetry function or API?

**Comment by miekg** [comment]
I also thought of having a status page with this info. But status pages
haven't been standardized yet in the oss world.

Open to suggestions however
