### ISSUE TITLE
REQUEST: New membership for zouyee

### ISSUE THREAD

**Issue by zouyee** [coredns/coredns#4057]
I have been following the coredns community for about two years. Since 2019, I have participated in community contributions and actively participated in the tracking and resolution of community problems. Currently, I hope to join the community and focus on the direction of dns in `serverless/mircoservice` and performance testing.

COPY FROM KUBERNETES

### Requirements

- [x]  Enabled [two-factor authentication] on their GitHub account

- [x] Have made multiple contributions to the project or community.  Contribution may include, but is not limited to:

    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub

- [x] Have read the [contributor guide](https://github.com/coredns/coredns/blob/master/CONTRIBUTING.md)

- [x] Actively contributing to 1 or more plugin.

- [x] Sponsored by 2 reviewers. **Note the following requirements for sponsors**:

    - Sponsors must have close interactions with the prospective member - e.g. code/design/proposal review, coordinating
      on issues, etc.
    ...

- [x]  Have your sponsoring reviewers reply confirmation of sponsorship: `+1`

**Comment by miekg** [comment]
I'm all in favor of this, you have been doing a lo of (grunt) work. Would welcome you as a contributor! (And add you to the list here: https://github.com/orgs/coredns/people)

**Comment by yongtang** [comment]
+1 as well. zouyee has been really very active and helping CoreDNS a lot 👍 .

**Comment by zouyee** [comment]
Thanks, I am ready to accept the invitation, LOL!

**Comment by miekg** [comment]
invite sent
