### ISSUE TITLE
Supports HA  for NodeLocalDNS

### ISSUE THREAD

**Issue by lzp0412** [coredns/coredns#4058]
We know that there are performance problems in DNS resolution on k8s，so the community proposed a nodelaocaldns solution。However, this solution does not solve the problem of high availability and can not achieve smooth upgrade.So it's there a plan of the component which supports HA?

**Comment by miekg** [comment]
NodelocalDNS is not a CoreDNS project, but maybe John can comment?

**Comment by johnbelamaric** [comment]
See discussion at https://github.com/kubernetes/dns/issues/324 for latest status. @prameshj is the real force behind the Node Local DNS, she can give you the latest info.
