### ISSUE TITLE
Auto Plugin Not Reloading Zone File

### ISSUE THREAD

**Issue by FakeNameSE** [coredns/coredns#4059]
**What happened**: The auto plugin does not seem to be reloading zone files for me. For instance, changing the IP address for a record in my zone file and then querying CoreDNS with dig does not result in the query returning the new IP address until I restart CoreDNS.

**What you expected to happen**: CoreDNS to detect the changes to my zone file and return the updated IP after the refresh interval has elapsed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install CoreDNS with `docker pull coredns/coredns`.
2. Create a directory called `coredns`.
3. Place the zone file and `Corefile` I pasted later in this report in `coredns`. The name of the zone file should be `db.dns`.
4. Run CoreDNS with `docker run -d --name coredns --restart=always --volume=/path/to/coredns/:/root/ -p 5300:53/udp coredns/coredns -conf /root/Corefile`
5. Query the coredns instance for `example.dns` with `dig @localhost -p 5300 a example.dns` (from the same machine that is running CoreDNS).
6. Change the IP in `db.dns` for `example` from `1.2.3.6` to `1.2.3.7`.
7. Wait at least 45 seconds and run the dig command again. The IP did not change.
8. Run `docker container restart coredns` and then run the dig command again. The IP will have changed now.

**Anything else we need to know?**: A small zone file which reproduces this (named `db.dns`) is:
```
$ORIGIN dns.
$TTL 1750
@       IN      SOA coredns1.dns. coredns0.dns. (
                                2017042745 ; serial
                                7200       ; refresh (2 hours)
                                3600       ; retry (1 hour)
                                1209600    ; expire (2 weeks)
                                3600       ; minimum (1 hour)
                                )

        IN NS coredns1.dns.

coredns0                IN  A           1.2.3.4
coredns1                IN  A           1.2.3.4
example                 IN  A           1.2.3.6
```

I tested the reloading of the zone file by changing the example record's IP between `1.2.3.6` and `1.2.3.7`.

**Environment**:

- the version of CoreDNS: The latest official container image off of Dockerhub.
- Corefile:
```
dns.:53 {
  auto {
    directory /root db\.(.*) {1}
    reload 45s
  }
  reload
  log
}
```

- logs, if applicable: CoreDNS logs obtained via `docker logs coredns`
```
[INFO] plugin/auto: Inserting zone `dns.' from: /root/db.dns
dns.:53
[INFO] plugin/reload: Running configuration MD5 = b7df3412698c86e5297b88c6386eb5f6
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
[INFO] plugin/file: Sent notifies for zone "dns." to []
[INFO] 172.17.0.1:49985 - 2383 "A IN example.dns. udp 52 false 4096" NOERROR qr,aa,rd 85 0.000155784s
[INFO] 172.17.0.1:37570 - 7538 "A IN example.dns. udp 52 false 4096" NOERROR qr,aa,rd 85 0.000096261s
[INFO] 172.17.0.1:33185 - 13527 "A IN example.dns. udp 52 false 4096" NOERROR qr,aa,rd 85 0.000204318s
[INFO] 172.17.0.1:34695 - 16318 "A IN example.dns. udp 52 false 4096" NOERROR qr,aa,rd 85 0.000154158s
```

- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Others: The Ubuntu machine I was running Ubuntu on is virtual.

**Comment by stp-ip** [comment]
Try increasing the SOA serial by one. That should lead to an update of the zone.
Zones are only updated on a new serial. We don't auto increment the serial.

**Comment by miekg** [comment]
Thanks for the logs though. That looks a bit ugly. Can prolly fix those

**Comment by FakeNameSE** [comment]
Great, thank you for the help! Is there a chance that this should be more clearly emphasized in the `auto` docs? It only really comes up a little buried in the section detailing parameters under reload.

**Comment by miekg** [comment]
Happy to review any text you want to add.

**Comment by FakeNameSE** [comment]
I'd love to make a slight modification. Is the documentation for `auto` generated from `coredns/plugin/auto/README.md`, or do I need to modify something else? I was thinking of just specifying at the end of Description that "New or changed zones are automatically picked up from disk only when serial changes." That way the behavior is mentioned within the scope of the whole plugin and not just for one of its parameters.

**Comment by miekg** [comment]
Yep that readme is the canonical source

**Comment by FakeNameSE** [comment]
Thank you, I made a small modification and submitted a pull request.
