### ISSUE TITLE
Weird phenomenon with no next plugin found

### ISSUE THREAD

**Issue by zouyee** [coredns/coredns#4062]
**What happened**:
`[ERROR] plugin/errors: 2 1693750506.280983805. HINFO: plugin/loop: no next plugin found`

**What you expected to happen**:
run without error

**How to reproduce it (as minimally and precisely as possible)**:
```bash
[root@xxx coredns] export KUBERNETES_SERVICE_HOST=xxx
[root@xxx coredns] export KUBERNETES_SERVICE_PORT=6443
[root@xxx coredns]# ls /var/run/secrets/kubernetes.io/serviceaccount/
ca.crt  namespace  token
[root@xxx coredns] ./coredns --conf Corefile
.:53
[INFO] plugin/reload: Running configuration MD5 = 47bad117956ad4b62eb757753c2ab3b4
CoreDNS-1.7.0
linux/386, go1.14.4, fc8be1e-dirty
[ERROR] plugin/errors: 2 33601755.256972879. HINFO: plugin/loop: no next plugin found
```

**_the above steps are not 100% reproducible_**

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: master
- Corefile:
```bash
.:53 {
    errors
    health {
       lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    cache 30
    loop
    reload
    loadbalance
}
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):  CentOS 7 
 
- Others:
  commit: fc8be1e223bbd330eb86a72081503a804ca01861

**Comment by chrisohaver** [comment]
No plugins in the chain can provide an answer to a query for `33601755.256972879.`. Hence the error.
Typically in a k8s deployment, the _forward_ plugin would do this, but it's missing from your config.

**Comment by zouyee** [comment]
The reproduction step is completed on the VM, but simulated the in-cluster method, no dns query through the VM.
