### ISSUE TITLE
plugin: add a new plugin for DNS chaos engineering

### ISSUE THREAD

**Issue by WangXiangUSTC** [coredns/coredns#4065]
**What would you like to be added**:

I want to add a new plugin for **DNS chaos engineering**, and this will be used in **[Chaos Mesh](https://chaos-mesh.org/)**, which is a powerful chaos engineering platform for Kubernetes.

This plugin will return random IP or `Unknown host` error  for a specific host, and this plugin will support some customized configuration, for example:
- Source IP/host: chaos will only work on the specific Pods.
- Chaos host: this plugin will only return random IP or `Unknown host` error for this host.
......

**Why is this needed**:

This plugin will help to **improve the system's stability**.  And I hope this plugin can be included in CoreDNS, not just as an external plugin. 😃

**Comment by miekg** [comment]
Thanks. We already have the "erratic" plugin, can it be folded in there?

**Comment by WangXiangUSTC** [comment]
Awesome! Are there any projects that use the plugin `erratic`? 
And seems this plugin can't control the scope of influence, we need to chaos for specific pods or source IP, maybe we can refine this plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin: add a..." ]
>Awesome! Are there any projects that use the plugin erratic?

we use it for testing coredns itself, that was the primary motivation for adding it in tht
first place.

>And seems this plugin can't control the scope of influence, we need to chaos
>for specific pods or source IP, maybe we can refine this plugin.

depends on how much code this adds, don't want to duplicate the k8s plugin into erratic's
code.

/Miek

--
Miek Gieben

**Comment by WangXiangUSTC** [comment]
OK, I will think about it, thanks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin: add a..." ]
>OK, I will think about it, thanks

meanwhile this can happily live as an external plugin on coredns.io/explugins

**Comment by WangXiangUSTC** [comment]
> meanwhile this can happily live as an external plugin on coredns.io/explugins

It sounds good 🤔
