### ISSUE TITLE
plugin foward dosen't support https and grpc ?

### ISSUE THREAD

**Issue by willzgli** [coredns/coredns#4067]
As I read the code in https://github.com/coredns/coredns/blob/master/plugin/forward/setup.go#L101,

variable trans will receive  one kind of values ,the values are   tls, grpc,  dns, and  https 

However  allowedTrans  (https://github.com/coredns/coredns/blob/master/plugin/forward/setup.go#L99 ) only matches  tls and dns . 

Is it a bug ?

Bellow is releated code section 

        allowedTrans := map[string]bool{"dns": true, "tls": true}
        for i, host := range toHosts {
  
               // Transport()  return one of  tls,  dns, grpc, https **
		trans, h := parse.Transport(host)  

               //allowedTrans only matches dns and tls , how about grpc  and https ?  
		if !allowedTrans[trans] { 
			return f, fmt.Errorf("'%s' is not supported as a destination protocol in forward: %s", trans, host)
		}

		p := NewProxy(h, trans)
		f.proxies = append(f.proxies, p)
		transports[i] = trans
         }

**Environment**:

- the version of CoreDNS: master branch

**Comment by willzgli** [comment]
@miekg  Hi Mieky ,as described above, I am confused. Can  you explain it for me ?

**Comment by willzgli** [comment]
@yongtang

**Comment by chrisohaver** [comment]
forward only supports tls and dns. This is not a bug. The other protocols are not implemented.

**Comment by chrisohaver** [comment]
See: https://github.com/coredns/coredns/pull/3817

**Comment by willzgli** [comment]
Hi， @chrisohaver . I am not clear about wheter the resolution service don't dosen't  support https/grpc  or olny  inband healthckecking  doesn't support  https/grpc ?

**Comment by johnbelamaric** [comment]
`forward` doesn't support anything other than tls and dns for any
functions. `grpc` supports the same features set but for grpc transport. I
don't think we have one for https. PRs welcome!

**Comment by chrisohaver** [comment]
Yes - from what I can tell looking at the code, if the protocol isn't tls, then it (forward) just makes a dns connection.
So even if you were to safely wrap health checking in nil checks, if you set the protocol to https it would just forward via dns.
