### ISSUE TITLE
middleware/auto NOTIFY for zone was not accepted with rcode NOERROR

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#407]
Not sure, if this is by design, but not accepted sounds like failed, but the rcode gives back NOERROR and as far as my preliminary tests are concerned the notify works. 
```Notify for zone "example.net" was not accepted by "0.0.0.0:53": rcode was "NOERROR"```

**Comment by miekg** [comment]
fixed with 0f8cb50
