### ISSUE TITLE
Rework plugin/cache into RR cache

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4076]
**What would you like to be added**:

the cache plugin should drop the caching of whole packets and move to a RRSet cache

**Why is this needed**:

It's way more efficient, although the implementation is tricker.

**Design**:

Some small notes on how I intent to do this:

This implementation is an RRSet cache. Anything in the answer and authority section of an answer
will be be cached according to TTL and DNSSEC signature life times (if available).

Based up on https://tools.ietf.org/html/rfc2308 and https://tools.ietf.org/html/rfc2181

See https://tools.ietf.org/html/rfc2181#section-5.4.1 Ranking Data

>   Unauthenticated RRs received and cached from the least trustworthy of
>   those groupings, that is data from the additional data section, and
>   data from the authority section of a non-authoritative answer, should
>   not be cached in such a way that they would ever be returned as
>   answers to a received query.  They may be returned as additional
>   information where appropriate.  Ignoring this would allow the
>   trustworthiness of relatively untrustworthy data to be increased
>   without cause or excuse.

Meaning data cached as from the additional section should only be used in the additional section,
never in answer sections.

AA bit on answers makes the answer more trustworthy. - should we care?

When we see a response *cache* will:

- extract rrsets from answer and authority and additional section
- check aa bit to .... ?
- cache the rrsets found, while keeping track in what section they were. Each RRset will be cached
  according to its name, type (and class, but that's always IN)

We responding to a query, *cache* will:

- check qname, qtype; do we have anything in the cache for this?
- if not let query through
- check unresolved domain names from answer section RRsets - check if those exist in the cache (but
  but only as additional) is so add them to additional.
- if client needs DNSSEC, check for for those types a well, if we don't have them let query through? Should we somehow cache that we don't have them?

## DNSSEC vs plain DNS
cache gets query for name (no DO), caches result. Now DO query for same name, no DNSSEC info in the cache? Just forward query and try to get the info - keeping track of returned response - if no DNSSEC even DO, we put this info at the original cache item?

**Comment by miekg** [comment]
I have another doc that I'll add here that lays out some more difficulties with moving to an RRSet cache.

**Comment by johnbelamaric** [comment]
Sounds like wonderful idea but certainly needs to be a new `rrcache` plugin.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/4207 and friends has showed that this is surprisingly complex. I won't pursue this further (for now). The memory saving from those previous PRs solve part of this.
