### ISSUE TITLE
health plugin `lameduck` option has misleading documentation.

### ISSUE THREAD

**Issue by UnwashedMeme** [coredns/coredns#4084]
**What happened**:

CoreDNS returns `200 OK` after SIGTERM while in lameduck mode.  

**What you expected to happen**:

As soon as the SIGTERM was received and lameduck mode was entered  I expected `/health` endpoint would no longer return 200 OK.

**How to reproduce it (as minimally and precisely as possible)**:
Run CoreDNS with
```
    health {
        lameduck 21s   # Specific time isn't really relevant, just make it long enough to observe
    }
```
In a separate terminal run `sudo pkill -SIGTERM coredns; while curl http://localhost:8080/health; do printf "\n\n"; sleep 1; date; done` 

**Anything else we need to know?**:

[The docs about lameduck say](https://coredns.io/plugins/health/):

>    Where lameduck will make the process unhealthy then wait for DURATION before the process shuts down.

* It looks like the lameduck changed in https://github.com/coredns/coredns/commit/c778b3a67ca43124a539acda21eca4934c8110f6#diff-8244c8b222eeb3813330b611798eb81bL78
  * L78 here is inside of `OnFinalShutdown`
  * It looks like that patch was addressing a slightly different situation but along the way it became "health always reports healthy"
* The ready plugin works exactly as expected in this situation:  `localhost:8181/ready` fails immediately upon entering lameduck mode.

I think the thing to do here is just fix up the docs, something like:

>  Where lameduck will delay shutdown for DURATION. `/health` will still report 200 OK and DNS requests are served but the [ready](https://coredns.io/plugins/ready/) plugin will start failing and can be used to observe that CoreDNS is in lameduck mode prior to shutdown.

**Environment**:

- the version of CoreDNS: 1.7.0
- Corefile:
```
. {
    errors
    ready
    health {
        lameduck 21s
    }
    prometheus :9153
    forward . 168.63.129.16
}
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
```
- CoreDNS Logs:

```
Aug 27 20:45:40 coredns1000002 coredns[3415]: [INFO] SIGTERM: Shutting down servers then terminating
Aug 27 20:45:40 coredns1000002 coredns[3415]: [INFO] plugin/health: Going into lameduck mode for 21s
```
- Separate window running curl http://localhost:8080/health in a loop:
```
Thu Aug 27 20:45:39 UTC 2020
OK
Thu Aug 27 20:45:40 UTC 2020
OK
Thu Aug 27 20:45:41 UTC 2020
OK
Thu Aug 27 20:45:42 UTC 2020
OK
...
Thu Aug 27 20:46:01 UTC 2020
OK
Thu Aug 27 20:46:02 UTC 2020
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

**Comment by UnwashedMeme** [comment]
To be super clear:  I don't think CoreDNS's current behavior is wrong. It just isn't what I expected from the docs and this caused me a while of confusion.  Slight fixup of the docs will make this a lot friendlier.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] health plugin..." ]
>To be super clear: I don't think CoreDNS's current behavior is wrong. It just
>isn't what I expected from the docs and this caused me a while of confusion.
>Slight fixup of the docs will make this a lot friendlier.

please send some text our way.

Thanks!
