### ISSUE TITLE
Clarifications about file plugin

### ISSUE THREAD

**Issue by fabrizior** [coredns/coredns#4088]
I'm trying to understand how the file plugin works.
Is not clear for me what physically reads the zone file.
In the plugin source file.go at row 43 (z, ok := f.Zones.Z[zone]) the z structure returns data from the zone file (for example the SOA) but I don't understand how and how it gets this data.

Can I have some help?
Sorry, I'm golang principiant.

Thanks, Fabrizio

**Comment by miekg** [comment]
https://github.com/coredns/coredns/blob/master/plugin/file/setup.go#L86 parsed the file from disk

**Comment by fabrizior** [comment]
Grazie
