### ISSUE TITLE
modify behavior for serve_stale 

### ISSUE THREAD

**Issue by ltagliamonte-dd** [coredns/coredns#4097]
As the documentation states for serve_stale:
```
cache will attempt to refresh the cache entry AFTER sending the expired cache entry to the client.
```

When serve_stale is in use the very first reply you receive from coreDNS is a stale reply and only the second one will be an update one.

In my case our main programming language is JVM based, in our apps we set a DNS cache ttl of 10s but if you use a serve_stale of 24hrs for example and you deploy everyday is it possible that a new container ends up on a node with a old and stale DNS entry and that container will get old IPs and it will be basically down for 10s (in our case) until it get the right IPs.

To better support use cases like mine i'd like to propose to change the `serve_stale` behavior and  fetch first from the upstream and in case of failure serve a stale entry if available.

**Comment by chrisohaver** [comment]
FWIW, CoreDNS implements the same behavior as Unbound's `serve-expired` option.  So there is a precedent for the current behavior.

Doing the check upstream before sending an answer to the client would impact performance greatly in the case that the upstream is down.

**Comment by ltagliamonte-dd** [comment]
@chrisohaver thank you for the reply could it be possible to add a flag that will change the order?
I'm my mind I would love to implement something like a circuit breaker... if the upstream fails N times start serving from the stale cache and start a corutine that with a backoff try to fetch the entry and when it succeed stop serving from the stale_cache.

**Comment by chrisohaver** [comment]
Sounds like a reasonable approach, but I'm not sure if we want to maintain two significantly different implementations of more or less the same feature in the cache plugin.  @miekg ?

**Comment by ltagliamonte-dd** [comment]
maybe a circuit breaker plugin?
To be honest I don't know so good the code and the complexity behind modifying the existing cache plugin or adding a new plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] modify behavi..." ]
>Sounds like a reasonable approach, but I'm not sure if we want to maintain two
>significantly different implementations of more or less the same feature in the
>cache plugin. @miekg ?

serve_stale is a mechanism that might save you a bit of time; it goes totally against the
spirit of DNS, so it's bound to be sub optimal in cases.

Making things more complex to have (slightly less?) sub optimal behavior in not something
we should do here.

/Miek

--
Miek Gieben

**Comment by zmedico** [comment]
I hope that https://github.com/coredns/coredns/pull/4536 provides a good compromise for this issue.  It adds a `refresh_stale sync` setting which ensures that TTL is respected when the upstream is available.

**Comment by miekg** [comment]
dns is inherently eventual consistent. There is _nothing_ you go do about that, besides not using the DNS for things.

Adding knobs to paper of this is just that, who says an intermediate cache doesn't have it. Also the TTL is not a MUST in RFC, you can cache stuff shorter or longer than a TTL, i.e TTL < 5s on the internet are mostly reset 5s

**Comment by zmedico** [comment]
> dns is inherently eventual consistent. There is _nothing_ you go do about that, besides not using the DNS for things.
> 
> Adding knobs to paper of this is just that, who says an intermediate cache doesn't have it. Also the TTL is not a MUST in RFC, you can cache stuff shorter or longer than a TTL, i.e TTL < 5s on the internet are mostly reset 5s

The makes the coredns cache plugin unusable as an intermediate cache for some use cases. For example, both bind and unbound implement `serve-expired-client-timeout` in order to support this intermediate cache use case. If `serve-expired-client-timeout` is set to `0`, then they behave as the coredns cache plugin currently behaves.

**Comment by chutz** [comment]
There is actually a RFC for the behaviour this is being requested here, see https://tools.ietf.org/html/rfc8767

This is a way of making systems resilient to DNS downtime or outages, it's quite useful when one is trying to get high availability.
