### ISSUE TITLE
external resolution server

### ISSUE THREAD

**Issue by my1990** [coredns/coredns#4104]
Coredns is configured with an external resolution server. How does the health check for this external resolution server do? If this external resolution server goes down, how long will coredns find out?
How often will coredns check whether the external resolution server is available?
![image](https://user-images.githubusercontent.com/16768690/92345071-ab9e7400-f0fa-11ea-9cc9-72df1748a86d.png)

**Comment by my1990** [comment]
![image](https://user-images.githubusercontent.com/16768690/92345196-0f28a180-f0fb-11ea-8910-008d6180aba9.png)
After manually stopping the external resolution server, coredns will keep restarting?

**Comment by chrisohaver** [comment]
CoreDNS 1.2.6 is extremely old, and the _proxy_ plugin has been deprecated for a while now.  It was removed from the coredns/coredns project and it sits in a different repo now as an external plugin.  Here is the readme for proxy ( covers health checking option): https://github.com/coredns/proxy/blob/master/README.md

_proxy_ was replaced with _forward_
