### ISSUE TITLE
health_check 0 causes high cpu usage when upstream unavailable

### ISSUE THREAD

**Issue by knisbet** [coredns/coredns#4113]
**What happened**:
Setting a `health_check` 0 in the forward plugin appears to cause a busy loop where the exponential backoff for the health_check isn't able to increment and as a result busy loops. This may also require a combination of attempting to use a localhost upstream that isn't present, for the probe to immediately fail.

**What you expected to happen**:
This is probably a miss-understanding on my part, I somehow got the impression that setting a 0 value would disable health_checks although I don't see this documented, and it isn't the case in the sources.

Alternatively, setting a value of 0 should be caught by the configuration checks to prevent this runaway CPU usage.

Alternatively a user may want aggressive health checking of down servers without a backoff, in which case no action is required.

**How to reproduce it (as minimally and precisely as possible)**:
Set a corefile with a forward server of localhost (assuming you don't have a resolver bound to localhost or all interfaces)
```
.:53 {
  reload
  bind 127.0.0.2
  errors
  forward . 127.0.0.1 {
    health_check 0
  }
}
```

Observe CPU usage
```
op - 15:18:43 up 18:16,  0 users,  load average: 1.32, 0.68, 0.41
Tasks:  47 total,   1 running,  46 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.5 us,  4.4 sy,  0.0 ni, 90.8 id,  0.0 wa,  0.0 hi,  1.4 si,  0.0 st
KiB Mem : 32067096 total, 17537880 free,  1163496 used, 13365720 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 30744004 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
18379 planet    20   0  750216  35508  25960 S 177.7  0.1   0:41.33 coredns
```

Normal range when communicating with an available DNS server is 0.3% CPU usage with the same configuration. 

**Anything else we need to know?**:
A value of 0 appears to be intentionally allowed here:
https://github.com/coredns/coredns/blob/e082bb5a61a94bf5be653900a568db26cae0a6e1/plugin/forward/setup.go#L161-L172

Tracing this through, it appears this ultimately get's passed to a backoff here (variable interval)
https://github.com/coredns/coredns/blob/master/plugin/pkg/up/up.go#L76-L79

Which I believe uses this function in backoff for incrementing the interval, which uses a multiplication against the initial 0 value leaving a result of 0.
https://github.com/cenkalti/backoff/blob/v4/exponential.go#L138-L145

I can PR a patch if there is an indication of what the preferred approach is. Allowing 0 to disable health_checks entirely, or enforcing a non-zero interval to avoid the backoff not incrementing. 

**Environment**:

- the version of CoreDNS: 1.7.0
- Corefile: 
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by zouyee** [comment]
I think we can consider setting a minimum value, similar to grpc https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] health_check ..." ]
>I think we can consider setting a minimum value, similar to grpc https://
>github.com/grpc/grpc/blob/master/doc/connection-backoff.md

from https://coredns.io/plugins/forward/

     When it detects an error a health check is performed. This checks runs in a loop,
     performing each check at a 0.5s interval for as long as the upstream reports unhealthy

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
setting this to 0 creates what you see here. work-as-intended.
