### ISSUE TITLE
Feature Request: `record` directive, eg MX or TXT within Corefile, no external source.

### ISSUE THREAD

**Issue by polarathene** [coredns/coredns#4130]
**What would you like to be added**:

A plugin similar to `hosts` (even just minimal support via a Corefile directive is fine), that allows you to also specify a record type to support records such as MX and TXT. Presently this seems to only be supported by CoreDNS via plugins to external software?

**Why is this needed**:

I contribute to a [docker packaged mail server project](https://github.com/tomav/docker-mailserver), and quite enjoy the simplicity of CoreDNS over alternatives. I would like to have an example of a local setup for users to test/learn with, providing DNS records this way seemed like a good idea.

I don't specifically need CoreDNS for this and could probably go with something like `dnsmasq` if this would be a feature that's quite a bit of effort to support. I have noticed that internally CoreDNS seems to have code for MX and TXT records at least, but I have no experience Go development to know how to tackle this plugin myself.

If I'm mistaken, and this is already possible to do with CoreDNS, I have raised a [documentation issue](https://github.com/coredns/coredns.io/issues/202). My use case is rather niche, but perhaps others would express their interest and share their own needs for specifying record types here to justify the value of such a feature/plugin.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Feature Request: ..." ]
>What would you like to be added:
>
>A plugin similar to hosts (even just minimal support via a Corefile directive
>is fine), that allows you to also specify a record type to support records such
>as MX and TXT. Presently this seems to only be supported by CoreDNS via plugins
>to external software?

There is no plugin that does this, but it's a neat idea and not hard to add. I also think
this would be a useful addition.

There are some corner cases, like should a SOA be mandatory, must there be NS records?
Should we synthesize these if not given? Do we allow multiline (probably hard with the
Corefile parser)

I think it could look something like:

``` corefile
example.org {
         records {
             @   IN  A   127.0.0.1 # @ uses origin here: example.org
             www IN  A   127.0.0.1 # example.org appended
         }
}
````

A garbage in, garbage out approach seems fine, if the record is there we return it when
queried.

**Comment by miekg** [comment]
I had some fun with this today, see https://github.com/coredns/coredns/pull/4132 (you can just check out and compile coredns and play with it)

**Comment by miekg** [comment]
https://coredns.io/explugins/records/
