### ISSUE TITLE
plugin/route53 documentation of AWS SDK version

### ISSUE THREAD

**Issue by millermatt** [coredns/coredns#4133]
**What would you like to be added**: route53 plugin docs should state which version of the AWS SDK is used

**Why is this needed**: I'd like to use [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html) to provide IAM credentials for the route53 plugin. I am unable to determine if the required AWS SDK version of 1.23.13 is used in the plugin.

**Comment by yongtang** [comment]
@millermatt See:

https://github.com/coredns/coredns/blob/master/go.mod#L10

**Comment by millermatt** [comment]
Thanks!
