### ISSUE TITLE
next version: 1.7.2 or 1.8.0

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4138]
Do we want to do another patch (1.7.2) release or jump to 1.8.0

For 1.8.0 we will merge:
* https://github.com/coredns/coredns/pull/4134
* https://github.com/coredns/coredns/pull/4069 (fixes bunch of issues as well)

**Comment by yongtang** [comment]
+1 for 1.8.0

**Comment by miekg** [comment]
ok, 1.8.0 it is. I'll merge a bunch of outstanding PRs that force us to do an 1.8.0

**Comment by yongtang** [comment]
PR #3972 also need to be re-applied. Have created a PR #4142 to cherry-pick (re-apply)

**Comment by miekg** [comment]
Awesome!! I'm failing to even apply the diff (too many rejects). I'll give
this a quick review
