### ISSUE TITLE
middleware/health status OK even for missing directories

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#414]
Coredns could start up with missing directories. Currently this misconfiguration leads to a log warning.
As long as there are directories or files missing it seems giving status "OK" seems imperfect.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] middleware/health s..." ]

> Coredns could start up with missing directories. Currently this misconfiguration leads to a log warning.
> As long as there are directories or files missing it seems giving status "OK" seems imperfect.

The current health signal conveys: up and running, ready to receive queries.

A potential extension would be to let each middleware register their own health,
i.e. /health/middleware/file would be the endpoint for the file middleware.

I believe the above condition could be picked up with proper monitoring.

**Comment by stp-ip** [comment]
The question is... can it actually receive queries, when specific middlewares are not ready?
In this case the health would be used to determine, if the instance is ready. It will be ready before the actual files are loaded in.
I will default back to starting coredns, when the directory is available, but might be something to think about.

Code around the issue:

```
while [ ! -d /etc/source/files/zones ]; do sleep 2; done; coredns
```

**Comment by miekg** [comment]
This health serves as binary is up and working and ready to receive queries. Anything else should moved to separate health endpoints.
