### ISSUE TITLE
Errors when trying to compile coredns

### ISSUE THREAD

**Issue by sanfx** [coredns/coredns#4144]
**What happened**:

**What you expected to happen**:
a comiled coredns binary

**How to reproduce it (as minimally and precisely as possible)**:
cd coredns
go install .

**Anything else we need to know?**:

**Environment**:
Arm64,
ubuntu 18.04

when I try t compile coredns from this cloned repo I ge the following error

# k8s.io/apimachinery/pkg/util/errors
../k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is
# go.etcd.io/etcd/clientv3/balancer/picker
../go.etcd.io/etcd/clientv3/balancer/picker/err.go:25:33: cannot use errPicker literal (type *errPicker) as type Picker in return argument:
	*errPicker does not implement Picker (wrong type for Pick method)
		have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
		want Pick(balancer.PickInfo) (balancer.PickResult, error)
../go.etcd.io/etcd/clientv3/balancer/picker/roundrobin_balanced.go:37:11: cannot use rrBalanced literal (type *rrBalanced) as type Picker in return argument:
	*rrBalanced does not implement Picker (wrong type for Pick method)
		have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
		want Pick(balancer.PickInfo) (balancer.PickResult, error)
# k8s.io/utils/trace
../k8s.io/utils/trace/trace.go:200:119: totalTime.Milliseconds undefined (type time.Duration has no field or method Milliseconds)
# github.com/mholt/acmez/acme
../github.com/mholt/acmez/acme/http.go:96:6: undefined: errors.As
../github.com/mholt/acmez/acme/http.go:161:14: undefined: http.NewRequestWithContext
../github.com/mholt/acmez/acme/order.go:149:6: undefined: errors.As
# sigs.k8s.io/structured-merge-diff/value
../sigs.k8s.io/structured-merge-diff/value/mapreflect.go:95:13: val.MapRange undefined (type reflect.Value has no field or method MapRange)
../sigs.k8s.io/structured-merge-diff/value/mapreflect.go:173:14: rhs.MapRange undefined (type reflect.Value has no field or method MapRange)
../sigs.k8s.io/structured-merge-diff/value/mapreflect.go:194:13: lhs.MapRange undefined (type reflect.Value has no field or method MapRange)
# k8s.io/apimachinery/pkg/util/net
../k8s.io/apimachinery/pkg/util/net/http.go:66:5: undefined: errors.As
../k8s.io/apimachinery/pkg/util/net/http.go:83:5: undefined: errors.As
../k8s.io/apimachinery/pkg/util/net/util.go:43:5: undefined: errors.As
../k8s.io/apimachinery/pkg/util/net/util.go:52:5: undefined: errors.As

how can I exclude for k8s.io to be excluded  ?

**Comment by zouyee** [comment]
Please use `go mod vendor`.
