### ISSUE TITLE
CoreDNS is performing very slow when there are more than 5000 acl records

### ISSUE THREAD

**Issue by mhoshim** [coredns/coredns#4145]
[Coredns_stack.zip](https://github.com/coredns/coredns/files/5286053/Coredns_stack.zip)

**What happened**: I have configured ACL policy for 20000 domains after that CoreDNS took 15 minutes to start and after start CPU usage was high.

**What you expected to happen**: It should start as normal within a few seconds and CPU usage also should be as usual.

**How to reproduce it (as minimally and precisely as possible)**: Create ACL policy for 20000 domains using script then start CoreDNS

**Anything else we need to know?**: I think memory management needs to improve

**Environment**: Linux

- the version of CoreDNS: 1.7
- Corefile:
- logs, if applicable: Attached
- OS (e.g: `cat /etc/os-release`): CentOS ver.7
- Others:
[Coredns_stack.zip](https://github.com/coredns/coredns/files/5286054/Coredns_stack.zip)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] CoreDNS is perfor..." ]
>What happened: I have configured ACL policy for 20000 domains after that
>CoreDNS took 15 minutes to start and after start CPU usage was high.
>
>What you expected to happen: It should start as normal within a few seconds and
>CPU usage also should be as usual.
>
>How to reproduce it (as minimally and precisely as possible): Create ACL policy
>for 20000 domains using script then start CoreDNS
>
>Anything else we need to know?: I think memory management needs to improve

what's the script, how can I repro?

**Comment by ihac** [comment]
@mhoshim More info is needed (e.g. IPv4 or IPv6?). Can you pls share a snippet of your ACL rules? Or it would be better if the IP list can be accessed publicly. I could check the performance locally.

By the way, I would assume that you're blocking single IPs considering 20,000 is not a small number. The point is, the internal data structure (Radix Tree) of `acl` does perform worse when dealing with sparse ip addresses.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS is pe..." ]
>@mhoshim More info is needed (e.g. IPv4 or IPv6?). Can you pls share a snippet
>of your ACL rules? Or it would be better if the IP list can be accessed
>publicly. I could check the performance locally.
>
>By the way, I would assume that you're blocking single IPs considering 20,000
>is not a small number. The point is, the internal data structure (Radix Tree)
>of acl does perform worse when dealing with sparse ip addresses.

Note that this slice might be responsible for some of it; *if* it is traversed for every
acl: https://github.com/coredns/coredns/blob/master/plugin/acl/acl.go#L25
(haven't looked deeper, I may be wrong)

/Miek

--
Miek Gieben

**Comment by ihac** [comment]
Hey @mhoshim. Just in case you missed something, I'd strongly suggest you to put multiple IPs together in one ACL rule when dealing with large volumes of IP addresses. Here is a sample:
```
Instead of:
acl {
    block net 192.168.0.0/24
    block net 192.168.1.0/24
    allow
}

Pls use:
acl {
    block net 192.168.0.0/24 192.168.1.0/24
    allow
}
```
This happens because we maintain a radix tree for each rule. If we set a single rule for each IP address, the performance will be even worse than checking IPs one by one.

**Comment by ihac** [comment]
We might need to let users understand the internal mechanism of acl and provide some best practices as well. cc @miekg

**Comment by miekg** [comment]
Please add docs to the readme if you think this will help.

**Comment by ihac** [comment]
@miekg Yeh, will do that.

@mhoshim I tried to block 20,000 random single IPs but was still not able to reproduce the the performance issue you run into. Everything works just fine on my side.

If you're still struggling with this issue, pls let me know.
