### ISSUE TITLE
Constantly getting DNS_PROBE_FINISHED_NXDOMAIN error on Chrome

### ISSUE THREAD

**Issue by guihkx** [coredns/coredns#4146]
**What happened**:

After updating to v1.7.1, I started getting this `DNS_PROBE_FINISHED_NXDOMAIN` error very often on Google Chrome, but not with all domains. However, having been using v1.7.0 for months, I can assure you I've never experienced that error before. 

And since Chrome has this feature that "auto-reloads error pages", once I get that DNS error I mentioned, Chrome will reload the tab automatically and the page will load normally. I can disable this feature by passing `--disable-auto-reload` to Chrome, making this bug (or whatever) much more "present".

It could be a misconfiguration on my part too, but I honestly don't understand why this happens only in v1.7.1, which is, I presume, a minor release.

**What you expected to happen**:

Not to get this `DNS_PROBE_FINISHED_NXDOMAIN` error on Chrome.

**How to reproduce it (as minimally and precisely as possible)**:

1. Be on CoreDNS v1.7.1
2. Run Chrome/Chromium with `--disable-auto-reload`
3. Try to load https://invent.kde.org/
4. You should get this `DNS_PROBE_FINISHED_NXDOMAIN` error at first, but upon reloading the page, it will load as expected.
5. Wait a minute or so and try reloading the page
6. You should get the error again

**Anything else we need to know?**:

I don't know if this is useful, but I ran the `nslookup` tool on both v1.7.0 and v1.7.1, and I got different results (visually, at least). But I don't know much about DNS to tell if that's indeed the root cause:

### v1.7.0

```
$ nslookup invent.kde.org 127.0.0.1
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
invent.kde.org	canonical name = leptone.kde.org.
Name:	leptone.kde.org
Address: 195.201.182.103
Name:	leptone.kde.org
Address: 2a01:4f8:231:3116::3
```

### v1.7.1

```
$ nslookup invent.kde.org 127.0.0.1
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
invent.kde.org	canonical name = leptone.kde.org.
invent.kde.org	rdata_46 = CNAME 8 3 1800 20201012085750 20200912082613 57411 kde.org. ijSv5FmsNjFviBcOFwQgqjt073lttxTTNqkno6oMa3DD3kC+IU2D9+bF zUF3L05GF3MmwqEBRZoFa4LNIvV8zCfOE+O86FGiITOTLtoTBmQfeIa1 vzpve4r33OPettGYa4pfAg7LyNLa0wQjONHbYI6+mAiS63sfhoZK34Sn 8W/pg4uywlyZxYnW+KQCGno6yXCQeYdfnTYcZ0i35+RiYQcJJiIBFE5Y xiLv2AzWyJM0IPCWJlsm9+7t9sQkrQsgp2m7hv31nd/Q4Dm4BmcDpD93 SHDPZVmn6zRihFS0x8oEFLLRJoDtM/aY5hojmDC06QWPRNqt8n70znN4 CVL0pw==
invent.kde.org	canonical name = leptone.kde.org.
invent.kde.org	rdata_46 = CNAME 8 3 1800 20201012085750 20200912082613 57411 kde.org. ijSv5FmsNjFviBcOFwQgqjt073lttxTTNqkno6oMa3DD3kC+IU2D9+bF zUF3L05GF3MmwqEBRZoFa4LNIvV8zCfOE+O86FGiITOTLtoTBmQfeIa1 vzpve4r33OPettGYa4pfAg7LyNLa0wQjONHbYI6+mAiS63sfhoZK34Sn 8W/pg4uywlyZxYnW+KQCGno6yXCQeYdfnTYcZ0i35+RiYQcJJiIBFE5Y xiLv2AzWyJM0IPCWJlsm9+7t9sQkrQsgp2m7hv31nd/Q4Dm4BmcDpD93 SHDPZVmn6zRihFS0x8oEFLLRJoDtM/aY5hojmDC06QWPRNqt8n70znN4 CVL0pw==

```

**Environment**:

- the version of CoreDNS: v1.7.1
- Corefile:
```
. {
  forward . tls://1.1.1.1 tls://1.0.0.1 {
    tls_servername cloudflare-dns.com
    health_check 5s
  }
  cache 30
}
```
- OS (e.g: `cat /etc/os-release`): Arch Linux

**Comment by miekg** [comment]
thanks for the detailed report. I've got a good idea what change caused this, probably
goes away when you remove the cache plugin.

As always, the corner cases in DNS are out to get (as DNS developer), it's commit acf9a0fa
- which I really want to keep because it makes cache more efficient, but obvs needs a fix.

/Miek

--
Miek Gieben

**Comment by guihkx** [comment]
>probably goes away when you remove the cache plugin.

That's spot on. Removing the cache plugin made the error go away indeed! :)

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/4148 is fix. Needs a testcase to test what you are seeing here. 

Also bit weird none of the existing test cases caught this, but that's live.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Constantly ge..." ]
>Closed #4146 via #4148.

I'm inclined to do a 1.8.0 release relatively soonish to get this fixed code out.

Could you give coredns [master] a try?

**Comment by guihkx** [comment]
Just did, and that Chrome error is gone. Also, the `nslookup` output is the same as of version 1.7.0.

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Constantly ge..." ]
>Just did, and that Chrome error is gone. Also, the nslookup output is the same
>as of version 1.7.0.

good to hear! And thanks for double checking.
