### ISSUE TITLE
middleware/file: dont reload zone with no SOA change

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#415]
Right now we just reload - should check the SOA and if not changed -> do nothing.

**Comment by miekg** [comment]
With the new `ignore_serial` that I'm adding to the *file* middleware this seems a bit senseless. A better way is being able to use `ignore_serial` in *auto* as well. Meaning we should store some hash sum of the file and only reload when that has changed (way may or may not involved a SOA serial update)

**Comment by stp-ip** [comment]
SOA just seemed to reflect the general behaviour between DNS servers best, but I agree that using a hash best reflects a change. Question is does the reload loop generate the hash of every file every time or are we basically looking at the timestamp and if that changed we generate a new hash and compare to the currently deployed hash/file?

As mentioned in the ignore_serial issue, I'm still not sure about the use case. But it seems most of the features in file would make sense in auto, which leads me to the same suggestions: Should the file and auto middleware be merged to prevent duplicating every feature?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] middleware/file..." ]
>SOA just seemed to reflect the general behaviour between DNS servers best, but I agree that using a hash best reflects a change. Question is does the reload loop generate the hash of every file every time or are we basically looking at the timestamp and if that changed we generate a new hash and compare to the currently deployed hash/file?

I believe just hashing each file works best.

>As mentioned in the ignore_serial issue, I'm still not sure about the use case. But it seems most of the features in file would make sense in auto, which leads me to the same suggestions: Should the file and auto middleware be merged to prevent duplicating every feature?

SOA serial is a relic from the 80s and doing DNS for at least 15 years, I
*still* forget to up the SOA serial whenever I change a zone. Use-case for me is
non signed zone that I run (I have a few). For signed zones the SOA is
incremented for me - for dynamic DNSSEC signing it does not matter.
