### ISSUE TITLE
Give plugins a type

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4158]
Not all plugins do a "DNS thing", some provide something (*bind*`, `*root*`) or just do something (*reload*). We should identify the types and make that more explicit by first identifying the types and then adding that to the docs.

Once we have them, each plugin will
* get a Type section in the README.md
* sort/group the types on the coredns.io website

**Comment by miekg** [comment]
OK, to kick this off. Let's define 3 types

1. `dns`: this does a dns thingy, I think technically this means it has a `ServeDNS` method
2. `process`: defines a process property, port to bind, config reload etc.
3. `config`: a configuration option

2 and 3 might be the same thing? 

Doing this for the current set of plugins, I get to: (*decrecated*) is labeled build, maybe we should remove that one all together.

* acl - dns
* any - dns
* auto - dns
* autopath - dns
* azure - dns
* bind - config
* bufsize - dns
* cache - dns
* cancel - process
* chaos - dns
* clouddns - dns
* debug  - config
* deprecated - build
* dns64 - dns
* dnssec - dns
* dnstap - process
* erratic - dns
* errors - process
* etcd - dns
* file - dns
* forward - dns
* grpc - dns
* health - process
* hosts - dns
* import - config
* k8s_external - dns
* kubernetes - dns
* loadbalance - dns
* log - process
* loop - dns
* metadata - process
* metrics - process
* nsid - dns
* pprof - process
* ready - process
* reload - config
* rewrite - dns
* root - config
* route53 - dns
* secondary - dns
* sign - dns
* template - dns
* tls - config
* trace - process
* transfer - dns
* whoami - dns

Very much open to discussion and other ideas here.

**Comment by miekg** [comment]
maybe we could use the label syntax from the metadata plugin?

**Comment by johnbelamaric** [comment]
Not sure that set of "types" makes sense. We need to figure out why we want
to formally designate types. In my mind, it would be to give the user some
indication of how to use the plugin. For example, in general a "backend"
plugin is responsible for providing the data for a specific set of
zones, and is typically authoritative on those zones (modulo
`fallthrough`). But what I call "manipulators" tweak the request, and many
of them may be instantiated several times for the same zone, or work across
zones handled by different backends. I would want the type designation to
provide some guidance for users as to how the plugin fits into that mental
model.

**Comment by stp-ip** [comment]
Types might also have an effect on the order. Data backends going before manipulation plugins etc.

**Comment by miekg** [comment]
That kinda true

**Comment by chrisohaver** [comment]
> Types might also have an effect on the order. Data backends going before manipulation plugins etc.

Typically data backends need to be positioned _after_ manipulators in the plugin chain, so the manipulators can act on a query before the backend sees it, and act on the response after next plugin returns an answer.

**Comment by chrisohaver** [comment]
Curious what the eyes emoji mean in this context? The other emojis seem pretty obvious.

But eyes mean ... "That is surprising?" "I've seen this before?" "I'm watching this issue?" "you've opened my eyes to this knowledge?"

I cant imagine that [Emojipedia's definition](https://emojipedia.org/eyes/) applies here.

**Comment by stp-ip** [comment]
In my case acknowledgment with a tiny bit of "thinking" + "it depends" I guess.

**Comment by chrisohaver** [comment]
> In my case acknowledgment with a tiny bit of "thinking" + "it depends" I guess.

Ah OK, thanks.  Well, I think if we wanted to ensure that a given backend could never be affected by a specific manipulator, then we would want to place that backend _before_ that manipulator in the chain, but I think that's a corner case.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Give plugins ..." ]
>    In my case acknowledgment with a tiny bit of "thinking" + "it depends" I
>    guess.
>
>Ah OK, thanks. Well, I think if we wanted to ensure that a given backend could
>never be affected by a specific manipulator, then we would want to place that
>backend before that manipulator in the chain, but I think that's a corner case.

I think we should a a 'Plugin Type' section to the READMEs to start this off. Which means
we need some kind of definition - that can probably in `plugin.md` - although we don't
have that file online (but that's an easy fix). This also allows grouping of plugin on
coredns.io

**Comment by chrisohaver** [comment]
I think the extremely fluid/agile framework for plugins (good thing) will make it hard to clearly categorize them.  Many plugins will lay on fuzzy lines or sit in multiple categories.

At a very high level, we have two kinds of plugins,  "handlers" and "non-handlers".  "**Handlers**" implement `plugin.Handler`, and sit in the server plugin stack, i.e. they process DNS requests.  "**Non-Handlers**" do not implement `plugin.Handler`, and don't sit in the server's plugin stack.  I think at least this delineation is clear.

Drilling down, **Handlers** could be divided into 2 sub categories as suggested above in comments...
- **Backend** - is any plugin that can produce an answer a backend? (_template, hosts_, probably yes. but is _cache_ a backend? _forward_? _acl_? )  or does it have to be the "original" creator of that record? (is _secondary_ a backend? _transfer_? )
- **Manipulator** (or Mutator) - rewrite, autopath, sign, ... _cache_ technically manipulates the query (dnssec), and i think maybe responses (i think some of the header bits - or maybe we don't any more).  _Forward_ changes the transport, and can change the response (truncation)...

I think *loop* fits into a separate **Handler** sub-category.  It's not a manipulator ... not a backend ... maybe an "**Observer**". Perhaps other **Observers** being *metadata*, *log*, *prometheus*.

**Comment by miekg** [comment]
Another question is: why are we doing this? Is this helping end users? Or plugin programmers or us?

**Comment by chrisohaver** [comment]
> Another question is: why are we doing this?

I agree with John when he said that it may be helpful to end-user and and plugin programmers to help them with their "mental model" of how plugins work and interact ... It doesn't help _us_ (maintainers) in any way, IMO.

**Comment by miekg** [comment]
IMO we should then keep it as simple as we can and (if possible) only have
3 types

**Comment by miekg** [comment]
think this fizzled out without a concrete plan
