### ISSUE TITLE
Add query_timestamp to RESPONSE events

### ISSUE THREAD

**Issue by SuperFunks** [coredns/coredns#4165]
**What would you like to be added**:
Add query_timestamp to RESPONSE events

**Why is this needed**:
In order to diff query_timestamp and response_timestamp to calculate the responsetime/resolutiontime performance.
I've started the discussion about this on the golang-dnstap github repository: https://github.com/dnstap/golang-dnstap/issues/36, but it appears to be a missing population in the RESPONSE events created in the CoreDNS DNSTAP Plugin.

"The plugin code appears to keep the query timestamp around as the QueryEpoch field of the dnstap plugin ResponseWriter, but does not use it when generating response reports."

**Comment by miekg** [comment]
I think https://github.com/coredns/coredns/pull/4179 fixes this. Could you double check?

**Comment by SuperFunks** [comment]
Yes for sure! - ill check this out first thing tomorrow.

**Comment by SuperFunks** [comment]
I have tested it out - and something is good - but other stuff is bad.

I did a readout from DIG against CoreDNS using the dnstap2 branch - and this was the results:

**From the JSON output:**
"query_time":"2020-10-06T12:34:33.091035862Z",
"response_time":"2020-10-06T12:34:33.331921193Z",

**Nanoseconds difference between timestamps:** 
240885331 = 240.88 milliseconds

**DiG tool reported this delay:**
;; Query time: 241 msec

I'm guessing DIG rounds up - and DNSTAP has the more precise timing - so this is great!

One bad thing i saw though was that all events returned from DNSTAP is now of type CLIENT_RESPONSE or FORWARDER_RESPONSE. What happened to CLIENT_QUERY or FORWARDER_QUERY?

It looks to me like you have merged all query and response type events - effectively cutting the number of events in half ( i like that :) ) - but increasing the size for all events ( i don't like that :P ).

Also i have found that if CoreDNS experiences a timeout to an upstream DNS provider in the Forward plugin - no query event is shipped by DNSTAP - but in this case we do get a FORWARDER_QUERY event but that event doesn't contain the query_address of the real client. This is pretty bad in terms of insights as we have no way of knowing who called us during an upstream outage.

The same thing happens with i use the Unbound plugin - no client_query event is generated - even if DNS Recursion somehow goes wrong.

Merging Query and Response events when both is present is a good idea - but losing the query events when something goes wrong is not good :(

**Comment by SuperFunks** [comment]
From a forensic perspective - i actually like that query and responses are in singular events - but losing the insights described is bad.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add query_tim..." ]
>I have tested it out - and something is good - but other stuff is bad.
>
>I did a readout from DIG against CoreDNS using the dnstap2 branch - and this
>was the results:
>
>From the JSON output:
>"query_time":"2020-10-06T12:34:33.091035862Z",
>"response_time":"2020-10-06T12:34:33.331921193Z",
>
>Nanoseconds difference between timestamps:
>240885331 = 240.88 milliseconds
>
>DiG tool reported this delay:
>;; Query time: 241 msec
>
>I'm guessing DIG rounds up - and DNSTAP has the more precise timing - so this
>is great!
>
>One bad thing i saw though was that all events returned from DNSTAP is now of
>type CLIENT_RESPONSE or FORWARDER_RESPONSE. What happened to CLIENT_QUERY or
>FORWARDER_QUERY?

I may have fucked that up, previous code was unclear (to me).

>It looks to me like you have merged all query and response type events -
>effectively cutting the number of events in half ( i like that :) ) - but
>increasing the size for all events ( i don't like that :P ).
>
>Also i have found that if CoreDNS experiences a timeout to an upstream DNS
>provider in the Forward plugin - no query event is shipped by DNSTAP - but in
>this case we do get a FORWARDER_QUERY event but that event doesn't contain the
>query_address of the real client. This is pretty bad in terms of insights as we
>have no way of knowing who called us during an upstream outage.
>
>The same thing happens with i use the Unbound plugin - no client_query event is
>generated - even if DNS Recursion somehow goes wrong.
>
>Merging Query and Response events when both is present is a good idea - but
>losing the query events when something goes wrong is not good :(

So this is a regressen from the previous code (just to make this clear).

Thanks for the feedback, stay tuned.

/Miek

--
Miek Gieben

**Comment by SuperFunks** [comment]
If you have anything you would like load tested or reviewed for backward compatibility input to warnings for existing parsers of DNSTAP output - just let me know.

**Comment by miekg** [comment]
Yes https://github.com/coredns/coredns/pull/4179 can be retested.

Thanks!

**Comment by SuperFunks** [comment]
Compiled from branch dnstap2 - the output is not good.

A single query like this: 

`dig @localhost dr.dk`

Produces 2 CLIENT_RESPONSE events to DNSTAP:

```
{
    "type":"MESSAGE",
    "message":{
        "type":"CLIENT_RESPONSE",
        "query_time":"2020-10-11T14:37:17.906073354Z",
        "response_time":"2020-10-11T14:37:17.906131694Z",
        "socket_family":"INET",
        "socket_protocol":"UDP",
        "query_address":"127.0.0.1",
        "query_port":49779,
        "response_message":";; opcode: QUERY, status: NOERROR, id: 54633\n;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1\n\n;; QUESTION SECTION:\n;dr.dk.\tIN\t A\n\n;; ANSWER SECTION:\ndr.dk.\t44\tIN\tA\t195.137.195.42\n\n;; ADDITIONAL SECTION:\n\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 4096\n; COOKIE: acdd01e3b807655a\n"
    }
}
```

```
{
    "type":"MESSAGE",
    "message":{
        "type":"CLIENT_RESPONSE",
        "query_time":"2020-10-11T14:37:17.906073354Z",
        "response_time":"2020-10-11T14:37:17.906131694Z",
        "socket_family":"INET",
        "socket_protocol":"UDP",
        "query_address":"127.0.0.1",
        "query_port":49779,
        "response_message":";; opcode: QUERY, status: NOERROR, id: 54633\n;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1\n\n;; QUESTION SECTION:\n;dr.dk.\tIN\t A\n\n;; ANSWER SECTION:\ndr.dk.\t44\tIN\tA\t195.137.195.42\n\n;; ADDITIONAL SECTION:\n\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 4096\n; COOKIE: acdd01e3b807655a\n"
    }
}
```

I expect there to be 2 Events - but one should be CLIENT_QUERY and another should be CLIENT_RESPONSE.
So we are still missing CLIENT_QUERY and FORWARDER_QUERY? events - and on the occasion we get a FORWARDER_QUERY - is when the plugin was unsuccesful.

So its the exact same result as from 5 days ago.

- Make sure the QUERY events gets produced along with the RESPONSE events.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add query_tim..." ]
>Compiled from branch dnstap2 - the output is not good.
>
>A single query like this:
>
>dig @localhost dr.dk
>
>Produces 2 CLIENT_RESPONSE events to DNSTAP:

Thanks. That's odd and the only way I can explain that if dnstap internally caches the
messages as we work on the same one via a pointer we overwrite before we send.

Changed this and a fix in the forward plugin to correctly pick up the dnstap plugin if
loaded.

This shows (in my testing)


type: MESSAGE
message:
   type: FORWARDER_QUERY
   query_time: !!timestamp 2020-10-11 15:31:11.136120534
   socket_family: INET
   socket_protocol: UDP
   query_address: 8.8.8.8
   query_port: 53
---
type: MESSAGE
message:
   type: FORWARDER_RESPONSE
   query_time: !!timestamp 2020-10-11 15:31:11.136120534
   response_time: !!timestamp 2020-10-11 15:31:11.188378489
---
type: MESSAGE
message:
   type: CLIENT_QUERY
   query_time: !!timestamp 2020-10-11 15:31:11.136113488
   socket_family: INET
   socket_protocol: UDP
   query_address: 127.0.0.1
   query_port: 60172
---
type: MESSAGE
message:
   type: CLIENT_RESPONSE
   query_time: !!timestamp 2020-10-11 15:31:11.136113488
   response_time: !!timestamp 2020-10-11 15:31:11.188454182
   socket_family: INET
   socket_protocol: UDP
   query_address: 127.0.0.1
   query_port: 60172
---

**Comment by SuperFunks** [comment]
Yes - confirmed! - The events now arrive as expected after the last commit.
Ill begin loadtesting now too

**Comment by SuperFunks** [comment]
OK - initial load testing is done - and the performance does seem great. However!
Upon timeout to an upstream server - we still do not get the CLIENT_QUERY event from DNSTAP.
A quick test with DIG gives me a SERVFAIL back from CoreDNS - but no RESPONSE event sent in DNSPTAP for that either.

```
dnstap.FrameStreamSockInput: accepted a socket connection
{"type":"MESSAGE","message":{"type":"FORWARDER_QUERY","query_time":"2020-10-11T20:27:43.310539075Z","socket_family":"INET","socket_protocol":"UDP","query_address":"10.10.83.113","query_port":53}}
{"type":"MESSAGE","message":{"type":"FORWARDER_QUERY","query_time":"2020-10-11T20:27:43.310539075Z","socket_family":"INET","socket_protocol":"UDP","query_address":"10.10.83.114","query_port":53}}
{"type":"MESSAGE","message":{"type":"FORWARDER_QUERY","query_time":"2020-10-11T20:27:43.310539075Z","socket_family":"INET","socket_protocol":"UDP","query_address":"10.10.84.113","query_port":53}}
{"type":"MESSAGE","message":{"type":"FORWARDER_QUERY","query_time":"2020-10-11T20:27:48.310401604Z","socket_family":"INET","socket_protocol":"UDP","query_address":"10.10.83.113","query_port":53}}
{"type":"MESSAGE","message":{"type":"FORWARDER_QUERY","query_time":"2020-10-11T20:27:48.310401604Z","socket_family":"INET","socket_protocol":"UDP","query_address":"10.10.83.114","query_port":53}}
{"type":"MESSAGE","message":{"type":"FORWARDER_QUERY","query_time":"2020-10-11T20:27:48.310401604Z","socket_family":"INET","socket_protocol":"UDP","query_address":"10.10.84.113","query_port":53}}
```

But we do get CoreDNS's attempts to retry against the Sequence of upstreams servers specified in the Corefile.

So yeah - performance is good - but we have lost the CLIENT_QUERY and possibly CLIENT_RESPONSE with SERVFAIL, upon upstream timeout.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add query_tim..." ]
>OK - initial load testing is done - and the performance does seem great.
>However!

excellent

>Upon timeout to an upstream server - we still do not get the CLIENT_QUERY event
>from DNSTAP.
>A quick test with DIG gives me a SERVFAIL back from CoreDNS - but no RESPONSE
>event sent in DNSPTAP for that either.

that code: https://github.com/coredns/coredns/pull/4179/files#diff-b12d06e8aa6117ce05d5715e1c8930c3
didn't change much. If there is no reply it will not be send back.

Note coredns synthesis a servfail later and this is then returned to the client.

/Miek

--
Miek Gieben

**Comment by SuperFunks** [comment]
I see - ill check if the timeout scenario also gives no CLIENT_QUERY events in the old version.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add query_tim..." ]
>I see - ill check if the timeout scenario also gives no CLIENT_QUERY events in
>the old version.

ack. We can of course fix that (here and now), but not sure how to signal timeout into
dnstap.

/Miek

--
Miek Gieben

**Comment by SuperFunks** [comment]
I see this was merged, but did we get the Client_Query on upstream failure in the DNSTAP, or should i create a feature request?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add query_tim..." ]
>I see this was merged, but did we get the Client_Query on upstream failure in
>the DNSTAP, or should i create a feature request?

afaict that never worked and as there isn't an upstream repsonse,so that would be a
feature request

**Comment by miekg** [comment]
this has been fixed. Closing this ticket.
