### ISSUE TITLE
Cache plugin should allow returned records to be shuffled for better load-balancing

### ISSUE THREAD

**Issue by aitorpazos** [coredns/coredns#4170]
**What would you like to be added**:
Currently, when I try to use the cache plugin (tested with `A` records), all records are returned exactly in the same order during the MINTTL, which has an important impact on the load-balancing behavior for different services.

**Why is this needed**:
It would be desirable to change the behavior so the returned values are shuffled on every request or at least have the option to enable this behavior.

**Comment by chrisohaver** [comment]
The _loadbalance_ plugin will randomize response order.

**Comment by aitorpazos** [comment]
I tried to use the `loadbalance` plugin and it didn't work, initially keeping as we had it before using cache:
```
<zone> {
    log . {
        class denial error
    }
    errors
    prometheus :19153
    bind 0.0.0.0
    reload
    loadbalance round_robin
    forward . <forward ips> {
        policy sequential
        max_fails 1
    }
    alternate SERVFAIL,REFUSED . <alternate ips>
    cache {
      <cache settings>
    }
}
```
and then adding the `loadbanace round_robin` entry at the end, same behaviour:
```
<zone> {
    log . {
        class denial error
    }
    errors
    prometheus :19153
    bind 0.0.0.0
    reload
    forward . <forward ips> {
        policy sequential
        max_fails 1
    }
    alternate SERVFAIL,REFUSED . <alternate ips>
    cache {
      <cache settings>
    }
    loadbalance round_robin
}
```
Should I expect it to work if I place it at the end and treat it as a bug if it doesn't perform the shuffling?

**Comment by aitorpazos** [comment]
Same output no matter where `loadbalance` is placed:
```
$ for i in $(seq 1 3);do echo "Iteration $i:"; dig +short @localhost -p 5553 consul.query.consul ; done
Iteration 1:
10.30.1.200
10.30.1.201
10.30.1.202
Iteration 2:
10.30.1.200
10.30.1.201
10.30.1.202
Iteration 3:
10.30.1.200
10.30.1.201
10.30.1.202
```

**Comment by chrisohaver** [comment]
Thanks - the code appears to have been written with the intent that this should work.  I'll take a deeper look at the code to see why it doesn't. Perhaps cache is not honoring the underlying response writer.

FYI - the order of plugins doesn't matter in the Corefile. Order of execution is determined by `/plugin.cfg`, in which _loadbalanace_ appears before _cache_ as expected for it to take effect.

**Comment by chrisohaver** [comment]
Before diving into the code, I did a quick test. 
The following works for me, randomizing answers as expected.
```
. {
  loadbalance
  cache
  forward . 8.8.8.8
}

```

**Comment by johnbelamaric** [comment]
Hmm. Speculation but ordering can be affected by the local resolver, though I would expect `dig` implements its own resolver. See https://github.com/coredns/learning-coredns/tree/master/plugins/onlyone

**Comment by chrisohaver** [comment]
I tested with `dig +short` above.  Load balancing cached responses worked as expected, order was random.

Could be CoreDNS didn't reload config change yet?
A local DNS cache in between dig and CoreDNS?

Hard to tell. Parts of the Corefile are scrubbed.

**Comment by aitorpazos** [comment]
After some more testing, let me provide a reproducible config and outputs to see this issue at play.

With this Corefile, it works as expected :+1: :
```
. {
    log . {
        class denial error
    }
    errors
    prometheus :19153
    bind 0.0.0.0
    reload
    loadbalance
    # cache
    forward . 8.8.8.8 {
        policy sequential
        max_fails 1
    }
    alternate SERVFAIL,REFUSED . 8.8.8.8
}
```
Output:
```
$ for i in $(seq 1 3);do echo "Iteration $i:"; dig +short @localhost -p 5553 www.youtube.com ; done
Iteration 1:
youtube-ui.l.google.com.
216.58.209.78
172.217.17.14
216.58.211.46
216.58.211.238
172.217.168.174
Iteration 2:
youtube-ui.l.google.com.
172.217.17.14
216.58.211.238
216.58.211.46
216.58.209.78
172.217.168.174
Iteration 3:
youtube-ui.l.google.com.
172.217.17.14
216.58.209.78
216.58.201.174
216.58.211.46
172.217.168.174
216.58.211.238
```

With this Corefile, it DOESN'T WORK :-1: :
```
. {
    log . {
        class denial error
    }
    errors
    prometheus :19153
    bind 0.0.0.0
    reload
    loadbalance
    cache
    forward . 8.8.8.8 {
        policy sequential
        max_fails 1
    }
    alternate SERVFAIL,REFUSED . 8.8.8.8
}
```
Output:
```
$ for i in $(seq 1 3);do echo "Iteration $i:"; dig +short @localhost -p 5553 www.youtube.com ; done
Iteration 1:
youtube-ui.l.google.com.
216.58.209.78
216.58.211.46
172.217.168.174
172.217.17.14
216.58.201.142
Iteration 2:
youtube-ui.l.google.com.
216.58.209.78
216.58.211.46
172.217.168.174
172.217.17.14
216.58.201.142
Iteration 3:
youtube-ui.l.google.com.
216.58.209.78
216.58.211.46
172.217.168.174
172.217.17.14
216.58.201.142
```

**Comment by chrisohaver** [comment]
It works as expected (randomized responses) in both instances when I try your example configs with a CoreDNS compiled with the alternate plugin.

What version of CoreDNS are you building on, and where are you positioning alternate plugin in plugin.cfg?
I built with CoreDNS @ master + alternate updated for recent caddy package move.

**Comment by aitorpazos** [comment]
Using CoreDNS 1.7.1 with the following plugin.cfg:
```
reload:reload
bind:bind
cache:cache
debug:debug
health:health
prometheus:metrics
errors:errors
log:log
dnstap:dnstap
acl:acl
loadbalance:loadbalance
alternate:github.com/coredns/alternate
forward:forward
on:github.com/caddyserver/caddy/onevent
secondary:secondary
bufsize:bufsize
```

**Comment by chrisohaver** [comment]
Ah.  You have also changed the order of plugins in `plugin.cfg` from the default.

loadbalance needs to go _before_ cache in `plugin.cfg`, otherwise answers from cache never get processed by the loadbalance plugin.
