### ISSUE TITLE
1.8.0 release tracking bug

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4172]
Track the 1.8.0 release

**Comment by miekg** [comment]
prolly want https://github.com/coredns/coredns/issues/4160 in there

**Comment by miekg** [comment]
and https://github.com/coredns/coredns/pull/4179 (although that doesn't have to be in 1.8.0)

**Comment by miekg** [comment]
this leaves https://github.com/coredns/coredns/pull/4190, as #4179 is now also merged.

**Comment by miekg** [comment]
all the bits are assembled, we can release. a miekg/dns update would fix a forward bug, might as well wait for that. Other than that we are good to go

**Comment by miekg** [comment]
and of course: https://github.com/coredns/coredns/pull/4207
(I decided to check one more time yesterday evening - rational in the PR)

**Comment by mrueg** [comment]
@miekg seems like those are all merged, would it be possible to release 1.8.0 soon?

**Comment by miekg** [comment]
Yes. This is good to go. I will do the needful tomorrow (Thu)

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/4225
