### ISSUE TITLE
Unable to compile CoreDNS with external Unbound plug-in

### ISSUE THREAD

**Issue by SuperFunks** [coredns/coredns#4173]
**What happened**:

$ go generate && go build
go: finding module for package github.com/coredns/unbound
go: downloading github.com/coredns/unbound v0.0.6
go: found github.com/coredns/unbound in github.com/coredns/unbound v0.0.6
go: finding module for package github.com/miekg/unbound
go: finding module for package github.com/caddyserver/caddy
go: downloading github.com/miekg/unbound v0.0.0-20180419064740-e2b53b2dbcba
go: downloading github.com/caddyserver/caddy v1.0.5
go: found github.com/caddyserver/caddy in github.com/caddyserver/caddy v1.0.5
go: found github.com/miekg/unbound in github.com/miekg/unbound v0.0.0-20180419064740-e2b53b2dbcba
\# github.com/coredns/unbound
/root/go/pkg/mod/github.com/coredns/unbound@v0.0.6/setup.go:24:21: cannot use c (type *"github.com/caddyserver/caddy".Controller) as type *"github.com/coredns/caddy".Controller in argument to dnsserver.GetConfig
/root/go/pkg/mod/github.com/coredns/unbound@v0.0.6/setup.go:31:28: cannot use c (type *"github.com/caddyserver/caddy".Controller) as type *"github.com/coredns/caddy".Controller in argument to dnsserver.GetConfig

**What you expected to happen**:
Successful compilation with Unbound

**How to reproduce it (as minimally and precisely as possible)**:
1: git clone https://github.com/coredns/coredns.git
2: Edit plugin.cfg to include unbound:github.com/coredns/unbound
3: Run go generate && go build

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.7.1
- Corefile: N/A
- logs, if applicable: N/A
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)

**Comment by SuperFunks** [comment]
Hmm - if i specifically checkout 1.7.1 it does seem to work though

1: git clone https://github.com/coredns/coredns.git
2: git checkout v1.7.1
3: Edit plugin.cfg to include unbound:github.com/coredns/unbound
4: Run go generate && go build

Works just fine. Is that intended?

**Comment by SuperFunks** [comment]
Just confirmed once more that the dependency error occurs, when I'm on the current master branch.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Unable to compile..." ]
>What happened:
>
>$ go generate && go build

you need `@master` and I've also tagged v0.0.7 with this fix

/close
/label external
