### ISSUE TITLE
Reverse lookup of statefulset pods should only return only $(podname).$(governing service domain) 

### ISSUE THREAD

**Issue by miheer** [coredns/coredns#4181]
**What happened**:
Reverse lookup of statefulset pods should only return only $(podname).$(governing service domain) as per upstream kubernetes doc https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id

 The code in the pull request https://github.com/coredns/coredns/pull/3687  will allow the reverse lookup to reply with all records for the IP. Such that, say if there are 4 headless services pointing to an endpoint, a reverse lookup would answer with 4 records

As per kubernetes standards ->" The domain managed by this Service takes the form: $(service name).$(namespace).svc.cluster.local, where "cluster.local" is the cluster domain. As each Pod is created, it gets a matching DNS subdomain, taking the form: $(podname).$(governing service domain), where the governing service is defined by the serviceName field on the StatefulSet."

Reference - https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id

As per this code while doing reverse lookup all the results will be returned whereas only the form: $(podname).$(governing service domain) shall be returned as per the above kubernetes doc link.

This also causes issue in applications like zookeeper because I don't see where Zookeeper iterates over the results.  
Zookeeper uses getHostName, and getHostName picks just one of the results, and it may pick the wrong one.

The fix https://github.com/coredns/coredns/pull/3687  will allow the reverse lookup to reply with all records for the IP. Such that, say if there are 4 headless services pointing to an endpoint, a reverse lookup would answer with 4 records.

But https://github.com/apache/zookeeper/blob/495906063078a477e26f4e99e14dfe8f89007625/zookeeper-server/src/main/java/org/apache/zookeeper/SaslServerPrincipal.java#L105

returns a string  not an array. 

https://github.com/apache/zookeeper/blob/master/zookeeper-server/src/main/java/org/apache/zookeeper/common/ZKTrustManager.java#L158

**What you expected to happen**:
Reverse lookup of statefulset pod ip should return pod name $(podname).$(governing service domain)  as per https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id

It will be good to have coredns return  only one record while doing a reverse lookup specified as per kubernetes standards https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id

Also right practices while doing reverse lookups are to return a single record. Some useful information in the following link ->
https://serverfault.com/questions/618700/why-multiple-ptr-records-in-dns-is-not-recommended

**How to reproduce it (as minimally and precisely as possible)**:
1.Install operator Strimzi
2.Install kafka
3.Try to do reverse lookup from any statefulset pod

The developer had asked few questions in the issue while implementing the PR https://github.com/coredns/coredns/issues/3686#issuecomment-589164195
"Will this cause confusion on the client's part? Receiving multiple answers? If so, how would we know which answer to provide? We could prioritize headless services, but what if there are more than one headless service pointing to the ip?"

My answer is ->

In the case of StatefulSets, we have an answer:  The StatefulSet's serviceName field specifies which service to use.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: built image from the master branch and used in openshift dns operator
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): CoreOS
- Others:

**Comment by chrisohaver** [comment]
The kubernetes plugin intends to implement the [Kubernetes DNS-Based Service Discovery](https://github.com/kubernetes/dns/blob/master/docs/specification.md) specification.

That document does not define the behavior described in https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id.

I'm aware of a couple of places now in the k8s docs that describe DNS behavior which is not defined in the DNS specification.  My understanding is that the  [Kubernetes DNS-Based Service Discovery](https://github.com/kubernetes/dns/blob/master/docs/specification.md) specification completely defines the requirements.  I'm unsure how to resolve the apparent documentation contradictions.

I'll raise this question with the Kubernetes DNS owners.

**Comment by chrisohaver** [comment]
> ... whereas only the form: $(podname).$(governing service domain) shall be returned as per the above kubernetes doc link

Reading more closely, the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) doesn't explicitly say that. It doesn't define reverse lookup behavior.  It just says that an A record should exist, which it does because a Headless service must exist for the stateful set. But it does not say that a reverse lookup on the IP should only return that one service, if more than one headless service selects the pod.

As far as multiple response from a PTR response: The spec says that for each endpoint there must be a PTR record: https://github.com/kubernetes/dns/blob/master/docs/specification.md#243---ptr-records.  So if there are multiple endpoints for a pod (e.g. due to multiple headless services selecting a Pod), then the pod gets multiple PTR records.

IOW, the documentation and the spec don't seem to conflict.

**Comment by chrisohaver** [comment]
This kind of customization should be done as an external plugin.

**Comment by mpmprock3** [comment]
@chrisohaver for two headless service it return one response only at a time for reverse lookup but we have inconsistent PTR record returned i.e sometimes it return name and sometime ip address **my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local or 
10-131-0-48.my-cluster-kafka-bootstrap.kafka.svc.cluster.local** . I think this is not expected behaviour.

```
$ for i in {1..10};do ifconfig | awk "/inet /{ print \$2; exit }" | xargs nslookup;done
48.0.131.10.in-addr.arpa	name = my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = 10-131-0-48.my-cluster-kafka-bootstrap.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = 10-131-0-48.my-cluster-kafka-bootstrap.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = 10-131-0-48.my-cluster-kafka-bootstrap.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = 10-131-0-48.my-cluster-kafka-bootstrap.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.

48.0.131.10.in-addr.arpa	name = 10-131-0-48.my-cluster-kafka-bootstrap.kafka.svc.cluster.local.
```

**Comment by chrisohaver** [comment]
Is it possible that `nslookup` is only displaying one result, and ignoring the other? Do you get the same result using `dig`?

**Comment by chrisohaver** [comment]
> Is is possible that `nslookup` is only displaying one result, and ignoring the other?

Yes - `nslookup -type=PTR 1.2.3.4`, will list them all.  `nslookup 1.2.3.4` will just display one, probably the first one, which is random due to _loadbalance_ plugin.

https://serverfault.com/questions/148401/how-do-i-check-a-ptr-record
