### ISSUE TITLE
README's it's 'SEE ALSO' not Also See

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4196]
Just looked at some man pages and they use 'See Also', not 'Also See' as the reference section. Should probably refer those words in all README.md's and in plugin.md where we detail this.

**Comment by saptarsi96** [comment]
@miekg Can you please elaborate on what changes need to be done for this issue?

**Comment by miekg** [comment]
Eg. https://coredns.io/plugins/any/#also-see must be reworded to "See Also". And this change must be made to all plugin READMEs that have such a section.

https://github.com/coredns/coredns/blob/master/plugin.md#documentation might need some extra text as well, to discuss the use of a See Also section.
