### ISSUE TITLE
Enhance configuration of dnstap plugin

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#4198]
**What would you like to be added**:

Plugin `dnstap` should support configuration options for allowed types of DNSTAP messages.
The config may look like
```
  dnstap tcp://127.0.0.1:9123 full CR FR
```
where all parameters after endpoint are optional
or
```
  dnstap tcp://127.0.0.1:9123 full {
    allow CR FR
  }
```
Other plugins should be able to check these config options. Bunch of booleans is ok.
See also https://github.com/coredns/coredns/pull/4179#discussion_r502541328 for reference

**Why is this needed**:
PR #4179 removed the ability to disable CQ and/or CR messages with flags passes via context. 
Adding the configuration options to dnstap plugin will restore ability to control generation of dnstap messages of particular types.

Note, other popular DNS servers (e.g. unbound) also have similar configuration options.

**Comment by miekg** [comment]
I would prefer the second syntax and probable s/allow/options/. Potentially also not using the abbreviations, because 'CR', 'FR' require deep knowledge of dnstap

**Comment by miekg** [comment]
no one is picking this up
