### ISSUE TITLE
plugin/kubernetes: Adjust Endpoints watch to support dual stack

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#4202]
**What would you like to be added**:

Migrate Endpoints watch to EndpointSlice to add support for dual stack headless services/endpoints.

**Why is this needed**:

In the latest Kubernetes implementation of dual-stack, the core Endpoints object will not be populated with both IPv6/IPv4 IPs for dual stack headless Services. Both IPs are available in the EndpointSlice object. EndpointSlice is currently beta, but should be GA next k8s release.

**Comment by chrisohaver** [comment]
Work in progress: https://github.com/coredns/coredns/compare/master...chrisohaver:k8s-epslices

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>Work in progress: master...chrisohaver:k8s-epslices

I wondered when we would need to look at endpoint slices. How do we know to use it?
Version check on the api?

**Comment by chrisohaver** [comment]
> Version check on the api?

Not sure yet. I think whether or not kube-proxy etal uses EndpointSlice as the "source of truth" for service->pod routing was optional/configurable in k8s for some number of releases .... so I may need to hunt down that config setting (hopefully stashed somewhere in the API).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/kubern..." ]
>    Version check on the api?
>
>Not sure yet. I think whether or not kube-proxy etal uses EndpointSlice as the
>"source of truth" for service->pod routing was optional/configurable in k8s for
>some number of releases .... so I may need to hunt down that config setting
>(hopefully stashed somewhere in the API).

linkerd and prometheus have added EndpointSlice, so here's hoping that they already solved
that problem.

Can you just query for it and see what the API returns?

**Comment by chrisohaver** [comment]
Of course, It would be nice to just cut over to EndpointSlice instead of supporting both in parallel. And I think we _almost_ could have ...

EndpointSlice has been populated with Service->Pod targets by default since 1.18. ... but ...

Unfortunately, EndpointSliceMirroring, where custom Endpoints are mirrored to EndpointSlices, was not added until k8s 1.19.  So people at 1.18 (still under k8s support when 1.20 releases) with custom Endpoints would need CoreDNS to monitor Endpoints instead of EndpointSlice.  So, in the event that a k8s 1.18 user needs a CoreDNS bug fix, the current version of CoreDNS would need to support Endpoint watch.
