### ISSUE TITLE
Intermittent DNS resolution

### ISSUE THREAD

**Issue by dfioravanti** [coredns/coredns#4206]
**What happened**:
We are running our bare metal cluster inside a local network called company.local. The first time a service.company.local name is resolved we get a NXDOMAIN error. All the subsequent queries are answered correctly. It problem does not exist outside the kubernetes cluster. I think this is the same issue as in  #4146 but I tried

1. Downgrade to 1.7.0 
2. Remove cashing 

and it is still present so maybe it is different.

**What you expected to happen**:
All the queries are answered correctly

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
kubectl exec -i -t dnsutils -- nslookup service.company.local
```

**Anything else we need to know?**:

If I run `snlookup` directly against the company.local dns server this issue does not happen. It happens only if query the kubernetes dns

**Environment**:

- the version of CoreDNS: 1.7.1
- Corefile:
```
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        loop
        reload
        loadbalance
        cache 30
    }
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```
- Others:

**Comment by chrisohaver** [comment]
What is the contents of `/etc/resolv.conf` on the node?

**Comment by dfioravanti** [comment]
Indeed there seams to have been a problem with the /etc/resolv.conf file. There was some internal miscommunication and the file was misconfigured as I was told the wrong IP. I think this has nothing to do with coredns but currently our Internet is currently dead so I cannot 100% confirm. I will close the issue and reopen if we figure out that the problem really exists. Sorry for the waste of time.
