### ISSUE TITLE
IP address filter 

### ISSUE THREAD

**Issue by ganeshr2** [coredns/coredns#4208]
I have the following requirement: 
Upstream dns send me  A and AAAA record for a dns. But within kubernetes for certain domain I should filter out and pass just the AAAA record.

its like querying eg: nslookup -query=AAAA $hostname

what is the best way to get this done in CoreDNS.

I know we can define record and point to that record which will be static approach. I am looking for some ways to do this dynamically.

Thanks,
Ganesh

**Comment by johnbelamaric** [comment]
I don't think we have a plugin that does that, but it should be easy to write. The `onlyone` plugin in the learning-coredns repo gets pretty close, you could start with that as a base.

**Comment by chrisohaver** [comment]
A DNS will only send back A and AAAA if the client makes 2 requests, one for A and one for AAAA.
The best way to solve this is to make the clients only request AAAA, and not also the A record.

**Comment by chrisohaver** [comment]
As a hack, you can use the _template_ plugin to respond negatively to `A` requests for certain domains ...  although this may have side effects.

**Comment by ganeshr2** [comment]
ok thank you all for the quick response!

chrisohaver: "The best way to solve this is to make the clients only request AAAA," 
Ganesh: " yes absolutely,  but unfortunately the client does not do that."

**Comment by chrisohaver** [comment]
OK, so if your client is always going to make two separate requests per lookup, AAAA and A, the only way to "block" A resposnes would be to...
* have CoreDNS ignore the `A` requests (no response at all), in which case client would have to wait for timeout.
* have CoreDNS respond with NXDOMAIN - which might confuse clients if it gets that response before the positive AAAA respose.
* have CoreDNS respond with NODATA - which might confuse clients during short name domain list searches

I _think_ the last one is the least problematic. It can be done with the template plugin. e.g. `template IN A mydomain.com` ... will always reply NODATA to `A` queries in mydomain.com .

**Comment by ganeshr2** [comment]
template with NODATA worked! thank you for the quick help! 

appreciate! 

   abcd.com:53 {
      forward . 8.8.8.8
      template IN A abcd.com
      errors
      log . {
        class denial
      }
    }

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] IP address fi..." ]
>Closed #4208.

/label question
