### ISSUE TITLE
plugin/cache: panic: runtime error: invalid memory address or nil pointer dereference,

### ISSUE THREAD

**Issue by milgradesec** [coredns/coredns#4218]
**What happened**:

```
panic: runtime error: invalid memory address or nil pointer dereference,
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x327260],
goroutine 298130 [running]:,
github.com/miekg/dns.(*EDNS0_PADDING).copy(0x0, 0x1, 0x1),
	/go/pkg/mod/github.com/miekg/dns@v1.1.32/edns.go:672 +0x20,
github.com/miekg/dns.(*OPT).copy(0x4000acc100, 0x1, 0x1),
	/go/pkg/mod/github.com/miekg/dns@v1.1.32/ztypes.go:855 +0x90,
github.com/miekg/dns.(*Msg).CopyTo(0x40006465a0, 0x4000740870, 0x40011b2480),
	/go/pkg/mod/github.com/miekg/dns@v1.1.32/msg.go:1069 +0x2ec,
github.com/miekg/dns.(*Msg).Copy(...),
	/go/pkg/mod/github.com/miekg/dns@v1.1.32/msg.go:1043,
github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS.func1(0x40006465a0, 0xfffffe0d0b3f0a00, 0x4000345560, 0x40011b0d80, 0x400058e830, 0xc, 0xab9f80, 0x4000acc140, 0xab11e0, 0x4000f17320),
	/go/src/app/coredns/plugin/cache/handler.go:52 +0x38,
created by github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS,
	/go/src/app/coredns/plugin/cache/handler.go:51 +0x47c,
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Crashed running as home DNS server, can't reproduce

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.7.1
- Corefile:
```
grpc://.:5300 {
    prometheus :9153
    
    cache {
        serve_stale
    }
    hosts /etc/Coredns/hosts {
        fallthrough
    }
    grpc . 127.0.0.1:5301
}
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Others: linux/arm64, go1.15.3

**Comment by miekg** [comment]
Looks vaguely similar to https://github.com/coredns/coredns/issues/4047

**Comment by miekg** [comment]
this needs a dump of the packet grpc is returning or decoding. Yes a `nil` `copy()` of an `EDNS0_PADDING` will panic. As one shoulnd't call it with a `nil` pointer. This could be mitigated in `msg.Copy()`, but there should not be a `nil` RR in the packet.

**Comment by miekg** [comment]
*or* we're holding grpc wrong and some buffer is rewritten from under us

**Comment by miekg** [comment]
can you replicate with master or the last release?

**Comment by milgradesec** [comment]
running v1.8.3 with grpc for ~20h, nothing has crashed so far
