### ISSUE TITLE
plugin/bind: Add an option to exempt some interfaces to bind. 

### ISSUE THREAD

**Issue by m-yosefpor** [coredns/coredns#4219]
**What would you like to be added**:
Add an option to exempt interfaces for coredns to bind to.

```
.:53 {
  bind {
      interfaces 0.0.0.0
      except-interfaces 127.0.0.1
  }
  .. whatever config here ...
}
```

**Why is this needed**:
We are going to migrate our production services from dnsmasq to coredns, and there is an option called `--except-interface` in dnsmasq to exempt some interfaces which it listens to (since they are already in use by some other services due to our dns architecture). So we need coredns to be able to listen on all interfaces other than a specific interface (in our case `lo`)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/bind: Add ..." ]
>What would you like to be added:
>Add an option to exempt interfaces for coredns to bind to.
>
>.:53 {
>  bind {
>      interfaces 0.0.0.0
>      except-interfaces 127.0.0.1
>  }
>  .. whatever config here ...
>}
>
>Why is this needed:
>We are going to migrate our production services from dnsmasq to coredns, and
>there is an option called --except-interface in dnsmasq to exempt some
>interfaces which it listens to (since they are already in use by some other
>services due to our dns architecture). So we need coredns to be able to listen
>on all interfaces other than a specific interface (in our case lo)

the current impl just binds on the ports listed. Excluding interfaces requires listing
interfaces and assigned addresses in a portable way (not sure that even exists for Go).

You probably either want to generate the list, or run in a network namespace.


/label plugin/bind

**Comment by miekg** [comment]
this is unlikely to be implemented

**Comment by m-yosefpor** [comment]
@miekg 
what about naming an interface with its name instead of ip?
e.g.
```
.:53 {
  bind eth0
  .. whatever config here ...
}
```

shall I open a new issue for it? or it won't be implemented either?

The main issue is we have to run CoreDNS as DaemonSet in host network namespace for some reason, so the Corefile Configmap is identical for all pods running on any node. We don't have the option to listen on all interfaces. So we need to exclude some, or listen on a specific interface by its name

**Comment by johnbelamaric** [comment]
As I recall that is actually quite difficult because the internal routines
bind by IP. Binding by “name” is typically implemented by figuring out the
IP on that interface and then binding to that. So it’s not clear what you
are asking for.

**Comment by m-yosefpor** [comment]
This is yet another feature which is already implemented in dnsmasq.
The plugin can check if the argument provided to bind matches a ip address OR matches an interface name. 
So can't it be implemented by sth like this, when modules are initialized?

```
list, err := net.Interfaces()

for _, iface := range list {
    if  iface.Name == exampleModuleArg {
      addrs, err := iface.Addrs()
  }
}
```

The same approach can be used to implement `exclude interface`. So is there any specific reason why you are telling this can be difficult to achieve? (I'm not a Go expert, just asking)

**Comment by johnbelamaric** [comment]
Yes, that is binding by IP still, at the core. How is that different, other
than convenience? Maybe I misunderstood the reason you are asking for this.

Not saying convenience isn’t a good reason, but trying to understand if
there is something more.

**Comment by johnbelamaric** [comment]
I was assuming you were looking for some sort of layer-2 association of the
socket to the interface, for example in the event that you are tying the
same IP to multiple interfaces via independent routing tables in the
kernel. That’s hard and not very universally useful. If all you want is the
convenience, it’s easy as you demonstrated.

**Comment by m-yosefpor** [comment]
Sorry I should have explained my self better. Yeah actually what I was looking for was a convenient way, and making Corefile config more generic. I didn't mean any core functional change.

In our case  it helps since we can have Corefile as a ConfigMap object and it is shared identically in all nodes. So we don't need to generate/template it per host.

So shall I go for its implementation and creating the subsequent PRs? (both for `interface by name`, and `exclude-interface`)

As it would be my first contribution to CoreDNS, I'm not sure to go for this or https://github.com/coredns/coredns/issues/4220. (Maybe both 😄) Any suggestions?

Also shall we reopen this issue?

**Comment by johnbelamaric** [comment]
By name makes sense and is easy, I would say go for it. Not sure what the
"exclude" would look like.

Unless Miek has some strong objection for some reason.

**Comment by lukasmrtvy** [comment]
This is valid use case, there is always system-resolved sitting on 127.0.0.53:53 by default in every systemd distro.
Would be nice to have ability to have something like: `bind: !127.0.0.53` to negate addresses to listen on.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/bind: ..." ]
>By name makes sense and is easy, I would say go for it. Not sure what the
>"exclude" would look like.
>
>Unless Miek has some strong objection for some reason.

wasn't aware `net` package has this stuff, so sgtm

`exclude` might be way more problematic

**Comment by sslavic** [comment]
@m-yosefpor were you able to make progress on any of the two options?

**Comment by m-yosefpor** [comment]
@sslavic yeah actually I implemented the bind by interface name and tested it, afterwards we solved our issue with an alternative workaround and I totally forgot to create the MR. Thanks for reminding me. I'll create the MR in the following days.

**Comment by sslavic** [comment]
@m-yosefpor bind by interface name is great, thank you very much for contributing! ❤️ 

Problem is, it's not quite the same thing as exempting an interface.

E.g. to exempt CoreDNS from listening on loopback, on EKS worker node where number of interfaces is dynamic (see [docs](https://docs.aws.amazon.com/eks/latest/userguide/pod-networking.html)), to be able to bind dnsmasq on loopback and CoreDNS on all other interfaces, while both are running on host network, think I'd need either:
- more flexible allow list of interfaces to listen on, e.g. bind by interface name wildcard or pattern, so `bind eth*`, or
- true deny list of names of interfaces not to listen on, e.g. `bind !lo` or through configuration `bind {except-interfaces lo}`

Does such feature make sense? If so, shall we reopen this issue?

**Comment by m-yosefpor** [comment]
@sslavic both wildcard pattern and exempt interface are simple to implement, and I'm willing to implement. I only need to hear what maintainers think of this idea, and if they have any objections. @miekg seems to had a concern about exempting interface

> `exclude` might be way more problematic

Implementing regexp matching is intuitive,  and the idea of exempting IPs/Interfaces is to remove whatever IP or Interface IPs provided in `except`, after calculating the `all` array.

```
.:53 {
  bind {
      include 192.168.1.2 eth* ens0
      except 127.0.0.1 eth1
  }
  .. whatever config here ...
}
```

We should also mention in documents that the order of  `except` and `include` does not matter and that `except` option always override the other. This is also the default behavior in dnsmasq.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] plugin/bind: ..." ]
>.:53 {
>  bind {
>      interfaces 0.0.0.0
>      except 127.0.0.1
>  }
>  .. whatever config here ...
>}
>
>We should also mention in documents that the order of except and interfaces
>does not matter and that except option always override the other. This is also
>default behavior in dnsmasq.

If that's easy, please continue to add an `except` here.

I think a globbing pattern for interface matching is way over the top, so no

**Comment by m-yosefpor** [comment]
I just noticed that bind directive can be used multiple times in a block. So there are 3 ways of implementing this:

1. We can calculate all bind IPs for each directive separately (`{includes} - {excludes}`), and calculate union of the results for all of them together.

e.g.
```
. {
     bind 1.1.1.1 2.2.2.2 { // this only adds 2.2.2.2
        except 1.1.1.1
     }
     bind 1.1.1.1 3.3.3.3 { // this only adds 1.1.1.1
         except 3.3.3.3
      }
```

Server will bind on `2.2.2.2` and ALSO `1.1.1.1` (which was excluded in first directive).

2. Calculate the Union of all includes, and then exclude the `except` ones (this is not intuitive and I don't recommend). For the previous example it would be: `{ 1.1.1.1, 2.2.2.2, 3.3.3.3 } - { 1.1.1.1 , 3.3.3.3 } = { 2.2.2.2 }`

3. We can force bind to be in the server block just once (I prefer this one, but this introduces a backward incompatible change in Corefile!)

Which one do you recommend?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] plugin/bind: ..." ]
>I just noticed that bind directive can be used multiple times in a block. So
>there are 3 ways of implementing this:
>
> 1. We can calculate all bind IPs for each directive separately ({includes} -
>    {excludes}), and calculate union of the results for all of them together.

Think this makes most sense.


> 3. We can force bind to be in the server block just once (I prefer this one,
>    but this introduces a backward incompatible change in Corefile!)
>
>Which one do you recommend?

nr 1, for 3. it's a bit of  niche feature to make this backwards incompatible.
