### ISSUE TITLE
add *minimal* plugin

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4220]
**What would you like to be added**:
Add a new plugin that minimizes responses as describe (e.g.) in the BIND manual
~~~
minimal-responses

 minimal-responses yes | no ;
 minimal-responses yes ;

If yes the server will only add records to the authority and additional data sections when they are required e.g. delegations, negative responses. This may improve the performance of the server. The BIND default is no. This statement may be used in a view or a global options clause.
~~~

**Why is this needed**:
This is another way to help UDP fragmentation. Unlike BIND this won't be a speed up because this plugin will only strip records that have been added by other plugins.

**Comment by chrisohaver** [comment]
IMO this would be a good "first plugin" for a contributor who hasn't written a plugin yet, and as looking for such an opportunity.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add *minimal*..." ]
>IMO this would be a good "first plugin" for a contributor who hasn't written a
>plugin yet, and as looking for such an opportunity.

agreed

**Comment by bharath-12345** [comment]
@miekg would like to pick this up. Please do assign me to this.

**Comment by bharath-123** [comment]
@miekg  and all. I would like to pick this issue up. Please assign me to this.

**Comment by bharath-123** [comment]
I am new to coredns. I will take some time to do my research to understand the plugin requirements and start implementing it.

**Comment by bharath-123** [comment]
Any references or suggestions as to how to begin would be really useful :)

**Comment by chrisohaver** [comment]
There is https://coredns.io/2016/12/19/writing-plugins-for-coredns/, which is quite old but still mostly relevant.
For this kind of plugin, one that is modifying the results produced by other plugins, you should use a wrapper around the responsewriter that stores the response instead of writing to the client when calling the next plugin. When you get a result fro the next plugin, you can then strip the unnecessary records response and write to the client.  A great example of this comes from the Learning CoreDNS O'Reilly Book, the _onlyone_ plugin: https://github.com/coredns/learning-coredns/blob/master/plugins/onlyone/onlyone.go.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add *minimal*..." ]
>There is https://coredns.io/2016/12/19/writing-plugins-for-coredns/, which is
>quite old but still mostly relevant.
>For this kind of plugin, one that is modifying the results produced by other
>plugins, you should use a wrapper around the responsewriter that stores the
>response instead of writing to the client when calling the next plugin. When
>you get a result fro the next plugin, you can then strip the unnecessary
>records response and write to the client. A great example of this comes from
>the Learning CoreDNS O'Reilly Book, the onlyone plugin: https://github.com/
>coredns/learning-coredns/blob/master/plugins/onlyone/onlyone.go.

+1 to this.

I would mostly focus on other plugins, and I almost already write the README.md first so I
get a bit of feel on what things will look like.

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
> write the README.md first

Yes, this has worked well before. You can start the PR with just a README which includes syntax, and get early feedback from reviewers before investing time on implementation.

**Comment by bharath-123** [comment]
@chrisohaver @miekg got it. If I understand the functionality required of the plugin right basically what is required is that the response returned after querying coredns should be minimal. right now when I run the following dig command
`dig @8.8.8.8 google.com` I get the ANSWER, AUTHORITY and ADDITIONAL records. This plugin would not fetch the AUTHORITY and ADDITIONAL records if not required. I think there should be more to this but this is what I have understood so far. This plugin basically minimizes the dns query response by stripping of unwanted records and by only presenting the most important records.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add *minimal*..." ]
>@chrisohaver @miekg got it. If I understand the functionality required of the
>plugin right basically what is required is that the response returned after
>querying coredns should be minimal. right now when I run the following dig
>command
>dig @8.8.8.8 google.com I get the ANSWER, AUTHORITY and ADDITIONAL records.
>This plugin would not fetch the AUTHORITY and ADDITIONAL records if not
>required. I think there should be more to this but this is what I have
>understood so far. This plugin basically minimizes the dns query response by
>stripping of unwanted records and by only presenting the most important
>records.

I'll try to dig up a doc on what's needed here. For DNS you need to understand that there
are different types of answer, see this code and docs https://github.com/coredns/coredns/tree/master/plugin/pkg/response
You can't just always remove the additional for instance.

Note that this plugin will see the query and do nothing except wrap it in a new
dns.ResponseWriter and will perform it's magic just before the response is written back to
the client.

**Comment by miekg** [comment]
this might have some insights: https://tools.ietf.org/html/draft-andrews-dnsop-glue-is-not-optional-01

**Comment by bharath-123** [comment]
Thanks @miekg ! I am also looking into the implementation of the BIND server. Want to how they have implemented minimal response.

**Comment by bharath-123** [comment]
I am having trouble opening the link you have sent me :(

**Comment by miekg** [comment]
hmm link just works for me, but tools.ietf.org can be flaky

**Comment by bharath-123** [comment]
@miekg @chrisohaver  I am also checking this out to understand the requirements for the minimal-response https://github.com/isc-projects/bind9/commit/d9112843333472bb7700c02a10d18e2b253b2708 This PR seems to be an implementation

I am also reading this https://github.com/isc-projects/bind9/blob/e64e3322a64a35ef246f83526e25bdf17099ec48/lib/ns/query.c 

The core magic seems to be to here
https://github.com/isc-projects/bind9/blob/e64e3322a64a35ef246f83526e25bdf17099ec48/lib/ns/query.c#L11174 where no authority and additional records are returned. 

But there is a special case for glue records.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add *minimal*..." ]
>@miekg @chrisohaver I am also checking this out to understand the requirements
>for the minimal-response isc-projects/bind9@d911284 This PR seems to be an
>implementation
>
>I am also reading this https://github.com/isc-projects/bind9/blob/
>e64e3322a64a35ef246f83526e25bdf17099ec48/lib/ns/query.c
>
>The core magic seems to be to here
>https://github.com/isc-projects/bind9/blob/
>e64e3322a64a35ef246f83526e25bdf17099ec48/lib/ns/query.c#L11174 where no
>authority and additional records are returned.
>
>But there is a special case for glue records.

are there tests as well? Copying what BIND does is fine, _maybe_ double checking with
unbound or something. Would be really good to find some external tests we can port.

**Comment by bharath-123** [comment]
These tests seem interesting https://github.com/isc-projects/bind9/blob/e64e3322a64a35ef246f83526e25bdf17099ec48/bin/tests/system/additional/tests.sh
They are not unit tests but looks like they setup nameservers and run the tests. The dns server to query in the dig command seems to be a private ip address. 
There is also an extra option in bind of no-auth and no-auth-recursive. I don't think no-auth-recursive applies to coredns as coredns cannot do recursive dns querying. But no-auth can be an option.

To my understanding of the requirements. The minimal response plugins intent is to remove the AUTHORITY and ADDITIONAL records in the dns response but we need to mindful to check whether the ADDITIONAL records contain any glue records which are necessary for dns resolution.

**Comment by bharath-123** [comment]
So this is part of the additional section of the system tests of bind9. It sets up a 3 nameservers locally on the loopback interface and runs the tests using them. These are somewhat like unit tests in the sense they test the feature and are completely self contained.

These tests basically run the dig command querying these nameservers and check if the output is as expected.

@miekg @chrisohaver Do you think we can port these tests into coredns and implement the plugin based on these tests?

**Comment by bharath-123** [comment]
So here are some examples I am using to understand the requirements:
1st example:
```
bharath12345@Bharaths-MacBook-Pro system % dig google.com

; <<>> DiG 9.10.6 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37859
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 9

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		293	IN	A	142.250.76.46

;; AUTHORITY SECTION:
google.com.		157127	IN	NS	ns2.google.com.
google.com.		157127	IN	NS	ns1.google.com.
google.com.		157127	IN	NS	ns3.google.com.
google.com.		157127	IN	NS	ns4.google.com.

;; ADDITIONAL SECTION:
ns2.google.com.		316273	IN	A	216.239.34.10
ns2.google.com.		157127	IN	AAAA	2001:4860:4802:34::a
ns3.google.com.		316274	IN	A	216.239.36.10
ns3.google.com.		157127	IN	AAAA	2001:4860:4802:36::a
ns1.google.com.		165555	IN	A	216.239.32.10
ns1.google.com.		165555	IN	AAAA	2001:4860:4802:32::a
ns4.google.com.		190188	IN	A	216.239.38.10
ns4.google.com.		157127	IN	AAAA	2001:4860:4802:38::a

;; Query time: 60 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Sat Oct 31 00:09:40 IST 2020
;; MSG SIZE  rcvd: 303
```
The minimal response in this same should not remove the additional and authority section as there are glue records in the additional section which resolve the nameservers in the authority. Although since the answer already contains the resolved the IP address are the ADDITIONAL and AUTHORITY records really useful now?

2nd example:
```
bharath12345@Bharaths-MacBook-Pro system % dig cure.fit

; <<>> DiG 9.10.6 <<>> cure.fit
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43712
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 6

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cure.fit.			IN	A

;; ANSWER SECTION:
cure.fit.		60	IN	A	54.182.0.7
cure.fit.		60	IN	A	54.182.0.68
cure.fit.		60	IN	A	54.182.0.6
cure.fit.		60	IN	A	54.182.0.128

;; AUTHORITY SECTION:
cure.fit.		157519	IN	NS	ns-1562.awsdns-03.co.uk.
cure.fit.		157519	IN	NS	ns-30.awsdns-03.com.
cure.fit.		157519	IN	NS	ns-562.awsdns-06.net.
cure.fit.		157519	IN	NS	ns-1525.awsdns-62.org.

;; ADDITIONAL SECTION:
ns-30.awsdns-03.com.	161451	IN	A	205.251.192.30
ns-30.awsdns-03.com.	134874	IN	AAAA	2600:9000:5300:1e00::1
ns-562.awsdns-06.net.	157095	IN	A	205.251.194.50
ns-562.awsdns-06.net.	157008	IN	AAAA	2600:9000:5302:3200::1
ns-1525.awsdns-62.org.	44922	IN	A	205.251.197.245

;; Query time: 351 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Sat Oct 31 00:11:47 IST 2020
;; MSG SIZE  rcvd: 344
```
Here the company is using route53 to host their dns records. The ns in the AUTHORITY section can be resolved on their own and we don't really need glue records. Here we can safely remove ADDITIONAL and AUTHORITY records albeit it can come at a performance penalty as we would require to query the dns servers again to resolve any nameservers.

**Comment by bharath-123** [comment]
gentle ping @miekg @chrisohaver Would love to know your views on my findings on the bind tests. I can begin work on the plugin once you all think that the tests can be ported.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add *minimal*..." ]
>So this is part of the additional section of the system tests of bind9. It sets
>up a 3 nameservers locally on the loopback interface and runs the tests using
>them. These are somewhat like unit tests in the sense they test the feature and
>are completely self contained.
>
>@miekg @chrisohaver Do you think we can port these tests into coredns and
>implement the plugin based on these tests?

We are in a much better shape, you can just call ServeDNS and see the reply, look at other
plugins for inspiration.

**Comment by bharath-123** [comment]
Thanks @miekg ! Needed some guidance here to understand the route to take. I ll start working on the design and raise a PR with the README.md! Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add *minimal*..." ]
>These tests seem interesting https://github.com/isc-projects/bind9/blob/
>e64e3322a64a35ef246f83526e25bdf17099ec48/bin/tests/system/additional/tests.sh

that looks barely usable :-( We'll just invent our own then.

>to remove the AUTHORITY and ADDITIONAL records in the dns response but we need
>to mindful to check whether the ADDITIONAL records contain any glue records
>which are necessary for dns resolution.

yes, any `response.Delegation` messages should be left alone by this plugin.

/Miek

--
Miek Gieben

**Comment by gdsoumya** [comment]
I would like to take up this issue if it is not being worked on, @miekg. I have been looking into how to create custom plugins for CoreDNS and I would like to try solve this issue. Though I don't have too much context about when the authoritative and additional sections are required(and when not), I did some initial research but couldn't come up with anything substantial. Any resources on this would be really helpful.

I found this resource on [wikipedia](https://en.wikipedia.org/wiki/Domain_Name_System#Circular_dependencies_and_glue_records), is this the only case when they are needed?

**Comment by gdsoumya** [comment]
> yes, any `response.Delegation` messages should be left alone by this plugin.

So to my understanding, this is the only case where the authority and additional sections are to be preserved and in other cases it can be removed. Is that correct?

**EDIT**: I think the authority and additional sections will remain in all cases except those which are of type `response.NoError` as glue records are required in both delegation and negative responses. Do correct me if i am wrong.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] add *minimal*..." ]
>    yes, any response.Delegation messages should be left alone by this plugin.
>
>So to my understanding, this is the only case where the authority and
>additional sections are to be preserved and in other cases it can be removed.
>Is that correct?

mostly yes. I'll try to write down some more details, those should be in the README.md
anyway. But it boils down to removing any info that not directly needed by the client.

It seems indeed this effort stalled, so feel free to pick it up.

/Miek

--
Miek Gieben

**Comment by gdsoumya** [comment]
Thanks I have already created the basic plugin just finishing up with the readme, will send a PR in a few hours. I will do the necessary changes or enhancements after the review.
