### ISSUE TITLE
Support DNS name for forwarder upstream 

### ISSUE THREAD

**Issue by adammw** [coredns/coredns#4224]
**What would you like to be added**:
Support DNS name for forwarder upstream rather than an explicit IP address

**Why is this needed**:
This makes it easier to configure the forwarder plugin where the upstream IP address is dynamic or not known in advance but resolved over DNS.

An example would be a situation where we want to forward all DNS requests for a certain zone to a Kubernetes service, it would be ideal to allow a configuration such as:
```
myservice.internal {
  forward . resolver.myservice.svc.cluster.local
} 

cluster.local {
  kubernetes
}
```

The idea is that CoreDNS would receive a foo.myservice.internal query, it would first attempt to resolve the upstream internally and then use that as the forward proxy configuration, and cache the results for the duration of the TTL.

**Comment by miekg** [comment]
discussed before https://github.com/coredns/coredns/issues/2864

/label duplicate
/close
