### ISSUE TITLE
Be able to forward specific cnames.

### ISSUE THREAD

**Issue by sch1ldkr0ete** [coredns/coredns#4227]
**What would you like to be added**:
It would be nice to have the possibility to be able to forward just specific cnames.

**Why is this needed**:
For some records we want to forward specific cnames.

**Comment by miekg** [comment]
you can maybe use multiple server blocks
~~~
name1 {
   forward . @<IP>
}
name 2 {
   forward . @<IP>
}
~~~
if that doesn't fit your needs, it can't be done.

**Comment by chrisohaver** [comment]
Depends on what you want to do.  The question doesnt make that clear.

You you can use the _template_ plugin to create CNAMEs that eclipse names in the _file_ plugin's zonefile.  Unclear if thats what you want to do.
