### ISSUE TITLE
can not build coredns image

### ISSUE THREAD

**Issue by Shawn71** [coredns/coredns#4228]
**What happened**:
there is error output below when I try to build coreDNS image by myself
ADD failed: stat /var/lib/docker/tmp/docker-builder076953404/coredns: no such file or directory
**What you expected to happen**:
build the coredns image successfully 
**How to reproduce it (as minimally and precisely as possible)**:
1.git clone https://github.com/coredns/coredns
2.cd coredns
3.docker build -t coredns:v1.2 ./
**Anything else we need to know?**:
[root@centos7 coredns]# docker build -t coredns:v1.2 ./
Sending build context to Docker daemon  3.072kB
Step 1/8 : FROM debian
 ---> 1510e8501783
Step 2/8 : RUN apt-get update && apt-get -uy upgrade
 ---> Using cache
 ---> fdebc3caa6a9
Step 3/8 : RUN apt-get -y install ca-certificates && update-ca-certificates
 ---> Using cache
 ---> aa9a26dff3a3
Step 4/8 : FROM scratch
 ---> 
Step 5/8 : COPY --from=0 /etc/ssl/certs /etc/ssl/certs
 ---> Using cache
 ---> 7b2aa8ba4b83
Step 6/8 : ADD coredns /coredns
ADD failed: stat /var/lib/docker/tmp/docker-builder069028715/coredns: no such file or directory
[root@centos7 coredns]# 

**Environment**:CentOS7
- the version of CoreDNS: 1.6.6 & latest
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
Before `docker build`, you'll need to `go build` coredns with appropriate target arch/os to produce a binary named "coredns".

**Comment by Shawn71** [comment]
got that ,thanks for the answer , is there some version requirement for set up Go environment .

**Comment by Shawn71** [comment]
when I try to go build coredns, It always got below error . really appreciated for you help .

github.com/coredns/coredns/plugin/k8s_external
k8s.io/api/core/v1
go build k8s.io/api/core/v1: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
github.com/coredns/coredns/plugin/metadata
github.com/coredns/coredns/plugin/loadbalance
github.com/coredns/coredns/plugin/pkg/replacer
github.com/coredns/coredns/plugin/log
github.com/coredns/coredns/plugin/loop
github.com/coredns/coredns/plugin/nsid
github.com/coredns/coredns/plugin/pprof
github.com/coredns/coredns/plugin/ready
github.com/coredns/coredns/plugin/reload
github.com/coredns/coredns/plugin/rewrite
github.com/coredns/coredns/plugin/root
github.com/coredns/coredns/plugin/route53
github.com/coredns/coredns/plugin/secondary
github.com/coredns/coredns/plugin/sign
github.com/coredns/coredns/plugin/template
github.com/coredns/coredns/plugin/tls
github.com/coredns/coredns/plugin/trace
github.com/coredns/coredns/plugin/whoami
make: *** [coredns] Error 1
[root@iZj6c68wjiec936146w9oaZ coredns]# pwd
/usr/local/go/src/github/coredns
[root@iZj6c68wjiec936146w9oaZ coredns]# go version
go version go1.15.2 linux/amd64

**Comment by chrisohaver** [comment]
pwd should be `/usr/local/go/src/github.com/coredns/coredns`

**Comment by chrisohaver** [comment]
Correction: pwd should be `$GOPATH/src/github.com/coredns/coredns` and $GOPATH is not typically `/usr/local`, it usually sits in your home directory.

**Comment by chrisohaver** [comment]
You could try compiling in a docker image, if you don't want to mess with getting your local go env set up : https://github.com/coredns/coredns#compilation-with-docker

**Comment by Shawn71** [comment]
thanks for you feedback, it still get the error below:

gopkg.in/DataDog/dd-trace-go.v1/internal
gopkg.in/DataDog/dd-trace-go.v1/internal/globalconfig
gopkg.in/DataDog/dd-trace-go.v1/internal/version
gopkg.in/DataDog/dd-trace-go.v1/internal/log
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer
github.com/coredns/coredns/plugin/trace
github.com/coredns/coredns/plugin/whoami
make: *** [Makefile:16: coredns] Error 2
[root@iZj6c68wjiec936146w9oaZ coredns]# docker run --rm -i -t -v $PWD:/v -w /v golang:1.15.2 make^C

**Comment by zouyee** [comment]
**latest version did not reproduce the issue.**
```
[root@xxx coredns]# docker run --rm -i -t -v $PWD:/v -w /v golang:1.14 make
go generate coredns.go
go: github.com/Azure/azure-sdk-for-go@v40.6.0+incompatible: Get "https://proxy.golang.org/github.com/%21azure/azure-sdk-for-go/@v/v40.6.0+incompatible.mod": dial tcp 172.217.27.145:443: i/o timeout
make: *** [Makefile:70: core/plugin/zplugin.go] Error 1
[root@xxx coredns]# docker run --rm -i -t -v $PWD:/v -w /v -e GOPROXY=https://goproxy.cn golang:1.14 make
...
[root@xxx coredns]# file coredns
coredns: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

**Comment by Shawn71** [comment]
thanks for the feedback .Sorry , i did not get it. Could you please give more explanation of the "latest version did not reproduce the issue."

I just tried  the command " docker run --rm -i -t -v $PWD:/v -w /v -e GOPROXY=https://goproxy.cn golang:1.14 make" , still get the error below :
github.com/coredns/coredns/plugin/whoami
make: *** [Makefile:16: coredns] Error 2

[root@iZj6c68wjiec936146w9oaZ coredns]# pwd
/root/go/src/github.com/coredns/coredns
[root@iZj6c68wjiec936146w9oaZ coredns]#

**Comment by Shawn71** [comment]
thank you all for the help, finally, it works. now I think I built the CoreDNS image successfully .but it is still can not enter into the container/pod once we running it with that specific self-build CoreDNS image,

Below is my Dockerfile:

FROM debian

RUN apt-get update && apt-get -uy upgrade
RUN apt-get -y install ca-certificates && update-ca-certificates

FROM scratch

COPY --from=0 /etc/ssl/certs /etc/ssl/certs
ADD coredns /coredns

EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]

[root@centos7 coredns]# docker build -t coredns:1.6.8 ./
Sending build context to Docker daemon  45.53MB
Step 1/8 : FROM debian
 ---> 1510e8501783
Step 2/8 : RUN apt-get update && apt-get -uy upgrade
 ---> Using cache
 ---> fdebc3caa6a9
Step 3/8 : RUN apt-get -y install ca-certificates && update-ca-certificates
 ---> Using cache
 ---> aa9a26dff3a3
Step 4/8 : FROM scratch
 ---> 
Step 5/8 : COPY --from=0 /etc/ssl/certs /etc/ssl/certs
 ---> Using cache
 ---> 7b2aa8ba4b83
Step 6/8 : ADD coredns /coredns
 ---> f4fda465bce1
Step 7/8 : EXPOSE 53 53/udp
 ---> Running in 21bf7ffab9b2
Removing intermediate container 21bf7ffab9b2
 ---> cdadea7f4a93
Step 8/8 : ENTRYPOINT ["/coredns"]
 ---> Running in 62b2f5781717
Removing intermediate container 62b2f5781717
 ---> 99acdd04145b
Successfully built 99acdd04145b
Successfully tagged coredns:1.6.8

[root@centos7 coredns]# docker run -it --rm --name=test coredns:1.6.8 /bin/sh
2020/10/24 02:02:53 extra command line arguments: [/bin/sh]

Meanwhile ,I am going to other terminal and try to enter this container  ,still get the error :

[root@centos7 ~]# docker exec -it test /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown

**Comment by Shawn71** [comment]
is there some way to enable the feature of EphemeralContainer ? thanks

**Comment by miekg** [comment]
topic is nothing todo w/ coredns anymore, closing
