### ISSUE TITLE
is there any chance or way that we can enter into the CoreDNS pod for troubleshooting

### ISSUE THREAD

**Issue by Shawn71** [coredns/coredns#4229]
**What would you like to be added**:
enter into the coreDNS pod
**Why is this needed**:
for troubleshooting some DNS resolution issues .

**Comment by chrisohaver** [comment]
The coredns images in dockerhub, and in k8s repos do not allow a shell session.  You should be able to troubleshoot by sending queries from another pod. https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by Shawn71** [comment]
Thank you for the feedback, is there anyway to enter into coreDNS pod to install tcpdump and doing traffic capture for analysis? such as build coreDNS image by myself via using Dockerfile .

**Comment by chrisohaver** [comment]
Yes, you can modify the Dockerfile to use a base image that supports a shell.

Although, you should be able to tcpdump traffic from the host (the worker node hosting the Pod).

**Comment by ShawnBian** [comment]
Thank you for the answer, do you know why always got below error when try to "make" the coreDNS? thanks 
go build k8s.io/api/core/v1: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
github.com/coredns/coredns/plugin/metadata
github.com/coredns/coredns/plugin/loadbalance
github.com/coredns/coredns/plugin/pkg/replacer
github.com/coredns/coredns/plugin/log
github.com/coredns/coredns/plugin/loop
github.com/coredns/coredns/plugin/nsid
github.com/coredns/coredns/plugin/pprof
github.com/coredns/coredns/plugin/ready
github.com/coredns/coredns/plugin/reload
github.com/coredns/coredns/plugin/rewrite
github.com/coredns/coredns/plugin/root
github.com/coredns/coredns/plugin/route53
github.com/coredns/coredns/plugin/secondary
github.com/coredns/coredns/plugin/sign
github.com/coredns/coredns/plugin/template
github.com/coredns/coredns/plugin/tls
github.com/coredns/coredns/plugin/trace
github.com/coredns/coredns/plugin/whoami
make: *** [coredns] Error 1

GO Version:

[root@iZj6c68wjiec936146w9oaZ coredns]# go version
go version go1.15.2 linux/amd64

**Comment by zouyee** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/

**Comment by Shawn71** [comment]
thank you all for the help, it seems there is no command regarding how to enable ephemeral-container from the cluster. do you know how to enable that feature?  really grateful for your help.

**Comment by chrisohaver** [comment]
>  is there anyway to enter into coreDNS pod to install tcpdump and **doing traffic capture for analysis**?

You should be able to tcpdump traffic from the host (the worker node hosting the Pod). I.e. you dont need to enter the CoreDNS container, you can monitor the traffic from the other side. Many tutorials out there, e.g. https://community.pivotal.io/s/article/How-to-get-tcpdump-for-containers-inside-Kubernetes-pods?language=en_US

**Comment by Shawn71** [comment]
thank you, I think I have already built the image and running on the  Kubernetes cluster, but it is still failed to running some cloud platform .so still need to investigate. I will close this issue. thanks
