### ISSUE TITLE
plugin/health: HealthDuration measure wrong endpoint

### ISSUE THREAD

**Issue by sergelogvinov** [coredns/coredns#4230]
**What happened**:

HealthDuration goes to http://h.Addr/ to measure response time

**What you expected to happen**:

Probably we need to use http://h.Addr/health endpoint
https://github.com/coredns/coredns/blob/3168a722cac244c91fc56e3a4d1d3d7fd48f0dd2/plugin/health/overloaded.go#L42 

**How to reproduce it (as minimally and precisely as possible)**:
```
sudo tcpdump -A -n -i lo0 port 8091  | grep GET

GET / HTTP/1.1
```

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.0
- Corefile:
```
.:53 {
    errors

    health 127.0.0.1:8091 {
        lameduck 5s
    }
}
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): MacOS
- Others: darwin/amd64, go1.14.2

**Comment by miekg** [comment]
closed via #4231
