### ISSUE TITLE
plugin/dnstap: slow test 

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4238]
The dnstapio tests a very slow:
~~~
% go t
2020/10/26 09:04:09 [WARNING] plugin/dnstap: Connection lost: write tcp 127.0.0.1:39918->127.0.0.1:41155: write: broken pipe
2020/10/26 09:04:09 [INFO] plugin/dnstap: Reconnected to dnstap
PASS
ok  	github.com/coredns/coredns/plugin/dnstap/dnstapio	9.046s
~~~
This needs to be sped up (< 1s). 

Also the `d.queue` uses a buffered channel (10,000 elements), no rational is given, so this should be made blocking. Further more for TCP we fiddle with nagle and set a (random sized) write buffer  - again without any rational. These need to be removed and/or given proper rational from the dnstap project.
*And* `d.socket` seem superfluous and can be removed.

**Comment by miekg** [comment]
the buffered channel and the internal buffer used gives the impression this code can't block; TL:DR; it can block. I've got a WIP PR
that removes another 246 lines of code, but currently failing over the concurrency issues this uncovered.

**Comment by miekg** [comment]
this has useful bits: https://github.com/coredns/coredns/pull/4240
but trying it with coredns, yields problems:
~~~
oreDNS-1.8.0
linux/amd64, go1.15.3, 
[ERROR] plugin/dnstap: Failed to flush dnstap: no connection
[INFO] plugin/dnstap: Reconnected to dnstap
^C[INFO] SIGINT: Shutting down
~~~
coredns now hangs

~~~
dnstap: opened input socket /tmp/dnstap.sock
dnstap.NewFrameStreamInput() failed: decoding error
dnstap.NewFrameStreamInput() failed: decoding error
~~~
on the dnstap side.

**Comment by rdrozhdzh** [comment]
Hi @miekg, please review #1280 again before doing your changes.

Also, just for reference, see the recent perf problem which unbound team faced recently - 
https://github.com/NLnetLabs/unbound/issues/305

I hope, the dnstap plugin will not experience similar problems

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/dnstap..." ]
>Hi @miekg, please review #1280 again before doing your changes.
>
>Also, just for reference, see the recent perf problem which unbound team faced
>recently -
>NLnetLabs/unbound#305
>
>I hope, the dnstap plugin will not experience similar problems

this just kicks the can forward. The used constants are pulled out of thin air.

Buffered channels in general are bad, as problems are only hit in production. The redoing of
dnstap with an internal buffer (1024x1024, why?) also needs backing up. I don't think I
see a use for `dnstap_encoder.go` and once gone the test also doesn't take 9s. The channel
(once unbuffered), might be good to keep though, just so we can drop the messages (easier).

**Comment by rdrozhdzh** [comment]
I don't mind improving the plugin by changing the numbers (to other magic numbers) or removing all buffering and queuing at all. As long as it doesn't break functionality and doesn't worsen performance.

In my previous message I meant to say that the change should be done with care.

**Comment by miekg** [comment]
this has been fixed; tests don't take 39s anymore
