### ISSUE TITLE
Docker configuration?

### ISSUE THREAD

**Issue by oester** [coredns/coredns#4249]
I looked over https://coredns.io/manual/toc/ and couldn't find any specific documentation on how to deploy using docker using straight docker commands or docker-compose. Does this exist?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Docker configurat..." ]
>I looked over https://coredns.io/manual/toc/ and couldn't find any specific
>documentation on how to deploy using docker using straight docker commands or
>docker-compose. Does this exist?


that doesn't exist, we publish a docker container with the coredns binary, how use docker
is off-topic for this repo.

/close
