### ISSUE TITLE
ServerBlock without bind plugin is inactive if other block has bind defined

### ISSUE THREAD

**Issue by nanorobocop** [coredns/coredns#4270]
**What happened**:

If there're ServerBlocks with and without bind plugin - ServerBlocks without bind plugin seems always inactive.

**What you expected to happen**:

As [bind](https://coredns.io/plugins/bind/) plugin describes, ServerBlock without bind plugin should serve all interfaces.

Or have a warning about unused ServerBlock from config.

**How to reproduce it (as minimally and precisely as possible)**:

1. Config with both bind defined - ORG ServerBlock works fine:

```
org:1053 {
    bind 127.0.0.1
    log . "{remote}:{port} - {name} - ZONEORG!"
}
.:1053 {
    bind 127.0.0.1
    log . "{remote}:{port} - {name} - ZONEALL!"
}
```

Result - OK: 
```
[INFO] 127.0.0.1:64459 - example.org. - ZONEORG!
```

2. But if config with and without bind - ORG ServerBlock is inactive:
```
org:1053 {
    log . "{remote}:{port} - {name} - ZONEORG!"
}
.:1053 {
    bind 127.0.0.1
    log . "{remote}:{port} - {name} - ZONEALL!"
}
```

Result - PROBLEM:
```
[INFO] 127.0.0.1:58720 - example.org. - ZONEALL!
```

**Anything else we need to know?**: No

**Environment**:

- the version of CoreDNS: Tested on 1.3.1 and current master branch.
- Corefile: as above
- logs, if applicable: as above
- OS (e.g: `cat /etc/os-release`): CentOS 7.8, MacOS 10.14
- Others: No

**Comment by miekg** [comment]
`[INFO] 127.0.0.1:58720 - example.org. - ZONEALL!`

but only `.` is bound to localhost and you're querying localhost (although you have omitted this from your report)

**Comment by miekg** [comment]
hmm, agree this is not very straight forward behavior

**Comment by miekg** [comment]
So I think this is WAI and maybe the docs should be tweaks. You get two internal servers, one on 127... and the other for all interfaces. Due the re-useport you don't get an binding error when the second servers opens a listening port, but it can't see the query because the first server get it.

**Comment by nanorobocop** [comment]
Do you mean block without bind works only for interfaces not mentioned in bind?

I also tested with other interfaces. At response becomes different.

Config:
```
org:1053 {
    log . "{remote}:{port} - {name} - ZONEORG!"
}
.:1053 {
    bind 127.0.0.1
    log . "{remote}:{port} - {name} - ZONEALL!"
}
```

I made 3 queries:
```
dig example.org @192.168.11.3 -p 1053
dig example.org @127.0.0.1 -p 1053
dig example.org @192.168.11.3 -p 1053
```

And results for 1st and 3rd queries are different:
```
[INFO] 192.168.11.3:50856 - example.org. - ZONEORG!
[INFO] 127.0.0.1:55613 - example.org. - ZONEALL!
[INFO] 192.168.11.3:51561 - example.org. - ZONEALL!
```

**Comment by chrisohaver** [comment]
> And results for 1st and 3rd queries are different:
>
>```
>[INFO] 192.168.11.3:50856 - example.org. - ZONEORG!
>[INFO] 127.0.0.1:55613 - example.org. - ZONEALL!
>[INFO] 192.168.11.3:51561 - example.org. - ZONEALL!
>```

That definitely looks like a bug. It seems that inconsistent bind inclusion causes server instances to listen to the same port.  I'll try to replicate it and see whats going on.

**Comment by chrisohaver** [comment]
Ah - i see. https://github.com/coredns/coredns/issues/4270#issuecomment-723980366

I don't think it's easily fixable.  In theory we could implicitly bind servers that dont have a bind specified to all interfaces that are not yet bound to the port.

This reminds me of a previous issue requesting that we allow a kind of "bind except" ... https://github.com/coredns/coredns/issues/4219.

Perhaps instead we should protect/warn against this configuration (require all servers or none have bind)? ... I don't think having two server listen to the same port would ever be intentional or desired.
