### ISSUE TITLE
Segfault with cache running again itself

### ISSUE THREAD

**Issue by owengo** [coredns/coredns#4271]
**What happened**:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb1f392]

goroutine 7095 [running]:
github.com/coredns/coredns/plugin/cache.(*ResponseWriter).LocalAddr(0xc000c81200, 0xc0, 0xc0)
        <autogenerated>:1 +0x32
github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS.func1(0x1, 0xc001000f30, 0xc0018fb4d0, 0xc00007f200, 0xc000e177e5, 0x9, 0x2077de0, 0xc0017b85c0, 0x2064f20, 0xc001333740)
        /tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/cache/handler.go:56 +0x4b
created by github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS
        /tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/cache/handler.go:52 +0x694

```

**What you expected to happen**:

no segfault

**How to reproduce it (as minimally and precisely as possible)**:

I think the cause is the mix of rewrite + cache. I had the issue with 1.7.0 eksbuild.1 and 1.8.0 from dockerhub.
The configuration is  quite big but here are the relevant parts:
```

apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite continue {
            name  regex (.*)\.(list-of-private-suffixes|amazonaws.com)\.cluster\.local {1}.{2}
            answer name (.*)\.(list-of-private-suffixes|amazonaws.com) {1}.{2}.cluster.local
        }
        rewrite stop {
            type AAAA A
        }
        kubernetes cluster.local {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache {
          prefetch 1
          success 1000 900
          denial 1000 60 30
          prefetch 1
          serve_stale
        }
        reload
        log
        loadbalance
        file /etc/node-local-zones/private-zone-file private-tld {
          reload 10s
        }
...

```

**Anything else we need to know?**:

Here the last lines of log before the crash:

```
[INFO] 172.16.xx.yy:34208 - 1390 "A IN xx-yy-zzz-37162fb9d97eed54.elb.eu-west-1.amazonaws.com. tcp 87 false 65535" NOERROR qr,aa,rd,ra 272 0.000019781s
[INFO] 172.16.xx.zz:53 - 31589 "A IN xx-yy-zzz-37162fb9d97eed54.elb.eu-west-1.amazonaws.com. tcp 87 true 65535" NOERROR qr,aa,rd,ra 272 0.000022215s
panic: runtime error: invalid memory address or nil pointer dereference

```

notice the [INFO] 172.16.xx.zz:53 - , which is very likely to be corrupt because it is the ip address of the container running coredns the listening port, so not a client
So maybe this is when the go routine tried to cache this corrupted answer that things went really bad.

Crashes also occur without the log activated.

**Environment**:

- the version of CoreDNS:  image: coredns/coredns:1.8.0
- Corefile: 

```
    .:53 {
        errors
        health
        rewrite continue {
            name  regex (.*)\.(list-of-private-suffixes|amazonaws.com)\.cluster\.local {1}.{2}
            answer name (.*)\.(list-of-private-suffixes|amazonaws.com) {1}.{2}.cluster.local
        }
        rewrite stop {
            type AAAA A
        }
        kubernetes cluster.local {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache {
          prefetch 1
          success 1000 900
          denial 1000 60 30
          prefetch 1
          serve_stale
        }
        reload
        log
        loadbalance
        file /etc/node-local-zones/private-zone-file private-tld {
          reload 10s
        }
```

- logs, if applicable:

```
[INFO] 172.16.xx.yy:34208 - 1390 "A IN xx-yy-zzz-37162fb9d97eed54.elb.eu-west-1.amazonaws.com. tcp 87 false 65535" NOERROR qr,aa,rd,ra 272 0.000019781s
[INFO] 172.16.xx.zz:53 - 31589 "A IN xx-yy-zzz-37162fb9d97eed54.elb.eu-west-1.amazonaws.com. tcp 87 true 65535" NOERROR qr,aa,rd,ra 272 0.000022215s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb1f392]

goroutine 7095 [running]:
github.com/coredns/coredns/plugin/cache.(*ResponseWriter).LocalAddr(0xc000c81200, 0xc0, 0xc0)
        <autogenerated>:1 +0x32
github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS.func1(0x1, 0xc001000f30, 0xc0018fb4d0, 0xc00007f200, 0xc000e177e5, 0x9, 0x2077de0, 0xc0017b85c0, 0x2064f20, 0xc001333740)
        /tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/cache/handler.go:56 +0x4b
created by github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS
        /tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/cache/handler.go:52 +0x694

```
- OS (e.g: `cat /etc/os-release`): coredns container in eks1.17 environment
- Others: issue occured with 1.7.0 build (provided by aws/eks ) and with 1.8.0 build.

**Comment by miekg** [comment]
hmm, yeah the `w.LocalAddr()` happens in the go-routine. Notice though that `state` holds a `responseWriter` as well. I think it's not used to write so that would be less of an issue, but be aware off.
Looking at that line (#56) I wonder why `prefetch: true` is there...

**Comment by owengo** [comment]
@miekg  this is not prefetch: true, according to the documentation:

`prefetch AMOUNT [[DURATION] [PERCENTAGE%]]`

_prefetch 1_ means ( if I understand well ) to prefetch records requested at least once in the last minute when 10% of their TTL is remaining

I agree the configuration is done twice, there is no justification for it. You think it might cause the go routing to be launched twice concurrently ?

**Comment by owengo** [comment]
Ok the problem seems to be caused by the double " prefetch 1" configuration, I do not reproduce the issue after fixing the typo.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Segfault with..." ]
>Ok the problem seems to be caused by the double " prefetch 1" configuration, I
>do not reproduce the issue after fixing the typo.

huh? that would still be a bug...

**Comment by owengo** [comment]
The bug is caused by a misconfiguration so I do not know what is your policy about this. Fixing the configuration fixes the issue. The "bug" would be to allow multiple "prefetch" directives in a cache block ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Segfault with..." ]
>The bug is caused by a misconfiguration so I do not know what is your policy
>about this. Fixing the configuration fixes the issue. The "bug" would be to
>allow multiple "prefetch" directives in a cache block ?

that can't actually be the bug, the `prefetch` values are just overwritten, the *cache* is
then created with the last value of `prefetch` seen.

**Comment by owengo** [comment]
ok I will try to get a better report
