### ISSUE TITLE
SRV Record Target names not rewritten by Rewrite Plugin

### ISSUE THREAD

**Issue by slick-nic** [coredns/coredns#4284]
**What happened**:
We use Kubernetes/Calico CNI with headless services and the coredns rewrite plugin to allow us to resolve addresses outside of the cluster.

This works fine for A records, but SRV Target domains in the answers for SRV records are not rewritten.

The A records in the Additional section of the SRV lookup response are also not rewritten.

See attached file for A + SRV dig lookup examples.
[Dig Output.txt](https://github.com/coredns/coredns/files/5525815/Dig.Output.txt)

**What you expected to happen**:
I expect rewrite to work for SRV Target.
Looking at the code, this probably also applies to other record types that return a domain name in the answer e.g. MX

**How to reproduce it (as minimally and precisely as possible)**:
Set up a headless service in kubernetes (with the config required to get headless service SRV records created)
Set up a rewrite from cluster.local to/from another.domain.uk
Resolve the SRV records for the rewritten domain, observe that the response still contains cluster.local

**Anything else we need to know?**:
I have written a unit test and a fix which I think identifies/fixes this issue _for me_, but I'm new to Go, I dont think this is the finished product in terms of a fix more of a starting point to discuss. Comments are welcome. I still have not run it in a K8s cluster to test fully.
[srv_revert.patch.txt](https://github.com/coredns/coredns/files/5525823/srv_revert.patch.txt)

**Environment**:
Kubernetes 1.19 / Calico CNI / CRI-O on Ubuntu Server 20.04
Core DNS 1.7.0 from k8s.gcr.io/coredns:1.7.0
YAML to update corefile in Kubernetes is attached.
[CoreFileUpdate.yaml.txt](https://github.com/coredns/coredns/files/5525811/CoreFileUpdate.yaml.txt)

Apologies for yaml / patch files as .txt - github doesnt accept patch or yaml files.

**Comment by chrisohaver** [comment]
FWIW, This has been discussed before in https://github.com/coredns/coredns/issues/2770. I knew it seemed familiar, but took me a while to find it.

**Comment by chrisohaver** [comment]
Does the current behavior cause a practical problem for SRV responses?
Currently neither the target or the addtl section are rewritten, so they match up.
If a client decides to ignore the additonal section records, and query the target names, they'd get the proper responses.

i.e.  is this fixing something that doesn't work now, or is it cosmetic in nature.

**Comment by slick-nic** [comment]
> Does the current behavior cause a practical problem for SRV responses?
> Currently neither the target or the addtl section are rewritten, so they match up.

Ok so the SRV Target not being rewritten causes a problem for me as the end client (behind another DNS server doing forwarding to coredns for a single domain) cannot resolve the "cluster.local" domain.
The changes for rewriting the additional section are just for consistency / cosmetic reasons but they will prevent the additional lookups in my case (I added them after testing the change).
I think your suggestion in the PR comments is probably the way to go; basically rewrite all record types returning names rather than just SRV then responses will always be consistant and always make sense.
The reason I didnt do this right away was simply trying to limit the scope / impact of the change.
IMHO it makes sense to have the whole response be consistent, rather than mixing two different domains that really mean the same thing.

**Comment by chrisohaver** [comment]
> ... the end client (behind another DNS server doing forwarding to coredns for a single domain) cannot resolve the "cluster.local" domain.

OK - makes sense, I hadn't thought of the forwarder-in-the-middle case.

**Comment by slick-nic** [comment]
Closing this issue as the related pull request has now been merged.
