### ISSUE TITLE
Non-existent CNAME target in the same zone should be returned with NXDOMAIN instead of NOERROR rcode

### ISSUE THREAD

**Issue by SivaKesava1** [coredns/coredns#4288]
Hi,

This is related to if 'A CNAME B' exists in a zone, but B (related to the same zone) does not exist, then the return code should be NXDOMAIN.  [RFC 6604](https://tools.ietf.org/html/rfc6604#section-3) mentions that 
> When chains are followed the RCODE in the ultimate DNS response MUST BE set based on the final query cycle leading to that
>       response.

Consider the following sample zone file

|  	|  	|  	|  	|
|-	|-	|-	|-	|
| example.com. 	| 500 | SOA 	| ns1.outside.com. root.example.com. 3 604800 86400 2419200 604800 	|
| example.com. 	| 500 | NS 	| ns1.outside.com.  	|
| b.c.example.com. 	| 500 | CNAME | c.c.example.com.  	|
| c.c.example.com. 	| 500 | CNAME	| d.c.example.com.  	|

For the query _<b.c.example.com. , A>_, the Coredns server returns the following response:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA",
          ";QUESTION",
          "b.c.campus.edu. IN A",
          ";ANSWER",
          "b.c.example.com. 500 IN CNAME c.c.example.com.",
          "c.c.example.com. 500 IN CNAME d.c.example.com.",
          ";AUTHORITY",
          "example.com. 500 IN NS ns1.outside.com.",
          ";ADDITIONAL"
```

**What you expected to happen**:
The expected response is the same as above except that the `rcode` should be `NXDOMAIN`. 

**Environment**:

- the version of CoreDNS: `CoreDNS-1.8.0  linux/amd64, go1.15.3, 054c9ae`
- Corefile:
```
example.com:53 {
    file db.example.com
    log
    errors
}
```
- OS: Ubuntu 18

**Comment by SivaKesava1** [comment]
There is a small twist here. The response is `NXDOMAIN` if the `CNAME` target does not exist and is `NOERROR` if the query type is `CNAME.` 
CoreDNS responds properly for the above cases except for the subtle case where the `CNAME` is a synthesized one. This is a minor issue but putting it down for future reference. 

Consider these cases, 
|  	|  	|  	|  	|
|-	|-	|-	|-	|
| foo.example.com. 	| 500 | CNAME | bar.example.com.  	|
| *.code.example.com. 	| 500 | CNAME	| test.example.com.  	|

For queries   _<foo.example.com. , A>_, and _<a.code.example.com. , A>_ CoreDNS responds with the corresponding `CNAME` record and with `NXDOMAIN`. Similarly for  _<foo.example.com. , CNAME>_, it responds with the `CNAME` record and with `NOERROR` code. This is the expected behavior and is followed by other implementations too. 

The issue is with the query  _<a.code.example.com. , CNAME>_. It correctly synthesizes the `CNAME` record but responds with  `NXDOMAIN`  which should be similar to the above case and should have been `NOERROR`. 

An even more subtle case is the one involving DNAMEs, you can look at them here:
https://github.com/NLnetLabs/nsd/issues/140
https://gitlab.isc.org/isc-projects/bind9/-/issues/2284
https://github.com/PowerDNS/pdns/issues/9725

**Comment by chrisohaver** [comment]
> The issue is with the query <a.code.example.com. , CNAME>. It correctly synthesizes the CNAME record but responds with NXDOMAIN which should be similar to the above case and should have been NOERROR.

That seems like an independent issue regarding how CNAME type queries of wildcard CNAMEs are handled, not an extension of this one.

**Comment by SivaKesava1** [comment]
Okay, I can file a new issue. Thanks
