### ISSUE TITLE
dns query loop should be detected and constrained during runtime

### ISSUE THREAD

**Issue by zq-david-wang** [coredns/coredns#4289]
**What happened**:
I have a k8s cluster with coredns deployed as deployment with 3 replica, and  purposely made a mistake by adding cluster dns service ip to /etc/resolv.conf to make some test.
This error configuration create a loop, but  could not be detected by loop plugin if  loop plugin finished its testing before the pod was put into serving endpoints.

**What you expected to happen**:
When a query causes a loop,  coredns should function normally

**How to reproduce it (as minimally and precisely as possible)**:
In k8s cluster
1. add k8s dns service virtual ip to /etc/resolv.conf on a k8s node
2. create core dns service
3. create coredns deployment/deamonset  in a k8s cluster, with readiness probe initalDelaySeconds set to 60
4. after coredns pod ready for use, make several fakeup dns query 

coredns pod would be oom-killed

**Anything else we need to know?**:
https://github.com/coredns/coredns/pull/2647 remove the code logic for loop detection,  could not understand the reasoning behind it.
A loop could be generated by all kinds of mistakes, crashing the serving pod or preventing the pod from running does not seem like a reasonable expected behavior

**Environment**:

- the version of CoreDNS:
CoreDNS-1.6.7
linux/amd64, go1.13.6, da7f65b
- Corefile:
```
:53 {
    errors
    health {
      lameduck 5s
    }
    ready
    kubernetes mylocal 172.17.0.0/16 {
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by miekg** [comment]
>    initalDelaySeconds set to 60

"The plugin will try to send the query for up to 30 seconds. This is done to give CoreDNS
enough time to start up."

https://coredns.io/plugins/loop/

**Comment by zq-david-wang** [comment]
@meikg  yes, I set the delay to 60 on purpose,  just make it easy to pass the initial test.
But the possibility that new loop  generated after coredns start up is still there.

**Comment by miekg** [comment]
closing old issues, this is fixed by not having a loop.
