### ISSUE TITLE
Getting UnkownHostException from SpringBoot Microservice running on top of kubernetes 

### ISSUE THREAD

**Issue by mootezbessifi** [coredns/coredns#4297]
**What happened**:
My application is running on top of kubernetes 1.17.4 with Coredns running as 3 replicas with  version 1.7.1
I am getting sometime (not frequent) an exception from Some microservices (spring-boot `2.0.5.RELEASE` using base image 
`openjdk:8-jre`) trying to request another service through k8s servicie name. telling me `UnknownHostException`..
That means the service which initiating the request is not able to resolve hostname through coredns.
    
**What you expected to happen**:
I am expecting to not see this exception and all calls are DNS resolvable.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
1. I Tried to make a script which run nslookup command 10000 time and i did not get any error and all calls to CoreDNS  were 
resolved successfully.
2. This issue happen like 6 to 10 times a day, means temporary and then get working fine again
**Environment**:

- the version of CoreDNS: 1.7.1
- Corefile: 

>    .:53 {
         errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }

- OS (e.g: `cat /etc/os-release`): ubuntu 16.04

Please any response here will be more than welcome

**Comment by chrisohaver** [comment]
IIUC, java throws UnknownHostException when the name resolution fails for _any_ reason. It could be that (1) it didn't not receive a response from the DNS server at all, or (2) that it got a reply staying that the name does not exist, no record for the name requested, or other error response. 

If the former (1), it's likely that CoreDNS never received the request, or that CoreDNS sent a response but the client never got it. Without more info, I'd guess that this is probably whats happening.

If the latter (2), it could mean that the service requested wasn't ready (e.g. a headless service with no endpoints).

You could try enabling logging on CoreDNS (add `log` to the Corefile) to see if a request was received and response sent during these failures, and if there was a response, what the response code was.

Regarding (1), there is a [known issue](https://github.com/kubernetes/kubernetes/issues/56903) in Kubernetes where packets can be dropped when routing packets to ClusterIP services. [Node Local DNS Cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) helps mitigate this issue, by deploying a DNS cache on each node.

**Comment by mootezbessifi** [comment]
@chrisohaver thank you for yoyur response.
As i mentioned above the UnknownHostException happen randomly and not frequently. Per day there are thousands of request to dns but sometimes it fail for 5,6 requests sometimes not.  so i think (2) does not make sense. 
Also it happen only for specific micro-services (5 out of 80 micro-service).
Also i used to run a for loop to generate 10000 nslookup from one of the services giving that exception and i got all of them fast and success which i think eliminates the possibility of (1).

I have some doubts about the base java image or the sprint boot version  mentioned above, so what do you think ?

**Comment by chrisohaver** [comment]
Without more information I cannot say.  There are many variables that can affect the outcome.  

I recommend deploying node local dns cache to see if it helps.

**Comment by mootezbessifi** [comment]
Could you help me how to do it, means technical steps.

**Comment by mootezbessifi** [comment]
Also could you tell me how to all log to core file to see both request received and response sent ? Many thanks in advance

**Comment by chrisohaver** [comment]
> help me how to do it, means technical steps.

https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

> tell me how to all log to core file

The _log_ plugin logs the name and type requested and the response code sent. Just add `log` to the Corefile. e.g.

```
.:53 {
        log
        errors
...
```

**Comment by cemo** [comment]
Hi @chrisohaver, 

I have exactly same issue https://github.com/coredns/coredns/issues/4357 . The problem is that one of the **CoreDNS** instance is not healthy in the moment of this is happening. 

The errors are happening because the instance is still receiving traffic before health check requests. The scenario is happening like this:

1. Kubernetes checks CoreDNS: OK
2. Applications send DNS requests to suspected CoreDNS server.
3. Randomly CoreDNS can not reply and apps throws UnknownHostException. 
4. Kubernetes checks CoreDNS: Fail
5. Kubernetes cuts traffic for this failing CoreDNS instance.

The strange thing is there is no burst on traffic. We are on AWS EKS and here is the configuration. I have shared numbers related to our issue when this is happening but I don't know why receiving traffic is increasing in that moment. 
https://github.com/coredns/coredns/issues/4357

```
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8080/health delay=0s timeout=1s period=10s #success=1 #failure=3
```

Thanks

**Comment by zouyee** [comment]
Post the result of `kubectl describe pods -n kube-system DNS_POD_NAME`, then try to increase memory/cpu resource.

**Comment by cemo** [comment]
@zouyee I did already. You can see on my previous comment.

What can cause such a sudden peak on cpu usage?

![image](https://user-images.githubusercontent.com/44156/103143576-e79d2980-4729-11eb-9b86-9d0e0c59084d.png)

**Comment by mimmus** [comment]
> @chrisohaver thank you for yoyur response. As i mentioned above the UnknownHostException happen randomly and not frequently. Per day there are thousands of request to dns but sometimes it fail for 5,6 requests sometimes not. so i think (2) does not make sense. Also it happen only for specific micro-services (5 out of 80 micro-service). Also i used to run a for loop to generate 10000 nslookup from one of the services giving that exception and i got all of them fast and success which i think eliminates the possibility of (1).
> 
> I have some doubts about the base java image or the sprint boot version mentioned above, so what do you think ?

I have exactly SAME issues with same symptoms and same "numbers".
Did you find a way to solve it?
