### ISSUE TITLE
Panic during coreDNS runtime

### ISSUE THREAD

**Issue by mnevadaf** [coredns/coredns#4298]
**What happened**:
I was running coredns v1.8.0 within an alpine docker container, and received the below error during runtime:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55bdbece1f4f]
goroutine 116139 [running]:
github.com/miekg/dns.(*Msg).IsEdns0(0xc00074c3f0, 0x0)
	/home/buildozer/go/pkg/mod/github.com/miekg/dns@v1.1.34/defaults.go:153 +0x6f
github.com/coredns/coredns/request.(*Request).Size(0xc000223af0, 0x55bdbff898e0)
	/home/buildozer/aports/testing/coredns/src/coredns-1.8.0/request/request.go:168 +0x45
github.com/coredns/coredns/plugin/forward.(*Proxy).Connect(0xc000272580, 0x55bdc0fd2400, 0xc00064cde0, 0xc00074c3f0, 0x55bdc0fe5080, 0xc000713ec0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/buildozer/aports/testing/coredns/src/coredns-1.8.0/plugin/forward/connect.go:94 +0xcd
github.com/coredns/coredns/plugin/forward.(*Forward).ServeDNS(0xc0004ee480, 0x55bdc0fd2400, 0xc00064cde0, 0x55bdc0fe5080, 0xc000713ec0, 0xc00074c3f0, 0x0, 0x0, 0x0)
	/home/buildozer/aports/testing/coredns/src/coredns-1.8.0/plugin/forward/forward.go:131 +0x530
github.com/coredns/coredns/plugin.NextOrFailure(0x55bdbff8acb3, 0x5, 0x55bdc0f9b340, 0xc0004ee480, 0x55bdc0fd2400, 0xc00064cde0, 0x55bdc0fe5080, 0xc000713ec0, 0xc00074c3f0, 0x0, ...)
	/home/buildozer/aports/testing/coredns/src/coredns-1.8.0/plugin/plugin.go:80 +0xfa
github.com/coredns/coredns/plugin/cache.(*Cache).doPrefetch(0xc000161d40, 0x55bdc0fd2400, 0xc00064cde0, 0xc00074c3f0, 0x55bdc0fe5260, 0xc0004a8680, 0x0, 0x0, 0x200, 0xc0001bfd80, ...)
	/home/buildozer/aports/testing/coredns/src/coredns-1.8.0/plugin/cache/handler.go:73 +0x17e
created by github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS
	/home/buildozer/aports/testing/coredns/src/coredns-1.8.0/plugin/cache/handler.go:64 +0x518
```

I was not able to determine which query (if any, it seems like it might have been triggered during Prefetch) exactly caused this error. 

**What you expected to happen**: I expected coreDNS to not panic during runtime.

**How to reproduce it (as minimally and precisely as possible)**: 

I was not able to reproduce it since encountering this error. I have since enabled logging on the client side to try to determine the exact query (if any) that preceded the issue, if it is seen again.

**Anything else we need to know?**:

The dns client making requests to coredns was Dnsmasq version 2.81. It happens to have the following configured:
`edns-packet-max=512` which could possibly be related.

**Environment**:
```
CoreDNS-1.8.0
linux/amd64, go1.15.3, v20200917-2898-gf99f96739d
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.1
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
config:
```
.:1053 {

    forward . 10.240.3.20 10.240.3.85

    log
    errors

    cache {
         success 10000 3600 1
         denial 2500 3600 1
         prefetch 1 1m 10%
         serve_stale 1h
    }
}
```

**Comment by chrisohaver** [comment]
Looks like it could be caused by a nil RR entry in the Extra slice of the request when processing the OPT record.  A nil entry here is not a valid state, and not sure how it could occur.  Perhaps if the incoming request has a malformed EDNS/OPT record, it can cause us to add a nil RR to the section.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Panic during ..." ]
>Looks like it could be caused by a nil RR entry in the Extra slice of the
>request when processing the OPT record. A nil entry here is not a valid state,
>and not sure how it could occur. Perhaps if the incoming request has a
>malformed ENDS/OPT record, it can cause us add a nil RR to the Section.

there has been more reports like these... We can guard against it, but the while
underlaying dns code should make sure this doesn't happen... Bit mystified at this point.

**Comment by mnevadaf** [comment]
Thanks for checking on it. I haven't seen the issue again, and only saw the one instance of it. I just wanted to make sure you noticed that the client to coredns server is a dnsmasq forwarder with the `edns-packet-max=512` configuration setting. Maybe that could explain a sometimes "malformed" EDNS/OPT record in the request seen by coredns?

**Comment by chrisohaver** [comment]
>  I just wanted to make sure you noticed that the client to coredns server is a dnsmasq forwarder with the edns-packet-max=512 configuration setting. 

Yes I did.  Thats why the request contains an EDNS OPT record. It doesn't explain how/why it would arrive malformed sometimes (if indeed that is what is happening - that was just conjecture).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Panic during ..." ]
>Thanks for checking on it. I haven't seen the issue again, and only saw the one
>instance of it. I just wanted to make sure you noticed that the client to
>coredns server is a dnsmasq forwarder with the edns-packet-max=512
>configuration setting. Maybe that could explain a sometimes "malformed" EDNS/
>OPT record in the request seen by coredns?

This is, I thinking, pointing to a bug somewhere in github.com/miekg/dns, but without
a tcpdump it's hard to tell.

We can put some bandaid in the coredns side, of course, but I rather go for a proper fix.

**Comment by sschepens** [comment]
Hi,
We're experiencing a similar crash but in `msg. IsTsig`:
```
github.com/miekg/dns.(*OPT).Header(0x0, 0x2070ca0)
	/tmp/tmp.yM3x7N1L0w/g/pkg/mod/github.com/miekg/dns@v1.1.34/ztypes.go:223 +0x5

github.com/miekg/dns.(*Msg).IsTsig(0xc00030ac60, 0xc000190400)
	/tmp/tmp.yM3x7N1L0w/g/pkg/mod/github.com/miekg/dns@v1.1.34/defaults.go:138 +0x62

github.com/miekg/dns.(*Conn).WriteMsg(0xc000584690, 0xc00030ac60, 0x39bbf373e8f9b, 0x2c571a0)
	/tmp/tmp.yM3x7N1L0w/g/pkg/mod/github.com/miekg/dns@v1.1.34/client.go:306 +0x32

github.com/coredns/coredns/plugin/forward.(*Proxy).Connect(0xc00015b640, 0x2064f20, 0xc000583140, 0xc00030ac60, 0x2077c00, 0xc000438e40, 0x0, 0x0, 0xffff, 0x0, ...)
	/tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/forward/connect.go:100 +0x165

github.com/coredns/coredns/plugin/forward.(*Forward).ServeDNS(0xc000438480, 0x2064f20, 0xc000583140, 0x2077c00, 0xc000438e40, 0xc00030ac60, 0x0, 0x0, 0x0)
	/tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/forward/forward.go:131 +0x530

github.com/coredns/coredns/plugin.NextOrFailure(0x1d85b3b, 0x5, 0x202de60, 0xc000438480, 0x2064f20, 0xc000583140, 0x2077c00, 0xc000438e40, 0xc00030ac60, 0x0, ...)
	/tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/plugin.go:80 +0xfa

github.com/coredns/coredns/plugin/cache.(*Cache).doPrefetch(0xc00030a000, 0x2064f20, 0xc000583140, 0xc00030ac60, 0x2077d20, 0xc00048c9e0, 0x0, 0x0, 0x200, 0xc0003b2360, ...)
	/tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/cache/handler.go:73 +0x17e

created by github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS
	/tmp/tmp.yM3x7N1L0w/g/src/github.com/coredns/coredns/plugin/cache/handler.go:64 +0x518
```

The malformed DNS query seems kind of strange, since it's all internal stuff.

Is there a way to catch this errors so that coredns does not crash?

**Comment by sschepens** [comment]
We're also experiencing the same `IsEdns0` crash al well

**Comment by rdrozhdzh** [comment]
This may be a race condition. Prefetch is running in a separate goroutine, and the original goroutine after starting prefetch may continue handling dns message, e.g. removing OPT record or some EDNS options. `IsEdns0()` first reads `len(dns.Extra)` and then tries to access element. At this time element may be already removed by original goroutine.
Possible solution - make a deep copy (`func (dns *Msg) Copy() *Msg`) of a DNS query before passing to prefetch gouroutine

**Comment by sschepens** [comment]
@rdrozhdzh this seems like an easy fix, should I attempt a PR?

**Comment by rdrozhdzh** [comment]
this is just my suppose, I'm not sure if I'm right. But you can try and see
