### ISSUE TITLE
middleware/{file,auto} some reloading stuff seems flaky

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#430]
Just wanted to log this upstream already. Will try to look into it further in the coming days.

**Comment by miekg** [comment]
Ack

**Comment by stp-ip** [comment]
Can't pinpoint. Might be something special in my setup. Closing for now.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/{fil..." ]

> Closed #430.

Hmmm, what _did_ you see? I.e. define "flaky"

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
It seemed that it didn't reload the files sometimes, but couldn't pinpoint it further. When I did extensive tests it seemed to work. Will look out for something in the logs, but for now no need to keep it open.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware/{fil..." ]

> It seemed that it didn't reload the files sometimes, but couldn't pinpoint it further. When I did extensive tests it seemed to work. Will look out for something in the logs, but for now no need to keep it open.

I'm starting to believe that fsnotify is inherently racy and the 30 second (or
whatever) walk scan should also check the SOA (or m/c-time of the file) and
then reload. This is somewhat similar to #415, this would mean it is usually
fast, but we have a back that reloads it later anyway.

/Miek

## 

Miek Gieben

**Comment by stp-ip** [comment]
We need to reopen this. This seems to still be an issue.

Either fsnotify is flaky or the auto middleware, but it seems to be a ~5% chance of updates not getting picked up. Nothing specific I could pin down yet.

I used a 30s rescan interval and it still didn't pick up the changes.

No action needed yet, but wanted to keep it logged. I'll do my best to pinpoint the actual issue.

Additional info: k8s + git-sync + coredns + auto middleware

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] middleware/{fil..." ]
>I used a 30s rescan interval and it still didn't pick up the changes.
>
>No action needed yet, but wanted to keep it logged. I'll do my best to pinpoint the actual issue.
>
>Additional info: k8s + git-sync + coredns + auto middleware

Ack. We should kill fsnotify here, clearly it does not work and make the 30s
reload scan more robust by hashing the file's contents (see the ignore_serial
discussion).

**Comment by miekg** [comment]
fsnotify is long gone, we Walk the entire tree here every X seconds. I'm afraid we will need to more debug info for this to be fixed.

**Comment by stp-ip** [comment]
Will try to dive into it more deeply in February, when I have some time.

**Comment by miekg** [comment]
Issue seems stale.

**Comment by stp-ip** [comment]
I could dig into it a bit more again.
"file" works without issues.
"auto" doesn't reload zones after the first reload.
Will check for more details.

**Comment by stp-ip** [comment]
Seems like the culprit is somewhere with "auto".
Some findings:
* Zone creation is recognized during the 60s rescan
* Zone deletion is recognized during the 60s rescan
* Zone update is not recognized at all

Still need to figure out, when zone updates get triggered to give you more data.

**Comment by stp-ip** [comment]
It seems to be working for the first few times in my tests ~5. Afterwards it doesn't recognize any updates anymore.
Additional note: The zone directory is symlinked.

**Comment by miekg** [comment]
> It seems to be working for the first few times in my tests ~5. Afterwards it doesn't recognize any updates anymore.
Additional note: The zone directory is symlinked.

WAT?

If you can simply run CoreDNS from source putting a lot of `printlns` in file/reload.go might shed some more light on this. What changes to the file do you make? 

With a simple test I still have trouble replicating (I'm editing this zone with VI and just change the SOA serial):
~~~
2017/08/31 16:17:20 [INFO] Inserting zone `miek.nl.' from: autotest/db.miek.nl
.:1053
2017/08/31 16:17:20 [INFO] CoreDNS-010
2017/08/31 16:17:20 [INFO] linux/amd64, go1.9, 
CoreDNS-010
linux/amd64, go1.9, 
::1 - [31/Aug/2017:16:17:39 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 124.599µs
::1 - [31/Aug/2017:16:17:42 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 75.745µs
::1 - [31/Aug/2017:16:17:47 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 83.193µs
^[[A::1 - [31/Aug/2017:16:18:32 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 153.783µs
2017/08/31 16:18:42 [INFO] Successfully reloaded zone `miek.nl.'
2017/08/31 16:18:42 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630060
2017/08/31 16:18:42 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630060
2017/08/31 16:18:42 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630060
::1 - [31/Aug/2017:16:18:46 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 119.999µs
::1 - [31/Aug/2017:16:18:51 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 103.745µs
2017/08/31 16:18:57 [ERROR] Failed to open `autotest/db.miek.nl' for `miek.nl.': open autotest/db.miek.nl: no such file or directory
2017/08/31 16:18:57 [INFO] Successfully reloaded zone `miek.nl.'
2017/08/31 16:18:57 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630059
2017/08/31 16:18:57 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630059
::1 - [31/Aug/2017:16:19:06 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 76.882µs
2017/08/31 16:19:15 [ERROR] Failed to open `autotest/db.miek.nl' for `miek.nl.': open autotest/db.miek.nl: no such file or directory
2017/08/31 16:19:15 [INFO] Successfully reloaded zone `miek.nl.'
2017/08/31 16:19:15 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630008
2017/08/31 16:19:15 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630008
::1 - [31/Aug/2017:16:19:19 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 110.177µs
::1 - [31/Aug/2017:16:19:21 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 182.309µs
2017/08/31 16:19:25 [ERROR] Failed to open `autotest/db.miek.nl' for `miek.nl.': open autotest/db.miek.nl: no such file or directory
2017/08/31 16:19:25 [INFO] Successfully reloaded zone `miek.nl.'
2017/08/31 16:19:25 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630009
2017/08/31 16:19:25 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630009
::1 - [31/Aug/2017:16:19:27 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 221.983µs
::1 - [31/Aug/2017:16:19:28 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 78.224µs
2017/08/31 16:19:32 [ERROR] Failed to open `autotest/db.miek.nl' for `miek.nl.': open autotest/db.miek.nl: no such file or directory
2017/08/31 16:19:32 [INFO] Successfully reloaded zone `miek.nl.'
2017/08/31 16:19:32 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630010
2017/08/31 16:19:32 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630010
::1 - [31/Aug/2017:16:19:34 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 79.29µs
::1 - [31/Aug/2017:16:20:43 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 129.117µs
2017/08/31 16:20:51 [ERROR] Failed to open `autotest/db.miek.nl' for `miek.nl.': open autotest/db.miek.nl: no such file or directory
2017/08/31 16:20:51 [INFO] Successfully reloaded zone `miek.nl.'
2017/08/31 16:20:51 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630011
2017/08/31 16:20:51 [WARNING] Parsing zone `miek.nl.': no change in serial: 1282630011
::1 - [31/Aug/2017:16:20:54 +0200] "SOA IN miek.nl. udp 37 false 4096" NOERROR qr,aa,rd,ra 204 85.687µs
~~~

**Comment by stp-ip** [comment]
Wasn't able to pinpoint it further. Quite annoying.

**Comment by miekg** [comment]
A, far fetched, idea could be that we miss fsnotify events...
Possible work around is always scanning all zones for SOA serial changes.

**Comment by stp-ip** [comment]
I assume the same.
Thought that was the idea around the scan interval we set or what does it actually do?

**Comment by miekg** [comment]
Picking up new, and dropping old zones

**Comment by stp-ip** [comment]
Should have read the code more closely I assume. Then it definitely makes more sense. Seems like one could use the interval as full fallback for all events now that we are checking the SOA.

Thanks for taking the time again.

**Comment by miekg** [comment]
Think we can morph the current reload code quite easily to such a new model.

**Comment by stp-ip** [comment]
\o/

**Comment by stp-ip** [comment]
With the drop of fsnotify the flakiness is gone. Awesome.
