### ISSUE TITLE
Forwarder doesn't properly multiplex DNS connections?

### ISSUE THREAD

**Issue by mzealey** [coredns/coredns#4300]
The DoH/DoT RFCs say that a client must support multiplexing over a single connection. The forwarder module here has connection caching, however from what I have seen it doesn't support DNS query multiplexing. Relevant code fragment is here:

https://github.com/coredns/coredns/blob/272ccb195d31cd1622d48f961f3a189ce3abb937/plugin/forward/connect.go#L110-L123

Basically with the current implementation if we want to send queries faster than the rtt + lookup time it will open multiple connections which is a bit of a problem on TCP/DoT or faster paced services. For proper forwarding I would expect this to open 1 connection over tcp, tls or udp (in the case of udp a single source port) and send multiple queries in parallel over that connection tracking them by their query ID, probably with some logic to timeout the query ids after a certain period, and perhaps open additional connections if there are too many (25%?) queries currently on the fly.

Is there any easy fix or alternative module which would do this - I've been unable to find one in go in my searches?

**Comment by mzealey** [comment]
We implemented this in https://github.com/DNSFilter/dns-multiplex in the end

**Comment by balboah** [comment]
Was there a particular reason why this wasn't implemented into coredns proxy/forwarder?
