### ISSUE TITLE
Authoritative Split-Key DNSSEC with Primary / Secondary

### ISSUE THREAD

**Issue by ntwkninja** [coredns/coredns#4301]
Greetings, I have a requirement for an authoritative CoreDNS server using split-key DNSSEC. We are running it as a k8s Deployment and it is not doing any in-cluster dns.

Is there a way to sign zones on-the-fly in a primary / secondary server configuration?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Authoritative Spl..." ]
>Greetings, I have a requirement for an authoritative CoreDNS server using
>split-key DNSSEC. We are running it as a k8s Deployment and it is not doing any
>in-cluster dns.

What is split-key DNSSEC?

>Is there a way to sign zones on-the-fly in a primary / secondary server
>configuration?

The *dnssec* plugin signs on the fly.

/Miek

--
Miek Gieben

**Comment by ntwkninja** [comment]
> [ Quoting <notifications@github.com> in "[coredns/coredns] Authoritative Spl..." ]

> What is split-key DNSSEC?

We are using a ZSK AND KSK via the dnssec plugin.

> Is there a way to sign zones on-the-fly in a primary / secondary server configuration?
> The *dnssec* plugin signs on the fly.

Agreed, however, we are trying to setup a primary and secondary so that we can publicly expose the secondary and manage zones on the primary. 

The transfer plugin is predefined to execute before the dnssec plugin but the secondary nameserver is not signing on the fly (only returns unsigned records). Is it possible for a publicly exposed secondary to transfer records from a primary and sign them on-the-fly with ZSK/KSK?

**Comment by anoncam** [comment]
The problem @ntwkninja seems to be describing the signing of the zone from the secondary server.  While the primary can send the zone to the secondary, the zone remains unsigned.

The transfer plugin fundamentally loaded sequentially.  The zone can't be signed after the transfer?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Authoritative..." ]
>    [ Quoting notifications@github.com in "[coredns/coredns] Authoritative
>    Spl..." ]
>
>    What is split-key DNSSEC?
>
>We are using a ZSK AND KSK via the dnssec plugin.

ack.

>    Is there a way to sign zones on-the-fly in a primary / secondary server
>    configuration?
>    The dnssec plugin signs on the fly.
>
>Agreed, however, we are trying to setup a primary and secondary is so that we
>can publicly expose the secondary and manage zones on the primary.

no, that doesn't work. This is (also) why DNSSEC required offline signing, so you can't
run into this particular problem.

What's wrong with _also_ online sign on the other server?

**Comment by ntwkninja** [comment]
> we are trying to setup a primary and secondary is so that we can publicly expose the secondary and manage zones on the primary.
> no, that doesn't work. This is (also) why DNSSEC required offline signing, so you can't run into this particular problem. What's wrong with _also_ online sign on the other server?

I'm not exactly sure of the question but we are able to publicly expose the primary server and use the dnssec plugin and ZSK to sign and serve. Would it be beneficial to simply forward the request to the primary (i.e. does this improve the security posture)? 

The basis of this question overall is to get a security best practice for implementation of authoritative CoreDNS as a deployment that minimizes threat surface area and adds a useful layer of security.

**Comment by anoncam** [comment]
bump.

**Comment by flickerfly** [comment]
Context: https://blog.shebash.io/building-a-cloud-native-dns-server/

**Comment by anoncam** [comment]
> Context: https://blog.shebash.io/building-a-cloud-native-dns-server/

you found my blog.

**Comment by miekg** [comment]
I you need this you need to use the *sign* plugin. There is no way to transfer the auto signed zone. If you want to keep on running with *dnssec* you need to transfer the keys to the other server(s) and dynamically sign there too.

**Comment by miekg** [comment]
Closing this as it's not possible.

**Comment by anoncam** [comment]
bummer
