### ISSUE TITLE
my masterNode is Ready,but the coredns is always restarting

### ISSUE THREAD

**Issue by chenlhcodes** [coredns/coredns#4306]
Hello everybody !
today, I deploy k8s on CentOS 7.9，for CNI, I chose the flannel.
Finally,the master node is Ready, but the coredns is CrashLoopBackOff.

![1](https://user-images.githubusercontent.com/69289383/99945269-4f6cf700-2daf-11eb-904b-ec0e80baef48.PNG)

![2](https://user-images.githubusercontent.com/69289383/99945284-54ca4180-2daf-11eb-87b0-1ed69c2a53b2.PNG)

The version I'm using
docker: 19.03
centos: 7.9
k8s: 1.15.2

thanks! :)

**Comment by clh-cod** [comment]
`[root@centos-k8s docker]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                 READY   STATUS             RESTARTS   AGE
kube-system   coredns-bccdc95cf-v88fw              0/1     CrashLoopBackOff   2          3m29s
kube-system   coredns-bccdc95cf-x4nz9              0/1     CrashLoopBackOff   2          3m29s
kube-system   etcd-centos-k8s                      1/1     Running            0          2m52s
kube-system   kube-apiserver-centos-k8s            1/1     Running            0          2m40s
kube-system   kube-controller-manager-centos-k8s   1/1     Running            0          2m37s
kube-system   kube-flannel-ds-amd64-tjrpm          1/1     Running            0          73s
kube-system   kube-proxy-2lxhq                     1/1     Running            0          3m28s
kube-system   kube-scheduler-centos-k8s            1/1     Running            0          2m50s`

`[root@centos-k8s mqtt]# kubectl logs -n kube-system coredns-5df4c9fcf6-89c6t
E1123 09:15:07.600033 1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1123 09:15:07.600033 1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
`

**Comment by chrisohaver** [comment]
Looks like flannel is not actually running (you'd see it in the pods list if it was).

**Comment by chenlhcodes** [comment]
no, I also think flannel is not actually running so I delete it and install again.
After I exec kubeadm reset, and reset iptables,
`iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X`
I develop k8s try again on the old machine.
Then,the coredns pods is running.
![2](https://user-images.githubusercontent.com/69289383/100034020-42dfb180-2e36-11eb-98f3-6db49647a57e.PNG)


This is a new CentOS system
![1](https://user-images.githubusercontent.com/69289383/100033193-abc62a00-2e34-11eb-8435-425dd153740f.PNG)

and there is a same problem.

**Comment by chenlhcodes** [comment]
It seems to be the `Flannel` with a problem? I've reconfigured a new system again, this time I chose the `Calico` plug-in. And there is no problem.
![3](https://user-images.githubusercontent.com/69289383/100037349-e3d16b00-2e3c-11eb-9a37-ae26de987268.PNG)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] my masterNode..." ]
>It seems to be the Flannel with a problem? I've reconfigured a system again,
>this time I chose the Calico plug-in. And there is no problem.
>3

seems to be k8s networking, which is not us

/close
/lock
