### ISSUE TITLE
the autopath plugin is not compatible with node-local-dns.

### ISSUE THREAD

**Issue by zlseu-edu** [coredns/coredns#4308]
In our kubernetes cluster, we use coredns' autopath plugin to reduce dns requests, also want to use [node-local-dns](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns) to improve dns performance, but find autopath not work. 

Steps to reproduce this issue are as follows.

step 1: deploy node-local-dns in kube-system.
``` bash
$ kubectl get ds node-local-dns -n kube-system
NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
node-local-dns   3         3         3       3            3           beta.kubernetes.io/os=linux   3d2h
```

step 2: set autopath and log in coredns corefile.
``` yaml
.:53 {
    errors
    log
    health
    ready

    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods verified
      fallthrough in-addr.arpa ip6.arpa
    }
    autopath @kubernetes
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```

step 3: query domain from default namespace via node-local-dns and lookup coredns log.
``` bash 
ping google.com

# print coredns log, find autopath not work.
[INFO] 192.168.0.106:13360 - 23671 "A IN google.com.default.svc.cluster.local. tcp 54 false 65535" NXDOMAIN qr,aa,rd 147 0.000133126s
[INFO] 192.168.0.106:47843 - 24049 "AAAA IN google.com.default.svc.cluster.local. tcp 54 false 65535" NXDOMAIN qr,aa,rd 147 0.000152154s
[INFO] 192.168.0.106:47843 - 46644 "A IN google.com.cluster.local. tcp 42 false 65535" NXDOMAIN qr,aa,rd 135 0.000053949s
[INFO] 192.168.0.106:47843 - 44696 "AAAA IN google.com.svc.cluster.local. tcp 46 false 65535" NXDOMAIN qr,aa,rd 139 0.000063889s
[INFO] 192.168.0.106:13360 - 44465 "A IN google.com.svc.cluster.local. tcp 46 false 65535" NXDOMAIN qr,aa,rd 139 0.000065178s
[INFO] 192.168.0.106:13360 - 47069 "AAAA IN google.com.cluster.local. tcp 42 false 65535" NXDOMAIN qr,aa,rd 135 0.000058719s
```

## Why not work ? ##

autopath get the search domains according to source request's pod ip.

``` bash
# plugin/kubernetes/autopath.go
	ip := state.IP()

	pod := k.podWithIP(ip)
	if pod == nil {
		return nil
	}

	search := make([]string, 3)
	if zone == "." {
		search[0] = pod.Namespace + ".svc."
		search[1] = "svc."
		search[2] = "."
	} else {
		search[0] = pod.Namespace + ".svc." + zone
		search[1] = "svc." + zone
		search[2] = zone
	}
```

and check if domain name is a sibling of the first element in the search path. if not, autopath will fail.

``` bash
# plugin/autopath/autopath.go
	if !firstInSearchPath(state.Name(), searchpath) {
		return plugin.NextOrFailure(a.Name(), a.Next, ctx, w, r)
	}


// firstInSearchPath checks if name is equal to are a sibling of the first element in the search path.
func firstInSearchPath(name string, searchpath []string) bool {
	if name == searchpath[0] {
		return true
	}
	if dns.IsSubDomain(searchpath[0], name) {
		return true
	}
	return false
}
```

In our cluster, dns requests like google.com.default.svc.cluster.local. from default namespace will be sent to node-local-dns which located in kube-system namespace, then upstream to coredns. because of source pod and namespace changed,  autopath not work correctly.

## Can autopath support node-local-dns ? ##
autopath and node-local-dns are quite important to cluster service discovery,  hope both work.

**Comment by chrisohaver** [comment]
There is an open [KEP](https://github.com/kubernetes/enhancements/pull/967) for adding autopath feature to node local dns, in the node local dns project (which is maintained as a [separate project](https://github.com/kubernetes/dns) from CoreDNS).

**Comment by zlseu-edu** [comment]
> There is an open [KEP](https://github.com/kubernetes/enhancements/pull/967) for adding autopath feature to node local dns, in the node local dns project (which is maintained as a [separate project](https://github.com/kubernetes/dns) from CoreDNS).

thx!
