### ISSUE TITLE
etcd/SkyDNS plugin does (not) provide wildcard support

### ISSUE THREAD

**Issue by kilokang** [coredns/coredns#4314]
As it is a SkyDNS replacement should provide a way of resolvind wildcard subdomain like in the original software which this plugins ins based: https://github.com/skynetservices/skydns#wildcards

**What happened**:
I insert manually or via [external-dns](https://github.com/kubernetes-sigs/external-dns) a wildcard (`*`) to a domain or ingress and it does not resolve.

**What you expected to happen**:
It should resolve any subdomain that matches `any`and `*` to the entry sotred in the etcd.

**How to reproduce it (as minimally and precisely as possible)**:
```json
{
  "host": "1.2.3.4",
  "ttl": 300,
  "targetstrip": 1
}
```
```bash
% etcdctl put /external-dns/internal/test/\*/manual-entry < entry
% dig test.test.internal +short | wc -l
0
% dig *.test.internal +short
1.2.3.4
```
**Environment**:

- the version of CoreDNS:
From DockerHub:
CoreDNS-1.8.0
linux/amd64, go1.15.3, 054c9ae
- Corefile:
```
test.internal.:53 {
  errors
  health {
    lameduck 5s
  }
  ready
  loop
  reload
  etcd test.internal {
    fallthrough
    path /external-dns
    endpoint http://etcd.external-dns:2379
  }
}
```
- logs, if applicable:
```
[ERROR] plugin/errors: 2 test.test.internal. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 test.test.internal. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 test.test.internal. A: plugin/loop: no next plugin found
```

**Comment by Diaoul** [comment]
I face the same issue wanting to manually add a wildcard DNS record with etcd but I cannot get it to work.
Seems the same as #1633
Has this been solved? Is there a workaround?

**Comment by kilokang** [comment]
I found not work around. I wanted to use it as a DNS with external-dns and I switched to PowerDNS for that purpose.

I do even have a Helm chart for that: https://github.com/txqueuelen/pdns-stateless/

**Comment by Bjohnson131** [comment]
Hello, has there been any changes to allow etcd to store `*` -style A/AAAA records with the base plugin?
