### ISSUE TITLE
EKS Coredns pods fails to resolve and throws connection timeout

### ISSUE THREAD

**Issue by vkperumal** [coredns/coredns#4327]
We have EKS cluster running 20 replicas of coredns and some of the coredns replicas throws timeout error on resolution which in turn causes the app to fail resolving DNS. We had to kill the coredns pods to fix the issue.

EKS version: 1.15

Coredns version: v1.6.6

CoreDNS configmap:
{
errors
health
kubernetes cluster.local in-addr.arpa ip6.arpa {
pods insecure
upstream
fallthrough in-addr.arpa ip6.arpa
}
prometheus :9153
forward . /etc/resolv.conf
cache 30
loop
reload
loadbalance
}

**Comment by chrisohaver** [comment]
logs?

**Comment by vkperumal** [comment]
the issue was with EKS reaching ENI dns limits. Thanks @chrisohaver for looking into this
