### ISSUE TITLE
Building failing due to missing dns.Len method

### ISSUE THREAD

**Issue by wrouesnel** [coredns/coredns#433]
Currently the source code build is failing due to a missing dns.Len method in the dns package. It looks like the RR_Header's len method would be a suitable replacement but at present it's private to the package so I'm not sure where the appropriate fix would go.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[miekg/coredns] Building failing du..." ]

> Currently the source code build is failing due to a missing dns.Len method in the dns package. It looks like the RR_Header's len method would be a suitable replacement but at present it's private to the package so I'm not sure where the appropriate fix would go.

Think your dns lib is too old:

 godoc github.com/miekg/dns Len

works for me.

/Miek

## 

Miek Gieben
