### ISSUE TITLE
Probable mistake in the Azure Plugin documentation

### ISSUE THREAD

**Issue by Seethaar** [coredns/coredns#4332]
https://coredns.io/plugins/azure/ states "The azure plugin supports all the DNS records supported by Azure, viz. A, AAAA, CNAME, MX, NS, PTR, SOA, SRV, and TXT record types."

But Azure DNS does not support NS records.

https://docs.microsoft.com/en-us/azure/dns/private-dns-privatednszone#restrictions

_"You can't create zone delegations (NS records) in a private DNS zone. If you intend to use a child domain, you can directly create the domain as a private DNS zone and link it to virtual network without setting up a nameserver delegation from the parent zone."_

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Probable mistake ..." ]
>https://coredns.io/plugins/azure/ states "The azure plugin supports all the DNS
>records supported by Azure, viz. A, AAAA, CNAME, MX, NS, PTR, SOA, SRV, and TXT
>record types."
>
>But Azure DNS does not support NS records.
>
>https://docs.microsoft.com/en-us/azure/dns/private-dns-privatednszone#
>restrictions
>
>"You can't create zone delegations (NS records) in a private DNS zone. If you
>intend to use a child domain, you can directly create the domain as a private
>DNS zone and link it to virtual network without setting up a nameserver
>delegation from the parent zone."

odd, but fair enough, can you send a PR to update the text?

**Comment by gunadhya** [comment]
Hi @miekg , So I came across this issue and did some digging and found that Azure does support NS records for public https://docs.microsoft.com/en-us/azure/dns/dns-zones-records#ns-records and the plugin seems to implement it here https://github.com/coredns/coredns/blob/ae330a3f55ea4d097a8e2e656da362fa6380c463/plugin/azure/azure.go#L192

But it doesn't work with Private as mentioned here https://docs.microsoft.com/en-us/azure/dns/private-dns-privatednszone#restrictions 
Maybe update the doc based on this?

**Comment by yongtang** [comment]
@gunadhya PRs for updating the doc is welcomed.
