### ISSUE TITLE
Return code for synthesized CNAME records (from wildcards and DNAMEs)

### ISSUE THREAD

**Issue by SivaKesava1** [coredns/coredns#4341]
Hi,

This is related to the return code when the query is for a `CNAME` record, but the zone file has either a matching wildcard `CNAME` or a `DNAME` record.

In general, the response is `NXDOMAIN` if the `CNAME` target does not exist and is `NOERROR` if the query type is `CNAME` irrespective of whether the target exists or not. 
CoreDNS responds properly for the above cases except for the subtle case where the `CNAME` is a synthesized one. This is a minor issue, but putting it down for future reference. 

Consider these cases, 
|  	|  	|  	|  	|
|-	|-	|-	|-	|
| foo.example.com. 	| 500 | CNAME | bar.example.com.  	|
| *.code.example.com. 	| 500 | CNAME	| test.example.com.  	|

For queries   _<foo.example.com. , A>_, and _<a.code.example.com. , A>_ CoreDNS responds with the corresponding `CNAME` record and `NXDOMAIN.` Similarly, for  _<foo.example.com. , CNAME>_, it responds with the `CNAME` record and with `NOERROR` code. This is the expected behavior and is followed by other implementations too. 

The issue is with the query  _<a.code.example.com. , CNAME>_. It correctly synthesizes the `CNAME` record but responds with  `NXDOMAIN,` which should be similar to the above case, _<foo.example.com. , CNAME>_, and should have been `NOERROR.` 

An even more subtle case is the one involving DNAMEs; you can please have a look at them here:
https://github.com/NLnetLabs/nsd/issues/140
https://gitlab.isc.org/isc-projects/bind9/-/issues/2284
https://github.com/PowerDNS/pdns/issues/9725

**Comment by ykhr53** [comment]
I can't reproduce the issue. It could be already resolved.
@SivaKesava1  Could you check with the latest commit? And if you still see a problem, please share details. 
Thanks!

```
$ dig a.code.example.org. CNAME +norec +qr @127.0.0.1

; <<>> DiG 9.16.20 <<>> a.code.example.org. CNAME +norec +qr @127.0.0.1
;; global options: +cmd
;; Sending:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33631
;; flags: ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 1810303e7ce661a7
;; QUESTION SECTION:
;a.code.example.org.		IN	CNAME

;; QUERY SIZE: 59

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33631
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 1810303e7ce661a7 (echoed)
;; QUESTION SECTION:
;a.code.example.org.		IN	CNAME

;; ANSWER SECTION:
a.code.example.org.	500	IN	CNAME	test.example.org.

;; AUTHORITY SECTION:
example.org.		3600	IN	NS	a.iana-servers.net.
example.org.		3600	IN	NS	b.iana-servers.net.

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Sep 08 08:42:45 JST 2021
;; MSG SIZE  rcvd: 193
```

**Comment by chrisohaver** [comment]
As described, it is solved by the recent fix, since the synthesized cname is no longer followed for a cname type query. Thanks!
