### ISSUE TITLE
Problems with latest 1.8.0

### ISSUE THREAD

**Issue by ltagliamonte-dd** [coredns/coredns#4343]
Hello Folks,
last week we update our prod environments to 1.8.0 from 1.6.9 and unfortunately we had to rollback, I did try to debug the issue but since was prod I didn't have enough time to get to the bottom of it. Here the symptoms:

- DNS queries (A type) for entries with high number of endpoints (>200) taking ~35ms and very often failing and coreDNS logging the following error:

```
[ERROR] plugin/errors: 2 <MyDNS>. A: dns: overflow unpacking uint16
[ERROR] plugin/errors: 2 <MyOtherDNS>. A: dns: overflow unpacking uint32
 ```
- 7X Number of DNS requests to the upsteam DNS server
<img width="829" alt="Screen Shot 2020-12-18 at 9 29 06 AM" src="https://user-images.githubusercontent.com/51684360/102643071-8a92e980-4113-11eb-82a0-724d487aeb53.png">

- DNS over TCP requests
<img width="820" alt="Screen Shot 2020-12-18 at 9 44 46 AM" src="https://user-images.githubusercontent.com/51684360/102644477-be6f0e80-4115-11eb-9e75-1475b84992f3.png">

I did a tcpdump but it looks inconclusive, but is is clear that each request is retransmitted:
<img width="1675" alt="Screen Shot 2020-12-18 at 9 48 24 AM" src="https://user-images.githubusercontent.com/51684360/102645007-9e8c1a80-4116-11eb-8067-41544dea4835.png">

this is the coreDNS config:
```
  Corefile: |-
    .:53 {
        bind 192.168.0.1
        errors
        health :8081 {
          lameduck 5s
        }
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        cache 30
        loadbalance
        reload
    }
    my-internal.domain {
      bind 192.168.0.1
      errors
      cache 30 {
        prefetch 2 1m 20%
      }
      forward . 127.0.0.1:8600 172.30.234.20:8600 {
        policy sequential
      }
    }

```

I gave a look at changes from 1.6.9 and 1.8.0 and i noticed some changes/fix on EDNS0 that's my main suspect atm.
I tried to reproduce the issue in staging without luck, so the QPS seems to be another factor.

**Comment by chrisohaver** [comment]
> Another interesting thing i noticed is coredns sending OPT request to itself:

What does `/etc/resolv.conf` contain (i.e. what is .53 being forwarded to)?

Can you give a bit of background on your set up?  The `bind` and `forward . 127.0.0.1:8600 ...` are out of the ordinary for a CoreDNS k8s deployment.

**Comment by ltagliamonte-dd** [comment]
@chrisohaver we have a redundant coreDNS setup:
- CoreDNS that runs as deployment (standard installation that comes with k8s)
- CoreDNS that runs as daemonset (full installation not just cache)

all our pods in their resolv.conf have:
```
nameserver 192.168.0.1 <- loopback interface that points to the local CoreDNS daemonset
nameserver 172.30.224.10 <- ClusterIP to the CoreDNS deployment
search service-template.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```

The coreDNS daemonset runs in the hostNetwork and its resolv.conf looks like:
```
nameserver 172.31.0.2 <- AWS VPC resolver
search us-west-2.compute.internal
```
The 127.0.0.1:8600 is a local Consul agent pod deployed as daemonset (my internal domain is in Consul )
The 172.30.234.20:8600 is the consul-agent ClusterIP so that when I update the local consul agent i have a fallback on a random node in the cluster.

**Comment by ltagliamonte-dd** [comment]
@chrisohaver i think the "loop" is config problem not related with the update, please disregard last point
i removed it from the initial message

**Comment by ltagliamonte-dd** [comment]
I think it is EDNS because the problem in resolution was really evident querying DNS with >200 records in.
Error in logs where only about this big endpoints.

**Comment by chrisohaver** [comment]
> I think it is EDNS because the problem in resolution was really evident querying DNS with >200 records in.
Error in logs where only about this big endpoints.

A typical client-server exchange to request a 200 endpoint headless service would as follows ...
1. Client makes request.  It has no foresight into how big the response will be, so the request is as normal/default.  Usually this is over UDP.  It may use EDNS to increase the max response size, but this would be per the default behavior for all queries.
2. Server replies to UDP request. If the response size exceeds the max size allowed (likely), the response is truncated.
3. Client processes response.  If the the response is truncated it retries the query using TCP.
4. Server replies to TCP request, sending complete response.

In your packet dump example, the client is retransmitting the request in UDP, which suggests that it times out before getting a response (e.g. due to packets loss).


```
[ERROR] plugin/errors: 2 <MyDNS>. A: dns: overflow unpacking uint16
[ERROR] plugin/errors: 2 <MyOtherDNS>. A: dns: overflow unpacking uint32
```

Are these errors generated for the exact FQDN names of the service being queried? Or do they have other domains attached?

**Comment by ltagliamonte-dd** [comment]
Hello @chrisohaver thank you for looking into this, the errors generated by CoreDNS are for the exact FQDN names of the service being queried.
Packet loss is almost impossible since all happens in locally, but i will give a look at my network metrics and update here if i find anything interesting

**Comment by chrisohaver** [comment]
> the errors generated by CoreDNS are for the exact FQDN names of the service being queried

The error could indicate that the first query received was malformed in some way (resulting in the overflow).  I don't know if a response is sent back to the client in this case (FORMERR?) or if no response is sent.  In any case, the client then presumably retransmits the request, and it works the second time (or eventually).

Cache could be coming into play here?

Without reproducible steps, this is all conjecture.

**Comment by ltagliamonte-dd** [comment]
I did look at the tx/rx network errors and I didn't find anything.
In the tcpdump I posted both the first and second (retransmitted) query get an answer back.

CoreDNS error logs belongs **exclusively** to records with high number of endpoints that don't fit in a UDP packet for sure.

In staging I have the same setup I've described here but I can't repro, I think that the next thing to to is to move up one release at the time instead of doing 1.6.9->1.8 and see where it breaks, I've looked at the changes they all look fundamentally ok, I was talking about the EDNS change just because the error in the logs shows up **only** with large endpoints.

**Comment by chrisohaver** [comment]
> In the tcpdump I posted both the first and second (retransmitted) query get an answer back.

What is the answer and response code to each request?  And is the first answer received before the retransmit?

> I think that the next thing to to is to move up one release at the time instead of doing 1.6.9->1.8 and see where it breaks

That would narrow things down further, but being able to reproduce this somewhere other than your production env would help the most.  Have you tried reproducing in staging with high QPS as you suggested?

**Comment by chrisohaver** [comment]
> In the tcpdump I posted both the first and second (retransmitted) query get an answer back.

Having as much detail as you can share of a full client-server exchange may help.  e.g. the initial query, the first response, retransmission, and follow up response(s), etc.

**Comment by ltagliamonte-dd** [comment]
@chrisohaver again i really appreciate you looking into this with me.
I've looked at the tcpdump and both DNS queries (including the retransmitted one) receive as replyCode: NoERROR.
Both of the reply contains 28 records and they have truncate flag set.

Because of the 7X numbers of queries the local consul agent that serves my internal domain was overwhelmed as well, I can see an increase of CPU and CPU throttling so maybe the retransmission is just caused my the local consul agent being slow, I don't have any errors in Consul.

Now that we are discussing this an i looked back at the config the local cache of 30s with the prefetch option should have shielded the consul agent from all this queries but it didn't.
The records for my internal domain have 10s TTL so the cache is configured properly imho.

What i'm trying to say is that maybe the problem is in the cache, have you made any major changes to the cache between 1.6.9 and 1.8?

**Comment by chrisohaver** [comment]
What domain are the DNS queries in?

**Comment by ltagliamonte-dd** [comment]
My internal domain we are moving away from kubernetes DNS domain

**Comment by chrisohaver** [comment]
Ok. I had incorrectly assumed Kubernetes.

This is probably related to a fix made to the forward plugin ( in an upstream repo miekg/dns). Prior to the fix, Forward was removing the truncation bit from upstream responses if they were truncated. It would therefore send an incomplete response to the client without marking it as truncated. The client would assume the response was complete and not retry over TCP to get the whole response. The fix was to retain the truncation bit of set when sending the answer to the client.

**Comment by chrisohaver** [comment]
Little details line up with that as the primary cause. Increase in TCP traffic (clients retrying now, as expected, over TCP). 7x traffic increase (28*7 = close to 200 = all records being returned now).

**Comment by ltagliamonte-dd** [comment]
@chrisohaver it does make sense but I'm not sure about the truncate flag I need to get a capture from prod that is now reverted to confirm.

I'm not totally convinced about the missing truncate flag being the cause, because just a couple of week ago I worked on reducing TCP queries in our infra.
In the same setup as of today (coreDNS version 1.6.9) we had a single DNS query to an external infrastructure that was getting retried over TCP, falling this time in the first part of my config file:
```
forward . /etc/resolv.conf
```

What I'm trying to say, is that i was seeing this retries in TCP on 1.6.9 the truncate flag must have been there. I solved that issue with a LB in front of that infra.

**Comment by ltagliamonte-dd** [comment]
1.6.9 def sends back the truncate flag:
```
dig @192.168.0.1 +noedns myBIGService.my-internal.domain
;; Truncated, retrying in TCP mode.
```

**Comment by chrisohaver** [comment]
Thanks. I can dig deeper if you can supply some steps to reproduce the bug.

**Comment by ltagliamonte-dd** [comment]
@chrisohaver today i was looking at some captures and I keep thinking this is an EDNS problem, at this line:
https://github.com/coredns/coredns/blob/master/plugin/pkg/upstream/upstream.go#L32

Is the EDNS size set to the client requested size or to the [buffsize](https://coredns.io/plugins/bufsize/) config option?

**Comment by amit-handda** [comment]
Hi @chrisohaver (@ltagliamonte-dd colleague here) some more info. if we set `force_tcp` to `forward` plugin config. it solves the issue.

regarding usual UDP interaction between client -> coredns -> myinternaldomain (forward domain):
It takes 5 secs before response is returned to client (containing 0 answers)
in the meantime, coredns forward plugin makes ~667 queries to the myinternaldomain dns server.
![image](https://user-images.githubusercontent.com/56566242/106094641-2d615f00-60e7-11eb-90f8-1b0914978605.png)

Also, difference between client -> coredns vs coredns -> myinternaldomain DNS request is as follows:

- latter sets UDP payload size to 2048 (former is 4096)
- D0 bit is set (PFA)

![image](https://user-images.githubusercontent.com/56566242/106094820-8af5ab80-60e7-11eb-9144-8e71b6338e5f.png)

**Comment by chrisohaver** [comment]
The "5 second delays over udp, and "everything works over tcp" observations correlate with packet loss symptoms alluded to earlier (keywords: kubernetes conntrack drops). Node local dns cache is commonly deployed to mitigate that issue.

**Comment by ltagliamonte** [comment]
@chrisohaver for what I understood, i think the problem is that coredns forwarding the request to consul doesn't respect the UDP opt size of 4096 received from the client and overwrite it to 2048.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Problems with..." ]
>@chrisohaver for what I understood, i think the problem is that coredns
>forwarding the request to consul doesn't respect the UDP opt size of 4096
>received from the client and overwrite it to 2048.

that is very likely not the issue

**Comment by amit-handda** [comment]
update: we have managed to find the patch which eliminates the issue, however, clueless about the exact bug still. will be grateful if you have further insights. issue summary is as follows:

# Current setup
* coredns daemonset v1.8.0 (bound to 192.168.0.1) deployed on v1.18.9 cluster. The DNS query in question, is forwarded to upstream dns server (serving mydomain)
* myservice.service.mydomain. : 401 answers

## Test Scenarios

* Tried out dns query with UDP. Played with EDNS,bufsize options as well, doesnt work.

$ dig myservice.service.mydomain.
$ dig @192.168.0.1 +edns +bufsize=4096 myservice.service.mydomain.

dig shows 0 answers. and coredns pod on the node shows following error:

```[ERROR] plugin/errors: 2 myservice.service.mydomain. A: dns: overflow unpacking uint32```

* Tried out dns query with TCP. It works.

$ dig +tcp myservice.service.mydomain.
It shows 401 answers. and coredns pod doesnt show any error.

# Patched Setup

Patched coredns v1.8.1 with minor update. set UDPSize to 8192 in the forward plugin.
https://github.com/coredns/coredns/compare/master...amit-handda:master
```	
-        pc.c.UDPSize = uint16(state.Size())
+	//pc.c.UDPSize = uint16(state.Size())
+	pc.c.UDPSize = uint16(8192)
```

The scenarios not working above, are working now.

**Comment by amit-handda** [comment]
in my limited understanding of the code. `bufsize` plugin should help ? but it didnt increase the UDP size when I did (verified via tcpdump). Also, bufsize is limited to 4096. can we increase to 8192 ? any issues ?

**Comment by amit-handda** [comment]
@chrisohaver morning. can I get your thoughts on it ? the patch fixes the issue, but I dont know why bufsize wont work and how to do it via config.

**Comment by chrisohaver** [comment]
_If you can provide reproducible steps_, I can look at it in with a debugger to see what the root cause is.  My thoughts are that setting the buffer size high just sidesteps the root issue without really fixing it.

**Comment by chrisohaver** [comment]
I was unable to reproduce the issue (as described [here](https://github.com/coredns/coredns/issues/4343#issuecomment-769425801)).

I replicated the scenario described [above](https://github.com/coredns/coredns/issues/4343#issuecomment-769425801), with coredns forwarding to another coredns instance as the upstream that held a 400+ answer A entry.  All dig queries worked fine.  As expected, the initial udp query response comes back truncated, prompting the client (dig) to automatically resend the request as TCP.

**Comment by amit-handda** [comment]
hi @chrisohaver thanks for responding.  however, In our case, client doing dns query(dig) doesnt get the truncated flag.
It receives servfail error.

```
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 63287
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available
```

# Code Analysis

I added debug logs to the code around [here](https://github.com/coredns/coredns/blob/d29fd8c5504cb86e7ee86ef9fdcedfb648ec0a5e/plugin/forward/forward.go#L131).

Done the code analysis via debug logs. TL;DR; adding `prefer_udp` config to forward plugin config fixes the error.

`ret` variable contains truncated dns response from upstream server. however, we dont have `prefer_udp` enabled in config. hence, [it](https://github.com/coredns/coredns/blob/d29fd8c5504cb86e7ee86ef9fdcedfb648ec0a5e/plugin/forward/forward.go#L137) doesnt switch to tcp. (on adding `prefer_udp`, it does, and the client gets all the answers and no error).

code continues [looping](https://github.com/coredns/coredns/blob/d29fd8c5504cb86e7ee86ef9fdcedfb648ec0a5e/plugin/forward/forward.go#L177) and retrying through the dns timeout duration (5s). It keeps getting same error (dns: overflow unpacking uint32).

At the end of it, [servfail error](https://github.com/coredns/coredns/blob/d29fd8c5504cb86e7ee86ef9fdcedfb648ec0a5e/plugin/forward/forward.go#L180) is returned.

**Comment by chrisohaver** [comment]
> we don't have prefer_udp enabled in config

Neither did I in my test.

What happens when you query your upstream server directly (coredns not in the middle)?

**Comment by amit-handda** [comment]
hey, thanks again. I get the truncated response if I ping the upstream server directly.

```
dig @upstream-server +bufsize=2048 +edns=0 myservice.service.mydomain. A +notcp
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.amzn2.0.2 <<>> @upstream-server +bufsize=2048 +edns=0 myservice.service.mydomain. A +notcp
```

hopefully, we are on the same page that via coredns, I should get similar truncated response so that dig can retry.

**Comment by chrisohaver** [comment]
> hopefully, we are on the same page that via coredns, I should get similar truncated response so that dig can retry.

Yes, as it did in my test above.

**Comment by chrisohaver** [comment]
> code continues looping and retrying through the dns timeout duration (5s). It keeps getting same error (dns: overflow unpacking uint32).

That error suggests that the response received from the upstream server is malformed in some way.
Perhaps dig is ignoring the malformation, or perhaps it aborts parsing the response once it sees the TC bit thus averting parsing the malformed part.

What happens if you try ...

`dig @upstream-server myservice.service.mydomain. A +ignore`

`+ignore` ignores the TC bit and displays the response as received.

**Comment by amit-handda** [comment]
Hi,

there are 200 response ideally. I get the following response (124 responses). thanks.

```
 dig @upstream-server +bufsize=2048 +edns=0 myservice.service.mydomain. A +notcp +ignore

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.amzn2.0.2 <<>> @upstream-server +bufsize=2048 +edns=0 myservice.service.mydomain. A +notcp +ignore
; (5 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39793
;; flags: qr aa tc rd ra; QUERY: 1, ANSWER: 124, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 2048
;; QUESTION SECTION:
;myservice.service.mydomain. IN A

;; ANSWER SECTION:
myservice.service.mydomain. 10 IN A 172.30.50.60
myservice.service.mydomain. 10 IN A 172.30.212.153
myservice.service.mydomain. 10 IN A 172.30.94.2
myservice.service.mydomain. 10 IN A 172.30.13.126
myservice.service.mydomain. 10 IN A 172.30.91.19
myservice.service.mydomain. 10 IN A 172.30.6.11
...
```

**Comment by chrisohaver** [comment]
Well - I don't know for sure, but maybe the upstream server is not truncating the response on a record boundary.  dig may be ignoring it. A packet capture would help confirm.

@miekg, Do you know if DNS servers are expected/required to truncate responses on record boundaries?  Or, should _forward_ be tolerating an incomplete final record in a truncated response (I guess it's only recourse would be to drop the record and decrement header count before sending to client).  

I would think the former, but I can't confirm in RFCs.

**Comment by amit-handda** [comment]
Hi @chrisohaver, thank you. from debugging the code, it does look that way. unpacking error comes from https://github.com/miekg/dns/blob/35023fab5c1d57c9ac56da33a897af8794eb9567/msg_helpers.go#L92 probably

PFB snapshot of the response from the upstream server. would it suffice ?

![image](https://user-images.githubusercontent.com/56566242/107436136-fc6b2c00-6ae1-11eb-900e-3af46437a97a.png)

**Comment by chrisohaver** [comment]
> Hi @chrisohaver, thank you. PFB snapshot of the response from the upstream server. would it suffice ?

If the response contains an incomplete record due to truncation, the last record would be cut off. Not the header, which is what you have drilled into in the screen shot.

**Comment by amit-handda** [comment]
Hi, sharing the last part of the dns response. does it help ? thanks
 
![image](https://user-images.githubusercontent.com/56566242/107440883-355acf00-6ae9-11eb-9044-9018740f9c8c.png)

**Comment by chrisohaver** [comment]
Well - that view doesn't show any malformation either.  Unfortunately the parse error is not specific as to where the problem is.  Since you are already in the frame of adding debug code, if you could add debugging to the parsing to see exactly where the errors are encountered it may help answer questions such as:  is it in the header, answer section, etc.  is it consistently failing and in the same place every time? 

I dont know if fragmentation of UDP packets could possibly manifest itself like this?

BTW, What DNS implementation is your upstream?

**Comment by amit-handda** [comment]
Hi @chrisohaver , I managed to copy the packet received in coredns and load it into wireshark. it shows malformation.
however, I dont see the same in the tcpdump output :( difference is in the size difference between the packets (2090 vs 2096), would you have an idea about the probable cause for it ?

coredns packet:
![image](https://user-images.githubusercontent.com/56566242/107568563-0a7d8300-6b9c-11eb-8057-2600bd91c9ab.png)

tcpdump output:
<img width="843" alt="Screen Shot 2021-02-10 at 12 40 16" src="https://user-images.githubusercontent.com/56566242/107569787-8e843a80-6b9d-11eb-892f-7bafe213c7e9.png">

**Comment by chrisohaver** [comment]
A possible cause is that the upstream server is (errantly) sending a malformed response.

**Comment by amit-handda** [comment]
@chrisohaver , thank you getting back to me.
first screenshot (in my earlier comment) is obtained via `debug.hexdump` in coredns [updated code](https://github.com/coredns/coredns/compare/master...amit-handda:master). I copied the output, xformed to pcap via text2pcap and loaded into wireshark
```/Applications/Wireshark.app/Contents/MacOS/text2pcap -i 46 -4 127.0.0.1,127.0.0.1 -u 99,8600 ~/badpacket3.txt ~/badpacket3.pcap```

second screenshot is the tcpdump capture of the upstream server. upstream server is consul v1.7.2 (using [miekg->dns v1.1.31](https://github.com/hashicorp/consul/blob/6eeccc93ce99d96c1151da9b71d83f967ccca35e/go.mod#L65) version)

do you think there could be an issue with upstream server ? since tcpdump of upstream server packet is clean, but once its inside coredns, its malformed ?
Thanks,

**Comment by chrisohaver** [comment]
It's challenging to draw conclusions from cropped (or even un-cropped) screen shots.  The second screen shot appears to show a _query_ not a _response_.
