### ISSUE TITLE
Azure Plugin returns SERVFAIL for some records (maybe paging issue)

### ISSUE THREAD

**Issue by mgugger** [coredns/coredns#4350]
**What happened**:
We have a private azure dns zone for which we use the azure plugin. Some records work and the azure plugin returns the A-record, some records however return SERVFAIL. The affected records are all records, which are not displayed when visiting the azure dns resource. Upon clicking "Load More" in the azure portal, the affected records are displayed. So we assumed it might be a paging issue after a certain amount of records.

**What you expected to happen**:
All records are correctly resolved.

**How to reproduce it (as minimally and precisely as possible)**:
Open a private azure dns zone with more than 100 records and use the azure plugin to resolve the zone. All records which are not within the first 100 in the list are not correctly resolved by the plugin.

**Anything else we need to know?**:
Seems similar to this issue but for gcp clouddns: https://github.com/coredns/coredns/issues/4322

**Environment**:
- the version of CoreDNS: 1.8.0
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04 LTS
- Others:

**Comment by miekg** [comment]
closed via #4351
