### ISSUE TITLE
failed to use go to build coredns

### ISSUE THREAD

**Issue by Shawn71** [coredns/coredns#4355]
failed to use go to build coredns.

step:
1.mkdir -p /root/temp/go/src/github.com/coredns/coredns && cd /root/temp/go/src/github.com/coredns/coredns
2.git clone https://github.com/coredns/coredns.git
3.cd coredns
4.  docker run --rm -i -t -v $PWD:/v -w /v golang:1.15.2 make 
## get below error 
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer
github.com/coredns/coredns/plugin/trace
github.com/coredns/coredns/plugin/whoami
make: *** [Makefile:16: coredns] Error 2

even I try to use other command " docker run --rm -i -t -v $PWD:/v -w /v golang:1.14 make" . both failed with same error .

I am really appreciated if someome who help me out of this . thanks in advance .

**Comment by zouyee** [comment]
`docker run --rm -i -t -v $PWD:/v -w /v -e GOPROXY=https://goproxy.cn golang:1.15.2 make`

**Comment by zouyee** [comment]
same issue：https://github.com/coredns/coredns/issues/4228
/label duplicate
