### ISSUE TITLE
how does the TTL to effect the client from configmap of  CoreDNS and what is the meaning of "cache 1800"

### ISSUE THREAD

**Issue by Shawn71** [coredns/coredns#4356]
details for configmap of CoreDNS:
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
            lameduck 5s
          }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 600
          }
        hosts {
           1.1.1.1 www.sina.com
           2.2.2.2 www.kaixinduole.com
           fallthrough
          }
        prometheus :9153
        forward . 114.114.114.114
        cache 1800
        loop
        reload
        loadbalance
       }
    kaixinduole.com {
        errors
        log
        cache 2
        forward . 8.8.4.4
       }
kind: ConfigMap
metadata:

I am trying to dig the kubernetes cluster name and do traffic capture in this pod simultaneously,the below is the traffic capture 

first response from coredns:
![image](https://user-images.githubusercontent.com/19188604/103132845-c3b5f580-46e1-11eb-8fbf-f3c44989c4ac.png)

second response from coredns:
![image](https://user-images.githubusercontent.com/19188604/103132958-9453b880-46e2-11eb-8f13-dbbc43d7134f.png)

and the TTL is set to 598 for the third resonse from coreDNS  and so on .

here is my two questions. really appreciated for some who can help .
1.why is TTL diminishing
2. cache 1800 . does it effect the coredns to cache the DNS response for 1800 seconds ?

**Comment by chrisohaver** [comment]
`cache 1800` will cache records for their TTL, but if the TTL is > 1800 seconds, then it will only be cached for 1800 seconds.
`ttl 600` in the kubernetes plugin section, will create records with a TTL of 600 seconds.

> 1.why is TTL diminishing

Because time is progressing forward.  For every second a record stay in cache, its TTL is reduced by one. Once the TTL drops to zero, it is no longer served from cache.
