### ISSUE TITLE
Sudden peaks under low load

### ISSUE THREAD

**Issue by cemo** [coredns/coredns#4357]
I have tried to understand why we had some dns issues on our production systems but could not find so far. However I have some clues and I wanted to share to here to get some help. 

We are using v1.6.6 Core (We can upgrade it but wanted to sure first why these spikes are happening)

As you can see we have extremely low request count:

![image](https://user-images.githubusercontent.com/44156/103136641-2c49a600-46d3-11eb-9c4b-236e3d9ab391.png)

However we have in increase on Receiving Packages (RX) and CPU. When these spikes are happening, pod could not answer DNS requests. 

![image](https://user-images.githubusercontent.com/44156/103136822-d249e000-46d4-11eb-9f47-b3167430ee0f.png)

Can someone point me what is the problem? How can I solve it?

**Comment by chrisohaver** [comment]
> However we have in increase on Receiving Packages (RX) and CPU. 

Do you know what the nature of the RX packets are?  Who is the sender?  What is the content?

**Comment by cemo** [comment]
@chrisohaver I have upgraded our cluster to `coredns:v1.7.0` and increased cpu resource 0.1 -> 0.5 cpu. Last 10 days we had 0 dns issue. I installed some tools to find sender. For now I will close this issue.

**Comment by Hardikrathod01** [comment]
Was this giving you intermittent unknown host exception? 
I also have same issue and I think may be your solution will work for me too.
