### ISSUE TITLE
Json api for DoH

### ISSUE THREAD

**Issue by kloenk** [coredns/coredns#4358]
**What would you like to be added**:
A DoH api, which uses json instead of the dns wired format, as described by [cloudflare](https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format) and google.

**Why is this needed**:
Give the ability to easily create a Webinterface like [google](https://dns.google.com/query?name=kloenk.de&rr_type=A&ecs=&show_dnssec=true) and also let's user debug DoH via curl

A simple implementation would need this to be resolved: https://github.com/miekg/dns/issues/1204

**Comment by kloenk** [comment]
I created a sample Implementation, but it still waits for miekg/dns#1205 to give working output

https://github.com/Kloenk/coredns/tree/doh-json

**Comment by miekg** [comment]
> For lack of an agreed upon JSON schema for DNS over HTTPS in the IETF, Cloudflare has chosen to follow the same schema as Google's DNS over HTTPS resolver.

There is a good reason for that, because the DNS presentation has many corner cases that this format probably doesn't work with

**Comment by balboah** [comment]
I'm also looking for this support. Can't we have it optional with "experimental_json = true" kind of config?
Willing to try to implement this by using https://github.com/m13253/dns-over-https/tree/master/json-dns, they already use the same DNS msg struct as coredns.

**Comment by balboah** [comment]
@Kloenk whats the status in your sample implementation? are you using it?

**Comment by kloenk** [comment]
Not really using it, as also the dependency pr did not get merged.

**Comment by balboah** [comment]
@Kloenk looks good to my untrained dns-eye. I rebased and added the suggested header stripping on that PR.
https://github.com/balboah/coredns/tree/doh-json

Thanks for doing this
