### ISSUE TITLE
Split Key (KSK/ZSK) Signed Zone Transfers

### ISSUE THREAD

**Issue by ntwkninja** [coredns/coredns#4361]
**What would you like to be added**:  Request added ability to transfer DNSSEC signed zonefiles using split key (ZSK/KSK) signing natively within CoreDNS.

**Why is this needed**:  please see [reference](https://github.com/coredns/coredns/issues/4301)*: This feature is requested to allow a publicly exposed secondary server to receive signed zone files from a hidden/protected primary server in order to achieve a better security posture for DNSSEC keys.

**Comment by miekg** [comment]
Using a CSK (as implemented by the *sign* plugin) is fine. Rolling your keys for DNS only leads to outages and there is no proof you actually need to roll your keys for any reason. And key rollovers is the reason ZSK/KSK split exists. If your keys are compromised you need to talk to your parent anyway, negating any perceived benefit of zsk/ksk.

This also works with transfers without problems.

**Comment by anoncam** [comment]
We are restricted via organizational policies to use only the KSK and ZSK.  We are not permitted to use a CSK.  BIND fully supports this DNSSEC architecture.  Since CoreDNS is the most progressed DNS option for Cloud Native architectures, we believe this should be supported.

**Comment by anoncam** [comment]
@miekg I am beginning to agree with the position of using a CSK.  If I were to dispel any perceived security reasons for not using a CSK, where can I start my research to dispel that posture?  I would like to get this policy changed on our end.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Split Key (KS..." ]
>@miekg I am beginning to agree with the position of using a CSK. If I were to
>dispel any perceived security reasons for not using a CSK, where can I start my
>research to dispel that posture? I would like to get this policy changed on our
>end.

Sadly when I (co-) wrote RFC 4641 I also bought into this (key split). The reason it's
there, is we were told if you use RSA to sign, you disseminate a bit of key material. Turns
out this is not true [citation needed] and with elliptic curve is certainly not true
[citation needed], so doing the split (and key rollovers) is an over the top approach to
DNSSEC. Hence the newer thinking of CSK and not rolling your keys, which is also a more
stable approach operationally and one of the reasons it's the only implementation in the
*sign* plugin.

Maybe @FiloSottile can provide a more authoritative answer here.

**Comment by FiloSottile** [comment]
There is no such a thing as leaking key material through signatures, that's correct.

The only reason for a KSK/ZSK split would be if they are kept in separate places, so it's possible for the ZSK to get compromised while the KSK is safe, allowing a ZSK rollover without changing the DS in the parent. That was more of a thing in the before days of offline manual signing, and indeed CSKs make sense for online signing setups like CoreDNS.

**Comment by miekg** [comment]
Thanks for chipping in @FiloSottile, appreciated!

**Comment by anoncam** [comment]
We are not in a position to change this policy.  I am posting this [blog post](https://blog.shebash.io/building-a-cloud-native-dns-server) for context.  Knowing that this is the mountain we would have to climb in order to get the policy changed in our organization, our position remains that this ought to be a feature of CoreDNS.  Federal customers are a large market segment and have needs that do not allow the flexibility to simply change architecture that is handled outside our direct control.  Is this something that can be thought through to achieve widespread adoption within our user base?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Split Key (KS..." ]
>We are not in a position to change this policy. I am posting this blog post for
>context. Knowing that this is the mountain we would have to climb in order to
>get the policy changed in our organization, our position remains that this
>ought to be a feature of CoreDNS. Federal customers are a large market segment
>and have needs that do not allow the flexibility to simply change architecture
>that is handled outside our direct control. Is this something that can be
>thought through to achieve widespread adoption within our user base?

The *sign* plugin does not do keyrollovers, nor the key split, so you will need to write a
plugin that does all that.

**Comment by anoncam** [comment]
@ntwkninja is the key rollover really the problem here?

**Comment by ntwkninja** [comment]
> @ntwkninja is the key rollover really the problem here?

No, this has nothing to do with key rollovers. We need to transfer 'signed zone files'. Specifically, zone files that have been signed with a ZSK in a split key (ZSK/KSK) architecture. There is no expectation or request for the management of keys.

**Comment by ntwkninja** [comment]
> Thanks for chipping in @FiloSottile, appreciated!

Much appreciated @FiloSottile!

**Comment by anoncam** [comment]
> > @ntwkninja is the key rollover really the problem here?
> 
> No, this has nothing to do with key rollovers. We need to transfer 'signed zone files'. Specifically, zone files that have been signed with a ZSK in a split key (ZSK/KSK) architecture. There is no expectation or request for the management of keys.

It appears that this **would** be possible if the way/order of loading plugins on the secondary server handled the `dnssec` plugin differently.

**Comment by miekg** [comment]
Closing this, as the discussion veered into a different area.

On this issue: if you use on-the-fly signing you need to distribute your signing keys to
all your servers. If you can't do that you need off line signing. The option asked for
here is not possible currently and making those changes is a huge undertaking.

/label wontfix
/close
/lock
