### ISSUE TITLE
Error during parsing: unknown property 'max_concurrent'

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#4362]
I'm running into this issue with CoreDNS on a fresh Kubernetes 1.20.1 installation with docker and flannel, the CoreDNS containers are just crash looping with that error in their logs. I'm using the vSphere Cloud Provider I have no other information to provide, if you have any questions or command/outputs you'd like to be to post, don't hesitate to give me a tag. Everything except CoreDNS appears to be functioning.

**Comment by chrisohaver** [comment]
Your cluster is probably running an old version of CoreDNS that doesn't support the `max_concurrent` option.  It was added in 1.6.9.

You can either update the coredns Deployment to use a newer version that supports the option, or remove the option from the coredns ConfigMap.
