### ISSUE TITLE
It fails on DNS resolution name - no such host

### ISSUE THREAD

**Issue by rca0** [coredns/coredns#4366]
Hi there,

I'm having some trouble about DNS resolution with CoreDNS, here are the specifications:

**What happened**:

```console
Post "http://api.prod.domain.local/admin": dial tcp: lookup api.prod.domain.local: no such host
```

This error is intermittent, it happens at least once a day and we are bother about it

![image](https://user-images.githubusercontent.com/38728338/103770565-fc6c9d80-5004-11eb-9b73-f091ef918439.png)

![image](https://user-images.githubusercontent.com/38728338/103770891-83217a80-5005-11eb-9e68-36f5f837b7a7.png)

This graph represents when occur the dns resolution error, after scale one more pod(deployment k8s spec) of CoreDNS, the DNS resolution back to normal

**What you expected to happen**:

DNS Resolution must be done successfully.

**Environment**:

- the version of CoreDNS: v1.6.6
- the CoreDNS is running on AWS-EKS version: v1.15.12-eks-31566f

Note: We already update the k8s components to recommended version. (https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html)
![image](https://user-images.githubusercontent.com/38728338/103770293-81a38280-5004-11eb-8695-882810b4655d.png)
- We are using a domain that is hosted on AWS Route53, everything is inside the AWS Cloud provider
- Corefile:
```console
  Corefile: |
    .:53 {
        autopath @kubernetes
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods verified
          upstream
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        reload
        cache 600
        loadbalance
    }
```

**Comment by chrisohaver** [comment]
Does `/etc/resolv.conf` (on the _nodes_ hosting CoreDNS) contain a mix of DNS servers? For example, a local DNS for handling `domain.local`, and public DNS for handling other domains?  If so, the name would sometimes be resolved by a server on which the domain does not exist.  The fix would be to add a [stub-domain](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns) for `domain.local` that directs queries to the correct DNS.

**Comment by rca0** [comment]
@chrisohaver thanks for your answer 
i've connected on the nodes that are hosting CoreDNS and this are the results:

```bash
[root@ip-172-31-120-153 ~]# cat /etc/resolv.conf
options timeout:2 attempts:5
; generated by /usr/sbin/dhclient-script
search prod.domain.local ec2.internal
nameserver 172.31.0.2
```

testing connection with dns server (172.31.0.2)

```bash
[root@ip-172-31-120-153 ~]# telnet 172.31.0.2 53
Trying 172.31.0.2...
Connected to 172.31.0.2.
Escape character is '^]'.
```

Testing resolution inside the node with dig command line:

```bash
[root@ip-172-31-120-153 ~]# dig api.prod.domain.local +short
traefik.prod.domain.local.
internal-<redacted>.us-east-1.elb.amazonaws.com.
172.31.220.148
172.31.230.253
```

note: The domain `prod.domain.local` is a private type hosted on route53

**Comment by chrisohaver** [comment]
Another _possibility_: 1.7.0 fixed a bug (#3890) that can cause autopath to stop working until CoreDNS restarts. When autopath stops working, the clients fall back to doing the search path themselves which would result in an increase of NXDOMAINs.

Even if this isn't the root cause, I generally recommend using the latest CoreDNS release no matter what version of Kubernetes is used.

**Comment by rca0** [comment]
good catch @chrisohaver!

i'm updating coreDNS to 1.7.0 in my environment and I will observe the result of this update

**Comment by rca0** [comment]
until now the issue has not occurred after i updated coreDNS to version 1.70
@chrisohaver thank you so much for your contribution
