### ISSUE TITLE
Sibling (In-bailiwick rule of RFC 8499) domain IP records can also be returned along with NS records

### ISSUE THREAD

**Issue by SivaKesava1** [coredns/coredns#4377]
**What would you like to be added**:
[RFC 8499 Page 25](https://www.rfc-editor.org/rfc/rfc8499.html): `Glue records for sibling domains are allowed, but not necessary.  For example, a delegation for "child.example.com"  in "example.com" zone may have a "sibling" name server name  "ns.another.example.com".`

More details can be found here:
https://gitlab.isc.org/isc-projects/bind9/-/issues/2384
https://gitlab.isc.org/isc-projects/bind9/-/issues/2385

**Why is this needed**:
Returning the IP records can reduce the number of round-trips by the resolver.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Silbling (In-bail..." ]
>What would you like to be added:
>RFC 8499 Page 25: Glue records for sibling domains are allowed, but not
>necessary. For example, a delegation for "child.example.com" in "example.com"
>zone may have a "sibling" name server name "ns.another.example.com".
>
>More details can be found here:
>https://gitlab.isc.org/isc-projects/bind9/-/issues/2384
>https://gitlab.isc.org/isc-projects/bind9/-/issues/2385
>
>Why is this needed:
>Returning the IP records can reduce the number of round-trips by the resolver.

*file* already searches for in-baliwick glue. Do you have a test case (preferrable actual
golang test case) that does that shows the problem?

**Comment by SivaKesava1** [comment]
Sure, please have a look at the test cases below.

In-bailiwick names are divided into two types of names for name servers: "in-domain" names and "sibling domain" names. [(RFC 8499 Page 25)](https://www.rfc-editor.org/rfc/pdfrfc/rfc8499.txt.pdf#page=25).

- In-domain: a modifier to describe a name server whose name is either subordinate to or (rarely) the same as the owner name of the NS resource records. An in-domain name server name **needs** to have glue records or name resolution fails. For example, a  delegation for `"child.example.com"` may have "in-domain" name server name` "ns.child.example.com."`
- Sibling domain: a name server’s name that is either subordinate to or (rarely) the same as the zone origin and not subordinate to or the same as the owner name of the NS resource records. Glue records for sibling domains are **allowed, but not necessary**. For example, a delegation for `"child.example.com" ` in `"example.com"` zone may have "sibling" name server name `"ns.another.example.com"`.

Coredns follows the In-domain part as per the rule. I was talking about the sibling domain case. _Since it is not a requirement to return those glue records, I have filed it as an enhancement as it can help reduce the round-trips by a resolver._ (Also, other implementations like PowerDNS, Knot, Nsd return those glue records)


|                    |           |                                                          |
|--------------------|-----------|----------------------------------------------------------|
|foo.com        | 500  SOA  | ns1.outside.edu. root.campus.edu. 3 86400 7200 604800 300 |
| foo.com.        | 500  NS   | ns1.outside.edu.                                         |
| foo.com.    | 500 AAAA| 2400:cb00:2049:1::a29f:1804                                          |
| foo.com.  | 500 A     | 1.1.1.1                                        |
| bar.foo.com.        | 500  NS   | foo.com.                                        |
| test.foo.com.  | 500 A     | 2.2.2.2                                        |
| core.foo.com.        | 500  NS   | test.foo.com.                                        |

If the query is `<something.core.foo.com, A>,` then Coredns currently returns the `NS` record, but it can also return the `test.foo.com, A, 2.2.2.2` record as it is a sibling domain for `core.foo.com`. 

Similarly, for the query `<something.bar.foo.com, A>,`  Coredns can return the `A` and `AAAA` records of  `foo.com` (rarely part in the definition of Sibling domain). 

_Thank you for your quick responses._

**Comment by SivaKesava1** [comment]
Hi @miekg,

This issue has been closed as completed, but if I try again, it seems to not return the IP records. Has this been closed as the implementation will not be changed to return the sibling glue records?

Best,
Siva
