### ISSUE TITLE
java.net.UnknownHostException intermittently

### ISSUE THREAD

**Issue by nandeeshb09** [coredns/coredns#4381]
Hi Team,

We are using coredns to resolve our dns queries in EKS cluster which is in AWS cloud.

Facing intermittent issue with unkownhost exception in the application side.

coredns version -- 1.6.6
EKS version -- 1.15

Below is the core file.

apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        reload
        loadbalance
    }

when do we check manually dns resolution on our ec2 worker nodes and its happening fine.

[ec2-user@hostname ~]$ dig api.panel.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.2 <<>> api.panel.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25674
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;api.panel.com.			IN	A

;; AUTHORITY SECTION:
panel.com.		3600	IN	SOA	NS91.WORLDNIC.com. namehost.WORLDNIC.com. 120030309 10800 3600 604800 3600

;; Query time: 44 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Mon Jan 11 13:42:44 UTC 2021
;; MSG SIZE  rcvd: 90

and below are the logs from application for one of the external dns and also same error for internal dns query.

Jan 9 10:40:54 amap-backend-container-analytics-77d85d6cbb-jpmbr amap-backend-container-charts INFO [INFO] [Thread-12349] [com.domain.amap.workgraph.util.panel.MpanelUtils] Sending the panel event failed because of: api.mixpanel.com c.m.amap.workgraph.util.panel.panelUtils
java.net.UnknownHostException: api.panel.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.panel.panelapi.panelAPI.sendData(panelAPI.java:134)
	at com.panel.panelapi.panelAPI.sendMessages(panelAPI.java:172)
	at com.panel.panelapi.panelAPI.deliver(panelAPI.java:103)
	at com.panel.panelapi.panelAPI.deliver(panelAPI.java:83)
	at com.panel.panelapi.panelAPI.sendMessage(panelAPI.java:71)
	at com.domain.amap.workgraph.util.panel.panelUtils.sendWorkflowCompletedMixpanelEvent(panelUtils.java:213)
	at com.domain.amap.workgraph.consumer.WorkflowRunConsumer.lambda$sendAsyncWorkflowCompletedEvent$0(WorkflowRunConsumer.java:230)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.lang.Thread.run(Thread.java:748)

Please suggest here whats went worng.

**Comment by chrisohaver** [comment]
> when do we check manually dns resolution on our ec2 worker nodes and its happening fine.
```
[ec2-user@hostname ~]$ dig api.panel.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.2 <<>> api.panel.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25674
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
```

The response shows no answer (`ANSWER: 0 `).  An application getting this response would not be able to resolve the host.

**Comment by nandeeshb09** [comment]
@chrisohaver Thanks for your responce.

Actual domain is different due to security reasons , have mentioned dummy domain name.

Below is the dig output from amazon.com. and let me know if you need more details.

[ec2-user@hostname ~]$ dig aws.amazon.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.2 <<>> aws.amazon.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54946
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;aws.amazon.com.			IN	A

;; ANSWER SECTION:
aws.amazon.com.		42	IN	CNAME	tp.8e49140c2-frontier.amazon.com.
tp.8e49140c2-frontier.amazon.com. 42 IN	CNAME	dr49lng3n1n2s.cloudfront.net.
dr49lng3n1n2s.cloudfront.net. 42 IN	A	13.32.180.70

;; Query time: 1 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Tue Jan 12 05:06:58 UTC 2021
;; MSG SIZE  rcvd: 126

**Comment by chrisohaver** [comment]
Do you see errors in the CoreDNS logs?

**Comment by nandeeshb09** [comment]
@chrisohaver Dont see any error in the logs and could see only responses in the core dns logs.

If you want I can attach the logs.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] java.net.Unkn..." ]
>@chrisohaver Dont see any error in the logs and could see only responses in the
>core dns logs.

you might add *dump* https://github.com/miekg/dump

this dumps all request when the *hit* coredns, not after they are processed.

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
No errors in the logs suggests that there are no timeouts when forwarding to the upstream nameserver, which can be an issue in AWS/EKS.

> Facing intermittent issue

Does this happen for all domains queried?
Can you categorize how intermittent this is? E.g. approximately 1 in every X queries.

If relatively infrequent, it could be a known cross-node cluster IP routing issue in Kubernetes.  The most common mitigation is to deploy node local DNS cache (where in, a caching tcp dns proxy is added to every node).  If you can see CoreDNS answering NXDOMAIN in the logs for a query that should have an answer, then this probably isn't the root cause.

If somewhat frequent, it could be a that there is a nameserver added to `/etc/resolv.conf` that doesn't know about the domain. Does `/etc/resolv.conf` on the nodes contain more than one nameserver? Caching and record TTLs could affect the frequency of one server's answer being sent to a client vs another.

**Comment by nandeeshb09** [comment]
@chrisohaver Thank you for your response,

Can you categorize how intermittent this is? E.g. approximately 1 in every X queries. --- This issue we are facing at specific time not always and it will be there for half an hour.
Does this happen for all domains queried? -- not all the domains only for some of the domains.

In core dns logs I could see NXDOMAIN for external domains, as because its looking for FQDN.

In /etc/resolv.conf only one nameserver and some times we get timeout for that nameserver in the application logs with specific time.

And how to trouble shoot this whats happening during at that time?

**Comment by chrisohaver** [comment]
> not all the domains only for some of the domains.

Is there anything special or different about the set of affected domains?

> In core dns logs I could see NXDOMAIN for external domains, as because its looking for FQDN.

I don't know what you mean by that. Why would a FQDN query imply an NXDOMAIN response? Can you provide more context?

> And how to trouble shoot this whats happening during at that time?

As @miekg says, you could compile and deploy CoreDNS with the dump plugin.  With that you could manually correlate failure times to the CoreDNS log to see if the queries ever reached CoreDNS.  This would produce a very large log.  You could perhaps keep the size in check by creating server blocks for one of the affected zones, and only adding the dump plugin to that zone.

**Comment by nandeeshb09** [comment]
Is there anything special or different about the set of affected domains? -- no there is no difference.

**I don't know what you mean by that. Why would a FQDN query imply an NXDOMAIN response? Can you provide more context?**
When an application connects to a remote host specified by name, a DNS resolution is performed typically via a syscall, like getaddrinfo(). If the name is not fully qualified (not ending with a .(dot)), will the syscall try to resolve the name as an absolute one first, or will go through the local search domains first? It depends on the ndots option.
From the resolv.conf man:
ndots:n
sets a threshold for the number of dots which must appear in a name before an initial absolute query will be made. The default for n is 1, meaning that if there are any dots in a name, the name will be tried first as an absolute name before any search list elements are appended to it.
This means that if ndots is set to 5 and the name contains less than 5 dots inside it, the syscall will try to resolve it sequentially going through all local search domains first and - in case none succeed - will resolve it as an absolute name only at last.
So that it will not search all the local domains first, and it will directly resolve absolute name and if your application does a lot of external traffic, for each TCP connection established, it will issue 5 DNS queries before the name is correctly resolved, because it will go through the 4 local search domains first and will finally issue an absolute name resolution query and also result into NXDOMAIN.
google.com.ec2.internal
google.com.svc.cluster.local.
google.com.cluster.local
google.com.

Dump thing I will try and let you know.

**Comment by chrisohaver** [comment]
> When an application connects ... FQDN ... not FQDN ... ndots ... finally issue an absolute name resolution query and also result into NXDOMAIN

OK yes I'm quite familiar with that. FYI, for the sake of brevity, in K8s that's called the cluster-first domain search. It's normal behavior.  In your case, it's the final NXDOMAIN response of the absolute name which is what you care about when you are looking in the log for NXDOMAIN responses - not the intermediate queries with the domain attached.

Since you _can_ see NXDOMAINs being returned for the absolute name in the log, it means that CoreDNS received the query, and sent a response to the client (as opposed to the client timing out because CoreDNS never received the requests).  So, correlating dump results probably wont reveal anything other than confirming that.

It seems most likely that CoreDNS is returning NXDOMAIN because the upstream DNS is returning NXDOMAIN.  You could try deploying a pod that tests by querying the upstream DNS directly, and reviewing the results to see if it returns NXDOMAIN intermittently.  If you want to try that, you can use https://github.com/chrisohaver/dnsdrone which can send a low stream of queries directly to the upstream DNS, and export prometheus metrics for later analysis.

**Comment by nandeeshb09** [comment]
@chrisohaver Sure I will check and update here
