### ISSUE TITLE
include coredns-git as a default plugin

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4384]
If there are no objection I like to include coredns-git as a *git* plugin in to coredns. This is a straight port from an old caddy plugin, current coredns code lives here: https://github.com/miekg/coredns-git

I think this is useful, it's a novel plugin *and* it doesn't add a new slew of deps to coredns.

It does need some extra tests to really see if git is pulling.

**Comment by johnbelamaric** [comment]
+1

**Comment by zouyee** [comment]
SGTM

**Comment by miekg** [comment]
See https://github.com/coredns/coredns/pull/4386 please voice concerns (or not there) so it can be merged. ta
