### ISSUE TITLE
How to pass information between plugins?

### ISSUE THREAD

**Issue by fhriley** [coredns/coredns#4397]
I am writing a plugin where the plugin needs information from other plugins. For example, this plugin wants to know if the cache plugin served the response from cache. Another example is it wants to know that if the request was forwarded, what address it was forwarded to. I thought the metadata plugin was for this purpose, but it is the first plugin called in the chain, which means the `Metadata()` method is called before the the other plugins have done anything with the request. Is there any mechanism for doing what I want to do? If not, would there be any opposition to creating it?

**Comment by fhriley** [comment]
So I've got a solution using the `metadata` plugin. It does it similar to how plugins use the `dnstap` plugin. The `forward` and `cache` plugins set their metadata if the `metadata` plugin is installed. However, this doesn't seem to be the way the `metadata` plugin was intended to be used. Is this an acceptable usage?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] How to pass i..." ]
>So I've got a solution using the metadata plugin. It does it similar to the
>dnstap plugin. The forward plugin sets the metatada if the metadata plugin is
>installed. However, this doesn't seem to be the way the metadata plugin was
>intended to be used. Is this an acceptable usage?

Yes, that's a way to solve it. Generally though plugins should not be aware of each other.

**Comment by fhriley** [comment]
Yes, agreed, but the only way for a plugin to report information on a query is for the other plugins to report it. I think the added information only when the metadata plugin is enabled should be minimal.
