### ISSUE TITLE
middleware/proxy: needs tests for https_google 

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#441]
Testing this is awkward, because of the cert stuff - I can only see it being easy with actually going to out <dns.google.com>. This will probably need a new test tag `net`, which means it need internet access.

A failing hermetic test (with something presenting the wrong cert) could (and should!) be done as well.

**Comment by ghost** [comment]
Test by hand or automated?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] middleware/http..." ]
>Test by hand or automated?

automatic. Some of the things that I have i mind:

* wrong cert on the other side (can be with a local webserver)
* backend unresponsive and checking the healthchecking code (can be done
  locally)
* querying google for some info (needs networking and probably a build tag +net
  or something)
