### ISSUE TITLE
CoreDNS 1.8.1 Docker Hub tags missing/outdated

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#4418]
**What happened**:

Due to the multi-arch manifest trouble in the 1.8.1 release, a `1.8.1` tag was not created.  Also, `latest` still points to the 1.8.0 image.
The various single-arch tags do point to 1.8.1, but it's probably not a good idea for people to use those long term, since those will be automatically updated at the next release.

**Comment by bfallik** [comment]
I just stumbled onto this problem as well.

**Comment by christianhuening** [comment]
um... maybe I missed something, but is there going to be a 1.8.1 tag published to docker hub? Or are we supposed to use the single-arch tags for now?

**Comment by sfudeus** [comment]
#4421 suggests that soon there will be 1.8.2 which is in docker hub again.
