### ISSUE TITLE
Unable to upgrade grpc >=v1.30.0

### ISSUE THREAD

**Issue by drewwells** [coredns/coredns#4419]
**What happened**:
Projects importing this code base are unable to upgrade to newer version of grpc. As noted by dependabot, the codebase fails when upgrading grpc https://github.com/coredns/coredns/pull/4402

**What you expected to happen**:
Track upstream issues in etcd for grpc v1.30.0 to remedy this problem or create abstractions so this codebase does not require importing etcd.

**How to reproduce it (as minimally and precisely as possible)**:

```
go get google.golang.org/grpc@v1.35.0
go mod tidy                                                                                                     
...
go: finding module for package google.golang.org/grpc/naming
github.com/coredns/coredns/plugin/etcd imports
        go.etcd.io/etcd/clientv3 tested by
        go.etcd.io/etcd/clientv3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.35.0), but does not contain package google.golang.org/grpc/naming
```

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by drewwells** [comment]
Blocked by etcd-io/etcd#12124

**Comment by miekg** [comment]
this is getting (somewhat) annoying, looks like etcd is making some progress towards fixing this...

**Comment by zouyee** [comment]
https://github.com/coredns/coredns/pull/4093

**Comment by xdu31** [comment]
Hi @drewwells, in 3.5.0-alpha.0 it's using google.golang.org/grpc v1.32.0:
https://github.com/etcd-io/etcd/blob/60d5159091ab06e80ad446ce9e4f415e5f53439e/go.mod#L31

**Comment by drewwells** [comment]
Glad coredns made the leap finally.
