### ISSUE TITLE
How to add external plugin to a kubernetes containerized instance

### ISSUE THREAD

**Issue by reesericci** [coredns/coredns#4423]
I want to add the k8s_gateway plugin to my coredns instance but using kubernetes to manage my coredns. How do I add the external plugin to my instance?

Thanks,
Reese

P.S Enable discussions on github to allow for questions to be distinguished from issues.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] How to add extern..." ]
>I want to add the k8s_gateway plugin to my coredns instance but using
>kubernetes to manage my coredns. How do I add the external plugin to my
>instance?

you have to compile it in https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/

>P.S Enable discussions on github to allow for questions to be distinguished
>from issues.

good point. Done

**Comment by reesericci** [comment]
figured it out, I had to use make instead of go build

**Comment by reesericci** [comment]
migrate this issue to a discussion
