### ISSUE TITLE
Using  a stub domain from Active Directory DNS inside Corefile - intermittent failures

### ISSUE THREAD

**Issue by nscriptdotgo** [coredns/coredns#4427]
Hello, 

I am trying to resolve hostnames that exist in my Active Directory DNS server. I have modified the Corefile to add my stub domain which looks like:
```
Corefile: |-
    .:53 {
        log
        errors
        health {
          lameduck 5s
        }
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        cache 30
        loadbalance
        reload
    }
    mydomain.mycompany.com:53 {
      rewrite stop type AAAA A
      log
      errors
      forward . x.x.x.x y.y.y.y {
          force_tcp
      }
      reload
    }
```

where x.x.x.x is my primary AD DNS server, and y.y.y.y is my secondary DNS server, mydomain.mycompany.com is my AD domain.

I am getting intermittent failures when trying to resolve a resource on my AD hosted domain, lots of NXDOMAIN errors.
Is this the proper way to configure a stub domain in CoreDNS or am I missing something? Thank you

Running kubernetes 1.16.4
CoreDNS 1.6.7

Any help would be greatly appreciated.

**Comment by chrisohaver** [comment]
Is y.y.y.y also an Active Directory DNS server?

**Comment by zouyee** [comment]
> I am getting intermittent failures when trying to resolve a resource on my AD hosted domain, lots of NXDOMAIN errors.
Is this the proper way to configure a stub domain in CoreDNS or am I missing something? Thank you

Could you provide a more detailed log, and confirm whether primary or secondary DNS server is working properly ?

**Comment by nscriptdotgo** [comment]
@chrisohaver Yes y.y.y.y is also an active directory DNS server.

@zouyee sure, if I connect to a pod and run dig for my host. I get the below:
`dig host.mydomain.mycompany.com.

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> host.mydomain.mycompany.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 21558
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;host.mydomain.mycompany.com. IN	A

;; Query time: 0 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Tue Jan 26 16:02:38 UTC 2021
;; MSG SIZE  rcvd: 60`

if I point dig to one of my AD servers to validate that it's resolving, I get a valid response:
`dig @y.y.y.y host.mydomain.mycompany.com.

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> @y.y.y.y host.mydomain.mycompany.com.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63108
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;host.mydomain.mycompany.com. IN	A

;; ANSWER SECTION:
host.mydomain.mycompany.com. 1200 IN A	x.x.x.x
host.mydomain.mycompany.com. 1200 IN A	x.x.x.x
host.mydomain.mycompany.com. 1200 IN A	x.x.x.x
host.mydomain.mycompany.com. 1200 IN A	x.x.x.x

;; Query time: 72 msec
;; SERVER: y.y.y.y#53(y.y.y.y)
;; WHEN: Tue Jan 26 16:05:59 UTC 2021
;; MSG SIZE  rcvd: 124`

and looking at the logs, when it does resolve I see the correct host in the CoreDNS logs:
`[INFO] 100.96.23.111:58399 - 11662 "A IN host.mydomain.mycompany.com. udp 72 false 4096" NOERROR qr,aa,rd,ra 248 0.064048702s`

**Comment by nscriptdotgo** [comment]
I tried upgrading coredns from 1.6.7 to 1.7.0 to see if that helps my issue late yesterday, no luck there.

**Comment by chrisohaver** [comment]
> and looking at the logs, when it does resolve I see the correct host in the CoreDNS logs:
[INFO] 100.96.23.111:58399 - 11662 "A IN host.mydomain.mycompany.com. udp 72 false 4096" NOERROR qr,aa,rd,ra 248 0.064048702s

What is the log entry in CoreDNS for the failures?

**Comment by nscriptdotgo** [comment]
The odd thing is that it does not output anything to the CoreDNS log when I get a failure.

**Comment by nscriptdotgo** [comment]
Well, I think I figured out my problem. Apparently my old kube-dns deployment was scaled back up so it was part of the kube-dns service. After scaling down kube-dns to 0, we are now hitting CoreDNS and it resolves successfully. Thanks for your responses everyone.
