### ISSUE TITLE
coredns log

### ISSUE THREAD

**Issue by Blue-Skies-firststar** [coredns/coredns#4429]
E0126 09:38:10.991053       1 reflector.go:201] github.com/coredns/coredns/plugin/kubernetes/controller.go:251: Failed to list *v1.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: x509: certificate has expired or is not yet valid
E0126 09:38:10.991610       1 reflector.go:201] github.com/coredns/coredns/plugin/kubernetes/controller.go:252: Failed to list *v1.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: x509: certificate has expired or is not yet valid

**Comment by miekg** [comment]
I don't what this is about

/close
/label anonymous
/lock
