### ISSUE TITLE
Fix #4409 in rewrite and other response mutating plugins

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#4432]
Fix the response response mutation issue fixed in #4409 (reverted) in other plugins instead of in _file_.

Assume that any plugin _might_ be returning a response that points to RRs or other structs in the plugin's persistent storage (as file does).  Therefore, any other plugin making changes to a response must make a copy to avoid also mutating the original plugin's  persistent store.

This includes at least rewrite, and perhaps other plugins.

**Comment by miekg** [comment]
To iterate, each of those plugins should just do a `msg.Copy()`.

**Comment by miekg** [comment]
*rewrite* has been fixed. Haven't looked at any other ones....
