### ISSUE TITLE
coredns office-image support mips64le

### ISSUE THREAD

**Issue by stan1334** [coredns/coredns#4434]
**What would you like to be added**:
coredns office-image not support mips64le 
https://hub.docker.com/r/coredns/coredns/tags?page=1&ordering=last_updated&name=1.8

**Why is this needed**:
i found dockfile FROM 
debian:stable-slim office-image support linux/mips64le already
so，i  think, coredns office-image could support mips64le 

See details：
https://hub.docker.com/_/debian?tab=tags&page=1&ordering=last_updated&name=stable-slim

**Comment by yongtang** [comment]
See #4421 which already adds mips64le to docker image build. The next release will have the docker image for mips64le to docker hub.
