### ISSUE TITLE
Allow overriding RA (RecursionAvailable) flag value

### ISSUE THREAD

**Issue by s-matyukevich** [coredns/coredns#4435]
**What would you like to be added**:

Allow uses to specify whether `file` plugin (and probably some other plugins as well) set RA flag or not.

**Why is this needed**:

After https://github.com/coredns/coredns/pull/2408 we no longer set RA flag. However, this breaks our use case: we use CoreDNS as upstream resolver and dmsmasq as a local cache. dnsmasq doesn't cache responses from upstream servers if RA flag is unset. Here is the relevant dnsmasq code snippet

```
  /* Don't put stuff from a truncated packet into the cache.
     Don't cache replies from non-recursive nameservers, since we may get a 
     reply containing a CNAME but not its target, even though the target 
     does exist. */
  if (!(header->hb3 & HB3_TC) && 
      !(header->hb4 & HB4_CD) &&
      (header->hb4 & HB4_RA) &&
      !no_cache_dnssec)
    cache_end_insert();
```

It would be great if we can set the value for this flag in Corefile. for example 

```
.:53 {
    file /some-file {
        reload 30s
        recursion-available true
    }
}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Allow overriding ..." ]
>What would you like to be added:
>
>Allow uses to specify whether file plugin (and probably some other plugins as
>well) set RA flag or not.
>
>Why is this needed:
>
>After #2408 we no longer set RA flag. However, this breaks our use case: we use
>CoreDNS as upstream resolver and dmsmasq as a local cache. dnsmasq doesn't
>cache responses from upstream servers if RA flag is unset. Here is the relevant
>dnsmasq code snippet
>
>  /* Don't put stuff from a truncated packet into the cache.
>     Don't cache replies from non-recursive nameservers, since we may get a
>     reply containing a CNAME but not its target, even though the target
>     does exist. */
>  if (!(header->hb3 & HB3_TC) &&
>      !(header->hb4 & HB4_CD) &&
>      (header->hb4 & HB4_RA) &&
>      !no_cache_dnssec)
>    cache_end_insert();
>
>It would be great if we can set the value for this flag in Corefile. for
>example
>
>.:53 {
>    file /some-file {
>        reload 30s
>        recursion-available true
>    }
>}

I consider this a bug in dnsmasq, it should be smarter then looking a 1 bit and making a
decision.

The *file* plugin isn't providing recursive services so this is WAI. IIRC we do RA when a
*forward* is loaded
