### ISSUE TITLE
CoreDNS requires restart after first deployment

### ISSUE THREAD

**Issue by aceeric** [coredns/coredns#4436]
All - I'm standing up a 3-node cluster (one controller, two workers) on a Ubuntu 20.04.1 LTS desktop host using VirtualBox CentOS 8 guests and bridge networking. This particular host has 12 CPUs and 64 gig of RAM. The approach is modeled after the Hightower k8s the hard way. (Except I'm using kube-router for pod networking, and Vbox/CentOS vs. gcloud/Ubuntu for the nodes). As recommended in various posts, I've disabled `firewalld` for now in all guest VMs.

I create and start the cluster, then create a `dnsutils` pod for troubleshooting. Then:
```
$ kubectl exec -i -t dnsutils -- nslookup kubernetes
Server:		10.32.0.10
Address:	10.32.0.10#53
** server can't find kubernetes: NXDOMAIN
command terminated with exit code 1
```
And the CoreDNS logs don't seem to see this activity:
```
$ kubectl -n kube-system   logs coredns-75c4c67f76-m5n74 -f
.:53
[INFO] plugin/reload: Running configuration MD5 = 98f0bbc9bb3d3c6b2f88ef69f511051d
CoreDNS-1.8.0
linux/amd64, go1.15.3, 054c9ae
[INFO] 127.0.0.1:57945 - 50906 "HINFO IN 6270127637058920514.4349600810579566757. udp 57 false 512" NXDOMAIN qr,rd,ra 132 0.055544143s
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
I0130 02:42:43.746474       1 trace.go:205] Trace[1427131847]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (30-Jan-2021 02:42:13.746) (total time: 30000ms):
Trace[1427131847]: [30.000382545s] [30.000382545s] END
E0130 02:42:43.746504       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get "https://10.32.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.32.0.1:443: i/o timeout
I0130 02:42:43.747075       1 trace.go:205] Trace[911902081]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (30-Jan-2021 02:42:13.746) (total time: 30000ms):
Trace[911902081]: [30.000220499s] [30.000220499s] END
E0130 02:42:43.747086       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.32.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.32.0.1:443: i/o timeout
I0130 02:42:43.747387       1 trace.go:205] Trace[1474941318]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (30-Jan-2021 02:42:13.747) (total time: 30000ms):
Trace[1474941318]: [30.000269017s] [30.000269017s] END
E0130 02:42:43.747396       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.32.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.32.0.1:443: i/o timeout
```
After the last timeout the logs go completely quiet.

Even though `nslookup kubernetes` fails, this succeds:
```
$ kubectl exec -i -t dnsutils -- nslookup google.com
Server:		10.32.0.10
Address:	10.32.0.10#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.5.238
Name:	google.com
Address: 2607:f8b0:4004:804::200e
```
But no record of this activity in the logs. If I do **nothing more** than scale the CoreDNS deployment:
```
kubectl -nkube-system scale deploy coredns --replicas=0; kubectl -nkube-system scale deploy coredns --replicas=1
```
Then as soon as the pod is running:
```
$ kubectl exec -i -t dnsutils -- nslookup kubernetes
Server:		10.32.0.10
Address:	10.32.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.32.0.1
```
Succeeds!

And the CoreDNS logs:
```
$ kubectl -n kube-system   logs coredns-75c4c67f76-zh767 -f
.:53
[INFO] plugin/reload: Running configuration MD5 = 98f0bbc9bb3d3c6b2f88ef69f511051d
CoreDNS-1.8.0
linux/amd64, go1.15.3, 054c9ae
[INFO] 127.0.0.1:47556 - 23893 "HINFO IN 3978360366552485432.4584456493141950666. udp 57 false 512" NXDOMAIN qr,rd,ra 132 0.048072459s
[INFO] 10.200.1.2:54673 - 32681 "A IN kubernetes.default.svc.cluster.local. udp 54 false 512" NOERROR qr,aa,rd 106 0.000557074s
[INFO] 10.200.1.2:58111 - 41073 "AAAA IN kubernetes.default.svc.cluster.local. udp 54 false 512" NOERROR qr,aa,rd 147 0.000315671s
```

This is my entire `coredns.yaml`:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - namespaces
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4 {
          tls_servername dns.google
        }
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: "CoreDNS"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: coredns
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 100
             podAffinityTerm:
               labelSelector:
                 matchExpressions:
                   - key: k8s-app
                     operator: In
                     values: ["kube-dns"]
               topologyKey: kubernetes.io/hostname
      containers:
      - name: coredns
        image: docker.io/coredns/coredns:1.8.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.32.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
```
Any help is appreciated. It seems odd that just cycling the deployment would resolve it. Thanks

**Comment by aceeric** [comment]
In addition to the info provided above, I would also like to add that this behavior occurs each time I start the cluster. So if I shut down all the nodes, then re-start the nodes - the exact same thing happens: CoreDNS does not seem to start successfully, so I scale the deployment down and up and then everything is fine.

**Comment by johnbelamaric** [comment]
Looks pretty clear to me that for some reason CoreDNS is giving up
connecting to the API server after a while, rather than
continuously retrying. That's something that needs to be investigated. You
could work around it in the meantime by changing your liveness probe to do
a real query and fail if there is no response. That will force k8s to
restart it after the failures.

**Comment by aceeric** [comment]
I will try that. What seems strange to me is that - on initial start - the timeouts begin immediately and never resolve. But on the restart - there are no timeouts at all. So it's almost like CoreDNS is changing the state of the cluster in a way that it cannot take advantage of until it is restarted. Like - it modifies etcd through the API server but doesn't detect the fact that the state change was successful, then when you restart it - the cluster state change has already taken effect and so it proceeds fine

**Comment by johnbelamaric** [comment]
Coredns is read only on the apiserver

**Comment by chrisohaver** [comment]
> CoreDNS is giving up connecting to the API server after a while, rather than continuously retrying 

CoreDNS used to try forever before starting the server.  IIRC, that changed at some point (for sake of bootstrapping scenarios?), so that after some time it lets the server start, but (should) continue trying to connect in a go routine. Possibly broken at some point? It seems like something that could be in the hard-to-unit-test-and-therefore-isnt-tested category.

> work around it in the meantime by changing your liveness probe to do a real query and fail if there is no response

Pointing the liveness probe to the `/ready` endpoint may also work, since when the API is not synced, it _should_ be failing. (before the health/ready plugin split, the health endpoint would fail when the API was unsynced, which would cause coredns pods to get killed and respawned if they could not connect to the API after too long)

**Comment by aceeric** [comment]
Just as an additional piece of info: setting the liveness probe to the ready endpoint had no effect. Therefore, it seems readiness is reporting "Ready" even when the server is not ready. So far - the only resolution is to restart the pod.

**Comment by zouyee** [comment]
The reproduction steps may be as follows:
1. Deploy coredns on ip1 node (export KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT)
`./coredns --conf ./Config`
2. Query service nginx is work well
```
nslookup nginx.default.svc.cluster.local xxx
Server:		xxx
Address:	xxx#53

Name:	nginx.default.svc.cluster.local
Address: yyy
```
3. Use iptables on the master node ip2 to reject access from ip1
`iptables -A INPUT -p tcp --dport 6443 -j REJECT --reject-with tcp-reset -s ip1`

4. At the same time, create a test service and perform domain name query
`ngs          ClusterIP      10.233.12.65    <none>        80/TCP         3s`

**5. Query the ready interface on the ip1 node**, the result is not as expected
`curl http://127.0.0.1:8181/ready
OK`
~6. Go back to the master node and delete the iptables rules~
~`iptables -D  INPUT -p tcp --dport 6443 -j REJECT --reject-with tcp-reset -s ip1`~
~7. Query the domain name of the test service~
```
nslookup ngs.default.svc.cluster.local xxx
Server:		xxx
Address:	xxx#53

** server can't find ngs.default.svc.cluster.local: NXDOMAIN
```
~8. restart coredns, then query `ngs` service~
~work well~

**Comment by oldthreefeng** [comment]
I have same issue with you on ubuntu server.  @aceeric . may this help you
```
$ uname  -a
Linux louis-master 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
``` 
the coredns error logs is 
```
 $ kubectl logs -n kube-system coredns-74ff55c5b-zfcmk 
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
[ERROR] plugin/errors: 2 1598332292965093750.624098100158056236. HINFO: read udp 100.118.245.2:54979->192.168.60.2:53: i/o timeout
[ERROR] plugin/errors: 2 1598332292965093750.624098100158056236. HINFO: read udp 100.118.245.2:46007->192.168.60.2:53: i/o timeout
[ERROR] plugin/errors: 2 1598332292965093750.624098100158056236. HINFO: read udp 100.118.245.2:49949->192.168.60.2:53: i/o timeout
```

i found my cni is not ready . from logs 
```
$ kubectl logs -n kube-system calico-node-ztj6d --tail 20 
[FATAL][623] int_dataplane.go 1018: Kernel's RPF check is set to 'loose'.  This would allow endpoints to spoof their IP address.  Calico requires net.ipv4.conf.all.rp_filter to be set to 0 or 1. If you require loose RPF and you are not concerned about spoofing, this check can be disabled by setting the IgnoreLooseRPF configuration parameter to 'true'.

```

when  set rp_filter to 0, and restart coredns and calico. the cluster return health. 

```
$ sysctl -w net.ipv4.conf.all.rp_filter=0

$ kubectl delete pod -n kube-system coredns-74ff55c5b-26str coredns-74ff55c5b-9gj9m calico-node-ztj6d calico-kube-controllers-69b47f4dfb-pllhx 
$  kubectl get pod --all-namespaces 
NAMESPACE     NAME                                       READY   STATUS        RESTARTS   AGE
kube-system   calico-kube-controllers-69b47f4dfb-lh4t9   1/1     Running       0          25s
kube-system   calico-kube-controllers-69b47f4dfb-pllhx   0/1     Terminating   0          3m54s
kube-system   calico-node-hf2vg                          1/1     Running       0          25s
kube-system   coredns-74ff55c5b-85wtt                    1/1     Running       0          25s
kube-system   coredns-74ff55c5b-hscnq                    1/1     Running       0          25s
kube-system   etcd-louis-master                          1/1     Running       0          4m7s
kube-system   kube-apiserver-louis-master                1/1     Running       0          4m7s
kube-system   kube-controller-manager-louis-master       1/1     Running       0          4m7s
kube-system   kube-proxy-ngxnw                           1/1     Running       0          3m54s
kube-system   kube-scheduler-louis-master                1/1     Running       0          4m7s
$  kubectl logs -n kube-system coredns-74ff55c5b-85wtt
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
```

**Comment by aceeric** [comment]
Thank you @oldthreefeng. I realized this as well and introduced a wait step after networking is deployed and before deploying CoreDNS. However, I think it would be an improvement for CoreDNS not to report Ready in this case. Then Kubernetes could re-start it after the ready timeout and it would heal itself.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] CoreDNS requi..." ]
>Thank you @oldthreefeng. I realized this as well and introduced a wait step
>after networking is deployed and before deploying CoreDNS. However, I think it
>would be an improvement for CoreDNS not to report Ready in this case. Then
>Kubernetes could re-start it after the ready timeout and it would heal itself.

making anything external an input for the ready state of the coredns process is setting
yourself up for a (awesome?) cascading failure.

**Comment by aceeric** [comment]
Since CoreDNS never successfully started to begin with, I'm not sure a cascade is possible in this instance by restarting it. The probe is configurable in the yaml. As the one configuring the manifest - including the probe - as long as the probe accurately reports readiness then I can configure the probe to ignore that if I'm worried about a cascade, or honor it. But as it stands, the software has removed that option by always reporting ready. By analogy: assume a database pod starts up - but "an external input" - that being its persistent storage - is unavailable. If I understand the perspective, it would be correct for the database to report ready to the cluster and begin accepting client connections. Respectfully - I guess there's room for dissenting viewpoints.
