### ISSUE TITLE
plugin/hosts: add support for multiple hosts files (glob or directory)

### ISSUE THREAD

**Issue by UiP9AV6Y** [coredns/coredns#4437]
**What would you like to be added**:

the *hosts* plugin can only be used once per server block and supports only a single file path.
we have multiple files that change at different rates by different providers. creating dedicated
server sections and combining them with a chained forwarder is not feasable.

**Why is this needed**:

we have multiple services which generate their own service discovery. to avoid conflicts, each
of them writes their own file.

**Possible implementations**:

i can provide a PR, but i would like to collect some feedback on the implementation approach first.

### globs

```
. {
    hosts /run/service-registry/*.txt
}
```

sanitizing and validating input is done during setup. if we keep the current approach, this would
also cause the glob to expand during startup. as a result file added at a later point would be missed.
this can be worked around by expanding the glob on demand with the drawback that the setup
can no longer validate the input correctly. on the plus side, this would be the most intuitive solution
for users and allows filtering.

### directory as input

```
. {
    hosts /run/service-registry/
}
```

going down this path would only require little adaptations to the setup code (remove the [IsDir()](https://github.com/coredns/coredns/blob/028f0eb33178612a14bba14b95040f4831f363d9/plugin/hosts/setup.go#L104) check).
the [Hostsfile](https://github.com/coredns/coredns/blob/028f0eb33178612a14bba14b95040f4831f363d9/plugin/hosts/hostsfile.go#L101) struct has to be altered to store a `map[string]os.FileInfo` (or a custom implementation storing only the modtime and size)
the downside of this approach is the lack of filtering as the plugin would load all files in the given directory.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] plugin/hosts: add..." ]
>the hosts plugin can only be used once per server block and supports only a
>single file path.
>we have multiple files that change at different rates by different providers.
>creating dedicated
>server sections and combining them with a chained forwarder is not feasable.

Why wouldn't the *auto* plugin be good enough then?

This goes way beyond what the *host* plugin provides and duplicating *auto* into *host*
This is not how we want plugins to be.

>we have multiple services which generate their own service discovery. to avoid
>conflicts, each
>of them writes their own file.

without knowing the details it would seem to me that it should be possible to merge these
into one file and provide that to the *host* plugin.

**Comment by UiP9AV6Y** [comment]
we have multiple production environments and just as many staging environments. currently our testers fetch the list of services from the prod environment, add the ip address of the associated staging environment to each service FQDN and put the result into their local /etc/hosts file. this somewhat works with desktop machines but becomes cumbersome with mobile devices. we would like to provide a DNS server which resolves production FQDN with staging addresses. since those are all just *A* records and because testers used to modify their /etc/hosts file, we decided to stick with that syntax (it makes transitioning easier). our idea was to re-generate the hosts files whenever an environment changes.
yes, we could render a zone file which contains only A records, but since we already have the hosts-file we wanted to keep it.
yes, we could cache and aggregate the files prior to reloading coredns, but that would require another system as our current solution only works on a per-environment basis.

**Comment by miekg** [comment]
Closing this for reasons sketched out. Seems entirely possible to use existing code or do
this outside of coredns

/close
