### ISSUE TITLE
Where to find the Dockerfile for https://hub.docker.com/r/coredns/coredns & how to use it?

### ISSUE THREAD

**Issue by spacewander** [coredns/coredns#4438]
There is an official docker image in docker hub: https://hub.docker.com/r/coredns/coredns.
However, I can't find any relative Dockerfile in CoreDNS's projects. The closest I have found is https://github.com/coredns/multicluster-dns/blob/644dd7672ee96dbeb7408e0117702841706e634c/Dockerfile, but I am not sure if it is.

And there is not description for the official image. How do people use it?

**Comment by miekg** [comment]
https://raw.githubusercontent.com/coredns/coredns/master/Dockerfile

/close
/lock
