### ISSUE TITLE
docker/official-images support corends image

### ISSUE THREAD

**Issue by stan1334** [coredns/coredns#4439]
**What would you like to be added**:
docker/official-images support corends image

**Why is this needed**:
mips docker/official-images include corends project

communication details：
https://github.com/docker-library/official-images/issues/9534

docker/official-images  Official reply：
They agree to add new items and submit a PR

@yongtang
@miekg

**Comment by miekg** [comment]
See #4418 and #4421

/label duplicate
/close
/lock
