### ISSUE TITLE
Add fallthrough support to file plugin

### ISSUE THREAD

**Issue by 0xMH** [coredns/coredns#4444]
**What would you like to be added**:

- Add fallthrough support to file plugin

**Why is this needed**:

I tried to use the `file` plugin for creating a local dns zone which
should get precedence over its public zone. 

So, Suppose there's a public hosted zone on AWS for `public.example.io` domain
which have these records:

```
esxi-1.public.example.io.   IN  A   10.10.1.101
esxi-2.public.example.io.   IN  A   10.10.1.102
esxi-3.public.example.io.   IN  A   10.10.1.103
esxi-4.public.example.io.   IN  A   10.10.1.104
```

Now suppose I want to override just the first 2 records from within my local CoreDNS, 
So If any of my servers who use CoreDNS as their primary DNS tried to resolve 
these domains they get:

```
esxi-1.public.example.io.  10.10.1.55
esxi-2.public.example.io.  10.10.1.56
```

Now I managed to do that easily by using the file plugin and create my local zone.
But the current problem is that servers can't resolve the others
two domains (`esxi-3` & `esxi-3`) at all, They get an empty response. 
And that's expected because fallthrough isn't supported.

As a work around I used the hosts plugin and I managed to 
create this scenario and get it to work 
but I prefer using the file plugin due to its flexibility. 

So to handle this use case something like this should work:

```
53 {
    forward . 8.8.8.8 1.1.1.1
    log
    errors
}

public.example.io:53 {
    file /root/public.example.io.db
    log
    errors
    fallthrough
    forward . 8.8.8.8 1.1.1.1
}
```

**Comment by miekg** [comment]
fallthrough is a DNS hack that we want to use sparingly. I'm not going to change anything in the file plugin to make this work.
you probably need to setup a proper DNS delegation tree to make this work.
