### ISSUE TITLE
Enforce server side MaxUDPSize

### ISSUE THREAD

**Issue by chantra** [coredns/coredns#4449]
**What happened**: Currently, the maximum size of an answer is informed by the client's accepted Bufsize (or optionally clamped by the bufsize plugin)

**What you expected to happen**:
The request UDP Size is only a signal of how much a client is willing to receive, but it should not be dictating how big an answer a server should send.
The server should be able to configure a MaxUDPSize value and the max answer size, for UDP should be:

```
max(MinUDPSize, min(ServerMaxUDPOutSize, client.UDPSize))
```
where client.UDPSize defaults to MinUDPSize if EDNS is not set.

**Anything else we need to know?**:

When Scrubbing the reply:
https://github.com/coredns/coredns/blob/03812bb1e7ec6af384976bc4a9fb22f054dece89/request/request.go#L220-L221)
The message is truncate to request.Size() size. This size is computed by looking at the client's request accepted bufsize, and then normalize.
https://github.com/coredns/coredns/blob/03812bb1e7ec6af384976bc4a9fb22f054dece89/request/request.go#L167-L174

This has the effect that if a client send a Bufsize of 4k, the server will reply up to 4k.

I am aware of the `bufsize` plugin, but I would argue it does not do the job, albeit there may be ways to change it in a way that make it compatible.

For one, the `bufsize` plugin adds EDNS when there is no EDNS. This is wrong for 2 reasons IMO:
- if there were no EDNS in the request, we should not add EDNS in the reply ([RFC6891 Section 7](https://tools.ietf.org/html/rfc6891#section-7)
> Lack of presence of an OPT record in a request MUST be taken as an
   indication that the requestor does not implement any part of this
   specification and that the responder MUST NOT include an OPT record
   in its response.
- by default, this would mean that the client accepts max 512, for any value of bufsize > 512, we would now possibly return payload bigger than accepted by the client.

If EDNS is set, the plugin may allow for a bigger payload than accepted by the requester (say requester allow 512, and we clamp to 1024, 1024 is now going to be the payload size allowed).

**Proposed solution**:

`Scrub` and `Size` being request methods, we somehow need to set the maximum UDP size as part of the request struct.

A possible solution would be to have a new attribute in the `Request` struct, say `MaxUDPSize`. The `ScrubWriter` could then set that value to whatever the server policy is willing to do when created the request object: https://github.com/coredns/coredns/blob/7339235de1663cd2cabb4e1f90b18eabcb799a65/request/writer.go#L17

`bufsize` plugin could then set this value instead e.g `w.MaxUDPSize = uint16(bufsize)`

**Considerations**:

* this MaxUDPSize should probably have a sane default. I would be tempted to go with [DNSFlagDay 2020](https://dnsflagday.net/2020/) values, but for backward compatibility, it is probably better to use 4096?
* MaxUDPSize == 0 would need to be handled by whichever sane default previously chosen.
* We may be willing to have a separate size for IPv4 and IPv6
* If the intent of `bufsize` was to set the max UDP payload the server was willing to receive, then this would not work as expected.

** Further considerations**:

Setting the response EDNS size to the request EDNS size is still not correct, but I view this more as cosmetic than a practical problem (based on my use-case), but the responder EDNS bufsize should reflect what the server is willing to accept as a UDP payload sent their way, typically for UPDATE for instance.

[RFC6891 Section 6.2.4](https://tools.ietf.org/html/rfc6891#section-6.2.4):
> The responder's maximum payload size can change over time but can
   reasonably be expected to remain constant between two closely spaced
   sequential transactions, for example, an arbitrary QUERY used as a
   probe to discover a responder's maximum UDP payload size, followed
   immediately by an UPDATE that takes advantage of this size.  This is
   considered preferable to the outright use of TCP for oversized
   requests, if there is any reason to suspect that the responder
   implements EDNS, and if a request will not fit in the default
   512-byte payload size limit.
   
   So likely, when calling `SizeAndDo` https://github.com/coredns/coredns/blob/03812bb1e7ec6af384976bc4a9fb22f054dece89/request/request.go#L191, this value should probably also be set to a server controlled value, similar to this bug report. And it could also probably be handled by the bufsize plugin.
   I am happy to open a separate issue for that though.

**Comment by chantra** [comment]
BTW, happy to provide a patch to this, but would like to first come up with a satisfiable solution which make sense for both CoreDNS and users of the github.com/coredns/coredns/request package.

**Comment by miekg** [comment]
I'm unsure if this is needed. When are replies so big that we fill up the (large) buffer
size? And if you have those large replies you may actually want to be able to serve them
over udp

**Comment by chantra** [comment]
@miekg I suppose large is subjective. One may consider large anything over 512, 1232 or whatever they may decide.

As it is, large is essentially decided by what the client sends in edns0, not by the server.

> And if you have those large replies you may actually want to be able to serve them over udp

Sure, or you may want to force them over TCP to prevent being used as an amplification vector. The `bufsize` plugin is kind of addressing this but I think there is a few rough edges which I tried to explain  when I opened this issue.

**Comment by chantra** [comment]
@miekg checking back on this one. Do you see any other ways to make sure that the server controls the maximum size it is willing to send out, and not the client?

The bufsize plugin could possibly be modified to handle this and be RFC if it was not adding EDNS when it is not present in the first place and only setting the new UDP Size if requested size > bufsize config.
This would work, albeit it would still not differentiate between client EDNS0 bufsize (what a client is willing to receive in a response), and server EDNS0 bufsize (what a server is willing to receive during a request for stuff like UPDATEs and such).

**Comment by chantra** [comment]
@miekg #4464 should illustrate the change that I had in mind to prevent sending UDP messages where the max size if driven by the client.
This does not address the fact that the response's bufsize mirrors the client's. But I think this can easily be address by bufsize as is.

**Comment by miekg** [comment]
when do you send replies this big?

I'm hesitant for this change because there is no RFC mandating it. I'm welcoming this change because of self preservation. But if you have an actual use-case for this I think it should be OK (this disregards any UDP fragmentation, which is another can of worms)

**Comment by chantra** [comment]
Thanks @miekg ,

> I'm hesitant for this change because there is no RFC mandating it.

Correct, this is not something mandated by RFC, [RFC2671](https://tools.ietf.org/html/rfc2671) is rather vague on this subject, the security consideration section talks about ICMP storm, but that is about it. The meaning of responder's UDP size is also not very clear, it is explained in [rfc2671#section-4.5.4](https://tools.ietf.org/html/rfc2671#section-4.5.4). I think this [KB from ISC](https://kb.isc.org/docs/aa-01350) does a good job at explaining the common misunderstanding:

> What's in a Query Response?
If you have been testing servers using dig or monitoring DNS queries and responses with packet tracing, you will have observed that servers also advertise an EDNS buffer size when they respond to clients. Intuitively you might expect them to be advertising the maximum payload they can respond with to a client. This would be incorrect! What they are advertising is the maximum size they can receive as a client. There is a good reason for this - and that is to provide a mechanism by which a client about to send a dynamic UPDATE to a server can test to find out the acceptable size limit beforehand by using a trivial QUERY - otherwise there is no other mechanism by which this can be determined. This is covered in section 4.5.4 of RFC 2671

I think in the end, the client is basically **_signaling_** that it can receive up to `bufsize`, but nothing mandates that the server uses this value, and if it cannot fit in what the server can handle to serve out, it will then truncate per RFC1035.

 
> I'm welcoming this change because of self preservation. 

Yes, this is exactly what it is. Well, self-preserving as well as preserving others from big answers via reflection/amplification :).

> But if you have an actual use-case for this I think it should be OK

The main use case is that for 99.99% of the cases, we reply small answers (typically something below 100 bytes), but there is always some answers that may be bigger (typically due to a mixture of TXT records used for a variety of reasons: site validations, SPF...), possibly ANY if one does not wish to apply [RFC8482](https://tools.ietf.org/html/rfc8482), `dig any cpsc.gov +notcp @one.of.its.nameserver` is currently returning 3.3k answers, which seems [better than what it used to be](https://blog.cloudflare.com/how-the-consumer-product-safety-commission-is-inadvertently-behind-the-internets-largest-ddos-attacks/)).
Those large answers can be used as a mean to run reflection/amplification attacks. The smaller the answer (over UDP), the least attractive to this type of attacks.
Forcing legitimate client to perform those rare queries over TCP is fine.

Controlling what people put in the DNS, while gated, can be tricky, even more so when automation comes into play. Being able to enforce administratively  at the server level the maximum size of UDP packets to be sent out ensures that whatever may end up in the zone, the abuse is limited.

Other authoritative servers have something similar implemented: [PowerDNS's udp-truncation-threshold](https://doc.powerdns.com/authoritative/settings.html#udp-truncation-threshold), [Bind's max-udp-size](https://bind9.readthedocs.io/en/latest/reference.html?highlight=max-udp-size#tuning), [Knot's udp-max-payload](https://www.knot-dns.cz/docs/2.9/html/reference.html#udp-max-payload) (formerly max-udp-payload), and I believe [NSD's ipv{4,6}-edns-size](https://www.nlnetlabs.nl/documentation/nsd/nsd.conf/#ipv4-edns-size), and I think the PR associated with this issue is how one would support DNS flagday 2020.

**Comment by chantra** [comment]
@miekg what do you think about this PR? Anything that need to be changed?

**Comment by chantra** [comment]
Hi folks,

Checking back to see what the opinion is on this issue/PR? Anything in #4464 that would need to be changed?

Thanks

**Comment by miekg** [comment]
No I'm not willing to make this change, as coredns is probably used in a lot of whacky settings where it provides SD for some internal network. A max buffer can fit 1500 SRV records if you have those SD requirements there is no need to impose an arbitrary maximum. For an internet facing setup you should just not do this.

**Comment by chantra** [comment]
Thanks for explaining the reasoning here @miekg .

Would making the default 4096, as commented in https://github.com/coredns/coredns/pull/4464#pullrequestreview-589789205 , be a reasonable tradeoff? Or do you think there is enough chances that people have purposefully set their client's Bufsize greater than 4096?
This would probably provide the backward compatibility needed while giving an opportunity to control the max size from the server side if one wishes to.
Alternatively, default (e.g 0) could be considered an unrestricted (current behaviour), and again, leaving an opportunity on the server side to clamp the max size if needed.
