### ISSUE TITLE
Could not resolve host: www.google.com

### ISSUE THREAD

**Issue by fluidjeel** [coredns/coredns#4455]
Facing issues with K8s coredns:

nslookup fails from any pod to www.google.com

resolv.conf has the following config:
```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local ec2.internal
options ndots:5
```

clusterDNS in ` /var/lib/kubelet/config.yaml ` looks to be pointing to ` 10.96.0.10 `

What value should ` clusterDNS ` point?
```
ubuntu@ip-10-16-102-208:~$ kubectl get svc -n kube-system
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   46m
```

```
coredns-56d6f8854c-gkj4d                   1/1     Running   0          25m    192.168.227.203   ip-10-16-102-189   <none>           <none>
coredns-56d6f8854c-jrxnm                   1/1     Running   0          25m    192.168.44.138    ip-10-16-102-88    <none>           <none>
```

Endpoints are fine
```
ubuntu@ip-10-16-102-208:~$ kubectl get ep kube-dns --namespace=kube-system
NAME       ENDPOINTS                                                        AGE
kube-dns   192.168.49.69:53,192.168.49.70:53,192.168.49.69:53 + 3 more...   45m

```

Cluster was provisioned using kubeadm with calico
```
sudo kubeadm init --pod-network-cidr=192.168.0.0/16
```

**Comment by chrisohaver** [comment]
Have you run through [k8s' dns troubleshooting steps](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/)?

**Comment by fluidjeel** [comment]
@chrisohaver calico latest seems to be a compatible with ubuntu16.04. i had issues with 18 n above Ubuntu version. The 18 n above version work well with v3.11 manifest of calico

**Comment by fluidjeel** [comment]
After repeated n exhaustive testing i can confirm the latest calico manifest under quick start doesn't work well will ubuntu versions 18 n up. (AWS standard AMIs t2.large )

If we use the old version of calico manifest it works fine.
https://docs.projectcalico.org/manifests/tigera-operator.yaml

@chrisohaver  this is potentially a bug

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Could not res..." ]
>After repeated n exhaustive testing i can confirm the latest calico manifest
>under quick start doesn't work well will ubuntu versions 18 n up. (AWS standard
>AMIs t2.large )
>
>If we use the old version of calico manifest it works fine.
>https://docs.projectcalico.org/manifests/tigera-operator.yaml
>
>@chrisohaver this is potentially a bug

please file this at the appropiate bug tracker, this has nothing to do with coredns

/close
