### ISSUE TITLE
i/o timeout after bad DNS requests

### ISSUE THREAD

**Issue by jgoeres** [coredns/coredns#4470]
This issue was originally filed with the minikube project (see https://github.com/kubernetes/minikube/issues/10280), since it appears like CoreDNS is involved, I am reporting it here as well.

In the workload that I deployed, there was a job that amongst other things did a "curl" command. A change in its parametrization triggered a bug in the job script that would cause curl to try to curl from several non-existing hostnames. We have our own retry logic in that job (since Kubernetes retries have quite inflexible retry behaviour with long and quickly rising backoff intervals), so that the failed curl would be retried once every second. The container running that job is one of the smaller ones, so it would usually be among the first to actually reach running state, which explains why only some of the other pods would reach running (all those were the DNS lookup had already been done), while most would not.

To reproduce the issue, I created a simple script and docker image:

killDns.sh

    #!/bin/bash
    
    if [[ $1 == "kill" ]]; then
      while [[ true ]]; do
         curl foo bar givesitnot
         sleep 1
      done
    elif [[ $1 == "check" ]]; then
    
      while [[ true ]]; do
         nslookup google.de | ts
         sleep 1
      done
    else
      echo "Bad command, use \"kill\" to try to kill DNS, use  \"check\" to test if lookups still work."
      exit 1
    fi

Dockerfile

    FROM alpine:3.12.3
    ADD killDns.sh /
    RUN apk update && \
        apk add \
            curl \
            bash \
            moreutils
    ENTRYPOINT [ "/killDns.sh"]
    CMD [ "check" ]

Put these two files in an otherwise empty dir. Open your favorite shell in that directory and use "minikube docker-env" to let your docker CLI talk to the docker daemon in the minikube VM, e.g., on bash shell, run

    eval $(minikube docker-env)

Build it with

    docker build -t dnskiller:0.0.1 .

Now open another shell (and do minikube docker-env in it)
and run the image as plain docker container like this

    docker run --rm --name dnschecker -it dnskiller:0.0.1 -- check

This will give you the output of a suuccessful nslookup for an existing hostname every second:

    Feb 11 08:10:32 Server:         10.0.2.3
    Feb 11 08:10:32 Address:        10.0.2.3:53
    Feb 11 08:10:32
    Feb 11 08:10:32 Non-authoritative answer:
    Feb 11 08:10:32 Name:   google.de
    Feb 11 08:10:32 Address: 173.194.73.94
    Feb 11 08:10:32
    [...]

No run the image as plain docker container like this:

    docker run --rm --name dnskiller -it dnskiller:0.0.1 -- kill

This will now do the curl command against a bunch of non-existing hostnames - also once every second:

    $ docker run --rm --name dnskiller -it dnskiller:0.0.1 kill
    curl: (6) Could not resolve host: foo
    curl: (6) Could not resolve host: bar
    curl: (6) Could not resolve host: givesitnot
    curl: (6) Could not resolve host: foo
    [...]

Leave both containers running for a while and keep an eye on the output of the dnschecker container... and you will see that both continue to run just fine, the "dnskiller" with failing curl commands, the "dnschecker" with successful nslookups.

Stop the dnskiller container.
Next, in another shell, follow the logs of the coreDNS pod in minikube with

    kubectl logs -n kube-system coredns-<THE_NAME_OF_YOUR_CORE_DNS_POD> -f

Now run the "dnskiller" again, but this time inside Kubernetes:

    kubectl run dnskiller -it --image dnskiller:0.0.1 -- kill

Again, keep an eye on the output of the dnschecker container - it will only take a few seconds to give you

    Feb 10 09:56:39 ;; connection timed out; no servers could be reached

At the same moment, CoreDNS will start logging error messages:

    [ERROR] plugin/errors: 2 foo. A: read udp 172.17.0.2:59806->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 foo. A: read udp 172.17.0.2:39949->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 bar. AAAA: read udp 172.17.0.2:48435->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 bar. A: read udp 172.17.0.2:51295->10.0.2.3:53: i/o timeout
    [...]
    [ERROR] plugin/errors: 2 givesitnot. AAAA: read udp 172.17.0.2:52102->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 givesitnot. A: read udp 172.17.0.2:58473->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 givesitnot. AAAA: read udp 172.17.0.2:39532->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 givesitnot. A: read udp 172.17.0.2:35336->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 givesitnot. A: read udp 172.17.0.2:38487->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 givesitnot. AAAA: read udp 172.17.0.2:51494->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 givesitnot. AAAA: read udp 172.17.0.2:47124->10.0.2.3:53: i/o timeout
    [...]
    [ERROR] plugin/errors: 2 foo. A: read udp 172.17.0.2:59186->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 foo. AAAA: read udp 172.17.0.2:56560->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 foo. A: read udp 172.17.0.2:42531->10.0.2.3:53: i/o timeout
    [ERROR] plugin/errors: 2 foo. AAAA: read udp 172.17.0.2:42847->10.0.2.3:53: i/o timeout
    [...]

Stopping the "dnskiller" pod will eventually stop these log messages. However, any DNS lookups (like those done by the "dnschecker") will continue failing .

Funny enough, once I have the system in this state, it will sometimes recover, sometimes not. In the latter case, even doing a "minikube delete" followed by a "minikube start" does not fix it. What DID fix it for me (aside from rebooting the Windows host) was deleting and starting minikube and also restarting the Windows "Host Network Service".
This also explains why I sometimes observed this issue already when enabling the ingress addon - since these are the first images that are actually pulled (where the K8s infra pods come preloaded with the image), this is the first time that DNS lookups are done.
I tried this with both Hyper-V and Virtualbox drivers, same result.
Summary: So failing DNS requests appear to somehow derail CoreDNS, which itself does something bad with the upstream DNS server, which in the case of a Windows host causes permanent DNS failures. Would be interesting to see if the same happens in other environments (Minikube on Linux, EKS, AKS, etc.). So the question is: who is to blame? curl? CoreDNS? The Windows DNS service? Since doing the test without CoreDNS in the loop does not show the problem, it probably makes sense to start looking this way. But note that I did not see the issue when using the Docker driver with my "Docker Desktop" installation.

**Comment by zouyee** [comment]
It seems network problem.

**Comment by jgoeres** [comment]
The result is indeed a network problem, but it is IMO quite clearly triggered by CoreDNS.
The relevant part is that when running the same ill-behaved process in the same environment directly on the Docker Daemon, the problem does not show up. But when running this in Kubernetes where CoreDNS handles the lookups, it does.
Don't you think that at least warrants some investigation?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] i/o timeout a..." ]
>when running this in Kubernetes where CoreDNS handles the lookups, it does.
>Don't you think that at least warrants some investigation?

we see this all time, k8s networking isn't reliable

/close
