### ISSUE TITLE
Forward plugin timeout configuration

### ISSUE THREAD

**Issue by arno-pons** [coredns/coredns#4493]
According to forward plugin documentation, the timeouts for communication are set as follows:
```
The dial timeout by default is 30s, and can decrease automatically down to 100ms based on early results.
The read timeout is static at 2s.
```

Sometimes we are experencing some timeout issues in DNS resolution using coredns in our Kubernetes clusters.
Theses timeout are probably caused by network latencies, and I want to understand if these forward plugin timeout values are configurable ? If not could at least explains how `dial timeout` is working (or point to a documentation if exists) ?

Thanks and regards.

**Comment by zouyee** [comment]
related pr:
https://github.com/coredns/coredns/pull/2319

It seems not be configured.
