### ISSUE TITLE
Forward plugin - remove Proxy

### ISSUE THREAD

**Issue by plieskovsky** [coredns/coredns#4494]
**Details**
Hello, i am currently working on a project, where i need to dynamically change the upstream DNS resolvers that will be used to resolve the requests. There is a reload plugin that is capable of reloading the service based on Corefile change, but it reloads all the plugins and it seems like a little bit of overhead. So i am looking for a way to update only the forward plugin internals.
There is a [SetProxy method](https://github.com/coredns/coredns/blob/1df7daf995b5e233acf5cd5b15986e773450bdda/plugin/forward/forward.go#L62) that allows to add a Proxy to the `Forward` struct. It would be beneficial if there would be also a way to remove a Proxy from the struct, so we can dynamically tell the forward plugin to stop using an upstream DNS resolver.
The idea behind this is, that i would introduce a custom plugin, get the forward plugin from the plugins chain and change the proxies it uses.

Would it be possible to add this functionality? Would it require a lot of refactoring or is it a pretty straightforward change? I see a possible problem in the removal of Proxy regarding the fact that it can be used by some request so we have to be sure to remove Proxy only if it currently doesn't serve any request.

What do you think about this improvement? Does it make sense to you? Or is there any better way to dynamically change the upstream DNS resolvers?
 
I would be happy to implement this improvement and open an PR if u advise me that it is possible and that it makes sense from your point of view.

**Comment by miekg** [comment]
We can't commit to making changes to the internal impl. That creates a maintainence
nightmare. In fact almost none of the functions/methods actually need to be public.

There is no way to tests this, there is no obligation to report back that certain
functionality is not needed anymore etc, etc.

If you need this and have custom plugin anyway it is trivial to compile your own fork of
forward as well.

**Comment by plieskovsky** [comment]
Thank you for the quick response and a good explanation of the problem👍.
