### ISSUE TITLE
TestLookupBalanceRewriteCacheDnssec() fails

### ISSUE THREAD

**Issue by 0x333333** [coredns/coredns#450]
Hi,

Test `TestLookupBalanceRewriteCacheDnssec()` in [middleware_dnssec_test.go](https://github.com/miekg/coredns/blob/master/test/middleware_dnssec_test.go#L45) fails to perform query with EDNS. 

The query sent was

```
;; opcode: QUERY, status: NOERROR, id: 584
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;example.org.	IN	 A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: do; udp: 4096
```

But somehow CoreDNS got another one with a broken `OPT PSEUDOSECTION`, then it failed to get EDNS version.

```
;; opcode: QUERY, status: NOERROR, id: 584
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;example.org.	IN	 A

;; ADDITIONAL SECTION:
;.	32768	CLASS4096	OPT
```

Thanks,
Zhiepng

**Comment by miekg** [comment]
Uhm, what?! :)

I don't see this when I run the tests, could you debug some more? 


/Miek

--
Miek Gieben

**Comment by 0x333333** [comment]
Interesting, I ran the tests in a remote VM they all passed.

Yesterday some heath check tests also failed and it turned out to be the problem of my local DNS, which was hijacked by local ISP and always returned a webpage no matter the URL is resolvable or not.

Probably they are related, anyway, I will close the false alarm first and take some time to dig deep.

Thanks, 😄 
Zhipeng

**Comment by 0x333333** [comment]
Hi Miek,

It turned to be the problem of my local outdated `github.com/miekg/dns`, which was before the commit https://github.com/miekg/dns/commit/5d001d020961ae1c184f9f8152fdc73810481677 and issue https://github.com/miekg/dns/issues/379 .

It sent the OPT section like this,

```
;; opcode: QUERY, status: NOERROR, id: 584
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;example.org.	IN	 A

;; ADDITIONAL SECTION:
;.	32768	CLASS4096	OPT
```

This would lead to an interface conversion error,

```
panic: interface conversion: dns.RR is *dns.RR_Header, not *dns.OPT
/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/miekg/dns.(*Msg).IsEdns0(0xc4201aea20, 0x104031)
	/Users/zhipeng/Development/go/src/github.com/miekg/dns/defaults.go:151 +0x104
github.com/miekg/coredns/middleware/pkg/edns.Version(0xc4201aea20, 0x1455368, 0x1cf5a40, 0xc4204f6c00)
	/Users/zhipeng/Development/go/src/github.com/miekg/coredns/middleware/pkg/edns/edns.go:15 +0x2f
github.com/miekg/coredns/core/dnsserver.(*Server).ServeDNS(0xc4204589a0, 0x1cf5a40, 0xc4204f6c00, 0xc4201aea20)
	/Users/zhipeng/Development/go/src/github.com/miekg/coredns/core/dnsserver/server.go:172 +0x8a
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc4203c9ae0, 0x1cf5a40, 0xc4204f6c00, 0xc4201aea20)
	/Users/zhipeng/Development/go/src/github.com/miekg/dns/server.go:210 +0x61
github.com/miekg/dns.(*Server).serve(0xc42048e000, 0x1ce6720, 0xc42036c6f0, 0x1ce0de0, 0xc4203c9ae0, 0xc420298000, 0x28, 0x200, 0xc4201980b0, 0xc420443e40, ...)
	/Users/zhipeng/Development/go/src/github.com/miekg/dns/server.go:577 +0x500
created by github.com/miekg/dns.(*Server).serveUDP
	/Users/zhipeng/Development/go/src/github.com/miekg/dns/server.go:531 +0x2d7
```

Lesson learned, update dependencies from time to time ;)

Thanks,
Zhipeng

**Comment by 0x333333** [comment]
How about enabling `go get -u` inside `deps` in Makefile?
