### ISSUE TITLE
DNSSEC in cache leads to unexpected results

### ISSUE THREAD

**Issue by howardjohn** [coredns/coredns#4502]
Note: I didn't know what eDNS was a few hours ago, so some of this may not make sense :slightly_smiling_face: 

Config:
```
.:5053 {
    errors
    health {
       lameduck 0.5s
    }
    ready
    prometheus :9153
    forward . /etc/resolv.conf {
       max_concurrent 1000
    }
    cache 1
    debug
    log . "{type} {class} {name} {proto} {size} do={>do} buf={>bufsize} || {rcode} {>rflags} {rsize} {duration}"
    loop
    reload
    loadbalance
}
```
I set up a dns host that just returns a lot of TXT data.
I send two requests back to back (first is cold, second is cached). edns and dnssec are disable
```
$ dig dns.howardjohn.info. TXT +bufsize=0 +ignore +noedns +nodnssec @127.0.0.1 -p 5053

; <<>> DiG 9.16.12-Debian <<>> dns.howardjohn.info. TXT +bufsize=0 +ignore +noedns +nodnssec @127.0.0.1 -p 5053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17614
;; flags: qr rd ra; QUERY: 1, ANSWER: 28, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 2048
;; QUESTION SECTION:
;dns.howardjohn.info.           IN      TXT

;; ANSWER SECTION:
dns.howardjohn.info.    1       IN      TXT     "hello" "world4"
<truncated>

;; Query time: 72 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Wed Mar 03 17:47:04 PST 2021
;; MSG SIZE  rcvd: 1294

$ dig dns.howardjohn.info. TXT +bufsize=0 +ignore +noedns +nodnssec @127.0.0.1 -p 5053

; <<>> DiG 9.16.12-Debian <<>> dns.howardjohn.info. TXT +bufsize=0 +ignore +noedns +nodnssec @127.0.0.1 -p 5053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30397
;; flags: qr aa tc rd ra; QUERY: 1, ANSWER: 18, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dns.howardjohn.info.           IN      TXT

;; ANSWER SECTION:
dns.howardjohn.info.    1       IN      TXT     "hello" "world4"
<truncated>

;; Query time: 4 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Wed Mar 03 17:47:05 PST 2021
;; MSG SIZE  rcvd: 493
```

In the first request, we see the edns of request is ignored:
```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 2048
```

With a miekg/dns client:
```
func TestDirect(t *testing.T) {
	for i := 0; i < 5; i++ {
		c := &dns.Client{Net: "udp"}
		m := new(dns.Msg)
		m.SetQuestion("dns.howardjohn.info.", dns.TypeTXT)
		r, ttl, err := c.Exchange(m, "127.0.0.1:5053")
		t.Log(r, ttl, err)
	}
}
```
I see `dns: overflow unpacking uint16` on the first request and the same as the second dig request for the last requests.

From a git bisect, this behavior changed in https://github.com/coredns/coredns/pull/4085. prior to this, it would always be truncated (without the TC flag?).

From the PR: "If a client just needs plain DNS, the DNSSEC records are stripped from the response." it seems that this only happens on cached requests but not the initial requests.

**Comment by miekg** [comment]
>  it seems that this only happens on cached requests but not the initial requests.
i thought we had done this in later PRs, but apparently still not :(

**Comment by miekg** [comment]
i don't see it doing anything wrong locally. You get a TC which dig. because you basically asked for it? 
I don't think we properly echo the bufsize of the client, I think we do, or some newer rfc said it should be the server's preferred bufsize.
