### ISSUE TITLE
Kubernetes: Fewer replicas with more traffic per replica or vice versa?

### ISSUE THREAD

**Issue by mlowery** [coredns/coredns#4506]
We run [cluster-proportional-autoscaler](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) but with a relatively high `nodesPerReplica` value. This yields a total replica count that is far smaller than what we would be running if the example in [Autoscale the DNS Service in a Cluster](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/#enablng-dns-horizontal-autoscaling) was used verbatim.

@yingnanzhang666 found that the limiting factor when running our smaller number of replicas is not CoreDNS but the UDP socket buffer. Would the maintainers be open to a PR to make the UDP buffer configurable (i.e. not the default)?

```diff
+               if err := unix.SetsockoptInt(int(fd), unix.SOL_SOCKET, unix.SO_RCVBUF, n); err != nil {
+                       log.Warningf("Failed to set SO_RCVBUF on socket: %s", err)
+               }
```

On the other hand, presumably we would not have run into the UDP socket buffer issue had we been running with a much higher replica count. Is there any guidance from the community about the number of replicas to run? [Scaling CoreDNS in Kubernetes Clusters](https://coredns.io/2018/11/15/scaling-coredns-in-kubernetes-clusters/) does not mention replica count.

In theory, running fewer replicas would:
1. Reduce resource usage
2. Increase cache hits (which also may reduce forwards)

**Comment by zouyee** [comment]
https://github.com/coredns/deployment/blob/master/kubernetes/Scaling_CoreDNS.md

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Kubernetes: Fewer..." ]
>We run cluster-proportional-autoscaler but with a relatively high
>nodesPerReplica value. This yields a total replica count that is far smaller
>than what we would be running if the example in Autoscale the DNS Service in a
>Cluster was used verbatim.
>
>We've found that the limiting factor when running our smaller number of
>replicas is not CoreDNS but the UDP socket buffer. Would the maintainers be
>open to a PR to make the UDP buffer configurable (i.e. not the default)?
>
>+               if err := unix.SetsockoptInt(int(fd), unix.SOL_SOCKET, unix.SO_RCVBUF, n); err != nil {
>+                       log.Warningf("Failed to set SO_RCVBUF on socket: %s", err)
>+               }

what would be a good value for 'n' ? There are many tweaks that can be done here, I think
the most sane why is a script (or init container) that makes those changes - of course
this assumes that can be done in a containerized setup as well.

**Comment by miekg** [comment]
Note the scaling_coredns document doesn't go into kernel details, but those can be find online for tweaking bind9 or any other DNS server.
