### ISSUE TITLE
label cardinality: remove `type` from coredns_dns_request_duration_seconds

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4507]
I was just manually looking at /metrics and that metric is *huge*, don't know yet when this was added or the original rational, but dropping the `type` here makes sense. This leaves server and zone (which can already be a lot)

**Comment by chrisohaver** [comment]
#3685

**Comment by miekg** [comment]
thank you and that was: https://github.com/coredns/coredns/issues/3684

I think that might be overkill, and only works in smaller setups....

**Comment by miekg** [comment]
clean revert leads to conflicts, and while looking at it we may want to remove `type` from `coredns_dns_requests_total` although that is a counter, but the types 10+X that as well. Real culprit here is actually 'zone' because _that_ is unbounded (in theory)

**Comment by szuecs** [comment]
@miekg what about having a flag to configure the behavior?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] label cardina..." ]
***@***.*** what about having a flag to configure the behavior?

the problem is deeper, once this hits prom/thanos things will blow, a flag do 'I know what
I'm doing' doesn't set well with me.

If you need this data there is logs, dnstap, etc. etc.

**Comment by szuecs** [comment]
Ok thanks for sharing
Different users want different things and as maintainer you have to have an opinion and judge, this is fine.

**Comment by miekg** [comment]
thanks. I get your point as well, but not everything is suitable for metrics

**Comment by SuperQ** [comment]
I agree, the type is probably too much cardinality for the histogram. But for the simple request counter, we should probably keep it.

**Comment by szuecs** [comment]
@SuperQ our problem was that AWS claimed that their route53 VPC endpoint is fine, but our data showed it was not. Then the discussion by them was that it's likely AAAA records that have the big latencies. For this we needed a split of A/AAAA records histogram.
I think counters would not show this.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] label cardina..." ]
>@SuperQ our problem was that AWS claimed that their route53 VPC endpoint is
>fine, but our data showed it was not. Then the discussion by them was that it's
>likely AAAA records that have the big latencies. For this we needed a split of
>A/AAAA records histogram.
>I think counters would not show this.

dnstap would tell....

**Comment by SuperQ** [comment]
Correct, the counter is not going to provide enough info on its own.

Would a duration counter to generate average be good enough? (basically histogram `_sum` and `_count` only, no buckets)

**Comment by yongtang** [comment]
@szuecs Will logging be able to solve the problem? Unless you need real time analysis, metrics may not be necessary ~~(logging can be done in offline mode)~~ (logging analysis can be done in offline mode)

**Comment by yongtang** [comment]
@szuecs  as @miekg suggested, dnstap is exactly the logging format used for dns.
