### ISSUE TITLE
[Feature Request] plugin/hosts: Add wildcard support.

### ISSUE THREAD

**Issue by F-TD5X** [coredns/coredns#4516]
Like I have to use multiple subdomain hosted on one server, ike `a.example.com`, `b.example.com` , etc. And I want to points all these domains to same IP address for better performance, remove ads or something. That's why I want to use hosts plugin to achieve this.

what I want to have was like
```
hosts{
     127.0.0.1 *.example.com
     127.0.0.1 *.sub.example.com
}
```

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[coredns/coredns] [Feature Request]..." ]
>Like I have to use multiple subdomain hosted on one server, ike a.example.com,
>b.example.com , etc. And I want to points all these domains to same IP address
>for better performance, remove ads or something. That's why I want to use hosts
>plugin to achieve this.
>
>what I want to have was like
>
>hosts{
>     127.0.0.1 *.example.com
>     127.0.0.1 *.sub.example.com
>}
>

that's not supported in the /etc/hosts file, the standards are old (RFC 608/606 and
probably others). You need to file or records plugin for this to work.

/close
/plugin hosts
