### ISSUE TITLE
helper tool for external middleware

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#453]
Caddy had `caddyext` as a tool for some time which was quite nice - we should probably create one for coredns.

Currently I'm not aware that Caddy has something other than the download system on <caddyserver.com> for getting middleware compiled into the binary, this makes development harder as well. Thus I think such a utility provides value.

<https://github.com/caddyserver/caddyext>
Plus this needs docs in `middleware.md`.

**Comment by miekg** [comment]
Is this *actual* useful, or should we just document the process?

**Comment by bwaz** [comment]
caddyext may lose support based on this forum post. 

> That tool will probably be phased out soon.
https://forum.caddyserver.com/t/caddys-source-not-found-on-any-gopath-directories/1118

**Comment by miekg** [comment]
Yes, I know. But removing this tool is not helpful - I want something for CoreDNS to aid in developing and having external middleware - so not everything needs to be in the main repo.

**Comment by bwaz** [comment]
This may work as a stop-gap solution for external middleware - please advise
We can setup a directives.yaml config file in the root directory 
```
...
-package "github.com/miekg/coredns/middleware/bind"
  -name "bind"
  -enabled true
-package "github.com/miekg/coredns/middleware/log"
  -name "log"
  -enabled true
...
```
core/cordns.go will be automatically created/updated on build-time to include only enabled packages
core/dnsserver/directives.go: var directives will be removed from this file,
it will be defined in a new file that is created at build-time as well.

I was successful in cloning a middleware  and moving it to a separate repo project, the build will pull from github when the package is defined in the coredns.go file.

**Comment by miekg** [comment]
I like the idea (not sure about yaml :) ). Note a middleware also needs to be ordered.

But I like the fact that this can be kept separate from the source. A Go generate can automatically parse this and edit the source to make stuff work

**Comment by bwaz** [comment]
This could be the middleware file - would generate the imports and define directives in the same order. 
The name of the package should be the same when caddy registering (I hope). We can ignore "#" lines. 
I'm assuming we should not import a package if it's not in the directives to make a smaller bin.
go:generate is not really needed in this case, we could just parse prior to build.

```
github.com/miekg/coredns/middleware/root
github.com/miekg/coredns/middleware/bind
github.com/miekg/coredns/middleware/trace
github.com/miekg/coredns/middleware/health
github.com/miekg/coredns/middleware/pprof
github.com/miekg/coredns/middleware/prometheus
github.com/miekg/coredns/middleware/errors
github.com/miekg/coredns/middleware/log
github.com/miekg/coredns/middleware/chaos
github.com/miekg/coredns/middleware/cache
github.com/miekg/coredns/middleware/rewrite
github.com/miekg/coredns/middleware/loadbalance
github.com/miekg/coredns/middleware/dnssec
github.com/miekg/coredns/middleware/file
github.com/miekg/coredns/middleware/auto
github.com/miekg/coredns/middleware/secondary
github.com/miekg/coredns/middleware/etcd
github.com/miekg/coredns/middleware/kubernetes
github.com/miekg/coredns/middleware/proxy
github.com/miekg/coredns/middleware/httpproxy
github.com/miekg/coredns/middleware/whoami
github.com/miekg/coredns/middleware/erratic
```

Alternatively the middleware its self could use go:generate to add to the directives.
each package could have a enabled/disabled, name and priority setting.  middleware with same priority would go in name order.  This way adding to the import in core/cordns.go will pull a middleware form any repo and add to the directives in the correct order.



I'm open to ideas

**Comment by miekg** [comment]
I would pref. only have support for external middleware. It should also work with the current way of building Go programs, so go generate && go build should do the trick.

Simplets way to get ordering is to just allow a number in the config file:
~~~
5:proxy2:github.com/<someone>/proxy
~~~
And have a little parser for it?

**Comment by bwaz** [comment]
https://github.com/miekg/coredns/pull/496

**Comment by bwaz** [comment]
close... (https://github.com/miekg/coredns/pull/496)
