### ISSUE TITLE
Does coredns only respond to requests on nodes?

### ISSUE THREAD

**Issue by wajika** [coredns/coredns#4530]
I have two nodes. I deploy coredns according to the method of coredns deployment. By default, it has only one pod. Coredns deploys node1. But I found that if I create a pod on node2, it can't resolve the external domain name, and even the logs of coredns don't record this request.

I try to increase the replicas of coredns to 2, and then the pod on node2 can resolve the external domain name.

So coredns needs to create one on each node?

```
[root@k8s-master2 kubernetes]# kubectl get pod -owide
NAME                   READY   STATUS    RESTARTS   AGE     IP            NODE        NOMINATED NODE   READINESS GATES
dnstest                1/1     Running   0          36m     10.244.0.13   k8s-node2   <none>           <none>
dnsutils               1/1     Running   0          12m     10.244.0.15   k8s-node2   <none>           <none>

[root@k8s-master2 kubernetes]# kubectl exec -ti dnsutils -- cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

[root@k8s-master2 kubernetes]# kubectl exec -i -t dnsutils -- nslookup kubernetes.default
;; connection timed out; no servers could be reached

command terminated with exit code 1

[root@k8s-master3 kubernetes]# kubectl logs --namespace=kube-system -l k8s-app=kube-dns
.:53
[INFO] plugin/reload: Running configuration MD5 = b0741fcbd8bd79287446297caa87f7a1
CoreDNS-1.8.3
linux/amd64, go1.16, 4293992
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 5s
[INFO] plugin/reload: Running configuration MD5 = 4a0afbe5ce12821caf9d084d4bec0f9c
[INFO] Reloading complete
[INFO] 127.0.0.1:42569 - 16884 "HINFO IN 1713998247640830607.3448062943235679723. udp 57 false 512" NXDOMAIN qr,rd,ra 132 0.03629159s



```

**Comment by chrisohaver** [comment]
> But I found that if I create a pod on node2, it can't resolve the external domain name, and even the logs of coredns don't record this request.

This indicates a problem with networking in your cluster.  Pods should be able to reach Pods on other nodes via ClusterIP.

**Comment by wajika** [comment]
@chrisohaver Hello, thank you for your reply.

I checked the Kube proxy log, and there was no error.

Can you teach me what to do next? I don't have any ideas

**Comment by chrisohaver** [comment]
Try reaching out on Kubernetes slack forums ... https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/#slack

**Comment by wajika** [comment]
@chrisohaver 
![coredns](https://user-images.githubusercontent.com/17058349/112587422-84aa5400-8e38-11eb-89e5-5f0abec22679.png)
Thank you, but it is mentioned in the document that if the resolution fails, then it should be a coredns or kube-dns issue

**Comment by chrisohaver** [comment]
> Thank you, but it is mentioned in the document that if the resolution fails, then it should be a coredns or kube-dns issue 

Thats not exactly what it says, it says _those_ errors indicate a dns issue. But those errors (negative responses from the server) are different than the error you are getting (no response at all).  The error you get suggests that the requests never reach CoreDNS - i.e. a networking problem in your cluster.
