### ISSUE TITLE
One node has thousands of gorutines than other nodes in my coredns cluster

### ISSUE THREAD

**Issue by lzp0412** [coredns/coredns#4542]
- version
   v1.6.3
- problem
   In my coredns cluster, one node has thousands of gorutines than other nodes. The qps per node is about 4k.Through pprof analysis, it is found that many gorutines are blocked on writeLock for writing udp data streams.
![image](https://user-images.githubusercontent.com/10192658/112088229-663f2100-8bca-11eb-85b7-c195f2ac6abe.png)
   Through pprof analysis, it is found that syscall.Syscall takes a long time in abnormal nodes. This causes writelock to release the lock slowly. So my question is why the abnormal node syscall.Syscall takes a long time？

The monitor graph of gorutine 
![image](https://user-images.githubusercontent.com/10192658/112088864-84f1e780-8bcb-11eb-871a-63efa4c1bcc6.png)

The abnormal node gorutine 
![image](https://user-images.githubusercontent.com/10192658/112088925-a4891000-8bcb-11eb-95a6-110cedd8bd21.png)

The flame graph of abnormal node
![image](https://user-images.githubusercontent.com/10192658/112089161-0ea1b500-8bcc-11eb-9bc3-57341fa958a7.png)

The flame graph of normal node
![image](https://user-images.githubusercontent.com/10192658/112089038-d9956280-8bcb-11eb-8ef0-e9f86ba32c2c.png)

**Comment by miekg** [comment]
please replicate outside of k8s, can't say anything about your networking are whatever crazyness is going on there.
