### ISSUE TITLE
forward causing high cpu usage

### ISSUE THREAD

**Issue by ThinkMo** [coredns/coredns#4544]
**What happened**:

when request . in NS use forward plugin，even all proxy return “2 . NS: dns: bad rdata”，it still in loop until defaultTimeout，causing high cpu usage

**Why is this needed**:

it‘s no need to request proxy when all return error，causing high cpu usage

**What you expected to happen**:

return err after all proxy return err

**How to reproduce it (as minimally and precisely as possible)**:

DNS like this
QUESTION: 
 QNAME: ns.dns.. QTYPE: NS QCLASS: in

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.6.6
- Corefile: 

```
. {
    reload 10s
    errors
    log
    etcd {
        path /skydns/ka2
        endpoint    xx
        fallthrough
    }

    loadbalance round_robin

    # upstream dns
    forward . 10.8.8.8:53 {
      prefer_udp
    }

    cache 10
    prometheus 0.0.0.0:9123
}
```

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): debian9
- Others:

**Comment by pacoxu** [comment]
> max_concurrent MAX will limit the number of concurrent queries to MAX. Any new query that would raise the number of concurrent queries above the MAX will result in a REFUSED response. This response does not count as a health failure. When choosing a value for MAX, pick a number at least greater than the expected upstream query rate * latency of the upstream servers. As an upper bound for MAX, consider that each concurrent query will use about 2kb of memory.


```
    forward . 10.8.8.8:53 {
      prefer_udp
      max_concurrent 100 ?
    }
```

Just a workaround. The max_concurrent here would help.
Health-check on forward is also an option.
I'm not expert of coredns. Only some of my thoughts that may help.

**Comment by ThinkMo** [comment]
> > max_concurrent MAX will limit the number of concurrent queries to MAX. Any new query that would raise the number of concurrent queries above the MAX will result in a REFUSED response. This response does not count as a health failure. When choosing a value for MAX, pick a number at least greater than the expected upstream query rate * latency of the upstream servers. As an upper bound for MAX, consider that each concurrent query will use about 2kb of memory.
> 
> ```
>     forward . 10.8.8.8:53 {
>       prefer_udp
>       max_concurrent 100 ?
>     }
> ```
> 
> Just a workaround. The max_concurrent here would help.
> Health-check on forward is also an option.
> I'm not expert of coredns. Only some of my thoughts that may help.

thanks, 

it's not work for me，Health-check  can't turn off.

**Comment by goudai** [comment]
I ran into the same problem @ThinkMo

**Comment by goudai** [comment]
The problem caused my Coredns CPU usage to reach 300%

**Comment by chrisohaver** [comment]
> DNS like this
> QUESTION:
> QNAME: ns.dns.. QTYPE: NS QCLASS: in

is the illegal  `..` in the QNAME intentional or a typo?

**Comment by chrisohaver** [comment]
#4824
