### ISSUE TITLE
Add fallthrough to file plugin, or add wildcards to hosts plugin

### ISSUE THREAD

**Issue by m-yosefpor** [coredns/coredns#4545]
**What would you like to be added**:
Either of these:
1. fallthrough for `file` plugin
2. wildcard for `host` plugin

**Why is this needed**:
We need to have some static records (some of them wildcard) for a domain which coredns is not authoritative for. `hosts` plugin have fallthrough option, but does not support wildcard. `file` plugin supports wildcard, but doesn't allow to fallthrough if domain is not found.

example.com zone:
```
aa.example.com 1.2.3.4
bb.example.com 2.3.4.5
*.apps.example.com 5.6.7.8
```
but there are also other domains under `example.com` which is not managed by our team (`cc.example.com` and we want to fallthrough to `forward` plugin for them.

I know we can use `template` plugin for that, but there are many static records which will result in a very long and messy Corefile. Also it's much better to have a separate file for static records and keep Corefile for our  coredns configuration (separate reload, human errors, etc)

**related issues:**
https://github.com/coredns/coredns/issues/3601

**Comment by m-yosefpor** [comment]
I'm ok to implement either of these, just want to know what do maintainers think of this.

**Comment by chrisohaver** [comment]
There's an external plugin that may help you here.  https://github.com/coredns/alternate
With it, you can forward to a local instance that uses the file plugin, which can define wild cards.  If the result is NXDOMAIN, then you can forward to an alternate server, which could be another local instance or upstream DNS server.

**Comment by m-yosefpor** [comment]
> There's an external plugin that may help you here. https://github.com/coredns/alternate

@chrisohaver Yeah, I know about `alternate` and `fallback` plugins, but are there any specific reasons why these plugins shouldn't have the support for those features?

And One general question: when should some feature be implemented in internal modules, and when should it be in external ones? i.e. why don't we have a fanout option in `forward` plugin in `policy` subdirective instead of having it only in external fanout plugin?

with external plugins, we should always build our custom version of coredns for each release, and can not use official images.

**Comment by chrisohaver** [comment]
My thoughts...

The _hosts_ plugin intends to follow the established format of a hosts file, which does not support wildcard notation. https://github.com/coredns/coredns/issues/4516#issuecomment-797362900

Fallthrough behavior has occasionally been requested for the _file_ plugin, but not adopted. I think the underlying reasoning is essentially the same - that _file_ intends to work within the features that a zonefile offers, and zonefiles don't offer fallthrough as described.

> why don't we have a fanout option in forward plugin in policy subdirective instead of having it only in external fanout plugin?

Fanout Issue and PR discussions answer why it's a separate plugin, and why it's external: https://github.com/coredns/coredns/issues/3653 https://github.com/coredns/coredns/pull/3652

related info:
https://coredns.io/2017/07/23/when-should-plugins-be-external/
Some more context on use of "fallthough" behavior: https://coredns.io/manual/explugins/#fallthrough

**Comment by m-yosefpor** [comment]
Thanks @chrisohaver for your thorough explanation.
As it is mentioned in fallthrough docs

> In a perfect world, the following would be true for plugins:

**Comment by m-yosefpor** [comment]
Thanks @chrisohaver  for your thourough explanation.

As it is mentioned in fallthrough section:
> In a perfect world, the following would be true for plugins: “Either you are responsible for a zone or not”.... Now, the world isn’t perfect, and there are good reasons to “fallthrough” to the next middleware..

I think it is also the case for file plugin here. Although a standard zonefile, does not provide fallthrough as you mentioned, but it is yet been requested many times and this feature have many valid use-cases (including what have been described in the issue description).
Also I think having the option for file plugin to fallthrough does not cause any unexpected behaviour due to violating the standard or sth, and only the users who have explicitly set this directive get this fallthrough behaviour.

I mean it makes sense to stick with some standards such as not supporting wildcard in `host` plugin or other features which cause the plugin to behave differently, but I think this `fallthrough` feature is somehow different.

**Comment by terefang** [comment]
i actually have the same use-case and business needs as @m-yosefpor 

in addition i am unable to use anything else than the base binary provided on github, 
so having this in core and not some external is an absolute requirement for me.

**Comment by chrisohaver** [comment]
> in addition i am unable to use anything else than the base binary provided on github,
so having this in core and not some external is an absolute requirement for me.

Would forking coredns, adding the external plugins to plugin.cfg, and releasing to your github fork work?

**Comment by terefang** [comment]
> > in addition i am unable to use anything else than the base binary provided on github,
> > so having this in core and not some external is an absolute requirement for me.
> 
> Would forking coredns, adding the external plugins to plugin.cfg, and releasing to your github fork work?

no

**Comment by NsLib** [comment]
any updates?

**Comment by chrisohaver** [comment]
> any updates?

Not that I am aware.

Per #4700 and #3601, adding `fallthrough`  to the _file_ plugin is not acceptable to the _file_ plugin CODEOWNERs.

And adding wildcard record support to the _hosts_ plugin also unacceptable per https://github.com/coredns/coredns/issues/4516#issuecomment-797362900.

Further blunting any effort to add these features: there are already external plugins that can solve these problems in other ways.

I'm going to close this, since both features have been requested in the past and rejected.

**Comment by kfox1111** [comment]
Needing this too. Having to rebuild kubernete's coredns containers to add an external plugin for this is not a great solution.

**Comment by kamikazechaser** [comment]
There is a hack using the template plugin where wildcard DNS queries can respond with a hardcoded answer e.g.

```
    template IN ANY x.net {
        match "\w*\.(x.net\.)$"
        answer "{{ .Name }} 3600 IN A 10.2.0.10" 
        fallthrough
    }
```

*.x.net -> A 10.2.0.10

**Comment by terefang** [comment]
@kamikazechaser 

how performant would this be with 1000s of domains ?

**Comment by kamikazechaser** [comment]
Not sure, but I would guess it would be still pretty performant. Our use case is about 20 domains on a captive portal to serve internal services all in the format `subdomain.x.net`.

[DNSmasq](https://github.com/iNethi/inethi-dev/blob/main/playbooks/dnsmasq.yml#L26) does it better tho. You just write this one line and it works for all subdomains.
