### ISSUE TITLE
[Error] overflow unpacking uint16

### ISSUE THREAD

**Issue by ltagliamonte-dd** [coredns/coredns#4547]
Picking up the not completed troubleshooting from https://github.com/coredns/coredns/issues/4343 @miekg and @chrisohaver 
First of all I'd like to thank you for all the help, and **the incredible OSS support you do**, thank you.

Interesting fact coredns and consul both use http://github.com/miekg/dns

I believe the biggest issue we had in #4343 was the luck of reproducible steps and missing tcpdump captures, I'm going to explain how to reproduce the issue on your local, attach tcpdump captures and will conclude with what I'm able to conclude on my side just looking at the captures.

## Steps to reproduce the issue
1 - Download and unzip consul server for your architecture (it is a single binary) at this [link](https://releases.hashicorp.com/consul/1.8.8/)

run the following cmds to create a local test env:
```
mkdir -p consul/data

cat <<'EOF' >> consul.json
{
  "enable_script_checks": false,
  "enable_local_script_checks": true,
  "skip_leave_on_interrupt": true,
  "disable_update_check": true,
  "discovery_max_stale": "48h",
  "disable_remote_exec": true,
  "http_config": {
    "allow_write_http_from": [
      "127.0.0.0/8",
      "::1/128"
    ]
  },
  "dns_config": {
    "allow_stale": true,
    "enable_truncate": true,
    "only_passing": true,
    "node_ttl": "1m",
    "service_ttl": {
      "*": "10s"
    },
    "use_cache": true,
    "cache_max_age": "5s",
    "enable_additional_node_meta_txt": false,
    "soa": {
      "expire": 86400,
      "min_ttl": 30,
      "refresh": 3600,
      "retry": 600
    }
  },
  "performance": {
    "raft_multiplier": 3
  },
  "ports": {
    "https": 8501
  },
  "telemetry": {
    "disable_hostname": true,
    "prometheus_retention_time": "60s"
  }
}
EOF

cat <<'EOF' >> init-consul.sh
#!/bin/bash
for i in {0..254}
do
cat <<EOP > payload.json
{
  "Node": "foobar",
  "Address": "192.168.10.10",
  "Service": {
    "ID": "deploy-${i}",
    "Service": "deployment-service-web",
    "Address": "192.168.1.${i}",
    "Port": 8000
  }
}
EOP
curl --request PUT --data @payload.json http://127.0.0.1:8500/v1/catalog/register
done
rm payload.json
EOF
```

in a shell run consul:
```
consul agent -server -client="0.0.0.0" -bind="0.0.0.0" -http-port=8500 -dns-port=8600 -data-dir=consul/data -recursor=1.1.1.1 -config-file=consul.json -enable-local-script-checks -ui -retry-interval=10s -advertise=127.0.0.1 -bootstrap-expect=1
```

in another shell, add some endpoints to consul using:
```
bash init-consul.sh
```

Create a coredns config:
NB. the double `forward . 127.0.0.1:8600 127.0.0.1:8600` is used in this case to mimic my prod configuration, in prod the second endpoint is not localhost, this doesn't influence the end results.
```
cat <<'EOF' >> core.json
    consul:1053 {
      bind 127.0.0.1
      errors
      cache 30 {
        prefetch 2 1m 20%
      }
      forward . 127.0.0.1:8600 127.0.0.1:8600 {
        policy sequential
      }
    }
EOF
```
Using latest master (commit id ea41dd23a01d653b01d153a868d586fac4d4381a)
```
make
./coredns -conf core.json
```

Setup is completed

## Test
if you reach consul directly, it works flawlessly:
```
dig @127.0.0.1 -p 8600 deployment-service-web.service.consul +edns +bufsize=4096
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 8600 deployment-service-web.service.consul +edns +bufsize=4096
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47955
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 255, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;deployment-service-web.service.consul. IN A

;; ANSWER SECTION:
deployment-service-web.service.consul. 10 IN A	192.168.1.95
deployment-service-web.service.consul. 10 IN A	192.168.1.18
deployment-service-web.service.consul. 10 IN A	192.168.1.11
...
deployment-service-web.service.consul. 10 IN A	192.168.1.214
deployment-service-web.service.consul. 10 IN A	192.168.1.134

;; Query time: 0 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Thu Mar 25 15:28:24 PDT 2021
;; MSG SIZE  rcvd: 4146
```

if you use coredns, the query timeouts after 5s
```
dig @127.0.0.1 -p 1053 deployment-service-web.service.consul +edns +bufsize=4096

; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 1053 deployment-service-web.service.consul +edns +bufsize=4096
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 45567
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;deployment-service-web.service.consul. IN A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Mar 25 15:30:28 PDT 2021
;; MSG SIZE  rcvd: 66
```

## Tcpdump Captures
I made the following 2 tcpdump captures:
- [dig-consul-direct.pcap.zip](https://github.com/coredns/coredns/files/6208188/dig-consul-direct.pcap.zip)
- [interaction_coredns_consul.pcap.zip](https://github.com/coredns/coredns/files/6208189/interaction_coredns_consul.pcap.zip)

## Looking at the capture
In the working capture `dig-consul-direct.pcap.zip` the behavior is pretty straightforward, dig makes the request, receives a response with the Truncate bit enabled and retries in TCP.

In the non working capture `interaction_coredns_consul.pcap.zip` I notice a few of things:
- packet 1: the OPT record from **dig** specifies a length of 4096, and has a `DO bit: Cannot handle DNSSEC security RRs`
- packet 2: the OPT record **coredns** uses towards the consul upstream specifies a length of 2048 (i tried to use bufsize 4096 but doesn't change the behavior) and has a `DO bit: Accepts DNSSEC security RRs`
- packet 3: **consul** responses contains the answer, the truncate flag, and has a `DO bit: Cannot handle DNSSEC security RRs`

from this point on I would expect coredns to relay back the response to dig and make dig decide if retry on TCP or not, but this doesn't happen, coredns starts flooding the consul upstream with requests until it timeouts and coredns log show:
```
[ERROR] plugin/errors: 2 deployment-service-web.service.consul. A: dns: overflow unpacking uint16
```

Should coredns respect the OPT size asked by the client? 
Why the buffsize plugin doesn't change the behavior ?

Looking forward to your support.
Thank you again and again.

**Comment by ltagliamonte-dd** [comment]
I made another experiment using amazon route53 DNS as upstream server, and the same 255 records
Same coredns configuration, different domain (it is a private domain can't share the capture, will try to repro this with a domain I can pub share).

In this case the coredns doesn't error out and the proxy works as expected.

I made a capture of this interaction as well and the **only diff between consul reply and route53 reply is that the reply from amazon DNS doesn't contain any partial answers `Answer RRs: 0` nor `Additional RRs: 0`**

<img width="886" alt="Screen Shot 2021-03-25 at 4 27 50 PM" src="https://user-images.githubusercontent.com/51684360/112556995-946a5f80-8d88-11eb-81bf-17040f52e992.png">

**Comment by ltagliamonte-dd** [comment]
I've recreated the route53 test on a domain i own.
CoreDNS config:
```
    dockerizeyourself.com:1053 {
      bind 127.0.0.1
      errors
      cache 30 {
        prefetch 2 1m 20%
      }
      forward . 205.251.192.239:53 205.251.192.239:53 {
        policy sequential
      }
    }
    consul:1053 {
      bind 127.0.0.1
      errors
      cache 30 {
        prefetch 2 1m 20%
      }
      forward . 127.0.0.1:8600 127.0.0.1:8600 {
        policy sequential
      }
    }
```

testing with dig:
```
dig @127.0.0.1 -p 1053 long.record.dockerizeyourself.com
```
works with no issue.
attaching tcpdump of the interaction: coredns -> route53
[route53.pcap.zip](https://github.com/coredns/coredns/files/6212895/route53.pcap.zip)

**Comment by ltagliamonte-dd** [comment]
I did try also with https://github.com/tianon/rawdns that uses http://github.com/miekg/dns as well and also in this case the UDP truncated response come back with no partial records only the truncate flag.
So far the problem seems related to truncated responses with partial records.

From the RFC https://tools.ietf.org/html/rfc2181 it appears that partial RRs can be left in the response:
```
Where TC is set, the partial RRSet that would not completely fit may
be left in the response.  When a DNS client receives a reply with TC
set, it should ignore that response, and query again, using a
mechanism, such as a TCP connection, that will permit larger replies.
```

**Comment by miekg** [comment]
A server must not respond with partial records in a TC response. This is
not is, but something upstream.

**Comment by ltagliamonte-dd** [comment]
@miekg i agree with you it is a problem with the upstream,
but there as still a couple of open questions on coredns side:
- why coredns is not honoring the size specified by dig
- why the buffsize plugin is not working

are you also saying that the behavior in https://tools.ietf.org/html/rfc2181 has been changed by some other RFC?

**Comment by chrisohaver** [comment]
IMO, setting a very large buf size to avoid truncation isn't a good fix.

> are you also saying that the behavior in https://tools.ietf.org/html/rfc2181 has been changed by some other RFC?

That RFC refers to sending incomplete  _RR Sets_ ... but an incomplete RR in the set is a protocol violation.  The response can be a subset of RRs, but each RR included in the response needs to be complete. IOW, you can respond with 4 of 5 records, but not 4.5 of 5.

> * why coredns is not honoring the size specified by dig

This is another matter ...  It's been discussed before here (don't have time to search now). I think it depends on how we categorize CoreDNS's role as a "middlebox" in https://tools.ietf.org/html/rfc6891#section-6.2.6.

> * why the buffsize plugin is not working

If the total response size is > 4096, then truncation will still occur.  If the upstream does not truncate correctly, then CoreDNS will fail to decode the response.

**Comment by ltagliamonte-dd** [comment]
@chrisohaver thank you for responding,
I agree with you about the partial RR and I'm looking at consul code and i see few problems there.

My env is pretty big and squeezing out all I can from EDNS and buff size is really important to me, that said would you accept a PR that will make coredns honor the buff size specified by the client (a new flag to maintain backward compatibility)?
I will be happy to work on that.

About the buffsize plugin, my expectations was to see a request towards the upstream with bigger size but it didn't happen, if you want i can open another issue to track this strange behavior.

Thank you @chrisohaver

**Comment by chrisohaver** [comment]
> My env is pretty big and squeezing out all I can from EDNS and buff size is really important to me, that said would you accept a PR that will make coredns honor the buff size specified by the client (a new flag to maintain backward compatibility)? I will be happy to work on that.

Open a separate issue so the behavior can be discussed and agreed upon before to opening a PR.

**Comment by janfrederik** [comment]
For other people still experiencing this issue running kubernetes under WSL:
I had the same errors resolving some hostnames running k3s in WSL2. Coredns log showed `overflow unpacking uint16` and `buffer size too small`.

Solution: disable the automatic dns settings from Windows in WSL, following the instructions from https://superuser.com/questions/1533291/how-do-i-change-the-dns-settings-for-wsl2.
