### ISSUE TITLE
1.8.4 release tracking

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4549]
Let's kick of the 1.8.4 release.

* we need release notes in order: #4535 (and prolly some follow ups)
* reverse zone fix:  #4538
* dnssec fix: #4537
* rewrite cleanup: #4473

together with what is already merged.

**Comment by chrisohaver** [comment]
Several folks asking on Slack when the next release is expected, I suspect looking to get the unready endpointslices fix (#4580).

**Comment by pires** [comment]
All seems to be merged! Would you be so kind to kick off the tires of a new release?  I was bitten by #4580 🙏🏻

**Comment by yongtang** [comment]
I think we are ready to release. Added PR #4624 to update the release note. Once merged, ready to release @miekg if you are ok (we can defer #4621 to next release?).

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] 1.8.4 release..." ]
>I think we are ready to release. Added PR #4624 to update the release note.
>Once merged, ready to release @miekg if you are ok (we can defer #4621 to next
>release?).

I *think* that can wait, but alternatively we can also release 1.8.5 with only that PR in
it. Version numbers are cheap

**Comment by miekg** [comment]
website: https://github.com/coredns/coredns.io/pull/223
and some final fixes https://github.com/coredns/coredns/pull/4627

**Comment by miekg** [comment]
and might want to not-merged-yet the normalize fixes, fuzzing picked up a crash (only via the config), and I don't want to quickly merge and then release.

**Comment by miekg** [comment]
ok, things have stabilized a bit. I'm still fairly busy, releasing should be a noop, unless something fails, then the cleanup takes a while. I should be able to release this evening (CEST)

**Comment by chrisohaver** [comment]
> and might want to not-merged-yet the normalize fixes, fuzzing picked up a crash (only via the config), and I don't want to quickly merge and then release.

Since it has already merged, I've opened #4648, so that external plugins don't become broken in this patch release. Otherwise, we might want to bump the minor version number for this release (`1.9.0`) to recognize the backward incompatibility with external plugins.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] 1.8.4 release..." ]
>    and might want to not-merged-yet the normalize fixes, fuzzing picked up a
>    crash (only via the config), and I don't want to quickly merge and then
>    release.
>
>Since it has already merged, I've opened #4648, so that external plugins don't
>become broken in this patch release. Otherwise, we might want to bump the minor
>version number for this release (1.9.0) to recognize the backward
>incompatibility with external plugins.

ack and that's also merged.

**Comment by miekg** [comment]
and done, sent announcement on twitter
