### ISSUE TITLE
Ability to create valid JSON logs

### ISSUE THREAD

**Issue by xaocon** [coredns/coredns#4564]
I found #4460 before filing this but since it was closed under the assumption that it was at least possible for a user to create JSON logs so I thought I'd try again.

**What would you like to be added**:
Either a way to specify that the log level shouldn't prefix all log messages from log plugin or an update to docs to describe how to do it.

**Why is this needed**:
Currently there isn't a way (at least that I can tell) to output valid JSON in logs. The log level is prefixed to all log messages. A log format like 
`"{\"request\": \"{type} {class} {name}\", \"size\": \"{size}\", \"duration\": \"{duration}\", \"response\": \"{rcode}\"}"`
results in a log like
`[INFO] {"request": "SOA IN example.com.", "size": "45", "duration": "0.000120082s", "response": "NOERROR"}`
which isn't parsable.

I don't see any info in the docs about how it would be possible to get around this. I also looked at the code but I don't know much GO. I wasn't really able to figure out what a Warning or Error log would look like with the above formatting rule but it would be great if more serious logs could be parsable JSON as well. The addition of a severity placeholder would be very helpful as well.

**Comment by chrisohaver** [comment]
The comments in #4460 suggest using a general purpose log processing tool external to coredns that can wrap the log output of coredns in json format. 

Using the custom log format in the log plugin won’t suffice because it only controls the format of logged queries, not messages or errors from other plugins or the server.
