### ISSUE TITLE
Support for NSEC3 for DNSSEC

### ISSUE THREAD

**Issue by anoncam** [coredns/coredns#4565]
**What would you like to be added**:
Support for NSEC3 in DNSSEC plugin.
**Why is this needed**:

From RFC 

> The DNS Security Extensions included the NSEC RR to provide
   authenticated denial of existence.  Though the NSEC RR meets the
   requirements for authenticated denial of existence, it introduces a
   side-effect in that the contents of a zone can be enumerated.  This
   property introduces undesired policy issues.

>   The enumeration is enabled by the set of NSEC records that exists
   inside a signed zone.  An NSEC record lists two names that are
   ordered canonically, in order to show that nothing exists between the
   two names.  The complete set of NSEC records lists all the names in a
   zone.  It is trivial to enumerate the content of a zone by querying
   for names that do not exist.

>   An enumerated zone can be used, for example, as a source of probable
   e-mail addresses for spam, or as a key for multiple WHOIS queries to
   reveal registrant data that many registries may have legal
   obligations to protect.  Many registries therefore prohibit the
   copying of their zone data; however, the use of NSEC RRs renders
   these policies unenforceable.

 >  A second problem is that the cost to cryptographically secure
   delegations to unsigned zones is high, relative to the perceived
   security benefit, in two cases: large, delegation-centric zones, and
   zones where insecure delegations will be updated rapidly.  In these
   cases, the costs of maintaining the NSEC RR chain may be extremely
   high and use of the "Opt-Out" convention may be more appropriate (for
   these unsecured zones).

  > This document presents the NSEC3 Resource Record which can be used as
   an alternative to NSEC to mitigate these issues.

Please see [RFC](https://tools.ietf.org/html/rfc5155#section-1.1)

**Comment by miekg** [comment]
>What would you like to be added:
>Support for NSEC3 in DNSSEC plugin.
>From RFC

yes, so actually this turned out to be not true... sad thing is nsec3 added _a lot_ of
complexity to DNSSEC for no benefit it all.

It also makes everything way more complex because you need to have an alternative tree for
the hashed names.

If you manage to come up with an implementation that doesn't suck I might reconsider, but
that doesn't change the fact that nsec3 is the worst idea to ever hit the DNS

**Comment by anoncam** [comment]
I will begin working on an implementation for your judgment.  At that time you may determine if it sucks. 

One question: how widely used is NSEC3?

**Comment by miekg** [comment]
For the wrong reasons, but 80% of TLDs use nsec3. It's more common than
nsec.

**Comment by anoncam** [comment]
So is it fair to say that compatibility alone is a reason to support it?  Objectively speaking.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] Support for N..." ]
>So is it fair to say that compatibility alone is a reason to support it?
>Objectively speaking.

for _serving_ zones there isn't a compatibility to speak of, and nsec is also well
supported. It's mostly a tick box.

**Comment by anoncam** [comment]
> [ Quoting ***@***.***> in "Re: [coredns/coredns] Support for N..." ]
> So is it fair to say that compatibility alone is a reason to support it? Objectively speaking.
> for _serving_ zones there isn't a compatibility to speak of, and nsec is also well supported. It's mostly a tick box.

Correct, but for those ticking boxes for NSEC3, Coredns won't be an option for them.

**Comment by miekg** [comment]
True, but it didn't create coredns for those folks...

**Comment by anoncam** [comment]
> I will begin working on an implementation for your judgment. At that time you may determine if it sucks.
> 
> One question: how widely used is NSEC3?

Our organization has that box to tick eventually so it seems CoreDNS is being used by those folks.  Would you rather a fork be maintained of CoreDNS, or would you be flexible to meet the needs of the community?
