### ISSUE TITLE
TestZoneExternalCNAMELookupWithProxy fails without networking

### ISSUE THREAD

**Issue by tv42** [coredns/coredns#4573]
**What happened**:

```
=== CONT  TestZoneExternalCNAMELookupWithProxy
    file_cname_proxy_test.go:75: Expected 2 RRs in answer section got 0
--- FAIL: TestZoneExternalCNAMELookupWithProxy (1.02s)
```

**What you expected to happen**:

Tests pass.

**How to reproduce it (as minimally and precisely as possible)**:

Remove/disable internet connection. Run `go test`.

This was observed in a hermetic NixOS/Nix build environment, essentially a container with no networking.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: v1.8.3
- OS (e.g: `cat /etc/os-release`): NixOS 20.09.3854.db4dda79f8f

Reading the unit test, it seems to resolve `example.net` via the google `8.8.8.8` or `8.8.4.4` addresses.

https://github.com/coredns/coredns/blob/5b9b079dabc7f71463cea3f0c6a92f338935039d/test/file_cname_proxy_test.go#L57

as the configuration used for the software under test doesn't look authoritative for `example.net`:

https://github.com/coredns/coredns/blob/5b9b079dabc7f71463cea3f0c6a92f338935039d/test/example_test.go#L3-L16

**Comment by miekg** [comment]
yes, this is the intended behavior of the test. And yes this introduces a dep. on the global DNS infra.

**Comment by tv42** [comment]
Any change of putting integration tests e.g. behind a build tag? This will fail in any kind of hermetic or containerized build that's set up "the right way".

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] TestZoneExter..." ]
>Any change of putting integration tests e.g. behind a build tag? This will fail
>in any kind of hermetic or containerized build that's set up "the right way".

a change here might happen at some point, but I don't see how your build system should
imply we make changes right now

/close
/lock
