### ISSUE TITLE
Tests assume system /etc/resolv.conf exists and is readable

### ISSUE THREAD

**Issue by tv42** [coredns/coredns#4574]
**What happened**:

```
=== RUN   TestReadme
    readme_test.go:80: Failed to start server with ../plugin/etcd/README.md, for input "plugin/forward: not an IP address or file: \"/etc/resolv.conf\"":
        skydns.local {
            etcd {
                path /skydns
            }
            cache
        }

        . {
            forward . /etc/resolv.conf
            cache
        }
    readme_test.go:80: Failed to start server with ../plugin/forward/README.md, for input "plugin/forward: not an IP address or file: \"/etc/resolv.conf\"":
        . {
            forward . /etc/resolv.conf {
                except example.org
            }
        }
    readme_test.go:80: Failed to start server with ../plugin/grpc/README.md, for input "plugin/grpc: not an IP address or file: \"/etc/resolv.conf\"":
        . {
            grpc . /etc/resolv.conf {
                except example.org
            }
        }
```

**What you expected to happen**:

Tests pass.

**How to reproduce it (as minimally and precisely as possible)**:

Run `go test` in a container that has no `/etc/resolv.conf`. This typically happens when the container has no network connection, or DNS service, in the first place; see https://github.com/coredns/coredns/issues/4573

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: v1.8.3
- OS (e.g: `cat /etc/os-release`): NixOS 20.09.3854.db4dda79f8f

**Comment by zouyee** [comment]
> Run go test in a container that has no /etc/resolv.conf

In general, there is no need to assume this situation.

**Comment by tv42** [comment]
Congratulations, your software now fails to build in NixOS hermetic build environments.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] Tests assume ..." ]
>    Run go test in a container that has no /etc/resolv.conf
>
>In general, there is no need to assume this situation.

I agree.

/lock
/label anonymous
