### ISSUE TITLE
SOA query on record does not respond with Authority Section in kubernetes

### ISSUE THREAD

**Issue by techmunk** [coredns/coredns#4585]
**What happened**:
We have a named/bind9 server which we use to resolve all our networks DNS. This server is configured with a forwarder for the `cluster.local.` domain to a coredns deployment running inside our kubernetes cluster. The named server is outside the cluster.

Most everything with this setup works as expected.

We configured a record (`test.record.tld`) in one of our zones to be a CNAME to the service inside kubernetes `sr.ns.svc.cluster.local.` as an example. This also seemed to work as expected.

Where we ran into issue was when attempting to issue a letsencrypt cerftificate on the above mentioned record using DNS01 challenge method and RFC2136 via cert-manager.io

RFC2136 (or cert-managers implementation) would fall over when attempting to do an SOA on `test.record.tld` due to our named server returning SERVFAIL.

The above request results in named making an SOA request to coredns inside our cluster for `sr.ns.svc.cluster.local.`. This resulted in named giving a "DNS format error, or FORMERR", with "reply has no answer".

Upon closer inspection, coredns is returning a NOERROR response with what seems to be the correct information. Looking closer still and after testing with several other domains running on different DNS servers/providers, we discovered that coredns was the only server that did not return the SOA in an authority section, and instead responded with an answer section. Our forwarder to coredns was the only forwarder we tested which caused named to fail the request.

We also noticed that changing the CNAME to just `cluster.local.` would actually work, even though the result was in an answer section. I suspect because we were requesting the root of the zone.

**What you expected to happen**:
We expected named not to respond with SERVFAIL for forwarded SOA queries.

**How to reproduce it (as minimally and precisely as possible)**:
Our coredns config I believe is stock/default for kubernetes.
```
    .:53 {
        log
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
```

Running the following command

`dig @<core dns ip> svc.cluster.local soa`

results in

```
; <<>> DiG 9.16.13-Ubuntu <<>> @10.96.0.10 svc.cluster.local soa
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49913
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 5a80dbacc96f81a9 (echoed)
;; QUESTION SECTION:
;svc.cluster.local.		IN	SOA

;; ANSWER SECTION:
cluster.local.		27	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1619328346 7200 1800 86400 30

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Sun Apr 25 05:26:09 UTC 2021
;; MSG SIZE  rcvd: 151
```

We'd instead expect

```
; <<>> DiG 9.16.13-Ubuntu <<>> @10.96.0.10 svc.cluster.local soa
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47775
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: e640ac1a44271985 (echoed)
;; QUESTION SECTION:
;svc.cluster.local.		IN	SOA

;; AUTHORITY SECTION:
cluster.local.		19	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1619326708 7200 1800 86400 30

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Sun Apr 25 05:29:02 UTC 2021
;; MSG SIZE  rcvd: 151
```

**Anything else we need to know?**:

We worked around this by adding the following to our coredns config. It's not ideal, but we think it's an ok workaround.
```
        template IN SOA cluster.local {
          match ".*\.cluster\.local\.$"
          authority "cluster.local. 30 IN SOA ns.dns.cluster.local. hostmaster.cluster.local. 1619326708 7200 1800 86400 30"
          fallthrough
        }
```
With this configuration in place, everything works as expected, and SSL certificate renewal works.

Is this behavior expected? Should the workaround be necessary?

**Environment**:

- the version of CoreDNS: Tested with 1.7.0 and 1.8.3
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
>Looking closer still and after testing with several other domains running on different DNS servers/providers, we discovered that coredns was the only server that did not return the SOA in an authority section, and instead responded with an answer section.

When querying directly for the SOA record type, I'd intuitively expect the SOA to be in the answer section, although I scanned the RFCs briefly and could not find this explicitly stated.

Google's DNS, behaves in the same way ...

```
$ dig @8.8.8.8 -t SOA google.com

; <<>> DiG 9.16.5 <<>> @8.8.8.8 -t SOA google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46513
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	SOA

;; ANSWER SECTION:
google.com.		47	IN	SOA	ns1.google.com. dns-admin.google.com. 370319298 900 900 1800 60

;; Query time: 29 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Apr 26 08:52:25 EDT 2021
;; MSG SIZE  rcvd: 89
****
```

**Comment by techmunk** [comment]
That is correct. But the issue is not when querying against the root of the zone, but against a record off that zone.

```
drill @8.8.8.8 SOA www.google.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 19401
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; www.google.com.	IN	SOA

;; ANSWER SECTION:

;; AUTHORITY SECTION:
google.com.	59	IN	SOA	ns1.google.com. dns-admin.google.com. 370319298 900 900 1800 60

;; ADDITIONAL SECTION:

;; Query time: 212 msec
;; SERVER: 8.8.8.8
;; WHEN: Mon Apr 26 22:56:54 2021
;; MSG SIZE  rcvd: 82
```
