### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by waterem** [coredns/coredns#459]
[root@MyCloudServer coredns]# go build
middleware/etcd/etcd.go:16:2: cannot find package "github.com/coreos/etcd/client" in any of:
        /root/goc/src/github.com/miekg/coredns/vendor/github.com/coreos/etcd/client (vendor tree)
        /root/go/src/github.com/coreos/etcd/client (from $GOROOT)

no etcd in coredns

**Comment by miekg** [comment]
did you `go get`?

**Comment by miekg** [comment]
Just did a clean build on a new systems. Just works.
