### ISSUE TITLE
force_tcp do not works for ROOT zone

### ISSUE THREAD

**Issue by sergey-safarov** [coredns/coredns#4615]
**What happened**:
I have configured
```
    forward . dns://[2600:1f1c:6d5:aa00::5]:53 dns://[2600:1f1c:6d5:aa01::5]:53 dns://[2600:1f18:578:5700::5]:53 dns://[2600:1f18:578:5700::5]:53 {
        force_tcp
    }
```
And expect all requests will be sent via TCP protocol to upstream servers.
But really this not happens. You can check it via PCAP file.

**What you expected to happen**:
All requests will be sent via TCP protocol.

**How to reproduce it (as minimally and precisely as possible)**:
Need to configure forwarder with `force_tcp` options
```
    forward . dns://[2600:1f1c:6d5:aa00::5]:53 dns://[2600:1f1c:6d5:aa01::5]:53 dns://[2600:1f18:578:5700::5]:53 dns://[2600:1f18:578:5700::5]:53 {
        force_tcp
    }
```

**Environment**:

- the version of CoreDNS:
```
[root@sbc-a0 ~]# coredns -version
CoreDNS-1.8.3
linux/arm64, go1.16, 4293992
```
- Corefile:
```
# All zones
. {
    # Bind on a specific IP
    bind 127.0.0.1
    cache

    # Forward queries for all zones to a resolver using TLS
    # forward . tls://1.1.1.1:853 tls://1.0.0.1:853

    # Forward queries for all zones to a resolver using plain ol' DNS
    forward . dns://[2600:1f1c:6d5:aa00::5]:53 dns://[2600:1f1c:6d5:aa01::5]:53 dns://[2600:1f18:578:5700::5]:53 dns://[2600:1f18:578:5700::5]:53 {
        force_tcp
    }

    # Forward queries for all zones to /etc/resolv.conf
    #forward . /etc/resolv.conf {
    #    force_tcp
    #}



    # Errors related to query processing are printed to STDOUT
    errors

    # Log all DNS queries
    log

    # Extra debug information
    debug

    # Resolve hostsnames specified in /etc/hosts
    #hosts {
    #  fallthrough
    #}
}

# Import Zone configurations from other files
# import AdditonalZones.conf
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
```
[root@sbc-a0 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```
- Others:

**Comment by sergey-safarov** [comment]
PCAP attached
[dns.pcap.gz](https://github.com/coredns/coredns/files/6451642/dns.pcap.gz)

**Comment by chrisohaver** [comment]
Health check probes to upstream DNS will always be over udp, regardless of `force_tcp` option. (see #3938)
It appears that the pcap attached doesn't contain payload info, so I cant verify if that is whats going on here.

**Comment by chrisohaver** [comment]
> It appears that the pcap attached doesn't contain payload info, so I cant verify if that is whats going on here.

Nevermind - user error.  I see the packet capture contains payloads, ~and I can see that the UDP queries are _not_ health checks~.

Edit: All ipv6 udp traffic appears to be health checks. Presumably the ipv4 traffic is from client to coredns, and ipv6 is coredns to upstream.

**Comment by sergey-safarov** [comment]
you can check PCAP using the Wireshark filter
```
ipv6 and udp
```
yes looks as here health check only via UDP.
Why not implement a health check via `TCP` if in the config  I have defined to force use TCP?

Why not merge https://github.com/coredns/coredns/pull/3940 ?

**Comment by chrisohaver** [comment]
> Why not merge #3940 ?

It appears to have been closed for being inactive for too long.

**Comment by sergey-safarov** [comment]
@chrisohaver could you review #3940, rebase and merge.
That is important because sometimes UDP does not work in the cloud environment.
Reasons:
1) docker do not clear iptables connection tables after socket checks https://github.com/moby/libnetwork/issues/2423
2) AWS does not support IPV6 network load balancers for UDP protocol. 
> [The load balancer must have only TCP and TLS listeners.](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-ip-address-type.html)

**Comment by miekg** [comment]
> That is important because sometimes UDP does not work in the cloud environment.

this is having priorities completely backwards...

**Comment by sergey-safarov** [comment]
@miekg I do not understand your message.
Could you rewrite the message?
