### ISSUE TITLE
Why not using the bind plugin will cause the parsing to fail

### ISSUE THREAD

**Issue by Zhaoyu1123** [coredns/coredns#4620]
### Description
When i use coredns as our intranet dns server, I found it will cause the parsing to fail when  not using the bind plugin.

coredns owned machine ip: xxx

### caddfile 

        .:53 {
        
            hosts ./hosts {
                fallthrough .
            }
        
            nacos {
                nacos_server test.xx.com
                nacos_server_port 80
            }
        
            log
            forward . /etc/resolv.conf
            reload
        }

If don`t set bind xxx in caddyfile, when I use `dig @xxx mysql2.coredns.dev` in cmd,It will reply no answer occasionally.

![image](https://user-images.githubusercontent.com/15028185/117947412-bfae0b80-b342-11eb-8c29-25866b5ffddb.png)

Has anyone encountered this problem？

**Comment by miekg** [comment]
not sure what your asking.

the screenshot isn't helping, please paste plain text

**Comment by Zhaoyu1123** [comment]
> not sure what your asking.
> 
> the screenshot isn't helping, please paste plain text

CoreDNS config file don`t set "bind 10.20.10.101", when I use "dig @10.20.10.101 mysql2.coredns.dev", sometimes the request can be parsed correctly by the coredns server, but sometimes the request cannot be received by  the coredns server.

when the CoreDNS config file set "bind 10.20.10.101" and start with bind plugin, the request can be resolved 100% correctly.

**Comment by chrisohaver** [comment]
Do you have multiple processes listening on port 53?

**Comment by Zhaoyu1123** [comment]
> Do you have multiple processes listening on port 53?

no, only coredns server listen on port 53.

**Comment by chrisohaver** [comment]
Do you have the issue if you remove the “nacos” plugin from the corefile?

**Comment by Zhaoyu1123** [comment]
> Do you have the issue if you remove the “nacos” plugin from the corefile?

this has no relationship with "nacos", bacause I request the name is in the "host", this request will not acess in "nacos".

**Comment by chrisohaver** [comment]
> > Do you have the issue if you remove the “nacos” plugin from the corefile?
> 
> this has no relationship with "nacos", bacause I request the name is in the "host", this request will not acess in "nacos".

Can you try it anyways?  The nacos plugin grabs _all_ requests for all domains and processes them.  If it has a bug, it could be consuming requests and not passing to the next plugin, thus quietly not-responding to the request.  Glancing quickly at the code, nacos does processing _that is dependent on which "local" interface the request came in on_. That said, since this issue is related to which local ports are bound to using _bind_, I think this warrants testing with and without the nacos plugin in the Corefile.

**Comment by chrisohaver** [comment]
> this has no relationship with "nacos", bacause I request the name is in the "host", this request will not acess in "nacos".

Ah - initially misunderstood the above  - are you saying that `mysql2.coredns.dev` is in the hosts file of the hosts plugin?

That makes sense.  But to make sure, when you compiled coredns with nacos, did you position the nacos plugin _after_ the hosts plugin in `plugin.cfg`.

**Comment by chrisohaver** [comment]
Assuming you used https://github.com/nacos-group/nacos-coredns-plugin/blob/master/bin/build.sh, it looks like it hacks the plugin directly into Directives instead of using `plugin.cfg`, and then runs a Makefile sans the directives generation, to place it after _whoami_  which _is_ after hosts... but also after forward - so seems like nacos never receives anything if forward is present.

Nevertheless, if that's the build script you used, then you are right: nacos would not be involved.

**Comment by Zhaoyu1123** [comment]
> > this has no relationship with "nacos", bacause I request the name is in the "host", this request will not acess in "nacos".
> 
> Ah - initially misunderstood the above - are you saying that `mysql2.coredns.dev` is in the hosts file of the hosts plugin?
> 
> That makes sense. But to make sure, when you compiled coredns with nacos, did you position the nacos plugin _after_ the hosts plugin in `plugin.cfg`.

yes it is. 

below is the hosts file:

     10.90.xxx.xxx  mysql1.coredns.local
     10.90.xxx.xxx  mysql2.coredns.local

below is the plugin.cfg file:

![image](https://user-images.githubusercontent.com/15028185/118579108-01660880-b7c0-11eb-9480-a20b99aee511.png)

**Comment by Zhaoyu1123** [comment]
> Assuming you used https://github.com/nacos-group/nacos-coredns-plugin/blob/master/bin/build.sh, it looks like it hacks the plugin directly into Directives instead of using `plugin.cfg`, and then runs a Makefile sans the directives generation, to place it after _whoami_ which _is_ after hosts... but also after forward - so seems like nacos never receives anything if forward is present.
> 
> Nevertheless, if that's the build script you used, then you are right: nacos would not be involved.

I didn't use the nacos build script, only copy the nacos source code directory into coredns plugins  directory, and add `nacos` in the plugin.cfg  as shown in the picture above.

**Comment by chrisohaver** [comment]
What do the failures look like when +short is not passed to dig?
Can you copy/paste text instead of using screen shots please?

**Comment by chrisohaver** [comment]
Looks like host file and queries don't match...

Hostfile:`mysql2.coredns.local` != query-screenshot:`mysql2.coredns.dev`
