### ISSUE TITLE
Getting the ServerName when using Dns over Tls

### ISSUE THREAD

**Issue by pawankanumalli** [coredns/coredns#4622]
Hi, I am new to CoreDNS and have been using it for the past couple of Weeks. I am trying to setup a dns over tls server with dynamic endpoints, i have a domain say:  dnstls.com. and i have configured a wildcard certificate on my server. 

The users will have unique userids, using which the endpoint is defined, like 1099.dnstls.com

I would like to extract 1099 and based on that customize the query processing.

I am able to set the dns over tls server block and it runs absolutely fine, but im not sure how to extract the userid .

my Corefile looks like this...

.:5353 tls://.:853 https://.:443 {
  
  tls /etc/letsencrypt/live/dnstls.com/fullchain.pem /etc/letsencrypt/live/dnstls.com/privkey.pem

  any
  errors
  log
  whoami
  hosts ./hosts {
    fallthrough
  }
  forward . tls://1.1.1.1 tls://1.0.0.1 {
    tls_servername cloudflare-dns.com
    health_check 60s
  }
}

I just need some pointers as to where can i extract the userid from the endpoint and also how to pass it in the context to various plugins/my custom plugin.

**Comment by miekg** [comment]
you can extract that by looking at the request and extracting the query name

**Comment by johnbelamaric** [comment]
I think the question is about the TLS server name being used by the client, not the question section. You'd have to look into the tls code and see if there's a way to get that and publish it via metadata.

**Comment by pawankanumalli** [comment]
Hi Miekg,

Thank you for your quick response. I am sorry but i might have not put across the question correctly. I do know how to extract the questionName from the dnsrequest

I am only looking to extract the endpoint to which the dns request is sent. i.e the unique endpoint of my server.  In Nginx we create a wild card virtual host and simply get this by using either $host or $server_name

I'm sorry to bother you again, i tried to look at the code but wasnt exactly able to find out which plugin or part of code to look at...

Thanks again.

**Comment by pawankanumalli** [comment]
> I think the question is about the TLS server name being used by the client, not the question section. You'd have to look into the tls code and see if there's a way to get that and publish it via metadata.

Thanks, this is exactly what i am looking for, would you be able to point me to the file where i should be looking at.

**Comment by johnbelamaric** [comment]
You'll probably need to do some magic in each of the servers that support
TLS: server_tls.go, server_grpc.go, server_https.go. See for example here:

https://github.com/coredns/coredns/blob/master/core/dnsserver/server_https.go#L75

Not sure where you get this info from the TLS connection in the go libs.

**Comment by johnbelamaric** [comment]
Let me explain a little more. There are two parts of this:

1) figuring out what the ServerName the client presented was. This you'll have to figure out from the go TLS library. I'm not sure how to do that.
2) Making it available to plugins. This should be done via the `metadata` plugin, or more precisely probably via a new metadata plugin provider (which is another plugin), like `metadata_tlsinfo` or something. Adding that to the plugin change would then publish details about the TLS connection to the metadata, where it can be accessed by other plugins.

Check out the policy plugin for extensive use of metadata.

**Comment by pawankanumalli** [comment]
Thanks for your inputs John, I will surely look into these files. I was also looking at Caddy Documentation to find if it passes on the host...
