### ISSUE TITLE
ability to specify min connect timeout in the forward plugin

### ISSUE THREAD

**Issue by blackgold** [coredns/coredns#4626]
**What would you like to be added**:
It will be nice if we can configure [min connect timeout](https://github.com/coredns/coredns/blob/master/plugin/forward/persistent.go#L153) value in forward plugin.

**Why is this needed**:

**Comment by snebel29** [comment]
I don't know if this feature request make sense to the core developers, but If there is a thumbs up to implement it (may be including `maxDialTimeout` as well) I volunteer to create a pull request.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] ability to sp..." ]
>/cc @miekg Are you ok with adding min connect timeout option in forward plugin?

no, I don't think we should add knobs like these. This things should be autotuned as much
as possible; just adding a config knob doesn't cut it
