### ISSUE TITLE
tls middleware pkg

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#465]
There are multiple middleware creating a `*tls.Config` and code looks similar we should abstract this into middleware/pkg/tls

middleware doing this: *etcd*, *proxy* (soon)

**Comment by johnbelamaric** [comment]
Just pushed this: https://github.com/johnbelamaric/coredns/pull/1 which does that for the most part. We could probably squeeze a little more out of parseUpstream and into pkg/tls if we really want to.

**Comment by miekg** [comment]
Calling it done.
