### ISSUE TITLE
plugin/secondary: Retries on i/o-timeout on startup

### ISSUE THREAD

**Issue by itssimple** [coredns/coredns#4661]
Is there a way to configure the `secondary`-plugin to do automatic retries if it fails to load a zone-file?
Or is there some way that I can trigger a reload on zones that failed?

I'm currently setting up a CoreDNS server with secondary, to handle primary DNS outages, but I sometimes get data like this:

```plain
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5
[INFO] plugin/file: Transferred: <host1>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host2>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host3>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host4>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host5>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host6>. from <axfr-host>:53
[ERROR] plugin/file: Failed to transfer `<host7>.' from "<axfr-host>:53": read tcp <local-ip>:33580-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host8>.' from "<axfr-host>:53": read tcp <local-ip>:33602-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host9>.' from "<axfr-host>:53": read tcp <local-ip>:33596-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host10>.' from "<axfr-host>:53": read tcp <local-ip>:33598-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host11>.' from "<axfr-host>:53": read tcp <local-ip>:33590-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host12>.' from "<axfr-host>:53": read tcp <local-ip>:33610-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host13>.' from "<axfr-host>:53": read tcp <local-ip>:33586-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host14>.' from "<axfr-host>:53": read tcp <local-ip>:33608-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host15>.' from "<axfr-host>:53": read tcp <local-ip>:33582-><axfr-host>:53: i/o timeout
[INFO] plugin/file: Transferred: <host16>. from <axfr-host>:53
```

The DNS provider is DNSimple.

**Comment by itssimple** [comment]
Asked in Slack and got the reply that it will only try once per domain, and then get stuck waiting for updates, forever.

**Comment by chrisohaver** [comment]
If CoreDNS receives a NOTIFY for a zone, it will try to transfer the zone in again.  So as a clumsy workaround, I think you could craft NOTIFY queries with appropriate serial for each affected zone and send them to CoreDNS.  However, it would be much more convenient if the secondary plugin kept trying the initial transfer until successful.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[coredns/coredns] plugin/secondary:..." ]
>Is there a way to configure the secondary-plugin to do automatic retries if it
>fails to load a zone-file?
>Or is there some way that I can trigger a reload on zones that failed?

I don't understand the problem. The code will retry until something is transferred...

**Comment by itssimple** [comment]
> I don't understand the problem. The code will retry until something is transferred...

Reason I'm asking is because the domains that failed with `i/o timeout` only got SERVFAIL as response even after letting the server run for an extended time.

And I never saw any of the failed zones being marked as Transferred in the log either.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] plugin/second..." ]
>    I don't understand the problem. The code will retry until something is
>    transferred...
>
>Reason I'm asking is because the domains that failed with i/o timeout only got
>SERVFAIL as response even after letting the server run for an extended time.
>
>And I never saw any of the failed zones being marked as Transferred in the log
>either.

ah, yes. OK. TransferIn() does stop after all masters are tried. Something like this
should probably help:

~~~
diff --git plugin/secondary/setup.go plugin/secondary/setup.go
index c0914727..3d6a0c07 100644
--- plugin/secondary/setup.go
+++ plugin/secondary/setup.go
@@ -1,10 +1,13 @@
  package secondary

  import (
+       "time"
+
         "github.com/coredns/caddy"
         "github.com/coredns/coredns/core/dnsserver"
         "github.com/coredns/coredns/plugin"
         "github.com/coredns/coredns/plugin/file"
+       "github.com/coredns/coredns/plugin/pkg/log"
         "github.com/coredns/coredns/plugin/pkg/parse"
         "github.com/coredns/coredns/plugin/pkg/upstream"
  )
@@ -24,7 +27,14 @@ func setup(c *caddy.Controller) error {
                         c.OnStartup(func() error {
                                 z.StartupOnce.Do(func() {
                                         go func() {
-                                               z.TransferIn()
+                                               for {
+                                                       err := z.TransferIn()
+                                                       if err == nil {
+                                                               break
+                                                       }
+                                                       log.Warningf("All masters failed to transfer: %s, retrying in 10s", err)
+                                                       time.Sleep(10 * time.Second)
+                                               }
                                                 z.Update()
                                         }()
                                 })
~~~
