### ISSUE TITLE
AWS EKS - dial tcp i/o timeout

### ISSUE THREAD

**Issue by mariojacobo** [coredns/coredns#4662]
**What happened**:

Some coredns PODs randomly give errors like these on AWS EKS : 

ERROR] plugin/errors: 2 xxxxxxxxxxxxxx.eu-west-3.rds.amazonaws.com. AAAA: dial tcp 10.28.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 xxxxxxxxxxxxxxx.eu-west-3.rds.amazonaws.com. AAAA: dial tcp 10.28.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 xxxxxxxxxxxxxxxxxxxxx.eu-west-3.rds.amazonaws.com. AAAA: dial tcp 10.28.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 xxxxxxxxxxxxxxxxxxxxx.eu-west-3.rds.amazonaws.com. AAAA: dial tcp 10.28.0.2:53: i/o timeout

**What you expected to happen**:
no timeouts; the interesting part is that specific IP 10.28.0.2 is nowhere to be found; the kube-dns service is always in the 172.XXX range.  

The fix for us was to switch the coredns deployment to a daemonSet instead; we did noticed that 2 PODs were regularly assigned to the same node, totally ignoring their podAntiAffinity which specifically prevents 2 coredns PODs to be assigned to the same node. 

**How to reproduce it (as minimally and precisely as possible)**:
N/A, using vanilla EKS cluster 1.16 

**Anything else we need to know?**:
we saw the issue while performing load tests, during increased traffic. 

**Environment**:

- the version of CoreDNS: 1.6.6
- Kubernetes version: 1.16.12
- Corefile:    
.:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      upstream
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): 
- Others:

**Comment by chrisohaver** [comment]
Those errors are CoreDNS timing out trying to connect to the upstream DNS server (10.28.0.2).

**Comment by mariojacobo** [comment]
in the end we went with nodelocaldns (https://www.vladionescu.me/posts/eks-dns/) which has fixed all the issues.
