### ISSUE TITLE
HINFO: unreachable backend: read udp 10.244.0.14:34014->168.63.129.16:53: i/o timeout

### ISSUE THREAD

**Issue by jsoule6** [coredns/coredns#4666]
Issue: CoreDNS cannot reach external DNS (Azure) and pods cannot connect to CoreDNS address.

1. Check CoreDNS service

`kubectl get svc -n kube-system`

![image](https://user-images.githubusercontent.com/53154637/120900908-914fe300-c605-11eb-96bc-38cc17fcf17b.png)

2. Check CoreDNS pod endpoints

`kubectl get ep -n kube-system`

![image](https://user-images.githubusercontent.com/53154637/120900950-cb20e980-c605-11eb-957a-eef4ce171973.png)

3. My Node DNS config:

![image](https://user-images.githubusercontent.com/53154637/120901008-2f43ad80-c606-11eb-97e0-5413a2b70899.png)

4. My DNS Config from Pod:

![image](https://user-images.githubusercontent.com/53154637/120901070-8d709080-c606-11eb-8507-ce9c6706dad1.png)

5. Check CoreDNS pod logs

![image](https://user-images.githubusercontent.com/53154637/120901095-b42ec700-c606-11eb-8164-9eb66898152e.png)

It's clear that the CoreDNS **pod ip** cannot connect to **node DNS address**. 

Any help on this would be greatly appreciated. This had been working fine up until yesterday morning and we are really not sure what changed...

**Comment by jsoule6** [comment]
I changed CoreDNS to use 8.8.8.8 as the DNS instead and the same result:

![image](https://user-images.githubusercontent.com/53154637/120901708-83509100-c60a-11eb-9b91-07b130dde77f.png)

**Comment by chrisohaver** [comment]
> Issue: CoreDNS cannot reach external DNS (Azure) and pods cannot connect to CoreDNS address.

Both of those symptoms (Pods cannot reach external IPs, and Pods cannot reach to Cluster IP services) suggest broader networking problems in your cluster.

I'd recommend following general Kubernetes network troubleshooting.

**Comment by chrisohaver** [comment]
e.g. For troubleshooting why a Pod cannot reach a Service: https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by jsoule6** [comment]
We were able to resolve this issue. Unfortunately, a setting in /etc/sysctl.conf was changed in an attempt to harden the environment. net.ipv4.ip_forward=0 was the setting that broke ip forwarding and thus the networking.
