### ISSUE TITLE
UDP connections don't seem to get closed

### ISSUE THREAD

**Issue by kdima** [coredns/coredns#467]
After 1-3 hours of running coredns seems to accumulate a bunch about 28k of not closed UDP connections. 
Here is the part of the Corefile that sets up proxying. These addresses are not mentioned anywhere else in the corefile. 
```
proxy . 169.254.169.254:53 8.8.8.8:53
```

Open connections
```
lsof -p COREDNS_PID
UDP coredns_server_ip:58421->8.8.8.8:domain
UDP coredns_server_ip:40939->8.8.8.8:domain
UDP coredns_server_ip:32799->169.254.169.254:domain
UDP coredns_server_ip:40991->8.8.8.8:domain
UDP coredns_server_ip:57377->8.8.8.8:domain
UDP coredns_server_ip:49185->169.254.169.254:domain
UDP coredns_server_ip:33846->169.254.169.254:domain
```

Metrics screenshot:
![image](https://cloud.githubusercontent.com/assets/4558851/21608861/fed29bc2-d1b6-11e6-90e4-e749b87baece.png)

So it really looks like it is something in proxy middleware.

**Comment by miekg** [comment]
The calling code is fairly trivial: https://github.com/miekg/coredns/blob/master/middleware/proxy/client.go#L33
This call `Close` on the underlaying `net.Conn`

But keeping 28K of them open is weird.

**Comment by johnbelamaric** [comment]
If there is a hard crash (say, a SEGV) in the call to c.Exchange, the go routine will terminate and the die silently. Could that leave it open?

**Comment by kdima** [comment]
Do we need to set the Read and Write timeouts on that connection? Because that is what happens in here github.com/miekg/dns/client.go:210

**Comment by kdima** [comment]
So I have just checked that theory @johnbelamaric I have inserted a panic here `github.com/miekg/coredns/middleware/proxy/client.go:61`

and I can see that the connections stay opened. Also panic recover does not seem to catch the panic i.e. I don't see the panic message I have inserted.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] UDP connections..." ]
>Do we need to set the Read and Write timeouts on that connection? Because that is what happens in here github.com/miekg/dns/client.go:210

Hmm... Isn't there a default that closes it after X minutes?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] UDP connections..." ]
>If there is a hard crash (say, a SEGV) in the call to c.Exchange, the go routine will terminate and the die silently. Could that leave it open?

panic should show up in the logs when you log errors.

**Comment by johnbelamaric** [comment]
Oh, so just "log stdout" won't do it? I have to have something else in my Corefile?

**Comment by johnbelamaric** [comment]
I see it's the errors middleware. Cool.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] UDP connections..." ]
>I see it's the errors middleware. Cool.

So we crash and the go routines lingers? :-(

**Comment by johnbelamaric** [comment]
go routine crashes and won't get rescheduled so the connection never gets closed. I guess it doesn't clean up stuff when it crashes. Wonder if the same happens for memory? Maybe since it's garbage collected it gets cleaned up. But other resources are leaked.

**Comment by kdima** [comment]
Also maybe worth updating documentation examples to include `errors stdout` in all snippets? Because currently it is only in dnssec examples.

**Comment by miekg** [comment]
I need to touch this code anyway for: #466 and maybe moving *httproxy* to it as well (related to John's work in #463)

Yes, docs can be improved (the *error* README.md still has TODOs in them), but littering every example with the `errors` goes a little bit too far.
The recover behavior of CoreDNS also needs to be documented, I've tripped over this myself a few times. 
And, also, also; maybe a dev-build can disable this, so you get a nice stack trace instead of a recover.

**Comment by miekg** [comment]
@kdima do you see crashes?

**Comment by kdima** [comment]
We have added errors middleware waiting for the issue to reappear. I was wrong with my original timeline it seems to take about 12 hours of running before it happens.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] UDP connections..." ]
>We have added errors middleware waiting for the issue to reappear. I was wrong with my original timeline it seems to take about 12 hours of running before it happens.

If every crash leaves a connection open and you have 28K open connection, you
should see 38 crashes per minute...

**Comment by kdima** [comment]
Based on the graphs we are seeing it looks like a spiral of doom. I.e. it operates perfectly for 10-12 hours and then starts leaving opened connections at the rate one per 8 or per 2 seconds. This looks like a retry loop.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] UDP connections..." ]
>Based on the graphs we are seeing it looks like a spiral of doom. I.e. it operates perfectly for 10-12 hours and then starts leaving opened connections at the rate one per 8 or per 2 seconds. This looks like a retry loop.

that explanation makes more sense. Prolly a network hiccup (If seen similar
things in *httpproxy* which re-uses some of the code). I suspect this related
to the code that marks an upstream unhealthy and indeed the retry behavior
there.

Pondering if I can come up with a good test for this.

**Comment by miekg** [comment]
I'm thinking of adding an *erratic* middleware that allows you to fiddle with ways to respond. I.e. delay a response by time X, or drop 1/x responses. This will be super useful in tests like these.

**Comment by johnbelamaric** [comment]
Yes, that sounds really useful.

In our testing we often use a super-simple server that just always returns a simple response for every query. This is used as an upstream for scale testing. Probably could serve that function as well. A sort of "test" middleware I guess.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] UDP connections..." ]
>Yes, that sounds really useful.
>
>In our testing we often use a super-simple server that just always returns a simple response for every query. This is used as an upstream for scale testing. Probably could serve that function as well. A sort of "test" middleware I guess.

Ack, will create something simple for a start: It will echo back the request
(maybe something ala the *whoami* middleware), or something static
, but with options to do other stuff:

~~~
erratic {
    drop 1/3
}
~~~
will drop 1 out of 3. `drop 0/3` will mimic your middleware.
