### ISSUE TITLE
Debug plugin option ignored in CoreDNS 1.8.4

### ISSUE THREAD

**Issue by rschone** [coredns/coredns#4674]
**What happened**:
When CoreDNS version bumped up from 1.6.1 to 1.8.4, debug outputs are not written to the output, although debug option is present in the configuration. 

**What you expected to happen**:
Debug outputs written to the output when debug plugin is active.

**How to reproduce it (as minimally and precisely as possible)**:
We've experienced it with `dig @localhost -p 40000 google.com` when logging debug outputs with zipkin trace ids in internal logging plugin, but it should be reproducible with any debug logging using coredns@1.8.4/plugin/pkg/log/plugin.go debug() or debugf() function.

**Anything else we need to know?**:
coredns@1.8.4/plugin/pkg/log/plugin.go debug() or debugf() functions use `if !D.Value()` to ignore debug outputs when debug plugin is not active. **Having debug plugin active in Corefile for several ports in the same configuration block is not reflected, D.Value() == false (see Corefile example).** Seems like the configuration is not being read properly.

**Environment**:

- the version of CoreDNS: 1.8.4
- Corefile:

.:8000 {
  health
  pprof
}

.:40000, .:40001, .:40002, .:40003 {
  error_trace
  debug
  forward . 64.6.64.6 8.8.8.8
  log . "plugin/log: [{>id}] '{type} {class} {name} {proto}:{port} {size} {>do} {>bufsize}' {rcode} {>rflags} {rsize} {duration}"
  ready
  any
}

**Comment by rschone** [comment]
Possible workaround: split configuration for different ports into separate configuration blocks.

**Comment by chrisohaver** [comment]
I was unable to reproduce this issue with built in plugins.

With the following ...
```
.:5397 .:5398 .:5399 {
  debug
  local
}
```

... queries for `localhost.test.` result in logged debug statements regardless of which port is queried.

What is `error_trace` ?

**Comment by rschone** [comment]
Sorry, error_trace is a custom plugin in which this bug can be simply reproduced:

```go
package errortrace

import (
	"context"

	"github.com/coredns/coredns/plugin"
	"github.com/coredns/coredns/plugin/pkg/log"
	"github.com/miekg/dns"
)

type errorHandler struct {
	Next plugin.Handler
}

// Name returns the plugin name.
func (h *errorHandler) Name() string { return pluginName }

// ServeDNS serves the DNS request.
func (h *errorHandler) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) (rcode int, err error) {
	var a log.P
	a.Debugf("Do you see the DEBUG OUTPUT?")

	return plugin.NextOrFailure(h.Name(), h.Next, ctx, w, r)
}
```

**Comment by chrisohaver** [comment]
That code works for me.  All ports display debug output.  I did infer the missing code not given above (plugin registration etc).

**Comment by rschone** [comment]
[coredns-corefile-bug.zip](https://github.com/coredns/coredns/files/6628919/coredns-corefile-bug.zip)

To reproduce the bug, run the following
1. extract the attached archive file and move into the directory
2. build the application with `make`
3. execute `bin/bug`
4. in different terminal execute `dig @localhost -p 40000 google.com`
5. on the output of the bug application, there shall be 'DEBUG 2' as `debug` plugin is enabled, but it is not

go: 1.16
coredns: 1.8.4
platform: macos

**Comment by chrisohaver** [comment]
I added your plugin code to `plugin/` and updated`plugin.cfg` in CoreDNS 1.8.4 , compiled it using the default Makefile (not yours) and it works as expected.  I see debug output.

FWIW - Your Corefile listens to 30000, not 40000 as queried in your instructions.

**Comment by rschone** [comment]
Suppose: Corefile contains configuration block activating `debug` and is defined for ports .:40000, .:40001, .:40002

Now what happens in the code: 

- register.go, func InspectServerBlocks initializes Config structure with the default Debug = false
- Debug plugin in its setup sets up `config.Debug = true`
- caddy.go, func executeDirectives calls setup of debug plugin, but the condition `if j > 0 {continue}` allows to call it only for the first server in the group; if we have configuration block for several ports e.g. .:40000, .:40001, .:40002, the setup function is called only for the first server (.:40000); that means, config.Debug for .:40001 and .:40002 stays FALSE
- server.go, func NewServer calls `log.D.Set()` or `log.D.Clear()` based on the specific server config; so it call `log.D.Set()` for .:40000 and follows with `log.D.Clear()` for .:40001 and then `log.D.Clear()` for .:40002

=> so finally the debug flag  in  log is FALSE, although it should be TRUE

**Comment by chrisohaver** [comment]
Is `if j > 0 {continue}` referring to: https://github.com/coredns/caddy/blob/master/caddy.go#L651-L654 ?
If so, that was added in coredns/caddy@v1.1.1, CoreDNS 1.8.4 uses coredns/caddy@v1.1.0.

The changes in coredns/caddy@v1.1.1 are part of https://github.com/coredns/coredns/pull/4593, which isn't merged yet.

**Comment by rschone** [comment]
THANKS Chris, that's it! We have github.com/coredns/caddy v1.1.1 referred explicitly in go.mod.
When I removed it and run `go mod tidy`, v1.1.0 has been added and the application logs debug messages like a charm :)
Seems that #4593 will have to be polished a little bit before merge.

**Comment by miekg** [comment]
nice find @rschone 
looks to me that #4593 will be fundamentally incompatible ...  I had feared that, but it looks sane...

**Comment by chrisohaver** [comment]
> Seems that #4593 will have to be polished a little bit before merge.

How so? #4593 is required to work with coredns/caddy@1.1.1. If you try to use 1.1.1 without the code in that PR, it is expected that stuff will break.

**Comment by chrisohaver** [comment]
Just as a sanity check, I tested PR #4593, and debug works as expected with that PR.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] Debug plugin ..." ]
>    Seems that #4593 will have to be polished a little bit before merge.
>
>How so? #4593 is required to work with ***@***.*** If you try to use
>1.1.1 without the code in that PR, it is expected that stuff will break.

huh, debug isn't set because the new code exits after the first zone?

Or do you mean to tell that because the other half in coredns isn't merged you get this
breakage now?

Can we at least add a test that shows debug being set in all 4 (or whatever) zones in the
PR?

**Comment by chrisohaver** [comment]
> Or do you mean to tell that because the other half in coredns isn't merged you get this
breakage now?

Yes - but depends on what you mean by "now" - 1.8.4 doesn't use 1.1.1, neither does master ... so this breakage doesn't exists "now" in 1.8.4 or in master.  It's only an issue if you update caddy to 1.1.1 in a custom build of coredns (as was the case here).

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] Debug plugin ..." ]
>    Or do you mean to tell that because the other half in coredns isn't merged
>    you get this
>    breakage now?
>
>Yes - but depends on what you mean by "now" - 1.8.4 doesn't use 1.1.1, neither
>does master ... so this breakage doesn't exists "now" 1.8.4 or in master. It's
>only an issue if you update caddy to 1.1.1 in a custom build of coredns (as was
>the case here).

ack, understood. A test might still be good though; but with debug that might be hard ish.

**Comment by chrisohaver** [comment]
> but with debug that might be hard ish.

Yeah - looking into it.  A unit test is tricky, since MakeServers (the part that ensures debug and other options are copied to all configs) is tightly intertwined with caddy's private components.

A integration test is also tricky, since we don't have access into the Config structs at that level, so we'd need to trap and parse log output.
