### ISSUE TITLE
Does route53 plugin supports creating record set automatically for k8s ingress object

### ISSUE THREAD

**Issue by Swathi2222** [coredns/coredns#4677]
Want to know what are usecases does route53 solves ? Does route53 plugin supports creating record set automatically for k8s ingress object.

**Comment by yongtang** [comment]
@lillytest The `Examples` sections consist of several Corefile that can be used. Will that be good enough? Or what types of usage scenarios are you looking for?

**Comment by lillytest** [comment]
Main issue is external DNS, Currently we are creating route53 urls through separate jenkins jobs. so the maintenance is problem adding or deleting.

**Comment by Swathi2222** [comment]
@yongtang  Currently we are creating route53 urls through separate jenkins jobs. so the maintenance is problem adding or deleting. We want to see if this will be solved by route53 plugin.
  if it supports creating record set automatically for k8s ingress object, just like what an k8s external dns is doing (https://github.com/kubernetes-sigs/external-dns). this tools continuously checks for declared sources in external dns deployment manifest file that when noticed, it will create DNS record in your DNS service (route53)

Please help

**Comment by yongtang** [comment]
@lillytest At the moment route53 plugin in CoreDNS is performing ready-only operations on persistent storage. We don't update record. (This applies to other CoreDNS plugins as well).

**Comment by Swathi2222** [comment]
@yongtang  Thank you
