### ISSUE TITLE
transfer's to does not allow IPv6 CIDR address

### ISSUE THREAD

**Issue by telmich** [coredns/coredns#4690]
**What happened**:

The documentation contradicts the implementation regarding to the **to** statement in the **transfer module**.

Using

        transfer {
          to 2a0a:e5c0::/29
          to 2a01:4f8:150:7092::2/64
        }

I get the error message

```
plugin/transfer: must specify an IP address: `2a0a:e5c0::/29'
```

**What you expected to happen**:

Support AXFR to hosts coming from 2a0a:e5c0::/29.

**How to reproduce it (as minimally and precisely as possible)**:

See above. 

**Anything else we need to know?**:

The documentation says:

```
to ADDRESS… The hosts transfer will transfer to. Use * to permit transfers to all addresses. ADDRESS must be denoted in CIDR notation (e.g., 127.0.0.1⁄32) or just as plain addresses. to may be specified multiple times.
```

Above is clearly cidr and the intent is to allow AXRFs from the given networks.

**Environment**:

- the version of CoreDNS: k8s.gcr.io/coredns/coredns:v1.8.0
- Corefile: See above
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
There's a "TODO" comment in the code to add support for CIDRs - currently only IPs are supported (i.e. the docs are wrong).
I'll go ahead and add this now, instead of adjusting the docs to match was it currently implements.

**Comment by chrisohaver** [comment]
There are two ways to "fix" this.  I've opened a PR for either way, only one should be merged:

1. Add support for CIDR notation in the `to` option for _transfer_. #4698
2. Remove CIDR as a valid input for `to` from the README, and document how to use _acl_ plugin to do accomplish this. #4711

**Comment by telmich** [comment]
From my point of view #4698 is making much more sense
