### ISSUE TITLE
Clarify `*` (wildcard use) in CoreDNS

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#470]
SkyDNS introduced to ability to use a wildcard label in a query(!) to signify "I don't care about the value of this label". This was carried forward in CoreDNS.
While reviewing PR #464 I noticed the following being used as a wildcard label:
`Qname: "_*._*.bogusservice.test-1.svc.cluster.local.", Qtype: dns.TypeSRV`

Which adds `_*` as a wildcard label as well. We should see if this is needed and if so clarify the README and implement this in the *etcd* middleware as well.

**Comment by miekg** [comment]
Comment from @chrisohaver 
> @miekg - When working with wild cards, i noticed some wild card unit tests which suggest that the prior implementation for * was incorrect. I have not changed the behavior. However, which of the following is the expected behavior for * wild cards?

> As implemented: One or more * present in a field will make that whole field wild, other characters ignored. e.g. delicious*taco* will match anything, including motor-oil
Or as one might expect wild cards to normally work: e.g. delicious*taco* matching delicious-beef-taco and delicious-taco-boat

**Comment by chrisohaver** [comment]
Can we disable the comment markup?  It's super annoying.  The copy-pasted comment above is unintelligible...

**Comment by chrisohaver** [comment]
The question is:
Should `*-apple` match `red-apple` and not `orange-orange`? This seems to be what one would expect.
However, as currently implemented, the presence of a `*` means that the entire field is wild, so `*-apple` is functionally equivalent to `*`, which means the expression matches both `red-apple` and `orange-orange`.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] Clarify `*` (wi..." ]
>The question is:
>Should `*-apple` match `red-apple` and not `orange-orange`?
>However, as currently implemented, the presence of a `*` means that the entire field is wild, so `*-apple` is functionally equivalent to `*`, which means the expression matches both `red-apple` and `orange-orange`.

The wildcard use should work exactly as the service side wildcard that we have
in the dns - so `*` will only work when it is the only thing in the label. The
only change made is that we allow multiple `*`-labels AFAICS.
