### ISSUE TITLE
when no response is written to client, prometheus plugin reports it as NOERROR response

### ISSUE THREAD

**Issue by Tantalor93** [coredns/coredns#4726]
**What happened**:
when no response is written from upstream plugins (for example due to timeout in forward plugin) the prometheus plugin reports it as NOERROR (successful) response

```
curl http://localhost:9153/metrics | grep coredns_dns_responses_total

coredns_dns_responses_total{rcode="NOERROR",server="dns://:53",zone="."} 2
```

**What you expected to happen**:
I would expect that it will be reported as SERVFAIL as it is returned to client as SERVFAIL
```
coredns_dns_responses_total{rcode="SERVFAIL",server="dns://:53",zone="."} 2
```

**How to reproduce it (as minimally and precisely as possible)**:
run CoreDNS with Corefile (the invalid IP in forward plugin is there on purpose to better simulate errors)
```
.:53 {
    forward . 9.8.7.6
    prometheus []:9153
}
```

run dig
```
dig @127.0.0.1 9gag.com
```

get metrics and look at the coredns_dns_responses_total metric
```
curl http://localhost:9153/metrics | grep coredns_dns_responses_total

# HELP coredns_dns_responses_total Counter of response status codes.
# TYPE coredns_dns_responses_total counter
coredns_dns_responses_total{rcode="NOERROR",server="dns://:53",zone="."} 2
```

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.4 (latest)
- Corefile:
```
.:53 {
    forward . 9.8.7.6
    prometheus []:9153
}
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by miekg** [comment]
ok, this makes sense as an issue
