### ISSUE TITLE
Override of forward in AKS cluster

### ISSUE THREAD

**Issue by san360** [coredns/coredns#4729]
I would like to override the forward configuration of coredns. By default in AKS it's set up as below

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        ready
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import custom/*.override
    }
    import custom/*.server
kind: ConfigMap
```

I used coredns-custom configmap to override the forward settings as below

```
apiVersion: v1
data:
  Corefile.override: |
        forward . 10.1.2.3
kind: ConfigMap
```

I get below error in coredns log.

```
coredns-75b9ff5757-7fmj7 coredns [WARNING] No files matching import glob pattern: custom/*.server
coredns-75b9ff5757-7fmj7 coredns [INFO] Reloading
coredns-75b9ff5757-7fmj7 coredns [WARNING] No files matching import glob pattern: custom/*.server
coredns-75b9ff5757-7fmj7 coredns [ERROR] Restart failed: plugin/forward: this plugin can only be used once per Server Block
coredns-75b9ff5757-7fmj7 coredns [ERROR] plugin/reload: Corefile changed but reload failed: starting with listener file descriptors: plugin/forward: this plugin can only be used once per Server Block
coredns-75b9ff5757-46n9w coredns [WARNING] No files matching import glob pattern: custom/*.override
coredns-75b9ff5757-46n9w coredns [WARNING] No files matching import glob pattern: custom/*.server
coredns-75b9ff5757-7fmj7 coredns [WARNING] No files matching import glob pattern: custom/*.server
coredns-75b9ff5757-46n9w coredns [WARNING] No files matching import glob pattern: custom/*.server
coredns-75b9ff5757-46n9w coredns [INFO] Reloading
coredns-75b9ff5757-46n9w coredns [WARNING] No files matching import glob pattern: custom/*.server
coredns-75b9ff5757-46n9w coredns [ERROR] Restart failed: plugin/forward: this plugin can only be used once per Server Block
coredns-75b9ff5757-46n9w coredns [ERROR] plugin/reload: Corefile changed but reload failed: starting with listener file descriptors: plugin/forward: this plugin can only be used once per Server Block
coredns-75b9ff5757-7fmj7 coredns [WARNING] No files matching import glob pattern: custom/*.server
coredns-75b9ff5757-46n9w coredns [WARNING] No files matching import glob pattern: custom/*.server
```
What's the best way to override the forward configuration in coredns running inside AKS cluster?

I cannot use subdomains as we have multiple domains we would like to be resolvable vis coredns and the config is not scalable.

**Comment by chrisohaver** [comment]
>coredns-75b9ff5757-46n9w coredns [ERROR] Restart failed: plugin/forward: this plugin can only be used once per Server Block

IMO, the name "override" is misleading.  The `import` directive just appends, it doesn't replace any existing plugins.  So, in doing what you have done above, you end up with two _forward_ declarations in a single server block, which is not allowed in CoreDNS.

The only way to change the forward options in the Corefile is to actually change the Corefile (if/how AKS permits that, I don't know).

**Comment by san360** [comment]
> > coredns-75b9ff5757-46n9w coredns [ERROR] Restart failed: plugin/forward: this plugin can only be used once per Server Block
> 
> IMO, the name "override" is misleading. The `import` directive just appends, it doesn't replace any existing plugins. So, in doing what you have done above, you end up with two _forward_ declarations in a single server block, which is not allowed in CoreDNS.
> 
> The only way to change the forward options in the Corefile is to actually change the Corefile (if/how AKS permits that, I don't know).

The AKS does not allow change in coredns default configuration file. I had an understanding that override will overwrite the configurations.

**Comment by cedricroijakkers** [comment]
A little late to the party, but I would like to chime in with a solution that actually works (in 2025 anyway). I have the problem that the coredns in Azure AKS does not do DNSSEC (because the upstream server configured in `/etc/resolv.conf` on the host does not do DNSSEC), while my application requires it. So I managed to override coredns with the `coredns-custom` ConfigMap mechanism which AKS provides, to use Google with the following ConfigMap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  Corefile.override: |
        forward . 8.8.8.8 8.8.4.4
```

Note the spacing and the name `Corefile.override`, it needs to be exactly like this, otherwise it will not work. After this change, my coredns started supporting DNSSEC.
