### ISSUE TITLE
What is the default name server in CoreDNS ?

### ISSUE THREAD

**Issue by archit** [coredns/coredns#4730]
In the documentation for CoreDNS, there is no clear indication of what name server does CoreDNS use, when resolving DNS queries for names not in its cache? In a Kubernetes environment, I'm trying to figure out, what default DNS name server does CoreDNS use when forwarding requests for names not in its cache, and not in the Kubernetes cluster domain.

**Comment by Tantalor93** [comment]
Hello, I am not maintainer, but I’ll try to answer. The upstream DNS resolving functionality is strongly dependant on what CoreDNS plugins are enabled and how are they configured (for example how the forward plugin is configured, whether kubernetes plugin is enabled etc.).

 If you are interested how the CoreDNS is configured in kubernetes, I suggest reading https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options. There you can find this info for default kubernetes CoreDNS configuration
`Any queries that are not within the cluster domain of Kubernetes will be forwarded to predefined resolvers (/etc/resolv.conf). `

**Comment by archit** [comment]
@Tantalor93  But for the forward plugin, I'm unsure which /etc/resolv.conf file they're referring to. Because when I `cat /etc/resolv.conf` on my Kubernetes pods, I only see it pointing back to CoreDNS Service in Kubernetes. So the queries will go to CoreDNS, and if CoreDNS doesn't have a name lookup in its cache, it should forward it to some place by default. That default name server value is what I'm looking for.

**Comment by chrisohaver** [comment]
@archit, CoreDNS pods use a different dnsPolicy than the other pods you observed. A coredns pod resolv.conf is copied from the node they are hosted on. See: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Comment by archit** [comment]
hey @chrisohaver based on your description, when I checked the node's `/etc/resolv.conf` it points to `systemd-resolved`

**Comment by chrisohaver** [comment]
> hey @chrisohaver based on your description, when I checked the node's /etc/resolv.conf it points to systemd-resolved

For systems with a local resolver, _kubelet_ should be configured to use an alternate `resolv.conf`. ... see https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues. kubelet determines which host resolv.conf file is used when creating a pod.
