### ISSUE TITLE
corefile forward config not working with 1.8.3

### ISSUE THREAD

**Issue by ssubramanian123** [coredns/coredns#4750]
I have updated my cluster from k8s 1.17.6 to k8s 1.21.2.  With this update my coredns also got updated from 1.6.3 to 1.8.3.

In 1.6.3 i had the corefile forward config as below and it was working fine, but with 1.8.3 it is not working. Not sure what I am missing.

```
 Corefile: |-
    myhost.com {
      forward . 10.100.30.100
      log
    } 
    test.myhost.com {
      forward . 10.230.20.100
      log
    } 
    .:53 {
        errors
        health {
        
    ```

Can anyone suggest what I am missing with latest version?

**Comment by chrisohaver** [comment]
What precisely isn’t working?

**Comment by ssubramanian123** [comment]
@chrisohaver  from my application pod i am trying to resolve the hostname myservice.test.myhost.com 

But it is not able to resolve the hostname.

this hostname is specific to our internal system which resolves with specific nameserver configured in corefile. It was working fine in 1.6.3

**Comment by chrisohaver** [comment]
The Corefile looks correct. There aren’t any changes between those versions that would affect forward in that configuration.

Any errors in Coredns logs?
What is logged for the failed query?

**Comment by ssubramanian123** [comment]
@chrisohaver  in coredns log, i see these errors.  It is one of my nameserver IP. I had two internal nameserver and one is not working so removed it. Still I am having the same issue

```
[ERROR] plugin/errors: 2 106.9.228.47.in-addr.arpa. PTR: dial tcp 10.32.xx.xxx:53: i/o timeout
[ERROR] plugin/errors: 2 106.9.228.47.in-addr.arpa. PTR: dial tcp 10.32.xx.xxx:53: i/o timeout
[ERROR] plugin/errors: 2 106.9.228.47.in-addr.arpa. PTR: dial tcp 10.32.xx.xxx:53: i/o timeout
[ERROR] plugin/errors: 2 172.8.228.47.in-addr.arpa. PTR: dial tcp 10.32.xx.xxx:53: i/o timeout
[ERROR] plugin/errors: 2 172.8.228.47.in-addr.arpa. PTR: dial tcp 10.32.xx.xxx:53: i/o timeout
[ERROR] plugin/errors: 2 94.9.228.47.in-addr.arpa. PTR: dial tcp 10.32.xx.xxx:53: i/o timeout
```

**Comment by zouyee** [comment]
Is the address (10.100.30.100)  reachable?

**Comment by chrisohaver** [comment]
> i am trying to resolve the hostname myservice.test.myhost.com 

What DNS tool are you using to make the query? What is the response for the failed query?

The errors you shared form the log do not appear to be related to the `myservice.test.myhost.com` query.

> Is the address (10.100.30.100) reachable?

 If `10.100.30.100` is unreachable, there will be errors for queries in the `test.myhost.com.` domain. e.g. 
```
[ERROR] plugin/errors: myservice.test.myhost.com. A: dial tcp 10.100.30.100:53: i/o timeout
```

**Comment by ssubramanian123** [comment]
@chrisohaver  @zouyee  I think I found the issue. Dont know how to fix it. I have Kops based kubernetes cluster 1.21.2 version.   I have fixed above error by updating right IP. Above timeout error got fixed, but still i was having issue. 

When I looked further into my application pod, it has nameserver as some IP `169.254.20.10` instead of coredns service ip. Am I missing anything in my kubernetes config.


```
cat /etc/resolv.conf 
search ns-dev.svc.cluster.local svc.cluster.local cluster.local ec2.internal
nameserver 169.254.20.10
options ndots
```

**Comment by chrisohaver** [comment]
> When I looked further into my application pod, it has nameserver as some IP 169.254.20.10 instead of coredns service ip. Am I missing anything in my kubernetes config.

The IP placed in `resolv.conf` not controlled by CoreDNS.  It is a `kubelet` configuration.

(edit: assuming your application pod is using dnsPolicy "clusterFirst", which is the default)

**Comment by ssubramanian123** [comment]
@chrisohaver  yes i use dnspolicy as clusterfirst `dnsPolicy: ClusterFirst` 

Not sure why kubelet get this new IP `nameserver 169.254.20.10` in this version.

**Comment by johnbelamaric** [comment]
Looks like the NodeLocalDNS address.

**Comment by ssubramanian123** [comment]
Thank you all. I found this NOdeLocalDNS IP is the culprit. After i disabled NodeLocal DNS, it started working. I will close this ticket. I really appreciate everyone helps.
