### ISSUE TITLE
CoreDNS 1.8.3 cannot resolve headless kubernetes services

### ISSUE THREAD

**Issue by abdennour** [coredns/coredns#4758]
**What happened**:
i've upgraded my EKS kubernetes cluster from 1.19 to 1.20.
The upgrade process includes upgrading CoreDNS from 1.8.0 to 1.8.3
I did.
After sometimes, pods which communicates with other pods thru headless services cannot more communicate. 

**What you expected to happen**:
I expected that CoreDNS 1.8.3 is backward compatible with CoreDNS 1.8.0

**How to reproduce it (as minimally and precisely as possible)**:
- Create kubernetes cluster 1.19 on AWS EKS
- Make sure that coredns deployment in kube-system has the version 1.8.0
- Deploy redis, Kafka or any app (helm chart) includes headless service
- Upgrade the k8s cluster to 1.20
- patch the coredns deployment in kube-system from v1.8.0 to 1.8.3
- the headless FQDN is not resolvable
```console
1:S 16 Jul 2021 15:39:33.852 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 16 Jul 2021 15:39:34.854 * Connecting to MASTER redis-master-0.redis-headless.redis-cluster.svc.cluster.local:6379
1:S 16 Jul 2021 15:39:34.859 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 16 Jul 2021 15:39:35.861 * Connecting to MASTER redis-master-0.redis-headless.redis-cluster.svc.cluster.local:6379
1:S 16 Jul 2021 15:39:35.865 # Unable to connect to MASTER: Resource temporarily unavailable
```

**Anything else we need to know?**:
https://github.com/bitnami/charts/issues/4830

**Environment**:

- the version of CoreDNS: 1.8.3
- Corefile: 
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): kubernetes 1.20
- Others:

**Comment by chrisohaver** [comment]
Do you have endpointslice api list and watch enabled for coredns?

**Comment by chrisohaver** [comment]
From https://github.com/coredns/coredns/blob/master/notes/coredns-1.8.1.md …

> If using the kubernetes plugin for a Kubernetes cluster >= 1.19, CoreDNS must be granted list and watch access to endpointslices.

**Comment by chrisohaver** [comment]
Please re-open if you find this was not caused by coredns not being granted list/watch for endpointslices.
