### ISSUE TITLE
Installing kubernetai plugin

### ISSUE THREAD

**Issue by krnchittora2** [coredns/coredns#4764]
I am using default coredns that come along with Kubernetes. I am running multiple clusters on a k8s headless service and want to resolve the DNS of one cluster from another. I tried configuring coredns using installation steps mentioned here: https://github.com/coredns/kubernetai#external-plugin and I also took reference from here: https://github.com/coredns/multicluster-dns/blob/master/build.sh but got error in both cases. Initially, I was using go version 1.10, so it could not locate some crypto package (or some other packages after modifying a bit). Then I upgraded the Go version to 1.16, but then it is showing below error on running the docker-push command:
Error: Cannot perform an interactive login from a non TTY device
Makefile.release:146: recipe for target 'docker-push' failed
make: *** [docker-push] Error 1
What commands do I need to run so that I can configure coredns with kubernetai plugin and how to connect it to kubernetes service after configuration?
Further, is there another way to modify plugin.cfg file in the pre-configured coredns setup (deployed on kubernetes)?

**Comment by chrisohaver** [comment]
> `Error: Cannot perform an interactive login from a non TTY device`

Try logging in before building (`docker login`), so it doesn't try to do the interactive log during the build.

> how to connect it to kubernetes service after configuration?

You need to update the coredns Deployment `image` to use to the new image in your docker hub account.

> Further, is there another way to modify plugin.cfg file in the pre-configured coredns setup (deployed on kubernetes)?

No, `plugin.cfg` is only used at compile time, so you must compile coredns, create a new docker image for it, push the image to a docker repo (e.g. docker hub), and update the deployment to use the new image.

**Comment by krnchittora2** [comment]
Thanks @chrisohaver for your response. I am using coredns only for local k8s setup (where docker is also installed). So I think I don't need to push that image to docker registry. However, I directly pulled the image "gcr.io/jbelamaric-public/coredns:kubernetai-v1.6.5" from docker and linked it to the coredns deployement, and it is working just fine.

**Comment by johnbelamaric** [comment]
Please don’t rely on that image existing for production. You can push it to
some other registry, but I can’t offer any SLA on that always being there!

**Comment by krnchittora2** [comment]
Okay. I'll push it to my docker registry. Thanks.
