### ISSUE TITLE
Issue with CoreDNS 1.8.4 and Hashicorp Consul

### ISSUE THREAD

**Issue by Shahard2** [coredns/coredns#4765]
Hello,
We have upgraded our cluster to EKS 1.20,
And CoreDNS to 1.8.4

If we try to install consul with helm, we get this errors in the pod logs:

` 13:59:59.27
 13:59:59.27 Welcome to the Bitnami consul container
 13:59:59.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-consul
 13:59:59.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-consul/issues
 13:59:59.27
 13:59:59.28 INFO  ==> ** Starting Consul setup **
 13:59:59.30 INFO  ==> Validating settings in CONSUL_* env vars..
 13:59:59.37 ERROR ==> The value for CONSUL_RETRY_JOIN_ADDRESS should be an IPv4 address or it must be a resolvable hostname`

**How to reproduce?**

`helm install --wait consul-lubiyoo -n <YOUR_NAMESPACE> bitnami/consul --set global.name=consul --set replicaCount=1 --set service.type=LoadBalancer --set service.port=8500`

Then you will see the pod is in crashloop.

**Please NOTE**
If we revert to CoreDNS 1.8.0, we don't see this issue. So it's must be a problem in the new COREdns version.

Please assist.

**Comment by chrisohaver** [comment]
Do you have endpointslice api list and watch enabled for coredns?
From https://github.com/coredns/coredns/blob/master/notes/coredns-1.8.1.md …

>If using the kubernetes plugin for a Kubernetes cluster >= 1.19, CoreDNS must be granted list and watch access to endpointslices.

Not doing this will prevent lookups for headless services from working.

**Comment by Shahard2** [comment]
Yeah we have it in this clusterrole:
system:coredns

Looks like this:

- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch

**Comment by chrisohaver** [comment]
> `ERROR ==> The value for CONSUL_RETRY_JOIN_ADDRESS should be an IPv4 address or it must be a resolvable hostname`

What is the value for `CONSUL_RETRY_JOIN_ADDRESS`?

**Comment by Shahard2** [comment]
> > `ERROR ==> The value for CONSUL_RETRY_JOIN_ADDRESS should be an IPv4 address or it must be a resolvable hostname`
> 
> What is the value for `CONSUL_RETRY_JOIN_ADDRESS`?

default value is 0.0.0.0, we don't edit it

**Comment by chrisohaver** [comment]
fyi https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by chrisohaver** [comment]
From [Bitnami-Docker-Consul readme](https://github.com/bitnami/bitnami-docker-consul)...

> CONSUL_RETRY_JOIN_ADDRESS: "Address of another agent to join upon starting up. **Default: 127.0.0.1**

Please [enable logging in CoreDNS](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#are-dns-queries-being-received-processed), to see DNS queries received and return codes during the failure.

**Comment by Shahard2** [comment]
> enable logging in CoreDNS

Hey,
enabled logging and that's what I see there regarding the consul in my namespace:


```
[INFO] 10.141.119.113:40512 - 29211 "A IN consul-lubiyoo-headless.blatestshahar.svc.cluster.local.blatestshahar.svc.cluster.local. tcp 105 false 65535" NXDOMAIN qr,aa,rd 198 0.000179165s
[INFO] 10.141.119.113:40512 - 25775 "A IN consul-lubiyoo-headless.blatestshahar.svc.cluster.local.svc.cluster.local. tcp 91 false 65535" NXDOMAIN qr,aa,rd 184 0.000129591s
[INFO] 10.141.119.113:40512 - 23135 "A IN consul-lubiyoo-headless.blatestshahar.svc.cluster.local.cluster.local. tcp 87 false 65535" NXDOMAIN qr,aa,rd 180 0.000094495s
[INFO] 10.141.119.113:40512 - 193 "A IN consul-lubiyoo-headless.blatestshahar.svc.cluster.local. tcp 73 false 65535" NXDOMAIN qr,aa,rd 166 0.00016232s
```

**Comment by chrisohaver** [comment]
What’s the output of …

`kubectl get endpointslices -n blatestshahar`

and …

`kubectl get services -n blatestshahar`

**Comment by Shahard2** [comment]
> What’s the output of …
> 
> `kubectl get endpointslices -n blatestshahar`
> 
> and …
> 
> `kubectl get services -n blatestshahar`

@chrisohaver 

```
 ~  kubectl get endpointslices -n blatestshahar         
                                                                                                                                                                                        
NAME                            ADDRESSTYPE   PORTS                        ENDPOINTS        AGE
consul-lubiyoo-headless-5fml2   IPv4          8301,8300,8301 + 4 more...   10.xxx.xxx.xxx   5h12m
consul-lubiyoo-headless-qppbm   IPv6          <unset>                      <unset>          5h12m
consul-lubiyoo-ui-hktlc         IPv4          8500                         10.xxx.xxx.xxx   5h12m
```
```
 ~  kubectl get services -n blatestshahar                                                                                                                                                                                                      

NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP                                                               PORT(S)                                                          AGE
consul-lubiyoo-headless   ClusterIP      None            <none>                                                                    8500/TCP,8400/TCP,8301/TCP,8301/UDP,8300/TCP,8600/TCP,8600/UDP   5h12m
consul-lubiyoo-ui         LoadBalancer   172.20.xxx.xxx   XXXXXXX   8500:31889/TCP                                                   5h12m
```

**Comment by chrisohaver** [comment]
What does the beginning of the log look like when CoreDNS starts up?  Are there any errors or warnings?

**Comment by Shahard2** [comment]
> What does the beginning of the log look like when CoreDNS starts up? Are there any errors or warnings?

Hey mate, @chrisohaver 
Actually none..

it looks clean:

`.:53
CoreDNS-1.8.4
linux/amd64, go1.13.15, 053c4d5c`

**Comment by chrisohaver** [comment]
Can you verify that the endpoint in the ipv4 slice is ready? e.g. 

```
kubectl describe endpointslices -n blatestshahar  consul-lubiyoo-headless-5fml2
```

If it's not ready, then CoreDNS will not create a DNS record for it.

```
Endpoints:
  - Addresses:  10.244.0.17
    Conditions:
      Ready:    true
    Hostname:   consul-test-0
    TargetRef:  Pod/consul-test-0
    Topology:   kubernetes.io/hostname=kind-control-plane
```

**Comment by Shahard2** [comment]
It's marked as false,
why is that? what can I do about it?




`Name:         consul-lubiyoo-headless-5fml2
Namespace:    blatestshahar
Labels:       app.kubernetes.io/instance=consul-lubiyoo
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=consul
              endpointslice.kubernetes.io/managed-by=endpointslice-controller.k8s.io
              helm.sh/chart=consul-9.2.14
              kubernetes.io/service-name=consul-lubiyoo-headless
              service.kubernetes.io/headless=
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2021-07-26T13:53:03Z
AddressType:  IPv4
Ports:
  Name         Port  Protocol
  ----         ----  --------
  serflan-udp  8301  UDP
  rpc-server   8300  TCP
  serflan-tcp  8301  TCP
  http         8500  TCP
  dns-udp      8600  UDP
  dns-tcp      8600  TCP
  rpc          8400  TCP
Endpoints:
  - Addresses:  XXXXXXX
    Conditions:
      Ready:    false
    Hostname:   consul-lubiyoo-0
    TargetRef:  Pod/consul-lubiyoo-0
    Topology:   kubernetes.io/hostname=ip-10-141-127-196.ec2.internal
                topology.kubernetes.io/region=us-east-1
                topology.kubernetes.io/zone=us-east-1c
Events:         <none>`

**Comment by chrisohaver** [comment]
> It's marked as false,
why is that? what can I do about it?

If the endpoint target `Pod/consul-lubiyoo-0` is crash looping, then it won't be ready.  Perhaps the pod is trying to resolve "itself" before it is ready.

**Comment by chrisohaver** [comment]
Try setting the `spec.publishNotReadyAddresses` to `true` in the headless service definition.

**Comment by chrisohaver** [comment]
The helm chart may still be using the _deprecated_ Service annotation `service.alpha.kubernetes.io/tolerate-unready-endpoints: true`.  If so it should instead be using the Spec option `publishNotReadyAddresses`.

**Comment by Shahard2** [comment]
Thanks alot @chrisohaver 
This was the issue,
Opened a PR for the chart maintainers (bitnami)


https://github.com/bitnami/charts/pull/7063


Closing this one
