### ISSUE TITLE
Core DNS pod stuck at Terminating state post k8s version upgrade from 1.18 to 1.19

### ISSUE THREAD

**Issue by marunachalam** [coredns/coredns#4766]
**What happened**: Core DNS pods stuck at Terminating state after  k8s version upgrade from 1.18 to 1.19

**What you expected to happen**: Core DNS pods to be up and running even after the k8s upgrade

**How to reproduce it (as minimally and precisely as possible)**: 
1. Deploy a k8s cluster with v1.18, coredns version 1.6.7, and create few workloads.
2. Upgrade the k8s cluster(master and worker nodes) from 1.18 to 1.19, reference doc: https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ 

Post Upgrade
observed core dns pods stuck at terminating state

**Anything else we need to know?**:
coredns moved to running state after doing the below change
Deleted the "max_concurrent" from coredns configmap and restarted the worker node

**Environment**:

- the version of CoreDNS: 1.6.7
- Corefile:
- logs, if applicable:  https://gist.github.com/marunachalam/88dad5aa0982f9d74e82326ef0b02c51
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.2 LTS
- Others:

**Comment by chrisohaver** [comment]
> coredns moved to running state after doing the below change
> Deleted the "max_concurrent" from coredns configmap and restarted the worker node

Sounds like a kubelet issue or some other kubernetes pod scheduling infrastructure issue.  Restarting the node the pod was on would have forcefully terminated the pod, thus resolving the issue.  IMO, removing "max_concurrent" is a red herring.
