### ISSUE TITLE
Mysql configuration request help

### ISSUE THREAD

**Issue by dreamskyw** [coredns/coredns#4772]
### conf/crefile
```
mysql {
    mysql root:root@/gva
}
. {
    bind 0.0.0.0
    forward . 8.8.8.8
    cache 3600 .
    log
}
```
### Error
```plugin/mysql: Error 1045: Access denied for user ''@'172.17.0.1' (using password: NO)```

**Comment by chrisohaver** [comment]
The _mysql_ plugin is an external plugin maintained in a separate repo: https://github.com/cloud66-oss/coredns_mysql.  Please raise the question there. 

cc @khash

**Comment by chrisohaver** [comment]
Ah, the question is already posted there cloud66-oss/coredns_mysql#1. Closing here.
