### ISSUE TITLE
Coredns in k8s is running but not ready.

### ISSUE THREAD

**Issue by blackredscarf** [coredns/coredns#4774]
### What happened:
Coredns in k8s is running but not ready.
```
# kubectl get po
NAME                       READY   STATUS    RESTARTS   AGE
coredns-746fcb4bc5-6qhtl   0/1     Running   0          40m
```
The log of coredns:
```
# kubectl logs coredns-746fcb4bc5-6qhtl
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:53
cluster.local.:53
[INFO] plugin/reload: Running configuration MD5 = 528a67c20a203cc830e48e3dbcd28c8d
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
```
The services of k8s:
```
# kubectl get svc
NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
kube-dns         ClusterIP   20.1.0.100   <none>        53/UDP,53/TCP,9153/TCP   48m
kubernetes       ClusterIP   20.1.0.1     <none>        443/TCP                  124m
```
The configmap of coredns: 
```
# kubectl describe cm coredns
Name:         coredns
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
Corefile:
----
cluster.local {
  errors
  health
  kubernetes cluster.local in-addr.arpa ip6.arpa {
    pods insecure
    fallthrough in-addr.arpa ip6.arpa
  }
  prometheus :9153
  ready :8181
  forward . /etc/resolv.conf
  cache 30
  loop
  reload
  loadbalance
}
. {
  cache 30
  loadbalance
  forward . /etc/resolv.conf
}
```
The parameters of kubelet:
```
/usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubeconfig-ssl --hostname-override=k8s-node-12 --log-dir=/var/log/kubernetes --cluster-dns=20.1.0.100 --cluster-domain=cluster.local --v=0
```

### Environment:
- Coredns 1.8.4
- Kubernetes 1.19
- OS: CentOS 7

**Comment by chrisohaver** [comment]
Hmm. IIRC, the intent of this behavior was to be able to serve upstream dns while the API is not reachable. However in that case, coredns should also report ready. Otherwise no queries will be directed to the Pod.

**Comment by blackredscarf** [comment]
@chrisohaver How can coredns report ready? I need more detail and guidance to fix this problem.

**Comment by snebel29** [comment]
@blackredscarf I think what Chris was saying is that the coredns pod is unable to reach kubernetes API to syncup the state of the k8s cluster causing it to start but never get ready, is there any problem in your cluster that could cause this to happen? have you try to troubleshoot that?

**Comment by snebel29** [comment]
> Hmm. IIRC, the intent of this behavior was to be able to serve upstream dns while the API is not reachable. However in that case, coredns should also report ready. Otherwise no queries will be directed to the Pod.

@chrisohaver Where you suggesting to remove ?https://github.com/coredns/coredns/blob/9d5b8cd13d541cc3d2b7598ab255643d6298ba9d/plugin/kubernetes/ready.go#L4

**Comment by chrisohaver** [comment]
I’m not suggesting that. I’ll take a look at this Monday.

**Comment by chrisohaver** [comment]
@blackredscarf, do you have a specific question?  You haven't asked one, so I am inferring your question is  "Is this normal?"  In which case, yes this is normal.  CoreDNS will not report ready if it is not yet synced to the APIs, because it will not be able to answer any queries for cluster resources e.g. services/endpoints/etc.  If the deployment readiness probe is defined to use the "/ready" endpoint of coredns, then this would mean that k8s will not send queries to the unready coredns pods.  This is intended behavior.

IMO, if someone wants their cluster to use coredns Pods that are in a 1/2 working state (i.e. can answer queries for upstream zones, but not the cluster zone), then they should able to deploy CoreDNS without a readiness probe defined (or re-define it to point to the "/health" endpoint).

So, I don't think any changes of behavior are required here.

**Comment by chrisohaver** [comment]
> How can coredns report ready?

@blackredscarf, If you want your coredns pods to be considered "ready" in this state (when they are not fully functioning), you can point the readiness probe to the "/health" endpoint (which always returns true if the server is running).  This is the same endpoint that the liveness probe uses.

>  I think what Chris was saying is that the coredns pod is unable to reach kubernetes API to syncup the state of the k8s cluster causing it to start but never get ready, is there any problem in your cluster that could cause this to happen? have you try to troubleshoot that?

Yes @snebel29, you are correct.

**Comment by blackredscarf** [comment]
@chrisohaver @snebel29 I change the readiness probe to /health and coredns becomes ready, but coredns does not work.

It cannot resolve any service in k8s. For example:
```
# kubectl exec -it busybox2 -- nslookup kube-dns
Server:    20.1.0.100
Address 1: 20.1.0.100

nslookup: can't resolve 'kube-dns'
```
It can resolve opera.com:
```
# kubectl exec -it busybox2 -- nslookup opera.com
Server:    20.1.0.100
Address 1: 20.1.0.100

Name:      opera.com
Address 1: 185.26.182.103 opera.com
Address 2: 185.26.182.104 opera.com
```
Does it relate to the previous problem? Why the coredns cannot reach Kubernetes API? 

I can access the kubernetes service by Cluster-IP.
```
# curl -k https://20.1.0.1/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

**Comment by chrisohaver** [comment]
> I change the readiness probe to /health and coredns becomes ready, but coredns does not work.
It cannot resolve any service in k8s.

Yes that's expected behavior.  That's why the readiness probe is configured the way it is by default.

> Does it relate to the previous problem? Why the coredns cannot reach Kubernetes API?

It means CoreDNS cannot resolve k8s names _because_ it cannot get the data it needs from the Kubernetes API.
CoreDNS cannot get the data it needs from the Kubernetes API because it cannot reach it, or cannot authenticate, or whatever reason, it could be RBAC. Does your coredns user have proper permissions to the API?

**Comment by blackredscarf** [comment]
@chrisohaver The serviceaccount, clusterrole and clusterrolebinding were created.
```
# kubectl describe clusterrole system:coredns
Name:         system:coredns
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  <none>
PolicyRule:
  Resources                        Non-Resource URLs  Resource Names  Verbs
  ---------                        -----------------  --------------  -----
  endpoints                        []                 []              [list watch]
  namespaces                       []                 []              [list watch]
  pods                             []                 []              [list watch]
  services                         []                 []              [list watch]
  endpointslices.discovery.k8s.io  []                 []              [list watch]
  
# kubectl describe clusterrolebinding  system:coredns
Name:         system:coredns
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
Role:
  Kind:  ClusterRole
  Name:  system:coredns
Subjects:
  Kind            Name     Namespace
  ----            ----     ---------
  ServiceAccount  coredns  kube-system
```

I found the log in apiserver:
```
Aug 08 01:08:53 k8s-master apiserver.sh[10572]: I0808 01:08:53.911749   10573 secure_serving.go:282] http: TLS handshake error from 192.168.223.13:60026: remote error: tls: bad certificate
Aug 08 01:08:54 k8s-master apiserver.sh[10572]: I0808 01:08:54.111952   10573 secure_serving.go:282] http: TLS handshake error from 192.168.223.13:60030: remote error: tls: bad certificate
Aug 08 01:08:54 k8s-master apiserver.sh[10572]: I0808 01:08:54.312867   10573 secure_serving.go:282] http: TLS handshake error from 192.168.223.13:60032: remote error: tls: bad certificate
```
`192.168.223.13` is the node where coredns pod is running. It seems the request cannot complete the TLS handshake. What cert file does the coredns use?

**Comment by blackredscarf** [comment]
@chrisohaver  I reconfirm and update the config of my cluster, After that, I reinstall the coredns, and it works. 

The work I did:

- Calibrate the time of nodes
- Update certificate files and keys of all components in K8s. Ensure the SSL config includes the Cluster-IP of API Server.
- Regenerate secrets of ServiceAccounts.
