### ISSUE TITLE
what reason trigger reloading? 

### ISSUE THREAD

**Issue by invent-lwj** [coredns/coredns#4804]
coredns version is 1.6.0
kubernetes version is 1.16.15
corefile
```
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        reload
        loadbalance
    }
```
dns is not work between two reloading, but i don't modify corefile, coredns pod is not restart too.
this is log of coredns pod and corefile modify time
```

/ # ls -l ./etc/coredns/Corefile
lrwxrwxrwx    1 root     root            15 Jul  9 11:53 ./etc/coredns/Corefile -> ..data/Corefile
/ # ls -l ./etc/coredns/..2021_08_12_09_19_00.710083026/Corefile
-rw-r--r--    1 root     root           252 Aug 12 09:19 ./etc/coredns/..2021_08_12_09_19_00.710083026/Corefile


coredns pod log:

2021-08-12T05:09:08.093Z [ERROR] plugin/errors: 2 bobft-cce-api-svc.cce-system. A: read udp 10.51.163.14:38406->10.51.51.51:53: i/o timeout
2021-08-12T08:29:16.657Z [ERROR] plugin/errors: 2 rfr-redis-redis-sentinel-to-sentinel. A: read udp 10.51.163.14:59109->10.51.51.51:53: i/o timeout
[INFO] Reloading
2021-08-12T08:49:09.660Z [INFO] plugin/reload: Running configuration MD5 = 2c2678d613dda4d5669dd465792642bd
[INFO] Reloading complete
[INFO] Reloading
2021-08-12T09:20:07.534Z [INFO] plugin/reload: Running configuration MD5 = 6f20f7ae09104da42bac99adb58783ea
[INFO] Reloading complete
2021-08-12T09:20:17.314Z [ERROR] plugin/errors: 2 alertmanager-main-1.alertmanager-operated.monitoring.svc. ANY: EOF
```
clould you tell me the reason, what reason trigger reloading, coredns pod is always  running i do not modify configmap, pod is not restart thanks!
![readdata jsp](https://user-images.githubusercontent.com/20390953/129555772-04f35f43-dc65-40ed-b127-6bb835f5b448.jpg)

**Comment by chrisohaver** [comment]
> what reason trigger reloading

According to the log, the MD5 checksum changed on the Corefile, hence the reload.

>  i do not modify configmap

Apparently _something_ did.

**Comment by invent-lwj** [comment]
Cloud you take some advise for debug?

**Comment by chrisohaver** [comment]
> Cloud you take some advise for debug?

It looks as if someone updated the ConfigMap but saw that it caused some problems, then ~30 minutes later they fixed it (or perhaps reverted it to prior state).  Maybe check the k8s api logs at around those times (8:49 and 9:20) to see if there are hints as to who might have done it (e.g. remote ip).
