### ISSUE TITLE
DOT support tls1.3 and support select cipheres for tls1.3

### ISSUE THREAD

**Issue by 0neday** [coredns/coredns#4807]
we know tls1.3 support FS, and use curve to encrypt data, and we know coredns support both client and server authority, 
and we also know coredns support http/2 for tls1.3(DOH).
so I wonder know coredns support tls1.3 and support select curve cipheres for DOT?

**Comment by chrisohaver** [comment]
Probably, via Golang's standard `tls` lib, but I have not tested it.

**Comment by 0neday** [comment]
@chrisohaver 
thx, I will test it like 
```
        tlsConfig.CurvePreferences = []tls.CurveID{29}
        tlsConfig.MinVersion = tls.VersionTLS13
        tlsConfig.CipherSuites = []uint16{
		tls.TLS_CHACHA20_POLY1305_SHA256,
		tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
		tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
		tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
		tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
	}
```
