### ISSUE TITLE
plugin/dns64 : support also intercepting DNS requests coming over IPv4 network

### ISSUE THREAD

**Issue by Tantalor93** [coredns/coredns#4808]
Hello, it seems we hit an issue related to this comment in `dns64` plugin https://github.com/coredns/coredns/blob/master/plugin/dns64/dns64.go#L78.
**What would you like to be added**:
We would like to add configuration to `dns64` plugin to enable intercepting DNS requests coming also over IPv4 network

**Why is this needed**:
our CoreDNS instance is sitting in IPv4 network and DNS requests are being forwarded to it from gateway in the same IPv4 network and we need to apply DNS64 to these forwarded requests, but CoreDNS does not apply DNS64 it due to them arriving from IPv4 address

our setup is something like this:
```
| IPv6-only| ----> |     IPv4 network     |
|  device  | ----> | gateway ----> CoreDNS|
```

**Comment by SuperQ** [comment]
For the record, this is likely to cause problems if non-DNS64 devices are also making requests through the same server.
