### ISSUE TITLE
plugin/dns64 not respecting EDNS options in original AAAA requests

### ISSUE THREAD

**Issue by Tantalor93** [coredns/coredns#4825]
**What happened**:
Hello 👋  while using `dns64` plugin I noticed that plugin `dns64` is not respecting EDNS options in original AAAA requests, for example ECS option from the original AAAA request is not taken into consideration when doing synthesis from A record. This brings additional problems as we are encoding additional info into EDNS options and these are not passed to upstream.

I have backtracked it to this code https://github.com/coredns/coredns/blob/master/plugin/pkg/upstream/upstream.go#L32 where the original EDNS options are lost (or rather they are not copied), it seems that the same issue will be even in `kubernetes` and `etcd` plugins

**What you expected to happen**:
EDNS options from original AAAA request be passed to upstream, see how to reproduce section

**How to reproduce it (as minimally and precisely as possible)**:
Let's have a Corefile
```
.:53 {
    dns64
    forward . 8.8.8.8
    log
}
```
when you do a DNS request with the ECS option with US subnet
```
dig @::1  aws.amazon.com +subnet=216.58.211.238/24 -t AAAA +short
tp.8e49140c2-frontier.amazon.com.
dr49lng3n1n2s.cloudfront.net.
64:ff9b::4109:5846
```

and another DNS request with ECS option with Czech subnet
```
dig @::1  aws.amazon.com +subnet=81.0.198.170/24 -t AAAA +short
tp.8e49140c2-frontier.amazon.com.
dr49lng3n1n2s.cloudfront.net.
64:ff9b::4109:5846
```

**you get the same synthesized address**, which is weird when you compare it with same requests done directly against GoogleDNS. You can see that these addresses differ and so should the synthesized AAAA records.
```
dig @8.8.8.8 aws.amazon.com +subnet=216.58.211.238/24 +short
tp.8e49140c2-frontier.amazon.com.
dr49lng3n1n2s.cloudfront.net.
13.35.123.36
```
```
dig @8.8.8.8 aws.amazon.com +subnet=81.0.198.170/24 +short
tp.8e49140c2-frontier.amazon.com.
dr49lng3n1n2s.cloudfront.net.
13.225.75.7
```

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: latest
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by miekg** [comment]
uhm actually. EDNS0 option are hop-by-hop and should not (think the rfc actually says MUST NOT) be forwarded.
https://datatracker.ietf.org/doc/html/rfc6891#section-1 paragraph 4

Now should we take some options into account, not sure. CoreDNS doesn't do ECS (wrecks havoc with your cache), so I think the expectations are wrong here.

**Comment by Tantalor93** [comment]
oh, I see. should have read the RFC better 🤔 then probably https://github.com/coredns/coredns/pull/4826 should be reverted as it seems to go against the RFC you mentioned @miekg?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] plugin/dns64 ..." ]
>oh, I see. should have read the RFC better 🤔 then probably #4826 should be
>reverted as it seems to go against the RFC you mentioned @miekg?

yes

However having a DNS proxy is weird thing in the DNS world. This is why I'm slowly comming
the realization that doing a plain proxy is the wrong angle to take, i.e 'proxy' was
dumped in favor for 'forward', and it's still hard.

So I think this should become a fullblown *resolver* (with RR level cache, not whole pkts
as now). There is some prior art in the sdns project, but still a LOT of work...

**Comment by chrisohaver** [comment]
> probably #4826 should be reverted

I don't think so. It's _forward_ that does the forwarding, and should be responsible for dropping EDNS options if they should be.

Upstream (upstream package) is perhaps a misnomer, in that it does not itself send queries upstream, it sends queries to itself...  which IMO isn't a real hop.  If a user looks up absent AAAA records for a zone that CoreDNS is authoritative, then you want to retain the EDNS options for the A lookup.

**Comment by miekg** [comment]
I'll keep the discussion here.

Good point @chrisohaver and I think you're right.

**Comment by miekg** [comment]
The comment in upstream should be changed as well `// Lookup routes lookups to our selves or forward to a remote.` as that was true a long time ago, but no longer. So:

*And* EDNS0 shenanigans mentioned in (probably) the method's documentation.

So:
~~~
// Lookup routes lookups to our selves to make it follow the plugin chain *again*, but with a (possibly) new query. As
// we are doing the query against ourselves again, there is no actual new hop, as such RFC 6891 does not apply and we
// need the EDNS0 option present in the *original* query to be present here too.
~~~

**Comment by Tantalor93** [comment]
ok, that makes sense. I'll close the revert PR and I can prepare the PR with code comment adjustments

**Comment by miekg** [comment]
@Tantalor93 that sounds good!
