### ISSUE TITLE
nslookup to internal hosts stooped working after coredns upgraded to 1.8.4

### ISSUE THREAD

**Issue by PrakashFromBunnings** [coredns/coredns#4833]
-->

**What happened**:    nslookup to internal services fail 
```
  nslookup np-pp01-scan.bbs.example.com.au
  ;; Question section mismatch: got np-pp01-scan.bbs.example.com.au.bbs.example.com.au/A/IN
 ^C
```
 

**What you expected to happen**: Nslookup start wokring fine

**How to reproduce it (as minimally and precisely as possible)**:
1.  Install AKS cluster with 1.20.7  in SYD region ( for some reason coredns 1.8.4 is pushed to only sydney region currently , not to melbourne region )
2.  Add custom dns config  with  for domain lets say bbs.example.com.au
3. create a pod and do nslookup

**Anything else we need to know?**:

We can confirm , issue goes away with coredns version 1.8.3.  But comes back with coredns 1.8.4

We have custom coredns config added to our aks cluster , which looks like below 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  np-pp01-scan.server: |
    reddog.microsoft.com:53 {
       log
        errors
       rewrite name substring reddog.microsoft.com bbs.example.com.au
        forward . /etc/resolv.conf
    }
```

**Environment**:

- the version of CoreDNS: 1.8.4
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
This should be failing in both versions. The rewrite rule needs an answer rewrite section otherwise you get the mismatch error.

**Comment by chrisohaver** [comment]
https://github.com/coredns/coredns/blob/master/plugin/rewrite/README.md#response-rewrites

**Comment by chrisohaver** [comment]
Looks to be the same bug as reported in #4834.

**Comment by PrakashFromBunnings** [comment]
@chrisohaver  Yep looked like that was the issue. 

Below update to config map fixed our issue . 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  np-pp01-scan.server: |
    reddog.microsoft.com:53 {
        log
        errors
        rewrite stop {
          name regex (.*)\.reddog.microsoft.com {1}.bbs.example.com.au
          answer name (.*)\.bbs\.example\.com\.au {1}.reddog.microsoft.com
        }
        forward . /etc/resolv.conf
    }
```

Happy to close this now.
