### ISSUE TITLE
Cache middleware never returns truncated

### ISSUE THREAD

**Issue by kdima** [coredns/coredns#484]
If you make a request to coredns and the reply is truncated it works first time round. After that the answer is put into cache. When you make a second request to coredns even though the reply is larger than advertised bufsize caching middleware will not reply with truncated.
Example:
```
dig @127.0.0.1 -p 10053 test.test.com SRV
;; Truncated, retrying in TCP mode.
Data

dig @127.0.0.1 -p 10053 test.test.com SRV
Data
```

A simple way to fix it is to call Scrub method here: src/github.com/miekg/coredns/middleware/cache/handler.go:31
But I am not sure if that is correct.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/coredns] Cache middleware ne..." ]
>If you make a request to coredns and the reply is truncated it works first time round. After that the answer is put into cache. When you make a second request to coredns even though the reply is larger than advertised bufsize caching middleware will not reply with truncated.
>Example:
>```
>dig @127.0.0.1 -p 10053 test.test.com SRV
>;; Truncated, retrying in TCP mode.
>Data
>
>dig @127.0.0.1 -p 10053 test.test.com SRV
>Data
>```
>
>A simple way to fix it is to call Scrub method here: src/github.com/miekg/coredns/middleware/cache/handler.go:31
>But I am not sure if that is correct.

Think it is easier to check for TC before putting it in the cache in the first
place?

**Comment by kdima** [comment]
Yeah I guess that makes sense.

**Comment by miekg** [comment]
Hmmm, `cache.go` has this: https://github.com/miekg/coredns/blob/master/middleware/cache/cache.go#L37

**Comment by miekg** [comment]
Scrub is still needed in case the same reply is being returned to another client with a smaller cache, so that is a good fix.

Creating a test to see if I can repro this.

**Comment by miekg** [comment]
@kdima assuming your merge PR fixed this issue?
