### ISSUE TITLE
plugin/hosts/hostsfile_test.go fail in golang 1.17

### ISSUE THREAD

**Issue by rouzier** [coredns/coredns#4843]
**What happened**:
plugin/hosts/hostsfile_test.go fail in golang 1.17

**How to reproduce it (as minimally and precisely as possible)**:
Run tests using golang-1.17

**Anything else we need to know?**:
This was caused by net.ParseIP and net.ParseCIDR functions now rejecting IPv4 addresses which contain decimal components with leading zeros.
https://golang.org/doc/go1.17#minor_library_changes

**Environment**:
- golang 1.17

**Comment by miekg** [comment]
Feel free to remove those test cases

**Comment by rouzier** [comment]
Would you want a pull request?

**Comment by yongtang** [comment]
@rouzier PR is welcomed
