### ISSUE TITLE
Remove docker step from release process

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#4858]
4 of the 5 release failures had docker as it's root cause. 

This is issue is to track the complete removal of docker code from the binary release process; it best to spun this off to a new Makefile.docker that contains the docker stuff. This should *download* from github the latest released binaries in put them in a docker image. This also allows for better retrying.

This needs:

* update to `.dreck.yaml` for a /docker command that calls into the Makefile.docker
* Removal/move of docker stuff from Makefile.release
* Update to coredns/release to add 'docker' script - although I hope this can be a few lines and call into Makefile.docker
* Update to the release process docs

**Comment by chrisohaver** [comment]
Closing. I think all bullets are complete.
