### ISSUE TITLE
Corefile weirdness

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#489]
This doesn't do what I would expect. Either the last stanza should be a syntax error, or both domains should serve off of port 5354:

```
example.com:5000 {
	proxy . /etc/resolv.conf
}

foobar.com:5353 {
	log stdout
	proxy . /etc/resolv.conf
}

foo.com bar.com :5354 {
	log stdout
	errors
	proxy . /etc/resolv.conf
}
```

Instead, there is no error but the servers created are odd:

```
ubuntu@godev:~/go-work/src/github.com/miekg/coredns$ sudo ./coredns -conf Corefile-multi
example.com.:5000
foobar.com.:5353
foo.com.:53
bar.com.:53
.:5354
2017/01/20 18:22:46 [INFO] CoreDNS-004
CoreDNS-004
^C2017/01/20 18:22:47 [INFO] SIGINT: Shutting down
ubuntu@godev:~/go-work/src/github.com/miekg/coredns$
```

Or maybe I just don't quite understand how this is supposed to work?

**Comment by miekg** [comment]
`.:5354` is odd here indeed. Prolly over-active normalization going on there.

Also I'm don't think I ever considered specifying a port like this, I believe it should be:
~~~
foo.com:5354 bar.com:5354 {
~~~
Why should it be a syntax error ?

**Comment by johnbelamaric** [comment]
Well, I meant if it didn't mean anything unambiguous then it should be an error. What you put above works:

```
ubuntu@godev:~/go-work/src/github.com/miekg/coredns$ ./coredns -conf Corefile-multi
example.com.:5000
foobar.com.:5353
foo.com.:5354
bar.com.:5354
2017/01/20 21:40:43 [INFO] CoreDNS-004
CoreDNS-004
```

**Comment by johnbelamaric** [comment]
So now it makes some sense that foo.com was on port 53, because that's the default port. But not bar.com above nor . on 5354.

**Comment by miekg** [comment]
Well, that space is normalized to `.`; but I agree that is a bug
~~~
foo.com bar.com :5354 {
~~~
boils down to ` :5354` should trigger an error, but `\ :5354` is legal?

**Comment by miekg** [comment]
so this:
~~~
{
    proxy . 8.8.8.8:53
    cache
    errors stdout
}
~~~
Is a valid Corefile and defaults to `.:53`. Question is, should we make this illegal, or document it's use?

**Comment by johnbelamaric** [comment]
I think we just document that `:123` becomes `.:123` and `foo.com {` becomes `foo.com .:53` and `` becomes `.:53` and it's fine.
