### ISSUE TITLE
kubernetes middleware port parsing breaks searches

### ISSUE THREAD

**Issue by devnev** [coredns/coredns#491]
The kubernetes middlware assumes all domains with 5 segments before the zone are of _port._protocol.service.namespace.type.zone format. it tests this assumption even for non-SRV requests, despite non-SRV having no such concept, and returns an SRVFAIL (not NXDOMAIN) when the check fails. as a consequence, the kubernetes search domains are broken as a lookup may accidentally match the 5-segment check.

as a simple example, running `apk update` in an alpine-based container breaks, as the `dl-cdn.alpinelinux.org` lookup becomes `dl-cdn.alpinelinux.org.default.svc.$ZONE`, matches the 5-segment check, and produces an error like
`23/Jan/2017:13:32:37 +0000 [ERROR 0 dl-cdn.alpinelinux.org.default.svc.$ZONE. A] srv port must start with an underscore or be a wildcard`. because this is a srvfail rather than nxdomain, the search stops there and the domain lookup fails.

**Comment by miekg** [comment]
@chrisohaver (cc @johnbelamaric) Chris this was exactly what we were complaining about.
Could you prepare a fix? Thanks.

**Comment by devnev** [comment]
This seems to be fixable just by returning `errInvalidRequest` from "github.com/miekg/coredns/middleware/kubernetes".(*Kubernetes).Services() when parseRequest returns an error.

**Comment by devnev** [comment]
https://github.com/miekg/coredns/compare/master...devnev:kubernetes-searches-fix?expand=1 is my quickfix but its loses some of the error details.

**Comment by chrisohaver** [comment]
It returned NXDOMAIN originally, but I changed it to SERVFAIL based on PR feedback.  I'll change it back to NXDOMAIN.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] kubernetes midd..." ]
> It returned NXDOMAIN originally, but I changed it to SERVFAIL based on PR feedback.  I'll change it back to NXDOMAIN.

NXDOMAIN was the wrong reply. But we need to get rid of assuming anything about
the number of labels in a name...

**Comment by johnbelamaric** [comment]
Hmm. The expectation in k8s is a certain structure in the name:

```
$service.$namespace.svc.$zone
```

where `$service` and `$namespace` are single labels. The number of labels to the left of the zone for a *valid* record will be fixed. It's just the invalid (i.e., for nonexistent records) queries that may have different numbers of labels. 

The reason this caused an issue is because the search list was requesting a record that isn't there, and isn't supposed to be there. ndots is set to 5 and the search list is long in k8s, so you get a bunch of invalid queries a lot.

We can check whether they are querying SRV or A though to change the expectation. SRVs look like:

```
_$port._$proto.$service.$namespace.svc.$zone
```

**Comment by johnbelamaric** [comment]
The NXDOMAIN makes sense to me here - essentially we're saying "this query name is in a format we do not recognize, therefore we do not have a record for it and it's NXDOMAIN".

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] kubernetes midd..." ]
>The NXDOMAIN makes sense to me here - essentially we're saying "this query name is in a format we do not recognize, therefore we do not have a record for it and it's NXDOMAIN".

OK. And there will be definition no names below that name? (if so then yes, I
should have been NXDOMAIN, and I was wrong in suggesting SERVFAIL).
I'm afraid of just masking entire sub-trees by responding NXDOMAIN.

**Comment by johnbelamaric** [comment]
Right. People can't make arbitrary entries, it's a fixed set of records based on K8s. Which is what led to my comment on #303 - if you could fall through to other middleware we could allow dynamic registration in combination with the automatic K8s records.
