### ISSUE TITLE
Edns (Additional Records, OPT) cause DNS query failed in most apps/SDKs view

### ISSUE THREAD

**Issue by gavinshark** [coredns/coredns#4911]
**What happened**:
DNS query failed. 
If an external domain's DNS query request is through coredns, the request will be added with Edns (Additional Records, OPT) by default??? and some domains' DNS records in response will be in additional records section rather than answer section. Most application/SDK will regard it as failure.

**What you expected to happen**:
Do NOT use Edns (Additional Records, OPT)  in DNS query by default.

**How to reproduce it (as minimally and precisely as possible)**:
`nslookup www.google.com 10.40.0.1`
Here 10.40.0.1 is one of the coredns pod's IP in k8s environment.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.5
- Corefile: default
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): VERSION="20.04.3 LTS (Focal Fossa)"
- Others:
![query](https://raw.githubusercontent.com/gavinshark/stayHungryStayFoolish/master/Topic/DNS/coredns/issue/pic/request.png)
![response](https://raw.githubusercontent.com/gavinshark/stayHungryStayFoolish/master/Topic/DNS/coredns/issue/pic/answer.png)

**Comment by chrisohaver** [comment]
> **How to reproduce it (as minimally and precisely as possible):**
nslookup www.google.com 10.40.0.1

works for me.  response is in answer section as expected.

**Comment by chrisohaver** [comment]
> If an external domain's DNS query request is through coredns, the request will be added with Edns (Additional Records, OPT) by default?

Yes, this is due to the _cache_ plugin. It enables dnssec for outgoing requests on cache miss, saves the response to cache, and then strips out dnssec the response to clients that didn't request dnssec. This way, dnssec and non-dnssec requests can use the same cached entry.

**Comment by gavinshark** [comment]
> > **How to reproduce it (as minimally and precisely as possible):**
> > nslookup [www.google.com](http://www.google.com) 10.40.0.1
> 
> works for me. response is in answer section as expected.

Could you please try api.greatersecurity.cn ? About 50% queries will fail.

**Comment by gavinshark** [comment]
> > If an external domain's DNS query request is through coredns, the request will be added with Edns (Additional Records, OPT) by default?
> 
> Yes, this is due to the _cache_ plugin. It enables dnssec for outgoing requests on cache miss, saves the response to cache, and then strips out dnssec the response to clients that didn't request dnssec. This way, dnssec and non-dnssec requests can use the same cached entry.

I see the right records will exist in "additional records". Will the "strips out" logic remove the additional records from the response to client and the client could not know the DNS records?

**Comment by gavinshark** [comment]
Hi @chrisohaver ,

I think I got some findings:

In my environment, the true IP records are in the additonal records section as you can see from my wireshark screen shot.
But in others' environment, the true IP records are in the answer section and OPT are in the additional records section.

Could you help to tell me why?

Thank you!

**Comment by chrisohaver** [comment]
> But in others' environment, the true IP records are in the answer section and OPT are in the additional records section.

This is normal behavior.

> In my environment, the true IP records are in the additional records section as you can see from my wireshark screen shot.

AFAIK, this is an abnormal response.

**Comment by chrisohaver** [comment]
> Could you please try `api.greatersecurity.cn`? About 50% queries will fail.

It seems to work fine for me.  Have you fixed/changed something on your end?

**Comment by gavinshark** [comment]
I think this is not coredns' issue.
I will check with the DNS resovling vendor about the abnormal response.
Thank you for your kind reply.
