### ISSUE TITLE
k8s_external plugin doesn't work with AWS ELB/NLB with query=SRV

### ISSUE THREAD

**Issue by denis-tingaikin** [coredns/coredns#4927]
## What happened
Steps to reproduce:

1. setup AWS ELB/NLB cluster 
2. override coredns config with adding `k8s_external my_cluster`
3. expose kube-dns service to public via `kubectl expose service kube-dns -n kube-system --port=53 --target-port=53 --protocol=TCP --name=exposed-kube-dns --type=LoadBalancer`
4. do lookup for SRV `_._tcp.exposed-kube-dns-service.kube-system.my_cluster`

**Actual: error 10.100.0.10:53: lame referral**

## What you expected to happen
 coredns responded  correctly 
 
 ## Anything else that we need to know
 
 1. It is not reproducing if force set `external-ip `for the service.
 2. IP address lookup is working correctly. 
  
## Environment

- the version of CoreDNS:
- Corefile:`coredns/coredns:1.8.4`

## Corefile

```
Name:         coredns
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
Corefile:
----
.:53 {
    errors
    health {
        lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    }
    k8s_external my_cluster
    prometheus :9153
    forward . /etc/resolv.conf {
        max_concurrent 1000
    }
    loop
}
```

**Comment by denis-tingaikin** [comment]
It seems to me this is very close to https://github.com/coredns/coredns/pull/3916

@chrisohaver Could you have a look?

**Comment by chrisohaver** [comment]
Can you try latest release?

**Comment by denis-tingaikin** [comment]
Reproducible with `coredns/coredns:1.8.6`
