### ISSUE TITLE
Update protobuf Module URL

### ISSUE THREAD

**Issue by utkonos** [coredns/coredns#4939]
**What would you like to be added**:
Update protobuf module URL.

**Why is this needed**:
The one being used is deprecated.

```
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
```

**Comment by Bosegeek** [comment]
Does any know how can we get this resolved ?

**build constraints exclude all Go files in /Users/xyz/go/pkg/mod/google.golang.org/protobuf@v1.27.1**

Updating the go.mod and updating the references does not work. I did try to install the package globally but still getting above error.

**Comment by miekg** [comment]
how/when do you see this error?

**Comment by yongtang** [comment]
@utkonos the issue has been fixed. Now coredns does not have reference to deprecated protobuf module any more. The dependency libraries may still pointing to the old protobuf module though that is outside of coredns control.
