### ISSUE TITLE
CoreDNS doesn't send NOTIFY for kubernetes zone

### ISSUE THREAD

**Issue by areytsman** [coredns/coredns#4941]
I have a kubernetes cluster and I want to transfer the cluster's DNS zone to my own DNS server.
I added "transfer" directive to my CoreDNS configmap like this:

    ...
    kubernetes my-cluster.example.com in-addr.arpa ip6.arpa {
       pods insecure
    }
    transfer {
       to 1.2.3.4
       to *
    }
    ...

But I'm don't receive any NOTIFY on 1.2.3.4
I try to tcpdump on cluster node, but see no IP packets to 1.2.3.4
Then I dig my-cluster.example.com SOA, I can see zone serial has changed after restarting any pods.

What am I doing wrong?

**Comment by chrisohaver** [comment]
Try specifying the zone in transfer plugin... i.e..

```
kubernetes my-cluster.example.com in-addr.arpa ip6.arpa {
   pods insecure
}
transfer my-cluster.example.com {
   to 1.2.3.4
   to *
}
```

**Comment by areytsman** [comment]
I tried this but with no success...

**Comment by chrisohaver** [comment]
Is CoreDNS not sending the notifies, or are they being blocked in transit?

**Comment by chrisohaver** [comment]
Oh, after looking at the code, it looks like notifies are not implemented for the _kubernetes_ plugin.

**Comment by areytsman** [comment]
Thank you for answer

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] CoreDNS doesn..." ]
>Oh, after looking at the code, it looks like notifies are not implemented for
>the kubernetes plugin.

I think the reason was that we would be sending notifies _all_ the time.
