### ISSUE TITLE
no internal type for both IPv4 and IPv6 Addresses (A+AAAA) for

### ISSUE THREAD

**Issue by cyrillpetroff** [coredns/coredns#4942]
**What happened**:

Hello everyone. I have registered a domain mydomain.com. The task is to redirect it to another existing domain, for example, google.com. The subdomain is randomly generated, for example,  super.mydomain.com, or puper.mydomain.com. When I directly indicate that it is necessary to redirect my subdomain, then everything works perfectly. When I try to use regular expressions (to describe a random subdomain), an error occurs. Although, everything is fine in the logs.

**What you expected to happen**:

I expected that everything would work using regular expressions, since there is no way to manually write all possible subdomain options in the config.

**How to reproduce it (as minimally and precisely as possible)**:
This config works flawlessly:

mydomain.com:53 {
    bind eth0
    rewrite name super.mydomain.com google.com
    forward . dns://208.67.222.222
    log
    errors
}

And the log looks clean (Ipv6 records don't bother me, only ipv4):

[INFO] 94.41.80.15:42071 - 34581 "A IN super.mydomain.com. udp 41 true 1480" NOERROR qr,ra,cd 77 0.03219867s
[INFO] 94.41.80.15:64276 - 13286 "A IN super.mydomain.com. udp 41 true 1480" NOERROR qr,rd,ra,cd 77 0.031955073s
[INFO] 94.41.157.98:12310 - 31912 "AAAA IN super.mydomain.com. udp 41 true 1480" SERVFAIL qr,ra,cd 51 0.032031078s
[INFO] 94.41.157.98:64583 - 962 "AAAA IN super.mydomain.com. udp 41 true 1480" SERVFAIL qr,ra,cd 51 0.031983268s
[INFO] 94.41.157.98:51889 - 59149 "AAAA IN super.mydomain.com. udp 41 true 1480" SERVFAIL qr,ra,cd 51 0.032238037s
[INFO] 94.41.157.98:64152 - 41303 "AAAA IN super.mydomain.com. udp 41 true 1480" SERVFAIL qr,ra,cd 51 0.032024896s
[INFO] 94.41.157.98:12565 - 31531 "AAAA IN super.mydomain.com. udp 41 true 1480" SERVFAIL qr,ra,cd 51 0.032073054s

And the regular expression option no longer works:

mydomain.com:53 {
    bind eth0
    rewrite name regex .*\\.mydomain\\.com google.com
    forward . dns://208.67.222.222
    log
    errors
}
I get an error: no internal type for both IPv4 and IPv6 Addresses (A+AAAA) for super.mydomain.com

And log:

[INFO] 94.41.80.15:42416 - 26429 "A IN super.mydomain.com. udp 41 true 1480" NOERROR qr,ra,cd 73 0.033101709s
[INFO] 94.41.80.15:7112 - 59074 "A IN super.mydomain.com. udp 41 true 1480" NOERROR qr,rd,ra,cd 73 0.032102316s
[INFO] 94.41.157.98:39775 - 34540 "AAAA IN super.mydomain.com. udp 41 true 1480" NOERROR qr,ra,cd 122 0.031993201s
[INFO] 94.41.157.98:35168 - 53147 "AAAA IN super.mydomain.com. udp 41 true 1480" NOERROR qr,rd,ra,cd 122 0.032036878s
^C[INFO] SIGINT: Shutting down

**Anything else we need to know?**: Nothing

**Environment**:

- the version of CoreDNS: CoreDNS-1.8.6 linux/amd64, go1.17.1, 13a9191
- Corefile: See above
- logs, if applicable: See above
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 11 (bullseye)
- Others: -

**Comment by chrisohaver** [comment]
try ... 

`rewrite name regex .*\.mydomain\.com\. google.com. answer auto`

**Comment by cyrillpetroff** [comment]
> try ...
> 
> `rewrite name regex .*\.mydomain\.com\. google.com. answer auto`

Everything works. Thanks.
