### ISSUE TITLE
Environment variables documented as inserted into corefile (but not quite so)

### ISSUE THREAD

**Issue by Kerrnel** [coredns/coredns#5003]
Putting "1.1.1.1 8.8.8.8 9.9.9.9" into FORWARD variable
Referencing {$FORWARD} in e.g.

`
forward . {$FORWARD}
`

gives an error that it is not an IP or filename.

No such restriction is documented afaics.

**Comment by chrisohaver** [comment]
> No such restriction is documented afaics.

I suppose it should be documented here somewhere, since caddy 1 docs are hard to find.

**Comment by miekg** [comment]
Or just copy the caddy 2 parsing code for caddy files
