### ISSUE TITLE
geoip middleware

### ISSUE THREAD

**Issue by felipewd** [coredns/coredns#513]
Hi all,

We're starting to use coredns with our application, and it's been great so far: Fast, reliable and simple. Thanks a lot for building and sharing this! :)

One thing we'd like to add is a geoip middleware, to sort the response based on the geoip of the client. We looked at the loadbalancer middleware to get inspired, but that code only has access to res.* variables, not the request. 

Without that, we can't build a proper geoip-based response.

Could anybody give me a few pointer on how to pass the req IP address (with or without EDNS) to a middleware?

**Comment by johnbelamaric** [comment]
In `ServeDNS` you get a `ResponseWriter` and a `dns.Msg`. Here is how you get the client source IP:

```
        state := request.Request{W: w, Req: r}
        source_ip := state.IP()
```

For an example (not merged though), see: https://github.com/johnbelamaric/coredns/blob/policy-middleware/middleware/policy/policy.go#L108 which may help.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] geoip middlewar..." ]
>In `ServeDNS` you get a `ResponseWriter` and a `dns.Msg`. Here is how you get the client source IP:
>
>```
>        state := request.Request{W: w, Req: r}
>        source_ip := state.IP()
>```

Yes, and state.Proto() the transport protocol used. See https://godoc.org/github.com/miekg/coredns/request
for more.

**Comment by miekg** [comment]
See #143 as well (feature request)
