### ISSUE TITLE
Rewrite middleware and fallthrough

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#515]
The rewrite middleware has `fallthrough` (at my request) to allows for falling through to the next middleware *even though* this middleware should be authoritative for this name.

q: should we keep something like `fallthrough` or just allow it? I'm not sure about the ramifications, but my gut feeling says that just allowing it can lead to weird to debug DNS issues... (and God forbid, maybe loops).
I'm also a fan of keeping things explicit; hence I think I'm in favor of keeping it.

**Comment by johnbelamaric** [comment]
I think we should keep it. I'd like to add it to the k8s one too.

**Comment by johnbelamaric** [comment]
Or maybe to etcd.

**Comment by miekg** [comment]
Ack. I can live with that. *Maybe* we should elevate it to be part of the Handler interface, as a `Fallthrough` method? We can then put in the NextOrFailure or something.

**Comment by miekg** [comment]
Best thing now is to document this behavior in `middleware.md`.

**Comment by stp-ip** [comment]
Adding fallthrough in general as a highlevel option would enable workarounds like having multiple ```auto``` directives within one server. Basically abusing fallthrough and the proxy middleware.
5053 -> auto . {} + proxy -> 5054 -> auto . {} + proxy -> 5055 -> k8s + proxy -> public resolution.
Huge performance issue, but would enable various workarounds and enable testing various solutions in the wild (ignoring the performance hit) until we can implement or decide to implement it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] Rewrite middlew..." ]
>Adding fallthrough in general as a highlevel option would enable workarounds like having multiple ```auto``` directives within one server. Basically abusing fallthrough and the proxy middleware.
>5053 -> auto . {} + proxy -> 5054 -> auto . {} + proxy -> 5055 -> k8s + proxy -> public resolution.
>Huge performance issue, but would enable various workarounds and enable testing various solutions in the wild (ignoring the performance hit) until we can implement or decide to implement it.

Not only a performance issue - what if your resolution fails, how do you debug
that? What about loops?

/Miek

--
Miek Gieben

**Comment by stp-ip** [comment]
One could also produce loops with the rewrite fallthrough. Debugging could be harder, but we could help by writing to the log each time a request falls through.
