### ISSUE TITLE
Graceful reload not working

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#519]
I found this while working on #511.

When doing a reload via SIGUSR1, the OnShutdown of the middleware is not being called. This is because the port bind is failing, so the Restart method is bailing partway through:

2017/02/10 15:55:00 [INFO] Reloading
2017/02/10 15:55:00 [INFO] Creating gRPC connection 0 to 127.0.0.1:4443.
2017/02/10 15:55:00 [INFO] Creating gRPC connection 1 to 127.0.0.1:4444.
2017/02/10 15:55:00 [ERROR] SIGUSR1: listen tcp :1053: bind: address already in use
It seems the issue stems from this statement here: https://github.com/mholt/caddy/blob/master/caddy.go#L619 - it seems dnsserver.Server is NOT implementing the GracefulServer interface: https://godoc.org/github.com/mholt/caddy#GracefulServer

**Comment by miekg** [comment]
@johnbelamaric not tested this myself yet. Does this work for you.

Also: can you easily distill a test? And I can probally add some code foo that makes sure coredns.Server implements the caddy.GracefulServer.
