### ISSUE TITLE
middleware/file: ignore SOA and use timeofday

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#528]
Add an option `ignore_serial` that on a zone reload just uses the time-of-day instead of the SOA serial.

**Comment by miekg** [comment]
damn, of course this doesn't work with DNSSEC.

**Comment by miekg** [comment]
But it can still be useful and with DNSSEC signing the SOA is usually bumped anyway - check for SOA sigs and then not perform this action even when enabled?

**Comment by stp-ip** [comment]
Why would one ignore the SOA? When someone changes the records they should also change the serial. Or a tool should do it for them. "breaking" the use of serial by ignoring it seems counterintuitive especially while this adds complexity to coredns and to DNSSEC signing.

**Comment by stp-ip** [comment]
So the real question is: What is the specific use-case besides people not updating their serial.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] middleware/file..." ]
>So the real question is: What is the specific use-case besides people not updating their serial.

people should not care, if a zone changed, the soa is incremented.

**Comment by miekg** [comment]
Pondering this some more as in the *auto* middleware we want to look at SOA records to see if zones have changed..

**Comment by stp-ip** [comment]
Ignoring SOA would only be usable for auto, if the new reload mechanism is introduced.

Idea:
read tree -> save last modified + file hash
read tree -> compare file modified and saved modified
  -> for miss -> generate file hash of new file -> compare hashes -> reload on miss
  -> for miss -> generate file hash of new file -> compare hashes -> save latest modify on hit

**Comment by miekg** [comment]
See #415, if we do something here it should apply to the *auto* middleware as well. Leaning again towards hashing the entire file and tracking that when `ignore_serial` is given.

**Comment by stp-ip** [comment]
My point here and in #415 was basically that hashing all files in every loop is not efficient. That's why I would introduce the layered approach with checking timestamps (file metadata) first.

Also it seems this is actually the better way to keep track of changes so it should be the default reload mechanism. What ignore_serial should do is disable another layer checking the SOA.

With ignore_serial:
time -> hash -> reload

Without ignore_serial/default:
time -> hash -> SOA

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] middleware/file..." ]
>My point here and in #415 was basically that hashing all files in every loop is not efficient. That's why I would introduce the layered approach with checking timestamps (file metadata) first.
>
>Also it seems this is actually the better way to keep track of changes so it should be the default reload mechanism. What ignore_serial should do is disable another layer checking the SOA.
>
>With ignore_serial:
>time -> hash -> reload
>
>Without ignore_serial/default:
>time -> hash -> SOA

Ack. This makes sense.

**Comment by stp-ip** [comment]
Could this go into 008?

**Comment by miekg** [comment]
Prolly won't make it for 008, also I think I need to see this in the larger picture of "fiddling with zones"

**Comment by miekg** [comment]
We will not do this.

**Comment by stp-ip** [comment]
Any reasoning behind not doing it? You were the proponent for this change, so would be interesting, why you redecided.

**Comment by miekg** [comment]
Doesn't work with DNSSEC and offline signing, i.e. need to resign the zone. *Might* revisit once I've worked out how to do DNSSEC entirely in the server (signing/succession and DS/CDS comms).

First other bugs instead of new features.
