### ISSUE TITLE
middleware/auto improve zone handling

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns#532]
Currently one has 2 options:

Option 1:
Have only one ```auto``` section such as:
```
    .:5053 {
      auto {
        directory /etc/source/files/zones/ (.*) {1} 30
        transfer to *
        transfer $provider_1
        transfer $provider_2
      }
    }
```

Option 2:
Add all zones served manually such as:
```
    .:5053 {
      auto production.example.com {
        directory /etc/source/files/zones/prod/ (.*) {1} 30
        transfer to *
        transfer $provider_1
      }
      auto development.example.com {
        directory /etc/source/files/zones/non-prod (.*) {1} 30
        transfer to *
        transfer $provider_2
      }
    }
```

Option 1 notifies both providers of updates and in general seems like the wrong solution.
Option 2 isn't really worth having the auto directive as one has to add all zones manually anyway.

Various solutions:
* bundle directory and transfer so only notifies to the right provider are done
* load zones from files instead of manually having to declare them
* let auto be chained basically it would run throught the first auto section for provider_1, if nothing is found it would use the section for provider_2 and if nothing is found it would SERVFAIL.

**Comment by miekg** [comment]
Shouldn't we just look at the NS records in the zones to infer upstreams?

**Comment by stp-ip** [comment]
Instead of providing ```transfer to $provider_ip``` you want to use the NS record?

That would mostly not work as the notify receiving and AXFR/IXFR servers of most providers are completely separated from their record serving servers, which would be the IPs you get back from using the NS record.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/coredns] middleware/auto..." ]
>Instead of providing ```transfer to $provider_ip``` you want to use the NS record?
>
>That would mostly not work as the notify receiving and AXFR/IXFR servers of most providers are completely separated from their record serving servers, which would be the IPs you get back from using the NS record.

Hmmm, good point.

**Comment by miekg** [comment]
We're contemplating the syntax for a language to allows filtering in #469. What you need IMHO is a specifier that takes the zone into account and then sets the upstream for notifies etc. Or maybe ticked off on where the zonefile lives, i.e. take the directory name into account.
~~~
transfer ${f:/non-prod/) to <something>
~~~
or something like that.

**Comment by stp-ip** [comment]
This would enable:
* catch-all zone
* paritioned notifies + transfers

Sounds like a better solution than fall through for this use-case.

**Comment by stp-ip** [comment]
transfer <file/path-regex> to <something>

most consistent would be the use of basepath instead of a regex, but that might limit usage.

basepath:
```
transfer /non-prod/ to 127.0.0.1
```

regex style:
```
transfer *dev* to 127.0.0.2
```
