### ISSUE TITLE
Move to github/coredns

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#538]
Tracking bug for things that break.

1. <strike>`Makefile.release` has hard ref to <github.com/miekg/coredns>.</strike>
2. More --> Add comments to this bug.

**Comment by miekg** [comment]
After the move split out the `logo` directory and put that in it's own coredns/logo repo.

**Comment by miekg** [comment]
Also the websites (and git repos) for coredns.io and blog.coredns.io.

**Comment by yongtang** [comment]
There might be some change in TravisCI and Codecov that are needed as well. But the changes are probably minor. We could just wait until it breaks and then fix it.

**Comment by miekg** [comment]
obviously this is now done. Moving some more website repos.

**Comment by miekg** [comment]
blogs have been moved and all links have been updated.

**Comment by yongtang** [comment]
The badge has been fixed. Now the import path in source code is still github.com/miekg/coredns. At some point when this import path is changed to github.com/coredns/coredns, the .travis.yml may need to be updated. But as release v006 is imminent, those changes could be deferred.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Move to githu..." ]
>The badge has been fixed. Now the import path in source code is still github.com/miekg/coredns. At some point when this import path is changed to github.com/coredns/coredns, the .travis.yml may need to be updated. But as release v006 is imminent, those changes could be deferred.

we can just do this now

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Move to githu..." ]
>The badge has been fixed. Now the import path in source code is still github.com/miekg/coredns. At some point when this import path is changed to github.com/coredns/coredns, the .travis.yml may need to be updated. But as release v006 is imminent, those changes could be deferred.

ah yeah, a simple grep show the size... Let's wait for 007 :)

**Comment by miekg** [comment]
done.
