### ISSUE TITLE
Enhancements for the google proxy

### ISSUE THREAD

**Issue by yawn** [coredns/coredns#540]
The google proxy is already working quite nicely for me in a non-server setting. I think it would benefit from the following enhancements though:

* [ ] automatically set `edns_client_subnet=0.0.0.0/0`
* [ ] automatically populate `random_padding` (either use random data or pad to 255 - length of the requested name)

From a security POV it might be sensible to:

* [ ] maybe support pinning (not sure how to ideally bootstrap this: in a client I wrote I hardcoded the fingerprints from https://www.ssllabs.com)
* [ ] maybe hardcode the G2 root certificate into the client TLS config
* [ ] there should be DNSSEC-signed zone matching the `dns.google.com` virtual CNAME ([equivalent](https://developers.google.com/speed/public-dns/faq) to the one for the public DNS service); this could be used to maintain a network whitelist

Maybe a faster HTTP client such as `fasthttp` might be useful. As soon as it's stable it might be also worthwhile to support QUIC on the client side (right now I could not measure a speed benefit over pooled HTTP/1.1 but this will obviously change in the future).

If you're interested I could decouple my client and provide it in a dedicated repository.

**Comment by miekg** [comment]
Happy to take PRs for the random padding stuff.
The EDNS0 client subnet might need broader support maybe in the *rewrite* middleware?

I have limited knowledge of your other suggested improvements. I do believe that hardcoding stuff is the wrong thing to do. Also we don't control dns.google.com so how can we add DNSSEC to that? And then CoreDNS does not have a resolver, so how to we asses it is correctly signed?

As for `fasthttp` I just want to stick to `net/http` but we should use http/2 and indeed maybe quic once it's available.

**Comment by yawn** [comment]
I've interpreted the EDNS client subnet option strictly in the sense of the documented privacy implications. Maybe we should just enable a passthrough option for a string in CIDR notation?

Padding: can do. For simplicities sake: pad with fixed characters up to `255 - len(name)`?

Regarding points 3..5:

3. pinning over the *public key* part of the presented certificate should be safe; [OWASP](https://www.owasp.org/index.php/Pinning_Cheat_Sheet#What_Should_Be_Pinned.3F) seems to indicate that Google's public keys should remain static / algorithm type (`vRer+nfp3FQHfMwZiqnU+2ErDAFfpIbz+am1/F1Uh8Q=` and `7HIpactkIAq2Y49orFOOQKurWxmmSFZhBCoQYcRhJ3Y=`)
4. Hardcoding [G2](https://pki.google.com) would also work, at least until the certificate expires

To be clear: primarily both points would just ensure that no hijacking can occur in hostile (e.g. cooperate) environments with HTTPS MITM happening transparently. Some form of pinning in Chrome was used in the past to detect CA [abuses](https://www.eff.org/deeplinks/2011/08/iranian-man-middle-attack-against-google) by state actors. 

5. was about verifying that a resolved IP address for `dns.google.com` is actually valid; this can be done through the locations DNS API which supports DNSSEC in itself (e.g. `dig +dnssec TXT locations.publicdns.goog @8.8.8.8`); unfortunately the equivalent for DNS-over-HTTPS (`locations.publicdns-https.goog`) does not seem to return equivalent TXT records - so unless I'm blind scratch 5

One more thing: wdyt about passing through `RRSIG`records? When doing a query with an appropriate `type` parameter (e.g. 255) DNSSEC enabled domains such as `example.com` could be proxied *with* DNSSEC still intact.

**Comment by miekg** [comment]
> One more thing: wdyt about passing through RRSIGrecords? When doing a query with an appropriate type parameter (e.g. 255) DNSSEC enabled domains such as example.com could be proxied with  DNSSEC still intact.

You mean allow '+cd+ to be specified? Yes that can work. Corefile-syntax wise we would probably have to  add another block where this can be specified:
~~~~
protocol https_google {
# extra options
}
~~~~

> 5. was about verifying that a resolved IP address for dns.google.com is actually valid; 

If it's not valid the cert wont match?

> 4. Hardcoding G2 would also work, 

I would like to avoid hard coding stuff as much as possible.

> Padding: can do. For simplicities sake: pad with fixed characters up to 255 - len(name)?

Why use len(name) here? We don't have a length restriction? Oh you want every thing to be of the same size. Interesting. I would not know what would be better.

**Comment by yawn** [comment]
Yes, support for `cd` would be awesome. This would allow e.g. using `dnssec-check-unsigned` for local `dnsmasq` setups.

Regarding 3..5: I think we (= you) should make a decision if we trust the CA chain enough for DNS. Google itself [recommends](https://security.googleblog.com/2017/01/the-foundation-of-more-secure-web.html?m=1) introducing a bundle of trustworthy roots for clients that want to securely connect to Google properties. Pinning will archive a similar level of security I believe.

In any case we should deprecate this issue and split it into 2..3 more:

* Auto-Padding
* EDNS0 client subnet support for the google proxy
* DNSSEC / `cd` for the google proxy
* Depending on your POV: pinning and / or explicit `*x509.CertPool` for the google proxy

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Enhancements ..." ]
>Yes, support for `cd` would be awesome. This would allow e.g. using `dnssec-check-unsigned` for local `dnsmasq` setups.
>
>Regarding 3..5: I think we (= you) should make a decision if we trust the CA chain enough for DNS. Google itself [recommends](https://security.googleblog.com/2017/01/the-foundation-of-more-secure-web.html?m=1) introducing a bundle of trustworthy roots for clients that want to securely connect to Google properties. Pinning will archive a similar level of security I believe.
>
>In any case we should deprecate this issue and split it into 2..3 more:
>
>* Auto-Padding
>* EDNS0 client subnet support for the google proxy
>* DNSSEC / `cd` for the google proxy

Please do! Up for sending a PR?

>* Depending on your POV: pinning and / or explicit `*x509.CertPool` for the google proxy

If something changes in this setup do you need to recompile CoreDNS (or update
config) to make things work again?

**Comment by yawn** [comment]
PR and issue: can do. Regarding the latter: for pinning we can easily expose the pins as part of the configuration: the behaviour could be even optional (no pins supplied means no pinning); for certificate pools this would be a little bit more ugly but we could pass e.g. G2 as PEM directly in the `Corefile`; maybe we should just support pinning this way?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Enhancements ..." ]
>PR and issue: can do. 

Nice! :)


> Regarding the latter: for pinning we can easily expose the pins as part of the configuration: the behaviour could be even optional (no pins supplied means no pinning); for certificate pools this would be a little bit more ugly but we could pass e.g. G2 as PEM directly in the `Corefile`; maybe we should just support pinning this way?

there is already code that loads certs and other files for TLS should be
relatively easy to re-use to for pinning. But do make it optional and explains
the tradeoff in the README.

Thanks!

/Miek

--
Miek Gieben

**Comment by yawn** [comment]
FYI: functionally I got pinning & padding done. Next step would be figuring out how to extend the proxy config.

**Comment by miekg** [comment]
Cool. Please submit these things and pieces so that reviewing becomes easier.

**Comment by namliz** [comment]
@miekg I really like this and am wondering whether you're open to expanding this to upstreams other than `dns.google.com`? 

dns-over-json is not an official standard afaik but seems incredibly easy to implement and this potentially has interesting uses. 

```
. {
    proxy . customdns.hostname.tld {
    protocol https_google bootstrap [127.0.0.1:3128|http(s)://customdns.hostname.tld/whatever/]
    }
    log stdout
}
```

- Custom TO instead of hardcoded 'dns.google.com'
- Ability to bootstrap to an IP:Port or an address
- With or without TLS, With TLS verification off 

The result would be CoreDNS wrapping an endpoint at http://customdns.hostname.tld/whatever/resolve?name=query with a dns interface.

**Comment by miekg** [comment]
We should reformat the `protocol` option a bit for all these features - becomes a bit to long.

* Custom `to` could be done
* Bootstrapping should already work like you say. Otherwise am I misinterpreting what you are saying?

The only downside is that the google https json stuff is not standardized and the protocol is not well specified.

**Comment by yawn** [comment]
Finally managed to look through the config mechanism and pushed the changes to my fork. Things that still need to be done:

* Fix tests
* Update `upstream_test.go` for configuration changes
* Check if error messages conform to the projects standard

**Comment by namliz** [comment]
@miekg bootstrapping stanza unfortunately demands currently an IP:PORT pair, doesn't work with an address.

I agree the syntax is becoming finicky. 

And yes the https json stuff is not a standard but in so far as it is already useful to support it in CoreDNS it is also useful to be able point at your own server endpoint (heck, even for testing purposes).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Enhancements ..." ]
>@miekg bootstrapping unfortunately demands currently an IP:PORT pair, doesn't work with an address.

Ah, so. Yes, this is becoming a cyclic dependency rather quickly.. If you don't
have a fixed address for DNS resolution things get tricky.

>I agree the syntax is becoming finicky.
>
>And yes the https json stuff is not a standard but in so far as it is already useful to support it in CoreDNS it is also useful to be able point at your own server endpoint (heck, even for testing purposes).

agreed. But we should add another block of parsing for all/some of these
options. I.e.

```
 ...
 protocol https_google {
    bootstrap
    tls
 }
 ...
 ```

**Comment by yawn** [comment]
Yeah, the changes to the config format are already in my PR. I *really* hope to get it ready-for-review on Friday.

**Comment by namliz** [comment]
> Ah, so. Yes, this is becoming a cyclic dependency rather quickly.. If you don't
have a fixed address for DNS resolution things get tricky.

It might be too clever but I believe CoreDNS could benefit from being re-entrant. 
Whenever you hit a hostname in the Corefile simply start resolving that from the top.

```
. {
    proxy example.org customdns.hostname.com {
      except hostname.com # implicit, can omit in config
      protocol https_google {
              bootstrap http://customdns.hostname.com/whatever/
              #tls
      }
    }
    log stdout
}
```

What do you reckon? In this case `hostname.com` would be resolved by the system dns but the interesting possibility opens up of adding another stanza that would capture it and send it to some other middleware (like etcd).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Enhancements ..." ]
>> Ah, so. Yes, this is becoming a cyclic dependency rather quickly.. If you don't
>have a fixed address for DNS resolution things get tricky.
>
>It might be too clever but I believe CoreDNS could benefit from being re-entrant.
>Whenever you hit an IP:PORT pairing in the Corefile simply start resolving that from the top.
>
>```
>. {
>    proxy example.org customdns.hostname.com {
>      except hostname.com # implicit, can omit in config
>      protocol https_google {
>              bootstrap http://customdns.hostname.com/whatever/
>              #tls
>      }
>    }
>    log stdout
>}
>```
>
>What do you reckon?

Let's not complicate this further. I think if you name something "bootstrap" in a
DNS server there can be a reasonable assumption that it will be an IP address.

/Miek

--
Miek Gieben

**Comment by namliz** [comment]
Fair enough, I was just contemplating how far one can run with the middleware idea. 

The appeal to me is that CoreDNS could wrap a run of the mill HTTP endpoint with a dns interface. You don't have a static IP available to point at in every situation (Heck, a file on s3 for a contrived example).

Say you have a datastore exposed somewhere at some address that lists instances. 

HTTP Endpoint <---> Server A: CoreDNS Proxy middleware <---> Server B

Maybe it makes more sense like this:

```
. {
    proxy example.org http://www.hostname.com/whatever/ {
      protocol dns_over_json
    }
    log stdout
}
```

`curl -s http://www.hostname.com/whatever/resolve?name=foo.com | jq '.Answer[0].data' `

"23.21.224.150"

Anyhow, I don't want to belabor the point - if it is clear but my use case is out of scope, so be it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Enhancements ..." ]
>Fair enough, I was just contemplating how far one can run with the middleware idea.
>
>The appeal to me is that CoreDNS could wrap a run of the mill HTTP endpoint with a dns interface. You don't have a static IP available to point at in every situation (Heck, a file on s3 for a contrived example).
>
>Say you have a datastore exposed somewhere at some address that lists instances.
>
>HTTP Endpoint <---> Server A: CoreDNS Proxy middleware <---> Server B
>
>Maybe it makes more sense like this:
>
>```
>. {
>    proxy example.org http://www.hostname.com/whatever/ {
>      protocol dns_over_json
>    }
>    log stdout
>}
>```
>
>`curl -s http://www.hostname.com/whatever/resolve?name=foo.com | jq '.Answer[0].data' `
>
>"23.21.224.150"
>
>Anyhow, I don't want to belabor the point - if it is clear but my use case is out of scope, so be it.

Note: I'm not directly saying out of scope, but separate from this PR/issue.
Please file a new one for this (copy some of the above text in there pleas), and
we can discuss there.

**Comment by miekg** [comment]
no progress here. Closing for now.
