### ISSUE TITLE
006 release imminent

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#543]
I have nothing more to fix, testing a recent git version on my server and soon on my raspberry pi.

Anything else?

**Comment by johnbelamaric** [comment]
I have something I'd like to get in there. I will submit a PR in a few minutes and you can see what you think.

**Comment by miekg** [comment]
*suspense* :+1:

**Comment by johnbelamaric** [comment]
Ugh, needs rebase. Here it is if you can't stand the suspense! https://github.com/johnbelamaric/coredns/tree/grpc-tracing

Basically it allows tracing to go through the grpc client calls so you can trace a request across the client and server.
