### ISSUE TITLE
Should we validate the domain name rather than providing answer for incorrect domain record configured?

### ISSUE THREAD

**Issue by harry1064** [coredns/coredns#5450]
I have configured a record with `*.*.ns1.example.com` in the db file zone `example.com`

Then I used dig command to query `something.*.ns1.example.com` and got back this response

```
; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 53 *.*.ns1.foo.example
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34412
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;*.*.ns1.foo.example.		IN	A

;; ANSWER SECTION:
*.*.ns1.foo.example.	3600	IN	A	10.0.0.53

;; AUTHORITY SECTION:
foo.example.		3600	IN	NS	ns1.foo.example.
foo.example.		3600	IN	NS	ns2.foo.example.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jun 22 02:56:32 HKT 2022
;; MSG SIZE  rcvd: 163
```
Is this a correct reply to be sent back as query domain name is not a valid domain name as per RFC specs?

Even `_` is acceptable in the label. Should coredns have some validations? or it should be the responsibility of person who write zone files?

```
; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 53 som_sds.*.ns1.foo.example
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45802
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;som_sds.*.ns1.foo.example.	IN	A

;; ANSWER SECTION:
som_sds.*.ns1.foo.example. 3600	IN	A	10.0.0.53

;; AUTHORITY SECTION:
foo.example.		3600	IN	NS	ns1.foo.example.
foo.example.		3600	IN	NS	ns2.foo.example.

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jun 22 02:58:48 HKT 2022
;; MSG SIZE  rcvd: 175
```

**Comment by chrisohaver** [comment]
> Is this a correct reply to be sent back as query domain name is not a valid domain name as per RFC specs?

`*.*.ns1.foo.example` and `som_sds.*.ns1.foo.example` are both valid domains per RFC.  The RFCs permit pretty much anything in a dns label.  There are length limits; that's about it. https://datatracker.ietf.org/doc/html/rfc1035#section-3.1

I think you'll have trouble finding a dns tool that actually allows you to send a request with an invalid domain.
But I think if CoreDNS receives one, it would return FORMERR (not 100% sure).

**Comment by harry1064** [comment]
Got it. Thanks @chrisohaver 

I have one another question, I don't know if it is relevant, Should we have some validation on domain names while parsing db files of zones?

**Comment by chrisohaver** [comment]
I don’t think it’s needed.

**Comment by harry1064** [comment]
okay. Thanks @chrisohaver 

I am closing the issue now. I have a comment on another issue [4256](https://github.com/coredns/coredns/issues/4256#issue-735809706)
Would love to hear about your feedback.
