### ISSUE TITLE
middleware/kubernetes: remove sh and yaml files

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#550]
Please remove (or move to subrepo) the `deploy.sh` and `coredns.yaml.sed` files. They serve as doc helpers and as such clutter the repo (a bit).

If used for tests they should move to .travis/kubernetes.

**Comment by johnbelamaric** [comment]
Ok, do we want a "docs" repo or maybe a "deploy" repo?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>Ok, do we want a "docs" repo or maybe a "deploy" repo?

kubernetes?

**Comment by johnbelamaric** [comment]
Hmm. What else would be in there? Seems kind of narrow. A "deploy" (or "deployment" or "packaging") one could have different scripts/manifests for deploying it in different environments. That was my line of thinking anyway. Or maybe it's just docs - so for example we could also document an example using a git-sync sidecar and auto middleware.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>Hmm. What else would be in there? Seems kind of narrow. A "deploy" (or "deployment" or "packaging") one could have different scripts/manifests for deploying it in different environments. That was my line of thinking anyway. Or maybe it's just docs - so for example we could also document an example using a git-sync sidecar and auto middleware.

Ah ok. Thought it would be more k8s oriented. "deploy" or "deployment SGTM

**Comment by johnbelamaric** [comment]
#554
