### ISSUE TITLE
release infra

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#555]
Need to setup some release (ci-server?) infra that handles releases and docker images (still need to upload 006 to the docker hub)

**Comment by sorenmat** [comment]
Any news on this one, I'm missing the version 006 docker image. Would be glad to help, if you could outline what the process should be?

**Comment by miekg** [comment]
I've uploaded the docker images and sent a PR #562 to make it more part of the release process.

I'm looking for a travis-CI like infra that allows me to run tests and kick of releases out of that. OTOH maybe `Makefile.release` is good enough for the time being?

**Comment by miekg** [comment]
Closing here, discussing with CNCF about have access to some compute somewhere.
