### ISSUE TITLE
grpc in go/dns

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#556]
I will file a separate bug in go dns as well, but I think it will be time well spend to make somekind of Transport layer on Go DNS that allows for a more natural way to use gRPC. This way the gRPC server part could be a more normal middleware and can be moved into this repo.

**Comment by miekg** [comment]
see https://github.com/miekg/dns/issues/464

**Comment by miekg** [comment]
@johnbelamaric this is work. I think it is worth doing, but there might be other things that have more prio.

**Comment by mwitkow** [comment]
@miekg would this be usable for Stub zones? I.e. a local `coredns` instance serves requests over DNS and if it doesn't find it forwards it to the stub-zoned `coredns` over gRPC?

This would allow us to avoid MTU issues crossing between clusters of Stub-zoned DNS.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] grpc in go/dn..." ]
>@miekg would this be usable for Stub zones? I.e. a local `coredns` instance serves requests over DNS and if it doesn't find it forwards it to the stub-zoned `coredns` over gRPC?
>
>This would allow us to avoid MTU issues crossing between clusters of Stub-zoned DNS.

probably...

First I want to allow DNS-over-gRPC to be a first class citizen in Go DNS
https://github.com/miekg/dns/issues/464

this would make plumbing it through CoreDNS easier as we can merge the gRPC
serving middleware as well (github.com/coredns/grpc)

**Comment by miekg** [comment]
Closing this, as #574 show promise of doing this entirely in CoreDNS - adding gRPC to Go DNS is not the way forward.
