### ISSUE TITLE
RSS feed for blog?

### ISSUE THREAD

**Issue by skpy** [coredns/coredns#557]
Not strictly related to the CoreDNS code, but an RSS or ATOM feed of the blog would be super helpful.  I'm lazy, and would much rather have my feed reader collect new posts than have to remember to visit the blog on a regular basis.  Thanks!

**Comment by miekg** [comment]
I've added a subscribe link in the footer that references the index.xml

**Comment by skpy** [comment]
❤️ Thanks!
