### ISSUE TITLE
dns: bad rdlength and dns: buffer size too small when using coredns and prometheus dns_sd

### ISSUE THREAD

**Issue by f0** [coredns/coredns#558]
Hi,

i use coredns with the etcd backend to provide dns_sd for prometheus
https://prometheus.io/docs/operating/configuration/#%3Cdns_sd_config%3E

i see such errors in the prometheus log, an ideas?

```
Feb 26 20:27:10 hw2067.example.net rkt[96880]: [1432236.258653] admin-monitor[50]: time="2017-02-26T19:27:10Z" level=warning msg="DNS resolution failed." name=node.backends.sysmon.local reason="dns: buffer size too small" server=172.16.28.1 source="dns.go:205"
Feb 26 20:27:10 hw2067.example.net rkt[96880]: [1432236.259343] admin-monitor[50]: time="2017-02-26T19:27:10Z" level=error msg="Error refreshing DNS targets: could not resolve node.backends.sysmon.local: no server responded" source="dns.go:116"
Feb 26 20:27:10 hw2067.example.net rkt[96880]: [1432236.259714] admin-monitor[50]: time="2017-02-26T19:27:10Z" level=warning msg="DNS resolution failed." name=cadvisor.backends.sysmon.local reason="dns: bad rdlength" server=172.16.28.1 source="dns.go:205"
Feb 26 20:27:10 hw2067.example.net rkt[96880]: [1432236.260097] admin-monitor[50]: time="2017-02-26T19:27:10Z" level=error msg="Error refreshing DNS targets: could not resolve cadvisor.backends.sysmon.local: no server responded" source="dns.go:116"

```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] dns: bad rdlength..." ]
>Hi,
>
>i use coredns with the etcd backend to provide dns_sd for prometheus
>https://prometheus.io/docs/operating/configuration/#%3Cdns_sd_config%3E
>
>i see such errors in the prometheus log, an ideas?
>
>```
>Feb 26 20:27:10 hw2067.example.net rkt[96880]: [1432236.258653] admin-monitor[50]: time="2017-02-26T19:27:10Z" level=warning msg="DNS resolution failed." name=node.backends.sysmon.local reason="dns: buffer size too small" server=172.16.28.1 source="dns.go:205"
>Feb 26 20:27:10 hw2067.example.net rkt[96880]: [1432236.259343] admin-monitor[50]: time="2017-02-26T19:27:10Z" level=error msg="Error refreshing DNS targets: could not resolve node.backends.sysmon.local: no server responded" source="dns.go:116"
>Feb 26 20:27:10 hw2067.example.net rkt[96880]: [1432236.259714] admin-monitor[50]: time="2017-02-26T19:27:10Z" level=warning msg="DNS resolution failed." name=cadvisor.backends.sysmon.local reason="dns: bad rdlength" server=172.16.28.1 source="dns.go:205"
>Feb 26 20:27:10 hw2067.example.net rkt[96880]: [1432236.260097] admin-monitor[50]: time="2017-02-26T19:27:10Z" level=error msg="Error refreshing DNS targets: could not resolve cadvisor.backends.sysmon.local: no server responded" source="dns.go:116"
>Feb 26 20:27:13 hw2067.example.net rkt[96880]: [1432238.936926] admin-monitor[50]:
>```

Not without more debugging. What's being asked, what's sent over the wire, etc.
etc.?

**Comment by f0** [comment]
i ask for a SRV record, and with dig, i got the correct answer

```
dig -t SRV @localhost node.backends.sysmon.local

; <<>> DiG 9.10.2-P4 <<>> -t SRV @localhost node.backends.sysmon.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59851
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 51, AUTHORITY: 0, ADDITIONAL: 43

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;node.backends.sysmon.local.    IN      SRV

;; ANSWER SECTION:
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw1910.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw1911.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw1927.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2419.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2422.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2436.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2578.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw1909.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2606.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2614.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2620.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw3981.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2581.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2613.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2615.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2618.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw3978.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw3979.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2583.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2433.example.net.
node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2576.example.net.
...
```

prometheus also got an answer (the systems are shown in the config), but also this errors.

regards f0

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] dns: bad rdle..." ]
>i ask for a SRV record, and with dig, i got the correct answer
>
>```
>dig -t SRV @localhost node.backends.sysmon.local
>
>; <<>> DiG 9.10.2-P4 <<>> -t SRV @localhost node.backends.sysmon.local
>; (1 server found)
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59851
>;; flags: qr aa rd ra; QUERY: 1, ANSWER: 51, AUTHORITY: 0, ADDITIONAL: 43
>
>;; OPT PSEUDOSECTION:
>; EDNS: version: 0, flags:; udp: 4096
>;; QUESTION SECTION:
>;node.backends.sysmon.local.    IN      SRV
>
>;; ANSWER SECTION:
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw1910.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw1911.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw1927.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2419.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2422.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2436.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2578.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw1909.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2606.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2614.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2620.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw3981.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2581.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2613.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2615.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2618.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw3978.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw3979.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2583.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2433.example.net.
>node.backends.sysmon.local. 124 IN      SRV     10 1 9100 hw2576.example.net.
>...
>```
>
>prometheus also got an answer (the systems are shown in the config), but also this errors.

So it *does* work, but just spews the errors? I *think* this is trying to unpack
a message in a buffer that is too small. Is the TC bit set on some of these?

(Again tcpdumps with the data would show this)

**Comment by miekg** [comment]
Has this been debugged from your side? Is this still an issue?

**Comment by f0** [comment]
@miekg hi, sorry for the delay...

yes this is still an issue.

i have done a tcpdump, and if i look at the time i got an error from prometheus there is no error in the dump.

I can send you the dump if needed (can't drop here)

regards f0

**Comment by miekg** [comment]
understood, send the dump to miek@miek.nl

**Comment by f0** [comment]
@miekg  mail is on the way

**Comment by f0** [comment]
@miekg  in the dump, you see 2 big Answers and some small ones, only the big ones are failing

**Comment by miekg** [comment]
From the dump is seems CoreDNS does not properly set the TC bit. I've got the corefile and try to replicate this setup.

**Comment by f0** [comment]
updated to latest coredns release (006) now i can not reproduce the error, seems fixed between 005 and 006
