### ISSUE TITLE
Add ability to re-load Corefile on signal

### ISSUE THREAD

**Issue by mwitkow** [coredns/coredns#559]
Not sure if coredns already supports it, it is available in upstream Caddy Server:
https://github.com/mholt/caddy/issues/107

We're thinking of migrating away etcd-defined Stub zones to `proxy <zone> destination` declaration and dynamically generating the proxied stub zones using something like [confd](https://github.com/kelseyhightower/confd).

Using `proxy` instead of `etcd` `stubzones` would allow us to use the experimental `grpc` transport for cross cluster communication

@kdima for context

**Comment by miekg** [comment]
Yes, this works, same signal `SIGUSR1`
