### ISSUE TITLE
List MAINTAINERS in a file

### ISSUE THREAD

**Issue by caniszczyk** [coredns/coredns#566]
It would be great if there was a file called MAINTAINERS (or OWNERS) that listed the leads/committers of the project. See Prometheus for inspiration: https://github.com/prometheus/prometheus/blob/master/MAINTAINERS.md

**Comment by miekg** [comment]
We should prolly generate said file when doing a release.

**Comment by stp-ip** [comment]
Not sure it really makes sense to generate that. As coredns won't grow to the size of kubernetes or the like the maintainers should not grow over 5 or maybe 10 so automation doesn't seems really efficient.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] List MAINTAIN..." ]
>Not sure it really makes sense to generate that. As coredns won't grow to the size of kubernetes or the like the maintainers should not grow over 5 or maybe 10 so automation doesn't seems really efficient.

True. But the desire to generate is not about size, but making it automatable
when doing a release.
