### ISSUE TITLE
errors middleware too spammy

### ISSUE THREAD

**Issue by kdima** [coredns/coredns#568]
Currently if you enable `errors` middleware you get a log for every invalid domain. Which means that if you have multiple search domains every dns request generates a number of error logs. Making `errors` middleware unusable. 
Example:
```
03/Mar/2017:14:12:40 +0000 [ERROR 0 test.svc.domain.improbable.io. AAAA] invalid query name
03/Mar/2017:14:12:41 +0000 [ERROR 0 some_other_service.improbable.io.svc.domain.improbable.io. AAAA] invalid query name
03/Mar/2017:14:12:41 +0000 [ERROR 0 some_other_service.improbable.io.domain.improbable.io. AAAA] invalid query name
03/Mar/2017:14:12:41 +0000 [ERROR 0 some_other_service.improbable.io.other_domain.improbable.io. AAAA] 100: Key not found (/skydns/io/something) [881827]
03/Mar/2017:14:12:41 +0000 [ERROR 0 some_other_service.improbable.io.domain.improbable.io. A] no items found
03/Mar/2017:14:12:43 +0000 [ERROR 0 kibana.domain.improbable.io. AAAA] invalid query name
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] errors middleware..." ]
>Currently if you enable `errors` middleware you get a log for every invalid domain. Which means that if you have multiple search domains every dns request generates a number of error logs. Making `errors` middleware unusable.
>Example:
>```
>03/Mar/2017:14:12:40 +0000 [ERROR 0 test.svc.domain.improbable.io. AAAA] invalid query name
>03/Mar/2017:14:12:41 +0000 [ERROR 0 some_other_service.improbable.io.svc.domain.improbable.io. AAAA] invalid query name
>03/Mar/2017:14:12:41 +0000 [ERROR 0 some_other_service.improbable.io.domain.improbable.io. AAAA] invalid query name
>03/Mar/2017:14:12:41 +0000 [ERROR 0 some_other_service.improbable.io.other_domain.improbable.io. AAAA] 100: Key not found (/skydns/io/something) [881827]
>03/Mar/2017:14:12:41 +0000 [ERROR 0 some_other_service.improbable.io.domain.improbable.io. A] no items found
>03/Mar/2017:14:12:43 +0000 [ERROR 0 kibana.domain.improbable.io. AAAA] invalid query name
>```

Yes, this looks suboptimal.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Think the `errInvalidRequest` should just not be logged.
