### ISSUE TITLE
net/context -> context

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#578]
We need to move all the older net/context calls over to the newer (go1.7) context package.

**Comment by miekg** [comment]
We can't move as long as grpc is using the external package.

The `protoc` tool chain needs a flip to generate the correct context package.

**Comment by johnbelamaric** [comment]
You mean our grpc code or the whole grpc lib and related ecosystem?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] net/context -..." ]
>You mean our grpc code or the whole grpc lib and related ecosystem?

both. The generation can be fixed. But it hooks into the grpc ecosystem
that still expects a net/context

**Comment by miekg** [comment]
Once go 1.9 is out?
