### ISSUE TITLE
middleware/cache: Prefetch entries

### ISSUE THREAD

**Issue by SuperQ** [coredns/coredns#581]
Feature proposal:

Add a `prefetch` feature to the cache.  This allows for cached records to be updated before the TTL expires.  This is useful to avoid empty cache records for frequently used DNS-based service discovery records.

**Comment by miekg** [comment]
Excellent idea. Note that *cache* is relative standalone, so the trick here will be: with what mechanism will the cache be refilled?

**Comment by miekg** [comment]
While talking with @stp-ip at KubeCon we somewhat settled that we should implement this in the caching middleware, i.e. add a proxy stanza to allow prefetch.

We also need to tell it when a record is 'hot' and should be prefetched, before the TTL expires. Popular might be defined as: x queries/minute.
~~~
prefetch ADRESS... {
     threshold 5 # meaning 5 requests seens in the last minute
}
~~~
And have threshold be some kind of default, so `prefetch ADDRESS..` will work as well.

**Comment by miekg** [comment]
Don't think we can fix this in time for 007 release (want to do that this month). Bumping to 008

**Comment by miekg** [comment]
I'm hoping to work on this, this week, in time for the 008 release.

**Comment by SuperQ** [comment]
Looks like this made it into 008. 🎉
