### ISSUE TITLE
Let's encrypt for TLS?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#582]
Now that TLS gets more prominent it makes sense to think more about automation. Specifically, can we use the let's encrypt stuff from Caddy? Does that even make sense to a DNS server?

I might also be worth to copy the tls `setup.go` from Caddy to have both impl. be somewhat in sync in how they parse the stanza.

**Comment by johnbelamaric** [comment]
I think it makes sense for the gRPC transport at a minimum.

**Comment by miekg** [comment]
On thing we need here (Caddy is contemplating something similar, but I don't like the direction they are taking; abstract storage away), is a means of having multiple CoreDNS instances being able to use each other as a let's encrypt proxies. They should only vaguely be aware of each other.

Of course there is the tricky bit of selecting a master, but maybe we can do something simple like hashing the names of the diff. instances and the start of the top of the list.

Another tricky bit is ACLing who is allowed to contact you and ratelimiting.
