### ISSUE TITLE
fix middleware/tls

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#584]
for gRPC to work fully the *tls* middleware needs to be updated to actually do something. We should take inspiration from https://caddyserver.com/docs/tls.

**Comment by johnbelamaric** [comment]
This works fine, at least for gRPC. I did improve the README with #631 .

**Comment by miekg** [comment]
Really? Ok, cool :-)

Is it possible to do TLS tests?

For 008 release I will look into Let's encrypt integration.

**Comment by johnbelamaric** [comment]
Sure, we can add some TLS tests.

**Comment by miekg** [comment]
Closing as it works.
