### ISSUE TITLE
middleware/health: allow changing path

### ISSUE THREAD

**Issue by mfischer-zd** [coredns/coredns#585]
Kubernetes standard is to serve health at `/healthz` path; other site standards may vary.

**Comment by johnbelamaric** [comment]
Ok, makes sense. I'd like to see readiness checks as well, and to have the health and readiness checks validate the health/readiness of each middleware.

**Comment by miekg** [comment]
What's the issue with the path btw? It's trivial to change on the prometheus side. /healthz is also a Google-ism. (Making path configurable is trivial as well otoh)

**Comment by mfischer-zd** [comment]
There's nothing wrong with the default path that I can think of.

**Comment by mfischer-zd** [comment]
@johnbelamaric Would you mind filing a separate issue re: the improvements you seek?

**Comment by johnbelamaric** [comment]
#587 and #588

**Comment by miekg** [comment]
So...? What do you want to accomplish with this issue then? :)

**Comment by mfischer-zd** [comment]
@miekg Make the endpoint configurable so that it can be made to comply with local site standards where necessary.  (Not clear from the title/description?)

**Comment by miekg** [comment]
Ack. Please send code :)

**Comment by mfischer-zd** [comment]
K :)

**Comment by miekg** [comment]
If noone cares enough to send code, we should probably close this
