### ISSUE TITLE
coredns logging format

### ISSUE THREAD

**Issue by ifelsefi** [coredns/coredns#5864]
Hi

Can you please tell me why core-dns logs show ".0" for client pod ip:

```[INFO] 172.29.17.0:15439 - 50129 "AAAA IN server.cluster.local. tcp 54 false 65535" NXDOMAIN qr,aa,rd 147 0.000046555s```

The default Common Log Format is:

`{remote}:{port} - {>id} "{type} {class} {name} {proto} {size} {>do} {>bufsize}" {rcode} {>rflags} {rsize} {duration}`

See https://coredns.io/plugins/log/

I am trying to track which pods are generating these queries but the IPs are not valid since they end in zero.

**Comment by chrisohaver** [comment]
It logs what it gets from the network packet.  IOW, if it shows a ".0" at the end of the client IP, it's because that is how it was in the source address of the dns request network packet.

**Comment by ifelsefi** [comment]
Thank you.  Perhaps related to CNI.
