### ISSUE TITLE
middleware/health: Per middleware health status

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#587]
I'd like to add functionality in the health middleware so that it calls a health check function on each installed middleware and only returns a healthy status if all middleware are healthy. For example, proxy could consider itself unhealthy if all upstream resolvers are unhealthy.

The reply could also contain some details of status for each middleware.

**Comment by miekg** [comment]
Yes this makes sense.

I would caution with putting anything more than 'OK' in the health reply though, before we know it we're exporting a giant HTTP API.

**Comment by miekg** [comment]
I think (now) that this is *not*  a good idea

**Comment by miekg** [comment]
This https://github.com/coredns/coredns/pull/976 does this.

I've changed my mind again :)

**Comment by miekg** [comment]
<strike>There is a complication here as the health check is process wide and not per server. So if you have two different servers you'll need two different health check endpoints.</strike>
You'll need to start multiple health middlewares per server and manually pick another port for it to listen on

**Comment by miekg** [comment]
That PR has been merged. Infrastructure to support this is now there.
