### ISSUE TITLE
middleware/health: Readiness check

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#588]
We should add a readiness check as part of the health middleware. Similar to the check described in #587, it should ask each middleware if it is ready. For example, between initialization and finishing loading zone data, the a middleware may be healthy but not ready.

**Comment by miekg** [comment]
We should check caddy's Events: https://godoc.org/github.com/mholt/caddy#EmitEvent
Seems that we could leverage this for more things as well (*maaaybee* monitoring, but I have some performance concerns there)

**Comment by miekg** [comment]
This is really complicated as some middleware automatically loads new stuff, such as the *auto* middleware. So it can become healthy and then unhealhy again.

I think this should be solved with monitoring, not with healthhecking.

Health OK for CoreDNS mean: binary is up and some stuff is working

**Comment by miekg** [comment]
I'll think I'm going to see if events work here. Each middleware defines its own health state and the health middleware capture the global state of coredns. Meaning one unhealthy middleware makes coredns unhealthy.

And middleware like auto might only consider themselves healthy when they have 0 zones are something.  The only thing the health middleware needs to know is what middleware exists in the server. Or we make it explicit by needing it to be configured in the Corefile. That at least makes you think about what middleware you care about.

**Comment by miekg** [comment]
Hmm caddy events seems to work in the other direction. Then we should just call a Health function in each middleware that returns a http status code

**Comment by kfox1111** [comment]
Its ok I think for pods to go ready/unready. k8s should route traffic around the bad servers.

I think maybe it would be good if each plugin had a config option to enable/disable its voting in the health check. Maybe 3 options?
readyvote: [fresh-only, stale-ok, ignored] 

'fresh-only' passes the readyness check only if it has all its zones pulled down and it has an up to date copy of them all.

'stale-ok' would cover if it can serve out a zone, but it isn't necessarily up to date. This would let a hypothetical persistent slave plugin serve immediately if its parent wasn't immediately available. I can see some cases the user might want to allow this.

'ignored' would not let the plugin vote in readyness. maybe the user really doesn't care about those zones.

**Comment by miekg** [comment]
This is current work in progress PR that lets middleware report health: https://github.com/coredns/coredns/pull/976/files

It's just a boolean right now: healthy or not, as this is what is eventually exported.

For the *auto* middleware (I think that what your mentioning) here: I was thinking along the lines: If it has at least one, non-expired, zone it is healthy.

**Comment by kfox1111** [comment]
I guess what I'm trying to get at is there are maybe two orthoganal things at play here.

the health check should call each plugin and get a boolean back. if any are not healthy, the health check should fail. Like in the pr.

Each plugin should also include at least one config option that has at minimum support for two different modes. mode 1 would do nothing to the health check value. just pass it on through. mode 2 would cause the normal plugin health check to be skipped and just return a true. Ie, ignore the health check built into the plugin, and just assume its healthy (the user doesnt care about its health)

maybe some plugins support more finer grained values too, like only return healthy if all zones are synced or return true if at least one zone is synced?

**Comment by miekg** [comment]
> Each plugin should also include at least one config option that has at minimum support for two different modes. mode 1 would do nothing to the health check value. just pass it on through. mode 2 would cause the normal plugin health check to be skipped and just return a true. Ie, ignore the health check built into the plugin, and just assume its healthy (the user doesnt care about its health)

Yes, mirrors my thinking as well, at least in regard to some middleware might need `health X` option to tweak this a little. Other like `chaos` don't implement health at all and don't impact the global health of CoreDNS.

Just filed https://github.com/coredns/coredns/issues/988 for discussion on this in the *auto* middleware.
