### ISSUE TITLE
middleware/file: abstract backend away

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#59]
Basically do the same thing as in SkyDNS and abstract away the access to the datasource. This will probably mean renaming the _file_ to ... _data_? or something.

It would be something like this:

```
type Backend interface {
    Insert(rr dns.RR)
    Delete(rr dns.RR)
    Get(rr dns.RR) *Elem
    Len() int
    Next(rr dns.RR) *Elem // for nsec
    Prev(rr dns.RR) *Elem
// nsec3 foo as well? Or just give up on that?
}
```

And Elem is defined as:

```
type Elem struct {
    m map[uint16][]dns.RR
}
```

And also has some methods on it.

**Comment by miekg** [comment]
Needs ClosestEncloser as well

**Comment by miekg** [comment]
Or just simply

```
    answer, ns, extra, result := z.Lookup(qname, state.QType(), state.Do())
```

'cause I don't care what the backend does.

```
type Backend interface {
   Lookup(name string, typ uint16, Opt <sometthing>) ([]dns.RR, []dns.RR, []dns.RR, Result)
```

Result can also say NODATA (which could be inferred, but better to make it explicit). So it just returns
the sections to you. This mean `file` easily implement the backend interface...

Should think about how to specify this in the config.

**Comment by stp-ip** [comment]
still needed?

**Comment by miekg** [comment]
Maybe... But not really that relevant atm (or that someone is actually working on this)
