### ISSUE TITLE
tracing

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#591]
Copy https://github.com/coredns/grpc/blob/master/middleware/grpc/grpc.go#L52-L60 into core/dnsserver/server.go and enable tracing for all server types.

**Comment by johnbelamaric** [comment]
Ok, so here's one issue. The tracing configuration is for the gRPC server itself. But our configuration is per zone. So, if we do:

```
grpc://example.com:5000 {
	log stdout
	errors
	trace zipkin localhost:9411
	proxy . /etc/resolv.conf
}

grpc://.:5000 {
	errors
	trace zipkin myzipkin:9411
	proxy . /etc/resolv.conf
}
```

The user would reasonably expect logging to two different trace servers. But we can't easily do that. Well, we could, but I think they would both get everything for all queries.

I am thinking that we take the configuration from the first "trace" middleware we find for any zone for a given server, and all others are ignored (maybe with a warning in the log).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] tracing (#591..." ]
>Ok, so here's one issue. The tracing configuration is for the gRPC server itself. But our configuration is per zone. So, if we do:
>
>```
>grpc://example.com:5000 {
>	log stdout
>	errors
>	trace zipkin localhost:9411
>	proxy . /etc/resolv.conf
>}
>
>grpc://.:5000 {
>	errors
>	trace zipkin myzipkin:9411
>	proxy . /etc/resolv.conf
>}
>```
>
>The user would reasonably expect logging to two different trace servers. But we can't easily do that. Well, we could, but I think they would both get everything for all queries.
>
>I am thinking that we take the configuration from the first "trace" middleware we find for any zone for a given server, and all others are ignored (maybe with a warning in the log).

same is true for monitoring - although I think we can set up multiple
handlers... But I don't think we should complicate things in such a matter.

Please check what we do in the metrics middleware and copy that (or the other
way around if you have better ideas)

Thanks!

**Comment by johnbelamaric** [comment]
Ok, looks like it errors when more than one is set up:

```
                if len(met.ZoneNames()) > 0 {
                        return met, c.Err("can only have one metrics module per server")
                }
```

So I'll do the same.

**Comment by johnbelamaric** [comment]
Actually that code doesn't seem to work, unless I am misunderstanding something. If that code works, I would expect this to fail:

```
foobar.com:5353 {
	prometheus
	log stdout
	proxy . /etc/resolv.conf
}

foo.bar:5353 {
	prometheus
	log stdout
	erratic
}
```

But it loads just fine.

**Comment by miekg** [comment]
But you don't redefine the handler endpoint there.

**Comment by johnbelamaric** [comment]
Doesn't matter. This loads fine too.

```
foobar.com:5353 {
	prometheus localhost:9999
	log stdout
	proxy . /etc/resolv.conf
}

foo.bar:5353 {
	prometheus localhost:9253
	log stdout
	erratic
}
```

Instrumenting the code a bit, it looks like the `prometheusParse` method is called twice, and each time `c.Next()` only returns one value.

**Comment by miekg** [comment]
Ah. That's​ indeed a bug then. I'll pick this up. Need something small to
get back into coding.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] tracing (#591..." ]
>Ok, looks like it errors when more than one is set up:
>
>```
>                if len(met.ZoneNames()) > 0 {
>                        return met, c.Err("can only have one metrics module per server")
>                }
>```
>
>So I'll do the same.

We allow multiple 'prometheus' directives and use the first addr specified
(either default or explicit).

.nl {
    prometheus localhost:1054
    errors stdout
    log stdout
}

.com {
    prometheus localhost:1055
    errors stdout
    log stdout
}

Doesn't err, but only start listener on 1054. We can start two listeners, but
that is a bit nonsensical. So I think erroring is cleaner.

**Comment by johnbelamaric** [comment]
#619 adds the tracing but only for gRPC. It doesn't deal with the multiple trace directives. I also found that the graceful restart isn't working for gRPC. I'll create a separate issue for that.

**Comment by johnbelamaric** [comment]
#619 for gRPC, I'll add a separate issue for non-gRPC.
