### ISSUE TITLE
How to setup internal communication for localhost development?

### ISSUE THREAD

**Issue by ghost** [coredns/coredns#5942]
I can get internal communication right by using a CoreDNS rewrite rule.
How to do this for https? For example a kubernetes api server only works with https.

I work with subdomains on localhost so I use one of those public domains that point back to localhost and CoreDNS rewrites requests to ...svc.cluster.local but it fails for https.

Is there a solution for kubernetes development on localhost that works with https? Exactly like a public domain?

**Comment by chrisohaver** [comment]
Please provide more description of what you are trying to do.

**Comment by ghost** [comment]
Yes of course. I'd like to try out Kubernetes on my local system. I first tried to use the domain `localhost` but most browsers block subdomains like `test.localhost`. I then tried `test.local.gd` which always resolves to 127.0.0.1. This fails for cluster internal communication, so I use CoreDNS to rewrite `test.local.gd` to `...svc.cluster.local`. This works for port 80 only, so I think the rewrite fails for port 443.

My goal is running Kubernetes on a local domain while using subdomains (and https).
I thought this must be easy, but it seems most people either use a public domain or don't care about the parity of development and production environments and work with IP addresses for development.

**Comment by chrisohaver** [comment]
> My goal is running Kubernetes on a local domain while using subdomains (and https).

I'm sorry, but I still don't understand what you are trying to do.  Maybe give some examples?

**Comment by ghost** [comment]
I made myself clear. I understand that you only help users that have a public github profile. Thank you for taking the time.
