### ISSUE TITLE
spurios "getsockopt: network is unreachable"

### ISSUE THREAD

**Issue by skpy** [coredns/coredns#596]
I get a lot of warning messages like this:
```
Mar 14 22:41:47 plato coredns: 2017/03/14 22:41:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=ichnaea.netflix.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: network is unreachable
Mar 14 22:41:47 plato coredns: 2017/03/14 22:41:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=secure.netflix.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: network is unreachable
Mar 14 22:45:47 plato coredns: 2017/03/14 22:45:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=history.google.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: connection timed out
Mar 14 22:45:47 plato coredns: 2017/03/14 22:45:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=init-p01st.push.apple.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: connection timed out
Mar 14 22:45:47 plato coredns: 2017/03/14 22:45:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=www.icloud.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: connection timed out
Mar 14 22:45:47 plato coredns: 2017/03/14 22:45:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=p26-keyvalueservice.icloud.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: connection timed out
```

```
$ sudo journalctl -u coredns.service | grep WARNING | wc -l
16372
```
Logs begin at Mon 2017-03-13 17:26:39 EDT, end at Tue 2017-03-14 22:51:07.

Here's my Corefile:
```
$ cat /etc/coredns/Corefile
. {
    proxy . 1.2.3.4:53 {
        protocol https_google
    }
}
```

The message claims "WARNING", but it's not clear to me why so many queries would be timing out.   And failing to connect to the only proxy backend seems more critical than just a warning.

How can I troubleshoot this?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] spurios "getsocko..." ]
>I get a lot of warning messages like this:
>```
>Mar 14 22:41:47 plato coredns: 2017/03/14 22:41:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=ichnaea.netflix.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: network is unreachable
>Mar 14 22:41:47 plato coredns: 2017/03/14 22:41:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=secure.netflix.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: network is unreachable
>Mar 14 22:45:47 plato coredns: 2017/03/14 22:45:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=history.google.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: connection timed out
>Mar 14 22:45:47 plato coredns: 2017/03/14 22:45:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=init-p01st.push.apple.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: connection timed out
>Mar 14 22:45:47 plato coredns: 2017/03/14 22:45:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=www.icloud.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: connection timed out
>Mar 14 22:45:47 plato coredns: 2017/03/14 22:45:47 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": Get https://1.2.3.4:53/resolve?name=p26-keyvalueservice.icloud.com.&type=1: dial tcp 1.2.3.4:53: getsockopt: connection timed out
>```
>
>```
>$ sudo journalctl -u coredns.service | grep WARNING | wc -l
>16372
>```
>Logs begin at Mon 2017-03-13 17:26:39 EDT, end at Tue 2017-03-14 22:51:07.
>
>Here's my Corefile:
>```
>$ cat /etc/coredns/Corefile
>. {
>    proxy . 1.2.3.4:53 {
>        protocol https_google
>    }
>}
>```
>
>The message claims "WARNING", but it's not clear to me why so many queries would be timing out.   And failing to connect to the only proxy backend seems more critical than just a warning.
>
>How can I troubleshoot this?

This only happens for me when my internet uplink is actually broken.

% sudo journalctl -u coredns | grep WARNING | wc -l
93
(I wasn't home, hence low amount of failures)

So far in my setup, this has always fixed itself after my connection come back.

What is running on "1.2.3.4"?

As for debugging, "dig" and "curl" are your friends. Can you replicate is
yourself? Do you get the same addresses back? Did you *have* connectivity issues
when this started?


Also see #441, #444 and #540.

**Comment by skpy** [comment]
1.2.3.4 is a bogus address, as specified in the proxy documentation:
> Note that TO is ignored when https_google is used, as its upstream is defined as dns.google.com.

It's possible that I'm having connectivity hiccups, but 16K over the course of two days seems like a lot; and I haven't seen any user-visible interruptions to streaming video or music.

I saw #444 before opening this issue.  It looked similar, but sufficiently different that I felt a new issue was warranted for my problem.

I can dig against Google's servers:
```
[skippy@plato ~]$ dig @8.8.8.8 apple.com

; <<>> DiG 9.10.4-P6-RedHat-9.10.4-3.P6.fc24 <<>> @8.8.8.8 apple.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42186
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;apple.com.			IN	A

;; ANSWER SECTION:
apple.com.		2874	IN	A	17.172.224.47
apple.com.		2874	IN	A	17.178.96.59
apple.com.		2874	IN	A	17.142.160.59

;; Query time: 37 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Mar 15 09:52:53 EDT 2017
;; MSG SIZE  rcvd: 86
```
And I can dig against OpenDNS's servers:
```
[skippy@plato ~]$ dig @208.67.222.222 apple.com

; <<>> DiG 9.10.4-P6-RedHat-9.10.4-3.P6.fc24 <<>> @208.67.222.222 apple.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27350
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;apple.com.			IN	A

;; ANSWER SECTION:
apple.com.		327	IN	A	17.142.160.59
apple.com.		327	IN	A	17.172.224.47
apple.com.		327	IN	A	17.178.96.59

;; Query time: 18 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Wed Mar 15 09:57:29 EDT 2017
;; MSG SIZE  rcvd: 86
```
And I can dig against my local setup:
```
[skippy@plato ~]$ cat /etc/resolv.conf
nameserver 127.0.0.1
nameserver 192.168.13.1
[skippy@plato ~]$ dig apple.com

; <<>> DiG 9.10.4-P6-RedHat-9.10.4-3.P6.fc24 <<>> apple.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53298
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 8, ADDITIONAL: 8

;; QUESTION SECTION:
;apple.com.			IN	A

;; ANSWER SECTION:
apple.com.		3376	IN	A	17.172.224.47
apple.com.		3376	IN	A	17.178.96.59
apple.com.		3376	IN	A	17.142.160.59

;; AUTHORITY SECTION:
apple.com.		19166	IN	NS	nserver3.apple.com.
apple.com.		19166	IN	NS	nserver2.apple.com.
apple.com.		19166	IN	NS	adns1.apple.com.
apple.com.		19166	IN	NS	nserver6.apple.com.
apple.com.		19166	IN	NS	nserver.apple.com.
apple.com.		19166	IN	NS	nserver4.apple.com.
apple.com.		19166	IN	NS	nserver5.apple.com.
apple.com.		19166	IN	NS	adns2.apple.com.

;; ADDITIONAL SECTION:
nserver6.apple.com.	15904	IN	A	17.171.63.40
nserver5.apple.com.	15499	IN	A	17.171.63.30
adns1.apple.com.	16495	IN	A	17.151.0.151
adns2.apple.com.	16876	IN	A	17.151.0.152
nserver4.apple.com.	16465	IN	A	17.112.144.59
nserver.apple.com.	16465	IN	A	17.254.0.50
nserver3.apple.com.	17860	IN	A	17.112.144.50
nserver2.apple.com.	15291	IN	A	17.254.0.59

;; Query time: 19 msec
;; SERVER: 192.168.13.1#53(192.168.13.1)
;; WHEN: Wed Mar 15 09:52:58 EDT 2017
;; MSG SIZE  rcvd: 380
```
Note that the response came from 192.168.13.1, which is my router address, while `resolv.conf` indicates that 127.0.0.1 should be used first.  When explicitly querying 127.0.0.1 to talk to CoreDNS:
```
[skippy@plato ~]$ dig @127.0.0.1 apple.com

; <<>> DiG 9.10.4-P6-RedHat-9.10.4-3.P6.fc24 <<>> @127.0.0.1 apple.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 41560
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;apple.com.			IN	A

;; Query time: 3110 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Mar 15 09:55:05 EDT 2017
;; MSG SIZE  rcvd: 38
```

I've confirmed that CoreDNS is running:
```
[skippy@plato ~]$ sudo systemctl status coredns
● coredns.service - CoreDNS DNS server
   Loaded: loaded (/etc/systemd/system/coredns.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-03-14 19:37:16 EDT; 14h ago
     Docs: https://coredns.io
 Main PID: 787 (coredns)
    Tasks: 9 (limit: 512)
   Memory: 1.1M
      CPU: 19.630s
   CGroup: /system.slice/coredns.service
           └─787 /usr/local/bin/coredns -conf=/etc/coredns/Corefile
[skippy@plato ~]$ pgrep -a coredns
787 /usr/local/bin/coredns -conf=/etc/coredns/Corefile
```

So my network appears to be working correctly, and I can query upstream resolvers; but CoreDNS appears to be having trouble talking to Google.

**Comment by skpy** [comment]
I restarted the coredns service, and queries seemed to start working again.
```
[skippy@plato ~]$ sudo systemctl restart coredns
[skippy@plato ~]$ dig @127.0.0.1 apple.com

; <<>> DiG 9.10.4-P6-RedHat-9.10.4-3.P6.fc24 <<>> @127.0.0.1 apple.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2118
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;apple.com.			IN	A

;; ANSWER SECTION:
apple.com.		2191	IN	A	17.172.224.47
apple.com.		2191	IN	A	17.178.96.59
apple.com.		2191	IN	A	17.142.160.59

;; Query time: 149 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Mar 15 10:04:17 EDT 2017
;; MSG SIZE  rcvd: 102
```

I also realized I'd been using CoreDNS v005; so I downloaded CoreDNS v006.
```
[skippy@plato coredns]$ tar zxf coredns_006_linux_x86_64.tgz
[skippy@plato coredns]$ ls -lha
total 49M
drwxrwxr-x.  2 skippy skippy  109 Mar 15 10:05 .
drwx------. 23 skippy skippy 4.0K Mar 15 09:43 ..
-rwxrwxr-x.  1 skippy skippy  32M Feb 22 16:24 coredns
-rw-rw-r--.  1 skippy skippy 8.2M Feb  9 13:49 coredns_005_linux_x86_64.tgz
-rw-rw-r--.  1 skippy skippy 8.9M Feb 22 16:24 coredns_006_linux_x86_64.tgz
-rw-rw-r--.  1 skippy skippy   67 Feb 21 10:35 Corefile
[skippy@plato coredns]$ sudo systemctl stop coredns.service
[skippy@plato coredns]$ which coredns
/usr/local/bin/coredns
[skippy@plato coredns]$ sudo cp coredns /usr/local/bin/
[skippy@plato coredns]$ sudo systemctl start coredns
[skippy@plato coredns]$ dig @127.0.0.1 apple.com

; <<>> DiG 9.10.4-P6-RedHat-9.10.4-3.P6.fc24 <<>> @127.0.0.1 apple.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16751
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;apple.com.			IN	A

;; ANSWER SECTION:
apple.com.		2086	IN	A	17.142.160.59
apple.com.		2086	IN	A	17.172.224.47
apple.com.		2086	IN	A	17.178.96.59

;; Query time: 204 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Mar 15 10:06:05 EDT 2017
;; MSG SIZE  rcvd: 102
```
Things seem to be working now; but things seemed to be working when I first started using CoreDNS, too.  I'll keep an eye on this and report back with any new details or observations.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] spurios "gets..." ]
>Things seem to be working now; but things seemed to be working when I first started using CoreDNS, too.  I'll keep an eye on this and report back with any new details or observations.

What is lingering in my mind is the following scenario (but haven't tested it):

There is a hiccup, backend is marked unhealthy and with a continues stream of
queries it never gets out of this state, until you restart coredns.

I've seen this with 005, but not with 006 on my home network. I see the hiccup,
but I also see coredns recovering from this. This is with a very low qps and, as
said, I never tested it with high qps.

If you have the time that would be a good test: Disable caching, have a couple
of `dig`s run on your laptop and disconnect coredns network conn. and check what
happens when you re-connect.

/Miek

--
Miek Gieben

**Comment by skpy** [comment]
The getsockopt errors seem to have subsided, to be replaced with
```
Mar 25 18:34:37 plato.skippy.lan coredns[30068]: 2017/03/25 18:34:37 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": failed to get 200 status code, got 502
Mar 25 18:34:37 plato.skippy.lan coredns[30068]: 2017/03/25 18:34:37 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": failed to get 200 status code, got 502
Mar 25 18:34:37 plato.skippy.lan coredns[30068]: 2017/03/25 18:34:37 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": failed to get 200 status code, got 502
Mar 25 18:36:35 plato.skippy.lan coredns[30068]: 2017/03/25 18:36:35 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": failed to get 200 status code, got 502
Mar 25 18:45:08 plato.skippy.lan coredns[30068]: 2017/03/25 18:45:08 [WARNING] Failed to connect to HTTPS backend "dns.google.com.": failed to get 200 status code, got 502
```
This looks transient, so I won't worry about it much for now.  The original problem seems to have been resolved by upgrading to 006.

Thanks!
