### ISSUE TITLE
middleware/secondary: Does not report NOTAUTH when transferring

### ISSUE THREAD

**Issue by SuperQ** [coredns/coredns#598]
When using `secondary` to transfer a zone, the server reports an error:

```
[ERROR] Failed to parse transfer `example.com.': dns: no SOA
[ERROR] Failed to transfer example.com.: dns: no SOA
```

The "real" error here is that the `transfer from` server is returning a RCODE of `NOTAUTH`.

**Comment by SuperQ** [comment]
Same thing happens for `REFUSED`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] middleware/second..." ]
>When using `secondary` to transfer a zone, the server reports an error:
>
>```
>[ERROR] Failed to parse transfer `example.com.': dns: no SOA
>[ERROR] Failed to transfer example.com.: dns: no SOA
>```
>
>The "real" error here is that the `transfer from` server is returning a RCODE of `NOTAUTH`.

Might actually be a bug in go/dns (github.com/miekg/dns) than coredns.
But code/tests welcome to fix this.

**Comment by SuperQ** [comment]
Yea, I was looking over the secondary middleware, and I think it may be a problem with the upstream dns code.  I wanted to file the issue here first to confirm and track that this was a problem before I dug into it more.

**Comment by miekg** [comment]
Also see https://github.com/miekg/dns/issues/467
