### ISSUE TITLE
Mysterious CircleCI failures 

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#5987]
CircleCI has been failing to launch our circle/ci jobs in contributor-opened PRs with the following error...

> Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

The suggested fix is to [revoke and reenable OAuth for CircleCI](https://support.circleci.com/hc/en-us/articles/12504745606171-Why-am-I-seeing-the-Could-not-find-a-usable-config-yml-you-may-have-revoked-the-CircleCI-OAuth-app-message).

IIUC, this is referring to the CoreDNS account.  **I think only a CoreDNS admin/owner can do this.**

Can someone with admin/owner owner role please try this to see if it fixes the issues?

**Comment by johnbelamaric** [comment]
You are now an Org Owner, Chris :)

**Comment by chrisohaver** [comment]
With my new org owner powers, I have toggled the CircleCI access switch ... will see if that fixed anything (I am doubtful).

**Comment by chrisohaver** [comment]
Still broken.

**Comment by chrisohaver** [comment]
CircleCI still fails for non-member PRs.

However, now I'm seeing CircleCI fail in a new way, after a merge, the kubernetes-test fails to checkout out the (public) master coredns branch due permission denied (ssh checkout).

**Comment by chrisohaver** [comment]
I am now seeing PRs come through without the CircleCI failure.  Maybe CircleCI fixed something on their end - or perhaps a bad token expired and was reissued (or otherwise fixed itself).

**Comment by chrisohaver** [comment]
> However, now I'm seeing CircleCI fail in a new way, after a merge, the kubernetes-test fails to checkout out the (public) master coredns branch due permission denied (ssh checkout). 

This started failing again more consistently. I have added a read only ssh key to the GitHub coredns project, and added the pub key to circle ci coredns project.  Seems to be working now.  Not sure it was ever working before without a key.
