### ISSUE TITLE
-log <file> still outputs to stdout for some logs

### ISSUE THREAD

**Issue by SuperQ** [coredns/coredns#602]
I'm testing an authoritative-only server setup.  When running with no default zone, I correctly get `REFUSED` messages for unknown zones.  But even with `-log /path/to/query.log`, I get INFO log lines to stdout.

```
coredns[20698]: 2017/03/16 17:31:49 [INFO] "A IN www.google.com." - No such zone at :53 (Remote: 5.170.133.149:41714)
```

If I configure a default zone, the queries correctly go to the log, but the queries respond with `SRVFAIL` and not `REFUSED`.  I also get this error on stdout:

```
coredns[17862]: 16/Mar/2017:17:01:46 +0000 [ERROR 0 www.google.com. A] middleware/log: no next middleware found
```

Is there a possible configuration I'm missing?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Recursion disable..." ]
>I'm testing an authoritative-only server setup.  When running with no default zone, I correctly get `REFUSED` messages for unknown zones.  But even with `-log /path/to/query.log`, I get INFO log lines to stdout.
>
>```
>coredns[20698]: 2017/03/16 17:31:49 [INFO] "A IN www.google.com." - No such zone at :53 (Remote: 5.170.133.149:41714)
>```
>
>If I configure a default zone, the queries correctly go to the log, but the queries respond with `SRVFAIL` and not `REFUSED`.  I also get this error on stdout:
>
>```
>coredns[17862]: 16/Mar/2017:17:01:46 +0000 [ERROR 0 www.google.com. A] middleware/log: no next middleware found
>```
>
>Is there a possible configuration I'm missing?

What's the bug? Stuff still going to stdout?


/Miek

--
Miek Gieben

**Comment by SuperQ** [comment]
Yes, there is still stuff going to stdout, and there doesn't seem to be a reasonable configuration for handling this use case.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Recursion disable..." ]
>I'm testing an authoritative-only server setup.  When running with no default zone, I correctly get `REFUSED` messages for unknown zones.  But even with `-log /path/to/query.log`, I get INFO log lines to stdout.
>
>```
>coredns[20698]: 2017/03/16 17:31:49 [INFO] "A IN www.google.com." - No such zone at :53 (Remote: 5.170.133.149:41714)
>```
>
>If I configure a default zone, the queries correctly go to the log, but the queries respond with `SRVFAIL` and not `REFUSED`.  I also get this error on stdout:
>
>```
>coredns[17862]: 16/Mar/2017:17:01:46 +0000 [ERROR 0 www.google.com. A] middleware/log: no next middleware found
>```
>
>Is there a possible configuration I'm missing?

No prolly a bug.

I'm not even sure if logging to a file makes sense. In a docker container it is
basically useless and currently I run my personal coredns's via systemd which
picks up stdout (-log stdout) and does stuff.

**Comment by SuperQ** [comment]
My goal is to keep query logs separated from other logs (for example, secondary transfers).  The default setup in a Debian systemd is to send it all to syslog.  This would be a bit much for query logs on a busy server.

I guess it would be easy enough to change the syslog config to push the coredns logs elsewhere.

**Comment by mfischer-zd** [comment]
I'd actually like to go the opposite direction, and log everything to stdout.  Implementors who would like different behavior can either redirect stdout, or connect its output to the log ingestor of their choice (e.g. `logger` on Debian).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] -log <file> s..." ]
>I'd actually like to go the opposite direction, and log everything to stdout.  Implementors who would like different behavior can either redirect stdout, or connect its output to the log ingestor of their choice (e.g. `logger` on Debian).

+1

This also makes a lot of sense when running coredns in a container.

**Comment by SuperQ** [comment]
Yup, logging everything to stdout is also a good way to go.  This is already possible with the `log stdout` in the config.

**Comment by mfischer-zd** [comment]
Should we drop `log syslog` and `log stderr` support @miekg ?  It's early enough that we could probably get away with it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] -log <file> s..." ]
>Should we drop `log syslog` and `log stderr` support @miekg ?  It's early enough that we could probably get away with it.

Does 'syslog' actually do something? :/ But I agree with the above.

I do think it make sense to keep 'stderr' as an option. Looking through the
errors README that indeed mention syslog - probably doesn't work and needs
cleaning as well (same might hold for log middleware).

**Comment by mfischer-zd** [comment]
What would be the rationale for keeping the `stderr` option?  I've not seen a log collection system that made a meaningful distinction between stderr and stdout (other than not collecting stderr, maybe, but that seems like a bad idea to me on the face of it).  Putting severities in the log seems more useful to me.

**Comment by SuperQ** [comment]
👍 I would probably remove stderr support.  I also recommend using logging levels in the log stream rather than differentiating by output stream.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] -log <file> s..." ]
>👍 I would probably remove stderr support.  I also recommend using logging levels in the log stream rather than differentiating by output stream.

What are logging levels? Currently we only have the literal string `[WARNING]`,
`[FATAL]` and `[INFO]`....

**Comment by mfischer-zd** [comment]
Unless we start logging in some sort of structured format, that's all we have.  At the very least, many log processing systems can parse severities out of a line-based stream using a regex.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] -log <file> s..." ]
>Unless we start logging in some sort of structured format, that's all we have.  At the very least, many log processing systems can parse severities out of a line-based stream using a regex.

Ok. sgtm.

So Caddy just uses the `log.Printf` system, which I don't mind too much (nice
and simple). 

There is also: https://github.com/coredns/coredns/issues/573 which
may indicate we need something smarter. OTOH, I rather have journald doing this
than implementing it in CoreDNS...

**Comment by mfischer-zd** [comment]
> OTOH, I rather have journald doing this than implementing it in CoreDNS...

Me too, but AFAIK most container runtimes (Docker, anyway) in which CoreDNS will be used only consume stdout and don't connect the managed programs to the journald socket.

**Comment by miekg** [comment]
What's the plan here now? I can live with removing the errors middleware and just having log and pun everything to stdout. Removing *errors* will also speed up things.

1 nit: we now recover from crashes with the *errors* middleware, that should probably be moved to another middleware like *recover*.

This fixex #573 as well (well, we move the problem out of coredns).

**Comment by miekg** [comment]
#684
