### ISSUE TITLE
cache README: `stale_cache` and `Each element in the cache is cached according to its TTL`

### ISSUE THREAD

**Issue by cattyhouse** [coredns/coredns#6077]
Let's say we have this cache setup: 
```
cache {
    serve_stale
}
```

And domain A has TTL of 30s

1. According to the doc `Each element in the cache is cached according to its TTL`, after 30s, **the cache of domain A will be removed (based on the understanding of this statement).** 

2. when query domain A again `after 30s`, according to `stale_cache` doc: `when serve_stale is set, cache will always serve an expired entry to a client ...`, but that `expired entry` was actually deleted due to TTL expire as per the doc above

my guess : unless when stale_cache is set, Each element in the cache is `not deleted according to it's TTL`?

**Comment by chrisohaver** [comment]
https://coredns.io/plugins/cache/#capacity-and-eviction

Records remain in the cache after they expire.  Expired records are not used for answers unless stale_cache is enabled.
Actual cache eviction (removal of records from cache) only happens when max capacity is exceeded.

**Comment by cattyhouse** [comment]
thanks for the clarification, Chris.
