### ISSUE TITLE
Which is the proper way of reloading CoreDNS

### ISSUE THREAD

**Issue by itomsawyer** [coredns/coredns#608]
After read the docs, I find that CoreDNS can be reloaded by notify SIGUSR1 to CoreDNS(which is a feature of Caddy). The reloading signal will cause all middleware to be recreated from Corefile. That is to say, if I execute reload process, the cache will be cleaned. I also found that file middleware has its on reload function. Is that to say if a single middleware want to reload without affecting the other middleware, it's the middleware's own responsibility to implement it?  Is there any common way?

**Comment by miekg** [comment]
No there isn't a common way for per middleware reload. The file middleware
needed this so only 1 zone will be reloaded on a change, instead of
reloading all zones all the time.
Think we should wait for a second impl. before thinking about creating some
infastructure.
