### ISSUE TITLE
Plugin kubernetes panics if noendpoints is set and it received a request for a headless service

### ISSUE THREAD

**Issue by liuycsd** [coredns/coredns#6087]
**What happened**:
Plugin `kubernetes` panics in `kubernetes.(*dnsControl).EpIndex` if `noendpoints` is set and it receives a request for a headless service.

**What you expected to happen**:
It should return `NXDOMAIN` as [documented](https://coredns.io/plugins/kubernetes/).

**How to reproduce it (as minimally and precisely as possible)**:

Start CoreDNS with `kubernetes` plugin enabled and `noendpoints` set.

Create a headless service in kubernetes, e.g. foo in default namespace.

`dig @10.96.0.10 foo.default.svc.cluster.local.`

CoreDNS returns `SERVFAIL` and logs a panic message.

**Anything else we need to know?**:

It seems PR [#2128](https://github.com/coredns/coredns/pull/2128) removes a lot of is-nil checks. Any special considerations?

**Environment**:

- the version of CoreDNS: v1.10.1
- Corefile:
```
...
  errors
  kubernetes ... {
    noendpoints
    ttl 30
    fallthrough
  }
...
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others: k8s v1.26.4

**Comment by chrisohaver** [comment]
Thanks for catching it.

> It seems PR https://github.com/coredns/coredns/pull/2128 removes a lot of is-nil checks. Any special considerations?

No, that check should not have been removed. It's just hard to catch those kinds of things when reviewing titanic refactor PRs.  Ideally if a unit test covered the case, it would have been caught.
