### ISSUE TITLE
forward : `MSG SIZE  rcvd:` much bigger than direct query

### ISSUE THREAD

**Issue by cattyhouse** [coredns/coredns#6089]
**What happened**:
#### Plain dns
- dig +tcp @1.1.1.1
```
dig aerserv-bc-us-east.bidswitch.net +tcp @1.1.1.1 | grep 'MSG SIZE'
;; MSG SIZE  rcvd: 2573
```
- coredns forward
```
.:1111 {
    bind 127.0.0.1
    forward . 1.1.1.1
}
```
```
dig aerserv-bc-us-east.bidswitch.net -p 1111 | grep 'MSG SIZE'
;; MSG SIZE  rcvd: 7597
```

#### DoT
- dig +tls @1.1.1.1
> 1.1.1.1 do response padding on DoT, it is **468 * integer** (the integer is 6 in this case)
```
dig aerserv-bc-us-east.bidswitch.net +tls @1.1.1.1 | grep 'MSG SIZE'
;; MSG SIZE  rcvd: 2808
```
- coredns forward
```
.:1111 {
    bind 127.0.0.1
    forward . tls://1.1.1.1 {
        tls_servername cloudflare-dns.com
    }
}
```
```
dig aerserv-bc-us-east.bidswitch.net -p 1111 | grep 'MSG SIZE'
;; MSG SIZE  rcvd: 7832
```
#### the MSG SIZE forward vs direct query is

```
7832 Bytes vs 2808 Bytes # DoT
7597 Bytes vs 2573 Bytes # plain dns
```
**What you expected to happen**:

`MSG SIZE  rcvd:` should be identical to direct query

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: `v1.10.1`
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):`Debian 12`
- Others:

**Comment by cattyhouse** [comment]
similar to #2242 ?

**Comment by chrisohaver** [comment]
CoreDNS only compresses responses when responding over UDP.
