### ISSUE TITLE
Add support for go vendor

### ISSUE THREAD

**Issue by andyxning** [coredns/coredns#610]
Add support for go vendor to make it build with a reproducible binary. :) 

How about we use godep to maintain coredns dependencies?

**Comment by miekg** [comment]
I don't like godep and I think we should wait until `dep` becomes the official way of handling dependencies in Go code.

**Comment by andyxning** [comment]
@miekg I have no special tastes on go dependency tools. :) I just propose that we need to make the dependencies recored ASAP. 

I have read the [roadmap](https://github.com/golang/dep/wiki/Roadmap) and [readme](https://github.com/golang/dep). It seems that there will be at least one year for it to be production ready. I am afraid this takes too long. And the project also said that `dep` is not an golang official project and there is no guarantee it will be merged into go tool chain.

As for `godep`, Kubernetes project is using it. Maybe it is not perfect. But it can work now. :)

**Comment by johnbelamaric** [comment]
We use https://glide.sh in our internal stuff. It's pretty straightforward. You create a YAML with the dependencies and it pulls in all the right vendor code. I've asked @mstaneuka to see what that would look like for CoreDNS.

**Comment by miekg** [comment]
Major reason why i don't like vendoring is that we then have to deal with a
upgrade-all-vendored code every once ina while. I rather deal with smaller
breakages along the way...

**Comment by johnbelamaric** [comment]
Yeah, I get that. We already have that issue with the one thing we vendor (k8s client), which we'll probably need to bump up sooner or later.

Without it though it makes a repeatable build harder. And if someone deletes an upstream repository we'll be hurting.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Add support f..." ]
>Yeah, I get that. We already have that issue with the one thing we vendor (k8s client), which we'll probably need to bump up sooner or later.
>
>Without it though it makes a repeatable build harder. And if someone deletes an upstream repository we'll be hurting.

that's true...

**Comment by andyxning** [comment]
> Major reason why i don't like vendoring is that we then have to deal with a
upgrade-all-vendored code every once ina while. I rather deal with smaller
breakages along the way...

@miekg I am afraid that it is a common and main job for vendor dependency management to upgrade vendored dependencies. It is unavoidable. :)
