### ISSUE TITLE
How to use multiple upstream proxies with different protocols?

### ISSUE THREAD

**Issue by skpy** [coredns/coredns#612]
I understand why #234 is not going to be implemented, but I'd like to be able to secure my DNS requests with more than just Google's non-standard DNS-over-HTTPS service.

The `proxy` middleware only supports a single protocol, so I can't easily load balance between a dnscrypt-proxy instance upstream and Google.

I tried running two proxies: one on a high port configured to send all requests to Google, and another on standard :53 that proxies to the high port proxy.  The thinking was that I could later add a dnscrypt-proxy instance on a different high port, and add that to the :53 proxy in my Corefile, thereby sending requests through multiple upstream secured providers.

```
.:5353 {
  proxy . 1.2.3.4:53 {
    protocol https_google
    health_check /health:8080
  }
}
proxy . 127.0.0.1:5353
health 127.0.0.1:8080
```

This didn't work, though:
```
[skippy@plato ~]$ sudo /usr/local/bin/coredns -conf /etc/coredns/Corefile
2017/04/11 07:49:04 cannot serve .:53 - zone already defined for .:5353
```

Is what I'm trying to do even feasible?  Would I need to run two distinct instances of coredns, rather than trying to have it all set up in a single instance?

**Comment by miekg** [comment]
Yes, I think you'll need 2 instances. There can only be 1 stanza for one zone. So you already have `.` defined, this means there can't be another.
Maybe you *could* hack around it by proxying all TLDs separately, but seems silly as running 2 coredns instances should be easy.
