### ISSUE TITLE
Cannot forward/proxy request outside of zone.

### ISSUE THREAD

**Issue by bdubn** [coredns/coredns#618]
Any ideas? Thank you!
----------------------------------------------------------------------------
Corefile:

corp.com {
  file /Users/xxxx/dns/corp.com
  bind xxx.xxx.xxx.xxx
  errors stdout
  log stdout
  proxy . 8.8.8.8:53
  cache
}

--------------------------------------------------------------------------
Zone file:

$TTL    1800
$ORIGIN corp.com.
@  1D   IN      SOA     ns01.corp.com. admin.corp.com. (
                 1282630061  ; Serial
                  4H         ; Refresh
                  1H         ; Retry
                  7D         ; Expire
                  4H         ; Negative Cache TTL
                 )

             IN      NS	    ns01.corp.com.

ns01     IN      A	    xxx.xxx.xxx.xxx

nsdev   IN      A           xxx.xxx.xxx.xxx
             IN      AAAA    xxxx:xxxx:xxxx:xxxx::xxxx

------------------------------------------------------------------------

Dig:

; <<>> DiG 9.8.3-P1 <<>> @xxx.xxx.xxx.xxx www.google.com A +short
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
dig @xxx.xxx.xxx.xxx www.citrix.com A +short
dig @xxx.xxx.xxx.xxx www.citrix.com

; <<>> DiG 9.8.3-P1 <<>> @xxx.xxx.xxx.xxx www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 49484
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.google.com.			IN	A

;; Query time: 42 msec
;; SERVER: xxx.xxx.xxx.xxx#53(xxx.xxx.xxx.xxx)
;; WHEN: Sun Apr 16 08:26:31 2017
;; MSG SIZE  rcvd: 32

----------------------------------------------------------------------------

STDOut:

017/04/16 08:26:30 [INFO] "A IN www.google.com." - No such zone at dns://xxx.xxx.xxx.xxx:53 (Remote: xxx.xxx.xxx.xxx:57582)

**Comment by miekg** [comment]
See: https://forum.caddyserver.com/t/cannot-forward-proxy-request-outside-of-zone/1799/3
