### ISSUE TITLE
middleware file: wildcards

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#62]
implement wildcard responses for both DNS and DNSSEC.

**Comment by miekg** [comment]
positive replies work. Now only nodata responses.

**Comment by luk4hn** [comment]
Hi @miekg,
I have a wildcard entry in my zone file, like below: 

> *.example.org.                           300     IN A       1.2.3.4

With this config only query for subdomains start with letter from a to s (example: a.example.org, b.example.org, c.example.org, ...) can get correct response (ip: 1.2.3.4).
Query for subdomains start with letter from t, u, v ... y, z (ex: t.example.org, ta.example.org, taa.example.org, ....) resulted in no answer received.

Do you have any idea on how to make wildcard entry work correctly ? Thanks

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware file..." ]

> Hi @miekg,
> I have a wildcard entry in my zone file, like below:
> 
> > *.example.org.                           300     IN A       1.2.3.4
> 
> With this config only query for subdomains start with letter from a to s (example: a.example.org, b.example.org, c.example.org, ...) can get correct response (ip: 1.2.3.4).
> Query for subdomains start with letter from t, u, v ... y, z (ex: t.example.org, ta.example.org, taa.example.org, ....) resulted in no answer received.
> 
> Do you have any idea on how to make wildcard entry work correctly ? Thanks

WAT?

Are you running CoreDNS from the git version? Can you post your zone + config
(or email me), I'll take a look.

/Miek

## 

Miek Gieben

**Comment by luk4hn** [comment]
I'm using release v002 (coredns_002_linux_x86_64.tgz). 
My config is like below
- Corefile 

```
.:53 {
  rewrite ANY HINFO

  file records/example.org example.org

  proxy . 8.8.4.4:53 8.8.8.8:53 {
    policy least_conn
    fail_timeout 30s
    max_fails 1
    except example.org
    spray
  }

  cache 60 example.org
  errors stderr
  log stdout
}
```
- zone file:

```
$ORIGIN .
@       3600    IN      SOA     example.org.    root.example.org.       (
                2016102001      ; serial
                7200            ; refresh
                3600            ; retry
                86400           ; expire
                3600)           ; minimum

; NS
example.org.                             300     IN      NS    ns1.example.org.
example.org.                             300     IN      NS    ns2.example.org.

; CNAME

; A
*.example.org.                           300     IN A       172.46.0.15

ns1.example.org.                         300     IN A       172.46.0.251
ns2.example.org.                         300     IN A       172.46.0.252
logging.example.org.                     300     IN A       172.46.0.25

microhub-ns-1.svr.example.org.           60      IN A       172.46.0.251
microhub-ns-2.svr.example.org.           60      IN A       172.46.0.252
microhub-kinglanding-1.svr.example.org.  60      IN A       172.46.0.183
microhub-jenkins-1.svr.example.org.      60      IN A       172.46.0.111
microhub-sauroneye-1.svr.example.org.    60      IN A       172.46.0.75
microhub-log-1.svr.example.org.          60      IN A       172.46.0.146
microhub-log-2.svr.example.org.          60      IN A       172.46.0.147
microhub-log-3.svr.example.org.          60      IN A       172.46.0.148
microhub-loadtest-1.svr.example.org.     60      IN A       172.46.0.76
microhub-cattle-1.svr.example.org.       60      IN A       172.46.0.37
```

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware file..." ]

> I'm using release v002 (coredns_002_linux_x86_64.tgz).

Ah, cool. I _completely_ reworked the looks algo for 003, so you might want to
compile that and see if that works for you. I'll double check with your config
if I actually fixed all the bugs there.

> My config is like below
> - Corefile
>   `.:53 {
>   rewrite ANY HINFO
>   
>   file records/example.org example.org
>   
>   proxy . 8.8.4.4:53 8.8.8.8:53 {
>    policy least_conn
>   fail_timeout 30s
>   max_fails 1
>   except example.org
>   spray
>   }
>   
>   cache 60 example.org
>   errors stderr
>   log stdout
>   }
>   `
> - zone file:
>   `$ORIGIN .
>   @       3600    IN      SOA     example.org.    root.example.org.       (
>              2016102001      ; serial
>              7200            ; refresh
>              3600            ; retry
>              86400           ; expire
>              3600)           ; minimum
> 
> ; NS
> example.org.                             300     IN      NS    ns1.example.org.
> example.org.                             300     IN      NS    ns2.example.org.
> 
> ; CNAME
> 
> ; A
> *.example.org.                           300     IN A       172.46.0.15
> 
> ns1.example.org.                         300     IN A       172.46.0.251
> ns2.example.org.                         300     IN A       172.46.0.252
> logging.example.org.                     300     IN A       172.46.0.25
> 
> microhub-ns-1.svr.example.org.           60      IN A       172.46.0.251
> microhub-ns-2.svr.example.org.           60      IN A       172.46.0.252
> microhub-kinglanding-1.svr.example.org.  60      IN A       172.46.0.183
> microhub-jenkins-1.svr.example.org.      60      IN A       172.46.0.111
> microhub-sauroneye-1.svr.example.org.    60      IN A       172.46.0.75
> microhub-log-1.svr.example.org.          60      IN A       172.46.0.146
> microhub-log-2.svr.example.org.          60      IN A       172.46.0.147
> microhub-log-3.svr.example.org.          60      IN A       172.46.0.148
> microhub-loadtest-1.svr.example.org.     60      IN A       172.46.0.76
> microhub-cattle-1.svr.example.org.       60      IN A       172.46.0.37
> `
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/miekg/coredns/issues/62#issuecomment-258832422
> /Miek

## 

Miek Gieben

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [miekg/coredns] middleware file..." ]

> I'm using release v002 (coredns_002_linux_x86_64.tgz).

Just checked your config; this works correcly with 003 (not yet released)

**Comment by luk4hn** [comment]
Thank you miekg for your quick response. I have been able to compile new binary from master branch and it seem to be working fine now, keep up the great work :+1:
