### ISSUE TITLE
Graceful restart for gRPC

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#620]
Currently sending a SIGUSR1 when using a grpc server will result in a "port in use" error.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Graceful restart ..." ]
>Currently sending a SIGUSR1 when using a grpc server will result in a "port in use" error.

Deja vu? Didn't we have this before?
(Anyway we didn't add a test for it, go figure)

/Miek

--
Miek Gieben

**Comment by johnbelamaric** [comment]
Yeah. In fact I bet it happens for the UDP and TCP servers too, but I haven't tried it.

The last time, the GracefulServer interface changed and we were missing one method. Now, it looks like there is a test for the Listener interface to have a File method, that's where I traced the issue to: https://github.com/mholt/caddy/blob/master/caddy.go#L165

`lnOk` is false for us.

**Comment by johnbelamaric** [comment]
Ok, works for regular servers, just not gRPC.

**Comment by miekg** [comment]
Trying it, but seems to work:
~~~
% ./coredns -conf ~/Corefile-grpc -log stdout
2017/04/18 08:32:11 [INFO] Blocking Command:"/bin/echo up"
up
grpc://.:4443
2017/04/18 08:32:11 [INFO] CoreDNS-006
CoreDNS-006
2017/04/18 08:32:39 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2017/04/18 08:33:23 [INFO] SIGUSR1: Reloading
2017/04/18 08:33:23 [INFO] Reloading
2017/04/18 08:33:23 [INFO] Reloading complete
2017/04/18 08:34:02 transport: http2Server.HandleStreams failed to receive the preface from client: unexpected EOF
~~~
The transport failures is me telnetting to port 4443

**Comment by johnbelamaric** [comment]
Hmm. Ok, maybe it's something I am doing in #619 that is different.

**Comment by miekg** [comment]
Checked out that PR and using it. Work for me. 

`go get -u` for up to date deps?

**Comment by johnbelamaric** [comment]
Yes, that did it! Freshly built and no issue now.
