### ISSUE TITLE
Undefined behavior with multiple trace statements for the same server

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#621]
If you specify the trace middleware for different zones that are served by the same server, the behavior is undefined. Instead it should probably be considered a config error. See #591 .

**Comment by miekg** [comment]
Can we add zone to the trace as we parse the config?

**Comment by johnbelamaric** [comment]
We can append that data in the tracing, but we can't use that to set different endpoints. The issue is that, at least for gRPC, that the same gRPC server is used for all of those zones, and there is only one place to add the tracing. Maybe we could add multiple tracers with different filters. Seems like overkill for an unlikely use case, though.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Undefined beh..." ]
>We can append that data in the tracing, but we can't use that to set different endpoints. The issue is that, at least for gRPC, that the same gRPC server is used for all of those zones, and there is only one place to add the tracing. Maybe we could add multiple tracers with different filters. Seems like overkill for an unlikely use case, though.

Ok, lets just error out then.

**Comment by miekg** [comment]
Should we close this?
