### ISSUE TITLE
gRPC protocol

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#625]
We getting there with supporting gRPC. Currently we wrap DNS data inside gRPC as a blob of bytes.

But we *can* control the client's lookups as well: nsswitch.conf and nss. We could write our own nss module (needs dynamically loadable, so no Go?), that implements a simpler(?) DNS in pure gRPC and implement the server side in CoreDNS.

Initially we could remove some of the silly limitations of DNS (255 max, 63 chars labels). Wondering about TTLs/watches and stuff like that. DNSSEC, nameserver records?

I also don't know a whole lot of nss (yet).

We should use this issue to flesh out some details

**Comment by miekg** [comment]
Also what features from `/etc/resolv.conf` should be supported?

**Comment by miekg** [comment]
Also see: https://github.com/dex4er/nss-docker

**Comment by miekg** [comment]
Note that with nss we still limited, but at least it can serve as an escape goat for doing 100% grpc

**Comment by johnbelamaric** [comment]
Good stuff Miek.

@cricketliu thought you might find this interesting

**Comment by miekg** [comment]
> But we can control the client's lookups as well: nsswitch.conf and nss. We could write our own nss module (needs dynamically loadable, so no Go?), that implements a simpler(?) DNS in pure gRPC and implement the server side in CoreDNS.

musl libc does not implement nsswitch
