### ISSUE TITLE
Runtime re-ordering of middleware

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#632]
Currently middleware are chained together according to the build-time order defined in middleware.cfg. It would be nice to be able to re-order those for more flexibility when using `fallthrough`.

At a minimum, we should at least have a flag to show users the order. The -plugins flag outputs them in alphabetical order.

**Comment by mholt** [comment]
I'm not sure about the DNS server, but if the HTTP server runs the HTTP middleware in an arbitrary order, it breaks things really bad. Why do you want to reorder them? (I'm not sure what 'fallthrough' is in this sense.)

**Comment by johnbelamaric** [comment]
Many of ours need to be in at least roughly the same order. But we have a subset of middleware that serve as backends to different data sources. Those would be nice to be able to reorder.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Runtime re-or..." ]
>I'm not sure about the DNS server, but if the HTTP server runs the HTTP middleware in an arbitrary order, it breaks things really bad. Why do you want to reorder them? (I'm not sure what 'fallthrough' is in this sense.)

I think I agree with that statement; i.e. runtime reordering can lead to really
weird things.

`fallthrough` is when we handle a query in middleware X, then discover we don't
have a good answer for it. We then don't return an error but fallthrough through
to the next middleware.

**Comment by johnbelamaric** [comment]
Maybe we can limit the set of middleware that can be re-ordered to just the backends. Needs more thought.

**Comment by stp-ip** [comment]
Wouldn't "fallthrough to X" as an option work. So you basically jump over middleware. The only thing needed then would be that the data source used by multiple middlewares is one of the last ones called.

Just an idea, haven't looked on how to implement this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Runtime re-or..." ]
>Wouldn't "fallthrough to X" as an option work. So you basically jump over middleware. The only thing needed then would be that the data source used by multiple middlewares is one of the last ones called.
>
>Just an idea, haven't looked on how to implement this.

I'm not convinced yet that this is a good idea. Mostly worried about weird
interactions and hard to debug problems. Also makes `middleware.cfg` part of the
runtime configuration which is weird (at this point in time).

**Comment by miekg** [comment]
Please re-open if we have an actual plan and agree that this is worth doing.
