### ISSUE TITLE
RRSIGs are served with expiration dates in the past

### ISSUE THREAD

**Issue by liamr4c** [coredns/coredns#635]
The errors given by DNSViz can be seen [here](http://dnsviz.net/d/liams.io/WPUjgA/dnssec/). Invalid RRSIGs obviously makes resolvers like google not want to resolve your domain.

I use the `file` middleware to load the zones and the `dnssec` middleware to sign DNSSEC on the fly, which normally works. My Corefile seems to not have anything obviously wrong:
```
liams.io:53 {
    file liams.io.zone
    dnssec {
        key file Kliams.io.+013+55741
    }
    errors stdout
    rewrite type ANY HINFO
}
```

Restarting coredns usually fixes this, so maybe it is the `cache` not taking into account the fact that RRSIGs expire?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] RRSIGs are served..." ]
>The errors given by DNSViz can be seen [here](http://dnsviz.net/d/liams.io/WPUjgA/dnssec/). Invalid RRSIGs obviously makes resolvers like google not want to resolve your domain.
>
>I use the `file` middleware to load the zones and the `dnssec` middleware to sign DNSSEC on the fly, which normally works. My Corefile seems to not have anything obviously wrong:
>```
>liams.io:53 {
>    file liams.io.zone
>    dnssec {
>        key file Kliams.io.+013+55741
>    }
>    errors stdout
>    rewrite type ANY HINFO
>}
>```
>
>Restarting coredns usually fixes this, so maybe it is the `cache` not taking into account the fact that RRSIGs expire?

you Corefile does not contain `cache` (in the above example). Regarding your
statement: #367

(so you're right; should be a simple fix though)

/Miek

--
Miek Gieben
