### ISSUE TITLE
middleware/http_proxy enhancements

### ISSUE THREAD

**Issue by namliz** [coredns/coredns#636]
Ref: #540, and possibly #522 (this will enable I think what 522 is actually trying to achieve, no API needed)
--

CoreDNS middleware can also be though of as storage backends. 
Currently there is File, and Etcd backends, and Proxy. 

I think it would be useful if CoreDNS could wrap *any* run of the mill HTTP endpoint with dns. The interface formats are already there: grpc and Google's json based [dns-over-https](https://developers.google.com/speed/public-dns/docs/dns-over-https).

Example:
--------

Server A: CoreDNS <---> Servers B, C, D

Say you have a `list_instances.py` script (and credentials for it) on Server A. 

A hackish thing to do currently would be for it to run periodically and generate a zone file, CoreDNS would pickup the changes. 

Servers B, C, D don't have any credentials and only know to use A as their dns resolver.

Proposal:
--------
HTTP Endpoint <---> Server A: CoreDNS http_proxy middleware <---> Servers B, C, D

Now there's no credentials or `list_instances.py` on Server A, it is fully decoupled and hidden behind an endpoint and can be updated separately. 

Possible Corefile syntax: 

```
. {
   http_proxy example.org http://www.hostname.com/whatever/
   log stdout
}
```

From server A:
```
$ curl -s http://www.hostname.com/whatever/resolve?name=something.example.org | jq '.Answer[0].data' 
"23.21.224.150"
```

```
From server B,C,D:
dig @serverA something.example.org
23.21.224.150
```

This would be useful for many use cases, for instance this is how B,C,D can discover each other initially.

**Comment by miekg** [comment]
Noone has seen any PRs. Closing for now.
