### ISSUE TITLE
007 release tracking bug

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#647]
@johnbelamaric anything to add to https://github.com/coredns/coredns/wiki/CoreDNS-007-Release

Want to release 007 before end of month-ish

**Comment by johnbelamaric** [comment]
I added a little there about the `fallthrough` in K8s middleware now. Think that's all.

**Comment by miekg** [comment]
Nice. Thank you. I'll push some buttons and release somewhere in the weekend or early next week.

**Comment by miekg** [comment]
v007 released.

**Comment by miekg** [comment]
post fact ping:  @nwoods3
