### ISSUE TITLE
KubeDNS/CoreDNS performance

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#648]
I've set up a scale test environment, and ran some scale tests to compare performance of kube-dns and coredns.

**Performance Test Environment**

  * 11 machines running in OpenStack, each 4 cpus, 6g ram
  * k8s v1.6.1 (1 master + 10 nodes)
  * k8s running 100 dummy services, with 400 endpoints

**Tests**

Tested by sending 50k valid service/endpoint queries at a sustained rate, ramping up the rate limit until the service started to drop requests.

  * Kube-DNS (cache enabled): 15k qps
  * CoreDNS (cache enabled):   8k qps

  * Kube-DNS (cache disabled): 7k qps
  * CoreDNS (cache disabled):  5k qps

Regarding _disabled_ cache results, I can add indexing for service and endpoint queries to improve performance.
  
Regarding _enabled_ cache results, I'm unfamiliar with the cache implementation.  Hoping @miekg can provide some insight.

**Comment by miekg** [comment]
Thanks for doing this Chris! Really useful. Even 15K for basically cache performance of dnsmasq does not seem that much.

Regardless, yes we should improve performance, but without more data is will be hard. Where is the time spend? Do we have pprof? Is is all over the board, or some easy low-hanging fruit?

CoreDNS's cache uses golang-lru to cache *packets*, not *RRsets*, but in the end this is just a Golang map (I think).

**Comment by miekg** [comment]
Ah, *another* thing that is useful here is proxy throughput.

**Comment by miekg** [comment]
re: cache, my guess would be lock contention

**Comment by chrisohaver** [comment]
For cache enabled CoreDNS, here are the top flat and cummulative CPU routines...

```
Showing top 10 nodes out of 180 (cum >= 4.13s)
      flat  flat%   sum%        cum   cum%
         0     0%     0%     11.05s 73.67%  runtime.goexit
         0     0%     0%      7.21s 48.07%  github.com/miekg/dns.(*Server).serve
     0.01s 0.067% 0.067%      6.84s 45.60%  github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1
         0     0% 0.067%      6.84s 45.60%  github.com/miekg/dns.HandlerFunc.ServeDNS
     0.07s  0.47%  0.53%      6.82s 45.47%  github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS
         0     0%  0.53%      6.62s 44.13%  github.com/coredns/coredns/middleware/errors.(*errorHandler).ServeDNS
     0.01s 0.067%   0.6%      6.62s 44.13%  github.com/coredns/coredns/middleware/errors.errorHandler.ServeDNS
     0.01s 0.067%  0.67%      6.54s 43.60%  github.com/coredns/coredns/middleware.NextOrFailure
         0     0%  0.67%      6.50s 43.33%  github.com/coredns/coredns/middleware/cache.(*Cache).ServeDNS
     3.54s 23.60% 24.27%      4.13s 27.53%  syscall.Syscall
(pprof) top
8950ms of 15000ms total (59.67%)
Dropped 204 nodes (cum <= 75ms)
Showing top 10 nodes out of 180 (cum >= 230ms)
      flat  flat%   sum%        cum   cum%
    3540ms 23.60% 23.60%     4130ms 27.53%  syscall.Syscall
    1970ms 13.13% 36.73%     1970ms 13.13%  runtime.futex
     700ms  4.67% 41.40%      700ms  4.67%  runtime.usleep
     670ms  4.47% 45.87%     1060ms  7.07%  runtime.scanobject
     610ms  4.07% 49.93%      610ms  4.07%  runtime.epollwait
     400ms  2.67% 52.60%     1530ms 10.20%  runtime.mallocgc
     320ms  2.13% 54.73%      330ms  2.20%  runtime.greyobject
     260ms  1.73% 56.47%      260ms  1.73%  runtime.memclrNoHeapPointers
     250ms  1.67% 58.13%      250ms  1.67%  runtime._ExternalCode
     230ms  1.53% 59.67%      230ms  1.53%  runtime.memmove

```

The high % syscall.syscall is in the recvmsg chain.

**Comment by miekg** [comment]
Can you completely kill the error middleware? I.e. disable it and rip out the error handling code (the defer and recover it does)?

> The high % syscall.syscall is in the recvmsg chain.
I've seen that before in the context of skydns and k8s (even!). What does that mean?

**Comment by miekg** [comment]
Could that OOB UDP socket annotation account for those syscall stuff? https://github.com/miekg/dns/blob/master/udp_linux.go
(this is needed to route the packet to the correct interface, but is not needed in all cases, and might slow things down)

**Comment by miekg** [comment]
To rule out the udp OOB stuff, we should create our dns.Reader in use that in the server.  Should not be too hard, but I would like to be able to run the benchmarks as well, instead of changing some code and then wait for you to run some tests :)

Cache handling is completely done in Go and in coredns so I consider that the least of our problem. Interaction with go-dns, Linux, UDP  and UDP session handling seems more interesting.

I'm also not sure of go pprof is up to the task and that we might need more advanced stuff (perf? sysdig? - never used those tools in anger).

**Comment by miekg** [comment]
And final question: what do you use for sending queries? I want standup is similar setup.

**Comment by johnbelamaric** [comment]
@chrisohaver will provide links to the tool we use. He also has scripts to set this up in k8s. What do you think about a "test" or "scale" repo for this stuff under the coredns org?

**Comment by chrisohaver** [comment]
I am using the 'mig' tool at https://github.com/infobloxopen/dnstools/.  The mig tool is located in mig/probe.

An example use of the tool:
`./mig -l  5000 -n 20000 -s 10.96.0.10 -d ~/scale/scale-a.no-pods.lst -o ./out.json`

-l = qps rate limit
-n = number of queries to send
-s = IP of dns service
-d = domain name file
-o = data output (which can be analyzed by grinder tool in mig/analysis)

**Comment by miekg** [comment]
Ack. Yeah, new repo is fine.

**Comment by miekg** [comment]
For most of these performance tests you don't even need k8s. But a repo (so we all test the same) will be handy

**Comment by johnbelamaric** [comment]
A home for these scripts: https://github.com/coredns/perf-tests

**Comment by miekg** [comment]
Filing bugs in the mig` repo.

Also I think `mig` let CoreDNS hit an internal go-routine limit (or something). Look interesting, but right now I'll continue with queryperf.

**Comment by miekg** [comment]
We should prolly move this discussion to the perf-tests repo. But if I can do 100+K qps on my laptop (4 cpu, 8 GB), we should aim for that kind of performance with caching enabled.

But having benchmarked for a day, my head is already spinning, some kind of reproduce-able setup would be *really* handy

**Comment by johnbelamaric** [comment]
Discussion moved to https://github.com/coredns/perf-tests/issues/4
