### ISSUE TITLE
No NS servers provide for a domain handled by the kubernetes middleware.

### ISSUE THREAD

**Issue by ashmere** [coredns/coredns#659]
It looks like coredns doesn't set the ns server for a domain handled by the kubernetes middleware, this prevents us from using things like stub zones to point to coredns for this domain.

**Comment by chrisohaver** [comment]
@ashmere, In your case, is the server pointing to coredns in cluster, or external to the cluster?

When the NS request source is in the cluster, we can always return the coredns service's cluster ip.

If the NS request source is _external_ to the cluster, we could return coredns service's external ip (if there is one configured).  However, as it is now, coredns builds A records for cluster IPs, not external IPs, so the answers would contain IPs that are unreachable from outside the cluster.

**Comment by miekg** [comment]
@ashmere do you mean that thing where skydns put the NS record in /skydns/dns/ns ? Or just that it does not have a reply for `NS`?

**Comment by ashmere** [comment]
@miekg here is an example of dig from a kubernetes node in the cluster 
`
dig -t ns corp-eu3.k8s.improbable.io 
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN
;; Question section mismatch: got ns.dns.corp-eu3.k8s.improbable.io/NS/IN

; <<>> DiG 9.10.2-P4 <<>> -t ns corp-eu3.k8s.improbable.io
;; global options: +cmd
;; connection timed out; no servers could be reached
`

@chrisohaver in our case external vs internal isn't a concern as these are all routable from everywhere we need. Ideally I'd prefer the coredns returned the service cluster ip for the coredns service, but even the binding ip address of the coredns server would work.

**Comment by chrisohaver** [comment]
I'm close to a solution (returning Cluster IP of service) ... I may have a PR in later today.

**Comment by johnbelamaric** [comment]
#662
