### ISSUE TITLE
Defaults in middleware/chaos don't match documentation

### ISSUE THREAD

**Issue by cricketliu** [coredns/coredns#667]
With a minimal Corefile using the chaos middleware:

.:53 {
        proxy . 10.102.3.10 10.0.2.60
        cache
        chaos 
        errors stdout
        log stdout
}

the default behavior is supposed to be to return "CoreDNS-<version>" to a version.bind query, at least according to https://github.com/coredns/coredns/tree/master/middleware/chaos.  However, what's returned is just "-":

% dig chaos txt version.bind. @127.0.0.1

; <<>> DiG 9.10.3 <<>> chaos txt version.bind. @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39416
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;version.bind.			CH	TXT

;; ANSWER SECTION:
version.bind.		0	CH	TXT	"-"

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri May 19 14:56:19 PDT 2017
;; MSG SIZE  rcvd: 67

**Comment by miekg** [comment]
Yes, looks broken. AppName and AppVersion are not properly set.
