### ISSUE TITLE
Procedure for updating deps

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#675]
What's the procedure for updating the dependencies? `go dep <something>`
I also propose that after a release we update the lot.

**Comment by johnbelamaric** [comment]
@yongtang is there an easy way to do this?

I agree we should do this after every release.

**Comment by yongtang** [comment]
@miekg @johnbelamaric I will update the README.md to have a section for the dependency updating procedures.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Procedure for..." ]
>@miekg @johnbelamaric I will update the README.md to have a section for the dependency updating procedures.

Thanks!

Should we put it in DEVELOPER.md file instead? README.md should be more user
oriented IMHO.

**Comment by miekg** [comment]
I *think* hashicorps syslog stuff isn't used anymore (see future PR) how can I check that and then subsequently remove the vendored directory?

**Comment by yongtang** [comment]
@miekg @johnbelamaric PR #688 added a section in `CONTRIBUTING.md` for vendor management.

@miekg With `dep endure --update` hashicorp 's stuff will be removed automatically.
