### ISSUE TITLE
middleware/secondary: store the zone on disk

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#681]
Currently we only have the zone in memory; you'll need to transfer all secondary zones on startup. We should store these on disk (actually mandated by the RFC as well).

**Comment by miekg** [comment]
1.0.0 for realz this time.

**Comment by virtualdxs** [comment]
Any particular reason this is wontfix? Lack of cycles? It's unfortunate, as having secondary persisted to disk is helpful for reliability.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/se..." ]
>Any particular reason this is wontfix? Lack of cycles? It's unfortunate, as
>having secondary persisted to disk is helpful for reliability.

lack of cycled *and* what _is_ disk in the context of k8s or anything else that isn't
running on a plain linux machine. Any "disk" abstraction like http.FileSystem would be
needed here.

**Comment by kfox1111** [comment]
disk still makes sense in a container. k8s typically persists things in a pvc. So not sure its any different then the plain linux machine case.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/se..." ]
>disk still makes sense in a container. k8s typically persists things in a pvc.

so does it persists or not. EmptyDir{} is similar to storing in memory, so I don't see
what the win is here. PVC look nice, but are on the network, how do you access those when
the DNS is down?

>So not sure its any different then the plain linux machine case.

http.FileSsystem abstraction *might* make some sense here to isolate us from disk.

**Comment by virtualdxs** [comment]
Bear with me, as I don't know how all this works behind the scenes, but it seems to me like you shouldn't have to worry about whether you're in k8s or not. What I would do is similar to auto and file have the user specify a zone file if they want it persisted (I see no reason to require persistence), and on server startup create it if it doesn't exist. That way, if an admin doesn't care about persistence, it maintains its behavior, and the admin can decide how persistent they want it - if it's in a container, they can mount a volume where the zone file will be if they want it to be truly persistent.

**Comment by kfox1111** [comment]
Yeah. Just like in normal linux, you can mount volumes into your containers in Kubernetes. They can be backed by tmpfs (emptydir) just like in normal linux, or it can be backed by all kinds of other ephermal or persistent storage like normal linux mounts.

You can just expose storage from the host its running on with hostPath or a local-storage provisioned PV (https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/), it can be stored in ceph, or other ha filesystems, etc.

But at the end of the day, to whatever's running in the container, its just a directory you can store stuff in just like regular linux. The software doesn't need to know anything about the fact its running in k8s or not, or change its behavior in any way. Its up to the person configuring the software and deploying the container to decide how to configure the software and how persistent the volume just like if it were running outside k8s. How the admin configures the mount may differ from raw linux vs k8s but to the software running inside, its no different at all.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/se..." ]
>Bear with me, as I don't know how all this works behind the scenes, but it
>seems to me like you shouldn't have to worry about whether you're in k8s or
>not. What I would do is similar to auto and file have the user specify a zone
>file if they want it persisted (I see no reason to require persistence), and on
>server startup create it if it doesn't exist. That way, if an admin doesn't
>care about persistence, it maintains its behavior, and the admin can decide how
>persistent they want it - if it's in a container, they can mount a volume where
>the zone file will be if they want it to be truly persistent.

I got lazy when implementing *auto* ideally that should also become disk agnostic so you
can store on s3, gcp, in-memory or actual disk. (also helps with testing)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/se..." ]
>Yeah. Just like in normal linux, you can mount volumes into your containers in

you're asuming we need a posix fs (or require a posix fs), I don't think we do.

**Comment by virtualdxs** [comment]
I'd definitely be in favor of an abstraction layer for that exact reason. Perhaps implement that for file and auto, and then come back and look at implementing it here?

As a side note, it would be nice to have an auto capability for this as well, and to read the serial from the file (vs memory) before updating it, so you could have multiple servers pointing at the same file and have one update it and the rest pick it up automatically. (This may be a given, but I figured worth mentioning just in case.)

**Comment by kfox1111** [comment]
Yeah, it would be interesting to have a single writer / multiple reader thing. If you did support plugable storage, you could then store it in a Kubernetes configmap or secret directly and not need to use a pvc at all.

Not apposed to plug-ability. Just mentioning that it isn't a requirement to implement the feature and still be compatible with Kubernetes. Plugability could be a separate pr.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/se..." ]
>Yeah, it would be interesting to have a single writer / multiple reader thing.
>If you did support plugable storage, you could then store it in a Kubernetes
>configmap or secret directly and not need to use a pvc at all.
>
>Not apposed to plug-ability. Just mentioning that it isn't a requirement to
>implement the feature and still be compatible with Kubernetes. Plugability
>could be a separate pr.

This is how I think it should look:

https://github.com/coredns/coredns/issues/3954 references a branch where I implemented
it for the tls package, meaning those (key/pem) files can now be stored on s3 (if I
implemented that)

/Miek

--
Miek Gieben

**Comment by virtualdxs** [comment]
Seeing as #3954 has been closed as wontfix, can this be reopened to be implemented without abstraction?

**Comment by MayCXC** [comment]
> [ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/se..." ]
> Yeah. Just like in normal linux, you can mount volumes into your containers in
> you're asuming we need a posix fs (or require a posix fs), I don't think we do.

k8s PVCs do use POSIX fs abstractions with `volumeMode: Filesystem`, and it is sufficient for `volumeMode: Block` to be interfaced with via a POSIX fs. for networked CSIs like https://github.com/ctrox/csi-s3 , it is still idiomatic to use a mounted POSIX fs via FUSE. is there some other k8s abstraction you need to be targeting? afaict every plugin should be able to do its needed disk operations with a configurable directory path and `fs`.
