### ISSUE TITLE
Release v008 Tracking

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#683]
Tracking issue for release v008. See also https://github.com/coredns/coredns/wiki/CoreDNS-008-Release

**Comment by johnbelamaric** [comment]
@miekg @nwoods3 issue for tracking the 008 release which is expected in the first half of June.

**Comment by johnbelamaric** [comment]
Open issues list: https://github.com/coredns/coredns/issues?q=is%3Aopen+is%3Aissue+milestone%3A008

@miekg @chrisohaver barring new bugs does next week look likely for release?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Release v008 ..." ]
>Open issues list: https://github.com/coredns/coredns/issues?q=is%3Aopen+is%3Aissue+milestone%3A008
>
>@miekg @chrisohaver barring new bugs does next week look likely for release?

SGTM.

**Comment by chrisohaver** [comment]
I think i’ll have #390 done by next week.

On Jun 6, 2017, at 10:02 AM, John Belamaric <notifications@github.com<mailto:notifications@github.com>> wrote:


Open issues list: https://github.com/coredns/coredns/issues?q=is%3Aopen+is%3Aissue+milestone%3A008

@miekg<https://github.com/miekg> @chrisohaver<https://github.com/chrisohaver> barring new bugs does next week look likely for release?

**Comment by miekg** [comment]
OK, #390 is the only ones left - bumped more invasive bugs to 009

**Comment by miekg** [comment]
I think we should release soonish, if #390 is not yet done we should bump to 009 (and maybe release that pretty quickly).
I would also like to merge #731 into 008, but can be persuaded to wait for 009.

WDYT?

**Comment by chrisohaver** [comment]
Regarding #390: Federation Support is added by #723. It implements the current kubernetes federated service discovery model.

**Comment by johnbelamaric** [comment]
Plan to release this later today.

**Comment by johnbelamaric** [comment]
@nwoods3 - release is done! Blog entry won't be out until tomorrow though

**Comment by miekg** [comment]
Pushed blog out and tweet. Release is public
