### ISSUE TITLE
AXFR not restrictable

### ISSUE THREAD

**Issue by Centzilius** [coredns/coredns#685]
Hi,
I can't restrict transfer of my zones to a single ip.
Steps to reproduce:
```
centzilius.tk {
    file /srv/coredns/centzilius.tk.txt centzilius.tk {
        transfer to 93.95.224.6
    }
    errors stdout
    log stdout
}
```
Log:
```
centzilius.tk.:53
2017/05/31 10:40:37 [INFO] CoreDNS-007
CoreDNS-007
2017/05/31 10:40:37 [INFO] Sent notify for zone "centzilius.tk." to "93.95.224.6:53"
93.95.224.6 - [31/May/2017:10:40:37 +0200] "SOA IN centzilius.tk. udp 43 false 2048" NOERROR 181 363.541µs
93.95.224.6 - [31/May/2017:10:40:37 +0200] "IXFR IN centzilius.tk. tcp 125 false 65535" SERVFAIL 31 197.076µs
93.95.224.6 - [31/May/2017:10:40:37 +0200] "SOA IN centzilius.tk. tcp 31 false 65535" NOERROR 169 250.6µs
93.95.224.6 - [31/May/2017:10:40:37 +0200] "AXFR IN centzilius.tk. tcp 31 false 65535" SERVFAIL 31 166.83µs
93.95.226.52 - [31/May/2017:10:40:38 +0200] "SOA IN centzilius.tk. udp 43 false 2048" NOERROR 181 523.102µs
93.95.226.52 - [31/May/2017:10:40:38 +0200] "IXFR IN centzilius.tk. tcp 125 false 65535" SERVFAIL 31 364.418µs
93.95.226.52 - [31/May/2017:10:40:38 +0200] "SOA IN centzilius.tk. tcp 31 false 65535" NOERROR 169 297.159µs
93.95.226.52 - [31/May/2017:10:40:38 +0200] "AXFR IN centzilius.tk. tcp 31 false 65535" SERVFAIL 31 379.819µs
```
AXFR is only possible if `transfer to *` is present.

**Comment by Centzilius** [comment]
This is a duplicate of #469. Sorry for wasting your time ._.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] AXFR not rest..." ]
>This is a duplicate of #469. Sorry for wasting your time ._.

Yes, ideas welcome - shoudl probably just go for a basic syntax and refine
latter

**Comment by Centzilius** [comment]
How about we check if the incoming ip is one of the ips beeing notified

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] AXFR not rest..." ]
>How about we check if the incoming ip is one of the ips beeing notified

Yes, but might be worth putting this in a separate middleware, like discussed in
the other bug.

**Comment by Centzilius** [comment]
yeah but maybe as a temporary solution...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] AXFR not rest..." ]
>yeah but maybe as a temporary solution...

Code needs to be written anyway, putting it in a diff. middleware isn't the hard
part here (IMHO)
