### ISSUE TITLE
middleware/kubernetes: coredns + minikube magic

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#690]
When coredns is run out-of-cluster on a system with minikube installed, k8s middleware "magically" connects successfully to the minkube API instance, as if it was running in-cluster.  It does this regardless of what api endpoint/cert is configured in the Corefile (it ignores the endpoint/cert configuration).

The k8s middleware may be falsely detecting that it is in cluster due the environment.  If you switch kubectl context away from minikube, the connection then fails.  So somehow, its picking up on the locally active kubectl context.

Not sure if this only happens with minikube, or if it would also happen on real k8s (but I suspect it would).

Expected behavior is that if an endpoint/cert is configured in k8s middleware, it should be used always.

**Comment by yongtang** [comment]
@chrisohaver Do you have a test case for this issue?

**Comment by chrisohaver** [comment]
You mean steps to reproduce?

**Comment by yongtang** [comment]
@chrisohaver yes would like to take a look if possible.

**Comment by chrisohaver** [comment]
I have a working fix for this - but I have not tested it rigorously.  In a nutshell the type of k8s client used is pulling in enviroment vars, and is confused by the presence of kubectl configurations.  The fix is to change the way we instatiate the client objects, so that the system envvars are not pulled in.  Works locally, but I want to test it a bit more before saying it's the right fix. 

This issue can be reproduced as described in the issue description... essentially by running the integration tests on a system that has minikube installed.
