### ISSUE TITLE
wildcard DNS / mimic xip.io

### ISSUE THREAD

**Issue by jremond** [coredns/coredns#691]
I started to look at implementing a behaviour similar to http://xip.io/
It's my first code in Go and the name is definitively not final but it is in my gurdil branch https://github.com/jremond/coredns/tree/gurdil

The idea is to resolve 
any.thing.1.2.3.4.example.com 
to 
1.2.3.4 

Corefile looks like
```
.:1053 {
    gurdil example.com
    log stdout
    errors stdout
}

```

Do you think it's worth putting more effort into a proper Go implementation ?

Thanks

**Comment by miekg** [comment]
Sure this looks useful. Does xip.io only do the forward A address? Or also reverse. What about ipv6?

Reminds me of the `reverse` middleware, btw: https://github.com/coredns/coredns/tree/master/middleware/reverse

Note that middleware can also be 'out of tree', by just editing `middleware.cfg` you can add new one from wherever.

**Comment by jremond** [comment]
From my understanding when reading https://github.com/basecamp/xip-pdns/blob/master/bin/xip-pdns
xip.io only supports IPv4 and only when requesting a domain like [anything.]IP.example.com
It also adds SOA and NS records from the configuration file.

I don't see which behaviour would be the right one for the reverse
should 192.30.253.112 resolves to 
* github.com
* 192.30.253.112.example.com
* 192.30.253.112.reverse.example.com

For ipv6 I don't think ":" is a valid character for a domain, how would you represent the IP to keep it human friendly ? Just remove it  and support only address with all 0 expanded ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard DNS ..." ]
>From my understanding when reading https://github.com/basecamp/xip-pdns/blob/master/bin/xip-pdns
>xip.io only supports IPv4 and only when requesting a domain like [anything.]IP.example.com
>It also adds SOA and NS records from the configuration file.

Ack.

>I don't see which behaviour would be the right one for the reverse
>should 192.30.253.112 resolves to
>* github.com
>* 192.30.253.112.example.com
>* 192.30.253.112.reverse.example.com

Depends who owns these IPs, reverse is always a bit tricky in that regard.

>For ipv6 I don't think ":" is a valid character for a domain, how would you represent the IP to keep it human friendly ? Just remove it  and support only address with all 0 expanded ?

Actually `:` should just work:  dig a:a:a.mx, although legacy tools might have
problems with that. We apply some conversion in the reverse middleware IIRC.

We shouldn't add a middleware that can only deal with IPv4. I tried to write
down some guidelines here:
https://github.com/coredns/coredns/blob/master/middleware.md#qualifying-for-main-repo

So if we can work out how to do v6 as well, hook up soa and ns records this can
indeed be useful.

**Comment by jremond** [comment]
For ipv6, does
;; ANSWER SECTION:
1:2:3:4:5:6:7:8.example.org. 0  IN      AAAA    1:2:3:4:5:6:7:8
that make sense to you ?
I updated my branch with some basic code https://github.com/jremond/coredns/tree/gurdil

Concerning the name, I'm not sure if "wildcard" is the right one, any idea ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard DNS ..." ]
>For ipv6, does
>;; ANSWER SECTION:
>1:2:3:4:5:6:7:8.example.org. 0  IN      AAAA    1:2:3:4:5:6:7:8
>that make sense to you ?
>I updated my branch with some basic code https://github.com/jremond/coredns/tree/gurdil
>
>Concerning the name, I'm not sure if "wildcard" is the right one, any idea ?

Looking back in this discussion *and* the README of the *reverse* middleware...
I think this is the exact same functionality as in *reverse*? (We had some
discussion about that name as well - maybe it should be renamed)

/Miek

--
Miek Gieben

**Comment by jremond** [comment]
After some testing it looks quite similar to reverse, except that with the reverse middleware you only have one A record for one IP.
In this case, the idea is to be able to use any domain name containing IP.example.org
test1.127.0.0.2.example.org
test2.127.0.0.2.example.org
test3.127.0.0.2.example.org
test4.127.0.0.2.example.org
all resolves to 127.0.0.2

I use it mainly for quick virtualhost testing with webservers.

I haven't found a way to put some wildcard in the template argument of reverse, that may be enough to do what I need.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard DNS ..." ]
>After some testing it looks quite similar to reverse, except that with the reverse middleware you only have one A record for one IP.
>In this case, the idea is to be able to use any domain name containing IP.example.org
>test1.127.0.0.2.example.org
>test2.127.0.0.2.example.org
>test3.127.0.0.2.example.org
>test4.127.0.0.2.example.org
>all resolves to 127.0.0.2

It would be good to make the reverse middleware more general applicable and add
to ability to have more than 1 IP per name?

/Miek

--
Miek Gieben

**Comment by jremond** [comment]
What would you expect when you say more than 1 IP per name ?
like test.127.0.0.example.org resolving to all 127.0.0.X IPs ?

I made a small try on another branch with only a way to replace the separator in the IPv4 
https://github.com/jremond/coredns/tree/reverse-wildcard

```
test:1053 {
    reverse 127.0.0.0/8 {
        hostname ip-{ip}.{zone[1]}
        ip4separator "."
    }
}
```

allows to resolve ip-127.0.3.1.test to 127.0.3.1

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard DNS ..." ]
>What would you expect when you say more than 1 IP per name ?
>like test.127.0.0.example.org resolving to all 127.0.0.X IPs ?

hmmm, interesting point. That can prove somewhat tricky. I think the point that
I was making is: we should add a middleware that is just slightly different, but
instead focus on making the already included middleware do what you want (if
possible).

You can also choose to keep this *xip* middleware out of tree - happy to
document this on our soon-to-be-redesigned-website.

/Miek

--
Miek Gieben

**Comment by jremond** [comment]
https://github.com/jremond/coredns/tree/reverse-wildcard
For now I tried to build a wildcard option
```
.:1053 {
    log stdout
    errors stdout
    reverse 127.0.0.0/8 {
        hostname ip-{ip}.example.org
        ip4separator "."
        wildcard
    }
}
```

-> dig +short @127.0.0.1 -p 1053 ip-127.0.3.1.example.org
127.0.3.1
-> dig +short @127.0.0.1 -p 1053 test.ip-127.0.3.1.example.org
127.0.3.1

-> dig +short @127.0.0.1 -p 1053  -x 127.0.3.1                                                       
ip-127.0.3.1.example.org.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard DNS ..." ]
>https://github.com/jremond/coredns/tree/reverse-wildcard
>For now I tried to build a wildcard option
>```
>.:1053 {
>    log stdout
>    errors stdout
>    reverse 127.0.0.0/8 {
>        hostname ip-{ip}.example.org
>        ip4separator "."
>        wildcard
>    }
>}
>```
>
>-> dig +short @127.0.0.1 -p 1053 ip-127.0.3.1.example.org
>127.0.3.1
>-> dig +short @127.0.0.1 -p 1053 test.ip-127.0.3.1.example.org
>127.0.3.1
>
>-> dig +short @127.0.0.1 -p 1053  -x 127.0.3.1
>ip-127.0.3.1.example.org.

That's nice! Could this also be done in the hostname spec? Like allowing `*`?
`*.ip-{ip}.exampl.org`, which means `ip-{ip}.example.org` and everything below.
But maybe a separate *wildcard* keyword is nicer - dunno.

What's ipv4seperator?

/Miek

--
Miek Gieben

**Comment by jremond** [comment]
`ip4separator` is the character between the 4 numbers in ip-127**.**0**.**3**.**1.example.org
it replaces the **-** which is the default

I tried to use `*` in the hostname spec but I don't know how to deal with the reverse record at this point
With `hostname *.ip-{ip}.{zone}` 
should 127.0.3.1 returns : 
* ip-127-0-3-1.example.org
* something else ?

Should I create a Pull request with WIP at this point https://github.com/jremond/coredns/tree/reverse-wildcard ?

**Comment by miekg** [comment]
>  tried to use * in the hostname spec but I don't know how to deal with the reverse record at this point
With hostname *.ip-{ip}.{zone}
should 127.0.3.1 returns :

> ip-127-0-3-1.example.org
> something else ?

But by having a separate wildcard keyword, you would have the same problem? I.e. `wildcard` is just prefixing the regexp with `*.` except we don't write that in the regexp? I still believe a `*` prefix and treating that differently is cleaner (the hostspec is not really a regexp anyway). The reverse name returned should then just work as if `*` was not prefixed.

Can you can rid of `ipv4seperator`?

**Comment by jremond** [comment]
With the separate wildcard keyword I don't change the Template but only the RegexMatchIP so no problem since the reverse only uses the Template.

The ipv4separator is a totally different question but aims at allowing people to change the character between numbers in the IP part of the domain name.

Should I create two different branches ?

**Comment by jremond** [comment]
@miekg would 2 merge requests make more sense ?
To separate the wildcard and the ipv4 separator character.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard DNS ..." ]
>@miekg would 2 merge requests make more sense ?
>To separate the wildcard and the ipv4 separator character.

Sorry, left you hanging there a bit. I really dislike the ipv4 separator thing, 
but I haven't found the time to leak into it in more detail.

/Miek

--
Miek Gieben

**Comment by jremond** [comment]
I don't want to change the default behaviour of the reverse middleware but I like the idea of having the ability to use the most common string representation of an IPv4 (127.2.3.4 instead of 127-2-3-4).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard DNS ..." ]
>I don't want to change the default behaviour of the reverse middleware but I like the idea of having the ability to use the most common string representation of an IPv4 (127.2.3.4 instead of 127-2-3-4).

I agree that that looks nicer (I consider CoreDNS young enough that changing 
defaults is still permitted, but we should have good reasons).

We could do the same with v6 addresses, i.e. leave the `:` (or change that to 
dots as well, might trip over some over zealous libraries that check for DNS 
correctness)


/Miek

--
Miek Gieben

**Comment by jremond** [comment]
I'm trying to look at the wildcard idea.
It does work cleanly with a separate keyword but I am not able to find a way to use the * character in the template value. I'm probably missing where to remove the * in some part of the code so it doesn't try to interpret it.

**Comment by jremond** [comment]
I pushed my implementation with a separate keyword.

**Comment by jremond** [comment]
All done here !

**Comment by tmm1** [comment]
Is there a new plugin that's equivalent to the old `reverse` middleware? Or a better way to implement xip.io style DNS?

**Comment by chrisohaver** [comment]
@tmm1, you should be able to use the _template_ plugin to accomplish the behavior described in this issue.

**Comment by gaby** [comment]
I don't understand with the `reverse` plugin was removed, it was so much easier than using `templates`.
