### ISSUE TITLE
middleware/consul: New middleware for Consul

### ISSUE THREAD

**Issue by VioletRainbows** [coredns/coredns#712]
New middleware for Consul.

Currently, the middleware would be heavily inspired by the etcd middleware.

_Claiming this issue as my own._

**Comment by johnbelamaric** [comment]
We also need etcd3 support 👍

**Comment by miekg** [comment]
etcd3: #341 (should probably drop v2 support, when we have v3)

**Comment by VioletRainbows** [comment]
I'm trying to use `dep` to download `github.com/hashicorp/consul/api`.

The result is over 7500 files added (https://github.com/VioletRainbows/coredns/commit/198c6ef45843d465fea1aad0823516567e4b1aa3)
```
$ dep ensure github.com/hashicorp/consul/api@^0.8.3
dependency path github.com/hashicorp/consul/api is not a project root, try github.com/hashicorp/consul instead

$ dep ensure github.com/hashicorp/consul@^0.8.3
# Adds 7.5k files
```

How do you handle such dependencies (as `consul/api` has very little requirements compare to `consul`)?

**Comment by johnbelamaric** [comment]
@yongtang any advice?

**Comment by miekg** [comment]
Just leave the dep side out of it. We'll sort that out later.

**Comment by VioletRainbows** [comment]
# Dependency madness
I'm having some real issues with the `dep` dependency management tool.

If, in a new project, I add `import consulapi "github.com/hashicorp/consul/api"` and run `dep ensure -v -n`, I get the following output:
```
Would have written the following projects to the vendor directory:
github.com/hashicorp/consul@f4360770d8e7b852e2d05835b583d20799e58133
github.com/hashicorp/go-cleanhttp@3573b8b52aa7b37b9358d966a898feb387f62437
github.com/hashicorp/go-rootcerts@6bb64b370b90e7ef1fa532be9e591a81c3493e00
github.com/mitchellh/go-homedir@b8bc1bf767474819792c23f32d8286a45736f1c6
github.com/hashicorp/serf@d6574a5bb1226678d7010325fb6c985db20ee458
```

It makes complete sence.

But, If I run the same command in CoreDns, I get the following output:
```
Would have written the following projects to the vendor directory:
github.com/openzipkin/zipkin-go-opentracing@6022d4d3ed39632fad842942bda1813a9b4f63c8
github.com/gogo/protobuf@100ba4e885062801d56799d78530b73b178a78f3
github.com/eapache/go-resiliency@6800482f2c813e689c88b7ed3282262385011890
github.com/kr/logfmt@b84e30acd515aadc4b783ad4ff83aff3299bdfe0
github.com/prometheus/procfs@65c1f6f8f0fc1e2185eb9863a3bc751496404259
github.com/blang/semver@b38d23b8782a487059e8fc8773e9a5b228a77cb6
github.com/PuerkitoBio/urlesc@bbf7a2afc14f93e1e0a5c06df524fbd75e5031e5
cloud.google.com/go@2e6a95edb1071d750f6d7db777bf66cd2997af6c
github.com/prometheus/client_model@6f3806018612930941127f2a7c6c453ba2c527d2
github.com/coreos/go-oidc@c797a55f1c1001ec3169f1d0fbb4c5523563bec6
github.com/hashicorp/golang-lru@0a025b7e63adc15a622f29b0b2c4c3848243bbf6
github.com/golang/snappy@553a641470496b2327abcac10b36396bd98e45c9
k8s.io/client-go@1195e3a8ee1a529d53eed7c624527a68555ddf1f
github.com/docker/distribution@a25b9ef0c9fe242ac04bb20d3a028442b7d266b6
github.com/prometheus/common@13ba4ddd0caa9c28ca7b7bffe1dfa9ed8d5ef207
gopkg.in/inf.v0@3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4
github.com/pborman/uuid@a97ce2ca70fa5a848076093f05e639a89ca34d06
google.golang.org/genproto@aa2eb687b4d3e17154372564ad8d6bf11c3cf21f
github.com/coreos/etcd@d267ca9c184e953554257d0acdd1dc9c47d38229
github.com/go-logfmt/logfmt@390ab7935ee28ec6b286364bba9b4dd6410cb3d5
golang.org/x/crypto@e1a4589e7d3ea14a3352255d04b6f1a418845e5e
github.com/PuerkitoBio/purell@0bcb03f4b4d0a9428594752bd2a3b9aa0a9d4bd4
google.golang.org/appengine@150dc57a1b433e64154302bdc40b6bb8aefa313a
golang.org/x/sys@b90f89a1e7a9c1f6b918820b3daa7f08488c8594
github.com/ghodss/yaml@0ca9ea5df5451ffdf184b4428c902747c2c11cd7
github.com/jonboulle/clockwork@2eee05ed794112d45db504eb05aa693efd2b8b09
github.com/fsnotify/fsnotify@629574ca2a5df945712d3079857300b5e4da0236
github.com/opentracing/opentracing-go@1949ddbfd147afd4d964a9f00b24eb291e0e7c38
github.com/mailru/easyjson@44c0351a5bc860bcb2608d54aa03ea686c4e7b25
github.com/apache/thrift@b2a4d4ae21c789b689dd162deb819665567f481c
github.com/eapache/queue@ded5959c0d4e360646dc9e9908cff48666781367
github.com/ugorji/go@708a42d246822952f38190a8d8c4e6b16a0e600c
github.com/hashicorp/go-cleanhttp@3573b8b52aa7b37b9358d966a898feb387f62437
github.com/grpc-ecosystem/grpc-opentracing@6c130eed1e297e1aa4d415a50c90d0c81c52677e
github.com/emicklei/go-restful@777bb3f19bcafe2575ffb2a3e46af92509ae9594
github.com/go-openapi/jsonreference@36d33bfe519efae5632669801b180bf1a245da3b
github.com/go-openapi/swag@e43299b4afa7bc7f22e5e82e3d48607230e4c177
golang.org/x/oauth2@f047394b6d14284165300fd82dad67edb3a4d7f6
golang.org/x/text@4ee4af566555f5fbe026368b75596286a312663a
github.com/howeyc/gopass@bf9dde6d0d2c004a008c27aaee91170c786f6db8
github.com/eapache/go-xerial-snappy@bb955e01b9346ac19dc29eb16586c90ded99a98c
github.com/hashicorp/consul@ea2a82b221c3e0a466a4f38ab4e8718ad8c60621
github.com/go-openapi/spec@e51c28f07047ad90caff03f6450908720d337e0c
github.com/googleapis/gax-go@9af46dd5a1713e8b5cd71106287eba3cefdde50b
github.com/imdario/mergo@3e95a51e0639b4cf372f2ccf74c86749d747fbdc
github.com/juju/ratelimit@5b9ff866471762aa2ab2dced63c9fb6f53921342
github.com/miekg/dns@e78414ef75607394ad7d917824f07f381df2eafa
github.com/beorn7/perks@4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9
github.com/golang/glog@23def4e6c14b4da8ac2ed8007337bc5eb5007998
github.com/spf13/pflag@e57e3eeb33f795204c1ca35f56c44f83227c6e66
github.com/mitchellh/go-homedir@b8bc1bf767474819792c23f32d8286a45736f1c6
github.com/matttproud/golang_protobuf_extensions@3247c84500bff8d9fb6d579d800f20b3e091582c
github.com/rcrowley/go-metrics@1f30fe9094a513ce4c700b9a54458bbb0c96996c
github.com/coreos/pkg@3ac0863d7acf3bc44daf49afef8919af12f704ef
github.com/Shopify/sarama@c01858abb625b73a3af51d0798e4ad42c8147093
google.golang.org/grpc@d2e1b51f33ff8c5e4a15560ff049d200e83726c5
github.com/pierrec/xxHash@f051bb7f1d1aaf1b5a665d74fb6b0217712c69f7
github.com/google/gofuzz@44d81051d367757e1c7c6a5a86423ece9afcf63c
github.com/golang/protobuf@5a0f697c9ed9d68fef0116532c6e05cfeae00e55
github.com/davecgh/go-spew@346938d642f2ec3594ed81d874461961cd0faa76
github.com/pierrec/lz4@5c9560bfa9ace2bf86080bf40d46b34ae44604df
github.com/prometheus/client_golang@c5b7fccd204277076155f10851dad72b76a49317
golang.org/x/net@3da985ce5951d99de868be4385f21ea6c2b22f24
github.com/hashicorp/go-rootcerts@6bb64b370b90e7ef1fa532be9e591a81c3493e00
github.com/hashicorp/serf@d6574a5bb1226678d7010325fb6c985db20ee458
github.com/go-openapi/jsonpointer@779f45308c19820f1a69e9a4cd965f496e0da10f
gopkg.in/yaml.v2@cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b
```

I still don't know why it's doing that.

I thought it could be mismatch in dependency name, so I verified it all, but the only new import is `consulapi "github.com/hashicorp/consul/api"`.

I've copied the dependencies of the new project to `vendor/` and it builds flawlessly.

I do not know what else to do or try. It feels like it just wants to update all dependencies.

**Comment by VioletRainbows** [comment]
# Update
It looks like there are missing files in `vendor/`

For instance, `vendor/github.com/miekg/dns/idn/` doesn't have the folder `dnsutil` or `idn`, while the project has them (https://github.com/miekg/dns/tree/e78414ef75607394ad7d917824f07f381df2eafa)

So it does add my dependencies correctly, but also adds all the missing files.

**Comment by miekg** [comment]
Interesting... Smells like a dep bug. I did do an earlier update for just
that repo

**Comment by VioletRainbows** [comment]
# How to reproduce

Modify coredns.go
```golang
package main

//go:generate go run directives_generate.go

import "github.com/coredns/coredns/coremain"
import "github.com/pkg/errors"

func main() {
	coremain.Run()	
	_, err := fmt.Println("foo")
	if err != nil {
	   errors.Wrap(err, "fmt failed")
	}
}
```

Run `dep ensure`

You will see plenty of things added, but only our dependency has been modified in Goplg.lock.
```
$ diff Gopkg.lock 
diff: missing operand after 'Gopkg.lock'
diff: Try 'diff --help' for more information.
[mia@beta coredns]$ git diff Gopkg.lock 
diff --git a/Gopkg.lock b/Gopkg.lock
index cb513973..7dc0b10b 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -266,6 +266,12 @@
   version = "v0.1.1"
 
 [[projects]]
+  name = "github.com/pkg/errors"
+  packages = ["."]
+  revision = "645ef00459ed84a119197bfb8d8205042c6df63d"
+  version = "v0.8.0"
+
+[[projects]]
   name = "github.com/prometheus/client_golang"
   packages = ["prometheus"]
   revision = "c5b7fccd204277076155f10851dad72b76a49317"
@@ -376,6 +382,6 @@
 [solve-meta]
   analyzer-name = "dep"
   analyzer-version = 1
-  inputs-digest = "a59be89c7a92b81f951b47efd072c2af04fb66b4f2b7a780cadb7466559d0d6b"
+  inputs-digest = "3ca6a696ad5b81e513d3922449dcd0a9c4179db86216d1066890ffe990e9a1bf"
   solver-name = "gps-cdcl"
   solver-version = 1
```

You probably need the latest version of `dep`. Need to figure out that part this afternoon.

**Comment by VioletRainbows** [comment]
`dep prune` removes all the extra files as per https://github.com/golang/dep/issues/625 and https://github.com/golang/dep/issues/120

**Comment by yongtang** [comment]
See `Updating Dependencies` section in `CONTRIBUTING.md`:
https://github.com/coredns/coredns/blob/master/CONTRIBUTING.md

**Comment by sdboyer** [comment]
*ears perk up*

you folks encountering some bugs with dep? or did you get it sorted?

**Comment by VioletRainbows** [comment]
All is fixed with dep. I was just _very_ confused.

I'm ready for review (https://github.com/coredns/coredns/pull/722). I need to rebase, which I will do tomorrow.

**Comment by 0xdavidm** [comment]
Is this already merged? I see the PR closed

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/co..." ]
>Is this already merged? I see the PR closed

No, work is happening on this branch: https://github.com/coredns/coredns/tree/backend-work

/Miek

--
Miek Gieben

**Comment by 0xdavidm** [comment]
Thanks @miekg 
Do you think this will be ready by the upcoming release?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/co..." ]
>Thanks @miekg
>Do you think this will be ready by the upcoming release?

https://github.com/coredns/coredns/issues/784
I don't think this will be ready in time.

/Miek

--
Miek Gieben

**Comment by 0xdavidm** [comment]
OK, thanks for the effort!

**Comment by VioletRainbows** [comment]
Hello,

I'm a bit slow on development right now. I should pick it up in September in the worst of cases.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/co..." ]
>Hello,
>
>I'm a bit slow on development right now. I should pick it up in September in the worst of cases.

no problem, thanks for letting us know

**Comment by miekg** [comment]
Note: I'm also playing with adding etcd3 support, mostly to check if the Backend interface is actually sufficient (code only exists in local branch though and it not ready)

**Comment by VioletRainbows** [comment]
@miekg I though I would have more time on my hand, but it is not the case. 

I can not continue to develop this feature.

If someone else is available to continue, please feel free to take it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/co..." ]
>@miekg I though I would have more time on my hand, but it is not the case.
>
>I can not continue to develop this feature.
>
>If someone else is available to continue, please feel free to take it.

Ok, thanks for letting us know. Thanks for your efforts, I'll keep your branch 
alive for the time being maybe we can copy some code off of it.

Thanks for your help anyway!
