### ISSUE TITLE
All DNS lookups timeout if a proxy is unavailable.

### ISSUE THREAD

**Issue by davidnoyes** [coredns/coredns#715]
## Observed:
When multiple proxies are being used and one of those proxies is down, all further lookups will stall and likely timeout while the health check is being performed. Once the health check has timed out on its connection attempt (advertised that the "Health check probe failed") further DNS lookups can be made until the next health check cycle at which point lookups will stall again.

## Steps to reproduce:
The best way to reproduce is using AWS instances: 3 'primary' DNS servers running coredns and 1 'secondary' DNS server that will proxy on to the 3 primary DNS servers.
When set up and DNS requests to the secondary DNS server are working, stop one of the primary DNS servers.
This will result in the observed issue and the 'Health check probe' will fail with an i/o timeout error after about 30 seconds.

This can be reproduced in Docker, however, with the way that Docker networking works by manipulating routing tables, stopping containers results in a much shorter timeout of 'no route to host' but the issue can still be observed if DNS requests are quick enough.
Docker compose files are provided below.

docker-compose.yml
```
version: '3'
services:
  coredns-primary-1:
    container_name: coredns-primary-1
    image: coredns/coredns:latest
    networks:
      coredns:
        ipv4_address: 172.16.238.11
    volumes:
      - ./Corefile.primary:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile

  coredns-primary-2:
    container_name: coredns-primary-2
    image: coredns/coredns:latest
    networks:
      coredns:
        ipv4_address: 172.16.238.12
    volumes:
      - ./Corefile.primary:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile

  coredns-primary-3:
    container_name: coredns-primary-3
    image: coredns/coredns:latest
    networks:
      coredns:
        ipv4_address: 172.16.238.13
    volumes:
      - ./Corefile.primary:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile



  coredns-secondary:
    depends_on:
      - coredns-primary-1
      - coredns-primary-2
      - coredns-primary-3
    container_name: coredns-secondary
    image: coredns/coredns:latest
    networks:
      coredns:
        ipv4_address: 172.16.238.21
    volumes:
      - ./Corefile.secondary:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"



networks:
  coredns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
```

Corefile.primary
```
.:53 {
    log stdout
    errors stdout
    health
    proxy . 8.8.8.8:53
}
```

Corefile.secondary
```
.:53 {
    log stdout
    errors stdout
    health
    proxy . 172.16.238.11:53 172.16.238.12:53 172.16.238.13:53 {
        policy round_robin
        fail_timeout 2s
        health_check /health:8080 5s
    }
}
```

DNS query
`watch -n0.1 dig @127.0.0.1 -p 5353 www.google.com`

1. Create docker-compose.yml, Corefile.primary & Corefile.secondary from sections above.
2. `$ docker-compose up -d`
3. `$ docker-compose logs -f coredns-secondary`
4. `$ watch -n0.1 dig @127.0.0.1 -p 5353 www.google.com`
5. Observe DNS requests being made successfully and no health probe errors
6. `$ docker-compose down coredns-primary-1`
7. Observe DNS logging and requests made stop
8. Observe the 'dig watch' time out with "connection timed out; no servers could be reached"
9. Observe the coredns log give a Health probe warning with an i/o timeout, followed by a no route to host error.
10. Observe further DNS requests made and then stop again while health checks are made.

## Sample output
NB: see how the query times go from ms to secons and even minutes after the first health check failure
```
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.472044ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.365466ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.662211ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.627279ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 17.940205ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.571801ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.611922ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.59918ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.822186ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.868965ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.765292ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.73534ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.540029ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.53002ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.416474ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 18.41688ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.656563ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.618374ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.797649ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.748291ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.439936ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.826777ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.540117ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.686539ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.722528ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 18.107535ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.802333ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.705905ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.48139ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.485718ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.552703ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.518026ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.495093ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.559348ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:15 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.692718ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:15 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.933964ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:15 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.613493ms
coredns-secondary    | 2017/06/07 12:52:47 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: i/o timeout
coredns-secondary    | 2017/06/07 12:53:17 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: i/o timeout
coredns-secondary    | 2017/06/07 12:53:20 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: getsockopt: no route to host
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 55.382071728s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 20.042954969s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.042477166s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 30.157539215s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 15.042867535s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 25.157803108s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 35.15825646s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 1m5.38324071s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 40.26801258s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 4.935663729s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 1m0.383373069s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 50.268561952s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 45.268679181s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 19.665651ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 17.989096ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 20.683365ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.453694ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.99212ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 17.093094ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 18.686241ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.828698ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.64404ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.420952ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.586984ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.778113ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.684681ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.697002ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.56975ms
coredns-secondary    | 2017/06/07 12:53:23 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: getsockopt: no route to host
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:23 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 1.137351305s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:24 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.678236ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:24 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.705543ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:24 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.658709ms
```

## Misc
Even more interesting things happen if I use IPTables rules to block all communications with a primary DNS server. It looks like coredns locks up all together with no sign of a timeout.
`iptables -A DOCKER -p all -d 172.16.238.11 -j DROP`

**Comment by miekg** [comment]
Thanks for this detailed bug report! With "all further lookups will stall and likely timeout while the health check is being performed", you mean that queries to should go to the healthy DNS are blocked as well?

**Comment by davidnoyes** [comment]
Yes. I'm afraid nothing gets routed to the healthy servers while waiting for the health check to timeout.
I suspect the culprit may be the mutex locks on lookups and health checks:
https://github.com/coredns/coredns/blob/3b5b6a233fc669dfb47a6dc4eb8899c3e992cc32/middleware/proxy/upstream.go#L96

and

https://github.com/coredns/coredns/blob/3b5b6a233fc669dfb47a6dc4eb8899c3e992cc32/middleware/proxy/upstream.go#L273

**Comment by miekg** [comment]
Hmmm, those should be per upstream, but obviously not.

Have 2 upstreams and one proxying coredns can also easily be captured in a test case. I'll work on that first.

**Comment by miekg** [comment]
I couldn't work on it tonight, but the sharing the mutex by different upstream makes for a good explanation. Pushing that down to each upstream host (or at least investigating of that is the issue should not be too hard).

**Comment by miekg** [comment]
Think this is because of singleInflight to suppress identical outstanding queries.

**Comment by miekg** [comment]
*confirmed*

**Comment by davidnoyes** [comment]
Hey Miek, thanks for your efforts on this.
I've just pulled the changes to master branch, edited coremain/version.go to change the version to "master", and done a `make -f Makefile.release docker-build`. I can see from the logs that it's running the new version:
```
coredns-secondary    | .:53
coredns-secondary    | 2017/06/09 09:13:42 [INFO] CoreDNS-master
coredns-secondary    | CoreDNS-master
```
However, I'm still seeing the same symptoms I described above when I stop one of the primary instances.
```
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:16:44 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.588579ms
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:16:45 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.537728ms
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:16:45 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.511627ms
coredns-secondary    | 2017/06/09 09:17:17 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: i/o timeout
coredns-secondary    | 2017/06/09 09:17:20 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: getsockopt: no route to host
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.673845359s
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 4.566771201s
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 29.781739422s
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 14.675185527s
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 19.681715725s
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 34.789524738s
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 24.790481602s
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 19.432757ms
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.393987ms
coredns-secondary    | 172.16.238.1 - [09/Jun/2017:09:17:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.664278ms
```

When you get a mo, would you be able to reverify for me please? Many thanks again.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] All DNS looku..." ]
>Hey Miek, thanks for your efforts on this.
>I've just pulled the changes to master branch, edited coremain/version.go to change the version to "master", and done a `make -f Makefile.release docker-build`. I can see from the logs that it's running the new version:
>```
>coredns-secondary    | .:53
>coredns-secondary    | 2017/06/09 09:13:42 [INFO] CoreDNS-master
>coredns-secondary    | CoreDNS-master
>```
>However, I'm still seeing the same symptoms I described above when I stop one of the primary instances. When you get a mo, would you be able to reverify for me please? Many thanks again.

Interesting and thanks for testing! I don't have an immediate explanation,
except that the PR we merged should have made a difference.

The test I added *should* reflect what you are seeing, but obviously not...

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
From the current master branch.

I have 3 CoreDNSs two backends, 1 proxy:
1. backend1: `Corefile1`:
   ~~~
   :1053 {
    whoami
    log
   }
   ~~~
2. backend2: `Corefile2`:
   ~~~
   :1054 {
    whoami
    log
   }
   ~~~
3. proxy: `Corefile`:
   ~~~
   .:1052 {
    proxy . 127.0.0.1:1053 127.0.0.1:1054
    log
   }
   ~~~

Start them all:
1. `~/g/src/github.com/coredns/coredns/coredns -conf ~/Corefile1 -log`
2.  `~/g/src/github.com/coredns/coredns/coredns -conf ~/Corefile2 -log`
3. ` ./coredns -log`

Have a `dig` loop query the proxy on 1052: `for i in {0..10000}; do dig @localhost -p 1052 a miek.nl; done`
* All three consoles spew logs of queries
* Mid loop I control-C one of the backends - nothing happens, the loop continues to work and logs are spewed in the working consoles
* Restarting the control-c-ed CoreDNS instances will make it get queries after the default timeout.

I.e. I can't reproduce this in a simpler setup....

**Comment by davidnoyes** [comment]
Ahh I think the difference is the IP address is still contactable.
I found that on my AWS instances, when stopping the coredns service the proxy was happy and detected that it was down and still served DNS queries. However, if I stopped/terminated the instance that the service was on, then I would see the issues in the bug report.

I'm trying to reproduce this with your example at the moment ~~but I'm currently having troubles trying to get coredns to run on a specific interface. Is there a way of defining that in the config?~~

Edit: I just discovered the Bind middleware (I always assumed it was something to do with BIND DNS configs and ignored it :) )

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] All DNS looku..." ]
>Ahh I think the difference is the IP address is still contactable.
>I found that on my AWS instances, when stopping the coredns service the proxy was happy and detected that it was down and still served DNS queries. However, if I stopped/terminated the instance that the service was on, then I would see the issues in the bug report.
>
>I'm trying to reproduce this with your example at the moment but I'm currently having troubles trying to get coredns to run on a specific interface. Is there a way of defining that in the config?

Yes, use the 'bind' "middleware"

**Comment by ghostflame** [comment]
Hi miekg,

I work with raspberrypython.  Thanks for jumping on this so quick.

What's killing us is the TCP syn timeout - which is long, and not trivially changed - that occurs when the remote host is absent.  I think that's why localhost testing is hard to do, because the local kernel cannot help but be aware of the proxy's network status.  If you are getting an ICMP reply back quickly, you can't easily reproduce the problem.

We kicked around a potential approach, that rather than a health bool to use an 'alive-until' timestamp that was constantly updated into the future by a successful health check.

In pseudocode:

Health check:
    Every intv seconds;
        ts = now()
        if health-check-ok()
            svr->healthy_until = ts + ( 2 * intv )
        else
            svr->healthy_until = 0

Lookup code:
     Select servers where ( svr->healthy_until > now() && (failure-count logic) )

The 2*intv seemed like a reasonable choice, but I defer to you for better logic.

This has the happy consequence that even if the health check gets stuck in minutes of tcp timeout because the proxy is gone (it was a terminated AWS instance in this case, so looooong SYN timeout rather than any hope of a quick ICMP reply), the server is marked as dead within a much shorter time because its alive-until time passes.  And if the health check ever takes double the interval time, we probably *want* that server marked dead.

A rapid failed health check (as in where the process is down, and the host reponds with unreachable at once) marks it dead at once, and the very next lookup perceives that.

The failure count logic as perceived by lookup code would remain more or less unchanged.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] All DNS looku..." ]
>A rapid failed health check (as in where the process is down, and the host reponds with unreachable at once) marks it dead at once, and the very next lookup perceives that.
>
>The failure count logic as perceived by lookup code would remain more or less unchanged.

sgtm - can you pour these words in to PR?

Thanks!

/Miek

--
Miek Gieben

**Comment by davidnoyes** [comment]
Ok I can reproduce it without docker but separate interfaces/hosts is the key.
```
$ git log
2ec96e0bb53e260f98935813818441620245a641 remove unused funcs (#724)
92dd947c51e7c6b56276615507af9447abb377b8 middleware/hosts for /etc/hosts parsing (#695)
990460ee7caffe752167b5307d7a5bffab37da61 middleware/file: don't reload zone when SOA isn't changed (#707)
1c45e262f5cf20aaa950f8e8d86248cbce6ae120 middleware/proxy: remove singleinflight from dns (#717)
36396e94ab738439aa9cfc0fe9ed5db2fca883d3 typo Recode->Rcode
```

### Add new virtual interfaces
```
sudo ip addr add 10.200.0.1/32 dev eno1 &&\
sudo ip addr add 10.200.0.2/32 dev eno1 &&\
sudo ip addr add 10.200.0.3/32 dev eno1
```

### Corefile1
```
.:5353 {
 bind 10.200.0.1
 log
 whoami
 health 10.200.0.1:8080
}
```

### Corefile2
```
.:5353 {
 bind 10.200.0.2
 log
 whoami
 health 10.200.0.2:8080
}
```

### CorefileProxy
```
.:5353 {
 bind 10.200.0.3
 proxy . 10.200.0.1:5353 10.200.0.2:5353 {
    #health_check /health:8080
 }
 log
}
```

### Run the 3 instances of CoreDNS
```
coredns -conf Corefile1
coredns -conf Corefile2
coredns -conf CorefileProxy
```

### Ctrl-C the instance of Corefile1
The proxy works fine as you suggested, there are no blocks

### Simulate the host going down / IP being uncontactable
sudo ip addr del 10.200.0.1/32 dev eno1

### Notice a small blip in lookup response and all lookups are blocked
```
10.200.0.3 - [09/Jun/2017:12:58:26 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 234.811µs
10.200.0.3 - [09/Jun/2017:12:58:26 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 333.609µs
10.200.0.3 - [09/Jun/2017:12:58:32 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 5.000664463s
10.200.0.3 - [09/Jun/2017:12:58:32 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 504.76µs
10.200.0.3 - [09/Jun/2017:12:58:32 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 256.566µs
```

### The problem really becomes noticeable when health checks are brought into the mix (uncomment the health check in the proxy). In fact it seems to have stopped routing anything at all to the 2nd server because we are not involving Dockers change to routing tables (no route to host).
```
10.200.0.3 - [09/Jun/2017:13:07:02 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 277.708µs
10.200.0.3 - [09/Jun/2017:13:07:02 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 265.72µs
10.200.0.3 - [09/Jun/2017:13:07:02 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 245.021µs
10.200.0.3 - [09/Jun/2017:13:07:02 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 287.279µs
10.200.0.3 - [09/Jun/2017:13:07:03 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 313.34µs
10.200.0.3 - [09/Jun/2017:13:07:03 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 252.136µs
10.200.0.3 - [09/Jun/2017:13:07:03 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 295.544µs
2017/06/09 13:07:34 [WARNING] Health check probe failed: Get http://10.200.0.1:8080/health: dial tcp 10.200.0.1:8080: i/o timeout
2017/06/09 13:08:04 [WARNING] Health check probe failed: Get http://10.200.0.1:8080/health: dial tcp 10.200.0.1:8080: i/o timeout
2017/06/09 13:08:34 [WARNING] Health check probe failed: Get http://10.200.0.1:8080/health: dial tcp 10.200.0.1:8080: i/o timeout
2017/06/09 13:09:04 [WARNING] Health check probe failed: Get http://10.200.0.1:8080/health: dial tcp 10.200.0.1:8080: i/o timeout
```

**Comment by miekg** [comment]
This looks pretty impossible to capture in a test :(

Can you at least make sure any PR works in this setup? Thanks!

[ Quoting <notifications@github.com> in "Re: [coredns/coredns] All DNS looku..." ]
>### Notice a small blip in lookup response and all lookups are blocked
>```
>10.200.0.3 - [09/Jun/2017:12:58:26 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 234.811µs
>10.200.0.3 - [09/Jun/2017:12:58:26 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 333.609µs
>10.200.0.3 - [09/Jun/2017:12:58:32 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 5.000664463s
>10.200.0.3 - [09/Jun/2017:12:58:32 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 504.76µs
>10.200.0.3 - [09/Jun/2017:12:58:32 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 256.566µs
>```
>
>### The problem really becomes noticeable when health checks are brought into the mix (uncomment the health check in the proxy). In fact it seems to have stopped routing anything at all to the 2nd server because we are not involving Dockers change to routing tables (no route to host).
>```
>10.200.0.3 - [09/Jun/2017:13:07:02 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 277.708µs
>10.200.0.3 - [09/Jun/2017:13:07:02 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 265.72µs
>10.200.0.3 - [09/Jun/2017:13:07:02 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 245.021µs
>10.200.0.3 - [09/Jun/2017:13:07:02 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 287.279µs
>10.200.0.3 - [09/Jun/2017:13:07:03 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 313.34µs
>10.200.0.3 - [09/Jun/2017:13:07:03 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 252.136µs
>10.200.0.3 - [09/Jun/2017:13:07:03 +0100] "A IN example.org. udp 41 false 4096" NOERROR 82 295.544µs
>2017/06/09 13:07:34 [WARNING] Health check probe failed: Get http://10.200.0.1:8080/health: dial tcp 10.200.0.1:8080: i/o timeout
>2017/06/09 13:08:04 [WARNING] Health check probe failed: Get http://10.200.0.1:8080/health: dial tcp 10.200.0.1:8080: i/o timeout
>2017/06/09 13:08:34 [WARNING] Health check probe failed: Get http://10.200.0.1:8080/health: dial tcp 10.200.0.1:8080: i/o timeout
>2017/06/09 13:09:04 [WARNING] Health check probe failed: Get http://10.200.0.1:8080/health: dial tcp 10.200.0.1:8080: i/o timeout
>```

This still stops *all* forwarding?

**Comment by davidnoyes** [comment]
#749

**Comment by davidnoyes** [comment]
Can this issue please be reopened and the above pull request (#749) reviewed?
Thanks!

**Comment by miekg** [comment]
PR was merged.
