### ISSUE TITLE
possible to block DNS types

### ISSUE THREAD

**Issue by ookangzheng** [coredns/coredns#725]
Is it possible block specified DNS type such as ANY, TXT request
like this project https://github.com/shawn1m/overture
Keyword: RejectQtype

Thanks in advanced

**Comment by miekg** [comment]
No we don't have that capability yet. But you can use the rewrite middleware for some of this.

Also see: #499 and #178

**Comment by johnbelamaric** [comment]
It's a more complex solution but you could do it with our out-of-tree middleware and policy engine https://github.com/infobloxopen/themis
