### ISSUE TITLE
Override dns entries

### ISSUE THREAD

**Issue by timbrd** [coredns/coredns#732]
I'd like to override a few dns entries of an existing domain locally and forward requests to an upstream dns server if the entry couldn't be found locally. So this is my configuration:

```
# Corefile
.:53 {
    file /tmp/google.com google.com
    proxy . 8.8.8.8:53
    log stdout
    errors stdout
}
```

```
# /tmp/google.com
$TTL         1M
$ORIGIN      google.com

www          IN  A      192.168.0.14
mail         IN  A      192.168.0.15
imap         IN  CNAME  mail.google.com
```

When querying coredns for www.google.com it resolves it correctly and answers the request with 192.168.118.0.14. Unfortunately coredns is not able to forward any unknown requests to 8.8.8.8 though:

```
13/Jun/2017:10:35:47 +0200 [PANIC abc.google.com. A] coredns/vendor/github.com/miekg/dns/ztypes.go:539 - runtime error: invalid memory address or nil pointer dereference
```

Any hints what I am missing or what I have done wrong?

Edit: I'm running CoreDNS-007

**Comment by johnbelamaric** [comment]
1 - It should never panic, that's a bug;
2 - in order to have multiple backend middleware handle the same domain, you need to use the fallthrough option. I happened to have just put out a blog on that:

https://blog.coredns.io/2017/06/08/how-queries-are-processed-in-coredns/

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Override dns ..." ]
>1 - It should never panic, that's a bug;

Just checked. Indeed crashes with 007, *not* with the current master branch,
there you get SERVFAIL.

>2 - in order to have multiple backend middleware handle the same domain, you need to use the fallthrough option. I happened to have just put out a blog on that:
>
>https://blog.coredns.io/2017/06/08/how-queries-are-processed-in-coredns/

This is indeed what is happening.

What you might want is the new *hosts* middleware:
https://github.com/coredns/coredns/tree/master/middleware/hosts

/Miek

--
Miek Gieben

**Comment by timbrd** [comment]
Thanks for the clarification. 

@johnbelamaric I have read your blog post before and was trying to test the fallthrough option, but wasn't able to due to the bug.

I'll try your suggestions once there is another release.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Override dns ..." ]
>Thanks for the clarification.
>
>@johnbelamaric I have read your blog post before and was trying to test the fallthrough option, but wasn't able to due to the bug.

Also *file* doesn't support *fallthrough* - should probably have some discussion
if all middleware should support that option.

>I'll try your suggestions once there is another release.

008 should out soonish.

/Miek

--
Miek Gieben

**Comment by fturib** [comment]
Hi Miek, for information, John is on vacation for  12 and 13th of June. Back on 14th for 008 release.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Override dns ..." ]
>Hi Miek, for information, John is on vacation for  12 and 13th of June. Back on 14th for 008 release.

ahhhhh! :)

**Comment by timbrd** [comment]
Cross-compiling for arm was easier than I thought. I have tested the current master branch and indeed, it fails with a servfail as expected.

I'm confused though that coredns answers with servfail even for queries which should find a valid entry.

```
# Corefile
.:53 {
    file /tmp/google.com google.com
    log stdout
    errors stdout
}
```

```
# /tmp/google.com
$TTL         1M
$ORIGIN      google.com.

www          IN  A      192.168.0.14
mail         IN  A      192.168.0.15
imap         IN  CNAME  mail.google.com
```

```
192.168.118.132 - [13/Jun/2017:19:28:48 +0200] "A IN abc.google.com. udp 32 false 512" SERVFAIL 32 702.565µs
192.168.118.132 - [13/Jun/2017:19:29:08 +0200] "A IN www.google.com. udp 32 false 512" SERVFAIL 32 667.399µs
```

Is my configuration invalid?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Override dns ..." ]
>```
># /tmp/google.com
>$TTL         1M
>$ORIGIN      google.com.
>
>www          IN  A      192.168.0.14
>mail         IN  A      192.168.0.15
>imap         IN  CNAME  mail.google.com
>```
>
>```
>192.168.118.132 - [13/Jun/2017:19:28:48 +0200] "A IN abc.google.com. udp 32 false 512" SERVFAIL 32 702.565µs
>192.168.118.132 - [13/Jun/2017:19:29:08 +0200] "A IN www.google.com. udp 32 false 512" SERVFAIL 32 667.399µs
>```
>
>Is my configuration invalid?

Seems we are quite liberal in zone parsing and allow zones without a SOA, or at
least don't tell you about it. I like the garbage in, garbage out approach, but
not having a SOA might actually be considered a syntax error....

/Miek

--
Miek Gieben
