### ISSUE TITLE
parallelize A/AAAA lookups

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#737]
We should look into the possibility to do parallel A and AAAA lookups. I.e. we see a lookup for an A record and then we immediately lunch a go-routine that looks up the AAAA for that name, which we then put in the cache. So when the client then comes the AAAA or NXDOMAIN/NODATA is already there.

**Comment by miekg** [comment]
Might be overkill if we also doing #747

**Comment by chrisohaver** [comment]
I think this is a good idea, even with #747

**Comment by miekg** [comment]
please re-open if we thing someone is working on it.
