### ISSUE TITLE
middleware/kubernetes: Preemptive search path lookups

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#747]
**Problem**:

A known issue with kube-dns and how K8s works is the long DNS search path and high ”ndots” in /etc/resolv.conf. https://github.com/kubernetes/kubernetes/issues/33554

For example, search path in a pod as dictated by the pod's dns policy is:
```
namespace.svc.cluster.local
svc.cluster.local
cluster.local
mydomain.com
```

If you try to lookup ”google.com” you will end up with queries:

```
google.com.namespace.svc.cluster.local.
google.com.svc.cluster.local.
google.com.cluster.local.
google.com.mydomain.com.
google.com.
```

This means that for every query of a host outside the cluster, the client has to make 5 queries.

**Proposed Solution**:

For queries from pods in the cluster, iterate on the search path in coredns, returning the first successful lookup back to the client.  This allows the client to get the answer in one query, instead of five. 

The condition for doing the preemptive lookups on an incoming question would have to meet all of the following...

- the incoming question would otherwise result in an NXDOMAIN (e.g. it doesn't match a service)
- the source is a pod in the kubernetes cluster
- the question ends with `namespace.svc.cluster.local.` where `namespace` is the namespace of the pod, and `cluster.local` is the zone

If these conditions are met, then the kubernetes middleware would strip the search path from the question, and try the remaining search paths until an answer is found.

**Comment by miekg** [comment]
Would there be a way to pull the proposed hackery into its own middleware?

**Comment by johnbelamaric** [comment]
It needs the pod watch that we put in for `pods verified` so it's probably not ideal to do that. It definitely though can be optionally enabled.

**Comment by johnbelamaric** [comment]
Or are you saying so that it can be used in non-k8s cases?

**Comment by miekg** [comment]
Reuse maybe. More from code complicity standpoint.

**Comment by miekg** [comment]
Should we call it *autopath* (like the name, but it is a bit non descriptive) or maybe *serverpath*?  *serversearch*, *autosearch*?
