### ISSUE TITLE
codecov should not fail the whole build

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#752]
Codecov is useful, but is should not fail the whole build (in github) when it fails.

@yongtang is that possible?

**Comment by yongtang** [comment]
The issue is fixed in #754. Now codecov is only considered as failure if coverage is less than 40%.

**Comment by yongtang** [comment]
Let me re-open it. The `codecov/project` entry has been fixed. But `codecov/patch` still need further fix.

**Comment by yongtang** [comment]
#752 should be fixed by PR #758. We will only see two status report for each PR: one is the TravisCI, another is `codecov/project` from CodeCov. That should address the confusion we had before.
