### ISSUE TITLE
CoreDNS 009 tracking bug

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#756]
Tracking bug the the 009 release

**Comment by miekg** [comment]
@johnbelamaric  @nwoods3 issue for tracking the 009 release.

I want to release pretty quicky, because secondary serving is broken in 008 and I just fixed a race in the caching middleware. We're doing one major k8s feature and that about it.

**Comment by johnbelamaric** [comment]
Sure. I moved some lower priority stuff out to 010. There a still a few in there you should take a look at.

**Comment by miekg** [comment]
All 009 issues have been fixed, I'll brush up the release notes and then we can release end of this week, or early next week.

**Comment by miekg** [comment]
release has been tagged and binaries have been built. Will push out the website and tweet later this evening (BST)

**Comment by miekg** [comment]
Done here - @johnbelamaric can you push 009 to Docker hub? I've literally de-installed Docker everywhere (yes, I can install it, but I've had/seen too many issue with it - so install; do coredns; deinstall - it too much effort ...)

**Comment by johnbelamaric** [comment]
Sure. Should be able to later today.

**Comment by johnbelamaric** [comment]
Done: https://hub.docker.com/r/coredns/coredns/tags/

**Comment by miekg** [comment]
awesome thank you.

(There are tools that can do this without docker 'buildah' seems a newer one)
