### ISSUE TITLE
new middleware: autopath

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#760]
Generalize the kubernetes autopath into a separate middleware.  The kubernetes autopath feature is tightly integrated and dependent on the kubernetes environment (particularly that the first search in the path is dynamic based on the namespace of the querying client's pod).  But the general idea of server-side path search could be pulled out into a separate middleware.

Per @miekg's suggestion in pr #750 ...
> ... this functionality is useful outside kubernetes - if only just for testing. If the server shares my /etc/resolv.conf I could just let it shortcut the search path. Would be superhandy for debugging ...

**Comment by miekg** [comment]
The idea would be that you can then test the CNAME handoff handling, we *could* maybe include it in the erratic middleware and put the duplicated code in middleware/pkg/autopath

**Comment by miekg** [comment]
Not sure if this should be a full blown middleware, pondering putting it in *erratic*

**Comment by miekg** [comment]
I think this *can* be a standalone middleware:

~~~
suffix := first-search
start:
   call-next-middleware-for-answer with suffix
   suffix = next-search
   if-nxdomain goto start
reply:
   modify answer; insert CNAME(s)
done:
~~~

**Comment by miekg** [comment]
Maybe this is too much hassle and messes too much with the middleware layering we have
