### ISSUE TITLE
middleware/mirror: new middleware

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#773]
Idea for new middleware (basically in the why not category); one that just mirrors the dns queries to another target (and drop the response).

**Comment by 2buisson** [comment]
Not sure if the initiator's firewall is going to accept the mirror response.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/mi..." ]
>Not sure if the initiator's firewall is going to accept the mirror response.

response should be ignored from the mirrored endpoint.

/Miek

--
Miek Gieben
