### ISSUE TITLE
wildcard A records *.domain. IN A not respecting more explicit entries

### ISSUE THREAD

**Issue by prologic** [coredns/coredns#776]
Not sure if this is a bug or intended behavior however since recently switching to CoreDNS I've found wildcard entries are returned in preference to more specific entries: Example:

```
*.domain. IN A 127.0.0.1

foo IN A 127.0.0.2
```

Doing a lookup on `foo` always returns `127.0.0.1` :(

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] wildcard A record..." ]
>Not sure if this is a bug or intended behavior however since recently switching to CoreDNS I've found wildcard entries are returned in preference to more specific entries: Example:
>
>```
>*.domain. IN A 127.0.0.1
>
>foo IN A 127.0.0.2
>```
>
>Doing a lookup on `foo` always returns `127.0.0.1` :(

No, that could be a bug - can you share some more data and how to trigger?

**Comment by prologic** [comment]
Sure!

```#!bash
git clone https://github.com/prologic/coredns-776
cd coredns#776
coredns -conf ./Corefile
```

And...

```#!bash
~/coredns#776
 (master) 0
$ dig @localhost -p 1053 foo.mydomain.com +short
127.0.0.2
```

**Comment by prologic** [comment]
=> https://github.com/prologic/coredns-776

**Comment by miekg** [comment]
Wildcard at the apex, yeah that will be a bug. IIRC I special case apex
lookups. May not be too difficult to fix though if we want to whack it
yourself.

Thanks for the details. Makes adding a testcase super easy.

**Comment by prologic** [comment]
Err:

```#!bash
git cone https://github.com/prologic/coredns-776
```

Can have a `#` in a loca path but not a remote path :) Thanks Github!

**Comment by prologic** [comment]
This is horribly breaking my local DNS I guess so yeah I can give it a go if you can help point me to where this logic is roughly in code? :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard A re..." ]
>This is horribly breaking my local DNS I guess so yeah I can give it a go if you can help point me to where this logic is roughly in code? :)

https://github.com/coredns/coredns/blob/master/middleware/file/lookup.go#L81

is the main lookup code and tree/*.go in that dir probably.

/Miek

--
Miek Gieben

**Comment by prologic** [comment]
I tried to have a go at fixing this but unfortunately I'd have to spend more time with the codebase to really get a good solution out. Perhaps someone more familiar can help fix this issue?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard A re..." ]
>I tried to have a go at fixing this but unfortunately I'd have to spend more time with the codebase to really get a good solution out. Perhaps someone more familiar can help fix this issue?

I haven't found time, but I'm planning to fix this soon.
(It is just that this code is tricky and a second pair of eyes would def. help)

**Comment by miekg** [comment]
It's not a wildcard issue... you don't fully qualify your $ORIGIN (not closing dot), so the zone's origin from the config gets added leading to `foo.mydomain.com.mydomain.com.`
Adding a closing dot to $ORIGIN fixes your problem.

**Comment by miekg** [comment]
This is basically WAI, and a non relative $ORIGIN is even allowed, the parser should then append the previous set $ORIGIN to it... So I'm not sure what I can do to make this clearer; barfing warnings seems overkill.

Adding axfr and transferring shows the problem:
~~~
.:1053 {
    file db.mydomain.com mydomain.com {
        transfer to *
    }
    health
    errors stdout
    log stdout
}
~~~

~~~
% dig @localhost -p 1053 axfr mydomain.com

; <<>> DiG 9.10.3-P4-Debian <<>> @localhost -p 1053 axfr mydomain.com
; (2 servers found)
;; global options: +cmd
mydomain.com.mydomain.com. 60	IN	SOA	mydomain.com. admin.mydomain.com. 2017071600 14400 3600 604800 14400
*.mydomain.com.		60	IN	A	127.0.0.2
mydomain.com.mydomain.com. 60	IN	A	127.0.0.1
foo.mydomain.com.mydomain.com. 60 IN	A	127.0.0.3
mydomain.com.mydomain.com. 60	IN	SOA	mydomain.com. admin.mydomain.com. 2017071600 14400 3600 604800 14400
;; Query time: 0 msec
;; SERVER: ::1#1053(::1)
;; WHEN: Fri Jul 21 10:43:11 UTC 2017
;; XFR size: 5 records (messages 1, bytes 328)
~~~

**Comment by miekg** [comment]
Closing this here. Please open a new issue if you want to discuss `$ORIGIN`

**Comment by prologic** [comment]
Oh dear :/ I'm sorry must have missed that!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Confirmed that fixed the issue! How embarrassing :D


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard A re..." ]
>Confirmed that fixed the issue! How embarrassing :D

No worries, glad it is solved. (And that my lookup code works :) )

**Comment by prologic** [comment]
I have a followup question :)

Should I expect the following to work?

```
$TTL 60
$ORIGIN mydomain.com.
@           IN  SOA  mydomain.com. admin.mydomain.com. (
                     2017072300 ; Serial
                     4H         ; Refresh
                     1H         ; Retry
                     7D         ; Expire
                     4H )       ; Negative Cache TTL


@           IN  A    127.0.0.1

*.mydomain.com. IN  A    127.0.0.2
*.intern.mydomain.com IN A 127.0.0.3

foo         IN  A    127.0.0.4
```

```#!bash
$ dig @localhost -p 1053 foo.mydomain.com +short
127.0.0.4

$ dig @localhost -p 1053 bar.mydomain.com +short
127.0.0.2
```

Which work fine; but this does not:

```#!bash
$ dig @localhost -p 1053 bar.intern.mydomain.com +short
127.0.0.2
```

It would seem the other wildcard entry is not respected?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard A re..." ]
>I have a followup question :)
>
>Should I expect the following to work?
>
>```
>$TTL 60
>$ORIGIN mydomain.com.
>@           IN  SOA  mydomain.com. admin.mydomain.com. (
>                     2017072300 ; Serial
>                     4H         ; Refresh
>                     1H         ; Retry
>                     7D         ; Expire
>                     4H )       ; Negative Cache TTL
>
>
>@           IN  A    127.0.0.1
>
>*.mydomain.com. IN  A    127.0.0.2
>*.intern.mydomain.com IN A 127.0.0.3
>
>foo         IN  A    127.0.0.4
>```
>
>```#!bash
>$ dig @localhost -p 1053 foo.mydomain.com +short
>127.0.0.4
>
>$ dig @localhost -p 1053 bar.mydomain.com +short
>127.0.0.2
>```
>
>Which work fine; but this does not:
>
>```#!bash
>$ dig @localhost -p 1053 bar.intern.mydomain.com +short
>127.0.0.2
>```
>
>It would seem the other wildcard entry is not respected?

`*.intern.mydomain.com IN A 127.0.0.3` does not has closing dot, so the origin 
gets added.

(haven't looked closely yet if there is an actual bug here)

**Comment by prologic** [comment]
Yes you are right about the missing `.` :/ I keep missing that :/

Even so with that corrected I cannot get a `anything.intern.mydomain.com` to resolve to `127.0.0.3`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] wildcard A re..." ]
>Yes you are right about the missing `.` :/ I keep missing that :/
>
>Even so with that corrected I cannot get a `anything.intern.mydomain.com` to resolve to `127.0.0.3`

I'll take a look. But why would you even do this? You have this running in prod?
(anyway; good corner cases are welcome - we should handle them correctly).

/Miek

--
Miek Gieben

**Comment by prologic** [comment]
Is it unreasonable to expect another wildcard entry to have a higher order in the tree? Use-case here is `*.mydomain.com` to expose/host a bunch of external facing resources and `*.intern.mydomain.com` to only expose internal resources internally facing.

**Comment by miekg** [comment]
Yes, fails. See https://github.com/coredns/coredns/pull/787

**Comment by prologic** [comment]
Thanks!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
