### ISSUE TITLE
middleware/kubernetes: Document two autopath issues

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#778]
**Partial middleware chain execution vs full** - Autopath search path execution passes non-kubernetes searches to next middleware.  This excludes those queries from processing by any middleware occurring upstream of kubernetes in the chain.  However if the client was executing these, then each query would be passed through the whole chain.

**Cache race condition** - It's possible for pods in different namespaces to get a different answer for the same question.  This causes a problem with cache - a pod can get another pods cached result.  

Example:

pod in ns ns1: `host google.com` receives ...
  `google.com.ns1.zone. IN CNAME google.com.`
  `google.com IN A 1.2.3.4`

pod in ns ns2: `host google.com.ns1.zone.` receives cached result…
  `google.com.ns1.zone. IN CNAME google.com.`
  `google.com IN A 1.2.3.4`

but should have received NXDOMAIN.

**Comment by miekg** [comment]
**Cache race** might be solvable by using the source IP as a key as well - but that is a pretty large change. (EDNS subnet needs something similar).

**Comment by chrisohaver** [comment]
> Cache race might be solvable by using the source IP as a key as well ...

Yes, it would, but also would increase significantly the number of cache entries.

**Comment by johnbelamaric** [comment]
I think if we go that route, we should give the user some control over the cache keys (source IP, some EDNS option, etc.)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>> Cache race might be solvable by using the source IP as a key as well ...
>
>Yes, it would, but also would increase significantly the number of cache entries.

Still trying to fill in some knowledge caps.

What triggers a different search path between pods?

**Comment by johnbelamaric** [comment]
The pod's namespace and `dnsPolicy` setting. We only apply the optimization for the `clusterFirst` policy. So, we could key the cache by namespace in this case (but the cache wouldn't know about that...).

**Comment by johnbelamaric** [comment]
At the risk of sounding like a broken record, when we integrate policy we really want a policy-aware cache. This could mean having a middleware before `cache` that tags the request with some relevant policy data.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>At the risk of sounding like a broken record, when we integrate policy we really want a policy-aware cache. This could mean having a middleware before `cache` that tags the request with some relevant policy data.

that would be useful in any case.

**Comment by chrisohaver** [comment]
> We only apply the optimization for the _clusterFirst_ policy.

Practically speaking yes. But technically we apply the optimization to any pod that makes a query in its own namespace. We assume that any pod using using _default_ dns policy will not be using coredns as its nameserver.  Or, in other words, that k8s nodes will not be configured to use the coredns service as their nameserver.  I believe this to be a safe assumption.  If it proves not to be, we can add the check.

**Comment by chrisohaver** [comment]
I believe the "Partial middleware chain execution vs full" issue is no longer a problem in the new autopath refactor.
