### ISSUE TITLE
middleware/kubernetes: AAAA NXDOMAIN response

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#779]
In k8s middleware `AAAA` queries always return an `NXDOMAIN` response.  The response should instead be conditional...

- If a service exists with that name, but there is not a `AAAA` record, the return should be a `NOERROR` with no answers.  `AAAA` is not supported in K8s yet, so currently there will never be a `AAAA` record.

- If a service exists doesn't exist with that name, the return should be a `NXDOMAIN`.

**Comment by johnbelamaric** [comment]
I think this is confusing some resolvers, causing them to be unable to lookup the name. They see the `NXDOMAIN` from the `AAAA` and return an error, even though they got a valid `A` record. I believe I am seeing this issue with `nginx`.

**Comment by johnbelamaric** [comment]
@miekg I think we need an immediate release to fix this, if the problem is really there.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>@miekg I think we need an immediate release to fix this, if the problem is really there.

fine with me, not bound to do monthly releases.

But would be good to get some other fixing in as well, apex wildcard for 
instance: #776

/Miek

--
Miek Gieben

**Comment by johnbelamaric** [comment]
The `nginx` issue is actually with hosts middleware #781 I believe, not with this one. For some reason it doesn't happen in my particular use case with the K8s ones but only hosts - my nginx config must be a little different for the different domains. Anyway, I imagine it could still confuse some resolvers, and there is a cosmetic issue when using `host` on the command line (spitting out `NXDOMAIN` as well as an IP). So I still think a new release very shortly is a good idea.
