### ISSUE TITLE
middleware/hosts: AAAA responses

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#781]
For a name that has an `A` record, but not an `AAAA` record, If the name is queried for the `AAAA` record, hosts middleware should return a `NOERROR` with 0 answers.  Currently it returns `NXDOMAIN`, even if there exists an `A` record.

**Comment by miekg** [comment]
as said in the other code review, should also double check other types. Does MX give back nodata as well?

**Comment by pmoroney** [comment]
Good point, I'll verify

**Comment by chrisohaver** [comment]
Can we close this one?

**Comment by pmoroney** [comment]
Yes, #782 fixes this and has been merged.
