### ISSUE TITLE
CoreDNS 010 Tracking

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#784]
@johnbelamaric @nwoods3 issue for tracking the 010 release.

**Comment by miekg** [comment]
@johnbelamaric I'm fine with you kicking of a release

**Comment by johnbelamaric** [comment]
Ok, probably this weekend or early next week.

**Comment by johnbelamaric** [comment]
Planning on releasing tomorrow. Last call for any bug fixes.

**Comment by johnbelamaric** [comment]
Released! Blog entry PR is  https://github.com/coredns/coredns.io/pull/15

**Comment by miekg** [comment]
Lgtm. Note that you now also need to update data/coredns.toml and I've
retroactively changed to last community bit of the notes to just point to
our community page.

**Comment by johnbelamaric** [comment]
Ok, will do.
