### ISSUE TITLE
Docker Stackfile / Service (ala docker-compose.yml)

### ISSUE THREAD

**Issue by prologic** [coredns/coredns#795]
Sharing here for others to borrow from / directly use and not sure where else to put this yet.

`dns.yml`:
```#!yaml
version: "3.2"

services:
  coredns:
    image: coredns/coredns
    command: -conf /data/Corefile
    ports:
      - "53:53/udp"
      - "9153:9153/tcp"
    volumes:
      - coredns:/data
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"
      restart_policy:
        condition: on-failure

volumes:
  coredns:
    external: true
```

**Usage:**
```#!bash
 $ docker volume crate coredns
 $ cd /path/to/Corefile  # and possibly other data like zones/*
 $ tar -zcvf - . | docker run -i -t --rm -v coredns:/data alpine /bin/sh -c "mkdir -p /data && tar -C ${2} -zxvf -"
 $ docker stack deploy -c dns.yml dns
```

Be sure to modify your deployment labels as appropriate or add `iface` labels to your nodes where the values are `intern` and `extern` for nodes that have internal-only facing interfaces and external facing interfaces respectively.

**Comment by prologic** [comment]
See also #790 which is attempting to fix the automated docker image builds so this is generally more useful and up-to-date.

**Comment by miekg** [comment]
Sounds like https://github.com/coredns/deployment is a perfect spot for dns.yaml

**Comment by prologic** [comment]
Excellent I'll submit a PR there!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by miekg** [comment]
closing here.
