### ISSUE TITLE
Change to semver

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#798]
We have a 10 releases now and just numbered than 001 to 010. It might be time to move to semver and also think about a possible 1.0.0, or to rephrase: if we move to semver what version should we use.

Recap:
1. Should we move to semver?
2. If yes, what version should we start with?

**Comment by pmoroney** [comment]
1. I think we should, I was planning on bringing it up at some point.
2. 1.0.0
To quote semver.org's FAQ:

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by miekg** [comment]
@pmoroney good points. I agree. I want external middleware to compile cleanly (which I think I've done in #794) though.

But then it looks like we should call 011 "1.0.0" (or 1.0.1 to use the same symbols and mess with everybody :-) )

**Comment by miekg** [comment]
next release is going to be 1.0.0
