### ISSUE TITLE
A middleware to shuffle the response?

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#800]
I have a use case where I would like to shuffle (randomize) the order of the records in a DNS response. 

For example, in case a DNS response is returned with 3 A records `10.2.1.1`, `10.2.2.1`, `10.2.3.1` from the last middleware, then placing the `shuffle` middleware will randomize the order into something like: `10.2.3.1`, `10.2.1.1`, `10.2.2.1`

This will be useful when we want to use coredns as a way of balancing the service (through dns-based service discovery).

Don't know if it is already possible to achieve it through existing middlewares. Otherwise I think it makes sense to add the implementation for the shuffle middleware.

**Comment by johnbelamaric** [comment]
Add a new policy in https://github.com/coredns/coredns/tree/master/middleware/loadbalance

**Comment by miekg** [comment]
think loadbalance already does this.

**Comment by yongtang** [comment]
ah yes loadbalance middleware does that.
