### ISSUE TITLE
middleware/rewrite: Support for EDNS Client Subnet

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#801]
Currently rewrite only allows modification of local and NSID EDNS0 options. We need support for ECS. This is already available in go-dns as the EDNS0_SUBNET struct.

**Comment by huynhmb359** [comment]
The syntax for the support would be 
```
rewrite edns0 subnet set <v4-bitmask-len>  <v6-bitmask-len>
```
where 

- <v4-bitmask-len> is the bit mask length for IP V4,  max 32 

- <v6-bitmask-len> is the bit mask length for IP V6,  max 128.

**Comment by fturib** [comment]
I understand the code is implemented and the issue can be closed.

**Comment by johnbelamaric** [comment]
Correct.
