### ISSUE TITLE
mw/kubernetes: handle incomplete SRV requests

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#808]
Treat missing `_service._protocol.` segments as wild cards.

**Comment by miekg** [comment]
With qtype A this is already done? Any other types should have the same behavior btw. Should check that for etcd as well, can't give NXDOMAIN for any name that is known to exist.

**Comment by chrisohaver** [comment]
i think you meant to comment on the other issue.  this one is about handling incomplete name.
But if you are speaking about this issue... the answer is no, and incomplete A request will not assume a wildcard for all requests...

e.g. A request for `namespace.svc.zone.` is not equivalent to `*.namespace.svc.zone.` ... A request for `namespace.svc.zone.` will not return a list `A` records for all services.

**Comment by chrisohaver** [comment]
Looks like an incompletely incomplete query doesn't get handled properly...

e.g. an SRV request for `*.svc-1-a.test-1.svc.cluster.local.` returns `NXDOMAIN` when the service `svc-1-a.test-1.svc.cluster.local.` exists.

**Comment by chrisohaver** [comment]
Closing this - `NXDOMAIN` is the expected behavior here per #975
