### ISSUE TITLE
mw/kubernetes: return NODATA for all records type queries...

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#809]
... if A record exists but the queried record type does not.

**Comment by miekg** [comment]
This tests should also be done for kubernetes:
https://github.com/coredns/coredns/blob/master/middleware/etcd/lookup_test.go#L155

**Comment by chrisohaver** [comment]
I'll do more extensive testing ... but it appears that the existing code already behaves correctly for both `SRV` and `TXT`...

```
dnstools# host svc2.scale.svc.cluster.local.
svc2.scale.svc.cluster.local has address 10.0.0.101

dnstools# host -t TXT svc2.scale.svc.cluster.local.
svc2.scale.svc.cluster.local has no TXT record

dnstools# host -t SRV _123.*.svc2.scale.svc.cluster.local.
_123.*.svc2.scale.svc.cluster.local has no SRV record
```

So, probably nothing to do here, but i'll do more testing to make sure.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] MW/K8S: retur..." ]
>I'll do more extensive testing ... but it appears that the existing code already behaves correctly for both `SRV` and `TXT`...
>
>```
>dnstools# host svc2.scale.svc.cluster.local.
>svc2.scale.svc.cluster.local has address 10.0.0.101
>
>dnstools# host -t TXT svc2.scale.svc.cluster.local.
>svc2.scale.svc.cluster.local has no TXT record
>
>dnstools# host -t SRV _123.*.svc2.scale.svc.cluster.local.
>_123.*.svc2.scale.svc.cluster.local has no SRV record
>```
>
>So, probably nothing to do here, but i'll do more testing to make sure.

Ack. But how about HINFO (to just name it type) And what about the slack 
discussion?

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
The slack discussion was about treating absence of service/protocol as wildcard service/protocol.
Different issue, which is fixed by #823

**Comment by chrisohaver** [comment]
This already works (currently) for record types that k8s middleware actually supports records for... but possibly not for obscure record types that k8s will never have a record for...

I modified the issue title and description to account for the change in scope of the issue.

**Comment by chrisohaver** [comment]
Miek - based on your pull requests... it looks like you are working on this issue... so I'll stop.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] MW/K8S: retur..." ]
>Miek - based on your pull requests... it looks like you are working on this issue... so I'll stop.

OK, Yeah, I want clean it up a little and bring it more inline with etcd (and 
hopefully simplify the code a bit <-- that's the main goal here)

**Comment by miekg** [comment]
I think I fixed most of this (*think*)
