### ISSUE TITLE
mw/kubernetes: Make kubernetes.coreDNSRecord threadsafe

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#812]

**Comment by chrisohaver** [comment]
Also handle out-of-cluster deployment better - i.e. detect if we are deployed out of cluster, and don't bother to try finding ourself in k8s pods/services.

**Comment by chrisohaver** [comment]
This touches conceptually on the "middleware ready" issue #588.
If we look up the value for `kubernetes.coreDNSRecord` at set up time, we'll need to wait for the k8s api caches to get seeded.  Meaning that we will need to detect when this happens, as we would have to do to detect "readiness".

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] MW/K8S: Make ..." ]
>This touches conceptually on the "middleware ready" issue #588.
>If we look up the value for `kubernetes.coreDNSRecord` at set up time, we'll need to wait for the k8s api caches to get seeded.  Meaning that we will need to detect when this happens, as we would have to do to detect "readiness".

And we reject all queries until that is done?

**Comment by johnbelamaric** [comment]
Yes. But for K8s, the idea is you have multiple copies running. If one dies, it gets pulled out of the load balancer pool. When a new one starts up, it won't get added to the pool until the readiness check passes.

**Comment by chrisohaver** [comment]
> And we reject all queries until that is done?

We could `REFUSE` ...  Otherwise we'd return `NXDOMAIN` for a service that hasn't reached the k8s cache yet.  IMO, this isn't a big deal for normal incoming queries since the k8s service/pod cache will be present before the first query comes in (except perhaps for extreme scale cases where the service/pos lists are very big and take some time to get).  

It's possible that reading the k8s cache is blocked until it is initialized/seeded with the current state from k8s, in which case this is isn't an issue.

**Comment by johnbelamaric** [comment]
With per-middleware checks, we can REFUSE only those queries that would hit an unready middleware. In the K8s case, our readiness check from K8s would wait until ALL mw are ready. But in other use cases we may want to be able to service the requests from mw that are ready as soon as possible.

**Comment by miekg** [comment]
So, after `InitKubeCache` we can get this local IP?

**Comment by chrisohaver** [comment]
`InitKubeCache` starts the cache watchers, which fill the cache asynchronously.  but perhaps just the updates are asynchronous, and the initial seeding of data is synchronous.

**Comment by miekg** [comment]
Refuse is the only sane response, you can't nxdomain stuff that you are not sure might exists.

**Comment by miekg** [comment]
For this specific issue: this code has been removed. Nothing is cached though; so this may impact performance.
