### ISSUE TITLE
mw/kubernetes: Use indexes for endpoints and services caches

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#814]
Add indexing to endpoints and services caches, (pod cache already uses indexes).

**Comment by chrisohaver** [comment]
The pods cache already uses indexes to look up pods `PodIndex(ip string)`.

The same should be done for services and endpoints, removing `ServiceList()` and `EndpointsList()`, and replacing with new methods `ServiceIndex(service, namespace string)`, and `EndpointIndex(service, namespace string)`.

**Comment by miekg** [comment]
Is something happening here?

**Comment by chrisohaver** [comment]
Yes. It's in progress.

**Comment by johnbelamaric** [comment]
#1149
