### ISSUE TITLE
http google api server protocol ?

### ISSUE THREAD

**Issue by mcarbonneaux** [coredns/coredns#816]
while be interesting to implemente http google api as server protocol (in similare way of grpc) in coredns to be abel to make dns over http request to coredns service and coredns proxyfing to any protocol that support as backend...

can be usefull to proxyfing as http request to local private dns like google do for public dns...

**Comment by miekg** [comment]
I'm not sure what the status of this protocol is within Google as it is not a (IETF) standard. Elevating this to incoming messages seems a stretch. Why wouldn't DNS with TLS work?

**Comment by mcarbonneaux** [comment]
> Why wouldn't DNS with TLS work?

Because with http is more simple to request it, and there many http client to do it in many language (java, javascript, php, python, ruby...) !
can also request in shell with curl !

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] http google a..." ]
>> Why wouldn't DNS with TLS work?
>Because with http is more simple to request it, and there many http client to do it in many language !

I think the gRPC interface is the better way forward, same arguments apply as 
for http.

**Comment by mcarbonneaux** [comment]
but grpc is not so simple to use than http... you must have specific binary than can talk grpc... 
with http you can use a simple netcat...

**Comment by mcarbonneaux** [comment]
but it possible to generate rest to grpc proxy ... 
https://github.com/grpc-ecosystem/grpc-gateway

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] http google a..." ]
>but grpc is not so simple to use than http... you must have specific binary than can talk grpc...
>with http you can use a simple netcat...

Yes, it's binary, I'll give you that :-) We also just wrap the DNS bytes in 
grpc, so there is no new protocol, just DNS over gRPC.

**Comment by miekg** [comment]
We should probably document the gRPC slightly better.

**Comment by mcarbonneaux** [comment]
Generaly grpc need stub (to decode/encode)  to work, rest need only http client support and are natively integreted in any language (many have also natively json parser).

**Comment by mcarbonneaux** [comment]
Google dns protocol are very simple... It's match dns request and response...

**Comment by miekg** [comment]
Sorry can't see the point your making. gRPC provides everything you want.

**Comment by johnbelamaric** [comment]
I think what he is saying is that if it's gRPC you need to compile in the protobuf definitions, but JSON is purely handled at runtime.

**Comment by mcarbonneaux** [comment]
yes @johnbelamaric is that... 

@miekg with json you can construct request from any language very simply, and human readable... 
for exemple i can call rest from shell very simply without need external specific program...

you can also expose private dns to program than use google api to request in private network...

grpc have advantage and disavantage, rest to. in somme case is more simple to use one or the other one...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] http google a..." ]
>yes @johnbelamaric is that...
>
>with json you can construct request from any language very simply, and human readable...
>
>you can also expose private dns to program than use google api to request in private network...
>
>grpc have advantage and disavantage, rest to. in somme case is more simple to use one or the other one...

True.

Note: I was involved in the creation of that Google josn API and I cannot vouch 
for it's continued existence. I don't won't to be the one holding the torch in 
this specific implementation. If there is an IETF supported protocol, we gladly 
implement it.

For now, the thing that comes reasonable close is the gRPC interface.

/Miek

--
Miek Gieben

**Comment by m13253** [comment]
I want to state 2 advantages of having HTTP(S) protocol:
1. Able to be cached with a standard CDN.
2. Able to share the same port with another HTTP(S) service.

For the latter, it is important if:
- The client must use a HTTP proxy to access the Internet, where only port 80 & 443 are available.
- The client is under a restrictive firewall, where non-standard ports are rejected.
- The client is living in some country where providing uncensored DNS service may result in political trouble (so the service provider wants to hide the service inside a HTTPS site).

These 3 scenarios are very common in some parts of the world, or maybe all over the world. Thus providing a HTTP protocol may be beneficial to the accessibility of the DNS service.

(As far as I know, gRPC can not share port with other vhosts / services. Please let me know if it actually can.)
