### ISSUE TITLE
mw/kubernetes: SRV requests for external services

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#817]
@chrisohaver this todo:
https://github.com/coredns/coredns/blob/master/middleware/kubernetes/kubernetes.go#L135
What should happen there? If we have a proxy do an external query? CNAMEs can point to internal names?

**Comment by chrisohaver** [comment]
corrected title... External services is already implemented for `A` records.  External services are registered services in k8s that point to an outside host. Wasn't sure how to handle `SRV` requests on one of these services.  Not sure if k8s allows you to define available ports/protocols for an external service.  If so, then we can check the local k8s object, if not, we'd need to proxy the `SRV` request upstream.

**Comment by chrisohaver** [comment]
> CNAMEs can point to internal names?

Had not considered that case. It may be possible to point an external service to a service inside the k8s cluster.  I have not tried. Not sure if that makes sense to do this.  But if it _can_ be done, to handle it we'd have to conditionally upstream only if the zone it not in the current zone.  Otherwise, lookup the service locally in k8s middleware.

**Comment by johnbelamaric** [comment]
We could set the upstream back to ourselves. See also https://github.com/kubernetes/dns/issues/131 which can be fixed the same way. You risk loops, though.

**Comment by johnbelamaric** [comment]
See also https://github.com/kubernetes/dns/issues/140

**Comment by chrisohaver** [comment]
@johnbelamaric opened issue kubernetes/dns#140 to get consensus on how we should handle SRV requests for external services.

**Comment by chrisohaver** [comment]
IMO cases 1-3 (listed in kubernetes/dns#140) are the same as “combine answers from both external service def and remote SRV request”.

I also think that it makes sense to do the same for 4.  In this case you are presenting the "real" SRV records for the external service target, in addition to "virtual" ones defined by the kubernetes external service definition.
