### ISSUE TITLE
Add go version and githash to -version output

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#821]
Useful in general, super useful when building a development build from source that some uses.

We have
~~~
% coredns -version
CoreDNS-010
~~~

Should become something like:

~~~
% coredns -version
CoreDNS-010
go1.8.3, 2c0fc318
~~~
I.e. put on a new line so anyway parsing the version won't get a nasty surpise.

**Comment by miekg** [comment]
Some of this can be copied from caddy, as the build.bash script as this:
~~~
Caddy 0.10.6 (+730ed8d Fri Aug 04 16:09:08 UTC 2017)
~~~

**Comment by mholt** [comment]
Note that putting the date in makes the builds not reproducible. I need to change it so the date is only inserted when building not at an exact tag or commit.

**Comment by yongtang** [comment]
Added PR #900

**Comment by miekg** [comment]
Done in that pr. No date has been added.
