### ISSUE TITLE
Setup error: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Roderick-Jonsson** [coredns/coredns#833]
I manually setup a basic custom kubernetes cluster with the automatically generated self signed certificates at /var/run/kubernetes/

When installing coredns from the tutorial [CoreDNS for Kubernetes Service Discover, Take 2](https://coredns.io/2017/03/01/coredns-for-kubernetes-service-discovery-take-2/) the kubernetes components spin up successfully. But when I look at the system log for the single coredns pod I see two error messages 

`E0805 04:58:47.905942       1 config.go:269] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
.:53
CoreDNS-010
2017/08/05 04:58:47 [INFO] CoreDNS-010
E0805 04:58:47.927179       1 reflector.go:214] github.com/coredns/coredns/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *api.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: x509: certificate signed by unknown authority`

1. How do I make coredns accept the unknown certificate from the Kubernetes API Server? 
2. Is there a possibility for coredns to contact the Kubernetes API Server using http instead https?

**Comment by johnbelamaric** [comment]
By default, the k8s middleware uses the standard service accounts that are created in each pod. If you are running K8s 1.6 or later with RBAC, you need to use a different manifest than the one in that blog: https://github.com/coredns/deployment/blob/master/kubernetes/coredns-1.6.yaml.sed

This looks though like the service account wasn't mounted for the pod. See:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

**Comment by johnbelamaric** [comment]
You *can* specify the endpoint which could be http:

`endpoint http://10.0.0.1:8080/`

for example. I don't think you can use the name (because that would be circular...).

**Comment by Roderick-Jonsson** [comment]
@johnbelamaric Thank you for thorough description. I will look into it after I return from my vacations.

I am using kubernetes 1.5 on centos. I have also noticed that when looking at the secrets, the one secret it is using doesn't include the certificate. (I hoped it would do this automatically, as it generated the certificates automatically for me)

**Comment by Roderick-Jonsson** [comment]
Issue closed as I went another route.

**Comment by nik786** [comment]
Im nt geting how to create certificates and integrate in to coredns??
