### ISSUE TITLE
mw/kubernetes: expose external IP entries of the nodes associated with a service in k8s

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#839]
One scenario of the production use cases of kubernetes is to expose the external IP entries of the nodes associated with a service.

For example, considering one service which deploys pods with influxdb and the port of 8086. The influxdb has the pod IP of `10.2.1.5`/`10.2.3.10` and is deployed on a node with external IP of `54.153.100.100` and `54.153.100.101`.

It is possible to expose the service to outside through LoadBalancer or NodePort. But there might be situations where you don't want to use a load balancer, e.g., for performance reasons. After all, there is always a cost associated with load balancing when your app has to reach several other host before it reaches the final destination. And NodePort will unnecessarily increase internal traffic substantially.

In that case, it would be desirable to expose the external IP of the nodes associated with influxdb and set `hostPort` to `8086:8086`. So that a query like `node.influxdb.coredns.io` will return `A` record of `54.153.100.100`  and `54.153.100.101`. An application from the outside world would be able to reach influxdb directly by just pointing to `node.influxdb.coredns.io`.

This may not fit into current k8s DNS schema but I think it is much more useful in real applications where you want to allow outside world to directly accessing it through simple methods (like DNS). And that may help push for more adoptions of CoreDNS.

**Comment by johnbelamaric** [comment]
Yes, I see a use case here. Also we want to zone transfer the external IPs. I think there are a number of use cases:

* In-cluster IPs with in-cluster names (what we do now, and kube-dns does too)
* A/AAAA/SRV for the NodePort services external IPs and ports
* A/AAAA/SRV for LoadBalancer services
* A/AAAA/SRV for services with `externalIP`
* A/AAAA/SRV for pod IPs when using routable pod CIDR

We should work on the DNS schema for these. We want to have something that can capture all of these and allow zone transfers of different sets of IPs.

**Comment by miekg** [comment]
Also see: https://github.com/coredns/coredns/pull/963
