### ISSUE TITLE
Response truncated

### ISSUE THREAD

**Issue by prologic** [coredns/coredns#844]
I'm experiencing issues with (*weird*) resolving netflix domains via Apple TV -> Netflix app.

This is what I'm seeing on the command-line after watching the coredns logs on a running instance as the Netflix app on the Apple TV4 struggled to succeed (*and failed*):

```#!bash
$ host -v api.netflix.com
Trying "api.netflix.com"
;; Truncated, retrying in TCP mode.
Trying "api.netflix.com"
;; Connection to 10.0.0.12#53(10.0.0.12) for api.netflix.com failed: connection refused.
;; Connection to 10.0.0.13#53(10.0.0.13) for api.netflix.com failed: connection refused.
;; Connection to 10.0.0.14#53(10.0.0.14) for api.netflix.com failed: connection refused.
```

I'm not even sure if coredns can be run in with both UDP and TCP listeners; but the truncated response is worrying.

More than happy to help debug this! Let me know what more you need!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] Response truncate..." ]
>I'm experiencing issues with (*weird*) resolving netflix domains via Apple TV -> Netflix app.
>
>This is what I'm seeing on the command-line after watching the coredns logs on a running instance as the Netflix app on the Apple TV4 struggled to succeed (*and failed*):
>
>```#!bash
>$ host -v api.netflix.com
>Trying "api.netflix.com"
>;; Truncated, retrying in TCP mode.
>Trying "api.netflix.com"
>;; Connection to 10.0.0.12#53(10.0.0.12) for api.netflix.com failed: connection refused.
>;; Connection to 10.0.0.13#53(10.0.0.13) for api.netflix.com failed: connection refused.
>;; Connection to 10.0.0.14#53(10.0.0.14) for api.netflix.com failed: connection refused.
>```
>
>I'm not even sure if coredns can be run in with both UDP and TCP listeners; but the truncated response is worrying.

CoreDNS always runs udp and tcp listeners.

>More than happy to help debug this! Let me know what more you need!

How are you running CoreDNS? (i.e. Corefile)

Connection refused is strange; ah is just does not do TCP (*argh*). Would be 
nice to pinpoint the truncated response *should* be in the logs - otherwise 
would be good to add.

So netflix returns TC (I think) and then disallows TCP?

does: dig +tcp @<netflix> "somename"
work?

/Miek

--
Miek Gieben

**Comment by prologic** [comment]
I'll poke at this further tomorrow; its annoying me since I want to use
CoreDNS everywhere and not have to shove 8.8.8.8 in strange places :D


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Response trun..." ]
>I'll poke at this further tomorrow; its annoying me since I want to use
>CoreDNS everywhere and not have to shove 8.8.8.8 in strange places :D

Good :-)

PR #845 is trivial and will help in debugging this - I will finish that up 
today.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I've merged #845 into master; running the lastest master and grepping for `tc` should help pinpoint things.

**Comment by prologic** [comment]
Cool thanks! I'll debug this tonight!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Not seeing anything obvious in the logs so far;

```#!bash
10.255.0.5 - [08/Aug/2017:07:29:12 +0000] "AAAA IN mail.google.com. udp 33 false 512" NOERROR 88 30.721959ms
10.255.0.14 - [08/Aug/2017:07:29:12 +0000] "A IN mail.google.com. udp 33 false 512" NOERROR 76 29.104985ms
```

**Comment by miekg** [comment]
That's doesn't look like the logs with the new info (rflags)...

**Comment by prologic** [comment]
I have no idea how this rflags thing works atm; but yeah working on it :D

**Comment by prologic** [comment]
Ahh! You must be talking about this:

Server logs:
```#!bash
prologic@Jamess-MacBook
Tue Aug 08 00:43:04
~/coredns#844
 2
$ coredns -conf ./Corefile
.:1053
2017/08/08 00:43:17 [INFO] CoreDNS-010
CoreDNS-010
::1 - [08/Aug/2017:00:44:31 -0700] "A IN api.netflix.com. udp 33 false 512" NOERROR qr,tc,rd,ra 218 12.10094ms
::1 - [08/Aug/2017:00:44:31 -0700] "A IN api.netflix.com. tcp 33 false 65535" NOERROR qr,rd,ra 218 29.840321ms
```

Client attempt:
```#!bash
prologic@Jamess-MacBook
Tue Aug 08 00:44:22
~/go-projects/msgbus
 (master) 1
$ dig @localhost -p 1053 api.netflix.com IN A
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.8.3-P1 <<>> @localhost -p 1053 api.netflix.com IN A
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32543
;; flags: qr rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.netflix.com.		IN	A

;; ANSWER SECTION:
api.netflix.com.	91	IN	CNAME	api.geo.netflix.com.
api.geo.netflix.com.	814	IN	CNAME	api.us-west-2.prodaa.netflix.com.
api.us-west-2.prodaa.netflix.com. 11 IN	A	52.89.218.79
api.us-west-2.prodaa.netflix.com. 11 IN	A	52.43.229.209
api.us-west-2.prodaa.netflix.com. 11 IN	A	52.42.114.165
api.us-west-2.prodaa.netflix.com. 11 IN	A	52.43.49.115
api.us-west-2.prodaa.netflix.com. 11 IN	A	52.40.85.186
api.us-west-2.prodaa.netflix.com. 11 IN	A	52.42.30.173
api.us-west-2.prodaa.netflix.com. 11 IN	A	52.89.110.149
api.us-west-2.prodaa.netflix.com. 11 IN	A	52.40.40.14

;; Query time: 31 msec
;; SERVER: ::1#1053(::1)
;; WHEN: Tue Aug  8 00:44:31 2017
;; MSG SIZE  rcvd: 218
```

^^^ Note I'm running this locally so I probably have a working UDP + TCP setup (*I should fix my production setup to also expose TCP*).

**Comment by prologic** [comment]
Now I still don't understand this `tc` thing nor why the response is getting truncated (*yet*).

**Comment by prologic** [comment]
>    Where TC is set, the partial RRSet that would not completely fit may
   be left in the response.  When a DNS client receives a reply with TC
   set, it should ignore that response, and query again, using a
   mechanism, such as a TCP connection, that will permit larger replies.

I see -- So this *may* not be a bug; but a misconfiguration

**Comment by prologic** [comment]
Although I wonder whether we're doing this bit correctly:

> In such cases
   the entire RRSet that will not fit in the response should be omitted,
   and the reply sent as is, with the TC bit clear.  If the recipient of
   the reply needs the omitted data, it can construct a query for that
   data and send that separately.

**Comment by prologic** [comment]
Reconfiguring the coredns services to also expose TCP resolves this issue.

**Comment by miekg** [comment]
How? Did you fw off the tcp port?

On Aug 8, 2017 8:56 AM, "James Mills" <notifications@github.com> wrote:

Reconfiguring the coredns services to also expose TCP resolves this issue.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/coredns/coredns/issues/844#issuecomment-320880616>, or mute
the thread

**Comment by prologic** [comment]
Never exposed it in the first place :)
