### ISSUE TITLE
no way to set Etcd client Transport

### ISSUE THREAD

**Issue by zzxun** [coredns/coredns#847]
IN 
[middleware/etcd/setup.go#newEtcdClient](https://github.com/coredns/coredns/blob/master/middleware/etcd/setup.go#L132) 
Etcd Client use
[middleware/pkg/tls.go#NewHTTPSTransport](https://github.com/coredns/coredns/blob/master/middleware/pkg/tls/tls.go#L110) 
to build a `http.Transport`.
But there is NO WAY TO SETTING `http.Transport`.  Specially the DEAULT `MaxIdleConnsPerHost` in go is just `2`, raises a big problem!

We are using coredns + etcd. On our testing environment, LXC on Linux:

- Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz / 48 cores
- 128G memory

After continual stress testing it for few days, `etcdctl` begin to error with `connect: cannot assign requested address` :

```
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.187.15.167:2379: connect: cannot assign requested address
; error #1: dial tcp xx:2379: connect: cannot assign requested address
; error #2: dial tcp xx:2379: connect: cannot assign requested address
; error #3: dial tcp xx:2379: connect: cannot assign requested address
; error #4: dial tcp xx:22379: connect: cannot assign requested address
...
```

And the are so many `TIME_WAIT` on `2379`:
```
netstat -apn | grep 2379 | wc -l
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
130646
```

Because sockets on 2379 open/close frequently under stress testing. 
Then I checkout source of coredns, and  change the `tls.go` make `MaxIdleConnsPerHost=25`, after rebuild and restart:
```
netstat -an | grep '2379' | grep 'ESTABLISH' | wc -l
46
netstat -an | grep '2379' | grep 'TIME_WAIT' | wc -l
4
```

Resolved.

**Comment by miekg** [comment]
We could make that a default. What are the downsides to it?

We should also work on getting etcd3 support into shape.

**Comment by miekg** [comment]
Want to send a small PR that does this?

**Comment by zzxun** [comment]
@miekg seems no downsides in DNS query. QPS in DNS query is really high, increase connection pool size is useful.

> https://stackoverflow.com/a/39834253
> The default http.Transport is opening and closing connections too quickly. Since all connections are to the same host:port combination, you need to increase MaxIdleConnsPerHost to match your value for num_coroutines. Otherwise, the transport will frequently close the extra connections, only to have them reopened immediately.

**Comment by zzxun** [comment]
#853
