### ISSUE TITLE
FOSSA license scan is failing

### ISSUE THREAD

**Issue by yongtang** [coredns/coredns#867]
I saw FOSSA license scan is failing:
[![FOSSA Status](https://app.fossa.io/api/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fcoredns%2Fcoredns.svg?type=shield)](https://app.fossa.io/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fcoredns%2Fcoredns?ref=badge_shield)

There is one issue related to `ratelimit` (GNU Lesser General Public License v3 (LGPL-3.0)) though I don't know what we need to do to fix it?

**Comment by miekg** [comment]
yeah, I noticed that too, but I couldn't access fossa @caniszczyk 

seems to be coming from k8s vendoring though?!?
