### ISSUE TITLE
middleware/kubernets: fix AutoPath callback

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#870]
That function: https://github.com/coredns/coredns/blob/master/middleware/kubernetes/autopath.go#L11
returns a path that the autopath middleware can use.

The current code return some nonsense (couldn't figure out what it should do). This method should return the correct searchpath.

@chrisohaver could you help here?

**Comment by chrisohaver** [comment]
It should be the 3 k8s domains ...

```
namespace.svc.zone.
svc.zone.
zone.
```
(namespace = namespace of the remote pod)
Followed by the domains pulled from the local `resolv.conf`

**Comment by miekg** [comment]
Thanks!

and `zone` must be the zone from the query (if it falls in the zone list k8s is auth for)? Or only the primary domain of kubernetes?

**Comment by chrisohaver** [comment]
zone from the query.

**Comment by miekg** [comment]
ack. Bit of a bummer to reparse the query again. But I guess that makes sense. I'll submit a PR with those changes.

**Comment by chrisohaver** [comment]
Correction... it can be the primary zone.  I don't understand the use case for multiple zones though.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/ku..." ]
>Correction... it can be the primary zone.  I don't understand the use case for multiple zones though.

If the query matches one of the zones that the k8s middleware handles this 
should not matter.

**Comment by chrisohaver** [comment]
I think there can be only one cluster domain per cluster.

**Comment by miekg** [comment]
But you might still want autopathing?

**Comment by chrisohaver** [comment]
cluster domain = zone....  one zone per cluster.
