### ISSUE TITLE
middleware/kubernetes: wildcard answers

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#872]
Answers to wildcard queries should contain the actual name of the record for each answer.  Currently the answers contain verbatim copies of the question, which contains wildcards.

For example:

An `A` query for `*.*.svc.cluster.local.` currently returns matches in the following way ...
```
*.*.svc.cluster.local.      123    IN      A       10.0.0.100
*.*.svc.cluster.local.      123    IN      A       10.0.0.101
```

With the answer above, you don't know the name of each record.

It would be more informative to include the actual fqdn in each answer... For example...
```
svc1.ns1.svc.cluster.local.      123    IN      A       10.0.0.100
svc2.ns1.svc.cluster.local.      123    IN      A       10.0.0.101
```

**Comment by miekg** [comment]
So... wildcard in the DNS are complex. First off a client will never issue a `*.*.svc.cluster.local.` query (normally). It will ask something as: `svc1.ns1.svc.cluster.local.`, but the server may have wildcard configured meaning *.ns1.svc.cluster.local matches *all* names under the `ns1` one node.

So we sort of discussing a client-side wildcard thing here. This was originally a SkyDNS thing, but I'm not sure what kube-dns has picked up from this and what is currently supported. Maybe it is time to drop this and act as if there are no wildcard in the kubernetes (this should be reflected in the DNS spec) *and* drop the client side wildcard hack as well.

As said this would depend mostly on what kube-dns does at the moment.

**Comment by miekg** [comment]
The current behavior of CoreDNS (and SkyDNS) is correct for these queries. Filling out the wildcard label will not work, because that is not the qname.

Closing with wont-fix. WAI
