### ISSUE TITLE
file: $INCLUDE in zone file prevents startup

### ISSUE THREAD

**Issue by itskenny0** [coredns/coredns#880]
When using $INCLUDE in a zone file, CoreDNS fails to start up with this message:

```2017/08/10 12:49:15 middleware/file: zone.mydomain.com: dns: failed to open `
': "\n" at line: 46:22```

The zonefile looks like this:

```$TTL 5m

mydomain.com.     IN      SOA     dns.yourdomain.com. postmaster.yourdomain.com. (
                        2017081001
                        14400
                        7200
                        604800
                        3600 )

<omitted>

$INCLUDE zone.mydomain.com-include

```

The file zone.mydomain.com-include exists in the CoreDNS startup directory which is the same folder the zonefiles reside in. Putting an absolute path doesn't change anything. Judging from the error message, maybe a parse error?

**Comment by miekg** [comment]
See https://github.com/miekg/dns/pull/503
(recompile with updated `miekg/dns`)

**Comment by itskenny0** [comment]
Thank you! Do you have an estimate on when a release containing this update could be out? We're unable to build this on our machines, currently.

**Comment by miekg** [comment]
We're roughly on a monthly schedule, but next release will be dubbed 1.0.0 so it make take somewhat longer. You can follow the 1.0.0 milestone; I can't give an estimate yet; there are some bug that I want to see fixed.

If you want it *now*; you should checkout v010, run `go get -u` and `go build` to get a update binary.

**Comment by itskenny0** [comment]
Thank you!
I built the latest CoreDNS on a testsystem and while it does start now, I can't get the include to work.

To reproduce:

**Corefile**
```
example.org:60053 {
	file zone.example.org
	errors stdout
	log stdout
}
```

**zone.example.org**
```
$TTL 5m

example.org.     IN      SOA     dns.otherdomain.com. postmaster.otherdomain.com. (
                        2017081004
                        14400
                        7200
                        604800
                        3600 )

$INCLUDE /root/coredns-playground/include.zone

test1		IN A		1.2.3.4
test2		IN A		4.3.2.1
test3		IN A		8.8.8.8
test4		IN A		8.8.4.4
```

**include.zone**
```
includedhost	IN A	11.22.33.44
includedhost2	IN A	44.33.22.11
```

I can resolve the hosts defined in the main zone, but not those defined in the include:

```
root@dns:~/coredns-playground# dig +short test1.example.org @127.0.0.1 -p 60053
1.2.3.4
root@dns:~/coredns-playground# dig +short test2.example.org @127.0.0.1 -p 60053
4.3.2.1
root@dns:~/coredns-playground# dig +short test3.example.org @127.0.0.1 -p 60053
8.8.8.8
root@dns:~/coredns-playground# dig +short test4.example.org @127.0.0.1 -p 60053
8.8.4.4
root@dns:~/coredns-playground# dig +short includedhost.example.org @127.0.0.1 -p 60053
root@dns:~/coredns-playground# dig +short includedhost2.example.org @127.0.0.1 -p 60053
root@dns:~/coredns-playground#
```

CoreDNS logs this when executing these queries:
```
root@dns:~/coredns-playground# ./coredns 
example.org.:60053
2017/08/10 15:36:57 [INFO] CoreDNS-010
CoreDNS-010
127.0.0.1 - [10/Aug/2017:15:36:59 +0000] "A IN includedhost2.example.org. udp 55 false 4096" NXDOMAIN qr,aa,rd,ra 136 263.414µs
127.0.0.1 - [10/Aug/2017:15:37:21 +0000] "A IN test1.example.org. udp 47 false 4096" NOERROR qr,aa,rd,ra 63 239.733µs
127.0.0.1 - [10/Aug/2017:15:37:25 +0000] "A IN test2.example.org. udp 47 false 4096" NOERROR qr,aa,rd,ra 63 196.815µs
127.0.0.1 - [10/Aug/2017:15:37:29 +0000] "A IN test3.example.org. udp 47 false 4096" NOERROR qr,aa,rd,ra 63 226.429µs
127.0.0.1 - [10/Aug/2017:15:37:32 +0000] "A IN test4.example.org. udp 47 false 4096" NOERROR qr,aa,rd,ra 63 283.504µs
127.0.0.1 - [10/Aug/2017:15:37:43 +0000] "A IN includedhost.example.org. udp 54 false 4096" NXDOMAIN qr,aa,rd,ra 135 243.733µs
127.0.0.1 - [10/Aug/2017:15:37:48 +0000] "A IN includedhost2.example.org. udp 55 false 4096" NXDOMAIN qr,aa,rd,ra 136 236.344µs
```

**Comment by itskenny0** [comment]
@miekg could I request your assistance on this? :-)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] file: $INCLUD..." ]
>@miekg could I request your assistance on this? :-)

To recompile coredns with updated deps?

**Comment by itskenny0** [comment]
No, please look above. With updated source CoreDNS doesn't fail starting with an include, but the includes are still not read.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] file: $INCLUD..." ]
>No, please look above. With updated source CoreDNS doesn't fail starting with an include, but the includes are still not read.

If you can: please replicate the issue in a small zone file and file an Go DNS 
issue (github.com/miekg/dns)

Thanks!

**Comment by miekg** [comment]
I'm taking a look.

**Comment by miekg** [comment]
Yeah, what I thought: the $ORIGIN is not inherited by the $INCLUDE. That is probably a bug.

In the mean time you could add $ORIGIN at the top of the file or use FQDN, except if you share this snippets with other zones - then this obviously doesn't work.

**Comment by itskenny0** [comment]
Thank you for your analysis and this great product! Looking forward to a fix.

**Comment by miekg** [comment]
np :-)

The filename is used as the origin :blush: in my tests:
~~~
seen: include./home/miek/include.miek.nl.	3600	IN	A	127.0.0.53
~~~

**Comment by miekg** [comment]
https://github.com/miekg/dns/pull/508

**Comment by miekg** [comment]
Waiting for Travis before I click "merge"

**Comment by miekg** [comment]
Go dns is fixed. Leaving this open for a while - we probably want a test in coredns as well to check if we're using the correct dns lib.
