### ISSUE TITLE
Idea/Feature request: File middleware with JSON data source

### ISSUE THREAD

**Issue by itskenny0** [coredns/coredns#882]
Hi there,

I was wondering if there's any chance we could see JSON files being used as a data source instead of standard RFC 1035 zone files. I saw that there are IETF drafts for JSON-based zone files, e.g. https://tools.ietf.org/id/draft-bortzmeyer-dns-json-01.html .

Seeing how the dns.google.com middleware already exists I suspect there might already be a good bit of work already done here. Do you think a feature like this is likely to make it into CoreDNS?

Thanks a lot!

Best,
kenny

**Comment by miekg** [comment]
There are a lot of pitfalls when using json for dns data; and the IETF isn't finished standardizing this yet. I rather wait for that.

Also see: https://github.com/coredns/coredns/issues/816. We do support the (non-standard) DNS in grpc - which just wraps the bits - so doesn't invent anything new.

**Comment by itskenny0** [comment]
Thank you for your assessment :)
