### ISSUE TITLE
Tests: speed up travis

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#886]
Just a general feeling with our Travis tests that they are slow. Would be nice to speed them up.

**Comment by chrisohaver** [comment]
You can do unit tests and integration locally on your system without `-race` detection for a faster "first pass" before submitting a PR to travis.  This is _much_ faster.

It's generally good practice (IMO) to get unit tests to pass locally before submitting a PR, instead of submitting a PR and waiting for Travis to do it for you.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] Tests: speed ..." ]
>You can do unit tests and integration locally on your system without `-race` detection for a faster "first pass" before submitting a PR to travis.  This is _much_ faster.
>
>It's generally good practice (IMO) to get unit tests to pass locally before submitting a PR and waiting for Travis to do it for you.

Yes, sure. But I'm usually waiting for the k8s integration (maybe I should do 
that locally as well).

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
It's definitely worth doing if you are going to be working in k8s middleware. You can run them locally by installing `minikube` and creating the k8s test services (the `kubectl apply ...`  command in `.travis.yml`)

**Comment by chrisohaver** [comment]
Most if not all of the coredns unit tests probably could be run in parallel. By setting t.Parallel()...

**Comment by miekg** [comment]
I've played with t.Parallel() a while back, didn't seem to increase that much... but might be worth experimenting again.

Current travis takes about 40+ minutes:
~~~
Dns.join 
#944 opened 41 minutes ago by miekg  
~~~
This is when I got the first email that one of the tests was finished.

**Comment by miekg** [comment]
See #947

coverage is the slow one - maybe that can be pulled out entirely or have it done some other way, dunno.

**Comment by miekg** [comment]
yes: coverage is 19 min:
~~~
 TEST_TYPE=coverage ETCD_VERSION=2.3.1 K8S_VERSION=1.5.0 KUBECTL="docker exec hyperkube /hyperkube kubectl"
 19 min 47 sec
~~~
Useful but slow. Other test run within 3, 4 minutes.

@yongtang do you have any ideas on how we can make coverage faster?

**Comment by yongtang** [comment]
@miekg Let me take a look.

**Comment by miekg** [comment]
Looks like with today's changes we back to 4 minutes :+1:
