### ISSUE TITLE
mw/kubernetes: CNAME handling?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#895]
When you remove the CNAME handling from `handler.go` the tests fails with
~~~
-- FAIL: TestServeDNS (0.00s)
	helpers.go:119: answer for "svc0.testns.fed.svc.cluster.local." contained 0 results, 1 expected
	handler_test.go:239: CNAME Service (Remote Federated) Received:
		 ;; opcode: QUERY, status: NOERROR, id: 10411
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
		
		;; QUESTION SECTION:
		;svc0.testns.fed.svc.cluster.local.	IN	 CNAME
		
		;; AUTHORITY SECTION:
		cluster.local.	300	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1502454179 7200 1800 86400 60
		
	helpers.go:119: answer for "external.testns.svc.cluster.local." contained 0 results, 1 expected
	handler_test.go:239: CNAME External Received:
		 ;; opcode: QUERY, status: NOERROR, id: 25541
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
		
		;; QUESTION SECTION:
		;external.testns.svc.cluster.local.	IN	 CNAME
		
		;; AUTHORITY SECTION:
		cluster.local.	300	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1502454179 7200 1800 86400 60
		
--- FAIL: TestServices (0.00s)
~~~
Why are we testing direct CNAME queries? Is this the federation protocol? No common libc client will make those queries so this will only work for custom clients...?

**Comment by miekg** [comment]
Related this diff:
~~~
               for _, svc := range s {
-                       if t, _ := svc.HostType(); t != dns.TypeCNAME {
-                               noext = append(noext, svc)
-                       }
+                       //if t, _ := svc.HostType(); t != dns.TypeCNAME {
+                       noext = append(noext, svc)
+                       //}
                }
~~~
Does not make any tests fails. What does that do and why isn't it tested?

**Comment by chrisohaver** [comment]
> Why are we testing direct CNAME queries? Is this the federation protocol? No common libc client will make those queries so this will only work for custom clients...?

Direct CNAME queries are tested because the testing A queries of CNAMEs is hard to test.  k.Proxy is type proxy middleware, instead of an interface, which means we cannot mock out the upstream proxy for a unit test. I submitted a PR a while back with some work toward making k.Proxy an interface to make it more easily testable, but ended up discarding it.

**Comment by chrisohaver** [comment]
> No common libc client will make those queries so this will only work for custom clients...?

But it's a valid query type.  You can query CNAMEs directly using `host` or `dig` ... so IMO coredns should handle them, and it should be tested.

**Comment by chrisohaver** [comment]
> Related this diff: 
...
>What does that do...

The comment immediately above the code explains what it does ... (not included in your code snip).

`// SRV for external services is not yet implemented, so remove those records`

This means that SRV for external services is not yet implemented, so we need to exclude the possibly incorrect external service CNAME record from the answer.  There is an open issue to add support for SRV queries on external services. 

It's not tested because it would be a test for something we don't support yet. We could add a test to ensure that we don't support it... until we do add support, then update the test.

**Comment by miekg** [comment]
If need to test with a proxy, just put the test in the toplevel test directory and that a backend coredns server and perform queries normally.

And indeed: CNAME queries are normal, that why they should not be handled specially in any way. They get handled by the `default` in handler.go's ServeDNS.

> This means that SRV for external services is not yet implemented, so we need to exclude the possibly incorrect external service CNAME record from the answer. There is an open issue to add support for SRV queries on external services.

So this CNAME point to "somewhere" and we don't resolve it? Can we use Lookup to just resolve this name?

**Comment by chrisohaver** [comment]
>If need to test with a proxy, just put the test in the toplevel test directory and that a backend coredns server and perform queries normally.

Some unit tests actually depend on running an instance of coredns as a upstream server?  hmm.  This seems more like an integration test... Wouldn't mocking the upstream proxy be more idiomatic from a unit test perspective?

> And indeed: CNAME queries are normal, that why they should not be handled specially in any way. They get handled by the default in handler.go's ServeDNS.

I'm not understanding what you mean here.

**Comment by chrisohaver** [comment]
> So this CNAME point to "somewhere" and we don't resolve it? Can we use Lookup to just resolve this name?

No, the constructed CNAME is invalid for SRV queries on external services.  So, instead of returning an invalid record we return NODATA.

**Comment by miekg** [comment]
PR #899 removes all the special cases and nothing fails.

**Comment by chrisohaver** [comment]
Ah, OK.  If you have added tests for SRV queries on external services, then thats cool.

**Comment by miekg** [comment]
Good. Thanks for answering my questions on this.
