### ISSUE TITLE
middleware/k8s: add integration tests for k8s+autopath

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#902]
Add autopath+k8s configuration testing to k8s integration testing.

This will require restructuring the test, "fixing" some shortcuts that until now were innocuous...
* Need to execute the queries from within a pod in the cluster (in the test-1 namespace). Currently queries are executed from outside the cluster.
* Should run the main coredns instance inside the cluster, replacing kube-dns.

**Comment by miekg** [comment]
We might want to do these tests completely outside coredns, i.e. different repo that gets pulled in to a running k8s cluster (running somewhere) and performs a bunch of tests.

**Comment by chrisohaver** [comment]
IMO it's just as difficult to set up an external system as it would be to make the travis tests more realistic (currently it kind of "cheats").  Possibly even easier to modify the travis test.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/k8..." ]
>IMO it's just as difficult to set up an external system as it would be to make the travis tests more realistic (currently it kind of "cheats").  Possibly even easier to modify the travis test.

Ok, please elaborate in this bug. I.e. design, what needs changing etc.

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
We should change the following ...

* We should execute the test queries from pods in the cluster. Currently queries are executed from outside the cluster.
* We should run the main coredns instance inside the cluster, replacing kube-dns.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/k8..." ]
>We should change the following ...
>
>* We should execute the test queries from pods in the cluster. Currently queries are executed from outside the cluster.
>* We should run the main coredns instance inside the cluster, replacing kube-dns.

Ack. So how are we going to run a pod inside a k8s cluster? We somehow build a 
executable from the tests and dockerize that and then start a pod with it?

**Comment by chrisohaver** [comment]
> ... build a executable from the tests and dockerize that and then start a pod with it?

Yes.

**Comment by miekg** [comment]
This is a good idea, but the experimentation of how this will work should be done outside the main coredns repo.

**Comment by johnbelamaric** [comment]
Doing all of this is harder, but querying from pods is more easily done:

```
ANN-M-JBELAMARIC:deploy jbelamaric$ kubectl run dnstools -it --rm --image=infoblox/dnstools --restart=Never -- -c "host kubernetes"
kubernetes.default.svc.cluster.local has address 10.0.0.1
```

**Comment by miekg** [comment]
But we also need to capture the results somehow?

**Comment by johnbelamaric** [comment]
Yes, it goes to standard out. So, you have to run that command in your test and capture the output. then parse it (yes, ugly). Though I believe $? also pass through so that may be sufficient for some tests at least.

**Comment by miekg** [comment]
Coming back to this. Go test *builds* a binary and runs that I believe. That should at least give you something to put in docker - or let docker build this on the fly and run it. I think re-using Go and maybe a bunch of CoreDNS tests and code will help in making this an integral part of testing at some point in the future.

**Comment by chrisohaver** [comment]
I meant to say earlier that _coredns_ needs to be dockerized and run in the cluster. The test itself does not need to be dockerized. Each query needs to be run from a pod, but these can be spun up ad hoc in pods in various namespaces as needed.

**Comment by chrisohaver** [comment]
I'm currently working on altering the existing travis test to run coredns and execute queries from within the cluster.  Re-using as much existing test infrastructure as I can.  Target flow ...

1. travis builds coredns docker image, publish to local docker repo, and deploy it in place of kube-dns
2. as needed, tests update coredns configmap and force coredns to reload config
3. tests executed using `host -v` command, which returns a dig-like result.
4. command output captured and parsed into `dns.Msg` object
5. existing test helpers compare `dns.Msg` to `test.Case`.

**Comment by miekg** [comment]
Nice.

Can this be done in a another repo or travis? I'm afraid it will again blow up our travis test duration. And it also just testing 1 middleware....

**Comment by chrisohaver** [comment]
We can move k8s integration tests to run in parallel in another travis instance if they end up taking a long time to run.

What is the benefit of moving k8s integration tests to a separate repo?

**Comment by miekg** [comment]
There is no reason this needs to be in the main repo, as I said: https://github.com/coredns/coredns/issues/902#issuecomment-323554368

Making and uploading a docker container sounds flaky and we already have enough flakiness in the tests, so we really should pile more on that. And it will take longer.

Setting up a webhook and pulling the PR should work just as well.

**Comment by johnbelamaric** [comment]
I think we should get started with what we have and just add it as a separate parallel test run (like Yong did with some of the other tests). Then if we see it taking a long time we disable it and move it to a different repo.

**Comment by johnbelamaric** [comment]
@chrisohaver is this done now or still underway?
