### ISSUE TITLE
mw/kubernetes: non exposed namespace is NXDOMAIN

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#905]
In `Entries()`:
~~~
	// Abort if the namespace does not contain a wildcard, and namespace is not published per CoreFile
	// Case where namespace contains a wildcard is handled in Get(...) method.
	if (!wildcard(r.namespace)) && (len(k.Namespaces) > 0) && (!dnsstrings.StringInSlice(r.namespace, k.Namespaces)) {
		return nil, errNsNotExposed
	}
~~~
This should not be an NXDOMAIN as the namespace exists, but we just hide it. Should be NODATA...

**Comment by johnbelamaric** [comment]
Not sure about that. The idea of filtering out the namespaces is for security/tenant isolation. So when you specify only certain namespaces, you are saying those are the only ones this CoreDNS should say exist at all.

**Comment by miekg** [comment]
And this is true for the lifetime of the cluster? Or at least for the TTL we put on this? (Think both answers are yes). Ok that makes sense.

**Comment by johnbelamaric** [comment]
Yes, certainly for the life of the running CoreDNS instance. The idea being that you may run different CoreDNS instances for different tenants. See https://github.com/kubernetes/dns/issues/132 for some more background.

**Comment by miekg** [comment]
John is right, NXDOMAIN is correct. Closing.
