### ISSUE TITLE
mw/kubernetes: federation refactoring

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#907]
There only reason that `parseRequest` is still a method on `Kubernetes` is because of a possibility of federation. `k.Entries` also sneaks in a federation check, when nothing is found.

We should make the federation flow completely separate from the normal resolution flow. We can detect  if it is a federation query by checking the federation label in early in `k.ServeDNS` and call a possible `federation.ServeDNS()` that handles the federation.

There is also little reason the federation function need to be methods in `Kubernetes`, 
* `federationCNAMERecord` only needs the federation records and a `node.API`, this `node.API` should be parameter to the function
* `stripFederation()` only need the federation to work.

Ideally the whole thing must be put in a federation sub package, except it can't because of the use of `recordRequest` which then should also be put in the subpackage, leading to a cascade of small package that not improve readability.

**Comment by miekg** [comment]
Motivation for putting federation in its own package is to have cleaner, shorter names for the methods.

**Comment by yongtang** [comment]
👍 For separation of federation from main kubernetes usage. Federation itself is not a necessary component of kubernetes and there are lot of users want to get around multi-cluster deployment with other means. No reason to mixture them together.

**Comment by miekg** [comment]
pulling this out into a separate middleware? That would even be better IMO (if possible - though I think it should, look at *autopath* that just calls one function in kubernetes).

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/914 (framework for new middleware)

**Comment by miekg** [comment]
This has been merged.
