### ISSUE TITLE
CoreDNS does not build with Go 1.7

### ISSUE THREAD

**Issue by insomniacslk** [coredns/coredns#917]
As discussed on https://github.com/coredns/coredns/commit/26d8680a11cbe444546d9ec247837ddf0594350e#commitcomment-23618661 , the build fails on Go 1.7. It succeeds on 1.8 and 1.6.
The Travis-CI configuration[1] only enforces 1.8 but as said by @miekg there's no policy but it makes sense to support at least the last two versions

[1] https://github.com/coredns/coredns/blob/00f5c7797e265dc2fecad5acbfcfdad9797e48e5/.travis.yml#L10

**Comment by johnbelamaric** [comment]
@yongtang can you take a look?

**Comment by insomniacslk** [comment]
Currently the only issue is with the kubernetes middleware, as I reported in the linked comment. I managed to build it by replacing the call to `p.Close()` into `p.listener.Close()`, which is the only thing that made sense to me. I may be wrong, so please review it.

If that's the right fix, the only necessary step would be to add Go 1.7 to the `.travis.yml` configuration and trigger a build.

Happy to help get this sorted out

**Comment by johnbelamaric** [comment]
Thanks, feel free to submit that as a PR, the fix and the 1.7 in Travis.

**Comment by insomniacslk** [comment]
Sure, will do that tonight

**Comment by johnbelamaric** [comment]
👍 thanks

**Comment by insomniacslk** [comment]
For reference, the current `apiProxy.Close` is a call to `http.Server.Close` as defined in Go 1.8.x's code, https://github.com/golang/go/blob/f776b9d5fa3577fe2fdaa3d2ef9d48adee329f9c/src/net/http/server.go#L2454 . It is meant to close all the active listeners.

In `apiProxy.Run`, the only listener is defined in the `apiProxy.listener`, an attribute of type `net.Listener`. As per this, if I understand correctly the code, the right thing to do here is to call `Close` on `apiProxy.listener`. I am building this change on Travis right now

**Comment by yongtang** [comment]
Closed through #919.
