### ISSUE TITLE
mw/dnstap: IP endpoint for dnstap

### ISSUE THREAD

**Issue by johnbelamaric** [coredns/coredns#924]
In a microservices environment, it makes more sense to send dnstap data over the network rather than to a domain socket. What level of effort would that be?

**Comment by 2buisson** [comment]
The dnstap message writer is buffered, I add a io.Writer that creates a new TCP connection each time the buffered writer wants to write. And there is the directive change which shouldn't be complicated.

Seems straightforward, will do when I have time.
