### ISSUE TITLE
crash: metrics/vars.Report

### ISSUE THREAD

**Issue by elephantfries** [coredns/coredns#925]
Hi, I am seeing coredns crashing every now and then with what appears to be 'index out of range'. I've seen at least three crashes like that, they all produce the same trace. This is with etcd backend with entries valid for a few hours before being discarded by etcd. Version CoreDNS-010. Trace captured by systemd.
[coredns.crash.1.txt](https://github.com/coredns/coredns/files/1227134/coredns.crash.1.txt)

**Comment by miekg** [comment]
Interesting crash. I'll take a look

**Comment by miekg** [comment]
The only reason this can crash if `req.Msg` is empty, meaning no incoming message has been seen. Which is odd to say the least.

**Comment by miekg** [comment]
This crashes in `DefaultErrorMsg` which together with metrics can lead to this. This is bug 2.

There are two crashes:
~~~
Aug 13 11:34:06 : panic: runtime error: index out of range [recovered]
Aug 13 11:34:06 : panic: runtime error: index out of range
~~~
On that gets recovered and then in the recover it crashes again, showing the stack trace.

Can you run with `debug` middleware enabled? That should show the first crash and bug 1.

**Comment by elephantfries** [comment]
Yes, added debug.  It may take a few days.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] crash: metric..." ]
>Yes, added debug.  It may take a few days.

Thank you.

**Comment by miekg** [comment]
@elephantfries We will probably release a 1.0.0 before we get a handle on this bug. But once seen and fixed will do a 1.0.1 (or whatever we're at then)

**Comment by elephantfries** [comment]
I just checked and saw all three of my test sites showing coredns crashing.  It took 11 days and then they all crashed within 8 hours of one another.  Strange.  Here's a trace from journald (removed host name from the log).  All three produce the same trace.
[coredns.crash.2.txt](https://github.com/coredns/coredns/files/1262406/coredns.crash.2.txt)

**Comment by elephantfries** [comment]
Just wanted to add that my system is an experimental network that uses hack job resolvers. It is possible it might unintentionally generate malformed queries. I'm very interested on my side of things if that is the case. But then, again, coredns is serving a stub domain off a domain hosted by namecheap.com. I would think a malformed query would be rejected before reaching the stub.

**Comment by miekg** [comment]
What, *etcd* and `stubzones`? You may be hitting:
~~~
https://github.com/coredns/coredns/blob/master/middleware/etcd/stub.go#L77
~~~
which would be a first (and a stretch, 'cause I can't see it in the trace).  The proper thing here would be to properly mutex this as even this pointer swap is not atomic.

**Comment by elephantfries** [comment]
I would think that the server at namecheap.com would be dealing with stub zones whereas coredns would be serving regular zones.  But I don't know the code. It seems it gets a query with an empty question or somehow the question disappears.  I can imagine disappearing etcd keys may cause trouble but would it result in what we're seeing?

Speaking of etcd, it probably needs a native etcd3 middleware. I am running etcd3 but it looks like it uses etcd2 API. Go 1.9 has support for concurrent maps which might help in implementation.

**Comment by miekg** [comment]
Can you post/add/mail you Corefile? I don't think etcd is to blame btw and yes etcd3 is in the works (I'm also tinkering with it atm)

empty question section should be cached earlier in the stack. We're still crashing in the DefaultErrorFunc which *does* point a `nil` Msg, but the main question is how this it get there as `nil`?

**Comment by elephantfries** [comment]
Attached. Also, before coredns, I used skydns 2.5.3c which never crashed.
[coredns.conf.txt](https://github.com/coredns/coredns/files/1264471/coredns.conf.txt)

**Comment by elephantfries** [comment]
Regarding etcd3. If there is some reasonably behaving code, I could test it. I can tolerate alpha quality.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] crash: metric..." ]
>Attached. Also, before coredns, I used skydns 2.5.3c which never crashed.
>[coredns.conf.txt](https://github.com/coredns/coredns/files/1264471/coredns.conf.txt)

Thanks. Code is mostly copied from SkyDNS, only new bit is the DefaultErrorFunc 
and metrics reporting in that function. I've merged a fix, but I think I should 
also fuzz this whole code path.

**Comment by ngphban** [comment]
Hi,
I'm having the same problems reported here. coreDNS crashed with same error ```panic: runtime error: index out of range```
Below is my Corefile and my CoreDNS version. Error log is also attached.
[coredns_crashed.txt](https://github.com/coredns/coredns/files/1266159/coredns_crashed.txt)

```
ubuntu@ip-172-31-15-121:~$ cat Corefile 
.:53 {
     proxy . 8.8.8.8:53
     etcd mydomain.com {
       stubzones
       path /skydns
       endpoint https://ELB_ETCD:2379 # Real ETCD load balancer name is hidden here for security
       upstream /etc/resolv.conf 
     }
     errors stdout
     log stdout
}
ubuntu@ip-172-31-15-121:~$ ./coredns -version
CoreDNS-008
```
Sorry I'm not sure how to enable debug mode. Thanks

**Comment by miekg** [comment]
You should be able to use CoreDNS from the master branch to see if that helps.

What I would *love* to have is some kind of repro of this issue, as I'm failing to come up with one myself.

**Comment by miekg** [comment]
Oh you can enable debug mode, by just added `debug` to your config:
~~~
.:53 {
   ....
   debug
   ...
}
~~~

**Comment by ngphban** [comment]
Thank you...I'm enabling debug now. Would take days to get the logs...

**Comment by miekg** [comment]
@elephantfries thanks, Corefile rules out stubzones.

**Comment by miekg** [comment]
Can either of you compile and run a coredns from master? I can provide binaries. #1009 will make this codepath more robust and should fix this issue.

**Comment by elephantfries** [comment]
Yes, I should be able to.  If you want to instrument it, I can run it, too.

**Comment by miekg** [comment]
Cool. I've merged  #1009 into master, so you can just download that branch.

**Comment by elephantfries** [comment]
Built off 5eccfa and deployed.  It may take another couple of weeks to see what it does.

**Comment by elephantfries** [comment]
BTW, looks like `00f5c7  mw/kubernetes: remove federation and cidr (#916)` breaks my client resolver. It appears 'proxy' is no longer enough. It seems 'fallthrough' is now required. It's a configuration file fix but people might want to know about that when upgrading to a release past 010.

**Comment by miekg** [comment]
yep, we are aware of these changes. See https://github.com/coredns/coredns/wiki/CoreDNS-1.0.0-Release
could you paste your old and new Corefile in that doc? That would help me detail the exact changes needed (esp. for the *etcd* middleware). Thanks!

**Comment by elephantfries** [comment]
updated, feel free to edit as needed
IP addresses, path, and domain names are changed to be generic.  Upstream IP is OpenDNS

**Comment by miekg** [comment]
thanks, looks good.

**Comment by johnbelamaric** [comment]
Can you explain where/how `fallthrough` is needed? `etcd` should only handle `mydomain.com`, shouldn't it?

**Comment by elephantfries** [comment]
Not in the example that I posted.  In addition to the local domain it is also resolving other domains via an external resolver.  I found out, fallthrough is now necessary in addition to the proxy declaration. If it ONLY serves the local domain, fallthrough is not needed.

**Comment by johnbelamaric** [comment]
@miekg I don't think this is the correct behavior. If a middleware doesn't handle a particular zone, it should just pass it on down the chain. That's how it's always worked before. For example, in `file`:

https://github.com/coredns/coredns/blob/master/middleware/file/file.go#L37

but in `etcd` we have:

https://github.com/coredns/coredns/blob/master/middleware/etcd/handler.go#L45

`fallthrough` should only be needed if the query is unhandled and the middleware *is authoritative for that zone*.

**Comment by miekg** [comment]
@johnbelamaric you're right! This is the normal: "empty zone go to next". I'll revert the bits from 00f5c7797 (and update release doc, etc. etc.)

**Comment by elephantfries** [comment]
FYI, so far so good, no crashes. Another couple of weeks like that and we should be able to close it.

**Comment by elephantfries** [comment]
It crashed.
It took almost four weeks this time and only one of my three instances crashed. Attached is a journal trace.
[coredns.crash.3.txt](https://github.com/coredns/coredns/files/1344764/coredns.crash.3.txt)

**Comment by miekg** [comment]
\o/ (or not)

I do have a sneaky suspicion what can be though, although this hints that there is a bug in miekg/dns in handling incoming packets.

**Comment by elephantfries** [comment]
If you want to instrument it, I can build from sources and install on my three instances.

**Comment by miekg** [comment]
No I think it is as simple as #1123. We used to use the dns.Server impl wholesale, but moved away from some speed up reasons. This means we can get something that resembles a packet, but it still invalid. Sort of bad

**Comment by elephantfries** [comment]
OK, I'll try it when it shows up in HEAD.   Would there be an option to see what that invalid packet was?  This is of great interest for me.  My project is a new network system with some new DNS queries which we pack into TXT for the moment (probably need new record type). I would want to know which of our packets were rejected.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] crash: metric..." ]
>OK, I'll try it when it shows up in HEAD.   Would there be an option to see what that invalid packet was?  This is of great interest for me.  My project is a new network system with some new DNS queries which we pack into TXT for the moment (probably need new record type). I would want to know which of our packets were rejected.

Well, from the crash you posted it seems to be without question section, or 
missing even more bits, just the header or shorter still.

**Comment by elephantfries** [comment]
That's very puzzling.  There is definitely a question section in what we send. And it works fine normally. The crash is a very infrequent event.  The other thing that's puzzling is that our potentially malformed packets were not being sent during the time of the crashes (the last one and the previous ones).  There were no queries.  The system is sitting mostly idle except in occasional test session that we run. I suppose I could  insert a print statement myself now that I know where it crashes.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] crash: metric..." ]
>That's very puzzling.  There is definitely a question section in what we send. And it works fine normally. The crash is a very infrequent event.  The other thing that's puzzling is that our potentially malformed packets were not being sent during the time of the crashes (the last one and the previous ones).  There were no queries.  The system is sitting mostly idle except in occasional test session that we run. I suppose I could  insert a print statement myself now that I know where it crashes.

*weird*

but the stacktrace points to a non existing question section...

**Comment by elephantfries** [comment]
I rebuilt coredns off commit 37d06f and installed on my three instances.  I also added a print out to tell me #1123 was hit. When I see this message and no crash, then I'll close the ticket. It can take a month.
I also looked at some tcpdump traces.  Looks like 'idle' is not that idle.  It gets a query for 'localhost' three times every hour plus some random queries from weird distant places.  Port scanners maybe. I suspect some of these could be malformed.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] crash: metric..." ]
>I rebuilt coredns off commit 37d06f and installed on my three instances.  I also added a print out to tell me #1123 was hit. When I see this message and no crash, then I'll close the ticket. It can take a month.
>I also looked at some tcpdump traces.  Looks like 'idle' is not that idle.  It gets a query for 'localhost' three times every hour plus some random queries from weird distant places.  Port scanners maybe. I suspect some of these could be malformed.

Thanks. This points at an issue in miekg/dns, which could use a new round of 
fuzzing as well. In general we should expect CoreDNS to receive a packet that
at least has a question section.

**Comment by elephantfries** [comment]
It's been a month with no crashes. Closing.

**Comment by elephantfries** [comment]
Finally, I saw a positive confirmation that the crash case gets hit but this time it survives.
