### ISSUE TITLE
mw/kubernetes: returns answers with 0 TTL?

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#935]
While coding federation I noticed that the *kubernetes* mw returns records with 0 TTL:
```
svc0.testns.prod.svc.cluster.local.	0	IN	CNAME	svc0.testns.cluster.local..svc.fd-az.fd-r.cluster.local.
```
Need to delve a bit deeper, but this seems weird.

**Comment by chrisohaver** [comment]
Empirically, this behavior changed starting with release 009...

In 008, TTLs are 5.  In 009, TTLs are 0.

Perhaps the defaults changed - k8s mw does not specify TTLs when creating response records.

**Comment by miekg** [comment]
Odd. So the question becomes, what should be the TTL, and of course what
does kube-dns do?

**Comment by johnbelamaric** [comment]
I think `kube-dns` does 5 seconds, but we should double-check.

**Comment by chrisohaver** [comment]
I think it's 30 seconds in kube-dns.
There's a request to make it configurable for pod responses: kubernetes/kubernetes#29642

**Comment by chrisohaver** [comment]
The justification for the request in kubernetes/kubernetes#29642 is specific to the kube-dns's handling of pod records... i.e. `pods insecure` in coredns.
For `pods verified`, you'd want the same TTL as other entries.

**Comment by miekg** [comment]
For the time being a global TTL in kubernetes of X seconds?

**Comment by chrisohaver** [comment]
Yes. Should be 30 seconds.

**Comment by chrisohaver** [comment]
Should this be in the spec?

**Comment by miekg** [comment]
Yes, think so. Together with SOA defaults , for among other things,
negative TTL.

**Comment by yongtang** [comment]
The headless service's TTL should be much lower at least by default e.g., 5 sec at the maximum (and could go lower) in a container-based system. Otherwise headless service will be of little use.

**Comment by miekg** [comment]
Think we should go a with a global default of 5s

**Comment by chrisohaver** [comment]
OK - so changing it back to what it was in 008.

Any ideas on what changed between 008 and 009 to change the default to 0?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] mw/kubernetes..." ]
>OK - so changing it back to what it was in 008.

yeah, I think that makes sense?

>Any ideas on what changed between 008 and 009 to change the default to 0?

Nope, you'll need git bisect if you really want to know, does this predate 
vendoring?

/Miek

--
Miek Gieben
