### ISSUE TITLE
mw/kubernetes: non-CNAME request for external services are filtered.

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#950]
Maybe similar to https://github.com/coredns/coredns/issues/817

Currently the external service test does a:
~~~
	"CNAME External": {
		Qname: "external.testns.svc.cluster.local.", Qtype: dns.TypeCNAME,
		Rcode: dns.RcodeSuccess,
		Answer: []dns.RR{
			test.CNAME("external.testns.svc.cluster.local.	0	IN	CNAME	ext.interwebs.test."),
		},
	},
~~~
Which works, but is strange because I don't think libc will create CNAME queries. Moving the Qtype to
`dns.TypeA`. Gives a NODATA answer;
~~~
--- FAIL: TestServeDNS (0.00s)
	helpers.go:120: answer for "external.testns.svc.cluster.local." contained 0 results, 1 expected
	helpers.go:274: ;; opcode: QUERY, status: NOERROR, id: 52174
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
		
		;; QUESTION SECTION:
		;external.testns.svc.cluster.local.	IN	 A
		
		;; AUTHORITY SECTION:
		cluster.local.	300	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1503164291 7200 1800 86400 60
~~~
The reason this happens is because of CNAME filtering happening in kubernetes.Services(). Removing those lines make it work.

**Comment by miekg** [comment]
This is 1 of 2 places where service's `HostType()` is used. Maybe the other place does not need to do this as well? Meaning we can remove this code as well.

**Comment by miekg** [comment]
`HostType()` is used in other places as well.

**Comment by chrisohaver** [comment]
Is there an `A` record for `ext.interwebs.test.` in the upstream server?  If not, what would the correct answer be? 

The CNAME filtering I think you are referring to used to only apply to `SRV` queries. Not sure after the refactor.

**Comment by miekg** [comment]
q: `;external.testns.svc.cluster.local.	IN	 A` should return the cname, so removing the cname is not the right thing to do here.

**Comment by miekg** [comment]
I think we should remove any CNAME filtering and just return what we've found. I'll try to come up with a PR.

**Comment by miekg** [comment]
Pushing post 1.0.0 release.
