### ISSUE TITLE
middleware/kubernetes: different SRV requests behavior in kube-dns

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#975]
kube-dns handles SRV requests differently than coredns...

In one expected difference, coredns uses endpoint names in `SRV` answer targets for headless services. kube-dns uses a large numerical ID.  IMO, this is innocuous, and I prefer the coredns behavior (it's easier to read). e.g.
   * kube-dns: `_http._tcp.headless-svc.test-1.svc.cluster.local. 30 IN	SRV	10 100 80 123874634889776.headless-svc.test-1.svc.cluster.local.`
   * coredns: `_http._tcp.headless-svc.test-1.svc.cluster.local. 30 IN	SRV	10 100 80 172-168-0-12.headless-svc.test-1.svc.cluster.local.` 

But some unexpected differences...
1. kube-dns ALWAYS uses the large numerical IDs in the answer targets, even for non-headless services.  coredns does not, it only uses the endpoint names as `SRV` targets if the service is headless.  Minor difference, but I prefer the coredns behavior here - it's cleaner. e.g.
   * kube-dns: `_http._tcp.svc-1-a.test-1.svc.cluster.local. 30 IN	SRV	10 100 80 6434636435323735.svc-1-a.test-1.svc.cluster.local.`
   * coredns: `_http._tcp.svc-1-a.test-1.svc.cluster.local. 30 IN	SRV	10 100 80 svc-1-a.test-1.svc.cluster.local.` 
2. kube-dns returns an `NXDOMAIN` for queries that specify the `_protocol` but not the `_service` part of the SRV prefix.  coredns returns all `SRV` records with the given `_protocol`.  IMO the coredns behavior makes more sense from a dns correctness perspective. e.g. 
   * kube-dns: `_tcp.svc1.example.cluster.local.` => `NXDOMAIN`
   * coredns: `_tcp.svc1.example.cluster.local.` => all tcp `SRV` records for service `svc1` 
3. kube-dns returns a bogus `SRV` record with port = 0 when no `SRV` prefix is present in the query.  coredns returns all `SRV` record for the service. IMO the coredns behavior makes more sense. e.g.
   * kube-dns: `svc1.example.cluster.local.` => a single bogus record on port 0
   * coredns: `svc1.example.cluster.local.` => all `SRV` records under service `svc1`

**Comment by chrisohaver** [comment]
... actually, for number 2 above, coredns currently response with `NXDOMAIN`... but there is an open issue to change that behavior #808 per review feedback of PR #884...

**Comment by chrisohaver** [comment]
The `NXDOMAIN` response for number 2 above makes sense if the `_tcp` segment is assumed to be an endpoint.  This must be what kube-dns assumes.

**Comment by chrisohaver** [comment]
The implied question here is - should we alter coredns behavior to match kube-dns, or document differences.

**Comment by chrisohaver** [comment]
For number 2, we will be changing expected coredns behavior back to `NXDOMAIN`to match kube-dns behavior.

**Comment by miekg** [comment]
So making this query against the correct master, with this diff yields:
```
diff --git a/middleware/kubernetes/handler_test.go b/middleware/kubernetes/handler_test.go
index 292ffdf3..2afc42fd 100644
--- a/middleware/kubernetes/handler_test.go
+++ b/middleware/kubernetes/handler_test.go
@@ -62,6 +62,16 @@ var dnsTestCases = map[string](test.Case){
                        test.A("svc1.testns.svc.cluster.local.  0       IN      A       10.0.0.1"),
                },
        },
+       "SRV Service _no _http": {
+               Qname: "_tcp.svc1.testns.svc.cluster.local.", Qtype: dns.TypeSRV,
+               Rcode: dns.RcodeSuccess,
+               Answer: []dns.RR{
+                       test.SRV("_http._tcp.svc1.testns.svc.cluster.local.     0       IN      SRV     0 100 80 svc1.testns.svc.cluster.local."),
+               },
+               Extra: []dns.RR{
+                       test.A("svc1.testns.svc.cluster.local.  0       IN      A       10.0.0.1"),
+               },
+       },
        "A Service (Headless)": {
                Qname: "hdls1.testns.svc.cluster.local.", Qtype: dns.TypeA,
                Rcode: dns.RcodeSuccess,
[1+] % go t                                                                                                           ~/g/src/github.com/coredns/coredns/middleware/kubernetes _tcp.nxdomain +
--- FAIL: TestServeDNS (0.00s)
	helpers.go:115: rcode is "NXDOMAIN", expected "NOERROR"
	helpers.go:274: ;; opcode: QUERY, status: NXDOMAIN, id: 59546
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
		
		;; QUESTION SECTION:
		;_tcp.svc1.testns.svc.cluster.local.	IN	 SRV
		
		;; AUTHORITY SECTION:
		cluster.local.	300	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1503561212 7200 1800 86400 60
		
FAIL
exit status 1
FAIL	github.com/coredns/coredns/middleware/kubernetes	0.419s
```
Which is correct? (i.e. test fails, because I just copy and pasted, but we return NXDOMAIN)

**Comment by chrisohaver** [comment]
The correct answer is `NXDOMAIN` because there does not exist an endpoint with the fqdn of `_tcp.svc1.testns.svc.cluster.local.`

The code makes the assumption that a single segment to the left of the service name ("_tcp") is an endpoint name, not a protocol.  This is an arbitrary decision for an ambiguous query, but consistent with kube-dns.

**Comment by chrisohaver** [comment]
The 3rd item is more unusual.

At the moment I cant think of a logical reason for kube-dns's behavior. Coredns's behavior seems more correct from a dns point of view.  Unless there is something "special" about the way that `SRV` prefixes work. Are they not supposed to be handled in the same hierarchical way as other domain segments.

**Comment by miekg** [comment]
yes, `SRV` *prefixes* are not special in any way. Just DNS labels.
