### ISSUE TITLE
middleware/health: healthcheck fails after graceful reload CoreDNS with SIGUSR1 signal

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [coredns/coredns#979]

**Comment by miekg** [comment]
We don't test for any reload thing - probably should.
Think it is fairly easy a get a CoreDNS instance with `test.CoreDNSServer` perform check and then call `Restart` on the `caddy.Instance` and check again.

**Comment by miekg** [comment]
Can't replicate with this test:
https://github.com/coredns/coredns/pull/980

**Comment by UladzimirTrehubenka** [comment]
I am not sure that this UT do the same stuff: start Coredns, kill -10 <coredns_pid> (healthcheck fails after that)

**Comment by miekg** [comment]
The metrics problems works in the same way, might have the same issue.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] middleware/he..." ]
>I ma not sure that this UT do the same as: start Coredns, kill -10 <coredns_pid> (healthcheck fails after that)

No, it is slightly different. Not sure why though.

/Miek

--
Miek Gieben
