### ISSUE TITLE
mw/kubetetes: TestKubernetesIntegrationFallthrough

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#983]
Which test cases in that test actually test the fallthrough? Looking at the tests a lot of them just ask the normal kubernetes queries? Except `Qname: "f.b.svc.cluster.local.", Qtype: dns.TypeA,` and maybe others?

We should trim this a bit probably...

**Comment by chrisohaver** [comment]
I believe @johnbelamaric wrote these. 
He's out on vacation until next week, so I'll review them and let you know.

**Comment by miekg** [comment]
thanks!

**Comment by chrisohaver** [comment]
Looks like the tests could be trimmed without reducing coverage.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] mw/kubetetes:..." ]
>Looks like the tests could be trimmed without reducing coverage.

Ack. probably just one.

We should also split this 1000 line long test file in to multiple ones.
