### ISSUE TITLE
mw/kubernetes: response that have other data and a cname

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#984]
In the kubernetes integration tests we check for these responses:
~~~
*.test-1.svc.cluster.local.	0	IN	A	10.0.0.100
		*.test-1.svc.cluster.local.	0	IN	A	10.0.0.110
		*.test-1.svc.cluster.local.	0	IN	A	10.0.0.115
		*.test-1.svc.cluster.local.	0	IN	A	172.17.0.2
		*.test-1.svc.cluster.local.	0	IN	A	172.17.0.4
		*.test-1.svc.cluster.local.	0	IN	CNAME	example.net.
		example.net.	3600	IN	A	13.14.15.16
		
	helpers.go:160: rr 3 should have a header rr type of 5, but has 1
	helpers.go:296: ;; opcode: QUERY, status: NOERROR, id: 13895
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0
		
		;; QUESTION SECTION:
		;any.test-1.svc.cluster.local.	IN	 A
		
		;; ANSWER SECTION:
		any.test-1.svc.cluster.local.	0	IN	A	10.0.0.100
		any.test-1.svc.cluster.local.	0	IN	A	10.0.0.110
		any.test-1.svc.cluster.local.	0	IN	A	10.0.0.115
		any.test-1.svc.cluster.local.	0	IN	A	172.17.0.2
		any.test-1.svc.cluster.local.	0	IN	A	172.17.0.4
		any.test-1.svc.cluster.local.	0	IN	CNAME	example.net.
		example.net.	3600	IN	A	13.14.15.16
~~~
These are illegal because you can't have other records with the same name as the CNAME record in responses:

What should we do about these? (obv if there is a CNAME it can be the only response, but I'm wondering about the A records here)

**Comment by chrisohaver** [comment]
This relates to #872.
Technically the underlying records are not the same name.  `any` is a wildcard.
Due to the way coredns answers wildcard queries, the answers don't list the actual record names. coredns simply regurgitates the exact query string back in the answers.

Maybe we should get rid of wildcard queries.  This would simplify tests and code. Do people use them?  What is the use case given the current implementation?

**Comment by miekg** [comment]
wildcards are part of dns. Looking again: this is wrong too (but maybe not very wrong):
~~~
*.test-1.svc.cluster.local.	0	IN	A	10.0.0.100
		*.test-1.svc.cluster.local.	0	IN	A	10.0.0.110
		*.test-1.svc.cluster.local.	0	IN	A	10.0.0.115
		*.test-1.svc.cluster.local.	0	IN	A	172.17.0.2
		*.test-1.svc.cluster.local.	0	IN	A	172.17.0.4
		*.test-1.svc.cluster.local.	0	IN	CNAME	example.net.
		example.net.	3600	IN	A	13.14.15.16
~~~
<strike>The `*` should be expanded to what we've found there.</strike> Wildcards in the middle `a.*.b` are an invention of SkyDNS, not sure how useful there are.
update: this answer is correct for the question being asked.

**Comment by miekg** [comment]
<strike>Maybe we should put the word `any` in such responses?</strike>
Wrong: reply is correct.

**Comment by miekg** [comment]
Interestingly I can't even replicate it in the kubernetes test dir:
~~~
	{
		Qname: "*.testns.svc.cluster.local.", Qtype: dns.TypeA,
		Rcode: dns.RcodeSuccess,
		Answer: []dns.RR{
			test.A("*.testns.svc.cluster.local.     303       IN      A       10.0.0.1"),
			test.A("*.testns.svc.cluster.local.     303       IN      A       172.0.0.2"),
			test.A("*.testns.svc.cluster.local.     303       IN      A       172.0.0.3"),
		},
	},
~~~
is valid, doesn't show the CNAME, while 
~~~
	{
		Qname: "external.testns.svc.cluster.local.", Qtype: dns.TypeCNAME,
		Rcode: dns.RcodeSuccess,
		Answer: []dns.RR{
			test.CNAME("external.testns.svc.cluster.local.	303	IN	CNAME	ext.interwebs.test."),
		},
	},
~~~
also passes.

**Comment by chrisohaver** [comment]
> The * should be expanded to what we've found there.

This is #872. Due to the way coredns answers wildcard queries, the answers don't list the actual record names. coredns simply regurgitates the exact query string back in the answers.

**Comment by chrisohaver** [comment]
> wildcards are part of dns

Wildcard _records_ certainly are.  A wild card _record_ creates synthetic entries for any incoming query that matches a wildcard record.  But there is no analog in kubernetes for wildcard records.  I.E. I can't think of any configuration of kubernetes objects that would prompt us to define a wild card record.

Wild card _queries_ is a different animal. It's unclear to me how this implementation of _queries_ that contain wildcards relates to wildcard records.  I always assumed this is an "outside of normal dns" thing.

Im fairly new to this, so please help me understand.

**Comment by chrisohaver** [comment]
From what I read in the RFC 1034 and in various forums...

- wild card records exist to dynamically create entries for queries (not containing wild cards themselves) that match the wildcard record.
- a query containing a wild card would simply match the wild card record (if one exists).  In effect, a `*`  in a query string should act as a literal  `*`.  It should not act as a wild card returning all matching records.

**Comment by chrisohaver** [comment]
RFC 4592 seems to confirm that treating `*` in queries as wildcards is not part of "normal" dns wildcard records...

> 2.3.  When Is a Wildcard Domain Name Not Special?
>   When a wildcard domain name appears in a message's query section, no
>  special processing occurs.  An asterisk label in a query name only
>  matches a single, corresponding asterisk label in the existing zone...

I also don't see anything regarding the use of `any` as  wildcard in queries (or in records).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] mw/kubernetes..." ]
>RFC 4592 seems to confirm that treating `*` in queries as wildcards is not part of "normal" dns wildcard records...
>
>> 2.3.  When Is a Wildcard Domain Name Not Special?
>>   When a wildcard domain name appears in a message's query section, no
>>  special processing occurs.  An asterisk label in a query name only
>>  matches a single, corresponding asterisk label in the existing zone...
>
>I also don't see anything regarding the use of `any` as  wildcard in queries (or in records).

Yep, all true. These are non-standard things that SkyDNS did, which actually 
made a lot of sense and made it way more powerful.

Removing this is another discussion, right now we return answer that directly 
violate the DNS spec and that can lead to problems.

**Comment by chrisohaver** [comment]
Basically you are saying we should fix #872, or remove the wildcard _query_ feature.
Correct?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] mw/kubernetes..." ]
>Basically you are saying we should fix #872, or remove the wildcard _query_ feature.
>Correct?

No, sorry. We should:

* <strike>fix #872</strike> This was never a bug and the responses are correct.
* fix #984
* maybe think if we should drop the in-the-middle wildcard, in the etcd 
 middleware is quite straight forward.

/Miek

--
Miek Gieben

**Comment by chrisohaver** [comment]
#984 is this issue... Did you mean to link to another issue?

FYI, _records_ with wildcards in the middle _are_ supported by RFC 4592.  They were specifically not supported in the original RFC 1034.

But, none of that relates to the wildcard _queries_ feature implemented in k8s middleware.
I dont know if other coredns middleware actually implements wildcard records, or just non-standard wildcard queries.

**Comment by chrisohaver** [comment]
If we implement  #872, then the two concerns raised in this ticket are addressed.  
1. Each answer will list the actual record name instead of echoing the query (literally #872)
2. `CNAME` and `A` answers won't have the same names (because they will reflect the actual record names, per #872)

**Comment by miekg** [comment]
> FYI, records with wildcards in the middle are supported by RFC 4592. They were specifically not supported in the original RFC 1034.

you mean *wildcards* or wildcard *labels*, i.e. just `*` without special meaning?

Reflecting on this, fixing #872 would be the proper thing to do.

**Comment by fturib** [comment]
@miekg : as #872 is the proper thing to do, should we add the #872 for Milestone 1.0.0 ? And close this issue ?

**Comment by miekg** [comment]
I'll try to elaborate more tonight, but #872 is not a bug. This is bug
covers the case where we actually return an answer in violation of the DNS
spec

On Aug 29, 2017 14:16, "Francois Tur" <notifications@github.com> wrote:

@miekg <https://github.com/miekg> : as #872
<https://github.com/coredns/coredns/issues/872> is the proper thing to do,
should we add the #872 <https://github.com/coredns/coredns/issues/872> for
Milestone 1.0.0 ? And close this issue ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/coredns/coredns/issues/984#issuecomment-325645414>, or mute
the thread

**Comment by chrisohaver** [comment]
The undesirable behavior explained in #872 directly causes a bug (this bug).  Implementing #872 will fix this bug.

IMO if #872 cannot be implemented now, we should remove wildcard queries until #872 is implemented.  Wildcard _queries_ are not part of DNS spec. In its current implementation, it's not very useful (because the answers are effectively anonymous).

To be clear:  Wildcard _records_  and wildcard _queries_ are completely different, and unrelated things. Wildcard _records_ are part of DNS spec, but this is in no way implemented currently, and not related at all to this bug or to #872. Wildcard _queries_ are an invention of skydns/coredns, not a DNS standard, nor widely adopted as an unofficial standard as far as I can tell.

**Comment by miekg** [comment]
To be clear: Wildcard *records* and wildcard *queries* are completely
different, and unrelated things. Wildcard *records* are part of DNS spec,
but this is in no way implemented currently, and not related at all to this
bug or to #872 <https://github.com/coredns/coredns/issues/872>. Wildcard
*queries* are an invention of skydns/coredns, not a DNS standard, nor
widely adopted as an unofficial standard as far as I can tell.

+1

Does kube-dns actually do something like this? Note we do this in the etcd
middleware and it might be useful.

**Comment by chrisohaver** [comment]
> Does kube-dns actually do something like this?

I assume no, since its not standard DNS... but I'll check.

**Comment by chrisohaver** [comment]
Apparently no

```
root@k8s-perf-master:~# dig -t a @10.96.0.10 kube-dns.kube-system.svc.cluster.local.

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t a @10.96.0.10 kube-dns.kube-system.svc.cluster.local.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48737
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kube-dns.kube-system.svc.cluster.local.	IN A

;; ANSWER SECTION:
kube-dns.kube-system.svc.cluster.local.	1 IN A	10.96.0.10

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Tue Aug 29 14:48:28 UTC 2017
;; MSG SIZE  rcvd: 83

root@k8s-perf-master:~# dig -t a @10.96.0.10 *.kube-system.svc.cluster.local.

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t a @10.96.0.10 *.kube-system.svc.cluster.local.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56471
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;*.kube-system.svc.cluster.local. IN	A

;; AUTHORITY SECTION:
cluster.local.		60	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1504015200 28800 7200 604800 60

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Tue Aug 29 14:48:31 UTC 2017
;; MSG SIZE  rcvd: 142

```

**Comment by miekg** [comment]
Ack. Good to know.

Even worse kube-dns responds with NXDOMAIN which is plainly wrong. What comes back for `kube-system.svc.cluster.local.` (i.e. without the first label entirely)?

**Comment by chrisohaver** [comment]
> @miekg, I see you closed  #872 as "wont fix".
>
> If you say that a wild card query cannot answer with actual names, then we should definitely remove the feature... since by design, it violates the DNS spec any time the query matches an A record and a CNAME.

Wildcard QUERIES don't exist in the DNS. Interpreting `*` in queries *assuming* they are wildcards is indeed not something this is normally done in DNS servers, however it works fine in other middleware.
This will not break any clients.

Putting a CNAME and other data in a reply is very wrong and will break clients.

**Comment by miekg** [comment]
Playing with #1007 and the test failures it produces I think it should possible to make the etcd return the same kind of response. Which means if we introduce such a CNAME (when qtype != TypeSRV) we should drop all other records, which then points to a bug in backend_lookup.go handling. This wouldn't make it less *yuck*, but at least consistent between the "dynamic" backends.

**Comment by chrisohaver** [comment]
> Even worse kube-dns responds with NXDOMAIN which is plainly wrong.

I'm not sure about that. According to the standard wildcard _record_ spec, a query such as `*.kube-system.svc.cluster.local.` "... only matches a single, corresponding asterisk label in the existing zone." In other words, it's a literal query for a wildcard record. This implies that if there is no matching asterisk label in the zone (no wildcard record), it should answer `NXDOMAIN`.

It follows that the non-standard wildcard _queries_  feature inherently violates the DNS spec because it lends special meaning and different behavior to queries containing asterisk.

In context, from RFC 4592 ...

> 2.3.  When Is a Wildcard Domain Name Not Special?
>   When a wildcard domain name appears in a message's query section, no
>  special processing occurs.  An asterisk label in a query name only
>  matches a single, corresponding asterisk label in the existing zone...
