### ISSUE TITLE
mw/kubernetes: e2e test from kubernetes

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#993]
With some effort it should be possible to create an e2e test for CoreDNS, but using the kube-dns test data from:
https://github.com/kubernetes/dns/tree/master/test/e2e/kubedns

**Comment by yongtang** [comment]
There are efforts from CNCF Cross-Cloud for supporting e2e test of CoreDNS/Kubernetes:
https://github.com/cncf/cross-cloud/blob/master/README.md

The source code of CNCF Cross-Cloud is available:

https://github.com/cncf/cross-cloud

https://gitlab.cncf.ci/cncf/cross-cloud

**Comment by fturib** [comment]
Hi, 

The CI Dashboard looks good. 
But I understand that the view are 'samples' for now. This project seems in 'Design' state.
(see the version v9.12 for CoreDNS)

@dlx, @hh, @lixuna : is there a ETA for the first release ?
Will the Dashboard be available on-line, and history of the Dashboard ?

**Comment by denverwilliams** [comment]
Thank you for the introduction, Yong. 

The CI Cross Cloud Pipeline is working software, as seen in the demo and in GitLab ex. https://gitlab.cncf.ci/cncf/cross-cloud/pipelines/1946.  

The CI Status Dashboard is in the design phase, as Francois noted. The Dashboard's start date is pending approval (no ETA available). When the CI Status Dashboard goes live, it will be public facing and linked from the cncf.io site.

The Dashboard will include the history of past deployments via pagination, as visualized on the Deployment View https://user-images.githubusercontent.com/11701267/29289209-28153ee6-8101-11e7-91e4-7bd3a13a6087.png. 

Cheers,
Denver

**Comment by taylor** [comment]
Hi, @miekg and @yongtang. 

We are looking forward to collaborating on the e2e tests for CoreDNS.

@miekg, how are you seeing the use of the Kubernetes kubedns tests?

@yongtang, it was mentioned that there are some tests being used in your TravisCI runs.  Would you like to look at those as well?  If so please provide the links to those tests.

Cheers,

Taylor

**Comment by yongtang** [comment]
Thanks @taylor. The tests being used in TravisCI is to test against a locally setup k8s:
https://github.com/coredns/coredns/blob/afad8abef3d0eb046d448f6e597cc18004628f4a/.travis.yml#L37-L49

As you could see, it setup a etcd container and then setup a hyperkube container. Wait until k8s is ready.

After that, it use:
```
$KUBECTL create -f /travis/kubernetes/dns-test.yaml 
```
to get dns-test deployed.

/cc @chrisohaver as he may know more about the configuration.

**Comment by chrisohaver** [comment]
Ideally we would test on a real multi-node deployment of kubernetes, not hyperkube as the current travis CI uses.
But more critically, the current travis set up doesn't actually run coredns in the cluster (replacing kube-dns). Also, the client dns queries are not executed from a pod in the cluster.

So, for realistic end to end testing, I think we'd want to at least:
- deploy coredns in cluster replacing kube-dns
- execute test queries from a pod in the cluster

Also probably better test on "real" multi node kubernetes, instead of a single node hyperkube.  I have run into some unusual issues with certain releases of hyperkube that I have not run into with "real" kubernetes.

**Comment by chrisohaver** [comment]
> If so please provide the links to those tests.

in addition to the travis.yml and dns-test.yaml setup configs, the actual tests reside at...
https://github.com/coredns/coredns/blob/master/test/kubernetes_test.go

**Comment by miekg** [comment]
hi @taylor!

> @miekg, how are you seeing the use of the Kubernetes kubedns tests?

I haven't looked at the code, but I *assume* at some point they fire DNS queries to the thing being tested. I also assume that "thing" can be swapped out and CoreDNS can be swapped in.

Just having a test made for kube-dns being fired at CoreDNS and inspecting the differences would be valuable.

**Comment by chrisohaver** [comment]
I think the main test case should match the main use case, which would be to make sure we can deploy coredns into a k8s cluster, and that pods in the cluster can properly resolve names.

**Comment by miekg** [comment]
Is something happening here? Who's doing what? Should we (coredns-team) do something?
