### ISSUE TITLE
mw/kubernetes: dynamic SOA record

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#994]
For #963 we need to have a dynamic SOA serial. Also having a custom minTTL would be handy - we should probably change the change the backend.SOA function to be more dynamic and either get the entire SOA record from the backend, or just a serial and minttl

**Comment by stp-ip** [comment]
So only for dynamic backends and not for more static ones such as file/auto right? You suggested a while back to have the dynamic option as first class so one doesn't need to update SOA values manually.

**Comment by miekg** [comment]
Yes. Dynamic SOA for static file clashes with presigned DNSSEC zones. 

Once the kubernetes dust has settled I want to start work on automatically managing (DNSSEC) zone, which includes dynamic SOA, signing and uploading DSs to the parent.

**Comment by miekg** [comment]
This has been implemented
